### ISSUE TITLE
Batch Editor Broken?

### ISSUE THREAD

**Issue by mjd85** [kwsch/PKHeX#1003]
Not sure what happened, but it doesn't seem to be working for me any longer. Seems like no matter the combination I put, it says Modified 0/0 files.

**Comment by kwsch** [comment]
Please post pics illustrating, and indicate if you are using the latest commits or the latest release.
Double check that your command syntax is correct as well.

**Comment by mjd85** [comment]
I've used the last commit by you, actually. #2559. Also tried a few of the other recent ones, same issue. #2524 still broken.
First attached is what it looks like broken:

![2559](https://cloud.githubusercontent.com/assets/2186585/24382648/90be7c36-1325-11e7-9a6b-987dcd7ec73e.PNG)


I rolled back to an older version and it worked out fine. See attached of #2199.

![2199](https://cloud.githubusercontent.com/assets/2186585/24382703/194dcd7c-1326-11e7-97cd-09dd5920683b.PNG)

**Comment by kwsch** [comment]
Unable to replicate :(

![image](https://cloud.githubusercontent.com/assets/6393368/24385667/33f86156-1320-11e7-9a80-425f8c61e396.png)

All that was changed is that the program won't modify the party/box if there's no party/box to begin with; so I dunno how you managed to yield that result. Try restarting the program and trying again... would need steps to replicate to track down what was going on!

**Comment by mjd85** [comment]
Hmm, that's odd. I've restarted program, computer etc. several times. Tried a fresh install of Pkhex. Wish I knew what I was doing wrong, it's worked fine for months and still works on older versions haha.

My steps were:

Open PkHex
Open Save File
Open Batch Editor
Run Command.
That's it. Same save file and edits.

It must be something funky on my computer, although I'm not entirely sure what. I'll keep toying with it and hopefully get it figured out. Thank you!

**Comment by Nawor3565** [comment]
I can't get screenshots at the moment, but I had the same problem a few days ago, running almost the exact same command. So it's not an isolated issue. Weird.

**Comment by mjd85** [comment]
Can confirm this fixed the issue. Thank you.

**Comment by Nawor3565** [comment]
Looks like it's happening again in both the 17/4/24 release and the newest commit, even though it was working fine before.

![2017-05-01 1](https://cloud.githubusercontent.com/assets/19783632/25589703/9cd17bf6-2e7b-11e7-9e19-7b06d51562e6.png)
