### ISSUE TITLE
[Feature] Evolve button

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1010]
Request for an evolve button.

This is important mainly due to how their attributes change once they evolve.  Specifically I am thinking about trash bytes.  When an evolved pokemon's name is shorter, it should **ALWAYS** retain remaining characters from its pre-evolved form.

**Comment by pokecal** [comment]
I'm interested in the retaining. It happens in probably all renaming.(hatch,evo,and nickname)
But OriginalTrainer can remove some retained bytes like this:
"Grimer"--evo-->"Muk"--nickname-->"abcde"--nickname-->"abcd"--nickname-->"Muk"

**Comment by kwsch** [comment]
I'd rather tie this in to the Special Characters form, similar to pokesav (?):
* Direct byte editing access
* Byte array string visualization

string entry
flowlayout containing [chars/bytes]*numeric up downs
flowlayout containing special character clickable labels (as is currently in the form)

combobox & button for applying a trash byte layer (species/transfer trash)
button to reset all trash
button to apply changes

would change from a popup to a dialog


It would include a flowlayoutpanel containing special characters (as clickable labels)

**Comment by kwsch** [comment]
As described above, the string editor has been refactored.
https://github.com/kwsch/PKHeX/commit/691493cafe98dffdbf5026f5fff983f64879d17b
