### ISSUE TITLE
Same OT on pokemons transfered from previous Generation

### ISSUE THREAD

**Issue by EvioKidd** [kwsch/PKHeX#1017]
So this issue popped up for me , i would like to apologize in advance if i am wrong or this has been posted again. I was doing some business on pkhex until i run into my box of transfered pokemon from pokemon X , pkhex has flagged the whole box and its reason is that the current handler cannot be past gen OT. I have the same character name in pokemon moon and X i dont see why that is an illegal thing though. The pokemon were transfered with PKSM's bank feature. Also these pokemon were transferred as they were, they were not touched in any way.
![screenshot_2](https://cloud.githubusercontent.com/assets/26828525/24573787/150f17a2-1691-11e7-94c9-1a7d071630e6.png)

**Comment by kwsch** [comment]
Go to the OT tab, look at the green highlight which indicates the current handler.
The current handler can never be the OT if you're on a different version.
