### ISSUE TITLE
bug with Latest commit d800ffd

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1019]
I think there is a bug in the code. It seems every Gen 7 hatched Pokemon I have now displays this.
![image](https://cloud.githubusercontent.com/assets/18354599/24581557/593caa68-16f8-11e7-95f4-3794e4b3042f.png)

**Comment by kwsch** [comment]
Thanks, https://github.com/kwsch/PKHeX/commit/d54bb72d59e23a4a462d3286c9ab348efaa6286a
