### ISSUE TITLE
Pokemon Firered/Leafgreen Error: Can't open misc edits

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1022]
Whenever I try to edit my save file and open the misc edits folder, it just throws this error and rather then letting me correct the invalid value, it just closes and I can't fix it.

![error picture](https://cloud.githubusercontent.com/assets/20786416/24590671/9c87b4fa-17ae-11e7-870e-f9e0da201417.png)

**Comment by kwsch** [comment]
It's either your BP or coin count being too large for the control. The controls are capped at 9999; 11210 too large! 

Can you provide more info on those two values ingame?

**Comment by PKMWM1** [comment]
I do not know what value is over 9999. But even though it may be capped in game, I just want a way to set the value back down and I can't even get in to do that
