### ISSUE TITLE
[Request] Auto open save in a JK Save Manager path

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#104]
The path for saves in the JK Save Manager are as follows and I was hoping they could be added to the options of auto-opening. In the case that there are various matching paths only the first one would be used This would count for both in the case there are saves for i.e. Alpha Sapphire _and_ Omega Ruby (AS would load as A is before O) and within the game's folder in case there are folders i.e. "export" and "export1" in which case "export" would be loaded.

Paths are:
`/JKSV/Saves/Pokémon_X/*/main`
`/JKSV/Saves/Pokémon_Y/*/main`
`/JKSV/Saves/Pokémon_Alpha_Sapphire/*/main`
`/JKSV/Saves/Pokémon_Omega_Ruby/*/main`

If you would have a better idea for implementing the issue of multiple saves in the paths please do, but I don't think there isn't much else to do but just load the first.

**Comment by kwsch** [comment]
Already exists, the program looks in /JKSV/Saves for all files called "main", then filters for valid sizes, then grabs the one with the latest modified date.

https://github.com/kwsch/PKHeX/blob/master/PKX/f1-Main.cs#L114-L118
