### ISSUE TITLE
Pkhex Crashes on latest commit

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1042]
With the latest commit, the program on windows simply crashes the second it opens and I can't use the program at all.

**Comment by kwsch** [comment]
Unable to replicate the issue; would need more details.
Try without SD card plugged in, idk.

**Comment by Tsunamical** [comment]
It's great that you're saying where the HEAD is, but we don't know what version of Windows you're running. Unable to replicate on Windows 10 with latest updates.

**Comment by kwsch** [comment]
Could be possible that a gen4 save was being auto-loaded and instant crashed with the latest commits; try again with the most recent ones.

**Comment by kamronbatman** [comment]
@PKMWM1 This was fixed.
