### ISSUE TITLE
Incorrect super rod encounters in Yellow

### ISSUE THREAD

**Issue by wwwwwwzx** [kwsch/PKHeX#1045]
It's possible to get a Lv 10 Dratini in the Safari Zone of Yellow.
The encounter raw file (encounter_yellow_f.pkl) looks strange. (no byte = 0x0A/0x0F for level = 10/15 )
Maybe it's better to summarize all fishing encounters of RBY than read from file.
This will not take much effort.

**Comment by kwsch** [comment]
the raw file is straight from the ROM
