### ISSUE TITLE
[Error] Save Editing Fire Red Game Freeze

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1047]
So, I extracted my friend's Fire Red save using Save Manager.nds, and then I made some changes with PKHeX. I originally gave the Pokemon in slot 1 of the party mail, and then when I check the summary the game froze. Using PKHeX I then remove the mail and replace it with another item. The game still freezes whenever I view the summary. The egg I created in the party also won't change it's name to English, PKHeX always reads it as Japanese, even though it's English on the actual cart. Below is a copy of the Fire Red save.
http://www.mediafire.com/file/kvgi2ttf3qqlyl7/POKEMON_FIRE.0.sav

Thanks for all your work with PKHeX, and for reading.

**Comment by greenDarkness** [comment]
I also restored the initial unedited save and it seems to work fine, so I don't think there were any error when extracting the save. I can provide the unedited save if need.

**Comment by javierhimura** [comment]
Just to clarify. Eggs in generation 3 always have the nickname tamego in japanesse, no matter in what language you are playing. 

The game will show the proper egg name for the language if that is the nickniname, this is why PkHex always replace the nickname for japanese tamego.

**Comment by greenDarkness** [comment]
@javierhimura Ah, I see. Thank you for the information. That's really interesting; I wonder why they decided to do things that way?

**Comment by kwsch** [comment]
Without looking, I don't know how PokeGen handled mail held-item pkm for Gen3/4; it's possible that the party data is referenced for the mail info and the game panics when there's a mismatch.

Might be useful to lock the slot from editing if it's holding a mail item for gen3/4 save files, and force the user to remove the item in-game before the slot is unlocked.

**Comment by greenDarkness** [comment]
That could work. 
It should also be noted that after making this change the game still freezes even if you change the mail to another item.

**Comment by kwsch** [comment]
Possible relation to https://github.com/kwsch/PKHeX/issues/1062

**Comment by greenDarkness** [comment]
I didn't mark any of the Pokemon. 
If there is anything I can do to test, just say the word.

**Comment by AngelSora** [comment]
When we hit "Set" on a Pokemon on PKHeX (Most recent build), The markings automatically turn on. Of course you can change that ingame but you HAVE to do it if you don't want the Summary Screen to Freeze the Game.

**Comment by kwsch** [comment]
thanks for the provided sav with "PRANKED" -> the written string bytes were too long (PRANKED\FF) with the FF overflowing into the marking value (8 bits set = badddd)

**Comment by greenDarkness** [comment]
No problem. So, basically the name was too long in conjunction with the bytes?

**Comment by pokecal** [comment]
pk3 0x85(known as pokerus) is mailID, 0x00 to 0x05.
This means, if this value set to 0 (for pokerus), and this mon held mail, I think that mailID0 is called.
mailserver(sav.block[3]+0xCE0 to 0xF1F, 1mail=0x24)
