### ISSUE TITLE
Gen 3 Enigma Berry isn't unreleased

### ISSUE THREAD

**Issue by Bl4ckSh4rk** [kwsch/PKHeX#1048]
Well as the title says the Enigma Berry isn't really unreleased in Gen 3.
It's true that you can't have the Enigma Berry as such, but the e-Card Berries have the same index number. They are just overwriting all the data of the Enigma Berry with their own data.
Since those berries can't be traded it's only legal in English and Japanese RS.

**Comment by javierhimura** [comment]
Well, technically the enigma berry itself is unreleased. The e-berry used the same index but have different data, but having the enigma berry without e-berry data in the save is illegal.

A perfect solution would be to check if the savegame contains e-berry and if there is no e-berry data mark the item as unreleased. Also in emerald, firered and leaf green enigma berry is always unreleased.
