### ISSUE TITLE
Legality Move Checker broken?

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#1057]
http://puu.sh/vjZwI.png

They both can have those moves by a prior evolution.

**-edit-**
http://puu.sh/vk09B.png
Uhm, tested something with a Snorlax, the move Recycle should be ok since it can be learn by a prior evolution.

Maybe the legality move checker (idk its name XD) is broken or something?

**Comment by kwsch** [comment]
Post the pkms, unable to replicate on latest commit or latest release.

**Comment by jisn064** [comment]
Ok, the error was on #2816
#2817 seems to work fine

http://puu.sh/vk4o9.png


since I got that kind of error, from who should I download the builds? /Master only?

**Comment by evandixon** [comment]
Without looking closer, those builds each correspond to a pull request, regardless of whether it was approved or rejected.  I recommend only using master unless you want to test a specific pull request (preferably after understanding how it's different first).

**Comment by jisn064** [comment]
I see, I'll stick with the master then XD

sorry for wasting your time D;
