### ISSUE TITLE
Pokemon Marking (3rd Gen)

### ISSUE THREAD

**Issue by AngelSora** [kwsch/PKHeX#1062]
Every time i edit a Pokemon on Gen 3, The Circle, Triangle, Square and Heart markings never turn off. And ingame, the Markings looks corrupted.

**Comment by kwsch** [comment]
Which game?

**Comment by AngelSora** [comment]
Tested on FireRed and Ruby.

**Comment by AngelSora** [comment]
Edit: When i check Pokemon with these marks, the Game entirely Freeze !

**Comment by kwsch** [comment]
Unable to replicate.

**Comment by AngelSora** [comment]
?

**Comment by kwsch** [comment]
I repeated the steps as described (was able to toggle markings in PKHeX and view changes ingame) for FireRed.

**Comment by AngelSora** [comment]
What does that mean ?

**Comment by kwsch** [comment]
I'm not experiencing any of the issues that you've listed if I try to repeat what you did.

**Comment by PrometheusG** [comment]
I can confirm this error
I just created a Wish Chansey and imported it to both my Firered and Leafgreen roms that I have extracted from my cartridges and playing them in the NO$GBA emulator. The marking symbols are shown glitchy in-game and "complete" in PKHeX and the rom crashes when I try to view the summary of the "test" pokemon

I have created it by using PKHeX build 2873 and haven't tested it in my real cartridges,only in my rom backups:
[113 - CHANSEY - 5F887EFD4D89.zip](https://github.com/kwsch/PKHeX/files/942138/113.-.CHANSEY.-.5F887EFD4D89.zip)

This is the error when I try to view the summary of the pokemon
![2017-04-20](https://cloud.githubusercontent.com/assets/20145301/25225648/db4f437c-25ca-11e7-9b8c-24935b86ce8a.png)

![2017-04-20 1](https://cloud.githubusercontent.com/assets/20145301/25225693/08252ec0-25cb-11e7-9f76-4fdde80b601b.png)

Thank you

**Comment by jisn064** [comment]
here is a little vid I made, this time in Emerald
https://youtu.be/8Z76rCV2CQ8

note the ralts' marks just before crashing (from 02:53)

**Comment by kwsch** [comment]
string refactor caused overflow into markings (0xFF) which is 4 unused bits -> causes panic

provided pkm has a 7 char OT name which was the key to replicate the issue :)
