### ISSUE TITLE
Legality for Traded Pokemon (FireRed)

### ISSUE THREAD

**Issue by AngelSora** [kwsch/PKHeX#1063]
Pokemon's like Lickitung, Farfetch’d, Mr. Mime and Jynx are not legal even with the Encounter Check. These Pokemon's can only be obtained by trade NPCs so i don't really know what is wrong with that.

**Comment by wwwwwwzx** [comment]
Which build?

**Comment by AngelSora** [comment]
From d751cb9. (I think)


[Traded Pokemon.zip](https://github.com/kwsch/PKHeX/files/922969/Traded.Pokemon.zip)

**Comment by AngelSora** [comment]
Also, Mr.Mime and Jynx Have NO Encounter check AT ALL !

**Comment by wwwwwwzx** [comment]
The pkm you provided are in your ID, not in-game trade

**Comment by javierhimura** [comment]
None of this pokemon that you have uploaded are legal. They do not have valid in-game trade data (for example met location should 253 in-game trade)
If you are traying to create an egg pokemon from this species the met level should be 0, that is how generation 3 determine if a pokemon was originated from an egg

**Comment by AngelSora** [comment]
I was just Generating them from PKHeX but... Thanks a lot, that really helped me. Now i now what to do.
