### ISSUE TITLE
Batch editor / legality issue

### ISSUE THREAD

**Issue by An0n1m00s3** [kwsch/PKHeX#1066]
After batch editing the legality still says illegal even though all the checkmarks are uncheckt it still requires a remove all press before its legal
![pkhex1](https://cloud.githubusercontent.com/assets/27587228/25067279/9f4ac6e2-223e-11e7-9071-dd42b446da2c.PNG)
![pkhex2](https://cloud.githubusercontent.com/assets/27587228/25067280/a3591590-223e-11e7-9434-70c7cb16989c.PNG)
 using latest version as of writting this (commit abcd541)

**Comment by kwsch** [comment]
Double check the alert message: "... unlocked flag".
```
.SecretSuperTrainingComplete=False
.SecretSuperTrainingUnlocked=False
```
