### ISSUE TITLE
[Feature Request] Add Legality Check for Some Previous Generation Events

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1069]
Some of the 3rd gen egg events still aren't reading as legal for me.
http://www.mediafire.com/file/m9j0mofahmg2a92/pkdb.rar
Primarily the Egg Pokemon Present Eggs
http://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_event_Pok%C3%A9mon_distributions_in_Generation_III#Egg_Pok.C3.A9mon_Present_Eggs

Also, Xatu, or Serviper  are legality checked it currently reads that it's hidden ability is unavailable, even though it can be obtained through transfer.

Thanks so much for all your work with PKHeX, and for reading this!

**Comment by javierhimura** [comment]
The pokemon included in the rar are illegal.

First, Egg Pokemon Present Eggs are exclusive for Fire Red and Leaf Green games. This pokemon could not have Emerald as the origin game. Keep in mind generation 3 pokemon do not change origin game when the egg hatch, even if the egg is received in a fire red game and trade to an Emerald game and hatched in Emerald, the origin game will remain Fire Red. Other event eggs from generation 3 are exclusive for Ruby and Sapphire.

Second, Fatefull encounter should not be checked. I tested it myself with real event eggs from Pokemon Box. The eggs before hatched have met location 255 (Fatefull Encounter) and have the Fatefull Encounter mark. But when the egg hatch the location change to the place where hatch and the fatefull check is lost.

**Comment by javierhimura** [comment]
I checked again and i fount the Wish Egg from the american events of the New York Center have two special moves, not only wish. I will make a commit with this missing moves but still even after adding this moves those pokemon have illegal moves. Even one of them is a level 5 Poliwhirl and that is not possible.

If you fix all this legal errors and still the program mark them as illegal i can check again with the fixed pkm files.

**Comment by greenDarkness** [comment]
Thank you to take the time to explain those mechanics, as I didn't realize that the origin version for the game wasn't changed once the egg hatched.
I went back and got all the Egg Pokemon Present Eggs to work.

The PCNY Eggs still aren't working for me though.
http://bulbapedia.bulbagarden.net/wiki/List_of_PCNY_event_Pok%C3%A9mon_distributions_in_Generation_III#Wish_Eggs
Some of the moves are transfer moves that could have only been learned in a previous generation, they should all be legal though; unless I'm missing something again?
The Poliwhirl is lv 25, but I made to so that it was transferred at lv 5. Did I denote that incorrectly? 
I'm using build 2855, and here are the pk7s.
Thank you again for taking time to look these over!
http://www.mediafire.com/file/5l665tz5d9qpdkt/pkdb.rar

**Comment by javierhimura** [comment]
Yes, one of the special egg moves from the PCNY Eggs are not included, but still some of this pokemon have another illegal moves.

Ok, now i see Poliwhirl correctly with level 25 and met level 5, but Encore is illegal for that Pokemon. Poliwhirl only learn Encore as an egg move starting in generation 4, a generation 3 pokemon could not have any egg moves from other generations. And in this case that we are talking about an event egg if also cant learn any egg move from generation 3, because the egg was not given with egg moves, Sweet Kiss and Bubble are the only moves in this event egg. That makes Sweet Kiss, the special move, incompatible with any other egg move.

Farfetch'd. Whirlwind is illegal. Farfetch'd only learn this move in generation 1.

Exeggute with Magic Coat. Completely illegal. It never learn it in any generation nor event that i found.

Chansey : Moves are valid but still report illegal. I need to check more in depth this pokemon

**Comment by greenDarkness** [comment]
Alright, I fixed Poliwhirl.
Farfetched doesn't have Whirlwind now, but it still reads as illegal.
Exeggute get's Magic Coat as a HGSS move tutor move. http://serebii.net/pokedex-sm/102.shtml

Thanks so much for looking into this!

**Comment by kwsch** [comment]
Exeggcute doesn't learn Magic Coat via tutor.
http://bulbapedia.bulbagarden.net/wiki/Exeggcute_(Pok%C3%A9mon)/Generation_IV_learnset#By_tutoring

Wish Events with a second special move aren't handled correctly (sweet scent causes the EventEgg check to fail -> regular egg is then checked and left)

**Comment by greenDarkness** [comment]
Are you positive about that? According to serebii.net it's an HGSS tutor move. https://snag.gy/6qe3Rp.jpg

Thank you!

**Comment by kwsch** [comment]
Serebii can be wrong sometimes :)
https://pokemondb.net/pokedex/exeggcute/moves/4

**Comment by javierhimura** [comment]
For this we try when is possible to load move learn tables directly from the raw files of the games. Is more accurate than web sites

**Comment by greenDarkness** [comment]
Serebii can be wrong. But in my experience pokemondb lacks updated information/accurate past information. So, I'll grab my copy of Heart Gold and try to teach an Exeggcute Magic Coat via move tutor.
