### ISSUE TITLE
Triplicates in Mystery Gift Database

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1071]
When a wondercard is added (lets say a PCD), that duplicates something already in the database, the database has 3 entries.

For example, I added this to the mgdb folder: [Crown Korean Suicune PCD](https://github.com/projectpokemon/EventsGallery/raw/master/Gen%204/KOR/030%20Crown%20Suicune%20KOR%20%5BPPorg%5D.pcd).  When I went to use it, there was another copy of this PCD (3 total).

This does not happen when I add something new to the database.

**Comment by kwsch** [comment]
the builtin event database doesn't check for duplicates, nor does it check for already-present matches when  loading the mgdb files.

I assume the duplication of the mgdb data is due to loading the mgdb folder twice (once on launch and again when opening the subform).

**Comment by kamronbatman** [comment]
That is a very good assumption.  So we need a way to determine duplicates.

**Comment by kwsch** [comment]
Probably best to use a [HashSet](https://msdn.microsoft.com/en-us/library/bb359438.aspx) when loading the data -> convert to array at the end.

**Comment by kamronbatman** [comment]
You use distinct which accomplishes the same thing. The issue is default comparison uses object hashes which are unique per object instance. Need to make a comparer that works based on content/properties.

**Comment by kwsch** [comment]
Marking as resolved due to HashSet additions. There will still be 'duplicates' where gender is assigned on download (thus random->static), as both cards are stored.

**Comment by kamronbatman** [comment]
I think that will be fine.  @kwsch, would it make sense to mark it in PKHex so people know the difference? Also will trash bytes in PGT/PCD be an issue?  The trash bytes for PGT and PCD are different, even for the exact same event.

**Comment by kwsch** [comment]
If the card bytes are any different, then they will both be in the db. The hash is computed over the entire gift.

Not sure in the use of any "slightly different" marking; users can inspect the trash bytes in the main editor.

**Comment by kamronbatman** [comment]
I am specifically talking about trash bytes in the card template itself, not the pokemon that is generated.  For example, there is no need to have the raw PGT if the PCD is there.  Are they already excluded from the DB internally? And do I need to separate my PGTs from PCDs so I don't have duplicates in that fashion?

I am sorry if we are getting into the grit.

**Comment by kwsch** [comment]
Just change the hash iteration to not iterate over card details, instead only over the gift template info.
