### ISSUE TITLE
Generation 4: Pokédex is buggy

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1073]
A bug that I found was whenever I use PKHex, my Pokédex is changed randomly when I return to the game. Such as some Pokemon who were marked as seen or even owned are now marked as not even seen. I don't know what patterns this takes, but it messes up my Pokédex.

**Comment by pokecal** [comment]
I've edited Gen4Dex #968, according to JapaneseVer, also cause the bug.
Please test older PKHeX, eb8b9602b2d00b4cbab57528727bb1cce5ebddb3 was the latest.
If it works good, I will undo the edit and try to isolate JPVer.

**Comment by PKMWM1** [comment]
It still just randomly messes up my Pokedex

**Comment by kwsch** [comment]
If possible, could you provide:

* Original Save File
* Actions performed
* Observed changes ingame
