### ISSUE TITLE
Chōonpu in gen III species names / transfers to gen IV

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1075]
The Japanese gen III games use a hyphen-minus (-) instead of a chōonpu (ー). Because of this, PKHeX mistakenly interprets non-nicknamed Pokémon with hyphen in their species names as being nicknamed in gen III.

![capture](https://cloud.githubusercontent.com/assets/23516075/25108913/cdb076ce-239e-11e7-8f48-acd356351aa5.PNG)

Also, Pokémon with a nickname or OT name containing a hyphen retain the hyphen when transferred to a later generation with PKHeX instead of having it change to a chōonpu. I'm not actually sure if that's a bug in PKHeX or if that's how it works in the actual game. I would assume non-nicknamed Pokémon would have their names corrected on transfer since the nickname flag isn't set (e.g. ハスボ- → ハスボー) but the hyphen-minus is also a valid character in gen IV (and Game Freak is incompetent lol) so it wouldn't surprise me if hyphens in nicknames and OT names were retained.

**Comment by kwsch** [comment]
@wwwwwwzx 
probably best to just re-point the 3->4 translation of the char

`public static readonly ushort[] G34_4J = ...`

**Comment by kwsch** [comment]
#1077
