### ISSUE TITLE
PK4 Transfer sets incorrect Egg Location

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1078]
Should be `Day-Care Couple`, set to `Faraway place` instead. Changing Egg Location causes the Turtwig to be deemed legal.

Before transfer:
![image](https://cloud.githubusercontent.com/assets/17801814/25211627/093b3416-2554-11e7-863e-2f1636a9fdf5.png)

After transfer (screenshot shows Gen 7, happens with Gens 5/6 as well):
![image](https://cloud.githubusercontent.com/assets/17801814/25211617/fe71bf28-2553-11e7-8e11-d45c5dc2f388.png)

**Comment by sora10pls** [comment]
Also for whatever reason, legality check displays "Valid un-hatched egg." from a Pokemon that *was already* hatched from an Egg.

![image](https://cloud.githubusercontent.com/assets/17801814/25211929/c6594906-2555-11e7-8c08-8367ddc8bdf1.png)

**Comment by kwsch** [comment]
Either way, it's hacked; the encounter type shouldn't be starter/gift (should be none) as it has an egg met location.

Gen4 uses 4 bytes to store met location; if the PKM is from PtHGSS the game stores Faraway Place for the DP location and the PtHGSS location is set to the actual location ID.

```
                else if (PtHGSS)
                {
                    BitConverter.GetBytes((ushort)value).CopyTo(Data, 0x46);
                    BitConverter.GetBytes((ushort)0xBBA).CopyTo(Data, 0x80); // Faraway Place (for DP display)
                }
```

When transferring, the 0x80 is transferred and 0x46 is wiped, thus leaving Faraway Place

**Comment by sora10pls** [comment]
Yeah I just made this PKM up quick from an existing one I had in this save file to show a quick example. Regardless, it still does transfer with Faraway place

**Comment by kwsch** [comment]
That's how the conversion code works, reference:
https://github.com/kwsch/PKHeX/blob/36515b81780b2d75c9ae92946c433a7b091c82ee/PKHeX/PKM/PK4.cs#L425-L426
+ my above comment

**Comment by sora10pls** [comment]
Latest commit now sets Egg Location to transfer Faraway place when transferred as intended, and displays as legal 👍 

![image](https://cloud.githubusercontent.com/assets/17801814/25295286/f210b898-26b0-11e7-833a-0d6f098c7820.png)
![image](https://cloud.githubusercontent.com/assets/17801814/25295269/e2903db2-26b0-11e7-8f58-8f87620aebca.png)
