### ISSUE TITLE
Bug: Battle Team slots stay put when Boxes are moved in Box Layout form

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1079]
Currently, my 26th and 27th PC Boxes in Moon have 36 placeholder Lopunny that I simply overwrite with new Pokemon when I wish to make Battle Teams, saves me from having to manually set them to a certain team in-game. However, I ended up finding a bug because of this.

When entering the Box Layout form, I decided to Box 26 up 1 slot to where Box 25 is located. Box moved fine and as intended, but the Battle Team slots that previously resided in Box 26 stayed in Box 26, setting the Battle Team slots to empty PC Box slots, rather than moving up to Box 25 as they should have.

Not sure how easily this can be worked around, but hopefully it can get fixed soon! :)

Before moving Box 26:
![image](https://cloud.githubusercontent.com/assets/17801814/25212435/484f050c-2558-11e7-816e-27975eff73cf.png)

After moving Box 26:
![image](https://cloud.githubusercontent.com/assets/17801814/25212452/597a7712-2558-11e7-8ca0-ed44cd0dc84e.png)
![image](https://cloud.githubusercontent.com/assets/17801814/25212464/66b010b8-2558-11e7-8b9b-41cf5a15d659.png)

**Comment by kwsch** [comment]
Not really a bug, just a non-feature.

PKHeX doesn't expose editing of the team slots for _safety_ reasons, hence why they are not re-pointed to the moved box.

**Comment by sora10pls** [comment]
Would probably be worth it to only allow editing team slot locations when Boxes are moved around, otherwise this happens :P

**Comment by kwsch** [comment]
Or I just prevent moving of boxes if it has a Teamslot as well!

**Comment by sora10pls** [comment]
That also works, as the player can just as easily move the Box in-game to have the same effect as I had described
