### ISSUE TITLE
WISHMKR Jirachi and Manaphy Legality

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1081]
This Jirachi is not reading as legal.
http://www.mediafire.com/file/pek1h06tk9h8q40/385_-_Jirachi_-_19FE797FA83E.pk7
Manaphy isn't either.
http://www.mediafire.com/file/covktxbs1cal4kw/490_-_Manaphy_-_A29BD9ECEA26.pk7

Thanks for reading!

**Comment by kwsch** [comment]
Gen3 events are currently not supported (no MG3 format has been agreed upon)
Manaphy isn't legal; missing an egg location value.

**Comment by greenDarkness** [comment]
Ah, I see. 
Thank you again!
