### ISSUE TITLE
Misc. Edits Missing for Pokemon Platinum

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1085]
For the Misc. Edits, for the Battle Frontier are missing for Pokemon Platinum.

**Comment by kwsch** [comment]
Not sure if it is intended to open for Pt saves:
https://github.com/kwsch/PKHeX/pull/1084/files#diff-b88b8bed8cc5fad47a20a642474bd30bR1146
Only opens for DP & HGSS (no Pt)
if it were supposed to, the DP/HGSS check would be replaced with (SAV is SAV4).

**Comment by ricksee** [comment]
@kwsch Pt does have the same Battle Frontier that was added later on in HGSS. So a SAV4 would probably be best to add to the check.

**Comment by javierhimura** [comment]
Yes and No. Platinum have Battle Frontier like HGSS, and also have Poketch like DP, and have fly destination too. But the offset probably will be different. That means it is needed not only to change the check but also to include the correct offsets for platinum.

**Comment by ricksee** [comment]
Can I ask why this was closed?

**Comment by kwsch** [comment]
Offsets are different for Platinum, and haven't been researched/implemented.
