### ISSUE TITLE
Pokemon XD Heart Gauge Bug

### ISSUE THREAD

**Issue by tayrae** [kwsch/PKHeX#1086]
The heart gauge meter adjusts for some Pokemon, but not others.
![pooch](https://cloud.githubusercontent.com/assets/21210812/25308303/09f3e1f0-277f-11e7-8e6e-759bf172d351.png)
![pooch2](https://cloud.githubusercontent.com/assets/21210812/25308305/09f67456-277f-11e7-9cac-3501da1a0592.png)
![teddi](https://cloud.githubusercontent.com/assets/21210812/25308306/09f77130-277f-11e7-9b14-937b06e99ccf.png)
![teddi2](https://cloud.githubusercontent.com/assets/21210812/25308304/09f5621e-277f-11e7-9b08-fbe1be882d48.png)

**Comment by kwsch** [comment]
What happens when you set -> view the pkm?

**Comment by tayrae** [comment]
Whatever I set the heart gauge to it remains the same in view. It doesn't change or revert back to what it originally was.

**Comment by kwsch** [comment]
If you were to export the save file and re-load the save -> re-view the pkm, does it show up correctly?

In XD, the game stores the heart gauge/purification values within the save file by tying a dictionary to the Shadow ID. Trying to figure out where this would be messing up; it could be in the saving of the ShadowInfo data.

**Comment by tayrae** [comment]
It still does not show up correctly if you reload the save.

**Comment by kwsch** [comment]
But does it show the original value or the edited value?

**Comment by tayrae** [comment]
Edited

**Comment by tayrae** [comment]
Here is my save file for the game: https://drive.google.com/open?id=0B2GZNjAG_c0IWUE5MkdNZEI4Y3M

The boxed Pokemon have not been edited in any way. As you can see some purification values are at the full bar and some are at zero for some reason. Hopefully this will help.

**Comment by kwsch** [comment]
The [ShadowInfo data structure](https://github.com/kwsch/PKHeX/blob/2b1bc213aad92eb593111334155acc640d34805c/PKHeX/Saves/Substructures/ShadowInfo.cs#L48-L65) is not thoroughly documented; I assume this is why the game doesn't recognize the changes.

I've attached the shadow info table for analysis; once the community has documented the structure in more detail it can be fixed.

[shadowinfo.zip](https://github.com/kwsch/PKHeX/files/949911/shadowinfo.zip)
