### ISSUE TITLE
No Option For Current Level for Gen 3 Batch Editor

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1087]
As of today, there is no level option for the Batch Editor for Gen 3 save files
![2017-04-23_0-44-49](https://cloud.githubusercontent.com/assets/21182549/25310878/498e2e3a-27be-11e7-89e8-b5939a3d3c71.png)

**Comment by kwsch** [comment]
The type-specific choices are for properties that are manually implemented (either as overrides or as exclusive properties). CurrentLevel is implemented in the superclass PKM, which PK3 inherits from.

More often than not you should just use the "Any" choice.
