### ISSUE TITLE
 #2913 build legality issues (?

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#1091]
using the lastest master build #2913, my pkmn has the following errors:

Deoxys from Emerald: http://puu.sh/vtU7M.png
Old Sea Map Mew: http://puu.sh/vtUbl.png
All Ultra Beast: http://puu.sh/vtUmx.png
All Tapus: http://puu.sh/vtUpH.png
Necrozma: http://puu.sh/vtUs1.png
Magearna: http://puu.sh/vtUu8.png
Nebby: http://puu.sh/vtUwA.png

**Comment by kwsch** [comment]
Started with https://github.com/kwsch/PKHeX/pull/1088

EncounterStatic is not a Subclass of EncounterStatic
