### ISSUE TITLE
Count Does Not Apply to Items in Gen 4

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1097]
When trying to change the count in the items tab for Platinum, the changes wouldn't apply.

**Comment by kwsch** [comment]
Unable to reproduce the issue as described, please provide more information / reproduction steps. Remember that an item has to be selected (can't have 100 of "None").

**Comment by ricksee** [comment]
Tried to change count to one. Nothing changes.
![paint](https://cloud.githubusercontent.com/assets/21182549/25415726/72c939c0-2a07-11e7-8cd1-046eb869a898.png)

![paint w](https://cloud.githubusercontent.com/assets/21182549/25415751/a282d4b4-2a07-11e7-84a0-2149b759cc61.png)

**Comment by kwsch** [comment]
Wat? Give All is associated with the number up/down entry. You can click on individual item counts and edit yourself.

**Comment by ricksee** [comment]
Oh I thought the count worked to edit all items at the same time. Is it possible to add a feature like that. It is somewhat of a hassle to manual edit the amount of items since there are alot of them.
