### ISSUE TITLE
Platinum (ESP) Egg name error

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#1100]
**(09/05/2017)Edit:**
All the eggs obtained in ESP Pokémon Platinum gives me the following error:
http://i.imgur.com/6U7hZaT.png

In-Game: http://i.imgur.com/T2BKaax.png

PKHeX #3010
Pokémon Platinum (ESP) CPUS-F1E69344
No$GBA 2.8d

```
**FIXED**
**(01/05/2017)Edit:** PKHeX #2985
Also there is an error with Vivillon giving invalid evolution level error
https://i.imgur.com/1uiRzNJ.png

Spewpa can evolves into Vivillon at Lv12.
http://i.imgur.com/EHLdic6.png

**(08/05/2017)Edit:**
Porygon can't be in a beast ball
http://i.imgur.com/LJREc7s.png

"Soaring in the sky" legendaries shouldn't have their HA
```

**Comment by kwsch** [comment]
Vivillon fixed in https://github.com/kwsch/PKHeX/commit/f0dcf2b6b23e816a3998aea6a5db6b5862441c45
