### ISSUE TITLE
Pokemon party-battle box in battle revolution?

### ISSUE THREAD

**Issue by GoldenGrenadier** [kwsch/PKHeX#1104]
Is there any possibility of adding the ability to edit the actual party slots of the pokemon battle revolution saves? I ask because I'm trying to recover pokemon from the Battle revolution save file and the most important ones are in the party. Unfortunately the game that the pokemon were copied from no longer has these pokemon. (they were sent to My Pokemon Ranch and the Wii died) If not, is there any known way to move them from the party to a box within the battle revolution save? The only other option I can think of is extracting the pokemon from a wii remote after having been saved to it.*edit*just realized I may have asked in the wrong place.

**Comment by kwsch** [comment]
has to get researched by the community first before implementation

Since research requests are not directly related to PKHeX (they are community tasks), the forums are the place for such topics
