### ISSUE TITLE
Allow File Associations for Compatible Files

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1106]
Is it possible to make an option that any file that is compatible with this program selects would become associated with it by default. Like making a man or .sav file being opened by PKHeX  just by double-clicking on it.

**Comment by evandixon** [comment]
I kinda doubt Kaphotics is going to go for this one, but in case he does, this project looks like it'd make it easier:
https://www.codeproject.com/kb/dotnet/system_file_association.aspx

**Comment by sora10pls** [comment]
Workaround if not implemented (assuming Windows 10, steps are similar for other OSes):

Right-click file > Open with > Choose another app > Navigate to `PKHeX.exe` > Make sure "Always use this app to open `.x` files" is ticked
x = file format

Outcome:
![image](https://cloud.githubusercontent.com/assets/17801814/25602799/a96027a2-2ec4-11e7-85f5-e9f94d590b53.png)
![image](https://cloud.githubusercontent.com/assets/17801814/25602808/b39b9b48-2ec4-11e7-993d-0e8891e66481.png)

Double-clicking opens the files fine with PKHeX.

**Comment by Tsunamical** [comment]
sora's solution is what I've been doing a while, hence how I noticed #828

**Comment by kwsch** [comment]
I'd rather not include a way to automatically associate files; PKHeX isn't installed to program files and the path of the exe can change if the user moves it.

Pretty sure someone can just make a small tool to select the exe and create the associations the same way the linked project does.
