### ISSUE TITLE
current move issue

### ISSUE THREAD

**Issue by Tobyheiam** [kwsch/PKHeX#1112]
i compile the latest commit myself, and find that breedrill with harden show illegal.
<img width="456" alt="screen shot 2017-05-08 at 11 34 40 pm" src="https://cloud.githubusercontent.com/assets/22422919/25834584/efc88ce8-3446-11e7-86b3-73473e761192.png">

**Comment by sora10pls** [comment]
Can't replicate on latest commit (Gen7)
![image](https://cloud.githubusercontent.com/assets/17801814/25834873/c8e5b432-3448-11e7-8bc4-6cb2ae5e3f8d.png)

**Comment by Tobyheiam** [comment]
catch a level 5 kakuna with harden and it evovle at level 10, why is it illegal. the pokemon is fromRoC'-PC. I guess I mess up with compling the latest commit?

**Comment by sora10pls** [comment]
The problem is that PKHeX isn't looking for pre-evolution only moves. Beedrill does not get Harden, but Kakuna does. There could be other cases of this, but I can't test since I'm in class.

**Comment by Tobyheiam** [comment]
but why the official build (20170425) doesn't have this issue.

**Comment by sora10pls** [comment]
>but I can't test since I'm in class
