### ISSUE TITLE
Egg Meet Location in HGSS

### ISSUE THREAD

**Issue by iKamus** [kwsch/PKHeX#1116]
PKhex say cant hatch a egg in Route 35

![diglett](https://cloud.githubusercontent.com/assets/10860419/25981334/fa2bd31e-36aa-11e7-9cda-05a501207f1f.png)

**Comment by sora10pls** [comment]
Simple typo in [Tables4](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables4.cs#L1343); `283` should be `183`. [My new pull request](https://github.com/kwsch/PKHeX/pull/1117) resolves this :)
