### ISSUE TITLE
Build error with latest refactoring commits

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1125]
Building with source code prior to the latest refactoring commits allows me to build and run PKHeX totally fine. However, anything past that throws me an error when PKHeX is run and suggests I debug to fix the problem. I'm using:
- Visual Studio 2017
- Version 15.2 (26430.6) Release

What I get when debugging:
![image](https://cloud.githubusercontent.com/assets/17801814/26012315/28e3a688-3722-11e7-8496-6fc95584c249.png)

**Comment by evandixon** [comment]
Duplicate of #1123, fixed in #1124

**Comment by sora10pls** [comment]
Wow, that's embarrassing since I started that issue lmao. Thanks :p
