### ISSUE TITLE
Bug: MainWindow text (and potentially other Subforms?) not entirely translated

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1127]
Tested using latest commit. This does not happen with the latest stable build from PP.org, yet it seems to only happen with the latest commits.

Oddly enough, the button on `Main.Designer.cs` labeled "Mystery Gift" has reverted to "Wondercard", and the button labeled "Export" inside `SAV_Wondercard.Designer.cs` has also reverted to "Output". If I recall correctly, these were intentionally changed to "Mystery Gift" and "Export" for consistency, so it's strange to see it revert.

Build 20170424 (Japanese, properly translated):
![image](https://cloud.githubusercontent.com/assets/17801814/26021254/fcc8d6fa-3757-11e7-9f5b-106e1b05ca68.png)

Build 20170424 (English, properly displays "Mystery Gift" and "Export")
![image](https://cloud.githubusercontent.com/assets/17801814/26021302/c05e68b4-3758-11e7-8fd7-e23163a97dc3.png)
![image](https://cloud.githubusercontent.com/assets/17801814/26021335/39c2d24e-3759-11e7-8f92-c6275dc014f0.png)

Latest commit (Japanese, not entirely translated):
![image](https://cloud.githubusercontent.com/assets/17801814/26021256/0db5b7bc-3758-11e7-88de-a568f00c1f8d.png)

Latest commit (English, displays "Wondercard" and "Output"):
![image](https://cloud.githubusercontent.com/assets/17801814/26021315/ea6acf76-3758-11e7-8598-5e0e48eb72f6.png)
![image](https://cloud.githubusercontent.com/assets/17801814/26021338/46b2dd82-3759-11e7-9ba0-8b6e9dde313c.png)

**Comment by sora10pls** [comment]
I can also confirm that this bug was not present in commit 3e47e1e, so it was likely a side effect from the refactoring commits.

**Comment by kwsch** [comment]
Text resources are not currently fetching correctly
