### ISSUE TITLE
Possible Option: Allow Saving Files As Other Formats 

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1130]
Is it possible that a conversion between supported formats is possible. Like changing .sav to .dsv for instance when exporting or is it a step simple as changing the file extension name.

**Comment by sora10pls** [comment]
What would the benefit of this be? DeSmuME allows you to import raw save files (.sav) directly through the "File" dropdown. Upon doing so, it immediately adds a .dsv equivalent in the "Battery" (saves) directory.

**Comment by ricksee** [comment]
It may be easier to do it on one program than relying on desume. Plus, .dsv wouldnt work for me when doing this.

**Comment by sora10pls** [comment]
As I said, DeSmuME imports .sav and immediately converts to .dsv

If you want to import a .dsv, just replace the file in your "Battery" directory => <same name as ROM>.dsv

Decision is always up to @kwsch and I understand its convenience, but I personally just find no use for it.
