### ISSUE TITLE
Pokemon Platinum not match encounter 

### ISSUE THREAD

**Issue by iKamus** [kwsch/PKHeX#1132]
![carnivine](https://cloud.githubusercontent.com/assets/10860419/26076325/c5bef994-398e-11e7-9cf2-03335d99adc2.png)
![tropius](https://cloud.githubusercontent.com/assets/10860419/26076330/c9bcd066-398e-11e7-9391-f94225af7a90.png)

**Comment by javierhimura** [comment]
What encounter type do have those pokemon?

**Comment by kwsch** [comment]
(upload the PKM files)

**Comment by iKamus** [comment]
here is pkm files
http://www.mediafire.com/file/94o635jlarpyypp/pkm.zip

**Comment by javierhimura** [comment]
I can not replicate the error with the latest commit

**Comment by sora10pls** [comment]
Also cannot replicate the error with the PKMs provided. Update to [the latest commit](https://teamcity.projectpokemon.org/viewLog.html?buildTypeId=PKHeX_BuildWindows&buildId=lastSuccessful&buildBranch=%3Cdefault%3E).

Log in as guest => Artifacts => Download `.zip`
![image](https://cloud.githubusercontent.com/assets/17801814/26126785/f0e13e72-3a54-11e7-833e-0e711a211ead.png)
![image](https://cloud.githubusercontent.com/assets/17801814/26126799/f99020d8-3a54-11e7-9e62-f9284277b9ec.png)

**Comment by iKamus** [comment]
I download lastest commit and it is fixed over there sorry
