### ISSUE TITLE
Build Failed For Compiling Pkhex

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1134]
Everytime I try to compile the latest version for Pkhex it gives the error that the build failed.
![here](https://cloud.githubusercontent.com/assets/21182549/26086650/fbf11a4e-39b9-11e7-8217-9461e122d0e6.png)

**Comment by kwsch** [comment]
https://projectpokemon.org/forums/forums/topic/40632-problems-compiling/
