### ISSUE TITLE
Pokemon Platinum trading to Pearl issue

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1135]
Hi again,
I am using **PKHeX Build 3097**:

Last night I wanted to complete my living dex in Pokemon Pearl so I dragged and dropped some pokemon from my Platinum save file.
I "accidentally" moved over a pokemon I had already traded normally(using 2 ds and the cartridges) over to pearl years ago.So now I have 2 exact copies of the same pokemon(Yanmega,see below)

What I found is that with normal trade I did in the past, the exact same pokemon(Yanmega) shows the correct location(Great Marsh).The "Clone" that was created by dragging over the same pokemon from platinum to pearl with PKHeX it shows "Faraway Place".
[faraway place platinum pokemon.zip](https://github.com/kwsch/PKHeX/files/1004117/faraway.place.platinum.pokemon.zip)

- The pokemon I am reffering to is my **Yanmega** which was caught in Great Marsh in Platinum

- **Togekiss** was an egg gift from Cynthia in Platinum so I think it is supposed to say "Faraway Place"

- There is also  Mime Jr. that I dragged from Roc's PC that I found in [PP.org](https://projectpokemon.org/forums/forums/topic/37566-rocs-pc-collection-through-the-ages-u-20170315/) that is from trophy Garden in Platinum but shows "Faraway Place" in Pearl

For the images below, I am using deSmuME with my rom backups and the sav files from my cartridges

Yanmega drag and drop with PKHeX (the 1:1 "clone")
![2017-05-16](https://cloud.githubusercontent.com/assets/20145301/26103526/9d37d66c-3a42-11e7-8fea-9accad392112.png)

Exact same, the "original" Yanmega with normal trade in the past:
![2017-05-16 1](https://cloud.githubusercontent.com/assets/20145301/26103595/e845239e-3a42-11e7-93ed-86466faf730e.png)

Mime Jr. from Roc (all the files from RoC's PC are fine and legit and thank you Roc for everything. Maybe this has something to do with the PKHeX trade - drag and drop mechanic):
![2017-05-16 2](https://cloud.githubusercontent.com/assets/20145301/26103691/5804fab0-3a43-11e7-8606-5d71ebf3faa0.png)

Cynthia's Egg Togepi (I think this is fine to say faraway place):
![2017-05-16 3](https://cloud.githubusercontent.com/assets/20145301/26103785/bd6753bc-3a43-11e7-86b9-554a8b4b7d6e.png)

Thank  you

P.S. I don't even know the half of what you know about programming languages, how PKHeX works and about Pokemon in general so please forgive me if it is my error and I didn't use PKHeX correctly.

**Comment by kwsch** [comment]
As far as I know, drag&drop doesn't modify the met location of a PKM for a same-generation transfer.

The Gen4 games use "Faraway Place" as a catch-all for newer locations introduced in Platinum and HG/SS.

**Comment by PrometheusG** [comment]
I first viewed the pokemon and then I set it to an empy slot in my Box.

The Drag & Drop feature works perfectly in the rest of the pokemon games, this is why I am not sure If I made a mistake.

I would like to add that the location (Great Marsh) of Yanmega is shown correctly in PKHeX when opening the Pearl Save file and even with the Platinum Save file,which I did the  same thing and then viewed the pokemon in-game, but not in Pokemon Pearl

**Comment by kwsch** [comment]
The setting from tabs is what causes the Met_Location property to be updated via the [`if (PtHGSS)`](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/PKM/PK4.cs#L275-L279) check. Will have to revise behavior, probably need to check if the location ID is in DP.
