### ISSUE TITLE
Legit Pokémon from XY and prior marked as hacks

### ISSUE THREAD

**Issue by Gourmont** [kwsch/PKHeX#1145]
Hello,
I am using the latest release of PKHex on SM and I have noticed that all of my imported Pokémon from X/Y and prior (including from RBY) are flagged as hacks, due to memories issues. Oddly enough, none of my Pokémon imported from ORAS have this problem, as it only seems to happen to RBY, Gen3, Gen4, Gen5 and XY Pokémon (although they have been regularly imported through the Bank).

I am not very familiar with the notion of memories, that's why I hope you'll be able to make me understand what is going wrong.

Below are two screens of a HP Ice Zapdos I SR'd in X who is a false positive.

https://puu.sh/vTaKr/b6bac3b896.png
https://puu.sh/vTakQ/ef7a8321d9.png

Let me know if you need any additionnal screen capture or information.

Thanks in advance !

**Comment by kwsch** [comment]
PKHeX is expecting the link trade memory, and is listing the associated values for the other arguments.

Withdrawing from Bank causes it to apply the Link Trade memory.

**Comment by Gourmont** [comment]
I am not sure to understand, since I imported Zapdos, and thus withdrawed it from the Bank, it should have the LT memory, correct ? So why is PKHeX not finding it ?

**Comment by kwsch** [comment]
Because the memory in the screenshot is not the link trade memory.

**Comment by sora10pls** [comment]
>Because the memory in the screenshot is not the link trade memory.

To add to this, your screenshot displays the Handling Trainer (notOT). Gen 7 Pokemon are not given memories aside from Link Trade if it was brought into the game via Pokemon Bank.

OT => From Pokemon X, has memories
HT => When transferred to Moon, should have Link Trade memory

Example below shows my (properly) transferred Zapdos from Y to Moon with its HT memories.
Gen 7 Handling Trainer memories:
![image](https://cloud.githubusercontent.com/assets/17801814/26179244/8d8181a2-3b30-11e7-85c4-4277760b0d27.png)

**Comment by Gourmont** [comment]
Alright, I think I get it ! After having checked, only my ORAS mons have got the LT memory, that's why they are the only ones that are not flagged as illegal (they have the same LT memory as your Zapdos).
But I still don't understand why my XY (and prior) mons did not get the LT memory when I withdrew them from the bank... Should I put them back in bank and try to withdraw them again ?

**Comment by Gourmont** [comment]
Thank you, this must be because my Trainer Name is the same in XY and in SM !
