### ISSUE TITLE
Question (maybe a bug?): how does PKHeX load "savpaths.txt"?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1146]
I have a file name `savpaths.txt` in my work directory as such:
![image](https://cloud.githubusercontent.com/assets/17801814/26175309/3debec8c-3b20-11e7-8f1f-702f780605fe.png)

Inside `savpaths.txt` is the directory leading to DeSmuME's battery directory (where `.dsv` files are stored):
`C:\Users\Matt\Emulators\DeSmuME\Battery`

When I go to Tools > Open Folder, I see this:
![image](https://cloud.githubusercontent.com/assets/17801814/26175415/9a11cbb2-3b20-11e7-9200-3ba4a195d15d.png)

Not only is "PKHeX Backups" the only option, but when I click on the button, it defaults to the `bak` directory and not the directory I set in `savpaths.txt`.

Am I missing something? Am I doing it wrong? Is there a character limit for paths entered? Thanks in advance!

**Comment by kwsch** [comment]
name[tab]path
name[tab]path

lets choose what name shows up for the button

in your case it would be:
`DeSmuME	C:\Users\Matt\Emulators\DeSmuME\Battery`

**Comment by sora10pls** [comment]
Ah! I assumed tab spacing was to separate paths. Thanks!

**Comment by kwsch** [comment]
yeah just line return to add another entry
```
DeSmuME	C:\Users\Matt\Emulators\DeSmuME\Battery
DeSmuME	C:\Users\Matt\Emulators\DeSmuME\Battery
DeSmuME	C:\Users\Matt\Emulators\DeSmuME\Battery
```
