### ISSUE TITLE
Illegal Mode Crashes upon launch

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1147]
Whenever I try to open the latest commit of pkhex in illegal mode by renaming it to PKHaX  it just throws an error that says that the program has stopped working. I tried removing the SD card it may have been using as a directory, but it still crashes upon being launched. Only illegal mode does this. PKHeX regular works fine.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/pull/1138

don't rename the exe
