### ISSUE TITLE
Bug(?): PKHeX doesn't display custom save folder paths if save file is loaded alongside program

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1149]
Tested with latest commit. Note that this is because I have my computer automatically associate certain file formats with PKHeX (such as `.sav`, `.dsv`, and `.bak`), so I simply double-clicked the file to have it be loaded on startup. To replicate:

Double-click `example.sav` (or if you don't wish to associate the file format with PKHeX, Open With) => Save file is loaded into PKHeX => CTRL-F => Only default buttons are displayed

![image](https://cloud.githubusercontent.com/assets/17801814/26183932/e38b1756-3b4f-11e7-9e63-8fe3914a5561.png)

If the program is run on its own and loads the blank Sun save file, it works as intended.
Loading any other save file via File > Open or even drag/drop, it works as intended.

**Comment by kwsch** [comment]
WorkingDirectory strikes again
