### ISSUE TITLE
XML namespace error

### ISSUE THREAD

**Issue by DracoMilesX** [kwsch/PKHeX#1150]
When trying to open the latest commit in VS2015 I receive the following error:

PKHeX-master\PKHeX.Core\PKHeX.Core.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  PKHeX-master\PKHeX.Core\PKHeX.Core.csproj

edit: Checked commits up to 2 days ago and same issue. So it probably is already for a while for me now.

**Comment by evandixon** [comment]
https://projectpokemon.org/forums/forums/topic/40632-problems-compiling/

We should really update the readme.

**Comment by DracoMilesX** [comment]
Thank you for the information hadn't checked the forum yet. Installed VS2017 and all it's working now.
