### ISSUE TITLE
Feature Request: only show valid Mystery Gift formats in Mystery Gift Database depending on SAV version

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1151]
This is due to the Mystery Gift Database being completely useless in Gens 1 through 3, as well as formats not being backwards compatible. If a Mystery Gift file can't be loaded into the SAV format, it shouldn't be displayed at all.

Note, I'm referring to `CB_Format` as well as all the Pokemon displayed in slots. By default, PKHeX displays ALL formats regardless of save file.

However, on the plus side, PKHeX already displays the proper format in `CB_Format` when a certain SAV is loaded (for SAV4, it defaults to `.pcd/.pgt`; for SAV5, it defaults to `.pgf`).

- No Mystery Gift Database in SAV1
- No Mystery Gift Database in SAV2
- No Mystery Gift Database in SAV3 (`.wc3`/`.me3` are only Items and are unsupported by PKHeX anyway)
- Hide the following for SAV4:
`.pgf` (Gen 5)
`.wc6` (Gen 6)
`.wc7` (Gen 7)
- Hide the following for SAV5:
`.wc6` (Gen 6)
`.wc7` (Gen 7)
- Hide the following for SAV6:
`.wc7` (Gen 7)
- Display all formats for SAV7 (this is already done)

And on an unrelated note, an exception occurs when loading Mystery Gift Database from a SAV4BR save file: https://pastebin.com/PAVH5HbL

**Comment by kwsch** [comment]
why restrict when you can improve?
