### ISSUE TITLE
Vespiquen Bug Buzz "invalid move" error

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#1154]
http://i.imgur.com/AgUcK7y.png
Build #3164; she can learn Bug Buzz as Combee at Lv29

_This error didn't happen in the #3097 build_
http://i.imgur.com/xXrpNME.png

**Comment by sora10pls** [comment]
Unable to replicate, make sure the Vespiquen is Lv. 21+
![image](https://cloud.githubusercontent.com/assets/17801814/26238131/cdd7c11a-3c45-11e7-8672-f0669aec949b.png)

**Comment by jisn064** [comment]
https://youtu.be/QPM30_0Z96A

Met location:
http://i.imgur.com/FL4F79b.png

**Comment by jisn064** [comment]
Sorry, I just noticed my mistake.
I'm very sorry for this error T-T (is not related to level...)
