### ISSUE TITLE
Issue with Xamarin

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#1155]
![captura](https://cloud.githubusercontent.com/assets/4681902/26265543/d09741e0-3ce1-11e7-9306-04633b0c7a17.PNG)

**Comment by kwsch** [comment]
Requires c# 7 as well as .NET Core/Standard; I suspect that the new format is unsupported in your version of xamarin.

**Comment by ajtudela** [comment]
Yes, Xamarin Studio is been deprecated to Visual Studio. I fixed, thanks!
