### ISSUE TITLE
Question regarding 3DS keys and encrypted save files

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1159]
Ever since the release of boot9strap thanks to @SciresM and a whole bunch of other developers, we're now able to dump the ARM9 BootROM and the ARM11 BootROM (as well as the console's unique OTP) directly from the 3DS through means of software.

My question is now that we are able to dump these, would it be possible for PKHeX to now decrypt/resign save files loaded directly from the "Nintendo 3DS" directory?

Encrypted save files are located in the following path:
`sdmc:/Nintendo 3DS/<id0>/<id1>/title/000400000/<8character_titleid>/data`

`<id0>` and `<id1>` are NAND specific and would vary per user.
Users may also have more than one of these paths due to having a potential EmuNAND or RedNAND.

The Title IDs for each game would be:
`00055d00` => Pokémon X
`00055e00` => Pokémon Y
`0011c400` => Pokémon Omega Ruby
`0011c500` => Pokémon Alpha Sapphire
`00164800` => Pokémon Sun
`00175e00` => Pokémon Moon

**Comment by kwsch** [comment]
Eventually yeah, but more work needs to be done before this can be feasible.
Like pk3ds, a general purpose save crypto standalone tool has to be made first.
