### ISSUE TITLE
Gen 7 WC Repeatable Push Back List

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1160]
Per our conversation, we identified a push back list that stores up to 50 WCFull IDs.  Would love to look into getting this supported.  My main reason for this feature is legality and preventing people from getting banned by importing a WC which must have a list entry.

A few things to note: Supporting this requires importing WCFulls, not just WCs.  How should importing WC be handled? Should PKHex be smart enough to know and prompt the user with a message telling them should use the WCFull instead?
Currently we are not sure how the game determines if it has been the next day for once-per-day repeatables.  I personally didn't see anything in the save file, but we should research this via code to make sure.

**Comment by kwsch** [comment]
PKHeX currently unpacks the wc#full to yield the wc#.

I'd rather not try to figure out how to insert this editing capability into the mg album editor; maybe a separate form? Dunno.

As for the 'once per day' deal; I assume the single 4byte date is the 'last once-per-day date received' storage.
`Savedata::MysteryGiftSave::ReceiveCheck(int a1)`

I can see GameSync grabbing the entire block via `SetupClone`, so it's entirely possible that this data is transmitted (and could be checked for invalid flags or lack of pushback). If the card is injected->received->deleted there shouldn't be any issues.

**Comment by kamronbatman** [comment]
I assume it must be injected>received>deleted between syncs.  I am on the fence about another form because to me it seems like a similar list to the normal WC List.

**Comment by kwsch** [comment]
Closing due to lack of community interest / documentation of mechanics on forums.
