### ISSUE TITLE
Honey Tree modification corrupts save data

### ISSUE THREAD

**Issue by StealthyAqua** [kwsch/PKHeX#1161]
On a Platinum save, any modification of the honey tree data causes the game to read the save data as corrupted upon loading. It then reverts to a version of the save that ignores all of the honey tree modifications.
![honey_tree](https://cloud.githubusercontent.com/assets/28866212/26311663/1d48a5f4-3ed3-11e7-857e-ccab0c012aad.png)

**Comment by kwsch** [comment]
paging @suloku

**Comment by kwsch** [comment]
Closed by #1215
