### ISSUE TITLE
Legality checks and one possible bug

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1163]
Hi,

First of all let me start with the bug I found in **PKHeX Build 3206**:

I am having trouble with the exp and level tab.
I cannot change the level, it seems like "locked" 
I can't change the experience of a pokemon correctly.If I change any digit, it just levels up or down the pokemon.I don't quite understand how is this happening.

Now the legality checks:

**Testing build 3206**
Last build that everything was ok, with none of the errors below, was **PKHeX Build 3143**

Here are all the files:
[legality checks.zip](https://github.com/kwsch/PKHeX/files/1023115/legality.checks.zip)

**_Starting with Generation 3_**

 **Emerald**:

1. Quasire shows "Invalid Move 1" Yawn (evolded from whoopa which learned Yawn,then leveled up)

2. Houndoom shows "Invalid Move 3" Feint Attack (same as woopa)

3. SEASOR (Kingdra, in-game trade) shows "Unable to match an encounter from origin game"

4. Masquerain shows "Invalid Move 1" Bubble Beam (same as woopa)

**_Moving to Generation 4:_**

**Pearl**

1. Beedril (KOUKOUNA) from LeafGreen, shows "PID-Gender mismatch" (reroll fixes it but I lose the seed)

2. Jigglypuff, hatched in Pearl shows "PID-Gender mismatch" (easy fix-reroll PID, but that wasn't happening before in eralier builds)

3. Wish Chansey, got it from the internet as palparked, with egg hatch location: Emerald. It shows invalid move Wish and Sweet Scent.Changing Origin Game from Emerald to Leafgreen/Firered fixes it.(I think it is illegal. It was only obtained in FR/LG and was able to be transfered in Emerald but the origin game should stay as either FR/LG)

4. SEASOR (Kingdra), the same pokemon palparked from emerald, shows "PID-Gender mismatch" in this generation.

**Platinum**

1. Kingler from HeartGold, shows "Invalid Move 3", Crabhammer (the same in HG) (caught as krabby and leveled up and learned it,then evolded into Kingler)

2. Infernape shows "Invalid Move 1" Close Combat ( it learns close combat)

3. Bibarel shows "PID-Gender mismatch"

**HeartGold**

1. Seadra shows "Invalid Move 2" Dragon Dance (caught as horsea maybe at lvl 37, then leveled up and evolved)

2. Venonat (pokewalker) shows "Invalid move 2" Poison Fang( caught as venomoth and evolved)

**_And last but not least, Generation 5_**

**White**

1. Wailord shows "Invalid Move 4" Heavy Slam (caught as wailmer and evolved)

2.  Gorge (Munchlax) in-game trade, shows "PID-Gender Mismatch" and "Ability mismatch for encounter"

3. Blueeye (Basculin) in-game trade, shows "PID-Gender Mismatch"

4. Minipete (Emolga) in-game trade, shows "PID-Gender Mismatch"

**  What I also found out was that all pokemon from gen 3 and some from gen 4 (infernape only) and from gen 5 (wailord only), when transfered to a gen 6 game lifts their errors that appeared in their corresponding generations.

In generation 7 games add also Kingler,Venonat and Seadra that their errors are fixed

Possible answer why they show this error is because they learned those move before leveling up because they were caught in high level in the wild and then evolved.

Thank you

**Comment by kwsch** [comment]
Levelup move was a recently introduced change (which was incorrect) when handling evolution checking.

Will have to revise a little so that the pkm level isn't decremented 
* a level 16 charmeleon with dragon rage can learn the move as a level 16 charmander -> immediately evolved
PKHeX currently assumes the charmander has to be level 15 for charmeleon to be 16 -- we know this is incorrect as charmander can be 16 for a short period of time to learn those moves.

**Comment by PrometheusG** [comment]
Thank you vey much!

**Comment by greenDarkness** [comment]
I'm experiencing this problem as well. It also seems that the forms for Rotom are also locked similarly to the levels.

**Comment by kwsch** [comment]
Chansey: Illegal anyway (won't explain/fix until gen3 events are fully supported)
Munchlax ability: todo (uses old correlation?)

everything else is fixed :)
