### ISSUE TITLE
[FEATURE REQUEST] Random Box Importing

### ISSUE THREAD

**Issue by SwampyGator** [kwsch/PKHeX#1164]
I am a WTer, and I keep all my pokes in a folder. I use PKHeX's Box Importer to get the pokes into my box. But they are always in the same order. Would it be possible to add a feature where you can import the pokes, but it is random order instead of alphabetical.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/dc911351fe8eca3a9fd8e4a0cd9ab638a118daa8/PKHeX.WinForms/Util/SAVUtil.cs#L97
replace with `Util.Shuffle(filepaths);`

not going to add to default behavior
