### ISSUE TITLE
Form description question

### ISSUE THREAD

**Issue by easyworld** [kwsch/PKHeX#117]
I recently translated some Chinese resources in project and got some question.
When I select "Venusaur" as species in "Main tab", form "Mega" can be seen in combobox, which refers to the resource  [file](https://github.com/kwsch/PKHeX/blob/master/Resources/text/en/text_Forms_en.txt) line  724. Then I select "Blastoise", "Mega" can be also seen in combobox. Why not refer it to [file](https://github.com/kwsch/PKHeX/blob/master/Resources/text/en/text_Forms_en.txt) line  727 which is "Mega Blastoise"?

**Comment by kwsch** [comment]
The text resources for the megas were modified so that "Mega" refers to the singular mega, and Mega X/Y refers to the other set.

https://github.com/kwsch/PKHeX/blob/master/Misc/PKX.cs#L809-L820
