### ISSUE TITLE
R/S Battle Tower Bug

### ISSUE THREAD

**Issue by TheMessageFromDoctorLight** [kwsch/PKHeX#1172]
It seems that, for whatever reason, after doing a round or two in the Battle Tower in both Ruby and Sapphire, PKHeX suddenly starts reading those saves as Emerald saves. Consequently, it also causes quite a few other issues such as several windows of what's shown in the screenshot as well as giving you over 50k of a bunch of items which doesn't seem to be too big of an issue as long as you don't save.

![tfwliterallyrobbed](https://cloud.githubusercontent.com/assets/29036446/26544400/af3ca792-442f-11e7-9ac8-dfbae0ac65d6.PNG)

**Comment by kwsch** [comment]
http://bulbapedia.bulbagarden.net/wiki/Save_data_structure_in_Generation_III#Game_Code

did it work prior to doing battle tower?

For now, hold control when opening the save file and you can manually specify the version.

**Comment by TheMessageFromDoctorLight** [comment]
Yes, the saves I have from before attempting the Battle Tower for work just fine for both Ruby and Sapphire. Thanks for looking into it.
