### ISSUE TITLE
Feature Request: unban Hoenn starter Mega Stones

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1174]
https://twitter.com/serebiinet/status/869404682552303617

Unfortunately not home so I can't submit a PR.

**Comment by kwsch** [comment]
Thanks, will unban with the next release commit :)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/2e30878e8b7c2870696328e55a845665c32eded2
