### ISSUE TITLE
Altar of the Moone Lunala Relearn Moves Error

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1176]
So, whenever Lunala is from the Altar, PKHeX says that it needs relearn moves.
Clicking "Relearn Moves" does not fill them in automatically. 
Thank you for reading.
http://www.mediafire.com/file/5hy300k5u3m47sc/792_-_Lunala_-_0608CCB0D294.pk7

**Comment by sora10pls** [comment]
Relevant thread issuing the same bug: https://projectpokemon.org/forums/forums/topic/40731-crashing-on-loading-save-with-drag-and-drop-and-new-legality-errors/
