### ISSUE TITLE
Build 3264 Eevee Relearn Moves Problem

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1179]
Clicking "Relearn Moves" yields this result. 
Thank you for reading.
![image](https://cloud.githubusercontent.com/assets/15519892/26609660/6d48cba8-4570-11e7-9be2-185f19cef0e4.png)
http://www.mediafire.com/file/2zfg23i77p7tx9t/133_%E2%98%85_-_Eevee_-_3CA8906D0CB1.pk7

**Comment by sora10pls** [comment]
#1176 

Same thread I linked mentions this same error, we should keep it to one central issue. Seems to only apply to Static/Gift Encounters.
