### ISSUE TITLE
Bug: template Pokemon (PK4 through PK7) marked illegal immediately on startup

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1181]
This bug was not present in 04242017 builds, though I'm unsure when this behaviour started to occur (I can check through builds momentarily after posting this issue if need be).

I currently have the following templates in my `template` directory:
![image](https://cloud.githubusercontent.com/assets/17801814/26649744/0e0dc5bc-4615-11e7-98a8-fe631ee2455a.png)

All of these templates were legitimately bred for in each case (Gen 1 is Bulbasaur chosen as my starter), so I can confirm that they're 100% legal. As the issue title says, I'm only getting this behaviour for my PK4, PK5, PK6, and PK7 templates; PK1, PK2, and PK3 all work fine.

If I check legality, it immediately updates to show that the Pokemon is legal.

In addition to this, straight up opening the PKM file (double-clicking, having PKHeX associated with the file format) has this same issue, and isn't limited to 4 through 7; instead, it's 3 through 7.

If need be, I could send the PKMs for you to try and replicate.

**Comment by ReignOfComputer** [comment]
Probably need to add updateLegality(); at https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L1846

**Comment by sora10pls** [comment]
That unfortunately didn't fix the issue.

**Comment by kwsch** [comment]
Can reproduce, tracing procedure:
* Set breakpoint on PID rand button click
* Inspect legality object, find invalid parse result
* Set breakpoint on invalid parse result message
* Find template data being flagged, note why was flagged
* Notice that Ability is set to 0
* Add watch for ability
* Step through loading procedure when pkm is loaded (conditional breakpoint for template species)
* Notice that UpdatePreviewSprite is the method that updated the ability
* Notice that UpdatePreviewSprite is set to call preparePKM via the main form

> preparing data before the other update methods are called

https://github.com/kwsch/PKHeX/blob/e5220946794a4def91cd4afc753abf6aca83f8be/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L231-L235

**Comment by sora10pls** [comment]
Great work finding what caused this. :)
