### ISSUE TITLE
Another legality question

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1183]
Hi sorry to keep bothering you. It seems like every time I make a pokemon legal from an illegal state (usually from the batch editor) it doesn't recognize that its legal and it requires me to manually click on the legal button to refresh it. Im not sure if this is a way to show people that this pokemon was once illegal or if its just the design of it, but would it be possible to automatically make it legal or have an option somewhere to re run legality checks. I had like 200 pokemon that were illegal and it doesn't make sense to have to manually click on every pokemon to refresh them. Thanks and im loving the new legality checks for previous gens.

**Comment by javierhimura** [comment]
Can you uploaded some of the pokemon that have the legal error?

**Comment by NinFanBoyFTW** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/21354941/26685150/374aaa06-46b7-11e7-83c5-22ad9f4c18ba.png)
So this is what it looks like after changing the legality in certain ways (batch editor, certain illegal traits that are fixed)
![untitled-2](https://cloud.githubusercontent.com/assets/21354941/26686378/bc7c2724-46ba-11e7-89ff-9e3652d6e8e9.png)
And here is what happens after I change it  to a legal state. It still shows up as illegal and I have to click on the legality checker to "refresh" the legality. shouldn't there be a button in the options menu to rerun legality because I could see the advantages of both. If you have a bunch of pokemon that were illegal and you fixed them but you wanted to see which ones were illegal in the first place then that would be useful. But in a general sense, if I fix all the legality issues with the batch editor and some of them weren't fixed in that process, then now I don't know what I still need to change. And in my case, I would need to check over 200 pokemon. Also I have checked this on multiple gens and its the same on all of them. Thanks

**Comment by kwsch** [comment]
Hold control when right clicking the pkm in the box. You can check legality without loading to tabs.
Can always just switch boxes to refresh the view.

**Comment by NinFanBoyFTW** [comment]
I just tried what you said and every time I try checking legality with the method you suggested, it comes up with why the pokemon wasnt legal earlier. then when I load the pokemon into the tab and check the legality of it, it says the pokemon is legal. Also even if this was working for me I would have to do this for over 200 pokemon manually. Inst there any way to have an option for rechecking every pokemon's legality or maybe every time you import a box of pokemon it automatically checks their legality, Because I fixed most of the legality issues with my pokemon but Im not sure which ones weren't fixed and this would cause me to manually click on every pokemon to check if they are legal. Like I said, maybe you could have an option similar to the sort all boxes option but for checking legality. sorry for bothering you on this but I just feel that this could make the whole legality system much more usable since people could easily see if they fixed their pokemon. I hope you consider it. Thanks

**Comment by kwsch** [comment]
The boxes update after you finish batch editing, if it still says it's not legal until loading to tabs, then your batch edits didn't fix the legality issues -- it's implying the tabs are fixing it for you.

**Comment by NinFanBoyFTW** [comment]
If the batch editor didn't fix it then why does it say legal when I check it in the tabs

**Comment by kwsch** [comment]
Because the tabs has its own built in corrections when it's asked to return the data (show a sprite or check legality).

**Comment by NinFanBoyFTW** [comment]
Well I dont see what is wrong with these pokemon. I also did a similar thing with my 4th gen pokemon and 7th gen and its the same idea of what is going on. Also Im not sure what it is changing on these pokemon, I looked at all of the tabs and nothing changes between the (illegal) state and the (legal) state.

**Comment by NinFanBoyFTW** [comment]
Actually im seeing that when I change the met location from its current position to a different one it works fine, but this also doesnt make sense because I have all of the pokemon as (met as egg) and if I change the current met location from ex. dewford town to dewford town it also says its legal

**Comment by NinFanBoyFTW** [comment]
Actually im seeing that when I change the met location from its current position to a different one it works fine, but this also doesnt make sense because I have all of the pokemon as (met as egg) and if I change the current met location from ex. dewford town to dewford town it also says its legal
