### ISSUE TITLE
Making pokemon with different gender forms an actual form

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1185]
Hi. I think Ive asked about this before but seeing some new things in pkhex gave me other ideas on this. I wanted to know if it would be possible to make all of the pokemon with gender seperate forms (unfezent, frillish, jellicent, pyroar) have their genders as forms just like meowstick has right now. This is mainly for the reason that when you export pokemon into pk files, you made the other change a while back where forms are noted on the pk file so that when you import them again they are in the correct order. Whenever I import my boxes, the frillish, jellicent, ect... are in different orders than before. I saw you had this set up for meowstick because I guess they actually do count it as a different form but I just wanted to know if it was possible to make all of these pokemon have the same thing as meowstick and that way when you export it, it will automattically have the (form) number. Thanks

**Comment by kwsch** [comment]
AltForms are based off of the stored value in the structure. Gender forms do not have different base stats, they are just use different sprites.

Use the box sort function.
