### ISSUE TITLE
Glitchy Legality Check

### ISSUE THREAD

**Issue by Majiya** [kwsch/PKHeX#1189]
Legality sometimes changes depending on what OT option is highlighted/clicked, despite not actually editing anything:

https://puu.sh/w9WpP/175afb5e1c.png
https://puu.sh/w9Wp7/ad6f46351a.png

When the legality fail is checked, the error is "Untraded: Current handler should not be the Handling Trainer": https://puu.sh/w9WqO/9eba357eec.png

Edit: I've realised that the "Current Handler" box shouldn't allow you to highlight it when it's empty - however sometimes it loads this way and causes a legality fail. Once you click off it, the Pokemon passes again and it does not allow you to click/highlight current handler again.

**Comment by kwsch** [comment]
PKHeX performs automatic fixes when preparing pkm data from tabs; this includes (but not limited to) fixing empty spaces between moves, PP for an empty moveslot, handler data, and memories.

Whenever legality is checked from the tabs (rather from the slot it originated from), the tabs will prepare and fix the data up.

The pkm you're loading is probably illegal; PKHeX fixes its problems and presents you with the fixed pkm's legality report. To see the original (un-modified pkm) legality report, hold control when right clicking the pkm in the box/party/etc slot. You can check legality without loading to tabs.

**Comment by Majiya** [comment]
Thanks for the response.

I tested it holding ctrl and I get the same issue:
https://puu.sh/waob1/09a1f5950e.png

The only illegal thing is "Untraded: Current handler should not be the Handling Trainer" when the Pokemon does not need to be traded. Sometimes I will load PKHeX and the same Pokemon will show as legal - they only fail when the "current handler" box is highlighted upon load despite being empty.

**Comment by kwsch** [comment]
Can't tell without the pkm file.

**Comment by Majiya** [comment]
Saving an individual Pokemon as a .pkm results in them always saving as legal, however this is not the case for the main:

https://www.dropbox.com/s/bszpcp1kpmjvrzk/main?dl=0

All of the Pokemon in this save show as illegal due to the latest handler box being highlighted green, however, if these same Pokemon are set anywhere else they automatically become legal again.

**Comment by kwsch** [comment]
Can't ever have an empty trainer name, the HT has to be 1 character or longer. If there's no handling trainer data, the current handler value should always point to the OT data.

PKHeX detects if it was traded by checking the length of the HT string; since no data is present, it is untraded. As mentioned above, any traded away pkm would get a HT string >= 1 character in length. Since there is no HT data, the current handler value should be 0=OT.

Working as intended :)

**Comment by Majiya** [comment]
So shouldn't it point to the OT then? All legit Pokemon I've caught in-game have an empty 'latest handler' as they've never been traded. The Pokemon in that main file also haven't been traded, and have an empty 'latest handler'.
They don't need to be traded to evolve, so why are they still showing as illegal? Shouldn't they display as legal?

**Comment by kwsch** [comment]
Look at the green highlighting. The green indicates which is the current handler; hence why it is flagging.

Re-read my first reply.

**Comment by Majiya** [comment]
I understand that, but why is it loading with the last handler highlighted? Once I click the OT again, there is no way to re-highlight the latest handler, so I'm curious as to why it's highlighting itself in the first place despite being empty?

Thanks

**Comment by kwsch** [comment]
The pkm data in the boxes is causing it to load the way it is. In the provided data, `[0x93 == 1](https://projectpokemon.org/wiki/Pokemon_Save_Structure_(X/Y)#Block_C_.280x78-0xAF.29)` sets the current handler to 1, being the Handling Trainer (not OT). The pkm data you've provided is not legal.

The game won't flag them as illegal. PKHeX is a more in-depth legality checker.

**Comment by Majiya** [comment]
Thank you so much, I understand now. Would 0x93 == 0 set the the OT as the current handler?

**Comment by kwsch** [comment]
Yes.
