### ISSUE TITLE
gen 7 legality issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1190]
Hi. When I checked the legality of my gen 7 collection, a lot of them (i guess ones I super trained) had this legality issue (cant have active super training unlocked flag for origins.) I guess I know how to fix this problem but I was just wondering what flag this corresponds to.

**Comment by kwsch** [comment]
You can't super train a pkm that originated in gen7, because there is no super training in Sun/Moon.
The pokemon was edited from a gen6 base file.

In general, misc questions belong on the forums; leave GitHub for reporting bugs.

**Comment by NinFanBoyFTW** [comment]
ok but I reported it as a bug because Im pretty sure I just imported these pokemon from gen 6 pk6 files, or I put them through poke bank. Shouldnt pkhex uncheck this flag when importing pokemon from gen 6 games. I didnt try to edit these somehow to add super training. Also can you just tell me what flags to uncheck to fix this legality issue.

**Comment by kwsch** [comment]
no, they're getting correctly flagged as hacks

use the batch editor to set the flags off

**Comment by NinFanBoyFTW** [comment]
How are they hacks though. I genuinly super trained these pokes in pokemon x and y and now im migrating them using either poke bank or just dragging the pk6 files directly into pokemon sun. Also can you please tell me what flags to uncheck. I dont know what flags are responsible for this legality issue

**Comment by kwsch** [comment]
use the search, first result for 'unlocked' after yours

https://github.com/kwsch/PKHeX/issues/1066
