### ISSUE TITLE
Feature Request: improved legality reports

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1193]
This definitely should not be of high priority, but it's something I'd like to see done as it would make things a little nicer to look at. I was thinking something along the lines of color coding the legality identifier before the legality string.

- "Valid:" = Green
- "Fishy:" = Yellow
- "Invalid:" = Red

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1141

**Comment by kwsch** [comment]
[Can't colorize a MessageBox](https://stackoverflow.com/questions/3734796/how-to-customize-message-box), would have to be a new form.

**Comment by greenDarkness** [comment]
>Can't colorize a MessageBox,
That is depressing. This was such a great idea in my opinion.

**Comment by kamronbatman** [comment]
@kwsch has expressed in the past that he is open to a PR to change from a modal to a form, but won't take the time to build it himself because it is not worth it.

**Comment by kwsch** [comment]
Only way I can see a prettier output working is a web-based solution (html) using the [WebBrowser control](https://stackoverflow.com/questions/7514328/how-to-show-html-formatted-content-without-image-in-a-winform).

I'm not interested in prettifying for colors myself, but am willing to accept a PR that shows a popup form with a docked webbrowser showing generated html content.
