### ISSUE TITLE
Umbreon Egg moves Legality Check error?

### ISSUE THREAD

**Issue by InFeX90** [kwsch/PKHeX#1198]
I've got an umbreon, 100 legal by breeding in Pokemon Moon, and pkhex shows this: 

static encounter relearn move mismatch
static encounter relearn move mismatch

It has Curse and Detect as egg moves: 

Umbreon (M) Item: Leftovers  
Ability: Synchronize  
Level: 100
Shiny: Yes  
EVs: 252 HP / 196 Def / 56 SpD  
Careful Nature  
- Curse  
- Detect  
- Moonlight  
- Detect

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1188
