### ISSUE TITLE
[Bug] Encounter Type PID mismatch on Spiky-Eared Pichu

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1199]
The Pichu was obtained legitimately (well as legitimate as it can be now since WFC was shut down and the event is no longer being distributed) in-game using the "Pikachu-Colored Pichu" Wonder Card to spawn the Spiky-Eared Pichu. No modifications were made to the Pichu's PID so this shouldn't be flagged as illegal.

![image](https://user-images.githubusercontent.com/17801814/26895112-7b447d50-4b8e-11e7-89e3-82345ef5c5f3.png)
![image](https://user-images.githubusercontent.com/17801814/26895128-8415c362-4b8e-11e7-91d1-f6d7e437f45b.png)

Edit 1: in case it's needed, here's the full legality report (note "PID Type: None")
![image](https://user-images.githubusercontent.com/17801814/26895292-2b3c47ba-4b8f-11e7-9174-6436cbb790fd.png)

Edit 2: If you need the PKM, [here](https://github.com/kwsch/PKHeX/files/1059007/spiky.zip) it is. TID and SID were zeroed out for my own sake. :P

**Comment by sora10pls** [comment]
Also something I just realized, SAV4 seems to not automatically flag legality like other save files do.

**Comment by kamronbatman** [comment]
Does the encounter use a modified PID method? Because by default we would assume it follows the same wild encounter method as all other soul silver pokemon.

**Comment by kwsch** [comment]
probably just best to add an exclusion case as there's no need to create a 'fixed PID static encounter' type or add a u32? to the encounterstatic class for this one-off.

**Comment by kwsch** [comment]
Forced naughty and antishiny, so not a fixed PID. Would need documentation on how it's generated.
