### ISSUE TITLE
Drag and drop between PKHex windows improvement request

### ISSUE THREAD

**Issue by Pkmnninja** [kwsch/PKHeX#12]
I tried dragging and dropping pokemon between PKHex windows, and the dragging works, except the data doesn't transfer from the second window to the first properly, with the first window setting a pokemon using the current data within the window instead of transferring the data over.

Example: I had Deoxys data up on the first window, dragged a Venusaur over from the second, and it made another Deoxys on the first instead of copying the Venusaur over.

This feature is active on Pokegen if it helps with the coding.

This would be really useful in mass transferring from one save file to another, or even just transferring from one game save to another in general.
Thanks.

**Comment by kwsch** [comment]
With the dragging between windows, it's just best to drop it into tabs for each, then set it into a slot. It's a lot of work for very little gain.
