### ISSUE TITLE
"Evolution not valid" bug on move-based evolutions

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1200]
Move-based evolutions should be legal at the same level the move is learned, as the level-up event that triggers the learning of the move also triggers evolution with no further level-up required. Also, they should be legal at any level in gen 7 as the move reminder now teaches any level-up move regardless of current level.

![capture](https://user-images.githubusercontent.com/23516075/26899790-cd8d9afe-4b95-11e7-99d6-e01a124197f4.PNG)

**Comment by javierhimura** [comment]
Ok, if i understand right that means
- Current level must be great or equal to the minimun learn level of the move, current check do not allow equal as legal.
- Minimun level for every move in generation 7 would be 2, that would be a pokemon learning the move at level 1 with move reminder and then level up to 2.

Still the current level must be one level after met level except for gen 3 non-eevee in generation 5 to 7.
