### ISSUE TITLE
Gen III Name/Money Bug

### ISSUE THREAD

**Issue by TheMessageFromDoctorLight** [kwsch/PKHeX#1204]
Another niche issue. When giving yourself the maximum amount of money possible while having a name with all 7 characters allowed, the name glitches out. Trying to access your Trainer Card just resets the game, but otherwise, I haven't checked to see if this has any other negative effects. Changing your name to something with less than 7 characters fixes the issue I found.

This seems to affect every GBA game.

![howdoyoupronouncethatagain](https://user-images.githubusercontent.com/29036446/26934555-b0732c8e-4c37-11e7-997e-317d8fbcbb5f.png)

**Comment by kwsch** [comment]
doubt it's related to money, probably related to the name length

**Comment by TheMessageFromDoctorLight** [comment]
I'm fairly certain its in some parts both. Looking into it a bit more, changing the amount of money you have in general with a 7 character name causes the issue.

**Comment by TheMessageFromDoctorLight** [comment]
So checking back on my LeafGreen save in PKHeX, I find the names for both the player, rival, and PC boxes have been converted to the Japanese version font, and trying to change them only leads to errors similar to the above, although everything is perfectly normal in-game if you don't bother changing anything from there.

Here's the save file in question if you want to have a look at it.

[Pokemon LeafGreen.zip](https://github.com/kwsch/PKHeX/files/1062284/Pokemon.LeafGreen.zip)
