### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1207]
#### Bug 1: Crash when loading PK1
Happens regardless of loading method. When debugging:
![image](https://user-images.githubusercontent.com/17801814/26958171-21217a94-4c97-11e7-9b16-30ad8066fabb.png)

#### Bug 2: Flag legality not checked by default in most cases
If a save file is loaded, flag legality is not checked by default. However, if a BAK save file is loaded, it is checked by default.

Edit: this one seems to have fixed itself, or at the very least, doesn't always happen. Not sure how it even happened. ¯\\_(ツ)_/¯

#### Bug 3: Save considered edited on load if template PKM is loaded
Same issue as described in #1076, only the difference is that this *only* happens if a template PKM is loaded alongside the save file.

**Comment by kwsch** [comment]
2: flag legality is a program setting that is loaded before any save file
