### ISSUE TITLE
missing item

### ISSUE THREAD

**Issue by asdfasdfui3** [kwsch/PKHeX#1209]
moon/sun is missing travel trunk(gold case)

**Comment by sora10pls** [comment]
Item was unused in Gen 6. If you want it, run PKHaX.

**Comment by kwsch** [comment]
The Gen6 Travel Trunk (1) was replaced with Makeup Bag in Gen7. The only travel trunk that remains is the second one.

**Comment by asdfasdfui3** [comment]
gold is the one that wasn't replaced, silver is what became the bag

but you're saying it'll show in the list if I switch to pkhax? 
...which google says you do just by renaming the pkhex.exe to "PKHax.exe"?
cause I tried that on the latest download from project pokemon and got an error message (unless I also renamed the core.ddl.config file in which case the item still didn't show)

**Comment by kwsch** [comment]
Invalid/Stubbed items are not shown in the default mode of PKHeX. Keeps the item list clean.

Info on how to start in illegal mode (hax) are detailed on the forums; the mode may be requested when launching the program via a command line argument.

Travel Trunk (2) is the item you are looking for.

**Comment by asdfasdfui3** [comment]
it's not in the three stickied threads, but I'll find it eventually with the search. anyway if the item is there thats fine then, may as well close this
