### ISSUE TITLE
[Bug] weird PKHaX prompt

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1210]
When running PKHaX from a batch file, the following is displayed:
![image](https://user-images.githubusercontent.com/17801814/26983476-ed096762-4d09-11e7-9251-06a1e131e997.png)

My batch file reads (as noted somewhere on the forums):
`start pkhex hax`
`exit 0`

**Comment by kwsch** [comment]
[just an inserted P by yours truly](https://github.com/kwsch/PKHeX/blame/dbb7b967ca454b55140f7698af2bf04107ab5576/PKHeX.WinForms/MainWindow/Main.cs#L172)

**Comment by sora10pls** [comment]
**P**retty funny eh?
