### ISSUE TITLE
Flabébé/Floette encounter legality issues

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1216]
The encounter check for Flabébé incorrectly assumes there's a single encounter slot with all forms being valid, but there are actually three different encounters that yield different forms at different levels. Yellow is the only form the current check adequately covers; Red and Blue are each exclusive to a different route, and Orange and White are encountered at fixed levels:

**Route 4**
- Red/Yellow (Lv. 6-8)
- Orange  (Lv. 7)
- White (Lv. 8)

**Route 7**
- Blue/Yellow (Lv. 12-14)
- Orange (Lv. 13)
- White (Lv. 14)

Also, all forms of Floette besides the Red Flower form are flagged as invalid encounters if they were evolved from wild Flabébé.

**Comment by kwsch** [comment]
https://projectpokemon.org/forums/forums/topic/37383-flab%C3%A9b%C3%A9-pumpkaboo-forms-blackwhite-flutes-and-friend-safari-floette-legality-checker/#comment-197156

>According to Encounter Tables, Orange Flabébé can only be found at Level 13, but other forms can be found at Level 14. But using a leading Pokémon with the ability Pressure (Hustle and Vital Spirit also work), when encoutering a specific species, there is a 50% chance of having the maximum level of the said species (different forms are treated as same species). This is how it is possible to meet an Orange Flabébé at Level 14.

Would need to see specimens for the latter half of the report; an Orange Florges at met level 8 on route 4 is valid.

**Comment by wwwwwwzx** [comment]
Just tested, an orange Flabébé met at level 14 on route 7 is possible

**Comment by White-Canary** [comment]
@wwwwwwzx Thanks for the input, but kwsch already pointed that out lol. I knew about the abilities but was unaware they used the maximum level for the species and not individual forms. You learn something new every day I guess.

@kwsch I'm assuming you tested that in gen 6 only? Further testing indicates the problem is indeed tied to form, but it appears to only happen in gen 7. Freshly caught and evolved Flabébé of every color came up valid, as did the previously tested Floette on an old backup of my gen 6 save. Transferring to gen 7 is what causes them to be flagged as invalid. Also, it only happens with Floette, evolving it to Florges fixes the issue.

**Comment by kwsch** [comment]
@White-Canary ah, is related to the prior Florges fix, needed to keep the part pertaining to Floette.

Can re-implement the meowstic form redirection while I'm at it
