### ISSUE TITLE
[Bug] B2/W2 Formes in B/W

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1218]
Tornadus, Thundurus, Landorus, Kyurem, and Keldeo all received new Formes in B2/W2; PKHeX allows you to change their Formes in B/W save files despite these not existing in B/W.

For reference, the only Legendary (or in this case, Mythical) Pokemon to have a second Forme that's in both B/W and B2/W2 is Meloetta and its Pirouette Forme.

In PKHeX:
![image](https://user-images.githubusercontent.com/17801814/27015723-d1c0449a-4ee3-11e7-97b3-01ac15fbdbbe.png)

In-game:
![02 - white__371](https://user-images.githubusercontent.com/17801814/27015729-fcd4e00a-4ee3-11e7-902c-a8d6cbdfa834.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/cf8f6573f2f11019fb9e77d23f0f69f63757a44d
