### ISSUE TITLE
[future request] disable legality checker when illegal mode (pkhax) is active

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#122]
I understand if you're against this idea but it's really kinda awkward for the tool to tell us what is and what is not legal when we're intentionally in illegal mode. After all, illegal mode is a feature that 'you have to know' coz ngl.. having to rename the tool is pretty darn sneaky (props for that btw!)

**Comment by jlopez788** [comment]
I took a copy of the code a while back and modified it and made it my own. this is one of the things I changed.

**Comment by Favna** [comment]
If you single out this change (so it's the only change compared to the Master branch) you could make it a Pull Request and then Kaphotics can merge it. That would be the best way to contribute.

**Comment by kwsch** [comment]
Already accounted for in the multigen branch:

https://github.com/kwsch/PKHeX/blob/multigen/PKX/f1-Main.cs#L765

The multigen branch will eventually be pushed into the master
