### ISSUE TITLE
[Feature Request] Cap PKM Friendship

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1220]
Making it function the way IVs/EVs textboxes do. If something greater than 255 is entered, automatically replace it with 255.

I recall this already being a feature but for whatever reason it doesn't automatically do this anymore.

**Comment by kwsch** [comment]
It still does, it now just does it on validation (when focus is changed from the MaskedTextBox).

**Comment by sora10pls** [comment]
Ah, thanks!
