### ISSUE TITLE
error MSB4041 while building

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#1222]
> 1>------ Rebuild All started: Project: PKHeX.WinForms, Configuration: Release Any CPU ------
> 1>F:\PKHeX\PKHeX.Core\PKHeX.Core.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
> 2>------ Rebuild All started: Project: PKHeX.Tests, Configuration: Release Any CPU ------
> 2>F:\PKHeX\PKHeX.Core\PKHeX.Core.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
> ========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

Lost my old PKHeX folder decided to clone fork again, getting this error when trying to build

**Comment by ReignOfComputer** [comment]
Are you on Visual Studio 2017?

**Comment by Ninjistix** [comment]
nope 2015, I wasn't around awhile did we switch from 2015 to 2017?
