### ISSUE TITLE
[Bug] Gen 5 Batch Editor modifies empty Party slots, turning them into placeholder data

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1224]
To replicate:
- Load any Gen 5 save file in PKHeX
- Have any number of empty slots in Party
- Run the `.MetDate` command in the Batch Editor to modify Met Dates of Pokemon
- Export save file

What it looks like in-game:
![1](https://user-images.githubusercontent.com/17801814/27108721-caa1337e-506c-11e7-8f61-0ad13f38b140.png)
![2](https://user-images.githubusercontent.com/17801814/27108722-caae4712-506c-11e7-9535-3635be4165df.png)

I'll try and see if other commands have this same behaviour, as I've only tested Met Date.

Edit 1: this happens with multiple commands. I think the problem is the Batch Editor is (more than likely) also modifying empty slots, and this seems to only affect Party slots. If a Pokemon from PC is placed into the Party and the placeholder is swapped into the PC, it then disappears when the PC is rebooted. Will have to check if this is the case for all other games.

Edit 2: This only affects Gen 5.

**Comment by kwsch** [comment]
Seems like it's setting the party count to 6? would need to do a before/after of the save file around 0x18E00

**Comment by sora10pls** [comment]
Before:
![image](https://user-images.githubusercontent.com/17801814/27113606-ce0e6800-508b-11e7-8f17-45fb861a498e.png)

After:
![image](https://user-images.githubusercontent.com/17801814/27113616-dce9fec0-508b-11e7-89e4-6995fa1ec4ce.png)

**Comment by kwsch** [comment]
Yeah, it's set to write partycount to the second 4 bytes; maybe it's [party max && party empty slots] or something like that. Will have to investigate other save setups.

**Comment by kwsch** [comment]
Yeah, it's set to write partycount to the second 4 bytes; not sure why it's writing 6. That's what causes it to think the empty slot is actual data.
The value correlates directly to party count; was that before sav only having 1 party pkm?

**Comment by sora10pls** [comment]
Yeah, I should've mentioned that prior.

`before.dsv` had only 1 Pokemon in the Party (Samurott).
`after.dsv` was that same save but had the Batch Editor edit.
