### ISSUE TITLE
milotic gen 3 error

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1229]
Hi. I just wanted to let you know that a milotic I made from smogon specs was flagged as illegal for having the move hypnosis. I had everything set correctly saying that it came from an egg, an it looks like hypnosis is an egg move of milotic. Thanks

**Comment by sora10pls** [comment]
Do you have the proper Relearn Moves? That should include Hypnosis.

I'm not at home so I can't test myself.

**Comment by NinFanBoyFTW** [comment]
I dont think gen 3 has relearn moves. Or at least I dont see them here

**Comment by sora10pls** [comment]
You're right, my mistake. That said, I can't replicate.

![image](https://user-images.githubusercontent.com/17801814/27161684-0aadff86-514b-11e7-815e-b5107517ba1d.png)
![image](https://user-images.githubusercontent.com/17801814/27161690-145d70ac-514b-11e7-9867-fa6cdd6bbd15.png)

**Comment by NinFanBoyFTW** [comment]
thats because your in moon. Im saying in Gen 3 (emerald)

**Comment by sora10pls** [comment]
I thought you meant from Gen 3, that was my mistake (again).

I can indeed replicate this.
![image](https://user-images.githubusercontent.com/17801814/27161805-c44346fe-514b-11e7-8396-c7a3fef39d1a.png)

**Comment by kwsch** [comment]
Let me guess, you don't have sufficient Beauty?

**Comment by sora10pls** [comment]
That's it, I forgot Prism Scale was Gen 5+!
![image](https://user-images.githubusercontent.com/17801814/27161897-535c1488-514c-11e7-85a4-2ff6b05fef9a.png)

**Comment by kwsch** [comment]
There's still an issue where it thinks Milotic is a valid egg encounter (no hypnosis and beauty = valid)
