### ISSUE TITLE
manaphy egg bug

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1231]
I have a manaphy egg in my diamond and it says its illegal. when I click on it this is what it spits out
Also if its possible, would you be able to make the egg sprite for manaphy, the manaphy egg, instead of the normal egg. Thanks
```
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.LegalityAnalysis.getLegalityReport()
   at PKHeX.WinForms.Main.clickLegality(Object sender, EventArgs e)
```

**Comment by kwsch** [comment]
You'll have to upload the PKM file, unable to reproduce.
