### ISSUE TITLE
pokemon met date when transferring them

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1233]
Hi. I wanted to know if it is possible to make it so that when you transfer a pokemon through pkhex, it retains its original met date. I know this isnt possible with gen 1-3 but for 4th-7th wouldn't it make sense to just keep the original met date instead of changing it to the date when you imported it on pkhex. I have a lot of pokemon from over 10 years ago and its hard to transfer them through pkhex because it loses the met data. Thanks

**Comment by kwsch** [comment]
PKHeX emulates the official transfer methods.
If you wish to have different behavior, make the change yourself on a private fork.

**Comment by NinFanBoyFTW** [comment]
Hi. I just tested it for myself, and when you transfer pokemon through the poke transfer, it keeps the met date. I transferred a pikachu from white 2, and it kept the date. Shouldn't it keep the dates in pkhex if thats how the official transfer method works.

**Comment by kwsch** [comment]
PKHeX does.

https://github.com/kwsch/PKHeX/blob/5d50f58d86378011fb0396437150ce972f42fb2f/PKHeX.Core/PKM/PK5.cs#L373-L379

**Comment by NinFanBoyFTW** [comment]
ok but every time I import a pokemon from gen 4 it sets the date to today's date. It also sometimes happens with gen 5 pokemon, but for the most part it it seems to be on gen 4 games

**Comment by kwsch** [comment]
>from gen 4

duh, it has to go 4->5->6(->7); since it does 4->5 (as listed above) it changes the date to today, because that's what poketransporter does.
