### ISSUE TITLE
[Feature Request] Add catch rate textbox to Gen 1 PKM editor

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1235]
As the issue title says; allow users to view/edit the Pokemon's catch rate.

Edit: this was already requested as an improvement in #247, though it was never re-opened after PK1 -> PK7 transfer was documented, so I figured that I'd ask again since PK1 shininess was added but not this.

**Comment by kwsch** [comment]
It's already automatically handled by the program when setting a species.

https://github.com/kwsch/PKHeX/blob/dc8639a31f4c12a9d88611ce3da05e20c9e94f7c/PKHeX.Core/PKM/PK1.cs#L135-L149

**Comment by sora10pls** [comment]
Would still be a nice addition for those who wish to just make legal Pokemon on the fly, and not have to edit Catch Rates in a hex editor.

Example would be editing a Bulbasaur to Raichu with Quick Attack. Would need to change Bulbasaur's 45 Catch Rate to Pikachu's 190 Catch Rate; couldn't be Raichu's since its Catch Rate is 75 and Quick Attack is Pikachu only.

**Comment by kwsch** [comment]
You don't have to edit it in a hex editor, you just switch to a legendary then to the target catch rate species

I'll add a click shortcut, not exposing this data outside of the Batch Editor.
