### ISSUE TITLE
[Feature Request] Gen 4 Shiny Leaf editor

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1236]
Add an editor for Gen 4's Shiny Leaves; [here's a Pastebin](https://pastebin.com/BhHGMQ10) I compiled which has every value that needs to be written to the PK4 for Shiny Leaves.

This Pastebin obtains every possible combination of Shiny Leaves (including Leaf Crown, though only 1, 2, 3, 4, 5, C should be allowed), and could probably be implemented the way PokeGen does it:
![image](https://user-images.githubusercontent.com/17801814/27250443-db74ad14-52fd-11e7-9e48-7bea300ffc55.png)

Edit: re-uploaded Pastebin to my account (which means new URL compared to original post), and added any missing Shiny Leaf values to Pastebin (was and should be just one).

**Comment by javierhimura** [comment]
Looking the Pastebin it seems is only a bitmap from the byte 0x41
The byte 0x07 is the checksum of the pokemon

The edition should allow any combination included illegal ones, illegal combinations should be marked by the legal analysis 
Probably  the only illegal combination is Crown with the other shiny leaf, or maybe crown without the other 5 shiny leafs, i dont know if the game remove the 1-5 shiny leaf when the crown is received

**Comment by sora10pls** [comment]
I could do some testing to see what happens when all 5 Shiny Leaves are obtained and then check with PokeGen to see which are checked/unchecked. Will report back once I do that.

**Comment by sora10pls** [comment]
Pokemon can keep their 5 Shiny Leaves, and are rewarded a Leaf Crown when speaking to Ethan/Lyra in New Bark Town.

Before speaking to Lyra:
![1](https://user-images.githubusercontent.com/17801814/27254411-761f6a8c-5355-11e7-8c1c-58111690820b.png)

After speaking to Lyra:
![2](https://user-images.githubusercontent.com/17801814/27254412-761fe8fe-5355-11e7-9ef8-cbd6df700cc9.png)

After receiving the Leaf Crown, all 5 Shiny Leaves are kept and the Crown is added.
![image](https://user-images.githubusercontent.com/17801814/27254419-99fec3f8-5355-11e7-9bc7-759c1d224514.png)

**Comment by sora10pls** [comment]
Legal Shiny Leaf values: https://pastebin.com/qCGfyYU1

Illegal Shiny Leaf values: anything including Crown but not having 1 through 5 obtained.

**Comment by kwsch** [comment]
Did you notice it's just 5 bitflags? ;)
https://projectpokemon.org/wiki/Pokemon_Save_Structure#Block_B

**Comment by sora10pls** [comment]
Would've been more smart of me to look it up prior lmao, oh well!

**Comment by kwsch** [comment]
looks terrible
![image](https://user-images.githubusercontent.com/6393368/27258094-ea9d4c6c-53a5-11e7-8627-83cc3cf83bff.png)
 /s

**Comment by sora10pls** [comment]
Hey, Bulbasaur isn't that bad ;P

**Comment by sora10pls** [comment]
Found a bug: Crown checkbox becomes disabled entirely if unticked, re-enables itself if another Shiny Leaf checkbox is unticked and then reticked.

To replicate:
Get a PKM with no Shiny Leaves -> Tick all 5 Shiny Leaf checkboxes -> Tick Leaf Crown checkbox ->Untick Leaf Crown checkbox
