### ISSUE TITLE
Couldn't drag pk7 files into box directly .Win10

### ISSUE THREAD

**Issue by ahthmz** [kwsch/PKHeX#1237]
Several days ago this bug had been fixed. But in recent updates,this bug comes out again.
Pk7 files can be dragged out from boxes.
But I couldn't drag pk7 files into box, main files either.

**Comment by ahthmz** [comment]
84d3247  update ,this bug still exists

**Comment by kwsch** [comment]
Not sure what the exact issue is.
Certain areas do not support drag-drop, refer to the mouse cursor feedback.
