### ISSUE TITLE
Problem with Crobat's Relearn Moves in G7

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1239]
In the 3405 build of PKHeX, Crobat's basic relearn moves cannot be added automatically. If you click 'relearn' it is missing basic egg moves on Zubat.
Thanks for reading!
http://www.mediafire.com/file/cjaz61k7jwij5cj/169_-_SpedieBoyes_-_3A04125C7AA1.pk7

**Comment by sora10pls** [comment]
Super Fang is OR/AS move tutor.

S/M origin (the PKM you provided):
![image](https://user-images.githubusercontent.com/17801814/27256750-23b4faee-538e-11e7-96b0-e24f7fc7472b.png)

OR/AS origin:
![image](https://user-images.githubusercontent.com/17801814/27256754-3fc41d3c-538e-11e7-8d3e-aea83b2cce05.png)
![image](https://user-images.githubusercontent.com/17801814/27256756-48c4c58a-538e-11e7-8ad4-f36b6ab7374a.png)

**Comment by sora10pls** [comment]
Crobat's Relearn Moves for Gen 7 are working as intended.

![image](https://user-images.githubusercontent.com/17801814/27256774-8da7acd0-538e-11e7-8b63-eda957c7c30e.png)
![image](https://user-images.githubusercontent.com/17801814/27256776-9299d42a-538e-11e7-87b2-ce8b12530e18.png)

**Comment by greenDarkness** [comment]
Pardon, I don't think I expressed the problem in detail enough. 
If you add an egg move to the Pokemon in the last picture, such as hypnosis, and then click 'relearn moves' this happens.
![image](https://user-images.githubusercontent.com/15519892/27256822-cea8d672-538f-11e7-834c-ada57100c65d.png)

**Comment by sora10pls** [comment]
Yeah I figured that was the bug you were referring to, but the Crobat isn't legal as it is. Happens when the Crobat is illegal but not when it's legal. :)

**Comment by greenDarkness** [comment]
Yeah, I realized that it had some ORAS move tutor moves. I probably should have used a legal G7 for the example as to avoid confusion. ^_^

**Comment by kwsch** [comment]
When in doubt, hold control when checking legality, it will let you know more details on what it matched.
In this case, it was matching it to a Wild Encounter (for whatever reason), as the egg encounter was invalid (bad relearn moves).
