### ISSUE TITLE
legality error gen 4

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1240]
Hey on the version of pkhex im running (github build from yesterday) on a bunch of my pokemon (legendaries, unown, etc) they have a legality error, Invalid encounter type PID mismatch. On the current official build of pkhex I have no legality errors. Also when I try to keep re rolling the pid or I change the met location back and forth, this error doesn't go away

**Comment by kwsch** [comment]
Behavior is working as intended; the current build of PKHeX checks for valid PIDIV combos for generation 3 & 4 now.

Rerolling from the PKM editor won't give you a valid PID.

**Comment by NinFanBoyFTW** [comment]
so how do you make these pokemon legal then

**Comment by kwsch** [comment]
Generate a legal PID with RNGReporter or any similar app; PKHeX does not have a PID Generator at this time.

**Comment by NinFanBoyFTW** [comment]
Ok but its showing up on legionaries that I caught in the wild with no hacks. I havent touched these guys at all
