### ISSUE TITLE
[Bug] Gen 3 Trainer Info + Language Detection bugs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1244]
**EDIT 1:** I can now confirm that this happens with all Gen 3 games, not just Emerald.

**EDIT 2:** Seems as if any Trainer Info modification has this effect. I had a FireRed save file with the Trainer Name "MATT", and simply changed the Play Time from 0:00:12 to 0:00:01; this then made PKHeX view the save file as Japanese rather than English. 

Tested with latest commit and all Gen 3 games (most testing done with Emerald). To replicate:

- Load any English Gen 3 save file
- Open Trainer Info Editor
- Change Trainer Name to something with 4 or less characters
- Save changes and export SAV

When loading the save file up a second time in PKHeX, it now automatically detects the save file as Japanese, rather than being English.

In my first set of testing, the Trainer Names were:
- "MATT!" (unmodified); was recognized as an English save file
- "MATT!!" (modified); was recognized as an English save file
- "MATT" (modified); was recognized as a Japanese save file

In my second set of testing, the Trainer Names were:
- "MATT" (unmodified); was recognized as an English save file
- "MAT" (modified); was recognized as a Japanese save file

**Comment by kwsch** [comment]
Related: https://github.com/kwsch/PKHeX/issues/1204
