### ISSUE TITLE
Unable to compile on Windows 7 32 bits

### ISSUE THREAD

**Issue by Gliscor** [kwsch/PKHeX#1247]
I'm a hard time compiling this on Windows 7 Starter (32 bit), everytime i use the command "MSbuild" on the PKHeX.WinForms folder i get this error:

`C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms>msbuild
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18/06/2017 08:50:10 p.m..
Project "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.cspr
oj" on node 1 (default targets).
C:\Program Files\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Micro
soft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemb
lies for framework ".NETFramework,Version=v4.6" were not found. To resolve this
, install the SDK or Targeting Pack for this framework version or retarget your
 application to a version of the framework for which you have the SDK or Target
ing Pack installed. Note that assemblies will be resolved from the Global Assem
bly Cache (GAC) and will be used in place of reference assemblies. Therefore yo
ur assembly may not be correctly targeted for the framework you intend. [C:\Use
rs\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.csproj]
Done Building Project "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX
.WinForms.csproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.csproj" (def
ault target) (1) ->
(GetReferenceAssemblyPaths target) ->
  C:\Program Files\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Mic
rosoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference asse
mblies for framework ".NETFramework,Version=v4.6" were not found. To resolve th
is, install the SDK or Targeting Pack for this framework version or retarget yo
ur application to a version of the framework for which you have the SDK or Targ
eting Pack installed. Note that assemblies will be resolved from the Global Ass
embly Cache (GAC) and will be used in place of reference assemblies. Therefore
your assembly may not be correctly targeted for the framework you intend. [C:\U
sers\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.12

C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms>`

I think i have installed all the necessary stuff to compile this: (see attached screenshot)
![visual 1](https://user-images.githubusercontent.com/11700855/27265785-6fb750b0-5468-11e7-9e15-22c6aaf9b8db.jpg)

Please help me, i want to be able to compile this by myself. Thanks!

**Comment by kwsch** [comment]
The error is descriptive enough...

>**The reference assemblies for framework ".NETFramework,Version=v4.6" were not found.** To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Comment by Gliscor** [comment]
As you can see on the screnshot, i have them installed, 4,7 isn't compatible with 4.6?

**Comment by kwsch** [comment]
I don't think 4.7 is a superset of 4.6; try running the 4.6.2 installer.

**Comment by Gliscor** [comment]
Hi, after uninstalling 4.7 and installing 4.6.2 with the https://www.microsoft.com/en-us/download/details.aspx?id=53321 i'm now getting this error:

`C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms>msbuild -p:FrameworkPathOverr
ide="C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.
6"
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18/06/2017 11:17:19 p.m..
Project "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.cspr
oj" on node 1 (default targets).
Project "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.cspr
oj" (1) is building "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj" (2) on node 1 (GetTargetFrameworkProperties target(s)).
C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.csproj : error MSB401
9: The imported project "C:\Program Files\Microsoft Visual Studio\2017\BuildToo
ls\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that th
e path in the <Import> declaration is correct, and that the file exists on disk
.
Done Building Project "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Cor
e.csproj" (GetTargetFrameworkProperties target(s)) -- FAILED.

Done Building Project "C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX
.WinForms.csproj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms\PKHeX.WinForms.csproj" (def
ault target) (1) ->
"C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.csproj" (GetTargetFr
ameworkProperties target) (2) ->
  C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.csproj : error MSB4
019: The imported project "C:\Program Files\Microsoft Visual Studio\2017\BuildT
ools\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that
the path in the <Import> declaration is correct, and that the file exists on di
sk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.26

C:\Users\XXXX\Desktop\PKHeX-master\PKHeX.WinForms>`

I don't have and never had a folder called: Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props in the "MSbuild" folder, please, help me to fix this, i don't know what to do now

**Comment by kwsch** [comment]
Are you using Visual Studio 2017?

**Comment by Gliscor** [comment]
Yeah, I've installed Microsoft Visual Studios Build Tools 2017

**Comment by kwsch** [comment]
build tools != ide
https://www.visualstudio.com/vs/whatsnew/

**Comment by Gliscor** [comment]
Sorry for pestering you, i don't have anybody with the technical knowledge to assist me in this issue, I've installed the Visual Studio 2017 IDE (Community) and keep getting the same error, it's necessary to install these big programs just to build that little PkHex.exe file?

**Comment by kwsch** [comment]
Big program is necessary as PKHeX uses the latest c# language features; there aren't small compilers that can deal with c#7.

Only advice I can offer is to google the basic error strings.

**Comment by evandixon** [comment]
If you just want the exe, you can go to PP's Team City server.
https://teamcity.projectpokemon.org/repository/download/PKHeX_BuildWindows/9512:id/PKHeX%20Build%203423.zip

**Comment by Gliscor** [comment]
Thank you @evandixon, but i want to build it by myself so i can have always the latest version.

Ok @kwsch, will do. Thanks.

**Comment by evandixon** [comment]
Here's the permalink (requires more clicking: log in as guest, go to the artifacts tab, download the zip file): 
https://teamcity.projectpokemon.org/viewLog.html?buildTypeId=PKHeX_BuildWindows&buildId=lastSuccessful&buildBranch=%3Cdefault%3E

**Comment by Gliscor** [comment]
Okay, I've installed Visual Studio Enterprise 2017 which fixed the:  Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props not found error... now, when i open a command line in the C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.WinForms folder and type: "MSbuild" i get all this errors:

> csproj]
  Saves\SAV3XD.cs(169,28): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(170,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(171,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(172,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(174,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(181,25): error CS0518: Predefined type 'System.Boolean' is no
t defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Cor
e.csproj]
  Saves\SAV3XD.cs(182,25): error CS0518: Predefined type 'System.String' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(236,25): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(237,25): error CS0518: Predefined type 'System.String' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(238,25): error CS0518: Predefined type 'System.UInt16' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(239,25): error CS0518: Predefined type 'System.UInt16' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(241,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(242,25): error CS0518: Predefined type 'System.UInt32' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(326,25): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(34,17): error CS0518: Predefined type 'System.Boolean' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(122,38): error CS0518: Predefined type 'System.Boolean' is no
t defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Cor
e.csproj]
  Saves\SAV3XD.cs(122,48): error CS0518: Predefined type 'System.Boolean' is no
t defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Cor
e.csproj]
  Saves\SAV3XD.cs(122,25): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(148,25): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(177,28): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(199,44): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(199,58): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(199,24): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(243,16): error CS0518: Predefined type 'System.UInt32' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(243,82): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(246,44): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(246,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(250,42): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(250,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(254,43): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(254,25): error CS0518: Predefined type 'System.String' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(258,41): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(258,50): error CS0518: Predefined type 'System.String' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(258,25): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(264,36): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(264,25): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(268,43): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(268,25): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(273,42): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(273,25): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(277,43): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(277,25): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(285,40): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(285,28): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(307,40): error CS0518: Predefined type 'System.Object' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(307,28): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(356,50): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(356,59): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(356,25): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(357,45): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(357,54): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(357,25): error CS0518: Predefined type 'System.Nullable`1' is
 not defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.
Core.csproj]
  Saves\SAV3XD.cs(357,25): error CS0518: Predefined type 'System.UInt32' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(358,49): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(358,58): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(358,25): error CS0518: Predefined type 'System.Nullable`1' is
 not defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.
Core.csproj]
  Saves\SAV3XD.cs(358,25): error CS0518: Predefined type 'System.Boolean' is no
t defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Cor
e.csproj]
  Saves\SAV3XD.cs(359,44): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(359,53): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(359,63): error CS0518: Predefined type 'System.UInt32' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(359,25): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(360,49): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(360,58): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(360,68): error CS0518: Predefined type 'System.Boolean' is no
t defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Cor
e.csproj]
  Saves\SAV3XD.cs(360,25): error CS0518: Predefined type 'System.Void' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(362,42): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(362,54): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(362,25): error CS0518: Predefined type 'System.String' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(363,42): error CS0518: Predefined type 'System.String' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(363,56): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(363,71): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(363,90): error CS0518: Predefined type 'System.UInt16' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]
  Saves\SAV3XD.cs(363,25): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(20,39): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(21,40): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(22,40): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(24,26): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(25,26): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(26,26): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(27,26): error CS0518: Predefined type 'System.Object' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(28,26): error CS0518: Predefined type 'System.Object' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(30,26): error CS0518: Predefined type 'System.UInt16' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(31,26): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(32,26): error CS0518: Predefined type 'System.Int32' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(33,26): error CS0518: Predefined type 'System.Object' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(35,23): error CS0518: Predefined type 'System.Byte' is not de
fined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.cs
proj]
  Saves\SAV3XD.cs(35,36): error CS0518: Predefined type 'System.Object' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(35,9): error CS0518: Predefined type 'System.Void' is not def
ined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.csp
roj]
  Saves\SAV3XD.cs(36,23): error CS0518: Predefined type 'System.Byte' is not de
fined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.cs
proj]
  Saves\SAV3XD.cs(36,9): error CS0518: Predefined type 'System.Void' is not def
ined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.csp
roj]
  Saves\SAV3XD.cs(121,26): error CS0518: Predefined type 'System.Byte' is not d
efined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.c
sproj]
  Saves\SAV3XD.cs(363,87): error CS0518: Predefined type 'System.Int32' is not
defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.
csproj]
  Saves\SAV3XD.cs(363,107): error CS0518: Predefined type 'System.Int32' is not
 defined or imported [C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core
.csproj]


"C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.sln" (default target) (1) ->
"C:\Users\Nacor\Desktop\PKHeX-master\Tests\PKHeX.Tests\PKHeX.Tests.csproj" (def
ault target) (2) ->
"C:\Users\Nacor\Desktop\PKHeX-master\PKHeX.Core\PKHeX.Core.csproj" (default tar
get) (3:2) ->
(GenerateBuildDependencyFile target) ->
  C:\Program Files\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microso
ft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Assets file 'C:\Users
\Nacor\Desktop\PKHeX-master\PKHeX.Core\obj\project.assets.json' not found. Run
a NuGet package restore to generate this file. [C:\Users\Nacor\Desktop\PKHeX-ma
ster\PKHeX.Core\PKHeX.Core.csproj]

    0 Warning(s)
    13468 Error(s)

Time Elapsed 00:00:24.10

C:\Users\Nacor\Desktop\PKHeX-master>

Can someone help fix this mess? I don't understand why switching to VS 2017 when with 2015 everything was working okay and build were easily made...

**Comment by kwsch** [comment]
c# 7 is only supported by vs2017; make sure you have all the applicable .net frameworks installed. Those system types are common .NET libraries, not PKHeX.

**Comment by Gliscor** [comment]
I think i found a work around, i opened the PKHeX.sln file with Visual Studio 2017 Enterprise and clicked: Build > build solution and it compiled without problems, i don't know if it includes the latest commit since it says 2017/05/30...

**Comment by kwsch** [comment]
version string only updates every time I post a new release to the forums

**Comment by evandixon** [comment]
Msbuild failed because of missing NuGet packages. The VS build worked because it automatically restored them.
