### ISSUE TITLE
[Bug] False fishy flag for Gen 3 Eggs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1248]
Eggs are hatched at Lv. 5. It should not include "Fishy: All EVs are zero, but leveled above Met Level."
![image](https://user-images.githubusercontent.com/17801814/27267850-6a49333a-5479-11e7-8af7-c6a01e45e7ec.png)

Edit: this also happens when the Egg is hatched.
![image](https://user-images.githubusercontent.com/17801814/27268039-eaff4ed2-547a-11e7-89b8-a5b46c18f8df.png)

**Comment by sora10pls** [comment]
And while I'm here, PKHeX doesn't flag Eggs that don't have the nickname "タマゴ".
![image](https://user-images.githubusercontent.com/17801814/27267912-c4ded44e-5479-11e7-950e-581ea7e2e394.png)

**Comment by kwsch** [comment]
Eggs auto-fix themselves prior to going into the Legality check routine; set it to slots then view :)
