### ISSUE TITLE
In-Game Trade Documentation [OT, TID, SID, PID]

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1249]
As the issue title says. This should work like the Gen 1 in-game trade OT checks function, and can use the exact same legality strings (V10 = invalid, V11 = valid). Can't say the same for any other in-game trades for other games, since I'm currently only running LeafGreen for testing.

![image](https://user-images.githubusercontent.com/17801814/27270006-33dedad8-5489-11e7-924b-5d1d6c3b875f.png)

**Comment by kwsch** [comment]
PID/OT details aren't readily available on the internet, and would require a bit of work to get documented.

**Comment by ReignOfComputer** [comment]
https://github.com/ReignOfComputer/RoCs-PC/tree/master/06%20-%20Gen%20III%20-%20FRLG%20Collection/Pokemon%20Fire%20Red/In-game%20Trades

If this helps :P

**Comment by sora10pls** [comment]
Lmao there are more in-game trades than I thought there were. So far I have documentation on 4 species (minus for Japanese/Korean games), will try to get more added to [this](https://pastebin.com/WbDykr2m) tomorrow when I'm not sleep deprived.

**Comment by javierhimura** [comment]
I look how to extract this data directly from the rom files, to avoid having to play all games in all languages to gather the information.
I found code in the program Universal Pokemon Randomizer prepared just for that, extract the names of traded pokemon, Is in Java, i started to adapt the code from the getIngameTrades functions to .NET to extract the data, but i do not have much time lately to complet it
https://github.com/Dabomstew/universal-pokemon-randomizer

**Comment by sora10pls** [comment]
Static Info Pastebin updated to list all TIDs/SIDs/PIDs; will work on getting language-specific OT Names and Nicknames.

**Comment by sora10pls** [comment]
Now all we're missing is Korean! @kwsch

**Comment by sora10pls** [comment]
Turns out there's another bug with the in-game trade Lickitung. PKHeX deems the English in-game trade legal, however in all other languages, it tries to match the Lickitung up with an Event rather than the in-game trade.

English:
![image](https://user-images.githubusercontent.com/17801814/27293413-5a53619c-54e4-11e7-8bf0-492d06a353e8.png)
Other languages:
![image](https://user-images.githubusercontent.com/17801814/27293392-4c8ae242-54e4-11e7-8376-6f836649fdfb.png)

**Comment by kwsch** [comment]
@sora10pls That's how the encounter generator works, it will stop generating encounters once a valid-enough match is found. In this case it stops at the Wish Lickitung Egg.

https://github.com/kwsch/PKHeX/blob/b4222c756a278d3ddcb568cca5c7283045a47971/PKHeX.Core/Legality/Encounters/EncounterGenerator.cs#L259-L285

Gifts -> Static -> FriendSafari(will remove) -> Wild -> Trade

Trades from Gen3/4 are difficult to match; when OT/ID/PID/IV info is added it will be possible to get a precise match. When this new matching info is added, we can probably prioritize generating ingame trades above gifts.

**Comment by kwsch** [comment]
With the Persian/Meowth example from yesterday, I think this ability portion is fixed.

So it just remains that the OT/PID isn't checked; will probably need a dictionary for all associated games (gen3/4), gen5 can be decided later.

**Comment by FlapjacksNsyrup** [comment]
https://bulbapedia.bulbagarden.net/wiki/In-game_trade#FireRed_and_LeafGreen

I'd assume the information on here should be accurate, no? It would save time having to play the games just to get the trades. Is there information you need that isn't present on that page?

**Comment by sora10pls** [comment]
Check my Pastebins above. That information only lists English/Japanese, and also doesn't display PID or SID. I've already gathered the information needed for FR/LG.

**Comment by sora10pls** [comment]
Gonna bump this since to this day I've only done FR/LG. What all else needs to be obtained for this to be resolved? I'm gonna assume it's:

- RSE trades
- DPPt/HGSS trades
- OT/TID/SID/PID for all trades

If it's anything like FR/LG, the only differing thing would be OT (rest are static).

**Comment by sora10pls** [comment]
In any case... onto Gen 4!

Static Info (All Languages): https://pastebin.com/Vfym14j5
OTs will be posted periodically as I get the chance to.

Compared to Gen 3, this will take time since some are time-based (ie, having required Gym Leader rematches and the NDS punishing you for changing internal clock -> 24hr time freeze).

**Comment by kwsch** [comment]
>not using DeSmuME and using the record movie function to provide a startup date

**Comment by sora10pls** [comment]
I didn't know you could do that! But in the end it doesn't even matter, since I forgot that changing the NDS clock only affects getting Blue's number, which isn't needed for HGSS in-game trades. All it *really* comes down to is when I have the time and motivation to grind out these trades in several languages other than English.

**Comment by kwsch** [comment]
>not looking up a static PIDs in the ROM to find the ingame trade data

**Comment by sora10pls** [comment]
leave me alone lmao

I'll get to it some time tomorrow after work.

**Comment by kwsch** [comment]
Magneton: 0000D136
Pikachu: 00485876
Rhyhorn: 0012971C
Steelix: 00101596

ps: RoC's PC has a lot of ingame trades, and having a huge bank of savefiles makes searching for TID/SID pairs easy ;)

**Comment by sora10pls** [comment]
Updated the Pastebin with those PIDs. And yeah that's how I've been managing it, even with FR/LG (which is done).

A base save file with all the PKMs needed for the trade, copied around to match the different game language (ROMs for FRE, GER, ITA, etc.), then from there it's just grabbing the OTs. English/Japanese OTs are on Bulbapedia, the only real task is getting the rest of the languages.

Out of curiosity, how would I go about searching for the data in the ROM using the PIDs?

**Comment by kwsch** [comment]
convert 32bit val back to bytes (or just look at the pkm data); then find which narc has those bytes.

NDS narcs are essentially equivalent to 3DS's garcs

there's also:
http://hackromtools.altervista.org/ds-trade-editor/

not sure if the PID is stored but I'd bet it is.

see also:
https://bulbapedia.bulbagarden.net/wiki/User:SnorlaxMonster/In-game_trades_in_other_languages

**Comment by sora10pls** [comment]
That last Bulbapedia article you linked is exactly what I needed.

Here's a 100% complete Pastebin with TIDs and PIDs: https://pastebin.com/Dk2HrxTZ

Click [here](https://bulbapedia.bulbagarden.net/wiki/User:SnorlaxMonster/In-game_trades_in_other_languages#Nicknames) for Nicknames in all languages.
Click [here](https://bulbapedia.bulbagarden.net/wiki/User:SnorlaxMonster/In-game_trades_in_other_languages#Original_Trainer) for Original Trainer names in all languages.
