### ISSUE TITLE
Invalid: OT Memory: X/Y exclusive memory on OR/AS origin.

### ISSUE THREAD

**Issue by sutiam** [kwsch/PKHeX#125]
![pk2](https://cloud.githubusercontent.com/assets/1111903/16275708/09f319dc-3860-11e6-91de-9a56dc2f9d15.JPG)
![pk1](https://cloud.githubusercontent.com/assets/1111903/16275721/1f4f6614-3860-11e6-82e9-5a4731a314fe.JPG)

Guys, can you help me out? Not sure what this invalid message means for my **Mashtomp**, he's my starter, and I never ever edited its info. on PKHex.

PS: I'm playing on AS, btw.

**Comment by sutiam** [comment]
**Update:**

Even though *PKHex* says it's invalid, I saved it anyway and everything seem to load just fine in the game, hmmm... wonder if it'll cause problem later on.

**Comment by kwsch** [comment]
Thanks for reporting, was a false positive in PKHeX.

The official checks don't bother checking memories, so you'd be fine even if PKHeX was right :+1:
