### ISSUE TITLE
Ribbon legality checks

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1250]
Most of the ribbons have missing or incomplete legality checks, so I've taken the liberty of compiling a list of requirements for the remaining ones. Hopefully I didn't miss anything:

- [x] **Kalos Champion:** Must be native to gen 3-6. If native to ORAS, must have non-OT handler data. If the memory "{0} battled at {1}'s side and defeated the Champion" is present, either this ribbon or the Hoenn Champion (ORAS) Ribbon must also be present.
- [x] **Best Friends:** If non-OT handler data isn't present, must have 255 affection. 
- [x] **Training:** Must be native to gen 3-6 and have all available Super Training medals.
- [x] **Skillful Battler/Expert Battler:** Must be native to gen 3-6 and be allowed in battle facilities. If the memory "{0} battled at {1}'s side and defeated a Battle Chatelaine" is present, at least one of these ribbons must also be present.
- [x] **Alert/Shock/Downcast/Careless/Relax/Snooze/Smile:** Must be native to gen 3-6.
- [x] **Gorgeous/Royal/Gorgeous Royal:** Must be native to gen 3-6. If native to XY, must have non-OT handler data.
- [x] **Footprint:** If native to gen 6 or 7, current level must be at least 30 levels higher than met level.
- [x] **Artist:** Must be native to gen 3. In gen 3-5, must have at least one gen 3 Master Rank Contest Ribbon. In gen 6 or 7, must have at least 4 Contest Memory Ribbons.
- [x] **Hoenn Champion (ORAS):** Must be native to gen 3-6. If native to XY, must have non-OT handler data.
- [x] **Contest Star**: Must be native to gen 3-6 and have all ORAS Contest Ribbons.
- [x] **ORAS Contest Ribbons:** Must be native to gen 3-6. If native to XY, must have non-OT handler data.
- [x] **Battle Royal Champion/Battle Tree Great/Battle Tree Master:** Must be allowed in battle facilities.
- [x] **Contest Memory:** Must be native to gen 3 or 4. If native to gen 4, can't have more than 20 Contest Memory Ribbons. Ditto and Unown can't have any Contest Memory Ribbons if native to gen 4, or more than 20 Contest Memory Ribbons if native to gen 3.
- [x] **Battle Memory:** Must be native to gen 3 or 4 and be allowed in battle facilities. If native to gen 4, can't have more than 6 Battle Memory Ribbons.
- [x] **Gen 3 Contest Ribbons**: Must be native to gen 3. Can't have a ribbon for a certain rank without the ribbons for all lower ranks in the same category.
- [x] **Gen 4 Contest Ribbons**: Can't have a ribbon for a certain rank without the ribbons for all lower ranks in the same category. Ditto and Unown can't have any gen 4 Contest Ribbons.
- [x] **Gen 3 Battle Ribbons:** Must be native to gen 3 and be allowed in battle facilities.
- [x] **Gen 4 Battle Ribbons:** Must be allowed in battle facilities.
- [x] Additionally, Pokemon native to gen 5 can't have any non-event ribbons in gen 5.

Also, kind of a minor nitpick but my OCD won't let it slide; the following ribbons should be relabeled with their correct in-game names:

- RibbonChampionAlola -> Alola Champion
- RibbonBattleRoyale -> Battle Royal Champion
- RibbonBattleTreeGreat -> Battle Tree Great
- RibbonBattleTreeMaster -> Battle Tree Master
- Past Contest Ribbons -> Contest Memory
- Past Battle Ribbons -> Battle Memory

Lastly, the following ribbons have different names (and in some cases different icons) in gen 3 and 4. I'm not sure it's even worth changing them just for those two gens since they're not legitimately available anyway, but I like to be thorough:

- Event -> History (same icon)
- Birthday -> Green ![green_ribbon](https://user-images.githubusercontent.com/23516075/27269853-a8eab0a4-547f-11e7-80c1-dc649b212c6b.png)
- Special -> Blue ![blue_ribbon](https://user-images.githubusercontent.com/23516075/27269826-85b34948-547f-11e7-8cad-c3133b9b957f.png)
- Souvenir -> Festival (same icon)
- Wishing -> Carnival (same icon)
- Battle Champion -> Marine ![marine_ribbon](https://user-images.githubusercontent.com/23516075/27269763-0430a2e4-547f-11e7-92e3-15691df814fe.png)
- Regional Champion -> Land ![land_ribbon](https://user-images.githubusercontent.com/23516075/27269780-30db5a1e-547f-11e7-99d4-f51ab74e382a.png)
- National Champion -> Sky ![sky_ribbon](https://user-images.githubusercontent.com/23516075/27269793-492e2ccc-547f-11e7-8fa2-4560cc77a5ae.png)
- World Champion -> Red ![red_ribbon](https://user-images.githubusercontent.com/23516075/27269806-61f46794-547f-11e7-8229-1ba4a2453ccf.png)

**Comment by sora10pls** [comment]
I know this is a WIP, but...

My legit Talonflame gets the following legality error, despite it having the Footprint Ribbon:
![image](https://user-images.githubusercontent.com/17801814/27398821-f8262d50-5688-11e7-8ba6-b4ba6b2a9ae8.png)

Same happens with my legit Decidueye (starter from Moon):
![image](https://user-images.githubusercontent.com/17801814/27398937-49789bde-5689-11e7-845f-54807266e839.png)

Oddly enough, if the Footprint Ribbon is removed, the error goes away.

**Comment by sora10pls** [comment]
Also, [here in this Pastebin](https://pastebin.com/CgbR5WFq) are those renamed Ribbons (including translations to save you some trouble) that @White-Canary mentioned in the second portion of the original post. These were ripped directly from pk3DS, so they're all the official translations. :)
