### ISSUE TITLE
Blank Error

### ISSUE THREAD

**Issue by ObscenityIB** [kwsch/PKHeX#1251]
Is it just me? I just built commit `b4222c756a278d3ddcb568cca5c7283045a47971` and its giving me a blank error box,  also illegal mode doesn't seem to work and also shows the blank error.

The compilation succeeded with no errors, this is just starting the program.

![image](https://user-images.githubusercontent.com/6983255/27303260-98d4587e-557d-11e7-9e70-4b47c5b08426.png)

**Comment by kwsch** [comment]
Have you tried debugging or pressing OK?

**Comment by sora10pls** [comment]
Running via command line argument still gives me a blank error on latest commit. Just loading regular PKHeX is fine though.

**Comment by kwsch** [comment]
Does the program still launch correctly?

I can try this later, but maybe overwriting the args to force hax on load -> pause after the error message -> resume -> find what is generating the error message.

**Comment by sora10pls** [comment]
Yeah, clicking OK runs it no problem (as far as I can tell).

**Comment by ObscenityIB** [comment]
I didn't want to use the program in case the error was meant to be important and would corrupt saves, but yeah if its nothing ill just go ahead and ignore it, and i didn't know there was a command line arg for it, do now, and it works.

**Comment by kwsch** [comment]
Weird, I can't replicate it on my end.

```
start pkhex hax
exit 0
```
works4me

**Comment by sora10pls** [comment]
So building from source has this happen in both regular PKHeX and PKHaX, though it only occurs with PKHaX if I'm using automated TeamCity builds. 🤔

**Comment by ReignOfComputer** [comment]
Figured out the blank error.

1. Open PKHeX with microSD card - save automatically loaded
2. Remove microSD card
3. Reopen PKHeX
