### ISSUE TITLE
Pokemon Gale of Darkness PID Generation

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1252]
So I keep getting this error every time I change the IVs or nature of a Pokemon from XD Gale of Darkness, and rerolling won't fix the issue. Are PIDs in XD locked? 
Thank you for taking the time to read this!

Invalid: Encounter Type PID mismatch.
===

Valid Move 1: Learned by TM/HM in Generation 4.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Move 4: Special Non-Relearn Move.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Valid: Valid gift/static encounter.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Special ingame Fateful Encounter.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: History block is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Static Encounter (Articuno)
PID Type: None

**Comment by sora10pls** [comment]
#1240

**Comment by greenDarkness** [comment]
Oh, I see. Thank you!

**Comment by greenDarkness** [comment]
So, is there currently any plans to include a PID Generator for PKHeX?

**Comment by sora10pls** [comment]
Wouldn't be too sure of that, though I am sure it'd require a lot of work. RNGReporter works well and gets the job done, though! Simply generate a PID with the IVs and Nature of the Pokemon in question, and re-enter the generated PID (outputted in decimal) into PKHeX's PKM Editor.

**Comment by greenDarkness** [comment]
I don't suppose you know where I can get my hands on the program by chance? I found a link for 9.95, but I don't think it's the newest version. Does Pokegen do that?

**Comment by sora10pls** [comment]
[Here's](https://github.com/kwsch/PKHeX/files/1086619/RNGReporter.zip) a download for 10.1.9. Not 100% sure if it's latest, but it's much more recent than 9.95.

**Comment by Gliscor** [comment]
@sora10pls How do i gen a PID with RNGReporter? I don't see a "PID Generation" tool for XD/Colosseum, have version 10.1.9. I'm trying to export a purified Lugia from XD to Moon, but everytime i change the Nature, IV's, Held item, EV's, i get the "Invalid: Encounter Type PID mismatch" error. I've attached the .pkm file
[XD 81 - Lugia.zip](https://github.com/kwsch/PKHeX/files/1101405/XD.81.-.Lugia.zip)

**Comment by sora10pls** [comment]
4th Gen Tools -> Generate PID from IVs -> Wait until you find a PID with Method "Colosseum/XD"
