### ISSUE TITLE
Egg-Related Bug Reports

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1257]
#### Bug 1: Manaphy Egg false fishy flags
Manaphy from the Pokemon Ranger Manaphy Egg hatches at Lv. 1, the first two fishy checks should not be there. Unsure if this applies to other Events.
![image](https://user-images.githubusercontent.com/17801814/27368018-25182374-561e-11e7-9322-e95c34ed9447.png)

#### Bug 2: Eggs and Hatched Pokemon cannot be Lv. 0 (FIXED)
Happens with multiple save formats. Example pics below are Gen 4.
![image](https://user-images.githubusercontent.com/17801814/27368684-f140d466-5621-11e7-8e83-6b0db733b653.png)
![image](https://user-images.githubusercontent.com/17801814/27367996-00d46586-561e-11e7-830a-cbcd8308c432.png)

#### Bug 3: Eggs cannot hold Items (FIXED)
Self-explanatory.
![image](https://user-images.githubusercontent.com/17801814/27368096-a2f1f180-561e-11e7-879d-de299fef81a5.png)

#### Bug 4: Egg Met Level inconsistency
Should be 0 for Gens 3/4, should be 1 for Gens 5+.
Note: Gens 3/4 properly detect an invalid Met Level.
![image](https://user-images.githubusercontent.com/17801814/27368166-fea99f1e-561e-11e7-8d6a-3b8ad7eeacca.png)

#### Bug 5: Setting Pokemon to "Is Egg" behaviour (FIXED)
- Nickname should automatically be set to "タマゴ" in Gen 3, not "EGG"
Note that exporting/importing or dragging/dropping the PKM into another instance of PKHeX properly sets the nickname to "タマゴ"
- Met Location should be set to where the Egg was obtained in Gen 3 (Day Care location)
Thanks @javierhimura!
If the Origin Game is R/S/E, Met Location should be set to "Route 117"
If the Origin Game is FR/LG, Met Location should be set to "Route 5" or "Four Island"
- Nickname checkbox should not automatically be ticked in Gen 4

#### Bug 6: Eggs cannot expend any PP (FIXED)
Thanks @javierhimura!
Note that Tackle's current PP is 34, while the base PP is 35.
![image](https://user-images.githubusercontent.com/17801814/27390578-a55d630e-566f-11e7-9b8e-03066cdf1493.png)

#### Bug 7: Gen 2 Eggs cannot have Pokerus
Only Eggs [from Generation 3 onward](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9rus#Infection) can have Pokerus be spread onto them.
![image](https://user-images.githubusercontent.com/17801814/27391406-e693d374-5671-11e7-9440-bebe5897d714.png)

**Comment by javierhimura** [comment]
Gift egg should not be tge default met locstion for gen 3 eggs. Tha location is only used for togepi and azurill gift eggs.

Normal day care eggs have the met locstion where the day care is located

**Comment by sora10pls** [comment]
Thanks for clarifying. Will edit post. :)

**Comment by javierhimura** [comment]
Another check for eggs.
Just like eggs cant have PPUps they cant expend any PPs, that means current pp values should be equals the default pp from the move.

**Comment by sora10pls** [comment]
Bug with the latest commit: PKHeX things every Egg has a Held Item.
![image](https://user-images.githubusercontent.com/17801814/27390811-43db44e2-5670-11e7-949d-3005d4b8d794.png)

**Comment by kwsch** [comment]
Setting IsEgg won't modify met location, you have to prompt for a suggestion.

**Comment by sora10pls** [comment]
Could that not be done for Gen 3? This is more of a feature request, as when you set "As Egg" in Met information for Gens 4+, it automatically sets the Egg Met Location to its respective Day Care Met Location (ie Day Care Helpers, Nursery Helpers, etc.), and since Gen 3 doesn't have "As Egg" Met Info, it'd be more useful to have the Met Location automatically set when "Is Egg" is checked.

**Comment by sora10pls** [comment]
Another bug with latest commit: Gen 3 nickname checkbox should be ticked if the Pokemon is in an Egg. This is properly checked for with Gen 5+, with the invalid legality statement "Invalid: Egg must be nicknamed." (legality string V12).
![image](https://user-images.githubusercontent.com/17801814/27396796-3c856fd0-5682-11e7-93b1-6858473c8751.png)

**Comment by sora10pls** [comment]
Regarding Gen 2 Eggs and Pokerus...

1. Latest commit did not fix the Gen 2 Pokerus check
![image](https://user-images.githubusercontent.com/17801814/27397240-a8f320da-5683-11e7-86c9-de3129a241d7.png)

2. Egg/Pokerus legality string is false
"V368 = Eggs can not be infected with Pokérus."

Eggs *can* be infected with Pokerus, however only in Gen 3 onward (refer to the Bulbapedia hyperlink reference in Bug 7 of original post). This should be revised to say "Eggs can not be infected with Pokérus in Gen 2."

**Comment by sora10pls** [comment]
Another thing: Eggs *can* be in the first Party slot.

In-game proof:
![03 - platinum__21170](https://user-images.githubusercontent.com/17801814/27397975-311e608a-5686-11e7-9aa1-c4d0214e88b5.png)

PKHeX allows for it to be dragged/dropped onto the slot, but does not allow for it to manually be set (Right-click slot -> Set). If it is, the following is outputted:
![image](https://user-images.githubusercontent.com/17801814/27398004-4ccebe74-5686-11e7-8d39-5352addffde5.png)

**Comment by kwsch** [comment]
That's just a lazy check from pre-abstract SaveFile class days; the goal was to make it difficult to only have eggs in the party.

I'll probably end up removing the check and instead add a Export prompt triggered by the following:
```
public bool IsPartyAllEggs => HasParty && PartyData.All(z => z.IsEgg);
```

```
Party data is only eggs. 
Continue exporting?
```

**Comment by kwsch** [comment]
Should notice that pkrs in gen2 isn't being loaded or saved ;)

**Comment by sora10pls** [comment]
Side-effect from a1b66ab: now all PK3/PK4 Eggs have false fishy checks. They're a unique case because Eggs in 3/4 are required to have Met Level 0.
![image](https://user-images.githubusercontent.com/17801814/27452418-78a44aca-5760-11e7-9174-d858a2005ba2.png)
![image](https://user-images.githubusercontent.com/17801814/27452353-480750d8-5760-11e7-939a-80ee3f78f15f.png)

**Comment by sora10pls** [comment]
Thanks a ton!
