### ISSUE TITLE
[Bug] Post-National Dex Great Marsh Drapion with false fishy flags

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1259]
Edit: Lmfao it would've been great if I didn't accidentally hit enter too quick to submit the issue and not write anything about it.

Drapion just caught from the Post-National Dex Great Marsh encounter tables, PKHeX thinks it being met at Lv. 28 and being Lv. 28 is fishy.

![image](https://user-images.githubusercontent.com/17801814/27402084-712bbaf8-5693-11e7-8058-ff21592021db.png)
![image](https://user-images.githubusercontent.com/17801814/27402195-cd070a8a-5693-11e7-93c3-1fe6b0ce3cfa.png)
![image](https://user-images.githubusercontent.com/17801814/27402067-63c348cc-5693-11e7-9397-f0c80c1c14c5.png)

**Comment by kwsch** [comment]
tfw no pkm file

**Comment by sora10pls** [comment]
[452 - DRAPION - BA728BF01B12.zip](https://github.com/kwsch/PKHeX/files/1093416/452.-.DRAPION.-.BA728BF01B12.zip)

**Comment by sora10pls** [comment]
May have found a fix for this, will push a pull request in just a sec.
