### ISSUE TITLE
[Feature Request] Add Current Poketch App ComboBox to Gen 4 Misc Editor

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1260]
**Edit:** I'm dumb and didn't even realize that there already is a Poketch App editor/unlocker in PKHeX. However, the second part of my initial request still stands: a Current Poketch App ComboBox similar to PokeSAV's.
![image](https://user-images.githubusercontent.com/17801814/27405483-b3eecf40-569f-11e7-8d20-c54a2f445767.png)

- Current Poketch App: `0x1162`
Current Poketch App ranges from `0x00` (Digital Watch) to `0x18` (Alarm Clock)
Reference: https://pastebin.com/FLGEqrXs

**Comment by kwsch** [comment]
Isn't this already partially covered via the Misc editor for Gen4?

**Comment by sora10pls** [comment]
Wow it is. Note to self: look before requesting.
