### ISSUE TITLE
[Bug] Current Poketch App causes save data corruption

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1263]
- Editing current app corrupts save data and has the game load "the most recent save data"
- There is no "None" for current app; `0x00` is Digital Watch, not no app at all
![image](https://user-images.githubusercontent.com/17801814/27447973-02a4c336-5751-11e7-810b-541922b0b427.png)

Perhaps there's a checksum for this? I'd suspect `0x1160` but I could be wrong.

**Comment by kwsch** [comment]
try checking pokesav to see how values are changed

**Comment by sora10pls** [comment]
Before:
Offset `0x1162` == `0x06` (Dowsing Machine; App 7)
Offset `0xCF2A` == `0x6A`
Offset `0xCF2B` == `0x8E`

After:
Offset `0x1162` == `0x05` (Friendship Checker; App 6)
Offset `0xCF2A` == `0x61`
Offset `0xCF2B` == `0xC1`

**Comment by sora10pls** [comment]
This may be useful reference: https://projectpokemon.org/wiki/Pok%C3%A9mon_NDS_Save_File_Checksum#Platinum_usage

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/427eb268e178a95e02c076c0afcc7876b51f4a01/PKHeX.Core/Saves/SAV4.cs#L74-L75

says it does a checksum 0x0000-0xCF18 and sets it to 0xCF2A

no idea why it didn't update on export...?

**Comment by sora10pls** [comment]
After more testing, seems as if checksum is done for .sav, but not .dsv

**Comment by sora10pls** [comment]
Okay, so I just did yet another test and when giving my save file all Poketch Apps, instead of updating the checksum at `0xCF2A`, it updated it at `0x4CF2A` and the save file loaded fine?

I assume that's the checksum for the backup save.

**Comment by sora10pls** [comment]
OKAY forget everything mentioned before, turns out it was just some bug with the save file itself. After re-saving in game, the checksum began to properly get updated with PKHeX.

Only thing left to change is the fact that there is no "None" option for Current App.

**Comment by sora10pls** [comment]
Yeah for some reason this keeps happening and then not happening, it's hard to fully replicate all the time.

**Comment by kwsch** [comment]
Removed the "None" dropdown option so it now correlates directly; feel free to close if this ghostly issue isn't reproducable.

**Comment by sora10pls** [comment]
Yeah I'm not too sure about this one, I'll go ahead and close.
