### ISSUE TITLE
[Feature Idea] Instant Item Collect

### ISSUE THREAD

**Issue by ewormPL** [kwsch/PKHeX#1264]
Just gonna throw it out there - it'd be neat if we could move all items held by Pokémon in the boxes (and perhaps the party) to the bag with a single click. Just like what putting the Pokémon in the Pokémon Bank does, except without having to do that (especially important for generations prior to six, which can't be brought back from the Bank to the game).

**Comment by kwsch** [comment]
Since PKHeX can fabricate items out of thin air, is there any point to interacting with the bag?

Clearing all held items is pretty easy to do by using the core api (get boxdata, iterate and set pkm.HeldItem=0, set boxdata)
