### ISSUE TITLE
[Bug] 3 different file import bugs

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#127]
Just throwing both of these in 1 issue.

---
1: Importing gen5 file gives an error
---
This previously worked but when I now try to import a generation 5 `.sav` pkhex gives the following error:

```
Unable to load file.

Sytem.IndexOutOfRangeException: Index was outside of the bounds of the array.
    at PKHeX.SAV5.get_Game()
    at PKHeX.SAV5.get_Version()
    at PKHeX.SAV5.ctor(Byte[] data, GameVersion versionOverride)
    at PKHeX.SaveUtil.getVariantSAV(Byte[] data)
    at PKHeX.Main.openSAV(Byte[] input, String path)
    at PKHeX.Main.openFile(Byte[] input, String path, String ext)
    at PKHeX.Main.openQuick(String path, Boolean force)
```

[Save for further testing](https://github.com/kwsch/PKHeX/files/339663/Pokemon.Black.2.zip)

---
2 - Importing a Save Box Data++ file
---

```
Unable to load file.

System.IndexOutOfRangException: Index was outside of the bounds of the ara.
    at PKHeX.SaveFile.setPCBin(Byte[] data)
    at PKHeX.Main.openFile(Byte[] input, String path, String ext)
    at PKHeX.Main.openQuick(String path, Boolean force)
```

Clicking `ok` then gives the error `Null input. Aborting.`

[Box Data file for testing](https://github.com/kwsch/PKHeX/files/339665/AS-BOX-DATA-AS-OFF-290602016.zip)

---
3 - When the directory path has a space importing a Main file sometimes fails
---

Yeah.. sometimes.. I sadly cannot consistently replicate this issue but every so often I notice this. Generally it does actually load which is weird but before it does that it gives a `Null input. Aborting.` error. What I do notice is that this more consistently happens when ***dragging*** the main file to the pkhex window as opposed to going to File->Open

**Comment by kwsch** [comment]
1: https://github.com/kwsch/PKHeX/commit/a0bade7dc0d8738f4e67fc945e5a892f4ab09a7a
2: https://github.com/kwsch/PKHeX/commit/c14b87fcd93545c3976f565a7db55f3d6d60cc06
3: https://github.com/kwsch/PKHeX/commit/d8ed96fd698b0a315f130bcbb88691d1d4c653b1
