### ISSUE TITLE
Build 3459 Illegal Mode Bag

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1270]
In the 3459 build of PKHeX, using PKHaX illegal mode removes items that you aren't supposed to have from the bag in Fire Red. If there is any way this change could be reinstated I would be very grateful. 
Thank you for taking time to read this!

**Comment by kwsch** [comment]
Works fine.

[The message only appears if you are using HeX](https://github.com/kwsch/PKHeX/blob/b339ddef0228f28365fa4faac58996010c554f67/PKHeX.WinForms/Subforms/Save%20Editors/SAV_Inventory.cs#L159-L166).

**Comment by greenDarkness** [comment]
The only thing that needs to be done to trigger illegal mode is change the 'e' to an 'a' in PKHeX, right?
Was the, "Please behave." Message removed?

**Comment by kwsch** [comment]
No, it's a command line argument.
You can tell if you're in HaX if the program title says PKHaX.

**Comment by greenDarkness** [comment]
Oh, I see.
I renamed 'PKHeX' to 'PKHaX' but I can't seem to launch illegal mode. 
![image](https://user-images.githubusercontent.com/15519892/27513463-ea4d7f54-5934-11e7-9342-49f3564570d8.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/pull/1138

**Comment by greenDarkness** [comment]
So, I saw in the other thread where you instructed someone to make a bat file. I did the same and it's working fine for me.
Thanks for the help!
