### ISSUE TITLE
[Feature Request] Generation-Specific Labels/Buttons

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1272]
Small feature request, change some text in the PKM Editor to fit the current format.

If <= Gen 5, Contest Stat is "Smart".
If >= Gen 6, Contest Stat is "Clever".

If <= Gen 2, they are DVs and Stat EXP.
If >= Gen 3, they are IVs and EVs.
The above 2 would affect both Labels and Buttons (randomize buttons).

**Comment by kwsch** [comment]
For DV/Stat EXP, im not going to account for that in the interface.
http://www.smogon.com/smog/issue28/evs_ivs

>Back in Generation I and II, competitive Pokémon wasn't that extended and most of us ignored the existence of these stat-determining values that are nowadays known to all competitive players: **Stat Experience, now known as Effort Values or EVs**, and **Determinant Values or DVs, now known as Individual Values or IVs**.

**Comment by sora10pls** [comment]
Figured I would ask just in case. Thanks!
