### ISSUE TITLE
Moltres french name

### ISSUE THREAD

**Issue by Pierrounator** [kwsch/PKHeX#1274]
I tried to edit a Moltres to make it french but I've an error.
Moltres in french is Sulfura

"Nickname too long" without the nickname box checked.
And if I put "Sulfuraaa" it works...

Same error for FRE, GER and ITA (other languages work)

The PK file : https://uploadfiles.io/wkn2q

**Comment by evandixon** [comment]
https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Checks.cs#L157

I suspect the language in that check isn't supposed to be `2`.

**Comment by kwsch** [comment]
How does the language value get set when transferring to pokebank?

I'm wondering if it's possible to transfer something from an english game (nicknamed to 10 characters) to a Japanese pokebank, yielding a JP language val with 10 characters of text.

Thoughts?

**Comment by Pierrounator** [comment]
I often did it and I never had this error. Maybe it's because of the Gen1?

**Comment by kamronbatman** [comment]
IIRC, language is set by the VC language you are transferring from.
