### ISSUE TITLE
Ribbon Legality Issues 2: Pikachu Boogaloo

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1276]
Since the last attempt to address ribbon legality issues seems to have broken far more than it fixed, I've taken the liberty of checking every conceivable ribbon legality scenario for every PKX format in every single generation and compiling what I hope is an exhaustive list of the remaining issues (I'm sure I must've overlooked something, but it's enough for now). Some of the checks are correctly applied in certain gens but may be applied only partially or not at all in other gens, I figured it would be best to list each gen separately.

## GEN 3
No problems here as far as I can tell. 👍 

## GEN 4
- **Ability/Great Ability/Double Ability/Multi Ability/Pair Ability/World Ability**
Should be flagged invalid on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys, Dialga, Palkia, Giratina, Phione, Manaphy, Darkrai, Shaymin, and Arceus.
- **Contest Ribbons**
Should be flagged invalid if any lower-rank Contest ribbons in the same category are missing.
- **Hoenn Champion (RSE)**
Should be flagged invalid on Pokemon native to gen 4.
- **Artist**
Should be flagged invalid on Pokemon without at least one gen 3 Master Rank Contest ribbon.

## GEN 5
- **Sinnoh Champion**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Ability/Great Ability/Double Ability/Multi Ability/Pair Ability/World Ability**
Should be flagged invalid on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys, Dialga, Palkia, Giratina, Phione, Manaphy, Darkrai, Shaymin, and Arceus. Should NOT be flagged on Pokemon native to gen 3.
- **Alert/Shock/Downcast/Careless/Relax/Snooze/Smile**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Gorgeous/Royal/Gorgeous Royal**
Should NOT be flagged on Pokemon native to gen 3 and 4.
- **Footprint**
Should be flagged invalid on Pokemon native to gen 5.
- **Legend**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Contest Ribbons**
Should be flagged invalid if any lower-rank ribbons in the same Contest category are missing.
- **Winning/Victory**
Should be flagged invalid on Pokemon native to gen 4 and 5, and on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, and Deoxys.
- **Artist**
Should NOT be flagged invalid on Pokemon native to gen 3 if they have at least one gen 3 Master Rank Contest Ribbon.
- **Effort**
Should be flagged invalid on Pokemon native to gen 5.

## GEN 6
- **Sinnoh Champion**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Best Friends**
Legality analysis should say _"Invalid Ribbon"_ (not _"Missing Ribbon"_) if affection is less than 255 and non-OT handler data is missing.
- **Training**
Should be flagged invalid on Pokemon without all available Super Training Medals (i.e. all except the unreleased distribution ones). Currently only the Rank 1 and 2 medals are checked for Pokemon native to gen 3-5, and none are checked for Pokemon native to gen 6.
- **Skillful Battler/Expert Battler**
Should be flagged invalid on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys, Dialga, Palkia, Giratina, Phione, Manaphy, Darkrai, Shaymin, Arceus, Victini, Reshiram, Zekrom, Kyurem, Keldeo, Meloetta, Genesect, Xerneas, Yveltal, Zygarde, Diancie, Hoopa, and Volcanion.
- **Alert/Shock/Downcast/Careless/Relax/Snooze/Smile**
Should NOT be flagged invalid on Pokemon native to gen 3 and 6.
- **Artist**
Should NOT be flagged invalid on Pokemon native to gen 3 if they have at least four Contest Memory Ribbons.
- **Footprint**
Should be flagged invalid on Pokemon native to gen 5 unless their current level is at least 30 higher than their met level.
- **Legend**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Contest Star**
Should be flagged invalid on Pokemon native to gen 6 if any of the Contest Master Ribbons are absent. Legality analysis for Pokemon with this ribbon but none of the Contest Master Ribbons should say _"Invalid Ribbon: Contest Star"_ instead of _"Invalid Ribbons: Cooless Master/Beauty Master/Cuteness Master/Cleverness Master/Toughness Master"_.
- **Coolness Master/Beauty Master/Cuteness Master/Cleverness Master/Toughness Master**
Should be flagged invalid on Pokemon native to XY unless they have non-OT handler data.
- **Battle Memory**
Should NOT be flagged invalid Pokemon native to gen 3. Should be flagged invalid on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys, Dialga, Palkia, Giratina, Phione, Manaphy, Darkrai, Shaymin, and Arceus. 

### MISSING RIBBONS
- **Kalos Champion/Hoenn Champion (ORAS)**
If a Pokemon native to XY has the OT memory _"{0} battled by {1}'s side and defeated the Champion"_ and the Kalos Champion Ribbon Ribbon is absent, the legality analysis should say _"Missing Ribbon: Kalos Champion"_. If a Pokemon has the non-OT memory _"{0} battled by {1}'s side and defeated the Champion"_ and neither of these ribbons is present, the legality analysis should say _"Missing Ribbon: Kalos Champion OR Hoenn Champion (ORAS)"_ (currently it seems to check for either ribbon but only flags the Hoenn Champion Ribbon as missing).
- **Skillful Battler/Expert Battler**
If a Pokemon has the memory _"{0} battled by {1}'s side and defeated a Battle Chatelaine"_ and neither of these ribbons is present, the legality analysis should say _"Missing Ribbon: Skillful Battler OR Expert Battler"_ (unless it's a Pokemon not allowed in the Battle Maison). Currently it only checks for Skillful Battler and flags it missing even if Expert Battler is present.
- **Contest Star**
If all of the Contest Master Ribbons are present and the Contest Star Ribbon is absent, the legality analysis should say _"Missing Ribbon: Contest Star"_.

## GEN 7
- **Sinnoh Champion**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Best Friends**
Should NOT be flagged invalid on Pokemon native to gen 1. Should NOT be flagged invalid on Pokemon native to gen 7 unless their affection is less than 255 and they don't have non-OT handler data.
- **Skillful Battler/Expert Battler**
Should be flagged invalid on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys, Dialga, Palkia, Giratina, Phione, Manaphy, Darkrai, Shaymin, Arceus, Victini, Reshiram, Zekrom, Kyurem, Keldeo, Meloetta, Genesect, Xerneas, Yveltal, Zygarde, Diancie, Hoopa, and Volcanion.
- **Alert/Shock/Downcast/Careless/Relax/Snooze/Smile**
Should NOT be flagged invalid on Pokemon native to gen 3 and 6.
- **Gorgeous/Royal/Gorgeous Royal**
Should be flagged invalid on Pokemon native to gen 1.
- **Artist**
Should NOT be flagged invalid on Pokemon native to gen 3 if they have at least four Contest Memory Ribbons.
- **Footprint**
Should be flagged invalid on Pokemon native to gen 1 or 5 unless their current level is at least 30 higher than their met level.
- **Legend**
Should be flagged invalid on Pokemon native to gen 5, not gen 3.
- **Contest Star**
Legality analysis for Pokemon with this ribbon but none of the Contest Master Ribbons should say _"Invalid Ribbon: Contest Star"_ instead of _"Invalid Ribbons: Cooless Master/Beauty Master/Cuteness Master/Cleverness Master/Toughness Master"_.
- **Battle Memory**
Should be flagged invalid on Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys, Dialga, Palkia, Giratina, Phione, Manaphy, Darkrai, Shaymin, and Arceus. 

### MISSING RIBBONS
- **Kalos Champion/Hoenn Champion (ORAS)**
If a Pokemon has the non-OT memory _"{0} battled by {1}'s side and defeated the Champion"_ and neither of these ribbons is present, the legality analysis should say _"Missing Ribbon: Kalos Champion OR Hoenn Champion (ORAS)"_.
- **Skillful Battler/Expert Battler**
If a Pokemon has the memory _"{0} battled by {1}'s side and defeated a Battle Chatelaine"_ and neither of these ribbons is present, the legality analysis should say _"Missing Ribbon: Skillful Battler OR Expert Battler"_ (unless it's a Pokemon not allowed in the Battle Maison). Currently it only checks for Skillful Battler and flags it missing even if Expert Battler is present.

**Comment by kamuisama** [comment]
gen 7 battle tree ribbon is also flagged as invalid..
