### ISSUE TITLE
Pokemon Colosseum/XD Legality issues

### ISSUE THREAD

**Issue by FlapjacksNsyrup** [kwsch/PKHeX#1277]
Hello! I'm brand new here but I've been using PKHeX for a little while now.

I decided to replay both Pokemon Colosseum and Pokemon XD on the Gamecube recently. Upon completion of both, I traded over every single Pokemon from both games into my Emerald game cart.

I went and opened it up in PKHeX so I could transfer some easily into my Sun game and noticed a few things regarding the legality checking for Pokemon originating in these games.

The mistakes I've found are as follows:

- According to PKHeX, all Pokemon snagged in Pokemon Colosseum should have a 'Fateful Encounter' flag. If it's missing, it marks the Pokemon saying, "Invalid: Special ingame Fateful Encounter flag missing." This is not correct. Pokemon snagged in Colosseum do not have a fateful encounter flag (Only Pokemon snagged from XD do).
- The Eevee you get as your starter in Pokemon XD does have a 'Fateful Encounter' flag by default but PKHeX seems to think that it shouldn't, stating, "Invalid: Fateful Encounter should not be checked." Again, this is incorrect and the Eevee starter from XD should in fact have a fateful encounter flag.
- Similarly, any wild Pokemon encountered at PokeSpots in Pokemon XD do have fateful encounter flags but PKHeX wrongly says they shouldn't.
- Finally, the Elekid (nicknamed ZAPRONG) you can trade for at the Outskirt Stand in XD states, "Invalid: Invalid Met Level, expected 0." This value should be 20, not 0.
- Female Snorunt caught in XD, transferred to a newer gen, and evolved to Froslass is being marked as illegal. Invalid Moves, Ribbons, and Unable to match encounter from origin game. It seems to not make the connection that a XD Snorunt could potentially be evolved to Froslass later down the line. File added below.

All of this data was gathered by me personally. Both games were played through start to finish without any cheats, glitches, or save file editing (Minus the Colosseum Master Ball glitch :D). Basically, the data is accurate. I'm not sure how much you guys really care about making sure the legality checking for Colosseum/XD is 100% accurate but I figured I could at least contribute this information. Hopefully it makes it into the next patch! Any further questions, feel free to reply here or send me a message! Hopefully this helps someone!

Possible Solution?: Would it be possible for PKHeX to check Pokemon species and 'met level' to determine which game it originated in (Between Colosseum/XD)? Then figure out if there should be a fateful encounter flag present or not based on that? Even though there are some Pokemon available in both games, the met level will never be the same between the two games as every encounter has a set level except for the wild Pokemon in XD. But even those, you can still determine based on species and met level which game they came from.

**Comment by kwsch** [comment]
99% has already been fixed since the release (less than 1mo ago), the remaining has already been fixed when I saw the forum post earlier today. I check both locations ;)

**Comment by FlapjacksNsyrup** [comment]
Was the Elekid/ZAPRONG issue fixed too? I tried checking the commits but couldn't tell what had been fixed and what hadn't.

**Comment by kwsch** [comment]
elekid: https://github.com/kwsch/PKHeX/commit/e635755dfd6fabfcb3d850e93c12289de01dc8b0
snorunt: https://github.com/kwsch/PKHeX/commit/86d39f2c81364d0a810797f6b4627b08aaa51c10

**Comment by FlapjacksNsyrup** [comment]
Great! That's awesome! Just wasn't sure since I added the Snorunt/Froslass issue after as an edit. That was very quick, thanks! :)

**Comment by javierhimura** [comment]
I think the bug with XD Snorun is caused because the variable FutureEvolutionsGen3_LevelUpGen4 is missing Frosslass (and Dusknoir)

**Comment by FlapjacksNsyrup** [comment]
Not sure. I also have a Dusknoir that came from XD as a Duskull and as far as I remember, it didn't have the same issue. Not at my computer to check right now though.
