### ISSUE TITLE
Wish Eggs bug

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1280]
The Wish Eggs from R/S/E/FR/LG are showing Illegal if the origin game is set at R, S or E,. If set at FR or LG they show legal. Tested with a genned Wish Chansey

When set to Ruby
![image](https://user-images.githubusercontent.com/18354599/27611854-75151a62-5b6e-11e7-9c01-8c17cde2dfb9.png)

When set to Fire Red
![image](https://user-images.githubusercontent.com/18354599/27611885-9e7d0c5c-5b6e-11e7-8d64-ebee9aa0e94c.png)

**Comment by kwsch** [comment]
https://bulbapedia.bulbagarden.net/wiki/List_of_PCNY_event_Pok%C3%A9mon_distributions_in_Generation_III#Wish_Eggs

Only distributed to FR/LG games.

And fwiw, both of those are not legal (PIDIV checks soon.tm)
