### ISSUE TITLE
gen 4 ribbon issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1282]
Hey I also just noticed that on my platinum, my infernape has the ability ribbon and pkhex flagged it as illegal even though I have a 21 streak at the battle frontier.

**Comment by kwsch** [comment]
works fine on latest commit:

![image](https://user-images.githubusercontent.com/6393368/27672288-97f54918-5c4e-11e7-890c-b72463975f84.png)

**Comment by NinFanBoyFTW** [comment]
ok great it works now thanks. I had a build from like 3 days ago so I wasnt sure if you had already fixed it.
