### ISSUE TITLE
pokemon xd legality issues (fateful encounter)

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1290]
Hi. So in my pokemon xd, all of the pokemon are flagged for not having the fateful encounter flag on but I havent touched these guys at all and they are legit. This is the same issue that you fixed for the Colosseum gen 2 starters. Thanks

**Comment by kwsch** [comment]
The fateful encounter flag check is based off of RoC's PC specimens from XD; all XD origin pkm had the fateful flag (except eevee).

**Comment by NinFanBoyFTW** [comment]
So I just played through pokemon xd from the beggining again up to the point where I purified the teddiursa, and it does not have the fateful encounter flag. I have seen RoC's pokemon and I dont know if its that he traded them to a certain gba game or what but im just telling you that none of these pokemon have a fateful encounter flag.

**Comment by ReignOfComputer** [comment]
Full disclosure, PkmGCSaveEditor was used to migrate my XD Pokemon to pk3/3gpkm.

I looked at other completed sets "Michael" and "TRISTAM" though, and the Pokemon do have Fateful Encounter flags checked. https://github.com/ReignOfComputer/RoCs-PC/tree/master/13%20-%20Gen%20IV%20-%20Gen%20III%20Pal%20Park/07%20-%20Gen%20III%20-%20XDCOLO%20Collection/ProjectPokemon

**Comment by NinFanBoyFTW** [comment]
So I just exported the teddiursa I got in xd from pkmGCSaveEditor and it is still coming up with no fateful encounter flag. Again, I literally just started this save from scratch to test this. I played through with no cheats up to when you purify teddiursa and it doesn't have the fateful encounter flag. All I know is that I have a new save with this pokemon and it doesn't have the fateful encounter flag, and I have my old save from 10 years ago, and that doesn't have any of the pokemon with the fateful encounter flag on. If you could, try for your self on your gamecube or on dolphin and see if you get the fateful encounter. Also this could mean nothing but why would the xd pokemon all have fateful encounter flags, and the Colosseum pokemon not have that flag. I know they are different games but still.

**Comment by ReignOfComputer** [comment]
https://bulbapedia.bulbagarden.net/wiki/Fateful_encounter

"Moreover, any Pokémon obtained in Pokémon XD will have this special flag set."

I don't know what to tell you lol >.<

**Comment by javierhimura** [comment]
Maybe the faterful flag is added when the pokemon is traded from a XD game to GBA games?

**Comment by NinFanBoyFTW** [comment]
but like I said. I literally started up a new save to test this and imported the save into pkhex. Im not trying to discredit your pokemon but, if you imported all of your pokemon using the older program, couldnt something have gone wrong. I have seen people saying that sometimes the older program has glitches with the fateful encounter. Like I said, could you just try to make a new xd save yourself and get up to the part where you purify your first pokemon because then we could get to the bottom of this once and for all. Also bulbapedia gets its info from people in the community (like you) and since you pretty much have the (master pokemon list) it doesnt seem out of the question that they are wrong. I know it sounds stupid to challenge the heads of the community but I love making pkhex better.

**Comment by NinFanBoyFTW** [comment]
Also its pretty funny because I just looked at you xd save and some of your pokemon have been flagged for not having fateful encounter on lol

**Comment by ijuintekka** [comment]
I can confirm that the flag is only set upon trading a native pokemon to a GBA game, including Eevee.
