### ISSUE TITLE
pokemon xd and colosseum glitches

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1292]
Hey just to let you know about another little glitch. when I check the trainer tab on my pokemon xd, it says the play time is zero when it is really like an hour. Also on my Colosseum save it says the play time is 8 hours and 30 mins, when it is really 1 hour and 30 mins. Thought I should mention it. Thanks

**Comment by kwsch** [comment]
Played Time is unimplemented in XD
Played Time in Colo uses the following:

```
private TimeSpan PlayedSpan
{
    get => TimeSpan.FromSeconds((double)(BigEndian.ToUInt32(Data, 40) - 0x47000000) / 128);
    set => BigEndian.GetBytes((uint)(value.TotalSeconds * 128) + 0x47000000).CopyTo(Data, 40);
}
public override int PlayedHours
{
    get => (ushort)PlayedSpan.Hours;
    set { var time = PlayedSpan; PlayedSpan = time - TimeSpan.FromHours(time.Hours) + TimeSpan.FromHours(value); }
}
public override int PlayedMinutes
{
    get => (byte)PlayedSpan.Minutes;
    set { var time = PlayedSpan; PlayedSpan = time - TimeSpan.FromMinutes(time.Minutes) + TimeSpan.FromMinutes(value); }
}
public override int PlayedSeconds
{
    get => (byte)PlayedSpan.Seconds;
    set { var time = PlayedSpan; PlayedSpan = time - TimeSpan.FromSeconds(time.Seconds) + TimeSpan.FromSeconds(value); }
}
```

which is a port from: 
https://github.com/trigger-death/TriggersPC/blob/08f35460d8afe10615c47a4307a238cf403bfe59/PokemonManager/Game/FileStructure/Gen3/GC/GCSaveData.cs#L290-L313

**Comment by NinFanBoyFTW** [comment]
Ok I kind of figured that the XD playtime wasnt implemented but the colosseum playtime just doesnt show up correctly, so I dont know if you can fix that or just disable it.

**Comment by NinFanBoyFTW** [comment]
So I just looked at my play time which is over 20 hours now and it is showing up correctly now. I dont understand if its something like when its a low play time it doesnt display correctly.
