### ISSUE TITLE
"Set data not found in clipboard" - Importing from QR codes.

### ISSUE THREAD

**Issue by ForcedToRock** [kwsch/PKHeX#1293]
Before now I could copy the direct link to a QR code image and be able to generate a mon from that info. Somehow that doesn't happen anymore, with the error "Set data not found in clipboard" being thrown up.

**Comment by sora10pls** [comment]
![image](https://user-images.githubusercontent.com/17801814/27775923-8c548ece-5f74-11e7-8222-78a43744f863.png)

**Comment by ForcedToRock** [comment]
That's the problem I'm saying, doing that throws up the message "Set data not found in clipboard."

**Comment by kwsch** [comment]
```
                if (Clipboard.ContainsText())
                    ClickShowdownImportPKM(sender, e);
                else
                    ImportQRToTabs();
```

both are text (qr is a url); should probably change things up.
