### ISSUE TITLE
17.07.02: XD Starter Eevee still doesn't like Fateful Encounter flag

### ISSUE THREAD

**Issue by FlapjacksNsyrup** [kwsch/PKHeX#1295]
Just downloaded the most recent full release, 17.07.02. The Eevee you get as a starter in XD is still saying it shouldn't have a Fateful Encounter flag when it in fact does have one. Can upload the .pkm file if that helps.

**Comment by kwsch** [comment]
Pseudo-duplicate with 1290

I started a new game, and the starter eevee did not have fateful encounter flagged.

**Comment by FlapjacksNsyrup** [comment]
Well this shouldn't be closed then. Obviously there are conflicting reports. I'm viewing an Eevee which was evolved into a Jolteon in XD and traded to Emerald through normal means. Never modified in any way. Has a fateful encounter flag.

**Comment by sora10pls** [comment]
>keep discussion re:fateful xd/c there
