### ISSUE TITLE
pokemon colosseum glitch

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1296]
Hey I wanted to let you know about a bad colosseum glitch with pkhex. I have all of my pokemon purified on this save. then I dumped the boxes and re loaded them. When I went back  in game a bunch of the pokemon are back in shadow form and I cant purify them again. Obviously this is an easy fix for me (re check that they are shadow pokemon in pkhex and re purify them) but this is a pretty bad bug.

**Comment by NinFanBoyFTW** [comment]
So I figured one thing out. I had used the time flute on some of these pokemon by putting 999 time flutes in my item pouch. That may be part of it but there are also some pokemon that I legit purified with just some normal use and they come up as shadow pokemon too. Just to make it clear again. Whenever I import these pokemon, it says that they are not shadow pokemon in pkhex, but when I go in game, they are shadow pokemon with a heart gauge of zero. But when I go to the relic stone, it acts like they are not shadow pokemon, not letting me purify them. Also An update from yesterday. I made the pokemon that were giving me trouble shadow pokemon again. Then I went in game and purified them. I went back to pkhex, exported them, imported them back all at once, and they came up again as shadow pokemon. Last thing I wanted to mention is that I havent modified these pokemon and its kind of funny because there are a few pokemon in this game that I have modified, and they arent affected by this. I am attaching my current folder of the pokemon, if you could just import them to a save, you could see them in game. Thanks

**Comment by kwsch** [comment]
You'd have to compare a before/after purification; it may just be the game not recognizing that the shadow pokemon you've once purified are now purified.

**Comment by NinFanBoyFTW** [comment]
Well im looking at them and nothing looks different. I re purified all of them and they all are fine now, but then I went and viewed the pokemon in tabs and set them to the party so I wouldn't have to edit my party in game and they changed back to shadow pokemon in the party. I think it may be a glitch with moving pokemon in pkhex, The pokemon I moved in this recent occurrence were pokemon that I purified completely legit and have not been modified in any way.

**Comment by NinFanBoyFTW** [comment]
I just looked at my pokemon xd, and my teddiursa, which I exported from pkhex and imported back into xd is now a shadow pokemon. Is there anything you can do about this since its much harder to purify in XD (no time flute). Im going to try the older program for xd since it has a (purify) option and see if that works. But clearly this is a big problem. Also just to let you know. I didnt cheat at all on this save file and this teddiursa was completely legally purified, so I know its not just because I used cheats or something like that

**Comment by NinFanBoyFTW** [comment]
Ok I just did one more test. I was noticing that whenever I was editing the pokemon in the PC in any way, it would reset the save file shadow pokemon count from 1 shadow pokemon and 1 purified pokemon (on the main menu continue screen) to 0 shadow pokemon (the the purified pokemon section was completely missing. So I did one more test. I opened the save file. And I immediately exported the save. I didnt edit anything. When I went back to the continue screen, It said 0 shadow pokemon and the purified pokemon section was completely missing. Obviously this means that something in the way pkhex is saving the pokemon xd and colosseum gci files is resetting the shadow pokemon count (and I guess the purified count). I dont know why this isnt a problem on most of the other save files (my older save files from when I was a kid) but it seems to be pkhex saving the file, and not even pkhex editing the pokemon.

**Comment by kwsch** [comment]
Probably related to the StrategyMemo data block (possibly corrupt?)

I've not heard of this issue from other users, so I assume it's related to your save file only...

**Comment by NinFanBoyFTW** [comment]
yeah but on colosseum and xd? Im not sure but maybe its somehow related to that other issue with the save time for colosseum and xd, where in the beginning of the game the play time was incorrect but as I played more it started working. Also I restarted my save file because of what happened with this and I purified teddiursa again, and this problem is still happening. So clearly its not just the save file.

**Comment by NinFanBoyFTW** [comment]
Hey can I send a copy of a before and after save file from my xd. Ill just include it here but I really hope that you can figure out what is wrong with this. Just to let you know, All I did was took the before save file, and then opened it up in pkhex, and then exported the save like normal. (I DID NOT CHANGE ANYTHING) So obviously this is not a problem with the way I edited a pokemon.

[01-GXXE-PokemonXD.zip](https://github.com/kwsch/PKHeX/files/1149832/01-GXXE-PokemonXD.zip)
