### ISSUE TITLE
Various gen 4 issues

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1297]
- [x] Encounter type for Pokemon encountered in the Old Chateau should be "Building/Enigma Stone", not "None".
- [x] Setting the Pokedex to "Caught All" adds French language entries regardless of the actual game language.
- [x] Setting the Pokedex Upgrade to "National Dex" enables viewing the National Dex but doesn't enable any of the other things it unlocks (only observed in DPPt, not sure if it also applies to HGSS).
- [x] Unhatched Ranger Manaphy egg gives the error "Unable to match an event Egg encounter from the origin game".
- [x] Any Mail present in the bag in doesn't show up in PKHeX, and Mail added to the bag in PKHeX doesn't show up in-game (DPPt only, works fine in HGSS).
- [x] The various Mail items should use the correct in-game name instead of "Mail ## (G4)" (also applies to gen 5, but the gen 5 Mail items are different from the gen 4 ones despite having the same index numbers).

**Comment by sora10pls** [comment]
Unable to replicate the Manaphy Egg bug.
![image](https://user-images.githubusercontent.com/17801814/27839749-bf749b8e-60c1-11e7-9985-9dc53f23c8fc.png)

As for Gen 4 mail, refer to source code's comment [on this line](https://github.com/kwsch/PKHeX/blob/5b5c9d00171681eb0576ddf1cd9810242a393d28/PKHeX.Core/Game/GameInfo.cs#L145).

**Comment by sora10pls** [comment]
Should the Mail names be changed in PKHeX, here's a list of their in-game names:

Mail 1 -- Grass Mail
Mail 2 -- Flame Mail
Mail 3 -- Bubble Mail
Mail 4 -- Bloom Mail
Mail 5 -- Tunnel Mail
Mail 6 -- Steel Mail
Mail 7 -- Heart Mail
Mail 8 -- Snow Mail
Mail 9 -- Space Mail
Mail 10 - Air Mail
Mail 11 - Mosaic Mail
Mail 12 - Brick Mail

**Comment by javierhimura** [comment]
To fix the old chateau encounter type the location should be removed from the list DPPt_MixInteriorExteriorLocations

**Comment by kwsch** [comment]
Issue with mail is that it changed names from Gen4 -> Gen5

```
136	0x0088	Lustrous Orb
137	0x0089	Greet Mail
138	0x008A	Favored Mail
139	0x008B	RSVP Mail
140	0x008C	Thanks Mail
141	0x008D	Inquiry Mail
142	0x008E	Like Mail
143	0x008F	Reply Mail
144	0x0090	BridgeMail S
145	0x0091	BridgeMail D
146	0x0092	BridgeMail T
147	0x0093	BridgeMail V
148	0x0094	BridgeMail M

136	0x0088	Lustrous Orb
137	0x0089	Grass Mail
138	0x008A	Flame Mail
139	0x008B	Bubble Mail
140	0x008C	Bloom Mail
141	0x008D	Tunnel Mail
142	0x008E	Steel Mail
143	0x008F	Heart Mail
144	0x0090	Snow Mail
145	0x0091	Space Mail
146	0x0092	Air Mail
147	0x0093	Mosaic Mail
148	0x0094	Brick Mail
```

`GetItemStrings` can be generation specific, but it only has special handling for gen3.
Gen1/2/3 have separate tables, and 4-7 use the same table.

**Comment by White-Canary** [comment]
@sora10pls The egg was received from the delivery man using the Wonder Card from PP.org and hasn't been edited in any way. And it hasn't been traded, so "None" should be the correct location, shouldn't it? At least it is with regular eggs, it might be different with Manaphy but like I said, I used the Wonder Card so it should be fine.

Also, the Mail thing only happens in DP. I thought I tested Platinum too but I didn't, seems it works fine there as well.

@kwsch Seems like talking to Professor Oak with a complete Sinnoh Dex sets an additional flag to unlock National Dex features in addition to upgrading the Pokedex. Shouldn't be too hard to figure it out.

**Comment by sora10pls** [comment]
It should be the correct Met Location, yes. "None" if received in that game, "Link Trade (Egg)" if traded. Oddly enough, the "Pokemon Ranger" Met Location is accepted, even though you can't hatch the Egg there.

**Comment by sora10pls** [comment]
From what I've gathered for the Manaphy Egg:

- "None" should be a valid Met Location when IsEgg = true; currently...
If IsEgg = true, "None" is flagged as illegal; this is false
If IsEgg = false, "None" is deemed legal; this is false

"Link Trade (Egg)" only applies to Manaphy Eggs that have been traded to other games; Manaphy Egg uses the save file's OT info and is not static like most Events

- "Pokemon Ranger" should not be a valid Met Location
Met Location is where the Egg was hatched in-game
- "Pokemon Ranger" should be the *only* valid Egg Met Location
Egg Met Location is where the Egg was obtained, and in Manaphy's case, it's only Pokemon Ranger

**Comment by kwsch** [comment]
When in doubt, check the complete legality report to see if it is matching it to the proper encounter.

Here's where it [checks for Ranger Manaphy](https://github.com/kwsch/PKHeX/blob/2e0f3a930574a43e4a3f9a51164f997ba70e5bcb/PKHeX.Core/Legality/Encounters/EncounterGenerator.cs#L904-L917).

As detailed above by @sora10pls, the Egg Location is always Ranger when `IsEgg`, and is either Ranger or Link Trade (Egg) when `!IsEgg`.

```
if (IsRangerManaphy(pkm))
    yield return new PGT { Data = { [0] = 7, [8] = 1 } };
yield break;
```
```
private static bool IsRangerManaphy(PKM pkm)
{
    var egg = pkm.Egg_Location;
    if (!pkm.IsEgg) // Ranger || Link Trade Egg
        return egg == 3001 || egg == 2002;
    
    // Egg Location must be Ranger
    // Met Location must be None or Link Trade Egg
    var met = pkm.Met_Location;
    return egg == 3001 && (met == 0 || met == 2002);
}
```

**Comment by sora10pls** [comment]
Would Egg Location not always be Pokemon Ranger? The only thing that would vary is Met Location.

Egg Location (where Egg originated): Pokemon Ranger

Met Location (where Egg was hatched):
If `IsEgg` -> "None" or "Link Trade (Egg)"
If `!IsEgg` -> Any legal area to hatch an Egg

The code provided above still lists all other Egg Met Locations as legal, and if Manaphy `IsEgg`, says Pokemon Ranger is legal.

**Comment by kwsch** [comment]
When an egg is hatched, if the met location is not 0, the met location will overwrite the egg location so that the hatch location can be the met location.

Hatching:
```
if (metloc != 0)
  eggloc = metloc
metloc = currentloc
```

A link traded manaphy egg retains its 'link trade egg' status when hatched, as it overwrites the Ranger status.

**Comment by sora10pls** [comment]
The updated code provided is exactly what I was trying to get to. Will submit a PR soon!

**Comment by kamronbatman** [comment]
@kwsch - Since anti-shiny is broken (it is tested against the egg's TID/SID, not the current handler), the PID can be anti-shiny and still shiny, or regular and still shiny.

**Comment by javierhimura** [comment]
@kamronbatman Manaphy can be shiny after hatching in another game different that the one who recieve de egg, but that means the egg should be traded to another game before being hatched and that will change the met location to Link Trade (egg), only when the Manaphy is hatched the TID/SID of the current handler will overwrite the egg TID/SID and make it shiny

That means:
- Shiny Manaphy inside an egg : Illegal
- Shiny Manaphy without "Link Trade (Egg)" egg met location : Illegal

Anti-shiny is broken, yes, but the bug only occurs after trade and hatch the egg, a shiny without trade or hatch is illegal.

**Comment by kamronbatman** [comment]
You are correct, except your second point, it must have "Link Trade (Egg)" and different OTN/TID/SID/OTG.  The chances of you trading with someone else that has the same OTN/TID/SID/OTG are remote to say the least.

I was more commenting on whether or not we have these checks in-place, and if we think it is a priority to add them if they aren't already.  Also specifically the anti-shiny.

**Comment by javierhimura** [comment]
The checks for the legal cases i mentioned are implemented. Anti-shiny is taken into account when the program is reproducind the RNG of PID-IV

      private static bool IsG4ManaphyPIDValid(PIDType val, PKM pkm)
        {
            if (val == PIDType.Method_1)
                return pkm.WasTradedEgg || !pkm.IsShiny; // can't be shiny on received game
            if (val != PIDType.G4MGAntiShiny)
                return false;
            if (pkm.WasTradedEgg)
                return true;
            var shinyPID = RNG.ARNG.Prev(pkm.PID);
            return (pkm.TID ^ pkm.SID ^ (shinyPID & 0xFFFF) ^ (shinyPID >> 16)) < 8; // shiny proc
        }

About what you said keep in mind a Link Trade (Egg) always have the 100% chance to have same  OTN/TID/SID/OTG, at the moment of hatch de pokemon. Remember original OTN/TID/SID/OTG is lost when the egg hatch in another game.

If manaphy is instead inside an egg and is Link Trade (Egg) there is no check againts the savegame OTN/TID/SID/OTG, in fact most of the legal checks are only done againts the pokemon data and not the savegame data.

But still the pokemon can be Link Trade (Egg) and have the same trainer data from the savegame, if the egg is traded to another game and then traded back to the original game.
