### ISSUE TITLE
Can you use the batch editor to make every Pokemon it's lowest legal level?

### ISSUE THREAD

**Issue by Nawor3565** [kwsch/PKHeX#1298]
I want to make every Pokemon in my PC their lowest "legal" level. So a Bulbasaur would become level 1, a Ivysaur would become level 16, and a Venusaur would become level 32. Not including events, gift Pokemon, or other special cases, just the lowest level they can normally be at. Is there a way to use the batch editor to do this? Thanks!

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/80e2d559996abb9e3d2728265be5c2ecfee8840e/PKHeX.WinForms/Subforms/PKM%20Editors/BatchEditor.cs#L493-L506

**Comment by Nawor3565** [comment]
I tried using commands like what's shown there, but I can't seem to get it working... Could you please give me an example command? :)

**Comment by Nawor3565** [comment]
Ah, I figured it out. Just have to use:
`.Met_Location=$suggest`
