### ISSUE TITLE
Wonder Card I/O - Only 11 Slots

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#130]
This should go without saying, there are only 11 slots for Wonder Cards when there should be 12 (signified by the '7-12' label)

**Comment by sora10pls** [comment]
Wow forgot to include the image lmao. Done with a save file of Pokemon Platinum

![screenshot_1](https://cloud.githubusercontent.com/assets/17801814/16592686/d35dcfac-42af-11e6-91cb-dd34034b2b38.png)

**Comment by kwsch** [comment]
There's technically only 11 (8 pgt, 3 pcd) slots.

I'll just add some code to update the labels so that the actual count is reflected. Showing the 8 & 3 separately while supporting other games feels like too much work.

**Comment by sora10pls** [comment]
Ah, did not know that. Thanks for clarifying :)

**Comment by kwsch** [comment]
New view:

![](http://i.imgur.com/erXpwBG.png)
