### ISSUE TITLE
pk3 to ck3 glitch

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1302]
So I also found another strange thing. I havent tried this on xd yet, but in Colosseum, I imported some pokemon that were from my old Colosseum but were currently in my fire red (pk3) I then exported them (ck3) and re imported them and went into game. Im not sure if there are other things wrong with them, but the main thing is that, all of their levels are 0 instead of whatever levels they should be. Just wanted to let you know. Thanks

**Comment by kwsch** [comment]
CK3/XK3 store battle stats in the structure; pkhex does not set those values at this time
