### ISSUE TITLE
Colo/XD met location names off by 1.

### ISSUE THREAD

**Issue by ijuintekka** [kwsch/PKHeX#1303]
The Teddiursa caught at Pokémon HQ Lab (143) displays as Gateon Port (144) for example.

**Comment by FlapjacksNsyrup** [comment]
Can confirm this issue.

Eeveelution showing as met at Cipher Lab. Seedot at Mt. Battle, etc.

**Comment by ijuintekka** [comment]
Gateon Port should be [144] is what I'm saying, but there when the list of locations is being enumerated it is given [143] because everything is offset by one.

The list of locations starts with "Outskirt Stand (C) Cipher Lab (XD)" which should be the second entry after a blank.

**Comment by ijuintekka** [comment]
Further to this: Eevee's met location is index 0, so it shouldn't be left blank. I would name it (Eevee) or (XD Starter).
