### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by JacenBoy** [kwsch/PKHeX#1305]
Recieved this error upon starting PKHeX:

Exception Details:
System.TypeInitializationException: The type initializer for 'PKHeX.WinForms.Main' threw an exception. ---> System.TypeInitializationException: The type initializer for 'PKHeX.Core.Legal' threw an exception. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at PKHeX.Core.Legal..cctor()
   --- End of inner exception stack trace ---
   at PKHeX.Core.SAV7..ctor(Byte[] data)
   at PKHeX.Core.SaveUtil.getBlankSAV(GameVersion Game)
   at PKHeX.Core.SaveUtil.getBlankSAV(GameVersion Game, String OT)
   at PKHeX.WinForms.Main..cctor()
   --- End of inner exception stack trace ---
   at PKHeX.WinForms.Main..ctor()
   at PKHeX.WinForms.Program.StartPKHeX()
   at PKHeX.WinForms.Program.Main()

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\James\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

--------------------
User Message:
An unhandled exception has occurred.
PKHeX must now close.

The night before I got the message, I had been editing a Pokemon Battle Revolution save. PKHeX runs normally when restarted after this error occurs.

**Comment by kwsch** [comment]
>Common Language Runtime detected an invalid program.
At a glance I don't think this is PKHeX related, but instead related to the contents of the folder you extracted the program to. Maybe some mismatching of dlls from prior versions are interfering... dunno.

**Comment by kwsch** [comment]
Try downloading the latest release and extracting all files to an empty folder.
