### ISSUE TITLE
Shiny Manaphy (bug) ?

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1308]
I cannot create a legal shiny Manaphy with PKHeX despite having it legal, according to RNGReporter, PID/SID values.

I created this thread over at Admiral-Fish's RNGReporter Github
https://github.com/Admiral-Fish/RNGReporter/issues/19

He believes I should take it up here.

Also asked about it here
https://projectpokemon.org/forums/files/file/66-pok%C3%A9mon-ranger-manaphy-egg/
![image](https://user-images.githubusercontent.com/18354599/27896664-18f2c4f8-61f6-11e7-92c5-d8643f836851.png)

**Comment by kwsch** [comment]
>no pkm file

RNG one yourself and observe the correct values needed :)
