### ISSUE TITLE
Inventory Sorting

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1312]
If sorted alphabetically...

- TM/HM (Gens 3 through 6)
HMs are set to the top of the list, should be bottom **(only exception is FR/LG)**
- Mail (Gen 4)
Should be 1-12, not 1, 10, 11, 12, 2-9 **(could be obsolete if Gen 4 Mail names are implemented)**

For reference, in B/W (when sorting was introduced; was expanded upon with B2/W2) onward, you are able to sort TMs "By Number", so it'd be TM01-TM95 (or TM100 if Gen 6+), and then HM01 to HM06 (or HM08 if XY/ORAS). Sorting TMs alphabetically in-game uses the actual move names, so it'd probably be better to sort TMs/HMs by number rather than alphabetically.

If given all (and PKHeX auto-sorts them by Item ID)...
- TM/HM (FR/LG)
HMs are set to the bottom of the list, should be top
This is correct for every instance ***except for*** **FR/LG**

This is all based off of how the games sort inventory.
HMs are always on the bottom of the list, unless it's FR/LG where they are at the top.

**Comment by kwsch** [comment]
abcdefgHijklmnopqrsTuvwxyz
H is before T
0123456789
String sorting sorts for each character, so Mail 1, Mail 10, Mail 11, etc becomes Mail 01, Mail 02, ...

Mitigation steps:
* Mail should use leading zero (ie ToString("00")) to make alphabetical sorting neater
* Add "Sort by Item ID"

**Comment by sora10pls** [comment]
Yeah that's what I was going for. The alphabetical sorting in PKHeX goes off of the item name (obviously H before T), while in-game is the move's name.
