### ISSUE TITLE
PCNY event Pokémon

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1313]
Pretty much all of the PCNY event Pokémon special moves are marked as illegal in 3533 build of PKHeX.
https://bulbapedia.bulbagarden.net/wiki/List_of_PCNY_event_Pok%C3%A9mon_distributions_in_Generation_III
Thank you for reading!

**Comment by kwsch** [comment]
That's because they aren't included in the event pkm table ;)

Since the TIDs are variant (0-65535) will have to add handling for TID=-1 like for SIDs.

@kamronbatman

**Comment by greenDarkness** [comment]
I was talking about the eggs specifically. Sorry, I should have clarified. ^_^

**Comment by kamronbatman** [comment]
I'll look into both.

**Comment by greenDarkness** [comment]
Thank you!

**Comment by kwsch** [comment]
Looks like unhatched eggs have random TID/SID based off the OT that receives it?

**Comment by kamronbatman** [comment]
That is correct. Same as PCJP 2004 eggs. I thought my merge accounted for that.

**Comment by kamronbatman** [comment]
@kwsch - It looks like your WC3 refactor broke it.  I can do another PR if you would like.
