### ISSUE TITLE
Properly handle illegal Event OTs

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1317]
There are a few events that use illegal characters, see this list:
https://www.reddit.com/r/pokemontrades/comments/67to6d/ots_can_change_to_sun_in_sunmoon/

Apparently some legal symbols in previous generations did not translate well to gen 7.

Related, the new mew with OT ２０ＴＨ☆ is using an illegal character (the wrong star).  We need to find a way to handle this since trading it will change it to Sun in the language of that pokemon, in this case Japanese (サン).

How should we handle this so the new event is still legal even with the changed name?

**Comment by kwsch** [comment]
* Move OT check near the end of matching a WC7
* If OT name does not match WC7, compare OT to a hashset of names that are modified
* If modified OT name is in hashset, check against the auto-fix name instead.

**Comment by kamronbatman** [comment]
That works.  Is it worth building it heuristically considering this is the 10th time and this problem affects non-event OT's too?

**Comment by kwsch** [comment]
The only OTs it would cause issue for are any `MysteryGift`, as they have OT matching requirements.
There's not a way to detect which illegal characters will be used in the future; we could probably store a list of all card OTs affected and tack on a bool property to the `MysteryGift` object instead of checking the hash every time.

**Comment by kamronbatman** [comment]
I was told by Kirzi that it can happen with regular OTs as well.  Not sure how predictable the bug is though in those circumstances.  I suppose until someone goes into the code and spots that check and the criteria, we can go with your idea. :)

**Comment by kamronbatman** [comment]
It appears there is evidence that characters are whitelisted or included in a table per language.  Some characters were erroneously missing such as & for the korean character set.

With regards to mystery gifts, it is clear that the OTs are using characters not included in that table.  With regular OTNs and Nicknames, it appears that the table has changed between Gen 6 and Gen 7.

We might be able to find this whitelist/table in the game and use that.

**Comment by kwsch** [comment]
Shouldn't matter for normal OTs as a player can always name themselves the 'fixed' name.

For fixed OT gifts that get flagged, I can always do a precompute on load to see if the OT gets reset (bool flag) and have a pool of available OTs for that.

Would just need a list of card hashes ;)

**Comment by kamronbatman** [comment]
@kwsch, I can give you the card hash list.  How do you do the hashes? Can you link me to the part of the PKHex core that hashes them?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/690cbaae798c43d388b008784227794ad23e7fbb/PKHeX.Core/MysteryGifts/MysteryGift.cs#L125-L131

basically just hashes the byte array

**Comment by kamronbatman** [comment]
We will need to standardize this because some are WCFull and others are WCs (and we are replacing WCs with WCFulls as time goes on with Gen 6).

With that said, is it ok if I hash just non-full data?

**Comment by kwsch** [comment]
yes, you can use the following method to get a list of hashes:

https://github.com/kwsch/PKHeX/blob/690cbaae798c43d388b008784227794ad23e7fbb/PKHeX.Core/MysteryGifts/MysteryGift.cs#L28-L51

with files as a string[]:
```c#
var hashes = files.Select(File.ReadAllBytes).Select(GetMysteryGift).Select(z => new {Hash = z.GetHashCode(), Gift = z});
```
