### ISSUE TITLE
PokeTransfer ball legality bug

### ISSUE THREAD

**Issue by JFSushi** [kwsch/PKHeX#1319]
There seems to be a bug in the Pokeball legality checker for Pokemon from past generations (encounter: Poké Transfer).

It's giving 'Invalid:  Can't have ball for encounter type' on several Pokemon. Most of these Pokemon I caught legitimately on HeartGold and LeafGreen and while I have edited them, I never modified their balls, so I'm positive they're legal.

![capture](https://user-images.githubusercontent.com/18478277/28052260-44dbe968-664d-11e7-8bfe-a3d58c1a9e15.PNG)

**Comment by kwsch** [comment]
>while I have edited them

yeah, they're no longer valid.

* wild encounters must have valid PIDIV
* eggs can only have pokeballs

pick one
