### ISSUE TITLE
Issues in transferring Pokemon from SoulSilver

### ISSUE THREAD

**Issue by frozenLake** [kwsch/PKHeX#132]
When I try to convert my pokemon, it claims it works, but the folder I'm sticking the pokemon into is still empty. I have decided to attach the save file in order to help reproduce the bug.
[POKEMON SS.0.zip](https://github.com/kwsch/PKHeX/files/356249/POKEMON.SS.0.zip)

**Comment by kwsch** [comment]
Are you using the latest commit or the latest release?

There's been a lot of changes; the latest commit is able to load past gen save files and edit them directly instead of directly importing to a future gen save file.
