### ISSUE TITLE
Set Origin Game with OT Label shortcut for SAV3/SAV4

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1320]
If the OT label in the OT/Misc tab is clicked, PKHeX auto-fills in some data to match that of the save file (OT, TID, SID, Language, Origin Game, and if Gen 6+, 3DS region settings).

With Gen 3 and Gen 4 save files, clicking the OT Label does indeed change all of this data, *except for* Origin Game. Gen 5+ works fine.

**Comment by kwsch** [comment]
[`SaveFile.Game` property is checked for validity, then applied.](https://github.com/kwsch/PKHeX/blob/1d93c5836e89bd45b03e15fe60c37c4397f302a7/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L321-L322).

[SaveFile defaults to -1, SAV3/4 do not override the SaveFile.Game property](https://github.com/kwsch/PKHeX/blob/1d93c5836e89bd45b03e15fe60c37c4397f302a7/PKHeX.Core/Saves/SaveFile.cs#L319)

will have to add the functionality

**Comment by kwsch** [comment]
Can't add described functionality for Gen3/4 as the game group (DP, HGSS, RS) is detected, not actual version. Since the game ID is not detectable from the SAV, we can't set a value on label click.

**Comment by architdate** [comment]
I'm not very sure about this, but wouldn't `$"{C_SAV.Version}"` actually give you the version string? even the specific game? since this is how the App title is being loaded and it has the version info in it? Once you have the above string can't you just switch - case it to set the Game Origin CB based on the string returned by the above GameVersion object? @kwsch

**Comment by kwsch** [comment]
* RS
* HGSS
* DP
* FRLG

Currently only FRLG prompts for split game determination (for picking Deoxys's base stats).
Look at the program window title when loading those saves; it displays the combo game not an individual version.

**Comment by architdate** [comment]
Ah my bad, I just checked emerald and that just showed E so I assumed it would be the same for the rest too

**Comment by architdate** [comment]
@kwsch wait so if these games can't be differentiated, I don't think there is any way this is possible right? So wondering why you didn't close this issue yet... Unless you believe there maybe a worthwhile direction to look into? Maybe some sort of flag that states what legendary was encountered? (Although those are Groudon/Kyogre as well)

**Comment by sora10pls** [comment]
While that could... maybe(?) work in the case of R/S, think of HG/SS where you can get BOTH Lugia and Ho-Oh regardless of version.

**Comment by kwsch** [comment]
Event Flags may be a possible detection path. If the user messes with them to unlock opposite-version things, then that'd mess with it.
