### ISSUE TITLE
Can´t legalize some pokemon :(

### ISSUE THREAD

**Issue by GonzoMtz** [kwsch/PKHeX#1325]
I can´t legalize some pokemon, I got this messages from PKHeX:
Invalid: Can´t have active Super Training unlocked flag for origins. 
Invalid: Unable to match to a Mystery Gift in the database.
Invalid: Encounter type PID mismatch.
Invalid: PID-Nature mismatch.

What can I do to fix this? Thanks for helping!

**Comment by kwsch** [comment]
GitHub issues is to report bugs/feature requests, not for help in faking data.
