### ISSUE TITLE
[Bug] Gen 3 Southern Island Latias/Latios Fateful Encounter

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1326]
If a Southern Island (not roaming, the E-reader event) Latias/Latios is transferred to Gen 4+, Fateful Encounter is kept as checked, making this legality check false.

"Invalid: Fateful Encounter should not be checked."

Before:
![image](https://user-images.githubusercontent.com/17801814/28178249-bd490d70-67cb-11e7-84c6-0969c3838cef.png)

After:
![image](https://user-images.githubusercontent.com/17801814/28178257-cb43ee7c-67cb-11e7-9835-a36a01aaa311.png)
![image](https://user-images.githubusercontent.com/17801814/28178277-df32aa86-67cb-11e7-9c18-7bf752efa901.png)

[PKM file.](https://github.com/kwsch/PKHeX/files/1146331/southernisland.zip)

**Comment by kamronbatman** [comment]
I think this bug was introduced because the fateful encounter rules were fixed for circumstances and now broke this situation.  I'll go back through it and submit a PR to fix it.

**Comment by kwsch** [comment]
Nah it wasn't because of that; Emerald has to methods to catch Lati@s, one with Fateful and one without.
The without is the first one encountered; due to it not rejecting the encounter from the generator, it finishes with the invalid fateful result.

Just need to add an exclusion case for the generator...

**Comment by kamronbatman** [comment]
I am just not sure if the gen 3 fateful encounter flag ALWAYS xfers to gen 4, or only for certain circumstances.

**Comment by sora10pls** [comment]
For added examples, I guess you could relate it to:

- Birth Island Deoxys (FR/LG/E)
- Navel Rock Ho-Oh and Lugia (FR/LG/E)
- Flower Paradise Shaymin (Pt)
- Sky Pillar Deoxys (OR/AS)

As far as I'm aware, the fateful encounter flag is *always* checked when transferred due to them being caught that way, with the flag enabled.

**Comment by kamronbatman** [comment]
@kwsch:
I am thinking a simple check in `GetValidWildEncounters` like
`if (pkm.FatefulEncounter) yield break;`

Would that work?

**Comment by kwsch** [comment]
Both are static encounters; I'd want to yield the encounter even if the fateful encounter flag is incorrect (as a legality message will explain why). The generator only returns encounters, not reasons why any {rejected encounter} wasn't checked further.
