### ISSUE TITLE
[Bug] Ash-Greninja legality

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1329]
Ash Greninja is being legalized as an egg based Mon. I am willing to provide a pk7 if the issue cannot be replicated :)

**Comment by sora10pls** [comment]
Can't replicate using my own, nor any from the Mystery Gift Database (obviously)... providing the PKM file would help.

**Comment by architdate** [comment]
Uploaded the file as requested. [Uploading 658-01 - Greninja - 2E28C74B7FF5.zip…](Egg Greninja)

**Comment by architdate** [comment]
Here is the requested file: @sora10pls [Ash-Greninja as an Egg](https://github.com/kwsch/PKHeX/files/1147124/658-01.-.Greninja.-.2E28C74B7FF5.zip)
