### ISSUE TITLE
pokemon sapphire beautifly legality

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1330]
Hi. So I am trying to put together my own group of fully legal pokemon so I can have every pokemon (that I caught) legally. I went and caught a wurmple in the wild leveled it up with rare candies and it ended up turning into a beautifly. When I went into pkhex, it says that the wurple encryption mismatch thing. I have encountered this before but with wurmples that may have been cheated (not sure) but this one I literally caught in the wild and leveled up in game.

**Comment by sora10pls** [comment]
Provide the PKM file.

**Comment by NinFanBoyFTW** [comment]
[267 - BEAUTIFLY - 266F57BDF51D.zip](https://github.com/kwsch/PKHeX/files/1147148/267.-.BEAUTIFLY.-.266F57BDF51D.zip)

**Comment by sora10pls** [comment]
Changing the species to Dustox (and applying suggested Current Moves) made it legal; PKHeX is checking for the opposite evolution line.

**Comment by architdate** [comment]
If the beautifly is indeed legal however this is an issue because rerolling EC keeps giving me the same error when it should be correcting it.. hmm

Also an intresting fact to note is, rerolling the PID actually gave me an illegal ball error, which is quite weird

**Comment by kwsch** [comment]
https://bulbapedia.bulbagarden.net/wiki/Personality_value#Wurmple.27s_evolution
PID = `57BDF51D`
F51D % 10 = 9

>If the result of `pword % 10` is less than 5, Wurmple will evolve into Silcoon. If it is greater than or equal to 5, Wurmple will evolve into Cascoon.

9 is >= 5, so it implies it should have evolved into Cascoon.

**Comment by kwsch** [comment]
Did you happen to have an Intimidate lead?

**Comment by kwsch** [comment]
@architdate rerolling the PID fixed the PID, but it undid the method 4 PID correlation causing it to be evaluated as an egg (no PIDIV = no wild capture).

Can't breed balls in gen3 ;)

**Comment by NinFanBoyFTW** [comment]
so what does this mean. Like you said, I found this pokemon in the wild as a wurmple
