### ISSUE TITLE
[Bug] MGDB WC7 Eggs Invalid Hatch Cycles

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1331]
When loading the Mareanie, Turtonator, Oranguru, Passimian, or Drampa Egg WC7s from the MGDB, PKHeX throws out the following:

![image](https://user-images.githubusercontent.com/17801814/28195084-3a7b71a8-6816-11e7-8f8a-ad8258867dd9.png)

**Comment by architdate** [comment]
Ah i see why, I think its treating the egg as a pokemon and confusing hatch counter for newly hatched friendship. Reducing Hatch counter to 0 should fix it, the base wc file also needs to be changed to fix the same for future issues

**Comment by sora10pls** [comment]
Reducing the Hatch Counter to anything less than or equal to 20 does remedy this.

**Comment by architdate** [comment]
Yeah so basically its just confusing hatch counter for a newly hatched eggs happiness. Seems like an issue with the base wondercard itself. Is this just this egg or all eggs in general in mgdb?

**Comment by sora10pls** [comment]
All Eggs in the MGDB, actually. Just tested with the other Gen 6 ones.

**Comment by architdate** [comment]
Ahh, then the eggs are being treated as hatched either by pkhex itself, or by the wc7, I'll look through the code to see if I can find anything

**Comment by architdate** [comment]
So it seems that this line of code `pk.CurrentFriendship = pk.IsEgg ? pi.HatchCycles : pi.BaseFriendship;` is what may be causing the error, from what I understand, it checks whether the Pokemon is an egg or not, if its not an egg, it sets the `CurrentFriendship` as `BaseFriendship` else it sets `HatchCycles` as `BaseFriendship` where base friendship is 70. @sora10pls 

Another thing that can be done to confirm this is transferring the egg straight into the box via PKHeX and checking the hatch counters via PokeCalcNTR in game to check if it is indeed 20. If what i am saying is correct (and I think it is) the egg should still have a hatch counter of 20 (or whatever the base hatch counter of that specific species is) but when viewed in PKHeX it will initialize the form with BaseFriendship as HatchCounter.
