### ISSUE TITLE
PCNY Wish Eggs Legality

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1334]
These events no longer read as legal, because their special moves are listed as invalid. 
https://bulbapedia.bulbagarden.net/wiki/List_of_PCNY_event_Pok%C3%A9mon_distributions_in_Generation_III
As well as the Egg Pokemon Present Eggs
https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_event_Pok%C3%A9mon_distributions_in_Generation_III#Egg_Pok.C3.A9mon_Present_Eggs

Thanks for reading this!

**Comment by kwsch** [comment]
Would need to see a pkm file; are you sure the PIDIV method matches what PKHeX is expecting for those?

**Comment by greenDarkness** [comment]
This is an untouched Wish Absol taken from the event gallery that currently reads as illegal. 
http://www.mediafire.com/file/x9c889qa1a11a7u/359_-_ABSOL_-_0D423D35F71F.pk3
https://projectpokemon.org/forums/files/file/1744-pcny-absol/

Current error: 
Invalid Move 4: Invalid Move.
Invalid: Encounter Type PID mismatch.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Fishy: SID is zero.
Fishy: All EVs are zero, but leveled above Met Level.
Fishy: Current experience matches level threshold.
Valid: Valid Wild Encounter at location.
Valid: Nickname matches species name.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: History block is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Wild Encounter Grass (Absol)
PID Type: None

Removing Wish will cause PKHeX to detect the mon as legal.

**Comment by kwsch** [comment]
>PID Type: None

Don't assume that the event gallery has legal files ;)

**Comment by greenDarkness** [comment]
My bad haha. ^_^ 
I'm still not understanding what's wrong with the file though. 
Is it just that PID types need to be added?

**Comment by kwsch** [comment]
I assume someone rerolled the PID before submitting it to the site, way back in the day.
You can probably copy a PIDIV from another valid wish pkm -- I'm not sure if it's entirely legal (dunno species determination RNG) but should be good enough for now if you're wanting something close. Or just make a new PID/IV based off the type it should have (Method 2).

@kamronbatman re: invalid event db pkm

**Comment by greenDarkness** [comment]
Must be. I made a new one based of Method 2 like you suggested, but it's still reading as illegal. 
http://www.mediafire.com/file/be7g9ketvnbiok5/359_-_Absol_-_B92BC01FDE5D.pk7

Invalid Move 4: Invalid Move.
Invalid: Encounter Type PID mismatch.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Fishy: SID is zero.
Fishy: All EVs are zero, but leveled above Met Level.
Fishy: Current experience matches level threshold.
Valid: Able to hatch an Egg at Met Location.
Valid: Nickname matches species name.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: History block is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Egg (Absol)
Origin Seed: 2D489F8E
PID Type: Method_2

**Comment by greenDarkness** [comment]
Thanks for the mark down help!

**Comment by kamronbatman** [comment]
All of mine are coming up as legal as of yesterday.  I'll check again against master.  I have them on the events gallery [here](https://github.com/projectpokemon/EventsGallery/tree/master/Gen%203/JPN/%E3%83%9D%E3%82%B1%E3%83%91%E3%83%BC%E3%82%AF/Eggs%202004)

**Comment by kamronbatman** [comment]
@greenDarkness The absol listed in PCNY is not an egg distribution.  It is part of the Gotta Catch Em All series, which nobody knows the algorithm for.  You can find several legit Absol's though in HaxAras & InsaneNutter's collection on digiex.  It is under the OverFlow sav file - box 1.

**Comment by greenDarkness** [comment]
I'll check the gallery as well.
Ah, you are absolutely correct.

I might have referenced the wrong event by mistake. The event that I was trying to get help with is the Wish Absol from a hatched egg; Pokémon Center 5th Anniversary Eggs I believe. 
https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_event_Pok%C3%A9mon_distributions_in_Generation_III#Wish_Absol

I dumped the box that had the events that are all reading that their special move is invalid. 
http://www.mediafire.com/file/ltm553gdql4n594/Pokemon.rar

Thank you so much for taking the time to look at this!

**Comment by greenDarkness** [comment]
I think I know what the problem was. I didn't have the "fateful encounter" marked for any of them.

**Comment by kamronbatman** [comment]
That Absol has a special algorithm

**Comment by kamronbatman** [comment]
@greenDarkness, You can download grab a 5th anniv egg [here](https://github.com/projectpokemon/EventsGallery/tree/master/Gen%203/JPN/5th%20Anniversary%20Eggs)
