### ISSUE TITLE
Ribbon legality error of Glaile from oras demo version

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1335]
Hi,
Testing PKHeX Build 3562 and latest official build of PKHeX, I have come across a legality error (Invalid:Missing Ribbon:Classic) in one of my event pokemon, Glalie from ORAS special demo version.

It does not have a classic ribbon and is legit [without any ribbons](https://bulbapedia.bulbagarden.net/wiki/List_of_game-based_Pok%C3%A9mon_distributions_in_Generation_VI#Glalie)

[362 - Glalie - 7E6DA287599F.zip](https://github.com/kwsch/PKHeX/files/1149803/362.-.Glalie.-.7E6DA287599F.zip)

I don't remember "touching it" at all, especially the ribbons, it has been over a year since I last used it, then I forgot it existed.

Thanks

**Comment by kwsch** [comment]
Thanks!

https://github.com/kwsch/PKHeX/commit/dc0a43ae8ffd16ba39f81a03d605b00c4958e1cd
