### ISSUE TITLE
[Bug] MGDB WC3 Eggs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1337]
Similar to my other issue, any WC3 that is currently an Egg is illegal. Common legality errors that come from them:
- Eggs cannot have modified PP counts (all Moves PP are set to 0)
- Invalid Egg Hatch Cycles (Hatch Counters are all set to be 70, same issue as described in #1331)

In some cases, there are Pokemon with Met Levels that are not 0 (Pichu, Igglybuff, Surskit, etc.).

In the case of Pokemon with the PID Method BACD_x, PKHeX expects Method "None".
Likewise, it also states that their Base Egg Moves are missing.

I'm pretty sure this covers most of the WC3 bugs.

**Comment by kwsch** [comment]
Some events with only 1 move defined (that have other undefined moves) show up as legal; obviously as an egg it's not valid but it's gen3. If someone adds the natural moves for those cases it'll behave properly.
