### ISSUE TITLE
[Feature Request] Option to Dump the Entire MGDB to a folder

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1338]
Would be very useful for legality checking species in the MGDB, and for bug reports, rather than having to View every individual slot in multiple different PKM formats (transfer-based legality checks)...

Ideally, it would work like saving Gifts are; allow for the user to either dump them all as PKM files, or as Gift files (WC3, PGF, PGT, PCD, etc.).

**Comment by kwsch** [comment]
?

![image](https://user-images.githubusercontent.com/6393368/28245390-7f3e257e-69ba-11e7-999e-a4f800032525.png)

**Comment by sora10pls** [comment]
The clipboard icon mislead me into thinking that's not what that feature did. My bad.
