### ISSUE TITLE
Legality Question / Bug

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1342]
Working with a Clefable with this spread

Clefable (F) @ Leftovers
EVs: 252 HP / 252 Def / 4 SpA
Ability: Magic Guard
Level: 100
Shiny: Yes
Bold Nature
- Thunder Wave
- Moonblast
- Soft-Boiled
- Flamethrower

[Clefable (Legal).zip](https://github.com/kwsch/PKHeX/files/1151478/Clefable.Legal.zip)

Being that it is a 3rd gen Pokemon, Has a Bold nature and a 6IV spread it should pop up as illegal based on nature pid mismatch but shows as legal even after many PID re rolls.

Unsure if I'm taking crazy pills or this is a bug. According to RNGReporter, it shouldn't be possible.

**Comment by kwsch** [comment]
```
Legal!
===

Valid Move 1: Learned by TM/HM.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up in Generation 3.
Valid Move 4: Learned by TM/HM.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Fishy: 2 EVs remaining.
Valid: Able to hatch an Egg at Met Location.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: History block is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Egg (Cleffa)
PID Type: None
```

'tis bred
