### ISSUE TITLE
Legality Issue : Gen VI (AlphaSapphire) with ribbon

### ISSUE THREAD

**Issue by 1412kaito** [kwsch/PKHeX#1343]
<img width="457" alt="ribbon" src="https://user-images.githubusercontent.com/29736675/28320368-9fe9d5a6-6bfa-11e7-876d-c9fad4613709.PNG">
I got the ribbon in-game, from talking to a woman IIRC in Mauville City
I found one _closed_ issue post here about ribbons (this one (https://github.com/kwsch/PKHeX/issues/1276), so I figured that the issue should have been fixed at this point?

**Comment by kwsch** [comment]
Using the latest release or the latest commit, I am not able to replicate the issue.

There's probably something else wrong with it that is causing it to get flagged, like it originating from X/Y without having the Handling Trainer set (which would be illegal). Would need to see the pkm.

**Comment by 1412kaito** [comment]
[issue.zip](https://github.com/kwsch/PKHeX/files/1159776/issue.zip)
all six were in my party when I talked to the woman
and if it matters, I have edited their EVs and IVs, but they were showing up as legal before :)
thanks for the quick response!

**Comment by architdate** [comment]
Using the latest commit of PKHeX the `Doge` Pokemon that you were editing is atleast legal so far (No ribbon issues encountered) Once I am free I can test the other pokemon although I am fairly certain that the mons are legal right now. Are you using the latest release/commit of PKHeX?  @1412kaito

**Comment by 1412kaito** [comment]
@architdate I think I am...
when I open PKHeX there is an About window that pops up... 
<img width="372" alt="drag" src="https://user-images.githubusercontent.com/29736675/28470941-9437366e-6e65-11e7-8462-1afc06f21805.PNG">
i think I downloaded this from teamcity about a week or so ago
anyway, if it's showing up legal on yours, I guess the issue is on my side. I'll try deleting PKHeX and getting a fresh one and see if that fixes it. Thanks!

**Comment by 1412kaito** [comment]
Update : 

I deleted PKHeX, and then downloaded PKHeX Build 3586 from teamcity, and my Pokemon are shown as Legal now. 
<img width="448" alt="legal" src="https://user-images.githubusercontent.com/29736675/28492801-3133f690-6f34-11e7-812d-921468007237.PNG">
