### ISSUE TITLE
Not sure if PKHeX issue or WC issue

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1344]
Shows Illegal in PKHeX (latest Commit)

Showdown template of Pokemon
다크라이 (Darkrai)
IVs: 16 HP / 26 Atk / 19 Def / 23 SpA / 28 SpD / 11 Spe
Ability: Bad Dreams
Level: 50
Gentle Nature
- Roar of Time
- Spacial Rend
- Nightmare
- Hypnosis

Error Report

Invalid Move 1: Invalid Move.
Invalid Move 2: Invalid Move.
Invalid: Non Platinum Darkrai from Newmoon Island. Unreleased event.
Invalid: Encounter Type PID mismatch.

Valid Move 3: Learned by Level-up.
Valid Move 4: Learned by Level-up.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Fishy: All EVs are zero, but leveled above Met Level.
Fishy: Current experience matches level threshold.
Valid: Ability matches ability number.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: Skipped History check due to other check being invalid.
Valid: Geolocation: Country is in 3DS region.

Encounter Type: Static Encounter (DP) (Darkrai)
PID Type: None

--- Hanguk Darkrai KOR [PPorg].pgt
[Hanguk Darkrai KOR [PPorg].zip](https://github.com/kwsch/PKHeX/files/1156412/Hanguk.Darkrai.KOR.PPorg.zip)

![image](https://user-images.githubusercontent.com/18354599/28326157-8d20d112-6bba-11e7-9152-371ddd1600b5.png)

**Comment by kwsch** [comment]
The gen4 encounter generator checks for event data first, so I assume something is preventing that event from being matched. Is it in the PKHeX mystery gift database? PKHeX only uses PCDs from the event gallery.

**Comment by Odaxis** [comment]
It is in the Mgdb folder, directly downloaded from the Project Pokemon Events Gallery

**Comment by kwsch** [comment]
The gen4 matcher only uses pcd files (OfType<PCD>>), as it has game compatibility data. PGT files are ignored

**Comment by kamronbatman** [comment]
@kwsch, I can make placeholder PCDs for the ones we are missing and the next release just pull from the github gallery. Does that work?

**Comment by kwsch** [comment]
@kamronbatman yes, can just use fabricated data.

* game compatibility data 
* card name for `EncounterMatch.Name` display

don't make one for ranger manaphy

**Comment by architdate** [comment]
@kamronbatman an elegant solution would be pulling from the pporg Event Gallery GitHub using a script, just gotta add an option to pull in the menu and run a git clone to the same directory PKHeX + rename that to mgdb, would also solve #722 . I may send a PR to do this soon actually

**Comment by architdate** [comment]
This would however require extrenal code from repositories like https://github.com/octokit/octokit.net which are of course licensed under MIT license.

**Comment by kamronbatman** [comment]
@kwsch and I have decided the natural progression is for PKHex to pull events _directly_ from the pp.org event gallery.  I am almost done making a file that will serve as a guide for a program that will create an index file.  That index file will be used by PKHex to download/update WCs.

As for the missing PCDs, I haven't had time to do it yet.  I'll keep everyone updated.

**Comment by kwsch** [comment]
Closing, issue & resolution unrelated to PKHeX.
