### ISSUE TITLE
Gen 2 Odd Egg

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#1346]
https://bulbapedia.bulbagarden.net/wiki/Odd_Egg

Dizzy Punch is showing up as invalid egg move for all of those Pokemon
![odd egg 1](https://user-images.githubusercontent.com/12572974/28338689-b802a8ca-6bd7-11e7-8a2c-82901f326897.PNG)
![odd egg 2](https://user-images.githubusercontent.com/12572974/28338690-b804a09e-6bd7-11e7-9eef-033ba3ac3620.PNG)

**Comment by sora10pls** [comment]
Probably related: #1245

**Comment by NinFanBoyFTW** [comment]
I am the one who made the other issue. I see your on the latest version so Im not sure but for my game the pokemon are coming up as legal now, so I dont know if you cheated for these or something but the problem doesn't seem to be happening since june 18th when the problem was "fixed"

**Comment by Ninjistix** [comment]
not sure what was changed but just rebuilt from the most recent commit and they are coming up legit now

**Comment by Ninjistix** [comment]
![capture](https://user-images.githubusercontent.com/12572974/28345377-093059ca-6bf8-11e7-85f4-48aa8a884123.PNG)
