### ISSUE TITLE
Gen 2 legality issues

### ISSUE THREAD

**Issue by Temmie45** [kwsch/PKHeX#1348]
For Gen 2 save files event exclusive moves are being flagged as illegal such as crunch on charmander. Edit: Never mind the milk drink thing it fixed itself

**Comment by kwsch** [comment]
Gen2 GB events are un-implemented besides Stadium encounters.
https://github.com/kwsch/PKHeX/blob/3b8643bc77bf46225ed6a5f4ac74a42e039dbd7d/PKHeX.Core/Legality/Tables2.cs#L96-L118
