### ISSUE TITLE
SAV1 & SAV2 Nickname "Issues"

### ISSUE THREAD

**Issue by TheKonqa** [kwsch/PKHeX#1349]
So i was in the progress of backing up/extracting pokémon out of german saves from yellow and crystal when i stumbled upon the fact that when you uncheck the nickname on a pokémon it changes the displayed & ingame nickname to the english name instead of the selected language equivalent.
This seems to be the case for other languages in PKHeX aswell.

Using SAV3 and onward type games like leafgreen/firered or sun/moon the function works likes a charm and the pokémons nickname is "reset" correctly.

**Comment by kwsch** [comment]
>selected language equivalent

pkm language selection is not visible for gen1/2 games; the language will be set to whatever the last language was before the save was loaded

![image](https://user-images.githubusercontent.com/6393368/28394903-126f78c4-6ca5-11e7-8a77-3ae28a8759c3.png)

**Comment by architdate** [comment]
This might actually be impossible to achieve for the following reasons.
- The games do not have a language setting like kwsch pointed
- There is no language setting in the trainer info as well.
- The games themselves not being multi language probably do not have multiple language support inside them which would mean that a non nicknamed japanese mon from a japanese Gen 1/2 game may be english based when it comes to an english game after a trade [Speculation, hope that someone tests this]
- If what i said above is the case, not giving it a nickname and just setting the mon as it is would change the name of the pokemon to the games native language for Gen 1/2
