### ISSUE TITLE
Suggestion: auto-fill hatched egg location data 

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1350]
Unchecking the "is egg" box should automatically set a correct met location, preferably using the the daycare location in the corresponding game: Route 117 in RSE, Four Island in FRLG, Solaceon Town in DPPt, Route 34 in HGSS, Route 3 in BW/B2W2, Route 7 in XY, Battle Resort in ORAS (because no one uses Route 117 lol), and Paniola Ranch in SM. In gen 6, the OT memory should also be automatically set to "{0} hatched from an egg and saw {1} for the first time at {2}" with the location "a riverside road" in XY or "a battling spot" in ORAS.

For traded eggs, egg met location should be changed from "Nursery helpers" to "a Link Trade (Egg)" and met location proper should be changed from "a Link Trade (Egg)" to the appropriate hatching location (yeah, for some reason it's backwards when the egg is unhatched, nice coding Game Freak). The OT/ID/SID and origin game* should also change to match the current save file (if the egg isn't set to a save, use the open save file if one exists, otherwise just keep the existing data).

*I seem to recall traded eggs keeping their origin game even after hatching in a different version in a previous gen, but that doesn't seem to be the case anymore in gen 7. Not sure at what point it was changed (if at all) or if I'm just confusing it with language or something.

**Comment by architdate** [comment]
To clarify this would set Egg Met locations and Memories if applicable correct? This is in-fact doable and I do not mind submitting a PR for this. However, what is your reasoning behind those specific egg locations? The eggs can be hatched in any location. A dedicated index for CB_MetLocation would be much more cleaner as compared to having a list of regions where the Day Care centre is actually located. What do you think @kwsch ?
