### ISSUE TITLE
Gen 6 native Zygarde form legality

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1351]
Zygarde originating in gen 6 should be legal in 10% Forme with Power Construct, as the Zygarde Cube can change Power Construct Zygarde between its two forms.

**Comment by kwsch** [comment]
Contradicts https://github.com/kwsch/PKHeX/issues/933

**Comment by sora10pls** [comment]
So the only disallowed Forme for Zygarde with Gen 6 Origin is 10%-C. From Bulbapedia:

>The Zygarde Cube can freely change the form of a **Power Construct Zygarde** between 10% Forme and 50% Forme.

**Comment by architdate** [comment]
```
if (pkm.Species == 718 && pkm.InhabitedGeneration(6) && pkm.AltForm == 1)
    return false;
```
should fix the above issue, may send a pull request regarding the same.

**Comment by architdate** [comment]
The above only marks 10% form as illegal (as @sora10pls suggested) Every other form should have legal forms.
