### ISSUE TITLE
[Request] Withdraw/Deposit PKMN

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#1352]
this was requested before along with #295, but would it be possible to be able to right click deposit/withdraw, without having to do click view > click set?

while playing on emulator's and editing sav's on the fly, it takes awhile to clear pkmn out from your party having to view>set each of them into an open box space, or trying to remember which pkmn you just copied out from your box

Ideally, it would be deposit pkmn to first open box space, or withdraw pkmn from box to first open party space (unless all boxes/party spots are full ofc)

**Comment by kwsch** [comment]
Double click the box tab to bring up an auxiliary box view.
Drag from party to the desired box slot.

**Comment by Ninjistix** [comment]
@kwsch Thanks, wasn't aware that it was possible to move pkmn from the Box Viewer/Party, but would it be possible to add a sort button to the Box Viewer? it Only has a switch to last box button

**Comment by kwsch** [comment]
Refer to the shortcuts, you can sort/clear boxes.
