### ISSUE TITLE
Help! leech seed oddish Pkhex

### ISSUE THREAD

**Issue by Cackletta** [kwsch/PKHeX#1356]
![oddish bug](https://user-images.githubusercontent.com/30359571/28486535-8d69bf88-6e50-11e7-93e7-241b4b1a7462.png)
#

I try to create an oddish of a 3rd Generation event and when placing leech seed I get the message on the grid

**Comment by kwsch** [comment]
GitHub issues are not for requesting help regarding making something legal.
