### ISSUE TITLE
Korean recognition problem in 4th generation save file

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#1357]
The Korean "가" displayed in the pkhex of the 4th generation save file is displayed as "?" In the game.
If you edit "각" instead of "가", "가" will be displayed normally in the game.

Add
Korean displayed in pkhex      →                   Korean displayed in 4th generation game
강                                             →                                          갔 
갑                                             →                                          감
갈                                             →                                          갇

**Comment by kwsch** [comment]
[relevant section for gen4 char tables](https://github.com/kwsch/PKHeX/blob/fb9dd6103dea6dbde65113814bc62423104b78b7/PKHeX.Core/PKM/PKX.cs#L1519-L1867)

**Comment by kamronbatman** [comment]
@host1126 - Is that a full list of **all** hangul that do not display properly?
@kwsch - Do we need someone to PR this?

**Comment by host1126** [comment]
It's not full list

**Comment by kamronbatman** [comment]
@host1126 - Do you believe you could make a complete list so we can properly fix this?

**Comment by host1126** [comment]
@kamronbatman Since there are more than 10,000 combinations of all Hangul, it is hard to make a full list.
But the cause of the error is certain. 
The following letters are arranged in the order of Korean arrangement.
가 각 간 갇 갈 
If you enter this in pkhex and check it in the 4th generation game, it will be displayed as follows.
?  가  각 간 갇
As a result, the previous letter of the letter entered in pkhex is displayed in the game.

**Comment by kamronbatman** [comment]
Ah so it is an off-by-1 error. @kwsch - Is this enough info to look into a fix?

**Comment by kwsch** [comment]
this is the raw table:

https://pastebin.com/raw/1YG1gHHe

sourced from [here](https://github.com/kwsch/PKHeX/blob/24703bfc2235e1cf850086c22f69463b65fe7298/Misc/pk2pk.cs#L1116-L1127), original link (nopaste) is dead
