### ISSUE TITLE
GitHub Repository's ProjectPokemon URL is Broken

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1360]
Didn't know where else to put this so...

The URL featured [next to the repo's description](http://projectpokemon.org/pkhex/) leads to a 404 error. The actual [URL to the thread](https://projectpokemon.org/forums/forums/topic/29182-pkhex-gen-1-7-savpkm-editor/) works fine, though.

**Comment by evandixon** [comment]
Fixed on the server side, sorry for the inconvenience
