### ISSUE TITLE
Swarm Seedot flagged as illegal

### ISSUE THREAD

**Issue by egzonqj** [kwsch/PKHeX#1362]
Not sure if this has been issued before but I thought I had to.

So I got lucky and a Seedot swarm happened in my Emerald cartridge (I wanted to catch it for my livingdex but that 1% appearance rate sucks). 

I got to catch a few of them and wanted to check it's stats in PKHEx, and then noticed that they were flagged illegal.
![image](https://user-images.githubusercontent.com/5099644/28576767-127c3a46-7155-11e7-8286-1be2ab049544.png)
![image](https://user-images.githubusercontent.com/5099644/28576775-17c0ca76-7155-11e7-83c1-461125450bed.png)

They certainly are encountered this way with Leech Seed learned, that's something also stated in [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_outbreak#Generation_III). 

Uploaded the pk3 file if needed
[273 - SEEDOT - C8E4DF97498D.zip](https://github.com/kwsch/PKHeX/files/1173433/273.-.SEEDOT.-.C8E4DF97498D.zip)

**Comment by javierhimura** [comment]
Leech Seed is the problem, is not implemented in PKHex for Swarm Seedot and Nuzleaf in Emerald.
I suppose the egg move can only be learned in Emerald Swarms. but Seedot and Nuzleaf can be a swarm encounter in Ruby Sapphire via record mixing

**Comment by egzonqj** [comment]
Oh I see, guess I'll let them be this way atm, thanks!
