### ISSUE TITLE
pkhex "Time Capsule" feature?

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1363]
Hi I wanted to know if it would be possible to add a feature to put pokemon not only from one gen to the next but from one gen backwards to a previous gen. I know it may sound stupid but I think it could be really good for a few reasons. I have most of my pokemon from when I was a kid transfered to gen 7, leaving all of my old pokemon games empty. Obviously im not a programmer like you so I dont know how hard it would be to do this but it seems like it would be easy to just have it so that pokemon in later gens can be converted back to any gen up to the gen they were caught in. EX: a charmander caught in gen 3 that is in gen 7 could be transferred all the way back to gen 3 but a charmander caught in gen 5 (you would obviously know by the met game) could only be transferred through gen 6 and 5. I have tried this with a few pokemon (zapdos, articuno... etc) and it works perfectly. I just copy all of the info from the pokemon (pid, nature, level, IV/EVs, TID, moves) the only thing I could see being a problem is if the pokemon has moves or something like that, that wasnt in the original games, or the location of the original pokemon which people would just have to make up. I dont think that would be a huge problem though because you could probably just have anything that wasn't in the gen you are transferring it to revert to a default or for things like moves just have the moves go back to nothing.  Like I said I know it sounds dumb but testing it with a few pokemon it seemed easy. for 200 pokemon+ it wouldn't be so easy though. I think this could work in the same way pokemon was able to make the time capsule for gen 1/2. I know the data for those games were much more simple (no ribbons,natures,locations...) but I think this could be usefull to people who may have even done simple things like transfered pokemon from gen 6 pokebank to gen 7 and cant bring those pokemon back. Thanks

**Comment by javierhimura** [comment]
Kaphotics has made a Time Capsule application that uses the PKHex Core but it is a separate application because most pokemon transfer with this tool will be illegal
https://github.com/kwsch/pk2pk

**Comment by NinFanBoyFTW** [comment]
Ok cool this looks good. The only thing though is that this doesn't support gen 7 (gen 7-6) and obviously it would be nice to be able to just drag and drop pokemon from my diamond save into my fire red save and have it do essentially thew same thing.

**Comment by NinFanBoyFTW** [comment]
Actually I just tried the tool and it only lets you go forward a generation, not backwards

**Comment by kwsch** [comment]
The linked tool does backwards conversion fine; you have to recompile from source as the old GUI only supported 4->6
