### ISSUE TITLE
Air Cutter is not a valid Gen6 tutor move for zapdos

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1364]
The fix should be editing the binary resource file called personal-ao inside the Util folder (in the Core project). If its not fixed by the time I'm back from work, I can also submit a pull request :) just wanted to give a headsup. 

P.S. This may also mean that there may be issues with Gen6 tutor move legalities in general. (Have not researched in that regard)

**Comment by kwsch** [comment]
https://bulbapedia.bulbagarden.net/wiki/Zapdos_(Pok%C3%A9mon)/Generation_VI_learnset#By_tutoring

![image](https://user-images.githubusercontent.com/6393368/28604405-53f4d242-717f-11e7-910a-a1fd2efcde28.png)

**Comment by architdate** [comment]
What i meant is that PKHeX is legalizing this (Air cutter being a gen 6 tutor move) @kwsch I'll upload a PK7 file for your reference.

[145 - Zapdos - 7DAE7DA8B731.zip](https://github.com/kwsch/PKHeX/files/1175580/145.-.Zapdos.-.7DAE7DA8B731.zip)

Here is the legality as shown (verbose)
```Legal!
===

Valid Move 1: Learned by Move Tutor in Generation 6.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Move 4: Learned by Level-up.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Valid: Valid gift/static encounter.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: History block is valid.
Valid: OT Memory is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Static Encounter (Zapdos)
PID Type: None```
