### ISSUE TITLE
pokemon gen 4 legality issues

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1365]
Hi so Ive been trying to catch every single pokemon legit so that I can have a completely legit collection of pokemon. I legally caught every form of unown in pokemon fire red including the ? and ! forms. I just transferred them into my platinum save and it is giving me the same error I have had in the past. invalid encounter type PID mismatch. I caught all of these unown legitimately (not even copy and pasting them with their new forms) and I haven't changed them at all. Ive had this problem before with pokemon that I know I haven't cheated with so Im just wondering why these errors keep coming up. I spent over an hour in fire red catching the unown forms and now its saying they are illegal so its a little frustrating. Thanks

**Comment by NinFanBoyFTW** [comment]
this also seems to be happening with the pokespot pokemon from xd as I noted in another issue

**Comment by kwsch** [comment]
Wild capture unown in gen3 have a special PIDIV method (1/2/4 Unown).

Can't tell if there really is a problem without seeing pkm files.
