### ISSUE TITLE
Chained shiney in 4th Gen raise Encounter type PID mismatch

### ISSUE THREAD

**Issue by ProPaint** [kwsch/PKHeX#1366]
I know that this shiney is legit at 100% but it raise Invalid:  Encounter type PID mismatch.
I have a bunch of other chained shiney that raise the same issue.
[362 ★ - ONIGLALI - 22C83454437F.zip](https://github.com/kwsch/PKHeX/files/1177505/362.-.ONIGLALI.-.22C83454437F.zip)

**Comment by kwsch** [comment]
Works fine on latest commits.
