### ISSUE TITLE
drifloon legality issues

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1368]
Hi. I just wanted to let you know that drifloon can only be found in diamond/pearl/platinum on Fridays. When I set a drifloon that I caught at the valley windworks to any date that isnt a friday, it doesnt flag the pokemon. This only effects gen 4 and obviously not with breeding. Thanks

**Comment by kwsch** [comment]
Boot game on friday, sit in front of NPC for >24h. NPC does not disappear during a date-change.
