### ISSUE TITLE
Error in latest commit?

### ISSUE THREAD

**Issue by xXAquaNightXx** [kwsch/PKHeX#1374]
Um what happened in the latest commit? All pokemon nicknames changed to numbers and flagged illegal.
![um](https://user-images.githubusercontent.com/24309423/28833183-94261718-76ac-11e7-8665-20893d9f3e5e.png)
![um2](https://user-images.githubusercontent.com/24309423/28833188-97f43b90-76ac-11e7-9f2e-cfb769471b55.png)

Toggling nickname fixes the numbers but will still flag illegal unless nickname remains checked.

![um3](https://user-images.githubusercontent.com/24309423/28833375-277da33c-76ad-11e7-8a46-bac2de426fa7.png)

![um4](https://user-images.githubusercontent.com/24309423/28833397-381f3322-76ad-11e7-9090-12aaa35804f3.png)

**Comment by kwsch** [comment]
Will fix later today, recent string conversion refactor uses a stringbuilder which apparently is treating each char as a literal string.

**Comment by Ninjistix** [comment]
I was just about to report, this issue with my Sun save, all names have been converted to numbers...
