### ISSUE TITLE
[Bug] D/P Static and Gift PKM

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1375]
Due to the recent refactoring commits, any and all static or gift PKMs originating from D/P are flagged as illegal. Does not seem to happen with any other games.

Below shows a Box including most of the D/P static and gift PKMs, and this Blissey (from the Happiny Egg) is flagged with an Encounter Type PID mismatch, and an illegal move.
![image](https://user-images.githubusercontent.com/17801814/28837269-263688b0-76ba-11e7-9d1c-16525e1a9886.png)

Everything else is flagged with "Unable to match an encounter from origin game".

**Comment by kwsch** [comment]
```
StaticD = GetStaticEncounters(Encounter_DPPt, GameVersion.B);
StaticP = GetStaticEncounters(Encounter_DPPt, GameVersion.W);
```
find the bug, lmao

**Comment by sora10pls** [comment]
LOL

I'll submit a PR in a sec
