### ISSUE TITLE
Legality errors in latest commits

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1377]
Hi, 

I tested generations 3,4,5,6,7 and come up with various legality errors with **PKHeX Build 3617**

**Gen 3**: all OK

**Gen 4**:
**HeartGold**

_Pokewalker Pokemon_
Some of the pokewalker pokemon dont have the Pokewalker PID:
Pikachu:Encounter type PID mismatch + PID:None(instead of Pokewalker
Venomoth:Same
Poliwag:Same
Shelder:Same
Onix:same
Horsea:same
Carvanha:same
duskull, dusclops:same
++ I will throw inside the .zip a metang from Pokewalker that is shows as legit.I don't know with the others lost the PID, I obtained them myself

_National Park pokemon_
Butterfree:Can't have ball for encounter type
Beedrill:Unable to match an encounter from origin game + Encounter type: invalid
Ninjask: same as beedrill
Pinsir(SHARP):same
Scyther:same

[HeartGold Pokemon.zip](https://github.com/kwsch/PKHeX/files/1191611/HeartGold.Pokemon.zip)

**Gen 5**:

**White**

Gen 4 in-game trades(platinum)
[gen 4 to gen 5.zip](https://github.com/kwsch/PKHeX/files/1191622/gen.4.to.gen.5.zip)

**Gen 6**:

**Alpha Sapphire**
 Egg-Move missing in a lot of pokemon
I will provide an example of some, inside the .zip file

There is also a legality error with a JPN event Greninja that says: Form Count is out of range. Expected <=0, got 0
[Alpha Sapphire Pokemon.zip](https://github.com/kwsch/PKHeX/files/1191631/Alpha.Sapphire.Pokemon.zip)

Thanks

-kwsch edit: removed content associated with other (recently fixed) issues

**Comment by sora10pls** [comment]
D/P static encounter bugs were already fixed by my recent PR.

**Comment by xXAquaNightXx** [comment]
There seems to be a legality error with the relearn moves from GEN 6 and 7 pokemon , it looks like its not reading the first relearn slot

![err1](https://user-images.githubusercontent.com/24309423/28847029-b55c9aea-76db-11e7-86cf-0ca6a170d4ca.png)

And if you fill in the second slot its legal

![err2](https://user-images.githubusercontent.com/24309423/28847036-c4e16324-76db-11e7-94f9-e3200b1eac20.png)

Same with user's pokemon above moving
![err3](https://user-images.githubusercontent.com/24309423/28847056-dd627f6e-76db-11e7-8fee-f9416848ac84.png)

**Comment by PrometheusG** [comment]
Hi,
Just a small update testing PKHeX build 3624:

**Gen 4- HeartGold- PID spiky ear pichu**

Spiky ear pichu shows PID type:Pokewalker insted of none, like the previous build.If I reroll the PID it shows as none but it will make the pichu illegal I think
I am also adding a beldum and a metagross(leveled up and evolved) from winner's path Pokewalker route that I forgot to put in the .zip file that were legit before PKHeX build 3624 and 3617, it doesn't matter, I know but you can keep them if you need to check anything else.

**Gen 7 - Moon - In-game trades - wc6 JPN greninja**

I also noticed that gen 6 greninja JPN event is fixed in AS but the error remains in Moon(Invalid: Form Count is out of range. Expected <= 0, got 0.)

Some in-game trades in moon throw an error too, a memories tab error.The memories with OT show:"The Pokémon seems to have a good memory, but it doesn’t seem to be able to remember..." 
If I change the memory to this (I take alola golem as an example,it is provided inside the .zip file as well as all in-game trades): "Veler met Sill at... a cave. Sill threw a Poké Ball at it, and they started to travel together. The Pokémon remembers that its feelings were indescribable."

Also that alola golem sometimes when I click on it it throws an excpetion error, the same as issue 1378 so I will not expand myself on that error

Thank you

[gen 4 -  gen 7 files.zip](https://github.com/kwsch/PKHeX/files/1193281/gen.4.-.gen.7.files.zip)
