### ISSUE TITLE
There is a very complete program for editing 4th, 5th and X/Y save files and it even has a small legality checker

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#138]
Unfortunately, the developer ceased development and decided to release the source code.
The source code is in [this thread](http://digiex.net/downloads/download-center-2-0/nintendo-ds-content/pokemon/14716-pikaedit-gen-4-gen-5-xy-download-pokemon-diamond-pearl-black-white-save-editor.html). It may be useful for you in case you didn't know about it.

**Comment by SciresM** [comment]
Pikaedit is known and very poorly written.

**Comment by poutros** [comment]
Ok then.
