### ISSUE TITLE
[Bug] Gen 4 Special Wallpapers

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1381]
Under the Categories "FRIENDS 1" and "FRIENDS 2" in-game, PKHeX does not recognize them at all.

Wallpaper "DISTORTION"
![image](https://user-images.githubusercontent.com/17801814/28971797-5ca9a754-78fb-11e7-8c08-e7cd3ef65893.png)

Wallpaper "TEAM GALACTIC"
![image](https://user-images.githubusercontent.com/17801814/28971827-81afcc0e-78fb-11e7-8eae-9e4fc7613fc6.png)

For testing, you can use [this tool](http://www.filb.de/games/tools/aikotoba) to unlock the special wallpapers.

**Comment by sora10pls** [comment]
Seems to only affect Platinum. D/P and HG/SS are fine...

Wallpaper "LEGEND"
![image](https://user-images.githubusercontent.com/17801814/28972278-06900a3c-78fd-11e7-9d1b-7adaa6960269.png)

Wallpaper "SOUL"
![image](https://user-images.githubusercontent.com/17801814/28972125-7ddb189e-78fc-11e7-8b5c-99f63ce9fbc7.png)

**Comment by sora10pls** [comment]
P.S. Pichu as detailed is still falsely flagged as illegal, as mentioned in #1377. PKHeX seems to think it's from Pokewalker ;)

![image](https://user-images.githubusercontent.com/17801814/28972338-5e0a9e58-78fd-11e7-9c6e-44b9f8756e68.png)

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/28976931-b8ecbde6-78f4-11e7-88d4-bce624233ff0.png)

dunno if the save is hacked, but would need to know if the wallpaper bytes it's retrieving are abnormal. HGSS does something odd for the special wallpapers, maybe there's something similar for Pt
`InvertHGSSBoxWallpaperAlias`

**Comment by sora10pls** [comment]
Save file isn't hacked, though when I checked it in Box Layout, it displayed "SPECIAL 8" even though as shown in my first post, it was "DISTORTION" in-game and Gen 6/7 "Simple" in PKHeX.

I can send the save file when I'm home.

**Comment by sora10pls** [comment]
[plat.zip](https://github.com/kwsch/PKHeX/files/1202098/plat.zip)
