### ISSUE TITLE
Legality issue for Avalanche teachable only in gen IV.

### ISSUE THREAD

**Issue by Monkfishy** [kwsch/PKHeX#1384]
Not sure if the right place to post. But some Pokemon that can only learn Avalanche in Gen IV by way of TM are throwing legality errors for that move. This happens with Blastoise, Nidoqueen, Aggron and likely others. However at the same time, this doesn't happen with other Pokemon that can only learn Avalanche through Gen IV TM, such as Kangeskhan.

![aggron](https://user-images.githubusercontent.com/30848216/29099845-a15540e6-7c9f-11e7-9411-acd85ce27e35.png)

http://www.serebii.net/pokedex-xy/306.shtml - See Transfer Only Moves

![kangeskhan](https://user-images.githubusercontent.com/30848216/29099850-a434593c-7c9f-11e7-8c14-3a2218d21184.png) (side note: no idea why this doesn't throw an encounter PID legality error, considering I didn't generate a valid gen IV PID for its IVs/Nature)

http://www.serebii.net/pokedex-xy/115.shtml - See Transfer Only Moves

**Comment by xXAquaNightXx** [comment]
![lol](https://user-images.githubusercontent.com/24309423/29101847-1eef994c-7c83-11e7-9c99-a8fe1b43ae43.png)

Its working for me

**Comment by xXAquaNightXx** [comment]
Try changing Met Level to 100

**Comment by kwsch** [comment]
You shouldn't suspect a 'bug' if the pkm was originally hacked ;)

**Comment by Monkfishy** [comment]
Haha oh that was so dumb of me. Met level had to be 100. I guess PkHex has changed a lot since I last used it. >_<

**Comment by kwsch** [comment]
The last line of the popup tells you why: there is no PIDIV relationship for Gen4 eggs, thus there is no chance for a "PIDIV method mismatch". Still needs to have the correct nature (PID%25) if transferred onward.
