### ISSUE TITLE
Pokemon Pearl Italian Version strange behaviour after import

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#1385]
I tried starting an egglocke using another save's Pokémons on my Pearl version.
I Dumped all boxes and Imported them back, as you can see in the -1 version of the .sav...

But my Pokédex has been strangely updated and it has 51 registered Pokémons... And looking at Chansey's entry crashes the game. What's going on?
[bak.zip](https://github.com/kwsch/PKHeX/files/1212738/bak.zip)

**Comment by kwsch** [comment]
Are you using the latest release? [Things have changed](https://github.com/kwsch/PKHeX/commit/04a11ae03029ca2a28a2d085aa4506c9ac0edd4c) since the 07/02/17 release.

**Comment by Lorenzooone** [comment]
https://projectpokemon.org/forums/files/file/1-pkhex/
I used this one, so it should be updated.
I tried to see if it was a cartridge problem by putting in my team a Chansey, but it's loaded fine there... It just crashes in the dex.

**Comment by kwsch** [comment]
The program was updated <48 hours ago; I wasn't able to replicate on the latest release.
You can disable pokedex setting via the Options->Set to SAV menu items.
