### ISSUE TITLE
[Feature Request] Import QR codes from file

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1386]
Hello,
Is there anyway you'd consider adding the ability to drag QR codes directly into PKHeX to import them? 
Thank you for reading this, and for all your work with PKHeX.

**Comment by kwsch** [comment]
copy url to clipboard, alt click the preview sprite (see shortcuts)

**Comment by kwsch** [comment]
QRs aren't meant to be a replacement for saved pkm files; they're meant to be an easy way to share them online.

Image processing is a bit far from PKHeX's scope, thus PKHeX uses online APIs to decode QRs. Just upload the image to imgur then have it decode from that URL.

**Comment by greenDarkness** [comment]
Ah, I understand.

Thanks for taking the time to give me an explanation.
