### ISSUE TITLE
gen 1 and 2 time capsule legality error

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1393]
Hi. I am trying out moving pokemon back and forth using the time capsule and using pkhex to directly move pokemon from gold/silver to red and blue. I am getting a bunch of different legality errors when doing this. I will just include a couple of samples to show you but one problem is with "illegal moves". Many moves show up as illegal. For the most part this is because gen 2 changed what level many pokemon learned certain moves (gen 1 Rhyhorn learns fury attack at 40. Gen 2 Rhyhorn learns fury attack at 19. I dont know if this can be solved very easily because obviously met data wasnt introduced until crystal so im not sure how you could possibly make a legality system for gen 1 or 2 besides legal moves or levels. It seems like there are too many variables without any data (ex #1221 ) Thanks

**Comment by kwsch** [comment]
Post any PKM files, you know the drill.

**Comment by NinFanBoyFTW** [comment]
[gen 1 pokes.zip](https://github.com/kwsch/PKHeX/files/1216922/gen.1.pokes.zip)
these were all in my pokemon gold and I moved them to pokemon red. im not sure if some f them would not have transfered through the actual emulator because of move differences or whatever but even so. That isnt the only problem coming up for them. Also Im sure you can tell but they were completely legit in gen 2.

**Comment by kwsch** [comment]
All show up legal in RBY if you specify Physical Cartridge & Allow Tradebacks.
