### ISSUE TITLE
Rare Ability Index bug

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1394]
So this is super rare, and hardly happens, but hopefully can be fixed... I'm uploading a Kartana file which is perfectly legal but is marked as illegal. The legality says legal if i choose any other ability and go back to my original ability again
For example: Ability(1) Beast Boost (illegal before)
 > Change it to Beast Boost(2)
 > Change it back to Beast Boost(1)
Fixed????

I mean the fix is fairly simple when implemented manually, but it would be amazing if this case is eliminated altogether :)

**Comment by architdate** [comment]
Closed by mistake

**Comment by architdate** [comment]
Just had a similar issue with Skarmory, however this time the issue is fixed when you uncheck and then recheck the `As Egg` Checkbox. Until then PKHeX just marks it as illegal

PK7 file: 
[227 - Skarmory - B8C84CA0F570.zip](https://github.com/kwsch/PKHeX/files/1224566/227.-.Skarmory.-.B8C84CA0F570.zip)

**Comment by kwsch** [comment]
Please don't report hacked pkm specimens (especially ones that originated from modified PKHeX versions); the AbilityNumber value is 0 when it should be 1/2/4 (1 in this case).

**Comment by architdate** [comment]
Oh that makes sense! I was trying to make api calls to PKHeX.Core to Gen Pokemon, seems i missed out the fact that Ability Numbers are not direct indices!
