### ISSUE TITLE
Edit .SAV files from GPemu

### ISSUE THREAD

**Issue by Alex9303** [kwsch/PKHeX#1403]
Is there a way you can make it so you can edit (and convert) .SAV files from [GPemu](https://github.com/matthewbauer/gametime-player)? [GPemu](https://github.com/matthewbauer/gametime-player) is an emulator on the chrome store and can import and export .SAV files. But these .SAV files are different than [Visual Boy Advance](https://www.emuparadise.me/Nintendo_Gameboy_Advance_Emulators/Windows/VisualBoyAdvance/86) .SAV files. [GPemu](https://github.com/matthewbauer/gametime-player) .SAV files cannot be imported to PKHeX while [Visual Boy Advance](https://www.emuparadise.me/Nintendo_Gameboy_Advance_Emulators/Windows/VisualBoyAdvance/86) .SAV files can be imported. Also .SAV files from [GPemu](https://github.com/matthewbauer/gametime-player) have a filesize of 82kb while [Visual Boy Advance](https://www.emuparadise.me/Nintendo_Gameboy_Advance_Emulators/Windows/VisualBoyAdvance/86) and other emulators are only 32kb. If there is any way you can add .SAV editing from [GPemu](https://github.com/matthewbauer/gametime-player) that would be amazing. Thank you.

**Comment by ObscenityIB** [comment]
Well from the filesize you mention, sounds like GPemu saves in savestates, not raw saves, which are needed for PKHeX

**Comment by Alex9303** [comment]
Oh ok. Thank you
