### ISSUE TITLE
Pkhex breeding emulation feature request

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1405]
Hi.  I'm not even sure if this will ever be possible  because of The ways breeding works but I think it would be an amazing feature to add if it is possible. I was wondering if there was a way to add a "breeding feature in pkhex that would emulate the way breeding works and spit out an egg into tabs or into the box in the same way you would do actual breeding.  Basically what I mean is that instead of having to breed in game you could breed "legit" Pokémon in pkhex.  Obviously you can edit everything in Pkhex already but I really think this could be a good feature because you could breed an entire box of Pokémon and then breed their offspring and eventually end up with a "legit" bred Pokémon without all of the time it take in game, and without just filling in fake stats and pid numbers that don't match the Pokémon. The other main reason is because whenever you edit Pokémon in pkhex, there are a ton of variables (pid, encryption, egg moves, relearn moves) and I think it would be great if pkhex could spawn eggs from 2 parents so that you don't have to worry about whether or not everything is legit.

**Comment by kwsch** [comment]
No.
