### ISSUE TITLE
[Feature Idea] Unlocking PokéWalker Routes in HGSS saves?

### ISSUE THREAD

**Issue by ewormPL** [kwsch/PKHeX#1406]
Exactly what it says on the tin - could PKHeX forcibly unlock the PokéWalker routes of our choosing on a save with a connected PokéWalker without the need of actually collecting millions of Watts? And could this include unlocking National Mode routes before beating the League?

**Comment by kwsch** [comment]
https://www.gamefaqs.com/boards/960099-pokemon-heartgold-version/56669153
would need to know how this AR code modifies the save file

**Comment by Bl4ckSh4rk** [comment]
The code sets 0x4E70C to 0x7FFFFFF.

**Comment by NinFanBoyFTW** [comment]
I made a before and after brand new save if you need any more info
[test.zip](https://github.com/kwsch/PKHeX/files/1254639/test.zip)
