### ISSUE TITLE
Pokemon XD Fateful encounter legality

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1410]
Hi. Sorry about bugging you with this but I just want to make sure that everything in PKHeX is accurate.
I just did some more testing with the fateful encounter flags and a lot of RoC's pokemon should be illegal because of the fateful encounter flag (obviously he could just change it). The reason why I say this is because I did some testing and in fact, PkmGCSaveEditor does automatically add the fateful encounter flag to every pokemon (they are assuming that the pokemon will be imported into another game). The problem with this on RoC's pokemon is that all of his pokemon are still in xk3 format with all of the things original shadow pokemon that havent been traded would have (shadow id) I did some other tests by trading one of my pokemon from XD (hitmonchan) to my emerald. Then I traded it back. The hitmonchan started with its shadow id (56) and no fateful encounter. When I traded it back to XD it now has a fateful encounter and shadow id of 0 (no shadow id) for RoC's Pokemon to be legit he would have needed to trade them so they would have the fateful encounter flag, but if he traded them they would have lost their shadow id. Obviously im not saying RoC cheated, but I think because of PkmGCSaveEditor that made his pokemon illegal. Sorry for the inconvenience. Also here is my hitmonchan after trading it back to xd. I dont have the original because I forgot to back the save up so ill include my hitmonchan from my other save that hasent been transferred out of XD for comparison 
[hitmonchan.zip](https://github.com/kwsch/PKHeX/files/1236866/hitmonchan.zip)

**Comment by kwsch** [comment]
So what do you want done with this? Flag `if pkm.FatefulEncounter && pkm is XK3 xk3 && xk3.ShadowID != 0`?

**Comment by NinFanBoyFTW** [comment]
I guess, if the pokemon has a fateful encounter and does have a shadow id other than 0 then it should be illegal. So my hitmonchan with shadow id of 56 would be legal but my hitmonchan with shadow id of 56 with a fateful encounter should not be legal.

**Comment by ReignOfComputer** [comment]
Thanks for researching. I'll fix the legality issues in my collection caused by PkmGCSaveEditor (if that was the issue) at a later date, when I find some time to do some legality pruning.

**Comment by NinFanBoyFTW** [comment]
No Problem. I like being able to help in any way. If I was you, I would just quickly check your whole collection in pkhex because from commit to commit,  I get pokemon that are legal turning illegal and Since you have the biggest pokemon collection you could probably find some good errors to fix.

**Comment by ReignOfComputer** [comment]
I've already been made aware of several events that aren't legit/legal, just need to find time to remove them. I'll purge those as well as the Pokewalker ones that were found to be illegal when I have the time, which unfortunately doesn't seem like the near future. Quite caught up with real life stuff at the moment :/
