### ISSUE TITLE
pokemon omega ruby pokemon bank glitch.

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1411]
Hi. I see you have had something like this on the forums a few years ago but there didnt seem to be an answer. When I go on to pokemon bank using my pokemon omega ruby, my save file only comes up with the first 30 pc boxes. I got all 31 boxes legit back when the game came out and I dont know when this started happening because I dont use pokebank that much. I could obviously try resetting my boxes back to the 8 boxes and then unlock them legit and see if that helps but I have tried that with another one of my saves a while back that had this same problem and it didnt work. Right now this only effected my pokemon omega ruby save.

**Comment by NinFanBoyFTW** [comment]
I just did a little more testing on this. I set my boxes back to the standard 8 unlocked boxes. then I proceeded to unlock the rest of the boxes like normal. Now I am stuck with 30 boxes in my game the same way it looks in pokemon bank.

**Comment by PKMWM1** [comment]
I don't know if this helps, but the 31st box of the PC is generated once rayquaza is captured to ensure that you always have a spot available to progress the story. I don't know if you've reached that far in the story

**Comment by NinFanBoyFTW** [comment]
I have caught rayquaza. My pc boxes were fine until a few months ago, I only noticed a week ago that they were  messed up in  pokemon bank. and now they are messed up in game too
