### ISSUE TITLE
pkhex database missing ck3 and xk3 options

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1412]
Hi. I just wanted to let you know I was going through the pkhex database and I noticed all of the search features were missing xk3 and ck3 options for the format. Thanks

**Comment by kwsch** [comment]
The format drop down is current Format (integer); where xk3, pk3, and ck3 all are equivalent (Format=3). It doesn't search by Extension.

pk* is used as it's the most recognizable.
