### ISSUE TITLE
pkhex database feature request 

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1413]
Hey I just wanted to know if its possible to add a toggle into the pkhex database to toggle for compatible pk files the same way you have the show legal and show illegal toggles.  For example if im in a gen 3-6 game and I load the database, when I have this toggle on I would not see gen 1-2 pk files since I cant use them in those games. Then if I was in gen 7 I would be able to see any pk file since I can use gen 3-6 pokemon and gen 1-2 are supported. Also this would obviously apply for any gen like if Im in 3rd gen I would only be able to see 3rd gen pk files, and if I was in gen 5 I could see gen 3-5 pk files.

**Comment by kwsch** [comment]
It already behaves this way; pick the format you wish to view for rather than the format of the individual files.
https://github.com/kwsch/PKHeX/blob/4f7c19d0cd670ab9367240b9bea2e57410261fb5/PKHeX.WinForms/Subforms/SAV_Database.cs#L423-L431

**Comment by NinFanBoyFTW** [comment]
Ok but I was saying because when I go into the database on any save, it always comes up with 6 of every pokemon (gen 1-6 collection of mine) and whenever I go to click on a pokemon it shows that its not compatible (while using 2nd or 1st gen for instance) I just thought it would be nice to have a toggle because I saw that you can search for format but I think it just makes more sense to have it so that as soon as you enter the database (and you have this toggle on) it would just show you the pokemon that are compatible. Like I said I know you can go searching through different formats, but if Im in a 2nd gen game almost every pokemon I click on (without searching) is incompatible without setting search parameters.

**Comment by NinFanBoyFTW** [comment]
Ok I see what you mean more now about the format. I couldnt see that it was sorting like I said. I still just think it would be nice if there was a toggle and you never had to search for the format again if you didnt want to. I just feel like there is an extra step that doesnt have to be there
