### ISSUE TITLE
pokemon gen 1 and 2 batch editor question.

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1419]
Hi. I wanted to know how you are supposed to make pokemon in gen 1 and 2 shiny in the batch editor. I know for the rest of the generations you do.pid=$shiny but pokemon dont have PIDs in these gens. I know it has to do with their dvs but I couldnt figure it out. Also I just feel like there should be an option to make them shiny in the batch editor instead of using pid and whatever the gen 1-2 method is. I dont know if its possible but it would be nice to just have in the editor something like .shiny=true

**Comment by egzonqj** [comment]
gen 1 has no shiny sprites so it's impossible these pokemon to be shiny there

**Comment by NinFanBoyFTW** [comment]
Gen 1 does have shiny pokemon. They are based off of their stats just like in gen 2. there weren't "shiny" pokemon in gen 1 but if you transfer these pokemon into gen 2 or even gen 7 they are shiny. Look up gen 1 shiny hunting and you can see all of the people getting gen 1 shinys in sun and moon

**Comment by kwsch** [comment]
The problem is gen2 shininess is different from gen1->7 shininess; hopefully gamefreak fixes this with gen2 bank transfers.

**Comment by NinFanBoyFTW** [comment]
Hey Im really sorry to bother you about this again but it still doesnt seem to work. Whenever I edit my silver save this is still what happens
![untitled-1](https://user-images.githubusercontent.com/21354941/29737384-af99dcbe-89da-11e7-8569-b7a65341d27c.png)
