### ISSUE TITLE
In the wonder i/o window there are two buttons that seemingly have different functions but have the same "title", ".wc6"

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#142]
![sem titulo](https://cloud.githubusercontent.com/assets/16060411/17210570/a0f1b5d8-54bb-11e6-9476-96f206c09137.png)

**Comment by evandixon** [comment]
I think lines 796 and 797 of lang_en.txt are to blame
https://github.com/kwsch/PKHeX/blob/master/Resources/text/en/lang_en.txt

**Comment by poutros** [comment]
It seems to be. Maybe change it to

**Comment by poutros** [comment]
I accidentally closed it...

**Comment by evandixon** [comment]
I was wondering where this issue went :P

**Comment by poutros** [comment]
Thanks.
