### ISSUE TITLE
Pokémon Colossum bug

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1420]
A major bug that I've been having is whenever I take a shadow Pokémon to modify it, if the shadow bar is depleted, but not purified, the shadow box isn't checked. However, if I purify a shadow Pokémon, then want to modify it, when I go back to the game, it's back to being a shadow Pokémon, and since it's already been recorded as purified by the game, it won't let me purify it again. This happens whenever I try to modify a purified shadow Pokémon.

What I did:
Reduced the Heart gauge of the shadow skiploom to zero
purified it, it acquired enough experience and it evolved into Jumpluff
Saved the game and opened PKHex
Changed its SID value to match the new one I set.
Saved it and the save file
Re-open the game and there is a shadow Jumpluff with its heart gauge at zero but can't purify.

Any help would be appreciated

**Comment by NinFanBoyFTW** [comment]
This should have been resolved with #1347 You have to compile the latest version of pkhex
