### ISSUE TITLE
batch editor shiny pokemon suggestion

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1422]
Hi. Thanks again for fixing the gen 1 and 2 problem I was having. It saved me hours of editing. I just wanted to know if its possible to make it so that when you batch edit I guess in general by at least for making pokemon shiny, that it only edits the pokemon in boxes, not your party. I know this may be a preference but any time I do mass edits like this, It usually drags my party pokemon into the batch edit when I only intended for the pokemon in the boxes to get the batch edit done to them. I think this wouldnt hurt anything because if people really did want the party pokemon to get the same batch edit they would just put them in the pc boxes. The main issue that think could arise from having pokemon in the party get changed with the batch editor is that, whenever I go to make pokemon shiny, it changes the party pokemon too and with shiny editing it messes with their ivs and other things that cannot be undone. I know I can just reload my last save and replace the party pokemon but a lot of times I dont realize that it changed the party and end up overwriting my save losing my original party. Thanks.

**Comment by kwsch** [comment]
Box -1 is how to reference the party.
```
=Box=-1
!Species=0
.Species=5
```
