### ISSUE TITLE
Caught pokemon shown as illegal

### ISSUE THREAD

**Issue by Juvencus** [kwsch/PKHeX#1424]
Pkhex reports these two pokemon as illegal. I have captured both myself (Alakazam as Abra). I have edited their IVs and Natures only.

[791 - Solgaleo - 5622D2D43AF0.zip](https://github.com/kwsch/PKHeX/files/1253544/791.-.Solgaleo.-.5622D2D43AF0.zip)
[065 - Alakazam - B054B09343E2.zip](https://github.com/kwsch/PKHeX/files/1253545/065.-.Alakazam.-.B054B09343E2.zip)

**Comment by egzonqj** [comment]
That Solgaleo had its Hidden Ability, which it's impossible to have.

**Comment by Juvencus** [comment]
You are absolutely right. Probably scroll-wheeled it while checking Abilities.

Still very confused about Alakazam. Tried rolling PID a few times but no change.

**Comment by egzonqj** [comment]
I said it, going to repost the text:
As for Alakazam, it lacks of Last Handler (meaning that you did not trade the Pokémon in order for it to evolve), so I guess typing something there will be good to go.

**Comment by Juvencus** [comment]
Sorry, didn't see the edit.

Not sure why it wouldn't though. I trade-evolved Kadabra normally.

**Comment by egzonqj** [comment]
Strange, maybe you edited it by mistake?
