### ISSUE TITLE
gen 5 c-gear and pokedex skin change implementation.

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1428]
Hey I just wanted to know if you were still planning to add c-gear and pokedex editing support to pkhex. I always knew that It worked (at least the c-gear) back in pokegen, but I saw in your implementation you had that you could import a png which was awesome. I just wanted to know if there was still a plan for that. Thanks

**Comment by kwsch** [comment]
Eventually; it's been too low priority as there have been more useful features to attend to.
