### ISSUE TITLE
PKHeX database import feature request.

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1431]
Hey I just wanted to know if its possible to have it so that whenever you go to load boxes and it askes you if you want to import from the PKHeX database, it then asks you a second question like, would you like to add all pokemon or only relevent pokemon. Relevent pokemon would be the generation that you are currently in. So if I am in pokemon black and white and I pick relevent pokemon it would load all of the pk5 files that are in the database. As it stands now I have all of my living dex stored in the database in pk1,2,3 etc... and every time I say load from database it imports every single pokemon that is compatible. So in gen 5 it looks like this.
![untitled-1](https://user-images.githubusercontent.com/21354941/29763040-7429e2a2-8b9f-11e7-8db3-89356544606f.png)
Because of this, the boxes get completely full by the gen 2 pokemon and it stops importing them. I think this would be a very good feature to put in so that if you just want to import everything in the database, you say import from database, and then a second prompt would say something like import all pokemon. The flip side of that is if you only want to load your living dex from a certain gen or you only want to load the pokemon you currently have in a specific pk format you would say import from database and then import from relevant pokemon or something of that nature. Thanks. 

Edit: Also pokemon colosseum and XD kind of desperatly need a feature like this because when I say load from database it loads my entire pk3 collection and runs Out of space

**Comment by kwsch** [comment]
That's the purpose of importing from a specified folder.
Use the Database search to dump to another folder, then import that new folder.

Having a 'smarter' import function won't work the way you described if users have more than (boxcount*30) pkm in that format.
