### ISSUE TITLE
[Documentation] XY Starter Event Constant

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1433]
Event Constant 48 in XY determines which starter you chose (can be used to determine which Kanto Bird you encounter in the post-game). When changing the value from 0 to 1 (chose Chespin, changed constant to believe I chose Fennekin), Shauna had a Chespin like she would if you chose Fennekin. :)

0 = Chespin
1 = Fennekin
2 = Froakie

**Comment by ReignOfComputer** [comment]
Related: https://projectpokemon.org/forums/forums/topic/40291-xy-hotel-in-game-trades-legendary-birds-flags-among-others/

**Comment by kwsch** [comment]
Best suited for a pull request ;)
