### ISSUE TITLE
Gen 3 Pokeball issue - Still

### ISSUE THREAD

**Issue by HaxMaster5235** [kwsch/PKHeX#1434]
SOMEONE (Kurt) closed the first one, so I'll make another. 

The Gen 3 Pokemon, when transferred to Gen 4 via Pal Park, keep the pokeball they were caught in. PkHex disagrees. PkHex says that it's invalid unless it has just a normal pokeball. 

"Invalid: Can't have ball for encounter type."

Now, I've enclosed the pokemon file AND my Save file, can someone PLEASE fix this issue?!

[NIDOKING.zip](https://github.com/kwsch/PKHeX/files/1258834/NIDOKING.zip)
[POKEMON PL.0.zip](https://github.com/kwsch/PKHeX/files/1258835/POKEMON.PL.0.zip)

**Comment by HaxMaster5235** [comment]
And no, Kurt didn't really give me any answers. Just that a question I had wasn't a bug, which I already knew, and to hold Control, but not anything on this. Completely ignored this, despite it being the WHOLE TOPIC.

**Comment by HaxMaster5235** [comment]
Validity Report:

Invalid: Can't have ball for encounter type.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Move 4: Learned by Level-up.

Fishy: All EVs are zero, but leveled above Met Level.
Fishy: Current experience matches level threshold.
Valid: Able to hatch an Egg at Met Location.
Valid: Nickname matches species name.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: Encounter Type matches encounter.
===

Encounter Type: Egg (Nidoran♂)
PID Type: None

**Comment by HaxMaster5235** [comment]
Note: It says egg, but I swear to God, this is from the Safari Zone it Fire Red, so I have absolutely NO CLUE why it says Egg, or how to fix.

**Comment by kwsch** [comment]
Do not create issues for hacked pkms.
This has already been discussed.

#1432
