### ISSUE TITLE
Cute Charm PID Bug

### ISSUE THREAD

**Issue by HaxMaster5235** [kwsch/PKHeX#1435]
So, this one is real. Gen 4's Cute Charm glitch allows for easy shinies, and usually generates odd PID's, so it's no surprise. 

http://prntscr.com/gecvm3

Here I have 8 Shiny Pokemon from HeartGold, all obtained by simply having a Clefable with Cute Charm in the front of my party, running around until a shiny spawned, and catching it. My TID/SID combo is already set up properly and everything.

Notice that 3 are flagged. These three share something in common. a Ponyta and the Spinarak have a PID of 0000000B, and the other Ponyta has a PID of 0000000A. The PID's have not been modified in any way, nor have the Pokemon themselves. These Pokemon are perfectly valid. The other Pokemon aren't flagged as invalid, and their PID's end in C, D, and E, with the rest being 0000000 . (I.E. 0000000C etc.)

Flagged
http://prntscr.com/gecx59
http://prntscr.com/gecy62
http://prntscr.com/gecyc9

Not Flagged
http://prntscr.com/gecygx
http://prntscr.com/gecymg
http://prntscr.com/gecyqi
http://prntscr.com/gecyuv
http://prntscr.com/gecyz0

It seems that PkHex flags these PID's as invalid, despite them being valid.

Inb4 "It's not a bug, use RNG Reporter."

It IS a bug, I've done the research, I have a brain, it's that simple. The game won't generate invalid PID's on it's own, Cute Charm or not, so the ONLY possibility is that I modified it, which I did NOT do, or PkHex has a bug.

**Comment by HaxMaster5235** [comment]
For now, since I know the PID's are in fact valid, I'm choosing to ignore these false flags, but I do personally hope that it gets fixed. I can deal with PID's in hacked pokemon, but having to change the PID for pokemon that I didn't hack, this is getting out of hand...

**Comment by HaxMaster5235** [comment]
Invalid: Encounter Type PID mismatch.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Empty Move.
Valid Move 4: Empty Move.

Valid: Valid Wild Encounter at location.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: Encounter Type matches encounter.
===

Encounter Type: Wild Encounter Grass (Spinarak)
PID Type: G5MGShiny

**Comment by HaxMaster5235** [comment]
Legal!
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Empty Move.
Valid Move 4: Empty Move.

Valid: Valid Wild Encounter at location.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Nature matches PID.
Valid: Encounter Type matches encounter.
===

Encounter Type: Wild Encounter Grass (Spinarak)
PID Type: CuteCharm

**Comment by architdate** [comment]
All 5 were cute charm is it? which would mean that the G5MGShiny Spinarak was wrongly identified?

**Comment by HaxMaster5235** [comment]
Exactly. All 8 were cute charm, and 3 were misidentified. From what I've seen on a few forums though, this has been a bug for a few builds now...

**Comment by architdate** [comment]
@kwsch what do u think about this? I believe if we used RNGReporter, and got the appropriate PIDIV combo, it would work out. However i am not quite sure why it didnt legalize it if it was indeed caught ingame.

**Comment by HaxMaster5235** [comment]
As far as the in-game thing, anyone can easily recreate this. I did it on Platinum on a physical cart, Heart Gold on a flash cart, AND Heart Gold on a PC, and I'm sure it holds true for Diamond, Pearl, and Soul Silver. It's as simple as using CCCalc, setting up the TID and SID, PkHex a Cute Charmer of the appropriate gender into Party slot 1, and catch a few pokemon, then export sav, and open in PkHex. I'm confident that it holds true across all of gen 4. When you open the sav, you'll find that most are valid, but ones with the mentioned PID's are flagged.

**Comment by kamronbatman** [comment]
Please give him time to look into this and address it. Some, more important issues, have taken MONTHS to fix.
Badgering him won't make it go faster. And it definitely doesn't make me want to fix it any faster either.

**Comment by HaxMaster5235** [comment]
Badgering? I'm not sure that opening an issue qualifies as badgering, but ok...?

**Comment by ReignOfComputer** [comment]
It's one thing to open an issue objectively (laying out details and test cases), it's another to use such an accusatory tone. There are lots of edge cases to consider when working on legality issues, this possibly being one of them. If it hasn't been added yet, it doesn't make it a bug, and is technically working as expected with regards to normal cases.

As previously mentioned, there are more pressing issues to be looked into. Coming across threateningly is a great way to bug Kaph, who doesn't get paid for this.

If you truly didn't hack the Pokemon, then don't change the PID - knowing your own Pokemon is legit should be more than enough.

**Comment by HaxMaster5235** [comment]
@kamronbatman I fail to see, A, how we badgered, or are badgering, anyone, and B, what is more important on PkHex then the program actually working properly. As for your attitude, I'm certainly not a fan of it. I didn't have to point out this bug, and I certainly didn't need to use PkHex for my stuff. PokeGen still works fine.

@ReignOfComputer As for you, claiming a tone in text is tricky business. I didn't type the issue in any accusatory tone, if read as it is written, and accusatory tones that one could misconstrew are entirely the fault of the reader, no offense. I'm also NOT coming across threateningly, nor am I trying to cause issues. Ask @architdate, we discovered this sorta together, I just posted it because I looked everywhere, and the only answers I found were to "use RNG Reporter" and that it was "Hacked", and knowing otherwise, I made the wise decision to make a post. That's what any "loyal user" would do. Of course, loyalty is a 2 sided street, and I guess you guys don't care for loyalty. Have fun being mean, I really hope you guys get it together for USUM though.

**Comment by kwsch** [comment]
>Now, someone needs to fix this. I've included ONE of the offending pokemon, AND the save file itself, so people can see that this IS able to be recreated easily, someone just needs to fix it.

>Now, can we focus on the issue at hand, the very NAME of this issue?

>SOMEONE (Kurt) closed the first one, so I'll make another.

>can someone PLEASE fix this issue?!

>Inb4 "It's not a bug, use RNG Reporter."

>It IS a bug, I've done the research, I have a brain, it's that simple. 

>I really hope you guys get it together

>I didn't type the issue in any accusatory tone
