### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by Pierrounator** [kwsch/PKHeX#1436]
Hi,

If PKHeX is in english, some regions in France have an english name too.

[Screenshot](https://gyazo.com/00823d4c24cf6b565e58aba44f20863d)

Brittany -> Bretagne
Burgundy -> Bourgogne
Corsica -> Corse
French Guiana -> Guyane Française
Lower Normandy -> Basse-Normandie
Picardy -> Picardie
Upper Normandy ->Haute-Normandie

**Comment by kwsch** [comment]
Working as intended; there are [localized region names for certain regions](https://github.com/kwsch/PKHeX/blob/3594d1af5cf86d946bdce1697a9c5e7a1894c995/PKHeX.Core/Resources/text/locale/sr_ID/sr_077.txt#L9).
