### ISSUE TITLE
Automatically change giratina's form when given the lustrous orb

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#144]

**Comment by kwsch** [comment]
I'd rather let the user have the illegal form than automatically fix that for them. If this was implemented, then why not Arceus with a plate, Genesect with a drive, or Keldeo with Secret Sword?

**Comment by poutros** [comment]
Actually, I just didn't remember those other cases because I was messing with a platinum save and giratina was the first in the box.
