### ISSUE TITLE
Zapdos Shiny/Static (HA) from RED appears legal

### ISSUE THREAD

**Issue by Pierrounator** [kwsch/PKHeX#1440]
```
Zapdos @ Leftovers
IVs: 0 Atk
Shiny: Yes
EVs: 252 HP / 252 Def / 4 SpD
Ability: Static
Bold Nature
- Volt Switch
- Roost
- Toxic
```
This set seems to be legal from Red. As they said on Discord, it seems it's not possible to get the HA in Red edition in any way. I thought, some pokemon already had HA but it only appears in other gen.

There is the PK7 file.

[145 ★ - Zapdos - 0FAA4406495B.zip](https://github.com/kwsch/PKHeX/files/1278056/145.-.Zapdos.-.0FAA4406495B.zip)

**Comment by sora10pls** [comment]
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9_Transporter#From_Generation_I

>Any Pokémon transferred from the Virtual Console releases of the Generation I games have their Hidden Ability.

**Comment by Pierrounator** [comment]
Well, they were all saying this one is illegal. Odaxis, ... So I thought it really was.

Then, why can't he learn `Heat Wave`?

**Comment by sora10pls** [comment]
Because going from Gen 1 -> Gen 7 means the Pokemon had no chance of learning the move via Move Tutor.

If you want a Hidden Ability Zapdos with Heat Wave, use the Gen 6 distribution.

**Comment by Pierrounator** [comment]
You can't do Gen1 > 2 then 3 then 4 then 5 ... ? 😮

**Comment by sora10pls** [comment]
Possible transfer methods:

Gen 1 -> Gen 2
Gen 1 -> Gen 7
Gen 3 -> Gen 4
Gen 4 -> Gen 5
Gen 5 -> Gen 6/7
Gen 6 -> Gen 7

**Comment by Pierrounator** [comment]
Even with Pokebank?

I wanted to try to get it Shiny ;)

**Comment by sora10pls** [comment]
You can't have a Gen 1 or Gen 2 origin Zapdos with its Hidden Ability **and** Heat Wave until US/UM which will more than likely have Move Tutors. This isn't a bug, nor are GitHub issues for help in faking data. Issue should be closed.

**Comment by Pierrounator** [comment]
I don't get why you can't transfer it.

Gen 1 > Gen 7 > Gen 6 > Gen 5 > Gen 4

It might be possible if I follow your "possible transfer methods"

**Comment by sora10pls** [comment]
No, it's not. You can't transfer a Pokemon **back** a Generation...
