### ISSUE TITLE
[Feature Request] Gen 5+ Nickname Censored Word Legality Checks

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1442]
As of Gen 5 onward, Pokemon with nicknames containing inappropriate words are not legal - the game simply refuses to let the nickname go through. This also applies to any Pokemon transferred from Gen 1/3/4/5 to 6/7 as Poke Transporter wipes nicknames that contain said censored words.

PKHeX should also flag these nicknames as illegal since they can not be used under normal circumstances.

Example:
![image](https://user-images.githubusercontent.com/17801814/30079282-b2782eb0-924d-11e7-9555-48ab24af550d.png)

Reference:
https://bulbapedia.bulbagarden.net/wiki/List_of_censored_words_in_Generation_V
https://bulbapedia.bulbagarden.net/wiki/User:Glik/List_of_censored_words_in_Generation_VI

**Comment by kwsch** [comment]
https://www.reddit.com/r/3dshacks/comments/45yhop/full_list_of_censored_words_on_3ds/

**Comment by sora10pls** [comment]
Gotta point out cheated PKMs at all costs ;)

**Comment by architdate** [comment]
Why not just have a banned words folder in resources with every text file and just load up the appropriate text file based on the generation?
Process it into a hashset and we got O(1) lookup time for banned words \o/
VOILA

**Comment by kwsch** [comment]
exact match != contains

ie: co**fag**rigus

**Comment by architdate** [comment]
would it be possible to load all bad nicknames in memory at start in the constructor hopefully? and if so could we please do it as hashsets over lists? much faster time complexity I feel

**Comment by kwsch** [comment]
Can't precompute any bad nicknames; it won't work.
https://stackoverflow.com/questions/273516/how-do-you-implement-a-good-profanity-filter

The games uses a regex to find bad strings _within_ strings.

If "fag" is a bad word, we don't want it in any string. Thus, "afag", "bfag", "cfag"... "wfaglol" etc has to be caught. You can't precompute a string hash for every possible character permutation (1000+ characters ^ 12 chars long). It's only possible / emulatable by using the regex lists.

**Comment by architdate** [comment]
so loop through the list of bad strings to find if pk.Nickname.Contains(list[i]) basically?

**Comment by kwsch** [comment]
Sort of, you'd just have to test every regex case against the input string.
`.*(ca|k|ka)ralh(inh|o|ã|õ).*`; can't do contains with that. [Regexes allow for more complex 'contains' finding](https://en.wikipedia.org/wiki/Regular_expression#Formal_language_theory), as you can look for combinations of characters rather than defining every permutation.

Contains "x" is precalculated, the above example has many different permutations (caralho, caralhinh, kralho, etc).

**Comment by architdate** [comment]
yeah im aware of how regex works, so I realise that we would need the regex strings as shown in the text files above. I just thought that the contains function checks for regex. Apparently not haha. so im assuming we would be doing `bool validName = Regex.IsMatch(pkm.Nickname, @".*"+list[i]+".*");` to include every regex stated in the text files + any characters before and after said regex.. right?

**Comment by sora10pls** [comment]
To add to this, I probably should've mentioned OT name as well. The same censors are used for your Player's name.

**Comment by kwsch** [comment]
Precomputing a list of bad word regexes for use (everything is less than 12 characters)
[bad.zip](https://github.com/kwsch/PKHeX/files/1279886/bad.zip)

```c#
string folder = @"D:\dev\bad";
var files = Directory.GetFiles(folder);
var lines = files.SelectMany(z => File.ReadAllLines(z));
File.WriteAllLines(
	@"D:\dev\out.txt", 
	lines.Distinct().Where(z => z.Length <= 14).OrderBy(a=>a)
	);
```
