### ISSUE TITLE
OT Name too long for French pokémon from Gen 1

### ISSUE THREAD

**Issue by Pierrounator** [kwsch/PKHeX#1443]
[French pokémon](https://gyazo.com/4d42cc839b59eccb576fee19e9306e82)

[The same with english language](https://gyazo.com/1e7141f0760e43cb24ff202bd7bda93a)

I'm playing Yellow and Blue right now and we can choose a nickname with 7 characters on both editions. So I think it's a bug from PKHeX. PKHeX allows only 5 characters in french.

There is the .PK1 file where I saw the bug

[001 - Bulbasaur.zip](https://github.com/kwsch/PKHeX/files/1281457/001.-.Bulbasaur.zip)

**Comment by kwsch** [comment]
>New Update Available!

Anyway...

```c#
if (tr.Length > (lang == 2 ? 7 : 5))
```
How does transporter set the language?

**Comment by Pierrounator** [comment]
I don't have the PokéBank so I don't know 😕

**Comment by sora10pls** [comment]
Now's a good a time as any to buy a Pokemon Bank pass ;)

I'll test this in a bit.

**Comment by sora10pls** [comment]
[Here](https://github.com/kwsch/PKHeX/files/1285820/fr_pika.zip) are two PKMs.

PK1 is the Pikachu from Yellow (French) before transferring.
PK7 is the Pikachu from Yellow (French) after transferring from Yellow to Moon.

All done via Poke Transporter and Pokemon Bank; no PKHeX whatsoever. @kwsch
