### ISSUE TITLE
[Bug] Gen 1/2 shiny button not working

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1444]
When clicking the shiny button to make a Pokemon shiny in Gen 1/2 save files, it does nothing. To reassure to myself, I exported a save with a Chikorita that was supposed to be made shiny by PKHeX, and in-game, the Chikorita was *not* shiny.

This is what I got after using the shiny button:
![image](https://user-images.githubusercontent.com/17801814/30129682-b5ead198-9314-11e7-8f55-c161c40bcb8d.png)

**Comment by kwsch** [comment]
heh looks like I forgot to commit / sync the rest of it
will push that in ~8 hours, until then, just set IVs to 2/10/10/10

**Comment by sora10pls** [comment]
Yeah latest release from PP.org also has this bug.
