### ISSUE TITLE
Ball inheritance showing Illegal

### ISSUE THREAD

**Issue by Zhakien** [kwsch/PKHeX#1445]
I'm not sure how many of these errors there may be, but I personally have noticed an error with Dreamball inheritance.

I had obtained all of the available Dreamball pokemon from the Dreamworld back in Gen 5 and transferred them over to Gen 6 and now Gen 7, but when I check some of the mon in PKHex they show as Illegal when they are now.

There is a new breeding mechanic where a parent's ball can be passed on through Eggs in Gen 7.

For example, taking a Dreamball Staravia and breeding it with another Starly/Staravia/Starraptor has a chance of passing on the Dreamball to a newly hatched Starly. However in PKHex that new Dreamball Starly shows as Illegal.

**Comment by kwsch** [comment]
Yes, it's probably an off-by-one referencing the wrong base species.
Are there any more examples besides Starly?

**Comment by Zhakien** [comment]
As of searching this particular save file, aside from Starly, I've only seen these errors regarding Dreamballs.

Gen 1/3/4 Starters - The original event distributed them all as male, but even after breeding new ones, females still show illegal.

**Comment by kwsch** [comment]
Shows up fine in Gen7.
![image](https://user-images.githubusercontent.com/6393368/30147600-1b11b958-9354-11e7-9761-9a5a29988f7e.png)

Ball inheritance was changed in Gen7 to allow passing by Ditto.
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_breeding#Inheriting_Pok.C3.A9_Balls

**Comment by Zhakien** [comment]
Oh, I see the problem. The DB Starters I had must have been Genned by someone in Gen 6 before the Pokeball inheritance mechanic. That explains things.

Anyway, the only other DB mon I can think of that you might want to take a look at aside from Starly would be other first stage evolutions that could not be obtained in B/W(2).
