### ISSUE TITLE
Error when reading old boxdata dumps.

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#1450]
Older versions of pkhex would export box data to .bin. I remember later on the file size was changed, Is there any way to make it so older.bin files are still read properly? Right now I get this:

Error

 Attempted to load an unsupported file type/size

File Loaded:
 C:\ pathhere

File Size:
215760 bytes (0x34AD0)

**Comment by kwsch** [comment]
Are you trying to load it to a different generation? can't do that

**Comment by ReZeroEmiria** [comment]
I was having this issue before gen 7 when I downloaded newer releases of pkhex and I wanted to load my old pcdata dumps.
