### ISSUE TITLE
Pokémon Emerald location bug

### ISSUE THREAD

**Issue by Tk77185** [kwsch/PKHeX#1452]
After edit my save with pkhex , I no longer have access to all city with fly

![sans titre](https://user-images.githubusercontent.com/31935144/30394290-f5cc1926-98c2-11e7-8f82-f0c2c8239145.png)

**Comment by architdate** [comment]
What exactly did you edit? any way to replicate the issue?

**Comment by kwsch** [comment]
16 different locations are unavailable, looks a lot like some bitflags got flipped to 0.
Would like to see before/after save files, probably 0xFFFF -> 0x0000 somehow?

**Comment by architdate** [comment]
Yeah that would be the case in my opinion as well. I think if the OP could tell us how he encountered the issue, we may be able to replicate it and isolate the code thats changing the bitflags from 0xFFFF to 0x0000

**Comment by egzonqj** [comment]
Ah this thing happened to me after doing some edits in Trainer Info (such as changing TID)

**Comment by Tk77185** [comment]
And how can i fix this :)

**Comment by egzonqj** [comment]
I fixed it by going back to Littleroot Town and passing by every city/entering League's first PKMN Center

**Comment by sora10pls** [comment]
[em-map.zip](https://github.com/kwsch/PKHeX/files/1312191/em-map.zip)

OT changed from `MATT` to `MATT1`, was able to replicate.
![image](https://user-images.githubusercontent.com/17801814/30564165-29c8e254-9c92-11e7-8c71-cddeb6c2606a.png)
