### ISSUE TITLE
[Feature Request] Add Support for Unofficial Gen 3 VC

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1453]
GBA Virtual Console uses 64KB save data as opposed to Gen 3's 128KB.

There are many custom Virtual Console files floating around of R/S/E and FR/LG, so there definitely is some incentive in adding support for this. Not to mention 26986ff was committed at one point, so unofficial VC support isn't out of the question!

**Comment by sora10pls** [comment]
[Here's](https://github.com/kwsch/PKHeX/files/1304295/g3vc-em.zip) a test save file you can have. Was played on my 3DS with custom VC, save exported is 64KB.

Pokemon Emerald
Starter was Torchic
Bag has 1 Potion

**Comment by kwsch** [comment]
Shouldn't they really be 128kb based on the recent 'actual' vc discoveries?
https://www.reddit.com/r/3dshacks/comments/6znqqg/1_mbit_agb_firm_lennies_%CA%96/

Anyway, the program already supports 64KB saves, because misconfigured emulators can have the same wrong-size issue.
```c#
public const int SIZE_G3RAW = 0x20000;
public const int SIZE_G3RAWHALF = 0x10000;
```

**Comment by sora10pls** [comment]
I have yet to try this out because the only public user-friendly tool to make custom VC with the 128KB save data is private, and when I messaged the developer of it I immediately ran into an exception lmao

If it does work (it should), this can be closed without a problem. May even submit a PR later after work (or you can commit while I'm there) with GodMode9's folder path for GBA VC save data.

`sdmc:/gm9/out/gbavc.sav`

**Comment by sora10pls** [comment]
Alright sweet the save is supported, was just the old implementation of the custom VC injector programs. The new beta injector using the proper save data type let the save data be read by PKHeX with no extra modification.

Thanks for the heads up :)
![image](https://user-images.githubusercontent.com/17801814/30454603-d83ad354-996a-11e7-87b8-fa1d8a5ceacc.png)
