### ISSUE TITLE
Support SRM RetroArch save files

### ISSUE THREAD

**Issue by megadrifter-pt** [kwsch/PKHeX#1455]
**RetroArch** uses a common save file format for all of it cores, with the extension _srm_ (Save RAM), including **Game Boy Color** cores (TGB Dual, Gambatte, etc).

Some of us may use this frontend to play on emulators. Would you add some support for those files ?

**Comment by kwsch** [comment]
PKHeX won't support save states, as RAM snapshots are not save files. Just retrieve the savegame after saving ingame.

**Comment by megadrifter-pt** [comment]
There are two kinds of SRM files. Those which are save states (found in _states_ folder), and those which are saves generated by games (found in _saves_ folder). The latter looks a lot like SAV files (if not exactly the same). Changing the extension to _sav_ does the job to open it with PKHeX.
___
Thanks a lot for this amazing tool!

**Comment by kwsch** [comment]
PKHeX doesn't care about extensions, you can always feed it those files directly (selecting all files filter or just dropping it in).
