### ISSUE TITLE
[QoL Request]Transition between tabs when dragging Pokemon to and from the party/PC.

### ISSUE THREAD

**Issue by Storm-Eagle20** [kwsch/PKHeX#1457]
https://i.imgur.com/WybvTeg.jpg

Basically, as of currently, when you drag a Pokemon to the party tab or the PC tab, the tab doesn't transition. This means that to move Pokemon to and from the party/PC, you have to view the Pokemon, set it in the party/PC, then delete the clone.

Would you mind adding this minor feature?

**Comment by kwsch** [comment]
Use the box viewer pop up.

**Comment by kwsch** [comment]
Eh why not ;)
