### ISSUE TITLE
My Pokemon Ranch validation

### ISSUE THREAD

**Issue by pepper-jk** [kwsch/PKHeX#1458]
I just tested some Event/Trade Pokemon of a [batch of "My Pokemon Ranch" Pokemon](https://projectpokemon.org/home/applications/core/interface/file/attachment.php?id=23829) I found a few days ago over at [pokemonproject.org](https://projectpokemon.org/home/forums/topic/37431-gen-i-v-event-contributions-thread/). And so far they all get "Encounter type PID mismatch.", "Encounter Type does not match encounter." - plus in the case of Mew it also marks "Hypnosis" and "Teleport" as invalid moves.
I never played "My Pokemon Ranch" or obtained the Pokemon before, but as far as I was concerned they were valid, even those with special moves.

**Comment by kwsch** [comment]
PKHeX doesn't legality check those encounters; nobody has figured out the PIDIV type either :)

**Comment by pepper-jk** [comment]
So is it fine to leave the issue open until it is implemented?
