### ISSUE TITLE
[Bug] Gen 3 eggs met level indecisive

### ISSUE THREAD

**Issue by Statharas** [kwsch/PKHeX#1459]
When making an egg, the app asks for a level of 5 to be valid.
->If met level is 5, it ignores it and says two things, that the met level must be 5 and again says that met level must be 0
->If met level is 0, it says met level must be 5

(which one is correct :P?)

**Comment by kwsch** [comment]
Hold control when viewing the legality report to see alternative encounters and why they were rejected.
Don't confuse met level with current level!

**Comment by Statharas** [comment]
Actually, yeah, you are /sort of/ right. The error message about current level not being 5 says "Met level" not "Current Level".
![screenshot 102](https://user-images.githubusercontent.com/2414202/30507940-8aabfbc4-9a94-11e7-89ff-84909f34b759.png)
