### ISSUE TITLE
LeafGreen save is misidentified as an emerald save

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#146]
Don't know if this happens to FireRed saves too.
Save:
[Pokémon LeafGreen.zip](https://github.com/kwsch/PKHeX/files/388331/Pokemon.LeafGreen.zip)

**Comment by kwsch** [comment]
What sort of cheating did you do with this save file?

The game code portion of the save file is all FF'd out (@0x000AC). The commit above should be adequate as there's no other way to auto-detect.

**Comment by poutros** [comment]
Purely events. Maybe I used a weird cheat?

**Comment by poutros** [comment]
Ok, so I restarted the game and now everything is detected properly.
