### ISSUE TITLE
Pokemon Dream Radar Legality

### ISSUE THREAD

**Issue by Sijiba** [kwsch/PKHeX#1465]
The Pokemon Tornadus is obtainable in B2W2 through the dream radar; the legality checker states Tornadus can't be acquired in White2

**Comment by kwsch** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/6393368/30526008-7b1a4f38-9bc7-11e7-8019-17005f61e440.png)

[641-01 - Tornadus - 7A861C1A0C5C.zip](https://github.com/kwsch/PKHeX/files/1309476/641-01.-.Tornadus.-.7A861C1A0C5C.zip)

**Comment by Sijiba** [comment]
Here's a file and a screenshot to accompany the report.

Side note - Dream Radar legendary pokemon arrive at level 40, not 10.


On Sep 17, 2017 6:46 PM, "Kurt" <notifications@github.com> wrote:

Closed #1465 <https://github.com/kwsch/PKHeX/issues/1465>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kwsch/PKHeX/issues/1465#event-1252669955>, or mute the
thread

**Comment by xXAquaNightXx** [comment]
Dream radar poke pokemon can arrive between levels 5-40 depending on how many badges you have

**Comment by Sijiba** [comment]
Didn't know that. Thanks
