### ISSUE TITLE
Transfer VC Gen 1 to 7 (Game version wrong)

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#1466]
I don't know if it's an issue, but when I transfer a Pokémon from Yellow to Moon with PKHex, the Origin Game of the Pokemon becomes Pokemon Red.

**Comment by sora10pls** [comment]
My best guess is because PK1 doesn't store the Origin Game, when transferred up, PKHeX defaults to the first supported Gen 1 game (Red).
