### ISSUE TITLE
4th Gen eggs hatched in Pal Park aren't considered legal

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#1468]
I hatched this Bagon in Pal Park and i got the red flag. The error is:

"Incalid: Can't hatch an egg in Met Location".

[371 - タツベイ - AE824AA03FA3.zip](https://github.com/kwsch/PKHeX/files/1312734/371.-.-.AE824AA03FA3.zip)

**Comment by kwsch** [comment]
Fixed a few days ago in prior commit:
https://github.com/kwsch/PKHeX/commit/eafc28422ef890feabec528c77212a5f53abe98d

Specimen is illegal tho (ITA egg hatched on JPN without trading).

**Comment by Real96** [comment]
Yeah i know, but i wante do signal the hatch location xP thanks!
