### ISSUE TITLE
Weird legality report on Gen1 VC Yellow

### ISSUE THREAD

**Issue by fattard** [kwsch/PKHeX#1470]
Just opened my save file extracted from 3DS VC for Yellow, to check my starter stats.
Reports as illegal, but when I click to check what is illegal, it seems to auto-correct itself and just reports as Legal this time.
Setting the now "legal" one over the party entry and saving, leads to a modified save file content.
Maybe some data not exposed in the UI?

Affected save file is attached.

[starter1_sav.zip](https://github.com/kwsch/PKHeX/files/1316678/starter1_sav.zip)

**Comment by kwsch** [comment]
Hold control when right clicking a storage/party slot to be able to export legality directly.

```
Invalid: Unable to match an encounter from origin game.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Empty Move.
Valid Move 4: Empty Move.

Valid: Valid Type A, matches species type.
Valid: Valid Type B, matches species type.
Valid: Catch Rate matches any species from Pokémon evolution chain.
===

Encounter Type: Invalid (Pikachu)
```

Loading something to tabs then checking the legality has the program auto-fix minor mistakes, which is what you're observing.

**Comment by fattard** [comment]
Nice feature! Didn't know about this.
There is enough information to fix the legality report?
Encounter type as starter should be possible, as is for Red/Blue starters.
