### ISSUE TITLE
X/Y/OR/AS Map Position

### ISSUE THREAD

**Issue by NickGurMatic69** [kwsch/PKHeX#1471]
Will editing the player's map position ever be enabled for X/Y/OR/AS as it is for Sun/Moon?

**Comment by sora10pls** [comment]
🤔 
![image](https://user-images.githubusercontent.com/17801814/30642539-4370bed2-9dd9-11e7-9284-93940ba3946a.png)

**Comment by NickGurMatic69** [comment]
:thinking:

[https://i.imgur.com/sNjhNi5.png](url)

**Comment by sora10pls** [comment]
Try the latest commit and see if you’re able to reproduce. If it still doesn’t work, send your save file to @kwsch.

**Comment by kwsch** [comment]
Coordinate editing is disabled in certain map locations where the stored coordinates are not reasonably representable. You're likely saved in an area that uses a different coordinate system (ie Lumiose City).

https://github.com/kwsch/PKHeX/blob/7b6d393b2ff8cafb455eb674562ab82a683506bf/PKHeX.WinForms/Subforms/Save%20Editors/Gen6/SAV_Trainer.cs#L413-L423

Save somewhere else then try again.
