### ISSUE TITLE
Geolocation invalid

### ISSUE THREAD

**Issue by hcyray** [kwsch/PKHeX#1473]
Hi, guys.
I found a problem in legality check.
I export the save from Pokemon Moon cartridge(Hong Kong version) via JKSM from a hacked 3DS (JPN version, B9S+luma 3ds). 
The following is my Trainer information:
![image](https://user-images.githubusercontent.com/29114602/30633647-0c76a95a-9e1f-11e7-8b3c-68c03d395861.png)
However,
![image](https://user-images.githubusercontent.com/29114602/30633366-fcd49ca6-9e1d-11e7-83e2-a9813b73fc9d.png)
As shown in the figure, Hong Kong is not in 3DS region and all my Pokemons are marked with the alert. However, if I change the country to Taiwan, PKHeX will think it is legal.
![image](https://user-images.githubusercontent.com/29114602/30633569-b50f734a-9e1e-11e7-890c-8e3a36880841.png)
It is wierd, and I think it may be a bug.

**Comment by kwsch** [comment]
3DS Region (Console) limits the countries available to select from.

Hong Kong (country 144) cannot be selected from a Taiwan 3DS, only Chinese.

https://github.com/kwsch/PKHeX/blob/b63e53af951f8be8ecde37248f279414c8aceb5d/PKHeX.Core/Legality/Checks.cs#L1751-L1756

**Comment by hcyray** [comment]
I think it is not true.
The picture below shows the hong kong version 3ds region selection.
![1](https://user-images.githubusercontent.com/29114602/30658527-8de687d2-9e6d-11e7-96f5-03fcaaba7d13.jpg)
We can see the hong kong version 3ds can only choose Taiwan or Hong Kong but not China.

Also, the picture of firmware version shows Hong Kong and Taiwan are in the same region. Both of them is VX.X.X-T. However, for China version, it is VX.X.X-C.
![2](https://user-images.githubusercontent.com/29114602/30658513-848cce80-9e6d-11e7-9d9e-f93405bf0bc6.jpg)

All the picture above are from a unhacked 3dsxl of Hong Kong version.
