### ISSUE TITLE
Apostrophe conversion issue

### ISSUE THREAD

**Issue by Tinytimrob** [kwsch/PKHeX#1474]
I used the PKHeX "Dump Boxes"/"Load Boxes" feature to dump all my Pokemon from Pearl and then import them into Black. Subsequently, I sent them to Moon through the Poké Transporter.

Two legal, unmodified and completely legit Pokémon (at least up to this point) refused to go through the transporter. On further inspection, the Pearl->Black transfer using PKHex had got the type of apostrophe wrong (apparently there is more than one in the charmap, one of which isn't valid) and so the nickname contained an invalid character, which is why the transporter was refusing to move the Pokémon.

I tried to delete the apostrophe and put it back using PKHeX but this didn't seem to work and it stayed with the wrong apostrophe type. In the end I had to replace the apostrophe using PokéGen instead.

Visual difference between the two apostrophes: they look almost identical in game (Black), the valid one is just marginally lower than the invalid one. It's hard to tell at first glance as there is probably a 1 pixel vertical difference between their positions.

An example of a Pokémon which after import into Black had the wrong apostrophe is CH'DING (the in-game trade Farfetch'd from Pokémon FireRed).

**Comment by sora10pls** [comment]
Please provide the PKM files.

**Comment by Tinytimrob** [comment]
[pokemon.zip](https://github.com/kwsch/PKHeX/files/1317830/pokemon.zip)

**Comment by kwsch** [comment]
Gen4 Name: `2D 01 32 01 B3 01 2E 01 33 01 38 01 31 01 FF FF`
Gen5 Name: `43 00 48 00 27 00 44 00 49 00 4E 00 47 00 FF FF` (good)
Gen5 Name: `43 00 48 00 19 20 44 00 49 00 4E 00 47 00 FF FF` (bad)

Mapping `0x01B3` to `0x2019` is incorrect, should be mapping to `0x0027`.

Apparently gen6 maps it back to the weird width? I'll just disable it for gen5 and prior.
