### ISSUE TITLE
gen 2 - gen 7 conversion question and legality issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1476]
Hey I know that the gen 2 -7 conversion is only hypothetical right now but I wasn't sure if this was a glitch. When I imported all of my pk2 into gen 7 all of my unown forms switched to the unown A form. Also when I change them to the right form it says it is legal so im not sure. Also my suicune got flagged for having water gun. It is a legal move that came on it in my pokemon gold. One other thing was I had this hoppip that was from my crystal that I imported and it is saying it is illegal because no encounter has been found even when I switched the met game to crystal. Maybe you could put something like unreleased encounter or something showing the fact that this is a crystal only encounter until they releace crystal on the VC. Thanks

**Comment by kwsch** [comment]
Crystal VC isn't a thing; PKHeX only generates Gold/Silver encounters when the format is > 2.
