### ISSUE TITLE
A few issues with the legality checks

### ISSUE THREAD

**Issue by exegg** [kwsch/PKHeX#1479]
The first one would be the fact some Pokemon are recognized as illegal at first glance, but when you check manually they're fine. This happens across Gen 6-7 save files, although less common with Gen 7. Now that I recall, in Gen 7 it has only happened with three Pokemon, which happened to be edited (within legal limits obviously) with PKSM.

For ORAS, which was the one I used this gif, this was not the case.

![blondcircularafricanmolesnake-size_restricted](https://user-images.githubusercontent.com/19347211/30768813-c3b54d84-9fdb-11e7-81ba-c88dc2f203c6.gif)

Also in SM, NPC trades are flagged as illegal
![2](https://user-images.githubusercontent.com/19347211/30768769-4ece8058-9fdb-11e7-83a4-0eb3b1ecd3c7.png)
![1](https://user-images.githubusercontent.com/19347211/30768770-4ed13870-9fdb-11e7-85bf-7f904d428e29.png)

**Comment by kwsch** [comment]
1. hold control when right clicking in the box slots; will give you the option to check directly from the slot. Loading to tabs then viewing the legality causes the PKM to be re-saved, which includes some obvious-error fixing (this is likely what is happening in your case).
2. Ingame trades in sun/moon have memories defined by the ROM; there's no way to clear these memories.
![image](https://user-images.githubusercontent.com/6393368/30769120-998786d0-9fc7-11e7-9315-ce312d063ab3.png)

**Comment by exegg** [comment]
> Is it possible that something had muddled with these pkm's data (wiping all gen7 origin memories even when it was not appropriate?)

Weird... I can't really think of something that could do that. They were never touched with any tool whatsoever. Traded in game straight to the box... 

>hold control when right clicking in the box slots; will give you the option to check directly from the slot. Loading to tabs then viewing the legality causes the PKM to be re-saved, which includes some obvious-error fixing (this is likely what is happening in your case).

About this, they all seem to have the same Legality Error "HT Gender Invalid: 2". Weird stuff...

**Comment by kwsch** [comment]
Handling Trainer gender is 0 (male) or 1 (female), never 2. Was caused by old versions of PKHeX setting a pkm without a Handling Trainer, which was neither male, nor female, thus genderless (2).
