### ISSUE TITLE
gen 2 save type alert box reverted

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1480]
Hey sorry to bother you. I noticed in the last commit you made about the gen 2 vc vs physical save it made it so that you dont get to choose whether the save is a vc or a physical save. it just automatically loads the legality settings and whatever else depending on the file name .dat vs .sav I dont know if this was a side effect of the last commit but just wanted to bring it up since gen 1 still has this feature that I do like and its better to keep continuity. Thanks

**Comment by kwsch** [comment]
dat vs sav is the way to detect vc vs cartridge; was an intended change.

The only reason cartridge checking was in was for the Gen1 'competitive' metagame where only RBY exists
