### ISSUE TITLE
gen 2-7 default met game

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1481]
Hey I have another minor continuity thing to bring up. When you import gen 2-7 the default met game is pokemon silver. As you have stated in the past for gen 1 the default met game is Red since that is the first game in the list on the met section. Obviously gold shows up before silver so instead of silver as the default met game it should be gold. OCD I know but like ive said before its always good to keep continuity in pkhex. Thanks

**Comment by kwsch** [comment]
nah, it's only Red and Silver because they were the two versions I owned years back

imo one game > random game; you can always modify the pk*->pk7 conversion code to always have the game you desire.
