### ISSUE TITLE
[Feature Request] Flag PK2 converted to PK7

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1482]
Like before Pokemon Bank and Poke Transporter's updates in January, PKHeX had legality check strings for pre-Bank species. If a PK7 originates from GSC, it should be flagged as illegal since there is no official transfer method until they get updated later this year for US/UM.

**Comment by kwsch** [comment]
I prefer it to not be flagged for now as it makes it easier for regular users to spot transfer-check mistakes now rather than wait until the official transfer method is out.

Obviously VC2 isn't available yet, only the user has themselves to blame for getting caught ;)

**Comment by sora10pls** [comment]
Makes sense. Out of curiosity, is that why you even bothered with adding 2->7 conversion early? I've been wondering because every statement from TPCi has mentioned that you can transfer from US/UM, but not S/M. [Refer to](https://www.pokemon.com/us/pokemon-video-games/pokemon-gold-version-and-pokemon-silver-version/):
![image](https://user-images.githubusercontent.com/17801814/30770460-627d5d30-9fff-11e7-8cf4-b25d584eb4c5.png)

I guess if you can't transfer directly to S/M, they'd probably make the following path doable:

G/S -> US/UM -> S/M

**Comment by kwsch** [comment]
just marketing/wording to get people to buy us/um; Bank (transporter) brings them from GS and USUM can pick them up (likely S/M too).

added conversion code because it's likely going to be the exact same as pk1->pk7 with minor alterations
* unown altform 
* updated Hidden Ability species table for species > 151
* changed met location to reflect origins
* properly interact with korean saves (biggest ouch)

**Comment by sora10pls** [comment]
Yeah that sounds about right, though I can never be too sure with what TCPi says! As for conversion code, I agree with you just because it'd make sense as it'd make Hidden Ability beasts available for the first time, if it weren't for inevitable GO transfer (which has yet to happen, and if it does, it'll probably be similar to VC).

Thanks for clarifying :)
