### ISSUE TITLE
Gen 2 RTC Feature Request

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1487]
Hey I am opening a new topic on this. I did some testing and I figured out how to reset the clock. So if you wanted to add a "reset RTC feature" that would probably be the best option because with the way RTC works on emulator and VC im not sure if it would work to directly edit the time on the save. either way Ill add anything else I find here too. Also ill include my save files im using. I took my pokemon gold save (before) then I used a reset code and shutdown the emulator (apparently it writes the save when you add in the reset code) Then I Went back into the game and set the time to Saturday 4:04 PM. So ill include the 3 save files for further research and ill keep looking too. Thanks
![untitled-1](https://user-images.githubusercontent.com/21354941/30776720-6f675fc6-a079-11e7-833a-c325404c30f2.png)
[Pokemon Gold.zip](https://github.com/kwsch/PKHeX/files/1326826/Pokemon.Gold.zip)

**Comment by NinFanBoyFTW** [comment]
I just did a little more testing and it looks like crystal has the exact method of resseting its clock (the picture above) I wasnt sure since they changed the way you have to acess the RTC reset screen. Ill include my crystal files as well so we have more data. Ill include my Before, after Resetting RTC, and after setting RTC File. RTC was set to Saturday 4:27 PM
[Pokemon Crystal.zip](https://github.com/kwsch/PKHeX/files/1326837/Pokemon.Crystal.zip)

**Comment by kwsch** [comment]
needs to support all languages

Such research topics belong in the [Save Research forum](https://projectpokemon.org/home/forums/forum/4-save-research-amp-development/), as it does not pertain directly to PKHeX.

**Comment by NinFanBoyFTW** [comment]
Hey sorry to keep bugging you on this but Im at the end of my "research" on this and I had 2 quick things to share so I didnt want to start a new forum post on this. I tested every version of the game I could find (USA, FR, PAL, KOR, SPA, JP) I forgot that the Japanese version dosent have an rtc reset feature its only in the western versions. Because the KOR version borrows from this version it doesnt have RTC Reset either. I think there is a way through the phone but that wouldn't involve what we are saying here. Also all of the versions I tested have the exact same way of resetting the RTC (picture above) so if you wanted to implement this all versions could be supported with the same button (EXCEPT FOR THE ASIAN VERSIONS). One last thing is that I dont think it is worth investing more time into RTC manipulation becides RTC reset. I tested the vc version and how it handles the RTC. I believe it stores in the save the time from when you set the RTC last , so you can do RTC manipulation with the 3ds clock and things like that. Also I think this means that if you reset the RTC in PKHEX, it might not correspond to the time in the VC correctly and it would probably just mess things up. So I think it would be fine to just add the RTC reset feature and let people set the correct time on whatever platform they choose (VC, emulator, Physical cartridge) I hope you'll consider adding this, and sorry about the annoyance. Thanks
