### ISSUE TITLE
[Bug] Gen 1/2 gender toggle while shiny

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1488]
If a shiny PKM has its gender toggled in the editing tabs, PKHeX crashes. It doesn't even give me the option to debug :/

This only happens in Gen 1/2 save files.
![image](https://user-images.githubusercontent.com/17801814/30777877-4d9b784a-a093-11e7-9912-89701636d93e.png)

**Comment by javierhimura** [comment]
Pokemon with 1:7 female to male ratio, those pokemon can not be shiny and female at the same time with gen 2 formulas. When the gender is changed to female PKHex enter an infinite loop triying to find a valid attack IVs for female pokemon, but that in combination with shiny is impossible.

**Comment by sora10pls** [comment]
Yeah that I’m aware of, but I didn’t expect it to crash lmao

**Comment by javierhimura** [comment]
I debug the program and the function ClickGender in PKMEditor.cs enters an infinite loop here

 if (pkm.Format <= 2)
                do { TB_ATKIV.Text = (Util.Rand32() & pkm.MaxIV).ToString(); } while (PKX.GetGender(Label_Gender.Text) != newGender);
