### ISSUE TITLE
When scrolling with the scrolling bar itself the window is not updated to be in the same position of the scrolling bar

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#149]

**Comment by kwsch** [comment]
What scrolling bar are you referring to?

**Comment by poutros** [comment]
It seems to happen with all scroll bars in pkhex.
Here is a video of the problem comparing how pkhex handles scrolling with the scroll bar and how chrome handles it. As you can see, chrome updates the content as you move the scroll bar but pkhex doesn't.
[record_000002.zip](https://github.com/kwsch/PKHeX/files/388907/record_000002.zip)

**Comment by kwsch** [comment]
Behavior of the TableLayoutPanel.

What operating system are you using? (.NET framework version too)... The scrolling behaves fine on my end, looks like it's only updating it when you release the scrollbar.

**Comment by poutros** [comment]
Windows 10 (version 10.0.10586, compilation 10586)
According to my registry and [this ](https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx#net_b) website, I have the 4.6.1 .net framework version. I also have the 2.0, 3.0, 3.5 and 4.0 versions.

Yes, it only updates when I release the scroll bar or use the mouse wheel.

**Comment by evandixon** [comment]
I've encountered this same issue in other programs, but not in the latest version of PKHeX.  I tried it on 3 different computers: My desktop (running the same version of Windows), my laptop, and a Windows Server.  Perhaps it's based on something else, like CPU architecture (32 bit vs. 64 bit) or the amount of RAM?

A web search yielded this, which might fix the issue.
http://stackoverflow.com/questions/1424482/smooth-scrolling-net-forms

**Comment by kwsch** [comment]
@poutros , would you please try with the latest commit? If it fixes the Main Window scrollbar and not the Event Flag scrolling, I can then apply it to the other scrollables.

**Comment by poutros** [comment]
Sorry, it's 00:41 where I am. Will try tomorrow.

**Comment by poutros** [comment]
The inventory editor window from the current release (28/7/2016) works fine btw.

**Comment by poutros** [comment]
@evandixon My pc is a 64 bit intel core i7-3537U 2GHz, has 4gb of ram and has Nvidia geforce 720m if that matters.

**Comment by poutros** [comment]
@kwsch After a lot of resistance from mono, I switched to visual studio and I can confirm that it works. After a bit of testing though it seems like the scroll bars in the super train window also work properly in the current release.
