### ISSUE TITLE
[Bug] Gen 2 RTC Reset Key is invalid

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1490]
Tested with Pokemon Silver. PKHeX will give me an invalid password, but [this generator](http://www.filb.de/pwf/) will give me a valid password.

Good password: `01245` (provided by generator mentioned above)
Bad password: `02520` (provided by PKHeX)

OT Name: `MATT`
TID: `61693`
Money: `353620`

**Comment by sora10pls** [comment]
Maybe this will be helpful? http://www.oocities.org/thelegendarydogs/faqs/gsc/time/timereset.htm

**Comment by kwsch** [comment]
http://www.psypokes.com/gsc/timechange.php
^ says 1240

did you test it?

I assume it's because of the money being greater than 16bits; if I truncate money to 16bits I get 1240 as well.

**Comment by sora10pls** [comment]
I did test it, both the password generated by PKHeX and the one you just sent are invalid. Only the site mentioned in the issue generated me a valid password.
