### ISSUE TITLE
gen 1 event flags question

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1491]
Hey I had a quick question on the gen 1 event flags you just implemented. I wanted to try and research some of the event flags (like legendaries) and some other things. I have my yellow save. I saved right in front of zapdos. then caught him. I compared the 2 saves and it looks like flag 1129 is set after catching zapdos. If I unset this flag zapdos doesnt re appear in game. I know you said (well the crappy ones at least) so does that mean that there are event flags missing from pkhex. Are the legendaries not even event flags?

**Comment by kwsch** [comment]
Event flags in gen1/2 are much more convoluted than gen3+.

https://github.com/pret/pokered/blob/fc9712596f6122fc114e0136c19795b36ee4868b/constants/event_constants.asm#L1132

Zapdos also has a Hide/Show toggle elsewhere:
https://github.com/pret/pokered/blob/fc9712596f6122fc114e0136c19795b36ee4868b/constants/hide_show_constants.asm#L94

Dunno where that is, and dunno how to expose the value for all languages.

**Comment by kwsch** [comment]
Found the hide/show data and was able to rebattle mewtwo.
Need to figure out more to differentiate savedata, just found out how to detect Yellow. Hopefully I can figure out how to detect red vs blue...

**Comment by NinFanBoyFTW** [comment]
is there any event flags that are red/blue exclusive, like some of the exclusive encounters. Also if this helps I made a red and blue save from scratch and changed the TID so essentially they are the same for testing.
[Pokemon Red.zip](https://github.com/kwsch/PKHeX/files/1327888/Pokemon.Red.zip)

**Comment by NinFanBoyFTW** [comment]
Also couldnt you just have the person select what game it is at start (the same way you have it for fire red/leafgreen)

**Comment by kwsch** [comment]
I could, but there's no advantages to having the user select for R/B. FireRed/LeafGreen have different stats for Deoxys.

Those 2 save files are identical except for trainer name and played time. I don't think there's a way to differentiate Red/Blue data so it's staying as GameVersion.RB
