### ISSUE TITLE
gen 1 move legality error

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1492]
Hey I was looking at my gen 1 collection again and I noticed a bunch of my pokemon were flagged with (Invalid move 1). All of the moves it is flagging seem to be moves that the pokemon doesnt learn but comes with (machamp with karate chop) (diglett with scratch). Also saying yes to gen 2 tradebacks if that makes a difference. Thanks.

**Comment by kwsch** [comment]
Use the latest commit.
https://github.com/kwsch/PKHeX/commit/499126f9a49066c75f0a51e221b77d46ba27a009
