### ISSUE TITLE
Event Eevee Legality 

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1493]
Celebrate Eevee when evolved into Umbreon give an error for the relearn moves, as well as any of Eevee's level up moves. Thank you for taking the time to read this, and for all your hard work.
https://www.mediafire.com/file/18y9cpu5mj5yin9/0201%20SM%20-%20%u30DD%u30B1%u30BB%u30F3%u266A%20Eevee%20%28JPN%29.wc7full

```Invalid Move 4: Invalid Move.
Invalid Relearn Move 1: Expected no Relearn Move in slot.
Invalid Relearn Move 2: Expected no Relearn Move in slot.
Invalid Relearn Move 3: Expected no Relearn Move in slot.
Invalid: Unable to match to a Mystery Gift in the database.
===

Valid Move 1: Relearnable Move.
Valid Move 2: Relearnable Move.
Valid Move 3: Relearnable Move.
Valid Relearn Move 4: Valid.

Valid: Current level is not below met level.
Valid: Ability matches ability number.
Valid: Skipped History check due to other check being invalid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Invalid (Umbreon)
PID Type: None
```

**Comment by kwsch** [comment]
Works fine for me. Double check that the Umbreon is level 11+, as Eevee -> Umbreon requires a level up.
[197 - Umbreon - AE964C9080DD.zip](https://github.com/kwsch/PKHeX/files/1331140/197.-.Umbreon.-.AE964C9080DD.zip)

**Comment by greenDarkness** [comment]
You're right there wasn't a problem. The event is just nature locked. 
Sorry about the confusion. Thanks again!
