### ISSUE TITLE
[Enhancement] Expand MGDB to Support other types

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1495]
@kwsch - What are your thoughts on extending the MGDB to support the other types of wondercards:
- Items/Dolls, Courses, Flute and others in Gen 4
- Items in Gen 5
- Items in Gen 6
- Items, Battle Points, Beans, and (I think?) Combos in Gen 7

Thoughts?

**Comment by kwsch** [comment]
Why? 

MGDB is used for legality checking (pkm only), and pkm generating to tabs. The interface is wholly for PKM related data.

Non-pkm mystery gifts would need a way of being shown in a list (need a suitable image resource), and would need a way of being searched.

There's no way to directly send a gift to the mysterygift album (what to do if full?); best to just save the file and import. Even then, you're better off just hacking in the item directly as there's no legality requirements to pay attention to.

**Comment by kamronbatman** [comment]
That is fair.
