### ISSUE TITLE
gen 3 non RS event flags question

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1497]
Hey I just wanted to know if there was a reason for this or if this should be changed. On every gen 3 save file (even non RS saves) it shows the event flags from Ruby and Sapphire. None of these event flags are even used in fire red and leaf green. I have also found that almost none of these (except for a couple) of these event flags are even used in Emerald. So guess I just wasn't sure if you should remove these particular event flags from LG FR and Emerald and replace them with the proper ones, or just leave it blank until more research is done. Also I wasn't sure, were you going to replace the in game name for these flags with something more user friendly (BADGE01_GET=Badge 1 Collected) Not a priority at all just wanted to bring it up. Thanks

![untitled-1](https://user-images.githubusercontent.com/21354941/30924150-ec0d3eb0-a37b-11e7-96a8-48f6a765ac63.png)

Edit: also I just noticed that it is recognizing my leaf green save and fire red save as emerald in the event flags. and my emerald save as stated only has a few flags checked off even though I have completed the whole game and there are a bunch more that should be checked off.

**Comment by kwsch** [comment]
the value names currently match the disassembly values 
https://github.com/pret/pokeruby/
