### ISSUE TITLE
Diancie event marked as ilegal because of OT memory feeling but the pokemon itself is legit and not edited

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#150]
It is marked as legal in my AS save but it's marked as ilegal in my Y save ~~even though they are the same event.~~ Nevermind, they aren't the same.
Zip contains saves and the diancie from each save:
[main.zip](https://github.com/kwsch/PKHeX/files/388324/main.zip)

**Comment by kwsch** [comment]
0xD0 in the Diancie (Y).pk6 is = 2.

According to the PK6 structure, [0xD0 is the OT Memory Feeling](https://projectpokemon.org/wiki/Pokemon_X/Y_3DS_Structure#Block_D_.280xB0-0xE7.29)

Works as intended? How did that Diancie get that 0xD0=2 value?

**Comment by poutros** [comment]
I have no idea. I never mess with memory stuff at all. The injected event was the same for both saves (both Y and AS) so I don't know. Does .wc6 have a memory region?

**Comment by kwsch** [comment]
WC6's do have an 'OT memory' region, which 99% of the time is unspecified. PKHeX actually checks for it if it is defined, but no event yet has an OT memory set afaik.

**Comment by poutros** [comment]
Ok, so I have been comparing the saves and it seems like:
1. The events are not the same.
2. The inject Y wondercard for diancie somehow got all the offsets 0xD4-0xD7 copied to 0xE4-0xE7 and since the 0xE4 is the memory value and it has the value `02`, the game recognizes it as normal.

I guess this issue can be closed since this is a problem on my end. Thanks for all the help and for making this program. :-)
