### ISSUE TITLE
Gen 5-7 legality error continued

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1500]
Hey sorry. I just checked my game and my togekiss is still marked as illegal. I didn't see until now but that togekiss was hatched from the platinum Cynthia egg if that matters. Also I just wanted to know, is faraway place the correct met location for this pokemon when transferring. I realize that Cynthia would not be the right met location but I wasn't sure about faraway place. Thanks.

**Comment by kwsch** [comment]
Shows up fine on latest commit; it was not a legality issue but a transfer 4->5 issue.
