### ISSUE TITLE
gen 2 RTC feature PT. 2

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1501]
Hey I dont know if you saw this but this just came out but maybe you could ask if you could incorporate this into PKHeX:
https://projectpokemon.org/home/files/file/2230-pokemon-gsc-clock-password-generator/

I know you were saying it would probably be better to leave this for a separate program like this because PKHeX deals with the currently loaded save, but when you think about it, the whole point of the code generator is that you have to use the code outside of PKHeX in the first place (no RTC reset button that would do it for you) so what I was trying to explain in the last thread was that a lot of times ill have my gold, silver, crystal save backup that I can open on my computer but it may be outdated so the money in the bag or whatever else may be different from what is on pkhex, which means that the code is worthless to me unless I go into trainer info and manually match the info. I just think that if you already are just going to use the code feature instead of and RTC reset, you might as well add the calculator into there so people can edit it if they need to. I guess to make it more in line with what you were saying about PKHeX dealing with the currently loaded save, you could have the info automatically populate with the loaded save info when you open up the RTC box giving you the code for that save, and then you could change the info if it wasn't correct for your save at the time /if you wanted to use it for another save. Thanks

**Comment by kwsch** [comment]
someone can create a standalone application; what you are requesting doesn't need a save file.

They can copy pkhex code
* character encoding tables to convert Trainer Name to bytes
* that's it

**Comment by sora10pls** [comment]
It’s like the legal PIDIV Generation requests. If there are programs out there that exist for that purpose (ie RNGReporter, the tool you listed in OP) and function properly, it shouldn’t be of high priority to add into PKHeX, if at all
