### ISSUE TITLE
HG/SS Headbutt Tree Encounter?

### ISSUE THREAD

**Issue by Rocker26a** [kwsch/PKHeX#1502]
I caught a Heracross from one of the trees in Azalea, and it's showing this. Any ideas?

![image](https://user-images.githubusercontent.com/23735586/31049828-83b112fa-a633-11e7-8ca3-10ea007f7026.png)

**Comment by kwsch** [comment]
duplicate:
https://github.com/kwsch/PKHeX/issues/1379

**Comment by Rocker26a** [comment]
.. Right. So, can I not resolve it? The explanation in the other thread doesn't really make sense to me.

**Comment by kwsch** [comment]
It's not fixed yet; you can just ignore the message if you'd like.

**Comment by kwsch** [comment]
with rock smash presumably working now, this leaves Headbutt encounters unfixed.

[supplementary examples](https://projectpokemon.org/home/forums/topic/41852-legality-error-events/?do=findComment&comment=221985)
