### ISSUE TITLE
[Question] Mewnium Z Wonder Card sprite

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1504]
Is it possible to load the Mewnium Z sprite rather than the placeholder sprite? The sprite *is* in [PKHeX's resources](https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/Resources/img/item/item_806.png), and it can properly identify which item the Wonder Card is set to give, so I was wondering if it'd be possible to properly display it.
![image](https://user-images.githubusercontent.com/17801814/31051116-e1419ea4-a62d-11e7-8a4c-eece2b738f97.png)

If not, I'd assume it's because of the Wonder Card having no ID number? Or some other factor since this is the only Wonder Card that grants the player a Z-Crystal.

**Comment by kwsch** [comment]
big z crystal (key item) != small z-crystal (held item)
two separate items

**Comment by sora10pls** [comment]
Would it just being a matter of adding the Key Item sprites (bigger) to resources? If it is then it shouldn’t be any problem at all since you’ve already got them even from the demo datamine.

**Comment by kwsch** [comment]
y waste teh space tho when the small sprites are enough visually?
