### ISSUE TITLE
Modifying Trainer Info in Gen2 Crystal Sav affects TM Bag Pocket

### ISSUE THREAD

**Issue by fattard** [kwsch/PKHeX#1505]
Some data is affecting the TM Pocket when I click the "Save" button in the Trainer Info dialog.
Verified with Crystal sav (US)

1. Enter "Item" dialog;
2. "Give all" TMs to make pocket full;
3. Click "Save" to close the items dialog;
4. Enter the "Trainer Info" dialog;
5. (Optional) Do any money or coin modification;
6. Click "Save" to close the dialog;
7. Enter the "Item" dialog again;
8. Observes that the TM pocket is missing the first 2 TMs (started counting at TM03), and the last 2 slots in the bag are "(none)".

Please, let me know if the steps to reproduce are not clear enough.

**Comment by PKMWM1** [comment]
This happens with gold and silver as well.

**Comment by kwsch** [comment]
badge setter is missing its cast (4 bytes -> 2 bytes) causing it to write 2 bytes too many (all zero since badges is always < 16bit).
```c#
JohtoBadges = 0x23E4;
PouchTMHM = 0x23E6;

public int Badges
{
    get => BitConverter.ToUInt16(Data, Offsets.JohtoBadges);
    set { if (value < 0) return; BitConverter.GetBytes(value).CopyTo(Data, Offsets.JohtoBadges); }
}
```
