### ISSUE TITLE
gen 7 event legality

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1506]
Hey I just wanted to let you know that my pikachu hoenn hat and pikachu sinnoh hat events are still illegal. I was  just wondering how exactly the event database works since most of the time when I get a new event, it has been added already but for these 2 they haven't been. Thanks

**Comment by ReignOfComputer** [comment]
Is this for the English ones that just got released? The mystery gift database in PKHeX is manually updated with each release, it doesn't automatically update when new events come out.

You can manually add the WC files to an mgdb folder in the same location as your PKHeX executable and it'll add them to your local copy of PKHeX.

**Comment by NinFanBoyFTW** [comment]
Yeah. I knew that it was a manual process but I wasn't sure who does it because most of the time when I check it, the events are legal (literally on the first day of the event) but I guess no one added these 2 events yet. Also I know I could add them to that folder but I dont like to do that because then its not the online database and I want to make sure that what I have is the latest database.

**Comment by kwsch** [comment]
PKHeX uses the https://github.com/projectpokemon/EventsGallery/ for its internal database; every PKHeX update the current repo is combined into the mgdb files.

The pikachu wc* files had not been added at that time, hence why they are not recognized.
Future updates to the program will have these new cards.
