### ISSUE TITLE
mgdb error (empty move)

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1507]
Hi,
checking PKHeX Build 3850 (and previous builds+ the stable from 170922) I have encountered the above error with several .wc3 event pokemon from the mgdb:empty move

![2017-10-03](https://user-images.githubusercontent.com/20145301/31141058-fb515a34-a87e-11e7-952a-b45a30680f7c.png)
![2017-10-03 1](https://user-images.githubusercontent.com/20145301/31141061-fead4292-a87e-11e7-8757-b41eeda1afae.png)

if I click to get suggested moves or if I check the internet to get the correct event moves it shows legal again

Thanks

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/ec491cdd52f5c899484e758c170b4edc8f2d3dfb/PKHeX.Core/MysteryGifts/WC3.cs#L142-L149

as a result of https://github.com/kwsch/PKHeX/commit/1149845db5f35f52cc9770ff65c55801e4e56d60 , the move list is never null; that null check should include All moves == 0
