### ISSUE TITLE
White event flag not updating

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1508]
Hi,

I have White game cartridge from a long time ago and yesterday, looking the event flags of my save file with PKHeX, I remembered that I haven't caught Volcarona yet from Relic Castle.

I had a spare time and a spare master ball and I caught it. I backed up my save game and I checked it with PKHeX to see if the flag for Volcarona (Volcarona dissapeared) was updated but it didn't
I have used action replay back then,to get items mostly, I hope it didn't break anything related to event flags.

I am attaching the .zip file with my save before catching Volcarona and after catching it.
If it is user-error and has nothing to do with PKHeX, please ignore this issue and close it
[Save files.zip](https://github.com/kwsch/PKHeX/files/1353478/Save.files.zip)

Thank you again

**Comment by kwsch** [comment]
Before/after gave me:
`0348, 0810, 1173,`

flags_bw says:
`0812	Volcarona disappeared`

could be that the flagnum is wrong for b/w

**Comment by PrometheusG** [comment]
I am sorry for not answering earlier, I fell asleep.
How can I see those flag numbers and  unset 0810?

Thank you

**Comment by kwsch** [comment]
There are multiple tabs in the event flag editor

**Comment by PrometheusG** [comment]
thanks, I  just didn't knew how it works but I found out.
un-setting 0810 flag didn't change anything, so I set it again. Only when I changed 0812 I got the checkmark in Volcarona dissapeared.
it is weird that the game did not recognize that I captured volcarona and did not mark the flag by itself
Thank you for helping me! you can close this issue
