### ISSUE TITLE
[Feature Request] Prioritize active folders over disabled folders

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1512]
When opening the Folder List, PKHeX will load them in a particular order. I believe it's:
`bak` -> `savpaths.txt` -> Paths listed in source code

While this works fine, it should instead display all of the enabled folder buttons before all of the others as it seems inconvenient to have a lot of disabled buttons covering the enabled ones.

Take this for example:
![image](https://user-images.githubusercontent.com/17801814/31242345-ba24b392-a9d4-11e7-9917-ade4f5811a07.png)

The buttons for `gm9` and `Checkpoint` are enabled, yet are below several disabled buttons. Ideally, the order should be as listed below:

VisualBoyAdvance, SAV Templates, PKM Templates, gm9, Checkpoint

Afterwards, should include all of the disabled buttons. Just makes more sense to me, and it's a QoL change, but it'd be nice to see added :)

**Comment by kwsch** [comment]
would have to modify around here:
https://github.com/kwsch/PKHeX/blob/ac05a63ebb5c1bc27899373be8d4fd932ef6fafb/PKHeX.WinForms/Subforms/SAV_FolderList.cs#L26

pull out enumerable (locs), do a .Select(z => z.First()) after the GroupBy(), then OrderBy(z => Directory.Exists(z.Path))

that way the FolderLocation enumerable is just a non-duplicate path ordered by existing or not

**Comment by sora10pls** [comment]
At work now so I'm unable to PR til later tonight when I have access to my PC, I guess it's whoever gets the time to first lol
