### ISSUE TITLE
Gen6 Legality Issue build 3862

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1513]
Imported this Pokemon from Showdown text over a gen6 Pokemon used as the base. It listed Bullet Punch as a relearn move.  After switching Scizor to non-mega, removing Bullet Punch from the relearn list, and clicking on relearn moves fixes this issue. 
```
Scizor-Mega (M) @ Scizorite  
Ability: Technician  
EVs: 248 HP / 64 Atk / 124 Def / 16 SpD / 56 Spe  
Adamant Nature  
- Swords Dance  
- Roost  
- Bug Bite  
- Bullet Punch  
```
Thank you for taking the time to read this! And for all your work on PKHeX.

**Comment by kwsch** [comment]
Imports just fine if you remove the -Mega from the set; PKHeX attempts to make the PKM as legal as possible (which includes applying any suggested relearn moves).

**Comment by greenDarkness** [comment]
Ah, I see. Thank you for the response!
