### ISSUE TITLE
[Feature Request] Edit Gen 1 Catch Rates

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1517]
Hello, 
I was wondering if you would consider implementing a way to to view, and edit the catch rate in the Generation 1 Pokemon games?
Thank you for taking the time to read this! And for all your work with PKHeX!

**Comment by kwsch** [comment]
use the batch editor if you really must; the catch rate is currently sync'd to the species for auto-legality purposes.

**Comment by greenDarkness** [comment]
Could you tell me the command, please? Is it supposed to be fixed automatically? Thank you.

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/31314702-34fde532-abbc-11e7-8869-aedb4b3618e3.png)
It's fixed automatically... hence why I said 'auto-legality'. The user is not expected to know what values are required, so the program automatically fixes them when you change the species.
