### ISSUE TITLE
Ash Cap Pikachu Legality

### ISSUE THREAD

**Issue by Ace1986** [kwsch/PKHeX#1518]
The mystery gift Ash Cap Pikachu (English Version) is not showing up as legal, it says invalid relearn moves 1-4 and unable to match to a mystery gift in the database. The only one showing as legal is the Original Cap where as the Hoenn Cap, Sinnoh Cap and Unova Cap is experiencing the legality issue.

**Comment by kwsch** [comment]
Mystery Gifts that are released after the program is published must be added manually by the user. PKHeX only has a built in database; it does not automatically download new gift data.

Create a folder called "mgdb" and add any new gifts there.
