### ISSUE TITLE
[Bug] XY map coordinate edits

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1523]
**Note:** Might not be limited to XY but it's all I've tested.

From what I can tell, every time map values are changed in PKHeX, the game will fail to load the save file after it's re-imported and will just stay on a black screen instead.

Below I've provided 3 save files.

- `before`: in front of Camphrier Town Pokemon Center
- `after_bad`: coordinates modified to match exactly what's shown in `after_good`
- `after_good`: flew in-game from Camphrier Town to Cyllage City (both in front of Pokemon Center)

[You can download the save files here.](https://github.com/kwsch/PKHeX/files/1384363/xy_map.zip)

**Comment by kwsch** [comment]
don't warp maps, only change coordinates

**Comment by sora10pls** [comment]
Warped from Chamber of Emptiness to Cyllage City, and while the game didn't crash this time, it instead lead me to a softlock with this odd blue screen.

![image](https://user-images.githubusercontent.com/17801814/31575557-9d362998-b0b7-11e7-9b5d-be455d35c2bb.png)

**Comment by sora10pls** [comment]
And doing yet another test taking what you said into consideration, I don't think the map editor does anything in terms of actually changing your coordinates.

Was in front of Camphrier Pokemon Center
- Current Map: `12`
- X: `669.5`
- Y: `0`
- Z: `525.5`

Used PKHeX to move 2 places right (X +` 2` = `671.5`)
Re-imported save data, and I was still in that same position from before editing the save data (X = `669.5`)

No crash or blue screen though! [And again, save files are here.](https://github.com/kwsch/PKHeX/files/1384641/xy_map3.zip)

**Comment by sora10pls** [comment]
After one final test, doing the following properly changed my coordinates without needing to do so in-game.

- Copy [Trainer1 block](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Saves/SAV6.cs#L191) from `camphrier_good`
- Paste + overwrite block into `camphrier_original`
- Fix checksums with PKHeX
- Re-import save data

**Comment by kwsch** [comment]
SAV6 doesn't update the Overworld block.

https://github.com/kwsch/PKHeX/blob/a11b6f4a606a87c241a985cea5ad0e625eae5449/PKHeX.Core/Saves/SAV7.cs#L444-L452

https://github.com/kwsch/PKHeX/blob/a11b6f4a606a87c241a985cea5ad0e625eae5449/PKHeX.Core/Saves/SAV7.cs#L444-L452

https://github.com/kwsch/PKHeX/blob/a11b6f4a606a87c241a985cea5ad0e625eae5449/PKHeX.Core/Saves/SAV7.cs#L217-L221
