### ISSUE TITLE
Bad Word Filter

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1524]
Looks like Gen < 5 legality in Gen < 5 format is subject to bad word filtering, even though those games do not have it.

**Comment by sora10pls** [comment]
https://github.com/kwsch/PKHeX/commit/d3ebbffb79d711142d327e323cdea7c253120b1f#commitcomment-24120571

**Comment by Jenetrix** [comment]
Just ran into this today with "Lulu" bring triggered on Ruby for the OT name. It is not made clear to the end user that the name will be removed/changed when moved into later generations. This needs to be changed from an outright Fail to a Warning.
