### ISSUE TITLE
Pokemon Emerald usability issues

### ISSUE THREAD

**Issue by bert-w** [kwsch/PKHeX#1528]
I'm encountering some usability bugs, which i think would improve the program if they were changed:

- I can click the star (*) icon on a non-shiny to create a shiny pokemon, but I cannot unshiny it using that same button
- I guess saving a pokemon after editing it is done using right-click on the sprite in the box, and clicking `Set`? If so, I would call it `Save`
- Left click does not do anything when clicking in the pokemon box. I assumed it would select the pokemon or open a dropdown with options
- Its unclear what the "Berry Fix" button does on the "Clock (RTC)" window, and why it sets the time to this specific value. A little title popover would be great

**Comment by kwsch** [comment]
* the star button disappears when you make the pkm shiny, you have to click the reroll button to the right instead.
* matches pokegen; save can be confused with save as hence why set is used. (Get/Set/Reset)
* left click is reserved for drag drop; unlike pokegen there is no slot selection as drag/drop and multiple box viewers is more usable
* berry fix does the same thing as the berry fix disc, which is resetting the clock value past the glitch maximum. See bulbapedia

**Comment by sora10pls** [comment]
Personally, I don't think any of these should be changed. I think I speak for a majority of people when I say this, too.

**Comment by bert-w** [comment]
I dont know the very specifics of savegame editing, so I dont see a relation between a shiny switch and a pid reroll. (I dont even know what a pid reroll is used for). Ive used some save game editors before, but I feel like i need to test a bunch of the functionalities out in PKHeX in order to see what it actually does.

Dont look at the points from a coder perspective.

**Comment by kwsch** [comment]
Shininess is derived from the Pokemon's PID (basically a 'unique' random number). Making a Pokemon shiny changes the PID; likewise, changing the PID will have to recalculate shininess.

Left clicking is also used with keyboard shortcuts to get/set/reset the slot (ctrl/shift/alt, respectively)

**Comment by sora10pls** [comment]
Pro-tip: Options -> About PKHeX

Click the "Shortcuts" button at the bottom-right of the window to view all shortcuts.
