### ISSUE TITLE
Pokémon XD special trade moves marked as illegal (and some evolutions?)

### ISSUE THREAD

**Issue by suloku** [kwsch/PKHeX#1529]
I've just noticed that all 4 available in-game trades with special moves get marked as illegal in pkhex. Also, seems they were never added as being obtainable in Pokemon XD.
Here you can see the 4 in-game trades and the special moves: https://bulbapedia.bulbagarden.net/wiki/In-game_trade#XD:_Gale_of_Darkness

Also my donphan is being marked as PID mismatch, maybe some slip on those pokémon obtainable on XD that can evolve since speon, golbat and skiploom are correctly recognized and aso where caught and evolved in XD.

Here's a pokémon XD save that has those 4 traded pokémon on the party and also the incorrectly recognized donphan (on pc): https://www.dropbox.com/s/94coko3mzkr9ggj/GXXP15_traded.raw?dl=0

ps: I'm using pkhex stable release 20171017

**Comment by kwsch** [comment]
Unable to open attached save file (no pkm saves on memcard?)

**Comment by suloku** [comment]
Oh, I see, it's due to language. I could provide OT names for the othe XD languages, since that's the only thing that changes.

Phanphy is a normal pokéspot encounter, but other pokéspot pokémon I evolved turn out as legal. I will remove other pokéspot pokémon from the purifying machine and see if other also turn out illegal, but doesn't seem to be species related.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1249#issuecomment-339213344
