### ISSUE TITLE
Gen IV Palparked pkm

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#153]
When I load a save of SS and import a .pkm file that had been pal parked it locations is rumination Field instead of pal Park. When I load The same pkm file pokegen it is correct.

**Comment by poutros** [comment]
https://github.com/kwsch/PKHeX/issues/140

Fixed with this commit: https://github.com/kwsch/PKHeX/commit/67a375ecae71c8ccdd17d4b5dee02b308796646f
