### ISSUE TITLE
About egg

### ISSUE THREAD

**Issue by powerws415** [kwsch/PKHeX#1530]
After edited egg's PID.
In connection exchange, the other person will see the name of the PKM, but not “egg”.
![qq 20171019220318](https://user-images.githubusercontent.com/32932982/31774779-4752e28a-b519-11e7-8108-df9bc40b8de9.png)
![qq 20171019220329](https://user-images.githubusercontent.com/32932982/31774781-47d889d0-b519-11e7-9b94-8b5e47c38e2b.png)

**Comment by kwsch** [comment]
Depends what is saved in the pkm file (egg vs hacked egg), not exactly sure what is wrong here.

**Comment by kwsch** [comment]
Not able to replicate on latest version.
