### ISSUE TITLE
Korean vc gold default name error

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#1534]
Sentret's Korean name is the 꼬리선. 
After editing the save file, the default name will be changed to 꼬릎선.

![default](https://user-images.githubusercontent.com/24352145/31805188-dc6e7372-b599-11e7-83eb-d00154c228b8.jpg)

**Comment by kwsch** [comment]
I noticed the same for quite a few other pokemon; I'm not familiar with Korean characters but I suspect there's an issue in the encoding tables.

https://bulbapedia.bulbagarden.net/wiki/Character_encoding_in_Generation_II/Korean#0x00

Can extract a pkm from the save without modification by dragging directly from the boxes to a folder, and can analyze the raw bytes....

**Comment by host1126** [comment]
I've checked that 251 Pokemon's default name is intact. The results are as follows 

Korean typed in pkhex - Korean displayed in game
풀 - 푿
리 - 릎
데 - 덮
침 - 칡
붑 - 붕
트 - 튱
크 - 큠
카 - 칭
나 - 낑
푸 - 푯
르 - 륭
덕 - 더
가 - blank
윈 - 윅
챙 - 챘
강 - 갔
괴 - 괭
력 - 렇
동 - 돗
눈 - 눅
날 - 낟
붐 - 붉
홍 - 홋
덩 - 덧
구 - 쿠
치 - blank 
에 - blank 
더 - blank
져 - 젱
뇽 - 뇻
베 - 벚
엘 - 엔
누 - 뇽
무 - 묫
호 - 혭
델 - 덴
갑 - 감

The common point of this result is that characters in front of the spelling of Korean entered in pkhex are displayed in the game.
The other bug is that the number 2 is treated as blank in pkhex and the Korean '츄' is forced to change as '췄'.

**Comment by kwsch** [comment]
Character table in PKHeX is messed up, will fix tomorrow.

**Comment by kwsch** [comment]
I'm not sure if there's documentation errors on Bulbapedia; please let me know if there's any more encoding issues :)
