### ISSUE TITLE
Gen 1 "legal" mons help

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1535]
Hey so I was making some gen 1 mons when I came across a legality error. If you have a mon originate from a gen 1 egg. It says it is legal even if you don't select a hidden ability. (Which is impossible because gen 1 VC transfer automatically give a transferred mon it's hidden ability.) The mon then is rejected during trade. Below is an example of such. Though this legality check is bypassed with many other mons as well.
[Illegal Kangaskhan.zip](https://github.com/kwsch/PKHeX/files/1403710/Illegal.Kangaskhan.zip)

I was originally trying to make this.

Kangaskhan (F) @ Gold Bottle Cap
IVs: 3 HP / 27 Spe
EVs: 252 Atk / 4 Def / 252 Spe
Ability: Scrappy
Level: 100
Jolly Nature
- Fake Out
- Body Slam
- Crunch
- Seismic Toss

EDIT: Just tried changing to hidden ability and trading. Still didn't do anything..

**Comment by kwsch** [comment]
Gen2->Gen7 is still not legal for online trades; PKHeX is currently set up to assume that Gen2->Gen7 is legal (again, it's not) so that legality checks can be sanity checked prior to the official feature being available.

**Comment by kwsch** [comment]
You also have Met As Egg data, which isn't valid. Hence why it doesn't trade.
