### ISSUE TITLE
CHANNEL Jirachi Legality

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#1537]
I've looked through other issues in regards to this and haven't found anything,

I have attached a zip file with two Channel Jirachi:
[Channel Jirachi.zip](https://github.com/kwsch/PKHeX/files/1404468/Channel.Jirachi.zip)

I saw that the "Legal" Shiny one used the "Channel" method of PID generation,(From what I've read Shiny Channel Jirachi should only be possible through a bug or glitch?) I attempted to use RNGreporter to calculate a pid for various spreads and when I tried them out I got an illegal Jirachi. In the error log it says "PID Type:None" when you look at the log on the Legal Shiny one it will say "PID Type: Channel". I don't know if I'm doing something wrong or if it's a problem on Pkhex's end.

![1](https://user-images.githubusercontent.com/31756219/31856131-456eb7f8-b688-11e7-88d4-bca2bcf85162.png)
![2](https://user-images.githubusercontent.com/31756219/31856133-47746b42-b688-11e7-844d-17babc7c22ec.png)

Also, I was trying to search for a way to find pids and spreads for WISHMKR Jirachi, the PID Type for that says  "BACD_R" on a legal Jirachi, could anyone help me find a tool that can give me various spreads using this PID Type.

**Comment by kwsch** [comment]
PKHeX checks beyond PIDIV for channel, which includes SID, Version, and Gender.
https://github.com/kwsch/PKHeX/blob/791a41b1a7a1817bf40e430f45c73b3225d872a1/PKHeX.Core/Legality/RNG/MethodFinder.cs#L212-L243

PokeGen can search for BACD spreads but is incredibly slow; I'm not aware of a search tool.
There's only 2^16 seeds, quick to bruteforce the entire list (done many years ago):
https://www.dropbox.com/s/tspclk1bv1yzdfk/CGR%20%28BACD%29%20Seed%20---%20PIDIV%20%28WISHMKR%20Jirachi%29.xlsm?dl=0

**Comment by kwsch** [comment]
Can step through the source code to see what values it is expecting.
PKHeX can also generate random ones. No plans for a PIDIV/etc search.

**Comment by ReZeroEmiria** [comment]
@kwsch Sorry if this is a silly question but how can I step through the source to see what value it is expecting? I'd like to make a couple different spreads from the screenshot I sent you so PID/IV search is not needed I just need a way to know what expected values will make this Jirachi Legal. Thank you (:

**Comment by kwsch** [comment]
Run the program under a debugger; compile with visual studio and set a breakpoint at one of the offsets for the method, then step through to see the comparisons done.

**Comment by ReZeroEmiria** [comment]
@kwsch  I'll ask my friend to see if he can help me with that (:
Just wondering, would it be possible to add a batch editor command to autofill this?

Like
=OT_Name= CHANNEL
=Species= 385
.(Game version)/Origin Game/Gender = $suggested

The first two just for a filter, (PID/IV can be found using rngreporter) just a thought since this event has a lot of forums and talk surrounding it, I'm sure I wouldn't be the only one who would benefit from something like that.

**Comment by kwsch** [comment]
No.
