### ISSUE TITLE
Spearow (KENYA) Gen 2 Flagged as Illegal

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#1538]
The Spearow that RANDY gives to you is flagged as illegal.

Invalid: Unable to match an encounter from origin game.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Move 4: Empty Move.

===

Encounter Type: Invalid (Spearow)

**Comment by sora10pls** [comment]
[021 - KENYA - BDAC.zip](https://github.com/kwsch/PKHeX/files/1405156/021.-.KENYA.-.BDAC.zip)
