### ISSUE TITLE
PKHeX Error

### ISSUE THREAD

**Issue by Bulbasaur1503** [kwsch/PKHeX#1539]
Exception Details:
System.Configuration.ConfigurationErrorsException: The configuration section 'connectionStrings' has an unexpected declaration.
   en System.Configuration.ConfigurationManager.get_ConnectionStrings()
   en System.Configuration.PrivilegedConfigurationManager.get_ConnectionStrings()
   en System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   en System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   en System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   en System.Configuration.SettingsBase.get_Item(String propertyName)
   en System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   en System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   en PKHeX.WinForms.Properties.Settings.get_Unicode()
   en PKHeX.WinForms.Main.FormLoadConfig(Boolean& BAKprompt, Boolean& showChangelog, Int32& languageID)
   en PKHeX.WinForms.Main.FormLoadInitialSettings(String[] args, Boolean& showChangelog, Boolean& BAKprompt)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Mauricio.Mauricreeper\Downloads\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Mauricio.Mauricreeper\Downloads\PKHeX\PKHeX.Core.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=es, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_es_b77a5c561934e089\System.Windows.Forms.resources.dll

mscorlib.resources, Version=4.0.0.0, Culture=es, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_es_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
Unable to load settings.

**Comment by kwsch** [comment]
Something went wrong parsing your configuration settings (corrupt file), however, the program (c# framework) did not report back the file name.

Try finding the config file and deleting it manually.
https://github.com/kwsch/PKHeX/search?q=ConfigurationErrorsException&type=Issues&utf8=✓

https://github.com/kwsch/PKHeX/issues/914#issuecomment-283572542
(replace username with your own)
