### ISSUE TITLE
Event flags window, Ribbon editor window and Medal editor window still have the scroll bar problem

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#154]

**Comment by kwsch** [comment]
I didn't change anything for those; [you said the Medal editor worked](https://github.com/kwsch/PKHeX/issues/149#issuecomment-236377523).

Does the main window bottom-right scroller behave but every other one doesn't?

**Comment by poutros** [comment]
I didn't say the medal editors scroll bar worked. On that other issue I only mentioned that the super train window and the inventory editor worked on the previous release. With this release (I compared both), the only window that has the problem fixed in comparison to the previous release is the main window. Now, the only windows that are left with this problem are the windows mentioned in the title.

**Comment by kwsch** [comment]
Ah I can see, I was confused with "Super Training" and the "Super Training Medals".

Good to hear confirmation that the FlowLayoutPanel fix worked, just need to fix the TableLayoutPanels (the 3 you mentioned).

**Comment by kwsch** [comment]
Resolved in the [1337th commit](https://github.com/kwsch/PKHeX/commit/ceff3845b792f13a84847162d04c2465fc94f21e).
