### ISSUE TITLE
[Feature Request] Directly load Wonder Card from URL to editing tabs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1542]
Useful for tweets from @mysterygiftbot on Twitter.

Instead of having to do the following:
- Have a save file open
- Open Mystery Gift Editor
- Copy image URL to clipboard
- Import URL
- Export WC7
- Load WC7 into editing tabs

The user could instead copy the image URL and directly import it to editing tabs should they only want the PKM and not the Wonder Card.

Perhaps CTRL click the PKM sprite to do so? As far as I can tell, CTRL shortcut isn't used for that at all.
Shift converts to QR, and Alt imports a Showdown set.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/a03ac10fc5a2c52e3264f6525f02be80a5972d40/PKHeX.WinForms/MainWindow/Main.cs#L989-L1014

Should probably just redirect the data[] loading to the main data loading method, as there's currently a way to load invalid pkm data to certain save types... ;)

**Comment by kwsch** [comment]
now ur gifs are old news

**Comment by sora10pls** [comment]
hahaha maybe I'll post an updated tweet if I'm not lazy after work
