### ISSUE TITLE
Default name error of PKHeX and suggestion

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#1547]
Thank you for solving the encoding issue.
I report on issues related to gen2 vc that have not yet been solved.
First, the korean default name of the pokémon is automatically changed in PKHeX.
The korean default name for Pikachu is "피카츄" However, after setting the default name, pressing "view" changes it to "피카췄".
![1](https://user-images.githubusercontent.com/24352145/31978428-5ae8c064-b97c-11e7-9009-394eaaa71e34.jpg)
![2](https://user-images.githubusercontent.com/24352145/31978430-5b694892-b97c-11e7-9dce-74c2b8f2b750.jpg)
That is, all of the Pichu, Pikachu, and Raichu using "츄" will have the wrong default name.
Machamp and Porygon2 have the same problem.
                 Default name - The default name changed in PKHeX
Machamp :    괴력몬       -      괴렇몬
Porygon2 :     폴리곤2    -       폴리곤

The second is a problem with Pokemon whose default names differed between now and in the past.
D / P was released and Pokemon Korea was officially translated into Korean. In this process, the Korean name of some Pokemon which was translated in G / S was changed.
                   Gen 2 - After gen 4
Tangela :   덩구리 - 텅구리
Poliwhirl :  수륙챙이 - 슈륙챙이

In the case of these two Pokémon, I think it is necessary to distinguish it from the other generations.

**Comment by kwsch** [comment]
first few are related to encoding table documentation errors. I've already fixed a few but I have zero familiarity with korean

https://github.com/kwsch/PKHeX/commit/3970b177afc1a7bc6f0c268beb85d1ad3a1ecf4f
https://github.com/kwsch/PKHeX/commit/cc2e379880990e9a219142e397d85c999d083bec

for the re-localized names, probably best to add a branch to `GetSpeciesNameGeneration` for fixing generation=2 && language=8, similar to how the french diacritics replacement works.

**Comment by host1126** [comment]
On the last commit, most Korean are displayed normally in the game. But the first problem I report is that PKHex automatically converts the correct default name.

**Comment by kwsch** [comment]
Right, PKHeX converts from `ingame -> text -> ingame`; basically A->B->A. The translation is consistent for both directions.

If some characters are swapped in the translation table, what they show up as ingame will be different from what is displayed in PKHeX. Getting the translation table to match the game is the tedious part ;)

**Comment by host1126** [comment]
Please understand that my English is not good enough to explain this problem. The characters typed in PKHeX match the game exactly. There is no problem with that. So I think this is not an encoding issue, but a problem with PKHeX itself. Or I may have misunderstood. However, it is certain that I have a problem with the five Pokémon I reported for the first time. After checking, I did not have any problems with the rest of Pokemon.

**Comment by kwsch** [comment]
>So I think this is not an encoding issue, but a problem with PKHeX itself

I agree

Fixing this is a more complex than fixing a single line of code, so I am just providing notes for myself to fix it later when I have more free time :)

- [ ] fix swapped chars: 츄 and 췄 in [StringConverter](https://github.com/kwsch/PKHeX/blob/a6ef1055445ba42eb6c10c40784c86b3c965789b/PKHeX.Core/PKM/StringConverter.cs) KOR_8 (`{0xE8, "췄"} - {"츄", 0xF2}`)
- [ ] fix generation specific localization cases in [GetSpeciesNameGeneration](https://github.com/kwsch/PKHeX/blob/a6ef1055445ba42eb6c10c40784c86b3c965789b/PKHeX.Core/PKM/PKX.cs#L217)

**Comment by host1126** [comment]
Okay. Thank you for your kind answers.
