### ISSUE TITLE
G/S VC Porygon2 korean default name issue

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#1548]
Thank you very much for solving the problem reported last time.
I think this is the last issue with the default name.
![porygon2](https://user-images.githubusercontent.com/24352145/32092439-86c7b506-bb33-11e7-8912-77bf9b9bf750.jpg)
The green box is the default name in the game and the red box is the default name for PKHeX.
I have dumped polygon 2 captured directly inside the game, not through PKHeX. I hope this helps.
![porygon2-1](https://user-images.githubusercontent.com/24352145/32092759-c928c74a-bb34-11e7-9c21-9422cf165a5b.jpg)

Finally, thanks again for your efforts.

**Comment by kwsch** [comment]
ah makes sense, looks like the 0x0 & 0xB kor table "numbers" should actually be `０１２３４５６７８９` not `0123456789`
