### ISSUE TITLE
Colosseum dogs - Invalid met location

### ISSUE THREAD

**Issue by ByReverso** [kwsch/PKHeX#1549]
After catching a set of Colosseum dogs (Raikou, Entei & Suicune) I noticed that PkHex flagged as illegal Raikou and Entei. All of them were catched at _Deep Colosseum (C) Agate Village (XD)_.

The message shown is:

`Invalid: Unable to match an encounter from origin game`

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/0e9960909bf9ea6fa4cee6ef4b1b627f975b6a89/PKHeX.Core/Legality/Encounters/Data/Encounters3.cs#L419-L427

need to see pkm files to get the met location ID

**Comment by ByReverso** [comment]
[ColoDogs.zip](https://github.com/kwsch/PKHeX/files/1425199/ColoDogs.zip)

Deep Colosseum Entei & Raikou. Sorry, already purified them.
