### ISSUE TITLE
About window seems to be missing this last update's changelog

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#155]

**Comment by sora10pls** [comment]
I see it just fine. This is from the compiled version on the PKHeX thread on ProjectPokemon

![screenshot_1](https://cloud.githubusercontent.com/assets/17801814/17278256/acfc1072-5726-11e6-83a9-dcb5ea72be28.png)

**Comment by poutros** [comment]
Are you sure? Because the last update is 07/31/16 and 07/28/16.

**Comment by sora10pls** [comment]
Oh yeah, now I see what you mean. The changelog is updated on GitHub (https://github.com/kwsch/PKHeX/blob/master/Resources/text/changelog.txt), but the compiled version on the thread doesn't include it

![screenshot_2](https://cloud.githubusercontent.com/assets/17801814/17278283/93e07e1a-5727-11e6-9964-a50c5375c7f3.png)

**Comment by poutros** [comment]
Yes, I know.
