### ISSUE TITLE
Pkhex don't detect Leafgreen

### ISSUE THREAD

**Issue by chgs54** [kwsch/PKHeX#1551]
Hi. I'm new to github so if I put this issue in the wrong place, I'm very sorry. I have PKHEX 20171017 and it doesn't detect my pokemon leafgreen .sav properly. I don't have access to party-battle box. 
Moreover, I cannot edit joyful games in misc edits section. Items and roamer section are also not working properly.
Surprisingly, when I loaded my firered .sav into the program it worked just fine. PKHEX just doesn't seem to detect my leafgreen .sav.cause when I'm loading my firered .sav I have a new window that says FireRed/LeafGreen Save File detected.
Also, there is no Clock (RTC) section in my firered .sav.
Could you help me with my problem?
Thanks a lot.         
![1](https://user-images.githubusercontent.com/33248006/32213652-5b04ef74-be1c-11e7-8c0e-5320649ed894.png)
![2](https://user-images.githubusercontent.com/33248006/32213653-5b269f2a-be1c-11e7-8930-168d425f2669.png)
![3](https://user-images.githubusercontent.com/33248006/32213654-5b4af8c0-be1c-11e7-9a0f-52636ffa9d34.png)
![4](https://user-images.githubusercontent.com/33248006/32213655-5b6b5b2e-be1c-11e7-8b6a-eb883b792b44.png)

**Comment by ReignOfComputer** [comment]
Could not reproduce. Can you attach your save file?

**Comment by kwsch** [comment]
Hold control when opening the save file to get the gen3 savegame selection override menu.
https://github.com/kwsch/PKHeX/blob/e9cebf933c47bb49b299daa9f19c8b54106b7ce7/PKHeX.WinForms/MainWindow/Main.cs#L847-L872

I'll assume that you've used cheat codes to modify values in the save file; some codes are damaging (item codes) which breaks the save detection routines.

**Comment by chgs54** [comment]
Thanks a lot. You're the best man
