### ISSUE TITLE
[Bug] Colosseum legality issues

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1556]
I don't actually have a Colosseum (or even XD) save file on hand so I borrowed my friend's save file who's been streaming the game, obviously without any hacks or cheating involved. He said that he doesn't mind his TID/SID being out in the wild :P

In his save file, I found 3 PKMs that were flagged as illegal, likely due to location IDs.
[colo_pkm.zip](https://github.com/kwsch/PKHeX/files/1442893/colo_pkm.zip)

**Comment by kwsch** [comment]
Hitmontop: 68
Raikou: 113
Entei: 106
