### ISSUE TITLE
[Feature Request] Disallow game-specific Forme transferring

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1559]
There are several instances where PKHeX will allow transfer between two same-Generation save files despite the Forms not existing in the target game.

- Rotom Forms can only be traded between Pt/HGSS
- Giratina-Origin can only be traded between Pt/HGSS*
- Shaymin-Sky can only be traded between Pt/HGSS*
- Tornadus/Thundurus/Landorus-Therian can only be traded between B2W2*
- Spiky-Eared Pichu can only be traded between HGSS
- Kyurem-White/Black can only be traded to BW after being defused*
- Cosplay Pikachu can only be traded between ORAS

\* => if the Pokemon is transferred to the previous game (ie, Pt -> DP or B2W2 -> BW), PKHeX will successfully transfer but then give the following legality error:
![image](https://user-images.githubusercontent.com/17801814/32417623-1f64692e-c22a-11e7-9e6c-d892b10f3701.png)

Because the Forme ID for the PKM is still 1, PKHeX is outputting Abilities for Forme ID 1 rather than 0.
Examples include Giratina-Altered with Levitate, and Thundurus-Incarnate with Volt Absorb.

This will also probably end up getting used for I Choose You Cap Pikachu, Dusk Form Lycanroc, and Dusk Mane/Dawn Wings Necrozma ;)

**Comment by kwsch** [comment]
Transfer (`PKMConverter`) code currently works between types (PK4->PK5); there is no format intermediary between versions of the same format.

We have two types of incompatibility:
* Trade Incompatibility (same generation, different games).
* Transfer Incompatibility (unable to transfer form up).

The Legality Check code is non-specific with regard to a SaveFile, in that a PKM is not checked against constraints for the save file it may exist on.

I'd rather not block users from setting formes that are exclusive to future same-generation games; I think the simplest resolution is to add a new constructor to the `LegalityAnalysis` that can permit save specific checks. That would solve trade incompatibility flagging.

The transfer incompatibility case only applies to GenNumber==4 Pichu and GenNumber==6 Pikachu. These can be hard-coded in the PKMConverter code to reject the transfer.
