### ISSUE TITLE
PKHeX error

### ISSUE THREAD

**Issue by LinkkJ** [kwsch/PKHeX#1561]
Everytime I open PKHeX.exe I get an error "A fatal non-UI PKHeX error has occurred, and there was a problem displaying the details. Please report this to the author." And here I am, I already update .NET framework and it still shows up, I tried researching it online and I didn't find any answers, It didn't use to happen before, I updated my laptop to Windows 10 but it still used to work fine except I couldn't see my Trainer Info, so I reinstalled thinking that would fix it but it just made it worse, I've reinstalled PKHeX several times too. I'm not sure what else I can do but help would be appreciated. Thanks
![screenshot_1](https://user-images.githubusercontent.com/33411089/32427604-df827c58-c286-11e7-9682-9e29f2c27d86.png)

**Comment by kwsch** [comment]
Extract the dll and the exe to the same folder.

**Comment by LinkkJ** [comment]
What do you mean?
