### ISSUE TITLE
Unable to match an event in mystery gift database

### ISSUE THREAD

**Issue by Rileythe3rd** [kwsch/PKHeX#1562]
There is no US silvally with the OT AETHER in the mystery gift database, so I cant properly check if the event silvally i have is legal or not.

**Comment by sora10pls** [comment]
https://github.com/kwsch/PKHeX/issues/1518#issuecomment-335507415

**Comment by Rileythe3rd** [comment]
Do you know how I can add the legit event to the folder? I don't actually know if the one I received is legal, so I don't want to manually add the wrong mon

**Comment by sora10pls** [comment]
Mystery Gift Editor -> View Wonder Card -> Export
Save the WC7 file to your `mgdb` folder, that's located where your `PKHeX.exe` is.
![image](https://user-images.githubusercontent.com/17801814/32430337-d0cf902c-c29c-11e7-840b-0fb0ffa57142.png)

**Comment by Rileythe3rd** [comment]
Ok thank you
