### ISSUE TITLE
Legality Bug for Aether Silvally?

### ISSUE THREAD

**Issue by DavidKDean** [kwsch/PKHeX#1567]
I'm having the same exact issue with the Aether Silvally as koukakou did on issue #458.

The error is:

Invalid Relearn Move 1: Expected no Relearn Move in slot.
Invalid Relearn Move 2: Expected no Relearn Move in slot.
Invalid Relearn Move 3: Expected no Relearn Move in slot.
Invalid Relearn Move 4: Expected no Relearn Move in slot.
Invalid: Unable to match to a Mystery Gift in the database.

Have I don't something wrong? The エーテル Silvallly shows up as 100% legal.

**Comment by sora10pls** [comment]
https://github.com/kwsch/PKHeX/issues/1518#issuecomment-335507415
#1562

**Comment by DavidKDean** [comment]
Ahh. I had the file "0629 SM - Æther Shiny Silvally.wc7full" under the mgdb folder. Seems an export of an imported card is needed. Have yet to see that in any instructions.

Thanks!
