### ISSUE TITLE
Time Bug?

### ISSUE THREAD

**Issue by LinkkJ** [kwsch/PKHeX#1568]
So I've been playing Pokemon Sun for a while now but one day I changed the time on the system settings because they weren't correct, and when I went back to the game instead of being daytime it was night time, I tried changing it with PKHeX but it didn't seem to do anything here are some screenshots if there's more information that I could provide but I forgot please tell me.
![screenshot_2](https://user-images.githubusercontent.com/33411089/32526610-ebc82214-c3ef-11e7-8728-34fe1128f467.png)
![screenshot_3](https://user-images.githubusercontent.com/33411089/32526681-4d2ea24e-c3f0-11e7-93d5-98a5bb063132.png) I already tried both Sun Time and Moon time option and both don't change anything

![screenshot_1](https://user-images.githubusercontent.com/33411089/32526596-d0b01180-c3ef-11e7-9c50-4893a2702154.png) It was 7 pm irl on this picture

**Comment by kwsch** [comment]
Not an issue with PKHeX, try just using the Sun/Moon time values.

**Comment by LinkkJ** [comment]
How do I do that?

**Comment by kwsch** [comment]
Sun Time | Moon Time, not an individual value

**Comment by LinkkJ** [comment]
Yeah, I thought it'd be that, Like I said they didn't make any difference at all, I'll try again to see if changes
