### ISSUE TITLE
[Question] Can this program still be built by Mono, and how? 

### ISSUE THREAD

**Issue by koukakou** [kwsch/PKHeX#1569]
I've noticed that the program now require C#7. Is Mono still compatible? What is the command to use then? 

Thanks!

**Comment by kwsch** [comment]
I'm only familiar with Visual Studio.
Hitting rebuild all in visual studio will generate the compiled program/dll for all configurations; you can grab the resulting exe from there.

Keep in mind the program does not work for the new data, it only recognizes the new savefile format.

**Comment by koukakou** [comment]
Thank you @kwsch 
For me Visual Studio is too huge (>20GB, community version). So I am looking for a lightweight compiler.

**Comment by kwsch** [comment]
I'm not aware of any lightweight IDE (like SharpDevelop) that supports c# 6+; not sure if VS Code can compile or if you can use msbuild via command line.

**Comment by andrewseabolt** [comment]
Hi! I'm observing the following errors when attempting to build in VS for Mac. Any suggestions?
![screen shot 2017-11-08 at 4 55 58 pm](https://user-images.githubusercontent.com/33500146/32576899-49c7e352-c4a6-11e7-8d6b-43a73d2c1c68.png)

**Comment by kwsch** [comment]
need to build the PKHeX.Core project before the PKHeX.WinForms project

**Comment by koukakou** [comment]
I will just rely on https://teamcity.projectpokemon.org/ for latest builds. No longer wanted to install VS.
