### ISSUE TITLE
Improvement in spanish language

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#157]
Hi, I made some improvements in spanish text but I can not push them to repository.

**Comment by evandixon** [comment]
1. Create a fork of PKHeX
2. Push your changes to the fork
3. Create a pull request merging your changes into kwsch/PKHeX

**Comment by evandixon** [comment]
Closing this issue since PR 158 was opened.  Further discussion should be moved there
https://github.com/kwsch/PKHeX/pull/158

It seems legit IMO.  As legit as it can seem without me knowing any Spanish or having seen how the layout.
