### ISSUE TITLE
PKHeX crashes when you click on Items window

### ISSUE THREAD

**Issue by Bapthax** [kwsch/PKHeX#1571]
I compiled the lastest version (as of 8th November 2017), i clicked on the "ITEMS" window and i get an exception details: **System.IndexOutOfRangeException: Index was outside the bounds of the array.** If you want to know more, here is a .txt file. (Sorry for my bad english, i'm not really fluent)
[untitled.txt](https://github.com/kwsch/PKHeX/files/1455061/untitled.txt)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1570

We're well aware that numerous features are 'enabled' but not working (ie crashing).
Will be fixed in the next 24h.
