### ISSUE TITLE
USUM Legality Submissions

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1577]
If you find something flagged illegal but shouldn't be (or vice versa), drop a sample or let the devs know here!

-----
Original Content

If it helps, I'll list out some Pokemon that are still marked as illegal in the latest commit as I continue to play through.

Totem Pokemon: https://github.com/ReignOfComputer/RoCs-PC/tree/master/25%20-%20Gen%20VII%20-%20USUM%20Collection/Totem%20Pokemon

The "Ditto Five": https://github.com/ReignOfComputer/RoCs-PC/tree/master/25%20-%20Gen%20VII%20-%20USUM%20Collection/Ditto%20Five

**Comment by ReignOfComputer** [comment]
Doesn't look like all of them have HA, @sora10pls (referring to your comment in https://github.com/kwsch/PKHeX/pull/1576 ).

Totem Araquanid that theSLAYER and I got has normal ability.

**Comment by kwsch** [comment]
At this point, most if not all of the fixes will be changing the Location value from -1 to the actual met location ID.

**Comment by sora10pls** [comment]
@ReignOfComputer HA when applicable. As shown in my PR, Araquanid, Salazzle, and Mimikyu have Ability 1 since they all only have one Ability

**Comment by ReignOfComputer** [comment]
The Salazzle I just got has Corrosion and not Oblivious.

**Comment by sora10pls** [comment]
I probably just saw Mimikyu only has Disguise and said the other 3 were the same. 

Rest assured, look at the PR I submitted. Those 3 entries already have “Ability = 1” right in them

**Comment by sora10pls** [comment]
Another thing I literally just noticed after sleep deprivation yesterday: Totem Vikavolt is probably US exclusive, as I got Togedemaru in UM.

**Comment by architdate** [comment]
Captured Kyogre, registeel, mewtwo, palkia in ultra moon from Ultra Space Wilds as well. I think it is safe to assume that every Non UB is level 60 and captured in Ultra Space Wilds. 

more over the UBS i captured so far are xurkitree obtained at ultra plant
nihilego obtained in ultra deep sea
pheromosa obtained in ultra desert
All ubs are level 60 as well.

**Comment by kade-robertson** [comment]
I imagine this is simply just going to require validating this Mystery Gift, but the QR code from going to see the Pokemon movie which gives you a Pikachu with Ash's hat is also considered invalid.

https://transfer.sh/3uolQ/025-07%20-%20Pikachu%20-%20D7C4633EA75D.pk7

**Comment by sora10pls** [comment]
@kade-robertson https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Encounters/Data/Encounters7.cs#L208

**Comment by ReignOfComputer** [comment]
Cap Pikachu location should be 40005.

**Comment by kade-robertson** [comment]
Even after the latest commit it's still considered invalid:

![Pic](https://i.imgur.com/ChP6odT.png)

**Comment by ReignOfComputer** [comment]
This hasn't been added in the latest commit yet.

**Comment by kade-robertson** [comment]
But it's in the encounter data file?

**Comment by sora10pls** [comment]
>Cap Pikachu location should be 40005.

-01 in the code is a placeholder that will flag every location as illegal; it hasn't been found until now.

Wait until it gets added.

**Comment by kade-robertson** [comment]
Right, my point was that's not the only invalid part. I've updated it with the proper location and it still isn't valid:

![Pic](https://i.imgur.com/ToiSVgZ.png)

**Comment by ReignOfComputer** [comment]
Some special handling needed because of the forme.

**Comment by architdate** [comment]
Zygarde is located at resolution cave. Cosmog is at lake of the sunne/moone. I'll upload the pk7's in a bit

**Comment by sora10pls** [comment]
Zygarde is already documented, Cosmog still needed I’m pretty sure.

**Comment by architdate** [comment]
Thats cosmog and a 10% zygarde that sina and dexio give when you battle them at their lab after getting the resolution cave zygarde
[Mons.zip](https://github.com/kwsch/PKHeX/files/1464252/Mons.zip)

**Comment by bui** [comment]
Surfing Pikachu, obtained by beating all 4 Mantine Surf hiscores and going to the associating building in Heahea City:

https://my.mixtape.moe/mhdlaz.pk7

**Comment by sora10pls** [comment]
Pikachu - `070`
Zygarde - `118`
Cosmog  - `142` (Sun)
Cosmog  - `144` (Moon)

**Comment by Demie3DS** [comment]
http://prntscr.com/h9hxvl

Dawn Form Necrozma is viewed as illegal because of Moongeist Beam, which it gets after using Z-Lunarizer

**Comment by AngefloSH** [comment]
Poipole has two locations. If you do not take it at Megalo Tower, you can return to Ultra Megalopolis, and the Recon Squad guy who gives you Poipole is now outside the tower.

**Comment by architdate** [comment]
The legality should probably add exceptions to ribbons such as Battle Tree victor, I won the battle tree singles using my necrozma which gave me a ribbon and made the mon illegal. I'm at a friends house right now, but if its not fixed by the time i'm home, I can send a PR to fix it, Just letting u guys know about this :)

**Comment by kwsch** [comment]
battle tree banlist is broken in the leaked copy, hence why you were able to compete with necrozma

**Comment by wwwwwwzx** [comment]
Seems 5 dittos have locked Ability 2 and locked natures: 
Bold, Jolly, Adamant, Modest, Timid

**Comment by Demie3DS** [comment]
Update

Same thing happens with Dusk Forme Necrozma and the Move Sunsteel Strike

**Comment by wwwwwwzx** [comment]
Bewear is at Hau’oli City (Shopping District)  
`Location = 20`

**Comment by ReignOfComputer** [comment]
Yay!

@wwwwwwzx out of curiosity, how do you trigger the Bewear encounter?

**Comment by wwwwwwzx** [comment]
@ReignOfComputer Bewear show in the shopping mall
