### ISSUE TITLE
Issue with Alola and Kalos hat Pikachus

### ISSUE THREAD

**Issue by DeathAngel74** [kwsch/PKHeX#1581]
![capture](https://user-images.githubusercontent.com/29271009/32641488-0ce4981c-c583-11e7-93de-fabd1061cf54.PNG)

First of all, thanks for all your hard work. I just noticed this with build #4054. Thanks in advance!

**Comment by kwsch** [comment]
Provide pkm files please (zip). Can't test/debug with screenshots.

**Comment by DeathAngel74** [comment]
[problematic_Pikas.zip](https://github.com/kwsch/PKHeX/files/1460001/problematic_Pikas.zip)
sorry about that. here they are.

**Comment by kwsch** [comment]
Works fine on current commits ;)

**Comment by DeathAngel74** [comment]
thanks
