### ISSUE TITLE
Handling Error 

### ISSUE THREAD

**Issue by ShadowsGod97** [kwsch/PKHeX#1586]
Starter Handling error plus inkay encounter as well, thanks for all your help

**Comment by ShadowsGod97** [comment]
No, just telling you that there's an error about that, for future updates...

**Comment by kwsch** [comment]
Please post PKM(s) that is incorrectly flagged.

**Comment by ShadowsGod97** [comment]
Just figured it out... Thanks for your attention... And i compile every commit you upload....
