### ISSUE TITLE
"PKHeX.Tests.dll is missing"

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#1587]
I'm trying to open up the program, but when I hit start, I get a message that says that PKHeX.Tests.dll is missing.

**Comment by ReignOfComputer** [comment]
Oh - you're attempting to run it via an IDE? Make sure PKHeX.Tests exists under the Solution, it should be in Tests > PKHeX.Tests.

**Comment by Araraura** [comment]
I'm still getting that error

**Comment by kwsch** [comment]
hit rebuild all

**Comment by Araraura** [comment]
Nope, still not working

**Comment by ReignOfComputer** [comment]
More information required about your environment. Make sure you're following the Building instructions in the Readme.

What version of Visual Studio are you on (if that's what you're using)? A screenshot of your Solution Explorer and solution project folder would be helpful.

If you just want the latest build, you can also just hit the green tick and download a precompiled version.

**Comment by Araraura** [comment]
Where is the green tick?

**Comment by ReignOfComputer** [comment]
https://github.com/kwsch/PKHeX/commits/master

**Comment by Araraura** [comment]
Now what? I can't see a download button

**Comment by ReignOfComputer** [comment]
https://projectpokemon.org/home/forums/topic/42335-is-pkhex-compatible-with-usum-yet/
