### ISSUE TITLE
Necrozma Forms not Applying [PMUS/PMUM]

### ISSUE THREAD

**Issue by CDAGaming** [kwsch/PKHeX#1598]
Ex: When i select the 'Ultra' Form of Necrozma, ingame it still displays and shows as its 'Normal' Form

**Comment by egzonqj** [comment]
Maybe cause Ultra form is just like Mega or Primal Reversion

**Comment by sora10pls** [comment]
@egzonqj is correct. Make sure it's not being set to your Party, but rather any PC Box slot, as the game will auto-revert Mega Pokemon/Primal Pokemon/Ultra Necrozma that are in your Party ;)

**Comment by CDAGaming** [comment]
Ah, okay, then thats probably why since it is in my party when i tried to change its form
