### ISSUE TITLE
Trainer Info Database

### ISSUE THREAD

**Issue by SirHax0rz** [kwsch/PKHeX#160]
A very useful feature would be to include a database or list of Trainer Info (Trainer Name, ID, SID) so when you go to fill in the OT for Pokemon, typing one of the 3 automatically will put in the other 2 parts. There could be more to it than that but it's just a basic idea right now.

**Comment by kwsch** [comment]
Just click the "OT" label to import the Trainer Information from the current save file.

There's a list of shortcuts accessible via Options->About PKHeX->Shortcuts button.
