### ISSUE TITLE
USUM: Fashion Items missing

### ISSUE THREAD

**Issue by froslumugu** [kwsch/PKHeX#1602]
When running the Give all Fashion Items cheat (both All Legal and Everything), several items appear to be unset, such as the Casual Cap, the Athletic Cap, Street Cap, Sports Cap sets, and possibly more.

**Comment by kwsch** [comment]
Sourced data from:
https://projectpokemon.org/home/forums/topic/39433-sunmoonultra-sunultra-moon-save-research-thread/?do=findComment&comment=222831

will leave open until a resolution is determined

**Comment by sora10pls** [comment]
From Holla! on PP:

>I just checked and you're right, the starting offset isn't 42616, but **42600**. Please do re-use them as I've rectified my post on this.

**Comment by kwsch** [comment]
Heh figured something was up with the offsets :)
Removing the offset shift for legal/illegal CopyTo will fix the issue. Probably need to remove the newgame comment referring to +0x16 too, assuming those offsets are correct.

**Comment by FeralFalcon** [comment]
Hey @kwsch it's me from the PP link.

Just need to clarify that the legal and illegal codes the current commits of PKHeX generates are slightly messed up, they had some values that I shouldn't have 00'd out, so I had to correct said codes. Please do re-use the code blocks for both gender's legal and illegal ones I posted on the PP thread.

Thanks for bringing this up, and sorry for the inconvenience!

**Comment by kwsch** [comment]
@FeralFalcon no worries, I'll trash the current values and reimplement :)

**Comment by FeralFalcon** [comment]
One more thing sorry in hindsight these offsets should be left as byte 03

Female
4265e
42808
42864
42995
429b4
42af9
42ba8

Male:
4263a
42709
427da
42905
429d9
42ab1
42b84

**Comment by kwsch** [comment]
The 01 / 03 difference is only to indicate if the item is "NEW".

Binary:
`1 = 01`
`3 = 11`
(lowest bit is 'hasItem', the other bit is 'is new')

Won't matter either way; can maybe enhance the 'cheat' to apply new only if the item was never in the wardrobe.

**Comment by FeralFalcon** [comment]
Yeah I know, but these ones specifically don't change at all. It's like that with the Sun/Moon payloads as well.
