### ISSUE TITLE
[Feature Request] Physical / Special / Status move indicators in PKHeX WinForms

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1603]
This would be more of an addon to do when the core dev of USUM is done, but its a great feature that a lot of competitive players would appreciate if implemented.
An implementation suggestion would be, if the move is legal instead of disabling the illegal move (red exclamation mark) marker, you would indicate with an icon if it is a physical special or a status move. (Just an idea, i'm pretty sure that there would be much more efficient implementations of this)

(From the coders perspective, I would assume that the filtering can be done by just having a text resource indicating which move is physical or special or status based)

**Comment by sora10pls** [comment]
If implemented, there will need to be an edge case for Photon Geyser; physical or special depending on which of Necrozma’s attacking stats is higher.

**Comment by kwsch** [comment]
No thanks,  too much visual clutter for negligible hajj

**Comment by ReignOfComputer** [comment]
Maybe if it were a tooltip on mouse hover of the individual move combobox?

**Comment by architdate** [comment]
That would work too ;o
