### ISSUE TITLE
[Feature Req] Mantine surf score editing!

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1605]
Plz <3

**Comment by sora10pls** [comment]
0x4538 = Melemele
0x453C = Akala
0x4540 = Ula'ula
0x4544 = Poni

**Comment by architdate** [comment]
Is it possible to add flags for unlocked surf moves too? Since once edited above the "boss score" threshold, you can't unlock a surf move if it was locked prior to the score editing. @kwsch

**Comment by kwsch** [comment]
Needs documentation.

**Comment by sora10pls** [comment]
@architdate #1612

**Comment by architdate** [comment]
thanks a lot man :] @sora10pls
