### ISSUE TITLE
[ US - UM: Bug Report ] Hall of Fame count.

### ISSUE THREAD

**Issue by smileynation** [kwsch/PKHeX#1607]
It seems that the count in the Hall of Fame is fixed to 77 when exporting save data.

<img width="300" alt="2017-11-15 14 21 52" src="https://user-images.githubusercontent.com/32617637/32820259-c202f4fa-ca10-11e7-9cf4-4d0c7878fdc8.png">

**Comment by kwsch** [comment]
Not able to replicate on any of my save files

**Comment by CyraFen** [comment]
I've had this issue with both SUMO and USUM files

![sumo hof 77](https://user-images.githubusercontent.com/25874350/32820663-931383b2-c99d-11e7-9c71-0d7ede4115ec.PNG)
![usum hof 77](https://user-images.githubusercontent.com/25874350/32820665-96270326-c99d-11e7-96fe-bd6b82821acf.PNG)

**Comment by smileynation** [comment]
Ultra Sun has been counted even before entering the Hall of Fame.
Ultra Moon entered the Hall of Fame once, but it has counted 77 times.

**Comment by smileynation** [comment]
Ultra Sun has been counted even before entering the Hall of Fame.
Ultra Moon entered the Hall of Fame once, but it has counted 77 times.
