### ISSUE TITLE
[Bug] USUM - Illegal Pokemon (Trade Evolution Required)

### ISSUE THREAD

**Issue by TankedThomas** [kwsch/PKHeX#1609]
I just compiled the latest commit of PKHeX, opened my Ultra Moon save, and my completely legit Butterfree is reported as illegal because it requires trade evolution.

I've attached the (zipped) pk7 from my save. I can provide the save if need be but I'd rather not unless it's necessary.

Yes, I did nickname it that because I am indeed a horrible person.

EDIT: Just realised it's affecting a few in my party too - Kadabra, Brionne and Trumbeak. I'm not that far into the game (just at the second island), so I'm going to assume there are others with this issue too since I've already found four out of my small amount of Pokemon.
Here's an updated zip file with all four pk7s.
[illegal_trade_evo_pk7.zip](https://github.com/kwsch/PKHeX/files/1475686/illegal_trade_evo_pk7.zip)

**Comment by kwsch** [comment]
Possibly goofed via prior commit:
https://github.com/kwsch/PKHeX/commit/897ed84933fa1741625d8ed73087d2f95bbd05ed

Try using a commit earlier than the most recent.
