### ISSUE TITLE
Pkhex Flags legal pokémon when it's not

### ISSUE THREAD

**Issue by ShadowsGod97** [kwsch/PKHeX#1613]
Hi! I was having a trouble when i was trading this pokémon... pkhex flagged it as legal but it's not... i compared it with other pk file of the same pokémon...

Here's the info:
3Fast%U (Serperior) (M) @ Life Orb
IVs: 0 Atk / 30 Def
EVs: 132 HP / 124 SpA / 252 Spe
Ability: Contrary
Level: 100
Timid Nature
- Dragon Pulse
- Giga Drain
- Hidden Power [Ice]
- Leaf Storm

(Couldn't upload the pk file to show u)

**Comment by ReignOfComputer** [comment]
Zip the pk file then attach it.

**Comment by ShadowsGod97** [comment]
It says that github does not supor that type of file...

**Comment by ReignOfComputer** [comment]
Then upload it to Mediafire or other host and post a link. If not, generate a QR code (right click the sprite at the center top, QR), click the QR to copy the image to clipboard, then paste it here.

**Comment by ShadowsGod97** [comment]
![pokemon](https://user-images.githubusercontent.com/30508666/32871832-f42319be-ca48-11e7-9860-4eb5df7871c8.jpg)

**Comment by ReignOfComputer** [comment]
Use the stable release on the forum. The version you're using (most likely one of the latest commits) is updated for USUM, which has move tutors. Your first move Dragon Pulse is a Move Tutor move. Either wait a day or so for USUM to release, or drop Serperior to Gen 6.

**Comment by ShadowsGod97** [comment]
Okay, thanks.
