### ISSUE TITLE
[Feature Request] Disallow transferring species 803-807 from USUM to SM

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1615]
A good inclusion before the next official release ;)

**Comment by SciresM** [comment]
Is this not handled automatically by the [MaxSpeciesID declaration in SAV7](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Saves/SAV7.cs#L70)?

**Comment by sora10pls** [comment]
It doesn't let you change species to anything above 802, but you're still able to transfer (either drag/drop or open) species 803+ into SM save files.

![image](https://user-images.githubusercontent.com/17801814/32912772-1130e4d8-cade-11e7-89d3-70ffefbb5665.png)

**Comment by SciresM** [comment]
Yeah, looks to me like this is already handled:

![pkhex](https://i.imgur.com/TDyV65U.png)

**Comment by SciresM** [comment]
Hmm, there are edge cases, though. Looks like SM save files will accept lycanroc dusk, partner cap pikachu fine and that *should* be fixed.

**Comment by sora10pls** [comment]
Strange, I don't get that prompt at all. It just straight up imports the PKM.

And on that note of what you brought up, that was actually brought up by me in a previous issue: #1559

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/1e377c2963420fcdb984b9337f7b508c565b6217/PKHeX.WinForms/Util/SAVUtil.cs#L168-L171

**Comment by SciresM** [comment]
IsNotTransferrable looks like a good place to edit -- there's a function in Ultra Moon .text called "IsNijiCompatible" -- I could reimplement and call it if gen == 7?

**Comment by sora10pls** [comment]
Found out my issue: my save file had the `.bak` extension. Removing the extensions entirely brought up the prompt.

**Comment by kwsch** [comment]
`PKMConverter` code is only called for PKM format interconversion and is not save-file specific.
Forme checking is done by the legality checks on the save file; can add forme check to the IsPKMCompatible check as well.

Bulk importing of a pcbin skips all these checks as the raw data is transferred in, hence the legality check serving its purpose.

**Comment by SciresM** [comment]
@kwsch Is there a location in SAV7 this could be easily implemented? CheckNijiCompatible is a very simple method to run on any incoming pokemon, would simplify things to just always do CheckNijiCompatible(PK7 pk7) on anything incoming.

**Comment by SciresM** [comment]
Added a helper method to PK7 that checks if the mon is compatible with SM: https://github.com/kwsch/PKHeX/commit/e8d1d1f5214c297e398736a56d7507d3d7d87da7

Not sure where it'd have to go to be used, but that's in place, at least, if we want it.

**Comment by SciresM** [comment]
Other thought -- FormConverter could perhaps be refactored to take in a GameVersion instead of a generation?

**Comment by kwsch** [comment]
Looks like the exact same checks (give or take) with the above IsPKMCompatible, which is already generalized for all games. I still think it is better to have something generalized, as this won't handle B2W2<->BW exclusive formes (which currently relies on the legality checker) in its current form.

Some portion of the legality check for `VerifyForm` can be extracted to determine if forme should be checked (exclusions being spewpa & scatterbug, off the top of my head are incorrectly missing form count values in gen6/7 personaltables). If the form is > the formcount permitted by the save file, then the message should be generated.

Hard part of rejecting injections is cleanly providing notification for the user. The PKM+derived classes aren't a good place for error message generation :\ SAVUtil is a wrapper for large operations, and will eventually be moved into PKHeX.Core when its compatbility with .NET Core is verified.

**Comment by SciresM** [comment]
Yeah, I agree a generalized mechanism would be preferable. Hmm...
