### ISSUE TITLE
Shortcut removed?

### ISSUE THREAD

**Issue by Arch9SK7** [kwsch/PKHeX#1618]
So despite it still being apart of the shortcuts in the tab explaining all of pkhex' shortcuts. the one for giving suggested movesets for relearn moves (at least for sun and moon save files doesnt work at all, haven't tried on any other saves). i have clicked in and around every inch of the box to get it to give me suggested relearn moves for my pokemon but it just will not show anything. I have tried shift clicking and control clicking and again nothing. Was this removed, bugged out? did i miss something in a previous build? the build i have is as of 11 commits ago now as i am writing this. (it is a simple diggersby).

**Comment by sora10pls** [comment]
You literally just click anywhere in the Relearn Moves groupbox, it was never removed or changed

**Comment by Arch9SK7** [comment]
Boi i did and it didn't work and i just now realized that it is only when you import a set from showdown that it doesn't work. (if you change one of the moves then try again it works again) but still a bug nonetheless.

**Comment by sora10pls** [comment]
I'm unable to replicate your issue regardless.

**Comment by Arch9SK7** [comment]
Enter this set then 

OG Bugz (Diggersby) (M) @ Master Ball  
Ability: Cheek Pouch  
Shiny: Yes
IVs: 31s
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- Fire Punch  
- Gunk Shot  
- Iron Head  
- Ice Punch

**Comment by sora10pls** [comment]
>IVs: 31s

Importing the set works fine for me, and automatically enters Relearn Moves.
```
OG Bugz (Diggersby) (M) @ Master Ball
Ability: Cheek Pouch
Shiny: Yes
EVs: 252 HP / 252 Atk / 4 SpD
Adamant Nature
- Fire Punch
- Gunk Shot
- Iron Head
- Ice Punch
```

**Comment by Arch9SK7** [comment]
that wasn't what i typed
ive you leave in the iv part i put in and the (invalid lines window shows up) you can no longer use relearn moves till you change a move on it.

**Comment by sora10pls** [comment]
The reason I excluded what I entered at the top of my comment is because Pokemon Showdown **never** exports that line, ever. It'll only display IV values if they're below 31.

**Comment by Arch9SK7** [comment]
well that is where the bug comes in

**Comment by sora10pls** [comment]
>Pokemon Showdown **never** exports that line, ever.

There is no bug with PKHeX, the problem lies with your invalid set.

**Comment by Arch9SK7** [comment]
omg i know an invalid line that bugs out a function in the program

**Comment by sora10pls** [comment]
If the user inputs an invalid set compared to what's expected, obviously, an invalid output will occur. PKHeX shouldn't have to baby the user for a line that Pokemon Showdown will never generate.

Please @kwsch, if you think it's necessary, lock this issue. The bug mentioned in the title doesn't exist.

**Comment by kwsch** [comment]
If you click the box and get no message, it's because the current moves match whatever is suggested.
If the current moves are invalid and you get no message, it's because there's something else that needs to be fixed.
