### ISSUE TITLE
Errors with Lycanroc

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#1619]
This is with a2e5219 (current latest commit)

Rockruff captured at Ten Carat Hill, with a Moon Ball, in Sun. It shows up fine.
Evolve it to Lycanroc in-game and it gets an "Unable to match an encounter from origin game" error.

I have it in a Moon Ball. I breed it to pass down the Moon Ball along with Rock Slide and Crunch.
The Rockruff I receive is in a Moon Ball, with Tackle, Leer, Rock Slide and Crunch as both its moves and its relearn moves. Everything shows up as legal.
Evolve it into Lycanroc, it gets "Evolution not valid (or level/trade evolution unsatisfied)" and "Can't obtain species in Ball", both of which are obviously not true.

Also, if the egg is traded before hatching, to have the egg met location as "a Link Trade (egg)" rather than "Nursery Helpers", all the relearn moves show up as invalid relearn moves, even though everything was legitimately bred and obtained in-game. None of my other traded egg-hatched Pokémon have this relearn moves error.

If I add a Latest (not OT) Handler, then suddenly everything becomes legal. But this shouldn't be required for any of this to be legal (except maybe for the traded eggs, but I did the trading by drag & drop between two instances of PKHeX, so if a latest handler *is* required for traded eggs, that means PKHeX isn't handling this properly.)

Everything is fine on 20171017 release.

(Github errors out whenever I try to upload & attach files, so I'll just share the .pk7 through dropbox.)
https://www.dropbox.com/s/d5dhnz5jjznwnwg/pkm.zip?dl=0

**Comment by kwsch** [comment]
Closed via https://github.com/kwsch/PKHeX/commit/8958646ae687d66edb063bd93a34985482a4490c
thanks for reporting ;)
