### ISSUE TITLE
[Bug] Dusk Form Lycanroc (event) flagged as illegal

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1622]
Rockruff flagged as legal, but when evolved, PKHeX says it can't match a gift in the Mystery Gift database. Doesn't happen with bred Dusk Form Lycanroc.

[745-02 - Lycanroc - 9067E86BC976.zip](https://github.com/kwsch/PKHeX/files/1481062/745-02.-.Lycanroc.-.9067E86BC976.zip)

**Comment by kwsch** [comment]
Closed via: https://github.com/kwsch/PKHeX/commit/55d8f4aa2684b6243796998baca4b6c8d89cffd0
recent release exe's updated with this fix
