### ISSUE TITLE
[USUM] New Game default flags checked

### ISSUE THREAD

**Issue by sebastienrouget** [kwsch/PKHeX#1625]
When loading a save at the very begining of the game (in your bedroom, when you just woke up), the following flags are already checked:

- Received Gift Cosmog
- Received Gift Magearna
- Solgaleo/Lunala Captured

Tested on version 20171117.
Save: [download](https://www.mediafire.com/file/kxvd8hil5q5955u/main)

**Comment by kwsch** [comment]
Working as intended; same as prior games. The game de-spawns certain encounters until the time you can naturally receive them.
