### ISSUE TITLE
[Enhancements] USUM Pokemon Showdown importing/exporting

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1626]
- Exporting sets for new Pokemon (species 803-807) [throws an exception](https://pastebin.com/H4Xu1BAC) (importing works fine)
- Dusk Mane Necrozma should import/export as `Necrozma-Dusk-Mane`
- Dawn Wings Necrozma should import/export as `Necrozma-Dawn-Wings`
- Dusk Rockruff should import/export without a Form name attached
- Totem-Sized Pokemon should export without a Form name attached

May be missing one or two, but that's all I could dig up.

For the last one, there's no way to detect whether it'd be Totem-Sized after importing so... just default to Base/Alola Form.

**Comment by kwsch** [comment]
Max species:
https://github.com/kwsch/PKHeX/blob/61c0bf5271e04f519611839be1117db7de4221cd/PKHeX.Core/PKM/ShowdownSet.cs#L23

Form i/o:
https://github.com/kwsch/PKHeX/blob/61c0bf5271e04f519611839be1117db7de4221cd/PKHeX.Core/PKM/ShowdownSet.cs#L354-L414

**Comment by Marty-D** [comment]
Re: Totem Pokemon, they aren't currently implemented on PS but when they are they'll be named with ``-Totem`` tacked on the end. So for example, Raticate-Alola-Totem or Gumshoos-Totem.
