### ISSUE TITLE
[Future Request - USUM] Change Rotom's nickname for the player

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#1632]
Among the small dialogues that Rotom has occasionally there is one where Rotom asks the player if he can start calling them by a nickname, for example, for me being called Favna the Rotom now calls me Roto-F. 

It would be really fun and nice if we could directly adjust this nickname to anything we want, within limitations of the character length and such, through pkhex.

**Comment by ReignOfComputer** [comment]
Oh, so that's why the OT was stored twice. This feature actually does exist in the latest commit.

https://github.com/kwsch/PKHeX/commit/469587bbbd144b10851422895de68334b41bcd0e

**Comment by Favna** [comment]
well if it helps here is my save file in which Rotom calls me Roto-F 
[main.zip](https://github.com/kwsch/PKHeX/files/1485443/main.zip)

**Comment by SubstituteCS** [comment]
@Favna Reign says the ability to edit it already exists in the latest source of pkhex.  If you can't compile it, I can and send it to you.

**Comment by Favna** [comment]
Morning misinterpretations. I am able to compile it myself, but thanks for the offer. 

On mobile rn so can't close issue but I guess it's resolved then.
