### ISSUE TITLE
No Move Legality Check for Poipole or Evo/Other Issues

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1633]
Hello. So I am using the latest build of PKHeX but when I try to make Poipole or Naganadel it's moves are always flagged invalid reguardless of if the moves where to normally be legal. I have added the file as an example. (I got it from https://github.com/ReignOfComputer/RoCs-PC/tree/master/25%20-%20Gen%20VII%20-%20USUM%20Collection )

[803 - Poipole - 5362439565AD.zip](https://github.com/kwsch/PKHeX/files/1485949/803.-.Poipole.-.5362439565AD.zip)

**Comment by kwsch** [comment]
Works fine on the current commit... ?

**Comment by DJPanda065** [comment]
![illegal](https://user-images.githubusercontent.com/29782059/32995315-27367520-cd38-11e7-9b56-778b19cfee44.png)


Yeah I was using the latest commit, something just updated on girhub it seems.

**Comment by DJPanda065** [comment]
Yep used the latest commit still doesn't fix.

**Comment by kwsch** [comment]
The arceus is a known issue with the official legality checker (another Rayquaza is incorrectly blocked).

**Comment by kwsch** [comment]
Closed via https://github.com/kwsch/PKHeX/commit/6d3ee54d44ddc6313efd25848805dc41d3cfbc6f
Thanks for reporting :)
