### ISSUE TITLE
FestivalPlaza Editor — Facilities Problems

### ISSUE THREAD

**Issue by Aochie** [kwsch/PKHeX#1636]
I'm currently using the latest commit of PKHex.
Whenever I try to modify the NPC of the Festival Plaza, it doesn't change when I click "Save".
Also, when I change the "color" of the facility, it sometimes changes the type to "Lottery BigDream".

**Comment by kwsch** [comment]
Thanks, closed by: https://github.com/kwsch/PKHeX/commit/6534ef19190b97ea9edf6e335f49f4e5da1c81ec

**Comment by Aochie** [comment]
On the latest commit, modifying the NPC of the Festival Plaza is not changing again.
