### ISSUE TITLE
Getting rid of the game sync ID on my savefile

### ISSUE THREAD

**Issue by Cyrean** [kwsch/PKHeX#1638]
Hi. So how can I get rid of my game sync ID on my US safe file? I want to do trainer edits without the risk of getting banned from PGL.

I hope I'm not breaking any rules by asking questions here.

Regards. :)

**Comment by kwsch** [comment]
Set it to 0.

**Comment by Cyrean** [comment]
Sorry for re-opening but where exactly? And do I need to put 16 0's or just one?

And then it'll act as if I had never synced that savefile and spit out a new Game Sync ID at Festival Plaza?

**Comment by kwsch** [comment]
SAV tab on the right side of the main window.
Should allow you to re-sync and get a new one.

Such save editing questions are unrelated to PKHeX issues and are more suitable for a forum thread ;)

**Comment by Cyrean** [comment]
I think I found what you meant, but that somehow doesn't remove the game sync id, but replaces it with a mess ID, which mainly consists of "W''s

Isn't there a flag somewhere which tells the game that it already created a Sync ID?

**Comment by kwsch** [comment]
Game Sync textbox is here: http://i.imgur.com/QnP22Fb.png
Not in the Festival Plaza editor

the game checks for game sync ID being set by checking the value == 0; no game sync ID means the GameSync ID is 0.

**Comment by Cyrean** [comment]
Yea, I did everything as you said and changed the Game Sync ID in PKHeX to "0000000000000000" exported the main file and imported it back into Ultra Sun. However, when I check at the Festival Plaza (with the edited sav) it says my GSI would be something like "????-WWWW-WWWW-WWWW" idk about the first 4 letters.

I know this thread started with a question that does not belong here and I'm sorry for that. But that right now seems like an issue to me. :/
