### ISSUE TITLE
Permissions revoked to guest users to download latest commits on TeamCity?

### ISSUE THREAD

**Issue by exegg** [kwsch/PKHeX#1640]
Hi. I tried to get the lastest build on TeamCity right now and was met with this message after I logged as a guest. I could download previous builds this way with no problems.

![portapapeles-1](https://user-images.githubusercontent.com/19347211/33047458-2f38097e-ce2c-11e7-9097-239dba6efed6.png)

**Comment by kwsch** [comment]
It's intended for now; https://github.com/kwsch/PKHeX/issues/1629

The teamcity builds aren't meant for general consumption and we'd prefer people use the stable releases until the commit rate dies back down.
