### ISSUE TITLE
GTS traded Pokemon without "Latest Handler"

### ISSUE THREAD

**Issue by alexj9626** [kwsch/PKHeX#1641]
So i just traded Lugia and Stakataka from the GTS and when i opened my save file, both are "ilegal" and it says: Invalid: Untraded: Current handler should not be the Handling Trainer.

The "Latest (Not OT) Handler" section is empty and colored green. Those 2 mons where traded via GTS, but the old OTs are not showing, causing PkHex to think they are illegal, cause they dont have my OT and are not traded.

**Comment by kwsch** [comment]
Upload the unaltered pkm files.

PKM that have a handling trainer flag set need a handling trainer string, which should not be empty.

**Comment by alexj9626** [comment]
So as soon as i made the pk7 file and opened it, the Latest Handler auto filled with PKHex. Gonna add my save file too, so you can  check it (In that one i got Lugia, Staka is on another one. If you need it, let me know)

[saves.zip](https://github.com/kwsch/PKHeX/files/1489686/saves.zip)

**Comment by kwsch** [comment]
Not able to replicate this; provided save file has invalid checksums so I'll wait for more evidence to accumulate (if any).
