### ISSUE TITLE
necrozma fused tab

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1647]
Hey I wasn't sure if you were already in the works with this or if this isn't how the necrozma fusion works but I was wondering if you were going to be adding the fused tab for necrozma the same way you have for kyurem. Thanks

**Comment by kwsch** [comment]
currently only fused[0] is shown (kyurem); showing more than what is currently shown would require some rework to the UI which I'm not sure on how it should be done.

code currently exists to retrieve the offset to read from, just no UI yet
https://github.com/kwsch/PKHeX/blob/5fd1e85ce603a486da0d231bdc935daa665c4183/PKHeX.Core/Saves/SAV7.cs#L1319-L1324

closing for now, it is on the look-ahead.
