### ISSUE TITLE
[error] 5th Anniversary Eggs Origin Game

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1650]
The origin game for these events does not detect Sapphire as a legal origin game. Currently only events obtained from Ruby register as legal even though these events can be obtained in either Ruby or Sapphire.
Thanks for taking the time to read this, and for all your work with PKHeX.

https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_event_Pok%C3%A9mon_distributions_in_Generation_III#Pok.C3.A9mon_Center_5th_Anniversary_Eggs

**Comment by kwsch** [comment]
Gen3 eggs were distributed with a set version ID; the game does not update the value when hatched.
Thus, only Ruby is possible.

**Comment by greenDarkness** [comment]
My apologies. Thank you for the information.
