### ISSUE TITLE
gen 2 conversion question

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1651]
Hey I just wanted to know if with the release of poketransporter for gen 2. Is there any differences to worry about with your theoretical conversion from a few months ago or is everything identical to how they ended up making the conversion process. I saw that the met location has changed but is that it? Thanks

**Comment by kwsch** [comment]
haven't had the opportunity to verify korean g2->g7 string conversion
conversion besides is identical
