### ISSUE TITLE
Ash Greninja Event No Legality

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1656]
Hey so on the latest PKHeX build, from the mgdb I keep getting illegal flags for Ash Greninja invalid event. (This is for all the Ash Greninja events.) Also the Ash Greninja won't go through Link Trade. (Says there is something wrong with the mon.) I have the latest mystery gift database.

![invalid ash greninja](https://user-images.githubusercontent.com/29782059/33218412-64a1c1e4-d102-11e7-957b-3cb532d89edf.png)
[658-01 - Greninja - AF3700000021.zip](https://github.com/kwsch/PKHeX/files/1502163/658-01.-.Greninja.-.AF3700000021.zip)

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/33218470-e9a8acc4-d0f1-11e7-9dbd-15d6c18e433f.png)
