### ISSUE TITLE
Mind Blown in SM

### ISSUE THREAD

**Issue by Ntonio36** [kwsch/PKHeX#1658]
![cabwtf-kaboum](https://user-images.githubusercontent.com/32229257/33221932-0c77f538-d15c-11e7-9ea4-faca35daac5f.PNG)
Tried to equip Mind Blown to my Blaziken. Mission half-successful 😆

**Comment by kwsch** [comment]
Thanks for the SM move report

As for the met level solgaleo, the program suggests the lowest level encounter first (the gift) rather than the level 65 encounter.
