### ISSUE TITLE
gen III shows pokedex incorrectly

### ISSUE THREAD

**Issue by bert-w** [kwsch/PKHeX#1660]
Hello, the latest build `20171125` seems to show incorrect pokedex checkboxes. Many Pokemon that have been catched do not have their checkboxes checked.

I've tested the previous build `20171017` and here it seems to work correctly. Tested using FireRed (FRLG) savegame.

**Comment by kwsch** [comment]
Likely this commit:
https://github.com/kwsch/PKHeX/commit/228b0e84fb4a4b9532fee4f92396747ceb82fe2e#diff-153b8212184aa6f9ffe833b81b1431c9

**Comment by bert-w** [comment]
thanks, will test again when its released
