### ISSUE TITLE
HaX mode no longer works....

### ISSUE THREAD

**Issue by ApacheThunder** [kwsch/PKHeX#1661]
I've looked through the code and the checks for this appears to still be present. However the original method of activating illegal mode no longer works. I don't know when this happened. But it seems sometime before the US/UM update? On older build from middle of the year but still after the C#7 refractor had it still working. But sometime after that it doesn't work anymore. (no longer see the prompt for it being activated and UI doesn't change)

It's not in the change log from what I can tell so it's not intended?

I'll go ahead and open an issue for this unless someone notifies me that it's removal was intentional or that if the activation method changed....

**Comment by ReignOfComputer** [comment]
PKHaX is now activated with the argument hax, as in "PKHeX.exe hax".

Perhaps some official documentation should be made, this is quite a common question.

**Comment by sora10pls** [comment]
https://projectpokemon.org/home/forums/topic/41057-illegal-mode-not-working/?tab=comments#comment-216467

**Comment by ApacheThunder** [comment]
Oh so it's a command line switch now? (And this does seem to be a much better way of doing it instead of renaming the exe file name. :P )
