### ISSUE TITLE
Swarm Beldum flagged as invalid 

### ISSUE THREAD

**Issue by CyraFen** [kwsch/PKHeX#1665]
https://bulbapedia.bulbagarden.net/wiki/Sinnoh_Route_228
![image](https://user-images.githubusercontent.com/25874350/33292277-aa15fc7c-d396-11e7-84c3-2b03187390c1.png)

**Comment by kwsch** [comment]
Right, current bleeding edge builds have RNG Frame filtering enabled. Certain types of encounters may not be recognized correctly; it's still a work in progress.

**Comment by CyraFen** [comment]
ok, sorry for bothering you.

**Comment by kwsch** [comment]
No worries :)
