### ISSUE TITLE
Totem-Marowak ORAS Legality Bug

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1667]
Hey so I tried genning this.

Marowak-Alola-Totem (F) @ Life Orb
EVs: 252 HP / 252 Atk / 4 Def
Ability: Rock Head
Level: 100
Adamant Nature
- Bonemerang
- Flare Blitz
- Shadow Bone
- Pain Split

And I came across PKHeX saying it's totem form is possible from ORAS games. Included sample file. If you could supply me with a file of the real one (since RoC's doesn't contain one,) that would be great.
[105-02 - Marowak - A36BF82DC6F6.zip](https://github.com/kwsch/PKHeX/files/1508166/105-02.-.Marowak.-.A36BF82DC6F6.zip)

**Comment by ReignOfComputer** [comment]
In the meantime, you can untick the egg box, remove the relearn moves, change the origin to Ultra Sun and just click the label to auto suggest the locations (Heahea Beach, Lv 25).
