### ISSUE TITLE
Scatterbug / Spewpa / Vivillon Forms via Island Scan are Flagged

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1668]
Setting it at first form (Icy Snow) clears the check. Any other form gets flagged.

https://github.com/ReignOfComputer/RoCs-PC/blob/master/25%20-%20Gen%20VII%20-%20USUM%20Collection/664-07%20-%20Scatterbug%20-%206703815D4F75.pk7
https://github.com/ReignOfComputer/RoCs-PC/blob/master/25%20-%20Gen%20VII%20-%20USUM%20Collection/665-07%20-%20Spewpa%20-%2067E1815D4F75.pk7
https://github.com/ReignOfComputer/RoCs-PC/blob/master/25%20-%20Gen%20VII%20-%20USUM%20Collection/666-07%20-%20Vivillon%20-%206560815D4F75.pk7

**Comment by sora10pls** [comment]
Any chance that this is related?
https://github.com/kwsch/PKHeX/commit/f5a6f2316151abce41d1d21b6300a965e2f57b8d#diff-a4f92a2194ea76c5e4e2c9984406f39dL318

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/1e0bf7b6ea07e676aa3fe3145c2dd653da61e4db/PKHeX.Core/Legality/Encounters/Data/Encounters7.cs#L237

encounter is here ^, no form specified (default form is 0). Needs to have SkipFormCheck set for the form to not be checked during the generation phase.

https://github.com/kwsch/PKHeX/blob/1e0bf7b6ea07e676aa3fe3145c2dd653da61e4db/PKHeX.Core/Legality/Encounters/EncounterGenerator.cs#L469
