### ISSUE TITLE
[Bug] Foppa Internal Error

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1672]
Doesn't matter whether it's Magikarp or Gyarados, the bug still happens. Have also double-checked Foppa from RoC's PC, same error.
![image](https://user-images.githubusercontent.com/17801814/33447587-c67bdcaa-d5d1-11e7-84ed-9c9591436041.png)

**Comment by kwsch** [comment]
Usually due to an exception thrown in the internal check; can clear the [`#define SUPPRESS`](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Analysis.cs#L1) in the Analysis.cs class to not swallow the exception.

**Comment by sora10pls** [comment]
https://pastebin.com/EJSAfhGz

**Comment by kwsch** [comment]
I already suspected it was in that method, just need to know which line

https://github.com/kwsch/PKHeX/blob/9930e8765aa5257c88b67e98c750c7d351f0691a/PKHeX.Core/Legality/Checks.cs#L372-L394

I can test this later myself ;)
