### ISSUE TITLE
[Bug] Transferring a PK3/4 up to SAV5-7 falsely flags it as illegal

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1676]
My best guess is because the Met Level is changed to Transferred Level.

Provided is a Roserade I caught as a Budew in Diamond. If transferred up, PKHeX will say it can't match encounter conditions to a possible RNG frame.

If the Current Level and Met Level are both changed to 20, for example, it will then be deemed legal. Note that this only seems to work in Gen 7 because PK7s no longer keep store the Encounter Type.

![image](https://user-images.githubusercontent.com/17801814/33499901-dff2a050-d6a4-11e7-8d86-21b20ee9d2b0.png)
[407 - ROSIE - BFB39C81D000.zip](https://github.com/kwsch/PKHeX/files/1522790/407.-.ROSIE.-.BFB39C81D000.zip)

**Comment by sora10pls** [comment]
Can confirm it also affects PK3s.

**Comment by kwsch** [comment]
comparison is incorrect
https://github.com/kwsch/PKHeX/blob/4b954cd1028fdc473fdfe467cba40a24ed388ed0/PKHeX.Core/Legality/RNG/Frame/Frame.cs#L44-L48
