### ISSUE TITLE
Umm I wanted to see the codes but the source code is giving me 2 errors while opening MainWindow

### ISSUE THREAD

**Issue by PreciousTrainer** [kwsch/PKHeX#1679]
I just wanted to see codes but it's giving this error when I opened the designer .
Here are some pictures:
![s](https://user-images.githubusercontent.com/20636894/33515528-3690d37e-d78f-11e7-8831-f10ac58db8bb.png)
![scshot](https://user-images.githubusercontent.com/20636894/33515586-9b17e9ae-d78f-11e7-9494-35a60340e190.png)

**Comment by kwsch** [comment]
Rebuild the entire solution first
