### ISSUE TITLE
USUM Ball throw type not saving.

### ISSUE THREAD

**Issue by Genesis-Nova** [kwsch/PKHeX#1695]
I don't know if this is a known issue or not, but when attempting to change your ball throw type in the trainer data editor it never takes effect after clicking save, and since its not giving an error like the fashion items (before the fix) I thought maybe it was a error.

**Comment by sora10pls** [comment]
I believe this was an intentional change until the flags were documented ([which they now are](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Resources/text/script/flags_usum_en.txt#L58-L65)).
