### ISSUE TITLE
Add multilanguage text for some parts

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#170]
There are some parts like items for gen3, rle places and some texts in medals supertraining that I can not translate into spanish.

**Comment by ajtudela** [comment]
The items in gen can not be trnaslated

**Comment by kwsch** [comment]
Right, as of now there's only an English list of gen3 items and locations:
`\PKHeX\Resources\text\gen3`

These gen3 strings are hard-coded to be english right now:
`g3items = Util.getStringList("ItemsG3", "en");`
`metRSEFRLG_00000 = Util.getStringList("rsefrlg_00000", "en");`

The program can be made to support multiple languages (by first checking if the string list requested is valid), but those text files have not been created/contributed.

**Comment by ajtudela** [comment]
So, I only have to create "text_ItemsG3_es.txt" and "text_rsefrlg_00000_es.txt" in gen3 folder?

**Comment by kwsch** [comment]
Yeah, it still needs to be 'hooked up' in the program code before it'll appear.
