### ISSUE TITLE
PKHeX does read certain Showdown import formats.

### ISSUE THREAD

**Issue by mmands994** [kwsch/PKHeX#1715]
It's a little weird, but there are times where PKHeX will not read showdown formats that were correctly made. Try to see if you can import this one yourself and see if it reads it.

Venusaur (F) (Serena) @ PP Max
Ability: Chlorophyll
Level: 100
Shiny: Yes
EVs: 248 HP / 0 Atk / 88 Def / 0 SpA / 156 SpD / 16 Spe
Calm Nature
IVs: 31 HP / 30 Atk / 31 Def / 30 SpA / 31 SpD / 30 Spe
-\ Leech Seed
-\Sludge Bomb
-\Hidden Power
-\ Synthesis

(remove the \ )

**Comment by kwsch** [comment]
Manual set != showdown format.

```
Serena (Venusaur) (F) @ PP Max  
Ability: Chlorophyll  
Shiny: Yes  
EVs: 248 HP / 88 Def / 156 SpD / 16 Spe  
Calm Nature  
IVs: 30 Atk / 30 SpA / 30 Spe  
- Leech Seed  
- Sludge Bomb  
- Hidden Power  
- Synthesis
```
