### ISSUE TITLE
Exporting Issue in PkHeX.

### ISSUE THREAD

**Issue by Cubbyholes** [kwsch/PKHeX#1718]
Recently, I've come across a problem using this program. When I tried exporting a fresh Ultra Moon save from PkHeX after injecting items (medicine and held items and berries, no z crystals or key items), upon importing the save with JKSM and running it, I got a corrupt file message. I tried the same process again, only to receive the same message. I tried an additional few times without editing the save; only exporting it from PkHeX, only to receive the same message of game data being corrupted. I've done other tests with JKSM alone and scanning my SD card for errors, only to find that they were functioning the way they should. I have not tried the exporting process on any save files that aren't brand new, because of having concerns of losing game data and collected wondercards. This has just started happening today (even before I updated to the most recent version). Any help would be appreciated.

**Comment by goodranite47** [comment]
Use [Checkpoint](https://github.com/BernardoGiordano/Checkpoint/releases). This is an issue with JKSM, not PKHeX
