### ISSUE TITLE
Legality Issues

### ISSUE THREAD

**Issue by goodranite47** [kwsch/PKHeX#1719]
PKHeX detects the Dusk Lycanroc (evolved from event Own Tempo Rockruff) as illegal. "Unable to match to a mystery gift in the database."

[745-02 - Lycaon - A4D42D040254.zip](https://github.com/kwsch/PKHeX/files/1578211/745-02.-.Lycaon.-.A4D42D040254.zip)

**Comment by sora10pls** [comment]
Works fine with latest commit.
![image](https://user-images.githubusercontent.com/17801814/34261217-776c0b6a-e636-11e7-9cb5-51495766e9cc.png)
