### ISSUE TITLE
[Feature Request] Export sav to vc format

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#1721]
is it possible to get PKHeX to handle converting VC > emulator and vice versa? it handles editing the sav.dat files exported from backup managers, but without HxD I haven't found a way to export an emulator/cartridge backup .sav to the .dat with the same filesize required by the VC to play.

If you start a game on emulator or original cartridge, and export that backup after editing it with PKHeX then proceed to transfer and restore it to the VC copy, the file becomes corrupt because the file size/format differ, as per mentioned before this mostly affects Gen2, (and possibly 3 haven't' tested it since there's no official gen3 VC release [yet]). But with HxD I would either have to delete , or add lines to the sav for it to work on the VC (which ends up corrupting the games internal clock [that the game lets you fix luckily])

At first I thought it was the sav manager issue, and opened the issue here https://github.com/BernardoGiordano/Checkpoint/issues/42 but was told it was the emulator issue [but I'm trying to assume that it would be possible for PKHeX to handel the the exporting to the proper format]

**Comment by kwsch** [comment]
that's something a separate tool can handle

**Comment by Ninjistix** [comment]
Does it exist or you mean something that can be done separately ?

**Comment by kwsch** [comment]
won't be done by pkhex, a separate tool can accomplish the same adding/removing bytes.

**Comment by Ninjistix** [comment]
Understandable thanks
