### ISSUE TITLE
Eevee and Evolutions Pokeball Legality

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1722]
Hey so I was working on the set below. I had been requested to give it a Moon ball, so I did. But it wasn't legal. So then I tried a Dusk Ball, still not legal. Then I tried Great and Ultra, still illegal. I know this is a little thing but based on https://www.serebii.net/games/geniball.shtml it should be legal. (This was in an Ultra Sun save.)

Umbreon (M) @ Leftovers
IVs: 0 Atk
EVs: 252 HP / 252 Def / 4 SpD
Ability: Synchronize
Level: 100
Bold Nature
- Heal Bell
- Moonlight
- Snarl
- Toxic

[197 - Umbreon - 8026135B99BB.zip](https://github.com/kwsch/PKHeX/files/1581151/197.-.Umbreon.-.8026135B99BB.zip)

**Comment by DeathAngel74** [comment]
It's working fine here. 
![2](https://user-images.githubusercontent.com/29271009/34281350-06ede740-e673-11e7-8334-9d6ee3aeb57d.PNG)
![capture](https://user-images.githubusercontent.com/29271009/34281357-0ae3cf40-e673-11e7-8824-6680b43a1748.PNG)

**Comment by DJPanda065** [comment]
@DeathAngel74 when u have as egg checked your met level is 11 not 1. Also needs egg moves if its bred

**Comment by DeathAngel74** [comment]
i know that, lol

[197 ★ - Umbreon_US - 7BA4584B4FED.zip](https://github.com/kwsch/PKHeX/files/1581239/197.-.Umbreon_US.-.7BA4584B4FED.zip)

**Comment by CyraFen** [comment]
@DJPanda065 you didn't add egg moves to yours, that's why.

**Comment by DeathAngel74** [comment]
I did, sorry, forgot to add in older SS. Was trying to help with Moon Ball issue.

**Comment by DJPanda065** [comment]
Ah alright figured it out thanks to CyranFen and DeathAngel74 my apologies.
