### ISSUE TITLE
Weird event flag "issue" with Solgaleo/Luna

### ISSUE THREAD

**Issue by DeathAngel74** [kwsch/PKHeX#1723]
Hi Kurt,
Ummm crazy question. If I'm still on the first island at Hau'oli Outskirts, can I uncheck this and still be ok? I don't want to break the storyline....

![capture](https://user-images.githubusercontent.com/29271009/34315682-3fc567da-e738-11e7-98f4-410c72334144.PNG)

I've only injected them to fuse with Necrozma, not officially caught yet. Happy Holidays! TIA

**Comment by sora10pls** [comment]
Setting Pokémon to slots has nothing to do with event flags. Opening the editor also doesn’t (un)set any flags without the user doing so.

Not a bug.

https://projectpokemon.org/home/forums/topic/42778-event-flag-already-activated/?tab=comments#comment-224084

**Comment by DeathAngel74** [comment]
Thank you and Merry Christmas! Please close.
