### ISSUE TITLE
QR Cycling Through Mons (Idea)

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1725]
This is something I was thinking of. When you open QR on a mon in PKHeX there should be a button you can press, that can make you go left or right to the next mon. In place of having to exist the QR scan and select a new mon and then open the QR thing.  To navigate left or right, you can use Shift + 4 (on the side number-pad) for left and Shift + 6 (on the side number-pad) for right.

**Comment by kwsch** [comment]
QRs are generated from the currently loaded PKM (left side of the window).

Control click the slot you want to export, then shift click the preview sprite to pop up the QR image. It's much more flexible.

If you're really trying to mass inject you should just use NTR or save editing.
