### ISSUE TITLE
GetSuggestedMetInfo / GetLowestLevel Issue on <Gen7 Mons.

### ISSUE THREAD

**Issue by Mitsukiii** [kwsch/PKHeX#1728]
This is only a small issue.

If u change the Level from a Pokemon that born on past Gens(<Gen7) the minimum level will always +1 as the current Level if its legal.

```
var encounter = legality.GetSuggestedMetInfo();
int minimumLvl = Legal.GetLowestLevel(PK7, encounter.LevelMin);

if (PK7.CurrentLevel < minimumLvl || PK7.CurrentLevel > PK7.Met_Level)
{
PK7.CurrentLevel = minimumLvl;
}

for ex. PK7.CurrentLevel is 30, minimumLvl will be 31.
```

**Comment by kwsch** [comment]
needs a pkm provided for the test case

relevant code

https://github.com/kwsch/PKHeX/commit/072f1ba83d965310b43ad916b3760e376f67f3f0#diff-738bfbce46a725950abacf2b6555ec93R1193

**Comment by Mitsukiii** [comment]
should trigger with any pokemon below gen 7, but here a example:

[657 ★ - Frogadier - E3001EDADB4C.zip](https://github.com/kwsch/PKHeX/files/1591706/657.-.Frogadier.-.E3001EDADB4C.zip)

**Comment by kwsch** [comment]
Not able to replicate for that one:
![image](https://user-images.githubusercontent.com/6393368/34418667-1e6005ca-ebb4-11e7-9b0f-62e5abf804f2.png)

**Comment by Mitsukiii** [comment]
hmm, Strange, gonna check it.
