### ISSUE TITLE
Help with monodevelop required.

### ISSUE THREAD

**Issue by spixi** [kwsch/PKHeX#1729]
Hi there. I am unable to compile the project with monodevelop 6.0.0.4761.

I always get "object reference not set to an instance of object" when trying to open the project PKHeX.Core. The project PKHeX.WinForms loads fine, however.

**Comment by kwsch** [comment]
need elaboration; where is this error being shown / what line / etc.

**Comment by spixi** [comment]
There is no line, unfortunately. The project folder just won’t open at all 😞

**Comment by spixi** [comment]
![screenshot at 2017-12-28 21 55 12](https://user-images.githubusercontent.com/3192596/34423059-e938a81e-ec19-11e7-822b-ff90fc6efd1b.png)

**Comment by kwsch** [comment]
possible related issue:
https://github.com/kwsch/PKHeX/issues/1688

have you tried building any of the mono builds?

**Comment by spixi** [comment]
Thank you. Which builds do you mean?

**Comment by kwsch** [comment]
There's 5+ configurations for building; ClickOnce, debug, debug-mono, release, release-mono

**Comment by spixi** [comment]
I’ll try it, but I see that I have to switch to a newer version of mono first, because you are using C# 7 syntax in many places.

**Comment by spixi** [comment]
Building of the debug-mono configuration is not possible, because of missing dependencies.

/mnt/hdd/home/mari/PKHeX/PKHeX.WinForms/Controls/PKM Editor/ContestStat.cs(13,13): Error CS0234: The type or namespace name 'Core' does not exist in the namespace 'PKHeX' (are you missing an assembly reference?) (CS0234) (PKHeX.WinForms)

**Comment by kwsch** [comment]
Try building the PKHeX.Core project first, then the sln.
PKHeX.WinForms uses PKHeX.Core project logic, so maybe the environment doesn't have the dll symbols necessary to allow PKHeX.WinForms to begin compiling...
