### ISSUE TITLE
Day care

### ISSUE THREAD

**Issue by Glitching-Queen** [kwsch/PKHeX#1730]
![15144908081171073410401](https://user-images.githubusercontent.com/34920501/34421713-21770aaa-ebce-11e7-8e12-40e3a92ac5b2.jpg)
are these offsets correct? For the location of if the daycare has an egg ready to be picked up for UsUm?

**Comment by kwsch** [comment]
Closed, not related to PKHeX.

**Comment by Glitching-Queen** [comment]
I know it isnt but i needed help and so many people said to ask you for the help because you will know how best to answer and i can never get ahold of you on twitter. And Michael doesnt ever answer tweets either.
