### ISSUE TITLE
pl6 issue in the  Events Gallery - 2017-11-29 Release for celebi

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#1734]
it is not reading on the PKHeX 
![pl6 to pk6](https://user-images.githubusercontent.com/18640392/34469279-d5c015c4-ef34-11e7-98de-6c09a1f35ab0.jpg)
 and this the message 
![pl6 eror message](https://user-images.githubusercontent.com/18640392/34469284-229f7a42-ef35-11e7-9f7d-2a4a27bf7ca5.jpg)

**Comment by sora10pls** [comment]
![image](https://user-images.githubusercontent.com/17801814/34469698-cd2b67ca-eef2-11e7-864c-b350d151d17c.png)
![image](https://user-images.githubusercontent.com/17801814/34469701-d670eaa8-eef2-11e7-8070-4002b43df8bc.png)
