### ISSUE TITLE
issue with box data report

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1736]
Hi. I just wanted to let you know that I found an issue with the box data report feature in pkhex. For my fire red game, the tid is 09777. in the box data viewer it only shows up as 9777. I dont know if this is for any other games but it is a glitch, as every other game seems to have the right tid. Thanks

**Comment by NinFanBoyFTW** [comment]
Edit: I also noticed that the same issue is happening with my pokemon ruby save. I believe that it is because on both of these saves, the tid starts with a 0.

**Comment by kwsch** [comment]
leading zeroes have no impact, the value is still the same.

**Comment by NinFanBoyFTW** [comment]
I understand that the value is the same but it isnt the same tid to any person just looking at it in the viewer
![untitled-1](https://user-images.githubusercontent.com/21354941/34487543-c112ec96-efa2-11e7-86ed-0df026ff4238.png)
![untitled-2](https://user-images.githubusercontent.com/21354941/34487547-c320e9f2-efa2-11e7-818e-c0e1265888ff.png)
