### ISSUE TITLE
[Minor] The link in "About" doesn't exist.

### ISSUE THREAD

**Issue by fr3quency** [kwsch/PKHeX#1737]
The link in "About is " http://projectpokemon.org/pkhex " which leads to a page that says "The page you requested does not exist".

I believe the link should be updated to either https://projectpokemon.org/site/tools/pkhex/ or https://projectpokemon.org/home/files/file/1-pkhex/

**Comment by sora10pls** [comment]
or just add a forward slash at the end of the URL

**Comment by ricksee** [comment]
and/or add a link to the github.

**Comment by sora10pls** [comment]
GitHub doesn’t have releases and most users don’t even know how to compile source code

**Comment by ricksee** [comment]
Fair enough. How about making the links clickable. The changelog doesn't seem to be able to.

**Comment by ricksee** [comment]
Just a quick thought why aren't there releases on Github anyway?

**Comment by ricksee** [comment]
@kwsch Sorry I didn't mean to. I was just curious.
