### ISSUE TITLE
Dates Legal for All Years Despite Being Introduced In Later Generations

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1739]
For Instance, Pokemon introduced in Gen 7 can still be legal before 2016. Pokemon with a .pk3 format introduced in gen 3 can still be declared before 2002. Gen 6 before 2013 and so on.

**Comment by sora10pls** [comment]
\>met dates get altered during transfer
\>NDS and 3DS have adjustable Date/Time

This has never been checked for in terms of legality and it likely never will be.

**Comment by ricksee** [comment]
@sora10pls The met date can be altered to a date before the transfer.
Still kind of unusual to have a Bewear with the met date from an egg from the year 2000. Unless it was an event.

**Comment by ricksee** [comment]
Oh okay then, if they don't care then this issue should be closed.
