### ISSUE TITLE
Importing Vivillon Showdown set changes wing pattern

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#174]
Tested with Poke Ball form. I copied the set, imported it, and it was changed to Icy Snow after importing

![screenshot_1](https://cloud.githubusercontent.com/assets/17801814/17571816/b9346a3c-5f1f-11e6-8a9e-8a5c6d28eaea.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17801814/17571815/b932aa1c-5f1f-11e6-9f18-33ca156a92da.png)

**Comment by Tsunamical** [comment]
Maybe this is why the Vivillon form editor was disabled?

**Comment by evandixon** [comment]
I was going to look into this, but I don't have a Vivillon handy.  If no one else has one, maybe someone can upload or link to one?

Uploading it here would be a good choice (definitely not biased, as the developer :P ).  While it currently doesn't distinguish between forms, the PK6 data will remain unaltered, and would likely take less time to upload than most other generic file sharing sites.
http://pkmdb.skyeditor.org/

**Comment by sora10pls** [comment]
Just now uploaded the .pk6 of the Vivillon there, if it helps.

**Comment by evandixon** [comment]
Found the problem:
https://github.com/kwsch/PKHeX/blob/master/PKHeX/PKM/ShowdownSet.cs#L99

The form is [looking for the form](https://github.com/kwsch/PKHeX/blob/master/PKHeX/MainWindow/Main.cs#L415) "PokéBall" in a list that contains "Poké Ball".  Removing the line linked to above should fix the issue, but might cause other side effects depending on why that line is there in the first place.
