### ISSUE TITLE
[Gen. III] Marking a Pokémon as egg always gives it the Japanese egg nickname

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#1747]
Self-explanatory. Even if the Pokémon's language isn't Japanese, checking the Is Egg checkbox always gives it the タマゴ nickname.

**Comment by Ammako** [comment]
Also in the same vein: PKHeX allows selecting Korean language for Gen. III Pokémon in Gen. III saves, before complaining that language ID should be <=7

**Comment by sora10pls** [comment]
Egg nickname isn’t a bug, that’s how the game names the Egg by default. Can test with any Egg received in RSE/FRLG.

**Comment by Ammako** [comment]
In that case, PKHeX should probably be updated to change what it displays, still. It's a bit misleading. :p

**Comment by Ammako** [comment]
Looks like, when an egg is generated in-game (or at least this is the case in R/S), the egg language is set to Japanese with タマゴ nickname, and then the Pokémon's language changes to the game's actual language upon hatching.

This could be worth adding a check for in the legality checker, since it marks non-Japanese language eggs as legal. Would prevent other people from getting thrown off by it too :p

**Comment by kwsch** [comment]
Should be noted that PKHeX doesn't care what you put for the language of the gen3 egg; it'll automatically change it to Japanese when you save it back from tabs (which is what the legality check does).
