### ISSUE TITLE
[Feature Request] Pokemon Battle Tower (C,R,S), Battle Subway, PWT, and White Treehollow/Black Tower

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1748]
Is it possible to add editing data for these?

**Comment by ricksee** [comment]
PWT Tournament Block:  20500 | 207FB | 207FE | 25F5E | Tournament Block

**Comment by sora10pls** [comment]
Battle Subway block documented
PWT records already added to PKHeX.Core

Probably needs more research before implementing, not just “This would be cool please add it”

**Comment by ricksee** [comment]
@sora10pls Has there been documentation for Black Tower/White Treehollow?

**Comment by sora10pls** [comment]
>Probably needs more research before implementing, not just “This would be cool please add it”

**Comment by ricksee** [comment]
How about the Battle Tower for Crystal, Ruby, and Sapphire?

**Comment by sora10pls** [comment]
My last comment is going to apply to everything you suggest.

**Comment by ricksee** [comment]
So I am assuming it has never been documented because the offsets for them are very difficult to find?

**Comment by ricksee** [comment]
Then I guess we can leave it open until we can get the research for it.

**Comment by kwsch** [comment]
No, needs to be documented completely and not already covered by another program.

Remember, PKHeX does not have to do everything (drafting the UI is very time intensive too).
