### ISSUE TITLE
Mega Import

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1750]
If possible, can you alter PKHeX to not add the Mega form when injecting a Showdown template that has the -Mega attached.

I've been trying to teach people to read by telling them that certain forms (Mega in this case) cannot be requested as those forms are battle only, yet they still request Pokémon generated in that form.

**Comment by architdate** [comment]
I would say that an implementation for this could be as such:
```
// Initial form handling here
if (!HaX) // Illegal Mode is Inactive
{
    pk.AltForm = 0 // Every Mega would have an altform 0 for their non-mega varient 
}
```
For form implementations in WinForms it could use `CB_Form.SelectedIndex = 0`

**Comment by kwsch** [comment]
I'd rather import exactly to the set details rather than have the opposite complaint (can I stop it clearing mega). Any legality implication can be fixed separately.
