### ISSUE TITLE
[Request] Regarding OT data Change

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1751]
Would it be possible to force the removal of memories when altering a pk6 file to match the OT data of a pk7 trainer when you Control+Click the OT?

Also, if possible, maybe set a generic G7 met location of say "Iki Town" or something instead of clearing it completely.

**Comment by sora10pls** [comment]
Is it really worth it to add features just so users can fake data more easily? You can always just open PKHeX and directly create a PK7 with your OT info...

PS: You only need to click the OT label, no need for CTRL-click.

**Comment by kwsch** [comment]
Met location only clears if the version group is different.
You can click the met location label to get suggested fixes and have them applied.
