### ISSUE TITLE
[Bug] Dragging and dropping Ash Greninja WC7 file generates an illegal pkm

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1753]
Self explanatory:
![image](https://user-images.githubusercontent.com/17220860/34724260-216c76e4-f588-11e7-8595-89844470204a.png)

Commit used is almost the latest (a few before the current latest) but I am pretty sure that none of them have modified code that should affect this legality... So it should show up illegal on the latest commit too

**Comment by kwsch** [comment]
Can't be received by ultra sun or ultra moon.

**Comment by subrajit999** [comment]
That ash Greninja wc7 is not visible and when dragged and dropped it is showing error, please suggest some solution and also pk6 pl6 wc7full files are also showing error when dragged and dropped
