### ISSUE TITLE
BatchEditor for WasEgg not updating properly

### ISSUE THREAD

**Issue by sithantic** [kwsch/PKHeX#1754]
Was trying to run the following in the BatchEditor:

.WasEgg = False

Stepping through the code, this did nothing to the PKM, nor did it uncheck the "As Egg" checkbox.

**Comment by kwsch** [comment]
WasEgg is a derived value/non-saved backing field used for legality purposes only:

https://github.com/kwsch/PKHeX/blob/f332e41869021195229de459ef113b2470cbf70c/PKHeX.Core/PKM/PKM.cs#L467-L483

The "As Egg" checkbox acts as an enable-disable for the Egg Location/Date groupbox control. The groupbox is only enabled if the PKM structure has egg data (egg location != 0):

https://github.com/kwsch/PKHeX/blob/9f2899617dd8ffeee6f62b00210c7d6a52ea610c/PKHeX.WinForms/Controls/PKM%20Editor/LoadSave.cs#L304-L318

Working as intended.
