### ISSUE TITLE
[Gen. VII] Strange behavior with 0-quantity items

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#1756]
(Potentially related to [#1670](https://github.com/kwsch/PKHeX/issues/1670)?)

The Inventory Editor behaves very strangely when it comes to displaying 0-quantity items. It often doesn't display everything, for whatever reason.

Had that issue for a while, noticed that Lustrous Orb and Blue Orb never showed up in my bags as quantity of 0 when I'd give them to Palkia and Kyogre, but Adamant Orb, Griseous Orb and Red Orb did.

Looking more into it right now, the same thing is still happening, with Houndoominite & many others not showing up in the list after I've given it to Houndoom.
So out of curiosity, I put my Houndoominite back into my bag to see how PKHeX would react.

[Before taking Houndoominite off](https://puu.sh/yYI7u/ac688717ea.png)
[After putting it back in my bags](https://puu.sh/yYI7C/83b413671c.png)

I have a lot more 0-quantity items than what is actually displayed, but something is causing PKHeX to not properly show everything.

Taking Houndoominite off and putting it back into my bags, also affects the Medicine pouch display on PKHeX. Where it showed Zinc, Sacred Ash and Hyper Potion as quantity of 0 before, it now shows Rare Candy, Sweet Heart, Soda Pop and PP Max (even though Houndoominite doesn't affect item counts in Medicine pocket.)

(I'll upload saves, after I'm done scrubbing them out of anything important that I don't want to be publicly available for download online, or if I can just replicate the issue on a separate throwaway save file. Unless someone else also noticed the issue and already has saves they're willing to upload.)

**Comment by Ammako** [comment]
BTW: looks like it's related to when you give/take items from Pokémon?

I had a save where I had never given any held item to Pokémon the whole game; only sold items that I didn't care about. I had a really long list of 0-quantity items shown in Medicine and Held Items bags.

Just to test, I gave 6 random items to my party members and compared in PKHeX. Over 3/4ths of the 0-quantity items were no longer showing up.

Went back in-game, took the items off my Pokémon, saved, exported save and compared. Now the Held Items bag only shows Heart Scales as 0-quantity, and the Medicine bag shows Potions and Super Potions, with Protein, Iron, Heal Powder and Revival Herb at the bottom of the list.

Went back in-game, gave 6 items to my party again, saved and exported again. PKHeX showed (nearly?) all of the 0-quantity items in Medicine pocket and Held Items pocket, but some key items appear to be missing which were previously showing.

[00001b51.zip](https://github.com/kwsch/PKHeX/files/1621069/00001b51.zip)

main-1 is the save file after taking the items off the party, main-2 is the save file after I gave them back.
I would have the original save file from before I even messed with held items, and the one after I gave held items for the first time, but hindsight is 20/20 and I deleted those thinking that it'd show items the same way if I just went in-game and took the items off my Pokémon, which it of course didn't. But those two save files showcase the problem pretty well on their own, I'd hope.

**Comment by kwsch** [comment]
Are you using the latest commits?

The game keeps 0 count items in the list so that if you ever receive another, it won't show up as NEW.

**Comment by Ammako** [comment]
I am aware that this is what the game uses 0-count items for. What I'm saying is that PKHeX doesn't display them properly (it doesn't display all of them, acts as if they aren't there.)

Not the latest commit, because they are no longer being made available on teamcity and I didn't really feel like messing around with trying to figure out how to get it to compile from source. I'm using the 2017/12/05 release.

**Comment by kwsch** [comment]
Data is being loaded exactly how it is in the save data:
![image](https://user-images.githubusercontent.com/6393368/34808326-0dd8bcd0-f643-11e7-8513-62dacf9dc0d6.png)

Data also saves back to the original data

Not sure how your 1/2 saves are mysteriously switching items; not able to replicate.

**Comment by Ammako** [comment]
All I'm doing is giving held items in-game to my Pokémon and taking them off. No external modifications to save file in doing so, though I guess I have to be using third-party software to extract my save files in the first place. If something's messing with my save data when backing up and/or restoring then I'm not sure what it is.

Whatever it is, though, the game behaves just fine, because even if an item doesn't show as 0 quantity in PKHeX, the game still registers that I already owned the item when I take it off. So I don't think the items are literally missing from the save file; they must be elsewhere, but where, I have no idea.

**Comment by Ammako** [comment]
Crummy example video.

https://www.youtube.com/watch?v=LW6XtPq-Xsg

This is on Citra, but this is exactly what's happening when I do it on real hardware as well.

**Comment by kwsch** [comment]
Could be the game just tidying up and moving item IDs to a bitflag region or something...

Closing since this is not currently related to PKHeX as PKHeX doesn't touch 0 count slots. If anyone can document the behavior completely on the forums then it can be replicated in PKHeX. Until then, the no-modification strategy stays.

**Comment by Ammako** [comment]
Sounds fair, at least it gives me peace of mind that my save file isn't being incorrectly read and no data is being incorrectly set (though I do wonder, if an item is being counted as non-new by the game but not showing up as 0-quantity, if re-adding that same item to the inventory could cause problems.)

It's weird if that's how it works, though. Since if the game can just keep track of items like this without having 0-quantity items in the bags, why would they bother ever having 0-quantity be a thing (and why would they seemingly randomly make them come and go?)

But I guess that's Game Freak we're talking about, lol.
