### ISSUE TITLE
[Legality Error] GS Spinarak

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1757]
Currently Hyper Beam is reading as illegal on Spinarak, although it can learn the move via TM 15.
Thanks for taking the time to read this, and for all your work!
https://www.serebii.net/pokedex-gs/167.shtml
![image](https://user-images.githubusercontent.com/15519892/34860114-37d2ae6a-f729-11e7-9c6b-2e322d0503df.png)

**Comment by kwsch** [comment]
Bulbapedia disagrees, I'd rather side with what PKHeX matches ;)
https://bulbapedia.bulbagarden.net/wiki/Spinarak_(Pokémon)/Generation_II_learnset#By_leveling_up
