### ISSUE TITLE
Festival Coins Spent Capped incorrectly

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1759]
When you modify your festival coins spent in the festival plaza tab, it only lets you cap it at 9,999,999 festival coins. But the true cap in-game and in the trainer data tab is actually 999,999,999. But when my Festival coins spent is 10,000,000+ and I open the festival plaza tab, it would automatically set it back to 9,999,999. So the festival plaza tab has the FC cap too low.

**Comment by kwsch** [comment]
Display cap != software cap

```c
int __fastcall Savedata::JoinFestaDataSave::AddCoin(int a1, int a2)
{
  unsigned int currentCoins; // r12
  signed int finalCoins; // r2
  unsigned int totalCoins; // r3
  int result; // r0

  currentCoins = *(a1 + 0x510) + a2;            // 0x508
  *(a1 + 0x510) = currentCoins;
  finalCoins = 9999999;
  totalCoins = *(a1 + 0x514) + a2;
  if ( currentCoins > 9999999 )
    currentCoins = 9999999;
  *(a1 + 0x514) = totalCoins;                   // 0x510
  if ( totalCoins <= 9999999 )
    finalCoins = totalCoins;
  *(a1 + 0x510) = currentCoins;
  *(a1 + 0x514) = finalCoins;
  result = a1 + 0x500;
  if ( *(result + 66) == 999 )
    *(result + 80) += a2;
  return result;
}
```

The game can't naturally go above 9,999,999.
