### ISSUE TITLE
Pokemon Stadium 1&2 - FLA Save

### ISSUE THREAD

**Issue by Papermanzero** [kwsch/PKHeX#1761]
Mupen64Plus stores the save file as fla.
Therefore the savefile for pokemon stadium 1 and 2 cannot be edited.

**Comment by kwsch** [comment]
Stadium saves are not supported.

**Comment by Papermanzero** [comment]
Can we add support for stadium saves?

**Comment by kwsch** [comment]
I personally have no interest in supporting these games; however, if someone submits a sufficient pull request with the support added -> it'll be merged.
