### ISSUE TITLE
Legal Non Event Ash Hat Pika 

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1762]
Apparently it says it's legal shiny too. Credit's to a fellow genner for finding this. Apparently changing hats/forms doesn't mess with legality.

[025-07_-_Pikachu_-_CBA900000000.zip](https://github.com/kwsch/PKHeX/files/1633138/025-07_-_Pikachu_-_CBA900000000.zip)

**Comment by DeathAngel74** [comment]
Thanks @DJPanda065 , I meant to report this after the holidays.
