### ISSUE TITLE
Legality Issue for in game Caught Pokemon + Memory Issue

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#1763]
[Pokemon Issues.zip](https://github.com/kwsch/PKHeX/files/1640655/Pokemon.Issues.zip)

A Crabrawler and a Grubbin I caught in game in Ultra Sun are being marked as Illegal. Crabrawler seems to not recognize that you can obtain it via the berry tree. Grubbin says ability mismatch for encounter but a previous grubbin I caught doesn't show this despite having the same ability.

Memory issue: I used the batch editor to change some previous generation bred Pokemon into Gen 7 bred pokemon.

I used the following script:

=WasEgg=True
.Version=31
.Met_Location=54
.Ball=4
.Met_Level=1
.Met_Month=1
.Met_Day=17
.Met_Year=18
.Egg_Location=60002
.Egg_Month=1
.Egg_Day=17
.Egg_Year=18

This resulted in a memory error and so I used the following:

.OT_Memory=0
.OT_Intensity=0
.OT_TextVar=0
.HT_Memory=0
.HT_Feeling=0

After this the Pokemon would still be flagged with the following error:

"Invalid: Memory: Not cleared properly."

The only fix for this I've found is to manually go into the memories of the pokemon and reset the memories with OT memory type option to : "The Pokemon seems to have a good memory.." Is there anyway to fix this for batch editor so I don't have to manually change this memory for all Pokemon?

Lastly, could you add the extra bytes to the batch editor? 0x2A seems to be missing and I bet a few more might be as well, I'd like to reset this byte to 0 on all of my pokemon as some of them seem to have a different value and doing it manually wouldn't be efficient.

**Comment by sora10pls** [comment]
Grubbin is being mistaken for the first encounter on Route 1
https://github.com/kwsch/PKHeX/blob/69896a3a04990bf7e12e36681df8687657bd2831/PKHeX.Core/Legality/Encounters/Data/Encounters7.cs#L281

**Comment by kwsch** [comment]
Crabrawler is listed as levels 26-29, not at level 25.
![image](https://user-images.githubusercontent.com/6393368/35123962-2f7ac81c-fc59-11e7-8ca7-ec77739ba00b.png)

As for the memory clearing, there's 4 memory properties for each trainer (OT & HT = 8 total).

0x2A is known as PelagoEventStatus
https://github.com/kwsch/PKHeX/blob/387030e16ff567d8c182db4260855c99f8eae683/PKHeX.Core/PKM/PK7.cs#L104
