### ISSUE TITLE
Gift Egg from HGSS Legality Check

### ISSUE THREAD

**Issue by Lusamine** [kwsch/PKHeX#1766]
Gift egg from HGSS becomes illegal after transfer from HGSS to Platinum to Black and then up through PokeTransporter.  I think the issue is related to the egg met location being overwritten on transfer.  

In Platinum:
![image](https://user-images.githubusercontent.com/30205550/35190172-0cbb7ce4-fe21-11e7-8d7e-44808fb87b1e.png)
In Gen 7:
![image](https://user-images.githubusercontent.com/30205550/35190175-2e731838-fe21-11e7-8fa0-fe7bb56a1dfa.png)

It appears it's in Black version that it gets wiped:
![image](https://user-images.githubusercontent.com/30205550/35190282-1a83b376-fe23-11e7-8d41-df498ad2d409.png)

This is the error message:
![image](https://user-images.githubusercontent.com/30205550/35190185-63b51b5e-fe21-11e7-8659-e23dbeda0f98.png)

**Comment by Orionsilver** [comment]
this HGSS Togepi Gift 
Togepi
The first gift Pokémon you get given is an Egg of Togepi. This Egg is the Mysterious Egg you get sent to collect at the start. After you beat Falkner at the Violet Gym, you will get a call stating that Professor Elm's aide has the Egg for you. He is in Violet City's PokéMart. Hatch the egg and you will quickly discover that the Togepi also has one of Togepi's Egg moves; Extrasensory

![hgss togepi gift](https://user-images.githubusercontent.com/18640392/35191466-ba03a282-fe94-11e7-9215-e8c09f421c76.jpg)

**Comment by Orionsilver** [comment]
the same issue with GS for the Togepi

**Comment by Orionsilver** [comment]
this GS Togepi Gift
![gs togepi gift](https://user-images.githubusercontent.com/18640392/35191525-8e1ec578-fe96-11e7-8400-c424c8afdb77.jpg)
