### ISSUE TITLE
Compile Versions please

### ISSUE THREAD

**Issue by netzulo** [kwsch/PKHeX#1767]
Community need it 

## TODOs 

+ [ ] tag releases
+ [ ] binaries versions as release

**Comment by ReignOfComputer** [comment]
Being worked on on the ProjectPokemon forums front.

**Comment by netzulo** [comment]
Thank you , can you keep this issue opened until have releases ?

**Comment by kwsch** [comment]
Releases are manually posted whenever I feel like the program is stable and worth updating.

**Comment by netzulo** [comment]
then... post links as release tags @kwsch
