### ISSUE TITLE
pokemon database sorting

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1769]
Hi. I just wanted to know if there is a way to change this or maybe add a toggle but when I search for a pokemon in the pokemon database I have my normal living dex, and then I also have my shiny living dex for every generation. Whenever I search for a pokemon, the shiny pokemon comes before the normal pokemon. Obviously this isnt a huge issue but I think that it just makes sense to have normal pokemon sorted first and then the shiny pokemon within the database. Thanks
![untitled-1](https://user-images.githubusercontent.com/21354941/35358985-7dda63ba-0126-11e8-8812-127a80b8f952.png)

**Comment by kwsch** [comment]
Saved files are sorted by file name.
You can always change the code to add a custom sorting algorithm. Not adding anything as it would slow down loading. The current order is by filename and position within the save file.
