### ISSUE TITLE
Pokemon Crystal bugs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1772]
- Celebi flagged (PK2 and PK7); attached are non-shiny/shiny Celebi transferred legitimately
- Met Locations are Gen 7's (again)

![image](https://user-images.githubusercontent.com/17801814/35417001-64000eb2-01f9-11e8-95b6-d98b0980e0f3.png)
[celebi.zip](https://github.com/kwsch/PKHeX/files/1665975/celebi.zip)

**Comment by kwsch** [comment]
Celebi: should clone encounter to use VCEvents like Mew.
https://github.com/kwsch/PKHeX/blob/bb20ec49cc4c14e8d0a359303a7c16a5bd44e1eb/PKHeX.Core/Legality/Encounters/Data/Encounters2.cs
https://github.com/kwsch/PKHeX/blob/bb20ec49cc4c14e8d0a359303a7c16a5bd44e1eb/PKHeX.Core/Legality/Encounters/Data/Encounters1.cs#L120

Met locations: should be returning Gen2 met locations, not sure why it isn't:
https://github.com/kwsch/PKHeX/blob/bb20ec49cc4c14e8d0a359303a7c16a5bd44e1eb/PKHeX.Core/Game/GameInfo.cs#L394-L397

Also note that the Incompatible Transfer move logic will have to be updated (similar to RBY Pay Day Mewtwo). Might be worth checking if Pay Day Mewtwo can be transferred from GSC...

**Comment by sora10pls** [comment]
Pay Day Mewtwo does transfer.
[mew2.zip](https://github.com/kwsch/PKHeX/files/1666152/mew2.zip)
