### ISSUE TITLE
pokemon legality error

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1778]
Hi. Im not sure why this happens for some of my pokemon, but for certain pokemon I have, when loading them from things like the pokemon database, they come up as illegal for not having an OT handler. I know how to change this but im not sure why this happens for some of my pokemon. Ill include 1 I just found now.

[063 - Abra - C4AA9DB7BA40.zip](https://github.com/kwsch/PKHeX/files/1669180/063.-.Abra.-.C4AA9DB7BA40.zip)

**Comment by kwsch** [comment]
Anything transferred from a prior generation to 6/7 can never lack a handling trainer. The original trainer is from a different generation.

ORAS->SM requires the HT to exist, as the OT cannot exist in the same generation.
(stop hacking the same TID/SID/OT/Gender across generations -- it's hacked either way.)
