### ISSUE TITLE
pokemon database xd colosseum issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1779]
Hey I was looking at the database and I wanted to know if its possible to add xk3 and ck3 to the format options on the pokemon database. currently I dont believe that there is any way to search for xk3 and ck3 other than OT type..

**Comment by kwsch** [comment]
The format search only indicates the base format (pk*); ck3/xk3 fall under the pk3 umbrella.

The available search filter controls can't cover every filtering scenario; you'll have to use the advanced filtering parameters. You can achieve filtering with SIZE_STORED.

https://github.com/kwsch/PKHeX/blob/c066df243f8b801980d7d481dc744ea9986bf0ce/PKHeX.Core/PKM/PKX.cs#L26-L27
