### ISSUE TITLE
Wine no longer working

### ISSUE THREAD

**Issue by juppaluri** [kwsch/PKHeX#178]
When trying to open the latest version of PKHeX in wine, PKHeX will crash.  This has not happened until this version.

**Comment by evandixon** [comment]
Do you mean the latest release or the latest commit?

**Comment by juppaluri** [comment]
Latest release.  Sorry I didn't specify that.

**Comment by juppaluri** [comment]
Also I am on Mac OS X.  The Linux people may have different experiences than me.

**Comment by evandixon** [comment]
Fixed in PR #176.
