### ISSUE TITLE
No exception for Crystal Female OT

### ISSUE THREAD

**Issue by CyraFen** [kwsch/PKHeX#1780]
![image](https://user-images.githubusercontent.com/25874350/35465984-121b66ca-02ce-11e8-934e-34d5feb268ac.png)

I understand that Crystal just came out and that you may still be fixing bugs ^_^ just something I noticed while making my team.

**Comment by kwsch** [comment]
Did you forget to put a met location?

**Comment by sora10pls** [comment]
\>making my team

Not a bug, Kaphotics is right. You didn't set a Met Location.
![image](https://user-images.githubusercontent.com/17801814/35467335-2129c47e-02db-11e8-9522-1b050dfe4b13.png)
![image](https://user-images.githubusercontent.com/17801814/35467340-3331bdfc-02db-11e8-8a00-022aaefb7ff2.png)

**Comment by CyraFen** [comment]
nevermind, it was a different issue I was having that I solved by myself, thank you both for your help though!
