### ISSUE TITLE
Pokemon database level filter

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1785]
So I was looking at the database and I noticed that for some reason whenever I search for any Pokemon level 100, no results show up. I have a bunch of level 100 Pokemon in the save I'm looking at, and no matter what filter I use ( <=.   >=.    ==) Nothing shows up. Thanks again

**Comment by k20stitch** [comment]
I believe this filter is for Event Pokemon only, and the level refers to what they're obtained at, not what level they are in your save.
