### ISSUE TITLE
Invalid Moves Crystal Muk

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1787]
![image](https://user-images.githubusercontent.com/2667537/35478952-942f70b8-0425-11e8-9bc2-d352d994533b.png)
![image](https://user-images.githubusercontent.com/2667537/35478954-99347176-0425-11e8-892a-9341d5cb1a06.png)

[089 - MUK - C772.zip](https://github.com/kwsch/PKHeX/files/1670772/089.-.MUK.-.C772.zip)

**Comment by kwsch** [comment]
Works fine on latest commits.

**Comment by ReignOfComputer** [comment]
On latest commit. Flagged in Box on Gen 2 save. Box 5.
[sav.zip](https://github.com/kwsch/PKHeX/files/1670792/sav.zip)

**Comment by kwsch** [comment]
It's got its level 1 moves instead of its Level 33 moves. Not sure why this one is an oddball.

**Comment by ReignOfComputer** [comment]
[085 - DORIS - ECF5.zip](https://github.com/kwsch/PKHeX/files/1670822/085.-.DORIS.-.ECF5.zip)

This too, cannot match encounter. In-game trade.
