### ISSUE TITLE
crystal celebi legality issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1791]
Hey I just wanted to let you know that for some reason now, my celebi that I caugfht in the vc crystal is showing up as illigal in gold and silver. When I load it into a crystal save it is fine, but when I drag it over to any gold or silver save, it acts like it was caught in those games causing a problem. Thanks

**Comment by ReignOfComputer** [comment]
Could not reproduce, is your Gold/Silver save "sav.dat" (VC) or "*.sav" (emu)?

**Comment by NinFanBoyFTW** [comment]
sorry i didnt realize that my gold and silver save was in sav format. it was showing as legal before so I wasnt sure what was going on.
