### ISSUE TITLE
Backwards conversion feature

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1792]
Hey I just wanted to know why or if it is possible to add the backwards conversion from pk2pk to PKHeX. I understand that you cant officially do this and you try to keep things official in PKHeX but would it be possible to at least add it in for PKHaX or something like that. You have the message in pk2pk that says that the conversion is not officially supported, try reflective conversion, so I dont see why that couldn't translate over to pkhex.. Hopefully you will consider it. Thanks

**Comment by sora10pls** [comment]
Seems like a lot of extra handling for such little gain...
