### ISSUE TITLE
Gen1 Mewtwo with Pay Day illegal flag

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#1794]
As title says, gen1 Mewtwo with Pay Day is seen as illegal.

Error:
Invalid Move 1: Incompatible transfer move

**Comment by ReignOfComputer** [comment]
Pay Day will not pass Pokemon Bank's transfer, unfortunately. Thanks GameFreak.

**Comment by Real96** [comment]
Did they change this? Because i passed it through bank some month ago D:

**Comment by ReignOfComputer** [comment]
At least, this was the case a year ago. Have they actually changed this? Gotta do a test.

**Comment by Real96** [comment]
Yeah they changed it. As you can see [here](https://twitter.com/zaksabeast/status/893126615936319489) (he's PCalc dev).

**Comment by sora10pls** [comment]
I already tested and it passed. Refer to #1772

**Comment by Real96** [comment]
Oh, so it has already been fixed. My bad
