### ISSUE TITLE
GTS Slot Bugs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1795]
Viewing in my Y save file:
![image](https://user-images.githubusercontent.com/17801814/35572426-9753a16e-05a2-11e8-8f64-ea139e7aa299.png)

Viewing in ORAS and SM/USUM throws an exception: https://pastebin.com/v8yrdJwe

**Comment by kwsch** [comment]
Will eventually be resolved via a redesign:
https://github.com/kwsch/PKHeX/tree/extraslots
