### ISSUE TITLE
Metronome missing from Banette tutor list

### ISSUE THREAD

**Issue by OmegaDonut** [kwsch/PKHeX#1797]
Body Slam, Mimic, etc. appear correctly as legal moves on a Gen 3 Banette, Metronome does not.

**Comment by kwsch** [comment]
Not able to replicate; post pkm pls :)

![image](https://user-images.githubusercontent.com/6393368/35601918-4da0ccb6-05ea-11e8-91de-150e1b0d5964.png)

**Comment by OmegaDonut** [comment]
closed because issue due to dumbass user error
