### ISSUE TITLE
question on pokemon colosseum

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1803]
Hi. I wasn't sure if this was an error to be corrected or if this was just how pokemon colosseum works but when I look at my colosseum pokemon, their heart gauge is on -100 and they are all purified. On my xd save all of my pokemon have a heart gauge value of 0 when they are purified. I just wasn't sure if that was the structure of pokemon colosseum heart gauges or if this was an error. Thanks

**Comment by kwsch** [comment]
working as intended
