### ISSUE TITLE
Gen 3 Shedinja move legality issues

### ISSUE THREAD

**Issue by OmegaDonut** [kwsch/PKHeX#1805]
1) False Swipe minimum level legality needs to be moved down to L25 from L26
2) Nincada + Ninjask move combo legality on caught Shedinjas restricted by level i.e.
- Swords Dance (Ninjask 25) + Metal Claw (Nincada 38) are illegal
- Slash (Ninjask 31) + Metal Claw (Nincada 38) are illegal
- Screech (Ninjask 20) + False Swipe (Nincada 25) are illegal

[292 - SHEDINJA - 953728844D0D.zip](https://github.com/kwsch/PKHeX/files/1686978/292.-.SHEDINJA.-.953728844D0D.zip)

**Comment by kwsch** [comment]
Are you using the latest commit?
https://github.com/kwsch/PKHeX/commit/4ac92b941800f70d0996cfff142b809a2957578b

**Comment by OmegaDonut** [comment]
bruh don't make me come back to IRC

![image](https://user-images.githubusercontent.com/5870365/35713910-bf1d1ac6-077e-11e8-8c00-36d7b6e6dcb9.png)
