### ISSUE TITLE
Hate to submit this as an issue, but I was curious about something regarding the code.

### ISSUE THREAD

**Issue by mmands994** [kwsch/PKHeX#1807]
I was hoping to fork the github and use it to add more "custom" parts to the showdown format like pokerus or met location. Obviously, this is not something that the actual showdown format uses but I was curious if I would be able to manually add such parts into the code without actually having any prior code knowledge.

Example, here's what a current showdown format looks like:

Salazzle (F) @ PP Max
Ability: Corrosion
Level: 100
Shiny: Yes
EVs: 31 HP / 30 Atk / 31 Def / 30 SpA / 31 SpD / 31 Spe
Timid Nature
IVs: 31 HP / 31 Atk / 31 Def / 31 SpA / 31 SpD / 31 Spe
- Nasty Plot
- Fire Blast
- Sludge Wave
- Hidden Power

However, I was hoping to add new parts to the showdown format and allow it to have something like..

Salazzle (F) @ PP Max
Ability: Corrosion
Level: 100
**Pokerus: Infected**
**Language: ENG**
Shiny: Yes
EVs: 31 HP / 30 Atk / 31 Def / 30 SpA / 31 SpD / 31 Spe
Timid Nature

Could I theoretically do something like this on my own? I mean, don't get me wrong I'm not requesting it as an actual feature but I'm just curious.

**Comment by kwsch** [comment]
Generic line parsing here:
https://github.com/kwsch/PKHeX/blob/1a5d4efdfe0e695d7fa52a8499827fba84413e6c/PKHeX.Core/PKM/ShowdownSet.cs#L97-L146
Generic line generation here:
https://github.com/kwsch/PKHeX/blob/1a5d4efdfe0e695d7fa52a8499827fba84413e6c/PKHeX.Core/PKM/ShowdownSet.cs#L159-L192

**Comment by mmands994** [comment]
Hey thanks for the help but honestly I've been having some trouble with this, the reasoning being that visual studio doesn't want to build after I added "languages" to the showdown format. See [here.](https://i.imgur.com/MiHAHzu.png)

Is there be any specific way I should go about doing this, which includes adding pokerus, met location, and OT Information (maybe)?

I'm trying to set this up for a Reddit forum that I own, if you're curious.

**Comment by kwsch** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0229
