### ISSUE TITLE
7th Gen Game Event Legality Check Error

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1808]
Shiny Tapu Koko currently reads as legal when marked as obtained from US/UM. However this is not possible.
https://www.serebii.net/events/dex/785.shtml
Thanks for taking the time to read this! And for all your work with PKHeX!
![image](https://user-images.githubusercontent.com/15519892/35726454-f613fbe0-07d2-11e8-9853-f87d83291c86.png)

**Comment by sora10pls** [comment]
#1727
Up to the user to know which game(s) the Wonder Card is receivable in.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1727

**Comment by greenDarkness** [comment]
Ah, I see. Thanks!
