### ISSUE TITLE
pokemon fire red event flags

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1809]
Hey I just wanted to know if you were going to try to add event flags to fire red and leaf green or if you just didnt know what the event flags were for the important events. Just let me know if you want me to look into some of the events (legendaries). I tried out getting mewtwo and thenm used the event flag researcher. Here were the results. Im not sure if this type of data is what you need to implement these events but just let me know and ill try to get some more if it helps. Thanks
[mewtwo.docx](https://github.com/kwsch/PKHeX/files/1692403/mewtwo.docx)

**Comment by kwsch** [comment]
Usually event flags get set to de-spawn an overworld object.

Closing, more suited for a research thread on the forums (not an issue with the program).
