### ISSUE TITLE
[Feature Request] Room Decoration Editing for GSC

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1819]
Hello,
I was wondering if it would be possible to add a "Give All Room Decorations" button for Gold, Silver, Crystal to PKHeX? 
I obtained a Gameshark code for "All Decorations" from the website below if it would help with the process.
```
01FFC6DA 
01FFC7DA 
01FFC8DA 
01FFC9DA 
01FFCADA 
01FFCBDA 
01FFCCDA 
```
http://glitchcity.info/wiki/Pok%C3%A9mon_Crystal_GameShark_codes

Thank you for taking the time to read this, and for all your work with PKHeX!

**Comment by kwsch** [comment]
These are already modifiable as event flags.
https://github.com/pret/pokecrystal/blob/b35eb72290b964b98844afbe741bb7ede34b9ef3/constants/event_flags.asm#L693-L738

0x2A4-0x2D1 = 676-721

**Comment by greenDarkness** [comment]
Haha, alright. I'll give that a try then. Thank you for the help. ^_^

**Comment by minuro63** [comment]
Hello! Would it be possible to remove decorations from player's PC in GSC with event flags? Currently, unchecking the event flag does not remove them from the list. Thank you very much for your work!

**Comment by kwsch** [comment]
> Hello! Would it be possible to remove decorations from player's PC in GSC with event flags? Currently, unchecking the event flag does not remove them from the list. Thank you very much for your work!

Nobody has documented where the stored decorations are located in all the Gen2 savefile structures.
