### ISSUE TITLE
Hidden power import issues?

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1821]
![image](https://user-images.githubusercontent.com/17220860/35907911-3388e3b8-0c2a-11e8-9e72-aa1ab3ce4b8b.png)
this import seems to translate to the following in PKHeX
![image](https://user-images.githubusercontent.com/17220860/35907969-5ad30cbe-0c2a-11e8-8953-0c59b25b9472.png)
I'm assuming that this is because of the IV functionality implemented in the commit [bfe4f32](https://github.com/kwsch/PKHeX/commit/bfe4f3222df86df303b37113bb98273fa961030d)
However because of this it seems to be directly disregarding the Hidden power if any sort of IVs are specified. My opinion on solving this would be to check if the provided IVs (in this case Atk = 0) satisfy the Hidden Power requirement. If they do not, then keep the specified IVs as they are and then try to implement Hidden power with the unspecified IVs. If implementation of HPs is impossible because of conflict in provided IVs and provided Hidden Power, then it should give priority to the provided IV distribution.

Keep up the work on PKHeX btw! Its amazing to see it grow so far from the ORAS days!

```
Rotom-Heat @ Choice Scarf
Ability: Levitate
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Defog
- Overheat
- Volt Switch
- Hidden Power [Ice]
```

**Comment by kwsch** [comment]
Ugh, Showdown started omitting flawed IVs in the output (as they can be hyper trained to 31). 31/0/31/31/31/31 is HP Dragon. Showdown conversion was initially implemented before Hyper Training existed :)

Probably will have to add special handling for setting a Hidden Power Type (rather than using Showdown's Gen6 IVs).

**Comment by architdate** [comment]
That was fast! Thanks for the fix! I don't have access to my PC to look through the code currently, but just to clarify, this is permuting flawless IVs between 30 and 31 to find the first valid HP combination while respecting user specified IVs too correct?

**Comment by kwsch** [comment]
Yes. 
It gets the index of all unspecified IVs (which are flawless [31]) and bitflips them (changing the order every attempt) to find a combination that results in the desired HP Type.
