### ISSUE TITLE
Add support for bank.bin from PKSM

### ISSUE THREAD

**Issue by DarkLordZach** [kwsch/PKHeX#1822]
I currently have basically all of my pokemon stored in PKSM's bank, which is alternative to the real Pokemon Bank, but offline and supportive of hacks. It stores it's data in a file called `bank.bin` or `bank_<time_date_string_here>.bak`, depending if it is the current or a backup. There appears to be no documentation of the format online, but upon some inspection it is simply the pk7 files concatenated in binary. It uses the 232 byte version and supports 300 boxes with 30 slots. I am asking that you add support for editing this bank file similar to a save file, without the party-battle box and daycare tabs and all of the buttons at the bottom. I started looking around the code and I couldn't think of a way to do it that isn't like 'make a save file but null out everything' or equally hacky.

**Comment by architdate** [comment]
Documentation can be found via PKSM code actually! And if it is what you say (`.pk7` files concatenated) then loading bank.bin into a box should be fairly simple by just having a function to get separate pk7 files (binary chunks with the pk7 file size) and then setting each one of them to the current box. (Something like battle video viewing in PKHeX)

**Comment by kwsch** [comment]
No existing save file format has 9,000 slots (at most 50 with RS Box), so it'd be unable to behave like the Battle Video import which dumps to the current save.

I'd rather not support unofficial data formats. You can always split the binary file to pcdata sizes with another program, and load those individually.

Using PKHeX.Core you can dump out the pkm files pretty easy. Load the byte array, read out 232 byte chunks, create a new pk7 instance with that data, then save it to a folder if the species isn't 0. At most 10 lines :)

```c#
var bin = File.ReadAllBytes(@"D:\bank.bin");
for (int i = 0; i < bin.Length; i += 232)
{
	var data = new byte[232];
	Array.Copy(bin, i, data, 0, 232);
	var pk = new PK7(data);
	if (pk.Species != 0)
		File.WriteAllBytes(Path.Combine(@"D:\", PKHeX.Core.Util.CleanFileName(pk.FileName)), data);
}
```
