### ISSUE TITLE
Legality Checker Issues

### ISSUE THREAD

**Issue by Perseonn** [kwsch/PKHeX#1823]
I noticed that the legality checker now has more rules, but something seems off. Opening my save from Pokemon FireRed, which I never tamper with, some Pokemon are marked as illegal, including my starter Charizard.

There's even this one Tyranitar marked as "Met Level must be 0".

[Charizard-Tyranitar.zip](https://github.com/kwsch/PKHeX/files/1705333/Charizard-Tyranitar.zip)

Another thing is that, when I opened my HGSS save, some Pokemons that I Pal Parked from Gen III which came with their Ultra Balls are marked as illegal (Can't Have Ball for Encounter Type).

Thank you for your good work!

**Comment by kwsch** [comment]
Can't catch larvitar at level 46 in Sevault Canyon. Likely you edited a Geodude (at level 46) into Larvitar ;)
That one is illegal.

Charizard has a Method 4 PID type instead of Method 1. Was this playthrough using an emulator?

**Comment by Perseonn** [comment]
Didn't remember about the Larvitar (Didnt have pokexes or pkegen back then :S), but yeah it was on Emulator. That affects the outcome?

**Comment by kwsch** [comment]
Yep, that'd explain it.

The game's PKM generation routine has the chance of getting interrupted by a screen refresh, which causes the internal RNG to advance once. Emulators don't emulate the exact speed, which results in a slightly slower game execution... which results in the PKM generation routine getting paused... resulting in an unexpected PID/IV. At least that's the current theory, as nobody has obtained a Method 2/4 spread from a legitimate cartridge.

PIDIV unobtainable on a cartridge => illegal pkm :)
