### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by scj643** [kwsch/PKHeX#1825]
A python library for working with Pokémon save files would be interesting. I don’t know much about c# but a scripting for PKHeX would be nice.

**Comment by kwsch** [comment]
Can do this with [LINQPad ](https://www.linqpad.net/) by adding the PKHeX.Core class library as a reference for all scripts.

Related python-c# library usage: https://stackoverflow.com/a/29854281
Leaving this issue open for a day or two, then closing.

**Comment by Mrtops** [comment]
I agree interesting idea but not worth it because we already have a good working version if you want to though you could make it in a fork
