### ISSUE TITLE
HP Ice Small Showdown Import Issue

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1826]
Hey for some reason when I try importing this set.. Manectric @ Manectite
Ability: Lightning Rod
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Flamethrower
- Thunderbolt
- Volt Switch
- Hidden Power [Ice]

I get this instead..

Manectric (F) @ Manectite
IVs: 30 HP / 0 Atk / 30 Def
EVs: 252 SpA / 4 SpD / 252 Spe
Ability: Lightning Rod
Level: 100
Timid Nature
- Flamethrower
- Thunderbolt
- Volt Switch
- Hidden Power [Ice]

The HP IVs don't affect the HP type. You can edit out the HP IV thing re-export the set in showdown format and re-import and its fine.

I feel like ever since Gen 2 Celebi has appears with its 5IV lock in its screwed up with the hidden powers. Maybe it should have some special exception that keeps it seperate from other imports. Something like If Celebi is shiny/has a gen 2 move then HP Ice = 30 IVs (Just putting down my thoughts, wish I was a coder but I'm a lot better at breaking things. :P )

**Comment by kwsch** [comment]
You can't get HP Ice on a 5IV=31 pkm.

**Comment by DJPanda065** [comment]
Yeah sorry I messed up what I was saying. If Shiny Celebi has HP Ice then instead of lowering atk and df like regular HP Ice does, it instead lowers the speed.

**Comment by kwsch** [comment]
If showdown provides illegal set data, then PKHeX will import the illegal set data (and not fix it -- importing does not have legality context).
