### ISSUE TITLE
Punishment Murkrow Legality

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1829]
https://bulbapedia.bulbagarden.net/wiki/Punishment_(move) PKHeX says Punishment Murkrow is legal but according to Bulbipedia it is unable to learn it at the given time. (Kinda in a situation similar to the HA starters I guess.)

**Comment by ReignOfComputer** [comment]
![image](https://user-images.githubusercontent.com/2667537/36068627-722cf842-0f14-11e8-9dee-1489818af54f.png)

**Comment by DJPanda065** [comment]
"In Pokémon Ultra Sun and Ultra Moon, Murkrow is programmed to be able to learn Punishment through breeding, but no other Pokémon in the Flying Group can pass down Punishment as an Egg Move in those games. Vullaby and Mandibuzz are the only Flying Egg Group Pokémon that can learn Punishment, but they cannot pass down the move due to being female-only species."

-Bulbipedia

This is what I am talking about

**Comment by ReignOfComputer** [comment]
Fascinating edge case.

GF is amazing.

**Comment by kwsch** [comment]
Related reading: 
- https://glitchcity.info/wiki/Unused_and_redundant_Egg_moves
- https://projectpokemon.org/home/files/file/1875-pk2-unobtainable-egg-moves-pokemon/
