### ISSUE TITLE
2009 Gen IV Event Regigigas Legality Issue

### ISSUE THREAD

**Issue by Shadic375** [kwsch/PKHeX#1830]
[486 - Regigigas - E48621B474B7.zip](https://github.com/kwsch/PKHeX/files/1714035/486.-.Regigigas.-.E48621B474B7.zip)

An event Regigigas from 2009 Gen IVappears to have legality issues with "can't have ball for encounter type"  and "faithful encounter should not be checked"  even though that's how it was distributed. Would love to see this fixed. Thanks!

Source:
https://www.serebii.net/events/dex/486.shtml

**Comment by kwsch** [comment]
>event Regigigas
>OT = CHRIS

That's hacked. Working as intended.
