### ISSUE TITLE
shiny ash pikachu

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#1831]
ash pikachu shiny sprites are the same as the originals, like magearna's normal form. pkhex shows all of ash pikachu forms to be darker even though this isn't what the shinies look like

magearna is fine

![image](https://user-images.githubusercontent.com/35694052/36069807-f0efb770-0ebd-11e8-9bb4-6c654c11dc77.png)

**Comment by kwsch** [comment]
PKHeX uses https://github.com/msikma/pokesprite ; if the pkm actually had a shiny texture it'd likely be the same as Pikachu. I'm fine with it the way it is.
