### ISSUE TITLE
[BUG] Pokeballs

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#184]
When generating pokemon, or editing them, it doesn't place them back in the correct pokeball. Changed all of my pokemon from Normal Pokeballs to Great Balls (in game)

**Comment by evandixon** [comment]
Just to clarify, what generation of Pokémon are you editing?

**Comment by kwsch** [comment]
You're too vague; please be sure you're using the latest version of the program.

The last posted update had a fix relating to gen4 balls.
https://github.com/kwsch/PKHeX/commit/a8a0060c2e31dfe21f5a994c14a310f4a428d302

What is the date on your program?

**Comment by Ninjistix** [comment]
pokemon platinum, using the one from [PKHeX (08-07-16).zip](https://projectpokemon.org/forums/showthread.php?36986)
