### ISSUE TITLE
PKHeX persist to set english language to any Pokémon I create

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#1843]
Sorry @kwsch you seem to have fixed it in #1842 but the problem remain (I compiled it after your fix).

I made a quick (30s) video Youtube to show what exactly the problem is.
https://youtu.be/FCNBUo-_0k4

It just persist to set english language on some Pokemon.

Attached my save if you want look:
http://www78.zippyshare.com/v/WF9zUkPa/file.html

**Comment by kwsch** [comment]
The program title is not indicative of the debug version.

**Comment by Asia81** [comment]
Oops sorry, then I will wait a bit more

**Comment by Ammako** [comment]
@kwsch Unless of course one compiles as Release, which just uses version string from previous stable release, without taking away from any of the recent commit changes.

!(gif)[https://puu.sh/zqGCZ/abc36d8b97.gif]
