### ISSUE TITLE
[Bug] Partner Cap Pikachu and Dusk Lycanroc in SM

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1845]
PKHeX allows for the user to set Pikachu to Partner Cap as well as Lycanroc to Dusk in SM save files. Necrozma working as intended.

**Comment by sora10pls** [comment]
Marowak and Mimikyu also affected (Totem-sized gifts). Looks like it's just any Pokemon that received a new form in USUM that already had at least 1 alt form.

**Comment by kwsch** [comment]
PKHeX already alerts the user that the forme count is out of range.

If the user wants to set invalid data, that's up to them.
