### ISSUE TITLE
Pokemon Gen 5 Ability Setting Error

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1846]
An error that I have found is that upon setting a Pokemon's ability to or from its hidden ability, sometimes, the flag of 0x42 which is the boolean flag that toggles a Pokemon's Hidden ability will not be changed, resulting in a Pokemon either regaining it's hidden ability or losing it upon evolving. I tried to search for problematic Pokemon through the conditions of 
=HiddenAbility=True
=_0x42=0
or
=HiddenAbility=False
=_0x42=1
But the second line never finds anything in the Batch Editor or the Pokemon Database advanced search, and as a result, this does nothing. In order for proper ability handling to work, they will both need to be True and 1 or False and 0 respectively. 
This error will also be exacerbated when opening PKHeX in illegal mode which will just randomly set Pokemon's 0x42 flag to zero, causing a Mismatch. This happened with my Therian Forme Trio from the Dream Radar as upon opening the program in illegal mode to modify items, upon saving, their flags were set to 0 even though I didn't even touch them during my using of illegal mode. 
So either fixing the mismatching error or allowing me to search and modify Pokemon through the 0x42 flag.

**Comment by kwsch** [comment]
`HiddenAbility` is the property to be searching for; _0x42 is not a valid searchable.
