### ISSUE TITLE
Time not set correctly in Gen 1

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#1847]
I guess the image say what's the problem is.
http://nsa39.casimages.com/img/2018/02/21/180221062958696252.png

Isn't 999h59mn59s the maximum in all pokémon games?
Anyways, without edit it, my played time is around 130h, so it's not limited to 99h59mn59s.

**Comment by kwsch** [comment]
999 = 0x3E7
231 = 0xE7

current logic:
https://github.com/kwsch/PKHeX/blob/d62b34f1404664274819b059e05b692fee9f1613/PKHeX.Core/Saves/SAV1.cs#L267-L281

**Comment by Asia81** [comment]
Strange, because I set to 255h58mn00s, I waited a bit, saved and reload my save, and time is back to 00h
http://nsa39.casimages.com/img/2018/02/21/180221064601411806.png

**Comment by kwsch** [comment]
https://github.com/pret/pokered/blob/5c2419383118280465a89657fed34ed6562f2981/wram.asm#L3180-L3189

Looks like it's capped to 255 hours max. Not sure when the play time maxed should be set...
[hrs, max, min, sec, frames]
