### ISSUE TITLE
Trading evolution

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#185]
It would be nice to add an option to "evolve" pokemon that only evolve by trading like kadabra. So by doing click in that option Kadabra will evolve in Alakazam like I would trade with an other player and he returned to me.

**Comment by kwsch** [comment]
Would only have a use gen6 onwards, and would only automate:

Changing Species (checking evolutions)
Adding HandlingTrainer, Two Regions (OT and HT), adding HT Memory, Friendship

I think it's too niche and is handled fine by the legality checker telling the user what needs to be updated.
