### ISSUE TITLE
Floette SOS legality

### ISSUE THREAD

**Issue by ParalyticStates** [kwsch/PKHeX#1850]
Apologies if this has already been addressed as I'm still using the latest stable release:

https://projectpokemon.org/pages/games/pok%C3%A9mon-ultra-sun-and-ultra-moon/new-pok%C3%A9ball-combinations-r19/

According to this, all Floette forms other than the default Red Flower form have a call rate of 0 in USUM, meaning that Blue Flower Floette can't have its hidden ability if caught in USUM, Blue Flower Flabébé can't be bred with its hidden ability in an Apricorn or Beast Ball, and Orange and White Flower Floette can't be caught in Poni Meadow at all.

**Comment by kwsch** [comment]
White/Orange can be SOS'd: https://github.com/kwsch/PKHeX/pull/1628

**Comment by kwsch** [comment]
Post Encounters7.cs setup modifications required:
- [ ] Remove Blue SOS slots
- [ ] Remove Orange/White SOS slots from non-Red origin callers
Checks.cs addition required:
- [ ] Flag Blue ball inheritance
