### ISSUE TITLE
[Request] Add a Event Flag Researcher in G/S (G2)

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#1851]
Like this one for Crystal:
http://nsa39.casimages.com/img/2018/02/26/180226013854645992.png

I would like to research some flags (like moving suicune entei and raikou, or lugia/ho-oh) and submit them to you.

**Comment by kwsch** [comment]
The event flag sub-editor is only available if the offset for Event Flags is set.

[Only Crystal has the offset specified for INT/JP (no Korean support)](https://github.com/kwsch/PKHeX/blob/89d3437d0b77d178a6e61e77515e1b0d1165f060/PKHeX.Core/Saves/Substructures/SAV2Offsets.cs), all others have not been documented.
