### ISSUE TITLE
PKME_Tabs.PKMIsUnsaved Behavior

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1853]
Just want to check if this was intended behavior.

1. Open SAV
2. View Pokemon from Box
3. Set Pokemon elsewhere in Box, not overwriting original
4. Save SAV

When exiting PKHeX, `PKME_Tabs.PKMIsUnsaved` is **true** which causes the "Any unsaved changes will be lost" dialog to appear.

**Comment by kwsch** [comment]
>3. Set Pokemon elsewhere in Box, not overwriting original

That's why. Whenever PKHeX writes data to a save file it flags it as edited; it does not check if the written data currently matches the existing byte sequence.
