### ISSUE TITLE
Request: autodetect *.SaveRAM extension

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#1856]
Much like how .dat and .dsv are detected.
This extension is used by BizHawk. Relevant for Gen. 1, 2 and 3.

One *could* just manually delete the extra ".sav" in the save dialog every time before saving, or remove it afterwards in file explorer, but for convenience reasons it'd be nice if the extension could just be detected as such and avoid adding an extra ".sav" at the end of the file name.

(Worth mentioning that, unlike DeSmuME, BizHawk uses raw save files, it just uses a different file extension. So the file contents are the same as you'd find in .sav or .dat, no header or footer or anything.)

**Comment by kwsch** [comment]
PKHeX will not support loading/editing of save states:
* RAM data is not laid out in the same manner as the stored savedata.
* Every emulator can have a different internal format.
* Internal formats can change between emulator versions.

**Comment by Ammako** [comment]
It's not save states lol.

**Comment by Ammako** [comment]
I didn't think I'd need to since I already specified that it's the exact same as .sav just in a different extension, much like how VC .dat is the same file contents as .sav, but

[Pokemon - Red Version (USA, Europe).zip](https://github.com/kwsch/PKHeX/files/1769489/Pokemon.-.Red.Version.USA.Europe.zip)

**Comment by kwsch** [comment]
File loads just fine via drag/drop, or opening with the file->open menu.
PKHeX doesn't care about file extensions; the only exception to this is checking ".dat" for determining if the save originated from a VC game.

Not going to add filters for every extension for every emulator that has their own unique file naming conventions. The All Files option is the default for file->open and allows for anything to be opened.

**Comment by Ammako** [comment]
>Not going to add filters for every extension for every emulator that has their own unique file naming conventions.

So I guess DeSmuME just gets special treatment because reasons?

**Comment by kwsch** [comment]
It doesn't get special treatment:
![image](https://user-images.githubusercontent.com/6393368/36823438-065707ec-1cb2-11e8-889d-0245b2ffcbe2.png)

**Comment by Ammako** [comment]
Demonstrably wrong.

![image](https://puu.sh/zxWLL.png)

**Comment by Ammako** [comment]
(Worth noting that .dat save files get "Save as type: SAV File (*.sav)" on the save as dialog, despite keeping their .dat extension as-is without getting an extra .sav added onto the end. However it's being done for .dat, it doesn't have to require adding a whole new file type extension like for DeSmuME DSV.)
