### ISSUE TITLE
Backstroke bot

### ISSUE THREAD

**Issue by Mrtops** [kwsch/PKHeX#1858]
We need to update the backstroke webhook in this repo

**Comment by Mrtops** [comment]
Here is what the bot itself says 

It's also worth noting that you're using an old version of Backstroke. At your earliest
convenience, please update to a newer version! Here's how:

Remove the http://backstroke.us webhook from your repository.
Visit https://backstroke.co/, and click the big Login with Github button.
Create a link mirroring the Backstroke setup you had previously.
Thanks!

**Comment by kwsch** [comment]
Removed webhook; was already configured on the new site (ie 2 -> 1).

**Comment by Mrtops** [comment]
Ok just wanted to make sure you were aware because I kept seeing that it was out of date.
