### ISSUE TITLE
HA Gen 7 Starters still illegal

### ISSUE THREAD

**Issue by CyraFen** [kwsch/PKHeX#1861]
![image](https://user-images.githubusercontent.com/25874350/37166348-d01ba5b8-22cc-11e8-9b38-a1447ad8f097.png)

Double checked that I am using the latest commit, and these were taken straight from the mystery gift guy with no modifications.

I'm assuming that unbanning the HAs was for breeding purposes and not for the actual event mons, but I just want to make sure.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1518#issuecomment-335507415
