### ISSUE TITLE
Showdown Import Issues

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1862]
Is ApplyMarkings() something new? If so, how about a toggle to skip marking the Pokemon based on its IVs?

Additionally, the latest commits no longer set the Pokemon's gender correctly if the Pokemon is genderless.

**Comment by kwsch** [comment]
Any reason why one would not want markings automatically applied? Just curious :)

Current auto-marking logic:
https://github.com/kwsch/PKHeX/blob/102550174edaf6ecb8fd337649e3d5ba0311db0b/PKHeX.Core/PKM/Editing/CommonEdits.cs#L306-L326

**Comment by sora10pls** [comment]
Could be people just don't like markings, in the case of Gen 7 some people may prefer the blue/pink to be inverted, some people only mark what stats *aren't* perfect, etc

**Comment by ReignOfComputer** [comment]
Same here. Not a fan of markings, doesn't feel clean :P

Could maybe add a setting under Showdown to toggle this.

**Comment by kwsch** [comment]
The options menu & managing it all is getting a little cluttered, maybe I can come up with a master settings managing window to better deal with things...
