### ISSUE TITLE
[Bug] Ditto Five legality

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1863]
All marked as invalid using the latest commit, unable to match encounters to origin game. Can test using the [PK7s from RoC's PC.](https://github.com/ReignOfComputer/RoCs-PC/tree/master/25%20-%20Gen%20VII%20-%20USUM%20Collection/Static%20Encounters/Ditto%20Five)
![image](https://user-images.githubusercontent.com/17801814/37305513-113f22c2-260b-11e8-8837-3b928cf4c7a7.png)

**Comment by sora10pls** [comment]
RoC's Konikoni City Adamant Ditto isn't flagged (rest are), though all of mine are. Here's a zip of mine as well: [ditto5.zip](https://github.com/kwsch/PKHeX/files/1804282/ditto5.zip)

**Comment by kwsch** [comment]
Fixed IV checks were recently introduced (previously unchecked), could be that the ordering of the IVs is wrong in the Encounters7.cs class (speed is not the last IV).

Generator/Validator:
https://github.com/kwsch/PKHeX/blob/102550174edaf6ecb8fd337649e3d5ba0311db0b/PKHeX.Core/Legality/Encounters/Generator/EncounterStaticGenerator.cs#L149-L152

Dittos:
https://github.com/kwsch/PKHeX/blob/102550174edaf6ecb8fd337649e3d5ba0311db0b/PKHeX.Core/Legality/Encounters/Data/Encounters7.cs#L356-L360
