### ISSUE TITLE
Suggested Moves Glitch

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1865]
Case 1:
1. Have a Pokemon with 4 moves at Level 1, say, Beldum or Ralts.
2. Have PKHeX suggest moves.
3. Only the first move is changed. The rest of the moves are not.

Case 2:
1. Have a PKHeX suggest 4 moves for any Pokemon.
2. Each time the suggestion is run, only 1 move is changed.

Looks like PKHeX is comparing and setting one move at a time, instead of all at once. No PC to debug with right now.

Also: Suggested moves now automatically have their PP maxed, just want to make sure this is intentional behavior?

**Comment by ReignOfComputer** [comment]
Issue stems from this line: https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L1459

Couldn't think of any other way except deregistering the EventHandlers and registering it back after the suggested moves are applied.

**Comment by kwsch** [comment]
Will address the PP maxing later today; thanks for the fixes :)
