### ISSUE TITLE
PokePark Whismur Origin Game

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1873]
According to Bulbapedia, this Whismur cannot be obtained in Ruby or Sapphire; however it only reads as legal if set as obtained in Ruby, but not Sapphire. Thanks for all your work with PKHeX!
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9Park_(theme_park)#Whismur

[293 - Whismur - FAFD1EB709AA.zip](https://github.com/kwsch/PKHeX/files/1831291/293.-.Whismur.-.FAFD1EB709AA.zip)

**Comment by kwsch** [comment]
Gen3 events are mostly not implemented; PKHeX attempts to match the data to anything. Just so happens that the event matches for one game.

https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Encounters/Data/EncountersWC3.cs

**Comment by greenDarkness** [comment]
If (int)GameVersion.R was changed to (int)GameVersion.RS wouldn't it make it so that the event matched for both? Or am I misunderstanding? 
Thank you taking the time to give me an explanation.

**Comment by kwsch** [comment]
The egg is distributed with the version set to Ruby regardless of the game receiving it. There is no way to have the game change it to Sapphire.

**Comment by greenDarkness** [comment]
Oh, I understand now. Sorry, I didn't know that it would always be set to Ruby regardless of the game it was actually obtained. Thanks again!
