### ISSUE TITLE
Legality Checker/Transfer Issue from Gen IV to Gen VII

### ISSUE THREAD

**Issue by JubalTheLion** [kwsch/PKHeX#1875]
I've been trying to help someone on Discord who has been manually exporting Pokemon from their SoulSilver save to their Sun save. From what I've gathered, these Pokemon have been RNG abused, specifically via Cute Charm TID/SID abuse.  

[PKM Files.zip](https://github.com/kwsch/PKHeX/files/1842989/PKM.Files.zip)

The Cubone and Farfetch'd were caught in the Safari Zone, while the Gloom was caught on Route 48. All three are reported as legal in the SoulSilver save, but show up as illegal once they are exported and imported to the Sun save. All three show the following message:

"Invalid: Can't have ball for encounter type." 

I am using the latest official release of PKHeX from 18/03/19. I figured that either these mons are triggering a false negative in Gen IV or a false positive in Gen VII (although the user who sent me these claims they are not hacked).

**Comment by kwsch** [comment]
Should be fixed as a part of a recent (after latest release) commit:
https://github.com/kwsch/PKHeX/commit/d1cfdd782ec1e81da41800aaa42091210029da19

**Comment by JubalTheLion** [comment]
I keep forgetting how quickly you work on this stuff. "What could have possibly been fixed since the latest official release?" 

Thanks for the response; in the future, I'll be sure to try the latest commit before opening an issue.
