### ISSUE TITLE
Pre-Gen6 pokemon OT affection.

### ISSUE THREAD

**Issue by ijuintekka** [kwsch/PKHeX#1881]
With the new check for contest related affection, any pre-gen6 pokemon are made illegal when their OT affection is set to zero.

https://github.com/kwsch/PKHeX/blob/78616e1ad533e01bcefbddfe1b701fae382dae90/PKHeX.Core/PKM/PK6.cs#L444

https://github.com/kwsch/PKHeX/blob/78616e1ad533e01bcefbddfe1b701fae382dae90/PKHeX.Core/PKM/PK7.cs#L499

https://github.com/kwsch/PKHeX/blob/78616e1ad533e01bcefbddfe1b701fae382dae90/PKHeX.WinForms/Subforms/PKM%20Editors/MemoryAmie.cs#L109

The checks for OT_Affection on pre-gen6 pokemon will also need to be changed to accommodate this.

**Comment by sora10pls** [comment]
Also worth noting, I just realized that events that were entered into Contests and have OT Affection of 255 are flagged. Should be any multiple of 20 as well as 255 (no 260)
![image](https://user-images.githubusercontent.com/17801814/38038241-878379be-3278-11e8-9378-2b1d3ffca4ba.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/78616e1ad533e01bcefbddfe1b701fae382dae90/PKHeX.Core/Legality/Checks.cs#L1588

`pkm.OT_Affection == 255 || pkm.OT_Affection % 20 != 0`
should be
`pkm.OT_Affection != 255 && pkm.OT_Affection % 20 != 0`
