### ISSUE TITLE
GS error

### ISSUE THREAD

**Issue by Narithegreat** [kwsch/PKHeX#1897]
Whenever I try to load up my Unown in the editing tabs for Gold, the form label scrolls a lot and is always read as "A" despite not being that one.

And another thing is for SMUSUM shouldn't this be illegal as there is no female player specifically for GS?
![untitled-3](https://user-images.githubusercontent.com/38122443/38833171-c9cceda4-4192-11e8-8954-16c0b999b7b1.jpg)

**Comment by kwsch** [comment]
2. Trade from C->G then transfer; the only way to remove C data is to trade to RBGY.
