### ISSUE TITLE
Gen7 Event Flags Solgaleo/Lunala Captured is wrong

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#1898]
I didn't catch Solgaleo/Lunala in my save file, but PKHeX shows the opposite in Event Flag. The problem is bot in SM/USM

**Comment by kwsch** [comment]
Event flags are related to spawning the NPC in the overworld; if it is not to be spawned, it can be flagged as such.

**Comment by Real96** [comment]
Oh i though it was related to the catch of Solgaleo/Lunala near the bridge. Thanks!
