### ISSUE TITLE
[Bug] Showdown Quirk

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1905]
The species name `Meowstic` is supposed to always be male according to showdown. The female form is denoted with the showdown name `Meowstic-F`. The current method of forcing male on meowstic is by using `Meowstic (M)` with the forced male gender denoted by `(M)`

Unfortunately I don't have access to my PC for the next hour. If you haven't worked on this till that time then I can send a PR for a fix :)

Thanks again for all your work on PKHeX! Keep up the great job!

**Comment by kwsch** [comment]
Just created a team on showdown;

```Meowstic (M) @ Sablenite  
Ability: Keen Eye  
- Hidden Power [Fire]  
- Dark Pulse  
- Light Screen  
- Fake Out  

Meowstic-F (F) @ Choice Scarf  
Ability: Keen Eye  
- Facade  
- Energy Ball  
- Extrasensory  
```

**Comment by architdate** [comment]
The issue is that 
```
Meowstic @ Sablenite
IVs: 30 Atk / 30 SpA / 30 Spe
Ability: Keen Eye
Level: 100
Hardy Nature
- Hidden Power [Fire]
- Dark Pulse
- Light Screen
- Fake Out
```
should also give male as the gender

**Comment by architdate** [comment]
The -F without specified (F) gender is handled already because you check for -F as a form and set it as the gender in `GetShowdownText` function. However importing something like
```
Meowstic @ Black Sludge  
Ability: Prankster  
Shiny: Yes  
Modest Nature  
- Assist  
- Barrier  
- Trick  
- Yawn
```
would cause issues with further legality as although the forme is set as male, the gender is still actually female, so it denies legality of moves such as assist, yawn etc (Which can only be learnt by male meowstic)
