### ISSUE TITLE
Gender Legality Check and Mothim Forms

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1912]
Hey so apparently if you import a set like this below. (A mon that can only be one gender.) PKHeX doesn't flag it as a specific gender only mon.  Amusingly eneough you can actually see the gender switch in game, as shown in the picture. Don't know if it actually affects anything lol. Also just looking at mons, apparently Mothim has Wordam's forms listed. Not sure if this is actually legit or not.

![female latios](https://user-images.githubusercontent.com/29782059/39162115-8918242a-4739-11e8-93c7-cdd2283bf2b6.png)

```
Latios (F) @ Latiosite
EVs: 4 Atk / 252 SpA / 252 Spe
Ability: Levitate
Level: 100
Naive Nature
- Draco Meteor
- Psychic
- Earthquake
- Roost
```

![mothim forms](https://user-images.githubusercontent.com/29782059/39162142-ae27278e-4739-11e8-91b3-4415a792ecec.png)

[Male Salazzle.zip](https://github.com/kwsch/PKHeX/files/1940562/Male.Salazzle.zip)

https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_gender_ratio

**Comment by kwsch** [comment]
Mothim doesn't clear the Burmy form it evolved from, so that's working as intended.
