### ISSUE TITLE
GSC Showdown Import Leftovers = TM42 when Finished

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1913]
```
Zapdos @ Leftovers
- Thunder
- Hidden Power Ice
- Rest
- Sleep Talk
```

It seems when I import sets in gen 2 save files. Sets with leftovers give the mons TM42 instead of the actual item.

Apparently when exporting you get this.

```
MILTANK (Miltank) (F) @ **Bridge Mail T**
IVs: 15 HP / 15 Atk / 15 Def / 15 SpA / 15 SpD / 15 Spe
Ability: —
Level: 100
Hardy Nature
- Heal Bell
- Milk Drink
- Growl
- Body Slam
```

https://github.com/ReignOfComputer/RoCs-PC/tree/master/04%20-%20Gen%20II%20-%20GSC%20Collection%20{pk2}/Save%20Data  Also I can't seem to reproduce it anymore but a couple times the pkhex app crashed when I tried loading the Gold save. (No error dump just the application stopped working and then forced exited. I dragged the save file into the application.) Might just be something to look out for. If it happens again I'll try posting or something.

**Comment by kwsch** [comment]
Right, that's because gen2 (and gen3) have different item tables than the contiguous NDS+ games.

Will investigate possible resolutions.
