### ISSUE TITLE
pokemon gen 6 feeling legality issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1917]
Hi. I just looked at my gen 6 save and I found that my event articuno and mew are illegal because their feeling is set to "it had fun". I have not edited these pokemon so Im not sure why these are like this. Also when I set it to "it was happy" they are legal so I dont know what happened.
[151 - Mew - 41FE7220611F.zip](https://github.com/kwsch/PKHeX/files/1958348/151.-.Mew.-.41FE7220611F.zip)

**Comment by kwsch** [comment]
Recent improvement in catching hacks:
https://github.com/kwsch/PKHeX/pull/1916

**Comment by NinFanBoyFTW** [comment]
Ok but these weren't hacks. These were both legit events that I got and then received in game. Unless pkhex edited them somehow, I didnt modify these.

**Comment by NinFanBoyFTW** [comment]
I also have the zapdos and moltres from that same exact event, and they are legal. Same recieved date and event.
