### ISSUE TITLE
Different SID and TID

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#1918]
Hey so I was collecting OT info for a friend of mine and was comparing mons from the same game, and appears something changed. The values from the TID and SID are different from the new pkhex versus the old one. Both of the same eggs are selected. The pkhex on the left was the value was what I originally had. (The latest stable.) While the other one is the latest commit of pkhex in general. Not sure if this is a bug or not. If it's not, maybe there should be a switch to see the other TID/SID values? 

![image](https://user-images.githubusercontent.com/29782059/39408136-cb832e42-4b97-11e8-8be7-e36ca72353c8.png)

**Comment by kwsch** [comment]
Check the game origin of each pkm.

Left = Gen 6 and below
Right = Gen 7 and above.
