### ISSUE TITLE
Trainer Card Hall of Fame + Game Sync ID

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#192]
I just have two questions about it. How do I change the First Hall of Fame entry on the Trainer Card. I changed the date in PKHex, but it doesn't apply to the card. 

Also, about changing Game Sync ID, is it as simple as changing the values in PKHeX or using a hex editor and a new game file to add a new id and apply it to the orginal game?

Also, if possible, can they're be a Game Sync ID randomizer added just like the EC Constant?

**Comment by kwsch** [comment]
Pretty sure you have to use the hall of fame editor to update the "first"
date as well.

Game Sync ID changing is only available if the save already has an ID. It's
intended use is to unban save files by copying the ID from a save that is
not banned.

**Comment by ricksee** [comment]
I still did that, but on the trainer card, the date remains unchanged.

So for the Game Sync ID, it can't be changed manually, like changing a letter or 2?

Thanks for the reply.

**Comment by kwsch** [comment]
Just to be sure, did you change the First Entry date in both the Trainer
Editor and Hall of Fame Editor? I think the SecondsToFame value is the one
displayed on your trainer card, and the HoF value is when you actually view
the record.

Game Sync ID is a number provided by the online server when you first
register. Tweaking the value will get you nowhere as the ID has to
correspond to an ID stored on the server. Think of it like a social
security number for your save file; you can steal the identity of someone
else, but not create your own.

**Comment by ricksee** [comment]
Yes. For the Hall of Fame Entry, it changes when I go to records from the PC. But for the trainer card, it does not.

As for Game Sync ID, I would have to make a new save file and get the new ID from PKHeX and then add it to the original banned game in PKHeX? Thanks for answering that one.

**Comment by ricksee** [comment]
I can show you if you want.

**Comment by kwsch** [comment]
SecondsToFame is the property; appears as if this is not exposed in the Gen6 Trainer Editor (but is for previous gens).
https://github.com/kwsch/PKHeX/blob/2b9b16ad39547016232806c6944362bafc8db552/PKHeX/Saves/SAV6.cs#L501

I'll add it to the gen6 editor.
