### ISSUE TITLE
feature request: disable pokemon database import export features

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1924]
Hi. I wanted to know if it would be possible to add a setting to the setting panel that would disable the pokemon database prompts when trying to load from folder or dump from boxes. I think it would be useful to have this feature for people like me who have way too many pokemon in the database to have the load from database option be useful. For me, if I do want to load from the pokemon database, I wil go to the database, find my pokemon with search criteria and export the results to the boxes. obviously this would be a setting in the setting panel so people who still want this feature enabled can have it.

**Comment by kwsch** [comment]
I'd rather not have way too many settings; it's only one dialog, you can always say no/escape every first dialog to skip it.
