### ISSUE TITLE
[Feature Request] Hovering Text box showing showdown set on mouse cursor when hovering a pokemon in the box

### ISSUE THREAD

**Issue by NuptupHHG** [kwsch/PKHeX#1925]
Hi, first time doing a request. I enjoy genning different sets and organizing my pokemon in tier order (smogon and VGC), However, one of the main drawbacks that I have found is that in order to identify a pokemon from one set to another apart from their items is to right click and check the selected pokemon info (which can be a slow process in pokemon that have LOTS of sets like Landorus, scizor, greninja, clef, etc). Which led me here.

I want to formally request (if possible) to add a hovering text box showing the showdown set in the following format: 

(example)

```
Greninja @ Choice Scarf
Ability: Protean
EVs: 176 Atk / 80 SpA / 252 Spe
Naive Nature
- Rock Slide
- U-turn
- Ice Beam
- Spikes
```

whenever I place my mouse cursor on top of any pokemon inside a box. That way it will be easier to identify and discern between pokemon that have similar sets, ev spreads, etc. Just a quality of life thing.If it is too hard to implement, maybe an add-on or extension that would allow to create a pop up whenever I click a pokemon so it shows its showdown set in text form or in read only form.

I want to thank you for creating this amazing tool which has helped a lot of ppl (including myself) to create new pokemon in the main games and such as well as finding enjoyment in the game both casually and competitive by streamlining the process of creating pokemon and avoiding hassles in both breeding and trading and chaining, etc. Congratulations from my behalf, really appreciate it!

**Comment by kwsch** [comment]
Implemented; hold Control & Shift when moving your mouse into the pkm's sprite area.

**Comment by architdate** [comment]
@kwsch maybe a settings toggle would be better? That way keys wont have to held all the time :)
