### ISSUE TITLE
[Bug] Regarding Showdown Data Previews

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1926]
I don't know how to perfectly explain this, but i'll try my best, once i press Ctrl + Shift, it seems that the flag is permanently set for that slot offset as i can hover over pokemon after that even without holding the key combination and it still previews the set. If i hover over a slot where i have not hovered over before, no set is shown even if there is a pokemon in that slot

However that is not all, turns out that the slot manager latches onto the box offset where the key combo was pressed. Because of this, a pokemon in the same slot index, but different box offset (different box) will show the exact same set as the previous box! take a look at the images below for reference

![image](https://user-images.githubusercontent.com/17220860/39665491-e90f9600-50c7-11e8-90b3-347756533bb2.png)
This is box 1

![image](https://user-images.githubusercontent.com/17220860/39665497-f868d206-50c7-11e8-910d-d16560724032.png)
This is box 2
(Also to note, im not holding the key combo atall for these, i just held it once while glancing over the box 1 pokemon and they control key flag seems to be set to true ever since!)

**Comment by sora10pls** [comment]
Also able to replicate this, though it works with any range of Boxes (my Raticate is in Box 1)
![image](https://user-images.githubusercontent.com/17801814/39666891-f0f6baa0-5078-11e8-98c3-e3167c390ad4.png)
