### ISSUE TITLE
Arceus forme legality oversight (might not be)

### ISSUE THREAD

**Issue by DaWoblefet** [kwsch/PKHeX#1928]
In Generation VII, it is possible via a glitch to maintain the forme aesthetics of any Arceus Forme while retaining Normal-type. This is done by trading an Arceus holding a Z-crystal; the Z-crystal is removed and the typing is updated, but the forme appearance remains the same. PKHeX currently flags such Arceus as illegal (see attached). I'm not certain of what the policy of counting glitched things as legit is, but this Arceus notably isn't legal in online communications. Just thought I'd pass it along. The legality check message is: "Invalid. Held Item does not match Form."

[493-07 - Arceus - FFF036C86521.zip](https://github.com/kwsch/PKHeX/files/1977831/493-07.-.Arceus.-.FFF036C86521.zip)

**Comment by kwsch** [comment]
>via a glitch
>typing is updated

does not compute; pkm types are derived from the current species & form. Can't change type without changing forme.
