### ISSUE TITLE
feature request (multiple databases)

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1942]
Hey I was just wondering if it would be possible to have a feature that lets us have multiple pokemon databases. even just 2 would be great. I think that this could be very helpful for people like me who want to have a separate database for my living dex vs my normal random pokemon database or something like that. I think it could be pretty helpful beyond that but that is just an example. I guess how it would work is that you could have your first pokemon database (pkmdb) and then maybe you could just add more folders next to pkmdb like (pkmbd 2)etc. Then in the database itself, when you go to tools, and search settings, "search within database" could be changed to "search within database 1" and the other databases you have would come below that "search within database 2" etc, allowing you to check off what databases should be searched. Hopefully you will maybe consider it. Thanks.

**Comment by kwsch** [comment]
* Users already can manually manage folders within pkmdb; the database loads all folders & files within
* Users can use IdentifierContains in the advanced search to search specific folders (use the folder name, for example).
