### ISSUE TITLE
[Bug] Cries do not play if save is opened with file association

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1943]
To replicate:

- Open a save file via right-click -> open with -> PKHeX
or
- Associate a `.sav`, `.bak`, `.dsv`, etc file with PKHeX and double-click to open it

Cries from the `sounds` folder aren't played unless PKHeX is opened, *then* the save file is.

**Comment by kwsch** [comment]
Probably the working directory deal again.

https://github.com/kwsch/PKHeX/blob/c10b01dc83cc9dc43150fd52caef6b6c293d8eed/PKHeX.WinForms/MainWindow/Main.cs#L91-L96

just need to add a similar string property here, then reference it in the playcry method.
