### ISSUE TITLE
[Bug] Plugin Loader

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1945]
Been playing around with this, and seems that the plugin loader throws an exception in ILMerged builds. Attached is the exception dump for viewing
[dump.txt](https://github.com/kwsch/PKHeX/files/2003324/dump.txt)

**Comment by architdate** [comment]
Oh for reference, `ExportQRCodes.dll` is the plugin that I am trying to load (Loads perfectly with an unmerged build for both Debug and Release environments)

**Comment by kwsch** [comment]
Is it using the latest commit that I just sync'd?

**Comment by architdate** [comment]
yeap latest commit

**Comment by architdate** [comment]
To rephrase, your latest commit doesn't throw an exception, but it just doesnt load the plugin as the exception handling causes the plugin to just not load. However if the exception were to be written to the console, the same exception is viewed

**Comment by architdate** [comment]
Also for debugging purposes, here is the [ExportQRCodes.dll](https://github.com/kwsch/PKHeX/files/2003334/ExportQRCodes.zip) plugin file.
Functionality is to dump qrcode png files of every pkm in `CurrentBox` into a folder called `qrcodes` in the same directory as PKHeX

**Comment by kwsch** [comment]
https://stackoverflow.com/a/21770848
;)

**Comment by architdate** [comment]
Ah I am not home to try this solution, but it makes sense.

However since most plugin files which will be downloaded by end-users, will be compiled on different computers, maybe the app.config file should enable `loadFromRemoteSources`

[Also it appears that the issue occurs even when pkhex isn't compiled on the same system (even if the plug-in is compiled on the same system). That's because in my case I compiled the plug-in on my pc, but used the merged build of my mod+pkhex via appveyor]

**Comment by architdate** [comment]
So I'm assuming the same issue will occur when someone downloads the release build from projectpokemon, and plugins from repos elsewhere

**Comment by architdate** [comment]
Seems that the issue still occurs with merged releases. (Used the teamcity merged build from this repo) Doesn't occur with unmerged ones due to `loadFromRemoteSources`
File to test: 
[AutoLegalityMod.dll](https://github.com/kwsch/PKHeX/files/2148485/AutoLegalityMod.zip)
If loaded correctly should display this:

![image](https://user-images.githubusercontent.com/17220860/42082297-339fd4f6-7bba-11e8-98f0-ed5899c8bf0e.png)
