### ISSUE TITLE
possible error with ctrl + shift

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1946]
Hi. Im not sure if this is just how you set it up or if it is an error, but when I try the ctrl + shift key combo, it sorts the boxes in reverse pokedex order instead of forwards. I know we are supposed to use the right click menu now but it is still helpful to just quickly use the key combo to sort.

**Comment by sora10pls** [comment]
Alt + Click = Clear Box
CTRL + Click = Sort Box

Have you tried just CTRL instead of CTRL-Shift?

https://github.com/kwsch/PKHeX/blob/4a20710a9694b9518e459caf3293e33dc59f1231/PKHeX.WinForms/Controls/SAV%20Editor/SAVEditor.cs#L383-L387

**Comment by NinFanBoyFTW** [comment]
Yeah. When I use       CTRL + Click = Sort Box      it sorts the current box, but with reverse pokedex order. When I use           CTRL + Shift + Click = Sort all Boxes     It sorts all boxes but with reverse pokedex order. I was just wondering if this was a mistake now or if there is a reason for this change.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/4a20710a9694b9518e459caf3293e33dc59f1231/PKHeX.WinForms/Controls/SAV%20Editor/Sorter.cs#L79-L86

ctrl is the reverse option for individual sort options; I guess I could replace the 386 line with a direct call to sort
