### ISSUE TITLE
[Bug] Alternate Form cries do not play

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1947]
As the issue title says; used to work a few days ago and now it doesn't. Tested with various cases:

- `25-7.wav`
- `718-1.wav`
- `718-4.wav`
- `800-3.wav`

Probably a side effect of https://github.com/kwsch/PKHeX/commit/663ec5c5366b8ed65bfb43e8cfce94d457222b28.

**Comment by kwsch** [comment]
It's a side effect of https://github.com/kwsch/PKHeX/commit/bbdb94007ec6cd7509bd196220945f4dd0e85a8f

The altform case should be checked first not second :P
