### ISSUE TITLE
Issue with Japanese OT Name Rating

### ISSUE THREAD

**Issue by WEERSOQUEER** [kwsch/PKHeX#1949]
So as you know, the gen 1 and 2 Name Raters will not acknowledge that a Pokemon is yours by just OT and TID alone but also by OT terminator sequence. And for these games in Japanese, the program needs to inject the **full 6 bytes** when clicking the OT label on the Pokemon's editing tab as shown here:
gen 1
![blue jap](https://user-images.githubusercontent.com/36747884/40138056-d7baba1a-5919-11e8-8535-15169708da9f.jpg)
gen 2
![gold jap](https://user-images.githubusercontent.com/36747884/40138088-eb15cb04-5919-11e8-901f-ab92ab2c230f.jpg)

**Comment by kwsch** [comment]
Does the program not already do this?

https://github.com/kwsch/PKHeX/commit/f9002c6cc99723e59985c9297e13ae00f610c17e
https://github.com/kwsch/PKHeX/blob/e818a587ff84a5da492a42367b7eecdd99abca79/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L335-L337
