### ISSUE TITLE
Future Update: Move Pokemon or Boxes to Another

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#195]
I don't know if there is a move option for Pokemon, but I wonder if I can move a Pokemon from one box to another easily. Like selecting a Pokemon and dragging it to a another box with the << >> arrows. Or an entire box, and say "Move to" any box in storage. If the new location already has Pokemon, it should say, "Are you sure you want to overwrite?" I don't know if this was already added because I can't find it. 

If there is no option, is it possible to add one to your next update?

**Comment by evandixon** [comment]
I don't know if it's a thing or not, but if it's not, I would request having two boxes open to allow dragging between them.  (That of course would be the harder thing to implement.)

For now (if this isn't already a feature), you'll just have to "view", change boxes, and "set".

**Comment by kwsch** [comment]
I'm also siding in favor of having a popout box that is a secondary form to drag between.

**Comment by ricksee** [comment]
I understand and thanks for listening to my question/suggestion. I just thought it would be easier to move Pokemon. Probably adding an option to select multiple Pokemon to move with Ctrl + Click and move them. 

Finally, I hope it can be possible to select multiple Pokemon from the boxes or an entire box and export them to the clipboard.

**Comment by kwsch** [comment]
Control+Click is already taken by quick-set.
Exporting an entire box can be done via Tools->Data->Dump Boxes

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/4ea349df118ee8b99e0414a3abfd5dabb6b0d3c1
Implemented box viewer popup window in the latest commit.

**Comment by ricksee** [comment]
No I mean like selecting certain Pokemon, such as Gengar or Hoppa at the same time.

**Comment by SciresM** [comment]
I don't really think there's any good way to design a sensible UI for that with the way PKHeX works right now. I'd be against it.
