### ISSUE TITLE
Platinum minor save corruption

### ISSUE THREAD

**Issue by gentlecolts** [kwsch/PKHeX#1950]
Pkhex Version: 20180417 (note: says 18 on the folder, 17 in the title bar)
Platinum environment: english rom dump played on a jpn n3ds via twloader

Upon clicking save from the "misc edits" menu, the currently available poketch apps will be shifted back one (ex, if app 2 is checked and app 3 is not, clicking save will render app 1 checked and app 2 not checked).  Additionally, the currently selected app is also saved incorrectly.

Discovery:
I had been making unrelated edits and had saved my changes.  Upon loading my game, I noticed that my poketch was no longer displaying at all.  I had initially thought to simply reset the currently selected app back to 1, and did so.  This resulted in the game displaying a "save corrupted" message next time I reloaded, however it seemed to load fine.  However, my available poketch apps were incorrect, leading me to discover the issue with shifting.

tangent: requesting means of editing gen4 contest items/pokeball stickers, unless that's already in and I completely missed it

**Comment by kwsch** [comment]
Fixed a few days ago:
https://projectpokemon.org/home/forums/topic/45236-bug-dpp-using-misc-edits-window-automatically-messes-with-poketch-data/

https://github.com/kwsch/PKHeX/commit/3ee6070b98be0a2a5b35786c8ff01ca954efbd21#diff-5d4ec1b9482c070a23d8e29e8cab9ece
https://github.com/kwsch/PKHeX/commit/4139299f00bca7259b6fe9e889c0b07afdf266ac#diff-5d4ec1b9482c070a23d8e29e8cab9ece
