### ISSUE TITLE
Showdown problems 

### ISSUE THREAD

**Issue by Andrew755** [kwsch/PKHeX#1951]
```
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.CommonEdits.ApplySetDetails(PKM pk, ShowdownSet Set)
   at PKHeX.WinForms.Controls.PKMEditor.LoadShowdownSetDefault(ShowdownSet Set)
   at PKHeX.WinForms.Main.ClickShowdownImportPKM(Object sender, EventArgs e)
```

**Comment by architdate** [comment]
What set were you trying to import?

**Comment by Andrew755** [comment]
Lilligant @ Life Orb
Ability: Chlorophyll
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
- Quiver Dance
- Sleep Powder
- Giga Drain
- Hidden Power Fire

**Comment by Andrew755** [comment]
It worked yesterday but now i'm having lots of issues

**Comment by Andrew755** [comment]
Um let me try restarting my computer

**Comment by architdate** [comment]
Are you sure that you are importing it properly? `Tools > Showdown > Import Set from Clipboard`
```
Lilligant @ Life Orb
Ability: Chlorophyll
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
- Quiver Dance
- Sleep Powder
- Giga Drain
- Hidden Power Fire
```
formatting should be as such. Restarting the computer will likely not solve the issue

**Comment by Andrew755** [comment]
Yes

**Comment by Andrew755** [comment]
Do you have discord so we can screen share

**Comment by architdate** [comment]
Are you using the latest commit of the application? behavior should never change like this overnight

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1929

Please do not report issues from debug builds without checking if you are on the latest version of debug builds.
