### ISSUE TITLE
[Bug] Batch Editor Box/Slot Commands

### ISSUE THREAD

**Issue by Wanderer1391** [kwsch/PKHeX#1954]
In the latest commits the Box and Slot commands no longer work properly as rather then effect only the one box or slot specified they instead effect all the Pokemon in the PC Boxes.

![batch editor](https://user-images.githubusercontent.com/34255707/40285552-64191368-5c6b-11e8-9652-f7071fa70101.png)

I also have two feature requests if possible:
1. Would it be possible to add Poke Ball to showdown importing?
2. In a Gen 1/2 save file would it possible to have the showdown set preview bubble show the Nature a Pokemon would have on transferring to Gen 7 as it already shows the Pokemon having a Hardy Nature due to Gen 1/2 not having Natures.

![pokemon gold](https://user-images.githubusercontent.com/34255707/40285770-f91fc518-5c6d-11e8-807d-f4b63e3d0f3b.png)

**Comment by kwsch** [comment]
ShowdownSet doesn't specify ball; PKHeX makes limited modifications but some encounters may require something that isn't a pokeball.
