### ISSUE TITLE
ANSI Characters No Longer Displayed in PKHeX

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1960]
ANSI characters such as ★ do not display correctly in the OT or under "Trainer Name" in the "Trainer Info" settings.
![image](https://user-images.githubusercontent.com/15519892/40354097-16930ff6-5d81-11e8-9d73-d48fd5cb0d1d.png)

Thanks reading this and for all your work with PKHeX.

**Comment by kwsch** [comment]
Works fine for me.

![image](https://user-images.githubusercontent.com/6393368/40363500-996073e4-5d84-11e8-826e-874c6e88e273.png)
