### ISSUE TITLE
Gen2 pokemon legality bug

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1962]
Hi,

I have found a strage legality bug with some pokemon on 1 crystal save I found on the internet, I have checked the save file both on the latest stable version of PKHeX (20180417) and on the latest build (d-20180524 or a25c6a4)

The stable version shows them up fine (legal shown as legal and illegal as illegal)
The latest commit (build with visual studio) shows some illegal pokemon as legal and some illegal as legal with various errors

If I try to set the "legal pokemon" into the "illegal" one it turns legal inside the box
Also some of them have gen 7 location (in the stable version 20180417 it is shown correctly)
When I hold ctrl and right click the pokemon inside the box the lagality check works for the latest commit

My english is not so good so I will post some pics as an example and give you the save file with these pokemon show in the pictures to examine it

Thank you for the program and all the hard work you put into it!

**Save File:**
[PCNYCrystal.zip](https://github.com/kwsch/PKHeX/files/2036530/PCNYCrystal.zip)

**Photos:** 
![2018-05-24](https://user-images.githubusercontent.com/20145301/40502341-54d48d1c-5f93-11e8-8586-96e55d357f93.png)

![2018-05-24 1](https://user-images.githubusercontent.com/20145301/40502758-9e0ef340-5f94-11e8-8b63-186f1e778723.png)

![2018-05-24 2](https://user-images.githubusercontent.com/20145301/40502764-a57bdc6a-5f94-11e8-8e47-116ed90ec6a7.png)

![2018-05-24 3](https://user-images.githubusercontent.com/20145301/40502770-afc55386-5f94-11e8-8a94-2a8008fcd800.png)

![2018-05-24 4](https://user-images.githubusercontent.com/20145301/40502791-bd68457a-5f94-11e8-80e6-2008c41828f7.png)

**Comment by kwsch** [comment]
Likely a result of https://github.com/kwsch/PKHeX/pull/1957

**Comment by PrometheusG** [comment]
I am sorry, I didn't see that, thank you :-)
You can close it
