### ISSUE TITLE
pokemon gen 2 location error.

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1963]
Hey I saw a few different issues related to this but now I see another. When I go into any gen 2 game, the location options are all gen 7 options. The gen 2 locations are missing. Also when I try to use the batch editor on it, it corresponds to the gen 7 location index (or at least I think it does)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1962
