### ISSUE TITLE
issue with PKHaX

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1964]
Hey. Whenever I try to load a gen 1-4 save with PKHaX, I get the message "unable to set to this slot". In addition to this, on gen 3, It doesnt give me all of the hax options once I get past that message. (some of the other gens let me do certain hax even after that message)

**Comment by kwsch** [comment]
Unable to replicate.

**Comment by NinFanBoyFTW** [comment]
I'm not sure. Sometimes it happens when I drag the save onto pkhax. A few times  it was happening when I would click open then navigate to the save directly.

Either way there is also the issue with gen 3 abilities not showing up

**Comment by kwsch** [comment]
Gen3 format does not store the ability ID, rather it uses a bit from the PID to determine which ability to use (0 or 1). There's no way to force an illegal ability for gen3 by editing the save file -- you'd have to edit the ROM.

**Comment by kwsch** [comment]
The "Unable to set to this slot" pops up because you're dragging the save file into a box slot; the save file ends up being loaded anyway but the program notifies you it can't load the file to that individual slot.

**Comment by NinFanBoyFTW** [comment]
Ok thanks.
