### ISSUE TITLE
question about the batch editor

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1966]
Hi. I'm not sure if this is an error or maybe a feature request, but when I try to use "$suggest" on the batch editor for a specific move "1, 2, 3, or 4" it doesn't work. It does work for the "Moves" variable but I just wanted to know if it was possible to use it for an individual move. Thanks

Edit: this also relates to the relearn moves variables.

**Comment by kwsch** [comment]
It's only for special handled cases.

https://github.com/kwsch/PKHeX/blob/05e10860ed9e89c4d8ebb990527104cfe8db3350/PKHeX.Core/Editing/Bulk/BatchEditing.cs#L344-L376
