### ISSUE TITLE
All the Gen2GBEvents can‘t be legel

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#1968]
All the Gen2GBEvents can‘t be legel

![image](https://user-images.githubusercontent.com/39662364/40582015-f1e70a54-619a-11e8-805c-03cae6eab9d5.png)

https://projectpokemon.org/home/files/file/1845-classic-pcny-splash-sunkern/

**Comment by kwsch** [comment]
PKHeX does not have data for the GCEA PCNY event pkm for gen 2.

https://bulbapedia.bulbagarden.net/wiki/List_of_Gotta_Catch_%27Em_All_event_Pokémon

https://github.com/kwsch/PKHeX/blob/e6765d36913edfe865217a910b4c447decb46e6e/PKHeX.Core/Legality/Encounters/Data/Encounters2.cs

I'm not interested in adding these myself (>100 different events?) so I don't consider this an issue with the scope of the program.
