### ISSUE TITLE
Correlate Game With Met Location Based on Game Itself

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#197]
Is it possible in the future to correlate met location of the Pokemon to the game that it can be in instead of just generation. For instance, if selecting AS as a game location, it should have all possible locations to that game alone instead of having other locations such as Anistar City.

**Comment by kwsch** [comment]
I'd rather not prevent the user from having whatever met location they want; the legality checker picks up on illegal properties, including invalid Met/Egg locations.

**Comment by ricksee** [comment]
I don't know I thought it would be easier to do so because it can be a hassle trying to find the a place that exist in the game. Well not too hard to find, but it could be one less burden for the editor at least.

**Comment by torin555** [comment]
I'd like to second something like this. Maybe at least by having the valid game locations all listed at the top? It would make genning mons much faster.
