### ISSUE TITLE
Bug: Analysis not available

### ISSUE THREAD

**Issue by netraagal** [kwsch/PKHeX#1971]
Hi,

I get this message when want to verify some creations... Appends when I create a Gen4 pokemon on a Gen5 file.

![image](https://user-images.githubusercontent.com/35922864/40587593-874e5f62-61d1-11e8-84cf-39694f0ee5fa.png)

Issue <a href="https://github.com/kwsch/PKHeX/issues/1238">#1238</a> mentionned it.

**Comment by wwwwwwzx** [comment]
![screen shot 2018-05-27 at 15 51 59](https://user-images.githubusercontent.com/14868500/40591422-f98ac6d0-61c5-11e8-8a69-1935cb28f722.png)
Not sure if it's this issue: It happens when you are editing from the default pokemon after loading a past gen save. Origin game version is blank.

**Comment by netraagal** [comment]
Thanks, I will considere that for next time :)
