### ISSUE TITLE
PKHeX pkmdb possible issue

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1973]
I noticed that PKHeX (both latest stable version and latest commits) read pokemon not only from the /pkmdb folder but from the /bak folder as welll

The save I loaded automatically created a file in the /bak folder so the pokemon that appear in the database are from that .bak file in the /bak folder.

The last 2 pokemon (chansey, rayquaza) are from the /pkmdb folder, I put them myself. If I delete the /bak folder only these 2 pokemon appear in the database (chansey,rayquaza).

If I create a /pkmdb folder and leave it empty then the pokemon that appear in the database are from the .bak save file. 
If more .bak save files are created, the database grows

Is this normal? if yes, please close and ignore this issue, thank you

![2018-05-28](https://user-images.githubusercontent.com/20145301/40605169-1b95aac0-626a-11e8-9fdd-51f6837011cb.png)

**Comment by sora10pls** [comment]
Tools -> Search Settings -> Uncheck "Search Within Boxes"

**Comment by PrometheusG** [comment]
This solution partly works. If I unckeck the "Search Within Boxes" then the pokemon that are in the /bak folder do not appear (which is good) but it also causes the pokemon that are inside folders inside the /pkmdb folder to not appear too

**Comment by kwsch** [comment]
Working as intended. If you want extra filtering, use the advanced search and "IdentifierContains".

**Comment by PrometheusG** [comment]
thank you both for the explanations!
