### ISSUE TITLE
Gen 3 Marine Ribbon -> Battle Champion Ribbon

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1975]
@stgiga noted to me that the Marine Ribbon (2003 Regional Tourney Champion Ribbon) gets converted to the `Battle Champion Ribbon` in Gen V. While very few people were awarded this ribbon, it is legal nonetheless.

I recommend instead of flagging the marine ribbon in gen3 (or gen 4 with gen 3 game origin) as illegal, it should be flagged as fishy. Same with the battle champion ribbon in gen 5 with gen 3 game origin.

**Comment by kwsch** [comment]
Can't have it as Fishy

* not all species can obtain the ribbon (regional banlist is...?); are there any further restrictions?
* `RibbonVerifier` only spits out a list of invalid ribbon name-messages (not `CheckResult` objects which contain the `Severity` rating that can be `Severity.Fishy`). Can always add another method to spit out Fishy-but-Legal ribbons.

**Comment by kamronbatman** [comment]
The ribbon was definitely given out for the 2003 regional tournaments. I was told by HaxAras that there is video proof. There was no definitive ban list except for Jirachi during that year. Whether or not mew or other legionaries were banned is unknown.

**Comment by kamronbatman** [comment]
So here is some more info:
2003 - Marine Ribbon given out - Only Hoenn Pokedex pokemon allowed. No Jirachi. - All pokemon must have game origin of Ruby or Sapphire.

2004 - Country/World Ribbons given out - All pokemon allowed except: Dragonite, Mewtwo, Mew, Tyranitar, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys (all forms). - Pokemon may not have game origin of Emerald.

2005 - Country/World Ribbons Given Out - All pokemon allowed except: Mewtwo, Mew, Lugia, Ho-Oh, Celebi, Kyogre, Groudon, Rayquaza, Jirachi, and Deoxys (all forms). (Note that dragonite and Tyranitar are allowed). - Any gen 3 origin.

2006 - ??? Ribbons - All Pokemon allowed except: Mew, Celebi, Jirachi, and Deoxys (all forms).

You can ignore 2004 since 2005 encompasses it for legality. I am just listing it for completeness.

**Comment by kamronbatman** [comment]
I forgot to mention that for 2003, all event pokes should be marked illegal with that ribbon except for 5th anniv eggs.

**Comment by kwsch** [comment]
Better to flag as illegal, it's too much of an effort for little gain. There's no surface indication for anything fishy; more often than not, the ribbon is not going to be legitimate.
