### ISSUE TITLE
[Bug] Batch Editor

### ISSUE THREAD

**Issue by Wanderer1391** [kwsch/PKHeX#1977]
In the latest commits and I made sure to compile e82dcdb to check, the box and slot commands are once again not working correctly as in #1954:
![batch editor](https://user-images.githubusercontent.com/34255707/40815920-d786ff0e-6517-11e8-95d8-0d49b410ad67.png)
![batch editor 2](https://user-images.githubusercontent.com/34255707/40815924-dee8fd9c-6517-11e8-9963-42fb2d231725.png)

A question on a side note, will PKHeX need any specific updates for loading saves from the Gold/Silver beta versions if its even possible to save in those versions?

**Comment by kwsch** [comment]
PKHeX won't support the beta versions due to the amount of differences from the retail games.
