### ISSUE TITLE
G3 save event egg

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#1978]
![image](https://user-images.githubusercontent.com/39662364/40869776-2faad57a-6653-11e8-95c0-539c2253226d.png)

![image](https://user-images.githubusercontent.com/39662364/40869782-5b21beda-6653-11e8-9801-2ce2c20aca36.png)

![image](https://user-images.githubusercontent.com/39662364/40869789-7190a122-6653-11e8-8f3c-47b7f4f6e6d4.png)

move to G4 game save
![image](https://user-images.githubusercontent.com/39662364/40869798-a9b49aa4-6653-11e8-9f79-34b0659a6d5e.png)

**Comment by PrometheusG** [comment]
Sorry to bump a closed thread but it is somehow relevant,

tested with the latest release and the latest commit, When you hatch a gen 3 egg, the language of the nickname is still shown as jpn in PKHeX and does not take the game's language nickname (the egg has a jpn nickname but when hatched it should change to an english or any other language nickname the cartridge is. 

(In-game the nickname changes normally, in PKHeX when you right click the box to hatch the egg the nickname is still in JPN )

Thank you and sorry for the bump

**Comment by kwsch** [comment]
@PrometheusG Gen3 save files do not indicate the language of the save file; it's set by the ROM data when you hatch. Can't really do anything about it.
