### ISSUE TITLE
TID/SID Issue

### ISSUE THREAD

**Issue by xXAquaNightXx** [kwsch/PKHeX#1980]
TID shown in pkhex and the ones output by data report are not the same also the ones shown in pkhex are wrong.

This is the box data output for this pokemon:

![output](https://user-images.githubusercontent.com/24309423/40985970-25e41c4c-68b3-11e8-839f-47b01c337c5c.png)

And this is the pokemon in pkhex the TID shown is MY TID although this pokemon was not caught by me:
 
![pkmn](https://user-images.githubusercontent.com/24309423/40985996-33016d8a-68b3-11e8-990a-7bed5b5c40d7.png)

This is the box data output of a pokemon hatched by me:

![out12](https://user-images.githubusercontent.com/24309423/40987057-ace21dbe-68b5-11e8-893b-e3dc53890dc4.png)

**Comment by kwsch** [comment]
The report grid shows the 16bit style of TIDs while the editor shows the ingame representation of data (gen7+ show 6digit ID, others show 16bit).

https://github.com/kwsch/PKHeX/blob/a5af7a443b9cd21ea398d2e257768d0756addd01/PKHeX.WinForms/Subforms/ReportGrid.cs#L93-L94

I assume you're referring to the Box Report Grid?
https://github.com/kwsch/PKHeX/blob/a5af7a443b9cd21ea398d2e257768d0756addd01/PKHeX.WinForms/Subforms/ReportGrid.cs#L93-L94

**Comment by xXAquaNightXx** [comment]
Yea but the original TID for this pokemon was 54442 and pkhex converted it to 626474 which is MY current TID.

**Comment by kwsch** [comment]
PKHeX doesn't convert any values. The editor used to display the 16 bit value but was recently changed so that it matches the ingame representation. The value saves to the same data either way; the values are equivalent.

It's like feet vs meters, different scale but same type of measurement.

**Comment by xXAquaNightXx** [comment]
But why is it displaying my gen7 TID for a pokemon that was never caught by me?

**Comment by kwsch** [comment]
Because it's the same.

(46487 << 16 | 54442) = 3046626474
(3046)626474

**Comment by xXAquaNightXx** [comment]
That makes sense now... thank you!
