### ISSUE TITLE
Legality issue from last version to new version 6/1 + Small Gender display issues.

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#1982]
So from the last build to this new build I noticed this issue with hypno and other older generation pokemon who are changed to future generations. It will give me the error "Invalid: OT Memory: Invalid Feeling." If I try to change the feeling and check legality nothing fixes this and it doesn't save the new feeling , if I click view on memories and look at feeling it stays the same as before.

[097 ★ - Hypno - A614999645BC.zip](https://github.com/kwsch/PKHeX/files/2077592/097.-.Hypno.-.A614999645BC.zip)

Also could, if you haven't already could you add a way for .Gender to not change the gender of genderless Pokemon, and 100% genderlocked pokemon?  I know the new version has an error message for when pokemon are impossible genders now but I don't think it's really necessary when you can just add a way to lock the gender of certain pokemon.

Jynx's error message for gender reads: "Genderless Pokemon should not have a gender" and if you switch Mewostic's form between male and female, the gender icon between PID and "reroll" will be the right gender but the wrong color, just minor graphic error haha.

**Comment by kwsch** [comment]
1. Old versions of the program added invalid memory feelings (faked Bank transfer). New legality checks highlight incorrect feelings/intensities.

2. The batch editor is very brute-force oriented, it sets the properties exactly as you say. Filter out genderless via `!Gender=2` first, and you can always revert fixed gender pkm by excluding Legal when setting to the other gender.

3. Some flag messages are slightly incoherent; it's preferred this way to reduce burden in string translations (less messages = quicker to translate, although only a couple languages have actually been translated). Reusing some strings which are slightly applicable (fixed gender should not have *this* gender).

I'll look into the coloration later :)

**Comment by ReZeroEmiria** [comment]
I  understand the new legality checks are more accurate. What I don't understand is why for example:

I change a feeling for a pokemon and it says "it was restless" then I save and "set" this pokemon to a slot in my box. After I do this, I view the set pokemon, go to memories and the feeling will be "it got teary eyed". So like the memory changes upon setting?

Also with a Pokemon I have changed from let's say Emerald Version Origin to Omega Ruby Origin, I change the feeling to match a legitimate Pokemon and it marks it as an error, but if I export its moveset and import the moveset onto a pokemon with a legitimate Omega Ruby Feeling then the Pokemon will be legit.

Also, I think someone else brought this up but if you change genders to male of all Pokemon, then Female form meowstic still appears incorrectly as legal. Other Pokemon from what I've seen such as Latias will flag the error though.

One question by the way, the new Gen 7 Trainer information format for the Pokemon, why is the SID 4 digits? I thought G7TID was calculated with the older TID/SID, where does this new SID come from ?

**Comment by architdate** [comment]
The new SID comes from the first 4 digits of the transformation
`(SID << 16 | TID)` is the transformation. The first 4 digits become the G7SID and the remaining 6 digits become the G7TID

**Comment by kwsch** [comment]
Whenever you set the save file, PKHeX automatically applies memories as if you just transferred from bank (the pkmeditor) to the save file. There's a setting to turn this off, but it should work correctly (ie no need to disable, it fixes common user problems).

Meowstic was handled yesterday (form must equal gender now).
