### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1983]
Wondering if it's possible to add an ability description on mouse over similar to the nature description, maybe also a description mouse over for items also?

**Comment by kwsch** [comment]
That would require adding in string localization data for every language across multiple generations (items can be removed between gens). Nature can rely on the GUI strings for IV/EV/Stats to indicate the stats being amped, so no resources are needed.

Simple data lookup can be done by the user externally... it's a little too much bloat imo.

* Ability Description (text)
* Item Description (text)
* Move Description (text)
* Species Types (types)
* Move data (power, type, category)
