### ISSUE TITLE
Gen 6, Egg-Relearn Moves error

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#1987]
Hi,

Testing with the latest commint, I have found this error with some hatched pokemon and their egg/relearn moves : 

- This tyrogue is a gift from a frined that has hatched it himself and has no access to PKHeX, it is an unedited pokemon:
[236 - Tyrogue - 88A5A8BF7345.zip](https://github.com/kwsch/PKHeX/files/2087600/236.-.Tyrogue.-.88A5A8BF7345.zip)

![2018-06-10 1](https://user-images.githubusercontent.com/20145301/41199071-1fd4e194-6c94-11e8-9c92-4aa0190a7818.png)

- This is a Tropius I hatched myself after I got it from an ESV giveaway, unedited:
[357 ★ - Walker Mower - 0272CF40335F.zip](https://github.com/kwsch/PKHeX/files/2087601/357.-.Walker.Mower.-.0272CF40335F.zip)

![2018-06-10 2](https://user-images.githubusercontent.com/20145301/41199085-5d2c4690-6c94-11e8-9b82-400e7e3db14d.png)

If I change the order of Tyrogue's Relearn Moves (Mach Punch to Slot 4 and Helping Hand to Slot 2) it becomes legit again. Same thing happen with Tropius (Leaf Storm in Slot 1 and Growth in Slot 4)

Thank you very much!

**Comment by kwsch** [comment]
Suspect change:
https://github.com/kwsch/PKHeX/commit/021ac7c54f7cb86d9a311ad11819a62bea7ce8da#diff-7eb7ef97a67243d17ac83521595b7c03R174
