### ISSUE TITLE
 In the right order?

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#1994]
![image](https://user-images.githubusercontent.com/39662364/41238977-e947e57c-6dc9-11e8-99ff-61270cfa4bfc.png)

![image](https://user-images.githubusercontent.com/39662364/41238765-503496f0-6dc9-11e8-8d71-9a62c5e65f49.png)

![image](https://user-images.githubusercontent.com/39662364/41238886-a7955c5e-6dc9-11e8-8053-e3c37fbc1386.png)

**Comment by kwsch** [comment]
As far as the overall ordering, the base moves are applied first then inherited moves are applied; if the parents moves are in a different order (not 1234) it'll yield a different order for the eggs since the game does not check if the egg already has the inherited move.
