### ISSUE TITLE
Pokemon emerald (and other gen 3 event flags)

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1996]
Hey I'm not sure if you just need people people like me to find the event flags in the gen 3 games, or if there is another reason why you don't have many of them (legendaries, etc) but I recently started a new emerald game and I have started to find some of the event flags. 

For rayquaza, the flag 0080 is set after battling (Which means when it is unset rayquaza reappears)

Please let me know if you want me to keep finding the event flags or if there is another reason you haven't implemented them. Thanks

**Comment by kwsch** [comment]
There's also another flag (0x1C0) which is also set after battle.

https://github.com/pret/pokeemerald/blob/eb65458b67412cc4fc01eb3a4fb1c37d88829b54/data/scripts/maps/SkyPillar_Top.inc#L31-L68

Event flags can be added via a pull request containing modifications to this file:
https://github.com/kwsch/PKHeX/blob/4778c9c75883bab5fb07a499cec5e8c17340bdf9/PKHeX.Core/Resources/text/script/flags_e_en.txt

**Comment by NinFanBoyFTW** [comment]
Yeah I saw that but when I did a test where I only unset that first flag, rayquaza was still battlable so I wasnt sure if the second one had to do with the rayquaza battle or not. Either way, I'm not really good with that stuff so I guess Ill just leave it for now. Thanks
