### ISSUE TITLE
Can the Date of the Egg Made the Program Overwrite When it Is Hatched In Game?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#200]
I don't know if this is a problem or not, whenever one creates an egg in the editor and puts in a hatched date. especially one that is earlier or later than when it is actually hatched.  For instance an egg of a level 100 Pokemon was made in January but the current date is December. However, when it hatches it uses the current date by the game/system. Can it avoid being overwritten by the game/system time?

**Comment by kwsch** [comment]
No.

Both dates may be overwritten (Egg=trade as egg, Met=hatch egg)
