### ISSUE TITLE
G1 suggest moves

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2000]
![image](https://user-images.githubusercontent.com/39662364/41324669-6c4b54da-6ee8-11e8-9090-0aebe8673194.png)
![image](https://user-images.githubusercontent.com/39662364/41294425-9f1dab1e-6e8a-11e8-94fe-cc2aaa6d75a6.png)
![image](https://user-images.githubusercontent.com/39662364/41294459-acf3e6cc-6e8a-11e8-9702-44a2524d9b42.png)
![image](https://user-images.githubusercontent.com/39662364/41294472-b3a8d900-6e8a-11e8-9ebb-779876e71eba.png)
![image](https://user-images.githubusercontent.com/39662364/41294490-bb4a1714-6e8a-11e8-9a4e-54bd9b44acc4.png)
![image](https://user-images.githubusercontent.com/39662364/41294501-c164a6b4-6e8a-11e8-9f4a-d3d9172113f9.png)
![image](https://user-images.githubusercontent.com/39662364/41294518-cd6da316-6e8a-11e8-8048-3cb34d536315.png)
Some Pokemon...

![image](https://user-images.githubusercontent.com/39662364/41294665-2d8ab068-6e8b-11e8-80b4-e9bf0bfa98ed.png)

**Comment by kwsch** [comment]
Likely need special consideration for pk1 format similar to the encounter->pkm generating:
https://github.com/kwsch/PKHeX/blob/5ad8a4e5a43b65921db05f08186e46f8f6d32de0/PKHeX.Core/Legality/Encounters/EncounterSlot.cs#L136-L138

**Comment by iiippppk** [comment]
![image](https://user-images.githubusercontent.com/39662364/41324695-98b519ac-6ee8-11e8-9517-7feddd7deb82.png)
![image](https://user-images.githubusercontent.com/39662364/41324700-a3c7e996-6ee8-11e8-8744-204bbfe8add1.png)
