### ISSUE TITLE
CXD PID-IVs

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2003]
![image](https://user-images.githubusercontent.com/39662364/41393533-d82a1772-6fd8-11e8-992b-f2336fe99bf7.png)
![image](https://user-images.githubusercontent.com/39662364/41393492-a9c37978-6fd8-11e8-9d66-cdc34af2a10e.png)
![image](https://user-images.githubusercontent.com/39662364/41393502-b62ee81e-6fd8-11e8-92b0-92d8a08ae36e.png)
![image](https://user-images.githubusercontent.com/39662364/41393524-d0728db6-6fd8-11e8-99c1-963c0c7a7d3d.png)

CXD
PID - CBF595E2
IVs - 10 24 28 6 1 16  or  0 14 31 30 17 15
Legel
Not only one IVs?
[CXD Kangaskhan.zip](https://github.com/kwsch/PKHeX/files/2100959/CXD.Kangaskhan.zip)

**Comment by ijuintekka** [comment]
The same PID can be reached in different ways. The first is the result of a PID re-roll on a shiny PID, which is forbidden on XD shadow pokemon, the second is a normal progression. Ironically, neither of these spreads are possible for Kangaskhan, so it is still illegal in both cases.

**Comment by kwsch** [comment]
Shadow PIDIV restrictions are not currently implemented :)
