### ISSUE TITLE
Problem making Shiny Kyogre and Groudon 

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#201]
i try to make a shiny kyogre and Groudon  and the message said is # **# Invaild: Encounter cannot be shiny** 
![gvdfvds](https://cloud.githubusercontent.com/assets/18640392/18000715/6a00b3e4-6b90-11e6-924a-9475ea8b9d8c.jpg)
![fevr4r](https://cloud.githubusercontent.com/assets/18640392/18006506/dba520be-6bb0-11e6-820e-267b729a7d69.jpg)
![g5grv](https://cloud.githubusercontent.com/assets/18640392/18006511/e17ef708-6bb0-11e6-80dd-5ed5af1132ff.jpg)
![rgrevre](https://cloud.githubusercontent.com/assets/18640392/18006512/e1a84216-6bb0-11e6-809a-1869c221f9af.jpg)

i check everything is fine but the Problem is i cannot make Shiny Kyogree  # **Invaild: Encounter cannot be shiny**
PLZ Fix this Issue PLZ 

**# ARIGATO**

**Comment by kwsch** [comment]
Nothing to fix, the storyline Kyogre is shiny locked.

**Comment by torin555** [comment]
If it says the encounter can't be shiny, that's because it can't.

**Comment by poutros** [comment]
You include a pic disproving your entire post? Shiny lock means the game makes it so that it will never be shiny legitimately if encoutered in that specific game.

**Comment by Orionsilver** [comment]
in the older PKHeX version making a Shiny Legendary was easy and now it is not fair

**Comment by kwsch** [comment]
PKHeX still lets you save the Pokémon even though it is not legal. You can always ignore PKHeX's legality warning.

**Comment by torin555** [comment]
Keep in mind your game card might get blacklisted from online play if you try to put it online.
