### ISSUE TITLE
problems with pokemon battle revolution and feature requests

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2010]
Hi. I was going onto my pokemon battle revolution save file and I noticed a couple of things that were off. I'm not sure if there is a reason for this, but the trainer info tab has no data in it even when a save is loaded onto battle revolution. It only shows default info as if it is a normal gen 4 game that hasn't been started. Then there is also an items tab which only seems to crash PKHeX so I'm not sure if that is needed. 

Onto the feature requests. These are obvious things but I just wanted to know if they would be possible or if they would need a lot of research. I was wondering if you would be able to add a misc edits section to the battle revolution saves that would have an option to unlock all colosseums and unlock all battle pass backgrounds (most important). I saw that there are gecko codes that allow you to do this so I would love to see this implemented some how in pkhex. I saw that some of the battle pass backgrounds are unobtainable in the non Japanese versions (unless you use a cheat like this one) and there are three backgrounds (the hoenn legendaries) which pretty much could only be obtained with the wfc feature which is now not available. I am hoping you are able to add these because I think it would be really great, and would really help the longevity of some of the extras in this game (since they arent really available now) Thanks again, and ill include the gecko codes I found. I have tested them and they worked for me on dolphin.
[battle revolution codes.txt](https://github.com/kwsch/PKHeX/files/2107990/battle.revolution.codes.txt)

Edit: I also found a code to give all trainer appearence items to the game so ill include that to just in case you want to look at all of these. Thanks

**Comment by kwsch** [comment]
Research requests aren't feature requests, if the exact byte changes are not documented they can't be easily integrated.

Research requests belong on the forums ;)
