### ISSUE TITLE
gen 4 showdown import error

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2012]
Hey, so I wass trying to import a showdown set from the gen 4 smogon page, and every time I try to import  the set, PKHeX freezes up and crashes with no error. Works fine on gen 5 and up

**Comment by kwsch** [comment]
Set details?

**Comment by NinFanBoyFTW** [comment]
any set that I try.

**Comment by kwsch** [comment]
In the future please try to be more descriptive; for example you could provide a set or test multiple savefile environments. The faster I can reproduce the issue on my end, the easier a fix will come (less tiring/annoying to fix).

Was able to reproduce importing any set on a gen4 save file (tested batrev).

**Comment by NinFanBoyFTW** [comment]
Hey sorry but I just checked and the issue is still happening on all gen 4 games and battle revolution. I think you said you understood the problem now but either way just to clarify

Importing any set on gen 4 (normal game or battle revolution) causes pkhex to completely crash with no error and the pokemon is not generated. Thanks again.
