### ISSUE TITLE
G1 VC 1 ♀ : 7 ♂ pokemon shiny♀ randomize moves

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2015]
![image](https://user-images.githubusercontent.com/39662364/41509209-28ab13a2-7283-11e8-9f9f-5e607e342d26.png)
In G7 save
![image](https://user-images.githubusercontent.com/39662364/41509217-41ad4da2-7283-11e8-98c6-3c3fffee32c0.png)
![image](https://user-images.githubusercontent.com/39662364/41509236-6e965fde-7283-11e8-899d-07de8f9eadaf.png)

**Comment by iiippppk** [comment]
[002 ★ - フシギソウ - A2E0A0746332.zip](https://github.com/kwsch/PKHeX/files/2109100/002.-.-.A2E0A0746332.zip)

**Comment by kwsch** [comment]
Working as intended; certain genders in Gen1/2 cannot be shiny due to the IVs determining gender and shininess.

#1755

**Comment by iiippppk** [comment]
G1 VC pokemon(1:7) ♀shiny randomize moves will get G2 moves
[001 ★ - Bisasam - BF14550168C1.zip](https://github.com/kwsch/PKHeX/files/2109638/001.-.Bisasam.-.BF14550168C1.zip)

![image](https://user-images.githubusercontent.com/39662364/41514287-345078f0-72d8-11e8-8901-e7de25bf9992.png)

![image](https://user-images.githubusercontent.com/39662364/41514274-2039eb1c-72d8-11e8-97b4-65052f006ff9.png)

**Comment by iiippppk** [comment]
i think
we wouldn't consider the moves learn in G2
when pokemon is G1 VC 1:7 ♀shiny

**Comment by kwsch** [comment]
Right, that's what the recent commit should do; it removes gen2 evo chains to prevent any moves from that era from being added to the list.
