### ISSUE TITLE
Shadow Pokémon & National Ribbon

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2021]
![image](https://user-images.githubusercontent.com/39662364/41521141-9eb3451c-7303-11e8-846c-0e7a816ae366.png)
![image](https://user-images.githubusercontent.com/39662364/41521158-a6c6d124-7303-11e8-9070-311579a103fb.png)
legal

**Comment by kwsch** [comment]
Current logic:
https://github.com/kwsch/PKHeX/blob/05e10860ed9e89c4d8ebb990527104cfe8db3350/PKHeX.Core/Legality/Ribbons/RibbonVerifier.cs#L293-L295

Only checks for the ribbon once it leaves the game of origin. Sure it could be made smarter but there's currently issues for reading shadow data in XD save files (via forums).

**Comment by kwsch** [comment]
The Purified status in XD is stored in the save file rather than the pkm; the check is weak on purpose as this data is not available when legality checking.
