### ISSUE TITLE
XY Undiscovered Egg Group wild IVs

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2025]
https://bulbapedia.bulbagarden.net/wiki/Individual_values
![image](https://user-images.githubusercontent.com/39662364/41755603-c101b54a-760a-11e8-9762-ae958fdd649a.png)

Route 11  Nidorina
Friend Safari  Togepi
Friend Safari  Tyrogue
Frost Cavern  Smoochum
Route 3 & Route 22  Azurill
Route 4  Budew
Route 11 & Reflection Cave  Chingling
Reflection Cave  Mime Jr.
Route 22 & Friend Safari  Riolu
Azure Bay & Shalour City & Route 12  Mantyke

**Comment by kwsch** [comment]
Can probably add a quick check in VerifyIVs as an Else case after the MysteryGift:

https://github.com/kwsch/PKHeX/blob/15593a21793b3f3d8750e92309f68b63072d0657/PKHeX.Core/Legality/Checks.cs#L586-L588

```c#
if (pkm.XY && PersonalInfo.XY[EncounterMatch.Species].EggGroups.Any(z => z == 15) && pkm.IVs.Count(iv => iv == 31) < 2))
    AddLine(Severity.Invalid, string.Format(V28, 3), CheckIdentifier.IVs);  // undiscovered have 3 flawless IVs
```

Would need confirmation ingame from someone; I don't trust Bulbapedia 100% ;)
