### ISSUE TITLE
Gen 3 Egg Moves

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#2027]
Test with the latest commit from today, it seems that egg moves in Gen3 are not on the green legit table list. Is it working as intended or is it just a minor bug?

![2018-06-22](https://user-images.githubusercontent.com/20145301/41776102-19d4c616-762f-11e8-9cc1-41bebc50f22e.png)

thank you

**Comment by kwsch** [comment]
Do they appear on the last release for the same pkm?

**Comment by PrometheusG** [comment]
No, egg moves remain in the same position as the image above. I have tested other egg pokemon in emerald and their egg moves do not show up in the green list.

If you put them in the attack/Current Moves slot they do not throw any legality error, the rest illegal moves(that he can not normally learn through breeding or level up or TM) do which is correct.

this is not of a big issue I just wanted to let you know

**Comment by kwsch** [comment]
PKMEditor doesn't list egg moves at this time:
https://github.com/kwsch/PKHeX/blob/7591f54de3390b976b5d0978119a5a5fd1b8f23d/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs

Green list is fetched from Legality.AllSuggestedMovesAndRelearn, which only retrieves TM/Tutor/LevelUp sources.

Egg moves are subject to the pkm's current encounter; although this could be detected, mixing in egg moves with moves that any similar encounter could learn. Would need to change a lot of things to contextually provide indication in a neat way (different color? intermixed or immediately below?).

Maybe in the coming months I'll revisit this... I'm currently preoccupied with legality reworks & eventual pkNX/LGPE feature update planning, so this will have to wait :)

**Comment by PrometheusG** [comment]
No worries, I understand, thank you very much!
