### ISSUE TITLE
Batch Editor AbilityNumber

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2029]
in G4 G5 save
Batch Editor
.AbilityNumber=
invalid

![image](https://user-images.githubusercontent.com/39662364/41815263-4633ffbe-7798-11e8-9597-3b332deb9888.png)
![image](https://user-images.githubusercontent.com/39662364/41815268-5be1370a-7798-11e8-988e-28bc12b64794.png)
![image](https://user-images.githubusercontent.com/39662364/41815280-923e3550-7798-11e8-8395-333e2f3663a2.png)
![image](https://user-images.githubusercontent.com/39662364/41815281-9d5713ee-7798-11e8-9ffe-1793461ce13f.png)

**Comment by kwsch** [comment]
The setters for those are stubbed; PKHeX doesn't double check to see if the value was updated.
https://github.com/kwsch/PKHeX/blob/ea6842e5eb83a88a1e89ff843f4390cc8d9e2f08/PKHeX.Core/PKM/Shared/_K4.cs#L49

For these cases if you want to edit the Ability (and its expressed ability number), you need to call it as follows:

https://github.com/kwsch/PKHeX/blob/ea6842e5eb83a88a1e89ff843f4390cc8d9e2f08/PKHeX.Core/Editing/Bulk/BatchEditing.cs#L430-L431

`.AbilityNumber=$2`
