### ISSUE TITLE
TID anf SID Batch edit

### ISSUE THREAD

**Issue by frostheart32** [kwsch/PKHeX#2034]
Thank-you for answer my last issue. I was able to fix my latest build.

I've been using the batch editor to edit my ultra moon save TID and SID on all my box pokemon.

When I use the batch editor to change the TID and SID with the following:
.SID=3464
.TID=755301

The numbers don't change to the above numbers, they change to other random numbers.
In this case, SID=2254 and TID=769544.

I double checked on my og sun save, which I had used the batch editor to fix TID and SID multiple times in the past. When I use the above line, it changes again to a set of random numbers.

Is the above situation an issue with my computer or the pkhex program? If the problem is my end, is there a solution I can run?

Thanks,
Frosty

**Comment by kwsch** [comment]
PKHeX's internal representation uses the existing 16bit format TID/SID values, not the new Gen7 style.

Define the values you want in the main window, then in the batch editor, look at the current values for those properties.
