### ISSUE TITLE
Gen 5 WCs with no moves

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#2037]
It looks like the Summer 2012 Keldeo PGF doesn't have any moves specified. According to our records, it looks like Guested uploaded it: [https://projectpokemon.org/home/forums/topic/13900-archived-sticky-gen-v-event-collection-and-contribution-thread/?page=19](https://projectpokemon.org/home/forums/topic/13900-archived-sticky-gen-v-event-collection-and-contribution-thread/?page=19).
As far as I can tell, the game must use learnset moves if the moves are not specified. This should be fixed in PKHex for generating events. Not sure if it affects legality.

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/42130987-435252ba-7cab-11e8-8e32-83723ca4a6a8.png)
List of cards in mgdb where there are no moves defined. Ignoring the Liberty Ticket card, there's a few undefined ones so it's not just a one-off (in that case I would have just requested you faked the data).

Will add shortly.

**Comment by kamronbatman** [comment]
FYI @kwsch, I confirmed they were not hacked. GF was lazy.
