### ISSUE TITLE
Import/Export Multiple Sets of Select Pokemon From and To the Clipboard

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#204]
I was wondering if it is possible to have multiple sets of Pokemon from and to the clipboard aside from the party and the battle box. For instance, for importing: I could copy multiple Pokemon from and too Smogon for instance: 

### Machamp

- Dynamic Punch
- Bullet Punch
- Payback
- Stone Edge / Ice Punch
Item Attached: Lum Berry
Ability: No Guard
EVs and Nature:
EVs: 252 HP / 252 Atk / 4 Spd
Adamant Nature (+Atk, -SAtk)

Rhyperior

- Earthquake
- Stone Edge
- Substitute / Megahorn / Avalanche
- Substitute / Megahorn / Avalanche
Item Attached: Leftovers
Trait: Solid Rock
EVs and Nature:
EVs: 252 HP / 80 Atk / 176 Def
Adamant Nature (+Atk, -SAtk)

Chandelure

-Substitute
-Fire Blast
-Shadow Ball
-Pain Split / Hidden Power [Fighting] / Calm Mind 
Item Attached: Life Orb
Ability: Shadow Tag
EVs and Nature:
EVs: 252 Speed / 252 Special Attack / 4 Defense
Timid Nature (+Spd, -Atk)

Breloom

-Spore
-Swords Dance
-Mach Punch
-Bullet Seed
Item Attached: Life Orb / Lum Berry / Fighting Gem
Ability: Technician
EVs and Nature:
EVs: 4 HP / 252 Atk / 252 Spe
Jolly Nature (+Spe, -SAtk) or Adamant Nature (+Atk, -SAtk)

Gyarados

- Dragon Dance
- Waterfall
- Stone Edge / Ice Fang / Earthquake
- Stone Edge / Ice Fang / Earthquake
Item Attached: Leftovers / Life Orb
Ability: Intimidate 
EVs and Nature:
EVs: 4 HP / 252 Atk / 252 Spd
Adamant Nature (+Atk, -SAtk)

Blaziken

- Swords Dance
- Flare Blitz
- High Jump Kick
- Protect / Knock Off
Item Attached: Life Orb
Ability: Speed Boost
EVs and Nature:
EVs: 252 Spd / 252 Atk / 4 SDef
Adamant Nature / Jolly Nature

copy all of this and import them from the clipboard. The clipboard, in order to not overload the program could take up to 6 sets at a time and fill them to any empty space in the box (if no more space, to another box).

The same way could work from Pokemon from the box, selecting certain Pokemon and export them to the clipboard into the same manner as the ones I placed above.

I don't know if this could be done, but I thought it could be a useful feature to add it it doesn't exist already (assuming it can be done).

**Comment by kwsch** [comment]
https://projectpokemon.org/forums/showthread.php?48860-Importing-Party-Set-from-Clipboard

Showdown Sets do not contain all information that would make a Pokémon battle legal. 
Import 1 at a time and tweak as necessary.
