### ISSUE TITLE
Metal Claw Shedinja flags as Illegal ORAS

### ISSUE THREAD

**Issue by XxPhoenix1996xX** [kwsch/PKHeX#2045]
[292 - Shedinja - 965967655AC8.zip](https://github.com/kwsch/PKHeX/files/2174709/292.-.Shedinja.-.965967655AC8.zip)
![notitle](https://user-images.githubusercontent.com/40975656/42431672-f9126f80-8314-11e8-9ba5-9dc73ec006c2.png)
Nincada learns Metal Claw at level 21; evolving it at level 22 generates a Metal Claw Ninjask

**Comment by kwsch** [comment]
Looks fine in gen7 due to the ability to move-reminder future level moves; PKHeX is likely incorrect in how it extrapolates the gen6 evolution chain (ie not having Nincada at [met-22]).

Will investigate further & fix later today :)
