### ISSUE TITLE
Hidden Ability Checks

### ISSUE THREAD

**Issue by ijuintekka** [kwsch/PKHeX#2047]
https://github.com/kwsch/PKHeX/blob/6d0dda1df0466e7a1e6ecf5e945dc75750ecf341/PKHeX.Core/Legality/Verifiers/AbilityVerifier.cs#L181-L182
This is flagging ability 2 instead of hidden abilities.

https://github.com/kwsch/PKHeX/blob/6d0dda1df0466e7a1e6ecf5e945dc75750ecf341/PKHeX.Core/Legality/Verifiers/BallVerifier.cs#L206-L207
This is flagging Sport Ball Illumise regardless of its ability.

**Comment by kwsch** [comment]
Yup, `abilnumber == 4` should be there instead. Initial rework was passing in `(abilitynumber >> 1)`.

Will fix later today :)
