### ISSUE TITLE
Gen1 Ingame Trade OT names transferred to Gen7+ via PokéBank

### ISSUE THREAD

**Issue by egzonqj** [kwsch/PKHeX#2049]
So I came into this last weekend, seems like PKHeX takes this as invalid because the OT is too long, but they are certainly legitimate and the OT is indeed "Entrenador", since I transferred them with PokéTransporter from my Spanish Pokémon Yellow/Red games.

![image](https://user-images.githubusercontent.com/5099644/42465620-c6201fee-83ac-11e8-9205-1bb3f6b53ba7.png)
![image](https://user-images.githubusercontent.com/5099644/42465627-cc9b1ea0-83ac-11e8-8d12-a636a5b05263.png)

I believe this is the code that should be updated but not that sure of that
https://github.com/kwsch/PKHeX/blob/e2f11edc438e9e21205d3b45f44bd05588110822/PKHeX.Core/Legality/Encounters/Data/Encounters1.cs#L23

**Comment by kwsch** [comment]
Changing that array would be incorrect; gen1/2 shows it as TRAINER and can't allow the user to input more than (n) characters.

Accounting for this can be thorny:

- Add in handling to require gen1 trades to have the {language} transfer OT name
- Add in handling to pkmconverter to use the language-specific TRAINER name if appropriate. 

What if the player named themselves "TRAINER" on purpose? PKHeX automatically replaces "TRAINER" with the single char code (which is incorrect if the player purposefully chose TRAINER); maybe just checking the single char code when converting the string is appropriate -- need to see if there's any other "Entrenador" variants for the other languages.

**Comment by egzonqj** [comment]
Oh I see, thanks for the reply!

Then waiting for the TRAINER variants would be the best scenario

**Comment by kwsch** [comment]
I don't have a 3DS so I can't test other language cases; I wonder if these names are documented anywhere else. Might have to scan the transporter binary for any strings... unless they've encrypted them like the regular games.

**Comment by egzonqj** [comment]
Fair enough, thanks for the reply!

**Comment by WEERSOQUEER** [comment]
The OT name in non-Japanese RBY games is simply "TRAINER" when viewed with a program (notice the  first value is 5D with the rest filled with "50" bytes taken from my Spanish Blue Mr. Mime's OT data as an example):
![untitled-1](https://user-images.githubusercontent.com/36747884/42486308-67034b68-83c9-11e8-9cee-ff9aef36e91c.jpg)





However, the language of the non-Japanese ROM data gives/shows its native OT name when viewed/imported to the specified language (same Mr. Mime when viewed in Spanish game versions):

![pokemon azul blue s s bf](https://user-images.githubusercontent.com/36747884/42486314-72c9c328-83c9-11e8-8ed7-123eda9411bb.png)


English & German: TRAINER
French: DRES.
Italian: ALLEN.
Spanish: ENTREN.


For Gen 7, they will get the OT name of the VC title's language you import them via Transporter as follows:

English & German: Trainer
French: Dresseur
Italian: Allenatore
Spanish: Entrenador
