### ISSUE TITLE
No Support for ORAS O-Powers

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#205]
I just wanted to ask why there is no ORAS support for O-Powers. I don't know if this is a program error or it is a game issue. I just wanted to ask.

**Comment by kwsch** [comment]
Nobody has researched it; nobody cares to edit it besides unlocking all O-Powers.

**Comment by ricksee** [comment]
Fair enough. I just thought the O-Powers would work the same as in XY since they are in the same generation and are using the same engine.
