### ISSUE TITLE
legality issue with ranger manaphy

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2052]
Hi. I just checked my Pokemon Pearl save and my Manaphy (which I legitimately played ranger to get and hatch, is coming up as illegal, saying, "Invalid: Ability does not match mystery gift" Again, I played through ranger, then legitimately sent the manaphy to my pearl and hatched it legitimately in my Pearl. Thanks
[490 - MANAPHY - 0DCF87D32BC1.zip](https://github.com/kwsch/PKHeX/files/2182875/490.-.MANAPHY.-.0DCF87D32BC1.zip)

Edit: this also effects the legality of the pokemon when it is transferred to gen 5 and up

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/57250823a8adce76bc05f3acb6f545566c2eb187
