### ISSUE TITLE
Another Minor Legality Issue.

### ISSUE THREAD

**Issue by ShinyYveltal** [kwsch/PKHeX#2054]
Type: Null / Silvally that are from USUM are counted as legal if met location is set at Aether Paradise. Sorry if they are actually available in Aether Paradise in USUM, all I know is that Type: Null / Silvally can only be obtained in Ancient Poni Path in USUM but in Aether Paradise in SM. (Please don't kill me if this issue is already fixed)

![silvally_null](https://user-images.githubusercontent.com/18177787/42599348-f1c4b386-852c-11e8-84c6-a0ff84297271.PNG)

**Comment by egzonqj** [comment]
If your party and boxes are full you can't take the Type: Null from Wicke on Poni Island, instead she will wait for you to come and get it in Aether Paradise. 

So yeah this is correct and legal.

**Comment by ShinyYveltal** [comment]
I'm stupid lol
