### ISSUE TITLE
Battle Test Rating + Other Stats on Battle Spot

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#206]
I don't know if this is a bug or not but changing the value of the Battle Test ranking for the Battle Institute only displays the changed values for Wi-Fi-Battles/Battle Spot but not the Institute itself. At the Institute, the most recent or unchanged rating remains the same. I don't know if it only applies to Wi-Fi only.

I heard there are other issues with the Battle Maison and BP on Wi-Fi/Battle Spot. You can check out the issue in the link below if you want:

https://projectpokemon.org/forums/showthread.php?49730-Wifi-Battle-On-Screen-Stats-Incorrect

**Comment by kwsch** [comment]
The Trainer Stats are the values shared over WiFi, the actual ingame record is stored elsewhere (unknown).

My reply in that thread covers both angles.
