### ISSUE TITLE
Issue with a few gen 1 in-game trade OT variants in gen 7

### ISSUE THREAD

**Issue by WEERSOQUEER** [kwsch/PKHeX#2060]
Hi, the RB in-game trade Nidoran♀, Nidorina and Jynx will not pass as legal with the OT of **Dresseur**, **Allenatore** and **Entrenador** when transferred to gen 7; all the others pass.

Here's an example:

![4](https://user-images.githubusercontent.com/36747884/42745018-72d8afa8-889e-11e8-9069-c6269c69aa43.jpg)
![3](https://user-images.githubusercontent.com/36747884/42745026-83d10f3a-889e-11e8-871e-735234cb01ea.jpg)

On the latest release btw.

**Comment by kwsch** [comment]
Full parse details indicate it is matching a Wild Encounter, will likely need to update the trade match deferral scenario logic so that it instead returns the trade encounter first.
