### ISSUE TITLE
Gen 3 SEASOR(Kingdra) in-game trade error

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#2062]
Hi,

Testing with the latest official build and latest commit it seems that SEASOR(Kingdra), the in-game trade emerald pokemon, shows up as illegal in generation 4,5 . 
In generation 3,6,7 it shows up as legit.

I have not edited the pokemon, the error is: "Ability does not match PID"

In build 20180601 that pokemon shows no errors, it starts with 20180709 and continues with 20180716.

Here is .pk3 file of Kingdra: 
[230 - SEASOR - D2460000007F.zip](https://github.com/kwsch/PKHeX/files/2198059/230.-.SEASOR.-.D2460000007F.zip)
It is the same pokemon in all files, I just leveled it up in some of my games because I used to play with it in battles

![2018-07-16](https://user-images.githubusercontent.com/20145301/42765080-dfef002a-891f-11e8-9594-867a44842250.png)

Thank you very much

**Comment by kwsch** [comment]
misbehavior in logic is suspected here:
https://github.com/kwsch/PKHeX/blob/6ee534c4b1cff321b97c9da66684bfe22ef9cb39/PKHeX.Core/Legality/Verifiers/AbilityVerifier.cs#L136-L163
