### ISSUE TITLE
Setting a suggested Met Location once changing Origin Game

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#2064]
I recall in previous builds, PKHeX would automatically change a Pokémon's Met Location once the user changed its Origin Game. Examples would include:

- Change Origin Game to `8` (SoulSilver) -> Met Location changed to `30001` (Poké Transfer)
- Change Origin Game to `38` (Yellow) -> Met Location changed to `30013` (The Kanto Region)
- Change Origin Game to `41` (Crystal) -> Met Location changed to `30017` (The Johto Region)
- Change Origin Game to `34` (GO) -> Met Location changed to `30012` (Pokémon GO)

I would like to see this re-added, since it is not present in the latest release and latest commits :)

**Comment by kwsch** [comment]
Should still be in there, could just be misbehaving.

https://github.com/kwsch/PKHeX/blame/15593a21793b3f3d8750e92309f68b63072d0657/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L1044-L1050

https://github.com/kwsch/PKHeX/blob/15593a21793b3f3d8750e92309f68b63072d0657/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L1027-L1050

Might be that the pkm.Version value is not updated prior to making the method call?
I can potentially see something else wrong (Gen4 encounter type) so I probably need to use Version.GetGeneration() instead (for that case only).
