### ISSUE TITLE
Issue with legality importing gen 2 -> 7 and Stadium 2 OT mistake

### ISSUE THREAD

**Issue by WEERSOQUEER** [kwsch/PKHeX#2065]
Hi, I found out that Pokemon introduced in gen 2 are passing when you give them the Origin Game of a gen 1 game and location of the Kanto Region. Some gen 2 introduced Pokemon pass right away when given a gen 1 game and Kanto Region location (the Sentret provided), and some give "Evolution not valid" (the Meganium provided). 

And in the case for Celebi, it also falsely passes. Just replicate the following:

1. Drop into gen 7.
2. Change Origin Game to a gen 1 title.
3. Set location as the Kanto Region.
4. Uncheck Fateful Encounter flag.
5. Set Ability as Hidden.

[pkmn2.zip](https://github.com/kwsch/PKHeX/files/2208483/pkmn2.zip)

No gen 2 introduced Pokemon should be legal with a gen 1 origin.

About Stadium 2, the Pokemon Farfetch'd and Gligar you get gifted are said to have the incorrect OT for Japanese games, but they pass when the ID is 1999 which is wrong: https://bulbapedia.bulbagarden.net/wiki/List_of_game-based_Pok%C3%A9mon_distributions_in_Generation_II#Pok.C3.A9mon_Stadium_Gold_and_Silver
![1](https://user-images.githubusercontent.com/36747884/42923239-9c385410-8af2-11e8-9b99-c0a5cd1f1721.jpg)
![2](https://user-images.githubusercontent.com/36747884/42923242-a07ce680-8af2-11e8-8ab8-aa46b1a5bdc7.jpg)

**Comment by kwsch** [comment]
Stadium 2:

Was added back >1y ago:
https://github.com/kwsch/PKHeX/commit/758adf2cfffe9da1c3e77221757a29d3ae649bb5#diff-af9ff61c4801a502b5a72ed9a1c3db83R503

Stadium 2 came out in 1999 in Japan, did it really have the OT ID as 2000 for the non-international release?

**Comment by WEERSOQUEER** [comment]
Stadium 2 (which released in 1999) is what became Stadium 1 in the west in 2000. 
This is the Stadium 1 released only for Japan (released in 1998): 
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Stadium_(Japanese)

Stadium 2 in the west is known as Pokemon Stadium Gold and Silver in Japan and came out in December 2000.

**Comment by WEERSOQUEER** [comment]
I just wanted to point out in this latest commit I tested, Stadium 2 (Stadium 1 in west)'s **Omanyte**, **Kabuto** and **Psyduck** are being flagged illegal due to having incorrect Stadium OT if they have the IDNo. 01999 in which they do for this version: https://bulbapedia.bulbagarden.net/wiki/List_of_game-based_Pok%C3%A9mon_distributions_in_Generation_I#Japanese_Pok.C3.A9mon_Stadium_2

Example:
![ef](https://user-images.githubusercontent.com/36747884/42984310-eb172508-8bb9-11e8-9bf2-6d6aee644df0.jpg)
