### ISSUE TITLE
small issue with glow sprite edges

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2066]
Hey, just checked out the glow sprite edges that you put into pkhex. I think it looks pretty good. 1 issue I found though is that most if not all of the ultra sun or ultra moon exclusive pokemon (partner cap pikachu, poiple, ultra necrozma etc...) are not showing up correctly. It seems that when you hover over their sprites, a glow comes over a box around them and not their sprites individually. Thanks

**Comment by kwsch** [comment]
Looks like the USUM sprites dumped did not properly set their transparency data...

Will have to run something to clean up the base sprites so that they can glow correctly.
