### ISSUE TITLE
SM Save Marowak large

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2068]
Marowak has 3 formes:
![image](https://user-images.githubusercontent.com/39662364/43057205-659828c0-8e73-11e8-902a-da8410108218.png)

![image](https://user-images.githubusercontent.com/39662364/43057241-a605ebcc-8e73-11e8-8ac7-c540cce75be6.png)

When I select the Large form at the bottom left the ListBox goes to Kangaskhan-1 instead, displaying the forms for Marowak:
![image](https://user-images.githubusercontent.com/39662364/43057280-e3122396-8e73-11e8-92d1-3510c445895a.png)

**Comment by kwsch** [comment]
Suspect behavior error sourced from this commit:
https://github.com/kwsch/PKHeX/commit/1c49b0681d51760446ed552f1d32816648c453e8

**Comment by kwsch** [comment]
Nope, looks like I forgot that Totem formes do not have dex sprite bits...
