### ISSUE TITLE
Event Flags Randomly Checked

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#207]
I don't know if this is a problem or not, but for me when you Click on Event Flags, some of them are checked, even though I just started the game. This been event in games XY and ORAS. It doesn't seem to affect the game for me, but I just wanted to make sure. 

This picture below is for an Omega Ruby game that I just started:
![2016-08-29_21-14-06](https://cloud.githubusercontent.com/assets/21182549/18072626/a2463428-6e2d-11e6-95f3-7fd9d86e73cb.png)

**Comment by kwsch** [comment]
They're intended. The game uses event flags to despawn certain NPCs at the
start of the game and only lets them appear when the time is right (event
flag cleared).

**Comment by ricksee** [comment]
@kwsch Thanks for clarifying and explaining it to me completely. You can close this thread if you want. Thank you.
