### ISSUE TITLE
Pre-Gen6 saves won't load properly.

### ISSUE THREAD

**Issue by Filo97** [kwsch/PKHeX#2070]
It detects the game, bu nothing actually loads. No pokèmons, trainer info, or anything appears. Tried with Pokèmon Platinum, Black, and HG. .SAV files come from DSiMenu++

**Comment by kwsch** [comment]
Do they load correctly in other programs?

**Comment by egzonqj** [comment]
Pretty strange behavior, an hour ago I opened some saves with the latest commit and it worked just fine, they were saves from real Gen 3 cartridges tho

**Comment by Filo97** [comment]
Yeah, loads correctly in pokegen

**Comment by Filo97** [comment]
and on stuff such as desmume.

**Comment by kwsch** [comment]
Care to post any save files? Can only speculate otherwise :\

**Comment by kwsch** [comment]
Closing until further information is provided; would need to know if the save file has only been saved once (uninitialized second save may result in that save being loaded? idk. probably a hardware quirk not present on regular systems)

**Comment by Filo97** [comment]
Gonna post the .sav file as soon as i'm back home, sorry but for some reason i never got the notification.

**Comment by Filo97** [comment]
Thank you very much. Where can i find latest nightlies since the official release is not yet updated on projectpokèmon? If there are no nightlies, most lightweight compiler there is?

**Comment by kwsch** [comment]
@Filo97 enter the game and save again so that both save slots are initialized with data.

**Comment by Filo97** [comment]
That was not what i asked? I wanted to know where i could find a precompiled build of the latest commit as the changes fixing gen 4 and 5 aren't in the release yet.

**Comment by kwsch** [comment]
@Filo97 It's a simple mitigation until the next release is posted; seeing as this 'issue' was present for >2y it's not something urgent to post a new binary for.
