### ISSUE TITLE
Gen1 pokemon error (catch rate, gen2 held item)

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#2071]
Hi,

Testing with the latest commit of today(20180723) some pokemon from my Blue game show an invalid error: "Catch rate does not match a valid held item from Generation 2"
Everything is fine in the latest release (180716)

When I transfer them via PKHeX to my Gold save they show up as legit again with their respective items they obtain after moving to Gen 2

Here is the .zip file of the pokemon and the screenshot:
[Gen1 pokemon.zip](https://github.com/kwsch/PKHeX/files/2219005/Gen1.pokemon.zip)

![2018-07-23](https://user-images.githubusercontent.com/20145301/43073204-5d111154-8e81-11e8-9305-54bc3f648fef.png)

Thank you very much

**Comment by kwsch** [comment]
CatchRate<->HeldItem checking is done here:
https://github.com/kwsch/PKHeX/blob/922cbdf583a02edf25e5316be7498b722f9cffda/PKHeX.Core/Legality/Verifiers/MiscVerifier.cs#L84-L120

**Comment by kwsch** [comment]
Not able to replicate on the current commit with the attached PKM files; maybe the export had 'fixed' them or importing does something I'm not aware of...

Can you send the save file? (can pm on forums too)
