### ISSUE TITLE
pkhex crashing issue

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2072]
Hey. So I'm not sure but I think this has to do with the new glowing animations (love the new addition with the pulsing animation by the way.) When I hover over a bunch of different pokemon one after the other, after about 30 seconds of hovering over random pokemon, my cursor turns to the loading cursor and then pkhex just crashes with no message or warning (the window just closes).

**Comment by kwsch** [comment]
Probably would have to debug this; could be that it's stopping the animation too many times? idk

During implementation there were various glitches with the animation not stopping, not cleaning up, and corrupting memory... guess I didn't catch everything ;)

**Comment by sora10pls** [comment]
Going to bump this as I've (finally) been able to replicate this while debugging. Unsure if this will help since the commit that closed this was a guess according to the attached comment, but I figured I'd share.
![screenshot_2](https://user-images.githubusercontent.com/17801814/44752894-72ce6c00-aaea-11e8-8aa5-59b1bd79073d.png)

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

**Comment by kwsch** [comment]
@sora10pls do you remember what exactly you were doing when the crash happened? `baseLayer` was disposed before the method executed, but knowing the stack trace triggered from would help.

**Comment by sora10pls** [comment]
I was quickly hovering over several Pokémon in a box, the glow animation would barely play on any of them because I was going fast. Right when I hovered over a Pokémon after a few seconds, it crashed. It's difficult to reproduce at will though since it seems random.

**Comment by architdate** [comment]
@kwsch reproduced stacktrace: https://pastebin.com/y4VkSFFh
![devenv_2018-08-29_07-00-51](https://user-images.githubusercontent.com/17220860/44755613-81a03780-ab59-11e8-8442-e1f08cb7537f.png)

Method of replication for me was a lot of consecutive click drags over to PKMEditor and then rapidly hovering back to box
