### ISSUE TITLE
Nickname egg translation

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#2079]
Hi, testing the program I notice something. When you mark a Pokémon as egg, it changes its name to "Egg". I would like to translated to "Huevo" as it showed in the games but I didn't find it in the txt files. 

![captura](https://user-images.githubusercontent.com/4681902/43310955-5c0a8c9e-9189-11e8-98c7-140918383ba3.PNG)

**Comment by egzonqj** [comment]
It already does it when you open a save file

**Comment by ajtudela** [comment]
I know, but when I edit a pkm without load a sav file, doesn't.

**Comment by egzonqj** [comment]
Try changing the language of the pokemon maybe?

**Comment by ajtudela** [comment]
Yes, I don't know how I can't figure it out

**Comment by kamronbatman** [comment]
Note for anyone seeing this and having issues on Gen 3. Eggs are always named in Japanese. The egg language flag (0x600) makes it appear correct (localization) for that language.
