### ISSUE TITLE
G3 Deoxys Base & Stats

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2082]
In G3 save
![image](https://user-images.githubusercontent.com/39662364/43352934-99a88ddc-925e-11e8-9ea3-7e9c24281341.png)
![image](https://user-images.githubusercontent.com/39662364/43352918-72744d3c-925e-11e8-98d2-b5404a707e72.png)
![image](https://user-images.githubusercontent.com/39662364/43352924-811a922e-925e-11e8-92b3-79e9f1042067.png)
![image](https://user-images.githubusercontent.com/39662364/43352927-8c650f10-925e-11e8-94c1-dc6ca2e817ed.png)

**Comment by iiippppk** [comment]
![image](https://user-images.githubusercontent.com/39662364/43353425-b15ed1c2-926b-11e8-8748-99246a23d861.png)
should be 160 Def & SpD Base
but 
in G3 save
Deoxys altform is always 0

**Comment by kwsch** [comment]
Need to edit the personal data tables to make them different :)
