### ISSUE TITLE
[Feature Request] Add check for Egg EXP

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#2083]
If a Pokémon is in an Egg and has any experience other than 0 without it reaching Level 2, PKHeX doesn't flag it as illegal.

Take Rowlet as an example, which needs 9 EXP to hit Level 2:
![image](https://user-images.githubusercontent.com/17801814/43360189-fd926776-927e-11e8-89d9-f3b3051b44d0.png)

Eggs can never gain EXP, so there should be a check in place for if a Pokémon is in an Egg and its EXP doesn't equal 0.

**Comment by kwsch** [comment]
Not so much a bug, just a lack of a check ;)

**Comment by sora10pls** [comment]
:P
