### ISSUE TITLE
Gen 5 B/W level up move error

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#2085]
Hi,

First of all thank you for the new release!

I have bumped into a small issue when I checked my save games, more specifically in my White (gen5) game. Tested on the latest release
I have found 4 pokemon that show the "invalid move" error.
Gligar, Remoraid, Absol and Drifblim

These are the .pk5 files: [Gen.5 pokemon.zip](https://github.com/kwsch/PKHeX/files/2256571/Gen.5.pokemon.zip)

Drifblim is lvl.49 and it shows that it cannot have Batton Pass as a legal move. This is true for B2/W2 but not for B/W as it can learn that move at lvl.44 in B/W  (and at lvl.52 for B2/W2)
I have leveled up the pokemon to level 52 and it is shown as legit again, with no errors
Same with the rest 3 pokemon
![2018-08-03 1](https://user-images.githubusercontent.com/20145301/43632918-3d5e3548-9710-11e8-944e-542a44582b46.png)
![2018-08-03 2](https://user-images.githubusercontent.com/20145301/43632928-44cddae0-9710-11e8-94e5-888d2317bdab.png)
![2018-08-03](https://user-images.githubusercontent.com/20145301/43632605-4dff5e64-970f-11e8-967f-fef17d2da258.png)
I think the error is that is is taking into account the B2/W2 level up moveset in those pokemon and not the B/W moveset

Thank you very much

Edit: "invalid move" error, not "illegal move" error, sorry

**Comment by kwsch** [comment]
Regression due to https://github.com/kwsch/PKHeX/commit/3d0a2946eb53486c9f1cf1a0515a48fda220ca87#diff-e18fd76770c57513eb4384fc55bbd1ff , will need to think of a clever solution so that the intended fix for that issue is also solved.
