### ISSUE TITLE
[Feature Request] Poké Ball Capsules management for D/P/Pt

### ISSUE THREAD

**Issue by LOuroboros** [kwsch/PKHeX#2089]
I just opened a savefile of Pokémon Diamond with PkHex because I wanted to test something, and I noticed that PkHex doesn't seem to allow editing the ball capsules. There isn't even a button to give them all automatically.

Could it be considered as a feature to add at some point down the road?
Thanks!

**Comment by kwsch** [comment]
Per the forum stickies, I don't do research requests. When things are thoroughly documented on the wiki/save research forum, they can be considered for implementation.
