### ISSUE TITLE
Possible Feature: Export Select Pokemon to Clipboard

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#209]
I know that importing multiple Pokemon from the clipboard is not possible. What about exporting multiple Pokemon that you select (Ctrl + Click) to the clipboard. I thought that would be possible because you do not need OT, memories, etc.

**Comment by kwsch** [comment]
Control/Shift/Alt clicking slots is already used for quick View/Set/Delete.

I don't see it saving much time, as nobody really exports multiple Pokémon for pasting into Showdown... it's usually importing from Showdown. Showdown Sets are by no means a substitute for exporting the PKM files if sharing teams with others is the goal.

**Comment by ricksee** [comment]
It would still be helpful if it could be added because it can help if the genned Pokemon can be used properly in a trained simulator for real online battle scenarios.

**Comment by kwsch** [comment]
Exporting individual Pokémon is already possible; adding in 'selections' would clutter the UI, so you'll have to settle for exporting one at a time.
