### ISSUE TITLE
Secret Super Training Still Locked Regardless of Medals and Time Entered and Earned

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#210]
Despite getting all 36 metals and putting appropriate times with the Pokemon, Secret Super Training is still locked and I still have to complete them one by one for the next one to be unlocked. I don't know if this is intended or not. This applies to (X/Y) and (ORAS).

I'll show you an image
![win_20160829_23_09_26_pro](https://cloud.githubusercontent.com/assets/21182549/18074838/c5cb510c-6e3d-11e6-8028-8ce5017ba1d7.jpg)

**Comment by kwsch** [comment]
Did you make sure that "Super Training Enabled" was checked?

![img](http://i.imgur.com/JRlV00F.png)

**Comment by ricksee** [comment]
Yes, I enabled it but it was still locked.

**Comment by ricksee** [comment]
![2016-08-29_23-21-18](https://cloud.githubusercontent.com/assets/21182549/18075033/63faeada-6e3f-11e6-80ed-3878cf4962c4.jpg)

**Comment by ricksee** [comment]
![2016-08-29_23-22-53](https://cloud.githubusercontent.com/assets/21182549/18075061/9419808c-6e3f-11e6-882b-716d2bfd4e3e.jpg)

**Comment by kwsch** [comment]
Even if the PKM has the medal, if the save file has never completed the mission, it'll still be 'locked' until you complete the prerequisite mission once.
