### ISSUE TITLE
Legal errors

### ISSUE THREAD

**Issue by Narithegreat** [kwsch/PKHeX#2103]
In GSC, some of my Pokemon eggs such as Igglybuff and Cleffa are flagged illegal due to them not being able to receive experience, but 100 is the base experience for them at level 5.

![rtrt](https://user-images.githubusercontent.com/38122443/44505643-8738e180-a670-11e8-8d3b-4fa7b35dbaad.jpg)

Another issue is that the DPPHGSS in-game trade Pokemon of Magikarp & Pikachu are illegal on Korean gen 4 because they cannot exist due to being non-Korean.
[Pokemon.zip](https://github.com/kwsch/PKHeX/files/2312980/Pokemon.zip)
.

**Comment by kwsch** [comment]
gen2 eggs should be fine on the latest commit:
![image](https://user-images.githubusercontent.com/6393368/44506324-c2301a80-a65a-11e8-835e-c73ee51921bd.png)
