### ISSUE TITLE
[Legality Issue] DW Shieldon special move flagged as illegal

### ISSUE THREAD

**Issue by lcagsthag** [kwsch/PKHeX#2104]
Hi, my Dream World Shieldon caught from Entree Forest is flagged as illegal for having the special move Counter. 

https://imgur.com/a/ZueFTlS

While it's normally an egg move, Shieldon can come with this move if caught from the Entree Forest, documented here: https://bulbapedia.bulbagarden.net/wiki/Icy_Cave_(Dream_World_area)

**Comment by kwsch** [comment]
Currently programmed to allow Counter as a move; will have to debug.
https://github.com/kwsch/PKHeX/blob/5fe9226c6293c000c6e30c171dbefe33cf17816b/PKHeX.Core/Legality/Encounters/Data/Encounters5.cs#L411

**Comment by kwsch** [comment]
Not able to replicate on current commit; there was a quick hotfix a few hours after the 8/3/18 release was posted, so lmk if there's still any issues if you re-download the exe.
![image](https://user-images.githubusercontent.com/6393368/44613152-9b8df300-a7c4-11e8-8144-ff2c3b614321.png)

**Comment by lcagsthag** [comment]
Still experiencing this issue. Here's the pk7 file in question: https://ufile.io/fjxj0

**Comment by kwsch** [comment]
@lcagsthag it can't have fissure AND counter; dream world pkm can only have one special move at a time.
