### ISSUE TITLE
Kyurem Forms

### ISSUE THREAD

**Issue by crzyc** [kwsch/PKHeX#2105]
Because of how the fusion mechanics work, there can only be one Fused Kyurem forme, with one Zekrom / Reshiram. PKHex doesn't count that, however. Not to mention, PKHex counts a Black / White Kyurem as legal even when there are no pokemon fused with DNA Splicers. As you may be aware, fused mons cannot be transferred or traded between games, rendering both of these situations illegal on a regular save.

Hopefully, this will be applied to Solgaleo / Lunala with Necrozma as well. It should be noted that while having one Dusk Mane Necrozma and one Dawn Wing Necrozma is possible, more than one of each is also impossible.

**Comment by kwsch** [comment]
Individual PKM Legality != Save File Legality
