### ISSUE TITLE
pokemon database feature request

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2108]
Hey, I thought this was already in the database but maybe I was just remembering wrong. I wanted to know if it would be possible to add the illegal marking (as it is in the normal boxes) on to pokemon in the database who are illegal. I think this would be great to visually know if your pokemon are illegal through the database without having to do a few advanced searches. Thanks

**Comment by kwsch** [comment]
There's an option to search for showing only illegal entries:

![image](https://user-images.githubusercontent.com/6393368/44948761-28920700-add8-11e8-9751-cdab75714e5d.png)

I guess I could show the indication like box sprites do.

**Comment by NinFanBoyFTW** [comment]
Thanks. I have been using that but I still feel that it would be nice to see the visual indication in case your searching both illegal and illegal pokemon.
