### ISSUE TITLE
Multiple bugs in latest commit

### ISSUE THREAD

**Issue by MichiS97** [kwsch/PKHeX#2111]
Hi,
I've just compiled the latest commit and I'm trying to edit a Pokemon Crystal (VC, EUR region) with it and I've stumbled across multiple bugs.
Firstly, the "clear box" and "clear ALL boxes" options don't work at all. They simply don't do anything.
Secondly, when I use the "Sort all boxes" option, the Pokemon seem to be sorted in a descending order and not in ascending order, like previously. That means if you'd have a full Pokedex in Crystal, Celebi would be in the first slot of the first box, and Bulbasaur would be in the last slot of the last box.
This is highly impractical for managing a Living Dex like I am. 
I would love for this to be fixed.

Thank you!

**Comment by kwsch** [comment]
Are you holding control when clicking any of the dropdown items?

Shift = All Boxes instead of current
Control = Invert action (reverse sorting order, clear opposites)
