### ISSUE TITLE
[Bug] Alt Form Cries not playing

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#2118]
Caused by https://github.com/kwsch/PKHeX/commit/d8c355cf64a76ceaa3baaa10af647da2c2e171c4; PKHeX is instead just playing the Cry of the Base Form.

**Comment by kwsch** [comment]
Probably because I forgot about the leading `_` for the resource name.

A `.Substring(1)` at the end should result in the correct filename.
