### ISSUE TITLE
[Legality Issue] Gorebyss & Huntail movesets don't include moves learnt as Clamperl

### ISSUE THREAD

**Issue by Bedo9041** [kwsch/PKHeX#2121]
Both Gorebyss and Huntail can get Clamp; Water Gun; Iron Defense and Shell Smash as Clamperl, however they are marked as illegal with these moves.
![image](https://user-images.githubusercontent.com/7407004/45578625-90d1f580-b87a-11e8-80a8-7c4263c77815.png)

**Comment by kwsch** [comment]
Works fine; pls do not report "x should be able to learn y" if it's not an unmodified PKM because there's more to legality than a movepool.

![image](https://user-images.githubusercontent.com/6393368/45579347-d3c0a880-b83b-11e8-943e-4304fdf93840.png)
