### ISSUE TITLE
Gen1 (Pokémon Yellow) save file changes not showing up in game!

### ISSUE THREAD

**Issue by NelsonBassanelo** [kwsch/PKHeX#2123]
I don't speak english so well, I hope you can understand... :)

I used GBC VC Injector for 3DS to converter the Pokémon Yellow rom of GBC to .cia and installed on my 3DS, so I backed up my save (.sav) using Checkpoint and then open on PKHeX (latest version, download today) on my PC... I can open the sav file and edit as well, then I saved and put again on the folder that checkpoint use as backup. I turn on my 3DS, open Checkpoint and use the function to restore the save file and appears that works successfully but when I open the game, the changes don't appear.

I open the same file again on PKHeX and the changes as made and save are still there, so I don't know what's happening.

I did something wrong?

**Comment by kwsch** [comment]
Try importing it to another emulator on PC.
You're likely not importing the file correctly, thus this is not a PKHeX issue.
