### ISSUE TITLE
Emerald plus shininess

### ISSUE THREAD

**Issue by matlink** [kwsch/PKHeX#2124]
I've encountered an issue while editing an emerald plus (ROM hack) savegame.
After having set a pokemon to be shiny (using the red star), it does not appear to be shiny in game.
I know emerald plus has an highly increased shiny encounter rate. Do you think shiny PIDs in vanilla emerald could be not shiny in emerald plus?
I've tried some other savegame editors without success.

**Comment by kwsch** [comment]
Not really a PKHeX issue. Shininess is a derived value from the PID; if a ROM Hack has modified the rules for determining a shiny, PKHeX won't know.

PKHeX supports the official unmodified games, any unintended support for unofficial games is provided as is.
