### ISSUE TITLE
cant compile pkhex

### ISSUE THREAD

**Issue by deisuke1234** [kwsch/PKHeX#2127]
hi i have this issue with i try to compile pkhex.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0101	The namespace 'PKHeX.Core' already contains a definition for 'MoveType'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Legality\Structures\MoveType.cs	3	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetMoveTypeGeneration' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Legality\Structures\MoveType.cs	28	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetMoveTypeFromG12' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Legality\Structures\MoveType.cs	35	Active
Error	CS0101	The namespace 'PKHeX.Core' already contains a definition for 'Nature'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Legality\Structures\Nature.cs	6	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetPKM' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	7	Active
Error	CS0111	Type 'Extensions' already defines a member called 'SetPKM' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	11	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraPKM' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	19	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	28	Active
Error	CS0102	The type 'Extensions' already contains a definition for 'None'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	41	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlotsUnsafe' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	43	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots2' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	57	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots3' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	65	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots4' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	75	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots5' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	83	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots6' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	92	Active
Error	CS0111	Type 'Extensions' already defines a member called 'GetExtraSlots7' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\Extensions.cs	106	Active
Error	CS0101	The namespace 'PKHeX.Core' already contains a definition for 'SlotChange'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\SlotChange.cs	3	Active
Error	CS0111	Type 'SlotChange' already defines a member called '.ctor' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\SlotChange.cs	19	Active
Error	CS0111	Type 'SlotChange' already defines a member called '.ctor' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\SlotChange.cs	21	Active
Error	CS0101	The namespace 'PKHeX.Core' already contains a definition for 'SlotChangeInfo'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\SlotChangeInfo.cs	3	Active
Error	CS0111	Type 'SlotChangeInfo' already defines a member called '.ctor' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\SlotChangeInfo.cs	17	Active
Error	CS0111	Type 'SlotChangeInfo' already defines a member called 'Reset' with the same parameter types	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\SlotChangeInfo.cs	25	Active
Error	CS0101	The namespace 'PKHeX.Core' already contains a definition for 'StorageSlotOffset'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\StorageSlotOffset.cs	3	Active
Error	CS0101	The namespace 'PKHeX.Core' already contains a definition for 'StorageSlotType'	PKHeX.Core(netstandard1.3)	C:\Users\Perham\Desktop\PKHeX-master\PKHeX.Core\Saves\Storage\StorageSlotType.cs	3	Active
Error		Couldn't process file Subforms\Save Editors\Gen1\SAV_EventReset1.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_MailBox.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen4\SAV_Misc4.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen3\SAV_Roamer3.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_Link6.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_SimpleTrainer.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_HallOfFame.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_Inventory.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen7\SAV_PokedexSM.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen5\SAV_Misc5.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_BoxLayout.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\SAV_Database.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_Trainer.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_PokeBlockORAS.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen5\SAV_Pokedex5.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_BerryFieldXY.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen7\SAV_HallOfFame7.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Misc\SplashScreen.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen7\SAV_Pokebean.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\SAV_MysteryGiftDB.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_SecretBase.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\PKM Editors\BatchEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_Pokepuff.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen4\SAV_Pokedex4.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_BoxViewer.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Controls\PKM Editor\ShinyLeaf.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_GameSelect.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\SAV_FolderList.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_BoxList.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen3\SAV_RTC3.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen7\SAV_ZygardeCell.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_PokedexORAS.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\PKM Editors\SuperTrainingEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen4\SAV_Underground.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_EventFlags.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen4\SAV_Apricorn.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Controls\PKM Editor\PKMEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen7\SAV_FestivalPlaza.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\PKM Editors\RibbonEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_SuperTrain.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen7\SAV_Trainer7.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Misc\QR.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\SettingsEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\PKM Editors\Text.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Misc\About.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen5\SAV_CGearSkin.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_SimplePokedex.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_PokedexXY.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen6\SAV_OPower.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Misc\ErrorWindow.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen4\SAV_HoneyTree.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\SAV_Wondercard.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\ReportGrid.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file MainWindow\Main.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\PKM Editors\MemoryAmie.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Subforms\Save Editors\Gen3\SAV_Misc3.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
Error		Couldn't process file Controls\SAV Editor\SAVEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	PKHeX.WinForms			
`   please help me and tell me what to do to fix this

**Comment by kwsch** [comment]
I assume you've downloaded the source code .zip; before you unpack it, be sure to unblock the file (right click the zip).
![image](https://user-images.githubusercontent.com/6393368/45932187-83c59e00-bf2d-11e8-95e9-f8f2331b2251.png)

Once you've re-extracted to an entirely new folder, be sure to build the project in the correct order. I think you've got duplicate files somewhere which is causing the first error.

I am closing this since this isn't a PKHeX issue, more a 'how to build a project from files online'.

**Comment by deisuke1234** [comment]
ok i will try
