### ISSUE TITLE
Possible Features Add in New Data for Wondercard Super Training Hack Or Make Medals x30

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#213]
Is it possible to include the hacked Super Training Mega Evolutions to the list in the future for time? Especially since giving a Pokemon gives x36 metals instead of 30.
I included the file below. 

If not possible, then it makes sense to make the medals 30 instead of 36. If you enable Secret Super Training especially if you click on Medals on a Pokemon, it increase it to 36. If there are x36 medals where are the extra 6?

[Hacked Distribution Super Training Cards.zip](https://github.com/kwsch/PKHeX/files/445634/Hacked.Distribution.Super.Training.Cards.zip)

**Comment by kwsch** [comment]
The wonder cards have to be received and used by the save file to unlock
them.

The exact modifications done by the game has not been documented; users can
just inject the wonder card and activate in-game.

**Comment by ricksee** [comment]
I know you can use the wondercard to inject them. But, can the new training levels be edited?

Plus another question if I can, why are there x36 medals when all available super training levels only can provide x30?

**Comment by kwsch** [comment]
There's 30 super training missions and 6 event missions, for a total of 36.

The Super Training Records editor does not include the Event missions:
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Subforms/Save%20Editors/Gen6/SAV_SuperTrain.cs#L20

Not sure if any records are saved for the Event missions.

**Comment by ricksee** [comment]
Can they still be added or if not adjusted so that the Pokemon has 30 but with secret training enabled? Just to make the Pokemon look like it has the medals as it should. The zip file I included are those event missions.
