### ISSUE TITLE
Gen 6+ static encounters with no ability lock get "Invalid: Ability mismatch for encounter"

### ISSUE THREAD

**Issue by nguyenhung9697** [kwsch/PKHeX#2136]
After kwsch/PKHeX@f507ab7, all gen6+ static encounters with no ability lock get "Invalid: Ability mismatch for encounter" with any ability.

**Comment by kwsch** [comment]
Pretty sure it was fixed already: https://github.com/kwsch/PKHeX/commit/4aa44c90c1d46452f71f9d0c7d05a095bd58e19f

**Comment by nguyenhung9697** [comment]
This is my starter litten from a new Ultra Sun save, without any modification. 
[StarterLitten.zip](https://github.com/kwsch/PKHeX/files/2456453/StarterLitten.zip)
My build is from kwsch/PKHeX@f65bc2e
![image](https://user-images.githubusercontent.com/13299300/46617270-8a1b6300-cb46-11e8-825a-12a28ee17d6d.png)
