### ISSUE TITLE
Generation 1 TM moves are illegal in generation 2

### ISSUE THREAD

**Issue by mid-kid** [kwsch/PKHeX#2137]
![](https://media.discordapp.net/attachments/256674336168083457/498996041643851776/unknown.png)
This is but one example of multiple. Moves that are learnable in generation 1 through TM are treated as illegal in generation 2 saves, while they shouldn't.
This bug is encountered with the latest 18.09.11 release.

**Comment by kwsch** [comment]
Not a bug... working as intended!
You have **Crystal met data** which should have been cleared when trading to Gen1.

https://projectpokemon.org/home/forums/topic/47807-not-bug-user-error-tradeback-moves-labelled-as-illegal/?do=findComment&comment=236773

![image](https://user-images.githubusercontent.com/6393368/46640299-f8006400-cb1f-11e8-92b4-0e5dbf7c177c.png)

**Comment by mid-kid** [comment]
Ah, thanks for clarifying!
