### ISSUE TITLE
[Request] Auto Update

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2138]
I know that #199 existed, but I wanted to re-visit the issue, instead of the link to new version, would it be possible PKHeX to update itself without the need to visit any website?

(current update steps)
1. click new update link (takes you to the [Forum Topic](https://projectpokemon.org/home/forums/topic/29182-pkhex-pok%C3%A9mon-save-file-editor/))
2. click another link (to get to actual [Download Page](https://projectpokemon.org/home/files/file/1-pkhex/))
3. click download on (correct version) to get new update
4. unblock zip file (windows possible issue)
5. extract and overwrite previous files 
6. profit?

(possible update steps)
1. prompt for new version
2. click yes/no to update
3. restart application
4. profit?

maybe its just me but having a builtin updater would save time, specifically for people with slow connections, or those with their browsers take forever to load (not mine).

**Comment by kwsch** [comment]
PKHeX is not an install-able program, it's instead a portable application.

With regards to anti-virus, an .exe file that downloads and saves/runs new executables could probably result in higher false positive flagging.

I'd rather not use an auto updater as I'd rather drive traffic to the site that is hosting the download.
Might revisit this after the next set of games are stable-y supported.

**Comment by Ninjistix** [comment]
okay understandable, but what about changing the link to the new version to the actual download page, and not the forum post, (the forum post doesn't show the change log anymore), so its kinda pointless 

all of the information from https://projectpokemon.org/home/forums/topic/29182-pkhex-pok%C3%A9mon-save-file-editor/

is already on the actual download page (minus a few changed topics I guess)

**Comment by kwsch** [comment]
The program links to:
https://github.com/kwsch/PKHeX/blob/b481358e929a5fbf0f8debc3c320184f02570ac3/PKHeX.WinForms/MainWindow/Main.cs#L105

Would have to be changed on the website's side to instead point to the download location rather than the thread.
cc @evandixon

**Comment by evandixon** [comment]
> Would have to be changed on the website's side to instead point to the download location rather than the thread.

Updated to point to https://projectpokemon.org/home/files/file/1-pkhex/

**Comment by Ninjistix** [comment]
cache/cookies need to be cleared in order for the new https://projectpokemon.org/pkhex/ for anyone else that doesn't see the change (tested it using incognito, because it took me back to the old forum page)
