### ISSUE TITLE
[Question] Plugins?

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2139]
Would it be possible to list all of the potential/compatible plugins that are supported with PKHeX or document them somewhere with links to their sources or downloads? (I know quite a few are on the website already but maybe some people don't know they exist, I didn't until a few days ago)

Or would it be possible to list them in pkhex somewhere with their download links (if they wont be included with releases)

**Comment by kwsch** [comment]
Best suited as a sticky in the subforum; someone would have to curate the list.

Maybe private message @PP-theSLAYER or @evandixon on the forums; it might be more feasible to just tag all plugin downloads and point to the category instead.

**Comment by Ninjistix** [comment]
hey @kwsch would you consider this being added to the readme? If so I can open a PR.

https://github.com/Ninjistix/PKHeX/commit/86516df8a642ba6183d2f1b98a58892b43b280e7
