### ISSUE TITLE
Adding the Option to Move More Than One (Select) Pokemon to Boxes 

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#214]
Will it be possible with the new update that we can select more than one Pokemon without having to dump a whole box. Let's say I want to move like 2 or 3 Pokemon from like one Box and I want to move it to another without dumping a whole Box. Or moving select Pokemon from multiple boxes and moving them to a new location.

**Comment by kwsch** [comment]
Duplicate issue: https://github.com/kwsch/PKHeX/issues/195
