### ISSUE TITLE
Pokedex Tab

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2141]
- Would  it be possible to update the pokedex tab with general completion info (eg. gen1 98/151), 
- To have a way to filter unseen/uncaught Pokemon? 
- A way to see what Pokemon were  caught but are no longer owned (in box or party), could be for Pokemon evolved/traded/released etc

could possibly be used to help keep a living dex for every game.

**Comment by kwsch** [comment]
Would require overhauling pretty much every single editor; not going to consider this especially since it's close to a new game release.

**Comment by Ninjistix** [comment]
new game? you mean Lets go EP? (personally idk how I feel about those), but yeah I do think this would have required a considerable amount of time, but eventually it would be a great feature to have, or maybe the 'Dex Storage Report' (not sure how it would function), but thanks for the input/feedback 👍
