### ISSUE TITLE
LINKE/LINKW Mew flagged as illegal in Generation 1 and 2

### ISSUE THREAD

**Issue by aplumafreak500** [kwsch/PKHeX#2142]
https://bulbapedia.bulbagarden.net/wiki/List_of_European_language_event_Pok%C3%A9mon_distributions_in_Generation_I#Pok.C3.A9mon_2000_Stadium_Tour_Mew

```
Invalid: Unable to match an encounter from origin game.
Invalid: Incorrect RBY event OT Name.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Empty Move.
Valid Move 3: Empty Move.
Valid Move 4: Empty Move.

Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: Valid Type A, matches species type.
Valid: Valid Type B, matches species type.
Valid: Catch Rate matches a species from Pokémon evolution chain.
===

Encounter Type: Invalid (Mew)
```

[Mew Pokemon Stadium 2000.zip](https://github.com/kwsch/PKHeX/files/2474575/Mew.Pokemon.Stadium.2000.zip)

Edit: Other cart-era Mew are also flagged as illegal, such as the YOSHIRA Mew. Currently, only the VC Mew is flagged legal (understandably due to the Virtual Console version) but I think that there should be extra checks in place for those who use emulators or who use raw save dumps.

**Comment by kwsch** [comment]
Generation 1/2 (GB) events are not implemented. It's up to the user to verify the encounter data.
https://github.com/kwsch/PKHeX/blob/c8d874462ca07097ebce98e85b9df57a30d1b02a/PKHeX.Core/Legality/Encounters/Data/Encounters1.cs
