### ISSUE TITLE
No Pokemon Cries

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2143]
There is an option to enable Pokemon cries when you hover over them. However, I cannot find the files for the cries anywhere. Where am I supposed to find them as everyone seems to already have them?

**Comment by kwsch** [comment]
Cries are essentially game assets, and aren't required for the program to function. They aren't included in this repository or executable binary (would bloat the program size).

If I recall correctly, there should be a tutorial on the forums, or a google search with "pkhex cries" should give you what you need.
