### ISSUE TITLE
Shiny Korean Gen 4 Pichu

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#2144]
It looks like the PID of the Shiny Korean Gen 4 Pichu was made using a similar technique to the G5MGShiny method, or by luck happens to fall into that algorithm. Either way, it is being misidentified because of it.

**Comment by kwsch** [comment]
Likely have to add a case for PCD when pcd.Gift.PID != 1 or whatever the trigger for random is.

https://github.com/kwsch/PKHeX/blob/93af3e61b7fc12f9d010c7071279107841505359/PKHeX.Core/Legality/RNG/MethodFinder.cs#L732-L760

**Comment by kamronbatman** [comment]
Yeah exactly!
