### ISSUE TITLE
Gen 1 error

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2149]
Tried to "evolve" or actually change an unedited  Kadabra I caught into Alakazam, and got the following two errors

The Below Error, occurs when you click "Yes" to allow Gen 2 trade backs
![capture](https://user-images.githubusercontent.com/12572974/47819601-5b517080-dd31-11e8-8505-6fec34555615.PNG)

The Below Error, occurs when you click "No" to allow Gen 2 trade backs
![capture2](https://user-images.githubusercontent.com/12572974/47819683-a075a280-dd31-11e8-8bb0-9d906686f2ac.PNG)

**Comment by kwsch** [comment]
Correct, you can't change the Catch Rate.
Working as intended.

**Comment by Ninjistix** [comment]
I didn't change the catch rate I changed the species
