### ISSUE TITLE
Please Add Pokemon Box (GCN) Support

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#215]
Hello. I would love if you guys added pokemon box for the gamecube support in pkhex. If you dont know what pokemon box is it was a gen 3 equivalent to pokemon bank and it had many great features that allow you to store thousands of pokemon (Gen 3) at once. I think it would be great if you guys could add support for this game as it would allow people to edit a variety of pokemon from multiple  games that the have all stored on this game at once. I know that most people dont have this game which is why im lucky to have it but I think it would be a cool feature seeing as 3rd gen is aready a thing in pkhex and hopefully Pokemon XD and Colosseum will be shorty too. Thank you and please keep up the amazing work you guys are the best.

**Comment by suloku** [comment]
I think any non-main series game (well, maybe gen 3 is special in that regard...) is besides the scope of pkhex, don't know what the main developers think about it. Certainly just managing boxes could be added, but there's Trigger's PC, a gen 3 only tool that I think is what you are looking for.

I know pkhex is currently becoming the centralized tool, but Trigger's pc has so many gen 3 features that I think it is worth it having both pkhex and Trigger's pc.

But afain, Trigger's pc is open source, so adding Colosseum, XD and Pokemon Box support for pokemon editing might not be a bad idea and requires no further research in save structure.

**Comment by poutros** [comment]
I have suggested colosseum and xd save editing/pokemon importing on #139 and the issue is still oppenned so it seems like it is being considered at least. I know there's also https://github.com/TuxSH/PkmGCTools and it allows for editing the majority of the saves' aspects. And it's also open source.

**Comment by kwsch** [comment]
Added over the course of the past couple weeks.
