### ISSUE TITLE
Certain Pokemon in Colosseum and XD have PID Mismatches

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2153]
I have been playing Pokemon Colosseum and have been using RNG Reporter in order to modify my Pokemon in order to have better, yet legal stats. However, now all of a sudden, my Makuhita, Gligar, and Murkrow are being flagged as illegal, even though their PID an IVs are considered legal by the RNG Reporters outputs.
I will attach the save file.
Steps to reproduce:
1.) Acquire the Shadow Gligar,
2.) Open in PKHex and launch RNG Reporter
3.) Access Gamecube TIme Finder and set the search method to "Gales /Colo"
4.) Set all stats except Special Attack to 31 and set nature to Impish
5.) Select one of the PIDs given and set the Gligars PID and IVs respectively
6.) It still yields a PID-Mismatch
[Pokemon Colosseum My Current Playthrough.zip](https://github.com/kwsch/PKHeX/files/2540490/Pokemon.Colosseum.My.Current.Playthrough.zip)
I haven't finished the game yet, but I would like to know what is going on and how to fix it.

**Comment by kwsch** [comment]
>have been using RNG Reporter in order to modify my Pokemon 

>in order to have better, yet legal stats.

No, they aren't legal. There are "shadow locks" which were recently added. Your edits don't pass the legality check. Working as intended ;)

**Comment by PKMWM1** [comment]
Ok, well can I get some advice on how to do it properly? I can't find any information on it online. How are the PIDs supposed to be generated? Can the article about resolving PID Mismatch be updated to include this information?

**Comment by kwsch** [comment]
There are restrictions for PID generation that weren't checked prior to the latest release; PKHeX didn't check it so it assumed legal. Try using more specialized tools like PokeFinder or Eligor.
