### ISSUE TITLE
[Gen 5] Suggestions and analysis are both nonfunctional

### ISSUE THREAD

**Issue by ketsuban** [kwsch/PKHeX#2159]
## Steps to reproduce

1. Run PKHex. (My version is the latest as of writing this, 18.11.01, and I downloaded it from ProjectPokemon.)
2. Open a Gen 5 savefile. (I used the BW Project 649 savefile also from ProjectPokemon.)
3. Click the warning symbol next to the Genesect sprite at the top of the window and read the dialog box. (Dismiss it afterwards.)
4. Switch to the Attacks tab.
5. Click on Current Moves and read the dialog box.

## Expected outcome

PKHex shows me a legality analysis for step 3 and a suggested moveset for step 5.

## Actual outcome

PKHex shows me two error messages, "Analysis not available for this Pokemon" for step 3 and "Suggestions are not available for this PKM format" for step 5.

**Comment by kwsch** [comment]
The template data that is loaded to fields is just an example. If it doesn't have a valid met version, it can't be analyzed or have a moveset suggested. Analysis depends on origin.
