### ISSUE TITLE
Let's Go Pokédex doesn't register height/weight

### ISSUE THREAD

**Issue by AnalogMan151** [kwsch/PKHeX#2167]
When injecting a new species of Pokémon, it does get added to the Pokédex but the record height and weight does not. Pokémon gifted by NPCs or Mystery Gifts don't increase the "Caught" count but do register record height and weights. 

To replicate: Set a new species that has not yet been registered in the Pokédex and compare that to Pokémon gifted by NPCs (such as the Charmander, Bulbasaur & Squirtle assuming you did not catch any wild ones yet). 

Bonus: Allow modification of catch count for Pokédex entries.

**Comment by kwsch** [comment]
Yup, it's currently marked as todo:

https://github.com/kwsch/PKHeX/blob/cff1ec68fd0be18afe0ed600473007bd1a2a42e4/PKHeX.Core/Saves/Substructures/PokeDex/Zukan7b.cs#L46-L56
