### ISSUE TITLE
Let's Go Eevee

### ISSUE THREAD

**Issue by Elenedeath** [kwsch/PKHeX#2168]
Hello nice and great work for the save editor,
I try your commit cff1ec6 and see difference between debug and release when i put my save on the debug version it's say my pikachu has invalid cp (171 and auto set to 170), due to this the legality mark say invalid but on release version it say legal.

https://prnt.sc/ljh0tv

The second issue is on all version debug, release and the compiled version you submit on projetpokemon.
i catch a Chansey on mont moon when you go down on the first  ladder. You go where you encounter the first rocket sbire and i catch it here.

https://prnt.sc/ljh0go

https://drive.google.com/file/d/1eiaJNDt9l95rNyF_a3dV_GllhHA9TfGh/view?usp=sharing
this is the same save but i maybe it 6h later
https://drive.google.com/file/d/144TDmhzg_64utZsDYPxXKEDnM-5PQnyJ/view?usp=sharing

**Comment by kwsch** [comment]
1) likely a floating point rounding error, can't tell with the information provided

2) already mentioned by changelog, more research is required.
https://github.com/kwsch/PKHeX/blob/cff1ec68fd0be18afe0ed600473007bd1a2a42e4/PKHeX.WinForms/Resources/text/changelog.txt#L6

**Comment by Elenedeath** [comment]
2 sorry for the second point, i dont read the changelog.
i closed this issue because not really usefull
