### ISSUE TITLE
Adding HG/SS Pichu Formes + B/W/B2/W2 Memory Link + Testing Out New Updates

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#217]
Is it possible to add in the Spike-Eared Pichu and Pikachu colored Pichu as a Form Option for Heart Gold and Soul Silver, though make it game-locked and exclusive to these games, since they can't be traded unless it is those two games. I think it comes as a question maker when these Pichu are in those games.

Also, for the Gen V games, can a memory link option be added?

Finally, is there a way to try out any changes to PKHeX in Github for myself to test it out or at least expect an download the updated version on Project Pokemon Link?

**Comment by evandixon** [comment]
`Finally, is there a way to try out any changes to PKHeX in Github for myself to test it out or at least expect an download the updated version on Project Pokemon Link?`

My build system is currently configured to build each PKHeX commit.  Here's a link to the latest one (commit 13669ef7d7cd9630a0f9001cf620edea569efafd):
http://teamcity.uniquegeeks.net/repository/download/PKHeX_PKHeXBuildPr/1527:id/PKHeX%20Build%20314.zip

**Comment by kwsch** [comment]
Closing, question 3 was answered -- 1 & 2 are duplicate with recent threads on the Forums. Please do not duplicate postings... we check both the Forums as well as GitHub Issues.
