### ISSUE TITLE
Pokemon let's go problem with party pokemon

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2171]
Hey. I just edited my Pokemon let's go Pikachu save. I deleted a couple of Pokemon that I didn't need. Then I sorted by Pokedex number. When I went back into the game, my party Pokemon were random Pokemon which I can only assume were the Pokemon in the position of my old party. This forced me to have to go find and re equip my party Pokemon. Thanks

**Comment by sora10pls** [comment]
Wasn't able to replicate this. Deleted a few Pokémon from the end of my Pokémon Box, sorted all by Pokédex No., and my party moved around as intended.
![image](https://user-images.githubusercontent.com/17801814/48686420-e59b3080-eb89-11e8-8c28-11ecee5d9e03.png)
![image](https://user-images.githubusercontent.com/17801814/48686468-1ed3a080-eb8a-11e8-9b62-0d00fae3130f.png)
