### ISSUE TITLE
legality issues in pokemon lets go pikachu and Eevee

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2172]
Hey I just checked my pokemon let's go save and found that my alolan persian which I leveled up from the in game alolan meoth trade is flagged as illegal with "Invalid: Calculated CP does not match stored value". Again, I havent hacked this pokemon and I only leveled it up with rare candies in game.

One other one that I forgot about was both of my pokeball plus mews. I'm assuming that this is because they werent added to the database yet, but I just wanted to make sure. 

Thanks

[053-01 - Persian - 9FF53F1B412C.zip](https://github.com/kwsch/PKHeX/files/2593865/053-01.-.Persian.-.9FF53F1B412C.zip)

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/48524-cp-height-weight-calculations/
