### ISSUE TITLE
feature request: party window for let's go

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2174]
Hey I am not sure if this is possible but I would love if this could be implemented at some point.

I wanted to know if it would be possible to have a "dummy party window" with the same layout as the normal games. The only difference would be that the pokemon listed in that window would be linked to the corresponding pokemon in the boxes. That way if you made any changes to the party pokemon, they would change the actual pokemon which are in the pc boxes. Another reason why this would be great is because right now (from what I can tell) there is no way to see what order, or properly re-order your pokemon without switching the slots of pokemon around.

**Comment by kwsch** [comment]
Would require too much work for little gain; I can probably add a sort-by-party option instead so that they get pulled to box 1 and are ordered 1-6.

**Comment by kwsch** [comment]
Implemented in the latest commit.
https://github.com/kwsch/PKHeX/commit/f27816e622d2a78ffc08b011708834bed384bae1
