### ISSUE TITLE
issue moving party pokemon in let's go

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2175]
Hey I'm not sure if this is intended but it doesn't seem intended. When you move a party pokemon in the pc boxes, the party symbol stays on the original slot that the pokemon was moved from. This in itself might be ok if you were trying to re-order your party but when you switch to another box and then go back to the original box, the symbol disappears and you must put a pokemon in that slot for the symbol to reappear. I'm hoping that you can at least fix this by allowing to set a pokemon as a party member or leaving the party symbol on the empty slot so that people know where to set a pokemon, or possibly implement my idea on #2174 which I think could make let's go fit in a lot better with pkhex. Thanks

**Comment by kwsch** [comment]
Working as intended, manual swaps are up to the user.

**Comment by NinFanBoyFTW** [comment]
ok but could you at least make it so that the party symbol stays on the empty slot when you switch back and forth on different boxes

**Comment by NinFanBoyFTW** [comment]
When I move a party pokemon individually to another slot, the party slot symbol stays on the original slot alone with no pokemon present. That is fine from what you have told me. The problem is that, if I leave that slot empty and switch to a different box number, then switch back to the first box, the party symbol is missing and you cant tell which slot is meant for the party member unless you put a pokemon back in that particular slot. So what I am saying is that would you be able to make the party slot symbol stay active on the screen even if you switch pages and then come back to the first page.

**Comment by kwsch** [comment]
Slot swaps retain the party team mark, and if the box is ever completely repopulated it will ignore the team flag. Saving the file will automatically clear invalid party pointers iirc, so it won't matter in the long run. I'm on the side of `user error` instead of rewriting something for little gain.
