### ISSUE TITLE
[Feature Request] Choose Blank Gen Save

### ISSUE THREAD

**Issue by DJPanda065** [kwsch/PKHeX#2180]
I was thinking that there could be an option in the pkhex settings to open a blank save from any gen. This allows the latest blank save gen to boot like it normally would. However, it would then give people the option to experiment with the other gens if they don''t have a save on hand. I personally do a lot of qr injection in SuMo so it would be nice to have a quick selection of the generations.

**Comment by kwsch** [comment]
Blank / template save files can be downloaded online (pporg has a gallery of these); not really worth building in the extra UI.
