### ISSUE TITLE
Height/Weight & CP don't generate while Building a new Pokemon

### ISSUE THREAD

**Issue by Mitsukiii** [kwsch/PKHeX#2183]
^ Title

> Report:
> 
> Invalid: Calculated Height does not match stored value.
> 
> Invalid: Calculated Weight does not match stored value.
> 
> Invalid: Calculated CP does not match stored value.
> 

Generated .PB7 File: 
[143 ★ - Snorlax - AA6E00000000.zip](https://github.com/kwsch/PKHeX/files/2626381/143.-.Snorlax.-.AA6E00000000.zip)

**Comment by kwsch** [comment]
Did you check the "Auto" checkbox in the main editor?

**Comment by Mitsukiii** [comment]
Seems to work now, recompiled Build and worked fine now, strange.

can be closed.
