### ISSUE TITLE
Evolved Pokemon Building returns Invalid Error's

### ISSUE THREAD

**Issue by Mitsukiii** [kwsch/PKHeX#2184]
Another Issue found:

if u build a Gengar for example it will be flagged as Illegal with Report: 

> Invalid: Unable to match an encounter from origin game.

if u set Latest (NOT) OT: with input it will resolve the Error.

Example File:

[094 ★ - Gengar - 137E2C769223.zip](https://github.com/kwsch/PKHeX/files/2626827/094.-.Gengar.-.137E2C769223.zip)

**Comment by kwsch** [comment]
Working as intended; it's not possible to get a Gengar without trading, which results in having a Latest (not OT) Trainer.
