### ISSUE TITLE
Missing "encounter" for Cianwood gift Shuckle

### ISSUE THREAD

**Issue by amagnemite** [kwsch/PKHeX#2185]
Super minor issue: the gift Shuckle (Shuckie) obtained in Cianwood City is currently flagged as illegal because of an unmatched encounter. 

![image](https://user-images.githubusercontent.com/41340875/49191398-60133f80-f344-11e8-8df1-a3ce750e0f9b.png)

**Comment by kwsch** [comment]
Have you checked the latest commit?
https://github.com/kwsch/PKHeX/commit/a3e7c4837e8b837236c1cff8db0f12d8d17b3d51

Can't tell why yours is being flagged without seeing the pkm data. The two shuckles are different between games.

https://projectpokemon.org/home/files/file/3048-kirks-shuckie/?tab=comments#comment-1424
