### ISSUE TITLE
Starter Eevee Dex

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2186]
![image](https://user-images.githubusercontent.com/39662364/49195792-71e7f780-f3c3-11e8-8a0b-9ffb329e32db.png)

**Comment by iiippppk** [comment]
can't edit?

**Comment by iiippppk** [comment]
pokedex editor can't edit height/weight dex values ?

**Comment by kwsch** [comment]
Sure you can edit it, but the game doesn't set it (Zukan7b.SetDex checks IsBuddy).

Height/Weight was figured out <24h ago :(
https://github.com/kwsch/PKHeX/commit/35a85670b360c566c1dc25c79f2b61df800d87fe

Will work on having it editable soonish.

**Comment by iiippppk** [comment]
![image](https://user-images.githubusercontent.com/39662364/49205073-d79aaa80-f3e8-11e8-9c5a-c135c446069e.png)

when i click Pikachu-Starter
goto 825-Pikachu-8

but when i click Eevee-Starter
goto 133-Eevee
not 8??-Eevee-1?

**Comment by kwsch** [comment]
The pokedex allocates bitflags for pikachu's forms (caps), but not for eevee's forms. It's kinda a leftover from USUM's bitflag allocation.
