### ISSUE TITLE
Have a better way to move Pokémon between boxes

### ISSUE THREAD

**Issue by Ntonio36** [kwsch/PKHeX#2188]
Now unless there's some wicked trickery and black magic I'm unaware of, I'm unable to move a Pokémon between two boxes inside the PC unless I :
- Free a spot in my team
- Move a Pokémon from Box A to my team
- Move that Pokémon to Box B from my team
Can the process become simpler, somehow, anyhow? As far as I recall in game, when you hold onto a Pokémon and hover over the >> sign to move in boxes, you would reach the next box until you stop hovering over these >>. Could this behavior be replicated, pretty please?

**Comment by kwsch** [comment]
Read the shortcuts :)
https://github.com/kwsch/PKHeX/blob/f6508bec5b3cc9ff98e382eb7a2d353528ce69ef/PKHeX.WinForms/Resources/text/shortcuts.txt#L71

I don't like hold-over-button-for-1000ms to change boxes, since it's harder to move multiple things in a row when compared to the popout boxes.

**Comment by Ntonio36** [comment]
OH. I didn't quite mind the shortcuts file, my bad ^^".
But yeah, that's some good trickery you made there.
