### ISSUE TITLE
Question: Will Adding Contest Ribbons Unlock All Ranks for Pokemon Contests?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#219]
If they don't can it be done for games like RSE, Gen IV, and so on including ORAS?

**Comment by kwsch** [comment]
Contest Ribbons only apply to a Pokémon, and not the save file.

In regards to whether or not having a ribbon allows you to participate in a given rank contest -- that's a general gameplay question, akin to someone trading you a 'complete' Pokémon and checking in-game if you can participate.
