### ISSUE TITLE
issue with max hyper training in let's go

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2195]
Hey. I just editing all of my pokemon to hyper train all of them. I went to the modify tab hit hyper train, but when I checked some of my pokemon, the pokemon with IVs of 1 seem to not be hyper trained in those stats. ill include 2 of them as an example
[011 - Metapod - DCAF2F9A6023.zip](https://github.com/kwsch/PKHeX/files/2640535/011.-.Metapod.-.DCAF2F9A6023.zip)

**Comment by kwsch** [comment]
Hyper Training ignores stats <= 1 as they sometimes have reasons for being that low.

Trickroom teams with hidden power, or PIDIV restrictions, or min-damage confusion with a hidden power.

PKHeX doesn't consider substitute numbers (ie 101 HP so seismic toss doesn't break sub at level 100).

Sure the criteria for not maxing a stat could be updated, but that criteria has not been defined by the community.

**Comment by NinFanBoyFTW** [comment]
Ok I understand that, but isn't the whole point of that modify tab to hyper train everyone to the max. If people want a trickroom set or something similar (which is more niche than a person wanting a Pokemon fully hyper trained) wouldnt they either use the batch editor or just fix the Pokemon after hyper training everyone. The problem to me is that you can always change a Pokemon back from something when you know that it has been maxed out (you know that a trick room Pokemon needs to be fixed if you max hyper train using the modify tab) rather than using the modify tab, thinking that all of your Pokemon are maxed out, then having to manually go through your Pokemon or having to go through the batch editor, which pretty much negates using the modify tab to begin with.
