### ISSUE TITLE
issue with max stats in pokemon let's go

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2196]
Hey. I just edited my pokemon again and now when all of my pokemon are at level 100 with max hyper training and 200 AVs in all stats, it seems like the pokemon keep their original stat numbers in game but show the 200 avs on screen.

Ill include a couple of examples but again, it seems that the stats in pkhex (what they should be) are not being applied to the pokemon in game. Thanks.

[124 - Jynx - F0417B70EF7F.zip](https://github.com/kwsch/PKHeX/files/2642380/124.-.Jynx.-.F0417B70EF7F.zip)

**Comment by kwsch** [comment]
Assuming you're batch editing, it's because stats are not updated from the batch editor.
Will add a $suggest for a new property (Stats), to trigger an update of party stats.
