### ISSUE TITLE
Pokemon Black Event Flag Problem

### ISSUE THREAD

**Issue by Kxcii** [kwsch/PKHeX#2201]
My save is from the European launch of Pokemon Black, pulled directly from the cart. Some time around 2013 I caught the in-game Volcarona. When opening my save in PkHex I found that my event flag was curiously unchecked despite the fact Volcarona was definitely disappeared. I tried to check it and load the game (with Volcarona still not present) and then uncheck it and load the game to make Volcarona reappear. This didn't work.

I found this page ( https://github.com/kwsch/PKHeX/issues/1508 ) while researching the issue and the responses mentioned another tab in PkHex's event section and being able to check 0810 and 0812. I took this to mean the Research tab and when I researched the flags mentioned as 'before' they each had a tick and the flag (0812) mentioned for after didn't. When ticking this flag from the Research tab the tick did appear on the first tab next to Volcarona disppeared and likewise ticking that makes 0812 appear ticked. (if you can tell, I don't really know an awful lot about this tab).

I've also noticed that when the event is manually ticked or otherwise investigating the flags 0810, 0348 and 1173 under the Research tab showed that each would appear with a tick next to them.

This might sound similar to the previous problem but where that user wanted to have his or her flag accurately reflect the fact that Volcarona was caught -- something I believe I could do too by ticking 0812 under the Research tab -- I actually want to have Volcarona appear again. Checking and unchecking the event flag didn't work. So here I am, with no real idea how to get this Pokemon to be encounterable once again. 

[POKEMON B.zip](https://github.com/kwsch/PKHeX/files/2649661/POKEMON.B.zip)

Attached is my save in zip form, directly outside the room in which Volcarona spawns.

**Comment by Kxcii** [comment]
"Have you tried leaving 810 unticked, then entering the area?"

Mission successful.

So in order to get the flag to correctly show caught, leave 0812 checked. In order to encounter Volcarona again, leave 0810 unchecked. All of that works.

Not sure why the game failed to check 0812 itself, or why when you uncheck the event in the Flags tab it doesn't uncheck 0810 itself, but thankfully we've worked around that.

**Comment by kwsch** [comment]
Probably PKHeX is just referencing the wrong flag ID (812 instead of 810). Will update to fix the flag ID later today; thanks for reporting & confirming!
