### ISSUE TITLE
Crossover saves

### ISSUE THREAD

**Issue by designgears** [kwsch/PKHeX#2203]
If I take my eevee save and move it over to pikachu I still have eevee on my head and in the play screen. The only thing wrong is the model, sounds are fine, image in menu is fine, loading save file shows pikachu.

Edit: I went thru and changed everything over to pikachu in pkhex as well, under each pokemon and trainer info.

**Comment by kwsch** [comment]
There's more version specific data that's not documented.
This isn't really a PKHeX issue; there's too many unknowns in what has to change in the save file.
