### ISSUE TITLE
Pokemon Gen 7 Can't have super training data for Colosseum Pokemon?

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2204]
For some reason, even though this legal Smeargle from Pokemon Colosseum is being flagged as illegal for participating in Super Training, which I was able to do in Gen 6 because I sent the Smeargle to Gen 6 to complete all the super training regiments. (Doing a personal quest to get as many Ribbons on one Pokemon as possible). Yet, PKHeX is flagging my Smeragle as illegal despite being from gen 3 and hence, would have had access to Super Training.
![error pic2](https://user-images.githubusercontent.com/20786416/49663838-1d6cf980-fa0d-11e8-875e-255c35f18d9f.png)

**Comment by kwsch** [comment]
Bank's data transfer clears these two super training flags on PK6->PK7 conversion.

https://github.com/kwsch/PKHeX/blob/d84ceabe937bbe3c463c72109d947510887f2e03/PKHeX.Core/PKM/PK6.cs#L566-L571
