### ISSUE TITLE
Incorrect Legality Flagging

### ISSUE THREAD

**Issue by UnderdarkFox** [kwsch/PKHeX#2211]
PKHeX is identifying Murkrow and Honchkrow as illegal with the relearn move "Punishment" despite it being a new egg move for it in USUM (and the one being flagged was indeed bred on the newer games).

**Comment by DJPanda065** [comment]
Actually it was more of an error on GF's part as getting Punishment as an egg move for it is impossible. The only way it "could" be possible is you need a male mandibuzz to pass it on to a female murkrow/honch. As it is not possible to get a male Mandibuzz you can't breed Punishment onto a murkrow.
