### ISSUE TITLE
Feebas fished from land not finding proper frame

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#2214]
Per this thread: https://projectpokemon.org/home/forums/topic/48850-hi-i-just-captured-a-feebas-and-it-comes-out-like-fishy-why-is-it/?tab=comments#comment-239060

dji captured a Feebas on Ruby while fishing on land and it came up fishy (frame could not be found). All of them that were fished from land came up fishy but the ones that were fished from water did not.

There are pictures in that thread that show possible land points.

**Comment by kwsch** [comment]
Per my comment:

> they're only 'Fishy' until they're worked on again

I'm not interested in resolving this in the short term; but pull requests upgrading things will be accepted.
