### ISSUE TITLE
Gen3 surfing pikachu

### ISSUE THREAD

**Issue by Franches** [kwsch/PKHeX#2217]
Here is the event pkm Yokohama Pikachu (surfing pikachu) in gen3 (RSE, FRLG) which is currently missing in the Mystery Gift database. It cannot pass the legality test which I think is an error.

[025 - ピカチュウ - EA76B289B2D9.zip](https://github.com/kwsch/PKHeX/files/2714157/025.-.-.EA76B289B2D9.zip)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1873
