### ISSUE TITLE
Possible Change: Super Training Time Format to Min:Sec

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#222]
Is it possible for Super Training time to be edited in a different format? Such as instead of having a time like 148.222 it can be in min:sec format like 2:12 or something. 

Can the target time can be added so that it would be a little easier to know what to put what time is equal or greater than the target time?

**Comment by kwsch** [comment]
Yes it's possible, but no, it's not realistic. The numbers are stored as floats and it's up to the user to know that there's 60 seconds in a minute...
