### ISSUE TITLE
issue with special unicode characters

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2221]
Hi. Im not sure if you are aware of this but for a really long time now (6-12 + months) when I use PKHeX the special unicode characters for things like the shiny icon are boxes instead of just the normal icon. I have tested this on over 10 computers and it is the same on all of them running windows 10 1703 and above. This also effects the files in windows when exporting pokemon. Because of this I thought it was a windows problem and when I did some research I found out that apparently they have been removing fonts and changing certain fonts (I think to move to more modern standards like emoji but it may also be a glitch) because of this I wanted to know if it would be possible to switch PKHeX over to using either these emoji characters or some other standard that is still being supported readily (especially since this also effects the pokemon files that you export with the shiny symbol and not just in the PKHeX UI). Thanks.

**Comment by kwsch** [comment]
possibly an operating system configuration issue instead, works fine for me:
https://superuser.com/questions/336197/unicode-characters-suddenly-start-displaying-as-boxes-in-some-applications

If the unicode characters aren't available, they show as boxes.
It should be noted that the Pokémon font does use some special unmapped characters (like Pk Mn) that won't be visible outside the program.

**Comment by NinFanBoyFTW** [comment]
I know its an issue with windows 10, but the problem is that this is how the operating system comes configured now. The 2 main machines that I use were recently started from scratch on the latest build on windows 10. My point is just that if you don't change some of these special unicode characters you may start to have more and more people having this issue as time goes on, as again, the 2 main computers that I use were just restarted on the latest build of windows 10 (I think your computer works because you probably have been upgrading it from a build of windows where it worked just fine).

**Comment by ReignOfComputer** [comment]
Known issue.
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/missing-unicode-star-after-update-to-2018-october/aa912568-6893-4788-9ce0-7f85c28df51e

**Comment by ReignOfComputer** [comment]
This has been fixed in Windows Update KB4476976. https://support.microsoft.com/en-sg/help/4476976/windows-10-update-kb4476976
