### ISSUE TITLE
change log opens EVERYTIME you open pkhex

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2228]
the change log opens every time i reopen a sav file.

**Comment by kwsch** [comment]
@evandixon 
https://stackoverflow.com/questions/2477576/how-to-persist-changes-in-a-settings-config-file-across-a-file-version-change

Calling Upgrade() absorbs previous version config files, which have an old version string.
https://github.com/kwsch/PKHeX/blob/376cf9fcd96967739317202594d6a0c2f44c99bb/PKHeX.WinForms/MainWindow/Main.cs#L268-L276

Removing Upgrade() doesn't fix the issue, as new updates result in a new config file.
Seems like the correct action is to only upgrade if the user upgraded (showing new changelog).
