### ISSUE TITLE
legality issues with gen 3

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2230]
Hey I was looking at my pokemon database and I saw that a bunch of my pokemon were marked as illegal for various reasons. All of these pokemon are not illegal as I caught them legitimately in game. Also I saw that my vaporeon which was my eevee from xd was marked as illegal for having the fateful encounter mark on it. I saw a while ago that you were editing how that legality check worked but maybe I am missing something. It is a completely legal pokemon and I traded it from xd which did give it a fateful encounter mark. Thanks
[pokemon.zip](https://github.com/kwsch/PKHeX/files/2731494/pokemon.zip)

**Comment by kwsch** [comment]
Works fine on the latest release, probably an issue with recent commits that the test cases didn't cover.
