### ISSUE TITLE
legality issue with gen 2

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2231]
Hey Thanks for fixing the other issues. I just saw this other one for my gen 2 living dex. Im not sure why it says it is not legit but I caught it in game. Thanks
[171 - LANTURN - 8BFC.zip](https://github.com/kwsch/PKHeX/files/2731645/171.-.LANTURN.-.8BFC.zip)

**Comment by kwsch** [comment]
another recent regression:

release:

```
Legal!
===

Valid Move 1: Default move.
Valid Move 2: Default move.
Valid Move 3: Default move.
Valid Move 4: Default move.

Valid: Valid Wild Encounter at location.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
===

Encounter Type: Wild Encounter Super Rod (Lanturn)
Location: Cinnabar Island
GameVersion: C
```
