### ISSUE TITLE
encounter database

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2233]
![image](https://user-images.githubusercontent.com/39662364/50821699-cc815580-136a-11e9-9ca3-2ab0c6ac0870.png)

**Comment by kwsch** [comment]
The IEncounterable generator usually gets you a completely valid mon, but some complex cases like gen3 shadow/event sets have extra requirements that have to be fixed by the user. I don't think it's worth the extra effort at this time.
