### ISSUE TITLE
Bug: No sound on Hover

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#2236]
Hi,

Testing with the latest commit (d-20190108), they only playable .wav sounds are those of poipole and zeraora..

I have set the: Play PKM Slot Cry on Hover
The sounds folder is in the same location as PKHeX.exe and .dll
the sounds folder comes from: Sounds-20180512T084854Z-001.zip

I don't remember when it started happening but testing build 20181202 and build 20190102 the issue is the same, only those 2 .wav files play
I have tested all the .wav files and they play fine in VLC media player

Does it have anything to do with the recent support of the Gen 7b games and Melmetal? 

Thanks

**Comment by kwsch** [comment]
Works fine for me. Nothing has changed for cry playback in months.
![image](https://user-images.githubusercontent.com/6393368/50862026-53283980-134f-11e9-92bf-3b42f3fcfd63.png)

**Comment by PrometheusG** [comment]
I found the reason:
Windows 10 Audio Driver <<< Realtek  HD Audio Driver

I did a clean install in December and forgot to install the audio driver again from my motherboard and I was using window's drivers...

My bad, I am sorry I bothered you
