### ISSUE TITLE
feature request for let's Go and continuation #2174

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2238]
Hey I wanted to know if it would be possible to add a feature like I requested in #2174 only instead of a window that looks like the normal party window, it could be an addition to the right click menu when you right click on a pokemon. I have made up some screenshots using photoshop of what I was picturing/ hope you are able to implement something like this. 

Basically you would right click on the pokemon that you wanted to add to your party, then a pop up would come prompting the user to select the slot that they want the pokemon to be in. Then the party slot would move to the slot with the desired pokemon (The pokemon would not move to the party slot). I hope you are able to implement something like this because it would be great to some kind of party editing in PKHeX itself and since you already added the pictures for the actual slot numbers I think this would work much better.

![untitled-1](https://user-images.githubusercontent.com/21354941/50936375-76311700-143d-11e9-8dbd-12206c7ccd75.png)
![untitled-2](https://user-images.githubusercontent.com/21354941/50936377-77624400-143d-11e9-8ab9-93f464823b63.png)

**Comment by kwsch** [comment]
Context menus can have submenus, so no need to pop up another form and fetch the return value to determine what party slot to inject at.

I'd rather not add box sim functionality at this time (#5 and #195 did end up getting implemented, albeit differently). The slot viewing code is probably the most crufty code in the whole project; I'd rather rewrite things so they're much more sane. It currently fetches the slot offset, then fetches a PKM; all it really needs to do is fetch a pkm at an index.

Swapping into a party slot has multiple scenarios:
* Slot not occupied; needs to slide into lowest unoccupied slot (redirected index).
* Slot occupied; needs to switch with the current occupant (in LGPE, just remove that slot's flags)
* Setting storage flags if appropriate (LGPE only)
* Swapping in empty data or deleting a party member needs appropriate handling

There's two types of slot viewer logic required:
* Array (redirection not performed for LGPE as a choice) = BOX
* List (small count, minimum capacity, rearrange slots on set/del) = PARTY

There's also the currently viewonly types:
Battle Box (Gen5/6): List
GTS: Array (single)
Fused: Array (single)
Pokepelago (not shown): List

I'll keep this in mind for future work, but at this time it's not worth trying to shoehorn something in that will only make things more complicated.
