### ISSUE TITLE
legality issue with gen 6 and 7

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2244]
Hey I just wanted to let you know that on my gen 6 and 7 save files, a couple of my event pokemon are showing up as illegal now. I will include the pokemon below. Thanks
[pokemon.zip](https://github.com/kwsch/PKHeX/files/2754214/pokemon.zip)

**Comment by kwsch** [comment]
All were Pokémon Link encounters; I only checked Celebi :\

Merged em into MysteryGift via https://github.com/kwsch/PKHeX/commit/41a3989b534257b2a7012bffd1d7f5797fa780a6 , will have to see why the encounters aren't matching.

**Comment by kwsch** [comment]
EventGallery simulated wondercards for these events have incorrect data...

Leaving the issue open until things are confirmed fixed for the simulated data.

**Comment by kamronbatman** [comment]
@NinFanBoyFTW, I replaced the WC6 files with WC6Full that should show up as legal.  Please test:
https://github.com/projectpokemon/EventsGallery/commit/2f98a191b0fcd53e6a5d6b7912f30246f73bb5f9
