### ISSUE TITLE
PKHex Mystery Gift OT Illegality

### ISSUE THREAD

**Issue by crzyc** [kwsch/PKHeX#2246]
![pkhex_2019-01-14_18-40-01](https://user-images.githubusercontent.com/18177787/51148350-dfdd6680-182b-11e9-8d24-241d6f7e20d7.png)

This Diancie should not be legal, as it is an event pokemon.

**Comment by kamronbatman** [comment]
@crzyc, can you please hold CTRL and click the checkmark. Then copy/paste the report so we can see what it thinks it is doing.
