### ISSUE TITLE
Sometimes it's not possible to change map location

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#225]
I'm on Crescent isle(467) if that helps. Changing it manually from a save with a different location works and doesn't grey out the options.

**Comment by kwsch** [comment]
Intended; [relevant section of code](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Subforms/Save%20Editors/Gen6/SAV_Trainer.cs#L402-L410) below:

```
            if (!GB_Map.Enabled || SAV.X%0.5 != 0 || SAV.Z%0.5 != 0 || SAV.Y%0.5 != 0)
                GB_Map.Enabled = false;
            else try
            {
                NUD_X.Value = (decimal)SAV.X;
                NUD_Z.Value = (decimal)SAV.Z;
                NUD_Y.Value = (decimal)SAV.Y;
            }
            catch { GB_Map.Enabled = false; }
```

If the game is storing coordinates in a non-standard format, it'll lock you out from defining them.
