### ISSUE TITLE
Compilation on macOS with Visual Studio fails due to missing DLL

### ISSUE THREAD

**Issue by Sparen** [kwsch/PKHeX#2254]
When attempting to build PKHex on macOS with Visual Studio, the build fails with the following:

`PKHeX.WinForms/CSC: Error CS0006: Metadata file '/Users/andrewfan/Desktop/USUM/Randomizing - Software/PKHeX (repo)/PKHeX.Core/bin/Debug/net46/PKHeX.Core.dll' could not be found (CS0006) (PKHeX.WinForms)`

There is a `netstandard1.3` directory that contains a DLL but there is no such directory for .NET 4.6

I'm not a Windows developer and this is my first time attempting to build a Windows program on a mac, so I'm hoping that there's a way to actually build this program.

And yes, I attempted copying and renaming the existing 1.3 but the build was unusable (IE no window/needed to force quit).

Thank you

**Comment by kwsch** [comment]
Before building WinForms, you should do a clean & rebuild

the netstandard 1.3 dll isn't for PKHeX.WinForms, so you'll have to figure out why net46 isn't building.

**Comment by kwsch** [comment]
I'd think it's due to not having the .NET Framework installed on the build machine (Mac), so you'll likely need to boot a Windows VM to build with the Mono flag.
