### ISSUE TITLE
Gen 4 Pokemon not being read correctly

### ISSUE THREAD

**Issue by MichiS97** [kwsch/PKHeX#2257]
So the issue I've opened up earlier today about all my Gen 4 Pokemon being marked as illegal on my Platinum save. That has been fixed, but the Pokemon are still not being read correctly. For example, I have a shiny Shaymin with Timid nature which the latest stable release correctly reads as such, but the latest commit says it's a regular, non-shiny Shaymin with Hasty nature.

As long as the Shaymin is still just in the box, it's shown with the shiny sprite and the little star next to it, but then when I right-click and select "Read" it shows as non-shiny and Hasty in the tabs. 
[Pokemon Platinum.zip](https://github.com/kwsch/PKHeX/files/2849220/Pokemon.Platinum.zip)
Here's the save file.

**Comment by kwsch** [comment]
You'd have to use the latest commit https://github.com/kwsch/PKHeX/commit/9715a08342bd2f1773d12975a70546cdfeb4d087

Works fine now:
![image](https://user-images.githubusercontent.com/6393368/52537957-7a44a300-2d21-11e9-9efb-a6ceade0c35f.png)
