### ISSUE TITLE
[Feature Request] USUM Battle Tree Trainer Catalogue

### ISSUE THREAD

**Issue by Astronox** [kwsch/PKHeX#2258]
When going into Multi Battles, you can choose an NPC partner to accompany you. I think a good addition to PKHeX would be the ability to add, remove, and edit the NPCs and the Pokemon they use. As an example, I've been trying to scout Corless with Mega-Metagross and Porygon2, but it's just not happening. I can never get him with those exact two Pokemon.

This feature request might be too much work, serebii has a catalogue of all the trainers and their possible teams, and it's massive.
https://www.serebii.net/ultrasunultramoon/battletree.shtml

**Comment by kwsch** [comment]
See previous issues regarding research requests:
https://github.com/kwsch/PKHeX/issues/2089#issuecomment-411512169

>Per the forum stickies, I don't do research requests. When things are thoroughly documented on the wiki/save research forum, they can be considered for implementation.

**Comment by SadisticMystic** [comment]
I've done some delving and documentation into this request: https://projectpokemon.org/home/forums/topic/39433-gen-7-save-research-thread/page/4/?tab=comments#comment-240861
