### ISSUE TITLE
Help with text_Forms_en.txt

### ISSUE THREAD

**Issue by Slashcash** [kwsch/PKHeX#2259]
I wanted to use the file text_Forms_en.txt for a project of mine (first of all: can i?) but i am not able to figure out the logic behind it.

Let's say i want to programmatically retrieve the name of a specific form of a specific pokemon, how can i do it? Forms seems to be ordered more or less randomly to my eyes. I explored the codebase but it is huge and i have not been able to find how PKHex parses this file.

**Comment by architdate** [comment]
The project is licensed under GPL v3 which states the following:
```
When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish), that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs, and that you know you can do these things.
```
This allows you to take parts of the code and use it in your own software as you wish. It is open source afterall. As for your question, the functions you are looking for can be found [here](https://github.com/kwsch/PKHeX/blob/383d4b7700d51cd867f80c89c185b6c50b88f52f/PKHeX.Core/PKM/Util/FormConverter.cs) (Ref: GetFormList)

The type list, and form list can be found in the `GameStrings` class. You can explore that class to figure out how the txt file is transformed to make it into a list that is readable by the `PKX.GetFormList` function. Hope this helps you with your project

**Comment by kwsch** [comment]
The text_Forms_\*.txt is exported from the game, and has minor alterations (adding Spiky in an unused section, and cleaning up stuff like Mega-Species to just Mega).

Rather than try to emulate how the game uses personal data + strings to fetch a form name, PKHeX has it hardcoded (with conditions for a given format/gen) to handle all cases with a little more flexibility (instead of showing no string for a default form, it'll show Normal, using type strings instead).

**Comment by Slashcash** [comment]
> `formnames[0]` is always `allforms[speciesID]`, and the game probably iterates upwards (from Bulbasaur) to find the starting index for the rest of the forms (skips to max species ID and over any used form strings for prior species).

So the game retrieves the index of the form name in that file by looking up the PERSONAL file, searches for the formeNum for every pokemon, it skips when formeNum is 1 and adds if is > 1 until it reaches the desired species. Than adds it to MAX SPECIES ID. Is that somewhat correct? It's a bit tricky.

**Comment by kwsch** [comment]
something like
```
~getFormName(string[] arr, int species, int form)

if (form == 0)
    return species;
int index = MAX_SPECIES;
for (int i = 0; i <= MAX_SPECIES; i++)
{
    if (i == species)
        return arr[index + form - 1];
    index += Personal[i].FormeCount - 1;
}
return -1;
```

not worth it in favor of hardcoding, since `Personal` and the string list would differ between games
