### ISSUE TITLE
cant change my trainer name in my secret base (oras)

### ISSUE THREAD

**Issue by jewelforest** [kwsch/PKHeX#2263]
i tried to change it. but clicking "save" will not save my new trainer name. each time i open the menu again, it is my old name again. i dont know why this happens, i could change the name on my trainer card and the ot on my pokemon, but not for my secret base.

**Comment by kwsch** [comment]
You have to set your secret base back to the save file before you save&close the window.

the "<" button

**Comment by cheeeeeeeeeen** [comment]
> You have to set your secret base back to the save file before you save&close the window.
> 
> the "<" button

Even if you press the "<" button, everything else saves **except the trainer name**.
