### ISSUE TITLE
Effect of EVs on RBY/GSC stats is slightly miscalculated

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2264]
For older generations where the mechanic worked differently, PKHeX is taking the conversion from the old proto-EV scale to the modern EV scale as a simple square root operation, and using that to determine what raw stats to display in the stats tab. In fact, what you really have to do is take the square root *then add 1* before doing the division by 4, albeit with a max of 63 stat points there because you don't want to add 1 to 255 and arrive at a 64th.

Essentially, this means that any L100 Pokemon who has an EV bank where the square root amounts to 1 less than a multiple of 4 (and isn't 255) will have PKHeX underestimate that stat by exactly 1 point. But to give a specific, constructive example, we can use the static Lake of Rage Gyarados encounter in GSC, whose IV boxes are guaranteed to be exactly (0)-14-10-10-10. Use some combination of rare candies and day care to increase its level to 38 without getting any experience from battles, then use two HP Ups on it. That fills the bank to 5120, where the square root is 71 and change, so PKHeX will calculate it as 17 stat points and, at L38, a stat of 126 HP. But in fact, the freebie is acting as a 72nd EV, which unlocks the 18th stat point, and you'll be able to see in game that the HP in this case is actually 127.

**Comment by kwsch** [comment]
Added a new test, can confirm behavior doesn't result in 127:

![image](https://user-images.githubusercontent.com/6393368/53380156-4375ac00-3921-11e9-8f0b-92cd4dfea6f8.png)

**Comment by kwsch** [comment]
Closed by #2265 and following commit.
