### ISSUE TITLE
Item bag errors for Colo/XD

### ISSUE THREAD

**Issue by Subject21J** [kwsch/PKHeX#2267]
Using the latest commit  bb2c7e2 of PKHeX opening the item bag for a Colosseum save file displays this screen a couple of time and deletes every item in the bag.
![image](https://user-images.githubusercontent.com/21994182/53685568-47168380-3cd1-11e9-9843-0328cfd056a0.png)

Again using the latest commit, opening the item bag for XD will lead to [this error](https://pastebin.com/z2bTxrq9)

**Comment by PMArkive** [comment]
I cannot reproduce with a Colosseum save and an XD save I found online. 65535 = 0xFFFF so it could be an invalid save dump.

**Comment by Subject21J** [comment]
Did you try the latest commit or the latest release from project pokemon? It works fine on latest release so it's not my save files but if needed I can upload my save files.

**Comment by PMArkive** [comment]
I built pkhex from bb2c7e2 and tested these: [colosseum_and_xd_from_gamefaqs.zip](https://github.com/kwsch/PKHeX/files/2922674/colosseum_and_xd_from_gamefaqs.zip).

**Comment by Subject21J** [comment]
Here are my save files. They come from nintnedont, on a modded Wii. They work fine on the system. If it's a bad save dump it might be time to get a new SD card :/ 
[colo_xd_saves_wii.zip](https://github.com/kwsch/PKHeX/files/2922702/colo_xd_saves_wii.zip)

**Comment by PMArkive** [comment]
Looks like PKHeX doesn't properly read blocks out of GC Memory card dumps ([ReadSaveGameData()](https://github.com/kwsch/PKHeX/blob/bb2c7e22cbd5a0a5ccb72afaaa99fcde84421c5f/PKHeX.Core/Saves/SAV3GCMemoryCard.cs#L306) doesn't read the linked-list of blocks).

I would suggest using Dolphin's GameCube Memory Card Manager for now to export/import the save out of the memory card dump but I had an error on save import...

**Comment by Subject21J** [comment]
PKHeX alters the size of the save file when exporting .gci save files. Simply open a save file ( I used the save files from @PMArkive ) and exported the save file without editing anything. The size of the save file will increase (384KB to 504 KB) thus unable to use Dolphin's MCM to import. Deleting the extra data with HxD allowed me to import it back. This doesn't happen in the release on pp.org so something got messed up between now and then. I'll just use PKHeX from pp.org for now, just wanted give more info about this issue.

**Comment by kwsch** [comment]
@PMArkive how exactly is it supposed to be reading them?

For the XD memcard, it says (at 0x4000) that the save starts at block 0x05, with a total of 0x2B blocks. PKHeX then yoinks out 0x56000 bytes.

```csharp
        public const int SIZE_G3XD = 0x56000;
        public const int SIZE_G3XDGCI = 0x56040; // +64 if has GCI data
```

**Comment by PMArkive** [comment]
I'm under the impression that GC memcards are (or based on) FAT16.
A file's blocks don't have to be in order and the File Allocation Table (FAT) links to a block's following block... I think...
So an `Array.Copy()` shouldn't work 100% of the time (and in this instance).

https://github.com/GerbilSoft/mcrecover/blob/77bf90722305892f8a26121aafc5654236ee895e/src/libmemcard/File.cpp#L101
https://github.com/dolphin-emu/dolphin/blob/c7373701cc4ad7e3ea223aabb0556386e2671cb3/Source/Core/Core/HW/GCMemcard/GCMemcard.cpp#L649

**Comment by kwsch** [comment]
https://github.com/dolphin-emu/dolphin/blob/c7373701cc4ad7e3ea223aabb0556386e2671cb3/Source/Core/Core/HW/GCMemcard/GCMemcard.h#L296-L314

Seems like the offset for each block would have to be fetched from the table at 0x000A, rather than just copying `n` blocks sequentially.

**Comment by PMArkive** [comment]
It seems the commit https://github.com/kwsch/PKHeX/commit/a385a8481dd838ecd9b8f470deb3f5d8e2689696 "Misc tweak to savefile export" is the problem. It's what causes exported GC saves to increase in size and also for the item errors to occur.

Also [this](http://hitmen.c02.at/files/yagcd/yagcd/chap12.html#sec12.4) says they haven't found non-linear files on a memcard so along with the lack of anyone complaining about Block Maps and such I don't think code should be added for it. [I had wrote some though](https://gist.github.com/PMArkive/a5bf455f27a4061643183acb2c48f6c0/revisions)

Also, [typo in SAV3GCMemoryCard.cs](https://github.com/kwsch/PKHeX/blob/9b783dd047c0f99503e47c39de937e7f782786ce/PKHeX.Core/Saves/SAV3GCMemoryCard.cs#L75). Should be:
` private const int BlockAllocBAK = BLOCK_SIZE * BlockAllocBackup_Block;`

**Comment by kwsch** [comment]
Note: opening the Inventory editor requires cloning the save file (so that any edits can be cancelled).

By skipping the Clone, the Items show up just fine (XD memcard)
![image](https://user-images.githubusercontent.com/6393368/54001134-05d20980-40ff-11e9-8671-adf4c4a7a191.png)

Looks like it's only an issue in writing the save file (possibly related to the bad sizing?)

**Comment by kwsch** [comment]
Turns out cloning tries to create a new SAV3XD directly from the memcard, so any r/w is totally misaligned :)

I should be able to fix it now.

**Comment by Ammako** [comment]
Is the save file size still meant to increase like it does?

> PKHeX alters the size of the save file when exporting .gci save files. Simply open a save file ( I used the save files from @PMArkive ) and exported the save file without editing anything. The size of the save file will increase (384KB to 504 KB) thus unable to use Dolphin's MCM to import. Deleting the extra data with HxD allowed me to import it back. This doesn't happen in the release on pp.org so something got messed up between now and then. I'll just use PKHeX from pp.org for now, just wanted give more info about this issue.

Newest stable is from March 11, so these commits should have been included, but the save file still increases in size to 504 KB making edited save files unable to be loaded in Dolphin without first deleting the extra data.

I'm not sure if that's intended, so I thought I'd point it out. If it matters, I use GCI folders for saving, so I just have the .gci files directly instead of having to mess with import/export with virtual memory cards. Length is 393,280 bytes (for Colosseum), PKHeX also removes the first 0x40 bytes when saving the file (which would bring it back down to exactly 0x60000), but without that 0x40 header, the save file is not recognized.

**Comment by kwsch** [comment]
@Ammako it was fixed after the last release
https://github.com/kwsch/PKHeX/commit/41bc3f6182d3e0fc8e5d837e2bd994fb1e61f29c
