### ISSUE TITLE
[Feature Requests/Ideas?] primary and secondary order/multiple pokemon scanner

### ISSUE THREAD

**Issue by SonicPrower** [kwsch/PKHeX#2268]
I've collected all the Pokemon in the national dex in ORAS and transferred all of them to Sun and then to Ultra Moon so I have 15 boxes full of Pokemon, that's excluding legendary, starter, Alolan, Pokemon with Mega evolution, Pokemon that are shiny and have Pokerus AND Ash's Pikachus, I have those in separate boxes. The reason I say this is because I like to sort my Pokemon by level primary and dex secondary, and since the Pokemon have migrated to 2 games, I didn't have time to sort them in Sun so I have 2 boxes full of multiple Pokemon of the same species, the reason I haven't released them is because I thought it would be a good idea to Wonder Trade them for Pokemon not considered caught in Ultra Moon's pokedex.

I realize that there's already an option to sort boxes under the box tab but I'm thinking maybe the option could be a button under the box where the other buttons are and it could open a window showing the primary options on the left and the secondary options on the right, once you click the sort button it opens another window showing all the boxes with 2 buttons that says Separate and Range, Separate sorts the highlighted boxes separately while Range like stretches the highlighter to different boxes sorting the Pokemon altogether.

The multiple Pokemon scanner or Poke-Scanner for short could also be a button, it opens a window scanning the boxes to see if there are multiple of the same species, once it's done it opens a window showing how many species of that same Pokemon there are, when you hover over one of the Pokemon it shows it's all of its attributes and level, once you highlight one of them you have 3 options named Keep, Move or Delete, Keep and Delete is self explanatory while the Move button moves the Pokemon to a different box

Those are my ideas for those options

**Comment by kwsch** [comment]
Hovering over a slot already indicates the stats (IVs/EVs), and you can sort with numerous options to help stratify your box contents. Additionally, the Database window allows you to search by species and delete content inside your box.

Custom stuff like this is best handled by custom code. You'd take an array of PKM data, group by Species ID, then order each group by some sort of potential rating, then only keep the first n from the ordered set. Everything else is placed in the 'trash'.

Seems like a lot of work for very little end-use. Not really worth the many hours required setting up a framework and UI.

**Comment by architdate** [comment]
PKHeX Plugins would be a fantastic way to write the custom code Kurt was talking about. You can write out the code and run it as a plugin to your PKHeX if you wish :) it's the beauty of PKHeX's iplugin interface and open source code
