### ISSUE TITLE
settings panel question / request

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2272]
Hey I just saw some of the new changes for the PKHeX settings panel and they look great. I just wanted to know if it would be possible to implement a restore defaults button on the settings/color pages. I only mention this because I tried changing some color settings and some of the character settings and I don't know of a way to change them back to the default.

**Comment by kwsch** [comment]
The settings are serialized to an xml file which is stored in your `C:\[USER]\AppData\Local\...` folder (projectpokemon), if I recall correctly.

Deleting this file will cause PKHeX to act like it's a fresh install, creating new settings.

I guess I could add a 'reset all' button, which will call `Reset();` on the settings object.
