### ISSUE TITLE
Custom box load feature request

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2275]
Hey I wanted to know if there would be a way to make a new button below the load boxes button called something like "Load Custom Folder" that would let you load from a predefined set of folders the same way you have with the Ctrl F folder section and the corresponding "savpaths.txt" file you make for that. I think this could be a useful feature because you could edit a hypothetical "boxpaths.txt" file and be able to load your living dex or other folder very quickly instead of navigating through the windows folder structure every time. 

I think if it is possible, it could have the same look as the save paths menu.

Thanks
![Annotation 2019-03-29 123610](https://user-images.githubusercontent.com/21354941/55247969-4238e700-521f-11e9-996e-6f366bf67dbd.jpg)

**Comment by kwsch** [comment]
You can just drop the desired folder of pkms onto the main window and it'll import; no need to try and dig through it with the folderbrowserdialog GUI.

https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/MainWindow/Main.cs#L545-L552

**Comment by kwsch** [comment]
Alternatively, you can use the Database for targeted importing.

* Store your pkm repos in the database (separate folders), 
* Do an IdentifierContains advanced search to select the desired folder,
* Load the results to the save file.
