### ISSUE TITLE
Pokemon Let's go language not changing

### ISSUE THREAD

**Issue by CookieXD** [kwsch/PKHeX#2277]
For the lastest release 2019.04.02 the language changing has no effect on either versions.
It always runs the game in English in both games even when the language is changed to something else with PKHeX.

Tested with the Patreon release of yuzu from 2019.04.01 and this saves:
[Pokemon_Lets_go_Starter_saves.zip](https://github.com/kwsch/PKHeX/files/3035068/Pokemon_Lets_go_Starter_saves.zip)

The language in Pokemon let's Go is my native language (German) automatically when I am using no save file, so the Problem may not be with [yuzu](https://cdn.discordapp.com/attachments/430158879465144320/562101760903217152/yuzu-windows-msvc-20190401-patreon.7z).

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/49767-request-a-lets-go-eevees-save-file/?do=findComment&comment=241069

PKHeX reads a value, but it seems like the value does not determine the game language.

It's currently un-researched. I'd assume that there's another value stored elsewhere.
