### ISSUE TITLE
VC transfers with met level==100 should be locked to a particular nature

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2279]
PKHeX already correctly identifies that if you transfer a Pokemon up from a VC game when it's already level 100, it doesn't have any level-ups left to consume that may be necessary for certain cross-gen evolutions like Weavile or Sylveon. However, there's one further refinement that can be made to this case. Due to the XP->level mapping, and the fact that each species only has one valid XP count for L100, they should also be locked into a particular nature if transferred up at that level: either Timid or Hardy as the case may be, depending on experience schedule.

As a corollary of this, if they were sent up with met level==2 (and aren't on the experience schedule used by most 3-stage lines, the one which gives Timid at 100), they're not locked into a nature but can at least be excluded from some natures, due to there being no possible XP count whose mod-25 gives the right nature without leveling up to 3.  
- The 800000 schedule is locked out of having Gentle, Sassy, Careful, Quirky, Hardy, Lonely, Brave, Adamant, Naughty, or Bold if transferred up at level 2
- The 1000000 schedule is locked out of Brave, Adamant, Naughty, Bold, Docile, or Relaxed
- The 1250000 schedule is locked out of Impish or Lax (not that I see any Pokemon in this group that are even possible to catch at level 2 in the GBC era)

Doubtful this codepath would be reached very often, but it's for completeness.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/b51bdc923036caaefee2495470e5c5bb900f15f0
