### ISSUE TITLE
PKHaX Mode: Sorting removes illegal quantites

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2281]
In older versions of PKHax, I could set item quantities above their legal cap. Such as between 1000-65535. However, recently. sorting the bag sets the quantities back to 999, despite the fact that I can still set them to that.

It also sets them just by saving the bag, despite being in illegal mode

**Comment by kwsch** [comment]
Which game?

**Comment by PKMWM1** [comment]
Platinum
