### ISSUE TITLE
Gen 1 In-Game Trade

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2282]
![image](https://user-images.githubusercontent.com/12572974/56062634-092e6580-5d3b-11e9-9259-2b74b2824ae8.png)

Flagged Invalid, https://bulbapedia.bulbagarden.net/wiki/In-game_trade#Yellow

**Comment by kwsch** [comment]
Was added 2y ago:
https://github.com/kwsch/PKHeX/pull/1310/files#diff-4ad277f71b867b03426d36f3f203ed7bR160

While it's true that Machoke's Catch Rate is 90, are you sure the pkm is untampered?

**Comment by Ninjistix** [comment]
yes it is unedited, i loaded the save and saw it was invalid. of all the IG trades that's the only one flagged invalid, i haven't checked red or blue yet
