### ISSUE TITLE
[Bug] PKM conversion prompt is reversed

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#2284]
When attempting to drag/drop an incompatible PKM file to a Box slot, PKHeX alerts the user that you can't convert x format into y format (example, PK7 to PK3). As the title of the issue says, the prompt has it backwards.

Take a look at this example of me trying to set a PK7 onto a Box slot in a B2W2 save file.
It should say "Cannot convert a PK7 to PK5":
![image](https://user-images.githubusercontent.com/17801814/56231038-7730a080-604b-11e9-9fa8-e5105bbd282a.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/f4740bbe52b15e97b56cf4c0fc07bf16c57c5006#diff-7e806f65e144c62297d512fe309005eaR246
