### ISSUE TITLE
Missing or Overwritten Pokemon

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2288]
I'm not sure what is the cause, or the issue, but I've noticed something strange when I edit my Soul Silver Save, once in awhile I'll notice some missing or duplicate pokemon in boxes.

Whenever I move Pokemon from party > to box, and then set or move a Pokemon into party from box, reload the save, play then game then exit game and edit the save again, some Pokemon are missing from the prior edit.

Which causes me to go over the bak file to see what Pokemon are missing or were overwritten

here are some save file comparison's from bak's i just sorted all of the boxes, for comparison but notice after a few of them some Pokemon are gone from the box or are duplicated, and no i did not withdraw or edit any of them.

![image](https://user-images.githubusercontent.com/12572974/56763998-b361b080-6771-11e9-86f5-aa51e4868aac.png)
the circled Pokemon are missing from the backups at a later time, when i noticed they were missing the last two files are from what I managed to restore from the previous backups, but as you can see some are still missing.. and this is from my most recent edits

![image](https://user-images.githubusercontent.com/12572974/56764993-09375800-6774-11e9-9080-24b4a47d3b0f.png)

this is box two, but i can't really compare since stuff is missing from box one which causes the shift to box 2+

![image](https://user-images.githubusercontent.com/12572974/56765434-012be800-6775-11e9-8ebf-b3748ce016c2.png)

I ideally began noticing this because of my habit of sorting all boxes after loading my save, and noticed every once in awhile the total number of Pokemon in the overall boxes keep going down, and also they were some duplicate of some Pokemon that I never caught more than once.

**Comment by kwsch** [comment]
Do you experience this on other games or without doing any sorts at all?

My initial suspicion is the sorting-writer not incrementing slot/array index correctly, but I can't see a missing/extra incrementation in the copyto code (below):
https://github.com/kwsch/PKHeX/blob/a2209701242c741b1b821c8d1ff2e8db55aad65d/PKHeX.Core/PKM/Util/PKX.cs#L847-L870

HGSS shouldn't skip writing to slots, so `count_in should == count_out`...

**Comment by Ninjistix** [comment]
Well I only recently started playing SS, I just finished R/B/Y and didn't have that issue, nor with ORAS (i'm playing AS right now and haven't noticed it) as far as the other gen's not sure.

**Comment by kwsch** [comment]
Assumed to be fixed via https://github.com/kwsch/PKHeX/commit/7c380a29c3529a341b8104e1677d0e74979452b6#diff-b252beba18b73755aefa294218cce557 , can't replicate on latest commit.
