### ISSUE TITLE
Linux mono exception on launch

### ISSUE THREAD

**Issue by julroy67** [kwsch/PKHeX#229]
Hi there,
I am trying to make PKHeX work on mono (my first time with it). I tried to fix all files to let it build on Mono for Linux (see : 6a968f7112492055091f09d89afcb8a33005aa82). But now generated build fails with below exception. I know it is not in your priorities, but any idea on what's wrong ?

> System.TypeInitializationException: The type initializer for 'PKHeX.Main' threw an exception. ---> System.TypeInitializationException: The type initializer for 'PKHeX.PKX' threw an exception. ---> System.TypeInitializationException: The type initializer for 'PKHeX.PersonalTable' threw an exception. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "PKHeX.Resources.resources" was correctly embedded or linked into assembly "PKHeX" at compile time, or that all the satellite assemblies required are loadable and fully signed.
>   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) [0x000a3] in /build/mono/src/mono-4.4.1/external/referencesource/mscorlib/system/resources/manifestbasedresourcegroveler.cs:694
>   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) [0x00110] in /build/mono/src/mono-4.4.1/external/referencesource/mscorlib/system/resources/manifestbasedresourcegroveler.cs:160
>   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, System.Threading.StackCrawlMark& stackMark) [0x000ad] in /build/mono/src/mono-4.4.1/external/referencesource/mscorlib/system/resources/resourcemanager.cs:809
>   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, Boolean createIfNotExists, Boolean tryParents) [0x00002] in /build/mono/src/mono-4.4.1/external/referencesource/mscorlib/system/resources/resourcemanager.cs:753
>   at System.Resources.ResourceManager.GetObject (System.String name, System.Globalization.CultureInfo culture, Boolean wrapUnmanagedMemStream) [0x00085] in /build/mono/src/mono-4.4.1/external/referencesource/mscorlib/system/resources/resourcemanager.cs:1423
>   at System.Resources.ResourceManager.GetObject (System.String name, System.Globalization.CultureInfo culture) [0x00000] in /build/mono/src/mono-4.4.1/external/referencesource/mscorlib/system/resources/resourcemanager.cs:1363
>   at PKHeX.Resources.get_personal_ao () [0x00010] in /home/julroy67/Dev/PKHeX/PKHeX/Properties/Resources.Designer.cs:10053
>   at PKHeX.PersonalTable..cctor () [0x00000] in /home/julroy67/Dev/PKHeX/PKHeX/PersonalInfo/PersonalTable.cs:7
>   --- End of inner exception stack trace ---
>   --- End of inner exception stack trace ---
>   at PKHeX.PKMConverter.getPKMDataFormat (System.Byte[] data) [0x00005] in /home/julroy67/Dev/PKHeX/PKHeX/PKM/PKMConverter.cs:29
>   at PKHeX.PKMConverter.checkEncrypted (System.Byte[]& pkm) [0x00003] in /home/julroy67/Dev/PKHeX/PKHeX/PKM/PKMConverter.cs:156
>   at PKHeX.PK6..ctor (System.Byte[] decryptedData, System.String ident) [0x00030] in /home/julroy67/Dev/PKHeX/PKHeX/PKM/PK6.cs:19
>   at PKHeX.Main..cctor () [0x00000] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:163
>   --- End of inner exception stack trace ---
>   at PKHeX.Program.Main () [0x0000c] in /home/julroy67/Dev/PKHeX/PKHeX/Program.cs:16

**Comment by evandixon** [comment]
Looks like PKHeX's resources weren't properly embeded in the assembly for some reason.

Were there any build warnings?

**Comment by kwsch** [comment]
Removing "Properties." from each resource will cause it to be unreferenced, as there is no "using PKHeX.Properties" at the top.

**Comment by julroy67** [comment]
I am certainly doing it wrong, but before removing "Properties" it gave me an error at build time for each of the lines with "Properties" :

> /home/julroy67/Dev/tmp/PKHeX/PKHeX/MainWindow/Main.cs(67,67): Error CS0234: The type or namespace name `Resources' does not exist in the namespace `PKHeX.Properties'. Are you missing an assembly reference? (CS0234) (PKHeX)

**Comment by SciresM** [comment]
Does your local copy of PKHeX have the personal tables for RBY/GSC, and are they present in your resources.resx? A TypeInitializationException occurs when a static class member fails to initialize, and PKHeX.PersonalTable's only plausible missing resources are the personal tables I added when I merge'd Gen I/II support.

**Comment by julroy67** [comment]
Let's start from scratch again ! I checked out again the PKHeX/master, applied the minimum fixes : 

- 5aae6554b3832c2a5a53ee2b441848bc57770f2e (Files are case sensitive on Linux so let's correct this)
- 6f2ce07c7b8709744003d27bc8d322023f8dfdaa (Use /path instead of \path, otherwise it won't find the files)

Now after building, lauching debug fails and launching release get's this : 
![capture d ecran de 2016-09-05 13-41-02](https://cloud.githubusercontent.com/assets/198724/18246954/8f4f0600-736f-11e6-9cdb-1e79af1e6a07.png)

Error : 
```
System.NotSupportedException: Specified method is not supported.
  at System.Linq.Enumerable+<ConcatIterator>c__IteratorE`1[TSource].Reset () <0x421c8920 + 0x00043> in <filename unknown>:0
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) [0x00066] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/BindingSource.cs:114
  at System.Windows.Forms.BindingSource.ResetList () [0x000a3] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/BindingSource.cs:161
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) [0x0002d] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/BindingSource.cs:78
  at at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.updateOriginGame (System.Object sender, System.EventArgs e) [0x00051] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:2216
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) [0x00023] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:1172
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) [0x000ab] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:1718
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) [0x00000] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:633
  at System.Windows.Forms.ComboBox.SetSelectedIndex () [0x00022] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:980
  at System.Windows.Forms.ComboBox.OnDataSourceChanged (System.EventArgs e) [0x00017] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:963
  at System.Windows.Forms.ListControl.set_DataSource (System.Object value) [0x00051] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ListControl.cs:175
  at System.Windows.Forms.ComboBox.set_DataSource (System.Object value) [0x00000] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:331
  at at (wrapper remoting-invoke-with-check) System.Windows.Forms.ComboBox:set_DataSource (object)
  at PKHeX.Main.populateFilteredDataSources () [0x0019a] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:1338
  at PKHeX.Main.InitializeLanguage () [0x0050a] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:1319
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) [0x00053] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:1081
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) [0x0001c] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripComboBox.cs:307
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) [0x00000] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripComboBox.cs:397
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) [0x00023] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:1172
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) [0x000ab] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:1718
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) [0x00000] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ComboBox.cs:633
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) [0x00000] in /build/mono/src/mono-4.4.1/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripComboBox.cs:176
  at at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () [0x00730] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:133
  at at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () [0x0000b] in /home/julroy67/Dev/PKHeX/PKHeX/Program.cs:16
```

**Comment by evandixon** [comment]
That stack trace looks similar to the one in issue #151.

**Comment by kwsch** [comment]
Font related error:
https://github.com/kwsch/PKHeX/blob/9b6552d3146f73c2a33f5254f0b673f8f08d9891/PKHeX/PKM/PKX.cs#L568-L580

It's ignoring the exception details; it's the first time I've heard it threw an exception :)

As for the Debug linq error, I can agree that it is probably the same type of error in the issue referenced above.

>at PKHeX.Main.updateOriginGame 
Method that is throwing, which uses BindingSource for the Met Locations after fetching from getLocationList. Two possible fixes:

Fix the called method:
private IEnumerable<ComboItem> getLocationList
-> from IEnumerable to List

Fix the variable
var met_list = getLocationList(Version, SAV.Generation, egg:false);
-> add ToList() -- also for the egg_list.

I'd think the second 'fix' would be simplest, less lines changed; however, getLocation**List** may be misleading, and it's still a simple fix to slap on .ToList() on every return statement.

**Comment by julroy67** [comment]
So, as for the font error we have this : 
```
System.EntryPointNotFoundException: AddFontMemResourceEx
  at at (wrapper managed-to-native) PKHeX.PKX:AddFontMemResourceEx (intptr,uint,intptr,uint&)
  at PKHeX.PKX.setPKXFont () [0x0002e] in /home/julroy67/Dev/PKHeX/PKHeX/PKM/PKX.cs:574
  at PKHeX.PKX.get_FontFamilies () [0x00011] in /home/julroy67/Dev/PKHeX/PKHeX/PKM/PKX.cs:560
  at PKHeX.PKX.getPKXFont (Single size) [0x00000] in /home/julroy67/Dev/PKHeX/PKHeX/PKM/PKX.cs:566
  at PKHeX.Main..ctor () [0x005c4] in /home/julroy67/Dev/PKHeX/PKHeX/MainWindow/Main.cs:104
  at at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () [0x0000b] in /home/julroy67/Dev/PKHeX/PKHeX/Program.cs:16
```

And applying your suggested fix, it's working ! (5d9f7bcf4b8a9b44b93a89cf7f287d096ed3d57a)

![capture d ecran de 2016-09-08 19-20-23](https://cloud.githubusercontent.com/assets/198724/18359288/8f84a2ba-75f9-11e6-8a24-73a61e3ac190.png)

**Comment by julroy67** [comment]
After a bit research, the font error seems to be tied to the loading of gdi32.dll which translates to gdiplus.so on Linux, and gdiplus has some undefined symbols : 

```
Mono: DllImport attempting to load: 'libgdiplus.so'.
Mono: DllImport error loading library '/home/julroy67/Dev/PKHeX/PKHeX/bin/Release/libgdiplus.so': '/home/julroy67/Dev/PKHeX/PKHeX/bin/Release/libgdiplus.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/home/julroy67/Dev/PKHeX/PKHeX/bin/Release/libgdiplus.so': '/home/julroy67/Dev/PKHeX/PKHeX/bin/Release/libgdiplus.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport loaded library '/usr/lib/libgdiplus.so'.
Mono: DllImport searching in: 'libgdiplus.so' ('/usr/lib/libgdiplus.so').
Mono: Searching for 'AddFontMemResourceEx'.
Mono: Probing 'AddFontMemResourceEx'.
Mono: Could not find 'AddFontMemResourceEx' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceEx'.
Mono: Probing 'AddFontMemResourceEx'.
Mono: Could not find 'AddFontMemResourceEx' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceEx'.
Mono: Probing 'AddFontMemResourceExA'.
Mono: Could not find 'AddFontMemResourceExA' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceExA'.
Mono: Probing 'AddFontMemResourceExA'.
Mono: Could not find 'AddFontMemResourceExA' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceExA'.
Mono: DllImport searching in: 'libgdiplus.so' ('/usr/lib/libgdiplus.so').
Mono: Searching for 'GdipPrivateAddMemoryFont'.
Mono: Probing 'GdipPrivateAddMemoryFont'.
Mono: Found as 'GdipPrivateAddMemoryFont'.
Mono: DllImport searching in: 'libgdiplus.so' ('/usr/lib/libgdiplus.so').
Mono: Searching for 'AddFontMemResourceEx'.
Mono: Probing 'AddFontMemResourceEx'.
Mono: Could not find 'AddFontMemResourceEx' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceEx'.
Mono: Probing 'AddFontMemResourceEx'.
Mono: Could not find 'AddFontMemResourceEx' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceEx'.
Mono: Probing 'AddFontMemResourceExA'.
Mono: Could not find 'AddFontMemResourceExA' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceExA'.
Mono: Probing 'AddFontMemResourceExA'.
Mono: Could not find 'AddFontMemResourceExA' due to '/usr/lib/libgdiplus.so: undefined symbol: AddFontMemResourceExA'.
```

And next one is that there is no libwinmm : 

```
Mono: DllImport attempting to load: 'winmm.dll'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll': '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll.so': '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/libwinmm.dll': '/usr/lib/libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/libwinmm.dll.so': '/usr/lib/libwinmm.dll.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm.dll': 'libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm.dll.so': 'libwinmm.dll.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'winmm.dll': 'winmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm': '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.so': '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/libwinmm': '/usr/lib/libwinmm: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/libwinmm.so': '/usr/lib/libwinmm.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm': 'libwinmm: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm.so': 'libwinmm.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'winmm': 'winmm: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll': '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll.so': '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/libwinmm.dll.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/libwinmm.dll': '/usr/lib/libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library '/usr/lib/libwinmm.dll.so': '/usr/lib/libwinmm.dll.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm.dll': 'libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm.dll.so': 'libwinmm.dll.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport error loading library 'libwinmm.dll': 'libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
Mono: DllImport unable to load library 'libwinmm.dll: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type'.
```

**Comment by kwsch** [comment]
Likely an issue with Mono finding the correct dll.
http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

**Comment by rickdgray** [comment]
Was this issue resolved? Building in MonoDevelop seems to produce the same result (crash on launch).

**Comment by julroy67** [comment]
@rickdgray You could test my [mono-fix branch](https://github.com/julroy67/PKHeX/tree/mono-fix), it should partially work (Japanese font loading is broken).

**Comment by rickdgray** [comment]
Still seems to have the same issue. No worries though, I can just use VS.

**Comment by evandixon** [comment]
I tried building the latest `master` using Mono Develop on my Linux VM, and got an error similar to what was reported here (except with my cool new exception window).  @julroy67's branch works for me.

Running the mono-built master branch with Wine didn't give an error, but the "Arceus" text in the nickname textbox was not visible, while @julroy67's mono-fix branch did display it.

**Comment by kwsch** [comment]
Merged change in #440. Thanks @julroy67 !

**Comment by julroy67** [comment]
@kwsch Is there something wrong with it ? (Revert e696d84a5a28ceab1ea775e0c04e218691ee2775 some hours after the merge)

**Comment by kwsch** [comment]
@julroy67 I had tested it a little and had no problems, but users reported that it wasn't functioning properly (#444). I tested again and saw the same thing the user did. It looks like the font failed to load.

Maybe it'd be better to have certain compiler flags for different OS builds.

**Comment by kwsch** [comment]
Conditionally implemented in https://github.com/kwsch/PKHeX/pull/697
