### ISSUE TITLE
[Feature Request] Randomize Height and Weight LGPE

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#2294]
Currently the %rand function when used with the below code for the batch editor doesn't change the height and weight of the effected Pokemon. 
Would you please consider adding that functionality?
```
=Box=8
.HeightScalar=$rand
.WeightScalar=$rand
```
Thank you for taking the time to read this, and for all your work with PKHeX!

**Comment by kwsch** [comment]
Works fine with the correct syntax:

```
.WeightScalar=$0,255
.HeightScalar=$0,255
.WeightAbsolute=$suggest
.HeightAbsolute=$suggest
```

**Comment by greenDarkness** [comment]
My mistake. Thank you for the syntax help!
