### ISSUE TITLE
N's Zorua should be legal in BW2

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#2297]
the N's Zorua should be legal with N Sparkle but it shows illegal 
it is a gift pokemon in BW2
![N Zora](https://user-images.githubusercontent.com/18640392/57509102-6f93ad00-7314-11e9-8960-75cda5919d63.png)
i included with N's Zorua.pk5 on a zip
[570 - Zorua - F296345FE3A1.zip](https://github.com/kwsch/PKHeX/files/3165272/570.-.Zorua.-.F296345FE3A1.zip)
i just accepted from Sage Rood in BW2

**Comment by Orionsilver** [comment]
this a message popup 
![image](https://user-images.githubusercontent.com/18640392/57509884-6dcae900-7316-11e9-8dd4-4714e7f564ce.png)

**Comment by kwsch** [comment]
There's currently only 1 N's Zorua encounter 'allowed' by PKHeX:
https://github.com/kwsch/PKHeX/blob/72edb6aa72c51b5edbf7b426b9448cf4ec529361/PKHeX.Core/Legality/Encounters/Data/Encounters5.cs#L650

The one you've provided doesn't have the same PID. Could be that B/W were restricted to a fixed PID, and B2/W2 could then have any PID (but still fixed gender)?

**Comment by Orionsilver** [comment]
sorry about that 
here is the unrolled pid 
[570 - Zorua - F296345FE3A1 unrolled pid.zip](https://github.com/kwsch/PKHeX/files/3167043/570.-.Zorua.-.F296345FE3A1.unrolled.pid.zip)

**Comment by kwsch** [comment]
Same situation; PKHeX is expecting 0xff00001f (male, hasty).

**Comment by Orionsilver** [comment]
thx for the help
