### ISSUE TITLE
Shiny Ash-Greninja false positive

### ISSUE THREAD

**Issue by DaWoblefet** [kwsch/PKHeX#2298]
As far as I know, Ash-Greninja can't be shiny; I was sent this pk7 of a Shiny Ash-Greninja that passes PKHeX's legality checker on the latest release.
![image](https://user-images.githubusercontent.com/23667022/57573024-ebaaf500-73e7-11e9-934c-058500d04266.png)
[658-01_-_Greninja_-_E95300000021.zip](https://github.com/kwsch/PKHeX/files/3169309/658-01_-_Greninja_-_E95300000021.zip)

**Comment by AbdallahKATAIE** [comment]
I'm a bit concerned about this.
Is it possible that there are some other forgotten cases ? if yes, how can I make sure that all my Pokémon are legal even though PkHex says they are ?

**Comment by WardenUnleashed** [comment]
Ash-Geninja's shiny check is a bit trickier than most as Ash-Greninja is not Shiny locked as an event however its PID is overwritten upon transfer to from the demo to SM.

I've written a bug fix for this issue, that will check to ensure that Ash-Geninja is not shiny.
