### ISSUE TITLE
OR/AS Castform and Beldum regression

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2309]
They both give an error, "Invalid: Unable to match an encounter from origin game", despite being unedited. There was no issue with them on the previous stable release of PKHeX, and [this](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Encounters/Data/Encounters6.cs#L288) hasn't been modified since January.

They show as illegal even when generated directly from the Encounter Database, otherwise this Castform shows it, as well.
https://projectpokemon.org/home/files/file/2615-weather-institutes-castform/

**Comment by kwsch** [comment]
ya @sora10pls is submitting a PR soon
IV comparison is checking all IVs == requirements; but some IVs are random (-1) resulting in the comparison failing.
