### ISSUE TITLE
Possible Option: Allow Automatic Backup of Save File to Backup Folder

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#231]
Is it possible to include an automatic backup of the main file with the date added to a backup folder of the user's choice instead of just copying that main and saving it somewhere else or having it as a .bak. Also, we can export any backup we want to override the save file in the 3DS memory card as an option as well. That would be very useful as Powersaves allow that option.

**Comment by kwsch** [comment]
Already exists (although undocumented); create a 'bak' folder in the same folder as PKHeX.exe and it will automatically store a backup when the save file is opened.

https://github.com/kwsch/PKHeX/blob/8e3fbf4e98fc1689aa356f8476b5c20f078ed499/PKHeX/MainWindow/Main.cs#L804-L805
