### ISSUE TITLE
Suggestion: Language transferring from Gen1/2 to Gen7

### ISSUE THREAD

**Issue by marcrobledo** [kwsch/PKHeX#2314]
When transferring a Pokémon from Gen1/2 to Gen7 it's always set to ENG language.
My legit Pokémon Bank transfers were set to ESP (Spanish) by Pokémon Bank since my games and my console are set to spanish.

It would be nice if PKHeX set the language correctly when doing these transfers. I don't know if RBY/GSC savegames have a language byte, but probably Pokémon Bank does it based on console language.

**Comment by kwsch** [comment]
If I recall correctly, Bank transfers are aware of the ROM code, so they know Version & Language. Since they're not stored in the savefile, PKHeX has to make guesses... updating the guessing logic is always nice ;)
