### ISSUE TITLE
Gen 1 to 2 Conversion Bugs

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#232]
I have some bugs when converting my Yellow to Silver Pkm.
- The gender of two Pokémon of my appears as female on PKHeX, and they are male on game (And I know for sure they are male, because I traded then once to Crystal to see)
- When I open my Silver save after converter, the game colors are weird... All the screen is in a Green color.

**Comment by SciresM** [comment]
What pokemon?

Could you share your save before and after the edits that caused the pallette weirdness?

**Comment by JHorbach** [comment]
It's a Venusaur(Konoha) and a Charizard(Vulcano). I deleted the silver save, cause it's a very beginning save, I just choose a starter and talk to Oak. but I can upload my Yellow save when I get home, and I'll try to replicate the palette weirdness,

OBS: Just to clarify, I'm Brazzillian, and I'm not using a translator, so there are a lot of grammar errors.

**Comment by JHorbach** [comment]
I can't replicate to color problem, but this time some Pokémon are Lvl 0 at the Box
Yellow - http://s000.tinyupload.com/index.php?file_id=49526339227767758553
Silver - http://s000.tinyupload.com/index.php?file_id=41307824893239735015
Silver Transfered - http://s000.tinyupload.com/index.php?file_id=31589557665854270988

**Comment by SciresM** [comment]
Bugs should be fixed.

If you can replicate the color issue, please open a new issue and I'll take a look at it :)
