### ISSUE TITLE
pk4 --> pk5 TradedEgg

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2320]
pkm file load in g4 save
![image](https://user-images.githubusercontent.com/39662364/59154391-0a161600-8aa4-11e9-95d1-99e2589c0984.png)

load in g5 save
![image](https://user-images.githubusercontent.com/39662364/59154398-21550380-8aa4-11e9-92de-7d25327a9b25.png)

pkm file
[010 - CATERPIE - A8BF57DCAF59.zip](https://github.com/kwsch/PKHeX/files/3269129/010.-.CATERPIE.-.A8BF57DCAF59.zip)

**Comment by kwsch** [comment]
Fix reverted: https://github.com/kwsch/PKHeX/commit/ab735de2d9c25101169b095cd5adf20c2f141904

Reopening reason:

https://github.com/kwsch/PKHeX/commit/904dc84b5225a19c6cdf819420b3e93404f4942c#commitcomment-34245376

> Transfers from Gen. 4 to Gen. 5 on real hardware don't actually decapitalize names. Only Bank does this, for Gen. 5 --> 6+

> Decapitalized names for transferred unevolved/non-evolvable Pokémon are also not legal, because OT+Gender+ID+SID alone are not enough to allow renaming at the name rater (I just checked.)

More complex logic is required here; need to have a special condition for PK5 if it has the current species in any of the prior gen evolution chains.
