### ISSUE TITLE
Invalid encounter for  origin game

### ISSUE THREAD

**Issue by webgem8** [kwsch/PKHeX#2324]
I caught this Golem as a Graveler on route 12 in Ultra Moon, a valid encounter. This is the first time I have viewed it in PkHeX, and it has not been edited. 

![image](https://user-images.githubusercontent.com/23044269/59319330-27530c00-8c7f-11e9-98cc-cf235605e9da.png)

**Comment by kwsch** [comment]
Doubt it.
You're probably lacking a Handling Trainer, which implies it was never traded, which implies you caught a Golem, which doesn't have an encounter in game.

**Comment by webgem8** [comment]
Nope, this is the first time I have viewed it. Lol I have no shame about hacking, plus who hacks a Golem?

**Comment by webgem8** [comment]
Okay, weird. I tried that and it did fix the issue. How is it that it did not have the field populated if I had just caught it a couple of days ago?

**Comment by webgem8** [comment]
Okay, I think I know what happened. When I traded it to evolve it (which I did lol), I traded it with another game which I hacked to have the same OT/TID/SID. Is it possible that the game got confused when it was traded back, since the "latest handler" and OT were effectively the same?

**Comment by kwsch** [comment]
> I traded it with another game which I hacked to have the same OT/TID/SID.
thus hacks were involved

the game checks the OT details of the receiving trainer. if it matches the PKM data, it doesn't set a handling trainer.
it's essentially impossible to have the same OT and 32bit trainer ID, only possible with cheats.

**Comment by webgem8** [comment]
Since it did not set a handling trainer, handling trainer was left blank. 

Since handling trainer was blank, pkhex flagged as illegitimate because it was a trade-evolved Pokémon.

I agree that it would only have been possible with cheats because as I said, I did hack to make OT/TID/SID equal. 

Pkhex may be working as intended but gf obviously did not plan for identical OT/TID/SID situation
