### ISSUE TITLE
An issue with Gen 1 saves: language and move legality

### ISSUE THREAD

**Issue by yamina-chan** [kwsch/PKHeX#2330]
After the latest update some of my Pokémon are incorrectly flagged for invalid moves, notably moves that are not learned by level up but are core movesets.
![Hitmonlee](https://user-images.githubusercontent.com/39206316/59796276-6adff280-92dd-11e9-812a-92c2c29e3d45.PNG)

Equally, PKHeX has incorrectly begun to flag my Pokémon as French or English when they should be listed as German.

**Comment by kwsch** [comment]
Language: Not stored in PKM data; it's auto detected as a way to auto-fill if you change the species or clear nickname. It's not the same as Gen3+.

Hitmonlee: Depends on its origins. Hold control when checking the legality to get the full report; it's likely there's something else wrong with the data.

**Comment by kwsch** [comment]
Works fine on latest commit:
![image](https://user-images.githubusercontent.com/6393368/59808900-1889dc00-92b3-11e9-89c6-25839a790f12.png)

**Comment by yamina-chan** [comment]
Ah, didn't know about the Language not being stored in the data in that version, haha.
Curiously enough it didn't change it in previous versions, but if the game won't complain about that miss-match then that's fine by me =D
Thanks for the reply too.

The Hitmonlee was a prize Pokémon from Pokémon Stadium, if that helps and thank you for the info about holding ctr when checking. I did not know that was a thing, heh. I'll keep that in mind for the future!
I've run into this issue in the latest compiled .exe version, which I assumed was identical to said commit. If that is not the case and there is a newer version in which this issue is fixed, then all the better. ^^

```
Invalid Move 1: Invalid Move.
Invalid Move 2: Invalid Move.
===

Valid Move 3: Empty Move.
Valid Move 4: Empty Move.

Fishy: Current experience matches level threshold.
Valid: Nickname does not match another species name.
Valid: Valid Type A, matches species type.
Valid: Valid Type B, matches species type.
Valid: Catch rate matches a valid held item from Generation 2.
===

Encounter Type: Egg (Rabauz)
```
You are correct in that the programm assumed it came from an egg even though it never trouched the second gen.

Again, thank you for the reply and I am glad there is a more recent version than I was aware of that fixes this issue. ^^

**Comment by kwsch** [comment]
Stadium cannot communicate with VC save files (sav.dat), hence why it is not giving you a match for the data your Hitmonlee has.
