### ISSUE TITLE
[Bug] Spanish GSC in-game trade Shuckle and Voltorb OT legality

### ISSUE THREAD

**Issue by WEERSOQUEER** [kwsch/PKHeX#2338]
I found another bug, this time with Shuckle's and Voltorb's Spanish OTs due to the characters _Í_ and _Á_ respectively.

While importing them directly into a slot in GSC retains their OT as is, the OT strings will get cut off if set into and from the controls, even if Modify PKM Info is turned off.

Here's an example:

Controls:
![controls](https://user-images.githubusercontent.com/36747884/60156931-9cfcc300-97bb-11e9-9a64-0ab4e1ae1283.png)
PK2 directly dragged+dropped to a slot:
![direct](https://user-images.githubusercontent.com/36747884/60156935-a128e080-97bb-11e9-885a-33d2b9f10abc.png)

Importing their PK2 files into SM/USUM only causes them to lose said characters:

![SHUCKI](https://user-images.githubusercontent.com/36747884/60154724-34f7ae00-97b6-11e9-83f5-cc01254fcd2d.jpg)
![VOLTI](https://user-images.githubusercontent.com/36747884/60154733-37f29e80-97b6-11e9-8574-733923881e6b.jpg)

That being said, trying to edit their OTs to the actual in SM/USUM results in "Invalid: OT from Generation 1/2 uses unavailable characters." While true you can't input those characters in Spanish RBY and GSC, these OTs are an exception.

https://bulbapedia.bulbagarden.net/wiki/User:SnorlaxMonster/In-game_trades_in_other_languages#Generation_II_2

[Spanish.zip](https://github.com/kwsch/PKHeX/files/3328633/Spanish.zip)

**Comment by kwsch** [comment]
Accented A: char code BF
Accented I: char code C9

https://bulbapedia.bulbagarden.net/wiki/Character_encoding_in_Generation_II
Character codes aren't documented for non English / Japanese games...

**Comment by WEERSOQUEER** [comment]
Here's what I've been able to document regarding Spanish characters in GSC:

à: ba
è: bb
é: bc
ù: bd
À: be
Á: bf
Ä: c0
Ö: c1
Ü: c2
ä: c3
ö: c4
ü: c5
È: c6
É: c7
Ì: c8
Í: c9
Ñ: ca
Ò: cb
Ó: cc
Ù: cd
Ú: ce
á: cf
ì: d0
í: d1
ñ: d2
ò: d3
ó: d4
ú: d5

They are all unused except for **BF and C9**, which again, is only used in those 2 in-game trades OTs.

**Comment by kwsch** [comment]
>I just want to point out that the GSC German in-game trade Shuckle "MODRI" throws a legality error upon importing it to SM/USUM due to its OT GABRIELE being too long; it passes fine on GSC, but the OT gender should be restricted to male only as all of them falsely pass due to it being female, more specifically for Crystal if it reads the Met Location of "Can't Tell."

https://github.com/kwsch/PKHeX/blob/71fdd01a930433d04cacc32211f2febbb389ed0b/PKHeX.Core/Legality/Verifiers/TrainerNameVerifier.cs#L119-L125

What exactly happens when the German Shuckle is transferred naturally? (pls pk2/7 me lol)

**Comment by WEERSOQUEER** [comment]
>  
> What exactly happens when the German Shuckle is transferred naturally? (pls pk2/7 me lol)

I put in the German Shuckle that was obtained from both GS as well as Crystal into a Silver and Crystal save, and also for research inserted them again, but with their OT gender set to female (hacked). They all passed, however, the ones with the modified OT gender Transported from my Silver were automatically changed to male by the app, while the ones Transported from Crystal kept the modified OT gender, which is obviously hacked.

I included them in 2 folders: one with the Pokemon inserted into and Transported from Silver and the other from Crystal. (The PK2s with Can't Tell as a Met Location are from Crystal.)

[Shuckle.zip](https://github.com/kwsch/PKHeX/files/3333561/Shuckle.zip)

**Comment by SatoMew** [comment]
> [The Crystal disassembly hasn't logged these either](https://github.com/pret/pokecrystal/blob/2d73d040d16a7836f935a7a6cb2a311aed2ca5a2/charmap.asm#L167-L169) (maybe Spanish isn't on their radar)

All languages will be added eventually. [Here's the current location for the Spanish Crystal character map.](https://github.com/mid-kid/pokecrystal/blob/i18n/version/crystal-es/charmap.inc)
