### ISSUE TITLE
Add legality info for Pokemon20 Victini

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#234]
It's obvious that the Pokemon is deemed illegal by PKHeX just because its info hasn't been added to the legality checker yet.

If you need the link to the .wc6, here's one I ripped directly from my save file after receiving it via Nintendo Network: https://drive.google.com/file/d/0B1IQ2MTU3CGYcDJPLWdnZlZINVE/view

![screenshot_6](https://cloud.githubusercontent.com/assets/17801814/18257808/e71db624-7397-11e6-868a-a4878968145d.png)

**Comment by kwsch** [comment]
Right, PKHeX does not auto-update its wc6 database -- it's manually updated every release.

To expand the database yourself, you can create a 'wc6' folder and toss in the wondercard.

**Comment by sora10pls** [comment]
Cool, didn't know that was a feature! I'll keep the link to the .wc6 active in case you need it
