### ISSUE TITLE
Bug Buzz "Invalid Move" for Butterfree (Pokemon X)

### ISSUE THREAD

**Issue by SilentResident** [kwsch/PKHeX#2346]
Even though Butterfree learns Bug Buzz as part of its levelup, PKHeX gives "Invalid Move" error when trying to give this move to my Butterfree (for Pokemon X).

**Comment by kwsch** [comment]
Works fine.
![image](https://user-images.githubusercontent.com/6393368/60557800-b5109d00-9cfb-11e9-9145-d18c1acf7eef.png)

You're likely modifying data incorrectly.

**Comment by SilentResident** [comment]
https://imgur.com/wEOFSQ2

I am using the May 2019 release of PKHeX which is still the one available for download from the Pokemon sites on the web. Perhaps you fixed it already since then?

**Comment by kwsch** [comment]
Just posing a screenshot does not help anyone.

Double check the current level and the level up requirement for the move.

**Comment by SilentResident** [comment]
You are right. Forgive me for my ignorance, it is below level requirement, but I have never imagined the "Invalid Move" error actually meant it is unavailable because of low level. Keep up the excellent work!
