### ISSUE TITLE
Let's Go! errors

### ISSUE THREAD

**Issue by Narithegreat** [kwsch/PKHeX#2348]
When I open a Let's Go! save into the newest PKHeX it tells me that checksums are invalid and causes the save to become corrupt if I export the save back to my game. 
There is also an issue with the Pokedex, in that language markers for entries are not being read and written properly.

It was working fine on the 20190515 release...

**Comment by kwsch** [comment]
I've uploaded a new exe to the downloads location, ty for reporting :)
