### ISSUE TITLE
Startup errors when trying to set "Blank Save Version" to "Pokemon X"

### ISSUE THREAD

**Issue by SilentResident** [kwsch/PKHeX#2349]
I just downloaded the newest version of PKHeX which was released a few hours ago and when I am trying to set "Blank Save Version" to "Pokemon X", it gives me the following error:

Exception Details:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   at PKHeX.Core.PKX.IsPKMPresent(Byte[] data, Int32 offset)
   at PKHeX.Core.SaveFile.IsPKMPresent(Int32 offset)
   at PKHeX.Core.SaveFile.ClearBoxes(Int32 BoxStart, Int32 BoxEnd, Func`2 deleteCriteria)
   at PKHeX.Core.SAV6..ctor(Int32 size, BlockInfo[] blocks, Int32 biOffset)
   at PKHeX.Core.SaveUtil.GetBlankSAV(GameVersion Game)
   at PKHeX.Core.SaveUtil.GetBlankSAV(GameVersion Game, String OT)
   at PKHeX.WinForms.Main.LoadBlankSaveFile(GameVersion ver)
   at PKHeX.WinForms.Main.FormLoadInitialFiles(String[] args)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=19.7.5.0, Culture=neutral, PublicKeyToken=null
D:\Users\SilentResident\Workshop\Pokémon Workshop\Pokémon X and Y\Tools\PKHeX (190705)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Users\SilentResident\Workshop\Pokémon Workshop\Pokémon X and Y\Tools\PKHeX (190705)\PKHeX.Core.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An error occurred while attempting to auto-load your save file.

**Comment by kwsch** [comment]
I've uploaded a new exe to the downloads location, ty for reporting :)
