### ISSUE TITLE
Weird green screen Gen 2

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#235]
I test the new commit and I transfered a Mew from Yellow to Silver, direct to party with drag and drop, it gives me an "drag and drop error", but it seems to be ok (Pokémon appears at the slot), but when I open the game, the screen is green, but mew is there.
Here the Save http://s000.tinyupload.com/index.php?file_id=77981483982107874788

**Comment by SciresM** [comment]
Could you also post a screenshot of what you mean by "green screen"? I can't reproduce this even using the save file you're providing.

**Comment by JHorbach** [comment]
https://s4.postimg.org/5dqpzyw19/Sem_t_tulo.png

**Comment by SciresM** [comment]
I really can't manage to reproduce this. That's the exact save you're using?

Here's what I see using the same VBA-M build as you using that save and a Pokemon Silver ROM: http://i.imgur.com/YVHfiGZ.png

**Comment by JHorbach** [comment]
Yeah it's the save, but today after reboot my pc the problem is gone, very strange.
