### ISSUE TITLE
Allow PKHaX to Select Pokemon Beyond Normal Ranges

### ISSUE THREAD

**Issue by ReclaimerShawn** [kwsch/PKHeX#2351]
I believe I once brought up a request for this on Project Pokemon Forums, but I'd like to bring it to light again. My original request was to allow people to be able to set IDs for Pokemon between 0-255 in Gen 1 and to set IDs for Pokemon between 0-65535 in Gen 3. This was implemented via SpeciesID1 and SpeciesID3. SpeciesID1 does nothing in Gen 1 games and doesn't solve the problem Species had. Interestingly, SpeciesID3 works perfectly fine. In Gen 2, Species can be used to set an ID between 0 and 255 just fine (they just show up red as invalid in the program, but load in-game). I wanted this because there was a wide variety of Missingno. in Gen 1 and interestingly there are a wide variety of Decamarks in Gen 3. 

In order to fix this, I think you could do one of four things. The first method could be to treat out-of-bounds Pokemon the same way they're treated in Gen 2. The second method could be to treat out-of-bounds Pokemon the same way they're treated in Gen 3 and do something like a SpeciesID for each Generation. The third method could be to give them all a Missingno. icon and just give them all the same base stats, even if that isn't the case to save time but still keep the internal species ID. This way stats can be edited directly even for invalid Pokemon.  The fourth method could be to allow the Pokemon ID to be set in PKHaX via a text-box, just like how you can via something like EXP, then do the same thing with the base stats as mentioned in method 3.

Also, if the same system that was used for Gen 3 could be implemented for Gen 4 or the fixed Gens for Pokemon 0-65535, that'd be great as there's a Hybrid Pokemon for every index at indices 32768-33261 and potentially other Pokemon to find.

**Comment by kwsch** [comment]
Batch Editor.

**Comment by ReclaimerShawn** [comment]
Typing in .SpeciesID1 and/or .Species doesn't work for out-of-bounds Pokemon on Gen 1. I also think it only partially works for Gen 4 as I tried bringing in a Hybrid Pokemon to only get #0
