### ISSUE TITLE
ORAS save now deletes ORAS items from bag

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2352]
This might have something to do with the change from SAV6 to SAV6OA as a classification in 190705. If an ORAS save is loaded, and you click the bag button, it tries to cull out the new items that are obviously legal, like new mega stones (Galladite), primal orbs, and key items like the Pokeblock Kit.

**Comment by kwsch** [comment]
Yap, fixed around the same time you logged the issue :)
https://github.com/kwsch/PKHeX/commit/8f88e630c277da4e68ba2bba17ac8c2a882445c5
