### ISSUE TITLE
SMUSUM errors

### ISSUE THREAD

**Issue by Narithegreat** [kwsch/PKHeX#2353]
In the Trainer editor, there is a problem with the stats "Champion Title Defense" 100 - 199 
they are being read at the wrong offset. This was not a problem in the previous release.

Secondly, Pokemon with an origin game of Generation I and II that have Super Training Medals applied should not be legal.

**Comment by kwsch** [comment]
Thanks; I've reuploaded (again, and again, and again) a new download with the latest commits ;)

**Comment by Narithegreat** [comment]
They will still get the "Legal!" message when applied any of the "DistSuperTrain" Medals. 
This is wrong.
