### ISSUE TITLE
Why does PKHex have no precompiled executable files?

### ISSUE THREAD

**Issue by MaxWhite20062003** [kwsch/PKHeX#2355]
Hi! Sorry bother you but, can I ask why the end-user needs compiles the PKHex? Do not think of it as a criticism or offense, I'm just curious ^^

**Comment by ReignOfComputer** [comment]
https://projectpokemon.org/home/files/file/1-pkhex/

**Comment by MaxWhite20062003** [comment]
> https://projectpokemon.org/home/files/file/1-pkhex/

Wow, that's was fast! Thanks!
