### ISSUE TITLE
(Gen 5?) Pokédex regression

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2356]
Applies to both BW and B2W2. Seen/Displayed flags don't work quite right, right now.

Example, half of the time, if I Set a non-shiny Pokémon in a slot, it sets the Shiny Seen flag anyway. Sometimes, the checkboxes don't actually reflect what is seen in-game. And, certain Pokémon that are supposed to have forms, don't show any in PKHeX (Kyurem, Genie trio, for instance.)

Also, sometimes, Seen/Displayed flags for forms will change, once you click on an entry in the list a few times.

One example:
![Example](https://i.imgur.com/vMzpNXH.png)

**Comment by kwsch** [comment]
I assume you're using the latest commit? I had done some hotfixes since posting the initial 7/5/19 release, so I just wanna confirm you aren't using a deficient exe :)

It's likely a bad read/write offset; can investigate if the latest is still having an issue.

**Comment by Ammako** [comment]
This is the latest stable currently available (f3f4dbb, if I'm not wrong.)

**Comment by Ammako** [comment]
If this helps, 1b02819 is what breaks it.

**Comment by Ammako** [comment]
Still partially broken, I'm afraid. Setting a base (default) form non-shiny Pokémon sets its shiny as Seen. This change is visible in-game for Pokédex entries that don't have multiple forms, and for those who have forms, it must be setting an unrelated flag somewhere which may or may not cause issues.

**Comment by Ammako** [comment]
This has not fixed it either :x

Just in case, I am referring to the checkboxes on the left side, rather than the ones on the right.

I also just realized, that it is actually only for genderless Pokémon, that this happens. All gendered 'mons are unaffected (even if the species is 100% male/female.)
