### ISSUE TITLE
Pokémons can't be accesed in battle revolution

### ISSUE THREAD

**Issue by Mattlau04** [kwsch/PKHeX#2358]
i tried adding a 6 pokémons team to my box 1 and my party battle box but when i run battle revolution it says my stock is empty and so i can't access my boxs and get my team

**Comment by kwsch** [comment]
If box data wasn't originally accessible, your additions won't be accessible either. Nobody has documented the flag to enable that access as far as I know.

**Comment by Mattlau04** [comment]
ah rip :/
