### ISSUE TITLE
Let's Go! Partner moves missing error

### ISSUE THREAD

**Issue by Narithegreat** [kwsch/PKHeX#2360]
I cannot input or view these moves that can be legitimately learned by the Partners in these games using the Move Tutors.

Partner Pikachu:

- Zippy Zap
- Floaty Fall
- Splishy Splash

Partner Eevee:

- Bouncy Bubble
- Buzzy Buzz
- Sizzly Slide
- Glitzy Glow
- Baddy Bad
- Sappy Seed
- Freezy Frost
- Sparkly Swirl

**Comment by sora10pls** [comment]
Moves 729-741 are not included here, though they should be (except Pika Papow and Veevee Volley): https://github.com/kwsch/PKHeX/blob/894237449b27b82644b1ce2a131ba489dbe45cc4/PKHeX.Core/Legality/Tables/Tables7b.cs#L250-L275
