### ISSUE TITLE
Starter 2nd-Encounter Missing for Colosseum

### ISSUE THREAD

**Issue by jjaldridge2009** [kwsch/PKHeX#2367]
If you fail to capture your starter in Phenac City at the start of the game, there is a second encounter in Realgam Tower where you can reclaim it.

My Bayleef was captured via this encounter, but Legality Checker doesn't recognize this in Colosseum.

![image](https://user-images.githubusercontent.com/16225603/62100353-6b19c900-b25f-11e9-8adf-054e176a4b30.png)

**Comment by ReignOfComputer** [comment]
The second encounters in Colosseum are manually entered, this one was missing.

Can you provide the full Met Location text, and/or the .ck3?

**Comment by jjaldridge2009** [comment]
Of course, here's the ck3
[153 - Wendy - 6142B44FFB04.zip](https://github.com/kwsch/PKHeX/files/3446927/153.-.Wendy.-.6142B44FFB04.zip)

**Comment by ReignOfComputer** [comment]
Thanks for contributing, Pull Request made.
