### ISSUE TITLE
EVs limit on Gen I an PC Items

### ISSUE THREAD

**Issue by exegg** [kwsch/PKHeX#237]
Using CTRL + Click on an EV spot caps the limit to 252. Also, the automatic total for this function appears to be 510. EVs are handled differently on Gen I-II, but I know you have that knowledge.

Also, will you enable PC Items editing? I know this is in a very early stage, I'll be testing a lot since I recently started playing the VC releases

**Comment by kwsch** [comment]
PC Items editing? Looks to be fully functional for Gen2 and Gen1. Gen3 doesn't have any PC item editing atm, if that's what you're referring to.

![test](http://i.imgur.com/ajhN3hr.png)

**Comment by exegg** [comment]
Oh... I was confused with the mail icon, which ended to be PC Items! Thanks

**Comment by suloku** [comment]
"Lack of better icon"
How about this one? I used the same Bag items colour since they should store the same type of items.

https://s12.postimg.io/cimdii1t9/Bag_PCItems.png
