### ISSUE TITLE
[Feature requests] Edit Repel value

### ISSUE THREAD

**Issue by namgold** [kwsch/PKHeX#2375]
Add ability to edit the number of repel step remaining. It's annoying that walking 250 step and the repel expired promt.

**Comment by sora10pls** [comment]
Some games have this value documented, but not all. See [Emerald's Event Constants](https://github.com/kwsch/PKHeX/blob/39f5500d8a3e4681ae54074ae9afa1723472cc45/PKHeX.Core/Resources/text/script/const_e_en.txt#L1), for example.

If it isn't documented for every game, then it can't be implemented for every game.
