### ISSUE TITLE
regarding #f0df115 Unable to access PC Box

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2377]
regarding f0df115ccd2d08e52144960a88b0abaebbd31a6a 

I'm having this issue with the PC box in Diamond (in red) vs pearl (in green)
![image](https://user-images.githubusercontent.com/12572974/63633449-b6cd5180-c616-11e9-8e81-11cc7d39c89a.png)

_Originally posted by @Ninjistix in https://github.com/kwsch/PKHeX/issues/2376#issuecomment-524525231_

Solution In Game:
to fix this issue, I had to catch a Pokemon in Diamond then deposit it into the box via in game PC, then save game and reload save with PKHEX to gain access to the PC box.

**Comment by kwsch** [comment]
It's showing red because the box data block is not initialized yet, and is all FF.

**Comment by Ninjistix** [comment]
But pearl loads with the box accessible it's only Diamond that loads with
the red PC box.
