### ISSUE TITLE
lets go sprites?

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#2378]
hi, are there any plans for pkhex to use the new lets go sprites ? like for example this venusaur

x and y
![image](https://user-images.githubusercontent.com/35694052/63662856-0f732a80-c78e-11e9-83be-7a031b2126d4.png)

lets go
![image](https://user-images.githubusercontent.com/35694052/63662828-f0749880-c78d-11e9-9e85-9d3b4d2d7967.png)

my best guess is you update them all when sword shield come out because they are bigger but i want to ask anyway !

**Comment by kwsch** [comment]
Bigger sprites don't fit in the current GUI layout, and only a small fraction have large sprites so far.

It's on my radar, but not necessary at this time.
