### ISSUE TITLE
[Feature Request] Register All Pokégear Phone Numbers

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#2379]
Documentation: https://pastebin.com/46Rk4Uhu

Probably could be added to Misc. Edits; click a button to register all Phone Numbers, which writes 0x00, 0x01, 0x02 ... ... 0x4A starting from offset 0xC0EC.

**Comment by greenDarkness** [comment]
I don't suppose this could be expanded into "Edit Pokegear Phone Numbers" or something to that effect? It would be very useful to be able to toggle which numbers the user would receive calls from; especially in the case a trainer is added accidentally. 
If not BlackShark wrote an AR code which clears all numbers, and adds non trainer numbers. If you'd be willing to add that?
Trainers:
```
00 Mother
01 Prof. Elm
02 Prof. Oak
03 Ethan
04 Lyra
05 Kurt
06 Day-C Man
07 Day-C Lady
09 Bill
0F Bike Shop
18 Baoba
```
https://projectpokemon.org/home/forums/topic/49014-hgss-pokegear-phone-numbers-memory-location/?_fromLogin=1

Thank you for taking the time to read this, and for all your work.
