### ISSUE TITLE
Dump and Load Gen 1 Pkm

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#238]
When I dump and then load Gen 1 Pkm Boxes, they are all wrong, the files names on db appears ok, but even when I try to load one by one it changes species and things...

**Comment by kwsch** [comment]
Thanks @SciresM for fixes:

Fixed [main menu dump boxes (individual files)](https://github.com/kwsch/PKHeX/commit/8b608389eb5c39d89e8f2a56632cee7f610ef99f#diff-5d810c415996899e54bc278b76e34a57R3397)

Fixed [importing pcdata / boxdata](https://github.com/kwsch/PKHeX/commit/b2860ea3de21d45015de51d2631ad82fea285ba5#diff-f9b992d86e08d24910caa8a0da742244R469)

If anything else is still not functioning as intended, feel free to open another issue :+1:
