### ISSUE TITLE
Trainer Info - Adventure Info displayed data does not shows AM/PM on non ENG system language

### ISSUE THREAD

**Issue by fattard** [kwsch/PKHeX#2388]
It seems that the raw data IS correct, but the information displayed might be being affected by system language (probably C# culture info problem).

The below image is for UltraSun save data:

![image](https://user-images.githubusercontent.com/1159052/65112190-38659480-d9b5-11e9-8cdd-905206699ef2.png)

My OS system language is PT-BR, which gives date as DD-MM-YYYY and time data is 24h clock.

The date is correct, but time data does not reflect the correct info.
Game Started should be 01:54 PM (or 13:54 on my system language)
Last Saved would need to be 01:33 AM (which is also 01:33 on my system language).

Not sure if this issue affects ENG system languages at all.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/f507ab70816bad89f6ac3b438beddeb436283df2/PKHeX.WinForms/Subforms/Save%20Editors/Gen7/SAV_Trainer7.Designer.cs#L1052
[tt => AM/PM](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datetimepicker.customformat?view=netframework-4.8). idk why it's not showing AM/PM for you...

It's probably best to change to "HH:mm:**ss**"; 24h clock, and showing the seconds. I'll add a commit in a few hours with this string replacement if nobody else does :)

`"hh:mm tt" -> "HH:mm:ss"`
