### ISSUE TITLE
How to Use PkHeX for Gen 1-5 Games?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#239]
Would I need homebrew for Gen 1 games, something like save_manager to extract the save file? And what about gen 3 games like RSE, are they for ROMs only or I have to buy something for the GBA system? Last but not least, what about gen 4-5?

**Comment by kwsch** [comment]
Closed, PKHeX edits save files and has nothing to do with obtaining them.

The tool you would use depends on the source of the game you are trying to obtain it from. 
* Emulators have the save files readily available
* Digital games (installed) need a digital method of dumping (homebrew or warez)
* Physical games can use a hardware method (dongle) or a digital method.
