### ISSUE TITLE
GameStrings.GetItemStrings does not respect generation after generation 3

### ISSUE THREAD

**Issue by FM1337** [kwsch/PKHeX#2393]
I attempted to call the function to receive the item strings for generation 4 however it returned items that are in generation 7 and LGPE

**Comment by FM1337** [comment]
![image](https://user-images.githubusercontent.com/5448220/65616880-2b870900-df92-11e9-8456-004fca86391c.png)

**Comment by kwsch** [comment]
It's done this way to minimize the amount of allocations done storing duplicate data.

PKM and SaveFile both expose [IGameValueLimit](https://github.com/kwsch/PKHeX/blob/7013d4f0c8ecbfe2cd589f0368fa84d15fa6cb3f/PKHeX.Core/PKM/Shared/IGameValueLimit.cs), which you can use to determine if it's out of bounds or not.
