### ISSUE TITLE
[LGPE - PkHeX latest release] Shiny Voltorb flagged as illegal

### ISSUE THREAD

**Issue by steph9009** [kwsch/PKHeX#2399]
Shiny Voltorb, met wild at level 42 in Power Plant [LGPE], is flagged improperly as illegal, on the latest version of PkHex (didn't try on previous releases, sorry).

It can have random nature and IVs. I think PkHeX is flagging as illegal because of Electrodes static encounters in LGPE Power Plant, with fixed(?) IVs*.

*appreciate if someone can confirm this

**Comment by kwsch** [comment]
Not able to replicate.
https://github.com/kwsch/PKHeX/blob/72aee7540da02b2baab61a95fdefbce16446b65c/PKHeX.Core/Legality/Encounters/Data/Encounters7b.cs#L39-L40
![image](https://user-images.githubusercontent.com/6393368/66661422-d25ade80-ebfb-11e9-8554-d90255ce1e86.png)

**Comment by kwsch** [comment]
Hm, might not have 3 flawless IVs?

**Comment by steph9009** [comment]
of course Voltorb DOESN'T have 3 flawless IVs, is a normal encounter with RANDOM IVs, not static, like i said before.

**Comment by steph9009** [comment]
also, there's NO Voltorb static encounter in LGPE Power Plant, only Electrode.

**Comment by kwsch** [comment]
Thanks for the confirmation :)

The encounter data was initially populated with raw game data; in this case, this encounter wasn't ever exposed for encountering in game:

![image](https://user-images.githubusercontent.com/6393368/66663324-59f61c80-ebff-11e9-931c-f359dd7bbac0.png)

I'll remove the static encounter definition.
