### ISSUE TITLE
New features in RBY and GSC

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#240]
- Adding Rival name .
- Adding  Pikachu friendship in RBY.
- Change IV for DV.
- Icon for badges.

**Comment by JHorbach** [comment]
I can't check right now, but if I'm correct Gen 1 has Egg in Daycare, which was a Introduced in Gen 2.

**Comment by BeyondTheHorizon** [comment]
@JHorbach There is a Day-Care Couple on Route 5 in RBY, to the south of Cerulean City.

**Comment by JHorbach** [comment]
I Know it @BeyondTheHorizon, but there is only, "one slot" at that Gen 1 day care, and you can't breed. As I said, I can't check because I'm not home, but if I remember well, there are two slots in RBY Editor, and a box saying is it has an Egg.

**Comment by BeyondTheHorizon** [comment]
Ah, okay. Sorry, I was confused.

**Comment by sora10pls** [comment]
I can also confirm that the Gen 1 Daycare Tab displays the current Egg Seed, despite Breeding not being introduced until Gen 2. Perhaps that could be removed before looking into OP's other suggestions, @kwsch?

**Comment by JHorbach** [comment]
Gen 2 doesn't have a Daycare tab, and stills IV in stats tab. There also "Randomize IVs" in both generations.

**Comment by kwsch** [comment]
Randomizing IVs/EVs is allowed for Gen1/2 :)

**Comment by JHorbach** [comment]
Sorry my bad, I was trying to say to change IV to DV :S

**Comment by kwsch** [comment]
Trainer/game specific trainer editor to be incorporated in a later release.

Closing this issue as #283 can serve the same purpose, and the rest of the requests for this issue have been dealt with.
