### ISSUE TITLE
VC Electivire and Magmortar legality check

### ISSUE THREAD

**Issue by Rayqo** [kwsch/PKHeX#2403]
Hi,

I observed this issue on mons from VC with exclusive moves.

![1](https://user-images.githubusercontent.com/43747386/66953705-4dd6e880-f05f-11e9-9a42-5ee8c5f18deb.png)

![2](https://user-images.githubusercontent.com/43747386/66953716-516a6f80-f05f-11e9-830a-1dac5214f333.png)

Same with Magmortar but no problems with Rhyperior.

**Comment by kwsch** [comment]
Probably related to the transfer level and the pre-evolutions permitted for the various games it has traveled through.

I'll take a look in a bit.

**Comment by kwsch** [comment]
Not able to replicate:
```
Legal!
===

Valid Move 1: Learned by TM/HM in Generation 1. [Gen1]
Valid Move 2: Learned by TM/HM.
Valid Move 3: Learned by TM/HM in Generation 2. [Gen2]
Valid Move 4: Learned by TM/HM in Generation 1. [Gen1]
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Fishy: Current experience matches level threshold.
Valid: Valid Wild Encounter at location.
Valid: Nickname matches species name.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: History block is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Wild Encounter Grass (Electabuzz)
GameVersion: RD
PID Type: None
```

![image](https://user-images.githubusercontent.com/6393368/66972216-c2525d00-f048-11e9-9299-b167f2c40ec8.png)
[electabuzz and electivire.zip](https://github.com/kwsch/PKHeX/files/3737100/electabuzz.and.electivire.zip)

**Comment by Rayqo** [comment]
I got this with the legality report :  

![3](https://user-images.githubusercontent.com/43747386/67007441-ae116d00-f0e7-11e9-85ff-4fc332fe5f19.png)

I didn't generate this Electivire. I just read my save. I'm on UM and the Electivire is level 15.

**Comment by Rayqo** [comment]
This issue is may be caused by the "Unable to match an encounter from origin game".

The old Electabuzz is from Gold.

**Comment by Rayqo** [comment]
If I change the met level to a value >= 30 (level evolution of Elekid to Electabuzz), the Electivire is recognized as legit.
