### ISSUE TITLE
Gen 7 Wonder Card QR Codes Generating Under Wrong Format

### ISSUE THREAD

**Issue by NoMoreStars** [kwsch/PKHeX#2405]
Gen 7 Wonder Card QR codes generated under the Mystery Gift sub menu display in the wrong format and cannot be scanned to inject a wc7 file using other programs like PKSM as seen below:

[Generated Gen 7 Wonder Card](https://i.imgur.com/esKH8Ge.png)

**Comment by kwsch** [comment]
QR Code importing incorrectly in other programs isn't a problem with PKHeX.

PKHeX imports the QR codes it generates just fine. Relevant logic:
https://github.com/kwsch/PKHeX/blob/f0b320eb28e273312e036b3a571e0161a17f2744/PKHeX.WinForms/Subforms/Save%20Editors/SAV_Wondercard.cs#L293-L354
