### ISSUE TITLE
Suggested current moves error for Mamoswine

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#2406]
![1](https://user-images.githubusercontent.com/24352145/67412449-42a13100-f5fa-11e9-86e6-b4672a4297c4.png)
![1-1](https://user-images.githubusercontent.com/24352145/67412461-47fe7b80-f5fa-11e9-9abd-7c33edcae2ec.jpg)
In this situation, when I apply suggested current moves, I get a legality error like this
![2](https://user-images.githubusercontent.com/24352145/67412282-f655f100-f5f9-11e9-9f91-6722a15195f1.jpg)
![2-1](https://user-images.githubusercontent.com/24352145/67412634-9ad83300-f5fa-11e9-9744-1c96af3c4ae9.jpg)

**Comment by kwsch** [comment]
Worth noting that the 4 moves are illegal due to Mamoswine not learning any of them naturally, and one has to be unlearned in order to know Ancientpower for evolving.
![image](https://user-images.githubusercontent.com/6393368/67535973-d2da8700-f689-11e9-9a66-63a285868ce5.png)
