### ISSUE TITLE
Increase Experience but not level

### ISSUE THREAD

**Issue by RaXorX** [kwsch/PKHeX#2408]
Any possible way to increase the experience without increasing the level, so it's possible to have the gained attacks from the level up. Right now, increasing the exp increases the lvl in PkHex too (if you try decreasing the lvl it will decrease the exp too) but doing this, the stats do change but not the attacks which the Pokémon would otherwise gain on level up.

Would be better if the experience was only increased after gaining experience with battle.

**Comment by kwsch** [comment]
The PKM's current level is derived from the experience points the PKM has earned. There's no way to disassociate the two.

https://bulbapedia.bulbagarden.net/wiki/Experience

You can always add an amount to the Experience so that the value doesn't match the level threshold, so you'll be part-way to leveling up.

**Comment by RaXorX** [comment]
As far as I can see it's just how it is implemented in the code. Whatever the experience box displays it automatically converts it to level. I think the best way to accomplish this would be to display the level based on the actual experience of the Pokémon and use another variable/box to enter the new experience points which doesn't trigger the level.

What you suggested works if you want to increase the Pokémon one level at a time which was not my intention. Right now, I made a slight alteration which displays the pokemon's level to 1 whenever you change the experience. This way my Pokémon returns to being level 1 while setting the experience points to what I need them to be, and after the first battle it has, everything else works as intended to be as I stated above. I get the desired level, I get the attacks too. 

The way I see it, "There's no way to disassociate the two." this is not entirely true. It's possible with temp variables and you only need one to set the experience without triggering the level. I would have done that if not for having to fiddle through VS for hours to figure out why the heck I didn't have the build button at all. 

(Apparently for some reason, trying to import a sln file just doesn't show me the button, and I had to create an empty project them import the other project over it just to keep the button from not disappearing. Weird shit going on. Took me 5 hours just to figure that out, while thinking something must be wrong with the .net framework.)

**Comment by kwsch** [comment]
Please read the documentation on PKM structures. When a pkm is stored in your box, there is no data saved to indicate the level it is currently at, only the amount of experience it has. Level is recalculated by the game whenever it is placed in your party.

For that reason, the two controls are interlinked; updating one will update the other.

If you want to modify party stats manually, there's HaX mode and also the Batch Editor to set properties individually.
