### ISSUE TITLE
Encounter Mismatches

### ISSUE THREAD

**Issue by johndu132** [kwsch/PKHeX#2409]
Hi there.  I noticed that there are no options to mark Pokemon as if they were caught in swarm in Diamond, Pearl, and Platinum versions.  However, Pokemon that have been caught in the swarm are marked with two errors:
"Invalid: Unable to match an encounter with origin game"
"Invalid: Encounter Type does not match encounter"

Also, Pokemon caught in the Trophy Garden are also marked this way.

**Comment by kwsch** [comment]
Works fine for PKM generated by PKHeX, are you experiencing this with legitimate pkm?

![image](https://user-images.githubusercontent.com/6393368/67819778-def08b00-fa73-11e9-8b7f-756ed2809f45.png)

![image](https://user-images.githubusercontent.com/6393368/67819786-e748c600-fa73-11e9-8dce-66df98b87afd.png)

![image](https://user-images.githubusercontent.com/6393368/67819795-efa10100-fa73-11e9-9d40-44d7eb86ab25.png)

**Comment by johndu132** [comment]
Yes, however how do I view that list?  I've also attached a few images showing my issues.
![Capture](https://user-images.githubusercontent.com/57157765/67822949-d3f32600-fa86-11e9-9817-7451dd9844c3.PNG)
![Capture2](https://user-images.githubusercontent.com/57157765/67822950-d3f32600-fa86-11e9-91cc-3b176762f4f5.PNG)
![Capture3](https://user-images.githubusercontent.com/57157765/67822952-d48bbc80-fa86-11e9-8d6b-99e95f4c0335.PNG)
![Capture4](https://user-images.githubusercontent.com/57157765/67822953-d48bbc80-fa86-11e9-98c3-08e2da3d4ace.PNG)

**Comment by kwsch** [comment]
Hold control when clicking on the legality indicator

If you could, pls upload an example PKM (don't modify PID); you can always PM me on the forums if you'd rather not post it publicly.

**Comment by johndu132** [comment]
I've attached a zip with all the Pokemon I have a problem with, and I don't mind posting publicly.  If I've run into this problem I'm sure I'm not the only one, so they could just look here for the answer.
[Pokemon.zip](https://github.com/kwsch/PKHeX/files/3786666/Pokemon.zip)

**Comment by kwsch** [comment]
Eevee: Platinum Eevee is listed at level 22 https://bulbapedia.bulbagarden.net/wiki/Trophy_Garden, but yours is level 16 (matches DP level range)

I'll have to look at this in more detail later... pretty sure this isn't a romhack save due to the obtained dates :P

**Comment by johndu132** [comment]
I don't really do romhacks.  What I do is use Action Replay to get legitimate Pokemon or to take out the grind that Pokemon requires.  I'm not one of those guys that becomes an inconvenience using cheats.

**Comment by kwsch** [comment]
Depends what the AR code is doing. If it is forcing certain encounters, then that would explain why certain things are being flagged as invalid; the AR doesn't force things legally.

**Comment by johndu132** [comment]
True, but the way I do things is actually forcing legitimate encounters.  There does tend to be some problems, but I'd say I have a good 98% success rate at what I do.

**Comment by johndu132** [comment]
I just wanted to check in and see if you may have found anything.

**Comment by Ammako** [comment]
Reobtain these Pokémon without using any AR codes and see the results. There's not much point in reporting "legal" Pokémon being shown as illegal, when you've used cheats to obtain them in the first place.

There is conflicting info online about met levels for some of them, if you're trying to create legal Pokémon using AR you can't really rely on that. For example, Serebii listing Phanpy as met Lv. 18 in Platinum, vs Lv. 5 in DP, while wikis show Lv. 5-7 for all three versions. Obviously one of the two sources are wrong, and if you don't know any better then the only way you'll know which one is right is to obtain them legitimately.

That being said, I'm fairly certain your Eevee at least is not legal.

![image](https://user-images.githubusercontent.com/43770697/68067204-f2bd1b00-fd19-11e9-828a-e402b90919fc.png)

Note that Trophy Garden special Pokémon show up in encounter slots 6 or 7. This PID/IV is valid for several other encounter slots, but highly unlikely to be valid for 6 or 7. If you are concerned about legality, don't use AR.
