### ISSUE TITLE
Sprites for gen

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#241]
I'm thinking it could be interesting if the pokemon sprites changes over the generations. If I load a pokemon red sav, PKHeX shows sprites for gen 1 and so on.

**Comment by suloku** [comment]
I think it bloats the programm unnecessarily, but now I feel like asking: when gen 7 is released (and datamined), will all sprites be updated to gen 7?

**Comment by sora10pls** [comment]
I don't think they'd be updating too many sprites in Gen 7, if any. The only sprite changes between X/Y and OR/AS (that I can remember off the top of my head) were Steelix, Treecko, Blaziken, and Diancie.

PKHeX still uses the X/Y sprites for all of those except Diancie, so when Gen 7 is released, all that's really needed are the sprites for new Pokemon :P

**Comment by JHorbach** [comment]
I don't think it would be good, as gen 1 and 2 sprites are so "blah". If Gen 7 change the sprites I think it will be good to update them at PKHeX.

**Comment by kwsch** [comment]
Gen1/2 sprites are not per-species which removes the first glance identification. Plus, they aren't the same dimensions (40x30).

As for future game sprites, we can't know until the games are out. If the sprites are very different the program would probably need a slight redesign.
