### ISSUE TITLE
Key Items removed from Bag

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2410]
In Pokemon FireRed and Leafgreen, if you open the bag, I get an error stating that all my Key Items will be removed upon saving the bag and if you try to give yourselves the items back, only Ruby & Sapphire's key Items are selectable despite none of them being available in FRLG.
![ErrorPic](https://user-images.githubusercontent.com/20786416/68066522-fe4f1880-fcfe-11e9-9d72-ab663edc09b3.png)

**Comment by kwsch** [comment]
```
            LegalKeyItems = Version switch
            {
                GameVersion.RS => Legal.Pouch_Key_RS,
                GameVersion.E => Legal.Pouch_Key_E,
                _ => Legal.Pouch_Key_RS
            };
```
lol find the mistake
