### ISSUE TITLE
View/set FireRed Farfetch'd (CH'DING) produces incorrect results

### ISSUE THREAD

**Issue by The-Fireplace** [kwsch/PKHeX#2412]
**Describe the bug**
When I view then set the Gen3 Farfetch'd (named CH'DING) received from an in-game trade, the name on the set data is truncated to CH and the invalid data warning is shown.
I searched through the issues first to see if it had already been reported and the only thing that appears to be similar (It was even the same trade pokemon that issue's author mentioned) is #1474 .
PKHeX 20190919

**To Reproduce**
1. Open a FireRed save with CH'DING in your party/box
2. Right click CH'DING and click view
3. Right click a slot and click set
4. See that the set data is invalid

**Expected behavior**
I'd expect the set data to be the same as the data I was viewing.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/5914284/68562372-fc780a00-040e-11ea-9a03-e907196e54cc.png)
After:
![image](https://user-images.githubusercontent.com/5914284/68562407-17e31500-040f-11ea-80d9-115890a0ab8c.png)

**Additional context**
No other data appears to have changed, and as far as I can tell, the pokemon's data appears perfectly valid.
[083 - CH - 1BB0151943D7.pk3.zip](https://github.com/kwsch/PKHeX/files/3829787/083.-.CH.-.1BB0151943D7.pk3.zip)
One other thing to note that seems to be related, when I do Tools > Showdown > Export Party to Clipboard, then try to import it with Tools > Showdown > Import Set from Clipboard, it gives me an error:
![image](https://user-images.githubusercontent.com/5914284/68562595-02221f80-0410-11ea-9204-7f12e2835ec2.png)
After clicking OK, the data being viewed looks like this. Note that almost every field is different from the original:
![image](https://user-images.githubusercontent.com/5914284/68562637-254ccf00-0410-11ea-8f7f-f194646d0f40.png)
The clipboard data:
https://pastebin.com/Ufwr1nLn

**Comment by kwsch** [comment]
Part 1: probably a string encoding issue

Part 2: importing set probably didn't fix checksum, resulting in the new pk3 decrypting itself again

will investigate later; it's sw/sh prep season :P
