### ISSUE TITLE
Loading any Pokémon from PKM Database crashes - PKHeX 19/09/19

### ISSUE THREAD

**Issue by SuperOkazaki** [kwsch/PKHeX#2413]
**Describe the bug**
When loading any .pkm file from the built-in database (.pk1 - .pk7), an unhandled exception occurs and prevents the pokemon from being loaded.

**To Reproduce**
1. Load a supported save file (I used USUM)
2. Click on 'Data' then 'PKM Database"
3. Right-Click on any PKM file
4. Click 'View'
5. Unhandled Exception occurs

**Expected behavior**
The Pokémon becomes loaded into the main PKHeX window

**Screenshots**
Here is a screencapture succinctly capturing the issue:
https://gfycat.com/leafyhastygannet

**Additional context**
Here is a PasteBin of the unhandled exception: https://pastebin.com/ZQw6quNp

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/55096-unhandled-exception-error-pkmdb/
