### ISSUE TITLE
USUM: Checksum problem

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2415]
**Describe the bug**
Checksum detection for USUM is broken, and results in save files that won't load.

**To Reproduce**
1. Load a known good save file (compare against latest stable)
2. Verify Checksums in SAV tab
Optionally:
3. Save the file
4. Reimport save file (or load on Citra)
5. "The saved game data is corrupted."

**Expected behavior**
For checksum detection to be correct, and to not result in corrupted save files.

**Screenshots**
![image](https://user-images.githubusercontent.com/43770697/68899733-4b1fef80-0700-11ea-8690-c7e3b4cd011e.png)

**Additional context**
Seems to work fine for SM.

**Comment by kwsch** [comment]
Probably has something to do with clearing memecrypto data prior to verifying the checksums.

**Comment by kwsch** [comment]
Am able to see it on other saves in the same region (block 24). Will investigate what is dirtying the contents...
