### ISSUE TITLE
Sword and Shield Legality issues 

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2416]
Hey just wanted to let you know that I am loving the new PKHeX and I was so happy to see you update it with Sword and Shield this quickly.

As for the legality, I know everything is very preliminary right now but I thought I might as well post some of my pokemon that are showing up as illegal so you can either see whats wrong, or so we can check this later after more legality checks are put in. Thanks again
[001.zip](https://github.com/kwsch/PKHeX/files/3853728/001.zip)

**Comment by deadair3210** [comment]
if examples are needed I have about 3 boxes of Pokemon and roughly a 3rd of them are being reported with various errors, can dump them just say the word

**Comment by SciresM** [comment]
@deadair3210 send them to me -- I'd guess most are static encounters that need tagging.

**Comment by deadair3210** [comment]
[Shield Pokemon Boxes.zip](https://github.com/kwsch/PKHeX/files/3853939/Shield.Pokemon.Boxes.zip)
Here you go, all of them are either normal captures or pokemon given to the player

**Comment by AnalogMan151** [comment]
A few more things:
https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Tables/Tables8.cs#L218
I'm pretty sure this is supposed to be `{(int)Species.MrRime, 1},`

Next, the Rage Candy bar is listed an an unobtainable item here:
https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Tables/Tables8.cs#L341
but I have one in my inventory. Can't be positive on where I got it but pretty sure it was either a reward from one of the battle cafés or by spending watts with an NPC.

**Comment by PandaUnit-TWL** [comment]
I've got about 10 false flags for legality too. What they all have in common is they were either obtained in a raid battle or in the wilds. Even so not all of my wild area catches show up illegal, I think all (or most) of my raid catches have. The legality checker can't match any of their origins.
[Flagged.zip](https://github.com/kwsch/PKHeX/files/3855652/Flagged.zip)

**Comment by ReignOfComputer** [comment]
Raid and over-leveled Pokemon in Wild Area are not checked for yet.

**Comment by PandaUnit-TWL** [comment]
Ah, ok. Well as long as I'm here thanks for all the work you put into this guys.

**Comment by architdate** [comment]
Just noting down the issue with the darmanitan forme being 0 which causes invalid form outside of battle error

**Comment by ReignOfComputer** [comment]
[Check.zip](https://github.com/kwsch/PKHeX/files/3862098/Check.zip)

Condensed Pokemon from above and RoC's PC that are still illegal after latest additions. These are still illegal because:
- Cross-boundary Pokemon (e.g. Pokemon from Rolling Fields that was encountered in Dappled Grove)
- Nest Encounter
- Impossible to add to Static Encounter list (e.g. more than 1 Rhyhorn as a Static Encounter, varying levels, but contributed Rhyhorn is at post-game Level)

**Comment by architdate** [comment]
Another thing to note would be that formes of silvally are also not recognized as valid encounters. (Normal type holding something is recognized, but a fire forme holding fire memory isn't recognized)

**Comment by AnalogMan151** [comment]
In regard to TM and TR taught moves showing as illegal is this line here:
https://github.com/kwsch/PKHeX/blob/686f69484d022b5a1c82664ccbe64bf5e1593006/PKHeX.Core/Editing/CommonEdits.cs#L580
Supposed to reference `Legal.TMHM_SWSH` instead of `Legal.Pouch_TMHM_SWSH`?

**Comment by ReignOfComputer** [comment]
[Legality Research.zip](https://github.com/kwsch/PKHeX/files/3873211/Legality.Research.zip)

Condensed Pokemon from above and other sources that still fail Legality Checks, classified.

**Comment by ReignOfComputer** [comment]
[Legality Research.zip](https://github.com/kwsch/PKHeX/files/3882787/Legality.Research.zip)

Latest version, grouped up into:
- Cross Boundary
- Gigantamax
- Invalid Move
- Other Wild Area
- Raids
- Shedinja

**Comment by KurushiiEX** [comment]
Cleffa/Clefairy/Clefable are coming up as Hidden Ability not available, but their abilities are listed as Hidden multiple times in the raid encounter list Kaphotics tweeted.

**Comment by kwsch** [comment]
@KurushiiEX The initial list was incorrect. The actual value translation was figured out after the games were played more thoroughly.

**Comment by BoxerMatt** [comment]
[094 ★ - Gengar - A83360149692.zip](https://github.com/kwsch/PKHeX/files/3899845/094.-.Gengar.-.A83360149692.zip)

I'm getting some flags even on the latest update. Can someone tell me why most of my G-max obtainable are getting the "Gigantamax Flag Mismatch" ?

**Comment by swampatha** [comment]
@BoxerMatt Change met level from 40 to 60.

**Comment by BoxerMatt** [comment]
Omg, it worked @swampatha ! How does this works exactly? All of them should have lvl 60 for met? Cuz it fixed my zard too!

**Comment by BoxerMatt** [comment]
Serebii don't have that lvl info @swampatha

**Comment by swampatha** [comment]
@BoxerMatt Gmaxes are only available from tier five, which are level 55-60 when caught.

**Comment by BoxerMatt** [comment]
That's amazing! Is there a way for them to have egg moves? I've heard I didn't need to breed to get those moves this gen, you just have to have a blank space for it to learn, is there a way for Gmax Corvi to get roost/defog?

**Comment by piapple1** [comment]
Hi, I am generating a female indeedee and it says legal then I try and trade online and it is blocked. I tried playing with location and level met to match a den and that did not work either. Origin game was set to sword each try because I was trying to match an OT. Here is the pokemon file. any help would be great thanks
[876-01 - Indeedee - D0D33C72010B.zip](https://github.com/kwsch/PKHeX/files/3900745/876-01.-.Indeedee.-.D0D33C72010B.zip)

**Comment by PP-theSLAYER** [comment]
I'll like to add that these should be illegal:
Bred Bulbasaur line
Bred Squirtle line
Bred Kantonian Meowth line (Kantonian Meowth cannot be bred in SWSH; Always Galarian version)
Bred Alolan Meowth line (Alolan Meowth cannot be bred in SWSH; Always Galarian version)
Bred Kantonian Ponyta line 
Bred Kantonian Farfetch'd line
Bred Kantonian Weezing line 
Bred Hoennian Zigzagoon line
Bred Johtonian Corsola
Bred Unovan Darumaka
Bred Unovan Yamask
Bred Alolan Starters

**Comment by AnalogMan151** [comment]
Bred Kanto Meowth and bred Unova Yamask are possible in the game. You can get a Unova Yamask via trade and then you can breed it by having it hold an Everstone while breeding. The result will be a Unova Yamask. Kanto Meowth can be obtained via mystery gift and bred the same way.

**Comment by PP-theSLAYER** [comment]
Yeah I realized my mistake. The rest wouldn't be, tho.

**Comment by Emzademon** [comment]
Noticed today that importing a Rotom-Mow set caused Leaf storm to be ticked as a TR relearn move and flagged as illegal.

Rotom-Mow @ Sitrus Berry
Ability: Levitate
Level: 50
EVs: 248 HP / 228 Def / 20 SpD / 12 Spe
Modest Nature
IVs: 0 Atk
- Protect
- Will-O-Wisp
- Volt Switch
- Leaf Storm


Not sure what interaction importing sets has but I've noticed it also clears the TR relearn moves, not sure if this was intentional or not? Wouldn't it be better to have it auto "give all"  like how it auto levels a Pokemon to level 100, gives all PP Ups and such?

**Comment by kwsch** [comment]
@Emzademon works fine on latest commit, was fixed via https://github.com/kwsch/PKHeX/commit/22a5df518109d5107f6e6eef38c4544b5277b8a9

**Comment by kwsch** [comment]
Closing this catch-all as it has served its purpose. For reporting future issues, please categorize them and describe /why/ they are actually legal so that their (awkward) mechanics can be handled.
