### ISSUE TITLE
Issue with PKHeX loading Sword Shield Saves after editing

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2417]
Hey I just edited my save and saved it. Then When I went to re edit it, it worked one time but now whenever I try to open this particular save file it says "Invalid save file loaded. Aborting.". I will attach the save below. Thanks
[main.zip](https://github.com/kwsch/PKHeX/files/3853737/main.zip)

**Comment by kwsch** [comment]
Fixed via https://github.com/kwsch/PKHeX/commit/c87674fd6d906d024d8cfd28a6380a5835e10b72
Revert to backup.

Game was set incorrectly via the trainer editor.

For advanced users, you can recover by setting the Game to the correct version ID when you've reached this method in `Main.cs`:

![image](https://user-images.githubusercontent.com/6393368/68988440-4a648780-07ec-11ea-9187-bb8c3e9881b0.png)
