### ISSUE TITLE
Issue with sword and shield pokemon blacklist

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2418]
Hey I was just looking at all of my save files to check over legality and other possible bugs. I saw that my gen 7 and gen 7 Lets go saves have the pokeball symbol on many of the pokemon, and then I realized that it was the sword and shield blacklist effecting the gen 7 saves. Ill include a screenshot. This effects gen 7 and gen 7 Let's go. Thanks.

![Annotation 2019-11-15 213652](https://user-images.githubusercontent.com/21354941/68986710-0d01f900-07f0-11ea-9a33-725ff35b1543.jpg)

**Comment by kwsch** [comment]
Heh, it shouldn't be using the large sprites when the generation is less than gen8...

**Comment by kwsch** [comment]
Fixed via https://github.com/kwsch/PKHeX/commit/4630bb83c81cdf385bca3f36947b7741f2f2ea9e .
