### ISSUE TITLE
Pokemon obtained from dynamax raids in SwSh are flagged as missing encounter

### ISSUE THREAD

**Issue by eip618** [kwsch/PKHeX#2422]
**Describe the problem**
as per title

**To Reproduce**
1. catch dynamax pokemon from raid
2. import save file into pkhex
3. caught dynamax mon is invalid due to missing encounter

**Expected behavior**
pokemon caught in-game should be legal

**Comment by architdate** [comment]
There are undocumented wildarea regions I believe cuz nobody has documented which of the 92 nests is which location ID which is why the legality is not perfect (the extra comment in `199570b12d682e4e6c4fc7f25287d6c9c7b07854` clarifies this) :)

**Comment by eip618** [comment]
gotcha, thanks, sorry, i'll close this if you are already aware of it

**Comment by kwsch** [comment]
I'm sure someone else will open an issue anyway ;) ;)
