### ISSUE TITLE
Support for unpacking/re-packing BNK and PCK files

### ISSUE THREAD

**Issue by Alexowo** [kwsch/PKHeX#2423]
I would like (if possible) to suggest adding support for unpacking and packing the various BNK files in Sword and Shield's sound directory (wwise)
I say this because at the moment there isn't any tool to do this and I'd love to know how to pack things into a .PCK specifically (I'm trying to make a music swap)

Also being able to unpack and manage BNK files would be good but I have no idea how challenging something like this would be, would you have to add support for loading a whole Pokemon Sword/Shield romfs dump?

**Comment by kwsch** [comment]
Unrelated to PKHeX, this is not a ROM editor.

pkNX doesn't interact with sound data. I've already posted how to unpack pck/bnk sound archives via quickBMS scripts.
