### ISSUE TITLE
Can't generate a Pokemon from FRLG that came from an egg and transferred to Gen 7

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#2426]
**Describe the bug**
I'm trying to create a Pokemon that was hatched on FRLG (For this example, Bulbasaur), but then I get an error telling me to set his Egg Met location to None, which then sets him as not hatched from an egg.

**To Reproduce**
1. Create a legit Bulbasaur that came from FRLG on a gen 7 save file
2. Set him as hatched from an egg
3. PKHeX will default the met location to Day-Care Couple, PKHeX will then tell you "Invalid Egg Location, expected none."
4. Setting him to (None) and then putting him in a box will cause him to not be from an egg anymore

**Expected behavior**
Either the Pokemon should be from a Day-Care couple (Or any other place where it will be legit) or somehow figure out what's wrong and fix.

**Screenshots**
![2019-11-16 14_56_02-PKHeX (20191115) - SAV7USUM_ maincomplete  Aether (US) - 201906021922](https://user-images.githubusercontent.com/25017422/68993472-3ae34e00-0881-11ea-94ed-0b254ae34cf3.png)

**Comment by kwsch** [comment]
Gen3 Pokemon do not have an egg location.
