### ISSUE TITLE
Open .DUC Files

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#243]
Is it possible to have Pkhex to open action replay .duc files. I have one, but it rejects it and gives me an error. Is it possible to convert it to .sav and then to .duc?

**Comment by evandixon** [comment]
Try this:
https://filetrip.net/nds-downloads/utilities/download-uniquegeeks-offline-save-file-type-converter-2-6-alpha-f26025.html

@kwsch: I can provide the source code for the above tool if you're interested in adding this functionality.

**Comment by ricksee** [comment]
@evandixon What would be the target format so that I can use PkHeX?

**Comment by ricksee** [comment]
@evandixon @kwsch If you want, I can provide you a .DUC file so that you can look at it.

**Comment by evandixon** [comment]
You should target a raw save file.

**Comment by ricksee** [comment]
@evandixon I converted it back to .DUC but it gives me a black screen.

**Comment by kwsch** [comment]
Can also try
http://www.shunyweb.info/convert.php

Not related to PKHeX (only gonna support common formats).
