### ISSUE TITLE
Pokédex Editor: Gigantamax Forms and their Pokédex Descriptions

### ISSUE THREAD

**Issue by igniscitrinus** [kwsch/PKHeX#2430]
**Describe the bug**
Gigantamax form flags aren't set on entries that otherwise have valid Gigantamax forms (Except 400 - Eternatus). If checked manually, in-game Pokédex descriptions aren't displayed, as though they haven't been captured or used. Suspect this might be what the UnknownFlag option controls.

**To Reproduce**
1. Go to SAV -> Pokédex Editor
2. Select any entry with a valid Gigantamax form (Full list in the Additional context section)
3. Press "Check All"

**Expected behavior**
All valid Gigantamax flags for applicable Pokémon should be enabled.

**Screenshots**
Current output:
![image](https://user-images.githubusercontent.com/14958008/68998468-f2448880-08b2-11ea-970f-dfe2c81c4c7d.png)

Expected output:
![image](https://user-images.githubusercontent.com/14958008/68998474-fc668700-08b2-11ea-8c95-bffbee83f6df.png)

**Additional context**
Valid Gigantamax Pokémon in the Pokédex:

- Charizard
- Butterfree
- Pikachu
- Meowth
- Machamp
- Gengar
- Kingler
- Lapras
- Eevee
- Snorlax
- Garbodor
- Corviknight
- Orbeetle
- Drednaw
- Coalossal
- Flapple
- Appletun
- Sandaconda
- Toxtricity
- Centiskorch
- Hatterene
- Grimmsnarl
- Alcremie
- Copperajah
- Duraludon
- Eternatus

**Comment by kwsch** [comment]
Upon looking at an unmodified entry for Sandaconda after it was captured with Gigantamax ability, the Unknown flag was still unchecked, but the Pokédex entry for the Gigantamax data was still ???.

The flag might be set once you Gigantamax it at least once yourself.

**Comment by igniscitrinus** [comment]
That seems to be the case, using e.g. Gigantamax Eevee in a Raid Battle and Dynamaxing it is what made the Pokédex entry for it appear.

**Comment by igniscitrinus** [comment]
Checking against an unedited save with the latest commit, the Unknown flag is definitely what controls the full entry visibility in the Pokédex.
![image](https://user-images.githubusercontent.com/14958008/68998982-c37de080-08b9-11ea-9b89-6c2afebfb78c.png)

![image](https://user-images.githubusercontent.com/14958008/68998986-de505500-08b9-11ea-9268-5896d33e6096.png)
