### ISSUE TITLE
Misplaced Battle Box slots

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2435]
**Describe the bug**
Instead of showing up under the Party-Battle Box tab, the Battle Box slots are showing up under the Other tab. Affects Gen. 6, may also affect Gen. 5.

**To Reproduce**
1. Load Gen. 6 save
2. Click on Party-Battle Box tab, only the Party is shown
3. Click on Other tab, Battle Box slots are shown vertically under the GTS and Fused slots

**Expected behavior**
Battle Box should probably be under the Party-Battle Box tab, like it used to be.

**Screenshots**
![image](https://user-images.githubusercontent.com/43770697/68999162-89491a80-088a-11ea-8361-61a95826a4f1.png)

**Additional context**
The graphics and borders around the Party are also missing, mentioning just in case this wasn't intentional.

**Comment by kwsch** [comment]
Intended behavior for both the location of battle box slots and the lack of graphics.

A graphical rework will be one of the future updates; moving away from Text-Label tabs to image pics like in the Inventory Editor.

The pkmeditor sprite is too big, and these new image tabs will be deeper so the UI will look better. I can't rescale / reposition the party sprites easily.
