### ISSUE TITLE
Gigantamax based changes

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#2436]
Recording changes here. I'll try and PR as and when I can code fixes too (if you don't fix it before I get the chance to)

for ShowdownSet: `SpeciesName-Gmax` should set CanGigantamax flag
for EncounterGenerator: Should probably have an argument that takes in gigantamax as an argument since it is species specific

**Comment by kwsch** [comment]
Showdown will probably change their syntax if there's ever a Gmax from an altform. Should be fine for at least a year :)
