### ISSUE TITLE
Named boxes in ORAS end in Unicode Unknown Char

### ISSUE THREAD

**Issue by deadair3210** [kwsch/PKHeX#2445]
**Describe the bug**
My boxes that were named in my ORAS saves end in a ? Diamond Character instead of ending correctly

**To Reproduce**
1. Build latest commit (4bcf60746b0097c593304eae3951545f7d7eebd8)
2. Open a ORAS save with named boxes
3. Look at Named Box and the name will end incorrectly

**Expected behavior**
For the name to end correctly as it does in prev versions and in game

**Screenshots**
![image](https://user-images.githubusercontent.com/1053504/69019765-9f80d480-0977-11ea-998f-fc220dead8d5.png)

**Additional context**

**Comment by kwsch** [comment]
Is the Box name exactly "Item Evo" or did you use one of the special characters? Only the Nickname and OT fields use the in-game font.

**Comment by Ammako** [comment]
It's related to the length of the string, not the custom box names. Box names 8 characters or longer have the �, 7 or lower don't. Special characters on my end get replaced with · instead (and a box name composed of 13 special characters showed up as ········�)

![image](https://user-images.githubusercontent.com/43770697/69022012-c47d4380-0987-11ea-8251-4736052c3921.png)

**Comment by Ammako** [comment]
Also, I wasn't completely sure, but names longer than 8 characters get cut-off at the 8th character.

![image](https://user-images.githubusercontent.com/43770697/69022294-e0cdb000-0988-11ea-8e9c-d75925a0e00e.png)

**Comment by Ammako** [comment]
Wow that's an old bug you've found too.

**Comment by deadair3210** [comment]
Just built the fixed commit, works great! Thanks!
