### ISSUE TITLE
Max Money Limit

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#245]
Prior to Gen 5, the maximum amount of Pokemon Dollars a player can have was 999,999. When editing a save file that's Gen 4 or earlier, PKHeX allows the user to modify their total amount of Pokemon Dollars to 9,999,999, which is over the limit. As stated at the beginning, having 9,999,999 is only possible in Gen 5 onward

**Comment by sora10pls** [comment]
Also, while on the topic of Pokemon Dollars...

Instead of using "$" to display money, would it be possible to use ![image](https://cloud.githubusercontent.com/assets/17801814/18363377/e2e97b64-75d7-11e6-9c5f-c2677b244d33.png) instead? I know it's not actual text and is just a very small image, but it'd be a nice little touch to make it feel more "Pokemon-esque". Totally up to you, not a major change after all


![image](https://cloud.githubusercontent.com/assets/17801814/18363373/dc9dee48-75d7-11e6-81e2-77c08b6fe7fd.png)

**Comment by kwsch** [comment]
I'm currently dissatisfied with the multi-gen handling of the Trainer Data Editor (tries to be too flexible?) Have to think about how the data should be presented and if the form can be generated to fit a list of SAV properties instead of hand-crafted.
