### ISSUE TITLE
Relearn move legality

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2450]
**Describe the problem**
Relearn move legality
Frosmoth can learn Bug Buzz in lv32
So, it should be able to relearn Bug Buzz in lv30
But, in PKHeX
If TR Bug Buzz is not checked
It will be not legality

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69111249-f8578680-0ab7-11ea-999a-0c5d3afe3dbe.png)

**Comment by kwsch** [comment]
You can't use the Move Tutor to learn moves that are learnable above your current level; this is different than what you can do in Gen7.

**Comment by iiippppk** [comment]
> You can't use the Move Tutor to learn moves that are learnable above your current level; this is different than what you can do in Gen7.

Oh
Then this issue should be closed
