### ISSUE TITLE
SW/SH Fossils Eggs

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2451]
**Describe the problem**
Fossils are Undiscovered
There should be no eggs

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69111312-305ec980-0ab8-11ea-93ab-bce844f6cc70.png)

**Comment by iiippppk** [comment]
![image](https://user-images.githubusercontent.com/39662364/69111468-a105e600-0ab8-11ea-8fb9-98c596a0d333.png)

**Comment by shyunsek** [comment]
^^^ The fossils in this gen cant breed, and are found on route 6 at level 10, jus for quick clarity
