### ISSUE TITLE
Obstagoon egg move Leer

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2452]
**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69111836-bf201600-0ab9-11ea-8011-45bf2469175d.png)
![image](https://user-images.githubusercontent.com/39662364/69111893-e1199880-0ab9-11ea-80af-321455561210.png)

**Comment by kwsch** [comment]
This is going to be a rough one to fix; a lot of old logic that doesn't depend on an "AltForm" for the egg move fetch methods :\
