### ISSUE TITLE
No Pid/Encryption Constant 

### ISSUE THREAD

**Issue by shyunsek** [kwsch/PKHeX#2454]
**Describe the bug**
When editing/creating a pokemon, the section to reroll the Pid and encryption constant is gone, making it buggy to make a pokemon non-shiny.

**To Reproduce**
Shows up on main Ui for any pokemon 

**Expected behavior**
.........

**Screenshots**
https://gyazo.com/ee900f8b5c4220314a436dcf7cc26c8d

**Additional context**

**Comment by kwsch** [comment]
Not a bug. 
You've turned on the "Hide Secret Details in Editors" setting, which hides those fields (to make screenshots not compromise unique data).
![image](https://user-images.githubusercontent.com/6393368/69112752-edf4a880-0a35-11ea-9ba9-663a775ad614.png)
