### ISSUE TITLE
SW/SH Event ribbons

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2455]
**Describe the problem**
Event ribbons should be legality

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69113695-b120c400-0abe-11ea-9ced-f333b8fa0786.png)

**Comment by kwsch** [comment]
Should have been fixed with https://github.com/kwsch/PKHeX/commit/21c3b4e1b1a8f390e5ac0f2d5943ddfefb5c29c3

Are you testing with latest commit? :)

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/69114202-c2b69b80-0abf-11ea-8133-77c621c10e72.png)
Can confirm that the latest commit works. Can be closed

**Comment by iiippppk** [comment]
Oh
I testing this commit
https://github.com/kwsch/PKHeX/commit/fac5182d4bbc942af703dce3d84840c1d9f0cdab
commit is updated too often :)
