### ISSUE TITLE
Gigantamax pokemon

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2457]
**Describe the problem**
Gigantamax pokemon not legality

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69116586-e087fe80-0ac7-11ea-961f-5fd3f02f37bd.png)

**Comment by kwsch** [comment]
Raid encounters are not thoroughly documented yet, so recognition of such events (and their associated properties like Gigantamax) aren't yet supported.

I think this one is one of the "super strong" distribution ones (download content outside of the ROM), for the record :)
