### ISSUE TITLE
Unhandled exception error (latest commit)

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#246]
Tested with a save file of Alpha Sapphire on the latest commit of PKHeX. I'm not sure if this is just due to lack of research on Poke Puffs in OR/AS (similar to O-Powers in OR/AS), but I figured that I'd report on it since it's an error and not an alert put in by you.

Full error can be found here: http://pastebin.com/EX87y5mf 

![image](https://cloud.githubusercontent.com/assets/17801814/18374238/31e9ca48-7619-11e6-9475-e9c323d0032f.png)

**Comment by kwsch** [comment]
You'd have to run under a debugger, the "Setup" method is throwing the exception.

https://github.com/kwsch/PKHeX/blob/master/PKHeX/Subforms/Save%20Editors/Gen6/SAV_Pokepuff.cs#L23-L58

Probably you have an invalid Poké Puff ID :)

`dgv.Rows[i].Cells[1].Value = pfa[SAV.Data[SAV.Puff + i]];`

Maybe just try hitting Continue and see what pops up.

**Comment by sora10pls** [comment]
Hitting continue just closes the exception and sends me back to the main form. Will report back when I test latest commit!

**Comment by sora10pls** [comment]
That sure did the trick. You're the best, man! :)

![image](https://cloud.githubusercontent.com/assets/17801814/18374651/c2ea61b2-761c-11e6-9b7e-9852f68c2f6b.png)
