### ISSUE TITLE
Level 0 with transfer pokemon?

### ISSUE THREAD

**Issue by Jrublgo** [kwsch/PKHeX#2463]
I transfer many pokemon from different gens (4,5,6,7) In pkhex also appear the correct level but when I load the save all, pokemon appear with level 0. I dont sure if i am doing wrong when load the save file (I use checkpoint) or maybe is a error from pkhex.

**Comment by ReignOfComputer** [comment]
Duplicate of https://github.com/kwsch/PKHeX/issues/2462 wrt transfer Pokemon.

For Level 0 display, bring your Pokemon into a battle and leave, then heal them at a Pokemon Center.
