### ISSUE TITLE
National Dex Ordering Option When Creating Pokemon

### ISSUE THREAD

**Issue by foohyfooh** [kwsch/PKHeX#2465]
**Is your feature request related to a problem? Please describe.**
It is sometimes difficult to find Pokemon since they are in only available alphabetical order.

**Describe the solution you'd like**
Provide an option in settings that allows for sorting by National Dex Order in the Pokemon editor.

**Comment by kwsch** [comment]
There's no easy way to add a toggle in the settings; the program has to be recompiled with different string settings.

Here's what you'd change in order to get the desired behavior:
![image](https://user-images.githubusercontent.com/6393368/69167266-8415e680-0aa9-11ea-888a-6d0153262994.png)
