### ISSUE TITLE
Question about Alcremie Forms

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2466]
Hey I just wanted to know if it is possible in PKHeX right now or if there is a way to add a feature to change Alcremie's form not just with the type of cream but with what type of sweet it evolved with. If you see on Serebii
https://www.serebii.net/swordshield/formchange.shtml
, apparently there are many combinations you can make with Alcremie but I believe in PKHeX right now you can only choose the type of cream with it defaulting to the strawberry sweet which leaves out over 50 combinations I think. Thanks in advance

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/d077d8549ea5c0f67578cae5461dbc23d221e441
