### ISSUE TITLE
Editing a pokemon ultra sun save will corrupt it

### ISSUE THREAD

**Issue by Mattlau04** [kwsch/PKHeX#2467]
**Describe the bug**
When using pkHeX to modify about anything from a pokemon ultra sun save, it will cause the save to be corrupted after being re-injected (in a screen after launching the game).

**To Reproduce**
1. Edit anything in the SAV tab (i only tested with editing unlocked stickers/trainer info/box layout/poké beans and festival plaza

2. Export the save

3. inject the save using checkpoint

4. launch the game

**Expected behavior**
Edit the save but not corrupt it

**Screenshots**
![2019-11-20_20-24-34 068_bot](https://user-images.githubusercontent.com/37871312/69175608-58741a00-0b04-11ea-91da-fd074d7ba975.jpg)
It's in french but basicly it just says the save is corrupted

**Additional context**
I'm using pokemon ultra sun version 1.2, the latest european update on my 3ds and the latest version of PKHeX

**Comment by kwsch** [comment]
This was fixed a couple days ago and a hotfix was uploaded at that time.

Be sure you are using the latest program.

**Comment by Mattlau04** [comment]
why though?

**Comment by Mattlau04** [comment]
re-downloaded latest then compiled and it still happens :/
