### ISSUE TITLE
Linux/Mac Support

### ISSUE THREAD

**Issue by Masaru2** [kwsch/PKHeX#2470]
The removal of the mono build makes the program unstable for linux and mac computers.
Wine and Mono in close the program immediately

**Comment by kwsch** [comment]
Refer to the commit notes that were included when the build option was removed: https://github.com/kwsch/PKHeX/commit/be26074e1aa2abc403be08fb31fecbb6e674a5e4

> With the FontUtil rewrite removing any platform specific code, there is no need to have two separate builds.

Per the readme:

> GNU/Linux is not the main Operating System of developers of this program so there may be bugs; some may come from non GNU/Linux specific code of Mono/Wine, so other users may not be able to reproduce the error you are experiencing.

You'll have to provide information on what changes need to be made.
