### ISSUE TITLE
SW/SH Silvally memory

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2473]
**Describe the problem**
Silvally held item memory should be legality

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69212512-7ee59400-0b9c-11ea-8e7a-42bb3cfbddef.png)
![image](https://user-images.githubusercontent.com/39662364/69212556-a76d8e00-0b9c-11ea-9348-b04d9024b19b.png)

**Comment by iiippppk** [comment]
![image](https://user-images.githubusercontent.com/39662364/69212806-47c3b280-0b9d-11ea-8bfa-8e381233cb7e.png)

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/26b21d8603c1a06ac20ad652333514ac6f74cf1e
:)
