### ISSUE TITLE
Alcremie Form Selection

### ISSUE THREAD

**Issue by CorvusAtrox** [kwsch/PKHeX#2474]
**Is your feature request related to a problem? Please describe.**
I noticed when setting Alcremie's Alt Form, either there seem to only be options for coat because that's what affects the sprite, but ability to set the decoration itself in addition would be great. I admittedly have a strawberry Alcremie already but the way it works makes me wonder if I changed the coat for a non-Strawberry Alcremie if it would change the decoration to a Strawberry one or keep its decoration as is.

**Describe the solution you'd like**
I'd like a way to set the decoration of an Alcremie rather than just the cream coat with PkHex as well as the clarification between Ruby Cream and Ruby Swirl forms rather than listing both of them as 'Ruby' and needing to click to see which one if you want one or the other.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
It could be that the way to set decoration is another part of the alt form selection or would be better under an additional dropdown.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2466
