### ISSUE TITLE
Issue with moving pokemon between saves

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2476]
Hey I just noticed that when you move a pokemon across 1 PKHeX window to another (2 different saves) the pokemon dissapears from the first save which makes it seem like you have permenatly moved that pokemon to the other save file. The problem is that  when you refresh the box view for the first save the pokemon reappears making it that you have copied the pokemon instead of moving the pokemon.

**Comment by jinzo302** [comment]
@NinFanBoyFTW just drag the pokemon to your desktop and it will create a file. then drag the file to your other save.
