### ISSUE TITLE
Gastrodon-West gives "Not an expected relearnable move"

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2479]
Using PKHeX 191115e with an Ultra Sun save file, this Gastrodon (which was an ordinary egg hatch, and has egg moves in its relearn list) shows up as illegal, when it wasn't setting off any problems prior to the Sw/Sh update. Changing the form to East suddenly makes it turn up completely legal, so I think somewhere along the line during the update, the database lost track of the move list for certain form-encounters.

[423 - Gastrodon - 782EBAC1ACE9.pk7.gz](https://github.com/kwsch/PKHeX/files/3871976/423.-.Gastrodon.-.782EBAC1ACE9.pk7.gz)

**Comment by kwsch** [comment]
Probably related to the rewrite of the Evolution Tree builder in a recent commit (necessary for accurately tracking form changes during evo).

I didn't double check if the modifications impacted the "fixer" method which rectified some evolution chains (see Gastrodon at the top):
https://github.com/kwsch/PKHeX/blob/ee9c91e8939c7516bdb0da991ef73b69a277fad9/PKHeX.Core/Legality/Evolutions/EvolutionTree.cs#L179-L223

Maybe that's not the issue, maybe it's something related to the eggmove fetch.

**Comment by SadisticMystic** [comment]
West is form 0 for Shellos and Gastrodon; is that line 187 trying to nuke evolution data for form 0 on Gastrodon?
