### ISSUE TITLE
Feature request: Pokemon Sword and shield event flags

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2480]
Hey I just wanted to know if you were going to be implementing the event flags feature into PKHeX 8th Gen. At this point I mainly wanted to research some of the flags for events and clothing. Thanks

**Comment by kwsch** [comment]
Clothing is already documented; like prior gens, I'm not including an editor. It's up to the community to make payload cheats that PKHeX can apply.

Too early for event flag stuff; it's always on the radar since every other mainline game has them exposed.
