### ISSUE TITLE
Special 'Square Shiny' Pokémon...

### ISSUE THREAD

**Issue by Nessus009** [kwsch/PKHeX#2488]
Can a line of code be added so we can choose if a Pokémon is standard shiny or special square shiny? Sword + Shield of course.

Many thanks!!!

**Comment by architdate** [comment]
Its already done actually. Just does not have a GUI. Hold shift and click the star icon!

**Comment by architdate** [comment]
Heres the reference commit: a50169d

**Comment by Nessus009** [comment]
WOW!!! Amazing! I will give this a try! So should we change the star from red to blue or something? Just to make it more obvious :D

**Comment by Nessus009** [comment]
Thank you so much!!!

**Comment by architdate** [comment]
Feel free to close the issue if its solved :)
