### ISSUE TITLE
Sort Game Location Per Generation/Game

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#249]
What I noticed was that only Gen 6 games had the list sorted based on the game they are in. However, previous generations do not.  Such in the picture below, Gen 4 is locations are not correctly sorted. By default, if the wrong game location is selected for an egg met location in the editor, the location when it is added to the game by default will be Lake Verity. Is it possible to sort the Egg Met/Met Locations based on the generation/game?

![see1](https://cloud.githubusercontent.com/assets/21182549/18405847/bb8fc3d8-76c3-11e6-9b66-b2f5cebd6d9f.png)

**Comment by kwsch** [comment]
You're quite likely using an out of date version of the program. This was fixed 4 days ago.

#233

**Comment by ricksee** [comment]
@kwsch Is there a way using the latest build from teamcity?

**Comment by evandixon** [comment]
I'm the one to talk to about Team City.  Look for the "continuous-integration/teamcity-dotnet" status check details, then look under Artifacts.

Here's the artifact for the latest build:
http://teamcity.uniquegeeks.net/repository/download/PKHeX_PKHeXBuildPr/1779:id/PKHeX%20Build%20386.zip

Tangent:
Using my builds, I haven't been able to get it to run in Linux, while the official builds do work, so it's Windows only for now.

**Comment by kwsch** [comment]
![img](http://i.imgur.com/tWSrMae.png)
