### ISSUE TITLE
[Feature request] UI scale for previous Gens

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2494]
**Is your feature request related to a problem? Please describe.**
The new larger UI for SW/SH makes the previous Gen's look small and out of date/style

**Describe the solution you'd like**
for either new box or party  size/scale to be applied to only the new SW/SH.

**Describe alternatives you've considered**

**Additional context**
not sure if the plan is to resize/rescale all of the box size/ui/display etc to be uniform across all generations.

comparison of issue,

Gen8 SW/SH (built from latest commit)
![image](https://user-images.githubusercontent.com/12572974/69404050-40e68e00-0cca-11ea-9529-81246a653acf.png)

Gen6 X/Y (built from the latest commit)
![image](https://user-images.githubusercontent.com/12572974/69404090-61164d00-0cca-11ea-8b2c-a08db926bf9f.png)

**Comment by kwsch** [comment]
The plan is to wait for HOME to deliver the re-scaled sprites (and uncompressed ones without jpeg-artifacts).

I don't really wanna open up another can of worms dealing with rendering issues for rescaled sprites :|
