### ISSUE TITLE
USUM saves corrupt on load post 11-15-19 update

### ISSUE THREAD

**Issue by DaWoblefet** [kwsch/PKHeX#2497]
**Describe the bug**
I recently updated to 11-15-19. When I edited my Ultra Moon save (I just added a Groudon to box 17, slot 1, but I doubt the Pokemon or slot has anything to do with it), and reimported with Checkpoint 3.7.3 (latest). It fails to load both on console (Luma 10.0.1 running off of whatever latest B9S is) and on latest Citra. I was able to replicate this without doing anything but loading and rexporting the save in an Ultra Sun cart.

**To Reproduce**
Resave any USUM save in PKHeX.

**Expected behavior**
I have had no issues with these saves before.

**Screenshots**
Here is what it's saying on load in Citra and on 3DS:
![image](https://user-images.githubusercontent.com/23667022/69466657-93678f00-0d4a-11ea-9c2b-9cd0f57d6944.png)

Attached is a zip of the save post-PKHeX export. Unfortunately I don't have the backup of the working save for a comparison for the Ultra Moon cart. So, I have also attached an Ultra Sun cart pre and post-export in PKHeX as a comparison. Importing the non-corrupted US save in latest Checkpoint loaded just fine, but after doing nothing but loading and re-exporting the save as main in 11-15-19, I hit the same "save corrupted" message on 3DS. I have given the save files names to indicate which were corrupted, as well as the uncorrupted Ultra Sun save.
[Corrupted USUM saves.zip](https://github.com/kwsch/PKHeX/files/3881789/Corrupted.USUM.saves.zip)

Comparing the files in HxD shows me that everything in the US carts are identical until 0x0006C100, so idk if that has to do with the signature or something, idk save structure.

**Comment by kwsch** [comment]
Has already been fixed and an updated exe has already been posted last week.
