### ISSUE TITLE
Illegal moves are listed even without renaming to PKHaX

### ISSUE THREAD

**Issue by flarn2006** [kwsch/PKHeX#25]
I can tell the intent is to only allow Pokemon to be given legal stats, abilities, etc. unless the user specifically says otherwise (by renaming the EXE to PKHaX.exe, or actually anything containing "HaX".) But illegal movesets can still be given even when not in "illegal mode". Just thought this seemed like an oversight.

**Comment by kwsch** [comment]
If I were to restrict moves to only levelup/egg, users would be prevented from viewing/editing event Pokemon with special moves. 

If I were to include an event move table (for every pokemon), that would be a huge amount of effort, plus needing to update the program every time some new event move is available.

It's up to the user to use legal moves.

**Comment by flarn2006** [comment]
Yeah I agree it should be possible if the user wants to. That's what the PKHaX mode is for. But yeah, that makes sense. Thanks for the quick reply!
