### ISSUE TITLE
Import Set from clipboard sets Stats Nature to the correct value, but should be setting both Nature values.

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2504]
**Describe the bug**
When importing a set from clipboard (showdown), the Stats Nature gets set to the correct value, however, the characteristics stats doesn't get set at all. Or at the very least, it doesn't get updated from the previously loaded value. When importing a set, both values should be set to the same value to be considered legal.

**To Reproduce**
1. Copy a pokemon to clipboard using Showdown format.
2. Go to `Tools >> Showdown >> Import Set from Clipboard`.
3. See that `Nature` and `Stat Nature` are not the same value. `Stat Nature` is correct, but `Nature` uses the previously loaded value.

Messenger (Delibird) (M) @ Leftovers
Ability: Insomnia
Level: 10
Shiny: Yes
EVs: 36 HP / 236 Atk / 236 Spe
Jolly Nature
- Drill Peck
- Ice Shard
- Ice Punch
- Protect

**Expected behavior**
Both `Nature` and `Stat Nature` should be set to the same, correct value.

**Screenshots**
![https://i.imgur.com/DMonVtx.gif](https://i.imgur.com/DMonVtx.gif)

**Comment by BetaLeaf** [comment]
Built using latest commit: f96eafa682f6e17652e77c040d6ac562cac20060

**Comment by kwsch** [comment]
Working as intended; this is 100% legal and is preferred as it does not modify past gen specimens with required Nature values.

**Comment by BetaLeaf** [comment]
Maybe I am a bit confused then. Every Pokemon I have ever caught on Sword & Shield had matching natures. Wouldn't this be a dead give-a-way that the pokemon is not legitimate?

**Comment by ReignOfComputer** [comment]
In Sword and Shield, you can now change your Pokemon nature using Sweets. When you change a Pokemon's nature, the Pokemon still retains its original nature (if it's Adamant it will be Adamant), but will use the nature of the sweet you give it (the Stat Nature).

For example, if a Pokemon is originally Adamant, its nature (for both `Nature` and `StatNature`) will be Adamant. When you give it a Jolly Sweet, its `Nature` will remain as Adamant but its `StatNature` will be Jolly. This displays in the game as the +- stats of the `StatNature` in the Stats page and the `Nature` on the Pokemon record page, where they can be different.

**Comment by BetaLeaf** [comment]
Oooh. Thanks for that explanation. I did not realize this game had that mechanic.

**Comment by Nessus009** [comment]
> In Sword and Shield, you can now change your Pokemon nature using Sweets. When you change a Pokemon's nature, the Pokemon still retains its original nature (if it's Adamant it will be Adamant), but will use the nature of the sweet you give it (the Stat Nature).
> 
> For example, if a Pokemon is originally Adamant, its nature (for both `Nature` and `StatNature`) will be Adamant. When you give it a Jolly Sweet, its `Nature` will remain as Adamant but its `StatNature` will be Jolly. This displays in the game as the +- stats of the `StatNature` in the Stats page and the `Nature` on the Pokemon record page, where they can be different.

This makes sense. Counter argument: As most genners will be genning Pokémon from scratch (by importing Showdown exports) rather than editing existing ones, wouldn't it be better if Nature and StatNature were 'linked' so they change together? Only in a rare instance would you want to make a Pokémon appear as though it was given a sweet to alter nature when genning. I understand the StatNature is the nature the Pokémon adopts but the group I gen for will always question if the Nature is "incorrect". If it is left the way it is I will always have to manually change the Nature of every Pokémon I gen :( You guys are the experts so whatever you guys decide is probably best but please consider my comments 👍 

P.S You guys kick ass! :D
