### ISSUE TITLE
Sword and Shield legal errors

### ISSUE THREAD

**Issue by Narithegreat** [kwsch/PKHeX#2506]
3 Pokemon I caught are being falsely marked, they are Trapinch, Galarian Linoone and Silcobra. For some reason Trapinch becomes legal if I just set its game as Shield, but it is not an exclusive as I caught it in Sword.

[sword.zip](https://github.com/kwsch/PKHeX/files/3882963/sword.zip)

**Comment by kwsch** [comment]
Linoone (non raid): [No wild encounters in this area match Linoone](https://www.serebii.net/pokearth/galar/hammerlockehills.shtml)

Trapinch (raid): Fixed in above commit

Silcobra (raid): To be fixed in the future commits when we add distribution raid content.
