### ISSUE TITLE
Showdown Import/Export

### ISSUE THREAD

**Issue by Nessus009** [kwsch/PKHeX#2510]
Hi folks,

Loving the work you guys are doing!!! <3 

**Issue: When you import Showdown set from clipboard the 'Stat Nature' rather than 'Nature' is effected.**

_Possibly not the best place to ask but what is the use of Stat Nature?_

Thanks again!

**Comment by ReignOfComputer** [comment]
Will answer in https://github.com/kwsch/PKHeX/issues/2504
