### ISSUE TITLE
When importing set from Showdown, remove previous Technical Records & give all compatible Technical Records automatically.

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2511]
**Is your feature request related to a problem? Please describe.**
When I import a set from Showdown, I am frustrated that I have to go to Technical Records twice, once to remove all records, then one to give all records. I have to do this because previous records are not removed when importing a set from Showdown.

**Describe the solution you'd like**
Automatically remove all records and give all compatible records when importing from Showdown.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
Ctrl+Click the Technical Records button to automatically Remove and Give all records.

**Comment by architdate** [comment]
Shift+Click on the button does give legal TRs :)
