### ISSUE TITLE
When importing set from Showdown, automatically suggest the Met Location

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2512]
**Is your feature request related to a problem? Please describe.**
Whenever I import a set from Showdown, I have to change the Met Location, as it defaults to the previously loaded values. 

**Describe the solution you'd like**
Since PKHeX is capable of recommending a Met Location, can this be done automatically on import?

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
Ask to change the met location on import

**Comment by kwsch** [comment]
Better to just rely on the shortcuts for this. You can click on the Level label to pop up the suggestion from the main tab. The met suggestion can be considered a nag by some, and it doesn't cover egg met location suggestions.

Ctrl click species, click level, most issues should be fixed.

PKHeX tries not to modify tons of properties outside of the imported set data. If you're just wanting a one-click import for a legal PKM, I suggest checking out https://github.com/architdate/PKHeX-Plugins
