### ISSUE TITLE
Ultra Shiny

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2513]
**Is your feature request related to a problem? Please describe.**
Sword and Shield introduced Ultra Shinies. I do not see an option to get these in PKHeX

**Describe the solution you'd like**
Add an option to generate ultra shiny pokemon

**Comment by Orionsilver** [comment]
There's already a shortcut built in (hold shift when clicking), otherwise it's always gonna give you stars

**Comment by Orionsilver** [comment]
shift+click star u get Xor=0

**Comment by BetaLeaf** [comment]
I can't get this to work. I'm on this mornings commit

**Comment by architdate** [comment]
hover over the PID, it should say xor=0 that means its a square shiny. Refer to this tweet made by @kwsch https://twitter.com/Kaphotics/status/1197027047224176640

**Comment by BetaLeaf** [comment]
Ok thanks I got it. I thought there would be an indication in game on the
stats screen. Only visible when sending the pokemon out for battle
