### ISSUE TITLE
SW/SH in the town of Postwick Rookidee

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2515]
**To Reproduce**
[821 - Rookidee - 99728F5F0DF7.zip](https://github.com/kwsch/PKHeX/files/3884492/821.-.Rookidee.-.99728F5F0DF7.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69506310-05b5ba80-0f69-11ea-9c5c-ba96e8eb7573.png)

**Comment by kwsch** [comment]
No encounter exists in Postwick for that; it's a "Crossover" location where the PKM roams/is coaxed across map boundaries to a different location ID.

Closing, as the other issue is already tracking this: https://github.com/kwsch/PKHeX/issues/2416
