### ISSUE TITLE
at West Lake Axewell (in a Wild Area) Diggersby

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2517]
**To Reproduce**
[660 - Diggersby - AED2BCD07847.zip](https://github.com/kwsch/PKHeX/files/3884896/660.-.Diggersby.-.AED2BCD07847.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69513247-22aab780-0f82-11ea-8bea-9ab7cdce275e.png)

**Comment by architdate** [comment]
This seems to be `EncounterStatic8 { Species = 660, Level = 15, Location = 122, }` (Rolling Fields (in a Wild Area))

**Comment by ReignOfComputer** [comment]
Probably Cross Boundary, yet to be fixed.

**Comment by architdate** [comment]
It does seem like it is cross boundary. `ConnectingArea8` does specify connecting areas to rolling fields: 
`{122, new byte[] {124, 128, 130}}`
(130 is west lake axewell)

**Comment by iiippppk** [comment]
Probably Cross Boundary，It's temporarily closed
