### ISSUE TITLE
Gen IV: HS, SS Pikachu-Colored Pichu: Was it added?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#252]
Is Pikachu-Colored Pichu also added to the games? I believe it is considered shiny, but is possible for this Pichu to trigger the Illex forest event in those games?

**Comment by kwsch** [comment]
http://bulbapedia.bulbagarden.net/wiki/Fateful_encounter#List_of_in-game_events_activated_by_fateful_encounter_Pok.C3.A9mon

Pichu + Shiny + Fateful Encounter => Event Triggered.
