### ISSUE TITLE
Ditto - Imposter (H) marked as illegal in SWSH?

### ISSUE THREAD

**Issue by Nessus009** [kwsch/PKHeX#2527]
Apologies, more of a question really...

Is Ditto's Hidden Ability Imposter genuinely illegal in SWSH? They trade just fine so though I'd ask :-)

THANKS AGAIN!

**Comment by Bappsack** [comment]
only the Ditto from Lake of Outrage can't have his HA.

Set Met_Locaction to "In a Pokemon Den", Met_Level to "60".

**Comment by Nessus009** [comment]
> only the Ditto from Lake of Outrage can't have his HA.
> 
> Set Met_Locaction to "In a Pokemon Den", Met_Level to "60".

Just tried and this does not work either :(

**Comment by kwsch** [comment]
This is not the place to ask questions related to legality.
