### ISSUE TITLE
GBA .SAV File Won't Load to PKHeX/Converting Files to .SAV Will Produce Similar Errors

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#253]
I managed to upload my FireRed .sav file to my SD card. But, when I tried to open it the program it gives me this error:

Attempted to load an unsupported file/size. But my file is 128kb long.

Any reason why?

**Comment by kwsch** [comment]
Depends if your OS file summary is rounding up or down.
internal const int SIZE_G3RAW = 0x20000;
internal const int SIZE_G3RAWHALF = 0x10000;

Could also be that the save is incomplete or unrecognizable. Hence why it does not load.

**Comment by ricksee** [comment]
I got something like this. I am using GBA Backup Tool Through Action Replay Dsi v. 1.25. Would I have to save my game twice like before?

![sef](https://cloud.githubusercontent.com/assets/21182549/18413551/04bb08e6-7779-11e6-92dc-7c1c4c4d5b79.png)

**Comment by ricksee** [comment]
@kwsch I should also note that converting any file that was originally not .sav will produce a similar error. I got 0x40000 when converting a .DUC to .SAV from the internet.

**Comment by kwsch** [comment]
It's not an error; it's that the program cannot edit save files if it has not been programmed to handle it (assuming the input is valid).

* Size is not valid
* Save file is not initialized completely
* Data stored is not valid (storage not initialized, blocks not set-up, corruption)

PKHeX has to juggle 24 different game savefiles. If you're interested in getting support for a 3rd-party format, you'd have the best luck implementing yourself and submitting a pull request.
