### ISSUE TITLE
Ditto - Imposter (H) marked as illegal in SWSH

### ISSUE THREAD

**Issue by Nessus009** [kwsch/PKHeX#2530]
_I think this is now the correct place to ask this? Please don't be upset with me if I have posted this in the wrong place again. I'm new to using this type of 'forum'._

****Is Ditto's Hidden Ability Imposter genuinely illegal in SWSH? They trade just fine so I thought I'd ask.** 

Bappsack commented on my last post _"only the Ditto from Lake of Outrage can't have his HA. Set Met_Location to "In a Pokemon Den", Met_Level to 60"_ but this was also flagged as illegal.

![Ditto HA1](https://user-images.githubusercontent.com/13892224/69683446-cf815380-10ac-11ea-94a6-8704aefe558c.png)

![Ditto HA2](https://user-images.githubusercontent.com/13892224/69683448-cf815380-10ac-11ea-9909-c3137902d5c0.png)

Thanks for reading!

**Comment by ReignOfComputer** [comment]
Use the ProjectPokemon forums.

If it's from a max raid give it a Dynamax Level, by the way.

**Comment by Bappsack** [comment]
u forgot Dynamax Level > 4.

**Comment by Nessus009** [comment]
> u forgot Dynamax Level >= 4.

I tried level 5-10 also but still didn’t work. You have a pk8 that is legal?

**Comment by architdate** [comment]
There you go
[132 - Ditto - 40037959F7C0.zip](https://github.com/kwsch/PKHeX/files/3894602/132.-.Ditto.-.40037959F7C0.zip)

**Comment by Bappsack** [comment]
FlawlessIV Count is 4

**Comment by Nessus009** [comment]
> There you go
> [132 - Ditto - 40037959F7C0.zip](https://github.com/kwsch/PKHeX/files/3894602/132.-.Ditto.-.40037959F7C0.zip)

Thanks you so much guys! Makes sense now! :D
