### ISSUE TITLE
PKHeX change the trainer card number

### ISSUE THREAD

**Issue by NOAME18** [kwsch/PKHeX#2532]
Can the  trainer card number be changed in PKHeX? 
Not a name,but a three-digit trainer card number in the lower left corner.
My default trainer card number seems to be causing some problems such as the clothing cannot be changed.

**Comment by kwsch** [comment]
Already implemented in the trainer info editor.

**Comment by NOAME18** [comment]
I tried looking for the option box that changed the number, but I really couldn't find it.
![BC 2019-11-28 11-17-18-309(1)](https://user-images.githubusercontent.com/53110680/69774645-752de300-11d1-11ea-8811-7ff8ccc3c10e.jpg)

**Comment by NOAME18** [comment]
Can someone guys tell me where to change it?

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/69775524-d7dd9b00-114d-11ea-930b-f1866139b03d.png)

**Comment by NOAME18** [comment]
Is the latest version 191125?

**Comment by NOAME18** [comment]
Is the latest version 191125?
![BC 2019-11-28 12-50-37-104](https://user-images.githubusercontent.com/53110680/69778110-1458d780-11de-11ea-97bb-0d0580f226a5.jpg)

**Comment by ReignOfComputer** [comment]
It's added in this commit https://github.com/kwsch/PKHeX/commit/c0270b18e4a691532986e37d733c85c5a924dfdd which hasn't been released yet.

**Comment by NOAME18** [comment]
Ok,i get it thank you guys!!
