### ISSUE TITLE
Adding Egg Met Location For Gen 3 Games

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#254]
Is it possible in the future that the egg met location could be added to Gen 3 games such as R/S/E? Day Care Center isn't there at all.

**Comment by kwsch** [comment]
Egg Location is not stored in pk2/3 files.

**Comment by ricksee** [comment]
Well the games do store the place it was hatched (city) (Egg) in the Trainer Memo in summary.

**Comment by kwsch** [comment]
That would be the Met Location.
