### ISSUE TITLE
SW/SH Memory Invalid

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2545]
**To Reproduce**
[247 - Pupitar - 6A9A3CB8804F.zip](https://github.com/kwsch/PKHeX/files/3906743/247.-.Pupitar.-.6A9A3CB8804F.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/69895716-3bdfa980-1370-11ea-9218-c70175eec65f.png)
![image](https://user-images.githubusercontent.com/39662364/69895714-32564180-1370-11ea-9267-042e33a75a99.png)

**Comment by sora10pls** [comment]
Memory mechanics are still being worked out -- https://github.com/kwsch/PKHeX/issues/2534#issuecomment-559369853
