### ISSUE TITLE
File to large

### ISSUE THREAD

**Issue by Zaccian** [kwsch/PKHeX#2546]
I cant find the correct save file all of them are to large or small someone please help me all i can find in save folder
![rerqRr 3](https://user-images.githubusercontent.com/58353017/69896043-701f7f80-1308-11ea-8c70-088b0f9d1f66.PNG)

**Comment by ReignOfComputer** [comment]
Dump your save files with Checkpoint. You need to be running CFW.
https://nh-server.github.io/switch-guide/

Not a bug.
