### ISSUE TITLE
IV/DV mixup + potential bug?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#255]
"Randomize IVs" should say "Randomize DVs". Another odd thing I've noticed is the way the HP DV string is handled in Gen 1 (maybe Gen 2 as well, don't have a save file handy to test). I'm not sure if it's intentional or not, but as shown in the two pictures...

The DV "0" for HP is centered and has no underscores (indicating how many digits can be entered)
![image](https://cloud.githubusercontent.com/assets/17801814/18414242/50b77156-778f-11e6-8213-222f4722d034.png)

When randomizing DV's, if the DV is <= 9, it'll show up as "0x" (x = whatever value the DV is), rather than "x_" like the other stats are (again, x = whatever value the DV is).

![image](https://cloud.githubusercontent.com/assets/17801814/18414252/6c6e71a6-778f-11e6-8d90-d54a3c284632.png)

Like I said, I'm not sure if it's intentional or not so I figured I would mention it.

**Comment by JHorbach** [comment]
I can confirm Gen 2 HP DV "0" digit.

**Comment by ajtudela** [comment]
I think we could just change the label.

**Comment by SciresM** [comment]
This is 2016. We're calling them IVs, not DVs. By your argument we should call them STATEXPs, not EVs, like Rhydon does, but that's dumb. They're IVs and EVs.
