### ISSUE TITLE
big sprites for let's go pikachu eevee

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#2551]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
i would like the big sprites for sword shield saves to also be used for let's go pikachu eevee because they also use them

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
none needed

**Additional context**
please and thank you

**Comment by Ninjistix** [comment]
believe this ties in with #2494 also

**Comment by sora10pls** [comment]
If this does get addressed before HOME's release,  LGPE is the most feasible start. Those games already use 68x56 sprites, they'd just need to be added to resources and changes would need to be made for LGPE to use the bigger sprite builder.

Some Species \*should* still use their SWSH sprites (i.e. Raichu and Dugtrio got new sprites in SWSH, while in LGPE they use the 3DS sprites just plopped onto the 68x56 canvas) over their LGPE sprites, though. They just look nicer and fit better.
