### ISSUE TITLE
Pokéball plus Mew crashing game when talking to move relearner

### ISSUE THREAD

**Issue by lagunyve** [kwsch/PKHeX#2553]
**Describe the bug**
I use a Mew, in Pokémon S/S, with every TR possible learnt and when you ask a move relearner in game to relearn one of Mew moves, the game crashes. (This problem is occuring only with Mew)

**To Reproduce**
1. Go to move relearner with Mew on the left of every pokémon center
2. Click on relearn move option
3. Scroll down to Mew and try to make it relearn a move
4. See error, game crashes

**Expected behavior**
There should not be a crash and you should be able to relearn old moves.

**Additional context**
There is no legality problem on PKHeX, I generated the Mew from "Encounter Database"

**Comment by sora10pls** [comment]
This is a bug with Sword & Shield, not with PKHeX. I tested this with both Kaphotics and SciresM to verify -- see [SciresM's Tweet here](https://twitter.com/SciresM/status/1194817757910454272) for clarification.

This can be closed seeing as how fixing this is up to Game Freak; to avoid the crash, simply set <= 66 TR flags or only set what your Mew currently has in its Moveset (Shift-Click the Technical Records button).
