### ISSUE TITLE
Cannot build from source on non-windows following removal of Mono-Release/Mono-Debug

### ISSUE THREAD

**Issue by wyatt8740** [kwsch/PKHeX#2554]
**Describe the bug**
https://aur.archlinux.org/packages/pkhex/ describes it as concisely as I can:

> I am afraid I am having troubles getting the new version to build. Upstream has done away with the mono build, and msbuild fails to find the Microsoft.NET.Sdk.WindowsDesktop sdk. I am having dotnet-sdk installed and the environment variables DOTNET_ROOT and MSBuildSdksPath set correctly, as well.

I am also encountering the same issues; #2470 should not have been closed, IMO.

Building was successful until the exact commit mentioned in that issue (except that it would still fail on the dotnetcore version since '.NET Core' does not include WinForms, as Mono did: https://github.com/dotnet/core/issues/2791 )

    /home/wyatt/development/pokemon/PKHeX/PKHeX.WinForms/PKHeX.WinForms.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.

All other parts of the project build alright, except that there's a casing error that makes `rare_icon_alt.png` fail to be discovered (path is entirely in lowercase where it should be in the actual case of the path on the git repo; non-windows is case-sensitive). That was easy to fix on my end.

`icon.ico` is also referenced as `Icon.ico`, which needs fixing.

**To Reproduce**
msbuild /p:Configuration=Debug

or

msbuild /p:Configuration=Release

…on a unix machine, and wait for the errors to roll in.

Replacing `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">` with `<Project Sdk="Microsoft.NET.Sdk">` makes it get to the end, and then fail when trying to link to `System.Windows.Forms` (predictably).

**Expected behavior**
Program builds.

Let me know if I can help; I'll try to get back quickly with additional information when prompted.

…so attempting to target this to .net core is meaningless.

**Comment by kwsch** [comment]
Per the referenced commit's changes:
https://github.com/kwsch/PKHeX/commit/be26074e1aa2abc403be08fb31fecbb6e674a5e4

> With the FontUtil rewrite removing any platform specific code, there is no need to have two separate builds.

Nothing changed besides removing the build option, which was exactly the same build option as the non-mono build. There was no platform specific code to be built, so no need to have two separate build options that do the same thing.

That said, I believe the issue you are facing was actually introduced in an earlier commit, namely:
https://github.com/kwsch/PKHeX/commit/c2d5d0cd42d1ac0b3d99faf14ce192cfa82c31c1#diff-a2c897d5623ddca71421d8c2704d3a06R1

The csproj format was changed from the old csproj format to the new sdk style, which depends on `WindowsDesktop`.

Will it be changed back to the old format? Nope. Gaining a .NET Core 3 target for the WinForms projects while losing non-Windows compilation is a worthwhile tradeoff, in my opinion.

**Comment by wyatt8740** [comment]
@kwsch Except (show me if I'm wrong) there is absolutely no WinForms in .Net Core 3, as per  dotnet/core#2791 . If not for that I'd be 100% on board.
