### ISSUE TITLE
about six-digit league card ID

### ISSUE THREAD

**Issue by funkyouo** [kwsch/PKHeX#2556]
Hello.When I used HexEditorNeo to load the main file in order to change league card ID, I found it in the 000ba509 to 000ba50b.For example, ef8720 is 364808, 93a828 is 900724.But when I keep increasing his value in the HexEditorNeo, the ID sometimes gets bigger and sometimes gets smaller. It makes me confused.Is the software I use wrong?Can you talk about the relationship between values and ID or add this feature in the new version of the PKHex?

**Comment by kwsch** [comment]
Save files are encrypted; looking at raw dumps may show an offset changing value, but won't describe what's happening when it's decrypted.
