### ISSUE TITLE
Limited characters for OT when JAP/KOR?

### ISSUE THREAD

**Issue by Nessus009** [kwsch/PKHeX#2559]
Hi folks,

When you select your Pokémon to be from either JAP or KOR they are flagged as illegal if you use:

- An OT with more than 5 characters for JAP
- An OT with more than 6 characters for KOR

All other languages allow 12 characters.

Is this correct? If so I apologise! 

Thanks for reading!

**Comment by kwsch** [comment]
https://bulbapedia.bulbagarden.net/wiki/Nickname#Limits_on_nicknames

This is not the place to ask questions related to legality, nor is this a bug.
