### ISSUE TITLE
Invalid : Invalid Console Region.

### ISSUE THREAD

**Issue by lavar23** [kwsch/PKHeX#2560]
Whenever I load up PKHeX and import or create a "legal" Pokemon I get the error of Invalid Console Region. This doesn't occur in the latest release but only when I compile myself. It happens when PKHeX is loaded as a standalone or with my save file loaded. 

The only way I know of getting rid of this error is to import or edit a set over a legit caught Pokemon from in game.

![Capture](https://user-images.githubusercontent.com/58532668/70183363-7f048a00-169a-11ea-8331-0a439d509eb5.PNG)

Same Tyranitar just imported over a legit caught Pokemon from my game now shows legal.

![Capture1](https://user-images.githubusercontent.com/58532668/70183875-7d879180-169b-11ea-9249-b28a1a3e89c1.PNG)

**Comment by kwsch** [comment]
New checks have been added since the last release; these new checks flag incorrectly data for console/country origins. SW/SH origin data should not have a Console Region / Country / Subregion value specified, as the Switch does not expose the same data as the 3DS did.
