### ISSUE TITLE
How do I correct "Invalid: Geolocation: Country is not in 3ds region." for Pokemon Sword and Shield on latest commit?

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2561]
As the title says, how do I correct "Invalid: Geolocation: Country is not in 3ds region." for Pokemon Sword and Shield on latest commit? Updated PKHeX today to find out basically all of my Pokes are invalid with this error. How do I fix it?

**Comment by BetaLeaf** [comment]
Read #2560, how do I remove these values?

**Comment by kwsch** [comment]
Batch Editor, as these are not exposed to the GUI.

**Comment by BetaLeaf** [comment]
Which value am I setting and what to?

**Comment by BetaLeaf** [comment]
I cannot find SubRegion. I tried setting the other 2 values to 0 but still illegal with same error

**Comment by BetaLeaf** [comment]
For the record, batch editor using this:
```
.ConsoleRegion=0
.Country=0
.Region=0
```
