### ISSUE TITLE
Gen 3 R/S(E) Egg Language.

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2563]
**Describe the bug**
Gen3 Egg Ruby and possibly Sapphire from Hot-springs is displaying wrong language, nickname and language is wrong,

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12572974/70346405-45638880-182c-11ea-92c2-cf5badce2151.png)

here is the same egg after hatching it
![image](https://user-images.githubusercontent.com/12572974/70346536-86f43380-182c-11ea-8916-924bafbae8fe.png)

**Additional context**

**Comment by kwsch** [comment]
All eggs are Japanese until they hatch. The game displays EGG anyways.

Working as intended.
