### ISSUE TITLE
Unable to view/edit form or happiness

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#2569]
This occurs when using the version 19.12.09  of PKHeX provided from the downloads section. When launching PKHeX 

The box to modify friendship is gone, and the dropdown box for form modification is also missing.
![image](https://user-images.githubusercontent.com/15519892/70410697-ed8c7380-1a1d-11ea-98df-c10505ddb3f3.png)

I'm running Windows 10 64 bit.
Thanks so much for taking the time to read this, and for all your work on PKHeX.

**Comment by kwsch** [comment]
Probably related to DPI setting and the addition of the new (FormArgument) combobox which makes the panel no longer show...

**Comment by greenDarkness** [comment]
The issue still persists on my machine after updating to the latest commit. 
Is there something I can do to help troubleshoot the issue?

**Comment by kwsch** [comment]
You'd have to play with the WinForms designer for the PKMEditor to change the width of the two FlowLayoutPanels that my commit attempted to modify. I might not have done it small enough?

**Comment by greenDarkness** [comment]
Is this the right spot? If so which values am I decreasing?
Thanks so much for taking the time to look into this.
