### ISSUE TITLE
Overworld encounters which are not currently recognized as legal

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#2570]
Below is a zip file containing 6 PK8 files which PKHeX currenly does not recognize as legal. 
All of these are overworld encounters except for Pumpkaboo which was a 4 star raid. 
[wew.zip](https://github.com/kwsch/PKHeX/files/3938051/wew.zip)

Thanks so much for all your work with PKHeX.

**Comment by kwsch** [comment]
Pumpkaboo: https://www.serebii.net/pokedex-swsh/pumpkaboo/

No raid locations listed for Dusty Bowl...?

**Comment by greenDarkness** [comment]
I can't remember which den I caught it at, but I know I haven't changed that Pumpkaboo in any way.

Also, latest commit fixes all the the Pokemon I attached previously except for the Pumpkaboo in question; however, I have two more to attach which are now marked as illegal. 
Both are overworld encounters.

[wew.zip](https://github.com/kwsch/PKHeX/files/3944140/wew.zip)

**Comment by greenDarkness** [comment]
Here's another addition.
[598 - Ferrothorn - 2332AF0C18CE.zip](https://github.com/kwsch/PKHeX/files/3954060/598.-.Ferrothorn.-.2332AF0C18CE.zip)

**Comment by greenDarkness** [comment]
This one might be out of the scope of this issue, but I figured I'd just post it here rather than opening a new issue for something this minor. 
After catching Gallade with a Corviknight a friend traded me from Shield, Corviknight's HT memory changed, and the Pokemon was marked as illegal. 
[823 - Corviknight - DBDDAFFEF1F9.zip](https://github.com/kwsch/PKHeX/files/3991030/823.-.Corviknight.-.DBDDAFFEF1F9.zip)

**Comment by ReclaimerShawn** [comment]
Here are some static encounter pokemon that are marked illegal but are legal:

Everything except Coalossal was caught in the Wild Area. Coalossal was caught as a Carkol in the Galar Mine and was evolved.

[Illegal Pokemon.zip](https://github.com/kwsch/PKHeX/files/3992169/Illegal.Pokemon.zip)

**Comment by kwsch** [comment]
All issues resolved besides the aforementioned 4-Star raid Pumpkaboo-0 at Dusty Bowl.
I checked the Raid Plugin mappings and none have Pumpkaboo-0 at Dusty Bowl, so I can't resolve this without more information.

**Comment by greenDarkness** [comment]
What sort of info would you need? Would another pk8 file for one suffice if I can get the encounter again?

**Comment by kwsch** [comment]
@greenDarkness It's been resolved!
https://github.com/kwsch/PKHeX/commit/ceae77c67753cfa614529d801a56a72b41d539f2

**Comment by greenDarkness** [comment]
Thanks! I was on mobile and I didn't see that.
