### ISSUE TITLE
Hatched egg after an egg trade does not have HT Memory values set to 0

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#2571]
**Describe the problem**
Looking at a legit save, the pkm are all traded as eggs to this save and then they are hatched on the save. Opening the PKM in PKMView and then clicking the red legality icon just automatically legalizes them and shows as legal (assuming due to memory being refreshed on legality check). So the screenshot below are after ctrl+clicking on the PKM in box!

**To Reproduce**
Trade an egg from one save file to another and then hatch it in the second save

**Expected behavior**
Should show legal. Probably another SWSH quirk

**Screenshots**
![image](https://user-images.githubusercontent.com/17220860/70439270-985a6b80-1aca-11ea-8fb2-f66cf03f6569.png)

Zipped up the PKM after dragging and dropping directly from the box
[lol.zip](https://github.com/kwsch/PKHeX/files/3939869/lol.zip)

**Comment by kwsch** [comment]
How annoying.
