### ISSUE TITLE
Zeraora: Event OT Friendship does not match base friendship.

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2572]
**Describe the problem**
Event Zeraora gets this error, even though OT Friendship matches base friendship.

**To Reproduce**
Get a Zeraora from Event Database, check legality.

**Expected behavior**
Should be legal.

**Screenshots**
![image](https://user-images.githubusercontent.com/43770697/70448287-23594880-1a6e-11ea-81c9-7c8730249b92.png)
![image](https://user-images.githubusercontent.com/43770697/70448349-3bc96300-1a6e-11ea-8e1e-7ad609cdb4b7.png)

**Additional context**

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/f832cff689bbeade8021a3f124e226b026885c89/PKHeX.Core/Legality/Verifiers/HistoryVerifier.cs#L176-L188

All `PersonalTable.SM` should be `PersonalTable.USUM`, as Zeraora was released in USUM. The SM fetch probably grabbed the wrong value.

The friendship check is probably flawed; not sure if there's any evolutions with different base friendship -- at the moment, the check compares the current SpeciesID.

**Comment by sora10pls** [comment]
@kwsch Some Pokémon \*do* have differing base Friendship values; some examples are Eevee (70) vs Leafeon/Glaceon (35) and Croagunk (100) vs Toxicroak (70).

Values I mentioned are from USUM (SWSH changed a handful).
