### ISSUE TITLE
Unreleased Items list currently complete?

### ISSUE THREAD

**Issue by AnalogMan151** [kwsch/PKHeX#2574]
I was wondering if this list of unreleased items is complete now or if you're still looking for contributions?

https://github.com/kwsch/PKHeX/blob/f832cff689bbeade8021a3f124e226b026885c89/PKHeX.Core/Legality/Tables/Tables8.cs#L376

**Comment by kwsch** [comment]
I had grabbed the list from Serebii's site; any item not mentioned (location wise) was added to the unreleased list.

@sora10pls mentioned that the wings were obtainable, so revisions to this list are expected 😄

**Comment by AnalogMan151** [comment]
By wings I assume you mean Feathers? If so I know you can find them on the bridges between Route 5 and Hulbury; and Motostoke and Motostoke Outskirts. They're the sparkly hidden items and repawn every day.

**Comment by sora10pls** [comment]
@AnalogMan151 Yes, they were renamed from Wings (Gens 5-7) to Feathers in Gen 8.

Currently, the revisions that need to be made are as follows:
* Add Ribbon Sweet and Star Sweet
* Remove Feathers (obtainable on Bridges, just like in BW/B2W2)
* Remove Old Gateau (obtainable from Battle Cafés)

Anything else will still need verification from people playing the game more, though it looks about as accurate as it can be for now.
