### ISSUE TITLE
Decrypt save files

### ISSUE THREAD

**Issue by funkyouo** [kwsch/PKHeX#2576]
I wanted to change my clothes data. So I used some Hex editor such as winhex to load the save files. By constantly buying clothes and comparing save files I found its address. But it looks like it is encrypted so that I cannot easily change its value. Is there a way to decrypt the save files like PKHex does and show its real value?

**Comment by kwsch** [comment]
You can dump the fashion block via the Immediate Window in visual studio; set a breakpoint at the end of the BlockAccessorSWSH creation

**Comment by funkyouo** [comment]
I remember that 0 means clothes aren't owned and 1means clothes are owned in SM/USUM. Unexpectedly it's so complicated in gen 8. Anyway, thank you for reply.
