### ISSUE TITLE
Generation 6 OT memories in Generation 7 saves.

### ISSUE THREAD

**Issue by ijuintekka** [kwsch/PKHeX#2581]
**Describe the problem**
Generation 6 pokemon with an OT memory, and Generation 7 in-game trades, are flagged in Generation 7 saves because of the new rule referencing format instead of origin:
https://github.com/kwsch/PKHeX/blob/802b93bb16d0df41beeaef838547c9df9b8c5a06/PKHeX.Core/Legality/Verifiers/MemoryVerifier.cs#L100
Also possibly the wrong memory for generation 7 in-game trades if that is the rule's intended purpose?

**To Reproduce**
Open any Generation 6 pokemon, or Generation 7 in-game trade, with an OT memory in a Generation 7 save.

**Expected behavior**
OT memories should be legal for Generation 6 pokemon and Generation 7 in-game trades.

**Screenshots**
![Image1](https://user-images.githubusercontent.com/28776339/70610569-b4a9f580-1bfb-11ea-9a09-98c5e0461465.png)

**Comment by IngEyn** [comment]
I just encountered the same issue through the same method.
