### ISSUE TITLE
FR/LG Selector Prompt

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2582]
Is the prompt for opening FR/LG still necessary? I opened a LG Sav but clicked FR by mistake and was able to open, edit and export the Sav file with no errors, also tested it by opening a LG sav selecting FR as the save type, at this point the prompt seems pointless

**Screenshots**
![image](https://user-images.githubusercontent.com/12572974/70732412-61f13c00-1cd6-11ea-96f8-b7dad6e51d45.png)

**Additional context**
if their was a previous issue with identifying FR/LG saves that was fixed, the prompt should be removed (IMO)

**Comment by sora10pls** [comment]
The selector is used for Personal Data differences (Attack Forme Deoxys in FireRed, Defense Forme Deoxys in LeafGreen).

[The game's Version ID is not detectable from the save data](https://github.com/kwsch/PKHeX/issues/1320#issuecomment-314614762), so PKHeX needs to ask the user which game the save data belongs to.

**Comment by Ninjistix** [comment]
okay, makes sense now, its best to close this then, now that I know what the prompt is actually for.
