### ISSUE TITLE
Poketch issue

### ISSUE THREAD

**Issue by Masaru2** [kwsch/PKHeX#2584]
in latest version of PKHeX, Editing Misc Edits in platinum breaks the step counter,  it can only reset to 0 then jump back to the number it was at before resetting after doing a step, Also changes the color of the poketch
![Screenshot_20191212-185800](https://user-images.githubusercontent.com/39504593/70759687-fb940a00-1d25-11ea-9e67-982545dfa8ec.png)

**Comment by kwsch** [comment]
Not able to replicate on current commits (no changes have been made since last release). 
Fetching the PoketchColor before/after saving results in the same value.
