### ISSUE TITLE
Sword and Shield in-game trades legality

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#2589]
**Describe the problem**
All of them do not get checked for their static Gender and Nature values.

**To Reproduce**
Modify any of their Gender (if applicable) and Nature values.

**Expected behavior**
Should not pass with said modifications.

**Screenshots**

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/In-game_trade#Sword_and_Shield
https://www.serebii.net/swordshield/ingametrade.shtml

**Comment by sora10pls** [comment]
Abilities don't have to be checked because Ability Capsule can swap between Abilities 1 and 2, and none of them come with their Hidden Abilities.

**Comment by architdate** [comment]
Wait what? Why close this? The commit referenced above isn't yet merged and this is still a valid issue!
