### ISSUE TITLE
UI Tweaks and translations

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#259]
Box Name without translations in Fire Red
![captura1](https://cloud.githubusercontent.com/assets/4681902/18417067/7a01c42a-7826-11e6-97ad-0a8b8270e294.PNG)

Form displaced in ORAS
![captura2](https://cloud.githubusercontent.com/assets/4681902/18417071/8846ef42-7826-11e6-913c-841757a63e4b.PNG)

Texts displaced in ORAS
![captura3](https://cloud.githubusercontent.com/assets/4681902/18417073/982b3d8c-7826-11e6-827d-e8ecb73a6b63.PNG)

Items and locations still show in english for Gen 1-3
![captura4](https://cloud.githubusercontent.com/assets/4681902/18417075/ae3bbd4a-7826-11e6-9991-48102517b29a.PNG)
![captura5](https://cloud.githubusercontent.com/assets/4681902/18417076/ae3d2900-7826-11e6-8b4d-cf491a6d9a0b.PNG)
![captura6](https://cloud.githubusercontent.com/assets/4681902/18417077/ae404bda-7826-11e6-9087-6306f3375799.PNG)

In gen 2, all PKM shows in Met Location (None)
![captura7](https://cloud.githubusercontent.com/assets/4681902/18417082/dbbbdca0-7826-11e6-947a-a40847e6a977.PNG)

**Comment by suloku** [comment]
Gen 2 met location: this is only generated in crystal or event pokemon, so it's probably fine.

**Comment by kwsch** [comment]
First pic: That's the name of the box in the save file.

`CB_BoxSelect.Items.Add($"BOX {i}");`

if it failed to load it'd be "BOX 1" instead of "BOX1" :)
