### ISSUE TITLE
Legality Check Issue when using DLL

### ISSUE THREAD

**Issue by FM1337** [kwsch/PKHeX#2594]
**Describe the problem**
When checking the legality of some Pokemon (sample files attached) I get "Analysis not available" and debug output of 

```
Exception thrown: 'System.ArgumentException' in PKHeX.Core.dll
RibbonNational
Exception thrown: 'System.ArgumentException' in PKHeX.Core.dll
RibbonNational
Exception thrown: 'System.ArgumentException' in PKHeX.Core.dll
RibbonWishing
Exception thrown: 'System.ArgumentException' in PKHeX.Core.dll
RibbonWishing
```

**To Reproduce**
Try running a legality check using the latest source build of the PkHeX core.

**Expected behavior**
A legality check to be performed correctly. 
**Screenshots**
![image](https://user-images.githubusercontent.com/5448220/71134046-3dfc9180-21d3-11ea-90f4-f8e9c82a2966.png)

**Additional context**
It works fine in the GUI version of PkHeX and so I'm not sure what I'm doing wrong.

[pkmn.zip](https://github.com/kwsch/PKHeX/files/3981088/pkmn.zip)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/4bf71de6213a40b5ae9e09f5212e47a3cdf16826/PKHeX.Core/Legality/Analysis.cs#L146

Set a breakpoint there and debug the process, or recompile with the `#define SUPPRESS` commented out so that the verification logic is done without a trycatch.
