### ISSUE TITLE
Integer scaling for box sprites

### ISSUE THREAD

**Issue by Corgano** [kwsch/PKHeX#2596]
The GUI in general is inexcusably tiny. If you open it on a small 4k screen, it is nearly impossible to tell one pokemon from another. However changing the size is already implemented for pokemon sword. Give an option to force this for older pokemon games! Sprites even at 2x or 3x scale still look nice, but would make it easier to see especially on high-res monitors.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2494
