### ISSUE TITLE
Fennel Munna not in Mystery Gift List

### ISSUE THREAD

**Issue by CorvusAtrox** [kwsch/PKHeX#2598]
**Describe the problem**
Was using PkHeX with Sun Version (in Spanish) and noticed my Fennel's Munna was flagged as illegal. Likewise did not see it 

**To Reproduce**
[517 - Munna - Prof. Oryza.zip](https://github.com/kwsch/PKHeX/files/3995122/517.-.Munna.-.Prof.Oryza.zip)
Both Munna and Mystery Gift Data are in file

Expected behavior
Should be legal and should be able to find in Mystery Gift Database

Screenshots
![OryzaMunna](https://user-images.githubusercontent.com/7748403/71360651-25cf9e00-2556-11ea-8bfe-7423531c336b.png)

**Comment by kwsch** [comment]
PKHeX uses https://github.com/projectpokemon/EventsGallery as the database source; see the last line of the legality report:

> Has the Mystery Gift data been contributed?

Nope, it's not in the above repository, so it won't be recognizable in PKHeX.

No result for card 1638:
![image](https://user-images.githubusercontent.com/6393368/71378600-452df180-257d-11ea-8304-0a0358e573cf.png)
@kamronbatman @PP-theSLAYER

**Comment by kamronbatman** [comment]
Added
