### ISSUE TITLE
changing the male to female

### ISSUE THREAD

**Issue by vinnycl** [kwsch/PKHeX#26]
i changed the sex for my trainer from male to female
i boot the the game , i saw the save with a female logo trainer
hit continue 
but it wont start
i waited 5 minutes 

is it possible to change the character ?

Try to change clothes. And copy all val from other game. But didn't work. 

I'm sure, copied everything.

**Comment by kwsch** [comment]
Probably not possible. I may end up disabling that DropDown for future releases since changing the gender causes the game to lose its marbles (models/flags etc)
