### ISSUE TITLE
Celebi shows as illegal using G/S/C blank save

### ISSUE THREAD

**Issue by slp32** [kwsch/PKHeX#2600]
**Describe the problem**
When using the blank save setting set to G/S/C, Celebi will always show as illegal as there is no way to change it's region to JPN. Maybe it could be made that the blank save uses VC legality checks, so the Celebi verifies as legal like the GEN1 VC Mew does.

**To Reproduce**
Change the blank save setting to either G/S/C, and import either the Celebi from the Encounter Database or [251 - CELEBI - 571A.zip](https://github.com/kwsch/PKHeX/files/3998598/251.-.CELEBI.-.571A.zip)

**Expected behavior**
Celebi shown as legal inside of the blank save and when transferred to a GEN2 VC save, but not when transferred to a regular GEN2 save.

**Screenshots**
![image](https://user-images.githubusercontent.com/59178883/71417815-5d763d00-265f-11ea-8148-a5bba052fada.png)

**Comment by kwsch** [comment]
The blank save is a gb era save file, not a virtual console blank save file.
GS Celebi was not obtainable on English saves.

**Comment by slp32** [comment]
This was more of a request to have the GEN2 blank save be seen as a VC blank save, so GS Celebi would be shown as legal. When using a GEN1 blank save, the VC Mew is shown as legal, which I don't think was an actual GEN1 event.

**Comment by slp32** [comment]
Commit 420307d doesn't seem to work. The same Celebi verifies as legal on an actual VC DAT save file, but not on the blank save.

**Comment by kwsch** [comment]
hahaha oops
