### ISSUE TITLE
G-Max Charizard Raid Not Marked as Rare (more research needed)

### ISSUE THREAD

**Issue by crzyc** [kwsch/PKHeX#2601]
**Describe the bug**
A Gigantamax Charizard Raid that was spawned in using the frame advance method does not have the IsRare boolean value set as true when viewed in PKHeX. I understand that this feature was just released today, meaning that more improvements are on the way, but hopefully, the following information will be helpful.

**To Reproduce**
DenType: 4
Flags: 1
Hash: 272156430860755085
IsActive: True
IsEvent: **False**
IsRare: **False**
RandRoll: 96
Seed: 17043611441262022461
Stars: 4

The following lines result in a G-Max Charizard in the Lake of Outrage. Put the following in Den 98 in PKHeX and save. A purple beam should appear where the Charizard normally spawns, which is a "rare" spawn.

Speaking of which, may I have some insight on what the Hash and RandRolls do?

**Expected behavior**
PKHeX should have marked it as "True" in IsRare.

**Screenshots**

![PKHeX_2019-12-24_20-52-02](https://user-images.githubusercontent.com/18177787/71428514-3fc0cc00-268f-11ea-9418-6ae392801fd6.png)

**Comment by architdate** [comment]
At the current moment the code marks odd raids as rare, which is wrong. But we dunno what makes a den rare yet!

**Comment by crzyc** [comment]
Do we know what Hash and RandRoll does yet? I know it has something to do with the pokemon generated (obviously, since replicating the same raid will result in a Sassy Charizard with a constant PID), but how does it tie in with said max raid pokemon?

**Comment by architdate** [comment]
Hash is probably just a check of some sort and randroll determines the species.

**Comment by crzyc** [comment]
Thank you. Happy holidays as always.

**Comment by kwsch** [comment]
RandRoll is the RNG call for selecting which encounter in the nest. 0-99
Hash is a fnv hash of something, so don't modify it!
