### ISSUE TITLE
Galarian Yamask and Runerigus damage counter

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2604]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Any Runerigus evolved from Galarian Yamask pass if their damage counter is below 49. 
If caught from a Raid, it passes if it's above 0.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

Set an evolved Runerigus' damage counter to 48 or lower, and a Raid's above 0.

**Expected behavior**

Evolved Runerigus would need to have a 49 or higher count to pass, and captured should always be 0.

**Screenshots**

N/A

**Additional context**

The counter always gets reset for both Galarian Yamask and Runerigus when setting to a slot, despite unticking the option to Modify PKM Info.

**Comment by NinFanBoyFTW** [comment]
Hey I just wanted to let you know that my Runerigus is showing up now as illegal and it is not hacked at all. Thanks

[867 - Runerigus - E61A31A4EC89.zip](https://github.com/kwsch/PKHeX/files/4050219/867.-.Runerigus.-.E61A31A4EC89.zip)

**Comment by kwsch** [comment]
Older PKHeX commits would clear the FormArgument incorrectly. It is not known if there's a way to get the game to clear the value.
