### ISSUE TITLE
Raid Milcery evo

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2605]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

I evolved a Milcery caught from a Raid and it evolved into the Matcha Cream variant, but PKHeX flags it. However, setting it to Vanilla Cream makes it pass.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

[869-02 - Alcremie - DED2086834BA.zip](https://github.com/kwsch/PKHeX/files/4006878/869-02.-.Alcremie.-.DED2086834BA.zip)

**Expected behavior**

It should be legal with other flavors.

**Screenshots**

**Additional context**

https://www.serebii.net/swordshield/maxraidbattles/den34.shtml
https://www.serebii.net/swordshield/maxraidbattles/den74.shtml

**Comment by kwsch** [comment]
Thanks, fixed by https://github.com/kwsch/PKHeX/commit/849347179374de4b56aff2044ea5059c06c1b4b8 !
