### ISSUE TITLE
Gen 3 Daycare + PC Box bugs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#261]
Other tab displays no data at all
![image](https://cloud.githubusercontent.com/assets/17801814/18418767/88db031e-781a-11e6-8f7a-105153703445.png)

When viewing certain Pokemon from my PC Boxes, I notice that it only semi-updates the information. As shown in the picture, when trying to view my Gengar, it keeps the nickname and sprite of the previous Pokemon I viewed (in my case, Gulpin).
![image](https://cloud.githubusercontent.com/assets/17801814/18418768/95aae5aa-781a-11e6-9972-d02f924ebc4f.png)

Some Pokemon work fine, such as this Kangaskhan, while some others in the PC Box don't (examples include Gengar, Mightyena, Skiploom, Swampert, and even more).

Also, as a side-note, unchecking the nickname checkbox keeps the nickname, and doesn't revert to the Pokemon's name in full capital letters.
![image](https://cloud.githubusercontent.com/assets/17801814/18418817/432ebc2e-781b-11e6-9f27-a484d19ee536.png)

**Comment by kwsch** [comment]
1: Gen3 daycare is undocumented / unimplemented (only gen that doesn't!)
2/3: Appears that something is preventing certain events from firing, I can't replicate / trace it. Try repeating it after restarting the program.

**Comment by sora10pls** [comment]
I tried as you suggested before (about 2 or 3 times) with no avail. I'm at work now so I can't do further testing until later tonight

**Comment by suloku** [comment]
I'm pretty sure trigger's pc has daycare and it's open source. Also has egg flags for daycare I think.

**Comment by ricksee** [comment]
@kwsch I would like to request to add "As an Egg" check under the met conditions. The games, especially Gen II and Gen III have the ability to make eggs. In the summary it said (Egg) next to the place it was hatched.

**Comment by kwsch** [comment]
@ricksee , the Pokémon is determined to be hatched from an egg if the Met Level is 1. There is no "As Egg" flag in any of the pk* structures. It's not worth making that checkbox visible when it's not a separate pkm property.

**Comment by kwsch** [comment]
Referenced commit ([above](https://github.com/kwsch/PKHeX/commit/50b4ebc4ba962c4d9467e09ab4ea0181ddb26374)) and [latest commit](https://github.com/kwsch/PKHeX/commit/74dd6012d1656204650a66f76f5db75609d8d00a) should clear up this issue. Thanks for reporting :+1:
