### ISSUE TITLE
Cherrim Legality with ver. 19/12/26

### ISSUE THREAD

**Issue by dstevenson12** [kwsch/PKHeX#2610]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Caught Cherubi from shaking berry tree in Wild Area at lv 60, post-story. Evolved to Cherrim with one (1) Rare Candy. 

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

[421 - Cherrim - 47D7B8D97991.zip](https://github.com/kwsch/PKHeX/files/4008399/421.-.Cherrim.-.47D7B8D97991.zip)

**Expected behavior**

**Screenshots**

**Additional context**

Not edited, legality flagged when viewing save.

**Comment by kwsch** [comment]
https://www.serebii.net/pokearth/galar/stonywilderness.shtml
https://www.serebii.net/swordshield/berrytrees.shtml

Stony Wilderness doesn't have a Berry Tree?

**Comment by kwsch** [comment]
Yay, this is another load-line overlap similar to the Den addressed in https://github.com/kwsch/PKHeX/commit/ceae77c67753cfa614529d801a56a72b41d539f2

Probably isn't a neat way to handle this so I'll probably just have to clone the location data.
