### ISSUE TITLE
G-Max Alcremie decoration

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2611]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Any G-Max and just regular Alcremie Raid captures only bear the Vanilla Cream (which is checked) and Stawberry decoration (not checked).

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

Change a G-Max Alcremie's decoration to anything other than Strawberry.

**Expected behavior**

G-Max Alcremie shouldn't pass with a decoration other than Strawberry.

**Screenshots**

Here's an example of an otherwise legal G-Max's decoration being edited:
![alcremie g-max](https://user-images.githubusercontent.com/43196464/71563490-3dc78600-2a5e-11ea-8c66-2b07a50e1856.jpg)

**Additional context**

**Comment by kwsch** [comment]
`FormArgument` verification isn't implemented yet, similar case as #2604
