### ISSUE TITLE
Pokemon Sword/Shield Shiny Variant Options

### ISSUE THREAD

**Issue by foohyfooh** [kwsch/PKHeX#2614]
**Is your feature request related to a problem? Please describe.**
Currently cannot set which shiny variant for Pokemon Sword and Shield

**Describe the solution you'd like**
Add the option to select which of the shiny variants when selecting shiny in Pokemon Sword and Shield

**Comment by slp32** [comment]
This is already in PKHeX. Hold Shift while clicking on the shiny button.

**Comment by foohyfooh** [comment]
@slp32 Thanks for informing me. It wasn't that intuitive to me.
