### ISSUE TITLE
Disable Popup Sound

### ISSUE THREAD

**Issue by foohyfooh** [kwsch/PKHeX#2615]
**Is your feature request related to a problem? Please describe.**
When I open the application or do a legality check there is a sound effect for the popup.

**Describe the solution you'd like**
Either remove the sound or provide an option in the settings to disable it.

**Comment by kwsch** [comment]
The sound playing is done via the popup dialog, and the sound is also triggered for other popups as well. 

https://github.com/kwsch/PKHeX/blob/350895aba6a0fb50b394a991a8751801b02eb870/PKHeX.WinForms/Util/WinFormsUtil.cs#L101-L125

Do you wish to disable all sounds from the program? There's also other manual calls to play a sound (pressing a cheat code button for example) to notify the user that an action has occurred successfully.

**Comment by foohyfooh** [comment]
The sound should definitely play for errors since a user is expecting something else to occur.
On startup or legality check where the user expects a dialog to popup and can see that it is a success of the action they clicked should probably not have a sound.
