### ISSUE TITLE
Validation for Gmax pokemon

### ISSUE THREAD

**Issue by mickeyandkaka** [kwsch/PKHeX#2617]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It seems that Gmax pokemon can be only obtained from raid battle. Also, from [here](https://github.com/Admiral-Fish/RNGWriteups/blob/master/Gen%208/Raid%20Generation.md), EC, PID was generated from specific and constant seed. Random PID  or random shiny PIDmay not be valid even currently pkhex marked it as legal.
So, can you generate the pid, ec, according to the rule if it's a gmax pokemon?

**Describe alternatives you've considered**
Anything following the generating rule will be ok.

**Additional context**
Nothing.

**Comment by mickeyandkaka** [comment]
Oh, does this  [commit](https://github.com/architdate/PKHeX-Plugins/commit/976e9a0455241e1d2331b870f61931ec607ee075) did this job ?

**Comment by kwsch** [comment]
Are you referring to the Legality Check (comparing EC/PID/IV for legality), or referring to the Encounter->PKM generating?

**Comment by mickeyandkaka** [comment]
Both. However I know it may be impossible for checking Gmax legality because seed will take long time to search.

But when generating pokemon, When I click star buttom to make shiny, I mean you will random a seed, then following the rule to generate the shiny pid, ec, ivs
