### ISSUE TITLE
Inputting invalid species name into Encounter Database causes it to keep searching

### ISSUE THREAD

**Issue by slp32** [kwsch/PKHeX#2620]
**Describe the bug**
When searching for an invalid species name in the Encounter Database (for example, just putting `AAAA`), causes it to keep searching forever. If you close the Encounter Database tab, open another and do the same thing, the program will start running slower.
If you do the same on the Mystery Gift Database/PKM Database, it will show `No results found!` which is correct.

**To Reproduce**
1. Open the Encounter Database.
2. Put an invalid name into the `Species` box.

**Expected behavior**
The message `No results found!` should pop up, like the other databases.

**Screenshots**
From the Encounter Database (notice the search bar darked out):
![image](https://user-images.githubusercontent.com/59178883/71763926-df752a00-2ed9-11ea-9526-15bff2b6abbc.png)
From the Mystery Gift Database:
![image](https://user-images.githubusercontent.com/59178883/71763933-03d10680-2eda-11ea-9a1e-4805e782ca08.png)

**Comment by slp32** [comment]
Actually, it does eventually stop searching. However it ends up showing every Pokemon in the Encounter Database, where it should show `No results found!`
![image](https://user-images.githubusercontent.com/59178883/71764071-008a4a80-2edb-11ea-87d8-cd2411140977.png)

**Comment by kwsch** [comment]
That's the expected behavior; "Any" species is the default case if nothing is specified, causing it to look for all species that can learn the moves specified.
