### ISSUE TITLE
Growlithe flagged as not legit (Pokemon Shield)

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#2621]
**Describe the problem**
Alert Window
Invalid: OT Memory: Can't obtain Location on OT Version

**To Reproduce**
Same pkm file from two different time saving of the same save. One is seen as legit, the second one as not legit

[Legit.zip](https://github.com/kwsch/PKHeX/files/4036524/Legit.zip)

[Alert.zip](https://github.com/kwsch/PKHeX/files/4036525/Alert.zip)

**Expected behavior**
I didn't use any cheat/hack so it should be legit, as the first one (it's the same pokemon)

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/72043677-9ec53a00-3266-11ea-9391-1b5341395400.png)

The TextVar value for the legal one is 12, not 9, so not sure where that value came from. Could be that the variable-less string has an unused variable value that's still set by the game (yay copypasted code).

**Comment by Real96** [comment]
Is there anything i can do?

**Comment by kwsch** [comment]
I dunno. Just ignore it for now.

The in-game implementation of memories has been pretty sloppy as far as I can tell, as some memories have text arguments but the string they are using doesn't use it...
