### ISSUE TITLE
Save file issue, possibly flags?

### ISSUE THREAD

**Issue by deadair3210** [kwsch/PKHeX#2622]
Sorry if this isnt directly involving pkhex, but every time I try to do the Team Yell battle on Route 9, my game crashes and was wondering if someone could possibly point me to somehow checking the story flags in my save? Or maybe  taking a look at it? Normal battles work fine, but that one battle immediately crashes and its a required battle so if I cant get it fixed I have to restart

**Comment by kwsch** [comment]
Event Flags are not editable for SW/SH via PKHeX; haven't found their location.

**Comment by deadair3210** [comment]
Thanks anyway, figured I would ask
