### ISSUE TITLE
Input file is too large.

### ISSUE THREAD

**Issue by jbjornberg** [kwsch/PKHeX#2623]
**Describe the bug**
When attempting to upload any save housing a Galarian Slowpoke, it returns this error.

**To Reproduce**
Step 1: Get new dank Slowpoke that came out recently
Step 2: Try to edit Slowpoke to be super dank
Step 3: Get slapped with error code

**Expected behavior**
I expected to make this Slowpoke the dankest slowpoke to ever live.

**Comment by kwsch** [comment]
Loading save files works fine on the latest commit.

Will likely update with the sprite, personal data, and new raid content in less than a day.
