### ISSUE TITLE
Add extra button shortcuts for Randomize IVs button

### ISSUE THREAD

**Issue by slp32** [kwsch/PKHeX#2629]
Currently, the only button shortcut for `Randomize IVs` is CTRL, which sets all IVs to 31. Could additional button shortcuts be added, such as pressing ALT to set all IVs to 0, and SHIFT to set all IVs to 30?

**Comment by kwsch** [comment]
Individual IVs can be clicked with alt for 0, Ctrl to toggle 30/31, and shift to hypertrain; it's not really worth having all IVs 0/30.
