### ISSUE TITLE
Lost Pokemon Center New York event pokemon

### ISSUE THREAD

**Issue by deadair3210** [kwsch/PKHeX#2631]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Recently, some lost event pokemon from the defunct Pokemon Center in New York were found and recovered, currently some of them are appearing as illegal due to not having a Met Location

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

Video explaining the lost pokemon situation - https://youtu.be/AVhqlol6k9o

**Expected behavior**

Event Pokemon marked as Legal

**Screenshots**

**Additional context**
Was mostly letting someone know about the issue, not a bug since until now they were lost

**Comment by kwsch** [comment]
Gen3 Event data is not serialized into a format which can be checked against.

https://github.com/kwsch/PKHeX/blob/95f24a9d36689026044e85618e58be8fae3c8b51/PKHeX.Core/Legality/Encounters/Data/EncountersWC3.cs#L6-L13

The community would have to organize that event data into some type of digestible format; I'm not going to hard-code every gen3 event myself.

**Comment by deadair3210** [comment]
Ok, was just letting someone know just in case

**Comment by deadair3210** [comment]
Would these be considered illegal if traded to later generations?

**Comment by deadair3210** [comment]
And sorry about the barrage of questions, but there are some event pokemon from gen 2 in there as well, are those the same?

**Comment by kwsch** [comment]
Same situation for gen1-2 event data.

Would they be considered illegal? Possibly, depends on what the official legality check has whitelisted (it's a very loose legality check).

**Comment by deadair3210** [comment]
I see what you mean about gen 1-3 event data being weird, the tid and pid of these pokemon are really weird.  TID 00005 SID 00000 on a Event Pikachu

**Comment by deadair3210** [comment]
Thanks anyway
