### ISSUE TITLE
About Block Data

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2635]
Hey, so I tried out the new Block Data feature implemented and it's really useful!
I was wondering, would it be possible to add an option to export only files of a certain type such as Data only?

On another note, I found my Rally Best Score on the raw.bin from the latest commit it made and hope it's of any help: 0xBAA86-0xBAA87 is for your main and 0x86829-0x8682A is what's displayed on your League Card. My save is from version 1.1.0 btw.

**Comment by kwsch** [comment]
Please use the latest commit to indicate which block-key these offsets are in.

With the ASCII marking, it has a format BLOCKXXXX HHHHHHHH, where X is the index and H is the key. If you omit the Key and Type info from the dump, the data starting right after HHH.. is Offset 0 for that block.

**Comment by CanoeHope** [comment]
Ok thanks. :)

I found it on the 874DA6FA.bin in 0x28-0x29 and 0x00-0x01 in the 38548020.bin files.

**Comment by CanoeHope** [comment]
One more thing I found is the main League/Uniform ID. (What PKHeX currently edits is just displayed on the Card)

Block Key: F25C070E

0x01-0x03
