### ISSUE TITLE
LGPE Legality Issues

### ISSUE THREAD

**Issue by dstevenson12** [kwsch/PKHeX#2636]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Electrode, Lapras and Porygon were flagged. Save hasn't been touched before opening today.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

[20200114-164605 David.zip](https://github.com/kwsch/PKHeX/files/4062125/20200114-164605.David.zip)

**Expected behavior**

**Screenshots**

**Additional context**
Lapras and Porygon are in-game gifts.
Electrode was a static encounter that did have less than the 3 IVs.

**Comment by kwsch** [comment]
The Lapras at Silph Co. has fixed IVs, same with Porygon:
https://github.com/kwsch/PKHeX/blob/f4162d2dcefdfb0ce42361a95c5be42823847f1e/PKHeX.Core/Legality/Encounters/Data/Encounters7b.cs#L49
https://github.com/kwsch/PKHeX/blob/f4162d2dcefdfb0ce42361a95c5be42823847f1e/PKHeX.Core/Legality/Encounters/Data/Encounters7b.cs#L58

The two you attached are 6*31 IV, which doesn't match the game data allowed.

The electrode is a static encounter with the same level as a wild encounter; a similar thing happened for the Voltorb: https://github.com/kwsch/PKHeX/issues/2399

I can just comment that encounter out and things will work fine. I'm not sure about the other two, unless they were changed by a game patch (doubtful).

**Comment by dstevenson12** [comment]
I'm honestly not sure either then. I guess I don't have a good way of replicating the Porygon/Lapras ones without playing through it again, so can't argue against what you have for the encounter data. To sanity check, I assume providing the whole save wouldn't be of additional value?

**Comment by kwsch** [comment]
The save won't be of any help :\

I've checked with other players, and they have the fixed-IV data matching the game (not 6IV).
I'll comment out the electrode encounter, but without any other proof, can't change anything.
