### ISSUE TITLE
HGSS Trading Flag Label

### ISSUE THREAD

**Issue by asterysx** [kwsch/PKHeX#2640]
Sorry @kwsch, I don't know if you've seen the comment I made on 726947eaf536f58088fd26a14c482bf58b27d3ae but I have a question:

Shouldn't the label text on flag **0789** say: "Trading Functionality **_Disabled_** (Pokecenter)"?

(The flag has to be **UnSet / unticked** to enable trading).

Thank you.

**Comment by kwsch** [comment]
Ah, I had just copypasted it from B/W assuming it was the same state required to trade.
https://github.com/kwsch/PKHeX/issues/2628
