### ISSUE TITLE
PKHeX.WinForms refuses to build on Linux

### ISSUE THREAD

**Issue by autofire372** [kwsch/PKHeX#2641]
**Describe the bug**
Trying to build PKHeX.WinForms on Linux via MonoDevelop causes the compiler to complain that the program can only build for Windows (error NETSDK1100).

**To Reproduce**
1. Get PKHeX source code
2. Install .NET Core 3.1 SDK
3. Open PKHeX.sln in MonoDevelop
4. Build PKHeX.core
5. Attempt to build PKHeX.WinForms
6. Observe error NETSDK1100 in output as build fails

**Expected behavior**
I expect PKHeX to build, frankly.

**Additional context**
Running Linux Mint 19.3 and MonoDevelop 7.8.4.2

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2554

**Comment by autofire372** [comment]
...There are no builds on Azure.

**Comment by kwsch** [comment]
Looks like Azure is having trouble displaying builds for users outside of the org/not logged in.

https://dev.azure.com/project-pokemon/PKHeX/_build/results?buildId=527&view=artifacts&type=publishedArtifacts

When it says "Build not found", just slap on `&view=artifacts&type=publishedArtifacts` at the end of the URL to jump to the artifacts download page for the build.

**Comment by autofire372** [comment]
Got it, thanks.

**Comment by autofire372** [comment]
I am now getting 401 errors trying to access the CI builds.

**Comment by architdate** [comment]
> I am now getting 401 errors trying to access the Azure builds.

https://projectpokemon.org/home/files/file/2445-pkhex-development-build/ there you go
