### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2644]
**To Reproduce**
Open PKHeX.exe

**Screenshots**
![image](https://user-images.githubusercontent.com/39662364/72672798-fd768900-3a9a-11ea-9d58-631913615939.png)

**Additional context**
Exception Details:
System.ArgumentException: type
   at PKHeX.Core.SCTypeCodeExtensions.SetValue(SCTypeCode type, Byte[] data, Object value)
   at PKHeX.Core.MyStatus8.set_Language(Int32 value)
   at PKHeX.Core.SAV8.set_Language(Int32 value)
   at PKHeX.Core.SaveUtil.GetBlankSAV(GameVersion Game, String OT)
   at PKHeX.WinForms.Main.LoadBlankSaveFile(GameVersion ver)
   at PKHeX.WinForms.Main.FormLoadInitialFiles(String[] args)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=20.1.10.0, Culture=neutral, PublicKeyToken=null
C:\Users\Administrator\Desktop\1\PKHeX-master\PKHeX.WinForms\bin\Release\net46\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

--------------------
User Message:
An error occurred while attempting to auto-load your save file.

**Comment by kwsch** [comment]
The save file that it was trying to load has something irregular about it; decoding threw an exception because it encountered something it thinks shouldn't be there.

**Comment by iiippppk** [comment]
When I run https://github.com/kwsch/PKHeX/commit/e4e1681e1cef7eed5937a8a7a0a6f100affdb1a8, everything is OK
When I ran https://github.com/kwsch/PKHeX/commit/2a7d475b5b2519114781cbac1ad9dfab1206beb0, it crashed

**Comment by kwsch** [comment]
It shouldn't crash on the latest commit; the SetValue logic has been updated since the crash commit you're referencing.

**Comment by iiippppk** [comment]
When I ran https://github.com/kwsch/PKHeX/commit/0244cc7489c757c265a2f0438c957d8ad5fab7d8, it crashed

**Comment by ReignOfComputer** [comment]
Is the error still the same? Latest commit should have extra information when throwing error if I'm not wrong.

**Comment by iiippppk** [comment]
> Is the error still the same? Latest commit should have extra information when throwing error if I'm not wrong.
Error
No information

**Comment by iiippppk** [comment]
Debug: No information

Release:

Exception Details:
System.ArgumentException: None
Parameter name: type
   at PKHeX.Core.SCTypeCodeExtensions.SetValue(SCTypeCode type, Byte[] data, Object value)
   at PKHeX.Core.MyStatus8.set_Language(Int32 value)
   at PKHeX.Core.SAV8.set_Language(Int32 value)
   at PKHeX.Core.SaveUtil.GetBlankSAV(GameVersion Game, String OT)
   at PKHeX.WinForms.Main.LoadBlankSaveFile(GameVersion ver)
   at PKHeX.WinForms.Main.FormLoadInitialFiles(String[] args)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=20.1.10.0, Culture=neutral, PublicKeyToken=null
C:\Users\Administrator\Desktop\1\PKHeX-master\PKHeX.WinForms\bin\Release\net46\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


--------------------

**Comment by iiippppk** [comment]
MyStatus8.cs

public int Language
{
    get => Data[Offset + 0xA7];
    set => Data[Offset + 0xA7] = (byte)value;
}
//everything is OK


public int Language
{
    get => Data[Offset + 0xA7];
    set
    {
        Data[Offset + 0xA7] = (byte) value;
        ((SAV8SWSH)SAV).SetValue(SaveBlockAccessorSWSH.KGameLanguage, (uint)value);
    }
}
//it crashed

**Comment by joey23475** [comment]
Thought i should post this here instead of opening a new issue with the same error.

Same issue on my end. After commit 2a7d475b5b2519114781cbac1ad9dfab1206beb0, PKHeX refuses to open after using visual studio to build. Getting the same error about attempting to auto-load my save file when launching PKHeX. 

Before 2a7d475b5b2519114781cbac1ad9dfab1206beb0 this was not a issue but after that commit was introduced, every commit after it have given the same result/error every time i launch the .exe.

**Comment by kwsch** [comment]
Oh I see it now; blank save related
