### ISSUE TITLE
Activating Gen 3 Events

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#265]
How is it to activate the Gen 3 events? Adding the Key Items such as the Eon Ticket and the Rainbow Pass didn't work for me.

**Comment by suloku** [comment]
When the time comes I'll try to code gen3 wondercard/mystery gift support for pkhex, we are still trying to collect all legit events.

Those events need some flags enabled besides key item. For now you might use morpheo's codes (or other) if you really want the event pokemon.

**Comment by ricksee** [comment]
I found this if it helps.

**Comment by suloku** [comment]
That program is only for japanesse savegames. In fact you'll find translated versions at project pokemon.

**Comment by ricksee** [comment]
@suloku I can't seem to find the link to it. Do you know where I can get it?

**Comment by ricksee** [comment]
@suloku Did you manage to find all legit events?

**Comment by suloku** [comment]
Sorry @ricksee for the late response:
https://github.com/suloku/wc-tool
https://projectpokemon.org/forums/forums/topic/39184-gen-iii-mystery-gift-tool-nintendo-events-wondercards-e-trainer-cards-and-e-berry-editor-and-more/

We did get at least one of each event that was officially released for each language.

I'm not sure if wc3/me3 import/export would really work for pkhex, the emerald japanese eon ticket is even more of a problem as it's not a wc3 or me3 file, but a record mixing item (which might count as me3 file) + a flag that got enabled via Mystery Event gba link cable connection.

**Comment by kwsch** [comment]
With the Misc editor that unlocks the ferry options automatically, a substitute is now available.
Injection of mg3/me3 may happen in the future, but for now this issue is closed.

**Comment by i0brendan0** [comment]
I know this issue has been closed for a long time but I’m trying to get the locations to show up but nothing is happening in my game. I’ve selected all the options in the Misc Edits > Ferry window, selected Get Tickets and even selected the “received <item> from mystery gift” event flags. The only things showing up are the Slateport/Lilycove and Battle Frontier options.
