### ISSUE TITLE
SwSh data I found

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2658]
Player's current skin color is located in **F25C070E at 0x8-0x9 and 0xD** 
(Located at **874DA6FA at 0x40-0x41 and 0x45** on the League Card).

Input the values for the following:

52 A0 and FD = M_Default
9F 9E and FC = M_Pale
EC 9C and FB = M_Tan
39 9B and FA = M_Dark
7D 8D and 54 = F_Default
64 88 and 51 = F_Pale
17 8A and 52 = F_Tan
FE 84 and 4F = F_Dark

For your mom's skin you should set the values in **F25C070E at 0x88-0x89 and 0x8D**  
(**874DA6FA at 0xC0-0xC1 and 0xC5** on the League Card) to the following respectively:

C0 95 and 52 = M_Default
73 97 and 53 = M_Pale
26 99 and 54 = M_Tan
D9 9A and 55 = M_Dark
8C 69 and CC = F_Default
3F 6B and CD = F_Pale
F2 6C and CE = F_Tan
A5 6E and CF = F_Dark

Block Key **3677602D stores the starter at 0x0** and **874DA6FA at 0x25 on the League Card**: 
0 is Grookey, 1 is Scorbunny, and 2 is Sobble.

Digging Duo streaks, both are starting at 0x00 in the following block keys:

A0F49CFB = Skill
066F38F5 = Stamina

They both appear to display beyond 10M from testing.

Block Key **874DA6FA at 0x2C-0x2E** holds the Pokémon Caught number displayed on your League Card. It only goes up to **99999** from testing.

I should also mention that https://github.com/kwsch/PKHeX/commit/ba5cc26e83277e9bf31cd37ecaa370302c8d1a5a doesn't import blocks to the save properly it seems, because there are problems in game like a static unresponsive model of Sonia outside of the lab, and also when I imported the block that had skin data it results to being stuck as the character model at the beginning of the game (shows starting outfit that's unchangeable, but skin changed).

I had no problems importing blocks and they work fine using https://github.com/kwsch/PKHeX/commit/1ba1597878e2e751fc143a9d55bc3c2548721114

**Comment by kwsch** [comment]
Model related stuff can be sticky when the block is changed. For the skin-color model content, it's just a u64 hash of the base model that is to be loaded.

I tested exporting->import->export of a few different blocks, and the data remained the same. Probably related to model hashes needing to be updated in multiple spots (especially in the big overworld block).

**Comment by kwsch** [comment]
In my commit comment (above, a88c7c4), I mentioned not hard-coding a place to edit these new values, since it'd be a pain to add GUI handling for every single one!

With the latest commit https://github.com/kwsch/PKHeX/commit/2adbca628be76bf6b8afbc5f02f20cdb66e5ef59 , value editing can now be done via the Block Dump view. I've expanded its functionality to show hex & converted value (hold shift to force hex view).
