### ISSUE TITLE
All eggs in my ultra moon save are listed as illegal

### ISSUE THREAD

**Issue by deadair3210** [kwsch/PKHeX#2666]
**Describe the problem**
Literally all of the eggs in my Ultra Moon save are listed as illegal due to a missing Origin Caught Location

**To Reproduce**
[main.zip](https://github.com/kwsch/PKHeX/files/4123725/main.zip)

**Expected behavior**
Eggs obtained and hatched legitimately are labeled as such

**Additional context**

**Comment by ReignOfComputer** [comment]
Nearly every Pokemon in this save appears to be hacked in. I highly doubt they were "hatched legitimately".

Unable to reproduce.

**Comment by deadair3210** [comment]
My bad, I misunderstood the owner of the save, the Pokemon are indeed illegit
