### ISSUE TITLE
Suggesting a Met Location does not auto-fill the Met Level anymore.

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2667]
It used to be when you have PKHeX suggest a Met Location, it would auto-fill both the location and level to the suggested values. Now, the suggested level value is not auto-filled and is now always set to 100.

**Comment by slp32** [comment]
The met level gets set to the Pokemon's current level, not to 100.

**Comment by BetaLeaf** [comment]
This issue is not fixed @kwsch, the met location is still set to the Pokemon's current level as described by @slp32. It should be set to the value suggested.

**Comment by BetaLeaf** [comment]
The commit that broke it was 81f280f4d1c96e4b00691544fe1234629db0e0c3. Commits before then work as intended, including 5a20dc707df3bc90f41c82e08e9528b03656696f, where you changed a bunch of code regarding the met level. I don't know nearly enough about c# code to help, but I know enough about visual studio and git to test on a per commit basis. Hope this helps you figure the issue out @kwsch.
