### ISSUE TITLE
Issue with Runerius

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2672]
Hey. I was checking my Sword save file and I noticed that my Runerigus was showing up as illegal again. My Runerigus was legitimately caught and evolved. Thanks.
[867 - Runerigus - E61A31A4EC89.zip](https://github.com/kwsch/PKHeX/files/4142105/867.-.Runerigus.-.E61A31A4EC89.zip)

**Comment by kwsch** [comment]
If you modified it or moved it in previous versions of the program, it would incorrectly wipe the `FormArgument` value. There isn't a known way to legitimately clear that value in-game after evolution.
