### ISSUE TITLE
sword/shield savedata language changed after export

### ISSUE THREAD

**Issue by kirafishy** [kwsch/PKHeX#2674]
**Describe the bug**
sword/shield Simplified Chinese savedata becomes Traditional Chinese after export

**To Reproduce**
my original savedata is Simplified Chinese
1. export savedata with no change
2. import savedata to switch and run the game
3. game language changed to Traditional Chinese

**Expected behavior**
game language doesn't change

**Screenshots**

**Additional context**
export savedata with "SAV-trainer info-KOR language", game language changed to Simplified Chinese

**Comment by kwsch** [comment]
Did you open and save the Trainer Info editor?

**Comment by iant632** [comment]
Similarly Korean changes to Simplified Chinese after saving the Trainer Info and Block Data

**Comment by kwsch** [comment]
Recent commits allowed for updating the game language, which apparently behaves a little differently. Maybe they're skipping Language 6 (unused), and shifting all the languages above (Spanish, Kor, CHS, CHT) down one.

![image](https://user-images.githubusercontent.com/6393368/73614125-2590dc80-45b1-11ea-8bbb-9b840159c7e9.png)

Try decreasing the value in your save file by 1 (don't modify trainer info afterwards).

**Comment by CanoeHope** [comment]
> Maybe they're skipping Language 6 (unused), and shifting all the languages above (Spanish, Kor, CHS, CHT) down one.

I can confirm that a legitimately started game in Spanish has a value of 6 for *UInt32 KGameLanguage.
PKHeX changes it to 7 (Korean) if you simply click save in the Trainer Info without making any edits there.
