### ISSUE TITLE
Request: Raids Tab!

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#2675]
Would you please add a Tab specifically for Raid data?

In addition to moving the Raids Patameter Editor into it's own tab (as opposed to a separate pop-up window), would you also create a display similar to Leanny's Plug-in that shows the active Pokémon, it's Gender, IV's, Nature, GMax status, and Shiny status to said tab.

One more major request for the new Raids tab: 

With the Block Data sectors for Wild Area News downloads (https://projectpokemon.org/tutorials/save-editing/gen-8_157/block-editing-r106/) were successfully located. As a result of this, Project Pokemon is now host downloads for the past Wild Area News downloads to revert to/replace with (https://projectpokemon.org/tutorials/save-editing/gen-8_157/block-editing-r106/).

Version 1.0.0
680EEB85 - 0996 Object is for drop_rewards
AD3920F5 - 1591 Object is for dai_encount
AD9DFA6A - 1597 Object is for normal_encount
EFCAE04E - 2246 Object is for bonus_rewards

Version 1.1.0
680EEB85 - 1037 Object is for drop_rewards
AD3920F5 - 1658 Object is for dai_encount
AD9DFA6A - 1664 Object is for normal_encount
EFCAE04E - 2350 Object is for bonus_rewards

I would like to ask that a button or option on the tab to be added titled: "News Den." Which would show (maybe one day edit), the Pokemon for EACH of the Raid Star levels (with their percentages to encounter) and ALL of their Rewards.

I know this information was only just mapped to the correct portion of memory but he's asking for the skies!

**Comment by kwsch** [comment]
The raid data isn't supposed to be mutable.

People can always inject blocks just fine without a separate editor, especially since the block names are now at the top of the list (latest commits).

It's probably better to just have as a separate project or plugin. Editing and parsing flatbuffer files is a pain.
