### ISSUE TITLE
I found the starting date and other things for SwSh

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2677]
These are on *Object TrainerCard

Date Registered is stored at 0x170-0x173 in YYYYMMDD values.
PokeDex completion mark is stored at 0x30: 1 means you have it and 0 means you don't.
PokeDex owned number is stored at 0x20-0x21.
Shiny Pokemon Found is stored at 0x22-0x23.
Game version displayed is stored at 0x24: 0 is Sword and 1 is Shield.
Curry types owned is stored at 0x26-0x27.
Language on League Card is stored at 0x1B. (a value of 6 isn't used for it.)
League Card printed date is stored at 0x1A8-0x1AB in Unix timestamp.

Below are some other things I came across playing with the blocks

Block Key 6EB72940 = CurryDex
Block Key E2F6E456 = First Hall of Fame Date (Unix timestamp)

**Comment by kwsch** [comment]
Current TrainerCard documention for record:
https://github.com/kwsch/PKHeX/blob/b31f0428cf0069d8e70115c26cf92e49ecdb6d44/PKHeX.Core/Saves/Substructures/Gen8/TrainerCard8.cs

Will work on getting these included :)
