### ISSUE TITLE
White Flute ORAS

### ISSUE THREAD

**Issue by Rayqo** [kwsch/PKHeX#2678]
Hi.

In ORAS the White Flute can decrease level of wild pokemon by 4. In this way we have access to some underleveled like level 12 Ludicolo but PKHeX says he's illegal. If I just change moves and the level by 14 (not met level), he's considered as legal.

![42](https://user-images.githubusercontent.com/43747386/73700250-5161ae80-46e6-11ea-8390-3814f3fb0bcd.png)

Here the .pk7 of the Ludicolo transfered into gen7:
[272 - Ludicolo - 2154AE8EDAF2.zip](https://github.com/kwsch/PKHeX/files/4150711/272.-.Ludicolo.-.2154AE8EDAF2.zip)

And the .pk6 of a level 1 Taillow rng'ed in the wild:
[276 ★ - Nirondelle - 0F8089C9AA57.zip](https://github.com/kwsch/PKHeX/files/4150684/276.-.Nirondelle.-.0F8089C9AA57.zip)

**Comment by kwsch** [comment]
https://m.bulbapedia.bulbagarden.net/wiki/White_Flute

**Comment by Rayqo** [comment]
According to 3DSRNGTool developed by wwwwwwzx, the White Flute can decrease the level by 4.

![42](https://user-images.githubusercontent.com/43747386/73731650-248ab700-4739-11ea-95b4-225e2a48bc87.png)

![flute_boost](https://user-images.githubusercontent.com/43747386/73731658-26ed1100-4739-11ea-9cbc-ee4d300dccc8.png)

https://github.com/wwwwwwzx/3DSRNGTool

And here the example of a level 12 Lombre rng abused on Route 114 in ORAS (we can find there level 16 Lombre). I don't modified or patched my game.

![271 - Lombre Niv 12 SA](https://user-images.githubusercontent.com/43747386/73730756-a24dc300-4737-11ea-817e-7ae59cf0c3e6.jpg)

![Route 114](https://user-images.githubusercontent.com/43747386/73732054-c90cf900-4739-11ea-8f6f-156ed4103dcf.png)

**Comment by SnorlaxMonster** [comment]
I checked in-game in Alpha Sapphire. The White Flute and Black Flute modify wild Pokémon's levels by 1-4 levels. I've also updated Bulbapedia accordingly.
