### ISSUE TITLE
Screenshot for PKHeX 

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#268]
i think it will be AWESOME that in PKHeX future Feature that i think will be a option that will screenshot PKHeX only because it will save time because printscreen then go to paint then go it will take time i think in the new Feature in PKHeX it will be AWESOME it will be save time

**Comment by suloku** [comment]
AltGr+printscreen does this, it's a windows feature.
Windows 7 aditionally comes with a screenshot tool (dunno english name, it's "recortes" in spanish)

**Comment by Orionsilver** [comment]
it will be better that PKHeX has that feature it will be AWESOME 
i have windows 10

**Comment by gocario** [comment]
Simply use "Alt + PrintScreen" (AltGr isn't mandatory).
You can aswell use the Windows "Snipping Tool" software to screencap a part of the screen.
