### ISSUE TITLE
Last 12 dens should not be active

### ISSUE THREAD

**Issue by pmsmall** [kwsch/PKHeX#2681]
**Describe the bug**
Last 12 dens should not be active. But "Activate All" button will activate them

**Expected behavior**
If them are active, there is no way to deactivate them in game.

**Comment by slp32** [comment]
Wouldn't it be the last 11? Last 12 would include `Lake of Outrage 4`.

**Comment by slp32** [comment]
@kwsch RaidCountLegal should be `100`, not `93`. The raid den plugin shows there being 100.
