### ISSUE TITLE
Change hatch suggestion for Gen 7 and add SWSH trade counter

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2685]
I was thinking that for SM and USUM, you could change the hatch suggestion to **Paniola Ranch** from Route 4 since the Day-Care is there and it's the most popular place to hatch eggs using the Tauros Ride.

For SWSH like SM and USUM does, would it be possible to add a trade stat updater that if you inject a Pokemon that isn't yours, it would update the **Trade** stat but this time by **2** because these games count 1 trade as 2 for some reason.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/bc45660f999611b0dae7c40bd9689216e1e2e896/PKHeX.Core/Legality/Tables/Locations.cs#L50-L51

50 -> 78
