### ISSUE TITLE
Stadium OT gender legality

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#2687]
**Describe the problem**
Stadium Farfetch'd and Gligar pass analysis with a female OT.

**Expected behavior**
Should not be passing with a female OT.

**Comment by kwsch** [comment]
Not able to replicate on latest commit...?
![image](https://user-images.githubusercontent.com/6393368/73992774-f6f26900-4904-11ea-9d78-c96a4edd5004.png)
![image](https://user-images.githubusercontent.com/6393368/73992801-15586480-4905-11ea-8682-fcddb99163aa.png)

**Comment by FeralFalcon** [comment]
That's weird, I just tried the latest commit and it still persists. 

Here's the files and a screenshot from my end for reference:
![Untitled-3](https://user-images.githubusercontent.com/33670476/74001161-88c79980-4938-11ea-8353-901a8da78a53.jpg)
[Stadium 2.zip](https://github.com/kwsch/PKHeX/files/4168973/Stadium.2.zip)

**Comment by FeralFalcon** [comment]
@kwsch 

Problem mysteriously returned in the latest commits and release.

[Illegal.zip](https://github.com/kwsch/PKHeX/files/6332340/Illegal.zip)
