### ISSUE TITLE
Dump Box Filenames

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#269]
I don't know if it's a real issue, but when I dump my boxes It doesn't saves more than one Pokémon of the same species, example: I have two Snorlax and the program saves just one, they are side by side on the box, by the way they aren't cloned.

Game - Gen 1 Yellow

**Comment by kwsch** [comment]
@SciresM the override string FileName is insufficient in differentiating similar files.

I suggest replacing:
`" - {OT_Name}"`
with
`" - {CalculateChecksum().ToString("X4")}"
and add in case 1 & 2 to CalculateChecksum (in PKM.cs) to return a checksum (maybe just a ushort = (ushort)Encrypt().Sum();)

**Comment by suloku** [comment]
It's a dump box function, so what about just appending box and slot? Of course a checksum is something more individualized if one was to mix the pk files.

**Comment by kwsch** [comment]
The intent of the checksum-naming is to ensure only unique data is stored. Dumping 300 cloned files will only result in 1 file in the dump location.
