### ISSUE TITLE
Shiny Zoroark (B2)

### ISSUE THREAD

**Issue by RulesBrooklyn** [kwsch/PKHeX#2702]
**Describe the problem**
When modifying a Zoroark [the lostlorn forest one] (got by legit cartbridge or by encounter database, doesn't matter) to shiny it'll result in "Static Encounter shiny mismatch", I used the RNG Reporter to get a true PID

**To Reproduce**
[Using a B2 save]
1. Select the legit Zoroark or the generated one 
2. Modify the PID to get it shiny (It has to be 100% Female according [Wiki](https://bulbapedia.bulbagarden.net/wiki/Lostlorn_Forest#Trivia))
3. Now check legality

**Expected behavior**
I think this should be possible because [the possibility](http://www.youtube.com/watch?v=WGILBbMUFvU&t=2m47s) of legit shiny zoroark at Lostlorn Forest

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/14964504/74332872-0820f700-4d97-11ea-9b51-547ca77b9e9b.PNG)

**Additional context**
[Zoroark.zip](https://github.com/kwsch/PKHeX/files/4191867/Zoroark.zip)
**NB:** In the zip there are the legit zoroark and the mismatched shiny one

**Comment by slp32** [comment]
In the description of the video linked, it shows a cheat code for removing the shiny lock.
The Lostlorn Forest Zoroark can not be shiny.

**Comment by RulesBrooklyn** [comment]
ah my bad I didn't see that, sorry
