### ISSUE TITLE
Hoopa-U always writes to box with form argument 0

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2706]
PKHeX gives a drop-down box when Hoopa's Unbound form is selected, listing 0, 1, 2, and 3 as options (which represent the number of days since using the Prison Bottle--though in Alola games, if it's in a PC box at that time it will not change back until it's *withdrawn* from the box, regardless of how long that takes). Regardless of what value you select, the process of saving it to a box does not respect that value, and always writes 0 instead--which then triggers a legality flag under the thought that it should have already changed back if the value really was 0. This means it's impossible to use the program to write a Hoopa-U that passes its own legality check.

**Comment by kwsch** [comment]
Depositing in-game clears the form duration and resets the form ID to zero, if I recall correctly. Same as Furfrou.

**Comment by SadisticMystic** [comment]
The correct form argument for a Hoopa-U that's been deposited in the PC box is 3, and attempting to set that value while it's in the left pane will allow it to certify as legal. The problem is that even after verifying that legality, dragging it into a box from there completely throws away the 3 and replaces it with 0, so it will so up with the illegal flag as soon as you send it there no matter what inputs you can possibly give (unless they involve setting it to Confined form or to a species other than Hoopa).

**Comment by kwsch** [comment]
You can't deposit it as a Hoopa-U, it'll immediately revert to Hoopa-C
![image](https://user-images.githubusercontent.com/6393368/74489455-30cded00-4e7a-11ea-9bed-b81953b98f37.png)

If it's ever set to a box, the form duration should be set to 0.

https://github.com/kwsch/PKHeX/blob/92b22b9f44b86725820e3914fe78d7fc51bfd551/PKHeX.Core/Saves/SAV7.cs#L207-L223

PKHeX doesn't automatically revert the form to zero, and instead flags it as invalid with that altform.

**Comment by SadisticMystic** [comment]
That's how it worked in 6; Bulbapedia's statement is incorrect with regard to 7 as the reversion is now delayed until the next withdrawal instead of happening immediately upon deposit. This change in transformation logic was necessary to allow Shaymin-Sky and Hoopa-Unbound (along with Furfrou forms) to exist on registered battle teams, such as in these examples:

https://3ds.pokemon-gl.com/rentalteam/usum/BT-8784-4D53
https://3ds.pokemon-gl.com/rentalteam/usum/BT-DCF8-4CAC
