### ISSUE TITLE
Route edgecase on LGPE

### ISSUE THREAD

**Issue by egzn** [kwsch/PKHeX#2707]
**Describe the problem**
There's a visual route-change in between Route 24 and Route 25, so there, Pokémon found on [Route 25](https://bulbapedia.bulbagarden.net/wiki/Kanto_Route_25#Generation_VII) (max level 14/15 on grass) can be captured on [Route 24](https://bulbapedia.bulbagarden.net/wiki/Kanto_Route_24#Generation_VII) (max level 12 on grass). 

**To Reproduce**
Check video proofs with the case reproduced. 

**Expected behavior**
Pokémon spawned on Route 25 should be legal when captured on Route 24.

**Screenshots**
Video proof 1: 
https://twitter.com/Saternoir/status/1228380939534749696

Video proof 2:
https://twitter.com/Saternoir/status/1228382592371580928

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/48525-lgpe-research-encounters-bleeding-into-a-different-location/

crossover location tables aren't documented for LGPE
