### ISSUE TITLE
kanto slowpoke in swsh

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#2708]
**Describe the bug**
kanto slowpoke is not usable in swsh right now but pkhex says it is legal (right now it is only bad egg)

**To Reproduce**
1. convert gen 7 slowpoke to gen 8 slowpoke
2. pkhex says legal

**Expected behavior**
flag until it is released

**Screenshots**
![image](https://user-images.githubusercontent.com/35694052/74566083-a69c8c00-4f40-11ea-8062-cf91e0098b1e.png)

**Comment by crzyc** [comment]
So, I'm not the *expert* on this, but regular Slowpoke is available through HOME - the game data still exists for it to transfer. Oddly enough, its evolutions are not in the game, so that might require some testing.

**Comment by poke-hexedit** [comment]
![image](https://user-images.githubusercontent.com/35694052/74566400-5ffb6180-4f41-11ea-8072-ad84a91fac2b.png)
only galar slowpoke is in game right now

**Comment by crzyc** [comment]
~~you should've put that screenshot as part of the initial issue page to prove your point, but i see now, good catch~~
