### ISSUE TITLE
Heavy Ball cannot apply to Excardrill

### ISSUE THREAD

**Issue by TaurusD** [kwsch/PKHeX#2709]
**Describe the problem**
Heavy Ball cannot apply to Excardrill under multiple versions (BW, ORAS, SM, USUM). 

**To Reproduce**
(How to upload?)

**Expected behavior**
Heavy Ball should be able to capture Excardrill. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21197539/74581042-a4d8d400-4fe5-11ea-8c26-b553522b5933.png)

**Additional context**

**Comment by Lusamine** [comment]
Heavy Ball Excadrill is illegal with origin BW (no apriballs), ORAS (no apriballs), SMUSUM (no Drillbur/Excadrill to catch).
