### ISSUE TITLE
Contest ribbons marked as illegal in gen 8

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#2710]
I transported my Pokemon into gen 8, and I noticed that it's now marked as illegal because it has contest ribbons with no affection, which doesn't exist in gen 8.

[468 - Togekiss - 26316966771C.zip](https://github.com/kwsch/PKHeX/files/4208512/468.-.Togekiss.-.26316966771C.zip)

![2020-02-15 15_18_09](https://user-images.githubusercontent.com/25017422/74588683-47ee1580-5007-11ea-82dd-1fb395e72fbc.png)

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/9e16df49702852426bb0cbcb9bf40773206bbf00
