### ISSUE TITLE
Toughness Master and Contest Star ribbons aren't being given

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#2711]
When you shift+click "Give all" in the ribbons menu, then it won't give the Pokemon the Toughness Master and the Contest Star ribbons automatically, even when they're completely legal.

**Comment by kwsch** [comment]
Related to #2710 , should be automatically resolved as PKHeX basically bruteforces legal ribbons. Once it realizes the ribbon is legal, it'll allow it to be automatically applied.

**Comment by CanoeHope** [comment]
On an unrelated note, I didn't even know about this shortcut! It should be added to the shortcuts list 'cause I don't see it there. Very useful!

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/9e16df49702852426bb0cbcb9bf40773206bbf00
