### ISSUE TITLE
League Card Doesn't Match Up to Game

### ISSUE THREAD

**Issue by ReclaimerShawn** [kwsch/PKHeX#2713]
I tried to migrate my Pokemon Shield save to Pokemon Sword and changed the Trainer Name, Trainer ID, and Secret ID so I could trade stuff back and forth between my Switch and my Switch Lite. My only problem: even though I changed the save from Shield to Sword, the League Card still says it's from Shield, even if I reprint the card.

I'll attach four pictures: my Pokemon Shield Save, my Pokemon Sword Save, the fact I'm playing Pokemon Sword, and the League Card in Pokemon Sword

![Shield Save](https://user-images.githubusercontent.com/30769105/74597819-86012e80-5033-11ea-88f3-5a3e2a4d13ae.png)
![Sword Save](https://user-images.githubusercontent.com/30769105/74597822-8e596980-5033-11ea-8918-d7da3b8fca89.png)
![Sword on Switch](https://user-images.githubusercontent.com/30769105/74597825-94e7e100-5033-11ea-8cb0-705e98e67009.jpg)
![Trainer Card in Game](https://user-images.githubusercontent.com/30769105/74597827-987b6800-5033-11ea-9aa8-fc19c143bc72.jpg)

**Comment by kwsch** [comment]
With the Block Info editor, you can try editing the trainercard and mystatus blocks directly; they expose all known attributes that can be edited. There's a 0/1 value (check the source code comments) that might be useful.

The version might be stored in an additional value storage, similar to game language.

It's not advisable to transfer saves between versions, especially with event flags and player unique values not being known.
