### ISSUE TITLE
Wurmple Evolution

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#2714]
On the ProjectPokemon forums, I found multiple threads in searches which indicated that the Legality check for the evolutionary line of Wurmple to determine if it's evolution to the legit branching evolution.

Since this is already part of the legality check, would you please add a Gray'd out "FORMS" box for Wurmple?

It would list either Beautifly or Dustox based upon the same PID legality check to determine how it should evolve.

Please and thanks!

**Comment by kwsch** [comment]
Control click the legality checkmark to get the verbose output; the verbose legality analysis will spit out what it evolves to.

![image](https://user-images.githubusercontent.com/6393368/74598355-00768200-5025-11ea-8f0f-b8471865613d.png)
