### ISSUE TITLE
Allow Pokémon to be modified to shiny as square in gen7

### ISSUE THREAD

**Issue by Sinets** [kwsch/PKHeX#2717]
After the Pokémon home is opened, I want to modify Pokémon in gen7 to be square shiny, and then transfer it to gen 8 through the Pokémon home. I learned that Pokémon's shiny type is determined by Pokémon's pid. Of course, square shiny Pokémon's pid is also legal in gen 7. I have tried by copying the random square shiny Pokémon's pid of gen8 to Pokemon of gen7, this is feasible. So can you add the ability to modify the shiny type in gen7 in the software so that I can modify it through batch editing instead of copying them one by one. thank you very much.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/a50169d3d2db9723939e3c64cd3b8f95ee81c918
https://github.com/kwsch/PKHeX/commit/f54bc7bf6fa665688c27e807544dabb3bf1f022a

**Comment by Sinets** [comment]
I know this, but when I use .PID = $ shiny0 in the game save of gen7, not all Pokémon in the save will become square shiny.Only a few of them became square shiny.why？

**Comment by Sinets** [comment]
I saw that you returned correct when pk.Format <= 7, and when pk.Format == 7, you did not judge whether xor is equal to 0. This may be the reason. Can this be modified?

**Comment by Sinets** [comment]
> [a50169d](https://github.com/kwsch/PKHeX/commit/a50169d3d2db9723939e3c64cd3b8f95ee81c918)
> [f54bc7b](https://github.com/kwsch/PKHeX/commit/f54bc7bf6fa665688c27e807544dabb3bf1f022a)



> [a50169d](https://github.com/kwsch/PKHeX/commit/a50169d3d2db9723939e3c64cd3b8f95ee81c918)
> [f54bc7b](https://github.com/kwsch/PKHeX/commit/f54bc7bf6fa665688c27e807544dabb3bf1f022a)

I saw that you returned true when pk.Format <= 7, and when pk.Format == 7, you did not judge whether xor is equal to 0. So when I use .PID = $ shiny0, I did not modify the shiny type. Can this be modified?

**Comment by kwsch** [comment]
Done ;)
