### ISSUE TITLE
Adding Pokedex Tab for Gen 3-5?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#272]
Is it possible to add a Pokedex tab just like for Gen 6 but for previous generations for Gen 1-5?

**Comment by ricksee** [comment]
Here is a link if it helps:
http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9dex_data_structure_in_Generation_III
http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_data_structure_in_Generation_IV
http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_data_structures_in_Generation_III

**Comment by Mrtops** [comment]
@kwsch I believe that this has been done and can be closed now.

**Comment by ReignOfComputer** [comment]
@Mrtops dude what? Please start checking before commenting in the future. No updates have been done on this.

**Comment by kwsch** [comment]
Added editors:
3 https://github.com/kwsch/PKHeX/commit/855025384200f78d92b48932870180a085166964
4 https://github.com/kwsch/PKHeX/commit/4874c174d8c3cc37df7db1f06474eccc88ab3361
5 https://github.com/kwsch/PKHeX/commit/5ecf01e481cd00f2b043aff5e74f0ad32c99df4e
