### ISSUE TITLE
Deoxys Base Forme minisprite is shown in every generation 3 game

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#2725]
Base stats are correctly calculated, but the minisprites are all base forme.

![image](https://user-images.githubusercontent.com/29823718/74873320-f8705800-532c-11ea-89bd-78a50a8c5499.png)

**Comment by kwsch** [comment]
Here's the specific code that /should/ be handling it:

https://github.com/kwsch/PKHeX/blob/4bfb57836a5674ca5936520d6db1811f9b27d89a/PKHeX.Drawing/Sprites/SpriteBuilder.cs#L37-L70
