### ISSUE TITLE
Add give all TRs to all Pokemon in Modify Boxes

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#2728]
An option to give all Pokemon in a box all the TRs each can learn through Box > Modify.

![2020-02-20 11_19_00](https://user-images.githubusercontent.com/25017422/74919148-d8936f80-53d2-11ea-80db-bbff6f6db6bf.png)

**Comment by kwsch** [comment]
Use the batch editor.

**Comment by sora10pls** [comment]
`.RelearnMoves=$suggestAll` @Araraura
