### ISSUE TITLE
Allowing Opening of Multiple Save Files/Drag Pokemon Across Save Files/Windows

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#273]
Is it possible for the program to open multiple save files at the same time? Also can it be possible that Pokemon can be transferred from one window from another without downloading the Pokemon's Data itself, like dragging/copying it from one file to another?

**Comment by kwsch** [comment]
No, an instance of PKHeX can only open one save file at a time.
You can always open PKHeX.exe multiple times to have multiple save files open.

Pokemon can be transferred one way between windows (data from source is not deleted). You can drag&drop between windows or you can dump boxes from _window A_ and load boxes in _window B_.
