### ISSUE TITLE
Ultra Shiny on Faraway Island Mew / WISHMKR Jirachi Crashes

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#2730]
If Shift+Click is used to try and make a Faraway Island Mew, WISHMKR Jirachi, or other similar events Ultra Shiny, PKHeX stops responding (appears to enter an infinite loop).

**To Reproduce**
1. Load in one of the Gen 3 Events
2. Shift+Click for Ultra Shiny

**Comment by kwsch** [comment]
Might be a result of this:
https://github.com/kwsch/PKHeX/commit/cc8e5d9c32a92318726ac3a77d5980ceca4f81cd

PID generator likely enforces the nature/ability index, which results in the PID never having a xor result of zero.

**Comment by kwsch** [comment]
Reverted offending commit: https://github.com/kwsch/PKHeX/commit/5240e67a14bfb04f8bb9fa5ecb73d6c492285d19
