### ISSUE TITLE
Legality Error: Can't Hatch Egg in Met Location

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2734]
The most recent legality checker is flagging some of my Pokemon illegal if they were hatched in the Battle Frontier, or any of its facilities, stating "Can't Hatch egg in location" Despite it being very easy to hatch an egg in any of those locations.

Steps to reproduce:
1.) Obtain an egg either through breeding or gifts
2.) Go to the Battle Frontier and hatch it in one of the facilities.
3.) Check met location (Should be Battle <Frontier,Tower,Hall,Factory,Castle,Arcade,Park>)
4.) Check in PKHeX and be annoyed that this perfectly legit Pokemon is being wrongly flagged as illegal

**Comment by sora10pls** [comment]
For the future, please specify which game the bug occurs in. Had to do some extra testing to verify which game this bug was present in (Platinum already has these marked as valid). :)

**Comment by PKMWM1** [comment]
I tested with Platinum and Heartgold. They were still considered invalid

**Comment by sora10pls** [comment]
Only considered invalid if Origin Game is HeartGold or SoulSilver. Prior to latest commit which resolves this issue, only Platinum had these Met Locations included:
https://github.com/kwsch/PKHeX/blob/0b5116f5677d244fc4de9ebb68cfd1cfc46d7dd1/PKHeX.Core/Legality/Tables/Tables4.cs#L228-L245
`080` + `112` thru `116` are Battle Frontier related. They were only missing from `ValidMet_HGSS`.
