### ISSUE TITLE
Jittery Mark and Smiley Mark don't set properly

### ISSUE THREAD

**Issue by jumpkain** [kwsch/PKHeX#2736]
**Describe the bug**
When adding the Smiley Mark to a Pokemon, it will also add the Jittery Mark. When attempting to add the Jittery Mark to a Pokemon, no mark is added. The changes will appear correct until closing the ribbons/marks window, but when re-opening the window, the issue will show itself.

Using the batch editor will yield the same results.

When looking at the Pokemon in-game, if you attempted to apply the Smiley Mark, you'll see the Jittery Mark. If you attempted to apply the Jittery Mark, you'll see no marks.

**To Reproduce**
1. Open the ribbons/marks window or batch editor
2. Apply either the Jittery Mark or Smiley Mark
3. Re-open the ribbons/marks window, or view the Pokemon in-game
4. Observe incorrect behavior

**Comment by kwsch** [comment]
Was fixed since last release: https://github.com/kwsch/PKHeX/commit/d560fbcf7ff11674aff02ed784d508c92a484ebb
