### ISSUE TITLE
Legal pokemon have problems and won't trade

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2737]
PKHeX says the following pokemon are legal, but when I try to trade them, they won't trade and the game says there is a problem with the pokemon

[3 pkm.zip](https://github.com/kwsch/PKHeX/files/4255179/3.pkm.zip)

Target Game is Sword

**Comment by BetaLeaf** [comment]
@rayzliao8787

**Comment by ReignOfComputer** [comment]
Not Legal on latest commit.

Must be in Poke Ball.

**Comment by BetaLeaf** [comment]
ah ok thanks! @ReignOfComputer
