### ISSUE TITLE
Legality: Egg Move/Tutor Move and Ribbons

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#2738]
Gen 3 (LeafGreen) Bred Dusclops should be able to learn Counter from FR/LG/E move tutors. Is marked as Illegal incorrectly, tested trading online in SwSh, trading is allowed.

(Klinklang ) Contest Ribbons from Gen 6 marked as legal in Gen 7 (after altering OT Affection to 255) however when transferring to SwSh they are marked as illegal. I've transferred the same Pokemon via Bank>Home and through just dragging and dropping pk7 into SwSh save file. 

Attempting to alter OT Affection ins SwSh doesn't work at all , just resets to 0, I'm assuming this is intended though.

Gen 3 (LeafGreen) Bred Arcanine should be able to know Morning Sun via the new Egg Move mechanic in the day care between Pokemon of the same species in SwSh. Morning Sun was a move Arcanine got as an egg move in HGSS exclusively and going forward so normally an Arcanine from a previous generation shouldn't be able to learn this. Probably many other Pokemon with Exclusive egg moves available after their original debut would be affected by this. One example I can think of is like Psychic Fangs Sharpedo. Arcanine is able to be traded online as well.

Including some Pokemon that have these issues some in pk7 and pk8 so you can test transfer them yourself or see if anything is incorrect.

[Moves and Ribbons.zip](https://github.com/kwsch/PKHeX/files/4265242/Moves.and.Ribbons.zip)

Also is there a reason why the MYSTRY Mew event cannot be from any other game aside from Ruby? It is flagged as illegal if you take the one from the database and change the game from Ruby to LeafGreen.

![MYSTRY MEW](https://user-images.githubusercontent.com/31756219/75510185-1c303f80-59b8-11ea-859e-e0bde9a28c99.png)

**Comment by ReZeroEmiria** [comment]
Should be in Legality parsing report
I'm sorry, I selected the wrong option.

**Comment by kwsch** [comment]
Bred Dusclops: Not legal, was transferred to Gen4 at level 5 (not Dusclops), therefore cannot learn Counter as it never existed as Dusclops in Gen3.

Klinklang: Works fine on latest commit -- https://github.com/kwsch/PKHeX/commit/549e6f616b9e290ddf3d419ecebc7a10c9777083

Affection in Gen8: Dummied stat, isn't saved anymore (functions now reference Friendship)

Arcanine: Works fine on latest commit -- https://github.com/kwsch/PKHeX/commit/549e6f616b9e290ddf3d419ecebc7a10c9777083

Mew: Gen3 events had fixed version IDs, as most were created on debug carts (ruby), and manually traded to the recipient.

====

Isn't legality fun? :)

**Comment by ReZeroEmiria** [comment]
It's interesting haha.. I hadn't thought about that on the Dusclops, thank you for the information! So when transferring from gen 3 - 4 the original location is changed to Poke transfer and level is overwritten to current?

**Comment by kwsch** [comment]
> when transferring from gen 3 - 4 the original location is changed to Poke transfer and level is overwritten to current?
Yep!

https://github.com/kwsch/PKHeX/blob/d58426ebf53ef06726d55cbc12b1b2d6181ed28b/PKHeX.Core/PKM/PK3.cs#L256-L257
