### ISSUE TITLE
Feature request: add Vivillon wing pattern legality checks

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#274]
While this may seem unnecessary, it still is something that could make certain Vivillon that are illegal deemed legal in PKHeX. Some wing patterns can only be obtained in certain places, and even if traded as a Scatterbug or Spewpa, the wing pattern of the future Vivillon stays the same in accordance to its residing country. When a Pokemon is traded, the 3DS location of the Pokemon is still that of where it was caught or hatched.

PokeBeach has a list (that seems to be complete) of all the wing patterns and where they can be obtained. The only two exceptions would be Fancy and Poke Ball (they already have legality checks), since they're event-only.

http://www.pokebeach.com/forums/threads/vivillon-secret-of-the-wings-colours-locations-possible-new-wings.116475/

**Comment by kwsch** [comment]
Some are too generic, such as 'New England sates of USA'

These would need to be translated to CountryID (and RegionID tuples if deviation per subregion).

May be best to just reverse engineer how the game determines the Vivillon form when generating it ingame, as that would be the most complete list possible.

**Comment by Snaid1** [comment]
if it helps I came across this list and map which looks like the most complete I've found online so far, although I agree if someone reversed engineered the code that would e the most complete possible.

https://docs.google.com/spreadsheets/d/1nE47IB6uY81f8ESsg05iCuA34QmoCJNqYb3qNyUOm_A/edit?type=view&gid=0&f=true&sortcolid=-1&sortasc=true&rowsperpage=250#gid=0
http://i.imgur.com/tROqHEg.png

**Comment by ricksee** [comment]
Locations

River:
Australia (New South Wales and South Australia confirmed, although it seems all states are the same)
Meadow:
Austria
Japan
France
Germany
Italy
Luxembourg
UK
US (Oregon)
Elegant:
Japan (Hokkaido)
USA
Modern:
USA (Alabama, Arkansas, Delaware, Florida, Georgia, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisianna, Maryland, Minnesota, Missouri, Nebraska, Nevada, North Carolina, North Dakota, Ohio, Oklahoma, South Carolina, Tennessee, Texas, Virginia, West Virginia)
Canada (Manitoba)
Bulgaria
Polar:
Canada (Alberta, New Brunswick, Ontario, Saskatchewan, Quebec, Nova Scotia)
Sweden
Norway
USA (Alaska, Conneticut, Maine, Massachusetts, Michigan, New Hampshire, New Jersey, New York, Rhode Island, Pennsylvania, Wisconsin, Wyoming)
Garden:
UK
USA (Virginia)
Czech Republic
Netherlands
Ireland
Australia (Tasmania)
New Zealand
Poland
Marine:
Austria
Chile
France
Germany
Greece
Italy
Poland
Spain
Potugal
Greece
Continental:
Belgium
France
Germany
Korea
Poland
Russia
Netherlands
Norway
Sweden
USA (Colorado)
Tundra:
Norway
Iceland
Sun:
Mexico
Icy Snow:
Finland
Canada (Yukon, Northwest Territories, Nunavut)
Norway
High Plains:
USA (Arizona, California, Oregon, Utah, Idaho, New Mexico, Washington Colorado)
Canada (British Columbia)
Jungle:
Malaysia
Colombia
Singapore
Ocean:
USA (Hawaii)
Reunion (Island off the coast of Madagascar)
Savannah
Brazil
Peru
Sandstorm
United Arab Emirates
Somalia
Monsoon
Hong Kong
India
Japan
Archipelago
Puerto Rico
Saint Lucia
South Africa (Western Cape)
Arizona (US)
Notes

**Comment by ReiKeima** [comment]
Just going to throw in that this should not be in the pk7 legality checker, as Sun and Moon re-assign the player's location each time the game is loaded as opposed to only when the save file is first started.

However, the Vivillon pattern appears to still be determined via the same method in Gen 6 and is locked in for the life of the save file.

**Comment by Skywalker25** [comment]
Here is a list I found when I was looking for vivillons' patterns location. 
https://goo.gl/79tqYV
I'm unsure if nintendo checks for matching location/pattern. but I have used it to generate legal shiny/normal vivillon with different patterns and have been able to go online. The exception are the pokeball/fancy patterns as they are event only.

**Comment by sora10pls** [comment]
This is awesome, glad to see it get implemented. Thanks a ton @wwwwwwzx and @kwsch!

**Comment by kwsch** [comment]
Probably better to just flag as Fishy instead of Illegal :)
