### ISSUE TITLE
load last loaded box in sword shield

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#2742]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
load last used box when open sword shield save file like in other games

**Describe alternatives you've considered**
none

**Additional context**
other games load your last loaded box from the game when you load your save but sword shield always go to box 1

**Comment by sora10pls** [comment]
I've already documented the appropriate byte that needs to be read/written to and sent it to @kwsch, just needs to be implemented.

`KCurrentBox = 0x17C3CBB;` Accepts a value from 0 to 31.
