### ISSUE TITLE
Mass Set (Set All) / Auto re-roll PID/EC

### ISSUE THREAD

**Issue by toim22** [kwsch/PKHeX#2743]
**Is your feature request related to a problem? Please describe.**
Mass set to the box, completing the all empty spaces (or even overwriting the existing ones if it is easier) with the same Pokemon, changing PID/EC to all of them at once (to avoid clone flags)

**Describe the solution you'd like**
I would like to have something like ctrl + shift + right click (or any other shortcut) to fulfill the current box within the Pokemon we have in the View. Also, it would be good to automatically randomize the PID/EC for each one of them (keeping all the other info like shiny/square shiny, OT, moves, IV and etc as usual) to avoid clones.

The automatically re-roll PID/EC (keeping the legal/shiny characteristics) would also be something in the Options > Settings. Something like a checkbox for "Auto re-roll PID/EC" and the user would check/uncheck at their own

**Describe alternatives you've considered**
I have tried to investigate and do something similar on my own, but as a Java developer for 15 years, I thought it would be easier for me than was actually.

**Additional context**
![Untitled-1](https://user-images.githubusercontent.com/10696666/75710660-f1353c80-5c92-11ea-9142-c8b3d08f76a8.png)
![Untitled-2](https://user-images.githubusercontent.com/10696666/75710681-f8f4e100-5c92-11ea-95ad-2a4f92500cdd.png)

**Comment by sora10pls** [comment]
Ctrl-Alt click a Box slot to set your current PKM in the editing tabs to all 30 slots.

Batch Editor:
```
=Box=12
.PID=$shiny
.EncryptionConstant=$rand
```

Boom, now Box 12 has 30 Shiny Charmander all with unique PIDs/ECs.

**Comment by toim22** [comment]
> Ctrl-Alt click a Box slot to set your current PKM in the editing tabs to all 30 slots.
> 
> Batch Editor:
> 
> ```
> =Box=12
> .PID=$shiny
> .EncryptionConstant=$rand
> ```
> 
> Boom, now Box 12 has 30 Shiny Charmander all with unique PIDs/ECs.

Excellent, I didn't know that. But two things:

1- the PID hasn't changed (EC changed)
2- what if I want to do the same but for square shiny, which would be the command?

Thanks!!!

**Comment by sora10pls** [comment]
1. I just tested and all of the Shiny PIDs are unique. Make sure you're viewing different slots, they should all be different.

2. For SWSH, `.PID=$shiny0` would be the command to give them Square sparkles.

**Comment by toim22** [comment]
> 1. I just tested and all of the Shiny PIDs are unique. Make sure you're viewing different slots, they should all be different.

No lucky here. Am I doing something wrong?

<img width="293" alt="Annotation 2020-03-02 150941" src="https://user-images.githubusercontent.com/10696666/75713590-17a9a680-5c98-11ea-9dec-edb0c585f478.png">
<img width="293" alt="Annotation 2020-03-02 151041" src="https://user-images.githubusercontent.com/10696666/75713593-1a0c0080-5c98-11ea-9fae-9c9aa912d3a2.png">
<img width="509" alt="Annotation 2020-03-02 1510411" src="https://user-images.githubusercontent.com/10696666/75713596-1bd5c400-5c98-11ea-8b20-5f3cacd31e63.png">
<img width="554" alt="Annotation 2020-03-02 1510412" src="https://user-images.githubusercontent.com/10696666/75713603-1ed0b480-5c98-11ea-821b-b1e4a679dae3.png">

**Comment by toim22** [comment]
> > 1. I just tested and all of the Shiny PIDs are unique. Make sure you're viewing different slots, they should all be different.
> 
> No lucky here. Am I doing something wrong?
> 
> <img alt="Annotation 2020-03-02 150941" width="293" src="https://user-images.githubusercontent.com/10696666/75713590-17a9a680-5c98-11ea-9dec-edb0c585f478.png">
> 
> <img alt="Annotation 2020-03-02 151041" width="293" src="https://user-images.githubusercontent.com/10696666/75713593-1a0c0080-5c98-11ea-9fae-9c9aa912d3a2.png">
> 
> <img alt="Annotation 2020-03-02 1510411" width="509" src="https://user-images.githubusercontent.com/10696666/75713596-1bd5c400-5c98-11ea-8b20-5f3cacd31e63.png">
> 
> <img alt="Annotation 2020-03-02 1510412" width="554" src="https://user-images.githubusercontent.com/10696666/75713603-1ed0b480-5c98-11ea-821b-b1e4a679dae3.png">

IDK why, but when I used $rand to PID and then used $shiny worked.

Also, to avoid disturb you guys, is there any place with a list of commands I can use in batch?

Thanks

**Comment by sora10pls** [comment]
Right in the Batch Editor itself.
![image](https://user-images.githubusercontent.com/17801814/75714427-aec32e00-5c99-11ea-8948-d056e6334483.png)

There's also a brief tutorial on the forums: https://projectpokemon.org/home/forums/topic/38168-frequently-asked-questions/?tab=comments#comment-201640

**Comment by toim22** [comment]
> Right in the Batch Editor itself.
> ![image](https://user-images.githubusercontent.com/17801814/75714427-aec32e00-5c99-11ea-8948-d056e6334483.png)
> 
> There's also a brief tutorial on the forums: https://projectpokemon.org/home/forums/topic/38168-frequently-asked-questions/?tab=comments#comment-201640

I know there is the combo box, but I was thinking more as the values we can use like I would never imagine using $rand to randomize EC/PID.

Thanks anyway, I will check the forums, you already helped me a lot with that info!
