### ISSUE TITLE
Alolan Raichu with VC origin (Gen 8)

### ISSUE THREAD

**Issue by jjaldridge2009** [kwsch/PKHeX#2746]
**Describe the problem**
Alolan Raichu with VC Origin shown as illegal when transferred up to Gen 8 save file. (Unsure if shown as illegal in USUM Save File)

**To Reproduce**
Transfer Pikachu\Pichu from VC RBY\GSC and transfer to USUM. Evolve to Alolan Raichu.

**Expected behavior**
This Raichu is legitimate and obtainable.

**Screenshots**
![image](https://user-images.githubusercontent.com/16225603/75944392-9273ec80-5e65-11ea-8b30-1b87e9993b53.png)

**Comment by kwsch** [comment]
Works fine on latest commit.
https://github.com/kwsch/PKHeX/commit/0e2734d2d5406761c5ca950c7dba0fb4083d96c9
