### ISSUE TITLE
Multiple Legality moves

### ISSUE THREAD

**Issue by toim22** [kwsch/PKHeX#2749]
**Describe the problem**
I don't know why but I am seeing multiple moves incorrect illegal flags with multiple pokemon. I am attaching some examples, but they are not the only ones.

**To Reproduce**
pk8 attached

**Expected behavior**
Moves to be legal

**Screenshots**
N/A

**Additional context**
It should be good to have the database from serebii or pokemonshowdown synced with those legality moves
[Legality Bug.zip](https://github.com/kwsch/PKHeX/files/4293901/Legality.Bug.zip)

**Comment by ReignOfComputer** [comment]
Not a bug.

Add the Technical Records.

**Comment by toim22** [comment]
> Not a bug.
> 
> Add the Technical Records.

I'm sorry, I did not get what you mean

**Comment by ReignOfComputer** [comment]
Moves > Technical Records

or

Shift+Click on Technical Records button

**Comment by toim22** [comment]
> Moves > Technical Records
> 
> or
> 
> Shift+Click on Technical Records button

got it thanks
