### ISSUE TITLE
Event region legality

### ISSUE THREAD

**Issue by Kirzi** [kwsch/PKHeX#275]
A Japanese Smash Greninja event was marked legal despite having region data set to the US (Florida). It was a Japanese serial code event that was only redeemable on a JPN 3DS, so it should be marked illegal.

This is the case for every JPN exclusive (or any region exclusive) serial code event as well as events distributed via Nintendo Zone.

**Comment by kwsch** [comment]
That information is not stored in wc6 or wc6full, it'd be something entirely manual.
Would need a list of card IDs that are only redeemable by a Japanese-Region, and it'd have to be updated every time an exclusive card came out :(

**Comment by suloku** [comment]
The current wc compilation by the_slayer is actually region sorted. Even if a given wc was redeemable in all regions, you will find that same wc inside each region folder. That leads to redundant files in the compilation, but acomplished the purpose of sorying the wcs per region.
The wcs have id in the filename, so making a list for each region shouldn't take more than 5 minutes with the propper tools if you would only need a text file for each region containing IDs.

**Comment by ricksee** [comment]
http://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_region_serial_code_event_Pok%C3%A9mon_distributions_in_Generation_VI

**Comment by kamronbatman** [comment]
I am working with @PP-theSLAYER and @Kirzi to create meta data that PKHex will be able to use to address this issue.

**Comment by TJGameplay** [comment]
> I am working with @PP-theSLAYER and @Kirzi to create meta data that PKHex will be able to use to address this issue.

This is great. Thank you so much.

When you are finished, will it be released in a version of PKHex, or will I have to obtain it some other way?
Thanks.

**Comment by Kirzi** [comment]
I'm not sure if this is what you had in mind, but I was putting this together for Porybox anyway:

https://docs.google.com/spreadsheets/d/1eyKUA9NY8LWoekqrD6Q1tzJbCUJtZ13PLKPZ5x725mc/edit?usp=sharing

It should be accurate, but it's possible I misremembered something.

**Comment by kwsch** [comment]
Closing due to lack of community interest.

For future note, a preferred implementation would be hashing details of the gift and retrieving a `[Flags]` enum indicating console regions the gift can be received by; should be precomputed and should be a separate binary (key [Flag]value pairs). There's < 8 console regions so {int,byte}*n binary will work.
