### ISSUE TITLE
"Invalid Skillful Battler" Ribbon in ORAS

### ISSUE THREAD

**Issue by Bowei-xiao** [kwsch/PKHeX#2754]
**Describe the bug**
To briefly described, it flagged illegal as it thinks it contains "skillful battler" ribbon while it's not supposed to. Hoever, looking at the pic below it doesn't really have one:

**To Reproduce**
1. Have a Kyogre caught in game
2. Transfer to pokemon bank along with other stuffs
3. not sure what happened but take it back down to oras

**Expected behavior**
This Kyogre was legally obtained from a AS copy without modification. It was originally showing legal, but I had put it into the pokemon bank and took it back and it suddenly showed illegal. Not sure if it was the pokemon bank that did something to it.

**Screenshots**
![Untitled1](https://user-images.githubusercontent.com/12563597/76137785-c76f7300-600e-11ea-878f-28912cd26e6f.png)

**Additional context**
P.S. I checked the memory about affection stats as indicated in other post. Don't think it's relevant as the memory is not that specific phrase mentioned

**Comment by kwsch** [comment]
Without seeing the Pokémon, the only place that Skillful is flagged without the ribbon is here:
https://github.com/kwsch/PKHeX/blob/b7998191314647a3ebf3d70b7832303a8b9257df/PKHeX.Core/Legality/Verifiers/Ribbons/RibbonVerifier.cs#L263-L266

If it has the "defeated the chatelaine", it should have the ribbon.
