### ISSUE TITLE
Switching my Cleffa's species to Clefairy invalidates 3 of its 4 known moves

### ISSUE THREAD

**Issue by LOuroboros** [kwsch/PKHeX#2756]
**Describe the bug**
I view the data of the Cleffa I caught in my savefile of Pokémon Ultra Sun _(no cheats that could modify a Pokémon's stats were used)_, then I switch its species to Clefairy *(because I need to check a certain move's behavior and I want to get it ready before booting up the game)*, and after having done that, PkHex tells me that Moves 2, 3 and 4 *(Sweet Kiss, Copycat and Magical Leaf respectively)* are... invalid?

**To Reproduce**
1. Import Cleffa to a savefile of Pokémon Ultra Sun v1.2 _(that's the version of the game that I have at least, would probably work fine on Ultra Moon too)_
2. Right Click on its icon > View
3. Go to the Main tab and change its species to Clefairy
4. Watch as the legality checkmark becomes an emergency warning triangle

[173 - Cleffa - 8F0911F0D52C.zip](https://github.com/kwsch/PKHeX/files/4318612/173.-.Cleffa.-.8F0911F0D52C.zip)

**Expected behavior**
I expected the program to tell me that Clefairy was legal, because it technically is.
For reference, [Bulbapedia has a list of the moves each Pokémon can learn and Cleffa can definitely learn those 3 moves](https://bulbapedia.bulbagarden.net/wiki/Cleffa_(Pok%C3%A9mon)/Generation_VII_learnset#By_leveling_up), so naturally, a Cleffa that knows them and evolves into a Clefairy would know them too.

**Screenshots**
How about a quick video instead?
https://streamable.com/umgxq

**Additional context**

**Comment by Lusamine** [comment]
Your Cleffa is a wild encounter and needs to gain at least one level to become a Clefairy. Of course only changing species makes it illegal. Works fine if you bump level up by one to 29.

**Comment by LOuroboros** [comment]
> Your Cleffa is a wild encounter and needs to gain at least one level to become a Clefairy. Of course only changing species makes it illegal. Works fine if you bump level up by one to 29.

Then shouldn't the legality checker reflect the actual issue instead of saying that X move isn't valid even though it is?

**Comment by ijuintekka** [comment]
> 
> 
> > Your Cleffa is a wild encounter and needs to gain at least one level to become a Clefairy. Of course only changing species makes it illegal. Works fine if you bump level up by one to 29.
> 
> In that case, shouldn't the legality checker reflect the actual issue instead of saying that X move isn't valid even though it is?

It's correct. Because the met level is equal to the current level it assumes that the Clefairy was never a Cleffa, and can't have those moves as a result.

**Comment by LOuroboros** [comment]
> 
> 
> > > Your Cleffa is a wild encounter and needs to gain at least one level to become a Clefairy. Of course only changing species makes it illegal. Works fine if you bump level up by one to 29.
> > 
> > 
> > In that case, shouldn't the legality checker reflect the actual issue instead of saying that X move isn't valid even though it is?
> 
> It's correct. Because the met level is equal to the current level it assumes that the Clefairy was never a Cleffa, and can't have those moves as a result.
Ah, that does make sense. And would it be impossible to make the program check that sort of situations? I suppose so, but I guess it's worth asking.

Whatever the case, sorry for bringing up this no-issue(?). My bad.

**Comment by ijuintekka** [comment]
Not impossible but as for whether or not it's worth implementing that's not for me to decide.

**Comment by kwsch** [comment]
The purpose of the legality checker is to verify the current legality state, not to advise the user on how to make things legal.

Performing unnecessary checks to see what needs to be deviated in order to achieve a legal result would slow things down, and would require extra logic.

[PKHeX-Plugins](https://github.com/architdate/pkhex-plugins) uses a different approach to mutate a Pokémon into a legal state by instead re-generating the Pokémon's required details, sourcing valid encounter templates from PKHeX's legality database. I suggest you use that plugin to assist in figuring out why your manual modifications are not valid.
