### ISSUE TITLE
Mark problem and Safari/Sport ball problem

### ISSUE THREAD

**Issue by YoshivsJoshi** [kwsch/PKHeX#2758]
The first problem is when you choose the Smiley mark it will instead give it the anxious mark and remove the smiley mark but keep the smiley mark on the PkHex mark settings, also Sport balls and Safari balls are still not legal on Pokémon that can legally get Safari balls like Rhyperior and Roserade, thank you

**Comment by Lusamine** [comment]
You aren't on the latest commit.  These problems were fixed already.
https://github.com/kwsch/PKHeX/commit/d560fbcf7ff11674aff02ed784d508c92a484ebb and https://github.com/kwsch/PKHeX/commit/9dbc3cd41806a8011cf20ed77bfb3e9dbb971389
