### ISSUE TITLE
How do the Stat TextFields work?

### ISSUE THREAD

**Issue by LCCoolJ95** [kwsch/PKHeX#2761]
Hello. I'm working on a Pokédex Pro application, and I was referencing PkHex for the stat calculations. I was wondering, how does it do the calculations in real time? And how does it prevent it from inputting anything other than integers? If it helps, I'm writing in Java.

**Comment by kwsch** [comment]
All of the parameters that are used for calculating stats (level, nature, IV, EV, species, form) fire events when their associated control's value is changed, which then calls a method to recalculate & display the new stats.
