### ISSUE TITLE
Pokemon XY ability to change skin color

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#277]
Hello. I wanted to know if you would be able to implement the ability to change a trainer's skin color in PKHeX. I was trying to help my friend with his Pokemon X by giving him my save file since his save file was corrupted and while I was able to change most of the important things like the name and play time, I was not able to change the skin color to more adequately fit him. I think this feature would be very useful. thank you very much

**Comment by kwsch** [comment]
It's already possible to change it using [these guides](http://imgur.com/a/yYWhg), however it's not researched enough to fully implement a user-friendly view. Just hex editing for now :)
