### ISSUE TITLE
Fateful encounter flag disappears

### ISSUE THREAD

**Issue by ByReverso** [kwsch/PKHeX#278]
When I import a 3gen Pokémon with the Fateful encounter flag to my Alpha Sapphire save file, it disappears and I have to check it manually. It becomes a problem when I have to import more than 150 from my Pokémon XD save file.

**Comment by kwsch** [comment]
Follow up needed:

What is the met location of the C/XD pokemon when in pk3 format?

**Comment by ByReverso** [comment]
The met location depends on the Pokémon. A Pokémon XD Kangaskhan has a 85 as location number whose name is "Citadark Isle". In Pokémon Colosseum is the same index number, but it means "Mt.Battle" and in Emerald means "Sky Pillar".

These links may help you:
http://bulbapedia.bulbagarden.net/wiki/List_of_locations_by_index_number_(GCN)
http://bulbapedia.bulbagarden.net/wiki/List_of_locations_by_index_number_(Generation_III)

I also attach my Kangaskhan from my XD save file.

**Comment by kwsch** [comment]
Thanks, the save file will be useful for the future implementation of C/XD save files.

Priority is on Pokémon Box first though :)

**Comment by ByReverso** [comment]
The Kangaskhan .pkm file I attached has been converted from XD to GBA. The original one from Pokémon XD is this: https://mega.nz/#!hJgxUJ6C!HMkQ7Uyl-VbVXqFfQET6WP5vuaBhLF-Y4fBG9hYrCXQ
