### ISSUE TITLE
Import Nature from Showdown/Smogon

### ISSUE THREAD

**Issue by toim22** [kwsch/PKHeX#2794]
**Describe the bug**
When I import the Pokemon from Showdown/Smogon with nature, it populates only the Stat Nature field, but the Nature field still the same previously used

**To Reproduce**
Go to Showndown, create a Pokemon with any nature. Import in PKHeX and the value chosen will populate only Stat Nature

**Expected behavior**
Both, Nature and Stat Nature field receives the value

**Additional context**
I have tried to use batch editor command .Nature=.StatNature but nothing was changed.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2504#issuecomment-557823944
https://github.com/kwsch/PKHeX/commit/66ebf7cb60bd6cae3c81dd7a8b4dcf87a55479fc

**Comment by toim22** [comment]
@kwsch I read the thread you have added and the guy was needing something like me.

Then I developed an option to configure this on the settings:

![image](https://user-images.githubusercontent.com/10696666/77110366-dd603900-69fb-11ea-81ff-48255ab8ae2c.png)

I don't know how the people are getting permission to add enhancements to this project, and I don't even know if I can change something and bring this to the official project, but I think this should be useful for those who prefer to default both values, Nature and StatNature. Of course, **I left this option unchecked as default** and if the user want it, just go there and check.

Please let me know if I can bring this to the project and how can I do that if possible.

**Comment by kwsch** [comment]
@toim22 I reimplemented it with your example, should behave exactly as you described!

**Comment by toim22** [comment]
> @toim22 I reimplemented it with your example, should behave exactly as you described!

Ok. I have developed here as well and I was trying to start helping on some small enhancements like this to get used to the project.

But that is ok, thanks!!

**Comment by kwsch** [comment]
The localization specific stuff (like strings) is pretty convoluted (there's a hidden dev menu with ctrl-alt-D) that can re-dump the localization files with updated values.

If you submit any pull requests for enhancements, I'll review & merge :D ; any questions you can poke me on pporg's discord
