### ISSUE TITLE
Raichu Family Volt Tackle Legality

### ISSUE THREAD

**Issue by Abyzab** [kwsch/PKHeX#2797]
**Describe the bug**
Pichu/Pikachu/Raichu with Volt Tackle (bred in Gen 8) is Flagged as Illegal

**To Reproduce**
1. Make a Pichu bred in Gen 8
2. Change a move to Volt Tackle
3. Flagged as Illegal : "Invalid Move"

**Expected behavior**
It should be legal

**Screenshots**
Illegal Raichu with Volt Tackle:
https://gyazo.com/a3ae93e1d800d0798e64be5ab2371347

Legally Obtained & then editted Raichu with Volt Tackle:
https://gyazo.com/f601467d6bacf1f65fb7aa0fdd88fc96
https://gyazo.com/32deecbf78cded84504c9a952408174e

**Additional context**
The way to get this move legally is by Breeding a Pikachu / Raichu (from Gen 7) that has the move Volt Tackle while the pokemon is holding a Light Ball (which is obtained by wild pikachus held item 5%) The bred pokemon from this will then have the move

**Comment by kwsch** [comment]
Do not report legality "issues" if you are failing to recreate something legally. The program is working as intended, flagging your modified PK8 as invalid.

**Comment by Abyzab** [comment]
I'm not sure if this goes through to you;

I'm not reporting it flagging some illegal Pokemon I'm making as illegal -
it's flagging something that's legal to get as illegal. (it's possible to
get this Pokemon). The way I made it legal is by getting it in game first
(to show it is legal too). I apologize if I did that incorrectly I was only
informing you since you might be unaware that it is legal to get

**Comment by Lusamine** [comment]
The program handles the Pokemon fine.  The problem is you created a legal Pokemon incorrectly.  Try actually getting the Pokemon legitimately in-game to see what happens instead of reporting your bad hacks.
![image](https://user-images.githubusercontent.com/30205550/77414796-8ce83300-6d8f-11ea-9b14-ff97943362c8.png)
