### ISSUE TITLE
.ekx not actually in save filter

### ISSUE THREAD

**Issue by Alphadelta14** [kwsch/PKHeX#28]
https://github.com/kwsch/PKHeX/blob/4b3cc3c186eb2a3cdeba1170288f77d4f8d7db54/PKX/f1-Main.Designer.cs#L2567

@kwsch I noticed this in a screenshot on the forums, but you don't actually have .ekx in there as a save option. You don't actually need to do All Files to use that format; just clean up the extensions a bit (one missing period and one missing asterisk).

**Comment by kwsch** [comment]
Fixed! https://github.com/kwsch/PKHeX/commit/f49758f57e248655c8316c5f8862c90286505810#diff-ca1f1c240eb87fcacc3445db600e51cbL2567

<3
