### ISSUE TITLE
LeafGreen In-Game Trade Lickitung appears illegal

### ISSUE THREAD

**Issue by merittl** [kwsch/PKHeX#2802]
**Describe the problem**
In Pokemon LeafGreen, the latest version (200314) does not see the Lickitung obtained from an in-game trade as legal.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

[LeafGreen SAV.zip](https://github.com/kwsch/PKHeX/files/4406358/LeafGreen.SAV.zip)

**Expected behavior**
Considering the Lickitung had been obtained legally through an in-game trade and had not been altered, so it should not appear illegal. Even in the previous version (200214) it appears as a legal Pokemon.

**Screenshots**
![pkhex leafgreen screenshot](https://user-images.githubusercontent.com/39877075/77979992-c529cd00-72cb-11ea-97fc-cf81ede47fce.jpg)

**Additional context**

**Comment by kwsch** [comment]
Works fine on latest commit; already reported: https://github.com/kwsch/PKHeX/issues/2787
