### ISSUE TITLE
Mystery gifts not loading

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#2803]
**Describe the bug**
I downloaded the whole Github repository of Events Gallery in the mgdb folder. I opened the mystery gift database in PKHeX and remove all sort filters. Only shows a few pokemon (2281 max). I noticed 2 things:

- WC*full are not loaded. 
- Not all pokemon inside wc are listed in "species" list box. 

**To Reproduce**
1. Download Events Gallery on mgdb folder.
2. Open Mystery Gift database.
3. Search for any Pokémon, for example Zygarde. 

**Expected behavior**
All wc files are loaded in PkHeX to be find and searched.

**Screenshots**
![pkhex](https://user-images.githubusercontent.com/4681902/78011666-2a210980-7344-11ea-8b90-8512f14ffe51.jpg)

**Comment by Ammako** [comment]
Well, of course it doesn't. These Pokémon don't exist in SWSH. They won't be shown unless you load a save file Gen. 7 or lower.

**Comment by ajtudela** [comment]
Damn! Sorry, I just forgot the Dexit. It works if I load a sun savegame.
