### ISSUE TITLE
Unable to give gen 4 pokemon custom abilities 

### ISSUE THREAD

**Issue by dkolenik** [kwsch/PKHeX#2805]
I am able to change the ability within PkHax but once getting them into the game they have their normal ability. Is it impossible to give custom abilities like in gen 3? Thanks in advance.

**Comment by sora10pls** [comment]
Unable to replicate
![wg](https://user-images.githubusercontent.com/17801814/78459895-69c05c00-768a-11ea-8597-461c7738b1c3.png)

**Comment by dkolenik** [comment]
> Unable to replicate
> ![wg](https://user-images.githubusercontent.com/17801814/78459895-69c05c00-768a-11ea-8597-461c7738b1c3.png)

I am doing this on an emulator, would that change anything?

**Comment by kwsch** [comment]
> I am doing this on an emulator, would that change anything?

No.
