### ISSUE TITLE
Alolan Raichu legality

### ISSUE THREAD

**Issue by MichiS97** [kwsch/PKHeX#2807]
Hi,

I've noticed a small issue regarding legality detection in the latest commit (270d9841301b3249f30c03f8c420b2d4e766f106).

My Alolan Raichu in my Pokemon Sun save is detected as not legal. The following report is given:
```
Invalid Move 1: Invalid Move.
Invalid Move 4: Invalid Move.
Invalid: Unable to match an encounter from origin game.
===

Valid Move 2: Learned by TM/HM.
Valid Move 3: Learned by Level-up.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Fishy: All EVs are zero, but leveled above Met Level.
Fishy: Current experience matches level threshold.
Valid: Nickname matches species name.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Form argument is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Invalid (Raichu)
PID Type: None
```
I've caught a Pichu completely legitimately in-game and then edited its friendship stat and level with PKHeX and then evolved the Pichu to Pikachu and Raichu in-game again. I'm pretty sure this should be legal.

I have attached my save file and the pk7 file in question.
[raichu_legality.zip](https://github.com/kwsch/PKHeX/files/4439070/raichu_legality.zip)

**Comment by ReignOfComputer** [comment]
I can replicate this issue with Raichu-Alola from RoC's PC.

It appears to be caused by unset HT Trainer. Adding HT Trainer data to the Pokemon makes PKHeX recognize it as Legal.
