### ISSUE TITLE
.RelearnMoves=$SuggestAll leaving boxes unchecked in menu

### ISSUE THREAD

**Issue by KingMarzy** [kwsch/PKHeX#2809]
whenever i use it it says "modified" but when i go in the TR menu everything is unchecked
or is it just not shown in the menu?

**Comment by sora10pls** [comment]
`.RelearnMoves=$suggestAll` works as intended.

`$SuggestAll` like mentioned in the issue title should either work fine (make it case insensitive) or display an error rather than stating that PKM were modified.

**Comment by KingMarzy** [comment]
i make it case sensitive but nothing changes so is the menu not supposed to be checked off because when i click give all in the TR menu it does it like i didnt use .RelearnMoves=$SuggestAll
