### ISSUE TITLE
Version 20.04.14 throws exceptions on startup and afterwards.

### ISSUE THREAD

**Issue by darkenedAspie** [kwsch/PKHeX#2812]
**Describe the bug**
When attempting to run the latest version, the software throws various exceptions.

**To Reproduce**
1. Start PKHeX (Or try to do anything at all after starting it)

**Expected behavior**
The expected behavior is quite simply for the software to run normally, as it did before I updated from v191226. Also, if there is a way to reacquire the executable for 191226, I would be delighted.

**Additional context**

This particular error happens when selecting 'Open...' in the file menu, but there are others that pop up when doing other things as well. (i.e. on starting the software)

Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.WinForms.Main.MainMenuOpen(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=20.4.14.0, Culture=neutral, PublicKeyToken=null
C:\Users\darkenedAspie\Programs\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by ReignOfComputer** [comment]
1. Do you happen to have a "PKHeX.Core.dll" in the same folder?
2. Can you try moving the PKHeX.exe to a new folder and run it from there?
3. Do you have .NET Framework 4.6 installed?

**Comment by darkenedAspie** [comment]
1. No. It didn't come with one.
2. Have not tried that, but I will in a moment.
3. Yes. Have ever since I first started using PKHeX.

On a side note, I managed to compile from source a build of the version I mentioned successfully using last, and so I no longer require a link to it.

**Comment by darkenedAspie** [comment]
So, I copied the executable for 200414 to my desktop, and somehow it doesn't seem to be having any problems now. I honestly have no idea why that would change anything, but it did. There weren't any spaces or special characters in either file path, so I'm not sure what the difference is between the two.

**Comment by darkenedAspie** [comment]
After doing a bit of testing, I have discovered that the program throws exceptions whenever I have the SD card from my 3DS plugged into the computer. Not while it _isn't_ there. Turning off automatic save detection seems to fix the problem as well.

**Comment by kwsch** [comment]
The posted stacktrace is kinda useless; would probably need to run with debug symbols in the folder to get the full stacktrace to see where exactly things are erroring.

Grab the build for that version off of azure: https://dev.azure.com/project-pokemon/PKHeX/_build/results?buildId=1378&view=artifacts&type=publishedArtifacts

You can also grab the latest commit the same way, to test if there's still any issues:

https://dev.azure.com/project-pokemon/PKHeX/_build/results?buildId=1424&view=artifacts&type=publishedArtifacts

Download the PKHeX/net46 folder; the nuget/netcore aren't necessary. You just want to get the `.pdb` file and run with the conditions you've described above.

**Comment by kwsch** [comment]
Closed due to inactivity.
