### ISSUE TITLE
Unable to compile PKHeX

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2814]
Hey I just wanted to let you know that for around a week or so I haven't been able to compile PKHeX using Visual Studio. Every time I try to compile I get the following errors. Thanks again

1>------ Build started: Project: PKHeX.Core, Configuration: Debug Any CPU ------
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(5,12,5,12): error CS1056: Unexpected character '�'
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(5,13,5,16): error CS1003: Syntax error, ',' expected
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(6,12,6,12): error CS1056: Unexpected character '�'
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(6,13,6,16): error CS1003: Syntax error, ',' expected
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(11,12,11,12): error CS1056: Unexpected character '�'
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(11,13,11,21): error CS1003: Syntax error, ',' expected
1>Done building project "PKHeX.Core.csproj" -- FAILED.
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(5,12,5,12): error CS1056: Unexpected character '�'
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(5,13,5,16): error CS1003: Syntax error, ',' expected
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(6,12,6,12): error CS1056: Unexpected character '�'
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(6,13,6,16): error CS1003: Syntax error, ',' expected
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(11,12,11,12): error CS1056: Unexpected character '�'
1>E:\Downloads\PKHeX-master\PKHeX.Core\Saves\Substructures\Gen8\ValueBlocks\MenuOrderOption.cs(11,13,11,21): error CS1003: Syntax error, ',' expected
1>Done building project "PKHeX.Core.csproj" -- FAILED.

**Comment by kwsch** [comment]
They're supposed to be `é`, not `�`. Whatever you downloaded is corrupt.
