### ISSUE TITLE
XY Nickname cut off if longer than 6 characters

### ISSUE THREAD

**Issue by CyraFen** [kwsch/PKHeX#2817]
**Describe the bug**
If the nickname of the player in XY is longer than 6 characters, PKHeX will replace the excess characters with a ? and the name will display incorrectly in game.

**To Reproduce**
1. Load an XY save
2. Go to the Trainer Info section -> Current Appearance (X/Y)
3. If the nickname is already longer than 6 characters, the bug should be visible. Otherwise, enter a name longer than 6 characters, save, and check the tab again

**Expected behavior**
The game allows for nicknames up to 12 characters, so names of these lengths should be allowed.

**Screenshots**
![image](https://user-images.githubusercontent.com/25874350/80291620-243cff00-871d-11ea-912d-6350a0066dd2.png)
![20200425_182125](https://user-images.githubusercontent.com/25874350/80292135-d2e33e80-8721-11ea-9462-b54dc22da68f.jpg)

**Comment by deadair3210** [comment]
What is your OT normally?

**Comment by CyraFen** [comment]
Apollyon, I also set that as the nickname
