### ISSUE TITLE
Legit 4th gen pokemon flagged as Illegal on 6th gen

### ISSUE THREAD

**Issue by Liger0** [kwsch/PKHeX#2818]
**Describe the problem**
I have never used Pkhex or any cheat/save editor on any of my Pokemon save files.

I transferred my RNGed 4th gen Pokemon to Y and AS via Pokébank, and put them in the box. I made a sav dump with Checkpoint, then I made a backup of the sav in the pkhex folder just to view it.

What I found is that, 

- Tropius and Shaymin are flagged as illegal because synthesis has 0 PP on both of them

- Another shaymin is flagged as illegal because hidden power has 0PP

- Suicune is flagged as illegal because Tailwind has 48PP

- Lugia is flagged as illegal because Tailwind has 48PP

- Latios is flagged as illegal because twister has 0PP

**Expected behavior**
None should be flagged cheat

**Comment by kwsch** [comment]
The program only checks for PP being above the game's limits. PP=0 is not flagged by the program.

![image](https://user-images.githubusercontent.com/6393368/80312330-88050d80-8799-11ea-904f-33608099b268.png)

Tailwind has 48 PP max in Gen4/5, but in Gen6, the maximum is 24 (with PP ups).

![image](https://user-images.githubusercontent.com/6393368/80312370-bc78c980-8799-11ea-8d4f-262cde11d550.png)

In their current state, they are illegal. I assume that withdrawing them from the box and placing them back in will cause the game to fix the problem that Bank caused.

**Comment by Liger0** [comment]
You're right, I noticed it referred to the higher PP in the legal analysis.
The fact it reports 0 PP on some moves is a different behaviour, altough I'm unsure what causes it.
