### ISSUE TITLE
Illegal Smeargle (I think?)

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#2821]
This Smeargle just hatched and was edited, shouldn't it be marked as illegal? It has four moves already, despite being unable to level up to get more Sketches.
[235 ★ - SMEARGLE - A0D209CEA5D0.zip](https://github.com/kwsch/PKHeX/files/4536736/235.-.SMEARGLE.-.A0D209CEA5D0.zip)

**Comment by kwsch** [comment]
https://bulbapedia.bulbagarden.net/wiki/Move_Reminder

**Comment by Kermalis** [comment]
Good point, I guess you could do that three times. Too lazy to test though, closing
