### ISSUE TITLE
items too high

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#2822]
hi in older versions of program the item images were close to the bottom but on the latest build i got from azure they are a little higher than normal . like beedrill mega stone for exmple it used to be at the bottom but now it is kind of close to middle in the box

is this intentional ?

**Comment by kwsch** [comment]
Intentional :)

https://github.com/kwsch/PKHeX/pull/2816

**Comment by poke-hexedit** [comment]
okay that make sense thank you @kwsch . is it still doable to have the small ones less high and put only them close to bottom ? it just look weird to me
