### ISSUE TITLE
Too small Main table in misc

### ISSUE THREAD

**Issue by Liger0** [kwsch/PKHeX#2825]
**Describe the bug**
The main table in the Misc menu in 5th gen is too small to show everything

**Screenshots**
![misc editor](https://user-images.githubusercontent.com/20385116/80579005-a113f580-8a09-11ea-8dd9-b2ec9447780a.png)

**Comment by kwsch** [comment]
That's all there is to show.

**Comment by Liger0** [comment]
What? Words are cut and can't be read.
