### ISSUE TITLE
Can't view all generation of pokemon in database at one time

### ISSUE THREAD

**Issue by Ninja013** [kwsch/PKHeX#2828]
If the save file is on gen 7 or below, it shows up to gen 7 but no gen 8, if it is on gen 8, it only show the pokemon that can be obtained in gen 8. This is after clicking on tools and going to PKM database.
Gen 1: No inteleon
![snipsnip2](https://user-images.githubusercontent.com/58060572/81258728-32c3ca00-8feb-11ea-8f73-2872675629a1.PNG)

Gen 8: nothing but obtainable in gen 8
![snipsnip1](https://user-images.githubusercontent.com/58060572/81258733-348d8d80-8feb-11ea-9ff0-bce76b46f412.PNG)

**Comment by kwsch** [comment]
Intended. It only shows things you can import to the currently loaded save file, for obvious reasons.

**Comment by Ninja013** [comment]
If that's the case why does luxray show up for yellow?

**Comment by kwsch** [comment]
> The pkm conversion checks prevent importing in all other scenarios.

**Comment by Ninja013** [comment]
Oh okay that makes sense. Thank you, if there any way I can disable this to make it were I can see all pokemon in the database? Thanks!

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/333693775e862f16a5f4d8d8b0ee294e864533b0/PKHeX.WinForms/Subforms/SAV_Database.cs#L344-L345

**Comment by Ninja013** [comment]
Yes! Thank you very much! Worked like a charm!
