### ISSUE TITLE
add dotnet core or dotnet 5 port for gnu/linux and macOS

### ISSUE THREAD

**Issue by SillyLily1313** [kwsch/PKHeX#2830]
port PKHeX to dotnet core or dotnet 5 to be cross platform instead of windows only.

readme list that there is experimental support for dotnet core 3.0 but project does not build for it on gnu/linux because there is still windows only features from .net framework

readme also says that gnu/linux os not used by the devs so there may be bugs but in 2020 should build for cross platform reguardless and do testing for the different platforms. there exsist cross platform options in your language of choice now and it is fully supported if you stick to the dotnet core so there is no excuse not to do so. 

PKHeX does not work in wine either btw. it will launch but the UI is not displaying fonts or textures so unuseable. a dotnet core port is needed to be able to use on gnu/linux and macOS and android and ios

**Comment by kwsch** [comment]
A dotnet core is already provided.

.NET 5 / netcore3.0 / netcore3.1 's support for Windows Forms only works on Windows machines.

[The net46 build option works for mono/wine.](https://projectpokemon.org/home/forums/topic/40026-pkhex-for-mac/)

I'm not going to port PKHeX to another GUI framework.
