### ISSUE TITLE
Pokemon XD Shiny Skip Pokemon flagged as Illegal

### ISSUE THREAD

**Issue by Sephirona** [kwsch/PKHeX#2832]
Hi! I finished RNGing a refresh Salamence in XD recently using the Shiny Skip method for an Adamant 31/31/31/25/31/31 spread, but after I finished the game and traded it over to my Emerald file through the trade center under Phenac it was marked as illegal due to a PID mismatch by PkHex. It was successfully RNGed with the following frame sequence for the party Pokemon, 
![1 salamence plan](https://user-images.githubusercontent.com/62824439/81615601-ddebcf00-93af-11ea-9b45-19a964a06ffa.png)

I marked the rerolled PID in red.

![2 salamence pid hit](https://user-images.githubusercontent.com/62824439/81616046-c8c37000-93b0-11ea-8e48-15cbe8f06cb3.png)

The first Nature Lock mon is a Docile Female, the second Pokemon is a Manectric that has its PID rerolled because of the shiny lock (TSV 2446) to two frames extra over the usual 7 frames it would take to generate the Shadow Pokemon, and then from the new Manectric PID the Salamence was generated 7 frames later with the Shiny Skip PID of 53505668.

I think that you may have already addressed a similar issue in ticket #2751 earlier this year, so if this is related and you already know about it, then sorry! It's just slightly different to the shiny skip reroll sequence outlined in that other ticket so I figured I'd open this one too.

**Comment by Sephirona** [comment]
Just wanted to add on to this, Anubis also got back to me with your latest commit as of the moment of this post and it's still coming up as a PID mismatch.

**Comment by kwsch** [comment]
Fixed by above linked commit (forgot to include as commit message).

Thanks for reporting!
