### ISSUE TITLE
Dex Nav Kecleon Flagged as Illegal

### ISSUE THREAD

**Issue by KR1dude** [kwsch/PKHeX#2837]
**Describe the problem**
Wild Kecleon can know the move Dizzy Punch while being hunted via the dex nav in ORAS. PKHeX flags the move as invalid.

**To Reproduce**
1. Dex Nav hunt a Kecleon that knows Dizzy Punch
2. Catch it and view it in PKHeX

**Expected behavior**
Kecleon knowing the move Dizzy Punch should be considered legal

**Screenshots**
![kec](https://user-images.githubusercontent.com/7884144/82408467-7ae9e000-9a20-11ea-8c7f-956811adb131.png)

**Comment by kwsch** [comment]
[352 - Kecleon - 900456C59796.zip](https://github.com/kwsch/PKHeX/files/4659899/352.-.Kecleon.-.900456C59796.zip)
Unable to replicate issue on latest commit.

**Comment by KR1dude** [comment]
Tried on latest commit, still flagged. I'm not sure what part of my Kec is incorrect, comparing it to yours.
[352 - Kecleon - 64830C822707.zip](https://github.com/kwsch/PKHeX/files/4659965/352.-.Kecleon.-.64830C822707.zip)

**Comment by kwsch** [comment]
Thanks; I always love edge cases that were overlooked due to game mechanic interactions :D
