### ISSUE TITLE
Importing Set from Clipboard Competitive Mode

### ISSUE THREAD

**Issue by foohyfooh** [kwsch/PKHeX#2839]
**Is your feature request related to a problem? Please describe.**
It is easy to forget to set the Dynamax Level to 10 for the Pokemon you want use in Battle Tower when you import the set from the clipboard. This also applies for setting TRs that you don't own so that you don't have to go back to PKHex  to make simple move changes.

**Describe the solution you'd like**
When importing set from clipboard in Gen 8, could the Dynamax Level be set to 10 and all the TRs be enabled for the current Pokemon.

**Describe alternatives you've considered**
I don't know if there is any reason that having a full Dynamax Level and knowing all the TRs, so alternatively there could be a checkbox to toggle this feature.

**Comment by kwsch** [comment]
Dynamax: Already implemented, will be in next release - https://github.com/kwsch/PKHeX/commit/4f40330af965a335d66c157e086ba925c34b1f53

All TRs: That's incredibly fishy; most Pokémon will have the bare minimum and almost never more than 8 flagged. Just inject extra TRs if you want to re-teach them.

**Comment by foohyfooh** [comment]
Thanks for informing me of this. I look forward to it. 
That is a good point on the TRs. Did not think about how it could look to some people.
