### ISSUE TITLE
Replace SystemSounds.Exclamation with SystemSounds.Asterisk when a successful action was completed?

### ISSUE THREAD

**Issue by obscurename** [kwsch/PKHeX#284]
SystemSounds.Asterisk is usually accompanied by a successful action was completed, SystemSounds.Exclamation sounds weird when successfully exporting a save file.

Just a thought.

**Comment by kwsch** [comment]
There's only 8 instances of 'Exclamation', and all appear to be related to errors.

```
\MainWindow\Main.cs(2751):            SystemSounds.Exclamation.Play();
\MainWindow\Main.cs(3024):            { SystemSounds.Exclamation.Play(); return; }
\MainWindow\Main.cs(3042):                SystemSounds.Exclamation.Play();
\Subforms\SAV_Database.cs(127):                System.Media.SystemSounds.Exclamation.Play();
\Subforms\SAV_Database.cs(144):                System.Media.SystemSounds.Exclamation.Play();
\Subforms\SAV_MysteryGiftDB.cs(124):                System.Media.SystemSounds.Exclamation.Play();
\Util\FormUtil.cs(128):            System.Media.SystemSounds.Exclamation.Play();
\Util\FormUtil.cs(139):             System.Media.SystemSounds.Exclamation.Play();
```

Asterisk is played by Util.Alert(), [which is what is shown when the save file is exported](https://github.com/kwsch/PKHeX/blob/6f0da56d1f998617326e6214f0c61ae3a6cddfe4/PKHeX/MainWindow/Main.cs#L2922).

**Comment by obscurename** [comment]
Windows 7 plays the Exclamation when the MessageBoxIcon is set to Warning and ignores the System.Media call @ 146 of Util\FormUtil.cs.

If the line @ 148 is changed from 
`return MessageBox.Show(msg, "Alert", MessageBoxButtons.OK, MessageBoxIcon.Warning);`
to
`return MessageBox.Show(msg, "Alert", MessageBoxButtons.OK, MessageBoxIcon.Information);`
then the sound is played.

I only have Windows 7 and have not been able to test it on Windows 10, as the sound is broken on my virtual machine. I bring this up in case it is a bug with 7 or the application itself.
