### ISSUE TITLE
Legality patcher?

### ISSUE THREAD

**Issue by YoshivsJoshi** [kwsch/PKHeX#2851]
One of the problems with PkHex is that the Pokémon legality only updates when PkHex itself is updated, is there any way that PkHex can receive like legality updates from inside the app instead of waiting for full updates?

I think it would be great if there was a feature that allowed Pokémon legality to be patched into PkHex so that bots like the Pokémon discord bot can instantly be able to trade brand new Pokémon like Shiny Gmax Meowth without having to wait for full PkHex updates  

I think a legality updater button on Pkhex that downloads the latest legality updates when Pokémon events come out or DLC would be extremely helpful for everyone so that we can collect the Pokémon from the discord bot straight away instead of waiting for full updates

**Comment by Bappsack** [comment]
you can click on the green checkmark to download commit builds

https://prnt.sc/sv5l4k

**Comment by sora10pls** [comment]
Furthermore: go to the [Events Gallery](https://github.com/projectpokemon/EventsGallery) and add Wonder Cards to your local Mystery Gift Database (`mgdb` folder where your PKHeX exe is) so the legality checker can reference those.

**Comment by YoshivsJoshi** [comment]
Thank you very much, I’m new to github, where do I find that thing in screenshot? I’m on my mobile at the moment so can’t see it

**Comment by sora10pls** [comment]
Right on [the main page of the repository](https://github.com/kwsch/PKHeX).
![image](https://user-images.githubusercontent.com/17801814/83957774-8a4a9500-a838-11ea-8312-684baa7a4286.png)
Click the checkmark -> Details -> View more details on Azure Pipelines -> Under `Related`, click `x Published` -> Download `PKHeX`

**Comment by YoshivsJoshi** [comment]
Thank you so much, appreciate the help!

**Comment by kwsch** [comment]
Alternatively, just wait for whenever the program is posted as a stable release.

You don't need to rely on the legality checker to make legal Pokémon...

**Comment by YoshivsJoshi** [comment]
The Pokémon discord bot that trades Pokémon to you requires that the Pokémon is legal in PkHex, that’s the main reason I wanted to ask

**Comment by YoshivsJoshi** [comment]
Hello, I've downloaded the files and it's still coming up as illegal, here is the pokemon Pk8 file if you're interested in seeing what I mean, thank you 
[https://mega.nz/file/bEpF1YiB#NUET-pnii6quQQOJccdyih6GuYm7GJwsmklGh3MpuPs](url)

**Comment by YoshivsJoshi** [comment]
Hello, I've downloaded the files and it's still coming up as illegal, here is the pokemon Pk8 file if you're interested in seeing what I mean, thank you 

https://projectpokemon.org/home/files/file/4175-hidden-ability-scorbunny/

**Comment by ReignOfComputer** [comment]
Mystery Gift database hasn't been updated with new Home gifts yet. Updates together with releases.

**Comment by penpexgit** [comment]
A little late to the party here, but I am not able to access the Azure page ('401-Uh,oh, you do not have access') after clicking on 'View more details on Azure Pipelines' and login into my Microsoft account. Is it normal?

**Comment by Lusamine** [comment]
> 
> 
> A little late to the party here, but I am not able to access the Azure page ('401-Uh,oh, you do not have access') after clicking on 'View more details on Azure Pipelines' and login into my Microsoft account. Is it normal?

Latest development build is available here now: https://projectpokemon.org/home/files/file/2445-pkhex-development-build/
