### ISSUE TITLE
[Request] Squares/Stars Shown on Gen 7 Saves

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#2852]
Hey Kurt,

In Sword & Shield, the games are designed to show the distinction of Shiny Star vs Shiny Square for Pokémon from past versions via Home. _(I have noticed every shiny Pokémon transferred into the game is Shiny Square which I can only assume it's linked to the broken code which flipped Squares from being rare to being the common.)_

Since this is calculated via Sword & Shield, if it is at all possible to add those calculations to PKHeX for viewing the the Gen 7 games that would be amazing. It would be nice to see if a Pokémon will be Square or Shiny in advance of it making the journey from Bank to Home.

Thanks in advance

**Comment by kwsch** [comment]
You can already hover over the PID and it will show the ShinyXor. https://github.com/kwsch/PKHeX/commit/a50169d3d2db9723939e3c64cd3b8f95ee81c918

Not going to show alternate squares for prior generations where the concept of square does not exist.
