### ISSUE TITLE
Gen 7: Murkrow/Honchkrow Ultra Egg Move

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#2854]
In Ultra Moon & Ultra Sun, almost every species was granted an extra Egg move not available in the Moon & Sun. The Ultra Egg move for Murkrow/Honchkrow is: Punishment.

![image](https://user-images.githubusercontent.com/57371173/83977638-db00d300-a8b6-11ea-8dd1-7727c6b08023.png)

![image](https://user-images.githubusercontent.com/57371173/83977617-ad1b8e80-a8b6-11ea-8de8-a4d4085de2e6.png)

PKHeX shows this as illegal.

**Comment by kwsch** [comment]
Because it is illegal.

https://github.com/kwsch/PKHeX/commit/38fb30e847ca359c0a9f9ebf051d914891697ca6
https://github.com/kwsch/PKHeX/issues/1829

There is no father to pass down the egg move, thus it is unobtainable.
