### ISSUE TITLE
Silvally Pledge moves

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2855]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Silvally passes checking with Fire Pledge and Water Pledge. While both are learnable by it as of USUM, the games legitimately only allow Grass Pledge to be tutored due to an oversight.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

Edit an otherwise legal Silvally with the aforementioned moves in a PK8 format.

**Expected behavior**

The Fire and Water variants being flagged like in Gen 7.

**Screenshots**

In Gen 7:
![Capturea](https://user-images.githubusercontent.com/43196464/84064276-5b473700-a990-11ea-96c7-9bc5c38a0a90.PNG)

In SWSH:
![Capture](https://user-images.githubusercontent.com/43196464/84063916-c7756b00-a98f-11ea-812f-4adc9cac9a0c.PNG)

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/Silvally_(Pok%C3%A9mon)#Trivia

> In Pokémon Ultra Sun and Ultra Moon, Silvally is programmed to be able to be taught all three Pledge moves (Grass Pledge, Fire Pledge, and Water Pledge). However, due to a coding error, the Move Tutor will only offer to teach it Grass Pledge, making the latter two unable to be learned legitimately. **The glitch continues to exist in Sword and Shield.** 

Can also confirm myself it still persists as of the latest game update.

**Comment by kwsch** [comment]
Oh joy...

[Already dealt with this in Gen7](https://github.com/kwsch/PKHeX/commit/72ec264f4c66669a0bef958e85c3be80a3da02c7); probably will have to deal with it in a week-or-so when the DLC hits.

**Comment by CanoeHope** [comment]
Judging from the fact that USUM never got a fix for this during its relevancy and SWSH acknowledging its return (such as giving its signature move a buff), but still not fixing this bug even during the 1/2 year it's been out for now, I'm 99% doubtful the upcoming DLC/update will fix it.

Hopefully I'm proven wrong next week, but from this history...

**Comment by CanoeHope** [comment]
Still persists as of 1.2.0...

**Comment by kwsch** [comment]
Thanks for checking!

There's some new things in personal data, so we'll be sure to handle this before the next program update. (This issue will be closed via a later commit, ofc)
