### ISSUE TITLE
X/Y Trainer nickname issues

### ISSUE THREAD

**Issue by EvM5** [kwsch/PKHeX#2856]
**Describe the bug**
Anything above 5 characters for my Trainer nickname (the one the other kids call you) gets "corrupted". A weird character is added to the end and depending on what the length of the nickname is, it's cut short as well.

Worth noting that I never actually wanted to change the nickname itself, but I edited the amount of money I had and I assume that's how it happened. 

**To Reproduce**
1. Go to 'Trainer info-> Current Appearance'
2. Try to edit the nickname
3. Save and go back to the Current Appearance menu.

**Expected behavior**
I'd see the nickname just as I entered it (assuming it complied with the game's standards, which it did)

**Screenshots**
What I entered
![image](https://user-images.githubusercontent.com/34165691/84104478-706aa700-aa1e-11ea-9126-e1da55d3964e.png)
What I got after refreshing
![image](https://user-images.githubusercontent.com/34165691/84104587-a740bd00-aa1e-11ea-951a-40c01bca911e.png)
Even if I simply put the shortened string minus the weird character
![image](https://user-images.githubusercontent.com/34165691/84104638-c93a3f80-aa1e-11ea-85b2-b564c57347c4.png)
After refreshing it still appears
![image](https://user-images.githubusercontent.com/34165691/84104660-d2c3a780-aa1e-11ea-8326-75f91c7ffc3b.png)

**Additional context**
You get the picture. If I limit it to 5 characters (instead of the above screenshots where I limited it to 6), there is no weird character, or anything that would suggest something's wrong. Once again, this never actually occurred because I tried to change the nickname. In fact, I had set the full nickname normally in-game, and only later noticed the change.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2817
