### ISSUE TITLE
 Can u help me？

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#2857]
Is it convenient for you to tell me how to parse the data of the savefile? I really want to learn it, and I want to learn such a technology.
For example, the item(id) that will appear in the DLC. I don't know how to get it.
I am very sorry for submitting questions that are not related to Pkhex here! But I really want to learn it, and I am a person with strong curiosity, can you satisfy my desire?
Thank u!!!!!

**Comment by CScorpion-h** [comment]
Here is my email : 2587896712@qq.com.Thank uuuuuu!

**Comment by kwsch** [comment]
PKHeX is open source.

You can step through the program's logic and see how it is interpreting the raw data.
