### ISSUE TITLE
Galarian Slowpoke flagged as legal but game rejects it during trade

### ISSUE THREAD

**Issue by legareal** [kwsch/PKHeX#2860]
**Describe the problem**
PKHeX says this Galarian Slowpoke is legal but when trying to trade online in Pokémon Sword it gets the "There is a problem with your Pokémon, it cannot be traded" error.

**To Reproduce**
Please see PKX file attached

**Expected behavior**
PKHeX should mark this Pokémon as illegal, having said that I've been unable to identify what's wrong with it at a glance.
[079-01 ★ - Slowpoke - Illegal.pk8.zip](https://github.com/kwsch/PKHeX/files/4783336/079-01.-.Slowpoke.-.Illegal.pk8.zip)

**Comment by Lusamine** [comment]
This was the problem:
![image](https://user-images.githubusercontent.com/30205550/84716497-e26c5000-af38-11ea-8fac-85408af6365b.png)
Changed it to this and it traded:
![image](https://user-images.githubusercontent.com/30205550/84716524-f57f2000-af38-11ea-99ac-845b3e05f984.png)
It can be changed by modifying the ability in PKHeX.

**Comment by legareal** [comment]
Interesting, thanks! 

Is that the ability byte? Is 0x00 not the Pokémon's first Ability (Gluttony in this case) then?

**Comment by Lusamine** [comment]
I am not sure how you did that but ``0x01`` is Gluttony, ``0x02`` is Own Tempo, and ``0x04`` is Regenerator.
