### ISSUE TITLE
Inverted Aurora/Mystic Ticket event flags in FRLG

### ISSUE THREAD

**Issue by AlamosIT** [kwsch/PKHeX#2862]
**Describe the bug**
Event Flags "Received Aurora Ticket from Mystery Gift" and "Received Mystic Ticket from Mystery Gift" are inverted.

**To Reproduce**
Reproducible looking "Event Flag" in a SAV file with Aurora Ticket or Mystic Ticket (obv not both) received via Mystery Gift.

**Expected behavior**
Right flags flagged.

**Screenshots**
This is what happens with Aurora Ticket on LG
![Annotazione 2020-04-14 104116](https://user-images.githubusercontent.com/62159869/84940770-9b20c380-b0e0-11ea-85fe-e30f0e278b0a.png)

**Additional context**
Already reported on [PKHeX forum](https://projectpokemon.org/home/forums/topic/56811-bug-inverted-auroramystic-ticket-event-flags-in-frlg), maybe here on GitHub is better. Thank you very much <3

**Comment by kwsch** [comment]
Notes:
https://github.com/pret/pokefirered/blob/c47eca8a182a2a202cd65e2af93e9ef322d8674c/include/constants/flags.h#L696-L697
https://github.com/pret/pokefirered/blob/c47eca8a182a2a202cd65e2af93e9ef322d8674c/include/constants/flags.h#L769-L770

https://github.com/kwsch/PKHeX/blob/db30170cc5ee623115d00ab80ed309b42edb2ab1/PKHeX.Core/Resources/text/script/flags_frlg_en.txt#L30-L34
