### ISSUE TITLE
Error when Opening Save file for Pokemon SW/SH

### ISSUE THREAD

**Issue by narendra-nauth** [kwsch/PKHeX#2866]
This bug occurs when opening a save file exported using Checkpoint after Pokemon SW/SH update on 2020-06-17

To Reproduce:
1. Update Pokemon SW/SH to current including DLC
2. Export save file using Checkpoint
3. Open save file using PKHex (20200414)
4. Encounter error: "Input file is too large. File Size: 1575705 bytes"

See screenshot below:
![image](https://user-images.githubusercontent.com/23318907/85024669-66deee80-b144-11ea-8fe1-5e44945270d6.png)

**Comment by architdate** [comment]
PKHeX is not yet updated to support the saves from the latest update. Please be patient and wait for the PKHeX update. Takes time to sort out new legality and new save files.
