### ISSUE TITLE
GTS and Kyurem/Necrozma fusion slots in "Other" tab are too small to hold the new icons

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2869]
![2020-06-20-004447_1920x1080_scrot](https://user-images.githubusercontent.com/12500361/85187522-a5cd8b00-b28f-11ea-84dc-617eb01dbc3d.png)

These boxes were of course big enough back when the program used the older games' native icon size when that game's save file was loaded, but no more.

**Comment by sora10pls** [comment]
This is a known issue and isn't of high priority to fix until we have big sprites for every Pokémon. You can opt out of using big sprites in older save files until then.
