### ISSUE TITLE
How to Open Popup Windows?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#287]

**Comment by kwsch** [comment]
Please include a description to your issue.

When in doubt, check the Shortcuts window (via PKHeX->About->Shortcuts).
[Relevant line.](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Resources/text/shortcuts.txt#L63)

> Doubleclick the Box tab to open up a new Box Viewer. Only one is allowed at a time, unless you hold shift when doubleclicking.

**Comment by ricksee** [comment]
Thanks.
