### ISSUE TITLE
"Save" for Raids & Raids (DLC 1) doesn't work

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#2872]
With the new version of PKHeX which released today, the "Save" button for both the original Raids and the new Raids (DLC) does not do anything other than close the prompts.

In the previous version, once you hit save and re-openned the Raids, you would see the update you made.

In the version, when you go back into the Raids (either or) you will see none of the changes you made were actually saved.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/45a234814bc123419b74d75606ee8fbbf09c4b5c

Hit Cancel for now, or use the Development build posted on the forums.
