### ISSUE TITLE
Adding View/Set/Delete in Box Viewer

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#288]
Is it possible to add view/set/delete to the box viewer?

**Comment by kwsch** [comment]
Yes it's always possible, no it's not worth it.

Click the <-> arrow in the top left corner to swap the Main window box with the Box Viewer, then use the Main Window for View/Set/Delete.

**Comment by ricksee** [comment]
@kwsch Yea I know, but it could be a bit easier to edit Pokemon while moving across multiple boxes.
