### ISSUE TITLE
All DLC raids marked as not active (and non-editable)

### ISSUE THREAD

**Issue by Classical-Maiku** [kwsch/PKHeX#2882]
**Describe the bug**
I exported a save file to edit a raid den (not modded, just a regular legit raid activated with a wishing piece) but when I click on Raids (DLC 1) every single raid has IsActive set to False (even the ones generated by the game). I found my raid by catching the first Pokémon and checking the seed. I tried to edit the seed, exported the save and reloaded the game, but I was still in front of the first mon (but the seed saved in the file was still different).

Also I tried a second time with another raid, I activated a rare beam, and the only active den shown in pkhex is marked as an Event raid. 

**To Reproduce**
1. Activate a raid
2. Export the save file
3. Open in Pkhex
4. Click on Raids (DLC 1)
5. Try to find the raid you activated
6. Change something like stars or RandRoll
7. Re-Inject the save file
8. No changes in game.

**Screenshots**
![image](https://user-images.githubusercontent.com/26364966/85198070-f243b580-b2e5-11ea-8620-6a8dd504a318.png)

**Comment by Classical-Maiku** [comment]
Ok I think probably some dens are simply missing from pkhex, because I tried to activate another den in the forest (the first one was in Stepping Stone Sea) and it works fine.

**Comment by kwsch** [comment]
These should be resolved in the latest commits:

* Amount of raids shown was increased
* Saving the raids now saves correctly
