### ISSUE TITLE
Legal Volcarona in Potbottom Desert flagged as illegal

### ISSUE THREAD

**Issue by crzyc** [kwsch/PKHeX#2884]
**Describe the problem**
A legitimate Volcarona is flagged as illegal; "Invalid: Unable to match encounter from origin game." It was obtained in Potbottom Desert, in the new wild area. This is most likely due to the lack of documentation on static species encounters in the Isle of Armor.

**To Reproduce**
[Volcarona.zip](https://github.com/kwsch/PKHeX/files/4807836/Volcarona.zip)

**Expected behavior**
This should be flagged as legal.

**Screenshots**
Not applicable.

**Additional context**
Title of this issue can/should be changed to documentation on static encounters in IoA.

**Comment by ReignOfComputer** [comment]
Already handled in https://github.com/kwsch/PKHeX/pull/2883.
