### ISSUE TITLE
[SAV Tab] Raids (Non DLC) - "Save" and "Cancel" buttons swapped functionality

### ISSUE THREAD

**Issue by bell4631** [kwsch/PKHeX#2885]
## Bug Description

When opening the raid editor under the save tab, it was observed that the Save and Cancel buttons did not operate as expected. 

## Steps to Reproduce

1. Open PkHex release 06.19.2020
2. Load a save file after the version 1.2.0 update for SwSh
3. Navigate to the SAV tab
4. Click the "Raids" Button
5. Change the raid data for one den (e.g. use Den 1 by default)
6. Click the "Save" Button
7. Click the "Raids" Button
8. Observe Den data was not committed from step 5, even though "Save" Button was used
9. Change Den data for the same den used in step 5
10. Click "Cancel" Button
11. Click the "Raids" Button
12. Observe Den data was committed from step 5, even though "Cancel" Button was used

## Expected Behavior

Using the Save button in the Raids editor should save edited data

Using the Cancel button in the Raids editor should cancel any edits

## Actual Behavior

Using the Cancel button in the Raids editor saves edited data

Using the Save button in the Raids editor cancels any edits

## Screenshots

![image](https://user-images.githubusercontent.com/16672751/85202253-b0f1dc80-b2ca-11ea-9a71-5eca2f1570ab.png)

## Additional Context

Plugins installed:

Automod Plugin
PKHeX Raid Plugin
QR Plugin

## Version Number

* [Release 20.06.19](https://github.com/kwsch/PKHeX/releases/tag/20.06.19)
* Commit e72a58b

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2872

**Comment by kwsch** [comment]
Are you sure this is still an issue on the latest commit? The release posted on the forums isn't the commit you've referenced.

**Comment by bell4631** [comment]
Ah, what is the commit for the Project Pokemon Forums? I initially received my PkHex Download through there to get the 06.19.2020 version update.

If a fix has been applied to it already then this can be disregarded.

**Comment by kwsch** [comment]
The commit on the forums is the one titled "Update ...xxx"; when initial reports started coming in, then the later commits fixed the issue. There's a development build posted on the forums which gets updated on each commit, but it might be unstable as there's multiple changes every day ;)

![image](https://user-images.githubusercontent.com/6393368/85205026-0e435900-b2de-11ea-8a20-59a0a69f3c9a.png)
