### ISSUE TITLE
the button of "randomize ivs"  has something wrong

### ISSUE THREAD

**Issue by gjfkkk** [kwsch/PKHeX#2886]
**Describe the bug**
the button of "randomize ivs" can be used(at least 3 ivs=31) when the species are 887 888 890 but not 880 881 882 883

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ReignOfComputer** [comment]
For clarity: Looks like the Fossil Pokemon are also 3IV minimum, and PKHeX doesn't take that into account. Can reproduce.

**Comment by kwsch** [comment]
Not an issue. The randomization of IVs is unrelated to encounter IV requirements.
