### ISSUE TITLE
Adding Drop Down Suggestion List for Pokemon Databases

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#289]
Is it possible to adding the same drop down suggestion list for the PKM database as well as the Mysyery Gift Data base. Just adding in info does not give suggestions.

**Comment by kwsch** [comment]
Already does suggestions.

![img](http://i.imgur.com/kLI7GN7.png)

**Comment by ricksee** [comment]
@kwsch Nevermind it was included. I didn't know why it stopped doing it. It works now thanks. I'll close this issue.
