### ISSUE TITLE
Raid Parameter Editor - Missing Available Dens in List

### ISSUE THREAD

**Issue by CarlosRamirezGriego** [kwsch/PKHeX#2893]
**Describe the bug**
List of DLC Dens is missing quite a few. I see 59 out of 90.

**Test Data**
Pokemon Sword: 1.2.0
PkHex Version: 20/06/19 Update
Checkpoint: v3.7.4

**To Reproduce**
1. I saved the game in front of a Den with a wishing star (specifically this one: https://serebii.net/swordshield/maxraidbattles/den105.shtml)
2. I Exported the Main with Checkpoint
3. I imported the Main into PkHex
4. Loaded the SAV section
5. Clicked the "Raids (DLC 1)" button
6. Scroll to the bottom in the list of Dens

**Expected Results**
Im not sure how many Dens should be listed, but i see only 59. According to RaidFinder 2.4.0 there should be 90.

**Actual Results**
The List has 59 Dens. See attachment. 
![dens](https://user-images.githubusercontent.com/32551875/85219452-b6960380-b358-11ea-9b8a-8c95b9ea6e43.png)

**Notes**
I noticed this when i set a Wishing Star in HoneyCalm Sea #84 in the game, and it just didnt appear on the list on the main export.

**Comment by egzn** [comment]
https://github.com/kwsch/PKHeX/commit/64be77f46c287b2d40cdbe98694f2cf51f7211f3
