### ISSUE TITLE
WISHMKR Jirachi - Invalid Version

### ISSUE THREAD

**Issue by dzh01** [kwsch/PKHeX#2904]
There's a legality issue in the current release of PKHeX it shows WISHMKR Jirachi as valid if Origin is Colo/XD but it's actually not legal. Can't trade them in Sw/Sh. If it shows Kanto/Hoenn as original region they are fine. Here's an attached file.

[385 - Jirachi - D7F930A2373F.zip](https://github.com/kwsch/PKHeX/files/4828435/385.-.Jirachi.-.D7F930A2373F.zip)

**Comment by Atrius97** [comment]
"Kanto origin" shouldn't be legal, even if Nintendo's legality checker says it is. WISHMKR is only obtainable from the Bonus Disk to Ruby/Sapphire as far as I know, not Emerald, FR/LG or either of the two Gamecube titles.

**Comment by kwsch** [comment]
Gen3 Gift Data is manually entered; a lot of them don't have specified version restrictions for which game can be the origin version :\

https://github.com/kwsch/PKHeX/blob/66a797371ade6c9fdd7ef77072b77bfe7f8795b9/PKHeX.Core/Legality/Encounters/Data/EncountersWC3.cs#L20
