### ISSUE TITLE
Mystery Gift Event Size

### ISSUE THREAD

**Issue by Snaid1** [kwsch/PKHeX#2908]
**Describe the bug**
The Mystery Gift Interface for Gen 4/5/6/7 game saves (and possibly others) still uses the small squares that used to be used in the storage interface. Making it sometimes difficult to see what the Gifts you have are.

**To Reproduce**
1. Start Pkhex
2. Load a gen 4 save with wonder cards in it.
3. Click SAV tab
4. Click Mystery Gift button
5. See issue

**Expected behavior**
Be able to see full pokemon and items like we can in the box view

**Screenshots**
![image](https://user-images.githubusercontent.com/23465479/85792720-31f90b80-b6f1-11ea-80bc-1871dc48bf84.png)
![image](https://user-images.githubusercontent.com/23465479/85792960-87351d00-b6f1-11ea-8f76-4e36a4d656ff.png)
![image](https://user-images.githubusercontent.com/23465479/85793605-7fc24380-b6f2-11ea-9cd4-9155206f7034.png)
![image](https://user-images.githubusercontent.com/23465479/85793353-222df700-b6f2-11ea-9f40-6e25de42da66.png)

**Additional context**
I tested with pokemon Diamond, Platinum, White, Omega Ruby, and Sun saves

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2869
