### ISSUE TITLE
Suggestion: when program is updated, show changelog on startup

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#291]
So let's start with a random scenario.

PKHeX 20160918 is updated to 20160927. For the first time that the program is run by the user, have it display the new changelog at startup so that the user can know what's been added, fixed, or removed. After their first time running the program, don't show the changelog on startup until a new update is released, and repeat this process.

I understand that the thread on ProjectPokemon shows this already, but let's be real, this is the Internet and so many people will just not even bother to read it. Now that could also be said about this suggestion, but considering it pops right in front of them, they're more likely to look into it.

**Comment by kwsch** [comment]
[for self reference](https://msdn.microsoft.com/en-us/library/bb397755(v=vs.110).aspx)
