### ISSUE TITLE
request : small items lower on box slot

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/PKHeX#2916]
**Is your feature request related to a problem? Please describe.**
items are sometimes too high when in view of a pokemon slot .

**Describe the solution you'd like**
if its possible i would like if smaller items can be put closer to the edge of the box slot like some big items fit fine but if a pokemon has for example a mega stone then it is very high and not close to border . for example in this the candy should be closer to bottom
![image](https://user-images.githubusercontent.com/35694052/86285972-9b768f80-bbb3-11ea-9b1f-52fa2d515a44.png)

**Describe alternatives you've considered**
none

**Additional context**
i asked in the past about items being higher than they were but i think this would be a good change for smaller item pictures .

**Comment by kwsch** [comment]
Closed by #3215 and #3213, thanks to @LukeThe 's initial PR and the follow-up item crop change.
