### ISSUE TITLE
Allow PKHeX to Automatically Go To Chose Directory When Opening Save File Other than Folder PKHeX is On/Allow Any Backup At Any Folder We Want 

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#292]
Is it possible to allow us to choose any directory we want as a default directory for when we wanna open our SAV files? I thought it be easier for people who save their games at other places than the program that is in? Can it apply to backups as well?

**Comment by kwsch** [comment]
It's preferred to export to the same folder the save was opened from.

You can always define favorite folders (Quick Access) in Windows Explorer, which can be easily jumped to when the Save File dialog appears.
