### ISSUE TITLE
Certain 1.2.0 additions should not be legal on lower than 1.2.0 saves.

### ISSUE THREAD

**Issue by PP-theSLAYER** [kwsch/PKHeX#2920]
**Describe the bug**
1.2.0 Mons should not be legal on lower than 1.2.0 saves.
While I imagine this will be laborious to implement, Gmax on hatched mons should be illegal on saves below 1.2.0

**To Reproduce**
I imported a pcdata.bin from a 1.2.0 save into 1.1.0, and Sandshrew showed up legal.
So did my mons that were hatched and has Gmax (as opposed to obtained from raid)

**Expected behavior**
Sandshrew being illegal.
My hatched Gmax Kanto starters should be illegal.
(so should be any mon returning in 1.2.0)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23535344/86435455-4ff2eb80-bd43-11ea-9721-00910ad4cb7a.PNG)

**Comment by kwsch** [comment]
I'm not gonna add in annotations and stuff so that old patches have different legality behavior. Seems like way too much work when things would be legal anyways -- trading locally/wifi requires updating, so there's no risk.
