### ISSUE TITLE
Shiny Zeraora from HOME

### ISSUE THREAD

**Issue by derbayer36** [kwsch/PKHeX#2922]
**Describe the problem**
Unlinke the Magearna from HOME, the Shiny Zeraora does not pass the legality check

**To Reproduce**
pkm file can be found here:
https://projectpokemon.org/home/files/file/4210-shiny-zeraora/

**Comment by ReignOfComputer** [comment]
![image](https://user-images.githubusercontent.com/2667537/86508868-032c1500-be16-11ea-817f-710b0deb7438.png)
Hint: It has not. See date when program was released, see when event was released.

**Comment by derbayer36** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/2667537/86508868-032c1500-be16-11ea-817f-710b0deb7438.png)
> Hint: It has not. See date when program was released, see when event was released.

i compiled the latest build today and it still does not work.

**Comment by architdate** [comment]
That is because a simulated wondercard has not been released for Zeraora.
What @ReignOfComputer was saying was that the mystery gift data has not been contributed. Once its contributed, it will work

PS. the pk8 file != Mystery gift data

**Comment by sora10pls** [comment]
#2917
