### ISSUE TITLE
Lycanroc (SwSh) Evolution

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#2924]
![image](https://user-images.githubusercontent.com/57371173/86522935-fc9f9c80-be19-11ea-914c-8426fe780bde.png)

Lycanroc's evolution is tied to time in Sword & Shield. There's no version exclusivity.

**Comment by kwsch** [comment]
Works fine on latest commit.
https://github.com/kwsch/PKHeX/commit/a5b72bd1ce2923ba38c07253b0a49b06488626bd
https://github.com/kwsch/PKHeX/commit/16cf59c8518517376d5a3059a6a75a4d521ccb98
