### ISSUE TITLE
False positive flag on Mew

### ISSUE THREAD

**Issue by randomdice101** [kwsch/PKHeX#2925]
I got my mew from the pokeball plus. When I load my save in pkhex I get the alert symbol but when I click on in PKhex says the pokemon is Legal...

(When first viewing the Mew)
![image](https://user-images.githubusercontent.com/4016932/86523284-19e36380-be38-11ea-938c-cb4dbddd8024.png)
(When looking at the Alert)
![image](https://user-images.githubusercontent.com/4016932/86523287-32ec1480-be38-11ea-89f5-52170949d8c0.png)

Playing in Japanese if that helps narrow it down.

**Comment by kwsch** [comment]
The PKM Editor automatically fixes minor issues for you.

To view legality without loading to tabs, hold control when right clicking the box slot; that will tell you what the original issue was.

**Comment by randomdice101** [comment]
This is what I got...

![image](https://user-images.githubusercontent.com/4016932/86523473-f837ab80-be3a-11ea-94e4-960a9465c4d3.png)

![image](https://user-images.githubusercontent.com/4016932/86523476-05549a80-be3b-11ea-8fe7-a40bd57fbe4e.png)

seems PP is set to 35 for some reason? thats how I got the pokemon from the pokeball... It's never been sent to home
