### ISSUE TITLE
Kyurem Skillful battler ribbon marked as invalid, seems confused with battle tree great ribbon.

### ISSUE THREAD

**Issue by randomdice101** [kwsch/PKHeX#2926]
**Describe the problem**
My ribbon master from White, Kyurem level 75 Is being flagged as having an invalid ribbon (Skillful Battler). That is not a ribbon my Kyurem has, it has the Battle tree great ribbon (from Ultra Moon). The 2019/09/19 version I kept displays the Kyurem as valid while the 2020/06/22 version (with the same Kyurem migrated to shield) marks it as an error but the Skillful Ribbon is not on it).

**To Reproduce**
I'm unsure what produces the glitch exactly. The Reshiram next to Kyurem also has the same ribbon. I got all possible ribbons on Kyurem then migrated it up through pokemon home.

**Expected behavior**
I expect the Kyurem to be legal and now complain about a ribbon it doesn't possess...

**Screenshots**
(2019-09-19 version Ultra Moon Save prior to migrating)
![image](https://user-images.githubusercontent.com/4016932/86523227-51054500-be37-11ea-96bb-4a6eade1a91c.png)
(2020-06-22 version Shield Save after I just got CFW on my Switch)
![image](https://user-images.githubusercontent.com/4016932/86523239-772ae500-be37-11ea-99b3-3c148a324f33.png)
(Flagged mew is also present from my other ticket. Alert message below)
![image](https://user-images.githubusercontent.com/4016932/86523250-90339600-be37-11ea-9e3e-5a2d55063e57.png)

**Comment by sora10pls** [comment]
Skillful Battler is obtained by defeating a Battle Chatelaine in Generation 6, but Kyurem is in the Battle Maison's banlist.
![image](https://user-images.githubusercontent.com/17801814/86524283-b14fb300-be46-11ea-8123-fb81e5310700.png)
![image](https://user-images.githubusercontent.com/17801814/86524289-b90f5780-be46-11ea-8a73-cb323212675d.png)

**Comment by randomdice101** [comment]
Yes I know it’s in the banlist. If you look at the other screenshots I included, I don’t have the skillful battler ribbon on the Kyurem. I never received it. I don’t know why it’s reporting that I have it

On Jul 4, 2020, at 22:36, Matt <notifications@github.com> wrote:

﻿

Skillful Battler is obtained by defeating a Battle Chatelaine in Generation 6, but Kyurem is in the Battle Maison's banlist.
[image]<https://user-images.githubusercontent.com/17801814/86524283-b14fb300-be46-11ea-8123-fb81e5310700.png>
[image]<https://user-images.githubusercontent.com/17801814/86524289-b90f5780-be46-11ea-8a73-cb323212675d.png>

**Comment by sora10pls** [comment]
Can you please provide the PK8?

**Comment by randomdice101** [comment]
Sure thing when I get back to my pc in the morning I’ll add it. I’m heading to sleep now. Just don’t close the ticket just yet please

On Jul 4, 2020, at 22:41, Matt <notifications@github.com> wrote:

﻿

Can you please provide the PK8?

**Comment by kwsch** [comment]
If it has the Memory of defeating a chatelaine, then it'd be flagged as well.

**Comment by randomdice101** [comment]
I've attached a pk6 pk7 and pk8 version of my Kyurem. The pk6 and pk7 were backed up prior to migrating to the next generation. None of them have the skillful battler ribbon. They don't have a memory of defating a chatelaine either since Kyurem can't get into the battle maison.

[Kyurem pk6-pk8.zip](https://github.com/kwsch/PKHeX/files/4874805/Kyurem.pk6-pk8.zip)

**Comment by kwsch** [comment]
PK6: Memory 0x11 (Kyurem battled at Autumn’s side and beat Loudred. The Pokémon remembers that it was restless.)
PK7: Memory 0x04 (Link Trade)
PK8: Memory 0x1E (Chatelaine/Strongest Trainer = Kyurem battled at ジェシカ’s side and defeated the strongest Trainer. The Pokémon definitely remembers that it felt good.)

Dunno what exactly grants this memory -- seems like they've changed the memory text so that something else may grant it?

**Comment by randomdice101** [comment]
The only thing I did with the Kyurem was beat Leon to get the battle tower ribbon. Is it using the same ID number for that memory?

On Jul 9, 2020, at 20:06, Kurt <notifications@github.com> wrote:

﻿

PK6: Memory 0x11 (Kyurem battled at Autumn’s side and beat Loudred. The Pokémon remembers that it was restless.)
PK7: Memory 0x04 (Link Trade)
PK8: Memory 0x1E (Chatelaine/Strongest Trainer = Kyurem battled at ジェシカ’s side and defeated the strongest Trainer. The Pokémon definitely remembers that it felt good.)

Dunno what exactly grants this memory -- seems like they've changed the memory text so that something else may grant it?
