### ISSUE TITLE
invalid Curry Mark in all Pokemon 

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#2931]
All the Pokemon with get a invalid Curry Mark 

![image](https://user-images.githubusercontent.com/18640392/86763888-b5531f00-c058-11ea-8ee0-c18f081d4a30.png)

lock to specific poke ball type

![image](https://user-images.githubusercontent.com/18640392/86764043-d156c080-c058-11ea-90ef-c53be2a4d592.png)

Mark on work on wild pokemon

this is a bug 

Thank You So Much 
Best Regards
OrionSilver

**Comment by Orionsilver** [comment]
this should look like this with wild caught 
![image](https://user-images.githubusercontent.com/18640392/86765543-568ea500-c05a-11ea-9169-9d867c167ba0.png)

**Comment by Orionsilver** [comment]
their should be more option for the pokeball type

**Comment by sora10pls** [comment]
Curry Mark is only applied to wild Pokémon that can join your Pokémon Camp while making curry, only if you have Poké Balls, Great Balls, and/or Ultra Balls in your Bag. Are you positive these Pokémon were obtained legitimately ingame with no edits whatsoever?
