### ISSUE TITLE
[Gen 2] Cleffa egg marked as illegal due to invalid experience

### ISSUE THREAD

**Issue by Blaziken257** [kwsch/PKHeX#2938]
**Describe the problem**
In Generation 2, a Cleffa egg is marked as illegal. The message is "Invalid: Eggs cannot receive experience."

**To Reproduce**
Breed a Clefairy and a compatible Pokémon to produce a Cleffa egg.

A .pk2 file is attached. (It's enclosed in a ZIP file because GitHub doesn't allow attaching .pk2 files.)
[173 ★ - EGG - 79DD.zip](https://github.com/kwsch/PKHeX/files/4907790/173.-.EGG.-.79DD.zip)

**Expected behavior**
Cleffa is in the Fast experience group, so it is expected to have 100 Exp. at Level 5. However, PKHeX flags this as illegal.

**Screenshots**
![pkhex_cleffa_gen_2](https://user-images.githubusercontent.com/2187686/87236186-afcc4080-c39a-11ea-9178-72aabf9e3bb0.png)

**Additional context**
I haven't seen this issue with other Pokémon, even others in the Fast experience group.

**Comment by sora10pls** [comment]
PKHeX is reading this encounter as the Odd Egg static encounter, which has a fixed 125 Exp. Points.
