### ISSUE TITLE
Pokemon XD: Editing Pokemon Breaks Shadow Monitor Entrees

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#2941]
**Describe the bug**
Using PKHeX to edit a Pokemon whose data is recorded in the shadow monitor breaks their entry in the shadow monitor

**To Reproduce**
1. Open XD Save in PKHeX
2.) Edit a shadow Pokemon, in my case, I changed the PID and IVs to be better, although still legal by PKHeX's standards
3.) Save and load into Pokemon XD
4.) Check the Shadow Monitor and you'll see broken entries and missing data

**Expected behavior**
The Shadow Monitor correctly reflects changes made to the Pokemon

**Screenshots**
![Error Pic](https://user-images.githubusercontent.com/20786416/87272660-28fb8e80-c494-11ea-9617-7380fbf00b08.png)

**Additional context**
I will also upload the save file in question. One save is before using PKHeX, and the other is after using PKHeX to change the Shadow Poocheyena and Teddiursa
[Pokemon XD Current Save.zip](https://github.com/kwsch/PKHeX/files/4910698/Pokemon.XD.Current.Save.zip)

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/53405-bug-oddity-with-shadow-recognition/
https://projectpokemon.org/home/forums/topic/56486-shadow-monitor-in-xd-messed-up/
