### ISSUE TITLE
Demo Ash Greninja Illegal

### ISSUE THREAD

**Issue by dzh01** [kwsch/PKHeX#2943]
**Describe the problem**
All .wc7 for Ash-Greninja are showing illegal

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

**Expected behavior**
Showed legal on earlier versions
[2046 SM - サトシ Greninja (JPN) (M).zip](https://github.com/kwsch/PKHeX/files/4915481/2046.SM.-.Greninja.JPN.M.zip)

**Screenshots**

**Additional context**

**Comment by kwsch** [comment]
Don't redeem it on games it can't be redeemed on.

Working as intended.
