### ISSUE TITLE
Original Color Magearna flagged illegal if not shiny

### ISSUE THREAD

**Issue by IAmEmber** [kwsch/PKHeX#2948]
**Describe the problem**
Original Color Magearna is shiny locked, but PKHeX won't recognize it as legal unless it's shiny. I assume this is due to PKHeX using a placeholder TID of 0, which would indeed make the Magearna shiny if it weren't locked. Interestingly it checks for shininess in general rather than the specific TID of 0, as altering the TID to anything else that yields a TSV of 0 maintains legality.

**To Reproduce**
Generating Magearna from the Mystery Gift database should yield a legal Magearna as all of the info is correct, but it's flagged as illegal unless the TID is altered to make it shiny.  Attached is my legitimate Original Color Magearna flagged as illegal, and a "legal" version edited to be shiny.

[magearna.zip](https://github.com/kwsch/PKHeX/files/4955689/magearna.zip)

**Expected behavior**
Should be flagged illegal if shiny and not the other way around. I'm not sure if a HOME TID with a TSV of 0 is legitimately possible and an all-zero PID would be altered to prevent shininess (there's definitely some kind of shiny lock in place as the shiny version can't be used online), but for now it's easiest to just assume a HOME TID with a TSV of 0 is impossible, and that all other TIDs are legal.

**Comment by kwsch** [comment]
Works fine on latest commit.
