### ISSUE TITLE
Better Editing For Pokemon In Party Box

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#295]
Is it possible to make the editing and dragging in Pokemon to the party similar to the ones in boxes? Dragging a Pokemon straight to a party slot does not work unless you press Set, other than that it won't appear. Sometimes deleting a Pokemon from a Party Slot can cause a ? mark left when you are about to save your game.

**Comment by Ninjistix** [comment]
adding this here for ref from my close PR, might be duplicate features but the same general idea.
*   ability to move/swap Pokemon in Party Box, just like in the BOX
*   ability to deposit Party Pokemon into BOX (leaving 1st Pokemon)
*   ability to drag Pokemon from party to be deposited in open box slot.

**Comment by ObscenityIB** [comment]
i never drag, i always set, everywhere

**Comment by Ninjistix** [comment]
@kwsch still not able to drag drop/ swap pkm in party, tried with gen 3/5/7

**Comment by kwsch** [comment]
Recompile yourself, the CI server is a little scrambled and is not compiling the latest commit.

**Comment by Ninjistix** [comment]
i always build myself

**Comment by Ninjistix** [comment]
[PKHeX.zip](https://github.com/kwsch/PKHeX/files/659285/PKHeX.zip)

**Comment by kwsch** [comment]
@Ninjistix 
I decompiled that .exe; all of the changes from https://github.com/kwsch/PKHeX/commit/796c2998eaf15b6d471438ec963d773602cb3d35 were not present.

**Comment by Ninjistix** [comment]
my mistake didn't see that e860fd6 changed the default location of the new build location, from bin/release to bin/x86/ClickOnce-Release, my shortcut was still running the older version
