### ISSUE TITLE
Gen4/Gen5/Gen6/Gen7: Pokemon sprites are cut in Wonder Card / Battle Box(Gen6 only)

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#2950]
**Describe the bug**
Pokemon sprites are cut inside the Wonder Card boxes. In Gen 6 this happens also inside Battle Box sprites boxes

**To Reproduce**
Just open a Gen4/5/6/7 save file with PKHex and go to SAV>Mystery Gift / Other (for Battle Box)

**Expected behavior**
Sprites should be seen entirely

**Screenshots**
![1](https://user-images.githubusercontent.com/20956021/88455190-adc2b100-ce73-11ea-8882-94a3a9f38920.png)
![2](https://user-images.githubusercontent.com/20956021/88455196-af8c7480-ce73-11ea-8616-575551d6f080.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2869
