### ISSUE TITLE
Ruby and Sapphire national pokédex unlock

### ISSUE THREAD

**Issue by albertodev01** [kwsch/PKHeX#2954]
**Describe the bug**

I tried to enable the national pokédex on ruby but I had no success. I did the following:

 - Event Flags > Event Flags > Received National Pokédex > Tick to enable
 - Event Flags > Event Constants > National Dex Enabled > Set it to 1

None of the above work. I downloaded A-Save and it worked. I noticed that A-Save set the following values:

 - Event Flags > Event Flags > Received National Pokédex > Tick to enable
 - Event Flags > Event Constants > National Dex Enabled > Set it to 770

When I tried with another save to manually set the value to 770 in National Dex Enabled I had no luck, still doesn't work. I imagine there's something more under the hood that has to be altered in order to enable the dex.

**To Reproduce**

 1. Event Flags > Event Flags > Received National Pokédex > Tick to enable
 2. Event Flags > Event Constants > National Dex Enabled > Set it to 1

**Expected behavior**

I'd expect the national pokédex to be enabled but there's still the regional one.

**Additional context**
This issue only happens on ruby **and** sapphire (emerald, fire red and leaf green are fine).

**Comment by Bl4ckSh4rk** [comment]
Well the game seems to require a few other values, not only flags. It won't work properly if these are not set.
> Block 0
> 0x19 → 1
> 0x1A → 0xDA
> 
> Block 2
> 0x5C0 bit 0 → 1

**Comment by albertodev01** [comment]
Could that be done automatically when ticking on _Received National Pokédex_ in the _Event Flags_ section?

**Comment by Ammako** [comment]
Most likely not, flags editor doesn't work that way. It just gets the list of flags from a text file and dynamically generates a list from that. Can't really make one checkbox behave differently from the others.

I think the best would be a button or checkbox under the Pokédex menu to handle enabling or disabling national dex, like every other gen has. The entries in flags/constants don't really serve a purpose.

**Comment by kwsch** [comment]
Block Data can already edit this via the NationalDex property toggle.
