### ISSUE TITLE
PKHeX chokes on Pokemon with non-null "Name Terminator" bytes

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2959]
Bytes C8 and C9 in the PK6/PK7 formats are documented as "Unused"; they immediately follow the 24-byte OT Name field and are probably intended to be a virtual 13th character which is always null to ensure the name will properly be null-terminated even if the trainer name has its maximum possible length. While the tests here were initially investigated using bytes C8-C9 at the end of the OT name, the same behavior arises on bytes 58-59 (with respect to the nickname), or 90-91 (with respect to the HT name).

For whatever reason, one of the Pokemon in my mechanics-testing box ended up with 0x0101 in those bytes instead of the usual 0x0000. Its OT name does not reach the 12-character maximum, so attempting to read its trainer name already comes up with a prior null character before the oddly-valued 13th character. The game itself is capable of reading this Pokemon without issue, and it performs normally under a variety of use cases including a link battle (which was aimed at testing a mechanic, though not really this particular mechanic).

For posterity, I tried again by constructing a Pokemon that did have the full 12 characters in its OT name, with a non-null 13th (so there's no terminator to be found), and in this case the game still worked sensibly with it except that the trainer name was displayed as blank, likely as a failsafe measure against buffer overruns when it can't find a terminating character.

PKHeX is less forgiving when it comes to parsing these Pokemon. If you try to load an individual pk7 with a non-null character in the 13th position (even if there is a terminating null earlier on in the name) you get a sound effect of disapproval, and the left pane becomes populated with incompletely-parsed gibberish. If you load a save file that has such a Pokemon in one of the PC boxes, that slot will appear with a red background and no Pokemon sprite at all; the program does not let you click to retrieve the data from that slot for loading into the left pane or for saving as an individual .pkX file. You can clobber it with something else and that slot behaves sensibly from then on, just the same as if you clobbered any other Pokemon; this still doesn't help you retrieve any of the contents that were there previously.

Given that these are fixed-length buffers, and the game itself copes with them sensibly and doesn't open up any kind of vulnerability to an overrun here, having a Pokemon with a non-null character in position 13 of one of its name fields should be regarded as a minor issue, akin to the "Invalid Trash Bytes" legality error in earlier games, and would even make sense to be one of the issues that gets auto-fixed when you save the Pokemon to a box slot. It shouldn't be such a crippling error that PKHeX completely fails loading that Pokemon's data structure at all.

**Comment by kwsch** [comment]
PKHeX assumes those null terminators are 00 00, always. 

```cs
        public PK7(byte[] data)
        {
            PokeCrypto.DecryptIfEncrypted67(ref data);
            if (data.Length != SIZE_6PARTY)
                Array.Resize(ref data, SIZE_6PARTY);
            Data = data;
        }

        public static void DecryptIfEncrypted67(ref byte[] pkm)
        {
            if (BitConverter.ToUInt16(pkm, 0xC8) != 0 || BitConverter.ToUInt16(pkm, 0x58) != 0)
                pkm = DecryptArray6(pkm);
        }
```

If the data does not have zeroes there, it is assumed to be encrypted, then the program decrypts it. I don't think it's worth refactoring tons of logic so that decryption happens prior to the new object creation, because then we'd lose the ability to one-line read encrypted PKM data.
