### ISSUE TITLE
Possible Addition: Adding an Evolution/Pre-Evolution Button/Column List

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#296]
For some Pokemon, they are able to evolve. Is it possible to add an Evolution Button of some sorts to instantly change its Pokemon to its form in its evolutionary line. For instance, changing a Pikachu to Raichu or Pichu with the Press of the "Evolutionary" button or something of the sorts. I thought it would be something to consider if someone just wanted it quickly than looking it up. Or at least an Evolution list and have all possible evolutions in a drop-down list to select or type up.

**Comment by evandixon** [comment]
Might get more complicated in cases where there's multiple possibilities, like Eevee or Kirlia.

**Comment by ricksee** [comment]
@evandixon In those cases or for all Pokemon that can evolve, I guess a Evolution Column could be added and then a list of all possible Pokemon within its evolutionary line could be implemented.

**Comment by kwsch** [comment]
No point in doing so. The user can always read bulbapedia or any other site to see what a Pokémon can evolve to, and type in the species name they want to change it to.
