### ISSUE TITLE
catch rate issue GEN1

### ISSUE THREAD

**Issue by uchujin64bit** [kwsch/PKHeX#2964]
**Describe the problem**
Sorry, my English is poor.
I'm playing pokemon yellow.
I have two rats.
1 is level 20 Raticate. this was captured as level 3 Rattata.
2 is level 17 Raticate. this was captured as level 17 Raticate.
I think Rattata's catch rate is 255. 1 has 255, because it evolved.
2's catch rate is 90, because it captured as it is.
PKHeX ver.20200718 showed me both of them are legal.
but, 20200807 said level 20 Raticate is illegal.

**To Reproduce**
How to reproduce is just open pkm file with PKHeX20200807,  20200718. And I think this problem couse by some pokemon's evolve.

**Expected behavior**
I hoped to that 20200807 shows me legal.

**Screenshots**
I added file that contains screenshots and pkm date.

**Additional context**
The same issue is seen with Primeape and Pidgeotto.
They were captured by me before evolution.
They are taking over the catch rate.
Version 20200807 said that Raticate,Primeape and Pigeotto were illegal.
But Gallados, which I got before evolution, is legal.

20200807 - legal : gallados
20200807 - illegal : Raticate, Primeape, Pidgeotto
20200718 - legal : all of them
[catch rate issue.zip](https://github.com/kwsch/PKHeX/files/5046837/catch.rate.issue.zip)

**Comment by kwsch** [comment]
Note to self: this will be fixed when the dev refactoring branch gets merged in: https://github.com/kwsch/PKHeX/tree/slotception

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/pull/2974 on August 21, 2020
