### ISSUE TITLE
GEN4 manaphy's egg isuue

### ISSUE THREAD

**Issue by uchujin64bit** [kwsch/PKHeX#2965]
**Describe the problem**
I'm sorry for my poor English.
I posted this isuue to discord.
but kindly member told me, when you have issue, you should post github.
So, I post this issue to here as well.
 
I have a manaphy egg.
this is from Pokémon Ranger Guardian Signs, and platinum(JP) + RNG.
PKHeX ver.20200807 said "Invalid: Invalid Met Level, expected 0."
but this egg's Met Level is 0.
and Manaphy has lost its own special egg icon.it has normal egg icon.

ver.20200314 showed egg is legal, and it own special egg icon.

**To Reproduce**
How to reproduce is just open pkm file with pkhex.

**Expected behavior**
20200807 shows me Manaphy's egg is legal, And it has special egg icon.

**Screenshots**
I added file that contains screenshots and pkm.

[manaphy egg GEN4.zip](https://github.com/kwsch/PKHeX/files/5046897/manaphy.egg.GEN4.zip)

**Comment by Ammako** [comment]
https://github.com/kwsch/PKHeX/blob/66454818292b15f2e5cd9a227ce086d5d3953cfc/PKHeX.Core/Legality/Verifiers/LevelVerifier.cs#L40

If this equals 1, as it does with every other egg, all is fine.

My guess is that `EncounterMatch.LevelMin` gets a value of 0 from the manaphy egg event gift data, while every other egg encounter has this set to 1 somewhere else in the code.
