### ISSUE TITLE
How do I use the program?

### ISSUE THREAD

**Issue by dani856e** [kwsch/PKHeX#2967]
Hey, I'm new to github and also pkhex in general. I've tried opening the solution file, but I've come to a conclusion that it's not the right way. How do I use pkhex?

**Comment by Lusamine** [comment]
Solution file is the source code.  Unless you're going to edit it or build it yourself, it's useless to you.

Download the program to use it: https://projectpokemon.org/home/files/file/1-pkhex/

**Comment by dani856e** [comment]
Okay, thank you. Do you know if it has been updated to approve Zarude and shiny Celebi yet?

**Comment by architdate** [comment]
It has
