### ISSUE TITLE
Possible Option: Adding a Sort Option for Species Based On Pokedex Number

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#297]
Is it possible to add another sort option for Pokemon species list in a drop-down list. Or at least, in the Pokemon databases?

**Comment by kwsch** [comment]
I don't see a point in doing so; I prefer alphabetical and alphabetical only for everything outside of Pokédex status editing. The toggle you requested falls in line with user preference, and is best suited for individual users tweaking the code.

[img]http://i.imgur.com/3oJsXu2.png[/img]
