### ISSUE TITLE
Bug in "Strategy Memo" Update in XD Saves

### ISSUE THREAD

**Issue by jjaldridge2009** [kwsch/PKHeX#2975]
**Describe the bug**

When Pokemon are added to a Pokemon XD save file, and then the save file is imported back to GameCube memory card a blank space appears at the top of the "Strategy Memo." The Blank Space has a normal type, and no name. 

**To Reproduce**

1. Open Pokemon XD Save File
2. Import Pokemon from other Gen 3 Games
3. Export Save to Memory Card
4. Load Save, Check Strategy Memo.

**Expected behavior**

When I took the save I used prior to adding Pokemon from my other Gen 3 games, and imported it to the Memory Card, the blank space did not appear and Abra was the first Pokemon in the list.

**Screenshots**

![image](https://user-images.githubusercontent.com/16225603/90698609-23415780-e24f-11ea-881f-1ca7f1fc8a29.png)

**Comment by kwsch** [comment]
Shadow Monitor and Strategy Memo writing has been disabled since the last release: https://github.com/kwsch/PKHeX/issues/2956

Until someone figures out how to get it working correctly, it'll stay disabled since it isn't much value added.
