### ISSUE TITLE
Pikachu's Beach Score

### ISSUE THREAD

**Issue by ShadowMario3** [kwsch/PKHeX#2976]
**Describe the bug**
I tested this with US and JPN saves. If I open the Trainer Info box and select save (doesn't matter if any changes to other values were made), the score for Pikachu's Beach completely changes. This issue has been around ever since this feature was added (191226). Still occurs on the 'slotception' branch build which seems to have fixed a lot of Gen I legality errors.

Another small issue is the score seems to be shuffled around a bit when viewed through PKHeX, though this isn't too big of an issue (in-game score of 5720 becomes 2057 in PKHeX)

**To Reproduce**
1. Load Yellow Save File
2. Go to 'SAV'
3. Click on 'Trainer Info'
4. Click on 'Save' without editing anything.
5. Click on 'Trainer Info' again
6. Pikachu Beach score has changed

**Expected behavior**
I would expect the score to simply remain in the original value. 

**Screenshots**
Video of the error: https://youtu.be/v2aJhzt3ebQ

Screenshot of minor error: 
![image](https://user-images.githubusercontent.com/36941677/91127068-72cebb80-e673-11ea-9bff-2b6a46531390.png)

**Additional context**
Normally wouldn't be too big of an issue, but I would like to keep whatever score I had if I mess around with Trainer Info.

**Comment by kwsch** [comment]
Notes:

binary coded decimal means {0x10, 0x00} gets printed as 1000
if pkhex is displaying 2750, the stored value would be {0x27, 0x50}
however, the "little endian" in the [disassembly comment](https://github.com/pret/pokeyellow/blob/500d99c258145d233af8d14cdb5c6e0200dfc1d8/wram.asm#L2923) implies it's different behavior than the regular BCD stored values like money
```c
wSurfingMinigamePikachuHP:: ; c5d6
    ds 2 ; little-endian BCD
wSurfingMinigameRadnessMeter:: ; c5d9
; number of consecutive tricks
    ds 1
wSurfingMinigameRadnessScore:: ; c5da
    ds 2 ; little-endian BCD
wSurfingMinigameTotalScore:: ; c5dc
    ds 2 ; little-endian BCD
wSurfingMinigameHiScore:: ds 2 ; 4-digit BCD little-endian
    ds 1
```
so maybe it's just the surfing scores being implemented differently from the other binary-coded-decimals, in which the values are read in reverse
