### ISSUE TITLE
crystal: unable to load save file from physical cartridge due to incorrect file size

### ISSUE THREAD

**Issue by Kashouryo** [kwsch/PKHeX#2979]
**Describe the bug**
Unable to load save file that has the incorrect file size that I dumped from a real cartridge.

**To Reproduce**
1. dump a pokemon crystal cartridge's save data
2. load it with pkhex
3. shows an error complaining about the file size and forces me to not load the save file

**Expected behavior**
save file from a physical cartridge should load normally

**Suggestion**
Allow the user to manually select the game version and have the option to ignore the file size(which caused by the missing RTC data at the end of the file that can only be created with an emulator in this case)

**Screenshots**
![image](https://user-images.githubusercontent.com/37679684/91645444-183ab400-ea13-11ea-9c66-e7db123dbded.png)

**Additional context**
The save file is valid and can be played on different emulators
The game was dumped with an insideGadgets GBxCart

**Comment by kwsch** [comment]
`0x8000` is already recognized as a valid save size.

https://github.com/kwsch/PKHeX/blob/1ee459a46c4d1cc8c61a7691dc277dbcf8fbbdad/PKHeX.Core/Saves/Util/SaveUtil.cs#L42

If the contents of the save data does not contain valid lists of PKM data, then it is not a valid save file.

https://github.com/kwsch/PKHeX/blob/1ee459a46c4d1cc8c61a7691dc277dbcf8fbbdad/PKHeX.Core/Saves/Util/SaveUtil.cs#L194-L204

Without seeing the save file, can't see why it is not recognizing things.

**Comment by Kashouryo** [comment]
[PKPCRYSTAL.zip](https://github.com/kwsch/PKHeX/files/5146154/PKPCRYSTAL.zip)

Here is the save file

**Comment by kwsch** [comment]
Not a valid save file.

I can force it to load, but the only valid data that appears is your trainer name `Zelda` with a trainer ID of 50433. Doesn't look like the save file has progressed at all, and everything is uninitialized (looking at the save file in a hex editor).

**Comment by Kashouryo** [comment]
OK... It's very likely that Polished Crystal (a crystal rom hack with quality of life enhancements) changed the save file structure, thus not compatible with pkhex.

Thanks for your help!
