### ISSUE TITLE
Adding Type/Met Date/Egg Met Date/Hatch Date/Ball Type/Met Location to Pokemon Database

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#298]
Is it possible to add to the Pokemon Database the Pokemon type, its met date, the met date if its an egg, an egg hatch date, the type of Pokeball it is in, and the Met Location to the Pokemon Database?

**Comment by kwsch** [comment]
Use the "Advanced Search" feature, where you can apply filters for many more pkm properties.
