### ISSUE TITLE
Issue with Pokemon Yellow legality

### ISSUE THREAD

**Issue by LiquidDeath911** [kwsch/PKHeX#2982]
**Describe the bug**
I am playing Pokemon Yellow on the Delta Emulator for iOS. I exported my save file from my iPhone to my computer and then opened it in PKHeX. I have not used any cheats and everything I have caught has been legitimate.

These following Pokemon are showing as "Illegal" in PKHeX:

Pidgeot - Caught as a Pidgey and evolved into a Pidgeotto then Pidgeot
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

Dugtrio - Caught as a Diglett and evolved into a Dugtrio
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

Fearow - Caught as a Spearow and evolved into a Fearow
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

Butterfree - Caught as a Caterpie and evolved into a Metapod then a Butterfree
- Invalid Move (Tackle)
- Invalid Move (Stringshot)
- Invalid Move (Harden)
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

Sandslash - Caught as a Sandshrew and evolved into a Sandslash
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

Raticate - Caught as a Ratata and evolved into a Raticate
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

Victreebel - Caught as a Bellsprout and evolved into a Weepinbell then a Victreebel
- Invalid Move (Vine Whip)
- Unable to match an encounter from origin game.
- Catch rate does not match any species from Pokemon evolution chain

**To Reproduce**
Attached is my .sav file, import it and see the errors.

**Expected behavior**
These Pokemon should show up as legal since they were caught in game and no cheats used.

[cc7d03262ebfaf2f06772c1a480c7d9d5f4a38e1.zip](https://github.com/kwsch/PKHeX/files/5185460/cc7d03262ebfaf2f06772c1a480c7d9d5f4a38e1.zip)

**Comment by Lusamine** [comment]
Everything in this save file is legal for me on latest commit.

**Comment by LiquidDeath911** [comment]
Well I just re-downloaded the latest commit, rebuilt the executable, and still have the illegal pokemon.
Going to attach screenshots of what I am seeing. The pokemon are in Box 4 and Box 5.

![Screenshot1](https://user-images.githubusercontent.com/35089748/92423853-2f328200-f148-11ea-8408-ea4e974a4ec9.JPG)
![Screenshot2](https://user-images.githubusercontent.com/35089748/92423856-2fcb1880-f148-11ea-9294-34a3269d486d.JPG)

**Comment by Lusamine** [comment]
Still fine for me.
![still fine](https://user-images.githubusercontent.com/30205550/92424797-e6c89380-f14a-11ea-93ee-ffaa51c098b1.gif)

**Comment by LiquidDeath911** [comment]
Lusamine,

Just double checking, there is a setting that says "Flag illegal slots in save file" is there any chance you have that unchecked?

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/92425786-debe2300-f14d-11ea-8586-eb54cbb3f0c6.png)
I have never unchecked this in my life.

**Comment by LiquidDeath911** [comment]
Then I have no idea why it is showing illegal on my side. In your video I noticed on your executable, the logo in the top left is Blue.
Does that mean anything? I am using the latest commit, version 20.08.07 and my executable still has the Red logo

**Comment by Lusamine** [comment]
I run PKHeX-Plugins which shouldn't affect the legality of Pokemon in a save file.

**Comment by LiquidDeath911** [comment]
So what can I do to figure out why this is happening then?
Also what plugins are you using?

**Comment by Lusamine** [comment]
I suspect you aren't on latest commit because the development build with no plugins, fresh out of the zip, also considers your Pokemon legal.

![image](https://user-images.githubusercontent.com/30205550/92426271-21ccc600-f14f-11ea-924b-6aefa709795a.png)

https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

**Comment by LiquidDeath911** [comment]
Oh, well I was downloading from GitHub, but looks like that development build you linked is newer.
Let me try that.

**Comment by LiquidDeath911** [comment]
Yes, looks like I was just using an older build. The GitHub release needs to be updated I guess.

Thank you for your help!
