### ISSUE TITLE
Shiny 10% Zygarde w/ Aura Break being falsely flagged as Legal

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#2984]
**Describe the problem**
PKHeX currently flags Shiny Zygarde as legal in any form with any ability, however the ingame encounter of 10% Zygarde with Aura Break is shiny-locked, and the Shiny 50% form from event distribution can only change form if it has already undergone the ability change to Power Construct via the Zygarde Cube key item, which is a one-way process. Therefore "Shiny 10% Zygarde with Aura Break" is impossible.

**To Reproduce**
PK7 files provided:
[Shiny Zygarde Legends 2018.zip](https://github.com/kwsch/PKHeX/files/5212436/Shiny.Zygarde.Legends.2018.zip)

**Expected behavior**
10% Shiny Zygarde should be flagged as illegal in form 718-01, (or just "10%" form), 
and only flagged legal in form 718-02, (or the "10%-C" form), as it requires Power Construct to become it's 10% form, and cannot regain Aura Break afterwards.

**Additional context**
There has been no event distribution for 10% Shiny "Aura Break" Zygarde to date, and the "Legends 2018" Shiny 50% Zygarde is the only possible Shiny Zygarde so far, and requires Power Construct ability first to become it's 10% form.

**Comment by kwsch** [comment]
Blame tracking: https://github.com/kwsch/PKHeX/commit/a62324a5a1ab2ee236b59ae7554af119108f2e3b#diff-738bfbce46a725950abacf2b6555ec93L307
