### ISSUE TITLE
Gen8 rental team reading

### ISSUE THREAD

**Issue by prrfun** [kwsch/PKHeX#2986]
![image](https://user-images.githubusercontent.com/21154722/93020099-e11cf300-f60d-11ea-9b00-27e505b615a1.png)
Anyway to use this function in pkhex? If need offset, what is the offset? Thanks

**Comment by kwsch** [comment]
It's a feature for using the PKHeX.Core API for other code authors. The PKHeX.WinForms GUI package does not utilize this logic.
