### ISSUE TITLE
Possible Option: Bulk Legality Check

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#299]
Is it possible to do a mass legality check for all Pokemon in the boxes? If don't can that be added? Like it doesn't have to tell which problems all the Pokemon that didn't pass have. Like for Pokemon that are legal get a check on the left on their sprite. Those that don't get the red sign. It could also display how many passed and how many failed.

**Comment by kwsch** [comment]
![img](http://i.imgur.com/loSbfCm.png)
