### ISSUE TITLE
"Winning Ribbon" not being flagged illegal on Level 51+ Met Encounters in Gen 3

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#2990]
**Describe the problem**
The "Winning Ribbon" is obtained from participation in Gen 3's (RSE) Battle Tower, in the Level 50 difficulty. All the documentation I can find on the topic says "Gen 3's Battle Tower doesn't scale levels and instead bars level 51+ Pokemon from entry in Level 50 mode", there should be no possible way for a level 51+ Pokemon to obtain this Ribbon.

PKHeX currently falsely flags the Winning Ribbon, (and by extension, a full 8/8 "Golden" Battle Memory Ribbon in later generations, where "old gen" Battle Tower Ribbons are consolidated into a single legacy ribbon), as legal on Pokemon from encounters that are level 51 or above.

Example using "Level 55+ encounter" Colosseum Shadow Tyranitar provided below, in original .ck3 format to show "Winning Ribbon" issue and .pk7 format to show "Battle Memory Ribbon" issue:

**To Reproduce**
Examples of Legal and Illegal versions of this encounter provided, (ck3 and pk7 formats):
[Level 55+ Encounter Colo Tyranitar.zip](https://github.com/kwsch/PKHeX/files/5243434/Level.55%2B.Encounter.Colo.Tyranitar.zip)

**Expected behavior**
All Gen 3 encounters that can only be encountered at level 51 or above should be flagged illegal if they have the "Winning Ribbon"

An original "Met Level" of Level 51 or above in Gen 3 should be mutually exclusive with the Winning Ribbon.

All Gen 3 encounters that can only be encountered at level 51 or above that are transferred into a generation where Battle Tower ribbons are consolidated into the single "Battle Memory Ribbon" should be flagged as illegal if they have the "8/8, Golden/Completed version" of the Battle Memory Ribbon, as the limit should be "7/8, Blue version" if the "Winning Ribbon" was not obtainable in Gen 3 for that encounter.

**Screenshots**
![3](https://user-images.githubusercontent.com/39707481/93557745-02951c00-f939-11ea-8eeb-cda84d6965d4.png)

**Additional context**
The displayed met level can change when transferred to later generations which may "legalize" some pokemon that were met at level 51+ but can be obtained elsewhere in the same game version, but some specific Gen 3 encounters/events/gifts are uniquely available at level 51+ and won't "become legal when transferred" due to the "Gen 3 met data" being replaced/lost.

The "Orre origin, Met Level 55+, Shadow Tyranitar" given as the above example will remain illegal even after transfer to Gen 4+ because of its unique encounter conditions, it is not obtainable in Orre by any other encounter, and the "Region/Game of Origin" information is retained through transfer. Similar unique encounters and event Pokemon distributed at level 51+ would also retain data like Region/Version, Event OT/ID, etc. that renders them still illegal in Gen 4+.

**Comment by soopercool101** [comment]
Since the list of "Pokémon not allowed in the Battle Tower at all" massively overlaps with the list of Pokémon only found at levels greater than 50, I found that the only other in-game example of this that I could find is the Shadow Dragonite from XD: Gale of Darkness. This is also notable for many event Pokémon, such as the 10ANNIV events which come in at level 70.
