### ISSUE TITLE
Request: Clothing editor in Sword/Shield

### ISSUE THREAD

**Issue by mariosmentor** [kwsch/PKHeX#2991]
**Is your feature request related to a problem? Please describe.**
Usually, I don't learn about clothing-related events for Sword/Shield until after the fact. I'm sick and tired of being constantly reminded that I'll never get the Wal-Mart tracksuit/Leon's Cap/etc.

**Describe the solution you'd like**
A button that gives you all the game's clothing items (especially those limited to events)

**Describe alternatives you've considered**
None that wouldn't require extensive research.

**Additional context**
n/a

**Comment by sora10pls** [comment]
You can import completed Fashion Blocks that are posted to the forums.
