### ISSUE TITLE
Can I ask you a question?

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#2999]
I compiled the latest pkhex and raid plugin. When I opened PKHEX, I didn't see the raid plugin.
And Also I placed Microsoft.Z3.dll and libz3.dll in the same folder as PKHeX.
I didn't know if I made a mistake or if pkhex did not load the plugin. Can you try it if it is convenient for you?

**Comment by sora10pls** [comment]
You should be asking this in that plugin's issues page, not the base program's.
