### ISSUE TITLE
About mystery gift's shiny serebii 

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3000]
The pid of serebii officially delivered is locked, that is 06730367.
It can be exchanged even if xor is 0, but it is illegal.
By the way, the ec of serebii is random.

**Comment by CScorpion-h** [comment]
I got this conclusion by getting multiple serebii officially delivered.

**Comment by Lusamine** [comment]
What exactly is the issue?  PKHeX handles the movie Shiny Celebi correctly.
Changing the PID away from ``06730367`` causes it to become illegal correctly.
EC can be changed as much as you want without it becoming illegal.

**Comment by CScorpion-h** [comment]
The official delivery is pid locked. It means that pids other than 06730367 are illegal.
Like 496C4C78, the pid with xor equal to 0 can be exchanged, but it is actually illegal.
You can go to those who obtained the serebii through the serial code and compare the pid. You'll find that the pid is consistent.

**Comment by Lusamine** [comment]
PKHeX already handles this.  Try it yourself.

**Comment by CScorpion-h** [comment]
> PKHeX already handles this. Try it yourself.

You can see my responses above

**Comment by Lusamine** [comment]
> 
> 
> > PKHeX already handles this. Try it yourself.
> 
> You can see my responses above

Okay, I finally understand what you mean.  It's already known that the PID is locked, and any imported WC8 show the correct PID.  Your issue is that PKHeX doesn't enforce the PID lock, right?

**Comment by CScorpion-h** [comment]
> > > PKHeX already handles this. Try it yourself.
> > 
> > 
> > You can see my responses above
> 
> Okay, I finally understand what you mean. It's already known that the PID is locked, and any imported WC8 show the correct PID. Your issue is that PKHeX doesn't enforce the PID lock, and illegal mons are incorrectly legal, right?

Yes, it is. I'm sorry for not explaining clearly.
