### ISSUE TITLE
XD Gales: Legit Anti-Shiny RNGed Pokemon marked as PID mismatch

### ISSUE THREAD

**Issue by Sephirona** [kwsch/PKHeX#3008]
**Describe the problem**
Since the last update, legitly Anti-shiny RNGed mons with correct TID/SID combinations are marked as illegal. They were fine before that. I did a little digging and noticed that in the last update, Lego had in issue #2952 pointed out that a Pokemon with the wrong TID/SID combination was incorrectly marked as legit despite not causing an anti-shiny jump. I'm not sure if fixing that was what caused this issue, but now it appears as though the correct TID/SID combinations produce a false positive legality result as well.

**To Reproduce**
The twin seeds I used in my RNGs were:

1243BC41 | 9D8707EB | !!! | Quirky | 1 | 31 | 0 | 31 | 31 | 31 | 31 |  
9243BC41 | 1D8787EB | !!! | Rash | 1 | 31 | 0 | 31 | 31 | 31 | 31 | 

My TID/SID combination: 
TID: 00007
SID: 39528

I found the seeds using RNGReporter, and, using Pokefinder, I RNGed an XD save file that would make the above Quirky and Rash PIDs shiny. Then, I played through the game and RNGed all possible useful Pokemon that could use the above spreads using Dolphin. No RAM hacking of any sort was used. 
In Anti-Shiny RNG, when the TID/SID would make a particular PID frame shiny, the game skips to the PID/nature two frames after the original PID but retains the original frame's IVs.
The Pokemon I RNGed came with the expected IVs and nature, as I show in screenshots I will attach below.

However, upon viewing the Pokemon Emerald file containing my traded-over XD mons (transferred using an emulated game link cable, not PkHex) all of the Anti-Shiny RNGed XD mons from the above seeds were marked illegal despite being fine in the previous version of PkHex.
I would prefer not to attach a pkm file to this post, but I can provide one of Articuno to you through a private channel as I did with my Salamence in an earlier ticket if you would like. 

**Expected behavior**
The Pokemon I RNGed were generated by the XD game itself and were not altered in any way, so I expected them to be marked as legal. PkHex was not used to open the Gales XD save file at any time, and was only used to view the save data after the Pokemon were already transferred through emulated gba link cable to my Emerald save.

**Screenshots**
These are the two seeds I used
![seed1](https://user-images.githubusercontent.com/62824439/94979144-2a66b100-04ef-11eb-8fc1-0acf9e154ad1.png)

One of the proofs of PID hit, of my Articuno. Articuno is a party slot 5 RNG in the final Greevil battle. Moltres was also RNGed using the same PID and was set into the Shadow Monitor by allowing myself to lose to Greevil. It is also one of the mons marked illegal despite being a legit RNG. The exported text file I used to find where I landed during the RNG is to the right. As you can see, there was an Anti-Shiny jump from the Quirky to the Timid PID two frames afterwards.
![3](https://user-images.githubusercontent.com/62824439/94979183-5eda6d00-04ef-11eb-8356-06bc6b03adba.png)

Here is the resulting Articuno, as well as the other Anti-Shiny RNGed mons that were marked illegal in this recent update. My Bold Anti-shiny 31/0/31/31/31/31 Zapdos was marked illegal as well in another box. 
![2](https://user-images.githubusercontent.com/62824439/94979357-22f3d780-04f0-11eb-961f-79cfb1f62cd8.png)

**Comment by ShadowMario3** [comment]
If you take a look at the issue you linked to, you will see that it was fixed on July 26. Using the latest dev version shows that this has been fixed (used both PIDs you listed):

![XD Ability 01](https://user-images.githubusercontent.com/36941677/94995926-72c5b380-056f-11eb-8177-2d06f18cfbfb.PNG)

![XD Ability 02](https://user-images.githubusercontent.com/36941677/94995929-76593a80-056f-11eb-8c7a-daf650b98fba.PNG)

The next stable release will include this fix.
