### ISSUE TITLE
Make default Japanese OT name "ＰＫＨｅＸ" instead of "1337"

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3009]
**Is your feature request related to a problem? Please describe.**
I noticed your commit of changing the default Japanese OT name to "1337", and I figured you can instead use the Japanese characters that resemble ASCII ones (you can choose these in-game even)

**Describe the solution you'd like**
Instead of "1337" as the default Japanese OT name, make it "ＰＫＨｅＸ"

**Additional context**
I've used these types of chars for my own needs in the past (mostly for Emerald-JP shiny Mew), and I think it's a very nice solution, especially since PKHeX is exactly 5 characters.

Brand new Emerald-JP save that was created in this name:
![image](https://user-images.githubusercontent.com/29823718/95006805-3ed1a900-05d6-11eb-832c-c8edf11d29ce.png)
![image](https://user-images.githubusercontent.com/29823718/95006790-05993900-05d6-11eb-8dec-ea27801b3608.png)

You can find these types of chars at the bottom of "character map" in Windows:
![image](https://user-images.githubusercontent.com/29823718/95006820-69bbfd00-05d6-11eb-9493-56781ae6cf42.png)
![image](https://user-images.githubusercontent.com/29823718/95006823-70e30b00-05d6-11eb-9348-83c396ab2c12.png)

They are legitimate Japanese characters.

**Comment by kwsch** [comment]
There are no ascii-like characters in the Gen1/2 character table.

https://github.com/kwsch/PKHeX/blob/5853888020f37b78214bdea816b7e61c63161953/PKHeX.Core/PKM/Strings/StringConverter12.cs#L319-L489
