### ISSUE TITLE
Please add an undo button

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#301]
Hi. I wanted to know if it was possible to add an undo button to pkhex. I constantly delete pokemon by mistake or do other irreversible things and there is no way that I know of to reverse these changes without restarting and losing all of my other changes I have made.

**Comment by kwsch** [comment]
Probably best implemented as a Stack object, where Set/Delete create new "BoxChange"es and push it to the stack. When an undo is requested, the BoxChange at the top of the stack is popped off and reverted.

[Stack Class](https://msdn.microsoft.com/en-us/library/system.collections.stack(v=vs.110).aspx)
[Default Stack Capacity is 10](http://referencesource.microsoft.com/#mscorlib/system/collections/stack.cs,7c1d0a7ea96800a3,references), which is probably enough.

BoxChange properties:
```
int Box
int Slot
int Offset
_object_ OriginalData
```

As for triggering the undo, maybe just a hotkey like CTRL-U. CTRL-Z is already a general purpose undo for text fields.

**Comment by evandixon** [comment]
Perhaps add standard Edit -> Undo/Redo menu items that, when clicked, call the same function that the Control+Z/Y event handlers call.

**Comment by ricksee** [comment]
@kwsch I would suggest a redo button in case as well.
