### ISSUE TITLE
About EncounterSuggest

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3010]
I'm making a multifunctional plugin, and I want to add the enctouenr-suggestion about Gen4's Pokemon.
It means there is no recommendation from `EncounterType`.
Thank you for the trouble!

**Comment by architdate** [comment]
Are you trying to get the EncounterType out of a Gen 4 Encounter that is yielded by the EncounterSuggestion class? Or am I understanding you wrong

**Comment by CScorpion-h** [comment]
> Are you trying to get the EncounterType out of a Gen 4 Encounter that is yielded by the EncounterSuggestion class? Or am I understanding you wrong

When Clicking the Met_Location Label, PKHeX will give a suggestion about Pokemon's enctounerInfo, but it doesn't have the recommendation about encounterType in Gen4.

**Comment by architdate** [comment]
Why not just `EncounterMatch` from the `LegalInfo` and then convert that to a Pokemon using `enc.ConvertToPKM`? That way the converted PKM would have the associated EncounterType and will even be legal as long as the encounter is valid.
