### ISSUE TITLE
Poké Puffs Editor forms sorting incorrectly.

### ISSUE THREAD

**Issue by diegofg10** [kwsch/PKHeX#302]
> SAV_Pokepuff.cs, line 78

```
int basepuff = 20
int basemod = 6
````
sorting incorrectly, as it sort from
```
20 Deluxe Spice Poké Puff
21 Supreme Wish Poké Puff
22 Supreme Honor Poké Puff
23 Supreme Spring Poké Puff
24 Supreme Summer Poké Puff
25 Supreme Autumn Poké Puff
````
leaving `26 Supreme Winter Poké Puff` out.

On the PKHeX it appears right but in-game you can see that the sorting was incorrect, I don't know if it is because the _Unlimited Tile Puzzle_ is locked.

Also could you make another `ModifierKeys` for 
```
21 Supreme Wish Poké Puff
22 Supreme Honor Poké Puff
```
since these two gives +10 affection rather than +6 from the other supremes.

**Comment by kwsch** [comment]
Implemented in latest commit:
https://github.com/kwsch/PKHeX/commit/41bc841eaa4946b68f4a1b560eda2f0bc60811a5

I figured the GiveAll should offer to give either a varied assortment, or the +10's. The original intent was to give the best possible.
