### ISSUE TITLE
(Alola) Route 14 encounters?

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#3025]
**Describe the problem**
PKHeX has a bunch of Route 14 encounters in the database for SM/USUM that I'm not sure should be there. pokemondb.net claims that there's a bunch of land encounters there, but this is the only source I've seen that claims this. Everywhere else shows only water or fishing encounters, and in-game there doesn't even seem to be anywhere for land-based encounters to happen on that route anyway.

**To Reproduce**
Every Walking encounter on [this page](https://pokemondb.net/location/alola-route-14) shows up in PKHeX's encounter database, and consequently they show up as legal when they probably shouldn't.

**Expected behavior**
These encounters probably shouldn't be in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/43770697/95665355-fa4a8e00-0b3e-11eb-8c89-615d15e5bbdc.png)

**Additional context**
---

**Comment by Ammako** [comment]
Same thing with Ancient Poni Path and water-based encounters, for some reason.

**Comment by CScorpion-h** [comment]
Not only Vulpix, but Sandshrew. There are only surfing and fishing encounters to capture Pokemon in Route 14. Although Tapu Village is on the 14th road in the map. That maybe something wrong.
