### ISSUE TITLE
Problem with Let's Go, Pikachu and Eevee Pokédex counters

### ISSUE THREAD

**Issue by CarlosofKalos** [kwsch/PKHeX#3028]
**Describe the bug**
Hi there! 

PKHeX now has the ability to modify the Capture and Transferred counters per Pokémon in the newest 20201010 update. I tried it out and encountered an error message where that if PKHeX detects any Captured or Transferred values above 9999 for an individual Pokémon, it will throw an Error window saying that a value over 9999 is not valid (in my case it's 10002 as seen in the screenshot below), though the game seems to go beyond the 9999 limit that PKHeX allows for them.

**To Reproduce**
1. Modify the Captured and Transferred counts of an easy to catch Pokémon (My case was Pidgey) to 9999.
2. Save your changes and export your save back to your game.
3. Catch and send the Pokémon that you modified the counts for to the Prof. then save your game and backup your save.
4. Import the save in PKHeX and go to the count modifier for that Pokémon you caught and/or transferred and you'll see said error saying something like "Value of '10000' is not valid for 'Value'."

**Expected behavior**
No error screens. 

**Screenshots**
![problem](https://user-images.githubusercontent.com/72763524/95785359-98576900-0ca3-11eb-9c59-857aaca1f974.PNG)

**Additional context**
I think PKHeX should expand the value limits of Captured and Transferred per Pokémon. Thanks!

**Comment by kwsch** [comment]
Capture is still capped at 9999, but individual Transfer counts are capped to the larger 99.... cap. Will have to revise the GUI to be wider & use the total clamp value.
