### ISSUE TITLE
Game Cannot Hold Item ???

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#303]
ISSUE: 
![item error](https://cloud.githubusercontent.com/assets/12572974/19052280/241ec1c4-8984-11e6-8828-f13c28eb5d83.JPG)

made a new game to export all starters, attempted to import starters back to one save and got that error, on Pokemon Gold,Silver and Crystal. I'm sure all starters from that Gen is holding a Berry when you receive them, and in game they are still holding the Berry.

**Comment by SciresM** [comment]
Fixed with latest commit.

Also fixed a whole slew of I<->II bugs and II<->II language bugs.

**Comment by Ninjistix** [comment]
thanks @SciresM
