### ISSUE TITLE
About Getting EggMoves

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3031]
I didn't seem to see a method to get the EggMoves directly in the code. I mean I want to get it in other program, but it's internal.
More concretely, according to different versions, get the corresponding egg moves of Pokemon.
For example, Snorlax has the following egg moves  in the Gen8: Double-Edge, Curse, Fissure, Counter and Belch. When the generation is 8, I can get the above egg moves. In other words, when the generation is 7, I can get the egg moves corresponding to the Gen7 of Snorlax.
I don't know if I have neglected. If there is such a method, please tell me the specific method name. If there is no such method, could you please add it?
Or do I use `eggmove.pkl` file to implement it myself? 
I feel it will be very troublesome. Because it's internal. Haha.

**Comment by kwsch** [comment]
What's the end goal for getting the egg moves?

`EncounterLearn` has the ability to check if a given species can know a list of moves, and you can extract info from those encounters.

**Comment by CScorpion-h** [comment]
> What's the end goal for getting the egg moves?
> 
> `EncounterLearn` has the ability to check if a given species can know a list of moves, and you can extract info from those encounters (version, type).

Ok, I will red EncounterLearn's code. And the goal is to turn Pokémon into an egg with one click and Auto Set egg moves, not basic moves. Although we can manually enter the name of the move.
