### ISSUE TITLE
About SuggestedMoves

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3032]
**Describe the bug**
When some pokemon's egg have empty moves, only three relearn moves are suggested, but in fact, the legality check results in four moves.Here is the ScreenShot:
![Screen1](https://user-images.githubusercontent.com/64029159/96021710-66502d80-0e82-11eb-8686-4536403a0c33.png)
![screen2](https://user-images.githubusercontent.com/64029159/96021716-6a7c4b00-0e82-11eb-8b80-0c506e6a225a.png)
And if pokemon has illegal skills such as pound, the suggested moves will have pound.
![Screen3](https://user-images.githubusercontent.com/64029159/96022085-ef676480-0e82-11eb-9c0c-b3bbeb8ff101.png)

**To Reproduce**
1. Set the species to combee(Any pokemon without egg moves)
2. Set pokemon to egg and Change Egg_Location to a Nursery worker
3. Empty the moves | Set illegal moves(eg: pound)
4. Click Suggested Relearn Moves 

**Expected behavior**
I don’t think it’s a bug but it should be an enhancement. It should be correctly suggest relearn moves.

**Additional context**
When debugging the pkhex, I found that the length of `window` variable in the `GetSuggestedRelearnMovesFromEncounter` method in the `Analysis ` class changed to 5 after AddRange() and Distinct(), and the value of index 4 is 0.

**Comment by kwsch** [comment]
If the egg Pokemon has a move it cannot learn via level up, it must be a relearn move.

Might be skipping the first index incorrectly...
