### ISSUE TITLE
About MethodFinder

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3035]
I want to calculate `seed` by `PID`, and then calculate `IVs` by seed.
I checked the code and found that there is a `MethodFinder` class.The Analyze method in this class can get the seed, but when I try to call this method, it always returns PIDIV.None.
My code is as follows:
`PIDIV analysis = MethodFinder.Analyze(pkm);
 PIDGenerator.SetValuesFromSeed(pkm, analysis.Type, analysis.OriginSeed);`
Here is my test sample:
[003 - VENUSAUR - 156F1CC41245.zip](https://github.com/kwsch/PKHeX/files/5396382/003.-.VENUSAUR.-.156F1CC41245.zip)
I don’t know if I did something wrong or my thinking was wrong.

**Comment by architdate** [comment]
`MethodFinder.Analyze` uses the pkm's pid and ivs to output it's rng method and seed

`SetValuesFromSeed` uses the rng method and seed to set appropriate PID and IVs to the pkm. 

You seem to be going about in a circle with that logic

**Comment by CScorpion-h** [comment]
My question is why do Analyze method always return None, I've tried other Pokemon too.  
There seems to be a method in PKHeX that calculates seed by using only PID

**Comment by kwsch** [comment]
Works fine for me...
![image](https://user-images.githubusercontent.com/6393368/96352661-bfce7d00-1079-11eb-97ed-fedb35635ae9.png)

**Comment by CScorpion-h** [comment]
Aha? That's weird. Maybe there's something wrong with me. 😂I don't think it's a question of program code. Maybe I should try again. After I wake up, take a look at what is going on.

**Comment by CScorpion-h** [comment]
Oh, I have changed its PID before. Does this matter? I changed it with the SetNaturePID method.

**Comment by kwsch** [comment]
Those methods don't follow any PIDIV algorithm; they just change the PID to satisfy some nature-gender correlation.

**Comment by CScorpion-h** [comment]
Oh, I see. I read the code again and these methods have nothing to do with the PIDIV algorithm. indeed. Thanks.
