### ISSUE TITLE
RBY In-Game Trades do not set nicknames

### ISSUE THREAD

**Issue by soopercool101** [kwsch/PKHeX#3039]
**Describe the bug**
RBY In-game trades do not have set nicknames in the encounter database, whereas they do have set nicknames in-game. As RBY trainers cannot be named with the hardcoded TRAINER string, the conditions for the name rater to rename these in-game trades is never possible without the use of major glitches (like coin case) or cheating devices.

**To Reproduce**
1. Import the Yellow version trade Machoke from the encounter database

**Expected behavior**
In english versions, should be nicknamed "RICKY". Instead is given no nickname. This Machamp is the only one available at level 5 without the use of glitches or cheating devices, and serves as a notable example due to this. None of the other Generation I in-game trades have nicknames set either as far as I can tell

**Comment by kwsch** [comment]
Gen1 In-Game Trade Nicknames are not implemented.

https://bulbapedia.bulbagarden.net/wiki/User:SnorlaxMonster/In-game_trades_in_other_languages#Nicknames

**Comment by kwsch** [comment]
Implemented by latest commit https://github.com/kwsch/PKHeX/commit/37782f0ce4248e7a2417419f8f90ad4e21775dcc
