### ISSUE TITLE
Gen3 Sav Unsupported

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#304]
![save error](https://cloud.githubusercontent.com/assets/12572974/19052901/93778086-8986-11e6-8da4-90da36bd39ae.JPG)
Attempting to open any sav file from Visual Boy Advance for Ruby/Sapphire/FireRed/LeafGreen/Emerald

I've tried both 64k and 128k save types and all give that same error.

not sure if using a different emulator will produce the same errors, or if different emulator settings might fix the sav not being read...

**Comment by kwsch** [comment]
Quite possible that the save file is not fully initialized, how far progressed is the story?

https://github.com/kwsch/PKHeX/blob/master/PKHeX/Saves/SaveUtil.cs#L220-L221

**Comment by Ninjistix** [comment]
collected first starter in each game, attempted to export starters but couldn't read the sav

**Comment by Ninjistix** [comment]
i restarted all of the games and collected the starters, again, not sure why it didnt work the first time

**Comment by Ninjistix** [comment]
okay for some reason it only worked on emerald...

**Comment by Ninjistix** [comment]
Here are the Sav files for the 4 games
[Saves in Question.zip](https://github.com/kwsch/PKHeX/files/507224/Saves.in.Question.zip)

**Comment by ricksee** [comment]
@Ninjistix I also have a similar problem with Gen 3. My Emerald works but Firered/LeafGreen doesn't.

**Comment by ricksee** [comment]
@kwsch It might be the program that I used to extract the saves.

**Comment by ricksee** [comment]
For FireRed, I completed the game and it didn't work.

**Comment by Ninjistix** [comment]
my saves were created by visual boy advance, ill try my gateway flash card later and see if those saves work

**Comment by ricksee** [comment]
Mine were used by GBA Backup Tool using Action Replay DSi.

**Comment by Ninjistix** [comment]
thanks @kwsch
