### ISSUE TITLE
Birth Island Deoxys falsely flagged as legal with JPN language from Emerald version

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3040]
**Describe the problem**
The Aurora Ticket event was never available for Japanese Emerald version, therefore the only legal Gen 3 JPN Deoxys can be met on JPN FireRed/LeafGreen's version of Birth Island. PKHeX currently flags JPN language Birth Island (Emerald) Deoxys as legal, despite being an encounter from an unreleased event.

**To Reproduce**
PK3 files provided below:
[JPN Birth Island Deoxys Examples.zip](https://github.com/kwsch/PKHeX/files/5420525/JPN.Birth.Island.Deoxys.Examples.zip)

**Expected behavior**
JPN language and Birth Island (E) Deoxys are mutually exclusive.

JPN Deoxys should be flagged illegal if origin game is Emerald/Met Location is Birth Island (E), as it's an unreleased event.

JPN Deoxys should still be legal from FireRed/LeafGreen and Birth Island (FRLG).

**Additional context**
Project Pokemon Gen 3 Event Research thread quote, (Thank you @PP-theSLAYER and Sabresite):
https://projectpokemon.org/home/forums/topic/39327-gen-iii-event-contribution-thread/?do=findComment&comment=237416

"The Japanese Aurora Ticket was only distributed in Summer 2004, before Emerald (Sept 16th 2004) was released. The software at that time had no support for Emerald games."

**Comment by kwsch** [comment]
Does this also imply that non-Japanese from Emerald are illegal as well?

**Comment by Atrius97** [comment]
I don't believe so. There was English/European versions of the event released for Emerald & FRLG later on (incompatible with JPN Emerald), but the Japanese version of the Emerald Aurora Ticket appears to have been exclusively released for FireRed and LeafGreen prior to Emerald's release and never redistributed. 

Project Pokémon's event catalog has records of other language versions of the Aurora Ticket that are compatible with Emerald, but as far as they're aware, JPN Emerald Aurora Ticket is unreleased.
