### ISSUE TITLE
Galarian Birds Met Location Legality

### ISSUE THREAD

**Issue by crzyc** [kwsch/PKHeX#3042]
**Describe the problem**
This is likely not limited to Galarian Zapdos, as all three are roaming pokemon, but Zapdos was the only one that showed up as illegal in PKHeX.

**To Reproduce**
[Galar Zapdos.zip](https://github.com/kwsch/PKHeX/files/5433663/Galar.Zapdos.zip)

**Expected behavior**
Should appear as legal.

**Screenshots**

**Additional context**
Zapdos has weird pathfinding. I was able to catch up to it in the Watchtower Ruins and trigger the battle there.

**Comment by kwsch** [comment]
They show up in multiple met locations, and we didn't have enough time to document each possible zone :D

**Comment by kwsch** [comment]
Resolved by #3044
