### ISSUE TITLE
Request: Dynamax Adventure Settings

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#3046]
Generations Impacted: Gen 8
Games Impacted: Sword & Shield
Versions Impacted: v.1.3.0+

I would like to request a new section (in the form of a button under the "SAV" tab) be added to loading Sword & Shield saves. I would like to ask for a "Dynamax Adventures" (with the button being Adventures.)

There are two vital pieces of data which belong easily accessible outside of block data (like Raids are) for users in regards to the new Dynamax Adventures feature:

1.) Max Lair Saved Legendaries
The games now have 3 save slots for the names/IDs of 3 Legendary Pokémon. These save slots are used for a player to re-host a Dynamax Adventure ending in that specific Legendary Pokémon until they capture and keep said Legendary OR they overwrite of their 3 save slots with another Legendary Pokémon.

I was able to confirm that the ONLY data stored is Legendary Pokémon:

- It's been made public that the stats are generated dynamically
- From 25 back-to-back SOLO Raids, I confirmed the Pathway data is SEPARATE from the Legendary Pokémon. It doesn't matter which of the 4 Legendary you choose (3 saved or next in line), the generated Pathway will be always the same.
- The Pathway consists Rental Pokémon available at the start and throughout, the joining NPCs required, the choices the NPC's make between battles, the items/NPCs between battles and were they are on the map, and all the Pokémon that appear on the map and which slot they appear in.

A dropdown including the option for "None" for each of the 3 Legendary Pokémon would be awesome here!

2.) Event Flags for Dynamax Adventures Legendary Pokémon
The information available to the public currently is that each Legendary Pokémon can only be caught once per Host per save file. This would suggest there are event flags for all the Legendary Pokémon in the Dynamax Adventures.

It goes without saying that re-battles by removing the flag and adding flags to prevent encounters would be very handy.

3.) Max Lair Failed Attempts (an Optional Extra)
I discovered the game stores the amount of times (or times in a row) you have failed a Pathway. The lady will charge you a re-entry fee if it hits 3 fails in a row (I believe it is.) The option to reset this to 0 would be the only use here.

I imagine there's a HUGE chance you are already working on this so thanks in advance, sorry to bother, and no rush! YOU ALL ARE DOING AMAZING!

**Comment by kwsch** [comment]
You can already edit these via the Block Editor.

Dump the ROM, and dump the AHTB list with pkNX. Rename the {key}\t{value} text file to SCBlocks and put it next to PKHeX, and the vast majority of blocks will be labeled.

1.
```
83ED55156F669A35	WK_EV_R2_CHIKA_LEGEND_SAVE_01
83ED52156F66951C	WK_EV_R2_CHIKA_LEGEND_SAVE_02
83ED53156F6696CF	WK_EV_R2_CHIKA_LEGEND_SAVE_03
```
2.
```
DCA344BDF75E5635	FSYS_CHIKA_LEGEND_01
DCA341BDF75E511C	FSYS_CHIKA_LEGEND_02
DCA342BDF75E52CF	FSYS_CHIKA_LEGEND_03
DCA33FBDF75E4DB6	FSYS_CHIKA_LEGEND_04
DCA340BDF75E4F69	FSYS_CHIKA_LEGEND_05
DCA33DBDF75E4A50	FSYS_CHIKA_LEGEND_06
DCA33EBDF75E4C03	FSYS_CHIKA_LEGEND_07
DCA34BBDF75E621A	FSYS_CHIKA_LEGEND_08
DCA34CBDF75E63CD	FSYS_CHIKA_LEGEND_09
DCA649BDF760948B	FSYS_CHIKA_LEGEND_10
DCA648BDF76092D8	FSYS_CHIKA_LEGEND_11
DCA64BBDF76097F1	FSYS_CHIKA_LEGEND_12
DCA64ABDF760963E	FSYS_CHIKA_LEGEND_13
DCA64DBDF7609B57	FSYS_CHIKA_LEGEND_14
DCA64CBDF76099A4	FSYS_CHIKA_LEGEND_15
DCA64FBDF7609EBD	FSYS_CHIKA_LEGEND_16
DCA64EBDF7609D0A	FSYS_CHIKA_LEGEND_17
DCA641BDF76086F3	FSYS_CHIKA_LEGEND_18
DCA640BDF7608540	FSYS_CHIKA_LEGEND_19
DC9C37BDF7582170	FSYS_CHIKA_LEGEND_20
DC9C38BDF7582323	FSYS_CHIKA_LEGEND_21
DC9C39BDF75824D6	FSYS_CHIKA_LEGEND_22
DC9C3ABDF7582689	FSYS_CHIKA_LEGEND_23
DC9C3BBDF758283C	FSYS_CHIKA_LEGEND_24
DC9C3CBDF75829EF	FSYS_CHIKA_LEGEND_25
DC9C3DBDF7582BA2	FSYS_CHIKA_LEGEND_26
DC9C3EBDF7582D55	FSYS_CHIKA_LEGEND_27
DC9C3FBDF7582F08	FSYS_CHIKA_LEGEND_28
DC9C40BDF75830BB	FSYS_CHIKA_LEGEND_29
DC9FBDBDF75B3AF9	FSYS_CHIKA_LEGEND_30
DC9FBCBDF75B3946	FSYS_CHIKA_LEGEND_31
DC9FBBBDF75B3793	FSYS_CHIKA_LEGEND_32
DC9FBABDF75B35E0	FSYS_CHIKA_LEGEND_33
DC9FC1BDF75B41C5	FSYS_CHIKA_LEGEND_34
DC9FC0BDF75B4012	FSYS_CHIKA_LEGEND_35
DC9FBFBDF75B3E5F	FSYS_CHIKA_LEGEND_36
DC9FBEBDF75B3CAC	FSYS_CHIKA_LEGEND_37
DC9FC5BDF75B4891	FSYS_CHIKA_LEGEND_38
DC9FC4BDF75B46DE	FSYS_CHIKA_LEGEND_39
DCB0BBBDF769AAC6	FSYS_CHIKA_LEGEND_40
DCB0BCBDF769AC79	FSYS_CHIKA_LEGEND_41
DCB0B9BDF769A760	FSYS_CHIKA_LEGEND_42
DCB0BABDF769A913	FSYS_CHIKA_LEGEND_43
DCB0BFBDF769B192	FSYS_CHIKA_LEGEND_44
DCB0C0BDF769B345	FSYS_CHIKA_LEGEND_45
DCB0BDBDF769AE2C	FSYS_CHIKA_LEGEND_46
DCB0BEBDF769AFDF	FSYS_CHIKA_LEGEND_47
DCB0C3BDF769B85E	FSYS_CHIKA_LEGEND_48
```

3.
```
15C4305D8EAEB8FF	WK_EV_R2_CHIKA_PENALTY
```

**Comment by Th3Alic3** [comment]
Hello @kwsch,

I came over from ProjectPokémon forums & as a basic PKHeX user the response you provide is a bit over my head.

I believe the left column of values is an ID for the BLOCK DATA however I am only familiar with seeing 8 digit values in PKHeX (from pasting Promoted Raid Data into my save.)

The event flags seem to range (based upon the 1st 6 digits) of: DC9C37 to DCB0C3. You stated: 
"The block list is not included because: internal names from ROM (not localized), and it's a huge file."

I assume that means the range of DC9C37 to DCB0C3 respresents a lot of data based upon that response. However, I also understand that to mean those Blocks are not currently in PKHeX. So, even if I used PKNX (I do not) and knew what the "AHTB list" & "SCBlocks" were I do not know how to add information to PKHeX Block Data without the IDs being in the list.

For less savvy users such as myself, will we see the "block list included" when the "internal names are localized"? Is there plans to make it as easy as it is for Gen 7 Wormhole Legendary Pokémon?

Thanks for your time!

**Comment by kwsch** [comment]
> will we see the "block list included" when the "internal names are localized"?

No, there are 68,000 different key-value-pairs that could be localized, greater than 2.8MB of text, for each language.

The block listing has tons more flexibility, without being hardcoded.

Only the lowest 8 bytes of the hash are used. Just use the rightmost 8 digits and you'll see these flags in the block editor.

For the first legendary flag: `DCA344BDF75E5635`, without the SCBlocks.txt...
![image](https://user-images.githubusercontent.com/6393368/97097424-70fe8580-162d-11eb-9265-60c077291c43.png)

**Comment by Th3Alic3** [comment]
I reviewed the range:

F7582170 - 4986 Bool
F769B85E - 5036 Bool

The Bool no. 5015 and 5016 are skipped with results in a total of 49 Bool in this range. All 48 of the Block Keys as provided above exist as Bools within this range.

The extra Bool is no.5017:
![image](https://user-images.githubusercontent.com/57371173/97098303-ae1c4500-1638-11eb-9e5f-d973552ec22d.png)

F7605C0C - 5017 Bool is the only Bool within this range that is BOTH not on this list and displaying "Bool2"

![image](https://user-images.githubusercontent.com/57371173/97098067-16b5f280-1636-11eb-914f-9f02eee1205e.png)

Finally, in the save that I have loaded: there are 0 caught Legendary Pokémon.

So, if I am understanding this correctly:
- Bool no.5017 is not a Pokémon Flag
- Bool1 = Uncaught/Can Be Caught

I should be good from here.

Thanks a million!


_(Is Bool no.5017 the flag to allow Ultra Beasts in the Dynamax Adventures?)_

**Comment by Th3Alic3** [comment]
I reviewed the values stored for these 3 Block entries and they were indeed the decimal values of the PokéDex numbers of the Legendary Pokémon:

> ```
> 83ED55156F669A35	WK_EV_R2_CHIKA_LEGEND_SAVE_01
> 83ED52156F66951C	WK_EV_R2_CHIKA_LEGEND_SAVE_02
> 83ED53156F6696CF	WK_EV_R2_CHIKA_LEGEND_SAVE_03
> ```

**Comment by Th3Alic3** [comment]
At this point, I have caught 14 of the Dynamax Adventure Legendary Pokémon.

When the data is re-sorted back into GameFreak's order, it becomes crystal clear that the list is JUST in PokéDex order:
![image](https://user-images.githubusercontent.com/57371173/97140331-95379080-1719-11eb-82b5-7c5521c11b3a.png)

**Comment by kwsch** [comment]
Refer to pkNX dumping of the dynamax adventures data. Index 46 is unused, but the order is roughly by species ID.
