### ISSUE TITLE
FireRed Party Box Blank/Red

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#305]
In reference to #304 I compiled the newest version but when I load the sav (FireRed) my party box looks like this
![party box error](https://cloud.githubusercontent.com/assets/12572974/19064264/3144ee4a-89da-11e6-8ccf-5209d9d20c13.JPG)

Noticed a diff when opening Leaf Green
First Prompt
![first prompt](https://cloud.githubusercontent.com/assets/12572974/19064305/837d2ce0-89da-11e6-9a83-2251155f26f4.JPG)
Second Prompt
![second prompt](https://cloud.githubusercontent.com/assets/12572974/19064322/9cb2710c-89da-11e6-8668-66e9a6387d0c.JPG)

FireRed Sav offers no second prompt.

Ruby/Sapphire/LeafGreen work, its just FireRed

**Comment by Ninjistix** [comment]
forgot to add that the save type is 128k, but for some reason all 64k show up that way by default, I also tried to delete and recreate the sav multiple times and got the same results.

**Comment by kwsch** [comment]
Please send the specific save file.

Looks like it is defaulting back to R/S (based off the program's title); the one you sent has a playtime of 00:02:45

**Comment by Ninjistix** [comment]
here's the game file... ill try to run a few more mins and see if it can open it
[Pokemon - Fire Red.zip](https://github.com/kwsch/PKHeX/files/509826/Pokemon.-.Fire.Red.zip)

**Comment by Ninjistix** [comment]
yeah, the time seemed to be the issue, used speed and ran game time upto 7mins.. and it let me open gave me both prompts

**Comment by Ninjistix** [comment]
i think the game time was too low... so ill close this... xD

**Comment by Ninjistix** [comment]
thanks @kwsch
