### ISSUE TITLE
Gen 1 and 2 low level Gyarados with RB Level 1 moves seen as illegal

### ISSUE THREAD

**Issue by MrPerson0** [kwsch/PKHeX#3054]
**Describe the problem**
In Red and Blue, Gyarados learns Bite, Leer, and Hydro Pump at level 1. Since the only way to obtain a low level Gyarados is in Yellow or GSC, these moves wouldn't normally be obtainable. However, if you trade the low level Gyarados to Red/Blue, and complete Stadium 2's Gym Leader Castle 

**To Reproduce**
Just grab a level 15 Gyarados from Yellow or GSC and try to teach it one of the three mentioned moves.

**Expected behavior**
Any of the three mentioned moves would be seen as legal in any Gen 1 or 2 game. However, the catch rate cannot be the original value (45) since it can only learn these moves when loaded through Stadium 2. Because of this, these moves are only valid in GB versions of Gen 1 and 2, not VC versions.

**Screenshots**
Screenshot of a RB low level Gyarados using the Move Relearner: 

![image](https://user-images.githubusercontent.com/26208088/97206304-e9c92300-178e-11eb-892e-fbbdf7feefd8.png)

Screenshot showing that Stadium 2 Move Relearner can be used as many times as you want (need to beat Elite Four for each use):

![image](https://user-images.githubusercontent.com/26208088/97206937-c357b780-178f-11eb-9124-fc37b5fef769.png)

Video showing the process of teaching one move to Gyarados:

https://www.youtube.com/watch?v=FvaAYd728a4

**Additional context**
Not sure if this affects other fully evolved Pokemon that can be obtained at a low level in other games as well. For example, in Gen 1, according to Bulbapedia, Persian has Screech as a level 1 move, but a level 19 Persian caught Silver is unable to learn it:

![image](https://user-images.githubusercontent.com/26208088/97209865-36aef880-1793-11eb-9f32-99b57f17dd24.png)

Which makes me think this only affects Gyarados due to its unique situation with its Red/Blue learnset.

**Comment by kwsch** [comment]
Can you try to get a few more examples of this? Feels kinda weird that it'd only affect Gyarados; programming an edge case is fine but this mechanic is still kinda foggy.

**Comment by MrPerson0** [comment]
Tried it with a list sent to me. Here are an album of the relearn moves: https://imgur.com/a/6bhykcA

Here is the list itself: 

Nidoking below level 23 relearn Thrash
**Clefable below level 19 relearn Minimize**
Level 15 Kadabra and Alakazam relearn Disable
**Level 14 Rapidash (Ingame trade) relearn Stomp**
**Muk below level 38 relearn Disable**
**Level 15 Haunter and Gengar relearn Confuse Ray**
Level 14 Marowak relearn Focus Energy (RB only)
**Level 16 Weezing relearn Sludge**
**Jolteon below level 16 relearn Thundershock**
**Flareon below level 16 relearn Ember**
**Porygon below level 18 relearn Sharpen**
Level 10 Dragonair relearn Agility

The ones in bold were able to learn the moves through the Move Relearner in Stadium 2. Don't know why some Pokemon can relearn these early moves while others cannot. Also, in the case of Kadabra and Alakazam, Alakazam has Confusion as a relearn move at level 15 though Kadabra oddly doesn't.

**Comment by kwsch** [comment]
It's probably related to the Stadium's internal ROM data. There might be differences compared to the actual mainline ROM games.

http://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Stadium:ROM_map#Moves_Legality_Checker

http://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Stadium:ROM_map#Pok.C3.A9mon_Base_data

http://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Stadium:ROM_map#Moves_Legality_arrays

They probably check these legality arrays prior to offering the moves to relearn; I assume there's bound to be some inconsistencies as you've already listed some above. They have two legality tables; one for RB and one for YW.

**Comment by kwsch** [comment]
With @ShadowMario3 we were able to see how Stadium1 recognizes Dragon Rage gyarados as legal (as it's in its Initial Moves); there isn't enough of a disassembly for Stadium 2 to indicate how it's determining the availability of moves. Seems like this is not sourced from the mainline ROMs, rather it's hardcoded into the n64 game.

**Comment by kwsch** [comment]
Looks like pret has a pending PR where someone identified some move legality checking logic, but for Stadium 1 :(

https://github.com/pret/pokestadium/pull/12/files

I'm probably gonna close this issue later since it's a GB-Era quirk and it's not really community documented.
