### ISSUE TITLE
A problem about assembly

### ISSUE THREAD

**Issue by ydgeud** [kwsch/PKHeX#3056]
I got the geteggmoves method with reflection getmethod, but the Assembly failed because there were two methods with the same name. Then the overload method of getmethod is used to increase the judgment of parameter type. However, the obtained method is null. So how do I get this method, or do you change the second geteggmoves method into private or internal？

![C2ED200E93D3A79397FDB04FA9761957](https://user-images.githubusercontent.com/73515761/97262284-822cd980-185b-11eb-9edf-e232576e05e2.png)

**Comment by kwsch** [comment]
Not sure what purpose you're using it for, but the class could be changed from internal to public so that you can call the method directly.
