### ISSUE TITLE
Please Linux!!

### ISSUE THREAD

**Issue by orangemn6** [kwsch/PKHeX#3059]
**Is your feature request related to a problem? Please describe.**
It does not work with wine or mono when I try to run it.
**Describe the solution you'd like**
I want a straightforward way to run pkhex on linux without wine

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
PKSM, but those pokemon cannot be traded
**Additional context**

**Comment by ReignOfComputer** [comment]
Eeenope. PKHeX is made in WinForms, which is Windows only.

Want it to run on Linux natively? Some developer will have to take that up. No small task there (though perhaps easier with PKHeX.Core having a .NET Core cross-platform variant?).

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2830#issuecomment-626392125

**Comment by orangemn6** [comment]
https://github.com/RazZziel/PortableLinuxGames/wiki/Creating-appimages-from-windows-applications

**Comment by orangemn6** [comment]
[FOund this, but I dont have enough storage]https://github.com/RazZziel/PortableLinuxGames/wiki/Creating-appimages-from-windows-applications)

**Comment by DevYukine** [comment]
i don't think you read the linked issue correctly, the owner and maintainer of this repo is not interested in moving to another GUI framework and Windows forms only works on windows so you can try to run it with mono or something yourself but don't expect native support.
