### ISSUE TITLE
Char stuck on Black Map/Screen.

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#306]
not sure if this is an open or past issue, but when modifying the pokemon party for Diamond and loading game char gets stuck on black map/screen, was able to fix the problem by going into options and exiting back. since I fixed the problem wasn't able to take a screenshot, will see if I can start a new game replicate the issue later for screenshot.

**Comment by Ninjistix** [comment]
![black map](https://cloud.githubusercontent.com/assets/12572974/19086751/668159e6-8a3d-11e6-833d-c8c4ade7f67d.JPG)
was able to duplicate the problem on Pearl too.

**Comment by kwsch** [comment]
Based on my past emulation experience, the game unloads the map when a fullscreen menu is opened, then re-loads the map.

Maybe you edited some trainer info (read->write not 1:1), as the Party region shouldn't be overflowing into that data.
