### ISSUE TITLE
.Ribbons=$suggest doesn't toggle Toughness Master and Contest Star ribbons.

### ISSUE THREAD

**Issue by ivanlonel** [kwsch/PKHeX#3061]
**Describe the bug**
When I use .Ribbons=$suggest in the batch editor for pokémon that can have all contest ribbons, it only toggles 4 of them, leaving Toughness Master off (and Contest Star, probably as a consequence).

**To Reproduce**
1 - Open any pokémon from XY or ORAS from the Encounter Database or Mistery Gift Database in PKHeX
2 - Either shift-click "Give All" in the Ribbon Editor or put it in a box and run Batch Editor with .Ribbons=$suggest
3 - Open Ribbon Editor and it should have Beauty Master, Cleverness Master, Coolness Master and Cuteness Master (among other unrelated ribbons), but no Toughness Master and no Contest Star.

**Expected behavior**
The pokémon should be given all 6 contest-related ribbons, as it's a valid condition within the games.

**Additional context**
I'm using the latest stable versions of PKHeX and the plugins (20.10.24) on Windows 10.

**Comment by kwsch** [comment]
Try to manually add one individually and see why.

Having all ribbons contest types requires the master ribbon, and having the master ribbon requires all the contest types. Since the ribbon applicator only does one ribbon at a time, it does not handle the dual requirement.

**Comment by Atrius97** [comment]
> =RibbonMasterBeauty=True
> =RibbonMasterCleverness=True
> =RibbonMasterCoolness=True
> =RibbonMasterCuteness=True
> .RibbonMasterToughness=True
> .RibbonContestStar=True

The above batch editor command can be used to apply both remaining Ribbons after running ".Ribbons=$suggest". 
(Including a filter to ensure the other ribbons are present/is eligible for ORAS Contest Ribbons)

**Comment by ivanlonel** [comment]
I've already been using `.RibbonMasterToughness=True` and `.RibbonContestStar=True` after `.Ribbons=$suggest` when editing mons from gen 6 and earlier (mostly from events).

Still, this new fix should save a lot of future mons from having an incomplete set of ribbons going unnoticed. :)

Thanks a lot both you guys!
