### ISSUE TITLE
About XD Shiny

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3062]
I calculated the square shiny PID of dragonite from XD through PokeFinder or RNGReporter, but PKHeX always shows illegal.
And I calculated the unshiny PID of the dragonite can be displayed legal.
And I want to know how to calculate a legal square shiny PID of XD version pkmn. Maybe PokeFinder and RNGReporter have different algorithms for XD. I don’t know exactly what data the PID in XD matches.
Could you help me out?

**Comment by kwsch** [comment]
Shadow Team locks are required to match.

**Comment by CScorpion-h** [comment]
> Shadow Team locks are required to match.

What's the meaning? How to match what you said? Is it in Extra Bytes? 
I havent't played XD, and I don't know what is the shadow ID? I don't understand what the locks means.
I just randomized the PID, and I found that 0x2A and 0x2B had changed. Is there a relation between them?

**Comment by kwsch** [comment]
Shadow Pokémon are sometimes generated after the rest of the team has been generated. The prior teammates have restrictions, which if you reverse calculate from a shadow pokemon, must be satisfied.

0x28/9/A/B is the PID for a `XK3`.
https://github.com/kwsch/PKHeX/blob/a33120c93e2fc53d621935089ff2da6bfafd88c9/PKHeX.Core/PKM/XK3.cs#L69

**Comment by CScorpion-h** [comment]
OK, I'll read it. Thanks.

**Comment by MrPerson0** [comment]
Another thing is I'm pretty sure Shadow Pokemon in XD can't be shiny no matter what, which is why PKHeX will see them as illegal.
