### ISSUE TITLE
Gen 6 Weezing has non relearnable moves in Gen 8

### ISSUE THREAD

**Issue by thuanle123** [kwsch/PKHeX#3063]
**Describe the bug**
A LEGIT Weezing Origin from Gen 6 when import to Gen 8 has illegal moves (the weezing took a stop in gen 7 first). The screenshot has a weezing completely pass legality check, and in Gen 8 it has the errors in the screenshot

**To Reproduce**
Make a normal Weezing with Curse, Pain Split, Stockpile - it will be illegal
Turn it to a koffing - the egg moves are legal
Turn it into galar-weezing - the egg moves are legal

**Expected behavior**
There should be nothing wrong with the weezing

**Screenshots**
https://i.imgur.com/n5iLZRs.png

**Comment by kwsch** [comment]
Works fine on latest commit.
https://github.com/kwsch/PKHeX/commit/b492d93f39891b1126d4916e7a4888ea26f1e467
