### ISSUE TITLE
Possible legality issue with gen 6+

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3066]
Hi, I was just looking over my save files to see if any legality issues have come up. I noticed that one of my vivillon forms was marked as illegal. I got this pokemon over the GTS a long time ago and I have no reason to believe that it is hacked from the information on it. It also wasn't labeled as illegal until very recently. Ill include the file so you can see. It also effects gen 6+ Thanks again.

[666-16 - Vivillon - 59D12C01810F.zip](https://github.com/kwsch/PKHeX/files/5468522/666-16.-.Vivillon.-.59D12C01810F.zip)

**Comment by ReignOfComputer** [comment]
Can confirm. Encounter seems to be a valid Friend Safari encounter, and becomes Legal in PKHeX once the form is changed to Icy Snow. My June build of PKHeX marks this as Legal, so the form identification must have changed somewhere along the way.
