### ISSUE TITLE
Problem with transferring pokemon between gens

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3067]
Hi, I was trying to view some pokemon that I caught in a lower gen than the save file I was viewing the pokemon in, and when you drag a pokemon from a lower gen directly into the viewing box for a later gen, it does not set the "latest (not OT) Handler". When I drag the pokemon into the PC boxes of a later gen it correctly sets the "latest (not OT) Handler". So the main problem is that PKHeX does not set this parameter when dragging directly into the view tab resulting in an illegal pokemon while viewing it. Thanks again

**Comment by kwsch** [comment]
Correct, because it hasn't been set to the savefile yet.

The program converts it to the destination format, but if it doesn't get set to a save file, then it doesn't know what save data to apply.
