### ISSUE TITLE
Add random height and weight generator to PKHeX

### ISSUE THREAD

**Issue by ESarem97** [kwsch/PKHeX#3068]
**Is your feature request related to a problem? Please describe.**
Encounter table Pokemon do not have a random height and weight assigned to them, thus making them not appear legit.

**Describe the solution you'd like**
Add a random height and weight generator, either as a button for the current Pokemon or assigned to an encountered Pokemon when selected in the Encounter database.

**Describe alternatives you've considered**
While there is an application created to randomly generate Height and Weight, not everyone can or wants to download a separate application.

**Additional context**
All encounter table Pokemon have 0 height and weight, but all Pokemon obtained legitimately have a random height and weight assigned to them.

**Comment by kwsch** [comment]
They're entirely legal with 0 for both Height & Weight.

Sure, it's statistically low, but still legal.

**Comment by Legends77yt** [comment]
Id you don't mind me asking, where can i find the previously mentioned application that does this for you?

**Comment by ESarem97** [comment]
Thanks for telling me they're entirely legal with 0 for both Height and Weight @kwsch, even if it's statistically low... I just wanted to check.
@Legends77yt , the application that randomly generates height and weight is downloadable at this link. 
https://projectpokemon.org/home/files/file/4303-random-tidsid-heightweight-generator/
