### ISSUE TITLE
Please make the path to the pkmdb database configureable?

### ISSUE THREAD

**Issue by headhunter45** [kwsch/PKHeX#3075]
### Context
My main use case is I have two folders on my desktop PKHeX and PKHeXOnlyMine. The first is every pokemon I've ever seen in a save. Some are probably illegitimate or illegal. The second is only pokemon I've caught or traded for in game. Currently I have a copy of PKHeX.exe in each folder and each folder has it's own pkmdb folder.

### The Features
* Let me set the path to the pkmdb folder. So I can have PKHeX in program files and my pkmdb in %Userprofile%\Documents\pkmdb
* Let me register multiple paths with different names
* Add a submenu such as Tools\Data\DB Path to let me select between registered db paths

**Comment by kwsch** [comment]
You can have multiple folders within the database folder, and can use Identifier contains in the advanced search filters to exclude/include folders.

**Comment by kwsch** [comment]
Keep in mind that save file backups are automatically included in the database; any Pokemon in a save file backup will show up in the list. You can toggle between the sources via options.
