### ISSUE TITLE
0 IV Speed Stakataka not being generated from sysbot

### ISSUE THREAD

**Issue by psongpin** [kwsch/PKHeX#3078]
**Describe the bug**
!trade or !convert command for stakataka on sysbot does not produce the correct pk8 or pokemon on trade. Always gets 4 best IV and 2 Hypertrained stats
```
Stakataka @ Shuca Berry  
Ability: Beast Boost  
Ball: Beast Ball
EVs: 252 HP / 252 Atk / 4 SpD  
Brave Nature  
IVs: 0 Spe  
- Gyro Ball  
- Trick Room  
- Body Press  
- Rock Slide
```

**Comment by Lusamine** [comment]
This is not the correct repository for your issue, and it's not an issue.
Gen 8 Max Lair uses Xoroshiro to generate IVs, which means you're likely not going to get the IVs you requested.
Target Gen 7 instead by using a move from gen 7 or a pk8.

**Comment by architdate** [comment]
Not a pkhex bug. Infact not a bug atall. The host has xoroshiro enabled. Ask them to disable it or use `=Gen7=true` as a regentemplate filter.

If it still doesn't work, open an issue on the PKHeX-Plugins repo

**Comment by psongpin** [comment]
Thank you  for answering my concern!

**Comment by psongpin** [comment]
@architdate @Lusamine what does the xoroshiro do? sorry I'm new to pkhex and stuff and I'm just messing with a bot in a discord server that I joined
