### ISSUE TITLE
Trainer name flagged as illegal by profanity filter

### ISSUE THREAD

**Issue by TrainerFromHoenn** [kwsch/PKHeX#3079]
**Describe the problem**
This is a legit squirtle caught in the game, and the trainer name has not been modified, it has been checked by the in game profanity filter and not been reported.

**To Reproduce**
PK8 file attached:
[007_-_Squirtle_-_D281169F1D72.zip](https://github.com/kwsch/PKHeX/files/5493933/007_-_Squirtle_-_D281169F1D72.zip)

**Expected behavior**
The game has not blocked the trainer name "Sobek" so it shouldn't be flagged as illegal.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/26364966/98234291-85f9e380-1f60-11eb-9cc5-3cf2cae150ff.png)

**Additional context**
Game Language is Italian

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1524
