### ISSUE TITLE
Shiny WISHMKR Jirachi from Sapphire are showing as illegal

### ISSUE THREAD

**Issue by JpDeathBlade** [kwsch/PKHeX#3082]
**Describe the bug**
AFAIK there are only 9 possible shiny WISHMKR Jirachi's. I generated a save file (attached below) with all 9 for Ruby and all 9 for Sapphire. In the latest version released 20/10/31 all 9 of the Sapphire Jirachi's are marked as illegal. Because the PID generation is the same between both games, these Pokemon should show as being legal.

**To Reproduce**
1. Create a WISHMKR Jirachi
2. Change it's Origin Game to Sapphire

[main.zip](https://github.com/kwsch/PKHeX/files/5500743/main.zip)

**Comment by kwsch** [comment]
The version is hard coded by the event disc. It's never receivable with a Sapphire version ID.
