### ISSUE TITLE
SIDs get reset to 0 when loading a .pk file

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#3087]
**Describe the bug**
When loading a .pk file, the SID of the loaded Pokemon gets reset to 0. I haven't tested it on other versions but it's happening to me on .pk8 on Pokemon that were transferred from HOME/Pokemon from Gen 7/8. I'm not exactly sure but I think the game origin has something to do with whether or not the SID gets reset.

**To Reproduce**
1. Load up a save file
2. Select a Pokemon and extract it as a .pk file
3. Reload the .pk file
4. The SID of the Pokemon will be set to 0.

**Expected behavior**
It should retain its original SID.

**Screenshots**
![2020-11-18 12_20_35](https://user-images.githubusercontent.com/25017422/99517993-b302b900-2998-11eb-9707-df0a9fa61059.png)
![2020-11-18 12_20_43](https://user-images.githubusercontent.com/25017422/99518000-b4cc7c80-2998-11eb-927f-c32cb3529e7e.png)
![2020-11-18 12_20_51](https://user-images.githubusercontent.com/25017422/99518012-b5fda980-2998-11eb-844b-6a61571c91ce.png)
![2020-11-18 12_20_59](https://user-images.githubusercontent.com/25017422/99518023-b7c76d00-2998-11eb-84a7-f246767de0c8.png)
![2020-11-18 12_21_02](https://user-images.githubusercontent.com/25017422/99518035-b9913080-2998-11eb-9c87-6a42dd93b219.png)

**Additional context**
This happened in the 3b66e2e commit. If your Pokemon's SID isn't being reset, then try it with this Magearna. Change it's SID to any number, then save it and reload it.
[801 - Magearna - A3EB261E1021.zip](https://github.com/kwsch/PKHeX/files/5559352/801.-.Magearna.-.A3EB261E1021.zip)

**Comment by AlamosIT** [comment]
I tried with this Magearna, but everything works fine.

I loaded you pk8, the SID was 0000, then I changed to 0301, I exported and reloaded pk8 and the SID was still 0301.

[801 - Magearna - 9996261E1021.zip](https://github.com/kwsch/PKHeX/files/5568390/801.-.Magearna.-.9996261E1021.zip)

**Comment by Araraura** [comment]
> I tried with this Magearna, but everything worked fine.
> 
> I loaded your pk8, the SID was 0000, then I changed to 0301, I exported and reloaded pk8 and the SID was still 0301.
> 
> [801 - Magearna - 9996261E1021.zip](https://github.com/kwsch/PKHeX/files/5568390/801.-.Magearna.-.9996261E1021.zip)

That's weird... apparently it's happening to someone else in the forums: https://projectpokemon.org/home/forums/topic/58159-sid-0000-bug-in-the-latest-development-build/
