### ISSUE TITLE
Get error while exported

### ISSUE THREAD

**Issue by Dalk2ness** [kwsch/PKHeX#3093]
![Screenshot_2020-11-22-22-07-53-98_523b8db31da625db78202bc5b2eb3aa2](https://user-images.githubusercontent.com/10178164/99907445-678d3980-2d0f-11eb-8c66-427a29def936.jpg)
![Screenshot_2020-11-22-22-07-57-68_523b8db31da625db78202bc5b2eb3aa2](https://user-images.githubusercontent.com/10178164/99907450-6bb95700-2d0f-11eb-8490-a15adae82d9b.jpg)
Cant export to save file please help

**Comment by kwsch** [comment]
This project does not run on Android.
