### ISSUE TITLE
Many Event Pokémon Incorrectly Labeled as Legal even though the Origin Game is Wrong

### ISSUE THREAD

**Issue by DestroyMagnet** [kwsch/PKHeX#3097]
An example is the Fall2010 Mew that was only available via Wifi to HGSS. I changed the origin game to Diamond and it says that it’s legal. This is a problem for lots of other event Pokémon too. Some Event Pokémon internal data can’t be “originated” with certain games and PKHEX doesn’t seem to recognize stuff like that. Some wrongfully made Event Pokémon may continue to circulate as if they are legal.
![B149096D-FBAE-49AE-974B-B60656011767](https://user-images.githubusercontent.com/52223223/100493920-267b9780-310a-11eb-8253-924f136d6053.png)

**Comment by ReignOfComputer** [comment]
Not really a bug, but more to do with the data source. IIRC the amount of work needed to mark out what Gen 4/5 Events can originate from which game is too substantial.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/1727

**Comment by Ammako** [comment]
Gen. 4 is different from Gen. 5+. Just read the version of origin from the wc4 when doing legality checks. This is different from #1727.
