### ISSUE TITLE
Virtual Console transfer OT legality

### ISSUE THREAD

**Issue by CarlosofKalos** [kwsch/PKHeX#3099]
**Describe the problem**
Hello!

While I was doing transfers from the Gen II Virtual Console games using the Poké Transporter app, I discovered that if you have a girl's OT on Pokémon in your save file's Box 1 in Gold or Silver and do an official transfer using the app, they become a boy's OT. This is retained if they are transferred from Crystal.

Another problem I should also mention while here is that a Pokémon with the Origin of Blue [JP] should only have the language as JPN to pass, because the Transporter follows the language of the Virtual Console game.

**To Reproduce**
This is the original:
[Original.zip](https://github.com/kwsch/PKHeX/files/5626083/Original.zip)

This is how it turned out when transferred from Gold (Changed to boy OT):
[Transferred from Gold.zip](https://github.com/kwsch/PKHeX/files/5626084/Transferred.from.Gold.zip)

This is how it turned out when transferred from Crystal (Retained girl OT):
[Transferred from Crystal.zip](https://github.com/kwsch/PKHeX/files/5626085/Transferred.from.Crystal.zip)

If you want to do it yourself:
1. Have one 3DS/2DS with Crystal playing as the girl character and another system with Gold/Silver.
2. Trade a Pokémon of her OT to the 3DS/2DS with the copy of Gold/Silver.
3. Place the Pokémon into Box 1.
4. Use Poké Transporter to transfer it into Bank then to preferably Sun, Moon, Ultra Sun, or Ultra Moon.
5. Open the save file of the game you placed them into in PKHeX to find your transferred Pokémon now got a boy OT.

If you don't have access to another 3DS/2DS, you can just import the girl player's PK2 into Box 1 of your Gold/Silver save file and transfer from there.

**Expected behavior**
What PKHeX should do is **make a PK7 or PK8 require a boy OT if the Origin is Gold or Silver when doing a legality check.**

**Additional context**
Yes, I know that if you trade a Pokémon of a girl player's OT from Crystal to Gold or Silver, the Pokémon will retain its girl OT. However, the **official** transferring app will only retain the girl OT if it pulls the Pokémon from a Crystal save file.

**Comment by kwsch** [comment]
PKHeX does not have VC savefile context when transferring a PK1/2 to a different game.

If there is data from Crystal (Met Data / Female Gender), it uses Crystal, otherwise Silver. This preserves as much data by picking the "optimal" trade game.

https://github.com/kwsch/PKHeX/blob/e54e94a734343f96d18deba7946a962e43ff4d50/PKHeX.Core/PKM/PK2.cs#L132-L144

**Comment by kwsch** [comment]
Coulda sworn there was a check for non-Crystal female OTs being flagged...
