### ISSUE TITLE
Adding Day Care-Couple as Default When "As an Egg" is Selected

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#310]
Is it possible to set "Day Care-Couple" as default when as an egg is selected. I think it would be convenient when making Pokemon as eggs since most eggs are from the day care couple. That is if you want of course.

**Comment by kwsch** [comment]
It already does this............?

**Comment by ricksee** [comment]
I don't think so. It doesn't apply to gen 5 that I know.

**Comment by ricksee** [comment]
It was (None) for instance Black 2.

**Comment by kwsch** [comment]
Unable to replicate.

**Comment by ricksee** [comment]
@kwsch I think it doesn't apply when the game file is open from a blank state or when you have a pokemon that wasn't an egg that was caught.

![2016-10-09_21-00-35](https://cloud.githubusercontent.com/assets/21182549/19225150/da52eb6c-8e63-11e6-929f-8cb44560fd71.png)
