### ISSUE TITLE
New gift pokemon file

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3101]
[113 - ラッキー - 1A4F451CA028.zip](https://github.com/kwsch/PKHeX/files/5640611/113.-.-.1A4F451CA028.zip)

**Comment by CScorpion-h** [comment]
Just lock trainerinfo.

**Comment by Lusamine** [comment]
Gen 8 Mystery Gift Wonder Cards are bundled with each stable release from the Event Database.  The Pokémon is unnecessary.
