### ISSUE TITLE
Bugged female Pikachu icon

### ISSUE THREAD

**Issue by AlamosIT** [kwsch/PKHeX#3102]
**Describe the bug**
Using old USUM icons female Pikachu looks like a male Pikachu with a question mark.
Probably the problem is that old PokéSprite database doesn't have female Pikachu, but new one has it.

**Screenshots**
![image](https://user-images.githubusercontent.com/62159869/101238919-d3927900-36e3-11eb-90cc-41317fe2d120.png)

**Additional context**
I know that old sprites will be removed one day, but until we have new sprites for every Pokémon a lot of people (like me) prefer to use old sprites in old games, it's more similar to original in-game experience.

If it could be useful, here there are normal and shiny female Pikachu sprites in USUM format (40x30).

[FemalePikachu.zip](https://github.com/kwsch/PKHeX/files/5646796/FemalePikachu.zip)

**Comment by kwsch** [comment]
Blame: #2966
