### ISSUE TITLE
Block Data: *UInt64 KMaxLairRentalChoiceSeed - unable to write intended value

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/PKHeX#3103]
Issue: Unable to update value of Block Data variable
Block Data variable: *UInt64 KMaxLairRentalChoiceSeed*UInt64 KMaxLairRentalChoiceSeed
Version: PKHeX 20.11.28

![image](https://user-images.githubusercontent.com/57371173/101432372-91249400-38bd-11eb-90ab-6c40d8f1f3b9.png)

The UInt64 same as every other one of the Raid SEED is stored in game as a 16 character/digit hexidecimal value.

PKHeX displays the stored value as a decimal value (converted from its native hexidecimal value.) The value within PKHeX is locked as a postive decimal value. This prevents users from editing the value with another hexidecimal SEED value:
![image](https://user-images.githubusercontent.com/57371173/101434740-fda09280-38bf-11eb-96bd-4acbbe1f0d30.png)

In addition to this, the restriction of a postive value prevents legal SEEDS from being entered. For example, the following SEED when converted to Decimal produces a negative value:

Hexidecimal: AECEF316882C9E83
equals
Decimal: -5850471587808239997

PKHeX prevents negative values from being entered:
![image](https://user-images.githubusercontent.com/57371173/101434685-de096a00-38bf-11eb-95a1-76c3be6fc736.png)

One cannot enter the same decimal value without the negative indicator because:

Decimal: 5850471587808239997
equals
Hexidecimal: 51310CE977D3617D
does not equal
Hexidecimal: AECEF316882C9E83

Would you please set this field to a HEXIDECIMAL value for display and editing? In addition to resolving the above concerns, this would make the feature more compatible with programs such as Capture Sight which displays these SEEDs in their native hexidecimal format.

Thanks

**Comment by kwsch** [comment]
Hexadecimal is not a [integral numeric type](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types); it is a way of representing values in base16 as opposed to base10.

The editor expects an unsigned 64 bit integer (base10).

Use the windows calculator if you must convert values. win-r => calc => alt-3 (or alt 4) for programmer mode, and you can toggle between hex/dec.

**Comment by Th3Alic3** [comment]
*cough*
![image](https://user-images.githubusercontent.com/57371173/101438563-87a02980-38c7-11eb-9485-fa7fd3c3a17b.png)

**Comment by kwsch** [comment]
There are many online converters ~ https://www.rapidtables.com/convert/number/hex-to-decimal.html

I checked in on windows calculator; they haven't formalized a sign toggle yet, sad.
