### ISSUE TITLE
Old gen transfer Pokémon not working properly

### ISSUE THREAD

**Issue by YoshivsJoshi** [kwsch/PKHeX#3104]
Pokemon from old older gens always come up with "invalid encounter type PID mismatch" this happens with all the Pokémon that I try and gen that are from older gens, I'll attach the files and if I'm doing something wrong I apologise but I don't think I am I've attached the files so you can see them for yourselves, thank you means I can use the Sysbot and get the Pokémon since they will always flag as illegal 
[Problem pokemon.zip](https://github.com/kwsch/PKHeX/files/5675848/Problem.pokemon.zip)

**Comment by kwsch** [comment]
This is not the place to ask why your hacks are being flagged as hacks.

Only report flagging errors on legitimate data, or lack of flags for impossible data.
