### ISSUE TITLE
Problem with Shiny Pokémon legality 

### ISSUE THREAD

**Issue by YoshivsJoshi** [kwsch/PKHeX#3105]
Hey, sorry I must've misspoken in my other post sorry, when you change Pokémon from regular to shiny it just says that "invalid Encounter type PID mismatch" I've attached the file that is legal and then I've attached the shiny version of that Pokémon that is illegal but I've refreshed the PID and made it shiny again but nothing changes, thank you, sorry for any confusion

[Heatran files.zip](https://github.com/kwsch/PKHeX/files/5676007/Heatran.files.zip)

**Comment by Lusamine** [comment]
Clicking shiny makes it illegal... Google the error to learn to fix it. Bad hacks are being flagged appropriately.

**Comment by YoshivsJoshi** [comment]
Thank you, appreciate it
