### ISSUE TITLE
Every Granbull and Flygon in 3rd gen are shown as illegal

### ISSUE THREAD

**Issue by AlamosIT** [kwsch/PKHeX#3108]
**Describe the bug**
In III gen games every Granbull and Flygon have illegal flag, but when check, PKHeX says "legal".

**To Reproduce**
Look Granbull or Flygon in a III gen game:
[Illegal Granbull and Flygon.zip](https://github.com/kwsch/PKHeX/files/5712132/Illegal.Granbull.and.Flygon.zip)

**Expected behavior**
PKHeX should flag them legal.

**Screenshots**

![image](https://user-images.githubusercontent.com/62159869/102543660-eaf23e80-40b3-11eb-8fbb-51cc6aa597b6.png)
![image](https://user-images.githubusercontent.com/62159869/102543688-f7769700-40b3-11eb-93ce-2f0598e1ff34.png)

**Comment by kwsch** [comment]
The PKM Editor portion of the editor fixes any issues when it is loaded to tabs; you can check legality directly from the slot by holding control when right clicking the slot.
