### ISSUE TITLE
Celebi and Deoxys from GO should be legal

### ISSUE THREAD

**Issue by albertodev01** [kwsch/PKHeX#3109]
**Describe the problem**
I have transferred a shiny celebi from Pokémon GO. It's (almost) all good because the legality checker says "_Unable to match an encounter from origin game_". I'm quite sure this happens just because PKHex's internal database hasn't been updated with Celebi's info.

The same issue also seem to happen with shiny deoxys from GO (event from August 2020).

**To Reproduce**
[celebi.pk8](albertomiola.com/celebi.pk8)

**Expected behavior**
I'd expect celebi to be flagged as "legal"

**Screenshots**
<img src="http://albertomiola.com/celebi.png" />

**Additional context**
If you also need the pk8 file of Deoxys I can get it but it's just a GO event like celebi!

**Comment by Lusamine** [comment]
GO Legality is updated separately (https://github.com/projectpokemon/PoGoEncTool) and bundled into each stable release.

**Comment by albertodev01** [comment]
Ok thank you, I can close this then

**Comment by sora10pls** [comment]
For the record, PKHeX will flag _all_ Deoxys in Sword & Shield because it's not in the games. Same reason why you won't find any in  any of the encounter databases for those games.
