### ISSUE TITLE
510 EV cap is enforced even in illegal mode

### ISSUE THREAD

**Issue by autofire372** [kwsch/PKHeX#311]
Running PKHeX in illegal mode currently does not allow one to ignore the 510 EV cap in R/S and newer. These games can handle Pokémon with more than 510 EVs without crashing or anything, so this strikes me as unnecessary.

**Comment by kwsch** [comment]
HackedStats has to be checked for obviously-hacked EVs.

**Comment by ricksee** [comment]
Can other generations such as gen 1-5 be in illegal mode.

**Comment by ricksee** [comment]
Because I tired doing it for gen 3 and tried to change ability. It made it turn to red and didn't drop down the abilities.

**Comment by kwsch** [comment]
Abilities are not stored in gen3 format, only ability number (0/1).

**Comment by ricksee** [comment]
Can they be edited by number? Does it apply to gens, 1,2,4, and 5 as well?

**Comment by kwsch** [comment]
Gen1/2: No abilities.
Gen3: Pokémon have two abilities, choose either ability0 or ability1.
Gen4+: Pokemon have multiple abilities, choose abilityID, not 0/1.

**Comment by ricksee** [comment]
@kwsch Let's say if I wanted to give a charizard wonder guard in gen 3. How can that be done?

**Comment by kwsch** [comment]
It's not possible.

**Comment by ricksee** [comment]
@kwsch Oh okay thanks.

**Comment by ricksee** [comment]
@kwsch Meaning that the abilities are set for the Pokemon assigned and care not independent?

**Comment by kwsch** [comment]
http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_data_substructures_in_Generation_III#IVs.2C_Egg.2C_and_Ability

You can have either of the two assigned abilities.
