### ISSUE TITLE
Batch editing nature in gen 3 does not work

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3114]
**Describe the bug**
If you go to the batch editor and use `.Nature=12` etc, it'll say all the Pokémon were modified, but none were. Nothing happens if you try to modify StatNature either. It also doesn't help if you select pk3 from the dropdown.

**To Reproduce**
1. Open batch editor
2. Try `.Nature=12`
3. All files modified
4. They were not modified

PID is not changed either. If you do this:
```
!Nature=12
.PID=$rand
```
It'll keep randomizing PIDs but the nature will not be randomized, it'll just stay as what it was.
So right now there's no way to change natures automatically with the batch editor.

**Comment by sora10pls** [comment]
Nature is derived from PID in Generations 3 and 4 (same with Gender), so you can't edit Nature without also modifying the PID (would likely make them illegal).

**Comment by Kermalis** [comment]
I'm aware, but that's not a concern, which is why I'm trying to do it. It works fine if you manually change the nature in the dropdown, so it should work in the batch editor

**Comment by kwsch** [comment]
The GUI has automated changes which force the value by calling PKX.GetRandomPID:

```cs
public static uint GetRandomPID(Random rnd, int species, int gender, int origin, int nature, int form, uint oldPID)
```

The batch editor is raw value get/set. Derived values cannot be set, because they are derived.

You can randomize the PID until you get 0 modified files.

**Comment by Kermalis** [comment]
Well I can't do that because the PID randomizing (in the batch editor) does not modify the nature, which is what I tried

**Comment by kwsch** [comment]
Nature in gen3&4 is calculated via %25.

You can try setting the PID to a fixed value, then try randomizing it. Keep in mind that gender too is derived from PID.

```cs

            else if (cmd.PropertyName == nameof(PKM.PID) && cmd.PropertyValue == CONST_RAND)
                pk.SetPIDGender(pk.Gender);

public void SetPIDGender(int gender)
        {
            var rnd = Util.Rand;
            do PID = PKX.GetRandomPID(rnd, Species, gender, Version, Nature, Form, PID);
            while (IsShiny);
            if (Format >= 6 && (Gen3 || Gen4 || Gen5))
                EncryptionConstant = PID;
```

**Comment by Ammako** [comment]
For Gen. 3 saves, `.PID=$rand` preserves nature by only picking PIDs that match each Pokémon's current nature. Is this intentional behavior?

**Comment by Kermalis** [comment]
I think everyone is misunderstanding the problem. I have a save of all breedable Pokémon in gen 3. Simply I want to change all of them to have a specific nature (Serious in this case)
Obviously since they're hatched from eggs they can have whatever IVs and nature they want. If they weren't or were non-breedable they wouldn't be legal, which I don't care about either, and is not the problem I'm having

I am not going to go around 350 manual changes even though the UI does literally what I want if you change the nature in the dropdown. Hence I go to the batch editor which should solve all of my automation needs, which is how I found the problem. I feel like I should be able to set the nature from there without having to go and compile C# code (given that you can automate nearly anything else there, I don't think this feels like entitlement either? It seems like a bug to me)

Instead I found the part of code kwsch previewed, and just replaced `Nature` with `12` so it doesn't keep the nature, which gave me what I wanted when I did `.PID=$rand`. If anyone else wanted to change natures from here, in gen 3 (and maybe 4) they would have to spend all of this time seeing the natures not being changed, go look up how to randomize PIDs (if they know it's tied to that), see that also does not work, then go into the code like I did. Again in my opinion, that's not a valid user experience when there's an automation tool that does 99% of the other attributes just fine

**Comment by Ammako** [comment]
> If anyone else wanted to change natures from here, in gen 3 (and maybe 4) they would have to spend all of this time seeing the natures not being changed, go look up how to randomize PIDs (if they know it's tied to that), see that also does not work, then go into the code like I did.

I don't think this is necessary:

- Set the nature to a desired nature on one of your Pokémon, copy the PID that gets generated from it
- Batch editor: `.PID=[your PID]` <-- this changes every Pokémon's nature to the desired nature

You can `.PID=$rand` afterwards if you want, so every Pokémon won't all have identical PIDs, but this will not fix PIDIV legality, so this is only a cosmetic change at best.
