### ISSUE TITLE
About Breeding.cs

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/PKHeX#3118]
`public static bool CanHatchAsEgg(int species, int form, GameVersion game)`
The return value of this method seems to never detect the form of Rotom.
I think `public static bool CanHatchAsEgg(int species, int form, int generation)` method can add the check according to the logic of the code

**Comment by kwsch** [comment]
```cs
            var gameInfo = GameData.GetPersonal(game);
            var entry = gameInfo.GetFormEntry(species, form);
            return form < entry.FormCount || (species == (int)Rotom && form <= 5);
```

It checks Rotom at the bottom though.

**Comment by CScorpion-h** [comment]
> ```cs
>             var gameInfo = GameData.GetPersonal(game);
>             var entry = gameInfo.GetFormEntry(species, form);
>             return form < entry.FormCount || (species == (int)Rotom && form <= 5);
> ```
> 
> It checks Rotom at the bottom though.

`form < entry.FormCount` is always true.

**Comment by kwsch** [comment]
> > ```cs
> >             var gameInfo = GameData.GetPersonal(game);
> >             var entry = gameInfo.GetFormEntry(species, form);
> >             return form < entry.FormCount || (species == (int)Rotom && form <= 5);
> > ```
> > 
> > 
> > It checks Rotom at the bottom though.
> 
> `form < entry.FormCount` is always true.

Not true; in DP's personal data, Rotom does not have any forms! (Platinum introduced forms for it).
https://github.com/kwsch/PKHeX/commit/4d3fd395e10bd655c82be918fa9e516748056001

**Comment by CScorpion-h** [comment]
> > > ```cs
> > >             var gameInfo = GameData.GetPersonal(game);
> > >             var entry = gameInfo.GetFormEntry(species, form);
> > >             return form < entry.FormCount || (species == (int)Rotom && form <= 5);
> > > ```
> > > 
> > > 
> > > It checks Rotom at the bottom though.
> > 
> > 
> > `form < entry.FormCount` is always true.
> 
> Not true; in DP's personal data, Rotom does not have any forms! (Platinum introduced forms for it). The form can be changed by trading it after hatching, hence the need for this extra-unusual check.
> [4d3fd39](https://github.com/kwsch/PKHeX/commit/4d3fd395e10bd655c82be918fa9e516748056001)

oh yeah, that's right. I forgot to say in Gen8.

**Comment by kwsch** [comment]
This logic in question is used to handle all generations besides generation 2. It only activates for DP Rotom.

**Comment by CScorpion-h** [comment]
> This logic in question is used to handle all generations besides generation 2. It only activates for DP Rotom.

Okay. `public static bool CanHatchAsEgg(int species, int form, int generation)`
According to the logic of this method, if the form is not 0, the following Pokémon will be detected, but Rotom with from not 0 will eventually return true.
The following are my test results:
![test](https://user-images.githubusercontent.com/64029159/103475058-e5e7fb80-4de4-11eb-8a80-b53368505c47.png)
test code:
![test1](https://user-images.githubusercontent.com/64029159/103475072-1039b900-4de5-11eb-842a-b16544c65170.png)

**Comment by kwsch** [comment]
Everything is already working fine; `FormVerifier` catches the impossible egg scenarios for forms:

https://github.com/kwsch/PKHeX/blob/916c70341acd4b16c8067bfdb8c136cef1e68bfb/PKHeX.Core/Legality/Verifiers/FormVerifier.cs#L160-L163

**Comment by CScorpion-h** [comment]
> Everything is already working fine; `FormVerifier` catches the impossible egg scenarios for forms:
> 
> https://github.com/kwsch/PKHeX/blob/916c70341acd4b16c8067bfdb8c136cef1e68bfb/PKHeX.Core/Legality/Verifiers/FormVerifier.cs#L160-L163

Yeah, I know that verifier is okay. I mean, `CanHatchAsEgg `in `Breeding `does not perform a check on Rotom, although it doesn't seem to be that important.
