### ISSUE TITLE
Latest update causes Curtis/Yancy in-game trades to be flagged as illegal

### ISSUE THREAD

**Issue by WonderSquid** [kwsch/PKHeX#3119]
**Describe the problem**
As of the latest update, the Curtis/Yancy in-game HA trades will now display an "Unable to match an encounter from origin game" error. This flag persists for both unedited Pokemon pulled directly from the encounter database, and for 100% legitimate Pokemon acquired normally from the Curtis/Yancy sidequest. 

**To Reproduce**
Load/view any Curtis/Yancy trade Pokemon, either generated via the encounter database, or through intended gameplay, in any recent build after 12/30. 

**Expected behavior**
The Pokemon in question are all legal and should not be flagged as such. In prior versions of PKHeX this wasn't an issue. 

**Screenshots**

![image](https://user-images.githubusercontent.com/30328976/103492545-4b41e980-4df1-11eb-8bf3-664f38c8a5f1.png)

![image](https://user-images.githubusercontent.com/30328976/103492533-3cf3cd80-4df1-11eb-8b5b-faa5b99f02cc.png)

**Additional context**

[pkm files.zip](https://github.com/kwsch/PKHeX/files/5762522/pkm.files.zip)

These are all the encounters being flagged. The Yancy ones were pulled from PKHeX's encounter database, and the Curtis ones were obtained completely legally in-game. They all give the same error regardless of how they're obtained, and the error persists across multiple generations if they are transferred up and through the stable and dev builds of PKHeX. 

I tested out some other in-game trades, both from B2W2 and other games, and to my knowledge these are the only ones that behave like this. 

Never done one of these before, will be happy to submit further information if needed.

**Comment by kwsch** [comment]
Thanks, I was working on updating that over the past day or so to ensure that all encounters are instantiated with a version.

The latest commit (https://github.com/kwsch/PKHeX/commit/33ad654be6ba0b7f939bd1f64a4aa054cc2110c7) now shows them legal! :)

![image](https://user-images.githubusercontent.com/6393368/103492987-905f1f00-4de3-11eb-8af0-06d451e78265.png)

Thanks for reporting!

**Comment by WonderSquid** [comment]
Wow, that was fast. Thank you so much!
