### ISSUE TITLE
Pokémon from Emerald's Safari Zone

### ISSUE THREAD

**Issue by brunoaugusto** [kwsch/PKHeX#3123]
My sister and I never bothered in editing save-files nor playing games "the hardcore way", but we had nothing to do last year for obvious reasons so we decided to play everything again.

Not sure how exactly we met PKHeX, but the possibility to adjust every single detail was very interesting (well, to me, at least), so I've been poking around along PokeFinder (2.5.4) to fix all the red flags present and for the most of them, it has been working perfectly, except for those from Safari Zone.

As I said, we never bothered with these things so, starting from the bottom of the line, meaning with an Emerald save-file and, as stated in the issue template, I'm attaching the PK3 of a flagged Doduo but worth to mention that so far none of the Safari encounters worked.

Also, the full error report:

[084 - DODUO - F763E58D1B25.zip](https://github.com/kwsch/PKHeX/files/5791237/084.-.DODUO.-.F763E58D1B25.zip) (zipped due to file-extension restrictions)

![report](https://user-images.githubusercontent.com/1514089/104093891-50c58680-526c-11eb-9752-3594880bc374.png)

Not sure if it's worth anything but while writing this issue I had the idea of reconfiguring the application so a blank save would be one of the later games and opening this PK3 after doing so, was just a matter of adjusting the **Origin** to _Poké Transfer_ and everything was considered valid.

Thank you for your time

**Comment by kwsch** [comment]
Met level is 30, but [there are no level 30 Doduo encounters in the RSE Safari Zone](https://www.serebii.net/pokearth/hoenn/3rd/safarizone.shtml).

When transferring from PK3=>PK4, the game changes the Met Location to Poketransfer, and sets the Met Level to whatever level the PKM was transferred as. PKHeX recognizes this mutation, and searches for any encounters `<=` the met level, rather than `==`.

**Comment by brunoaugusto** [comment]
Well, I confess after several tries poking the editor I *might* have changed that from the original value, can't say for sure, I don't remember.

However — and this worth to mention for anyone else in the future — the core problem of this Issue wasn't even the Level (in fact, I haven't even paid attention to it at the time I was writing this). The REAL problem was the **Quick Attack** move which, according to PokemonDB (Serebii is too hard for newcomers), is an Egg Move hence the expected Level to be zero and the invalid ball.
