### ISSUE TITLE
update the mystery gifts

### ISSUE THREAD

**Issue by kckxpyr1** [kwsch/PKHeX#3126]
Dear Kwsch,there are new illegal elves,
![image](https://user-images.githubusercontent.com/66785179/104796294-de1a5500-57ef-11eb-9b5f-b45f49b2a42b.png)
can you please update the mystery gifts Pokémon,thanks.

**Comment by kwsch** [comment]
Program release date: 12/30/2020
Event release date: 2021

Gee, wonder why it's not recognized.

This program is updated when it is updated.

https://github.com/kwsch/PKHeX/issues/3101
