### ISSUE TITLE
IL2CPP Error with latest Core DLL

### ISSUE THREAD

**Issue by Manurocker95** [kwsch/PKHeX#3128]
**Describe the bug**

IL2CPP error: 

IL2CPP error for method 'System.Void PKHeX.Core.BattleBox6::.ctor(PKHeX.Core.SaveFile,System.Int32)' in assembly 'I:\UnityProjects\PKHexUnity\Temp\StagingArea\Data\Managed\PKHeX.Core.dll'
Additional information: Attempting to return a value from method 'System.Void PKHeX.Core.BattleBox6::.ctor(PKHeX.Core.SaveFile,System.Int32)' when there is no value on the stack. Is this invalid IL code?

**To Reproduce**
1. Compile PKHex Core as DLL (I'm using .Net 4.6)
2. Copy it into any Unity project. The folder doesn't matter, but it should go under Assets/Plugins
3. Set project settings to backend IL2CPP, and .net4.x
4. Try to build the project

**Expected behavior**
Build the project

**Screenshots**
It gives a console error

**Additional context**
I have an old version from september 2020 and it compiles just fine.

**Comment by Manurocker95** [comment]
If it matters, PKM.Generation and PKM.Version accessors were not public

**Comment by kwsch** [comment]
You should probably be using the NuGet package rather than a self compiled version.

Also, ensure you have the .NET 4.6 Developer Pack installed.

Probably a Unity bug, not a PKHeX bug.

https://forum.unity.com/threads/il2cpp-error-for-method-system-void.940908/

**Comment by Manurocker95** [comment]
Nuget DLL doesn't work either. Other versions of Unity don't fix the issue but using the old DLL does, so it's something with it for sure.

**Comment by kwsch** [comment]
Might be that the unity runtime doesn't support recent c# compiler improvements like `init` and other code analysis stuff like `NotNullWhen`. 

Maybe try stripping them out (replace all `init` with `set`)?
