### ISSUE TITLE
Pokemon XD Deoxys Legality Issue

### ISSUE THREAD

**Issue by ReclaimerShawn** [kwsch/PKHeX#3130]
**Describe the problem**
I made four Deoxys's on Pokemon LeafGreen. I tried to use these Deoxys's in the VS. Mode feature of Pokemon XD by connecting my Gameboy to my Wii (which can play Gamecube games), but Pokemon XD said all four were illegal, despite PKHex reporting the Pokemon as legal. The rules of the match were set to anything goes. The Deoxys's were generated by Method 1 on RNGReporter and the matching PIDs, Nature, and IVs were used. Their current met Location is at Birth Island in Emerald. Setting these Pokemon to have originated from Birth Island on FRLG doesn't solve the problem either. The Deoxys's have the Obedience Flag checked. I am using the latest version of PKHex.

**To Reproduce**
This is a .ZIP file containing four .PKM files, each of one of the Deoxys's I created.
[Four Deoxys.zip](https://github.com/kwsch/PKHeX/files/5830153/Four.Deoxys.zip)

**Screenshots**
![140157095_261009535366786_1271062335800307907_n](https://user-images.githubusercontent.com/30769105/104915758-1be9bb80-595f-11eb-8178-758d491ba702.jpg)
![139949294_124567712846284_5656045992375735309_n](https://user-images.githubusercontent.com/30769105/104915771-2015d900-595f-11eb-94e5-bcbf2e8347fc.jpg)

**Additional context**
If there is no problem with the PKHex file (which there might be), then either RNGReporter, PKHex, or both are wrong about the legality of these Pokemon. A retail Gamecube-to-Gameboy Link Cable is being used. The stars were removed from the Deoxys .PKM files by me so I could could compress the files into .ZIP format to upload them. They are shiny nonetheless. I am using a legitimate catridge for Pokemon LeafGreen, a legit disc for Pokemon XD, and am playing on a real Wii console. Nothing like Nintendont is being used. The Wii itself is softmodded, however.

Below are the attached results of RNGReporter:
[rngreporter.txt](https://github.com/kwsch/PKHeX/files/5830186/rngreporter.txt)

All I could think of that could cause the problem woild be the amount of frames needed to produce each of the four PIDs with said IVs was incredibly high. You can see that in the text file. Perhaps the game either thinks this is essentially impossible or the frames go out of range for what Pokemon XD counts in frames?

**Comment by kwsch** [comment]
Maybe XD disallows shiny Deoxys (+ other mythicals?) by design?

Have you tried creating them with different TID/SID to make them nonshiny and see if it accepts it?

**Comment by ReclaimerShawn** [comment]
That isn't the problem, as a Shiny Deoxys that I have in Emerald and Ruby aren't considered illegal in-game at all. PKHex also considered these legal. They are attached below:
[Legal Deoxys.zip](https://github.com/kwsch/PKHeX/files/5833669/Legal.Deoxys.zip)

**Comment by ShadowMario3** [comment]
Did my own check with the .pkm files you provided, and can confirm that I have the same issue on my copy of XD using a FireRed cart:

![Snapshot_20210119_155232](https://user-images.githubusercontent.com/36941677/105091948-96edc780-5a6e-11eb-8825-4792a1c72339.jpg)

However, when they were loaded through Emerald, it (and the other Defense ones in a later test) passed without any issue:

![Uploading Snapshot_20210119_155921.jpg…]()

Just for the sake of testing, it passed Colosseum's check (used FireRed to register) as well:

![Snapshot_20210119_161532](https://user-images.githubusercontent.com/36941677/105093993-960a6500-5a71-11eb-927b-be6a2a5ab270.jpg)

I guess XD doesn't see those PIDs as legal for FireRed/LeafGreen for some reason.

**Comment by kwsch** [comment]
Ultimately, they're legal; whatever XD's legality checks are, they may be incorrectly checking something and disallowing.

Not really a PKHeX issue.
