### ISSUE TITLE
Gen 3 mon are being flagged as illegal because of "wordfilter" on the OT name

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3138]
Gen 3 has no word filter, so these should not be flagged in my opinion since it's very misleading, at the most they should be given a "Fishy" rating for this gen. The entire PC, party and daycare will forever show red exclamation points for this OT

Side note, is this name actually banned nowadays, and what would happen if it was sent to Bank? Would the Pokémon be rejected completely?

![image](https://user-images.githubusercontent.com/29823718/106424312-f44f2480-642f-11eb-82b0-594b0a782766.png)

[003 ★ - VENUSAUR - B912EF0C4314.zip](https://github.com/kwsch/PKHeX/files/5902321/003.-.VENUSAUR.-.B912EF0C4314.zip)

**Comment by MrPerson0** [comment]
From what I recall, this also happens when a Gen 1 or 2 save is loaded as well.

**Comment by Kermalis** [comment]
They have no nicknames, it's the OT name. I'm wondering what the OT name would become, or would the Pokémon be disallowed?

**Comment by kwsch** [comment]
#1524

**Comment by Kermalis** [comment]
It just seems silly to me to make the entire PC red exclamation points because of the OT name when they're all legal

![image](https://user-images.githubusercontent.com/29823718/106524345-7121e300-64b0-11eb-836f-02295c9dde7e.png)

**Comment by kwsch** [comment]
They're not legal per the wordfilter rules used by later generation :P

**Comment by Kermalis** [comment]
What about a yellow exclamation, similar to unusable moves in gen 8? That seems like a good enough heads up without being misleading. Probably hard to implement that with your current systems though. A setting in the config would also be a good compromise for people like me, and is easier to do
