### ISSUE TITLE
Item Capacity [Bug]

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#314]
I'm sure item capacity for Fire Red goes up to 999 but for whatever reason, any number over 99 that you set only shows up 99 in game. not sure if this is an issue in other gen 3 games.

**Comment by Ninjistix** [comment]
thanks a lot for the quick fix... 🍡

**Comment by Ninjistix** [comment]
@kwsch problem, when you modify items now its not being saved, or i'm not sure if the 99 cap is still being enforced, I pulled the most recent commit and built it.

**Comment by kwsch** [comment]
Seems to be working fine for me...

**Comment by Ninjistix** [comment]
it also seem like when I'm modifying the items quantity its not being saved, anything over 100 is being converted to 95

**Comment by kwsch** [comment]
Right, PKHeX caps out gen3 items @ 95; can always bump this up to 99.
