### ISSUE TITLE
Gen 1 Pikachu flagged illegal

### ISSUE THREAD

**Issue by PP-theSLAYER** [kwsch/PKHeX#3140]
**Describe the bug**
RB Pikachu above level 5 recognized as Y Starter Pikachu, despite wrong catch rate.
Hence, it gets flagged illegal.

**To Reproduce**
1. Catch a RB Pikachu (Lv 3 or 4)
2. Level it up to 5
3. Now check its full legality status

**Expected behavior**
Pikachu being recognized properly.

**Additional context**
First seen on this thread: https://projectpokemon.org/home/forums/topic/58501-legit-caught-mon-suddenly-flagged-as-illegal/

**Comment by kwsch** [comment]
Works fine on latest commit & hotfixed exe in the download thread.
