### ISSUE TITLE
Generation VIII Pokemon Marked as Illegal With TR Moves

### ISSUE THREAD

**Issue by Bulthax** [kwsch/PKHeX#3145]
**Describe the problem**
I'm using this with Pokemon Sword. I've tried having the following pokemon learn TRs that are on their Bulbapedia Move Lists but the moves are read as Illegal by the program. This seems to affect any TR that you do not have in your Bag. Even when adding the TR to your bag through PKHex this issue will persist. (I have not tried loading the game and re-editing the file after)

Cinderace
Drednaw
Orbeetle

This probably affects all TRs but I haven't tested beyond these three thus far.

**To Reproduce**
My sav file:
https://www.dropbox.com/s/318scxxglnrmd6k/main?dl=0

The easiest way to Reproduce is to edit Cinderace:
Attempt to edit a move into TR02 Flamethrower (this SAV doesn't have this TR in Bag), will show Cinderace as illegal.
Attempt to edit a move into TR12 Agility (this SAV does have this TR in Bag), will show Cinderace as legal.

**Expected behavior**
TRs that a pokemon can legally learn should be marked as Legal even if the bag does not start with that TR in it.

**Screenshots**

**Additional context**

**Comment by sora10pls** [comment]
Cinderace learns Agility at Level 24, so it can be taught this Move via the Move Reminder after evolving. TR not required.
Cinderace only learns Flamethrower via TR02, **thus requires the appropriate TR flag to be set.**

Owning a TR means nothing, because you can trade Held Items to other players.

Please do not report your bad hacks as bugs when the legality checks are working as intended.

**Comment by Bulthax** [comment]
> Cinderace learns Agility at Level 24, so it can be taught this Move via the Move Reminder after evolving. TR not required.
> Cinderace only learns Flamethrower via TR02, **thus requires the appropriate TR flag to be set.**
> 
> Owning a TR means nothing, because you can trade Held Items to other players in addition to trading PKM and having another player use a TM/TR on the PKM.
> 
> Please do not report your bad hacks as bugs when the legality checks are working as intended.

Thanks for the rude reply. Since there arent any instructions could you possibly inform me what you mean by "requires the appropriate TR flag" maybe without the same level of rudeness? Thanks.

**Comment by kwsch** [comment]
@Bulthax The issue template you used had the following instructions:

> **Describe the problem**
> A clear and concise description of what the bug is. **_This is not to ask why fabricated data does not pass the legality check._**

GitHub issues are not for providing help with using the program. Feel free to search previous "Issues" relating to Technical Records.
