### ISSUE TITLE
Invalid OTs with Half-Width Characters falsely flagged as legal on Past-Gen JPN mons

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3148]
**Describe the problem**
Half-width latin characters aren't available on JPN games until LGPE and Gen 8 (only half-width Latin characters are available on the Switch), therefore having a half-width Latin character OT on a past-gen JPN mon shouldn't be possible, only full-width Latin characters should be allowed.

**To Reproduce**
Example JPN Emerald Mews provided below, one with an invalid half-width Latin character OT, and one with a valid full-width character OT.
[Example Mews.zip](https://github.com/kwsch/PKHeX/files/5963006/Example.Mews.zip)

**Expected behavior**
Only full-width Latin characters should be allowed on JPN lang OTs for Pokemon that originate from games where half-width characters cannot be entered.

**Additional context**
This should also extend to nicknames for Gen 5, 6 and 7 (3DS, not LGPE) origin JPN lang Pokemon, as you can rename Pokemon in Gen 4 with **only** a matching TID (even on the wrong language), and the Switch removea the ability to enter full-width characters entirely.

Additionally while most outsider Pokemon can be renamed in Gen 8, fateful encounter flagged Pokemon cannot, so from Gen 5 onward fateful encounter pokemon can only be nicknamed while still on their original savefile, and are restricted to the text entry conditions of their original game.

https://bulbapedia.bulbagarden.net/wiki/Text_entry_in_the_Pok%C3%A9mon_games
https://bulbapedia.bulbagarden.net/wiki/Name_Rater#Renamable_Pok.C3.A9mon

**Comment by kwsch** [comment]
Need someone to catalog every single enterable character / character availability rules for each generation. Once the community research is done, then it can be added.
