### ISSUE TITLE
Downgrading pk8 to pk7 changes Pokemon's Stats

### ISSUE THREAD

**Issue by jojoiso36** [kwsch/PKHeX#3151]
**Describe the bug**
Loading in a .pk8 in a sav7, HAX enabled PKHeX causes some values to change. I have personally noticed seemingly random IVs having their values increased or decreased by 1, the met date being reset, as well as having the pokerus status changed from null to infected. Additionally, the executable does nothing if certain species of .pk8 are dragged in. Caterpie, Pidgeot and Fearow were examples for me.

**To Reproduce**
1. Use .bat file to open up PKHaX
2. Options > Settings > Set Blank Save Version to USUM
3. Drag in .pk8 file

**Expected behavior**
For these values to remain unchanged through the downgrading process, as well as all species being able to be imported.

**Screenshots**
Changed IV: https://cdn.discordapp.com/attachments/367479180398428170/810892063255953448/unknown.png
Changed Met Date: https://cdn.discordapp.com/attachments/367479180398428170/810890963870154782/unknown.png
Changed pokerus: https://cdn.discordapp.com/attachments/367479180398428170/810903987351322664/unknown.png

**Additional context**
My .pk8 were dumped from Home and have seen zero modifications before and during this process.

**Comment by kwsch** [comment]
Fixed by 0d0571558
