### ISSUE TITLE
plugin's not loading properly.

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3152]
**Describe the bug**
if you open any save and go to tools, the plugin's are missing unless you open pkhex without loading a save first

**To Reproduce**
1. Go to tools after loading any save and plugins are missing.
2. open blank pkhex and plugins are there.

**Expected behavior**
for plug's to load when you open a save form file association.

**Screenshots**
[blank pkhex save]
-save file loaded by file open.
![image](https://user-images.githubusercontent.com/12572974/108014063-12458900-6fdb-11eb-982d-32ab36dae76a.png)
[save loaded from pkhex file association]
-save file loaded by double clicking on save data.
![image](https://user-images.githubusercontent.com/12572974/108014082-1d98b480-6fdb-11eb-9c22-d48b7f650bc5.png)

**Additional context**
the save windows are also two different sizes.

**Comment by kwsch** [comment]
The sprites being a different size implies that the config file is different.

Are you sure that your file association is pointing to the correct executable?

**Comment by Ninjistix** [comment]
Yes I tried to point it agin in case, is there a way to remove the
association and reset it?

**Comment by ReignOfComputer** [comment]
https://edu.gcfglobal.org/en/windowsbasics/opening-files-with-different-applications/1/

**Comment by Ninjistix** [comment]
yeah I tried changing the extension to something else, then resetting it to
the current build of my  pkhex pull, and same thing, it only shows the
plugins if i open a blank sav

**Comment by kwsch** [comment]
When opening the PKM Database, is their any difference between the two startups?

**Comment by Ninjistix** [comment]
besides the window size, no
[image: image.png]
[image: image.png]

**Comment by Ninjistix** [comment]
no, they both look the same, besides the window size.
![image](https://user-images.githubusercontent.com/12572974/108027800-c0136080-6ff8-11eb-8cb9-60e0590c4e1f.png)
![image](https://user-images.githubusercontent.com/12572974/108027814-c6094180-6ff8-11eb-8095-539ae2988c19.png)

**Comment by Bappsack** [comment]
Open task manager, go to Details, find PKHEX.exe, rightclick -> Open Filepath.

**Comment by Ninjistix** [comment]
> Open task manager, go to Details, find PKHEX.exe, rightclick -> Open Filepath.
@kwsch @Bappsack  sorry for the mixup.
I checked this it was pointing to  a net46 folder and my blank file was coming from net5.0
