### ISSUE TITLE
OCT2014 Diancie

### ISSUE THREAD

**Issue by jojoiso36** [kwsch/PKHeX#3153]
**Describe the problem**
This event had a first, short release that didn't have guaranteed 3 IVs. PKHeX reports these otherwise legal pokemon as illegal.
https://projectpokemon.org/home/files/file/579-0525-xy-oct2014-diancie-us-eng/

**To Reproduce**
Use PKSM to inject the event. Export .sav to PC, open in PKHeX. View Diancie.

**Expected behavior**
This Diancie should report as Legal.

**Screenshots**

**Additional context**
Worth noting is that I had my own Diancie before genning this new one with PKSM. However, even though I believe I redeemed that one myself, I cannot guarantee 100% that I did. If I didn't, then I got it from the Casual Pokemon Trades subreddit, where it could have been generated from the same Wondercard.

**Comment by ReignOfComputer** [comment]
Can reproduce from the OCT2014 Diancie (No Set IVs) from within PKHeX's Event Database.

**Comment by Atrius97** [comment]
I should also add that this was apperently addressed already back in September 2017, but no long appears to be "playing favorites" with the 0 guaranteed IVs ones anymore:
https://github.com/kwsch/PKHeX/commit/16341b4d910c676e05663dd4b050fe53fba4b161

![Screenshot_20210216-040631_Chrome](https://user-images.githubusercontent.com/39707481/108054999-9ebc6f80-700c-11eb-869a-3c911cb6c648.jpg)
