### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by 19024626nggeliangstephen** [kwsch/PKHeX#3154]
**Describe the bug**
i followed the tutorial on compiling a new pkhex , however i received an error 

**To Reproduce**

download visual studio (community 2019 ) via the provided link from forum: https://visualstudio.microsoft.com/downloads/
download pkHeX-master.zip , unzip
open and run the project ( PKHeX.sln )
and build it

**Expected behavior**
Build started...
1>------ Build started: Project: PKHeX.Core, Configuration: Debug Any CPU ------
1>PKHeX.Core -> C:\Users\19024626\Downloads\PKHeX-master\PKHeX-master\PKHeX.Core\bin\Debug\net46\PKHeX.Core.dll
1>PKHeX.Core -> C:\Users\19024626\Downloads\PKHeX-master\PKHeX-master\PKHeX.Core\bin\Debug\netstandard2.0\PKHeX.Core.dll
2>------ Build started: Project: PKHeX.Drawing, Configuration: Debug Any CPU ------
3>------ Build started: Project: PKHeX.Core.Tests, Configuration: Debug Any CPU ------
2>PKHeX.Drawing -> C:\Users\19024626\Downloads\PKHeX-master\PKHeX-master\PKHeX.Drawing\bin\Debug\net46\PKHeX.Drawing.dll
3>PKHeX.Core.Tests -> C:\Users\19024626\Downloads\PKHeX-master\PKHeX-master\Tests\PKHeX.Core.Tests\bin\Debug\net5.0\PKHeX.Core.Tests.dll
2>PKHeX.Drawing -> C:\Users\19024626\Downloads\PKHeX-master\PKHeX-master\PKHeX.Drawing\bin\Debug\net5.0\PKHeX.Drawing.dll
4>------ Build started: Project: PKHeX.WinForms, Configuration: Debug Any CPU ------
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3075,5): error MSB3821: Couldn't process file Subforms\Save Editors\SAV_Inventory.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.
4>Done building project "PKHeX.WinForms.csproj" -- FAILED.
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3075,5): error MSB3821: Couldn't process file Subforms\Save Editors\SAV_Inventory.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.
4>Done building project "PKHeX.WinForms.csproj" -- FAILED.
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

application does not appear on winforms

**Screenshots**
![image](https://user-images.githubusercontent.com/68007467/108584574-65be2b00-737d-11eb-89e9-d8659e0444bd.png)

**Additional context**
visual studio community 2019 used  , must it really be 2017?

**Comment by ReignOfComputer** [comment]
Offending files -> Right Click -> Properties -> Unblock.
