### ISSUE TITLE
‘Total Battles’ in Trainer Info/Record should go up by 1 when injecting a mon

### ISSUE THREAD

**Issue by Priestyle** [kwsch/PKHeX#3158]
Hi, whenever a pokemon is injected and ‘Modify PKM info’ is ticked in the settings, only ‘Total Wild Pokemon Battles’ & ‘Pokemon Caught’ goes up by 1 in the trainer record/info. ‘Total Battles’ and for gen 7, ‘Balls Used’ counts should also go up by 1.

**Comment by kwsch** [comment]
Record IDs: https://github.com/kwsch/PKHeX/blob/dcd5f1fce1c790151b4a2abcedddc2ede4009424/PKHeX.Core/Saves/Substructures/Records.cs#L166

https://github.com/kwsch/PKHeX/blob/dcd5f1fce1c790151b4a2abcedddc2ede4009424/PKHeX.Core/Saves/Substructures/Records.cs#L352

https://github.com/kwsch/PKHeX/blob/dcd5f1fce1c790151b4a2abcedddc2ede4009424/PKHeX.Core/Saves/Substructures/Records.cs#L533

SAV8: https://github.com/kwsch/PKHeX/blob/666a1805ba2f3133a58bdcc783ddc0c0cccaf39f/PKHeX.Core/Saves/SAV8.cs#L132-L146

SAV7: https://github.com/kwsch/PKHeX/blob/4e92195b80f94acd3eeed4a75639191c40b73dab/PKHeX.Core/Saves/SAV7.cs#L191-L198

SAV6:
https://github.com/kwsch/PKHeX/blob/c8d815dc594c18f1deb05edb20e9da5fc89aaa86/PKHeX.Core/Saves/SAV6.cs#L144-L151

**Comment by Priestyle** [comment]
Hey, thanks for showing me the code for edits made in the trainer info when injecting a pokemon. Can you make pkhex so that it also ups the count of Total Battles and also Balls Used (for SAV7)? (It's total_all_battles for gen 8) Thx
