### ISSUE TITLE
SAV4BR: unique save identification

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#317]
Whenever building the latest release visual studio 2015 spits out the following warning:

`[Path_To_Solution]\PKHeX\Saves\SAV4BR.cs(55,30,55,39): warning CS0649: Field 'SAV4BR.SaveCount' is never assigned to, and will always have its default value 0`

![image](https://cloud.githubusercontent.com/assets/4019718/19282936/77a51fe2-8ff0-11e6-928b-52572b6b98e3.png)

**Comment by evandixon** [comment]
Not strictly a bug, but a feature that hasn't been added yet.
`private readonly int SaveCount; // TODO : unique save identification`
