### ISSUE TITLE
Why do two identical Pokemon display differently in different modifiers

### ISSUE THREAD

**Issue by shenhongtao1314** [kwsch/PKHeX#3170]
![image](https://user-images.githubusercontent.com/76119285/110060520-03afed80-7da1-11eb-977c-e8389c1805e4.png)
![image](https://user-images.githubusercontent.com/76119285/110060538-0ad6fb80-7da1-11eb-9822-1567abd44088.png)
![image](https://user-images.githubusercontent.com/76119285/110060564-1296a000-7da1-11eb-97d3-021fda16ce6c.png)
![image](https://user-images.githubusercontent.com/76119285/110060591-1a564480-7da1-11eb-938e-67b36f5563d4.png)
![image](https://user-images.githubusercontent.com/76119285/110060610-217d5280-7da1-11eb-87c5-e7935617c25b.png)

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/110060916-4be0f880-7d2c-11eb-8bca-ee4ee6105e38.png)
Newer versions can have updated legality checks.

**Comment by shenhongtao1314** [comment]
I download the 1.30 version of the code is normal and legal. But the code you updated recently is illegal after I compile it

**Comment by shenhongtao1314** [comment]
> ![image](https://user-images.githubusercontent.com/30205550/110060916-4be0f880-7d2c-11eb-8bca-ee4ee6105e38.png)
> 更新版本可以进行更新的合法性检查。

I download the 1.30 version of the code is normal and legal. But the code you updated recently is illegal after I compile it

**Comment by Lusamine** [comment]
If you are building the latest commit, it includes [validation for PIDIV](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/RNG/Overworld8RNG.cs) for overworld Pokemon such as Galarian Articuno.  This was added 19 days ago.

If you generated that Pokemon manually, it is likely appropriately illegal.

**Comment by shenhongtao1314** [comment]
> If you are building the latest commit, it includes [validation for PIDIV](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/RNG/Overworld8RNG.cs) for overworld Pokemon such as Galarian Articuno. This was added 19 days ago.
> Delachion. Biligeon. Goupaluon three can't change bid, Sid, trainer name
> If you generated that Pokemon manually, it is likely appropriately illegal.
