### ISSUE TITLE
Why do two identical Pokemon show two situations in different versions

### ISSUE THREAD

**Issue by shenhongtao1314** [kwsch/PKHeX#3175]
![QQ截图20210316160603](https://user-images.githubusercontent.com/76119285/111276210-0ef0fc00-8672-11eb-812d-18891ad6be4d.png)

**Comment by Lusamine** [comment]
This is the same problem as explained here https://github.com/kwsch/PKHeX/issues/3170#issuecomment-791132898.

Your Pokemon is correctly illegal.
