### ISSUE TITLE
Request: ORAS Boppoyama high score editing

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#3177]
Hey, I think being able to edit this in the Secret Base tab would be great. It's just a byte that goes up to 255.

For your player character, it's located at 0x23E98.
For the other players as listed in PKHeX, here are the locations:

Player 0: 0x241AC
Player 1: 0x2458C
Player 2: 0x2496C
Player 3: 0x24D4C
Player 4: 0x2512C
Player 5: 0x2550C
Player 6: 0x258EC
Player 7: 0x25CCC
Player 8: 0x260AC
Player 9: 0x2648C
Player 10: 0x2686C
Player 11: 0x26C4C
Player 12: 0x2702C
Player 13: 0x2740C
Player 14: 0x277EC
Player 15: 0x27BCC
Player 16: 0x27FAC
Player 17: 0x2838C
Player 18: 0x2876C
Player 19: 0x28B4C
Player 20: 0x28F2C
Player 21: 0x2930C
Player 22: 0x296EC
Player 23: 0x29ACC
Player 24: 0x29EAC
Player 25: 0x2A28C
Player 26: 0x2A66C
Player 27: 0x2AA4C
Player 28: 0x2AE2C
Player 29: 0x2B20C

This is located at 0x172 in .SB6 btw.

**Comment by elsaxo** [comment]
> Hey, I think being able to edit this in the Secret Base tab would be great. It's just a byte that goes up to 255.
> 
> For your player character, it's located at 0x23E98.
> For the other players as listed in PKHeX, here are the locations:
> 
> Player 0: 0x241AC
> Player 1: 0x2458C
> Player 2: 0x2496C
> Player 3: 0x24D4C
> Player 4: 0x2512C
> Player 5: 0x2550C
> Player 6: 0x258EC
> Player 7: 0x25CCC
> Player 8: 0x260AC
> Player 9: 0x2648C
> Player 10: 0x2686C
> Player 11: 0x26C4C
> Player 12: 0x2702C
> Player 13: 0x2740C
> Player 14: 0x277EC
> Player 15: 0x27BCC
> Player 16: 0x27FAC
> Player 17: 0x2838C
> Player 18: 0x2876C
> Player 19: 0x28B4C
> Player 20: 0x28F2C
> Player 21: 0x2930C
> Player 22: 0x296EC
> Player 23: 0x29ACC
> Player 24: 0x29EAC
> Player 25: 0x2A28C
> Player 26: 0x2A66C
> Player 27: 0x2AA4C
> Player 28: 0x2AE2C
> Player 29: 0x2B20C
> 
> This is located at 0x172 in .SB6 btw.
