### ISSUE TITLE
ORAS gift eggs being flagged as illegal

### ISSUE THREAD

**Issue by CyraFen** [kwsch/PKHeX#3178]
**Describe the problem**
ORAS gift eggs (Wynaut and Togepi) are being flagged as illegal when loaded directly from an ORAS save. 

**To Reproduce**
Load an ORAS save with the eggs. If the eggs are loaded from a .pk6 file into a blank save they will show as legal (met location will correct automatically).
[eggs.zip](https://github.com/kwsch/PKHeX/files/6174707/eggs.zip)

**Expected behavior**
These eggs are unmodified directly from the game itself and so should be legal.

**Screenshots**
When the save is loaded:
![image](https://user-images.githubusercontent.com/25874350/111855829-314a7a00-88fd-11eb-8451-c55ea1126233.png)
When the .pk6 is loaded:
![image](https://user-images.githubusercontent.com/25874350/111855837-3f989600-88fd-11eb-8135-3db56d3fcd94.png)

**Additional context**
This seems to be an issue with the met location. When loaded directly from the save, the met location is set to "(None)". However, when they are loaded from a .pk6, the met location will change automatically to "a Link Trade (egg)". If "(None)" is changed to "a Link Trade (egg)" the egg becomes legal, but this shouldn't be necessary as the egg was never traded.

**Comment by kwsch** [comment]
The correct arrangement is not having an Egg Location.

![image](https://user-images.githubusercontent.com/6393368/111858838-43c2b480-88f9-11eb-8e92-f93a9ab792f3.png)

When the egg is traded or hatched, it moves the current Met Location to the Egg Location, and applies the new met location.
