### ISSUE TITLE
Gen3 Fossil KI

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#318]
Gave myself Dome Fossil and Old Amber, but the guy in the game tells me I don't have any

**Comment by kwsch** [comment]
Bulbapedia has them listed as in the Key Items Pouch, so does [PKHeX](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables3.cs#L13) (286/287).

Possible that the game is checking for a certain event flag in the save file, as opposed to the item ID.

**Comment by Ninjistix** [comment]
might be the case, because i can confirm i have the KI's in game, but he still says i don't have any

**Comment by kwsch** [comment]
That's probably what is happening; key item / inventory editing won't be tied to event flags, at least until gen3 eventflags are implemented (if ever).

**Comment by suloku** [comment]
Those flags should be easy to find via map scripting.
