### ISSUE TITLE
Changing the player's name of a LeafGreen save file corrupted the save

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3184]
When I changed the name of the player and saved, when I went to play the save, the game gave me a "save file is corrupt" error message, even though the new name was present. I'm not sure exactly why that happened, but I'm uploading the save just in case you can figure it out just from that.

Using the previous release fixes the problem, by the way, so this is due to splitting the sav classes.

[Pokemon Leaf Green v1.1 (U)(Independent).sav.zip](https://github.com/kwsch/PKHeX/files/6261509/Pokemon.Leaf.Green.v1.1.U.Independent.sav.zip)

**Comment by kwsch** [comment]
Is this the original save file?

**Comment by Kermalis** [comment]
This is in the latest commit, not the latest release

I unfortunately can't use the latest commit right now, because I re-downloaded the previous release and am using that for now

However, here's what the save file looked like before my PKHeX changes:
[Pokémon LG - (JAY, m, e).zip](https://github.com/kwsch/PKHeX/files/6262078/Pokemon.LG.-.JAY.m.e.zip)

You can see all I changed was the trainer's name, and the trainer's name in all of the Pokémon

**Comment by kwsch** [comment]
Thanks, fixed in latest commit. The property setter wasn't writing to the correct byte[] :(

https://github.com/kwsch/PKHeX/commit/223b56d779c11019482f8b97cfcf62312342b867

Time to roll a new release...
