### ISSUE TITLE
Event Flags problem

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#3187]
**Describe the bug**

Checking/Unchecking Event Flags in the Research tab for GSC-LGPE does not write the changes upon hitting save, and also clicking the Event Flags tab for a FRLG save results in an error (see screenshot below).

Constants appear to be fine btw.

**To Reproduce**
1. Click Event Flags for the aforementioned games. (FRLG will throw an error.)
2. Click the Research tab
3. Check/Uncheck any Flags
4. Click Save, then go back to the Event Flags tab to find your Flag changes not saved.

**Expected behavior**
For changes to be set.

**Screenshots**

Attempting to access Event Flags for my FR save:
![nnnnnnnnnnnnn](https://user-images.githubusercontent.com/43196464/113960886-28114680-97f3-11eb-9093-966f0579efb4.jpg)

**Additional context**

N/A

**Comment by kwsch** [comment]
A hotfix for the FRLG was already posted (-b)
