### ISSUE TITLE
Crystal Headbutt Heracross incorrectly reported as illegal

### ISSUE THREAD

**Issue by oleombruni** [kwsch/PKHeX#3189]
**Describe the problem**
A Heracross caught in Azalea Town via Headbutt is incorrectly reported as illegal in the latest version of PKHeX (20210406).

**To Reproduce**
Play an English version of Pokémon Crystal with a TID ending in 5 (I used a female trainer with TID 25505). This results in the following Headbutt Azalea Town map:

<img width="486" alt="heracrosstree" src="https://user-images.githubusercontent.com/22159506/114056819-585bf200-9892-11eb-8d3b-4710459c4c4d.png">

Headbutting the two valid starred trees will result in drawing from the "high-encounter" pool, which in Crystal contains a level 10 Heracross. Any Heracross caught in this way is flagged as illegal in PKHeX.

I've included in [this zip file](https://github.com/kwsch/PKHeX/files/6279891/illegal_heracross.zip) both the .pkm file of an incorrectly-reported Heracross and the save file in which it was caught. The save file contains three Heracross (two caught in the tree circled in the screenshot above, the other caught in the other valid tree) along with a Spearow and Aipom caught from the same trees, which are instead correctly marked as legal.

**Expected behavior**
The described Heracross should be reported as legal.

**Additional context**
This is the complete legality information provided by PKHeX for the provided .pkm file:

    Invalid: Could not find a tree for Crystal headbutt encounter that matches OTID.
    ===
    
    Valid Move 1: Learned by Level-up.
    Valid Move 2: Learned by Level-up.
    Valid Move 3: Learned by Level-up.
    Valid Move 4: Learned by TM/HM.
    
    Valid: Nickname does not match another species name.
    Valid: Current level is not below met level.
    ===
    
    Encounter Type: Wild Encounter Headbutt, Special (Heracross)
    Location: Azalea Town
    GameVersion: C
    PID Type: None
    Other match(es):
    Invalid: Could not find a tree for Crystal headbutt encounter that matches OTID.

**Comment by kwsch** [comment]
PKHeX uses a list of possible tree coordinates to build a possibility list for the location.

https://github.com/kwsch/PKHeX.EncounterSlotDumper/blob/50c53d6b33983a12606a3a6a414ec7e738cad7b8/Resources/gen2/trees.json#L191

Will have to double check the list to see if all trees are in it. It's manually entered, and there have been errors in the past 😅

**Comment by oleombruni** [comment]
Yeah I checked and the affected trees are already in the list, in the case of TID ending in 5 they are (25,11) and (35,12). I'm going to check if the same behavior occurs with other TIDs.

**Comment by oleombruni** [comment]
It appears that only the TIDs ending in 5 have this problem, and only in Azalea Town (Heracross caught in Route 42 or 44 are flagged as valid, while Route 33 doesn't have valid Headbutt trees for TIDs ending in 5).

**Comment by kwsch** [comment]
For reference: coordinates in G2Map:

![image](https://user-images.githubusercontent.com/6393368/114095087-dfe53900-9871-11eb-9be9-63a909ae0a99.png)

**Comment by kwsch** [comment]
Looks like the game converts player coordinates (0 indexed) to padded coordinates, and uses the padded coordinates in the calculation (rather than the unpadded).

https://github.com/pret/pokecrystal/blob/5db892782adaa5bb5a3e4cd6fa06565764bd1fb0/engine/overworld/player_object.asm#L74-L84

https://github.com/pret/pokecrystal/blob/e791c5392b19f589c51afd98666d19e778278847/home/map.asm#L1778-L1788

Assumedly this helps in preventing underflow, since no maps are >200, so pad by 4? Heh. Guess I'll have to re-generate the tree permit bits.
