### ISSUE TITLE
Crystal Raikou/Entei Locations flagged

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#3196]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

Seems like Raikou and Entei are being flagged for being caught at certain Routes. This was fine in previous releases.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

Take any legal Raikou or Entei from Crystal, and set any of their Locations to Routes 42, 43, 44, 45, and 46.

**Expected behavior**

Routes 42-46 being legal.

**Screenshots**

N/A

**Additional context**

For reference, these are the valid Routes they can roam to:

Route 29
Route 30
Route 31
Route 32
Route 33
Route 34
Route 35
Route 36
Route 37
Route 38
Route 39
Route 42
Route 43
Route 44
Route 45
Route 46

**Comment by kwsch** [comment]
RoamLocations in EncounterStatic2 looks to be missing the upper bits for these locations, 37,39,43,45 missing

**Comment by Lusamine** [comment]
Should be fixed in https://github.com/kwsch/PKHeX/commit/eceb498da3ef0f070eeb395694e1e6db2eeafbcd
