### ISSUE TITLE
Event Flag Editor won't set flags

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#3197]
**Describe the bug**
When using the event flag editor in the research tab, setting or unsetting any flag will not be saved and will revert upon selecting a different flag or closing the tab.

**To Reproduce**
1.) Open a gen 2-7 game save in PKHeX
2.) Open the event flag editor and go to the research tab.
3.) Select any flag and then select a different flag.
4.) Go back to the original flag and rather than the changes being saved, it will have reverted as if it was never changed

**Expected behavior**
Setting or unsetting a flag actually applies the change

**Comment by CanoeHope** [comment]
#3187 
Already addressed in https://github.com/kwsch/PKHeX/commit/f8a2bb3229c41faad3715b7cddc7914c7bc074ec
