### ISSUE TITLE
Golduck Hydro Pump and Confusion seen as illegal.

### ISSUE THREAD

**Issue by Ceroes** [kwsch/PKHeX#3198]
**Describe the problem**
Hydro Pump, Confusion, amnesia and fury swipes are all missing as legal moves.

**To Reproduce**
[New folder.zip](https://github.com/kwsch/PKHeX/files/6371991/New.folder.zip)

**Expected behavior**
They are learned upon level up as seen here and here.
https://github.com/pret/pokeyellow/blob/master/data/pokemon/evos_moves.asm#L1538-L1547
https://bulbapedia.bulbagarden.net/wiki/Golduck_(Pok%C3%A9mon)/Generation_I_learnset#By_TM.2FHM

![image](https://user-images.githubusercontent.com/34236578/115994673-ff849d00-a5a5-11eb-87ad-0a03e1e4bff7.png)

**Comment by ReignOfComputer** [comment]
Your Golduck is Level 15 and cannot learn those moves.

As mentioned in the issue template, "This is not to ask why fabricated data does not pass the legality check".
