### ISSUE TITLE
Flame thrower is illegal on Arcanine and growlithe

### ISSUE THREAD

**Issue by Ceroes** [kwsch/PKHeX#3199]
**Describe the problem**
Flame thrower is a level up move for Growlithe so should be legal.
**Expected behavior**
Should be seen as legal.
**Screenshots**
![image](https://user-images.githubusercontent.com/34236578/115995161-1b893e00-a5a8-11eb-9e1a-a6135a84ea32.png)

**Comment by ReignOfComputer** [comment]
Like https://github.com/kwsch/PKHeX/issues/3198, willing to bet the Pokemon is not above Level 50, which is needed for Flamethrower.

To reiterate, "This is not to ask why fabricated data does not pass the legality check".
