### ISSUE TITLE
Feature Request: PK* Gen1-6 DB

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#320]
I would love to have a DB (included with build) of GEN1-6 .pk* with Legit/Legal info, I would be willing to help obtain .pk* files from any GEN to help build the DB

I read somewhere PKHeX converts from Gen3>4>5>6, but some time ago I believe they added GEN1 to the PokeBank with the release of the VC. I'm looking to get ready for GEN7, and want to build the ultimate legit collection of every PKMN from every GEN.

@ReignOfComputer Started doing something similar [here](https://github.com/ReignOfComputer/RoCs-PC), but I figured it'd be better integrated into PKHeX to help everyone build/complete their Pokedex's for every GEN*. He also has some event .pk*s for different GENs so that would be an awesome addition to the DB

**Comment by kwsch** [comment]
A PKM database contains ingame received data (OT/TID/SID) and won't ever be built into the program. Remember, mystery gift (templates) are not pkm files.

PKHeX uses the 'db' folder to store dumped boxes and to populate the user's PKM Database (CTRL-D); **a user is free to add and remove files in that folder.**
