### ISSUE TITLE
Bellsprout illegal moves

### ISSUE THREAD

**Issue by Ceroes** [kwsch/PKHeX#3200]
Also missing moves it would normally learn upon level up.

**Comment by ReignOfComputer** [comment]
Stop making new "bug" reports and learn to hack. Thanks.

**Comment by Lusamine** [comment]
There is no information provided here.  If you edited this Pokemon like in https://github.com/kwsch/PKHeX/issues/3198 and it is illegal, this is not the place to ask why badly hacked data is illegal.
