### ISSUE TITLE
Lycanroc [Dusk] invalid Move - Crush Claw

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3204]
**Describe the problem**
![image](https://user-images.githubusercontent.com/12572974/116959776-afc06880-ac6c-11eb-8f3c-cfa27e73f68c.png)

**To Reproduce**
[745-02 - Lycanroc - 3C5AF94CDFD2.zip](https://github.com/kwsch/PKHeX/files/6418965/745-02.-.Lycanroc.-.3C5AF94CDFD2.zip)

**Expected behavior**
move should be valid as it is learned during evolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/12572974/116960073-5a388b80-ac6d-11eb-82d2-b4dd5015073f.png)
![image](https://user-images.githubusercontent.com/12572974/116959725-80a9f700-ac6c-11eb-8070-837b3713e979.png)

**Comment by ReignOfComputer** [comment]
You're in a Gen 7 save, looking at Gen 8 movesets on Bulbapedia. Not a bug.

**Comment by Ninjistix** [comment]
my bad, didn't see the badge.
