### ISSUE TITLE
20th Anniversary Keldeo Marked Illegal Despite Legitimate 

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#321]
The 20th anniversary Keldeo is marked illegal despite the fact it has legit. Apparently, it can't relearn Aqua Jet, Bubble Beam, Double Kick, and Leer and is not considered a valid gift.

**Comment by kwsch** [comment]
The last release was 9/18.
Keldeo began distribution on October 1.

Obviously the last release wouldn't have the Wonder Card built in; again, you can add the card as discussed previously. 
https://github.com/kwsch/PKHeX/issues/234
