### ISSUE TITLE
Batch Editor Box Targeting Fails

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#3229]
**Describe the bug**
Batch Editor box targeting no longer works, likely as of https://github.com/kwsch/PKHeX/commit/3e7775fc44b01051f998d6369c519ca4930e83e1

**To Reproduce**
1. Go to 'Batch Editor'
2. Use `=Box=1` and another modifier to target Pokemon in Box 1
3. No Pokemon fit the target with a box target

**Screenshots**
![image](https://user-images.githubusercontent.com/2667537/124342475-d95b2900-dbf6-11eb-9111-787615882e6c.png)

**Additional context**
Additionally, note that as shown in the screenshot, batch editor now thinks there are 930 Pokemon to target (instead of just 1 in the save file).

**Comment by sora10pls** [comment]
Tested using a non-blank save file, `=Box=1` is targeting Box 2 instead of Box 1.
