### ISSUE TITLE
Encounter Type PID mismatch Gen 3-4 when editing pokemon

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3230]
**Describe the problem**
edits to pokemon give "invalid: Encounter Type PID mismatch"
editing pokemon's gender/ivs/level/moveset

**To Reproduce**
[Pokemon Ruby Version.zip](https://github.com/kwsch/PKHeX/files/6765704/Pokemon.Ruby.Version.zip)

**Expected behavior**
should be able to edit/generate caught pokemon to modify their gender/stats without PID error.

**Screenshots**
Before Edit
![image](https://user-images.githubusercontent.com/12572974/124503878-65568780-dd94-11eb-8210-3beef3649405.png)
After Gender Change
![image](https://user-images.githubusercontent.com/12572974/124503909-743d3a00-dd94-11eb-9a88-9bb7531871a9.png)
Reverted Gender Change, and Randomized IVs
![image](https://user-images.githubusercontent.com/12572974/124503960-8f0fae80-dd94-11eb-9a6a-f2a289e3c33e.png)
Reverted Randomized IV's and Rerolled PID
![image](https://user-images.githubusercontent.com/12572974/124504146-ddbd4880-dd94-11eb-9f90-1c3e757b72a8.png)

**Additional context**
Happens only to the following Generations/Games
Gen III - R\S\E\FR\LF
Gen IV - D\P\Pt\HG\SS

To test this in different generations I download [ROC](https://github.com/ReignOfComputer/RoCs-PC)'s sav data to test if I could edit anything and they all give Encounter Type PID mismatch except from generation 6+ (1-2 had no errors for editing stats/genders)

**Comment by Lusamine** [comment]
Not a bug.  Pokemon in gen 3-4 have PIDIV correlation.  Editing legal mons will make them illegal.

Tutorials to fix this yourself.

https://projectpokemon.org/tutorials/save-editing/using-pkhex/pid-mismatch-origin-game-rsefrlg-r94/
https://projectpokemon.org/tutorials/save-editing/using-pkhex/pid-mismatch-origin-game-dppt-hgss-r95/
