### ISSUE TITLE
Gen 8 Slot encounters are illegally forced Square Shiny from encounter database

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3232]
**Describe the bug**
On the development build uploaded to Project Pokemon, selecting any Gen 8 slot encounter from the encounter database forcefully loads a square shiny version of the Pokemon, disregarding Gen 8 Overworld PIDIV, which also causes it to be illegal.

**To Reproduce**
1. Download the development build from [Here](https://projectpokemon.org/home/files/file/2445-pkhex-development-build/)
2. Extract to a clean folder
3. Open the encounter database and search for Wooloo for species, (unselect all checkboxes on the middle of the right panel except "Slot")
4. Click view on any of the slot encounter Wooloo to reproduce the error, they should all be Square Shiny in the main window.

**Expected behavior**
The encounter database shouldn't be forcing a shiny PID for any encounter that isn't already forced shiny by the game.

**Screenshots**
(Apologies for the somewhat buggy gif, it glitches at the beginning, but it does show the error)
![GIF 09-07-2021 3-21-08 AM](https://user-images.githubusercontent.com/39707481/125056643-a9cc7680-e065-11eb-85c7-bd3d9e81f632.gif)

**Additional context**
I am running PKHeX Build 21.5.22+111 on Windows 7 and .NET Framework 4.8.
The folder was not extracted to a network location like OneDrive, a fresh folder, and there were no plugins installed.

**Comment by sora10pls** [comment]
This is a known issue; it can be replicated when `UseTabsAsCriteria` in encounter database settings is set to true, where it’ll reroll IVs and the PID to always be xor0.
