### ISSUE TITLE
ORAS Castform Legality Check Error - Not Valid Encounter Error

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#324]
The legality check keeps saying that Castform at Rout 119 is not a valid encounter even though it was given at the lab in the Weather Institute.

![seeya](https://cloud.githubusercontent.com/assets/21182549/19462691/b0f138c8-94bc-11e6-8605-ad0d0ac4f1db.png)

**Comment by kwsch** [comment]
There's a bunch of other properties like IVs/Nature, probably that's what's incorrect on your pkm.

**Comment by ricksee** [comment]
@kwsch Never mind I found the mistake.

**Comment by rubylim6** [comment]
So what was the problem with the castform? Im currently experiencing the same problem too

**Comment by wwwwwwzx** [comment]
Please check the Gender(Female), IVs(SpA =31), Nature(Lax), etc

**Comment by rubylim6** [comment]
I made an additional castform personally as the original one however it still experience problems :c

**Comment by kwsch** [comment]
Castform has contest stats iirc.
Please do not request legality help via Issues. This space is to report problems with the checking of legitimate inputs, not trouble faking data.
