### ISSUE TITLE
The legality of ho-oh in colo,maybe a bug?

### ISSUE THREAD

**Issue by liketolike** [kwsch/PKHeX#3242]
I used the user skylink24 to save, changed the saved language and region(jp), and the ho-oh obtained is illegal.
The reason is ✔Fateful encounter,when transferred to R / S / E / FR / LG, √ will be cancelled.
![HO-OH](https://user-images.githubusercontent.com/88918365/129438624-c2aa638b-ea6d-444a-9b57-b497356be871.PNG)
I will save and change the suffix. 
Only the region and language were changed !!
[01-GC6J-pokemon_colosseum.gci.txt](https://github.com/kwsch/PKHeX/files/6986075/01-GC6J-pokemon_colosseum.gci.txt)

**Comment by liketolike** [comment]
[250 - ホウオウ - 78FFB29361F0.ck3.txt](https://github.com/kwsch/PKHeX/files/6986082/250.-.-.78FFB29361F0.ck3.txt)

**Comment by Atrius97** [comment]
As far as I'm aware, this is not a bug. The Mt. Battle Ho-Oh gift, according to Project Pokemon's legitimate examples [here](https://projectpokemon.org/home/files/file/2900-mt-battle-present-room-mattle-ho-oh/) (English) and [here](https://projectpokemon.org/home/files/file/3464-mt-battle-%E3%83%90%E3%83%88%E3%83%AB%E3%82%84%E3%81%BE-ho-oh/) (Japanese), does indeed have the met location as "(fateful encounter)", but the "Fateful Encounter" flag left unchecked.

Please make sure that when you're reporting a legality error that you've obtained the pokemon yourself, and not editing a publicly uploaded savefile and reporting an error, without knowing the legality conditions for what you're reporting.

**Comment by Atrius97** [comment]
> I changed the saved region and language, and then obtained ho-oh in mt.battle,is this illegal?
A: The only issue with your Ho-oh is the fateful encounter flag is set true.
B: I can confirm that that does not occur in a normal Colosseum save, nor the savefile you used, regardless of language/region.

I downloaded the savefile you originally used from [here](https://projectpokemon.org/home/files/file/2821-pokemon-gamecube-saves/) and converted the language and region of the savefile using **Game Cube Save Converter**, as suggested on the same page. 

The Ho-oh I received did not have the fateful encounter flag checked when using the original PAL savefile, nor the converted language/region version. Both original PAL Ho-oh and region/language converted Ho-oh appeared legal in PKHeX and had the proper data.

![Capture](https://user-images.githubusercontent.com/39707481/130036514-f40b5428-3f0f-45a8-bdec-8a18c79e07ab.PNG)

Either you were playing a modified ROM that alters the behavior of the Ho-oh gift to have the fateful encounter flag checked, or this is simple user error.

**Comment by liketolike** [comment]
> > I changed the saved region and language, and then obtained ho-oh in mt.battle,is this illegal?
> 
> A: The only issue with your Ho-oh is the fateful encounter flag is set true.
> B: I can confirm that that does not occur in a normal Colosseum save, nor the savefile you used, regardless of language/region.
> 
> I downloaded the savefile you originally used from [here](https://projectpokemon.org/home/files/file/2821-pokemon-gamecube-saves/) and converted the language and region of the savefile using **Game Cube Save Converter**, as suggested on the same page.
> 
> The Ho-oh I received did not have the fateful encounter flag checked when using the original PAL savefile, nor the converted language/region version(s). Both original PAL Ho-oh and region/language converted Ho-oh(s) appeared legal in PKHeX and had the proper data. I'm unable to reproduce this behavior.
> 
> ![Capture](https://user-images.githubusercontent.com/39707481/130036514-f40b5428-3f0f-45a8-bdec-8a18c79e07ab.PNG)
> 
> Either you were playing a modified ROM that alters the behavior of the Ho-oh gift to have the fateful encounter flag checked, or this is simple user error. The legality checker is working as intended, your Ho-oh is indeed illegal.
> 
> Edit: Lusamine was kind enough to also test the "trading to Gen 3 GBA" part, and was also unable to reproduce Ho-oh gaining the fateful encounter flag as well.

Thanks for the test. Sometime I will save through MT.Battle in Japanese, try again!

**Comment by Lusamine** [comment]
The issue was that the Fateful encounter flag was being misread in Colosseum, and the Ho-Oh should not be Fateful after all.  It incorrectly appeared to be Fateful in Japanese Colosseum, not in English Colosseum I attempted.  This should be corrected in c1a7d04c5c0ee13fdaeb9becbbe3ddedfa71ad54.
