### ISSUE TITLE
"Too High" PP Numbers on VC Import Pokemon

### ISSUE THREAD

**Issue by jjaldridge2009** [kwsch/PKHeX#3244]
**Describe the problem**
Pokemon Imported using PokeTransporter from VC Yellow into Ultra Sun are showing insanely high current PP (in this example 255 PP on Focus Energy).

In game this same Nidoking is showing 30/30 PP on Focus Energy. 

I looked at the .pkm in hex, and it looks like the move actually is showing 0xFF for Move 4 Current PP which is a very strange behavior.

Withdrawing the Pokemon into Party, and using Pokemon Center corrected the values to expected Current PP.

**To Reproduce**
Import Pokemon from VC to PokeTransporter and Directly into boxes.

[034 - Nidoking - 3A07C96A0186.zip](https://github.com/kwsch/PKHeX/files/7018726/034.-.Nidoking.-.3A07C96A0186.zip)

**Expected behavior**

Normally I'd expect a situation like this to indeed flag as illegal, because the moves current PP actually is above the acceptable range. However, this seems to be a legitimate case where going through official channels results in an "illegal" Pokemon.

Considering in-game the Pokemon only shows its maximum PP value anyway, I'm not sure the best way to handle this. Just reporting a strange behavior.

**Screenshots**

![image](https://user-images.githubusercontent.com/16225603/130168305-992bb082-f9fd-424d-83f0-b2059761d2da.png)
![image](https://user-images.githubusercontent.com/16225603/130168320-6db96eca-8054-41bd-bd06-698fc4868947.png)

**Comment by Lusamine** [comment]
1. You should update your PKHeX.  Reporting bugs on a version that's over a year old is bad practice.
2. This is an issue on GF's end, so it'll be flagged since it shouldn't be correct or legal to have 255 pp on a mon, nor would it be ideal to permit this in more situations.  Heal them in-game to fix it.

**Comment by jjaldridge2009** [comment]
Sorry, screenshot is from older version because I was just checking. This also appears in the latest version.

Understandable, like I said, just reporting because it was a strange behavior that I wasn't sure how best to handle. 

Thanks for your time. <3

**Comment by kwsch** [comment]
Can also heal them within PKHeX via Box's right click menu:

![image](https://user-images.githubusercontent.com/6393368/130173621-ac2d53bf-a24f-4aed-83c1-02a22058b7ba.png)
