### ISSUE TITLE
Feature Request: Editable Pokecoupon count GBA side

### ISSUE THREAD

**Issue by Billo-PS** [kwsch/PKHeX#3248]
**Is your feature request related to a problem? Please describe.**
Pokecoupons are a currency used in Colosseum (Namely for the Celebi Bonus disc for Japan Players), they are used to buy items/Pokemon at the store within Colosseum and on the Celebi Bonus Disc. PKHeX currently supports editing Pokecoupons in a Colosseum save file but I couldn't find anything that allowed edits to the GBA Pokecoupon count. 

**Ideal Solution:**
To be able to edit GBA Pokecoupon count. (Research required though I have ran a few basic tests.)

**Alternatives:**
The only way to obtain these Pokecoupons on a GBA save file go through a tedious process of completing many battles.

**Additional context**
Completed tests:
- Compared a before and after save file and checked their counts when connected to Pokemon Colosseum.
- Compared a before and after save file on Colosseum to help confirm that this is not something editable within the game.

Below are some extra details regarding Pokecoupons and their transfer mechanics:

Ways to earn Pokecoupons:
- Winning MT Battle with GBA team in increments of 10, points rewarded per 10 trainers beat
- Colosseum Battle with GBA team

Pokecoupons can then be sent from Colosseum to a GBA save file by a prompt to connect a GBA to receive points after ending or completing a challenge. Obtaining them is a very slow and tedious (and required) process to RNGing the Celebi from the JPN bonus disc.

Attached are 2 USA Pokemon Emerald save files with and without 50 Pokecoupons, and a completed Colosseum save file. Thank you in advance to those looking into it.

(Note: You're only able to see GBA Pokecoupon count when connected to a Gamecube, this displays on "PokeCoupon exchange" store in Colosseums "Colosseum Battle" menu screen.)

[SaveFiles.zip](https://github.com/kwsch/PKHeX/files/7028283/SaveFiles.zip)

**Comment by kwsch** [comment]
Notes:

https://github.com/pret/pokeruby/blob/2162e948d1889cbf5c651b9747dab1194323f2da/include/global.h#L622
https://github.com/pret/pokeemerald/blob/f7a699c686d329edb48686d175caf709de426bf5/include/global.h#L916
https://github.com/pret/pokefirered/blob/585d92f298e1edd8f756f8362de45c9fadc6fcab/include/global.h#L748

**Comment by kwsch** [comment]
Can be accessed from the block editor button, which can directly edit the values
