### ISSUE TITLE
PBRSaveData (from Japanese version of Battle Revolution)

### ISSUE THREAD

**Issue by Arymond** [kwsch/PKHeX#3253]
loading from a generated Dolphin save

doesn't seem to load i'm not sure if i have to get to a certain point in the game or not?

https://cdn.discordapp.com/attachments/753692117796388974/882012093660930088/PbrSaveData

![image](https://user-images.githubusercontent.com/22692858/131407420-962fab61-f81e-47c4-984d-908b3de9b03d.png)

**Comment by kwsch** [comment]
You've only saved once; the other save file half is not a valid encrypted save file partition.

Try saving again in-game so that the savefile backup is completely initialized. Plus, try to make sure you progress enough so that unlocking the boxes is a usable feature :)
