### ISSUE TITLE
Gen 3 (Fire Red) giving unsupported file type error

### ISSUE THREAD

**Issue by zurgeg** [kwsch/PKHeX#3257]
**Describe the bug**
Gen 3 (Fire Red) gives an unsupported file type error

**To Reproduce**
1. Open the attached save file in PKHeX
2. See error

**Expected behavior**
The save should open.

**Screenshots**
N/A

**Additional context**
My save (stored in a ZIP because GitHub doesn't support SAV files)
[FireRedSave.zip](https://github.com/kwsch/PKHeX/files/7163924/FireRedSave.zip)

**Comment by Masamune3210** [comment]
modded rom/patched in absolutely any way,  or official?

**Comment by zurgeg** [comment]
> 
> 
> modded rom/patched in absolutely any way, or official?

Official, I'll check if it matches with No-Intro checksums

**Comment by sora10pls** [comment]
A majority of your save file is 0xFF... make sure you're feeding PKHeX valid save data. All of my Gen3 saves (including FRLG) work just fine.

**Comment by zurgeg** [comment]
> 
> 
> A majority of your save file is 0xFF... make sure you're feeding PKHeX valid save data. All of my Gen3 saves (including FRLG) work just fine.

Hmm, can you send your save, or at least the size of it? I wonder if the 0xFF is padding or something

**Comment by zurgeg** [comment]
Alright, I've did further research, and I believe this issue is likely due to my progression (or lack thereof) in the game. My (perfectly valid when running under an emu) save data opens up with `FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF`, however, an all shiny save I downloaded opens up with `C8C3BDC5FFFFFFFF00800546D73287001E121400220000000000DA0000000000`, closing this for now because it's likely a non-issue

**Comment by Lusamine** [comment]
I loaded your save into emulator, re-saved in game, and it works fine in PKHeX afterwards.
[frsave-resaved.zip](https://github.com/kwsch/PKHeX/files/7165932/frsave-resaved.zip)
Not sure why yours came out unusable.
