### ISSUE TITLE
Request: 2 features to edit

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#3258]
Hey there, I thought that editing these 2 things would be some nice additions to the program.

They are the Blue Card Points for Crystal (goes up to 30 legitimately) and the "main" offset that tells your LGPE game what gender your starter Pikachu/Eevee is to be read as in the overworld and cutscenes.

**Crystal Blue Card Points Offset**
Crystal (U/E): 0x27D9
Crystal (JPN): 0x278E

**LGPE Partner Pikachu/Eevee Gender Offset**: 0x10B9

Male is 00 and Female is 01.

Also wanted to point out that for the Mystery Gift function for LGPE, the buttons to make All Unused/Used and the QR generator should probably be disabled or hidden. 

Thanks

**Comment by kwsch** [comment]
LGPE Starter gender already accessible via block editing -- doesn't seem too worthwhile to make as a GUI option
https://github.com/kwsch/PKHeX/blob/c3051b30023b7bf31af9c1ae64bf2febd9eee40b/PKHeX.Core/Saves/Substructures/Gen7/MyStatus7b.cs#L71

**Comment by kwsch** [comment]
Closed with https://github.com/kwsch/PKHeX/commit/b9d47215539c5acdf2ea1ef8b832dff389c80e15 ; all other points covered.
