### ISSUE TITLE
Request: Add Poké Transfer minigame score editing (Gen 5)

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#3259]
Hi, thanks for the previous request. 
For this request, I'd simply like to see the generation 5 Poké Transfer minigame's high score added and editable in the "Block Data" function of BW and B2W2 save editing.

It's located at 0x21214 for BW and 0x21118 for B2W2.

Please and thanks again. :)

**Comment by kwsch** [comment]
Is it a 32bit value or an 8 bit value/etc?

**Comment by FeralFalcon** [comment]
It shows up to 999 in-game, but I guess it holds up to 65535. So 16bit? (Sorry, correct me if I'm wrong because I'm no good with data types lol)

**Comment by FeralFalcon** [comment]
@kwsch 
Thanks!
Just tested this new commit, only to find out that whenever I try to edit the number it doesn't stick. It displays fine, though.

**Comment by kwsch** [comment]
Should be good now :)
