### ISSUE TITLE
Add support for Sun&Moon?

### ISSUE THREAD

**Issue by goteniai** [kwsch/PKHeX#326]
Dummy Message

**Comment by suloku** [comment]
They are on it, just wait

**Comment by goteniai** [comment]
Aha, part of the reason of this is that I'm the fan translator of the Pokemon XY and ORAS.

**Comment by ricksee** [comment]
Can I ask a question? What is RSA encryption? How does it apply to Sun and Moon? And since the game is already data mined and RSA is cracked, that means that the game or at least the demo can be edited? Would it be anymore difficult that past games?

**Comment by kwsch** [comment]
https://simple.wikipedia.org/wiki/RSA_(algorithm)
Save file has another layer of validation beyond the regular gen6 save format,
Yes
A little more difficult, but probably doable prior to full game release.

**Comment by kwsch** [comment]
E

**Comment by ricksee** [comment]
@kwsch Would that mean the player would have to save their file twice or would the editor have to change the way it changes the Sav file?

**Comment by ricksee** [comment]
Plus are the Ultra Beasts catchable? If they are considered not Pokemon or if they are NPC's then, they shouldn't be in the Pokedex entries.

**Comment by kwsch** [comment]
Added in commit from today.
