### ISSUE TITLE
3 Colo/XD legality issues

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#3260]
**Describe the problem**
1. Colosseum's Mt. Battle Ho-Oh OT in the German language (DUELLBERG) is flagged. This is only the case for the untraded CK3, not PK3; Other languages are fine.

2. HORDEL's Elekid from XD doesn't seem to get checked for the nickname of **コンセント** for Japanese and **ZAPRONG** for the rest of the languages.

3. There are unreleased COLOS Pikachu and AGATE Celebi in languages other than English that don't appear to be registered in the program's code. They have the following OTs per language:

Pikachu
French and German = COLOSSEUM
Italian = ARENA
Spanish = CLAUDIO

Celebi
French = SAMARAGD
German = EMERITAE
Italian = SOFO
Spanish = ÁGATA

**To Reproduce**
Here is a ZIP containing folders for each case: [GC.zip](https://github.com/kwsch/PKHeX/files/7261365/GC.zip)

**Expected behavior**
1. The 7+ character German Mt. Battle Ho-Oh OT being legal.
2. Elekid having a nickname check.
3. Acknowledge the data for French, German, Italian, and Spanish languages of COLOS Pikachu and AGATE Celebi as unreleased.

**Additional context**
Ho-Oh's initial German OT is in the program's code according to the search results:
https://github.com/kwsch/PKHeX/blob/c1a7d04c5c0ee13fdaeb9becbbe3ddedfa71ad54/PKHeX.Core/Legality/Encounters/Data/EncountersWC3.cs#L31

**Comment by kwsch** [comment]
3. Unreleased events are unimplemented in the program to prevent them from leaking into the Encounter Generator. Not going to add logic checks to see if an encounter is actually possible.

It's the same as acknowledging debug data like METEOR Jirachi; not accessible without breaking the game / etc

**Comment by FeralFalcon** [comment]
Fair enough, but it's weird when the English ones are being flagged as unreleased.
