### ISSUE TITLE
Legal Pokémon

### ISSUE THREAD

**Issue by X-Driving** [kwsch/PKHeX#3261]
Hi, 

I am contacting you to report a problem with the PID of Pokémon

I'm not sure if it's a good idea to use the PkHex update after the release of Pokémon Sword and Shield, but it's a good idea to use the PkHex update after the release of Pokémon Sword and Shield.

Except that since then, many updates have passed and my pokémon are recognized as hack (+300) 

The problem is often related to the PID but in the details we will often see the memory related to the pokémon, other cases are related to evs and experience, knowing that in the last games we can have a lot of super candy so it remains legitimate 

If it's possible to do something about it 

Thanks to you

![screen1](https://user-images.githubusercontent.com/91772384/135704444-54ab89b9-788b-4502-a3c5-5efeac5d7347.PNG)
![screen2](https://user-images.githubusercontent.com/91772384/135704445-c47302ae-86de-4e4e-8ad6-ff534cb8e256.PNG)

**Comment by ReignOfComputer** [comment]
Are these Pokemon created by you, or caught in-game without any modifications?

**Comment by X-Driving** [comment]
Yes i create all

**Comment by kwsch** [comment]
Working as intended. PKHeX knows all the legality rules and flags your hacks correctly.

**Comment by X-Driving** [comment]
> Working as intended. PKHeX knows all the legality rules and flags your hacks correctly.

not all the rules exactly

**Comment by Masamune3210** [comment]
I can almost guarantee that it's an issue with your gens rather than pkhex. Look at what its reporting, a missing memory in this case, and either fix the issue

**Comment by X-Driving** [comment]
> I can almost guarantee that it's an issue with your gens rather than pkhex. Look at what its reporting, a missing memory in this case, and fix the issue

The problem is related to the fact that this update of Pkhex is not able to generate PID, moreover let us admit I begin the adventure with a Froakie resulting from an egg, at this time it is legal, but when I will give him 99 super candy, it will be recognized as hack because 0 EV in the stats and for the experiments, it is about a problem to be corrected in PkHex

**Comment by X-Driving** [comment]
All my pokémon that make up the living dex of SwSh with DLC1 + DLC2 have no EV and experience as new linked to level, not even 1 exp as it is part of the legality rule. And even if they do have EVs, there are bays that take away EVs that is still legal.

I would have liked to send my backup for you to see for yourselve

**Comment by ReignOfComputer** [comment]
Again, working as intended. Have a good day.

**Comment by X-Driving** [comment]
It works but there is this "rule of legality" detail to correct, thanks in advance

**Comment by Masamune3210** [comment]
You really aren't going to quit are you...

**Comment by X-Driving** [comment]
> You really aren't going to quit are you...

- I made an account on github on purpose to report this problem
- You declare it solved when it's not
- This problem does not exist with older versions of pkhex
- Pkhex is not able to generate PIDs anymore and for proof
- The problem is still not solved (although it should be solved in the next software update) 

Unless you have another program that generates PIDs and just copy/paste them, Pokegen's was great but unfortunately it's only compatible with DS.

I'd find it abusive to have made an account and everything for nothing at all

**Comment by ReignOfComputer** [comment]
Feel free to get a refund.

**Comment by X-Driving** [comment]
> Feel free to get a refund.

Don't hesitate to learn how to do an update correctly ;)

**Comment by Lusamine** [comment]
I do not see any bugs.  Your hacked Pokémon are hacked, and the program recognizes it correctly.  The instructions say not to report issues with hacked Pokémon.  Please only report errors with legitimate data you obtained by playing the game properly. 

Leveling up a Pokémon with no EVs does not make it flag illegal as you claim. 

Finally, use the encounter database if you don't know how to generate PIDIV.

If you are unhappy for time lost creating an account to report issues, I would suggest looking into how to use the program (Google to find other people with the error) and reading the instructions before opening an issue.
