### ISSUE TITLE
Legal Pokemon

### ISSUE THREAD

**Issue by X-Driving** [kwsch/PKHeX#3262]
![screen1](https://user-images.githubusercontent.com/91772384/135751241-9db939de-5ea0-4a48-a5ba-c94a252d3207.PNG)
![screen2](https://user-images.githubusercontent.com/91772384/135751243-cabb22a4-2e22-4731-b1dc-86b3d791757f.PNG)
![screen3](https://user-images.githubusercontent.com/91772384/135751244-91dbc674-97ea-4907-807a-8364f3c6d78c.PNG)
![screen4](https://user-images.githubusercontent.com/91772384/135751252-66c390a7-67f3-446f-8bc4-dc5b3f30dd36.PNG)

**Comment by Lusamine** [comment]
Please learn to read and quit spamming the repo.
