### ISSUE TITLE
[Legality Report] - Jungle Celebi 

### ISSUE THREAD

**Issue by albertodev01** [kwsch/PKHeX#3264]
**Describe the problem**

When I try to import a Jungle Celebi (the event one) it's reported as illegal

**To Reproduce**

Just drag & drop the file (wondercard) and PKHeX will generate the Pokémon.

[jungle_celebi.zip](https://github.com/kwsch/PKHeX/files/7307055/jungle_celebi.zip)

Direct download is [here](https://projectpokemon.org/home/files/file/4586-western-release-jungle-celebi/)

**Expected behavior**

PKHeX shouldn't complain about the illegality of the pokémon

**Screenshots**

![error](https://user-images.githubusercontent.com/2848696/136465424-e16b9973-d693-4008-acdb-9f5dbc6898a1.png)

**Additional context**

This event just released (today, October 7 2021) and that's why it's not yet in the event database

**Comment by Lusamine** [comment]
The wc needs to be added to an `mgdb` folder in the same directory, or you need to wait until next stable release when it's bundled into the program.
