### ISSUE TITLE
GSC .dat legalities

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#3266]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why fabricated data does not pass the legality check.

For GSC, any Pokemon that evolves by direct trade is flagged as an outsider for some reason. This only affects the .dat extensions of the save, and works fine on .sav for some reason.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

Check out a legal Graveler, Machoke, Haunter, and Kadabra on the .dat extension of a GSC save file.

**Expected behavior**

Legal on .dat extension, too.

**Screenshots**

Here's how it looks on .dat:
![error](https://user-images.githubusercontent.com/43196464/136490682-3c41674d-cd22-4049-9efb-d69e567f3ef5.jpg)
![error2](https://user-images.githubusercontent.com/43196464/136494306-bd03b449-0c02-491b-a6c6-0cb1d7f7818a.jpg)

Here's .sav:
![error1](https://user-images.githubusercontent.com/43196464/136490756-5ace66e8-a24c-4a29-a5e5-5bb99aa74cd3.jpg)
![error3](https://user-images.githubusercontent.com/43196464/136494321-f0ad249c-7890-473a-a76b-06aa11435803.jpg)

**Additional context**

N/A

**Comment by kwsch** [comment]
Might be mis-applied to Gen1...
