### ISSUE TITLE
Request: Rival name editing (Gen 1-5)

### ISSUE THREAD

**Issue by FeralFalcon** [kwsch/PKHeX#3268]
Hey again, and thanks so much for the previous requests. :)

I just have one more request, and that is adding the ability to edit your Rival's name in the games that don't include it currently.
So far, it's editable in FRLG and LGPE. Implementing it for the other released games would really complete it thus far -- especially DP in which it's so far editable in Pokesav DP, and that'd be the big nail for Pokesav's coffin.

These are the starting offsets for the games which have custom Rival naming that aren't implemented into PKHeX yet:

Gen 1 (JPN) = 0x25F1
Gen 1 (US/EU) = 0x25F6
Gen 2 (JPN) = 0x2017
Gen 2 (US/EU) = 0x2021
Gen 2 (KOR) = 0x2021
DP = 0x25A8
Pt = 0x27E8
HGSS = 0x22D4
B2W2 = 0x23BA4

I suppose you can add them via Block Data editing like the previous request if you feel it's not worthwhile to implement them into a GUI. I know you can edit Colosseum's Rui's name there, too.

Thanks once again.

**Comment by FeralFalcon** [comment]
Thanks so much, @kwsch! :D

However, I've ran into some quirks on the latest build https://github.com/kwsch/PKHeX/commit/3ad0e29f1981262f92722873a57aa973d1d69f59...

-DPPtHGSS only displays the first 4 characters, cutting off afterwards.
-B2W2 cuts off after 3 chars, but if the name is 3+ chars it will always display a � symbol at the end. (e.g. Hugh becomes "Hug�", Mac becomes "Mac�" etc. etc.)

**Comment by kwsch** [comment]
Thanks, revised: https://github.com/kwsch/PKHeX/commit/6304ef2006f87dce227f2e8ae97063e00d2cf238
