### ISSUE TITLE
[feature request] Add the ability to modify Chatot's Cry/Chatter noise

### ISSUE THREAD

**Issue by zurgeg** [kwsch/PKHeX#3269]
**Is your feature request related to a problem? Please describe.**
It'd be nice if I could change Chatot's Chatter noise.

**Describe the solution you'd like**
The ability to modify the sound of Chatter

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by kwsch** [comment]
Needs to be documented where & how the data is stored prior to it being able to be implemented.
