### ISSUE TITLE
Changing the PID of a Pokemon that changes its nature doesn't change the colors in the Stats tab.

### ISSUE THREAD

**Issue by valthisse** [kwsch/PKHeX#3272]
**Describe the bug**
This is a minor bug, but when you change the PID of a Pokemon and this PID changes the nature, when you navigate to Stats tab, this tab doesn't have the colors according to the new nature of the Pokemon.

**To Reproduce**
1. Import the .pk4
2. Change the PID to 0000000F (this PID is from a Modest nature)
3. Cick to Species input and see how changes from Jolly to Modest the Nature input.
4. Navigate to Stats tab. This tab has the colors of Jolly nature, no Modest.

**Expected behavior**
It is expected that when the nature of the Pokemon changes, the colors of the corresponding nature will be reflected in the Stats tab.

**Screenshots**
N/A

**Additional context**
Modify any text of the Nature input triggers the change to Stats tab.

[418 ★ - BUIZEL - 5E680000000D.zip](https://github.com/kwsch/PKHeX/files/7346809/418.-.BUIZEL.-.5E680000000D.zip)

**Comment by kwsch** [comment]
In generation 4, the ability ID is stored separately from the PID and can be disjointed from the correlation by event gifts or colosseum/XD encounters.

Nature is 100% derived from the PID, hence it updating the nature selection when the PID changes.

Probably just missing a call in that update method to refresh the stat amp colors
