### ISSUE TITLE
[feature request] Editing Dreaming Pokemon in Gen 5

### ISSUE THREAD

**Issue by zurgeg** [kwsch/PKHeX#3274]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Ability to edit the dreaming Pokemon data stored at 0x1D309

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
Hex editing the save to put the encrypted Pokemon data in a box, but this is a somewhat janky solution

**Additional context**
N/A

**Comment by kwsch** [comment]
Already implemented, use the latest release. Visible on one of the sav tabs.

https://github.com/kwsch/PKHeX/commit/c0d748a9751e82aa2dbc1c6106f868470cf52000
