### ISSUE TITLE
EMR: Battle frontier symbols get set to 0

### ISSUE THREAD

**Issue by BartTerpstra1** [kwsch/PKHeX#3279]
when using misc edits on a save file, battle frontier symbols get set from their current values to [none]. it can read correctly if they have been attained, but saving misc edits sets them to 1 less than you loaded them as.

**To Reproduce**
1. open a save with battle frontier gold or silver symbols
2. go to misc>battle frontier> save
3. close misc editor
4. open misc editor
5. you're symbols are now all silver or [none] respectively

**Expected behavior**
i expect the symbols to be saved as what is shown when i view the battle frontier tab, whether i have edited them or not.

**Additional context**
i have also had issues with getting working ferry tickets, but this is probably unrelated.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/338bc562bb9ed90c49752acf52381ab3f5da6a18/PKHeX.WinForms/Subforms/Save%20Editors/Gen3/SAV_Misc3.cs#L380-L388
https://github.com/kwsch/PKHeX/blob/338bc562bb9ed90c49752acf52381ab3f5da6a18/PKHeX.WinForms/Subforms/Save%20Editors/Gen3/SAV_Misc3.cs#L392-L402
