### ISSUE TITLE
Pokemon Management UI Feature Requests

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#328]
- ability to move/swap Pokemon in Party Box, like BOX
- ability to deposit Party Pokemon (leaving 1st Pokemon)
- ability to drag party Pokemon to be deposited in open box slot.

**Comment by Ninjistix** [comment]
thanks @evandixon

**Comment by kwsch** [comment]
Duplicate with https://github.com/kwsch/PKHeX/issues/295

**Comment by Ninjistix** [comment]
missed that one, ill close this
