### ISSUE TITLE
Cannot open Brilliant Diamond save file

### ISSUE THREAD

**Issue by derbayer36** [kwsch/PKHeX#3283]
Title, I got this error:

![Untitled](https://user-images.githubusercontent.com/24847629/140910541-4ccfc2bf-4d3d-45cd-baba-73ceb449624c.png)

**Comment by ReignOfComputer** [comment]
Seriously. Shoo.

**Comment by derbayer36** [comment]
> 
> 
> Seriously. Shoo.

Lol. Something must be done about this right?

**Comment by derbayer36** [comment]
> 
> 
> Seriously. Shoo.

I'll leave the save file here anyway.

https://mega.nz/file/w8km2R5D#bI_AXfsqkjiOErKXEOfLKyUYbfVknFtMJ3ma_5_7vsY

**Comment by Masamune3210** [comment]
Games not even out yet, why would you think it has support here lol

**Comment by Kreygasm13** [comment]
It was actually leaked. People got it early into their hands. File format is however different from older titles. instead of main its SaveData.bin

**Comment by Lusamine** [comment]
The game is not officially released.  Support for an unreleased game should not be expected or requested.  Be patient, it will be ready when it's ready.

**Comment by Masamune3210** [comment]
@Kreygasm13  Supporting an unreleased game is a good way to have lawyers on their way. Ergo, no support until official release
