### ISSUE TITLE
Spiky-Eared Pichu is marked as valid if it has Sinnoh ribbons (should be invalid)

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3286]
**Describe the problem**
Simply put, a Spiky-Eared Pichu cannot be traded at all, and so it can only have HGSS ribbons. Sinnoh Champion, the contest ribbons, and the Resort Area ribbons are unobtainable, yet PKHeX marks the Pichu as okay.
The only 10 ribbons it should have are `Alert, Careless, Downcast, Effort, Footprint, Legend, Relax, Shock, Smile, and Snooze`. 7 of these are free on each day of the week, and the other 3 can be obtained by anything.

**To Reproduce**
Grab it from the encounter database and shift click the "Give all" in the ribbons editor. It has Sinnoh's ribbons which it should not.

**Comment by sora10pls** [comment]
Same issue with Cosplay Pikachu and Kalos ribbons (e.g. Kalos Champion).
