### ISSUE TITLE
Potential Feature: Undo/Redo History

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#329]
Is it possible to add a history for the Undo and Redo Buttons. For instance, go to be able to go back 5 actions instead of the last one, with all the changes that were being made or what was added to the Pokemon like "Ability changed to Mold Breaker" or changed level to 100.

**Comment by kwsch** [comment]
Seems a little excessive, the undo-redo is meant to help revert changes made accidentally. Coming up with a way to describe what was changed in the slot seems like a lot of work for little gain.

**Comment by ricksee** [comment]
@kwsch I just thought just like Microsoft Word it can track changes in the program. Just to not overload the program, it can just track like the last 5 or 10 changes.

**Comment by evandixon** [comment]
It _is_ similar to Word, in that a history of changes is stored, but adding a list of them would require a way to display the changes in a user-friendly manor.

I think it'd be cool if this was a thing, but _I_ certainly wouldn't want to code it, so I can't reasonably expect anyone else to want to code it either.  And as kwsch said, it wouldn't be that much of a gain.

**Comment by ricksee** [comment]
@kwsch @evandixon Well fair enough. Im just here to give ideas to see what improvements can be made to the program. I do not expect every request to be done. Thanks for listening anyway.

**Comment by kwsch** [comment]
By default, the undo-redo has a stack of 20 slot actions it can undo. It's only for slot editing.

Undoing pkm field editing isn't something that would be useful, just re-load the pkm from the source file/slot.
