### ISSUE TITLE
BDSP Version doesnt support batch edit inputs.

### ISSUE THREAD

**Issue by Atomic646** [kwsch/PKHeX#3292]
tried using shsw batch commands and doesnt work.

**Comment by kwsch** [comment]
Unable to replicate.
![image](https://user-images.githubusercontent.com/6393368/142717103-c36c2148-b915-4567-8ecd-55f7ec14a6be.png)

**Comment by Atomic646** [comment]
![254741687_5100548399996497_3417223240526233571_n](https://user-images.githubusercontent.com/33273602/142717662-5610b8dc-9309-4a6b-9fce-66b20fcd954a.jpg)

Also my int32 is red for some reason.
