### ISSUE TITLE
Invalid Moves for some Pokemon (Brilliant Diamond)

### ISSUE THREAD

**Issue by x7l7j8cc** [kwsch/PKHeX#3293]
**Describe the problem**
This moves can be learned by Level up or TM.
Anyway, this pokemon are Legit obtained in-game by capturing (Abra and Snover)  or hatch egg (Riolu).

**Screenshots**
![5fb41c32ea5b2bb86ec7d81bf41ad880](https://user-images.githubusercontent.com/526407/142718104-a3c83f02-8b2f-4c94-a9ca-8cb1d50ac06f.png)
![6362097129bf0e7636a1c605b18ae32f](https://user-images.githubusercontent.com/526407/142718106-3c6e3216-18ef-4ae0-bfeb-c970f264a928.png)
![ce6fba693458343ad855b7288ea60469](https://user-images.githubusercontent.com/526407/142718108-85b27228-c8ab-42a8-bde8-e85f5fb93824.png)

**Comment by x7l7j8cc** [comment]
@kwsch Thanks for fix.
Anyway, why Technical Records (Sword and Shield) and Dynamax / Gigantamax , is Enabled in BD and SP?

![1b59bbb196c7dc7fe51cf2cd5378e4e8](https://user-images.githubusercontent.com/526407/142719082-8328186b-1d18-42fe-8f85-79dbebc41f7b.png)
![86fb50f626afb45d69840c1d0cfafb54](https://user-images.githubusercontent.com/526407/142719083-55231602-d6b2-4df6-a29f-db4715553d48.png)

**Comment by kwsch** [comment]
> @kwsch Thanks for fix. Anyway, why Technical Records (Sword and Shield) and Dynamax / Gigantamax , is Enabled in BD and SP?

Because they still exist for the format, they just aren't mutable in-game. With future connectivity updates to Sword/Shield, they may end up having data for things transferred into BDSP.

Same as the "Favorite" mark from LGPE still being a possible field in G8PKM structures; people can mess it up/sneak it, so PKHeX checks for it and allows it to be edited.

**Comment by x7l7j8cc** [comment]
Ok..
Anyway another problem..

Shaymin and Darkrai (Event Triggered) and Captured, flagged as Illegal.
![a51ac70b13b7eeda77af91f9e6f39a6a](https://user-images.githubusercontent.com/526407/142720802-367dd7fe-a68d-49e7-9ea7-a98b4cd8a35c.png)
![f75724b1fa44db8738dc2aa06a43167d](https://user-images.githubusercontent.com/526407/142720803-5cb32f59-2262-43d2-ab53-95b09611bd99.png)

**Comment by Lusamine** [comment]
Those events are not released so they are illegal.

**Comment by x7l7j8cc** [comment]
@Lusamine  yes, but the pokemon is caught in-game.. Events are only to give you the Member Card and Oak's letter.
So, indifferently if I got them with the tickets given by nintendo or activated with pkhex, this only activates the event for the capture, it does not give you the pokemon itself.

Correct me, if im wrong.

**Comment by sora10pls** [comment]
Oak’s Letter and Member Card are not officially released yet, so those encounters with Shaymin and Darkrai respectively are not available right now, and are therefore illegal.

If you had to cheat to accomplish it, you should know why they’re flagged.
