### ISSUE TITLE
Rhydon with Ice fang from Grand Underground falsely flagged as illegal (BDSP)

### ISSUE THREAD

**Issue by derbayer36** [kwsch/PKHeX#3295]
**Describe the bug**
Rhydon with Ice fang from Grand Underground falsely flagged as illegal 

**To Reproduce**
Catch Rhydon from the Grand Underground (056)

**Expected behavior**
All Pokemons from Grand Underground have one egg move learned and Rhydon has Ice fang:

https://pokemondb.net/pokedex/rhydon

**Comment by Lusamine** [comment]
Can you provide a file of a legitimately caught, unedited Pokemon?
