### ISSUE TITLE
Mesprit catch location falsely flagged as Illegal (BDSP)

### ISSUE THREAD

**Issue by derbayer36** [kwsch/PKHeX#3296]
**Describe the bug**
Caught Mesprit legally but PKheX flags it as illegal (Unable to match an encounter from original game).

**To Reproduce**
Catch Mesprit in the wild after he escapes the cave.
Use PKHeX

**Comment by Lusamine** [comment]
Again, please provide legitimately obtained and unedited Pokemon files.

**Comment by derbayer36** [comment]
> Again, please provide legitimately obtained and unedited Pokemon files.

Caught it in route 220 while surfing.

[481 - Mesprit - 0381BDB3CB8C.zip](https://github.com/kwsch/PKHeX/files/7574320/481.-.Mesprit.-.0381BDB3CB8C.zip)
