### ISSUE TITLE
[BDSP] Trainer Data Editor

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#3297]
**Describe the bug**
Trainer Data Editor doesn't recognize earned badges properly, but Event Flags recognizes them fine.

IDs in trainer info are fine, but it's showing 5-digit TID and SID instead of TID7 and SID7.

Map position reads 0 for everything, same for Game Started time (not sure about Hall of Fame, I'm not there yet.)

**To Reproduce**
1. Load BD/SP save file
2. Check Trainer Info tab

**Expected behavior**
The data should be read correctly, and IDs shown as ID7

**Screenshots**

<details>

  ![image](https://user-images.githubusercontent.com/43770697/142731395-17c630bc-d7c2-48bf-adc0-c4d0e1441ce8.png)
  ![image](https://user-images.githubusercontent.com/43770697/142731419-93bbbdb8-7775-4bb3-a1fa-440388628707.png)

</details>

**Additional context**
If the offsets for Map Position and Game Started/Hall of Fame times are not known, it might be worth greying out those fields, to make it clear they can't be edited yet.

**Comment by kwsch** [comment]
Trainer editor is currently using the generic one for past games; a specialized one wasn't ready in time for the initial release.
