### ISSUE TITLE
Crash upon opening BD save file

### ISSUE THREAD

**Issue by Cu3PO42** [kwsch/PKHeX#3298]
**Describe the bug**

I have checked out and built the current `master` branch (at the time of writing, this was commit `1d3d3176659ffaaadd77424d27bfe845d3472b44`) and attempted to open a Brilliant Diamond `SaveData.bin` from a save I dumped from my Switch. PKHeX crashes as the result of an unhandled `ArgumentOutOfRangeException`. It is raised [here](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Saves/Substructures/Gen8/BS/MyStatus8b.cs#L78). The value that `ROMCode` has in my case is 195.

Opening my `Backup.bin` causes no such crashes. The game starts without any indication that its main save file is corrupt and I am exactly at the spot I last saved at.

Out of curiosity, I have moved a few tiles in game, saved again, dumped the save and tried to open the new one as well. The same error occurs with the same value of `ROMCode`. Again, my `Backup.bin` opens just fine.

**To Reproduce**
1.  Go to the 'File' menu
2. Click on 'Open...'
3. Select my save file

**Expected behavior**
PKHeX loads the save file into its editor or displays an error explaining the save is corrupt rather than crashing.

**Additional context**
I am running the latest Switch FW and have downloaded all applicable updates to BD. My Switch is not running any CFW, I have dumped the save from its NAND.

I am happy to share the save files with anyone who wants to debug this issue, however, I would rather not share it publicly. Please let me know if and how you would like to receive the files.

**Comment by kwsch** [comment]
Invalid ROM codes are invalid save files, hence the exception message.

There's no way to mutate the ROMCode from 0/1 to 195.

**Comment by kwsch** [comment]
Did you by chance use the Trainer Info editor? Not sure if there's anything related to overlapping/overflowing into other regions. Another user may have an issue with opening the trainer card...

**Comment by Cu3PO42** [comment]
I understand that this shouldn't happen and looks invalid on the surface, but this is an entirely unedited save file that I got straight from my Switch. It has never been modified with external tools. All checksums in the SaveFS are valid as well.

For context, although this is most likely irrelevant in this instance, I barely got my first gym badge and this is the first I have dumped the file with the results described above.

The byte at 0x79bdf is indeed 195 in my file. I manually changed that byte to 0 and the file opens now, but my OT information is definitely incorrect. My actual OT is 'Copper', displayed is 'ᚒ쾸㝝む䁼䣻㈓ﻧ�㵩掞ᴩ' which I assume is just the result of interpreting some other data as UTF-8/UTF-16 or whatever it is in this game. The string Copper (UTF-8 encoded) does not appear within my save file, but appears multiple times in my `Backup.bin`. So it would appear there is indeed an issue Trainer Information. Further, my party is displayed as empty, but actually contains 6 Pokémon. This is correctly reflected within my Backup.bin as well and It all appears fine in-game.

All of this would lead me to believe that `SaveData.bin` is corrupt if it weren't for the fact that it loads up without complaint and when I saved again, the issue persisted. The save file changed between these two revisions, so it doesn't appear that my game is using Backup.bin exclusively.

**Comment by kwsch** [comment]
Mentioned you via discord; can always try copying the `SaveData.bin` to the `Backup.bin` and see if the game loads with both files being the same "bad" file that PKHeX doesn't like. I suspect it's silently falling over to the backup without notifying you, giving the illusion that the main savedata is valid when it is not.

**Comment by kwsch** [comment]
Discussed this issue in Discord -- we've noticed the first half of the save file is not completely initialized at the start of the game, and has data up to 0x80000 filled with empty PB8 data. Likely due to not allocating zeroed-data (unity, yay).

Advice for users who experience the same issue: progress sufficiently in-game to get all the data initialized by the game. Maybe save twice :)
