### ISSUE TITLE
Ability to edit Outfits, Stickers, Poffins, and Accessories

### ISSUE THREAD

**Issue by MewtwoFanz** [kwsch/PKHeX#3299]
I'm really annoyed that we cannot edit stuff like outfits or stickers. 

**Describe the solution you'd like**
I would like to see a tab where we can edit miscellaneous things like Outfits, Stickers, and Poffins. 

**Describe alternatives you've considered**
I would be fine if you were able to edit poffins, accessories, outfits and stickers in an updated trainer editor. 

**Additional context**
N/A

**Comment by sora10pls** [comment]
Outfits are already editable and unlockable with the block data editor and event flag editor.

You may find it annoying, but adding features like this takes time to research, document, and implement in an easy to use way. If it's unknown how to view/edit them, how can PKHeX view/edit them?

**Comment by AyanamiRei1** [comment]
Yeah it's quite easy honestly.

![image](https://user-images.githubusercontent.com/25233407/142748408-ef3a65e5-4b61-4be7-8d68-fddefcde86b6.png)

Click on Block Data

and scroll down until you see "My Status" click the arrow and you'll see FashionID.

**Comment by MewtwoFanz** [comment]
Yes, but I also want to edit stickers, accessories, and poffins. Does anyone know if that's possible yet?

**Comment by kwsch** [comment]
> Yes, but I also want to edit stickers, accessories, and poffins. Does anyone know if that's possible yet?

It's not. Feel free to document where & how that data is stored, and reply back here. We aren't taking community research requests at this time, especially for cosmetic tweaks.
