### ISSUE TITLE
[XY] Friend safari slot unlocking

### ISSUE THREAD

**Issue by suloku** [kwsch/PKHeX#330]
I've been researching friend safari a little. It relies on the friend list on the 3DS console, each friend code gives a safari with 3 pokemon, the 3rd pokemon is only accessible if the friend has been on the PSS at the same time as you.

Turns out the lock are bitflags, stored on a single byte.

Friend safari list offset: 0x1E800
I holds up to 100 entries, each one being 0x15 bytes in size. The byte that controls the lock status for each safari entry is the last one. I don't have a clue about what the other bytes do, but since the entries get updated at boot depending on the console's friend list I don't think there's any point.

Here are all the possible values (i though an image would be better):
https://s17.postimg.org/f90hfmrmn/safari.png

It would be great if this could be implemented at some point, there's probably other priorities right now but I think this is rather useful since less and less people will play gen VI.

I'll try to make a list of 71 unique friend codes that allow to have every single friend safari pokemon in the game.

**Comment by suloku** [comment]
I've just realized friend code exchanging has been going forever and there are sites like these:

http://friend-safari-exchange.tumblr.com/
http://safaricode.com/users

Getting the 71 code combinations shouldn't be diffult searching those site, if anyone wants to help compiling please contact me.

**Comment by Shinigati** [comment]
Correct me if i'm wrong but don't we need to add people to unlock the friend safari? even if we did modify the save file with a dummy safari list the game will rescan the friend list on every launch afaik which will remove them to match only those on your system.

**Comment by kwsch** [comment]
Since it depends on the console's stored FC's, not something that can be reliably edited. Better to just hack in the pkm :)

**Comment by suloku** [comment]
@kwsch Unlocking the third slot has nothing to do with the actual friend list. The normal way to unlock the 3rd slot is for you and your friends to be online simultaneously, the feature I request removes this need.

This also allows unlocking the 3rd slot for friends you may have in your friendlist that don't play XY.

Being able to modify/fake the friend list (with is something unrelated to pkhex) still needs the "unlock third slot" feature too, and I'm talking about the friend file in the 3DS, not the list stored in the savegame.

**Comment by Shinigati** [comment]
The feature you're asking for actually requires modifying either the rom or the 3ds friends list file and is not possible through save file editing, so i suggest not asking for the impossible, this github is about pkhex and as you suggested this has nothing to do with pkhex so i suggest asking another dev that works in that field.

**Comment by kwsch** [comment]
Should be documented on the forums first prior to being a candidate for implementation. I'd like to not inter mix research requests and feature requests.

**Comment by ReignOfComputer** [comment]
Noting @suloku's unlocker tool here: https://github.com/suloku/gen6_safari_mirage_tool

**Comment by greenDarkness** [comment]
So basically in order to use this tool I'd need to dump this friend file, modify it with the tool, and then inject it back into the 3ds?

If so I think it would be a nice addition to PKHeX.

**Comment by suloku** [comment]
Clarification:
- When the game runs the friend list gets saved in the savegame as 2HIDDEN+1LOCKED safari slots
- The 2 HIDDEN slots are revealed by encountering the pokémon in the safari.
- The 3rd slot gets unlocked (legally) by being online at the same time as your friend. After that, it will appear as a 3rd hidden slot until you encounter the 3rd pokémon in the safari.
- Adding/removing friends from the 3DS list will update the list in the savegame, but any friend that  is still in the list will be kept in the save, alongside the hidden/lock status.

This is the code needed to fully unlock (all 3 slots unlocked + unhidden) all safaris present in the savegame (+checksum fixing):
`//Unlock safaris
				  int i;
				  for (i=1;i<101;i++)
				  {
				    if( savebuffer_XY[0x1E7FF+(0x15*i)] != 0x00 )
				        savebuffer_XY[0x1E7FF+(0x15*i)] = 0x3D;
				  `}``
This image shows all possible values for the slot status (I know they are bitflags, but this felt more graphic): https://s17.postimg.org/f90hfmrmn/safari.png

What this allows to do:
- Access the 3rd safari slot (and capture the pokémon) without needed to be at least once online at the same time as your friend.
- Access 3rd safari slot of friends that don't own/play

Altering the friend list to have desired safaris is unrelated to pkhex and I should have left that research outside of this issue, the confusion is my fault and I'm sorry, but altering the friend list will still need the unlock feature for maximum benefit.

I hope everything is clear now.
