### ISSUE TITLE
Certain berries missing from item editor

### ISSUE THREAD

**Issue by Thamusicgod5** [kwsch/PKHeX#3301]
**Describe the bug**
Certain berries are missing from the PKHeX item editor for BDSP. 

**To Reproduce**
I went into the item editor and added all berries and then went into the game into Floaroma town to trade for stickers and noticed some were missing. I then went back into PKHeX and noticed the berries were no where to be found, even as held items. 

**Expected behavior**
Just letting you guys know so that it can be fixed and appear in PKHeX. No rush I know you guys are busy! 

**Screenshots**
Showing the berries missing in game. 
![724D1F35-6FB0-48A8-8922-51D45984C6DC](https://user-images.githubusercontent.com/94777638/142753260-bbd706b3-d3bb-48d3-bb54-ff444f6246da.jpeg)
![C0CCB172-01E7-487A-8E19-18DE9F740240](https://user-images.githubusercontent.com/94777638/142753263-aa084636-9966-454b-8ab7-7cf659505661.jpeg)
![F306B262-ED06-4BDF-AC68-74E3D823FEE9](https://user-images.githubusercontent.com/94777638/142753266-1a9530af-f0dc-4597-8c51-5fe89e745566.jpeg)

**Additional context**
A few are: Nomel, Rabuta, Magost, Cornn, Wupear, Nanab, Bluk, and Razz but there may be more.

**Comment by LegoFigure11** [comment]
Watmel, Durin, Belue, Spelon, and Pamtre are also missing, amongst potential others.
Loading up a Pokemon holding one of them in the editor clears its item slot, though viewing it in the box will display the correct held item icon.
