### ISSUE TITLE
[BDSP] Trading Evolutions always marked as illegal

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#3310]
Trying to make a living dex, All trade Evolutions are marked as Illegal, regardless of level. 

Make any of the following pokemon based off of a pre-evolution:

Alakazam
Machamp
Golem
Gengar
Politoed
Slowking
Steelix
Scizor
Kingdra
Porygon2
Huntail
Gorebyss
Weavile
Rhyperior
Electivire
Magmortar
Porygon-Z
Duskull

**Expected behavior**
Pokemon should be legal

**Comment by ReignOfComputer** [comment]
Bet it's because you didn't specify a HT Trainer.

**Comment by ReZeroEmiria** [comment]
Actually yes, apologies.
In that case, not sure if it's an easy addition but can you change the invalid prompt from 
"Invalid: Evolution not valid (or level/trade evolution unsatisfied) " to something that more directly references the HT Trainer?

Also 1 question, how does the PID generation on roamers (Cresselia and Mesprit) work? Trying to generate a few specific spreads on them but have no idea how it functions so I don't get PID Mismatch.

**Comment by ReignOfComputer** [comment]
See: https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/RNG/Roaming8bRNG.cs

You'd need to work backwards.

**Comment by Lusamine** [comment]
Please don't submit fabricated data as bugs.
