### ISSUE TITLE
"Invalid: Egg must be not nicknamed"

### ISSUE THREAD

**Issue by ghost** [kwsch/PKHeX#3311]
**Describe the problem**
If an egg has Nicknamed checked, PKHeX (BDSP) complains that the egg is invalid. Except that checking the "Is Egg" flag on a Pokémon will also automatically check the Nicknamed flag, and the Manaphy Egg wondercard also shows up with Nicknamed flag by default. Either the legality check is bad, or PKHeX is erroneously applying the Nicknamed flag when loading an egg.

**To Reproduce**
Load Manaphy Egg wondercard from mgdb, or click the Is Egg checkbox on any Pokémon

**Expected behavior**
The legality check and/or nicknamed status of the egg should be valid

**Screenshots**
<details>

![image](https://user-images.githubusercontent.com/43770697/143135494-54257aeb-80eb-4143-b014-bc22e4e86ed9.png)

</details>

**Additional context**
20211121

**Comment by kwsch** [comment]
The legality check is correct, the issue is that the GUI doesn't know if it needs the flag or not, so it goes with the usual logic of "yes".
