### ISSUE TITLE
Magearna & Zeraora gifts are marked as invalid with the new Weight/Height checks

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3313]
**Describe the problem**
The original colored Magearna event and the shiny Zeraora event always come with 0 height and weight (according to the Mystery Gift db) so they are marked as invalid according to the parse settings even though they are considered gen 8.

**To Reproduce**
Grab them from the Mystery Gift database
![image](https://user-images.githubusercontent.com/29823718/143387248-e264adbc-bde8-4f0d-8693-92ddbe3339ad.png)

**Comment by kwsch** [comment]
Resolved by latest commit: https://github.com/kwsch/PKHeX/commit/039095d75ca10d0684a4b5c0e908a179aaf03c6a
