### ISSUE TITLE
Issue with Magnezone legality

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3314]
Hi, I just looked at my BDSP saves for a legality check and PKHeX is saying that my Magnezone which I legit caught as a magnemite and then evolved is illegal for knowing zap cannon and "unable to match an encounter". Ill attach the file below. Thanks
[462 - Magnezone - 2316659C51CA.zip](https://github.com/kwsch/PKHeX/files/7610896/462.-.Magnezone.-.2316659C51CA.zip)

**Comment by kwsch** [comment]
Similar issue as Feebas having multiple evolution types to Milotic, with the more restricted one (trades) being checked first.

Will have to rearrange the evolution data for that...

**Comment by NinFanBoyFTW** [comment]
Hey thanks for fixing that issue. I just checked again with the latest commit and I have one more like this, being this milotic I legit traded and evolved as feebas
[350 - Milotic - 57AFA827A961.zip](https://github.com/kwsch/PKHeX/files/7620644/350.-.Milotic.-.57AFA827A961.zip)

**Comment by ReignOfComputer** [comment]
You evolved the Milotic with Prism Scale trade, can the Prism Scale be found in BDSP?

**Comment by NinFanBoyFTW** [comment]
I may be mistaken then. I thought that it was available in the underground but that may be a rumor

**Comment by Lusamine** [comment]
Heart Scale exists there, not Prism Scale.  Mon is illegal if evolved with an illegal item.

**Comment by NinFanBoyFTW** [comment]
I just realized I was getting mixed up with the available trade items like the deep sea scale and the dragon scale. Is there maybe a way to make a feature when adding items to games to add another button next to the "Give All" button that says something like "Give All Legal Items "excluding non obtainable items? this seems like it would also be useful in other games like sword and shield where if you were to have a black list of all unobtainable items, you wouldn't have a bag full of those dynamax crystals that are not even available and other items like that. Maybe just a thought?
