### ISSUE TITLE
legality issues with egg bred pokemon

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3323]
Hi I just looked at some of my pokemon and some of the pokemon that I bred are now illegal because of the pokeball they have. I never changed the pokeball they are in and it looks like most of the illegal ones are in pokeballs which my Ditto had in the daycare.

Thanks
[285 - Shroomish - 0A13F0569FB5.zip](https://github.com/kwsch/PKHeX/files/7654776/285.-.Shroomish.-.0A13F0569FB5.zip)

**Comment by sora10pls** [comment]
Shroomish can only be encountered in the Great Marsh, which requires it to be in a Safari Ball. Pokémon that are bred with Ditto will always pass down their Ball, not Ditto’s.

**Comment by NinFanBoyFTW** [comment]
See that's weird though because when I bred these other pokemon I got them from someone online and they showed up as legal, and I believe they had a safari ball so I don't know where the poke ball is coming from. Ill test it out in game now
