### ISSUE TITLE
Pokemon residing in Gen 3/4/5 with 255 in all 5 contest stats are falsely flagged legal with less than 255 Sheen.

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3324]
**Describe the problem**
While it is possible for Pokémon in Gen 3 and 4 to obtain 255 in all contest stats via specific sets of Pokéblock or Poffin recipes, all combinations that result in maxed contest stats must also result in 255 Sheen.

Pokémon can freely obtain max contest stats in Gen 6 and BDSP without also having 255 Sheen, due to ORAS Pokéblocks not affecting or taking Sheen into account, and BDSP Poffin recipes that can produce max stats with less than 255 Sheen.

**Expected behavior**
Pokémon that **cannot** have max contest stats without 255 Sheen legitimately, and **should be flagged illegal** with max contest stats and less than 255 Sheen:

1. Pokémon currently residing in Gen 3 and Gen 4.

2. Pokémon that have visited Gen 3 or 4 and currently reside in Gen 5.

Pokémon that **can** have max contest stats without 255 Sheen legitimately, and **should not be flagged illegal** with max contest stats and less than 255 Sheen.:

1. Pokémon currently residing in Gen 6.

2. Pokémon that have been transferred through Gen 6 and reside in Gen 7 or SWSH.

3. Pokémon that have visited BDSP (when/if HOME support releases and allows transfer to BDSP) or currently reside in BDSP.

**Additional context**

Along the same lines, any situation where Sheen would need to be applied for ANY contest stats to exist should flag pokemon with "any contest stats, and 0 Sheen" as illegal, since the value of Sheen should be at least 1 if the Pokéblock/Poffin/Daisy Massage was applied in any game other than ORAS.

- Gen 3 Pokéblocks Recipes for Max Contest Stats (including and excluding E-Reader Berries):
https://www.reddit.com/r/pokemonribbons/comments/11su8j/pok%C3%A9block_recipes_to_give_a_pok%C3%A9mon_perfect/

- Gen 4 Poffin Recipes for Max Contest Stats:
https://www.reddit.com/r/pokemonribbons/comments/11osph/poffin_recipes_to_give_a_pok%C3%A9mon_perfect/

- Daisy Oak's Massages in HGSS raise Beauty, but also raise Sheen (HGSS does not provide a loophole to increase Beauty without increasing Sheen):
https://www.serebii.net/heartgoldsoulsilver/daisyoak.shtml

- Gen 6 ORAS Pokéblocks do not take Sheen into account at all:
https://bulbapedia.bulbagarden.net/wiki/Sheen
"In Pokémon Omega Ruby and Alpha Sapphire, Pokéblocks neither affect nor are affected by sheen."

- Austin John Plays demonstrating that BDSP allows Max Contest stats with less than 255 Sheen (shown at timestamp 22:29):
https://youtu.be/Dw53HqznXUQ?t=1349

**Comment by kwsch** [comment]
Are there any considerations for encounters that can be obtained with a fixed amount of contest stats already awarded?

* EncounterTrade3 (RSEFRLG have 30/5/5/5/5/10 sheen)
* EncounterTrade4PID (DPPt Chatot has 20/20.../0 sheen)

Is there any correlation for sum-average of stats earned earned and the amount of sheen? It appears Gen3 has a 10-earned,10-sheen. Since getting maxed out contest stats also requires maxed out sheen, that is also a 1:1 stat-sum : sheen correlation, which can be checked instead?
