### ISSUE TITLE
Legal Pokemon (Cleffa, Giratina) appear as illegal

### ISSUE THREAD

**Issue by zurgeg** [kwsch/PKHeX#3326]
**Describe the problem**
2 legal Pokemon I have in a Pokemon Platinum save (Cleffa and Giratina) are appearing as illegal:
- The Cleffa has "an invalid PID for it's encounter" (Mt. Coronet, PID is 188BE729, met at Lv. 13)
- The Giratina was encountered in the Distortion World (the static Giratina encounter in Platinum) and it's nickname appears as ???????? even though it appears as GIRATINA in game, although that's a seperate bug, 

**To Reproduce**
This Pokemon (the Giratina obtained just after fighting Cyrus)
![Static Encounter Giratina in Platinum](https://user-images.githubusercontent.com/46549042/145223416-9470540c-50a2-48af-a7ef-aa641d4271c2.png)
Or this Cleffa (Wild Encounter Grass, at met level, caught in Mt. Coronet):
![Mt. Coronet Cleffa](https://user-images.githubusercontent.com/46549042/145254168-1dcb415c-e816-4d0d-929f-96d27f81b296.png)

**Expected behavior**
These Pokemon should be recognized as legal by PKHeX

**Screenshots**
The error I get on Cleffa:
![Invalid PID for encounter](https://user-images.githubusercontent.com/46549042/145254278-7dda1ce7-0083-4ab3-b88c-f9f41fcb9fcb.png)

And the one on Giratina:
![Various validation errors](https://user-images.githubusercontent.com/46549042/145254416-191679db-dfab-46c6-afa8-7a3bcea66bc2.png)

Giratina's "Main" page:
![image](https://user-images.githubusercontent.com/46549042/145254572-83128632-6d09-4c1c-a29e-7e26e1c0a6d0.png)

**Additional context**
N/A

**Comment by zurgeg** [comment]
> Please provide your PK4 data when submitting issues like this.

Alright, I'll get them in a minute. If it helps, I can try make a Pokemon from scratch that can reproduce it too.

**Comment by kwsch** [comment]
Unable to replicate.
![image](https://user-images.githubusercontent.com/6393368/145255726-ea28e4a5-5ffd-4507-8e84-42bce86813c7.png)
![image](https://user-images.githubusercontent.com/6393368/145255981-d427f85f-a10d-4390-b7ff-3783fb1db039.png)

**Comment by zurgeg** [comment]
Here are the PK4 Files: [Giratina and Cleffa.zip](https://github.com/kwsch/PKHeX/files/7677854/Giratina.and.Cleffa.zip)

**Comment by zurgeg** [comment]
Alright, so I just checked my save, and something odd seems to be happening, because my Giratina is showing up as coming from "a faraway place". However, the Cleffa is still completely intact

**Comment by kwsch** [comment]
Cleffa has a bad PIDIV correlation; PID should be A8D92E8B for the IVs that it has (maintaining Modest nature).

27F1E5EB => Lax
A7F165EB => Naive
A8D92E8B  => Modest
28D9AE8B => Timid
17E6D0C1 => Naive
97E650C1 => Rash

188BE729 is none of them, hence it does not have a Method 1 PIDIV correlation (matches no other known correlation), thus hacked/cheats interfering = illegal.

**Comment by zurgeg** [comment]
> Cleffa has a bad PIDIV correlation; PID should be A8D92E8B for the IVs that it has (maintaining Modest nature).
> 
> 27F1E5EB => Lax A7F165EB => Naive A8D92E8B => Modest 28D9AE8B => Timid 17E6D0C1 => Naive 97E650C1 => Rash
> 
> 188BE729 is none of them, hence it does not have a Method 1 PIDIV correlation (matches no other known correlation), thus hacked/cheats interfering = illegal.

Huh, that's odd, I have no clue what happened there, I guess I'll check to see if I had a cheat on or something.
