### ISSUE TITLE
Can't edit Hall of Fame for BD/SP

### ISSUE THREAD

**Issue by yirila7459** [kwsch/PKHeX#3332]
There is no option available for editing the Hall of Fame Records, including the records located on the computer and your trainer card

**Comment by Lusamine** [comment]
This is not a bug.  Needs to be documented what to edit in order for an editor to be made.

**Comment by yirila7459** [comment]
> This is not a bug. Needs to be documented what to edit in order for an editor to be made.

stfu faggot
