### ISSUE TITLE
Gen 2 Unown

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#334]
looks like the unknown forms went MIA, use to be able to set/see what Letter the unowns were in GEN2, but its gone now

**Comment by Ninjistix** [comment]
not sure if this is related to the unknown problem but I can't seem to open Unknowns S,T,U,V,W,X,Y,Z with PKHeX get the following error message 

> Exception Details:
> System.ArgumentOutOfRangeException: InvalidArgument=Value of '18' is not valid for 'SelectedIndex'.
> Parameter name: SelectedIndex
>    at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>    at PKHeX.Main.populateFieldsPK2() in C:\Users\Ninjistix\Downloads\PKHeX\PKHeX\MainWindow\MainPK2.cs:line 25
>    at PKHeX.Main.populateFields(PKM pk, Boolean focus) in C:\Users\Ninjistix\Downloads\PKHeX\PKHeX\MainWindow\Main.cs:line 1551
>    at PKHeX.Main.openFile(Byte[] input, String path, String ext) in C:\Users\Ninjistix\Downloads\PKHeX\PKHeX\MainWindow\Main.cs:line 681
>    at PKHeX.Main.openQuick(String path, Boolean force) in C:\Users\Ninjistix\Downloads\PKHeX\PKHeX\MainWindow\Main.cs:line 630
> 
> Loaded Assemblies:
> --------------------
> mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
> 
> PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> C:\Users\Ninjistix\Downloads\PKHeX\PKHeX\bin\Release\PKHeX.exe
> 
> System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
> 
> System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
> 
> System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
> 
> System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
> 
> System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
> 
> System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
> 
> --------------------
> User Message:
> Unable to load file.
> Path: C:\Users\Ninjistix\Desktop\201 - UNOWN - AD24.pk2

**Comment by Ninjistix** [comment]
@kwsch I checked the version on the  forums, and that let you view the unowns, not sure if/when i was able to change the forms

**Comment by Ninjistix** [comment]
thanks

**Comment by Ninjistix** [comment]
sorry @kwsch what about being able to set the unown forms for gen 2?

**Comment by kwsch** [comment]
Should work now, the program now randomizes IVs until the form is as desired. (That's how unown form is determined)

**Comment by Ninjistix** [comment]
Yes working now thanks
