### ISSUE TITLE
Used Items not showing in item editor

### ISSUE THREAD

**Issue by MewtwoFanz** [kwsch/PKHeX#3356]
**Describe the bug**
Any items that I've used in-game are not showing up in the item editor in my list of items. I always have to refill my items even if I haven't used all of them up.

**To Reproduce**
1. Add any item to your list of items.
2. Import the save, and use only one of the said item.
3. Save the game
4. Backup the new save and edit it in PKHeX
5. Go to the items tab.
6. Notice your item isn't showing up. Most noticeable when you give all items.

**Expected behavior**
It's supposed to list all of the items you have in your directory

**Screenshots**

**Additional context**

**Comment by sora10pls** [comment]
Stating which game you're having an issue with is very important.

If you're talking about BDSP, then the latest commits should have already fixed any item editing issues?

**Comment by MewtwoFanz** [comment]
The issues I'm having is with BDSP, I've run into this problem a couple of times now.
I'll send screenshots at a later time because I'm on vacation for the holidays

**Comment by kwsch** [comment]
The release build (on pporg) has the behavior you're describing; the development build (latest commits) is fine, no misbehavior,
