### ISSUE TITLE
template folder and pk#/pb# files not being properly used as template trainer data for blank savefile

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3358]
**Describe the bug**
"template" folder and setting default trainer data from pk#/pb# files is not functioning properly, either defaults back to PKHeX default blank save trainer data, or mutates hybrid trainer data from provided file + default blank save trainer data.

**Screenshots**
Examples:
PB8 file loaded from template folder via template.pb8
![opened via pb8 in template folder](https://user-images.githubusercontent.com/39707481/147737698-680ca174-280e-419a-b54c-345b70c5c24e.PNG)

PB8 File opened with PKHeX manually
![pb8 opened with PKHeX manually](https://user-images.githubusercontent.com/39707481/147737651-de2e2032-2b7b-480d-b9e2-bea4021a6af5.PNG)

**Additional context**
Was able to reproduce on latest and stable PKHeX, and without plugins.

**Comment by kwsch** [comment]
1. Viewing a template does not source an originator-Trainer to convert the `IEncounterTemplate`=>`PKM`; it only uses the currently loaded save file's details (with sanity checked mutations for language/etc):
https://github.com/kwsch/PKHeX/blob/0cf7b2236324ad3d74bb7f6d1316cb3f405f4da0/PKHeX.WinForms/Subforms/SAV_Encounters.cs#L133-L135

2. Opening a file or drag/drop will adapt the `PKM` to the currently loaded save file, to be transparent on what is changed, only if `ModifyPKM` is `true`. This is the intended behavior -- gender being different is the reason it sets the HT in one and not the other.
