### ISSUE TITLE
Fire Red reported as "unsupported"

### ISSUE THREAD

**Issue by renatolond** [kwsch/PKHeX#336]
Hi!

I have a Fire Red save with half the size (65536) that works normally on the game, but it's not being loaded by PKHeX. A previous version of the same save works normally. It seems that when it gets `SaveUtils.cs:234`, the `BlockOrder` array has this content:

```
[0]     1
[1]     2
[2]     3
[3]     4
[4]     5
[5]     6
[6]     7
[7]     8
[8]     9
[9]     10
[10]    11
[11]    12
[12]    12
[13]    13
```

And so the `Block0` check fails.

Edit: more info, I'm on Arch Linux, Mono Develop v5.10.1.

Should I upload the save? How is the best way to help debugging this?

Best,

**Comment by kwsch** [comment]
PKHeX is unable to determine what block is the 0th block, since apparently there's a duplication in the reference table.

Try re-saving the game.
