### ISSUE TITLE
[Question] Where can I find the format of the save for BDSP ?

### ISSUE THREAD

**Issue by Shraneid** [kwsch/PKHeX#3360]
Hey, great project, I've been trying to recover a broken save file I have to make it work again, and I found the issue which is that my mystery record thing is broken. Since it's greyed out in the UI, I can't modify it to a legal value like I'd like to try.
So I wanted to change it with a hex editor and another save file, however I can't seem to find what the save format is, so if you could point me into which file(s) are responsible for it that'd be great, I looked around, but not being familiar with the code base it is likely going to take quite some time.

Thanks ! :)

**Comment by kwsch** [comment]
The class name of the save file is displayed in the main UI. `SAV8BS`.

Searching GitHub: https://github.com/kwsch/PKHeX/blob/eb71576803894606114494993cfe6c851cdc292b/PKHeX.Core/Saves/SAV8BS.cs

**Comment by Shraneid** [comment]
thanks ! :)
