### ISSUE TITLE
Kangaskhan illegal

### ISSUE THREAD

**Issue by T3chTobi** [kwsch/PKHeX#3363]
**Describe the problem**
Invalid: Can't have ball for encounter type.

**To Reproduce**
Latest version of PKHeX (03.01.22)
Kangaskhan
- Met Location: Route 209
- Ball: Poke Ball
- Met Level: 1
- As Egg: Checked
- Location: Nursery Couple (2)

**Expected behavior**
To be legal

**Additional context**
When I change the ball to safari ball the Pokemon is legal. But as far as I know it can only be a Poke Ball as an egg.

**Comment by Lusamine** [comment]
Kangaskhan can only be caught in Safari Ball in BDSP prior to transfers.
Eggs copy the ball from parent in BDSP.
Not a bug.
