### ISSUE TITLE
Item amounts are broken in Gen 3 saves in latest commits

### ISSUE THREAD

**Issue by MichiS97** [kwsch/PKHeX#3369]
**Describe the bug**
In the most recent commits (the latest release is NOT affected) the item editor in generation 3 save files seems to be broken. Item amounts are not parsed correctly from the save file resulting in too large numbers being displayed as you can see in the screenshot down below. I'm guessing this could have been introduced by the refactoring from arrays to spans but I'm not sure as I've never worked with those.

**To Reproduce**
1. Load any 3rd gen save file
2. Open Inventory Editor
3. See error

**Expected behavior**
Item names and amounts should be displayed correctly.

**Screenshots**

**Additional context**
![PKHeX values vs actual in-game values](https://i.imgur.com/jJIDL5K.png)

**Comment by kwsch** [comment]
> refactoring from arrays to spans

yep :)
