### ISSUE TITLE
Box Viewer - Refresh

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#338]
I've found that the box viewer does not auto-refresh if the box gets sorted, you have to change to one Box and back to see the changes. Not sure if it was intended to be this way, or if their could be some way to auto refresh the box viewer tab when the boxes are sorted. The box viewer does get updated if a Pokemon is deleted/added from the box,

**Comment by Ninjistix** [comment]
Actually noticed, it refreshes the box with sort a few times, its not 100%

**Comment by kwsch** [comment]
Sort/Delete individual box: Working
Sort/Delete all boxes: Not working for boxes that are on another box (diff from main window)
BoxLayout changed: Not working for boxes that are on another box (diff from main window)

Probably just need to change it to add an optional param to updateBoxViewers to make the check always true:
`    foreach (var v in views.Where(v => v.CurrentBox == CB_BoxSelect.SelectedIndex))`

**Comment by Ninjistix** [comment]
thanks for everything as always @kwsch .
