### ISSUE TITLE
[Feature Request] A shortcut to enable the National Pokédex in a Pokémon White savefile

### ISSUE THREAD

**Issue by LOuroboros** [kwsch/PKHeX#3381]
I suggest adding a shortcut/option somewhere, maybe in Block Data -> Tab_Raw, where a user could enable the National Pokédex in their savefile of Pokémon White 1.

I hope I'm not being super blind right now, but I'm not seeing an option to do this anywhere.

I quickly opened a Pokémon Emerald savefile and noticed that there's a boolean value for the National Dex at SAV -> Block Data, but for Pokémon White 1 there is no such thing.

**Comment by kwsch** [comment]
The flag has not been documented; needs to be documented prior to be considered for implementation.
