### ISSUE TITLE
Alpha Flag mismatch on legitimate Tidewater Dam Bibarel

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3383]
**Describe the problem**
This legitimately caught Alpha Bibarel is falsely flagged as "Alpha Flag Mismatch", despite the encounter database containing the exact encounter this was obtained from.

**To Reproduce**
[400 - Bibarel - 11DB27E0CE87.zip](https://github.com/kwsch/PKHeX/files/8007252/400.-.Bibarel.-.11DB27E0CE87.zip)
Trainer details altered for privacy, otherwise unchanged.

**Additional context**
Recreating the same Alpha Bibarel by pulling from the Encounter database and altering moveset, move relearn/mastery flags, ball, etc. to match mine yields a legal Bibarel. I'm unsure as to why two seemingly identical instances of this Bibarel would be flagged differently.

**Comment by kwsch** [comment]
Normally things get a flat +15 or +20 level boost when it is an alpha; curious that this is level 16 and not much higher.

**Comment by Atrius97** [comment]
Perhaps underleveling can occur on Alphas by exploring during early game? I obtained this fairly early in my playthrough, and the exact moment I was given any freedom to explore past the tutorial, I went to every land-accessible area of Obsidian Fieldlands before advancing the story.

**Comment by kwsch** [comment]
4 flawless IVs (pkm) != 3 flawless IVs (encounter)
hehe :)
