### ISSUE TITLE
bugs with the encounter database

### ISSUE THREAD

**Issue by odin880** [kwsch/PKHeX#3387]
**Describe the bug**

**To Reproduce**
1. Go to '.pkhex
2. Click on '..encounter database.
3. goto samurott or any starter that is alpha
![wvSwjz2TXD](https://user-images.githubusercontent.com/69611332/152632862-93e49dc8-65f0-4cc8-89c8-5545ef17281a.jpg)

**Comment by Atrius97** [comment]
The Typhlosion in the last slot seems to pull straight from the encounter database at level 86 but met level 88.

**Comment by ReignOfComputer** [comment]
Seems like this affects most things with a Hisui form, like Samurott and Braviary.

**Comment by Atrius97** [comment]
> Seems like this affects most things with a Hisui form, like Samurott and Braviary.
Shot in the dark, EXP calculation is wrong because it's using non-regional form as the template?
