### ISSUE TITLE
Inventory exporting & importing

### ISSUE THREAD

**Issue by InkDragon** [kwsch/PKHeX#3388]
**Is your feature request related to a problem? Please describe.**
Was wondering if it would be possible to add an option to export & import akin to what is available for NHSE? An option to load a preset selection of items rather then use the give all items would be useful for quick starting a new game.

**Describe the solution you'd like**
just a little save load feature for the inventory/main bag so i don't have to edit in the same 2 dozen items or so every time I restart my game. Similar to what is in nhse, where you can export a file for easy loading later.

**Describe alternatives you've considered**
i've considered keeping a starting back up file for each game, but that's only really useful for fresh plays. if i forget to use it, or end up starting when i am away from the pc I end up needing to edit in the same items again.

**Comment by kwsch** [comment]
You can dump blocks, assuming you're referring to SWSH or PLA.

**Comment by InkDragon** [comment]
for those games that's useful to know, but is there an option for older games(gba/ds/3ds)?

**Comment by Ninjistix** [comment]
every gen supports modifying bag slots to get x quantity of all items.

**Comment by kwsch** [comment]
I think GiveAll is suitable for almost all purposes. Trying to come up with an abstraction to handle importing/exporting pouch data for all games doesn't seem worth it.

Could be something someone could make a plugin for, to load an external list (text) of items, and sets the inventory accordingly.
