### ISSUE TITLE
Error Loading PKMN Yellow Sav

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#339]
> Exception Details:
> System.ArgumentNullException: Value cannot be null.
> Parameter name: source
>    at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
>    at PKHeX.GameInfo.setItemDataSource(Boolean HaX, Int32 MaxItemID, IEnumerable`1 allowed, Int32 generation, GameVersion game, GameStrings s) in C:\Users\Desktop\PKHeX\PKHeX\Game\GameInfo.cs:line 306
>    at PKHeX.Main.populateFilteredDataSources() in C:\Users\Desktop\PKHeX\PKHeX\MainWindow\Main.cs:line 1296
>    at PKHeX.Main.openSAV(SaveFile sav, String path) in C:\Users\Desktop\PKHeX\PKHeX\MainWindow\Main.cs:line 1131
>    at PKHeX.Main.openFile(Byte[] input, String path, String ext) in C:\Users\Desktop\PKHeX\PKHeX\MainWindow\Main.cs:line 659
>    at PKHeX.Main.openQuick(String path, Boolean force) in C:\Users\Desktop\PKHeX\PKHeX\MainWindow\Main.cs:line 622
> 
> Loaded Assemblies:
> --------------------
> mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
> 
> PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> C:\Users\Desktop\PKHeX\PKHeX\bin\Release\PKHeX.exe
> 
> System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
> 
> System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
> 
> System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
> 
> System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
> 
> System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
> 
> System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
> 
> --------------------
> User Message:
> Unable to load file.
> Path: G:\Complete\Pokemon - Yellow.sav

Got that Error Trying to load a Yellow Sav File... I had no problems opening it with previous versions. I get prompted a continue option which still opens the file (unsure if I want to make changes with it like that).

**Comment by evandixon** [comment]
It looks like this is because `SAV1.HeldItems` is null.  All other saves set this to Legal.HeldItems_Something in the constructor, but SAV1 does not.  This might be solved if `SAV1.HeldItems` is set to `Legal.Pouch_Items_RBY`, but I'm not 100% sure that's the proper thing to set it to.

**Comment by Ninjistix** [comment]
@kwsch any chance you can once this over? it doesn't look like its been addressed with recent fixes

**Comment by Ninjistix** [comment]
thanks @kwsch
