### ISSUE TITLE
Growlithe marked as Illegal from Database

### ISSUE THREAD

**Issue by fadedlamp42** [kwsch/PKHeX#3391]
**Describe the problem**
When selecting any of the Growlithe files from the database, all have various legality errors.

**To Reproduce**
1. Go to tools > Data > Encounter Database
2. Type Growlithe and select any of the options.
3. All are maked as illegal.

**Expected behavior**
Given that it is the database, I expected them to be legal.

**Screenshots**
![image](https://user-images.githubusercontent.com/47757510/152639039-6e80d34b-2aa1-4d82-a8a6-8a949d3f7e52.png)

**Additional context**
None, thank you!

**Comment by sora10pls** [comment]
Works fine on latest commit.
![image](https://user-images.githubusercontent.com/17801814/152647760-6b1f6564-6df2-4ef7-900a-b3134473e366.png)
