### ISSUE TITLE
Can't uncheck "Complete" mark even with 0 in each tasks

### ISSUE THREAD

**Issue by Valnoob** [kwsch/PKHeX#3393]
**Describe the bug**
I would like to go back to Full Odds for some Pokemon so I edited the Pokedex page but even if I put 0 in each task it does not change the "complete" mark. I don't know if I'm doing something wrong so excuse me if this post is innapropriate. 

**To Reproduce**
1. Go to 'Pokedex'
2. Click on 'Edit task
3. Put every task to 0
4. Check the Pokedex Page
5. Every task is to 0 but the Research Level is still to 10

**Expected behavior**
I would like the research level back to 0 

**Screenshots**
(https://prnt.sc/26p5djm)

**Additional context**
I tried to catch one Basculin to force the edit of the page and when I talked to the Professor the game take like 30 seconds until the dialogue line triggered. I thank my game crashed but the music was still playing so I waited.

**Comment by SciresM** [comment]
Reducing Pokédex progress is likely to lead to game crash/instability, yes, it's not recommended.

**Comment by kwsch** [comment]
Edit the ROM to have whatever shiny bonuses you want (try pkNX's shiny rate editor), or use a different save file.
