### ISSUE TITLE
Pokédex editing won't work

### ISSUE THREAD

**Issue by drewlobel** [kwsch/PKHeX#3394]
I tired to edit the Pokédex for wurmple, and wurmple only. When I uploaded the save the edit Wasn't there 

**To Reproduce**
1. Upload save 
2. Go to pokedex 
3. Edit the Pokémon entry
4. Click save 
5. Downloaded new save 

**Expected behavior**
The Pokédex entry to save 

**Screenshots**

**Additional context**
I understand this is a new game with bugs. Thank you guys for everything you do. I appreciate it

**Comment by sora10pls** [comment]
Already fixed on latest commits: https://github.com/kwsch/PKHeX/commit/cb92166aa2f3276988c9bad9689ef14e72047cb0
