### ISSUE TITLE
Edit All Tasks...

### ISSUE THREAD

**Issue by xgorinx** [kwsch/PKHeX#3399]
**Describe the bug**
I don't believe the Edit All Tasks... button works properly.  When you open that up and set a number, it only applies to the pokemon that you have selected, not all pokemon.

**To Reproduce**
1. Go to 'SAV'
2. Click on 'Pokedex'
3. Click on 'Edit All Tasks...'
4. After applying a value and hitting Save, it only affects the one pokemon you have selected, not all

**Comment by sora10pls** [comment]
That's the entire point of the editor? It edits **all tasks** for that Pokémon, not **all tasks** for **all Pokémon.**

**Comment by xgorinx** [comment]
Well that makes sense.  My bad.  Is there a possibility of modifying all tasks for all pokemon though?

**Comment by Lusamine** [comment]
Currently, no. The dex is very complicated to edit.

**Comment by xgorinx** [comment]
Okay good to know!  Thank you :)
