### ISSUE TITLE
Feature request: Importing multiple .wc6 files and adding them to the save file in sequential order

### ISSUE THREAD

**Issue by arkriloth** [kwsch/PKHeX#34]
It's rather tedious to import then add multiple wondercard files if you have to do tens of them in one go,  would it be possible to include the above feature?

**Comment by kwsch** [comment]
Implemented in the latest commit: https://github.com/kwsch/PKHeX/commit/6f516a23d1b0d717146b7c0c745c98692989ea4a

It'll add them in the order they were selected in your file browser, just drag&drop a bunch in and it'll add starting at the selected WC index.
