### ISSUE TITLE
Pokemon Black 2 dst is too Large 

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#340]
when i drag from the black 2.dst is say to me it is **Input File is too Large**  and the dst file came from DeSmuME_0.9.11_x64 
![5ger3](https://cloud.githubusercontent.com/assets/18640392/20069979/2f81ca46-a538-11e6-9dc3-0cf6a2d46b9b.jpg)
 can u fix this problem in the future PLZ 
ARIGATO GOZAIMAS
the different between PokeGen and PKHeX is PokeGen have a Shiny Locked and for PKHeX it is esay to create Shiny Pokemon that came from older Gen 😄

**Comment by kwsch** [comment]
dst files are save states, not save files.

Export Backup Memory (save file) to edit instead.
