### ISSUE TITLE
Ability to sort box/all boxes by regional dex numbers

### ISSUE THREAD

**Issue by BtEtta** [kwsch/PKHeX#3409]
**Is your feature request related to a problem? Please describe.**
For games like Sword/Shield & Pokémon Legends: Arceus where there is no national dex would would be nice to be able to use the sort feature to organise the boxes according to the only dex numbering available in those games.

**Describe the solution you'd like**
Which right-clicking the "Box" tab either have new entries added under the "Sort" submenu for "Regional Dex No." (and the reverse). Or have ctrl clicking (and ctrl+shift clicking) on the existing entries operate the sort function on a regional dex number basis.

**Additional context**
Due to DLC there would be some interesting considerations in Sword/Shield in particular as to how to handle the Isle of Armor/Crown Tundra additions (as well as the Pokémon which appear in those games but do not get dex numbers). The simplest solution would be a sort order along the lines of:
Galar Dex#
Isle of Armor Dex# (minus those that already exist in Galar Dex)
Crown Tundra Dex# (again, minus repeats)
All remaining Pokémon by National Dex#

**Comment by drewlobel** [comment]
https://github.com/foohyfooh/PKHeXSortingPlugin/releases/tag/0.0.5

**Comment by kwsch** [comment]
As mentioned above, cosmetic sorting can be done via a plugin.
