### ISSUE TITLE
Moving Pokémon between different boxes increases capture counts

### ISSUE THREAD

**Issue by BtEtta** [kwsch/PKHeX#3411]
**Describe the bug**
Double clicking on the "Box" tab to open a second box view on a different, then dragging a Pokémon between them will increase a variety of different capture counts in at least PLA, BDSP, & SwSh

**To Reproduce**
1. Take note of the capture count in the Pokédex for a particular Pokémon species (in BDSP/SwSh instead note the CAPTURE_POKE/capture_wild value in trainer info).
2. Double-click the "Box" tab to open a second box view.
3. Make sure that two different boxes are visible, and that one of those boxes contains the species noted in step 1 (if using a PLA save).
4. Drag-and-drop the Pokémon from one box to the other.
5. Check the capture count again and it should have increased.

**Expected behavior**
Reordering your Pokémon should not result in any new captures being counted.

**Additional context**
The above reproduction method was consistent, and it does also appear to happen even just moving within boxes. I observed some instances where the capture value didn't go up, but those might have been egg hatches in either BDSP/SwSh and so may have changed values other than CAPTURE_POKE/capture_wild
I also had a Let's Go Pikachu save available to test and could not get the same effect, none of the capture numbers I could see incremented in any of my tests.
I saw similarly increased capture counts when using this plugin: https://github.com/foohyfooh/PKHeXSortingPlugin
It's possible that the problem is in whichever method that plugin is using to move Pokémon around. Sorting using the internal methods does NOT change any capture counts.

**Comment by joeymavity** [comment]
This actually explains something I experienced but couldn't adduce why it was happening. Well done @BtEtta

**Comment by cactysman** [comment]
I've experienced that too, with PLA,, it seems that just changing the PID increases the capture count somehow.
