### ISSUE TITLE
Pokemon Black (Italy) - Local event ROCKET Meowth shown as invalid

### ISSUE THREAD

**Issue by SSUPII** [kwsch/PKHeX#3413]
**Describe the problem**
Pokemon Event Meowth in Pokemon Black appears as invalid on PKHeX. "Has the mystery gift data been contributed?".

**To Reproduce**
[052 - Meowth - 5A1568D26BF9.pk5.zip](https://github.com/kwsch/PKHeX/files/8022607/052.-.Meowth.-.5A1568D26BF9.pk5.zip)
PK5 file for unmodified event Meowth

**Screenshots**
![Istantanea_2022-02-08_10-47-15](https://user-images.githubusercontent.com/42090377/152965222-d3766987-e70d-467d-b214-f676f9c689e1.png)

**Additional context**
[Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/List_of_local_Italian_event_Pok%C3%A9mon_distributions_(Generation_V)#Team_Rocket_Meowth)
[Official statement](https://archive.ph/fbmuF)

**Comment by Atrius97** [comment]
Project Pokémon does appear to have this event catalogued as well, in ITA:
https://projectpokemon.org/home/files/file/1206-team-rocket-meowth/

**Comment by drewlobel** [comment]
Go to the folder where pkhex.exe is
- Make a folder named "mgdb"
- Drag and drop that meowth file into the "mgdb" folder
- Reboot PKHex

**Comment by Atrius97** [comment]
Adding it to the mgdb folder is a temporary fix until the next stable release, but regardless PKHeX's built-in Mystery Gift Database should still be updated if it doesn't currently contain this event.

**Comment by SSUPII** [comment]
The following event IS in the EventsGallery repo.
https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%205/Wondercards/ITA/0120%20BWB2W2%20-%20ROCKET%20Meowth%20(ITA).pgf

**Comment by kwsch** [comment]
> The following event IS in the EventsGallery repo. https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%205/Wondercards/ITA/0120%20BWB2W2%20-%20ROCKET%20Meowth%20(ITA).pgf

The issue is with the `pgf` itself; the OT name string in the pgf data is `ROCKET ` (has a space at the end) when it shouldn't. Likely is a faked card; again, take it up with the EventsGallery and reference the comment here.

![image](https://user-images.githubusercontent.com/6393368/153028261-ed5a31f2-0aaf-409b-b07e-24f699c7153c.png)

**Comment by Atrius97** [comment]
The Project Pokemon staff believe this is the correct card, with the space in the OT Name included. The original card PPORG had the OT `ROCKET`, without a space, but it was corrected to the one with `ROCKET ` after an attendee came forward with the correct wondercard.

See this thread:
https://projectpokemon.org/home/forums/topic/56388-legality-bug-original-team-rockets-meowth-event-from-italian-pok%C3%A9mon-day-2013-is-shown-as-illegal/#comment-254062

Photos from the event to help verify legitimacy: https://imgur.com/a/xhXxk

**Comment by SSUPII** [comment]
I deleted the card from my mystery gift album some months ago, so can't get info from that. 
Also, it isn't a true 2013 Mirabilandia Meowth, as it was gotten from Wi-Fi in 2021 while connected to private servers (KaeruWFC, that proxies to Wiimmfi than again proxies to Pokè Classic Network). The Pokemon and pk5 file I sent isn't modified in any way, and can be seen as encountered in 22/05/2021 and with the OT name "ROCKET" (with no space).
Other local events I couldn't participate obtained with this method on the same save file appear as legal on the PKHeX software. In fact, just adding a space at the end makes it legal according to the software.
While of course the Meowth is non-legit, the discrepancy between the data is still there.

**Comment by kwsch** [comment]
Private servers offer the same mystery gifts from the events gallery; they're likely offering an old version of a bad card.

Dates are irrelevant to legality checking as the console date can be anything upon receipt. Only HOME gifts are generated with realtime date. Still makes it suspicious as most legitimate acquisitions would have a date on the actual distribution day.
