### ISSUE TITLE
No Notification for Updates

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3414]
**Describe the bug**
PKHex doesn't notify you of new version for download (I'm on win 11)

**To Reproduce**
Opening PKHeX doesn't notify you that there's a new version.

**Expected behavior**
To be notified of updates.

**Screenshots**

**Additional context**
Have to manually check GitHub or the website for new release. (could end up potentially reporting bugs that were previously fixed.)

**Comment by drewlobel** [comment]
PKHeX doesn't have an automatic updater. I understand there used to be a link but it is not there anymore for some reason. I suggest signing up for emails when there is a new version, and turning the GitHub email address to priority

**Comment by drewlobel** [comment]
Your right it used to be like that, with a blue link, but it's not like that anymore. Idk why. But that is just my suggestion 😅
