### ISSUE TITLE
Quicksave area sometimes showing pokémon as invalid even when it's shown as valid elsewhere

### ISSUE THREAD

**Issue by BtEtta** [kwsch/PKHeX#3416]
**Describe the problem**
Sometimes when viewing a pokémon the quicksave area will show as invalid even though there is no invalid mark in the box viewer

**To Reproduce**
1. Create a blank PLA save and import the two attached pokémon
2. View 1417C0AEC90C — the quicksave box will correctly show as valid
3. View D121164E98F1 — the quicksave box will show as invalid (Invalid: Calculated Height does not match stored value.)
4. Without viewing any other pokémon select view on D121164E98F1 again — the quicksave box will now show valid

**Expected behavior**
Quicksave box should show as valid in all above circumstances.

**Screenshots**
![1417C0AEC90C](https://user-images.githubusercontent.com/221650/153074791-56d2422f-c5bb-48df-b7cc-219e4a32c910.png)
![D121164E98F1](https://user-images.githubusercontent.com/221650/153074831-1003e965-378b-4462-8b2b-06cbeb30bdda.png)

[712 - Bergmite - 1417C0AEC90C.zip](https://github.com/kwsch/PKHeX/files/8027417/712.-.Bergmite.-.1417C0AEC90C.zip)
[712 - Bergmite - D121164E98F1.zip](https://github.com/kwsch/PKHeX/files/8027418/712.-.Bergmite.-.D121164E98F1.zip)

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/48524-cp-height-weight-calculations/

.NET Framework's float calculations do not match the results stored in the data; the framework doesn't read/write the value correctly.

It calculates closer on the NET6 build, but still isn't exact; however, it's within the program's tolerances.

```
NET6:
obj.HeightAbsolute.ToString("F8") = "100.86275482"
obj.CalcHeightAbsolute.ToString("F8") = "100.86273956"

NET4.6:
obj.HeightAbsolute.ToString("F8") = "100.86280000"
obj.CalcHeightAbsolute.ToString("F8") = "100.86270000"
```

Emulating the Switch's floating point calculations would be required for accurate calculations, but that has not been implemented (even 3 years later). No estimate of if/when accuracy will be available, hence the current behavior as-is.

**Comment by kwsch** [comment]
Ha, I've figured something out ;)

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/pull/3417
