### ISSUE TITLE
[PLA] Reducing research progress doesn't seem to be quite stable yet

### ISSUE THREAD

**Issue by cactysman** [kwsch/PKHeX#3418]
## Versions affected
[22.02.04](https://github.com/kwsch/PKHeX/releases/tag/22.02.04), [22.02.08](https://github.com/kwsch/PKHeX/releases/tag/22.02.08)
## Describe the bug
Reducing a research task's progress seems to mess up Pokédex research stats as in showing the right count, but tasks completed along the way are still checked off.

The unreported tasks counter gets messed up and that makes the game thing there's 99+ unreported tasks.

Attempting to report these tasks works, but it'll be loading incredibly long (about two minutes?)

## To Reproduce
1. Go to the Pokédex editor
2. Reduce a research task's progress (see screenshots)
3. Save and go back into the game
4. Check the Pokédex and optionally try to report your progress

## Expected behavior
Some other values regarding total research progress will have to be changed for this to not cause any problems. More research might be necessary.

### Editing the tasks
I reduced the number caught from 3 to 1
![image](https://user-images.githubusercontent.com/5056880/153104246-6d8835c8-81b8-4dcd-bc33-e0f9e84f665a.png)

### Before reporting
![image](https://user-images.githubusercontent.com/5056880/153104213-975d0253-0c59-4df3-a9a1-ccd1cb8e0054.png)

### The report
![image](https://user-images.githubusercontent.com/5056880/153105260-84b0a78b-d4c2-41aa-8e7d-24d56e0feb73.png)

### After reporting
![image](https://user-images.githubusercontent.com/5056880/153105610-3ab3509c-1c63-461c-8451-7e47e73ddcdc.png)

## Additional context
I thought it could be related to #3411 (see [my comment here](https://github.com/kwsch/PKHeX/issues/3411#issuecomment-1032014215)) but despite that having been fixed, it's still happening in v`22.02.08`.

I hope it's not just me missing something else I have to do in the Pokédex section, but I can't seem to be able to do anything else that would help it.

**Comment by kwsch** [comment]
Right; for now, only forward progress is accurately edited.

The game doesn't revert progress, so someone would have to write a pokedex-reevaluation method.
