### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drewlobel** [kwsch/PKHeX#3425]
I am trying to move up a gengar from FRLG and I keep getting an error that says 
"Current handler cannot be past gen OT for transferred specimen." What does that mean?

**Comment by kwsch** [comment]
Please do not use GitHub Issues for requesting help fabricating data. This place is for reporting bugs or requesting implementation of documented behavior.

I suggest using the forums instead, and brush up on what is actually legal to obtain.
