### ISSUE TITLE
Garbled Chinese name for Pokemon

### ISSUE THREAD

**Issue by samyex6** [kwsch/PKHeX#343]
The text file `Resources/text/zh/text_Species_zh.txt` is garbled.

**Comment by kwsch** [comment]
That's the way it should be, as far as I know. The new gen7 font hasn't been added; I'm pretty sure they're reserving a portion of the characters for the Pokémon names.

**Comment by ericjwg** [comment]
well.... load separate nickname and species text file should help.
one plain text file(Chinese characters) for displaying the species.
the other one is the game extraction for nickname,

**Comment by evandixon** [comment]
Looks like PR #360 solves this.
