### ISSUE TITLE
Graveler temporarily marked invalid

### ISSUE THREAD

**Issue by joeymavity** [kwsch/PKHeX#3430]
**Describe the bug**
When viewing the attached Graveler (valid catch, changed stats) after looking at a different pokemon species, it's initially marked invalid ("Invalid: Calculated Weight does not match stored value."). If you right-click -> view again, it's valid. If you look at another graveler and then this one, it stays valid. But any time you view after viewing another species, it's temporarily invalid again. If you save while invalid, the new copy remains invalid. 

**To Reproduce**
1. Import attached mon to any box. 
2. View non-graveler, then view the imported mon
3. Should see "Invalid" message above. 
4. Right-click -> view the same mon again, it should pass validity. 

**Expected behavior**
Should always be valid

**Screenshots**

**Additional context**
[075 - Graveler - validity error.zip](https://github.com/kwsch/PKHeX/files/8051222/075.-.Graveler.-.validity.error.zip)

For what it's worth: If I click "auto" under height/weight, it's always marked valid. But it seems odd that when unchecked, no other mons give this issue. And also weird that viewing it a second time resolves it.

**Comment by kwsch** [comment]
Works fine on the latest commit; already been reported and fixed ~ https://github.com/kwsch/PKHeX/pull/3417
