### ISSUE TITLE
Misalignment of IVs and EVs numbers under 'Stats' tab.

### ISSUE THREAD

**Issue by micrahman** [kwsch/PKHeX#3436]
**Describe the bug**
Text inside the IVs and EVs fields become misaligned if certain actions are performed.

**To Reproduce**
1. Go to 'Stats'
2. Right-click on any IVs, EVs or GVs (for PLA) field
3. Check "Right to left reading order"
4. Uncheck "Right to left reading order"
5. Which ever field steps 3 to 4 were done on becomes misaligned.

**Expected behavior**
Unchecking "Right to left reading order" should make the text inside the field go back to where it was before.

**Screenshot**
The result after step 5 is attached.
![unknown](https://user-images.githubusercontent.com/41705814/153783851-5e32a1b6-c38a-400c-8da5-705714dede28.png)

**Comment by kwsch** [comment]
> "Right to left reading order"

Don't toggle this. This behavior doesn't persist if you restart the application.

WinForms doesn't retain the original TextAlign value when changing the RTL order (no event is fired either), so the only real alternative is to replace the ContextMenu entirely for all controls (textbox, combobox, etc). 

GUI framework quirk; not worth the amount of time to try and mitigate this. Nobody in the past 8 years has complained about this being possible, until now ;)
