### ISSUE TITLE
PLA Piplup mystery gift marked as illegal

### ISSUE THREAD

**Issue by gentlecolts** [kwsch/PKHeX#3437]
Piplup from the mystery gift database shows up as "Invalid: Event OT Friendship does not match base friendship."

**Comment by Atrius97** [comment]
Already solved in this commit: https://github.com/kwsch/PKHeX/commit/7b05d0c0562a17715929a4a74aee4efae2cad7b7

In the future please check that your issue still occurs in the latest development build, bugs that appear in the latest stable release may have already been resolved before you report them.
