### ISSUE TITLE
Pokémon Legends: Arceus: Pokédex Autofill Options Request

### ISSUE THREAD

**Issue by jdroo** [kwsch/PKHeX#3438]
Pardon my lack of correct lingo and junk, I'm not so good at wording this properly, but I tried my best!

Requesting an options to be added that can edit the pokedex entries in **Pokémon Legends: Arceus**, Specifically some options to 100% the pokedex in a legal clean manor with all research filled in correctly with the correct max values for all individual settings for each pokemon. 

Being each pokemon in Pokémon Legends has different research tasks, and numbers that fulfill them, it would be nice to add a "Full Research" toggle of some sort, 

There are so many pokemon, that doing this manually is a major task, the added research, and the variations between what pokemon get what is all different, and is not as simple as just maxing everything out. Would be nice if there was a nice way to auto fill this data to the max default setting the game looks for, I know you can go over, but making this look clean would be nice too, looks kinda weird having everything maxed to 999 or 100..

for example With a single button press, maybe it could just auto fill everything to their max setting, whatever that may be. like these images I did manually.

https://i.imgur.com/KUvq9yu.png
to
https://i.imgur.com/ZYKS6sY.png

I honestly don't care if it's done in bulk, or per pokemon, cause a single button press after choosing the pokemon, is better than having to manually type in each max number for every research requests.

I have tried using cheats to do this, but the cheats others make just set 100 or 999 for every research option, and not only does that look horrid, but it looks so dirty and suspicious, and to be honest, I have no idea what the Nintendo Switch looks for, and what might flag your game. I'd rather there was a more legit looking fashion to fill all this data in.

Also adding a way to export all this would be nice too, so people can export and import their current pokedex to a different save file or to share with others, would be pretty rad.

Sorryy for the bother! Have a nice day. :D

**Comment by Lusamine** [comment]
Refer to https://github.com/kwsch/PKHeX/issues/3399#issuecomment-1030676409.

If you want to export the dex blocks, you can move `KZukan` around.

**Comment by jdroo** [comment]
> `KZukan`

And what would be the best rout to do this? Sorry I'm kinda a noob. lol

**Comment by jdroo** [comment]
> If you want to export the dex blocks, you can move `KZukan` around.

How would one do this, sorry 'm a bit of a noob, I know I can block edit, but is there more I should keep in mind?

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/154574983-048c0787-3d54-4cba-8443-c9da81e72674.png)

**Comment by jdroo** [comment]
So i just export that current block, and import it into another save? ez nuff.

**Comment by jdroo** [comment]
![dotnet_V8gjb6OENA](https://user-images.githubusercontent.com/13055804/154576554-b7025551-a78a-4f7b-af49-48238ac4c709.png)

hmmm..... tried it and got a weird result, does not reset the current research completed, is that stored separately? I'mma start my game over and see what results that gets me.

**Comment by jdroo** [comment]
Atempting to import a legit "100% pokedex" save, pokedex entries.

**Comment by Lusamine** [comment]
Again, the dex is complex and not everything is handled by simply moving one block around. Expect unusual behavior when using a 3rd party program to bypass what usually requires playing in-game.

Regardless, this isn't the place to seek help for aberrant behavior caused by doing this. This is for reporting issues with the program.
