### ISSUE TITLE
Unable to change gender

### ISSUE THREAD

**Issue by Zekario** [kwsch/PKHeX#344]
I don't see an option to change the gender of a Pokemon, not even a way to view it. Am I missing something, or is there simply no support (yet)?

**Comment by evandixon** [comment]
What generation is this for?

**Comment by Orionsilver** [comment]
@Zekario  be more detail and why is the gender is not changing

**Comment by Zekario** [comment]
@evandixon @Orionsilver Sorry, I should have been more specific. I'm using it for Moon, running on Linux. I don't see any option to change the gender anywhere. [I stitched together an example of what I'm seeing here.](https://i.sli.mg/r3lW4G.png)

**Comment by kwsch** [comment]
Have you tried Options -> Unicode?

**Comment by Zekario** [comment]
@kwsch Ah, I see it now. Thanks! I guess it was trying to show a character it couldn't.
