### ISSUE TITLE
Complete Dex

### ISSUE THREAD

**Issue by drewlobel** [kwsch/PKHeX#3442]
Is there a way to automatically complete the PLA Pokédex? I don't see a button. Thx!!!

**Comment by Atrius97** [comment]
There isn't one. You already opened an issue about this 12 days ago and it was answered then:
https://github.com/kwsch/PKHeX/issues/3419

**Comment by Lusamine** [comment]
Refer to https://github.com/kwsch/PKHeX/issues/3399#issuecomment-1030676409.
