### ISSUE TITLE
CS8983 and CS0006 Error message

### ISSUE THREAD

**Issue by Drageto** [kwsch/PKHeX#3445]
I'm using Microsoft Visual studios on the most updated version of windows 10, I installed both the [.NET Framework v4.6] and [.NET 6.0]. When I right click pkHeX.sln and try to build or rebuilt the solution it keeps giving me these errors and says the dlls cannot be found.

**Comment by Lusamine** [comment]
Make sure you installed the one that's labelled as "developer pack".  Not an issue with the program.

**Comment by Drageto** [comment]
I've specifically installed and reinstalled the developer pack it still gives me the same error message. 

This is the bug that keeps happening to me https://stackoverflow.com/questions/71145085/vs-2022-17-1-wont-build-c-sharp-10-struct-cs8983-17-0-5-liked-it-what-happen

**Comment by Drageto** [comment]
It works now! awesome job and thanks.
