### ISSUE TITLE
BDSP Manaphy Egg marked as legal, but the game blocks it for "having a problem"

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3446]
**Describe the problem**
PKHeX marks the .pb8 as legal when the game decided it's not legal since it was blocked while trading on the latest version (1.2)

[490 - Egg - 07CE64D3494B.zip](https://github.com/kwsch/PKHeX/files/8113036/490.-.Egg.-.07CE64D3494B.zip)

I'm not exactly sure what the issue could be aside from HT memories or something weird. PKHeX had problems with HT data in the past for BDSP Manaphy Eggs even when they actually were legal, but that seems to have gone away sometime in the last few weeks of commits, or PKHeX has "fixed" them in a way that PKHeX is satisfied but the game isn't. It could be completely unrelated to that but that's my experience with these.

**Comment by Atrius97** [comment]
As a side note, just because something is blocked via the trade servers doesn't mean it's illegal. 
To this day, a LGPE origin pokémon evolved into a Gen 2+ species will be blocked from trading in SWSH, despite being perfectly legitimate.
(LGPE origin Blissey, for example)

Likewise, the hack checks on the server often allow completely illegal pokémon to pass, (such as Shiny Keldeo, which has never legitimately been available as shiny).

Legal =/= "Allowed to be traded online"
Legal = Possible to obtain ingame without 3rd party modifications or intentional glitching.

**Comment by Kermalis** [comment]
I get that, but it did work on this version with another Manaphy Egg, so I don't think Manaphy Eggs themselves are banned. The one that worked was an older egg but it still worked while this one didn't so that's what prompted me to create this issue just in case there really is a problem on PKHeX's side. I might've used an older one (when there were HT errors like I mentioned above) but I don't think I did. It just needs a bit of investigating

**Comment by Lusamine** [comment]
I tried to trade your egg and it traded fine. If you try it on the new version, be sure you do not have clones of it in game or it will not trade.

**Comment by Atrius97** [comment]
See this tweet for reference, a new legality check was added to BDSP today:
https://twitter.com/Kaphotics/status/1495965127031816192

**Comment by Kermalis** [comment]
Interesting, but it wasn't cloned on the save either

**Comment by Atrius97** [comment]
Open your savefile in the latest dev build of PKHeX, there is now a legality check for Pokémon that have been flagged as illegal clones:
https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

If this is the issue with your Manaphy egg, then it should appear properly flagged illegal in all future builds.

**Comment by Kermalis** [comment]
Still legal
![image](https://user-images.githubusercontent.com/29823718/155122670-27f0855d-8eae-404c-8103-88dc9906485d.png)


Gonna try with the new update again and see what's up, I'll comment again

**Comment by Kermalis** [comment]
Alright I guess somehow the Egg I tried to trade was duplicated even though I believed it wasn't. The one I uploaded/pictured here works

**Comment by Atrius97** [comment]
As stated in the tweet, all but one of the clones will be flagged. Any duplicate instances will become untradable, with one remaining as the "original".
