### ISSUE TITLE
SAV4 Pal Park/Migrated PKMN in "Other" tab or API

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3447]
**Is your feature request related to a problem? Please describe.**
It'd be nice to be able to edit the pkmn that were migrated from GBA but not caught in Pal Park yet. It'd be a nice feature for people who aren't able to experience the games the same way they were at release

**Describe the solution you'd like**
If putting them in the other tab would be too complicated, maybe API access could be a possibility. It would take a lot of time to add this feature but I figured I might as well put it out there in case it's interesting. I'm also unsure if placing PKMN in those slots in the save would break Pal Park in any way, but editing them after migration should be possible once offsets are found.

Feel free to close this issue if it's not a priority or the offsets aren't known yet. Decomps aren't far enough to look at those

**Comment by kwsch** [comment]
Undocumented, can't be implemented without knowing how the data is stored and what is required to enable functionality in game.
