### ISSUE TITLE
[LGPE] Some pokémon caught in the GO Park have incorrect encounter types

### ISSUE THREAD

**Issue by BtEtta** [kwsch/PKHeX#3449]
**Describe the problem**
Certain Pokémon do not show an encounter type of "Wild Encounter (Wild)" when caught in the GO park after transferring from Pokémon GO which can cause spurious validation errors. I did not test every possible pokémon but every Alolan pokémon I looked at had this problem, and every Kantonian (+Meltan/Melmetal) pokémon I looked at did not.
This problem also extends to pokémon later transferred via HOME to Sword/Shield.

**To Reproduce**
1. Transfer an Alolan pokémon from Pokémon Go to either Let's Go game (I used Let's Go Pikachu)
2. Catch that pokémon from the GO Park, if you use any ball other than a regular pokéball that makes the problem more obvious

**Expected behavior**
Pokémon should display in PKHeX as valid, with an encounter type of "Wild Encounter (Wild)"

**Screenshots**
![Vulpix](https://user-images.githubusercontent.com/221650/155733817-3c8ded3f-4f45-4054-96b8-013a74fc5486.png)
![Diglett](https://user-images.githubusercontent.com/221650/155733846-3ea4ee9b-195e-4414-b357-c0871287f0c3.png)
![Machop](https://user-images.githubusercontent.com/221650/155733869-f90f9792-aeb3-4561-8318-1b7944f15731.png)

**Additional context**
Alolan Vulpix - Shows as "Encounter Type: Wild Encounter (Egg)" 
Will show as "Invalid: Can't have ball for encounter type" if not caught in a regular pokéball
[037-01 - Vulpix - E0DA80DB4A21.zip](https://github.com/kwsch/PKHeX/files/8141934/037-01.-.Vulpix.-.E0DA80DB4A21.zip)

Alolan Diglett - Shows as "Encounter Type: Invalid"
Will always show as "Invalid: Unable to match an encounter from origin game"
[050-01 - Diglett - 80AFCB6900E4.zip](https://github.com/kwsch/PKHeX/files/8141945/050-01.-.Diglett.-.80AFCB6900E4.zip)

Machop - (For reference) Shows correctly as "Encounter Type: Wild Encounter (Wild)"
[066 - Machop - F69CE0C1CF3D.zip](https://github.com/kwsch/PKHeX/files/8141952/066.-.Machop.-.F69CE0C1CF3D.zip)

**Comment by kwsch** [comment]
Diglett's met date is prior to it being available in GO, so that one is correctly flagged as legal.

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/ccca8abdad055c777f80c6270425e5d878d07391
Fixes the vulpix-alola ball making it check wild capture balls instead of the GO encounter ball.
