### ISSUE TITLE
Hello, request code to add

### ISSUE THREAD

**Issue by q67732897** [kwsch/PKHeX#345]
Hello, request code to add
Support Chinese
![qq 20161109195015](https://cloud.githubusercontent.com/assets/6880568/20137495/c4675954-a6b5-11e6-8b11-d36c6053bd74.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/6f62bc685eea7fc0a79ee68a049ee55337a4f698
