### ISSUE TITLE
Shaymin + Disabled Pokemon

### ISSUE THREAD

**Issue by T3chTobi** [kwsch/PKHeX#3451]
**Describe the bug**
- Shaymin is available now for everyone
- Multiple Pokemon (legendary and normal) are flagged als LEGAL in PKHeX, but are disabled to use in the Battle Tower or Online Battles from the BDSP games. This may be related to their unique ID.

**Comment by kwsch** [comment]
1. PKHeX hasn't yet updated per the changes in Pokémon Presents.
2. Clones are checked by BDSP, and the last release made PKHeX's bulk analysis more accessible in the SAV tab. Use that to validate you don't have any clones prior to letting the game flag your stuff.
