### ISSUE TITLE
BDSP/PLA Hidden Power Type Drop-down

### ISSUE THREAD

**Issue by y0shin** [kwsch/PKHeX#3457]
**Is your feature request related to a problem? Please describe.**
Hidden Power has a drop-down menu in the "Stats" tab for games in generations 2 through 7, but not in any generation 8 game despite existing in both BDSP and PLA.

**Describe the solution you'd like**
If the save is from BDSP or PLA simply restore the Hidden Power type drop-down menu.

**Comment by sora10pls** [comment]
BDSP: Has been fixed almost 2 weeks ago. https://github.com/kwsch/PKHeX/commit/3f6427f3235a8647e991a4169bc4b806351a147b

LA: Hidden Power does not work the same in LA, so the Hidden Power Type dropdown should remain hidden.
