### ISSUE TITLE
2016.11.10 Update Fixed：text_Species_zh.txt

### ISSUE THREAD

**Issue by q67732897** [kwsch/PKHeX#346]
2016.11.10 Update
Fixed several missing Pokemon
Now it is complete with 803（CHS）
[text_Species_zh.txt](https://github.com/kwsch/PKHeX/files/582372/text_Species_zh.txt)
![3](https://cloud.githubusercontent.com/assets/6880568/20162948/99eb7d76-a733-11e6-86fa-d28af32850f9.jpg)

**Comment by q67732897** [comment]
[text_Species_zh.txt](https://github.com/kwsch/PKHeX/files/582368/text_Species_zh.txt)
2016.11.10

**Comment by evandixon** [comment]
Just to confirm, does this issue still need to be open after PR #360?  (Since I don't know the language, I can't double-check this.)
