### ISSUE TITLE
PLA Character "Photo" Edit

### ISSUE THREAD

**Issue by x7l7j8cc** [kwsch/PKHeX#3467]
Hi, as the title suggest, i would ask if pkhex can edit the Character "photo" of the save file

Example (not mine):
![FKOVv-6VIAM0kOi](https://user-images.githubusercontent.com/526407/158883379-9eaec3e5-2b67-4c45-b67a-9f2179e0f664.jpeg)

and change it to any else of these:
![show](https://user-images.githubusercontent.com/526407/158883376-0676c002-9a83-415c-b3cc-6a6a0466e602.png)

**Comment by x7l7j8cc** [comment]
Do you know which is the right one?
And for 64bit hash values, you mean the data in "Block Data"->"Block Key" with UInt64 .. right?

**Comment by kwsch** [comment]
It's probably an object which stores multiple hashes including the rest of your player appearance.

Nobody has documented this info as far as I'm aware. Best to continue discussion on the forums instead of here.
