### ISSUE TITLE
Japanese Pokemon Box RS not supported?

### ISSUE THREAD

**Issue by SynapseProperty** [kwsch/PKHeX#3468]
When trying to open the JP Pokemon Box save file through Nintendont or GX Loader on the Wii emulated it does not open properly in PKHeX

I try to open the save, it just appears blank even though I do have some mons in there for testing

![image](https://user-images.githubusercontent.com/102123944/159389276-ca62bc72-baf5-413c-b909-b1fc0dde92fe.png)
![image](https://user-images.githubusercontent.com/102123944/159389356-bf4cbb75-0cb3-461d-b213-d65f8f694626.png)

I tried opening an EN save file ver of the game I downloaded online and it works properly
![image](https://user-images.githubusercontent.com/102123944/159389375-f61570fa-cc6f-4561-beb3-2ab9b10d4bb0.png)

It also just breaks if I load the save in.
https://gyazo.com/4e3c8e8e6e017ee2c61cd625487755e5

I asked in the discord if it was not supported but was asked to put in a bug instead.

Getting the JP ver of Pokemon Box to even start was hard I had to make sure the save file for it was only specifically going to use 59 blocks of memory on the virtual card, anything bigger and Pokemon Box would not allow me to make a save at all.

I learned it from this thread: https://forums.dolphin-emu.org/Thread-meet-some-tough-problems-about-gc-pokemon-box-rs-emulation-and-connection-to-gba

Attached JP Box save file:
[JP Pokemon Box Save.zip](https://github.com/kwsch/PKHeX/files/8320222/JP.Pokemon.Box.Save.zip)

There should be an Egg Nidorina and Venonat like the earlier picture

**Comment by kwsch** [comment]
Do you have a save file to reference as not loading? In the 5+ years it has been implemented (for international saves), nobody has come forward with a Japanese save file to test with for implementation.

**Comment by SynapseProperty** [comment]
> Do you have a save file to reference as not loading? In the 5+ years it has been implemented (for international saves), nobody has come forward with a Japanese save file to test with for implementation.

Hey srry I uploaded the rest of the post contents it was suppose to have I submitted early accidentally, would you want me to send the actual save file?

**Comment by Atrius97** [comment]
> Hey srry I uploaded the rest of the post contents it was suppose to have I submitted early accidentally, would you want me to send the actual save file?

Yes, please upload the savefile in question. 
You should be able to include it by making a .zip file, placing the savefile inside, and dragging the .zip file into this window when making a comment.
![Capture](https://user-images.githubusercontent.com/39707481/159390451-eb087917-006b-4a9d-8ec3-10add4824b29.PNG)
