### ISSUE TITLE
Kenya Mail not being read/written correctly in Gold/Silver (Unknown if Crystal as well)

### ISSUE THREAD

**Issue by WonderSquid** [kwsch/PKHeX#3470]
Kenya's mail will break and no longer be recognised by the game as valid if either Kenya or the Mailbox is interact with in any way. The letter cannot be manually fixed in PKHeX, and the only workaround is to either reset the "obtained" flag and get another Kenya/letter,  or restore to an earlier unedited save. 

**To Reproduce**
1. Interact with Kenya in a way that would cause its mail to be read in PKHeX (either by switching Kenya's position in the party, or by viewing and then saving the mail submenu (viewing the letter specifically does not make a difference either way, but if the letter is viewed, the "t" in "to another path" is not displayed. 
2. Attempt to interact with the man on Route 31, who will claim it is not his letter. Editing the "t" back into the letter has no effect on whether or not he'll accept it, and multiple bytes are changed. 
3. If Kenya is moved to another slot, the slot for the mailbox associated with the party slot will not update accordingly. However, I've been unable to check if this has any effect on whether or not the letter will be accepted, and the mail being in the correct slot will also result in an invalid letter anyway. Manually editing a letter into the correct position with the correct details also does not result in a legal letter. 
4. Regardless of the method used to reproduce this glitch or whether or not you attempt to restore the message, the second line of the letter will be blanked out entirely, and the NPC will not accept it. 

**Expected behavior**
PKHeX would presumably not break any letters in general. I've been unable to replicate this bug with other letters created by the player, so something about this one causes it to be incorrectly read. In addition, multiple bytes are changed upon the program "viewing" this letter even tangentially. These bytes again wildly differ if one attempts to "correct" the letter. 

**Screenshots**
![mail](https://user-images.githubusercontent.com/30328976/160270747-fea48990-c625-4a44-ae6c-0885ef1b4873.png)
![addresses](https://user-images.githubusercontent.com/30328976/160271227-9231ba1a-5ebe-4f60-8fed-36791dba4854.png)

**Additional context**
Enclosed save files show unaltered and altered bytes for the letter with the bug replicated by viewing the mail tab and saving it. Relevant addresses are 0x6FA-6FB, 0x70B, and 0x712-715 (the same information also seems to be present at 0x814-815, 0x825, 0x82C-82F).
[saves.zip](https://github.com/kwsch/PKHeX/files/8357111/saves.zip)

Hope this helps, will be happy to submit further information upon request.

**Comment by kwsch** [comment]
notes:
party mail (6 slots) is stored twice (primary and backup)
0x10 chars for first line (0x4E for `next` as last char), 0x10 chars for second line (0x50 as last char); 0x00 for end message (0x21 bytes total), with other data to round out 0x2F.
Swapping party slots swaps mail slots, assumedly, hence why mail mismatches occur and the script doesn't like it.

Game does a strcmp to check if the mail in the script's specified party slot matches the exact mail message.
https://github.com/pret/pokecrystal/blob/2fe0cbbb19df504723934f39473064033c64ef6f/maps/Route31.asm#L195
