### ISSUE TITLE
PLGE False Flag on Event Pikachu

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3474]
**Describe the problem**
Pikachu keeps flip flopping between Legal and Illegal.

**To Reproduce**
Pokémon is from Event gallery Database, Legal upon import, but once save is exported and the save is reopened it's flagged illegal. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12572974/162350671-510a0f6c-5dfa-4043-b112-901ba13b9670.png)
![image](https://user-images.githubusercontent.com/12572974/162350550-c0e1016b-ce0b-45bf-a1f7-54f2547a65bf.png)
![image](https://user-images.githubusercontent.com/12572974/162350419-ad2891d0-849b-4990-869f-49545345574e.png)

**Comment by kwsch** [comment]
Likely missing met location data, try loading the Met tab. Not sure if that's the issue.

**Comment by Ninjistix** [comment]
![image](https://user-images.githubusercontent.com/12572974/162360838-46be7335-debf-4937-b108-1ec5e23f2575.png)

**Comment by Atrius97** [comment]
> Pokémon is from Event gallery Database, Legal upon import, but once save is exported and the save is reopened it's flagged illegal.

I'm unable to replicate this behavior on latest dev build, both versions of the Shiny Pikachu event for LGPE appear legal after following the steps to try to replicate this.

**Comment by Ninjistix** [comment]
[pkhex.zip](https://github.com/kwsch/PKHeX/files/8451253/pkhex.zip)
here's everything in question, my GE and GP save file, the pkhex version, and the .wb7 files.

upon

**Comment by Lusamine** [comment]
All the Pokemon in both save files are legal for me upon immediately opening the save and the Pikachu remains legal when choosing view over and over again. I tried using the PKHeX executable in your zip as well as my own (which is latest development build).  Main difference I can see is that you're on Windows 11 and I'm on 10.  Does this happen to you on Development build as well?

**Comment by Ninjistix** [comment]
ill test the dev build, right now sec

**Comment by Atrius97** [comment]
If you are unable to recreate the issue by re-following your steps in the latest dev build, then whatever issue was causing your error is already resolved and will likely not occur in the next stable release.

**Comment by Ninjistix** [comment]
well since it seems to be fixed in the most recent dev build, I'll close this since the problem was most likely fixed already, thanks everyone.
