### ISSUE TITLE
Invalid: Pokerus strain 0 cannot be obtained in PLA (Version 22.3.19+46)

### ISSUE THREAD

**Issue by ngtunganh123** [kwsch/PKHeX#3480]
![unknown](https://user-images.githubusercontent.com/62158391/163430816-5623182b-60d2-4d4e-85fb-232f3b926ef6.png)
All pokemon in PLA masked with illegal (Invalid: Pokerus strain 0 cannot be obtained) 
I'm using Dev build Version 22.3.19+46

**Comment by Lusamine** [comment]
It's correct that Pokérus is not possible in LA, and I do not have this error on any of my legitimately obtained Pokémon.  Do you have examples you can provide that you believe are incorrectly flagged?
