### ISSUE TITLE
Non-UI Fatal Error - Running on Linux through WINE

### ISSUE THREAD

**Issue by EggEngineer** [kwsch/PKHeX#3486]
I'm not sure if someone else had this already... But I've been running PKHeX through Wine on Xubuntu Linux, I have Wine-Mono installed and a 32-bit environment with .NET 6 and .NET 4 as well, but it seems there's a font family issue or something like that now that won't run it at all.

1. Go to terminal
2. cd (directory)
3. use `wine PKHeX.exe`

I expected it to run, but something just won't work right.

**Screenshots**
All I have is this error report.

[PKHeX_Error_Report 20220504130254.txt](https://github.com/kwsch/PKHeX/files/8624608/PKHeX_Error_Report.20220504130254.txt)

**Comment by kwsch** [comment]
Fails to load fonts. Not sure if that's something you have to install when running via wine. 

PKHeX needs net461 at a minimum, not just net4

**Comment by kwsch** [comment]
Likely need to install fonts ~ https://forums.linuxmint.com/viewtopic.php?f=47&t=293498

`The requested FontFamily could not be found` `GenericSansSerif`
