### ISSUE TITLE
Add the Lock Capsule PCD Box Slot for Pokemon HeartGold and SoulSilver Save Files

### ISSUE THREAD

**Issue by DeadSkullzJr** [kwsch/PKHeX#3487]
**Is your feature request related to a problem? Please describe.**
No requests in relation to a problem.

**Describe the solution you'd like**
You should add the Lock Capsule PCD box (though separate from the rest) into the Mystery Gift section for Pokemon HeartGold and SoulSilver saves. This PCD box is only used for the Lock Capsule and is what enables the ability to partake in the event. The reason I am saying to make it separate from the other three PCD boxes is because the fourth slot doesn't function like the original three given you don't receive events in-game from it at all (I've done the tests and have thrown a random wonder cards into the slot, you can't receive anything in-game from it, you can only view the Lock Capsule information).

**Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.**
Noted, I already did the research though, the Lock Capsule PCD box information is stored at _0xB064-0xB3BB_ in the main portion of the save files, and stored in _0x4B064-0x4B3BB_ in the backup section of the save files, 855 (decimal) bytes of wonder card data is stored here. The game does the rest of the dirty work by reading the data in this location (the Lock Capsule in this case) and will allow players to partake in the event.

**Additional context**
Here is a mock-up image of what it would look like in PKHeX.
https://i.imgur.com/OhiogBF.png

**Comment by kwsch** [comment]
related: https://projectpokemon.org/home/forums/topic/37579-lock-capsule-hgss/?do=findComment&comment=258454

**Comment by DeadSkullzJr** [comment]
> related: https://projectpokemon.org/home/forums/topic/37579-lock-capsule-hgss/?do=findComment&comment=258454

I missed this thread it seems lol. Thanks for posting.
