### ISSUE TITLE
Filter Encounter by Location

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3490]
Is it possible to add a Location filter for Pokémon, so you can see all available Pokémon in a certain map location? I know you can filter by species, but then you have to hover over all of them to find the exact map you want.
![image](https://user-images.githubusercontent.com/12572974/167256999-35a8d2b4-f7da-4230-ad50-69272202c5e9.png)

**Comment by sora10pls** [comment]
`=Location=x` in the Advanced tab, where `x` is the met location index. You can use tons of batch editor commands to filter out extra parameters.

**Comment by Ninjistix** [comment]
that is invalid, I also tried `=Met_Location=Route 201` to see if I can see any/all Pokémon from Route 201, and got nothing.

I'm essentially tying to search for any pokemon by route locaiton instead of species

**Comment by Lusamine** [comment]
You're supposed to use the index, not the name of the location.  You can load up any Pokémon with the location you're interested in and open batch editor to see what that value is

**Comment by Ninjistix** [comment]
sorry was out all day, still couldn't get it to work, can you send me a screenshot, and also @Lusamine  the batch editor doesn't have the location index numbers.

**Comment by sora10pls** [comment]
![image](https://user-images.githubusercontent.com/17801814/167278009-8215b641-54e5-4fba-9c7e-99a8ab87049f.png)

**Comment by kwsch** [comment]
Open a PKM in the editor, then change the Met Location drop-down to whatever location you want to find the `location index` for.
Then, open the batch editor (via CTRL-M). Change the property drop-down to Met_Location, and it'll show the current integer value from the PKM Editor. That is your `location index`, which you can type in according to Matt's screenshot above.

**Comment by Lusamine** [comment]
This is explained at the bottom of the [Batch Editor Guide](https://projectpokemon.org/home/forums/topic/45398-using-pkhex-how-to-use-the-batch-editor-in-pkhex/).

Go down to this section.
![image](https://user-images.githubusercontent.com/30205550/167278167-fc4dd630-6c04-4a62-a66e-088d9a838275.png)

**Comment by Ninjistix** [comment]
if I don't choose a pokemon, even just using the filter with any, I get 
![image](https://user-images.githubusercontent.com/12572974/167313842-beb966ff-8732-48ca-a733-d7ceb8308389.png)

![image](https://user-images.githubusercontent.com/12572974/167313857-a6d343f4-067f-4757-bfc4-c79c5392dfd8.png)

I also tried the =Location=16 as posted above, and got the same error 

it only works if I select a species, btw using my BD save to test this (running the dev build)

**Comment by sora10pls** [comment]
Options > Settings > EncounterDb > ReturnNoneIfEmptySearch

Not a problem with the program, your settings don't allow it.

**Comment by Ninjistix** [comment]
got it working thanks
