### ISSUE TITLE
Cannot load stadium 2 saves with no registered teams

### ISSUE THREAD

**Issue by keiyakins** [kwsch/PKHeX#3494]
**Describe the bug**
PKHeX is unable to load Stadium 2 saves that have pokémon in the n64 boxes, but no registered teams.

**To Reproduce**
1. Create new Pokémon Stadium 2 save.
2. DO NOT register any teams
3. Attempt to load the save in PKHeX

**Expected behavior**
I expect it to load and show the pokémon in the n64 boxes, like it does if I register a team of random junk from the rentals.

**Additional context**
Encountered on PKHeX 20220508

**Comment by kwsch** [comment]
Please upload a reference save file.

**Comment by keiyakins** [comment]
Sure, here's a save with a couple pokémon from the start of a Pokémon Yellow game, transferred to n64 box 1.
[Pokemon Stadium 2 (U) [!].zip](https://github.com/kwsch/PKHeX/files/8693974/Pokemon.Stadium.2.U.zip)
