### ISSUE TITLE
Celebi and Deoxys in BDSP

### ISSUE THREAD

**Issue by T3chTobi** [kwsch/PKHeX#3496]
**Describe the problem**
Celebi and Deoxys from Pokemon Home are displayed as illegal in BDSP

**To Reproduce**
I'm using the lastest PKHeX version 22.05.08

**Expected behavior**
Both Pokemon should be displayed legal

**Comment by Lusamine** [comment]
The latest stable version was released before the HOME update so this behaviour is expected.  Be patient while research is happening so the program can be updated.
