### ISSUE TITLE
Problem SuMo "Location Met"

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#350]
For now i have found that Alolan Grimer, Pikipek, Ladyba and few others, when imported a save, will lose their real Location met (normally Route 1 and the first city). Also, Grimer has "internal error" if you put manually the real location.

**Comment by Arch9SK7** [comment]
I see

**Comment by fadeZero** [comment]
I have continued the adventure and found that those pokemons have the same problem:
Rockruff, Grubbin, Abra, Pichu, Spinda, Carbink, Caterpie, Spinark, Bonsly. They are from various routes, also from Ten Carat Hill. But some of the pokemon caught in ten carat hill have the right met location, and others, like Rockruff, will have in PKHEX the Mistery Zone "______". This means that if i open a save, do nothing and save many pokemon in the boxes will become unlegit even if they are legit or if i have not selected them

**Comment by fadeZero** [comment]
Confirmed that it change the locations of many pokemon to "_____" when you simply load the file in PKHEX. it must be a sort of glitch in reading the data, the problem is that it automatically change it on all those pokemons making them corrupted
