### ISSUE TITLE
Legality issue in BDSP with pokemon home

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3502]
Hi I just looked at my saves after not touching them for a while with the latest build of PKHeX. I had a legality issue pop up that is new. After putting one of my pokemon in home, and then transferring it back I now get "Invalid pokemon home transfer tracker should be 0" Like I said I literally just put the pokemon in home and transferred it back, so I am not sure if there is something new about home 2.0 but this pokemon was not illegal before this. Thanks again
[001 - Bulbasaur - 2C67CB92D5F5.zip](https://github.com/kwsch/PKHeX/files/8748776/001.-.Bulbasaur.-.2C67CB92D5F5.zip)

**Comment by NinFanBoyFTW** [comment]
Also I just looked at my PLA save and after transferring some pokemon back and forth from home, there are pokemon with the same issue, and another legality issue being "Move 1 PP is above the amount allowed". Again, these pokemon are completely legal not messed with other than dropping in home and then putting back on the save.
[706-01 - Goodra - 74405CE5605E.zip](https://github.com/kwsch/PKHeX/files/8748780/706-01.-.Goodra.-.74405CE5605E.zip)

**Comment by kwsch** [comment]
The home support branch is still a work in progress, and we have an external action log separate from the main repo. I'll make sure this issue is resolved prior to merging the branch.
