### ISSUE TITLE
My Pokemon Ranch event Pokemon (JPN)

### ISSUE THREAD

**Issue by Lunatoon** [kwsch/PKHeX#3503]
**Describe the problem**
mons distributed at Japanese events in My pokemon ranch are flagged as illegal.
It has not been added to the database.

**To Reproduce**
[illegal JPN mon.zip](https://github.com/kwsch/PKHeX/files/8749406/illegal.JPN.mon.zip)

**Expected behavior**
It will be added to the Mystery Gift database and flagged as legal unless it is an unusual move or status.

**Screenshots**
![JPfly](https://user-images.githubusercontent.com/105991595/169695712-ac02f961-f2fb-4c0d-9e30-e8a628b21c7d.png)
ex. Flygon

**Additional context**
I got most of the other mystery gifts at my Pokémon ranch from ALM and most of them were flagged as legal.
but, the Japanese Pokemon ranch event mon(in Cherish Ball), including this Flygon, are flagged as illegal.

**Comment by Lusamine** [comment]
Did you obtain these events legitimately?

**Comment by kwsch** [comment]
Looks like the mystery gift database does not have these events catalogued.

https://github.com/projectpokemon/EventsGallery/tree/master/Released/Gen%204/Wondercards/JPN

@PP-theSLAYER @Manu098vm -- might need to add these as simulated pcd files, copy from the pokecenter ones (octillery for example). I see the pk4 in the other folder.

**Comment by kwsch** [comment]
Closing here; see the issue on the correct repo. Once they're added to the events gallery, they'll be recognized after PKHeX updates its copy.
https://github.com/projectpokemon/EventsGallery/issues/276
