### ISSUE TITLE
Add Pokémon Types to PKM class

### ISSUE THREAD

**Issue by Manurocker95** [kwsch/PKHeX#3509]
As far as I see GameInfo.Strings.Types returns the type list in English but there's no way to get a pokémon's type1 and type2 strings nor index in the list.

Could you add a method for that?

thanks in advance

**Comment by kwsch** [comment]
A Pokemon's Type1/Type2 is stored in the PersonalInfo, not in the pkm data class.

You can get the PersonalInfo for a PKM object, and fetch the Type1/Type2 integer for the pkm, or, you can reference the Personal Table directly and fetch details for arbitrary species-forms.

**Comment by Manurocker95** [comment]
True, sorry for the inconveniences and thanks.
