### ISSUE TITLE
Feeding poffins to Gen1/Gen2 Transferred Pokemon in BDSP Marked as Illegal

### ISSUE THREAD

**Issue by MewtwoFanz** [kwsch/PKHeX#3513]
**Describe the problem**
When feeding a poffin to a Pokemon from the virtual console versions of RBY & GSC, it marks the pokemon with "Invalid: Contest stats should be 0."

**To Reproduce**
1. Feed a Gen1/Gen2 originating Pokemon a poffin of any kind in BDSP.
2. Dump the save file after doing so, and open it in PKHeX.
3. See that it is marked Illegal.
Here is an example with my Crystal Ilex Forrest Celebi transferred to BDSP:
[251 ★ - Serebii - 9B6C9F83E749.zip](https://github.com/kwsch/PKHeX/files/8828922/251.-.Serebii.-.9B6C9F83E749.zip)

**Expected behavior**
Should be flagged as legal, as now you can feed Gen1/Gen2 Pokemon Poffins in BDSP.

**Comment by Wanghaoran86** [comment]
Gen7 Sun/Moon Pokemon transfer to BDSP also have this problem.

**Comment by MewtwoFanz** [comment]
Thank you so much! It's marked legal now!
