### ISSUE TITLE
Encounter Database [Question]

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3515]
why doesn't the encounter database randomize the natures / gender of pokemon?

**Comment by sora10pls** [comment]
You probably have EncounterDb > UseTabsAsCriteria enabled in your PKHeX settings. Once you generate a PKM via a template, whatever is generated will then be used for each subsequent PKM. Either that, or you’re grabbing PKM with fixed genders and/or natures.

**Comment by Ninjistix** [comment]
that was it, thank you.
