### ISSUE TITLE
Add Enabling Mobile Adapter Flag as an option to Japanese Crystal Saves

### ISSUE THREAD

**Issue by DarkshadeDX** [kwsch/PKHeX#3518]
After connecting a Mobile Adapter to Japanese Pokémon Crystal, it would set a flag to determine that it had been previously connected.
This would cause a Mobile Adapter GB splash screen to pop upon booting the ROM.

This would allow the user to set information about their Mobile Profile, as well as changes the dialogue of about 6 NPCs to reference the PCC in Goldenrod City.

This flag can be set by changing the value in the save at address $E800 to 81 and the value at address $9000 to 7E.

As noted in the following TCRF article:
https://tcrf.net/Proto:Pok%C3%A9mon_Crystal/English_Localization_Prototypes#Mobile_System_GB

NOTE: This should only be legitimately possible in Japanese version of Pokémon Crystal.

**Comment by kwsch** [comment]
Those are RAM offsets, not save file offsets. Gen2 save files are 0x8000 bytes. Even if I tried changing those offsets in RAM, it does not persist on reload / in the save data.

RAM cheats that modify the ROM code can't be replicated in a save editor.
