### ISSUE TITLE
UTF-8 encoding é is broken on non-Windows systems, breaking builds

### ISSUE THREAD

**Issue by jonbarrow** [kwsch/PKHeX#3519]
**Describe the bug**
When files containing characters such as `é`, like [MenuOrderOption.cs](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Saves/Substructures/Gen8/ValueBlocks/MenuOrderOption.cs), are viewed or cloned into non-Windows systems, the character `é` is wrongly encoded and results in `�` being used instead. This breaks building unless manually changed

Checked on MacOS and Ubuntu

**To Reproduce**
Clone the repo on a non-Windows system and view `PKHeX/PKHeX.Core/Saves/Substructures/Gen8/ValueBlocks/MenuOrderOption.cs` in a code editor. Or view the raw file on GitHub in any browser

**Expected behavior**
For the formatting to not be messed up and the correct character shown

**Screenshots**
<img src="https://cdn.discordapp.com/attachments/273959618097446912/985247614201122936/unknown.png">
<img src="https://cdn.discordapp.com/attachments/273959618097446912/985246939132076112/unknown.png">
<img src="https://cdn.discordapp.com/attachments/273959618097446912/985249308746063962/unknown.png">

**Comment by kwsch** [comment]
Thanks; lemme know if there's any other problematic files re: encoding, or considerations for compiling on non-windows systems. I don't venture far from my Windows bubble ;)
