### ISSUE TITLE
SuMo: Complete Dex partially works

### ISSUE THREAD

**Issue by AnalogMan151** [kwsch/PKHeX#352]
Using the complete dex feature on a SuMo save results in some Pokémon being listed as caught, some as seen, and some previously caught Pokémon as not being discovered when loaded back into game.

**Comment by kwsch** [comment]
Should be fixed in latest commit.
https://github.com/kwsch/PKHeX/commit/ab5d1304540f02f8c7c101c5d7f39e378d618cc0

**Comment by arturfelipet** [comment]
worked here
