### ISSUE TITLE
Zeraora

### ISSUE THREAD

**Issue by jonklee99** [kwsch/PKHeX#3526]
It keeps flagging as illegal its on the latest version of pkhex i have had the event for a long time it has never flagged for swsh on pkhex so i'm reporting this to you
![Screenshot (31)](https://user-images.githubusercontent.com/90940611/174413934-8610867f-6465-49d6-ac6b-035caac3f4bc.png)

**Comment by Lusamine** [comment]
Latest commit is not latest stable release.
Download development build where this is already fixed.
Only report issues if they are present on development build.
