### ISSUE TITLE
SuMo: TM100 is removed from PKHEX

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#353]
the program delete the TM100 (and i suspect also 96-97-98-99) when open a save.

**Comment by evandixon** [comment]
I think this was fixed two hours ago.  Can you try the latest build and see if it's resolved?
http://teamcity.skyeditor.org/repository/download/PKHeX_PKHeXBuildPr/2855:id/PKHeX%20Build%20600.zip  (Click log in as guest if prompted)

**Comment by fadeZero** [comment]
i have tested but the problem of TM100 persists with the new version. Also if i try to add a new TM, i can only add from 1 to 95 and not from 1 to 100

**Comment by ApacheThunder** [comment]
I just now checked this when putting in a mon on my moon save....TM100 is still listed and noticed nothing else missing. So I'm not having this issue. not on the latest commit anyways.

**Comment by fadeZero** [comment]
maybe i have a previous build, but it's strange, i've downloaded it from the link of evandixon. Btw, if it is solved you can close this

**Comment by ApacheThunder** [comment]
Yeah the place you got it must not have the latest build. I compiled mine half an hour ago and it doesn't have this issue. :P

**Comment by Dandy562** [comment]
are you guys able to save the data and if you are how do you do it? i cant save file

**Comment by ApacheThunder** [comment]
Sounds like you have a build that predates the Moon leak. It had some demo support added in, but they didn't add the ability to save to keep the code behind the new save hash crypto private till the full game came out. Now that it's out more or less, they added the save code. You must have the older demo only build.

**Comment by kwsch** [comment]
was fixed as a result of the previous issue you had filed
fix: https://github.com/kwsch/PKHeX/commit/27ac04022d7df0ad07d728aba9acb897d9b25e1e
issue: https://github.com/kwsch/PKHeX/issues/351

There's other items that are in incorrect pouches (looks like EV items are in Medicine)
