### ISSUE TITLE
Pokémon generated/imported into slots in XD vanish ingame

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3530]
**Describe the bug**
Pokémon generated in XD may not always appear in the box slots. Editing/moving Pokémon that are already in XD (including those traded from GBA) appear to work perfectly fine, but attempting to load a pk3 or Pokémon from the encounter database yields an empty slot.

Before:
![Before PKHeX](https://user-images.githubusercontent.com/39707481/174452890-aeaa46a6-3a6f-4388-a239-7a17f7e2e667.PNG)
![Before Ingame](https://user-images.githubusercontent.com/39707481/174452892-bf36f166-544c-4cd4-beed-a5fe24e8da9a.png)
After generating encounter database Zigzagoon, they do not appear ingame, notice the Snorlax I moved into the adjacent slot appears without issue:
![After PKHeX](https://user-images.githubusercontent.com/39707481/174452896-437e0b5a-5b71-486f-b06e-72f60e527c4e.PNG)
![After Ingame](https://user-images.githubusercontent.com/39707481/174452899-2f7b8520-6fb8-4d80-81c7-dcf453cf08cb.PNG)

**To Reproduce**

Savefiles from before and after:
[XD Gale of Darkness Saves.zip](https://github.com/kwsch/PKHeX/files/8934159/XD.Gale.of.Darkness.Saves.zip)
(Trainer details altered for privacy, bug was tested and occurred both before and after changing trainer details)

**Additional context**
Occurs in latest stable and latest dev build of PKHeX, (also occurs without any plugins).
Tested on Dolphin and retail hardware, (save originated from retail), no noticeable difference, bug occurs in both.

This savefile was previously an untouched retail savefile dumped directly via homebrew, but I was unable to reproduce the issue on a brand new savefile.

I'm unsure what is different about this savefile that is causing PKHeX not to correctly write to box slots, aside from having completed a significant portion of the game, and having previously traded with GBA, but I don't see how either would cause this issue.

**Comment by Atrius97** [comment]
I created a Zigzagoon, (I copied immutable values so it would be the same pokemon across the board), and performed a few tests.

Test 1: Generated it directly into party slot 5 in XD from encounter database, did not appear ingame.
Test 2: Generated it in Ruby, exported to .pk3, imported into party slot 5 in PKHeX, did not appear ingame.

Test 2.5: Generated it in XD, exported to .xk3, imported into party in Ruby. When opening the trade between XD and Ruby, the Zigzagoon did not appear in the trade window in my Ruby party, even though it did appear in my party when opening the Ruby normally. 
Whatever the issue is persists even when an .xk3 of an affected pokemon is imported into other games, XD seemingly can't see it at all.

Test 3: Generated it fresh in Ruby, traded it to XD, Zigzagoon appeared in trade window and traded normally.

Savefiles from Test 1/2 (Zigzagoon Generated.gci) and Test 3 (Zigzagoon Traded from GBA.gci):
[GBA Trade VS PKHeX Test.zip](https://github.com/kwsch/PKHeX/files/8934303/GBA.Trade.VS.PKHeX.Test.zip)

**Comment by kwsch** [comment]
What does the Zigzagoon data look like if transferred into XD legitimately?

PKHeX has logic to clear the "Invalid" flag, but doesn't initialize a blank xk3 any other way.

**Comment by Atrius97** [comment]
I'm not entirely sure but they do appear to have a difference, these 4 bytes appear different between the imported/generated version (invisible ingame), and the legitimately traded version
![Byte Comparison](https://user-images.githubusercontent.com/39707481/174457448-4d9075f6-0fc4-4bf2-bf3d-63a69e3d8047.PNG)
