### ISSUE TITLE
BDSP: loading Gen 3-4 Poké Transfer Pokémon to tabs, temporarily shows them as illegal

### ISSUE THREAD

**Issue by ghost** [kwsch/PKHeX#3533]
**Describe the bug**
On BDSP save file (20220601), importing past-gen Pokémon originating from Gen. 3-4, when loading them to tabs, the UI will show a red exclamation point on tabs as if it were illegal, which turns back to a green check mark upon clicking it.

Using these as an example:
https://github.com/ReignOfComputer/RoCs-PC/blob/master/15%20-%20Gen%20V%20-%20B2W2%20Collection/Save%20Data/Pokemon%20White%202.sav
https://github.com/ReignOfComputer/RoCs-PC/blob/master/33%20-%20Gen%20VIII%20-%20BDSP%20Collection/Save%20Data/0100000011D90000%20-%20BD/SaveData.bin

Note: Gen. 3 event Pokémon (from events database) are unaffected, for some reason?

**To Reproduce**
1. Load BDSP save and B2W2 save in separate windows
2. Drag Pokémon of Gen 3-4 origin over from B2W2 to BDSP to transfer them
3. Right-click --> View on BDSP side

**Expected behavior**
UI should recognise Pokémon as legal right away, instead of needing that extra nudge.

**Screenshots**
<details>
  <summary>Example:</summary>

  Gen 3 origin:
  ![image](https://user-images.githubusercontent.com/105753022/174483815-55551921-0757-48cb-a08b-8602be89a256.png)

  Gen 4 origin:
  ![image](https://user-images.githubusercontent.com/105753022/174483691-87bd4622-fb47-4691-9eca-fdbf895bfe9f.png)

  Gen. 3 Event:
  ![image](https://user-images.githubusercontent.com/105753022/174483709-323e38b6-f3e7-47e9-85a3-1ca454bd2588.png)

  Gen. 4 Event:
  ![image](https://user-images.githubusercontent.com/105753022/174483868-8c2922b4-e669-484f-86d5-0bbda022800b.png)

  B2W2 origin:
  ![image](https://user-images.githubusercontent.com/105753022/174483725-7da45fa4-e8d7-49ca-a830-859e9ec0478d.png)

</details>

**Additional context**
With SetUpdatePKM == False, the only legality issue after transferring is an incorrect handling trainer, so I believe this is only a display bug rather than an actual legality problem. Ctrl-Rightlick --> Legality without loading to tabs doesn't find anything unusual either, and Verify All PKMs only complains about missing home tracker which is unrelated.

**Comment by Lusamine** [comment]
I am not able to replicate this.  Are you testing on Development build or the latest stable release?  If you only used latest stable, can you try this on [development build](https://projectpokemon.org/home/files/file/2445-pkhex-development-build/) and see if the issue is already fixed?

![bulbasaur](https://user-images.githubusercontent.com/30205550/174484657-f8812e92-9917-44f0-b06f-3d313e12aabb.gif)

**Comment by Lusamine** [comment]
Usually the development build has fixes on top of stable, so check on there first before opening an issue.
