### ISSUE TITLE
Pokémon Sw&Sh - In-Game Trades - Invalid: TID sharing across different trainer names detected.

### ISSUE THREAD

**Issue by Immersion95** [kwsch/PKHeX#3546]
In-game trades are valid but returns this message with "Verify All Pokémons".

_Invalid: TID sharing across different trainer names detected._

Why ? There 2 trainers with the same TID with the in-game trades : 

**English :** 
> ID : 101141
> Name : Kapoor & Regina

**French (in my case) :** 
> ID : 101141
> Name : Salvador & Régiona

Please see here : https://www.serebii.net/swordshield/ingametrade.shtml

It may be intended so please close this issue if it is.

**Comment by Lusamine** [comment]
This check does not exclude every single edge case where sharing immutable values is possible -- that's up to you to exclude.
