### ISSUE TITLE
It doesnt let me save once am finish?

### ISSUE THREAD

**Issue by Dandy562** [kwsch/PKHeX#355]
after am done with the editing i go to save, and it doesnt let me click the save option.

**Comment by kittleapps** [comment]
I'd assume they need additional information, as this seemed too vague for me personally. (what did you edit, what are you saving, which save option)

Assuming you're editing your imported game-save (e.g. File > Open > main), when you're done do File > Export Sav... > export (main/Backup). this is working for me personally on Pokemon Moon. Pokemon Alpha Sapphire, and Pokemon Y (Checked just before i commented here using the latest source code)

Assuming you mean the Pokedex's Save, at the time i am writing the checkboxes/Values don't set properly for Pokemon Moon, so the save inside the Pokedex's menu will not work. (and is a known issue, based on #352 at least)

**Comment by Dandy562** [comment]
am using pkhex with pokemon moon, after i drag my save file to pkhex and edit some pokemon, when i go to save PGL.JPEG wont let me click on it.

**Comment by kwsch** [comment]
Hid JPEG button as it is not in gen7; https://github.com/kwsch/PKHeX/commit/c6078cb5274927a9bfbfb73671bebcfafad91572

Use the File->Export SAV->Export main
