### ISSUE TITLE
Issue with PKHeX loading Omega Ruby Save I haven't touched in a while

### ISSUE THREAD

**Issue by Tua0** [kwsch/PKHeX#3552]
I just started homebrewing my old 3ds after years of not using it and wanted to try using pkhex to modify the saved file of my Omega Ruby game. However, every time I try to open the main save with pkhex it gives me this error: 'Invalid save file loaded. Aborting.'

For extra info: my 3ds is from America, the game is from the e-shop so it is saved in the sd card, and this is the first time I have ever tried homebrewing/pkhexing the game

I hope you can help me with this. I will upload the main file so you can take a look. 
Thanks in advance for any help.
[main.zip](https://github.com/kwsch/PKHeX/files/9128938/main.zip)

**Comment by sora10pls** [comment]
Valid Omega Ruby/Alpha Sapphire save files are `0x76000` (472KB) in length, yours is `0x65600` (406KB). This is not an issue with PKHeX, but rather with how you're dumping and moving your save data over to your computer.

I recommend using JKSM or Checkpoint to export your save data. There are plenty of online tutorials on how to do so, such as [the ones on ProjectPokémon](https://projectpokemon.org/home/tutorials/save-editing/managing-3ds-saves/), which includes a subsection on handling "corrupted" saves.

**Comment by Tua0** [comment]
Thanks a lot for the reply, I actually used checkpoint to get the main save filed. I will read about the possible fixes for my save file to see what i can do. thanks  lot

**Comment by Tua0** [comment]
Wait I just realised I uploaded the wrong main save file lol. This is the actual main file from the Omega Ruby game extracted with the Checkpoint app

[main.zip](https://github.com/kwsch/PKHeX/files/9128981/main.zip)

**Comment by kwsch** [comment]
Please don't submit reports to multiple places... This is properly communicated as an issue with you transferring/dumping data incorrectly.

I have provided a similar response on the forums; continue discussion there rather than here, as dumping data is unrelated to the scope of the program & the issue tracker here.

https://projectpokemon.org/home/forums/topic/61819-issue-with-pkhex-loading-omega-ruby-save-i-havent-touched-in-a-while/
