### ISSUE TITLE
PkHex not recognizing 'main' save file from Omega Ruby

### ISSUE THREAD

**Issue by Tua0** [kwsch/PKHeX#3553]
I already made a post about this issue before but I uploaded the wrong 'main' save file, this is the story:

I just started homebrewing my old 3ds after years of not using it and wanted to try using pkhex to modify the saved file of my Omega Ruby game. However, every time I try to open the main save with pkhex it gives me this error: 'Invalid save file loaded. Aborting.'

For extra info: my 3ds is from America, the game is from the e-shop so it is saved in the sd card, and this is the first time I have ever tried homebrewing/pkhexing the game. I used the app Checkpoint to obtain the main save file

I hope you can help me with this. I will upload the main file so you can take a look.
Thanks in advance for any help.

[main.zip](https://github.com/kwsch/PKHeX/files/9129604/main.zip)

**Comment by kwsch** [comment]
Duplicate: #3552
