### ISSUE TITLE
[HG/SS] Togepi Egg Invalid

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3559]
**Describe the problem**
Togepi Egg is marked invalid.

**To Reproduce**
[175 - Egg - A335D19A7332.zip](https://github.com/kwsch/PKHeX/files/9199100/175.-.Egg.-.A335D19A7332.zip)

**Expected behavior**
It should be valid, was collected from Prof Assistant in Pokemart

**Screenshots**
![image](https://user-images.githubusercontent.com/12572974/181255086-2db7c540-7b63-4883-90cc-012a178ecadd.png)

**Comment by sora10pls** [comment]
Not flagged on latest commit, please do not report "bugs" with legality checks unless you are using the most up-to-date build possible.
