### ISSUE TITLE
The number of items in bag cannot be set as 0

### ISSUE THREAD

**Issue by 139god** [kwsch/PKHeX#356]
So there is an extra Sparkling Stone in my bag.

**Comment by evandixon** [comment]
Try setting the `Sparking Stone` to `(None)`

**Comment by 139god** [comment]
@evandixon 
It works but I dont know whether or not it will cause some side effects
thanks for your reply

**Comment by kwsch** [comment]
Changed in recent commit:
https://github.com/kwsch/PKHeX/commit/fc97d688472aa90ef4c89a66016d5c7cf7fef1ac
Resolves user issue as reported.
