### ISSUE TITLE
[SWSH] Marill from Cool Off Event is flagged as illegal.

### ISSUE THREAD

**Issue by twinbee321** [kwsch/PKHeX#3565]
**Describe the problem**
a Marill from Cool Off Event has fixed moves; 'Play Rough', 'Aqua Ring'
but these moves are can be learned after at least lvl 21. and this Marill is lvl17 because 1 rarity.
so these moves are causing Marill flagged as illegal even though it's legal.

**To Reproduce**
[183_-_-_A6CC383EC0B9.zip](https://github.com/kwsch/PKHeX/files/9286949/183_-_-_A6CC383EC0B9.zip)
Here is a sample pkm from my game

**Expected behavior**
The Marill should be flagged as legal.

**Screenshots**
![PKHeX_10CneoPxwH](https://user-images.githubusercontent.com/99508812/183569424-aa164136-47df-4c05-bf8b-930df5c7e5a1.png)
![PKHeX_VmXjf27bvV](https://user-images.githubusercontent.com/99508812/183569478-e328bd9e-8aaf-4ef8-a071-d3dc03cb4736.png)

**Comment by kwsch** [comment]
PKHeX does not know about future event encounters, so the June release won't know about July event data (Cool Off Event).

Works fine on the latest commit.
