### ISSUE TITLE
(BDSP) (None) Loaded as an unusable item in game, cannot remove it via save editing healing items

### ISSUE THREAD

**Issue by MewtwoFanz** [kwsch/PKHeX#3568]
**Describe the bug**
An item labeled as None in PKHeX is loading into the healing items pocket as an unusable item in-game, and I cannot remove it whatsoever.

**To Reproduce**
1. Go to 'Healing Items'
2. Click on 'Give all Items'
3. Click 'Save'
4. Save changes to save file
5. Import the save to your console
6. Load the game, and find the Healing Items Pocket
7. Find the glitched None item.

**Expected behavior**
It's supposed to not give me such a glitched item.

**Screenshots**

**Additional context**
It cannot be sold, nor thrown away, hence it clogs up space in your bag.

**Comment by sora10pls** [comment]
Unable to replicate after several tests on both base game and Ver 1.3.0.
Make sure you're using the latest development build prior to testing, and didn't use any third party cheat codes that may have mucked your inventory data.

![top](https://user-images.githubusercontent.com/17801814/184494169-e44616ba-b30e-4cb7-bee1-76bdf516350d.png)
![bottom](https://user-images.githubusercontent.com/17801814/184494172-acd6696b-1a87-40d3-9ff6-c03ad8d35e05.png)

**Comment by MewtwoFanz** [comment]
I swear, I did not do anything like that! I really just one day found the item there, with no clue as to how it got there. And I can't even remove it. What am I going to do?

**Comment by Atrius97** [comment]
Restore a savefile backup that doesn't contain the glitched item.
>  I really just one day found the item there, with no clue as to how it got there.

This implies that PKHeX didn't cause it and it just appeared on it's own/it was there before selecting "Give all Items", in which case did you just make up the steps to replicate the problem?

**Comment by MewtwoFanz** [comment]
I think, I might have found something that must've contributed to this: When clicking give all in the healing items section, you aren't given any Sacred Ashes. Giving myself some of it manually didn't fix my issue, but it may have contributed to it in some way.

**Comment by MewtwoFanz** [comment]
And no, I Did not make up the steps. That's how I remember finding it in my inventory.

**Comment by sora10pls** [comment]
Those Sacred Ashes in my photo were manually added after giving all items, and even without doing it, I couldn’t replicate, so that’s not the issue.

**Comment by MewtwoFanz** [comment]
Well, I really don't know then.
Where could I get further help? I just feel really bad for bugging you guys over this.

**Comment by kwsch** [comment]
If you don't mind sharing your save file, you can send it to one of us on [Discord](https://discord.gg/pkhex) so we can identify what's wrong with your `(None)` item slot. Can't identify what the behavior is without replicating the behavior :)

**Comment by MewtwoFanz** [comment]
Ok, Which discord server? I clicked the link, but it said the invite was invalid.

**Comment by kwsch** [comment]
Try https://discord.com/invite/tDMvSRv

**Comment by MewtwoFanz** [comment]
Just joined the server. Do you mind if I DM you through there? Or is that not allowed?

**Comment by Vikingtons** [comment]
I've been able to reproduce this issue too. Happens whenever I edit a pokemon in my party (EVs, IVs, Abilities, Moves etc) and export the save back to the game. 
![image](https://user-images.githubusercontent.com/9853124/190861460-27fe1ae6-8a7a-44ff-bb2e-25905e250ed4.png)

Can provide a clean save file for repro if it helps

**Comment by Lusamine** [comment]
> I've been able to reproduce this issue too. Happens whenever I edit a Pokemon in my party (EVs, IVs, Abilities, Moves etc) and export the save back to the game. I do not interact with the player inventory in any way. ![image](https://user-images.githubusercontent.com/9853124/190861460-27fe1ae6-8a7a-44ff-bb2e-25905e250ed4.png)
> 
> Can provide a clean save file for repro if it helps

The issue in this thread was caused by using mods.
You claim your issue is not from using mods, so it is not the same issue.
It would be better to create a new issue, complete with the reproduction steps, and provide any files there instead of necromancing a closed issue about using mods.

**Comment by Vikingtons** [comment]
> > I've been able to reproduce this issue too. Happens whenever I edit a Pokemon in my party (EVs, IVs, Abilities, Moves etc) and export the save back to the game. I do not interact with the player inventory in any way. ![image](https://user-images.githubusercontent.com/9853124/190861460-27fe1ae6-8a7a-44ff-bb2e-25905e250ed4.png)
> > Can provide a clean save file for repro if it helps
> 
> The issue in this thread was caused by using mods. You claim your issue is not from using mods, so it is not the same issue. It would be better to create a new issue, complete with the reproduction steps, and provide any files there instead of necromancing a closed issue about using mods. If you are in fact using mods, the solution is not to use mods.

Right, I didn't notice any mention of mods from the OP. I've not been using anything besides the base game (+V 1.3.0) with the latest Ryujinx or Yuzu builds.

I'll try to figure out the minimum viable repro and I will funnel the info into a new ticket. Cheers.
