### ISSUE TITLE
Language in Trainer Data still cannot be set as CHT or CHS

### ISSUE THREAD

**Issue by 139god** [kwsch/PKHeX#357]
Please add it, ty.

**Comment by evandixon** [comment]
Duplicate of #345

Have you tried the latest build?  (Say "log in as guest" if prompted)
http://teamcity.uniquegeeks.net/repository/download/PKHeX_PKHeXBuildPr/2859:id/PKHeX%20Build%20602.zip

**Comment by 139god** [comment]
@evandixon In pokemon editor the language option is nine
What I said is in the Trainer Info section, where you can set the start time, ID, played hours, etc

**Comment by ericjwg** [comment]
fixed
