### ISSUE TITLE
LPA : Max Ether

### ISSUE THREAD

**Issue by Rilgar84** [kwsch/PKHeX#3574]
In Legend Pokémon Arceus you forgot Max Ether an item

**Comment by kwsch** [comment]
It's there.
![image](https://user-images.githubusercontent.com/6393368/186779025-38670adb-6f06-4868-9137-71acb645bf33.png)

**Comment by Rilgar84** [comment]
thanks, the problem comes from the name in French, you put "Max Elixir" instead of "Soin PP".

**Comment by Lusamine** [comment]
You said "Max Ether" in the original post and now "Max Elixir". This also seems to be there?
![image](https://user-images.githubusercontent.com/30205550/186782414-9628a68f-a8b1-4e98-8193-98c8b5b06f45.png)

Bulbapedia indicates that it uses "Élixir Max" from LGPE onwards, not "Soin PP".
![image](https://user-images.githubusercontent.com/30205550/186782440-438bee3e-12e4-4a91-9fd6-5f031b03e8bf.png)

**Comment by Rilgar84** [comment]
https://www.pokepedia.fr/Soin_PP This, but thanks

**Comment by Lusamine** [comment]
I see what you're saying. The French version has "Max Elixir" = "Maxi Soin PP" and "Max Ether" = "Soin PP". The items simply use the names from previous games instead.

**Comment by Rilgar84** [comment]
yes exactly :)

**Comment by Lusamine** [comment]
In the future, when making issues, it's best to give as much detail as possible so other people can understand how to have the same problem.  In this case, knowing that it's a change in the French translation was necessary to understand the issue.

**Comment by Rilgar84** [comment]
yes i'm sorry, i don't use the english version of pkhex :(
thanks for you
