### ISSUE TITLE
Some Gen 1 Event Flags not correctly resetting

### ISSUE THREAD

**Issue by TwoTailedFox** [kwsch/PKHeX#3576]
**Describe the bug**
Currently using NA/EU Pokémon Red. The Eevee and Hitmonlee event resetters do not work; they will reset within the program, and upon reloading the save they will also show the events still in a state of reset (with the buttons greyed out), but when loaded in-game, the events are still in their pre-reset states.

Platform is RetroArch 1.10.3, using VBA-M core on a GNU/Linux OS with save files in SRM format.

**To Reproduce**
I have included two files for this purpose. File 1 is the save file before event reset, while File 2 is post-event reset. The second file, when loaded in PKHeX, will show the event flags reset, but if loaded in-game will not show the events ready to trigger again.

**Expected behavior**
The events are supposed to reset back to their original state (i.e., the Eevee event is supposed to result in a new Eevee Pokémon in Celadon becoming available to the player, while the Hitmonlee/Hitmonchat event is supposed to result in both Pokémon being available for collection with the fifth NPC Blackbelt trainer urging you to pick one if you talk to him).

**Additional context**
[Pokemon - Red Version (USA, Europe) (SGB Enhanced)-1.zip](https://github.com/kwsch/PKHeX/files/9438708/Pokemon.-.Red.Version.USA.Europe.SGB.Enhanced.-1.zip)
[Pokemon - Red Version (USA, Europe) (SGB Enhanced).zip](https://github.com/kwsch/PKHeX/files/9438710/Pokemon.-.Red.Version.USA.Europe.SGB.Enhanced.zip)

**Comment by kwsch** [comment]
You sure about that? I loaded in the second attachment to Red, and could receive Hitmonlee.
![image](https://user-images.githubusercontent.com/6393368/187055072-3f019097-aae7-4d3d-acee-7429f176dc8c.png)
