### ISSUE TITLE
Swablu Egg from Box Ruby Sapphire flagged as illegal

### ISSUE THREAD

**Issue by wararjey** [kwsch/PKHeX#3577]
[swablu.zip](https://github.com/kwsch/PKHeX/files/9463146/swablu.zip)
This egg was obtained from starting Box Ruby Sapphire with Dolphin, and linking it via virtual Link Cable with a Ruby game played with mgba.

22.08.31, flags it as illegal. 22.06.26, does not complain.

Regards,

**Comment by Kermalis** [comment]
![image](https://user-images.githubusercontent.com/29823718/188057143-6b334ebf-6a9a-461a-bdba-6404d1fe47ce.png)

Looks like a mistake (2735)
