### ISSUE TITLE
Database search does nothing

### ISSUE THREAD

**Issue by bjstrange** [kwsch/PKHeX#3580]
**Describe the bug**
Searching for a species show no results, even when the mon is shown on the initial db load window

**To Reproduce**
Open Database
Select a species
Click Search
Nothing is found

**Expected behavior**
Matching species shown

**Screenshots**
![loaded](https://user-images.githubusercontent.com/35301140/188687822-498543ae-1cd7-4949-bb77-032f9af4575e.png)
![search](https://user-images.githubusercontent.com/35301140/188687853-100b2d11-3594-476a-b3ba-d1a359357aec.png)
![after](https://user-images.githubusercontent.com/35301140/188687869-b67ce6ee-87cc-473d-9624-994f337961c4.png)

**Additional context**
On the initial window opening all of the contents of the db folder show. I'm just not able to limit the search to specific mon or change any search settings such as do not search boxes.

**Comment by Lusamine** [comment]
This is already fixed in https://projectpokemon.org/home/files/file/2445-pkhex-development-build/.

Bugs should be tested on dev build / latest commit first before opening an issue.
