### ISSUE TITLE
Platinum Save Not Working?

### ISSUE THREAD

**Issue by Al2707** [kwsch/PKHeX#3581]
Hello all! I'm new to PKHex and it seems that something went wrong when I tried to insert my Pokémon Platinum save file into the program.
My party and and Pokémon in the daycase all appear as red squares. I can't interact with them.
![image](https://user-images.githubusercontent.com/113258719/189496110-6455347e-66d2-4a84-a00a-c4f6be1378b5.png)
Is this a bug or is it fixable? I can give the save file if it's needed.

**Comment by kwsch** [comment]
Party editing works fine. You have a bad save dump; dump it again and ensure that all other aspects of the save (like box & trainer info) are correct.
