### ISSUE TITLE
LG save always gets loaded as FR save when opened from the Folder List

### ISSUE THREAD

**Issue by wararjey** [kwsch/PKHeX#3582]
**Describe the bug**
When opening a FR or LG save, PKHeX asks if the file is a FR or LG save.
When loading the LG save normally via the "Open" menu entry, when selecting "LG", the save correctly gets loaded as LG save.
However, when opening an LG save from the Folder List, the save gets loaded as a FR save, as I can see in the PKHeX window's title bar.
Furthermore, once I have exported the save at least once, after loading it via the "Open" menu entry, and not the Folder List, upon restarting PKHeX and trying to load the save via the Folder List, the save gets listed as FR save.

**To Reproduce**
1. Load a LG save for the first time via "Open"
2. Save it, restart PKHeX. Open the folder list
3. The "remembered" save has FR displayed as its "Game".
4. Select and "open" the save from the folder list. PKHeX asks if the save is FR or LG. Choose LG.
5. Save gets loaded as FR, as displayed in the window's title bar.
6. Load the save via the "open" menu entry. When selecting LG the save gets correctly loaded as LG save

**Expected behavior**
When loading a save from the folder list (Ctrl-F), the FR/LG game selection dialog should work and the save be loaded as LG save.
Icing on the cake: Perhaps the folder list could remember the last game selection, too, so that the save appears as LG in the folder list, as well? Even more optional: Once PKHeX does remember if the save loaded via the folder list is a LG save, the selection dialog could be set to have the correct game pre-selected so that the user only needs to click "okay" to load the save as LG.

Obvious workaround is to always open the LG save via "Open" and not the folder list. However, if you have many saves from many games in a somewhat complex folder structure, this can be a bit tedious.

Regards,

**Comment by kwsch** [comment]
In generation 3, there is no way to differentiate a `FR` save from a `LG` save without user input -- can't rely on an appropriately named file. The only thing it's used for is to see which Deoxys form to display, and for a valid trainer Version from the start (not a lumped one like `FRLG`

The above commit will correctly show the override version in the program title. It previously still initialized the savedata as a `LG` save (`Deoxys-Defense` form), just the program title was reflecting the original un-overriden version string.
