### ISSUE TITLE
Shiny Eternatus event

### ISSUE THREAD

**Issue by albertodev01** [kwsch/PKHeX#3589]
**Describe the bug**

Shiny Eternatus [event](https://projectpokemon.org/home/files/file/4819-galar-shiny-eternatus/) is marked as illegal since it's not yet in the database

**Expected behavior**

The `.wc8` file attached below should be leagal

**Additional context**

[eternatus.zip](https://github.com/kwsch/PKHeX/files/9595529/eternatus.zip)

This is the file I used (the same as in projectpokemon.com)

**Comment by Lusamine** [comment]
New events released after PKHeX was released will not be recognized until the next stable release.  Add the wonder card yourself to an `mgdb` folder.

This is the same answer you were told previously:
https://github.com/kwsch/PKHeX/issues/3264
https://github.com/kwsch/PKHeX/issues/3109

You don't need to open issues for every new event.
