### ISSUE TITLE
Fixed：Support for Chinese archives

### ISSUE THREAD

**Issue by q67732897** [kwsch/PKHeX#359]
![1](https://cloud.githubusercontent.com/assets/6880568/20162738/f2301e94-a731-11e6-86ac-5897c6d47d45.png)
PKHeX-master\PKHeX\Resources\text\locale\languages.txt

![2](https://cloud.githubusercontent.com/assets/6880568/20162740/f5b9fd0a-a731-11e6-8df0-c27e11e86ae5.jpg)
PKHeX-master\PKHeX\Subforms\Save Editors\Gen7\SAV_Trainer7.cs

**Comment by ericjwg** [comment]
newest commit fixed the problem.

just few mins before your post.

**Comment by q67732897** [comment]
@ericjwg OK

**Comment by ericjwg** [comment]
![image](https://cloud.githubusercontent.com/assets/19739613/20163262/15724300-a6c9-11e6-856f-f78693e51904.png)
