### ISSUE TITLE
Gen 3 PokeBlocks use 7 bytes while aligning to 8 bytes. PKHeX ignores the last byte, leading to corruption

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3590]
Using the API, you can modify PokeBlocks, but doing so causes invalid PokeBlocks to appear in-game:
![image](https://user-images.githubusercontent.com/29823718/191822178-28057ff5-b171-4b23-943b-d44a3f996ac8.png)

Changing SIZE to 8 is enough to fix it, but I can't open a PR at this time.

```cs
public sealed class PokeBlock3
{
    public const int SIZE = 8;
    private readonly byte[] Data;
    public PokeBlock3(byte[] data)
    {
        Data = data;
    }
	...
```

![image](https://user-images.githubusercontent.com/29823718/191822421-eac3168b-8ddb-481d-9ce1-a5de322e69d1.png)

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/0a9fbfc8c38ec88c7cff71c4dea5e2992fcb2022
