### ISSUE TITLE
Minior possible incorrect battle form check

### ISSUE THREAD

**Issue by JelleInfinity** [kwsch/PKHeX#3592]
https://github.com/kwsch/PKHeX/blob/05d43cef7cdf9918291372523521e1df4561ba24/PKHeX.Core/Legality/Tables/FormInfo.cs#L32

Shouldn't this account for the base form? Currently form 0 is also a battle form.

If 0 is the normal form it should just not check Minior at all and just use the
`default:
    return form != 0;`

**Comment by sora10pls** [comment]
Minior has 14 forms in total. The first 7 are its Meteor Forms, **which are battle only**, and the last 7 are its Core Forms, which can exist both in and out of battle. The current logic is correct.
