### ISSUE TITLE
SWSH - batch editor Language

### ISSUE THREAD

**Issue by CompaHeart** [kwsch/PKHeX#3593]
i try to find the correct number for germany  to change the pokemon language from ENG ( english ) to GER ( germany ), found some links to your github but everytime i only get this ; The 'kwsch/PKHeX' repository doesn't contain the 'PKHeX.Core/Resources/text/en/text_Items_en.txt' path in 'master'.

exist a list or something to see the numbers for the countrys? read many times the faq about batch editor but i dont understand how i figured out by myself :/

**Comment by kwsch** [comment]
"found some links" is not descriptive enough. If there is an external guide that someone has written, that has outdated links pointing to files that have moved, that's on them to fix. You're still able to [search filenames on GitHub](https://github.com/kwsch/PKHeX/find/master).

The tutorial on ProjectPokemon describes how to find the "value" for a given "name" displayed in the PKM Editor at the very bottom of the guide.
![image](https://user-images.githubusercontent.com/6393368/192381878-306ddd6d-43bc-40fc-96e8-5e336e5b1670.png)
