### ISSUE TITLE
make compiled exe files available for all release on the github releases page

### ISSUE THREAD

**Issue by shadow-absorber** [kwsch/PKHeX#3596]
making all the compiled exe files available will make it easier to figure out when a bug started happening and how to fix it.... it will also help mac and linux users using wine to run the app if something suddenly breaks on new releases making pkhex not run.

**Comment by kwsch** [comment]
No.

The ProjectPokemon site already hosts Downloads for current releases, past releases (for about a year), and different builds for the latest commits (not releases).

**Comment by shadow-absorber** [comment]
oh missed that you could download old version from projectpokemon... thanks for including that info... will go there
