### ISSUE TITLE
Allow load of 129 KB save files for GBA games

### ISSUE THREAD

**Issue by MrPerson0** [kwsch/PKHeX#3604]
With mGBA 0.10.0, the RTC is now written to the save file for GBA games:  https://github.com/mgba-emu/mgba/issues/240

For example, it adds line 0x2000 to US Emerald making the file 129 KB instead of 128 KB. Can you allow PKHeX to read this expanded save file?

**Comment by sora10pls** [comment]
This has already been addressed by a recently merged pull request, which was opened not too soon before you opened this issue: #3603

**Comment by MrPerson0** [comment]
My bad, should have looked at pull requests instead of just looking at issues!
