### ISSUE TITLE
Legality issue with LG Height Weight

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3607]
Hey long time no see. I was looking at my saves today and I saw that a bunch of my pokemon in LG are now illegal from mismatched heights and weights. I have never touched any of these pokemon with PKHeX and they were legal until recently.
[063 - Abra - EE51355D6014.zip](https://github.com/kwsch/PKHeX/files/9825585/063.-.Abra.-.EE51355D6014.zip)

**Comment by Lusamine** [comment]
If you ever viewed and set them with older version of PKHeX before the height/weight calculation was corrected earlier this year, they will become illegal. The value should be corrected if you tick the "Auto" box.  Current legality checks should be accurate.
