### ISSUE TITLE
Legality issue with Gen 6

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3608]
I was also checking my gen 6 saves and found a bunch of pokemon that have never been touched and were never illegal with the error "Invalid: HT Memory: Invalid Feeling"

[483 - Dialga - 0205842E6624.zip](https://github.com/kwsch/PKHeX/files/9825595/483.-.Dialga.-.0205842E6624.zip)

**Comment by Lusamine** [comment]
This legality check was activated recently. If you ever used an older version of PKHeX to set these Pokémon in a box, they could potentially have gained an invalid feeling. Invalid flag is correct.
