### ISSUE TITLE
Legality with Melmetal Pokemon Home event from 2020

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#3609]
The only other one I see right now is my Melmetal Pokemon home event from 2020. It seems to just be missing and shows up as illegal.

[809 - Melmetal - F14600000000.zip](https://github.com/kwsch/PKHeX/files/9825692/809.-.Melmetal.-.F14600000000.zip)

**Comment by Lusamine** [comment]
This does not look like a legitimate event file. Please only report data that has not been fabricated.

Yours:
![image](https://user-images.githubusercontent.com/30205550/196844038-b60813bf-d3a2-472e-a33f-2c82b776390b.png)

As you can see, the SID/TID should be 3014/808809.
Reference: https://projectpokemon.org/home/files/file/4345-pok%C3%A9mon-go-transfer-gift-melmetal/

**Comment by NinFanBoyFTW** [comment]
I didn't fabricate this event, this is how I received it exactly from pokemon home, then transferred through to Sword and shield. I don't touch these events I only preserve what I get

**Comment by NinFanBoyFTW** [comment]
Also I am pretty sure that there was a bug for a while in pokemon home where the sid was not working correctly with these events or something along those lines. Nothing was ever altered here

**Comment by Lusamine** [comment]
I do not see any documentation that some GMax Melmetal had an SID of 0, and my personal one claimed 4 days before yours has the correct SID. If yours is the only one with the incorrect TID, the assumption is that something has happened to alter yours.
