### ISSUE TITLE
S/M - Item legality checks are misplaced

### ISSUE THREAD

**Issue by webrunners** [kwsch/PKHeX#361]
I know that Rare Candy has been dealt with in d5b6f1 already, there are more of those. HP Up, Protein, Iron, Calcium, Zinc, Carbos, Sacred Ash, PP Up, PP Max all belong to Medicine Pocket.

Also, could we have a checkbox to override the sanity checks for items?

**Comment by kwsch** [comment]
>Also, could we have a checkbox to override the sanity checks for items?
that's what HaX is for

had my suspicions there's more as noted in #353
