### ISSUE TITLE
Reroll button (or through code) for Wurmple evolution line PID generates invalid PIDs

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3610]
Generating a random PID for Wurmple evolutions usually fails. Silcoon/Beautifly/Cascoon/Dustox. It doesn't check that evo line or re-roll on its own, so it has a half chance of being invalid. It requires some re-rolls to get lucky (Quite annoying when batch modifying)

![image](https://user-images.githubusercontent.com/29823718/196852456-e826046a-3005-41bf-ac8a-e58171984d4c.png)

**Comment by kwsch** [comment]
Enforcing regeneration of legal values is difficult to handle all edge cases.

The recommended method for generating things legally is to use the encounter database. Too much logic would have to be implemented for developing "legal mutations" for all properties.
