### ISSUE TITLE
Internal error when setting Pokemon to an Egg

### ISSUE THREAD

**Issue by Phyore** [kwsch/PKHeX#3617]
Using the latest Master build of PKHeX. Trying to set all Pokemon in Box 31 to be an Egg.
![image](https://user-images.githubusercontent.com/2222368/198032270-05f92365-7836-41f1-ad16-d8965d1d3a0b.png)

Receiving this error:
![image](https://user-images.githubusercontent.com/2222368/198032322-21215e37-a3d8-4c57-a0d9-d2e24aa83969.png)

Extra Question: is there a set Hatch Counter?

**Comment by sora10pls** [comment]
Probably a syntax error. Please use the command builder instead of trying to manually enter in commands with invalid field names. Try:
```
=Box=31
.IsEgg=true
```

Hatch counter is the same field as `CurrentFriendship` while a PKM is in an Egg.
