### ISSUE TITLE
SuMo Legality Issue on some mons

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#362]
after the fix of the met location we have a new problem:

1) the Bounsweet that you get from a ingame NPC link trade (Met: Link Trade) gives error to check
2) Grimer and so Muk continuosly gives Invalid Encounter error even if they are legally caught
3) the evolved alolan forms (like Persian, Raticate, Dugtrio etc) will get Invalid Encounter error even if they are evolved ingame starting with a legally caught pokemon (FYI the pre-evo of those, so Meowth, Diglett etc will NOT give the error, so they are ok. The error occurs when they are evolved)
4) Starters (i talk, in my case about Rowlet, are giving an error in legality: Invalid Relearn move 1-4 Static encounter relearn move mismatch. But they are legal, so don't know why this error. They have all None in relearn moves

**Comment by kwsch** [comment]
Closing as most (if not all) have been addressed.
Future legality reports please refer to #377
