### ISSUE TITLE
Invalid: Word Filter: .*sob.*

### ISSUE THREAD

**Issue by LOuroboros** [kwsch/PKHeX#3620]
**Describe the problem**
I was checking the data of some of the Pokémon I caught in my savefile of Pokémon Sword *(v1.3.2 with both IoA and CT installed.)* and I noticed that for some reason, my Bergmite called "OtsoBergmite" [inspired by a character from the Assassin's Creed Series with the same name](https://assassinscreed.fandom.com/wiki/Juhani_Otso_Berg) made PkHex give this weird error in the legality checker.

I imagine it's a good idea to bring it up in case it's a mistake that could and should be solved.

For whatever it's worth, the savefile has been made and played solely using emulators, specifically Yuzu and a couple of times Ryujinx, but I can't imagine that being a critical factor since this Bergmite is the only single Pokémon in the entire savefile that triggers the legality checker like this.

**To Reproduce**
[712 - OtsoBergmite - 231348C6A87E.zip](https://github.com/kwsch/PKHeX/files/9882937/712.-.OtsoBergmite.-.231348C6A87E.zip)

**Expected behavior**
I guess I expected PkHex to not give me any legality errors?

**Screenshots**
![PKHeX_20221027_173632112](https://user-images.githubusercontent.com/4485172/198392786-b2465895-846e-42fd-b966-525a0244020d.png)

**Comment by kwsch** [comment]
PKHeX uses the 3DS word filter regex. The regex is satisfied -- your nickname has "soB".

https://www.urbandictionary.com/define.php?term=SOB

Working as intended.
