### ISSUE TITLE
Some CHT Text Resources didn't Generate Automatically

### ISSUE THREAD

**Issue by Kitcham** [kwsch/PKHeX#3629]
Since PKHeX was updated a few minutes ago, text resources in different languages would update automatically. 

However I found that some text in CHT didn't generate automatically, such as: `PKHeX.WinForms\Resources\text\lang_zh2.txt` `PKHeX.Core\Resources\text\program\MessageStrings_zh2.txt`   
This will make the program not work properly in Traditional Chinese settings.

It's sure that I can update by hand and create a PR for them. But I'd like to know whether I missed some code changes before, which caused their auto-generation failures? 

If this is the cause, I would like to know which file should be modified and committed together in the next PR. THX!

**Comment by kwsch** [comment]
Should be fixed now -- the DevUtil debug class didn't process the `zh2` language, and didn't regen the files.

I've added it in a recent commit, and pushed the regenerated translation files for zh2 ~ https://github.com/kwsch/PKHeX/commit/9131febef03f391b116000ccf13496574343d8a8#diff-387fd49cf137416ed2a04523f451ccedbc106a8a3ba18699f0fe191864e8200dR18

Should be ready for translation now ;)

**Comment by Kitcham** [comment]
THX Kurt a lot! :)
