### ISSUE TITLE
Ditto 6V Invaild

### ISSUE THREAD

**Issue by drakcraft** [kwsch/PKHeX#3630]
**Describe the bug**
When trying to set Ditto to 6V it says Invaild : Can't hyper train a pokemon with Perfect IVs

I suspect the legal way to get Ditto is max 5V? But when i trying to modify Great Tusk then 6v is legal, may i know is this is a bug or something.

**Comment by Lusamine** [comment]
Can you provide more information about what you are doing to get this error?  Where is the Ditto from?

**Comment by drakcraft** [comment]
Ditto is catch by myslef, but opening other's save ditto seems can set to 6v

**Comment by Lusamine** [comment]
Please provide the save file so we can look at it, if it is legitimately captured.

**Comment by InkDragon** [comment]
likely they hyper trained the ditto before editing it or some how enabled hyper training on a stat when editing. I've had same issue in swsh.
