### ISSUE TITLE
older gen pokemon not imported

### ISSUE THREAD

**Issue by hawktwin91** [kwsch/PKHeX#3632]
first i made a folder, putting pokemon files from sword, shield, ultra sun into it.  then when i try to drag a pkmn file from a folder to a scarlet save, pkhex refuses to import it.  When i run a load boxes, only the pokemon that are originally from scarlet and violet are imported.  did i make a mistake

**Comment by Lusamine** [comment]
It is not possible to transfer anything into SV right now through HOME, so this is the correct behavior.
