### ISSUE TITLE
Fix the Fly To Button in Scarlet and Violet

### ISSUE THREAD

**Issue by ShadyRelapse-PP** [kwsch/PKHeX#3635]
The button seems to unlock the already completed gym, team star and story progression so they show up on the map even after completion. To fix it I think all the scenarios need to be set to false

**Comment by kwsch** [comment]
@sora10pls pls yeet any unnecessary fly flags -- https://github.com/kwsch/PKHeX/blob/f8b15846d77f050892ec9463b956f592b0a5fa1d/PKHeX.WinForms/Subforms/Save%20Editors/Gen9/SAV_Trainer9.cs#L152
