### ISSUE TITLE
Attempting to change nickname of different language throws error

### ISSUE THREAD

**Issue by BRTPOB** [kwsch/PKHeX#3643]
**Describe the problem**
When you've got a Pokemon from a different region, and you try to reset the Nickname to that of the actual species in your language, you will receive an error that "Invalid: Nickname does not match species name."

**To Reproduce**
Attached PKM of Fuecoco. PKM is of German origin, attempting to change Nickname to Fuecoco (ENG) returns error.

**Expected behavior**
Expected Species to have no bearing on nickname.

**Screenshots**
![image](https://user-images.githubusercontent.com/7201028/204064940-26e04977-f0e0-4de5-9282-e4cde563ba1b.png)

**Additional context**
If the Nickname checkbox is unchecked, then the bug occurs. If you check the Nickname checkbox, the bug does not occur.
[909 - Fuecoco.zip](https://github.com/kwsch/PKHeX/files/10095365/909.-.Fuecoco.zip)

**Comment by kwsch** [comment]
A hatched German Fuecoco should be created with Krokel, not Fuecoco.

The file you attached is a German one with Fuecoco, not Krokel as expected, hence the message.
Loading it to tabs, the program auto-corrects it to Krokel and is then legal.
