### ISSUE TITLE
TRs Error

### ISSUE THREAD

**Issue by MercaFolf** [kwsch/PKHeX#3647]
When Technical Records are given to Pokemon, it always brings up an error saying this:
![image_2022-11-26_013615443](https://user-images.githubusercontent.com/96933379/204077792-21ae0c0b-4154-48af-9b10-ffba87072757.png)

**Comment by kwsch** [comment]
Already reported and fixed since last release -- https://github.com/kwsch/PKHeX/commit/6993f9d661e3a15d9821e1e53ac2c92786fcb17b

Please double check that things are fine on the latest development build: https://projectpokemon.org/home/files/file/2445-pkhex-development-build/
