### ISSUE TITLE
Few Legality Reports 

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#3648]
I'd like to list a few pokemon which were caught in my game (unaltered) which are being flagged as illegal

Koraidon/Miraidon
Met Location : Area Zero (5)
Met Level: 72

Rotom
Any form change via the Rotom Catalog provides the error

"Invalid: Tera Type does no match either of the default types."

Also if possible would like to ask, what are the determining factors for Maushold (Family type) and Dudunsparce (Segment #) ?
I'm assuming PID and/or EC , I feel like 1 and the other for each pokemon from my testing but would like confirmation if possible. Thank you!

**Comment by Lusamine** [comment]
Please double check that things are fine on the latest development build before reporting issues... all of these should be fixed already.

https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

Use the Discussions for questions. Issues should be for issues with the program.
