### ISSUE TITLE
pk8 can't be imported.

### ISSUE THREAD

**Issue by xcoder14** [kwsch/PKHeX#3652]
**Describe the bug**

Can't import pk8 or older to violet and scarlet

**To Reproduce**
just import a pk8 or old generation, it can't be read and all is blank when a save of scarlet or violet is loaded.
It didn't work with import bank.

**Expected behavior**
Import pokemon and randomise what it's different.

**Screenshots**
![image](https://user-images.githubusercontent.com/87050978/204108656-585e0284-bb4c-4c6c-86bd-749df64cb8b9.png)
it's happen when i load pk8 pokemon file

**Additional context**
i can load old file if i open old version pokemon save (sword and shield), export to showdown, open scarlet save and load from showdown.

Many thanks for your help and your work !

**Comment by sora10pls** [comment]
Not an issue, working as intended. It is not currently possible to transfer Pokémon from past games into Scarlet and Violet.

Come back in 2023 after HOME updates to support the games.
