### ISSUE TITLE
Contest Hall ribbons marked as unobtainable in >ORAS - <BDSP

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#3655]
**Describe the problem**
Pokemon in ORAS/Gen 7 games will be marked as illegal if they have the contest hall ribbons. This doesn't happen in Switch games, because I assume PKHeX understands that you can obtain them in BDSP.

**To Reproduce**
Open a legitimate Pokemon in a ORAS / SM / USUM save file (Switch saves won't trigger it) and give it one or multiple of the contest halls ribbons. 
[158 - Totodile - 0B693A429FCB.zip](https://github.com/kwsch/PKHeX/files/10097759/158.-.Totodile.-.0B693A429FCB.zip)

**Expected behavior**
The ribbons should be accepted in those games and not mark the Pokemon as illegal.

**Screenshots**
![2022-11-27 09_39_32-Window](https://user-images.githubusercontent.com/25017422/204124667-54cd1d71-5c24-47fa-a959-865cf23420e2.png)

**Comment by kwsch** [comment]
Not a bug. Winning an ORAS contest grants OT affection, which yours lacks.
