### ISSUE TITLE
[Feature Request] Search for pokemon with any mark or ribbon in the local database

### ISSUE THREAD

**Issue by nonamethanks** [kwsch/PKHeX#3659]
As the title says.
I asked in the discord but got no reply, and I couldn't find anything useful in the advanced search. There's individual entries to search for each type of ribbon and mark, but no way to search for any pokemon that has a ribbon or mark attached, or to search by count of marks/ribbons.

**Comment by kwsch** [comment]
Not implemented, and not really something concise to implement (until the program is upgraded to .NET7 in the coming months).
