### ISSUE TITLE
GEN IX - Input file is too large

### ISSUE THREAD

**Issue by sudot0ph** [kwsch/PKHeX#3662]
**Describe the bug**
Trying to open any file of my Pokémon Violet savegame leads to an error message saying "File Size too large".

**To Reproduce**
1. Open PkHex
2. Loading Savegame

**Screenshots**
<img width="304" alt="File Size too large error" src="https://user-images.githubusercontent.com/43375596/204294093-832d6bb5-48a0-4418-b8fe-93a264be5f4c.png">

I'm on MacOS Ventura, so I'm running PkHex in a Wine Wrapper.

**Savegame**
[violetsave.zip](https://github.com/kwsch/PKHeX/files/10104285/violetsave.zip)

Mid Game, some Terra Raids done, 4/5 Titans, 3/5 Star Bases, 3 Badges.

Savegame dumped via JKSV.

**Comment by Lusamine** [comment]
What sort of online interactions did you have? Did you start on 1.0.0 and upgrade to 1.0.1, or start on 1.0.1?

**Comment by sudot0ph** [comment]
> What sort of online interactions did you have? 

None whatsoever.

> Did you start on 1.0.0 and upgrade to 1.0.1, or start on 1.0.1?

Started on 1.0.1.

**Comment by Lusamine** [comment]
This might be because your file transfer mode needs to be set to binary. A standard basic 1.0.1 save should work fine.

**Comment by sudot0ph** [comment]
Thanks, will try that.

**Comment by sudot0ph** [comment]
That did it. FileZilla needs to be forced to Binary. Thank you very much for your help and insight.

**Comment by lokotron211** [comment]
i have the same problem how did you fix it
