### ISSUE TITLE
Egg Moves taught with Mirror Herb at Picnics aren't considered valid

### ISSUE THREAD

**Issue by au5ton** [kwsch/PKHeX#3664]
**Describe the problem**
In Gen IX, a new item was added called the *[Mirror Herb](https://bulbapedia.bulbagarden.net/wiki/Mirror_Herb)*. Outside of battles, this allows Egg Moves to be taught to a Pokemon without breeding. A Pokemon which knows an Egg Move may teach it to an existing Pokemon, with certain compatibility constraints.

_From [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Mirror_Herb)_:
> *Outside of combat, a held Mirror Herb will allow a pokemon to learn a move that could be gained through breeding from another pokemon in your party. In Scarlet and Violet, this occurs during a Picnic while the "learning" pokemon has at least one slot open in it's moveset, and the "teaching" pokemon has the move currently registered. After a minute or two of the picnic, the "learning" pokemon will have gained the egg move, and can pass it down normally. For instance, Azumarill can "learn" Belly Drum from Hariyama in this manner.*

**To Reproduce**
Attached is the Flying Tera Type Pikachu from the Pokemon Scarlet/Violet WiFi event. Replacing the attack "Wild Charge" with "Volt Tackle" produces the illegal warning: `Invalid Move 1: Invalid Move`.

**Expected behavior**
If my understanding is correct, Pikachu should be able to learn "Volt Tackle" this way from another Pikachu that already learned "Volt Tackle" via Breeding. It would be helpful if someone smarter than me could fact check this though so a false positive isn't coded.

**Screenshots**
![image](https://user-images.githubusercontent.com/4109551/204407293-3fc11212-2b6d-4d5e-a5a8-f674c9548b0c.png)
![image](https://user-images.githubusercontent.com/4109551/204407335-efbe23be-06e0-4b8e-aaaa-949d743d300f.png)

**Additional context**

**Comment by sora10pls** [comment]
Volt Tackle is not a standard Egg Move for Pichu, and is a special case when considering what moves should be passed down to the offspring. As such, Volt Tackle can not be shared with other Pokémon via Picnics and Mirror Herb.

Please only report issues after you have verified that they can be done in-game, and not due to assumptions.
