### ISSUE TITLE
Not working with Scarlet/Violet new update

### ISSUE THREAD

**Issue by ShuhengLi** [kwsch/PKHeX#3665]
After the update on Dec 1st, can't open the save file. Getting error message "input file is too large. File size: xxxxxx"

**Comment by Masamune3210** [comment]
Please actually repeat what the error says, the number is important to helping you, xxxx tells nothing

**Comment by ReignOfComputer** [comment]
The number doesn't matter, the OP states "after the update". PKHeX hasn't been updated since the update. Obviously, it's not going to work yet. Wait for an update.

**Comment by ShuhengLi** [comment]
Thank you for your response. My save file size is 3.17MB and I belived this is normal size. And I'm not the only one having this issue here. https://projectpokemon.org/home/forums/topic/62655-pkhex-says-file-pokemon-scarlet-file-is-too-big-after-the-update/
I'm just the first one to report the issue, I belived this is a gerneral problem not a single rare case what's why I didn't mentioned the actual number there.

**Comment by Masamune3210** [comment]
Fair point, I may have had narrow vision when I saw the error message. I deal with people not telling me the whole error all the time at work and in other projects so I get a little triggered by it

**Comment by Masamune3210** [comment]
> Thank you for your response. My save file size is 3.17MB and I belived this is normal size. And I'm not the only one having this issue here. https://projectpokemon.org/home/forums/topic/62655-pkhex-says-file-pokemon-scarlet-file-is-too-big-after-the-update/
> I'm just the first one to report the issue, I belived this is a gerneral problem not a single rare case that's why I didn't mentioned the actual number there. 

As was already said, update isn't supported yet. Will have to wait until support gets added
