### ISSUE TITLE
No memory in PLA is considered "fishy"

### ISSUE THREAD

**Issue by Araraura** [kwsch/PKHeX#3667]
**Describe the problem**
In PLA, Pokemon from older games(?) have their memory legality check marked as "fishy" for the current handler, even though PLA can't have memories for the current trainer. This does not happen with Pokemon caught in PLA.

**To Reproduce**
[026 ★ - Raichu - 17A68D44D288.zip](https://github.com/kwsch/PKHeX/files/10147517/026.-.Raichu.-.17A68D44D288.zip)

**Expected behavior**
The legality check should not report current handler memories as "fishy".

**Screenshots**
![2022-12-04 01_13_22-Window](https://user-images.githubusercontent.com/25017422/205466072-1dac8003-a123-45b2-ab07-5b309c2ab70d.png)

**Comment by Masamune3210** [comment]
Does Pokemon HOME even support trading from other games to the new games yet?

**Comment by Araraura** [comment]
> Does Pokemon HOME even support trading from other games to the new games yet?

This is in PLA, not SV

**Comment by Masamune3210** [comment]
Does HOME support trading to and from Arceus?

**Comment by Araraura** [comment]
> Does HOME support trading to and from Arceus? 

Yea, it was there since May. This Pokemon in the screenshot was specifically from before Switch games, but it happens even if you transfer one from SwSh to PLA it seems.

**Comment by Masamune3210** [comment]
Aah, might be a oversight or something. I haven't played Arceus yet so I haven't messed with it
