### ISSUE TITLE
Ilegal Titan Tatsugiri and Bombirdier in Database

### ISSUE THREAD

**Issue by Gmatrick** [kwsch/PKHeX#3671]
I tried to create a Titan Bombirdier but It seems that both the Titan forms of tatsugiri and bombirdier appear as illegal in the Encounter database, even in the last Development build

![55d23793ad56bb5ced36a7193e0edae1](https://user-images.githubusercontent.com/43705486/205556432-6cae668b-26ea-4772-abbd-0be99266c894.png)

**Comment by kwsch** [comment]
#3669
Works fine if you load the met tab.
