### ISSUE TITLE
Pal Park Transferred Pokemon Between Levels 1-4 Are Considered Illegal by PKHeX

### ISSUE THREAD

**Issue by DeadSkullzJr** [kwsch/PKHeX#3675]
**Describe the problem**
Pokemon transferred through Pal Park between levels 1-4 are considered illegal by PKHeX, producing an _Invalid: Invalid Met Level for transfer._ error.

**To Reproduce**
Transfer Pokemon between levels 1-4 into Pal Park, or transfer between a third generation save to a fourth generation save by dragging and dropping PK3 files into the fourth generation save file, automatically converting them into Pal Park transferred Pokemon.

PK3 Files:
[Treecko PK3 Files.zip](https://github.com/kwsch/PKHeX/files/10172496/Treecko.PK3.Files.zip)

**Expected behavior**
Transferring the intended way or dragging previous generation Pokemon data over to a fourth generation save should yield legal Pal Park transferred Pokemon.

**Screenshots**
https://i.imgur.com/m38yQ6z.png
https://i.imgur.com/EA6DSZS.png

**Comment by sora10pls** [comment]
Eggs hatch at Level 5 in Generation 3. You can not get a Level 1, 2, 3, or 4 Treecko in those games.
