### ISSUE TITLE
Minor Encounter Database origin game errors BW2

### ISSUE THREAD

**Issue by NickPlayeZ** [kwsch/PKHeX#3676]
The BW2 ingame trades for both Petilil and Cottonee are displayed even if one chooses only B2 OR only W2 as OT Version, despite the trades being version exclusive. It even shows the Game Version being the other version that you did not select if you hover over it.

Also the static Undella Town Jellicent with Damp hidden ability is shown as 2 different encounters which to my knowledge doesn't make sense as there is only that one Jellicent (that respawns with the exact same general properties every time).

1. Go to the encounter database
2. Make the OT Version be Black 2 or White 2
3. Search for Petilil if you chose W2 or Cottonee if you chose B2 (or Jellicent) and look at the Trades (/Statics)
4. Hover over the Pokemons encounter in question and see the error

The Petilil ingame trade should NOT be shown if W2 is the OT Version, the Cottonee trade should NOT be shown if B2 is the OT Version and the male Static Jellicent should not have 2 different encounters. Only the one that describes a male version in B2 and a female version in W2 should stay as these genders for this Jellicent are indeed version exclusive.

**Comment by kwsch** [comment]
Fixed by #3729
