### ISSUE TITLE
SuMo TID/SID 5 digits

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#368]
My TID/SID turned out to be 5 digits.

when it will be 6, how we need to fix the pre-existing pokemon?

**Comment by kwsch** [comment]
To clear up any questions:

Existing TID/SID is still stored as a 32 bit number. Gen 3-6 displayed 16 of those bits. Gen 7 displays a calculated value from all 32 bits.

PKHeX displays the TID/SID in the past-generation style; hovering over either of the fields will indicate the Gen7 TID.
