### ISSUE TITLE
Current version of PKHex does not recognise EUR versions of Colosseum/XD

### ISSUE THREAD

**Issue by TheZett** [kwsch/PKHeX#3682]
I tried to test something by modifying my Pokemon XD savedata file, but the current version of PKHex does not recognise my EUR Pokemon savedata files on my Dolphin EUR.RAW memory card file.

It only recognised the US savedata files of Colosseum/XD, which are stored in a separate savedata file by Dolphin (USA.RAW).

If I try to load my EUR savedata with an older version of PKHex (220318) it gives me a pop-up menu and asks me to select which version I want to load (Colosseum or XD).

I have attached my savedata file, which can be loaded in PKHex (220318) but not in the most recent PKHex (221201).

[MemoryCardA.EUR.zip](https://github.com/kwsch/PKHeX/files/10200993/MemoryCardA.EUR.zip)

**Comment by kwsch** [comment]
A wild Dota2 aficionado appeared! <3
