### ISSUE TITLE
Ilegall event nicknamed PokéCenter Flabébé 

### ISSUE THREAD

**Issue by javierhimura** [kwsch/PKHeX#3684]
PokéCenter Flabébé received in-game with mystery gift after injecting the wonder card in the BCAT file. It is reported as illegal due to being nicknamed. I am playing with a Spanish save the file, not an English or Japanese.

![imagen](https://user-images.githubusercontent.com/21158487/206903643-93188b2f-f863-4c53-903d-6583dc008d3b.png)

I have injected the wonder card of the event with the following tutorial.
https://projectpokemon.org/home/forums/topic/62491-switch-gift-data-manager-import-wondercards-into-switch-games-by-faking-bcat-packages/
Then used Mystery Gift in the game to receive the pokemon in my boxes. The pokemon has been received with the English name (which happens to be the same as the Spanish name for this pokemon) but flagged as nicknamed.

Adding the wonder card directly to the save file doesn't create a nicknamed pokemon, having a Japanese name instead of an English one. Unflagging the nickname in the BCAT pokemon turns it into legal, with the English name still different from injecting the pokemon directly with PkHex.

According to Bulbapedia, "This Pokémon has Japanese tags unless redeemed in an English game. " but it has no information about non-English, non-Japanese games (but it mentions being able to receive it on Korean and Chinese games with bugs in the nickname)
https://bulbapedia.bulbagarden.net/wiki/List_of_serial_code_event_Pok%C3%A9mon_distributions_(Generation_IX)

I included both Flabébés, the one injected through PkHex, and the one injected through BCAT.

[Flabébé.zip](https://github.com/kwsch/PKHeX/files/10202183/Flabebe.zip)

I am not sure which of the two behaviors is the legal one given that the result is different between both, but the one flagged as illegal is the one received with Mystery Gift in-game, and I am not sure if BCAT injection with a legal wonder card is exactly the same as a legit receive of the gift.

**Comment by Lusamine** [comment]
I redeemed a legitimate code in a Spanish save file and it came out with JPN tag, nickname is ticked. It does look like the behavior may have changed compared to past games, which would have allowed the name in the save language, but not be nicknamed.

This also has the implication that once evolved, it's still stuck with the base form's name.
![image](https://user-images.githubusercontent.com/30205550/207489502-f00c4fc1-f4e0-4bb0-abf6-a3ce02720ba2.png)

**Comment by kwsch** [comment]
The event card has been fixed and correctly locks the language.

Rather than programming around the original card's odd behaviors (nightmare), I find it will be easier to flag it and let the user decide if it really was the original card and if the nickname obeys the rules.
