### ISSUE TITLE
Edit in-game version time

### ISSUE THREAD

**Issue by Matdu10** [kwsch/PKHeX#369]
As you may know, Sun and Moon have an in-game time difference (Moon is +12 hours).

After transfering the save from one version to another (moon -> sun or sun -> moon), the game keep its old time, it doesn't adapt to the new version.

An option to fix this would be welcome :)

**Comment by kwsch** [comment]
Swapping saves between versions will never be supported; the game sets event flags and other values depending on the game that it was originally started on.
