### ISSUE TITLE
Legality: trading updates obedience level to current pokémon's level

### ISSUE THREAD

**Issue by suloku** [kwsch/PKHeX#3690]
I noticed some of my legit pokémon were flagged as illegal with "invalid obedience level" and I think the reason is the following: after trading obedience level is set to that of the pokémon current level, so obedience level can be higher to met level without being an illegal pokémon.

**Comment by Lusamine** [comment]
Please post an example of a legitimate, unmodified Pokémon file where you feel this flag is in error.

**Comment by Doctor-Pokemon** [comment]
> I noticed some of my legit pokémon were flagged as illegal with "invalid obedience level" and I think the reason is the following: after trading obedience level is set to that of the pokémon current level, so obedience level can be higher to met level without being an illegal pokémon.

I've also noticed PKHeX tends to mark ANY Mon as illegal if the Met level and Obedience level do not match.

I have all 8 Gym Badges in my current save file though...so I cannot know for sure if this level is changed upon trading INTO that save.

However, I would be happy to test this when I get home from work tonight, and supply said files upon completion of the experiment.

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/208309671-aa301769-4070-46e4-aef3-09a6afaa8495.png)
My legitimately obtained, leveled-up, and traded Dragalge is not flagging despite being a different obedience level from the met level.

I am unable to replicate what you two are claiming.  Again, if you can do this with zero editing, then explain how it can be done legitimately.

**Comment by suloku** [comment]
I think I've identified the problem after further inspection, the pokémon that are flagged were traded with a 2nd switch that had my savegame injected to it, so the pokemon was traded, obedience level was updated but since the pokemon trade was never "to a different trainer" "latest (not OT) Handler" data is blank.
This is a rare case of not having any modified savedata but the pokemon becoming illegal by the process.

I guess in the extremly unlikely case of two people sharing same OT information this could tecnically happen in real life. I guess the game tests for OT name, TID, SID, trainer gender and language, but I'm curious if it also tests for version. I know that it's not the game version (my trade was between versions), but I don't know if it will check the ot information version stored in the save (scarlet vs violet).

**Comment by Lusamine** [comment]
> 2nd switch that had my savegame injected to it,

As you stated, hacking was required to trade to yourself on the exact same save file.  This is not considered legitimate gameplay.

Even though there is a nonzero (aka astronomically unlikely) chance that two people in Gen 9 manage to legitimately have the exact same trainer info and trade with each other, it is still better to flag the other 99.999999999% of cases which would be due to bad hacks and save file manipulation.

**Comment by suloku** [comment]
Yes I agree. I didn't notice at first the flagged pokémon were traded to that savegame, thus causing the problem, I'm sorry for the confusion. The legit event is extremely unlikely to ocur and pkhex behavior should stays as is, my statements about the OT information used by the game to determine original trainer were mere personal curiosity.
