### ISSUE TITLE
BW2 false met locations for hatched eggs shown as legal

### ISSUE THREAD

**Issue by NickPlayeZ** [kwsch/PKHeX#3691]
When choosing the met location of a Pokemon that was hatched from an egg using PKHeX you have the option to select many places. Three of these in BW2 are falsely counted as legal (2 per version). With either version as the Origin Game, the Trial Chamber is falsely counted as a legal met (hatched) location. Trial Chamber was a small cave within BW1s Victory Road where you could catch Terrakion which is no longer accessible in BW2.
The other issue lies with the Black Gate/White Gate met locations. Whilst it is true that you can exchange the Black City and White Forest in these versions, the Gate leading to it is still referred to by your versions color. I tested that by simply changing my White 2 via the Key System to have the Black City and then hatched an egg in both the northern and the western gates that lead to it. Both had "White Gate" as the met location. Therefore in W2 you cannot have Black Gate as a met location and in B2 you cannot have White Gate as a met location.

**To Reproduce**
Simply get yourself an egg or two from the daycare (/hack one in) and hatch them in the Gates Leading to the City/Forest.

Important Addon:
After reconfirming my tests to answer to the reply to this original bug report I remembered something else. What if I were to hatch an egg in the small area of the old BW1 Victory Road that is still accessible in BW2. PKHeX shows the origin game being White 2 as expected in my example test and the met location as "Victory Road (B/W)" which is flagged as illegal despite me having hatched the egg as legitimately as any other egg in the bit of the old BW1 victory Road. So here PKHeX shows something as illegal falsely. Regular Wild Pokemon caught in the small BW1 victory road cave section left in BW2 are flagged as legal correctly however with the same met location "Victory Road (B/W)".

**Comment by aplumafreak500** [comment]
If I remember correctly, this is working as intended, as the legality logic is as follows:

- Egg is created in, say, Black 2
- Egg is traded to White 1
- Egg hatches in White Gate
- Resulting Pokemon is sent back to Black 2

In that case, while Met Game would still say Black 2, Met Location is set to White Gate, which, as outlined above, would still be legal.

Similar logic would apply in the case of the Trial Chamber, and, indeed, any B/W2 exclusive location for Eggs created in B/W then hatched in B/W2.

**Comment by NickPlayeZ** [comment]
then theres the issue of route 10; why would that not be counted as legal?

**Comment by NickPlayeZ** [comment]
> If I remember correctly, this is working as intended, as the legality logic is as follows:
> 
>     * Egg is created in, say, Black 2
> 
>     * Egg is traded to White 1
> 
>     * Egg hatches in White Gate
> 
>     * Resulting Pokemon is sent back to Black 2
> 
> 
> In that case, while Met Game would still say Black 2, Met Location is set to White Gate, which, as outlined above, would still be legal.
> 
> Similar logic would apply in the case of the Trial Chamber, and, indeed, any B/W2 exclusive location for Eggs created in B/W then hatched in B/W2.

That is not how that works I did test my theory before writing a bug report. When the egg is hatched in White 1, its origin game is set to White 1.
And even if you trade it back to the original creator of the egg, it'll still have the egg met condition "link trade (egg)".
Therefore it is not possible to have e.g. the Trial Chamber be a met location for a Pokemon with an origin game of BW2.
