### ISSUE TITLE
CRLF in some text resources

### ISSUE THREAD

**Issue by CaiMiao** [kwsch/PKHeX#370]
languages.txt and regions3ds.txt uses CRLF, which makes some weird issue when I commited things earlier.

**Comment by CaiMiao** [comment]
Logs when I encounters this rare problem:

Exception Details:
System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.Main.InitializeFields() in C:\Users\gaiba\Desktop\PM\PKHeX\PKHeX\MainWindow\Main.cs:line 1266
   at PKHeX.Main..ctor() in C:\Users\gaiba\Desktop\PM\PKHeX\PKHeX\MainWindow\Main.cs:line 159
   at PKHeX.Program.Main() in C:\Users\gaiba\Desktop\PM\PKHeX\PKHeX\Program.cs:line 29

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\gaiba\Desktop\PM\PKHeX\PKHeX\bin\Debug\PKHeX.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.Windows.Forms.resources.dll

mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
PKHeX must now close.

**Comment by evandixon** [comment]
Git should check in to the repository with LF line endings, and should check out using whatever line ending settings are used in your environment.  If that's not the case, check your Git installation, and if that's OK, we may need to adjust the .gitattributes file.

I looked at the code around the exception you've posted, and CRLF line endings shouldn't make any difference.  The code expects LF, then trims away any remaining CR's.  Because of this, I suspect the problem lies elsewhere.  Since `master` doesn't currently crash in that line, at least for me, the problem likely lies elsewhere.

**Comment by CaiMiao** [comment]
> Because of this, I suspect the problem lies elsewhere. Since master doesn't currently crash in that line, at least for me, the problem likely lies elsewhere.

I know the main branch is not crashing, but I've once porting LF files back to CRLF repo automatically converted by VS2015, it crashed. BUT the next time I did samething, it properly works. So I'm also confused.

**Comment by CaiMiao** [comment]
The problem can be reproduced by resetting to 4af7eabd806de55f20395f230eff92e3d9de526a on my branch
