### ISSUE TITLE
Gen 9 - TMs added through PKHeX do not become available to craft ingame

### ISSUE THREAD

**Issue by Ritaku02** [kwsch/PKHeX#3708]
**Describe the bug**
TMs added through PKHeX do not become available to make ingame from the TM Machine.

**To Reproduce**
1. Add any TM to your inventory that you do not already possess, and cannot currently create, using PKHeX.
2. Go to the TM Machine at any Pokemon Center ingame. The added TM is not available to make.

**Expected behavior**
TMs added through PKHeX should be available to create ingame through the TM Machine, same as if you'd obtained it within the game itself.

**Comment by Lusamine** [comment]
Every single TM has its own "can craft" flag which is labeled for you. You can flip them all to true if you want.
![image](https://user-images.githubusercontent.com/30205550/210158891-a46fbf02-4b30-47b5-953d-60763035b9d7.png)
