### ISSUE TITLE
wrong pokemon species code

### ISSUE THREAD

**Issue by sunqian2007** [kwsch/PKHeX#3709]
**Describe the bug**
the species code of Toedscool should be 948 instead of 1006. However, when I export the pk9 file of Toedscool, the file name become :
1006 - Toedscool - 2503CEAE2311.pk9

**Screenshots**
![微信截图_20230101132957](https://user-images.githubusercontent.com/65378398/210161930-42048f79-bf04-46f4-973a-db1b22a88e57.png)

**Comment by Lusamine** [comment]
PKHeX currently uses the internal number, which is 1006, because everything in the game refers to this internal index. This may be changed in the future, but is not an accident or bug.

**Comment by sunqian2007** [comment]
> PKHeX currently uses the internal number, which is 1006, because everything in the game refers to this internal index. This may be changed in the future, but is not an accident or bug.

But when I do the command of `sorted by the pokedex NO.`, it will be mistake

**Comment by sunqian2007** [comment]
Also, I have written a shell code like this to help my pokemon sorted by the Paldea Region NO. I hope this function can be added into the pkhex.
`echo "请选择您要排序的地区图鉴"
echo "1:重置全国图鉴编号"
echo "2:城都图鉴编号"
echo "3:丰缘图鉴编号"
echo "4:神奥图鉴编号"
echo "5:合众图鉴编号"
echo "5.1:新合众图鉴编号"
echo "6:卡洛斯图鉴编号"
echo "7:阿罗拉图鉴编号"
echo "7.1:新阿罗拉图鉴编号"
echo "8:伽勒尔图鉴编号"
echo "8.1:洗翠图鉴编号"
echo "9:帕底亚图鉴编号"
read -p "请输入： " gen
echo "read name, name is $gen"
folder=./DB;


if [ "$gen" == "1" ];
then
	for file in `ls -1 DB| tr ' ' '#'`;
	do
		echo $file
		no=`echo $file | awk -F '#' '{print $1}'| awk -F '-' '{print $1}'`
		name=`echo $file | awk -F '#' '{print $(NF-2)}'`
		real_no=` cat global.log|grep -n $name|awk -F '	' '{print $1}'|awk -F ':' '{print $2}'`
		id=`echo $file | awk -F '#' '{print $NF}'`
		mv ./DB/$no*$id ./DB/$real_no"#"$name"#"$id;
		echo $no
	done
	exit

else
	for file in `ls -1 DB| tr ' ' '#'`;
	do
		echo $file
		
		no=`echo $file | awk -F '#' '{print $1}'| awk -F '-' '{print $1}'`
		id=`echo $file | awk -F '#' '{print $NF}'`
		newno=` cat Gen$gen.log |awk -F ' ' '{print $2}'|grep -n $no|awk -F ':' '{print $1}'`
		if [ $newno -lt 1000 ];then
			newno=0$newno
		fi
		if [ $newno -lt 100 ];then
			newno=0$newno
		fi
		if [ $newno -lt 10 ];then
			newno=0$newno
		fi

		mv ./DB/$no*$id ./DB/$newno+$file;
		#echo "ebd"
	done
	exit
fi





`

**Comment by sunqian2007** [comment]
Also, I have written a shell code like this to help my pokemon sorted by the Paldea Region NO. I hope this function can be added into the pkhex.
`
```
echo "请选择您要排序的地区图鉴"
echo "1:重置全国图鉴编号"
echo "2:城都图鉴编号"
echo "3:丰缘图鉴编号"
echo "4:神奥图鉴编号"
echo "5:合众图鉴编号"
echo "5.1:新合众图鉴编号"
echo "6:卡洛斯图鉴编号"
echo "7:阿罗拉图鉴编号"
echo "7.1:新阿罗拉图鉴编号"
echo "8:伽勒尔图鉴编号"
echo "8.1:洗翠图鉴编号"
echo "9:帕底亚图鉴编号"
read -p "请输入： " gen
echo "read name, name is $gen"
folder=./DB;

if [ "$gen" == "1" ];
then
for file in ls -1 DB| tr ' ' '#';
do
echo $file
no=echo $file | awk -F '#' '{print $1}'| awk -F '-' '{print $1}'
name=echo $file | awk -F '#' '{print $(NF-2)}'
real_no= cat global.log|grep -n $name|awk -F '	' '{print $1}'|awk -F ':' '{print $2}'
id=echo $file | awk -F '#' '{print $NF}'
mv ./DB/$no*$id ./DB/$real_no"#"$name"#"$id;
echo $no
done
exit

else
for file in ls -1 DB| tr ' ' '#';
do
echo $file

	no=`echo $file | awk -F '#' '{print $1}'| awk -F '-' '{print $1}'`
	id=`echo $file | awk -F '#' '{print $NF}'`
	newno=` cat Gen$gen.log |awk -F ' ' '{print $2}'|grep -n $no|awk -F ':' '{print $1}'`
	if [ $newno -lt 1000 ];then
		newno=0$newno
	fi
	if [ $newno -lt 100 ];then
		newno=0$newno
	fi
	if [ $newno -lt 10 ];then
		newno=0$newno
	fi

	mv ./DB/$no*$id ./DB/$newno+$file;
	#echo "ebd"
done
exit
fi
```

`

**Comment by Lusamine** [comment]
No, it is not a mistake to use the internal number. This is intentional right now. As I said, this may change in the future, but right now, it is correct.

There are currently no plans to implement regional dex sorting. There are plugins that can do this for you: https://github.com/foohyfooh/PKHexSortingPlugin
