### ISSUE TITLE
VC GSC Celebi incorrect met location

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#3710]
**Describe the problem**
A Celebi with the "Caught data" bytes of 0x0000 in 3DS VC saves passes the legality checks. In VC, Celebi was only ever available in Crystal, and it cannot be traded to gen 1, so it cannot have those bytes set to 0.

**To Reproduce**
Load a VC game save with Celebi, remove its Met data, set its trainer gender to male, and check for legality.

**Expected behavior**
The legality checks should fail.

**Screenshots**

**Additional context**
While I'm here, I also noticed you can set the Met Location to None with a level of 1, and the mon will pass the legality checks (at least for Delibird, from what I've seen), is this supposed to happen?

**Comment by kwsch** [comment]
> I also noticed you can set the Met Location to None with a level of 1, and the mon will pass the legality checks (at least for Delibird, from what I've seen), is this supposed to happen?

"(None)" is actually the location ID of the second floor of the Pokecenter 😆 
https://github.com/kwsch/PKHeX/commit/256b3c66ca34568dc1eae32402eb97ed6d630663
