### ISSUE TITLE
Trying to use Tera Finder as a PKHeX plugin produces an error while save is loaded in PKHeX

### ISSUE THREAD

**Issue by nefariouslegion** [kwsch/PKHeX#3711]
**Describe the bug**
Trying to setup Tera Finder as pkhex plugin. I copied all the Tera Finder files to the pkhex/plugins folder. It makes the menu show up for it. But I tried loading my save into pkhex and then clicking on the "Tera Raid Viewer/Editor" but then I get the attached error. Without the save loaded it opens but without my save file data as i mentioned. I'm wondering how to fix this? I'm not sure if this is a Tera Finder issue or a PKHeX issue. 

FYI using Tera Finder as a standalone program works fine without errors.

**To Reproduce**
1. Place Tera Finder in the PKHeX/plugins folder
2. Open PKHeX
3. Load a save file
4. Click Tools > Tera Finder Plugin > Tera Raid Viewer/Editor
5. See error (screenshot attached)

**Expected behavior**
The Tera Raid Editor should open with my save file data loaded into it.

**Screenshots**
![image](https://user-images.githubusercontent.com/89366675/210171301-edd20831-cc70-4451-b603-cab78d314378.png)
![image](https://user-images.githubusercontent.com/89366675/210171306-4a2954e2-55e8-4b55-86df-421ca9373653.png)

**Additional context**

**Comment by nefariouslegion** [comment]
Fixed with latest master commit

**Comment by Lusamine** [comment]
Plugin issues are not a problem with PKHeX. You need to ensure compatibility with the correct version, or wait for the owner to update them.
