### ISSUE TITLE
SV Nouveaux raids, pokemon "illégaux"

### ISSUE THREAD

**Issue by lacrima08** [kwsch/PKHeX#3715]
Bonjour Michael,

Sur la dernière release en date (22.12.18), les pokémon des derniers raids sont reconnus comme illégaux dans PKhex, je pense notamment aux Cadoizo et au Pyrobut Tera Combat de l'évent du nouvel an

Le Dracaufeu du raid lui passe sans pb les checks

Je te mets la capture pour le Pyrobut

![Capture](https://user-images.githubusercontent.com/3358989/210237588-4d8e71b5-06b0-4123-9a3f-9ce74e7c3bbb.PNG)

Merci encore pour ce que tu fais entre autres avec PKhex !

Je te souhaite une très belle année 2023 !

lacrima08

**Comment by sora10pls** [comment]
PKHeX released on December 18, 2022
Cinderace raids released on December 30, 2022

Releases in the past can not know about encounters that were released in the future. Use the latest commit or wait for the next stable release.

**Comment by sora10pls** [comment]
Either build from source code yourself, or download the latest development build here - https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

**Comment by lacrima08** [comment]
> Either build from source code yourself, or download the latest development build here - https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

Thank you, i'll look at that !
