### ISSUE TITLE
Feature Request: Set 12 hour schedule on Sun/Moon manually. 

### ISSUE THREAD

**Issue by ZarekDaniel** [kwsch/PKHeX#372]
After finding out you could transfer save files between the two versions some people realized you retain the day/night cycle of the version you started that file with. Perhaps that could be edited? Something like a Daylight cycle: Sun/Moon option?

**Comment by kwsch** [comment]
New save editing features have to be researched first -- discussion and research requests belong in the Save Editing Research and Development forum, as they are not related to the use of PKHeX.
