### ISSUE TITLE
Reroll top half of PID for certain forced shinies when selecting the Shiny button

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3721]
**Is your feature request related to a problem? Please describe.**
There are several types of encounters that "shinify" pokemon by taking an initial PID, and rerolling the first half of it to XOR as shiny for the TID and SID.
Currently, when the shiny button is selected, PKHeX rerolls the entire PID to be shiny for the TID and SID, not respecting the method that the game would use for a given encounter. If the user wants to shinify a Pokémon in a way that respects this method, they currently have to use outside tools and/or calculate the matching first half of the PID manually.

**Describe the solution you'd like**
Conditionally check if the encounter would use the "reroll first half of the PID" method of shinification for a given encounter type, and shinify the PID accordingly.

If this is possible, batch commands for this method of shinification would also be useful, something along the lines of "$shinyHigh", and "$shinyHigh0" and "$shinyHigh1" for forced XOR = 0 and XOR = 1 cases, respectively.

**Describe alternatives you've considered**
If this is undesirable and/or checking conditionally is too intensive, having key combo shortcuts for that form of shinification would work instead, having the user judge whether that's the correct form of PID alteration themselves.

**Comment by kwsch** [comment]
Won't correctly reroll for Gen4 Chain Shiny or Gen5 Mystery Gift Shiny cases.

**Comment by javierhimura** [comment]
Maybe give the option to make the pokémon shiny by changing the SID? That will preserve PID and IVs, so any required encounter relation will be preserved after changing the SID. Sure, this will make the pokémon a foreigner, but in the cases where the pokémon has already moved from its original generation, it won't matter. Of course, this won't work for Pokémon with fixed SID and TID.

**Comment by sora10pls** [comment]
@javierhimura Already exists, hold Alt when rolling for Shiny.

**Comment by kwsch** [comment]
> Maybe give the option to make the pokémon shiny by changing the SID?
Already exists, hold alt when forcing shiny 😃

**Comment by kwsch** [comment]
Not implementing this.

GUI doesn't strictly respect legality, just value expression. To do a precise PID reroll, there'd have to be an entirely new API on top of the encounters to have the encounter regenerate it per the current specs. No API -> no clean usage.
