### ISSUE TITLE
Correct Gen 9 Pokédex Order

### ISSUE THREAD

**Issue by foohyfooh** [kwsch/PKHeX#3724]
**Is your feature request related to a problem? Please describe.**
Currently the order of the Pokédex doesn't match what appears to be the official one from the [One Thousand Pokémon!](https://www.youtube.com/watch?v=pa08Y-fhfTI) video.

**Describe the solution you'd like**
Change the order of the Pokédex to match the official one.

**Comment by Lusamine** [comment]
Previously discussed here: https://github.com/kwsch/PKHeX/issues/3709

**Comment by kwsch** [comment]
Will be resolved when net7 is merged.

https://github.com/kwsch/PKHeX/commit/f4e255067c8c32b13ef79fb8c553481d1d438d39
