### ISSUE TITLE
Issue Exporting Pokemon Red SAV

### ISSUE THREAD

**Issue by evermanwa** [kwsch/PKHeX#3726]
Good afternoon,

First off, I would like to thank you for the hard work you do in supporting as well as creating it in the first place. I have been trying to edit a pokemon red save file, and there is an issue where once I export the save file only the pokemon box that is holding the last pokemon I edited is visible within Pokemon Stadium. I'll my best to show this in screen shots.

Here are the Box contents when viewing this SAV in Pokemon Stadium:
![image](https://user-images.githubusercontent.com/17550950/213317080-3fa92855-b65a-4ddb-a34a-b498007cbf3b.png)

He are the Box Contents when viewing this SAV in the PKHeX app:
![image](https://user-images.githubusercontent.com/17550950/213317301-b64d85ca-84f1-4cef-9801-b5b708efa4e5.png)

As you can see, Box 4 in this case is only visible in the PkHex app, but not in PS.

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/52293-pkhex-problem-gen-1-box-slots/?do=findComment&comment=275840
https://github.com/kwsch/PKHeX/commit/d58aed109d32d65e71b174b5ee96b8a10f8bc233
