### ISSUE TITLE
The latest submission of the net7 branch cannot be synchronized with the Pokémon Pokédex!

### ISSUE THREAD

**Issue by RocCaiy23** [kwsch/PKHeX#3728]
The latest submission of the net7 branch cannot be synchronized with the Pokémon Pokédex!

**Comment by kwsch** [comment]
Please clarify.

The national Dex numbers were confirmed, so the species ID handling was updated for the new Pokemon.

**Comment by RocCaiy23** [comment]
> Please clarify.
> 
> The national Dex numbers were confirmed, so the species ID handling was updated for the new Pokemon.

After testing, the latest submission `6d402bb` can already be synchronized, but it seems that there is an offset problem with the id. For example, I set `384-Iron Hands` to shiny, but actually `383-Iron Bundle` is in effect.

**Comment by sora10pls** [comment]
As you were already told, the net7 branch was updated to use official National Pokédex numbers.

The internal species IDs for Scarlet and Violet have Iron Bundle as 992, while Iron Hands is 992 in the National Pokédex. This is not an issue and is working as intended.
