### ISSUE TITLE
The Pokémon gender couldn't changed in the last release 23.01.26

### ISSUE THREAD

**Issue by boxerxing** [kwsch/PKHeX#3743]
Hello , Thanks for u provide the useful Pokémon game tool，i download and used it in yesterday but find an issue please check it in below：
**Describe the bug**
The Pokémon gender couldn't changed in the last release 23.01.26

**To Reproduce**
1. Open the PKHeX and import the main file.
2. View anyone Pokémon which has gender.
3. Click the gender icon to change this status.
4. See error, the gender status has no change

**Expected behavior**
The  gender can be change to another one status.

**Comment by Lusamine** [comment]
![gender](https://user-images.githubusercontent.com/30205550/215252727-2dcc65ef-cdd7-4bdc-97d3-38b36e2c0c59.gif)

Not able to replicate this with your steps. Can you be more specific how to have this problem?

**Comment by boxerxing** [comment]
I know the video stpes and i do these the same to you ，but it don't to like this video (T_T).   OK i would like to repeat it this tonight.
