### ISSUE TITLE
Multiple issues in SV Pokedex

### ISSUE THREAD

**Issue by KPJoshi** [kwsch/PKHeX#3745]
This is with version 23.01.26

**Issue 1:**
Slowbro has a "Mega" form checkbox in forms list, despite said form not being in game.

**Issue 2:**
Selecting Scovillain(251) or Wiglett(288) in a never-modified save causes following exception and the "Displayed Form" dropdown remains empty:
```
Exception Details:
System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'SelectedIndex'. (Parameter 'value')
Actual value was 1.
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.SAV_PokedexSV.GetEntry(UInt16 species)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
above also occurs for Bramblin(242) in my modified save.

**Issue 3:**
Multiple Pokemon have invalid gender checkboxes ticked in a never-modified save. Not sure if caused by game itself or PKHeX. List: Tandemaus, Maushold, Annhilape, Dudunsparce, Farigiraf, Grafaiai, Bramblin, Kingambit, Veluza, Frigibax line, ruin quartet, box legends, Roaring Moon, Iron Valiant.

**Issue 4:**
Shift+clicking on "Complete Dex" causes Gallade male seen checkbox and Floette female seen checkbox to be unticked (others in evo line not affected).

**Comment by KPJoshi** [comment]
**EDIT: Issue 5:**
I shift+clicked on "Complete Dex" and then unchecked the shiny seen and shiny displayed checkboxes for Gimmighoul, Gholdengo, the ruin quartet, and box legends. However, only Miraidon (I'm playing Violet) does not show a shiny, all others continue to show a shiny form.

**Comment by sora10pls** [comment]
Slowbro has three forms:
0 = Base
1 = Mega
2 = Galarian
Just because the form doesn’t exist doesn’t mean the index doesn’t exist. The same applies to all Pikachu with a cap forms in LGPE, and the base forms of Hisuian forms in LA. Ignore it.

**Comment by KPJoshi** [comment]
> Just because the form doesn’t exist doesn’t mean the index doesn’t exist. The same applies to all Pikachu with a cap forms in LGPE, and the base forms of Hisuian forms in LA. Ignore it.

I see, so while the form is unobtainable, it's still technically in the game's code? All the other mega forms are not listed, hence my suspicion that it's a bug.

**Comment by KPJoshi** [comment]
I can confirm that this issue appears to be fixed in PKHeX and in game as of the dev build at commit [93c4abb](https://github.com/kwsch/PKHeX/commit/93c4abbbd5853a9c38f3ffcc24cc71f7d2364846).
