### ISSUE TITLE
Improve visibility and consistency of shiny markers

### ISSUE THREAD

**Issue by KPJoshi** [kwsch/PKHeX#3749]
**Issue:**
The bright red star shiny marker is easily visible (though maybe a white border around it would make it more visible against dark box backgrounds). However, the pale yellow square shiny marker can be hard to see against light backgrounds, and I was initially confused as to what it meant since it looked so different compared to the star shiny marker. Moreover, both types of shinies show yellow/white sparkles in game, so there is no distinction in that sense.

**Proposed solution:**
Make the square shiny marker also red and put a white border around both shiny markers to improve visibility against dark box backgrounds.

I tried to find the markers in the image resources to edit them myself, but I am not sure where they're stored.

**Comment by KPJoshi** [comment]
OK, I found the markers in https://github.com/kwsch/PKHeX/tree/master/PKHeX.Drawing.PokeSprite/Resources/img/Pokemon%20Sprite%20Overlays

Will try to edit them.

**Comment by KPJoshi** [comment]
Here's my simple proposal for the square shiny marker - the yellow is replaced with red, with a white border around it, and a transparent middle.
![rare_icon_2](https://user-images.githubusercontent.com/7266023/216830227-ce594f53-3716-4616-8131-bbf5681f21c4.png)

**Comment by Lusamine** [comment]
Honestly, I would rather leave it alone. That looks like some sort of symbol that will trigger even more questions because users can't find it on Bulbapedia.

**Comment by KPJoshi** [comment]
The star shiny marker is on Bulbapedia, there is no separate square shiny marker shown. I'd agree that the star shiny marker should have minimal changes, but the square shiny marker seems to be a PKHeX only thing.

**Comment by Lusamine** [comment]
Right, I do not see any reason to make a big change to something that has been in PKHeX for several years, and which has less visibility in gen 9 than in gen 8.

**Comment by KPJoshi** [comment]
Alright, that makes sense. The visibility issue is still there though. Perhaps the minimal change for the square marker would be to give it a red border like the star marker has a white border in some cases.

**Comment by Lusamine** [comment]
The icon is already standard, and people have been able to see it for over 3 years.  If the issue is visibility, I would suggest making the borders darker. Adding multiple borders in new, different colors is going to be a bigger change to the icon itself when it's already very small.

**Comment by Lusamine** [comment]
Since we're no longer limited to a 10 x 10 icon space, we could consider changing the icon altogether to match the current games. Here's a mockup for both kinds of shiny types.

![image](https://user-images.githubusercontent.com/30205550/216842880-bc6b131a-9a94-4959-89a3-d46e02cb83e2.png)
![image](https://user-images.githubusercontent.com/30205550/216842884-a2acbe03-7dcc-49ea-af9a-f55062207f62.png)

The icon by PID will need to be adjusted but this is an example of how they will display in the boxes and on the active Pokemon in the editing pane.

**Comment by KPJoshi** [comment]
Yeah, this solution sounds better. I made my mockup assuming the 10x10 pixel limit still existed.
