### ISSUE TITLE
PKHex UI Interface Options

### ISSUE THREAD

**Issue by FireGeneral** [kwsch/PKHeX#3750]
**Is your feature request related to a problem? Please describe.**
I prefer the UI for ver.20230126 instead of ver.20230130, I don't really like "Main/Moves/Met/Cosmetic/Stats/OT" constantly moving around while I'm using the program.

**Describe the solution you'd like**
Is it possible to add an option which allows users to switch between some pre-selected UI interfaces for the program? 

**Describe alternatives you've considered**
Add an alternate 20230130 version which uses ver20230126 version UI interface.

**Additional context**
![Sample1](https://user-images.githubusercontent.com/82710934/215460012-647ef0ea-5543-43b9-a44a-c6107fe8d4bc.png)
![Sample2](https://user-images.githubusercontent.com/82710934/215460046-c611c4c9-c2c4-4998-80a6-2bc2ddfd995a.png)
Thank you for all the hard works!!

**Comment by Lusamine** [comment]
What did you do while using the program to make it do that? It still looks the same for me.

**Comment by FireGeneral** [comment]
> What did you do while using the program to make it do that? It still looks the same for me.

I didn't do anything...
I thought you changed the program interface...
I downloaded the program today as soon as I saw there's a new update.
Open the zip file, run the program, and the interface just looks like that.

**Comment by Manu098vm** [comment]
Same here for me
![immagine](https://user-images.githubusercontent.com/52102823/215485260-f9fecf70-b5c7-4286-aac9-f521e43f9055.png)
Apparently the navigation buttons didn't like the changes to make the UI to scale properly 😆

That's still lot a better than the previous version, where if the program was not run at DPI scale 100% half of the interface was unusable :P

**Comment by FireGeneral** [comment]
> Same here for me ![immagine](https://user-images.githubusercontent.com/52102823/215485260-f9fecf70-b5c7-4286-aac9-f521e43f9055.png) Apparently the navigation buttons didn't like the changes to make the UI to scale properly 😆
> 
> That's still lot a better than the previous version, where if the program was not run at DPI scale 100% half of the interface was unusable :P

Sorry, but is the interface looks like this actually a bug or intentional?

**Comment by kwsch** [comment]
I snuck in a commit to un-fix the left pane of the main window, which explains the now-wider portion (no longer clips into the formarg NumericUpDown). Seems like the width&height for ScaleControl needs to stay un-swapped (can you test @Manu098vm ?)
https://github.com/kwsch/PKHeX/blob/5265643f3ef4d08acedd6f3acd421cb6f3ba7814/PKHeX.WinForms/Controls/PKM%20Editor/VerticalTabControl.cs#L43-L47
