### ISSUE TITLE
Miraidon and Koraidon pokédex entry issue

### ISSUE THREAD

**Issue by emilyrome1** [kwsch/PKHeX#3753]
**Describe the bug**

In my game

**To Reproduce**

(Files: [saves.zip](https://github.com/kwsch/PKHeX/files/10551934/saves.zip))

First of all, check the main_1 file, where I did NOT change Miraidon and Koraidon entries. It should look like this:

![one](https://user-images.githubusercontent.com/124105332/215909525-952bc802-2fa8-4025-9ae2-e70562420c97.png)

Now check the main_2 file, where I have changed Miraidon and Koraidon:

![two](https://user-images.githubusercontent.com/124105332/215909594-0175a49b-83fc-40e8-b6ae-f252562e57b5.png)

I clicked "Check all". This is the result:

![two](https://user-images.githubusercontent.com/124105332/215910019-6678999d-4acf-4b2e-9660-6f9e35a0bf8c.png)

As you can see, they are not marked as caught (no green line at the top)

**Expected behavior**

After having checked all entries, both should appear in the Pokédex as "caught".

**Screenshots**

See above

**Additional context**

I have already caught the 2nd Miraidon in the underground

**Comment by kwsch** [comment]
Have you completed the main storyline?

**Comment by emilyrome1** [comment]
Yes I did. I have done all three quests, beaten the prof. in the underground, unlocked the "Area zero" and caught the 2nd Miraidon

**Comment by emilyrome1** [comment]
You can check my save files, they are in a ZIP file

**Comment by kwsch** [comment]
To confirm, you're using the latest release (01/30)?

**Comment by emilyrome1** [comment]
PKHeX (20230130)

**Comment by Lusamine** [comment]
![2023013118011300-B6CE40797459B0890BF7CEF68A4CE587](https://user-images.githubusercontent.com/30205550/215912078-3ae397d4-459f-4b88-9370-3f005c27a11b.jpg)

My Pokédex is legitimately filled out and looks like this. You can read their Dex entries by opening them.

**Comment by emilyrome1** [comment]
![tre](https://user-images.githubusercontent.com/124105332/215912617-522feea8-b207-4bbc-8832-60a2d8024b58.png)

With this change, still the same result. May that be a bug in the game?

**Comment by Lusamine** [comment]
Why must it be a bug? It's probably displaying the box legends as a different color because they're special. I do not think this is a PKHeX issue, but how the game works normally.
