### ISSUE TITLE
Sun/Moon: Roseli Berry removed from pouch

### ISSUE THREAD

**Issue by bui** [kwsch/PKHeX#376]
![image](https://cloud.githubusercontent.com/assets/1788767/20226798/753ad60c-a841-11e6-94e4-914761130f35.png)

I think this is a bug? I have a Roseli Berry in the game.

**Comment by andibadra** [comment]
Clever Wing and Swift Wing too, you can fix that by added item id on Table7.cs

**Comment by Morente5** [comment]
TM100 is also removed

**Comment by andibadra** [comment]
i think on current build still missing Pretty Wing on list.

**Comment by bui** [comment]
Yeah, a friend is missing Protein, PP Up, Rare Candy, and Pretty Wing on the latest commit @kwsch

**Comment by kwsch** [comment]
Pretty wing (571) has been moved to the Medicine pouch, same as all the others.

![img](http://i.imgur.com/7xVjbCG.png)
