### ISSUE TITLE
Bug in the itens editor

### ISSUE THREAD

**Issue by GrayJack** [kwsch/PKHeX#378]
After the commit that removes the vitamins/pp/ash of items bag, weird bug is happening when use the "give all" function (I'm using the last commit and it still does that)

That's what it's look in the save editor:
![captura de tela de 2016-11-11 14-31-102](https://cloud.githubusercontent.com/assets/17973728/20229495/e0f5d2e2-a83d-11e6-9792-5acce195eefa.png)

And that is what actually showed in the game

![20161111_164308](https://cloud.githubusercontent.com/assets/17973728/20229550/3f8153cc-a83e-11e6-8cb6-166ac1b61328.jpg)

![20161111_165839](https://cloud.githubusercontent.com/assets/17973728/20229559/47ac71c6-a83e-11e6-9922-cdaf8208f9a8.jpg)

![20161111_165844](https://cloud.githubusercontent.com/assets/17973728/20229565/4d560c90-a83e-11e6-9535-e3f1f0aceac4.jpg)

**Comment by kwsch** [comment]
Unable to replicate behavior.

**Comment by GrayJack** [comment]
It still does that to me, compiled 17h ago

**Comment by kwsch** [comment]
Try clearing the pouch by holding alt. Still not able to replicate behavior, and nobody else has chimed in so closing.

**Comment by GrayJack** [comment]
I did as you recommended, but the pouch was not completely creared
I still have a slot of Dream Ball and 5 slots of Beast Ball

**Comment by GrayJack** [comment]
Ook, I managed that
After load the save and saw that I still had 6 slots of itens, I saved and dumped it again and I could clear completely the item slot
