### ISSUE TITLE
About Colosseum/XD Shadow ID and Heart Gauge

### ISSUE THREAD

**Issue by ppllouf** [kwsch/PKHeX#3795]
Other Origin Games Pokémon  Shadow ID and Heart Gauge can only be 0，otherwise it is illegal.

**Comment by Lusamine** [comment]
Can you provide an example of the problem?

**Comment by ppllouf** [comment]
-Pokémon Origin Game is Ruby or Platinum Shadow ID can only be 0.
-Not all Pokémon in Colosseum/XD can be Shadow Pokémon. I'm counting their numbers.
 It is expected that the statistics will be completed tomorrow

**Comment by ppllouf** [comment]
[ShadowPokemonlist.txt](https://github.com/kwsch/PKHeX/files/10775608/ShadowPokemonlist.txt)
Shadow Pokémon, can not be level up.

**Comment by javierhimura** [comment]
PKHex already has all shadow Pokemon encounters defined, so basically, the legal analysis should be
- If the Pokemon encounter is not a Shadow encounter from the current GC game, then Shadow ID must be 0.
- If the Shadow Pokemon is not purified then level pokemon must match the encounter level. The moves are also fixed, it cant learn any move even TM before being purified, but I am not sure what moves they have in data before being purified, encounter moves, or shadow moves.
- What about OT Trainer? Do Shadow Pokemon already have Gamecube OT ID before being purified? If that is true then a Shadow Pokemon can't be a foreigner, and any foreigner Pokemon, even from other Colosseum/XD saves probably have Shadow ID 0.

**Comment by ppllouf** [comment]
> PKHex already has all shadow Pokemon encounters defined, so basically, the legal analysis should be
> 
> * If the Pokemon encounter is not a Shadow encounter from the current GC game, then Shadow ID must be 0.
> * If the Shadow Pokemon is not purified then level pokemon must match the encounter level. The moves are also fixed, it cant learn any move even TM before being purified, but I am not sure what moves they have in data before being purified, encounter moves, or shadow moves.
> * What about OT Trainer? Do Shadow Pokemon already have Gamecube OT ID before being purified? If that is true then a Shadow Pokemon can't be a foreigner, and any foreigner Pokemon, even from other Colosseum/XD saves probably have Shadow ID 0.

​
You are  all right. 
Shadow Pokemon was rescued from NPC,The moves are fixed.

**Comment by ijuintekka** [comment]
It's questionable as to whether this needs to be tracked. Given how it is used, it's highly unlikely anyone except the owner of Colo/XD save file will ever see it. Even if you were to assign a value to a non-shadow pokemon, it is lost as soon as the pokemon is traded away. The shadow monitor index is specific to the game currently being played, does not survive after trading, and has no bearing on how the pokemon is generated.

**Comment by ppllouf** [comment]
> 

I agree with you, so I intend to close this issue.
