### ISSUE TITLE
Low level Pokémon from eggs in gen 3 reported as legal

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#3797]
**Describe the problem**
My lvl 3 Pidgey hatched from an egg (minimum level 5) should not be legal.

**To Reproduce**
[Lorenzooone_pidgey_Leaf_Green_bug.zip](https://github.com/kwsch/PKHeX/files/10775631/Lorenzooone_pidgey_Leaf_Green_bug.zip)

**Expected behavior**
Pidgey should be marked as illegal.

**Screenshots**
![pidgey_bug](https://user-images.githubusercontent.com/7537905/219910424-c5b7cde6-2357-494e-9442-7d12e23aaa2f.png)

**Additional context**
Extra weird thing: It says it's from Littleroot Town in the window on the right, when the hatched location is, in reality, Four Island.

**Comment by kwsch** [comment]
Displayed location: it shows the `Egg_Location` value which is 0; starts being used in gen4+
