### ISSUE TITLE
Add tera type & ribbons/medals  to box data report

### ISSUE THREAD

**Issue by lati111** [kwsch/PKHeX#3799]
Hi, I'm using the csv file generated by PKHeX's box data report feature for a personal project of mine, and I'm currently attempting to add gen9 support. Unfortunately the current version of PKHeX box data report does not include the tera type field in the exported csv.

I'd like for the tera type field to be included in the box data report csv in a future version, which strikes me as fairly doable. 
An alternative would be to add a different csv dump feature that dumps all info, though that strikes me as even more work initially, though it would prevent missing data for future features. 

UPDATE: If possible, I would also like to be able to read a pokemon's ribbons and medals through the data report feature or potential full dump feature. For this it might be easier to do a full data csv dump instead of updating box data report.

**Comment by Doctor-Pokemon** [comment]
> . . . I'd like for the tera type field to be included in the box data report csv in a future version. . .

Don't you mean default Tera Type & _Current_ Tera Type?

I don't know what kind of project you're working on, but each Pokémon has **_TWO_** Tera Type values; They have the Type with which they would've been generated **_AND_ (if its Tera Type changed later via tera Shards)** they would also have a _Current_ Tera Type.

Your proposed CSV would likely be more useful with this more accurate reporting method.
I know **_I_** would certainly appreciate this addition as well.

**Comment by kwsch** [comment]
The report grid is a multi-format display, and is not intended to be for specific formats (like Tera Type). There are many many more properties and ways to display a PKM's data like localizing met locations, date formats, etc.

I recommend using PKHeX.Core on nuget and a linqpad/plugin to generate a csv/json to your liking. The GUI grid is a general solution to showing shared properties by the `PKM` class, as it can view savedata (single format) or folder (multi format).
