### ISSUE TITLE
Fix issue with edge case save loading gen 3

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#3805]
https://github.com/kwsch/PKHeX/blob/77cac48d3443a8df73c3826e5795a509d18da743/PKHeX.Core/Saves/SAV3.cs#L128
I know what this comment says, but fixing this should be very easy.
All you need to do is to make an if when either one of count1 or count0 is 0xFFFFFFFF, and return the other one if it's 0. Otherwise, it's business as usual.

(I am also sorry that there are no labels... I used the "Create issue referencing this line" option and it didn't present the usual templates)

**Comment by kwsch** [comment]
Do you have a save file where this is applicable? A save file will always have >= 0 if it has all sectors present, which is checked prior to the count comparison. If the blocks are not present, then the other save is used.
