### ISSUE TITLE
Gen 3 Japanese Nickname length

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#3809]
**Describe the problem**
Through the usage of Ruby USA 1.0, it is possible to edit the nicknames of Pokémon with the same OT Name, TID/SID, but different language.
This means that you can have nicknames for Japanese Pokémon of length > 5 (but not 7), if the OT Name is valid for both English and Japanese. Nicknaming a Pokémon in this way with 7 letters will crash the game though, so it's not a possibility.

Ruby USA 1.0 also causes issues by not checking the language of the Pokémon when trying to change its name upon evolution. Because of that, any Japanese Pokémon with name length <= 5 which can evolve, can have its name changed to be of a new length, regardless of the OT Name... But to a set value. Idk how different languages behave... I only tested USA Ruby 1.0.
It's important to note that ABRA will become KADABRA when evolved this way, which has a name length of 7. This causes all sorts of crashes when its data is viewed, but by trading with Colosseum, it's possible to have this (and other) 7 name length Pokémon exit the cartridge, and be transferred to other games, where they'll mantain the 7 letter name, but will not cause crashes.

These are all marked as invalid, even though they work fine, and are obtainable through legit methods (even though they're very contorted).

**To Reproduce**
I documented the traveling steps of a Kadabra obtained this way (from Ruby USA 1.0 to Emerald), and then I included an example with a Marshtomp nicknamed in Ruby USA 1.0.
[Pokemon_invalid_length_japanese.zip](https://github.com/kwsch/PKHeX/files/10820325/Pokemon_invalid_length_japanese.zip)

**Expected behavior**
These Pokémon should be marked as valid.
If that is not feasible, something which would be nice, is automatically cutting the names to be of size <= 5, since receiving Japanese names of size 7 through trades crashes USA Ruby 1.0 too.

**Screenshots**

**Additional context**

**Comment by Lusamine** [comment]
If it is only possible to do this through RNG manipulating or editing OT/TID to match a Pokémon in another language, the preferred handling is to flag these Pokémon.

Randomly getting into the situation that you can somehow name a Pokémon from another save game is very, very unlikely.  The vast majority that break the rule will be hacked.

I don't know why you would want to legalize mons that crash the game either.

**Comment by Lorenzooone** [comment]
> If it is only possible to do this through RNG manipulating or editing OT/TID to match a Pokémon in another language, the preferred handling is to flag these Pokémon.
> 
> Randomly getting into the situation that you can somehow name a Pokémon from another save game is very, very unlikely. The vast majority that break the rule will be hacked. Anyone who is RNG manipulating knows what they did and can ignore the flag.
> 
> I don't know why you would want to legalize mons that crash the game either.

Ok, but what about the thing about evolutions of Japanese Pokémon in USA Ruby 1.0? That requires no RNG...
And yeah, I'd understand not allowing Pokémon with a name length of 7, but Pokémon like ARON should be fine...?

**Comment by Lusamine** [comment]
I evolved a JPN Kadabra in an ENG Emerald game and it became this.  It did not become "KADABRA".
![image](https://user-images.githubusercontent.com/30205550/221086923-1b24cca9-4903-46e9-98c5-0470e4dca1b9.png)

Also, hacking the wide spaced JPN chars into an ITA save is illegal because of keyboard differences.
![image](https://user-images.githubusercontent.com/30205550/221085768-5ff2e2cc-8ced-431b-82e6-2bbc260b5580.png)
Please do not report anything that requires fabricating impossible data.

> Also, I'm confused... Why are Pokémon with international languages but japanese characters marked as legal, then?

Keyboard legality is not fully validated, because this requires someone to document every possible keyboard key in every single game and language, and all the changes to the characters through various forms of transfer.

**Comment by Lorenzooone** [comment]
> I evolved a JPN Abra in an ENG Emerald game and it became this. It did not become "KADABRA". ![image](https://user-images.githubusercontent.com/30205550/221086923-1b24cca9-4903-46e9-98c5-0470e4dca1b9.png)

Yeah, it's something that only happens in USA Ruby 1.0. That's why I'm talking about that. They changed it in Ruby 1.1 onwards.

> Also, hacking the wide spaced JPN chars into an ITA game or loading a JPN save into an ITA game is illegal because of keyboard differences. ![image](https://user-images.githubusercontent.com/30205550/221085768-5ff2e2cc-8ced-431b-82e6-2bbc260b5580.png) Please do not report anything that requires fabricating impossible data.

Language is not actually saved. RED is the same chars as wide spaced RED. But that does require RNG Manip, so it is out of question, yeah.

**Comment by Lusamine** [comment]
> Language is not actually saved. RED is the same chars as wide spaced RED.

I am aware, but I am not able to locate the wide spaced RED characters on a Ruby 1.1 newgame. Your other Pokémon in the save with the same TID have "RED" but not wide spaced, which suggests something is hacked. I do not see how you can RNG manip impossible characters without moving a savegame into different carts of different languages (also hacks).

> They changed it in Ruby 1.1 onwards.

We generally respect the latest patch; if the behavior is only on an older version that was later fixed,  So current behavior is preferred.

**Comment by Lorenzooone** [comment]
> > Language is not actually saved. RED is the same chars as wide spaced RED.
> 
> I am aware, but I am not able to locate the wide spaced RED characters on a Ruby 1.1 newgame. Your other Pokémon in the save with the same TID have "RED" with language ITA but not wide spaced, which suggests something is hacked. I do not see how you can RNG manip impossible characters without moving a savegame into different carts of different languages (also hacks).

The bytes are actually the exact same. The Wide-spaceness is something that PKHex puts in. The Pokémon with OT RED but language ITA come from my save file which traded to this one. I was testing the Nincada "glitch" with nicknames, which is another quirk of Japanese Ruby. You can see the number of trades for that (and you can also check the "hacky" workaround they implemented, if you have a link cable around). And, regardless of whether you use Japanese Ruby 1.0 or USA Ruby 1.0, you'll be able to edit the nicknames of all three of the mons with OT RED. Both Japanese and Italian. But not for OT LORENZO, as expected, which will still get the Shedinja with Language set to Italian but Japanese name.

> 
> > Also, it must be named "ABRA". It's important.
> 
> The wide vs narrow chars is important. A Japanese game would have wide characters. The ITA or ENG game would have narrow chars.

The ABRA has been caught in a legit playthrough of Japanese Ruby, and named ABRA with the included Alphabet. Because the bytes are the same, it's not really important. You can actually test it yourself, if you don't believe me!

> 
> > They changed it in Ruby 1.1 onwards.
> 
> We generally respect the latest patch, if the behavior is only on an older version that was later fixed, So current behavior is preferred.

Understandable...

**Comment by Atrius97** [comment]
> The Wide-spaceness is something that PKHex puts in.

No, it very much is not. They are different characters. "RED" half width latin characters are not the same as "ＲＥＤ" full width characters.

Full width characters are only enterable on a Japanese game, all others use half width.

**Comment by Lusamine** [comment]
> The bytes are actually the exact same.

No, they are not.  Please stop debating about this. It is not going to be changed.

![image](https://user-images.githubusercontent.com/30205550/221091130-45368fae-4502-4133-8f3d-51da6856509d.png)

**Comment by Lorenzooone** [comment]
> > The Wide-spaceness is something that PKHex puts in.
> 
> No, it very much is not. They are different characters. "RED" half width latin characters are not the same as "ＲＥＤ" full width characters.
> 
> Full width characters are only enterable on a Japanese game, all others use half width.

Please enter the name RED on an English game, and on a Japanese one. Then check the strings. Remember that names are terminated at the first FF. So anything after that the game does not interpret and/or read for its checks.

**Comment by kwsch** [comment]
Until someone creates APIs for keyboard checks for all games, not worth implementing anything for this.

The intent is to find user entry mistakes, not "is this extreme edge case plausible". That is left to the user to decide.
