### ISSUE TITLE
7-star tera raid Pikachu update request

### ISSUE THREAD

**Issue by AshKoen** [kwsch/PKHeX#3813]
Hi I'm a new guy using sysbot. I wanted to edit my 7-star Pikachu's scale so I traded it but found out that I cant trade it back. Please update 7-star tera raid Pikachu event please. Thank you!

**Comment by Lusamine** [comment]
PKHeX is already updated on latest commit for the Pikachu.  SysBot pulls stable releases, not the latest commit.  This is not a PKHeX issue. Your bot host either needs to figure out how to update their bot or wait for the next release.
