### ISSUE TITLE
Violet Input file too large

### ISSUE THREAD

**Issue by k20stitch** [kwsch/PKHeX#3816]
**Describe the bug**
PKHex reports Violet save file is too large. I don't know if this was a result of an update but I tried updating in order to resolve this issue. I don't recall doing updates prior.

Initially I thought my save was corrupt because what livehex was reporting in my boxes were not right and none of my other pkhex dependent apps worked. Figured I'd try through pKhex only using the save manager but that generated the file too large error, so I created another user and a brand new save, got far enough to save so that I could export my save file and see my boxes but my brand new save file is the same exact size and still doesn't work. I do not have another jailbroken switch to test. Save file attached.

**To Reproduce**
1. Download existing save using JKSV
2. Transfer to computer via ftp (bin, auto, ascii I tried them all with different clients but should be bin).
3. Open in PKhex

**Expected behavior**
Save file should open

**Screenshots**
![image](https://user-images.githubusercontent.com/25312232/221718764-e8f93b7f-c1dd-4785-be74-49ed00bc386e.png)

**Additional context**

[main.zip](https://github.com/kwsch/PKHeX/files/10845382/main.zip)

**Comment by Lusamine** [comment]
Not a bug. Program is not expected to work on an update released after it.

If you can figure out how to use the testing branch for 1.2.0, try it.
https://github.com/kwsch/PKHeX/tree/sv120

Otherwise, be patient and wait for an update.
