### ISSUE TITLE
Scarlet/Violet Mystery Gift Pokemon with a Height/Weight of 0

### ISSUE THREAD

**Issue by Wanderer1391** [kwsch/PKHeX#3820]
**Describe the problem**
Mystery Gift Pokemon in Scarlet/Violet that are set by the event to have a Height and Weight of 0 such as Jiseok's Garganacl and the DLC Purchase Hisuian Zoroark register as invalid due to being considered statistically improbable.

**To Reproduce**
Selecting either Mystery Gift from the Mystery Gift Database or the Encounter Database.

**Expected behavior**
They should register as legal.

**Comment by kwsch** [comment]
Nope, that's how it works.
