### ISSUE TITLE
Changing Pokemon Level generates an "Individual: Individual (XX_XX) AV Should be greater than X" error (X can be different values)

### ISSUE THREAD

**Issue by MarvelousMoth** [kwsch/PKHeX#3821]
**Describe the problem**

I am currently trying to create a realistic Pokemon (Bellsprout in this case) to send over to my Let's Go Pikachu game via trading. I am doing the following steps:

- Using PKHex's latest version (23/02/27), I created a blank save file for Let's Go Eevee by going into Options> Blank Save Version
- Using the Encounter Database, I searched for a Bellsprout from LGE, I selected the one from Route 24, Levels between 8 - 12. 
- Selected View, changed the level from 7 > 8
- Went to "Cosmetic", checked Auto and then unchecked it so that the CP updates
- Clicked on the red legality triangle, and received an error reading "Individual: Individual (AV_HP) AV Should be greater than 1"
- Additionally, the overall IVs do not change to reflect a "level up"
- Using Randomize AVs does fix the issue, however it creates Pokemon with an unreasonably high CP for the level (LV 9 with 1662 CP for example)

**To Reproduce**
Follow the steps shown above or check the PB7 file.
PB7 added in the .zip file.

**Expected behavior**

- When changing the level of a Pokemon within the bounds of that "encounter group" (lv 8 - 12 for example), I expect that the IVs should reflect the change between levels of that "encounter group". Alternatively, there should be on option to select which level from that "encounter group" should be applied to the Pokemon chosen using a dropdown or something

**Screenshots**
Encounter DB:
![image](https://user-images.githubusercontent.com/126654267/222077481-b31f1c42-a402-49fa-ae26-8f43c88690ca.png)

Stats at LV 7:
![image](https://user-images.githubusercontent.com/126654267/222077754-01a0a175-444a-4d15-9cf4-ca1df536ec91.png)
![image](https://user-images.githubusercontent.com/126654267/222077666-be5de20e-3dd2-43ee-a1b0-5b4e1fdc71f2.png)
![image](https://user-images.githubusercontent.com/126654267/222078033-14a26746-d5d7-4c2e-ab70-9b7d1c96bd79.png)

Stats at LV8 when only changing the LV from the "Main" Screen:
![image](https://user-images.githubusercontent.com/126654267/222077919-98608364-0893-4c87-8cce-cbc5eccd86db.png)
![image](https://user-images.githubusercontent.com/126654267/222077965-28210cbc-fba9-4a0c-9c53-9a206c20d767.png)
![image](https://user-images.githubusercontent.com/126654267/222078093-08ab42c3-f4f8-4f16-b5c2-315ce9492e6c.png)

Error message:
![image](https://user-images.githubusercontent.com/126654267/222078212-72eceb9f-b88b-4335-851d-a5367b9904f0.png)

**Additional context**
[069 - Bellsprout - 51F3F83BE039.zip](https://github.com/kwsch/PKHeX/files/10858322/069.-.Bellsprout.-.51F3F83BE039.zip)

**Comment by Lusamine** [comment]
I'm not sure what you're saying is a bug.

Level is for the user to decide.
IVs do not change with level up.
AVs are gained in a non-deterministic manner each level and the message tells you where you need to add AVs for it to be legal. When you gave the Bellsprout 1 level, you had to give it at least 1 Defense AV.

Everything you've described is working as intended. Just read the message and do what it says.

**Comment by MarvelousMoth** [comment]
Fair enough, thank you for the explanation, my understanding seems to have been wrong. Thank you again!
