### ISSUE TITLE
Kanto Mr Mime from PLA is illegal in SWSH

### ISSUE THREAD

**Issue by twinbee321** [kwsch/PKHeX#3829]
**Describe the bug**
Kanto Mr Mime from PLA is illegal in SWSH
Invalid: Unable to match an encounter from origin game.

below attached file is original pa8 file of Mr Mime from PLA
[122 - 마임맨 - CC09E426AF47.zip](https://github.com/kwsch/PKHeX/files/10910934/122.-.-.CC09E426AF47.zip)
below attached file is pk8 file of Mr Mime which was converted to SWSH from PLA also has illegal flagged
[122 - 마임맨 - F89EE426AF47.zip](https://github.com/kwsch/PKHeX/files/10910964/122.-.-.F89EE426AF47.zip)

**To Reproduce**
Drag and Drop the Mr.Mime from PLA to SWSH

**Screenshots**
![001](https://user-images.githubusercontent.com/99508812/223464742-4205f41d-66eb-4f71-a5de-ed78047d1371.jpg)

and thanks for your hard work!

**Comment by Lusamine** [comment]
This is currently known and involves a lot of Pokémon whose evolution methods are different in different games.

Kanto Weezing with SWSH origin (evolved in BDSP) has a similar issue.
Level 1 Leafeon from Gen 7 origin (evolution no longer requires a level up) has a similar issue.

It'll be fixed eventually but needs a fairly significant refactor, so it's on the back burner.
