### ISSUE TITLE
Pokewalker Event Route false illegality shown for non Japanese/Korean games

### ISSUE THREAD

**Issue by NickPlayeZ** [kwsch/PKHeX#3837]
Pokemon caught on Pokewalker Event Routes that were exclusive to Japanese and/or Korean games are shown as illegal (e.g. the level 5 Magby from Amity Meadow).
They are however legal due to how Pokewalkers can interact with games they're not paired to. If one were to take e.g. a Japanese Soulsilver game that downloaded the Amity Meadow Event Route, pair this savefile with a Pokewalker, take a stroll on Amity Meadow and catch for example the earlier mentioned Magby. Now you don't only have the option to transfer that to your Japanese Soulsilver but you could also instead "receive gifts" from this Pokewalker on e.g. an English language Heartgold. If you do that and receive the Magby on your English Heartgold this way, the Magby will have the Heartgold savefiles' OT, Trainer ID, Secret ID and the games English origin Language.

(for more info read part 11 of this guide my friend happylappy made: https://docs.google.com/document/d/1-etPYFvFmDarEiIjhETrKkl7fJjo01tcH3K8SOEe5iM/edit)

**Comment by kwsch** [comment]
Related: https://github.com/kwsch/PKHeX/issues/3594

**Comment by Atrius97** [comment]
Can you provide any form of proof that shows the Recieve Gifts function works for PokeWalkers that are not linked with a given copy of HGSS, including one with a different language than the save that set the PokeWalker on a stroll?

The original source for the claim is dubious at best, since they were using cheat codes for shiny lock removal. We would need evidence this is possible in two unmodified instances of the game, without the use of savefile editors, cheats, or glitches.
> Through the efforts of ShinyCollector, a shiny hunter who used an AR code to remove the shiny-lock for and successively shiny-hunt a pokewalker pokemon. They claimed to use several pokewalkers simultaneously to shiny-hunt their Wailmer, and I understandably had questions for them about that. Through interviewing them, they revealed that a pokewalker can send pokemon to a copy of HGSS it is not paired with.

**Comment by NickPlayeZ** [comment]
Yeah sure I'll record a video with a korean and german game to youtube and send the link here (I'll edit this message with the link; probably will be able to make the video in about 1-2 hours)


> Can you provide any form of proof that shows the Recieve Gifts function works as you've described for PokeWalkers that are not linked with a given copy of HGSS, including one with a different language than the save that set the PokeWalker on a stroll?
> 
> The original source for the claim is dubious at best, since they were using cheat codes for shiny lock removal. We would need evidence this is possible in two unmodified instances of the game, without the use of savefile editors, cheats, or glitches.
> 
> > Through the efforts of ShinyCollector, a shiny hunter who used an AR code to remove the shiny-lock for and successively shiny-hunt a pokewalker pokemon. They claimed to use several pokewalkers simultaneously to shiny-hunt their Wailmer, and I understandably had questions for them about that. Through interviewing them, they revealed that a pokewalker can send pokemon to a copy of HGSS it is not paired with.

**Comment by Atrius97** [comment]
If possible, please be sure to show the entire process, specifically the Korean game setting a Korean event exclusive route, and sending a pokemon exclusive to that route to a German game, where it recieves the German game's IDs and OT.

**Comment by Atrius97** [comment]
Thank you for sharing, it looks like with this new discovery that the changes made in #3594 should be reverted.
