### ISSUE TITLE
Megearna QR code event for database

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#384]
this is my QR code for the japanese megearna event. As it is region locked and works only on JAP 3ds and game, please scan it on a jap console and extract the legal pokemon to add to the database!

also please check #377  i have more legality bugs on evolved egg-mons

![unnamed](https://cloud.githubusercontent.com/assets/23362234/20238349/48965e02-a8e9-11e6-9e34-520101763a59.jpg)

**Comment by kwsch** [comment]
Event database is currently WC6 only; and it only imports Mystery Gift files.
Pretty sure that event QRs do not grant you the pokemon, you have to go capture it.

**Comment by SciresM** [comment]
Magearna QR is special, sets an event flag in the save. I'm currently working on event flag support, so expect Magearna soon.

**Comment by fadeZero** [comment]
great news SciresM! so, maybe, there are more ingame events that needs only to be activated? maybe Ethernal Floette, some Shiny UB and Marshadow?

**Comment by SciresM** [comment]
no.
