### ISSUE TITLE
[GEN 2] EVs sqrt off by one

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#3841]
**Describe the bug**
Setting EVs for a stat to 63001 (251*251) gives 63 stat points instead of 62 in PkHex. The game gives 62 stat points. You can test this by recalculating the stats by depositiong the Pokémon and withdrawing it.

**To Reproduce**
[POKEMONG.zip](https://github.com/kwsch/PKHeX/files/11011027/POKEMONG.zip)
Look at the Pidgeot's speed in PkHex. Look at its speed in-game. To check that it's not a non-updated stat, deposit it and withdraw it.

**Expected behavior**
All precise squares should not be rounded up.

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/7537905/226176275-6f1e1483-30c9-4735-a999-0ec4f6832a83.PNG)

**Additional context**
I noticed this bug while testing for my own applications, to understand how I should implement the calculations.

**Comment by kwsch** [comment]
Related: https://github.com/kwsch/PKHeX/issues/2264

**Comment by Lorenzooone** [comment]
Wait! You need to clamp the value at 0xFF. The new current code will give 64 stats when EVs are maxed!
