### ISSUE TITLE
Valid gen II moves reported as ilegal

### ISSUE THREAD

**Issue by yor-so** [kwsch/PKHeX#3849]
Game: Pokemon Crystal (3DS Virtual Console).
PkHex Version: 20230227.

Valid gen II moves are being reported as ilegal.

-Beedrill. Level 13. Moves: Harden, Fury Attack.
-Kadabra. Level 18. Moves: Confusion.
-Larvitar. Level 40. Moves: Peck, Tail Whip, Supersonic, Horn Attack.
-Porygon. Level 15. Moves: Peck, Supersonic, Horn Attack.

I got all those pokemon in-game without any modifications.

![image](https://user-images.githubusercontent.com/5457965/227725271-e5d89197-5983-4cec-a769-fe7f838c8849.png)
![image](https://user-images.githubusercontent.com/5457965/227725282-6330b8e8-3694-499f-83d9-fcdcd26acd30.png)
![image](https://user-images.githubusercontent.com/5457965/227725524-2cac4257-190d-4f8d-b15c-331234a8977f.png)
![image](https://user-images.githubusercontent.com/5457965/227725517-bfec590b-bbc7-4b7f-ae0a-30311aa076c0.png)

**Comment by Lusamine** [comment]
Please provide the files for these Pokémon if they are still illegal on the [Development Build](https://projectpokemon.org/home/files/file/2445-pkhex-development-build/), not the latest stable release.

**Comment by yor-so** [comment]
Same happens with the Development Build.
Attaching my save file.

[sav.zip](https://github.com/kwsch/PKHeX/files/11069385/sav.zip)

**Comment by Lusamine** [comment]
This looks like the same problem as this: https://github.com/kwsch/PKHeX/issues/3830

Related to: https://github.com/kwsch/PKHeX/pull/3359

The Pokémon is treated as legal in Gen 1 but not Gen 2.
![image](https://user-images.githubusercontent.com/30205550/227729760-dc27616b-27c3-4801-bdd4-901a4a112212.png)

Will eventually be fixed, just not soon.
