### ISSUE TITLE
Numerous False Positives on "Encounter Type PID Mismatch"

### ISSUE THREAD

**Issue by Zetawilk** [kwsch/PKHeX#3855]
The "Encounter Type PID Mismatch" legality error is frequently a false positive. The following examples come from Soul Silver: 

Zubat can be met at level 2 in Dark Cave. 
Zigzagoon can be met at level 3 in Sprout Tower using the Hoenn Sound feature. 
The roaming legendaries Entei, Raikou, and Suicune. 
The legendaries Ho-oh and Moltres. 
NPC Riley gives the player a Riolu egg which can hatch and then evolve into Lucario and be traded over. 

The list goes on. Advise: Remove "Encounter Type PID Mismatch" in cases where it doesn't apply. Reconsider from the ground-up what the multiple points of the error's terminology means: "Encounter Type", "PID", and "Mismatch".

**Comment by Lusamine** [comment]
Please provide example files of legitimate Pokemon that are triggering the "numerous false positives".

**Comment by Zetawilk** [comment]
[PKHeX (23.02.27)a.zip](https://github.com/kwsch/PKHeX/files/11174651/PKHeX.23.02.27.a.zip)

**Comment by Lusamine** [comment]
Did you make any edits to these Pokémon at all? And are they from a legitimate game (and not a romance for example)?

**Comment by kwsch** [comment]
These are not legitimate files. Briefly checking the IVs, their sum is oddly high, hinting that they were manually adjusted upwards or came from a ROM Hack that tampered with the IV generation routine.

"Encounter Type PID Mismatch" means exactly what it says; the encounter type must have a specific PID(IV/etc) correlation, and the detected type does not match what the encounter is expected to have (aka, a mismatch).
