### ISSUE TITLE
Feature Request: SuMo Story Progression/simple location editing

### ISSUE THREAD

**Issue by agent55511** [kwsch/PKHeX#386]
Title.

**Comment by kwsch** [comment]
1. Event Flags not currently exposed, will be once SciresM completes legendary flag research.

2. ???????? I'm not adding 5.9 MB of maps to the exe, adding vector coordinates to highlight met locations on the map, or doing any of that for previous generations since that will be the next 'logical' step.

**Comment by agent55511** [comment]
If not a GUI, could you consider adding a fail safe that stops players from entering invalid X, Y coordinates for the selected map by replacing the invalid coordinates with known good ones for the map selected? The game will crash if the map is changed without changing the X, Y coordinates entered.

**Comment by kwsch** [comment]
And how is PKHeX supposed to know the in-bounds values for every single map?

**Comment by agent55511** [comment]
Actually, forget the whole fail safe... in theory you could leave the system as is in place, then add a simple location editor alongside it which only knows a single set of good coordinates for each location. That way wouldn't have to worry about the bounds. If this is asking too much I'll stop.

**Comment by kwsch** [comment]
And who is going to prepare a list of valid coordinates for every map?

Best to not include in the program and instead as a forum post, it's just a reference not a constraint/supplement necessary to have in the program.
