### ISSUE TITLE
Crystal - Egg Availability Flag

### ISSUE THREAD

**Issue by hylianpi** [kwsch/PKHeX#3862]
**Is your feature request related to a problem? Please describe.**
I find that eggs take tediously long to become available at the daycare in Pokemon Crystal, so I would really appreciate the egg availability flag to be added to the flag list.

**Describe the solution you'd like**
I have researched this and found the offset of the flag. It is located at both 1C83 and 2A83 (I'm not sure why data is duplicated), and it is the 2nd bit in the byte there. For example, I updated the byte from a1 to e1 (1010 to 1110) and successfully had an egg available. In another test I've seen it go from 81 to c1 (1000 to 1100). I do not know what the other bits are for.

**Comment by fattard** [comment]
This is actually a little more complex.
Offset 0x2A83 in international Crystal stores a saved copy of the wram var `wDayCareMan` (as named in [Pret disassemblies](https://github.com/pret/pokecrystal/blob/9a917e35760210a1f34057ecada2148f1fefc390/constants/wram_constants.asm#L307)).
This var is a bit field, and the bit 6 is the one that toggles the egg available.

So this need to be accessed as a flag value, something like `SAV.setFlag(0x2A83 + (6 >> 3), 6 & 7, true);`

BTW, the offset for international GS is 0x2AA8.

@hylianpi you can already do what you want with my plugin [FlagsEditorEX](https://github.com/fattard/FlagsEditorEXPlugin).
It is available through the Edit Flags > Raw Flags Edit > Sys Flags

![image](https://github.com/kwsch/PKHeX/assets/1159052/292a3e85-f326-4fb2-9e7f-304be261df7d)

Not all flags need to be exposed by the main PKHeX, unless they are pretty useful.
Until this is decided, you can use the above solution.
