### ISSUE TITLE
Pokemon SV Ver.1.3.0 Update start!

### ISSUE THREAD

**Issue by scd02** [kwsch/PKHeX#3864]
**Describe the bug**

**To Reproduce**

**Expected behavior**

Hello, Pokemon Scarlet and Violet updated to Ver.1.3.0 yesterday.
In response to this, please provide a new update.
Thank you.

**Screenshots**

**Additional context**

**Comment by Lusamine** [comment]
This is not a bug.  A program made to work for 1.2.0 is not expected to work for 1.3.0.

Please be patient and do not open issues asking for an update faster.

**Comment by Lusamine** [comment]
\ PKHeX works fine for Scarlet/Violet 1.3.0 as far as I can tell.

Please upload a save if it is not working for some reason.
