### ISSUE TITLE
Calling Current before MoveNext is undefined

### ISSUE THREAD

**Issue by Junjun-zhao** [kwsch/PKHeX#3871]
When run the PKHeX with the latest .NET 8 Preview4 runtime, IEnumerable.Current throw System.InvalidOperationException when IEnumerable collection is empty.
please see details link: 
https://github.com/dotnet/runtime/issues/85243
https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current?view=net-7.0

**Comment by kwsch** [comment]
What is the use case? An un-traversed ienumerable won't have a current if you haven't checked MoveNext
