### ISSUE TITLE
shadow pokemon showing up as illegal

### ISSUE THREAD

**Issue by doblothedumb** [kwsch/PKHeX#3872]
when looking at boxes from XD gale of darkness using PKHeX, shadow Pokémon with a completely empty heart gauge are shown as invalid, due to not having the national ribbon. attached two screenshots showing the same box in pkhex and in game. alongside the save file.

![image1](https://user-images.githubusercontent.com/131919486/234706391-6374e22f-8f39-4ff1-996c-c399a2afa5b9.png)
![image](https://user-images.githubusercontent.com/131919486/234706406-b4628984-13f2-4698-8374-f5e6fa8f7c49.png)
[01-GXXE-PokemonXD - Copy.gci.zip](https://github.com/kwsch/PKHeX/files/11337440/01-GXXE-PokemonXD.-.Copy.gci.zip)

**Comment by kwsch** [comment]
This is kind-of intended; there is no way to differentiate a correctly purified Pokémon from a Shadow (in XD) unless the savedata is involved.
