### ISSUE TITLE
Pokemon missing Abilities

### ISSUE THREAD

**Issue by deisuke1234** [kwsch/PKHeX#388]
Hello guys i saw some issue with that some pokemons are limited with the ability and not the full list of which ability it can have. Let say for example Suicune at this pkhex it has pressure and inner focus but at the older pkhex he has water absorn which dosent seem to appear to this new pkhex. Please solve this issue.

**Comment by kwsch** [comment]
Suicune's ability was changed, it no longer has water absorb.
