### ISSUE TITLE
Request: set encounterable vivillion forms in Scarlet/violet

### ISSUE THREAD

**Issue by bloggingninja** [kwsch/PKHeX#3884]
**Is your feature request related to a problem? Please describe.**
pokemon lets you send a postcard from go to Scarlet/Violet to encounter different vivillion forms than normal. It would be nice if there was someplace in pkhex to edit for similar functionality.

**Describe the solution you'd like**
a way in pkhex to set the encounterable vivillion form for the save, even if it requires setting a start time for the "24 hours"

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
spoofing location in Pokemon go to get other postcards.

**Additional context**
I feel like there's got to be a way through the save block editor of doing this but I can't seem to figure it out.

**Comment by Lusamine** [comment]
This is already editable through block editor if you search "Vivillon" and hit enter.
![image](https://github.com/kwsch/PKHeX/assets/30205550/23f8b980-20bd-4b94-b2b2-90a28ab425b1)

If that's too hard, there are also plugins to help you do it.
https://projectpokemon.org/home/forums/topic/63197-sv-overworld-vivillon-form-changer-plugin/
