### ISSUE TITLE
S/V Batch edit TR Relearn Flags

### ISSUE THREAD

**Issue by observeroftime01** [kwsch/PKHeX#3887]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have boxes full of Pokemon, and I want to quickly and efficiently give all of my boxes worth of Pokemon their TR / TM relearn flags. This is regarding Scarlet / Violet, but could probably also happen in other games which have a similar list of "remembered" moves. I find it nice to have my entire collection of Pokemon to be ready to remember any TR move, without me having to carry around the entire list of TRs in my backpack (or stopping by a pokemart to make them). It is a relatively _minor_ inconvenience in the grand scheme of things, I know. 

**Describe the solution you'd like**
I'd like to open up the batch editor, and do something like `.RelearnFlags=$all` or `RelearnFlags=$suggest` to give all my Pokemon their respective (and appropriate) TM Relearn flags. 

**Describe alternatives you've considered**
Setting up  some kind of AHK macro to click through all of my boxes for me, checking the "give all" option under "Relearn Flags", setting the Pokemon, and moving onto the next. This is obviously pretty cumbersome and not ideal, since we have a built-in batch editor that seems well suited for the task, and if the macro messes up for whatever reason, the results can be... well let's call it interesting.

**Additional context**
I do not know if this feature requires more research, but I believe it does not. The reason for my belief is that we already have a TR Relearn Flag editor in the program, which automatically assigns the correct TRs to the Pokemon when asked to. It doesn't seem like a huge leap to suggest automating this via the batch editor, unless there is some aspect I've failed to consider which would present an obstacle.

This is the part of the post where I hope I'm not simply blind, and the feature is already implemented somewhere and I just can't find it 😅.

Anyways, that is my suggestion, thank you for your time.

**Comment by sora10pls** [comment]
.RelearnMoves=$suggestAll

**Comment by observeroftime01** [comment]
Whelp. I knew it. Thanks a lot, case closed.
