### ISSUE TITLE
Fennekin non-Legality

### ISSUE THREAD

**Issue by leafeon012** [kwsch/PKHeX#3901]
Fennekin hatched from eggs in SV can't be set as a Dream Ball, but the legality is said to be correct.

Looked at all the cases of the previous generation, but there was no way that Fennekin could be born in Dream Ball.

**Comment by sora10pls** [comment]
This is known; ball breed legality is not yet revised for past-gen imports to SV. It’s still a work in progress.

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/c52b49de086a42073a35cde18585de50eb2ff7e9
