### ISSUE TITLE
UX Improvement Suggestion under "Latest (not OT) Handler" in OT/Misc tabs

### ISSUE THREAD

**Issue by teward** [kwsch/PKHeX#3902]
**Is your feature request related to a problem? Please describe.**
It is slightly confusing when we have "OT" in two places in the same tab. Specifically, "OT" is used to refer to both Current Handler Name field and OT Trainer information.  Which is a little confusing.

**Describe the solution you'd like**
Change of "OT" under "Latest Handler" to either "Name" or "HT".  Attached image with the freehand circles and arrows points at where on the page it irks me.

**Describe alternatives you've considered**
N/A - this is strictly a UX suggestion

**Additional context**

![image](https://github.com/kwsch/PKHeX/assets/327952/bac1b2e3-6afb-43e3-8899-652800f86c70)

**Comment by kwsch** [comment]
Current handler is a combo box that already shows as OT/HT, and the label just changes color for a quick visibility indication.

I don't think this is worth changing.
