### ISSUE TITLE
Unable to match an encounter from origin game. 

### ISSUE THREAD

**Issue by BarbarianBling** [kwsch/PKHeX#3904]
![Screenshot 2023-06-06 144013](https://github.com/kwsch/PKHeX/assets/116987330/f86f5d9f-cce0-4b6f-a0cc-b979d3fea16c)
I have already looked up the encounter location and the encounter level for Hisuian Zoroark and it still won't legallize it.

**Comment by sora10pls** [comment]
Per the issue template you chose to ignore:
> This is not to ask why fabricated data does not pass the legality check.
