### ISSUE TITLE
unable to change trainer id and original trainer info

### ISSUE THREAD

**Issue by supertails12** [kwsch/PKHeX#3905]
trying to make a mew glitch mew legit by changing the ot to gf and the id to 22796 but it isnt working can you help with this

**Comment by sora10pls** [comment]
PKHeX can not make legit Pokémon, only legal. Legit implies they were obtained without any cheats or third-party software. 

Per the issue template you chose to ignore:
> This is not to ask why fabricated data does not pass the legality check.
