### ISSUE TITLE
Crash on loading a 32 box save

### ISSUE THREAD

**Issue by albertodev01** [kwsch/PKHeX#3906]
**Describe the bug**

My Pokémon SUN save file has 32 box filled and I always get this error:

<details>
  <summary>See trace</summary>
  

> Exception Details:
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at PKHeX.Core.LearnPossible.FlagEncounterMoves(PKM pk, IEncounterTemplate enc, Span`1 result)
>    at PKHeX.Core.LearnPossible.Get(PKM pk, IEncounterTemplate enc, EvolutionHistory history, Span`1 result, MoveSourceType types)
>    at PKHeX.Core.LegalMoveInfo.ReloadMoves(LegalityAnalysis la)
>    at PKHeX.Core.LegalMoveSource`1.ReloadMoves(LegalityAnalysis source)
>    at PKHeX.WinForms.Controls.PKMEditor.UpdateLegality(LegalityAnalysis la, UpdateLegalityArgs args)
>    at PKHeX.WinForms.Controls.PKMEditor.LoadFieldsFromPKM(PKM pk, Boolean focus, Boolean skipConversionCheck)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
> 
> Loaded Assemblies:
> --------------------
> System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Private.CoreLib.dll
> 
> PKHeX, Version=23.6.3.0, Culture=neutral, PublicKeyToken=null
> C:\Users\ALBERT~1\AppData\Local\Temp\.net\PKHeX\vnzrralZc+FxlLdkUHFTiKTdtLbULF4=\PKHeX.dll
> 
> System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Runtime.dll
> 
> System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\System.Windows.Forms.dll
> 
> System.ComponentModel.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.ComponentModel.Primitives.dll
> 
> System.Windows.Forms.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\System.Windows.Forms.Primitives.dll
> 
> System.Runtime.InteropServices, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Runtime.InteropServices.dll
> 
> System.Drawing.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Drawing.Primitives.dll
> 
> System.Collections.Specialized, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Collections.Specialized.dll
> 
> System.Threading.Thread, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Threading.Thread.dll
> 
> System.Collections, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Collections.dll
> 
> System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Threading.dll
> 
> System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Diagnostics.TraceSource.dll
> 
> System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\System.Drawing.Common.dll
> 
> Microsoft.Win32.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\Microsoft.Win32.Primitives.dll
> 
> System.ComponentModel.EventBasedAsync, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.ComponentModel.EventBasedAsync.dll
> 
> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\Accessibility.dll
> 
> System.Resources.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\System.Resources.Extensions.dll
> 
> System.Memory, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Memory.dll
> 
> System.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\System.Drawing.dll
> 
> System.Numerics.Vectors, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Numerics.Vectors.dll
> 
> PKHeX.Core, Version=23.6.3.0, Culture=neutral, PublicKeyToken=null
> C:\Users\ALBERT~1\AppData\Local\Temp\.net\PKHeX\vnzrralZc+FxlLdkUHFTiKTdtLbULF4=\PKHeX.Core.dll
> 
> System.Linq, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Linq.dll
> 
> Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\Microsoft.Win32.SystemEvents.dll
> 
> System.Collections.NonGeneric, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Collections.NonGeneric.dll
> 
> System.ComponentModel.TypeConverter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.ComponentModel.TypeConverter.dll
> 
> System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Text.Json.dll
> 
> System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.ComponentModel.dll
> 
> System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Text.Encodings.Web.dll
> 
> System.Text.Encoding.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Text.Encoding.Extensions.dll
> 
> System.Runtime.Intrinsics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Runtime.Intrinsics.dll
> 
> System.Collections.Concurrent, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Collections.Concurrent.dll
> 
> PKHeX.Drawing.PokeSprite, Version=23.6.3.0, Culture=neutral, PublicKeyToken=null
> C:\Users\ALBERT~1\AppData\Local\Temp\.net\PKHeX\vnzrralZc+FxlLdkUHFTiKTdtLbULF4=\PKHeX.Drawing.PokeSprite.dll
> 
> System.ObjectModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.ObjectModel.dll
> 
> System.Runtime.Loader, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Runtime.Loader.dll
> 
> System.Private.Uri, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Private.Uri.dll
> 
> System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Net.Http.dll
> 
> System.Net.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Net.Primitives.dll
> 
> System.Diagnostics.Tracing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Diagnostics.Tracing.dll
> 
> System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Diagnostics.DiagnosticSource.dll
> 
> System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Net.Security.dll
> 
> System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Security.Cryptography.dll
> 
> System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Net.Quic.dll
> 
> PKHeX.Drawing, Version=23.6.3.0, Culture=neutral, PublicKeyToken=null
> C:\Users\ALBERT~1\AppData\Local\Temp\.net\PKHeX\vnzrralZc+FxlLdkUHFTiKTdtLbULF4=\PKHeX.Drawing.dll
> 
> PKHeX.Drawing.Misc, Version=23.6.3.0, Culture=neutral, PublicKeyToken=null
> C:\Users\ALBERT~1\AppData\Local\Temp\.net\PKHeX\vnzrralZc+FxlLdkUHFTiKTdtLbULF4=\PKHeX.Drawing.Misc.dll
> 
> System.Threading.ThreadPool, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Threading.ThreadPool.dll
> 
> System.Net.Sockets, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Net.Sockets.dll
> 
> System.Threading.Overlapped, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Threading.Overlapped.dll
> 
> System.Net.NameResolution, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Net.NameResolution.dll
> 
> System.Security.Principal.Windows, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Security.Principal.Windows.dll
> 
> System.Security.Claims, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Security.Claims.dll
> 
> System.Text.RegularExpressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Text.RegularExpressions.dll
> 
> System.Windows.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.2\System.Windows.Extensions.dll
> 
> System.Runtime.Serialization.Formatters, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Runtime.Serialization.Formatters.dll
> 
> System.Diagnostics.StackTrace, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Diagnostics.StackTrace.dll
> 
> System.Reflection.Metadata, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Reflection.Metadata.dll
> 
> System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Collections.Immutable.dll
> 
> --------------------
> User Message:
> An unhandled exception has occurred.
> You can continue running PKHeX, but please report this error.

</details>

It does not happen with other saves

**To Reproduce**

 1. Get the latest PKHeX version
 2. Open my [save.zip](https://github.com/kwsch/PKHeX/files/11680189/save.zip) file
 3. Go to Box 1 and see the red box
 4. Do right click and "View" on the red box

**Expected behavior**

I'd expect that all box entries are correctly loaded

**Screenshots**

![error](https://github.com/kwsch/PKHeX/assets/2848696/6ac36d17-64bf-4548-a3a9-c05959aaf04c)

**Additional context**

I didn't notice this error in previous PKHeX versions (at least before the latest major .NET upgrade)

**Comment by kwsch** [comment]
Not sure what happened to the Ivysaur in that slot, but its checksum is not valid. The game hasn't yet detected it as invalid, and it lacks the bad egg flag. Likely will get caught the next time you try reading it in-game.

The relearn move 3 is affected by a bitflip, causing it to be read as `0x4000` which is out of range of all moves. The stacktrace you provided indicates that the LearnPossible.FlagEncounterMoves is lacking some bounds checks on invalid Relearn Moves. I'll add something to account for bad Relearn Moves :)
