### ISSUE TITLE
Item Editor automatically removed my Oval Charm

### ISSUE THREAD

**Issue by kamuisama** [kwsch/PKHeX#391]
So I just got Oval Charm in my game after beating the game and when I opened my save in latest build > item editor, it automatically removed it. I think there is something wrong with the event flag...

**Comment by qqslam** [comment]
Adding onto that, it also seems to remove rare candy and pretty wing from the item pouch.
![image](https://cloud.githubusercontent.com/assets/15657794/20243537/ddf0b6ca-a919-11e6-8ed9-5aa8b08cab8d.png)

**Comment by kwsch** [comment]
According to #351, Rare Candies are not in the Items Pouch but instead in the Medicine Pouch; same for the wings.

You can test to see what pouch an item really belongs in by dragging it off of the Pokémon; the pouch that it goes in will light up.

![img](http://i.imgur.com/90zrx3g.png)

**Comment by qqslam** [comment]
Oh youre right about rare candies!  "Pretty wing" should be items though
