### ISSUE TITLE
mono devel not build work on linux not solved

### ISSUE THREAD

**Issue by amidevous** [kwsch/PKHeX#3914]
Your answer doesn't solve the issue I opened at all.

https://github.com/kwsch/PKHeX/issues/3913

so why close it I'm waiting for a clear answer from you how to install on linux with mono

Visual Studio is only for windows

only mono and compatible with linux and mac

so be sure to indicate how to install at least one version for this system with mono

I do not ask to force the latest version but at least a compatible version

**Comment by kwsch** [comment]
I already answered in the other issue. Per the readme:

PKHeX is a Windows Forms application which requires [.NET 7.0](https://dotnet.microsoft.com/download/dotnet/7.0).

The executable can be built with any compiler that supports C# 11.

There is no obligation or requirement to support every compiler that people want to compile with. If they are out of date or incompatible with modern runtimes, then that is not an issue with the repo you are wanting to compile, it is an issue with your setup.

Others have devised ways to compile PKHeX on systems that are not a Windows operating system. But again, it is irrelevant to the repo. This repo is a Windows Forms application that requires .NET 7; I don't care if you can't compile -- I list how to do it (via Visual Studio), and if you can't run that, that's on you.
