### ISSUE TITLE
Origin symbol mismatches + suggestion

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#392]
Adding Gen 6 origin to a Pokemon shows Gen 7 origin:
![image](https://cloud.githubusercontent.com/assets/17801814/20243854/e0049e68-a937-11e6-8c9a-cce3cb8b7ed3.png)

Adding Gen 5 origin to a Pokemon shows Gen 6 origin:
![image](https://cloud.githubusercontent.com/assets/17801814/20243880/ebe8e9da-a939-11e6-8b39-9ef65f0c9cb3.png)

Anything Gen 4 and below is correct and has no symbol of origin.

When dragging/dropping a .pk6 into the form of a Gen 7 save file, it automatically defaults to showing Gen 6 origin (the blue pentagon)

Gen 6 origin is also shown off in-game with a black pentagon (as seen in the picture below [Gen 5 and below still shows no symbol, also shown in the picture below]), so perhaps have that be added into the program when having a Pokemon with Gen 6 origin in a Gen 7 save file?
![image](https://cloud.githubusercontent.com/assets/17801814/20243877/bdd12724-a939-11e6-83e4-bbe6318cd6c2.png)

**Comment by kwsch** [comment]
Probably because changing origin game doesn't call an update for markings
