### ISSUE TITLE
Pokemon caught in SV and evolved in PLA

### ISSUE THREAD

**Issue by cicciochiave** [kwsch/PKHeX#3929]
**Describe the problem**
Pokemon that can be evolved only in PLA are marked as illegal if borned or catched in SV, transfered in PLA for evolving and then transfered back in SV.

- Dartrix in Decidueye-H
- Bergmite in Avalugg-H
- Goomy in Sliggoo-H (and Goodra-H)
- Rufflet in Braviary-H
- Basculin-H in Basculegion
- Petilil in Lilligant-H
- Dewott in Samurott-H
- Qwilfish-H in Overqwil
- Quilava in Typhlosion-H
- Ursaring in Ursaluna
- Scyther in Kleavor
- Stantler in Wyrdeer

I'm expecting the same error with Slowpoke-G that can evolve only in Sword/Shield with Galarica Cuff or Galarica Wreath.

**To Reproduce**
Catch in SV a Pokemon with a PLA unique evolution (Ursaring in North Province Area 2).
Transfer it in HOME, then in PLA.
Evolve it in PLA (Ursaluna with Peat Block during full moon).
Transfer it back to HOME, then to SV.
[0901 - Ursaluna - 19B9A528CA43.zip](https://github.com/kwsch/PKHeX/files/11899537/0901.-.Ursaluna.-.19B9A528CA43.zip)

**Expected behavior**
The evolved Pokemon should be legal.

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/52650679/3b6616f2-53b8-41d1-bd2a-0caf15ead1f7)

**Additional context**
I didn't try with Hisui Pokemon that can be evolved in SV but i don't think there will be any error.

- Zorua-H in Zoroark-H (level 30)
- Sneasel-H in Sneasler (level up with Razor Claw)
- Voltorb-H in Electrode-H (Leaf Stone)
- Growlithe-H in Arcanine-H (Fire Stone)

Thank you ;)

**Comment by kwsch** [comment]
Duplicate #3917.

**Comment by cicciochiave** [comment]
Oops... sorry
