### ISSUE TITLE
Modern Forme Vivillion not an option.

### ISSUE THREAD

**Issue by ForcedToRock** [kwsch/PKHeX#393]
Had to use an older version of PKHex

![asdas](https://cloud.githubusercontent.com/assets/10488946/20244798/e2ef01a2-a95c-11e6-8049-c7f9e1cbb1fe.png)

**Comment by Tsunamical** [comment]
@kwsch It looks like 8e2438789b64777f5a665604c440930e12db587d caused line numbers to be off in text_Forms_en, offsetting proper forms

**Comment by kwsch** [comment]
Resolved in latest commit.
https://github.com/kwsch/PKHeX/commit/b9bf2ff709ba7a50e9e6cd78275f36d81bfb3e00
