### ISSUE TITLE
Best Friends and Effort Ribbons flagged illegal on previously PLA-exclusive evo lines in SV

### ISSUE THREAD

**Issue by IAmEmber** [kwsch/PKHeX#3930]
Hisui Pokémon that were previously ineligible for the Best Friends and Effort Ribbons due to not having a pre-evolution that could enter SWSH or BDSP (i.e. Basculegion, Sneasler, Overqwil, and Enamorus) are still flagged as illegal if they earned said ribbons in SV.

[0902-01 ★ - Basculegion - 321396F7D91E.zip](https://github.com/kwsch/PKHeX/files/11908329/0902-01.-.Basculegion.-.321396F7D91E.zip)

**Comment by kwsch** [comment]
Duplicate #3917
