### ISSUE TITLE
Alolan Raichu vs. Normal Raichu

### ISSUE THREAD

**Issue by Sentry108** [kwsch/PKHeX#3935]
**Describe the bug**
When generating a Pichu from the Encounter Database for USUM and "evolving" it to a Raichu everything checks out, green check mark that it's legal. However, when I change the form to Alolan, it says it "unable match encounter from the origin game." Even though both information is the exact same for both versions of Raichu, it kicks it back that Alolan version is not legal. 

![image](https://github.com/kwsch/PKHeX/assets/82391602/a1b95527-7837-4438-b984-d6feb3cd66cf)
![image](https://github.com/kwsch/PKHeX/assets/82391602/de30e0c3-bfd0-49b0-aeee-65a8183cdb73)

And here is Alolan, the only difference is changing the form. 

![image](https://github.com/kwsch/PKHeX/assets/82391602/58b26591-40a2-4957-aee0-7f2c374bce85)
![image](https://github.com/kwsch/PKHeX/assets/82391602/26eda0d0-51e5-4669-b411-3c4a840499b9)

**To Reproduce**
 Went to Encounter Database for a hatched Pichu, changed the pokemon to Raichu and then changed the form. Both HT and OT were changed to reflect being different to one another. 

**Expected behavior**
For the encoutner to be legal.

**Additional context**
I was trying to do a search to see if anyone else had this issue for S/V, but the only issue I've seen regarding this was back in 2020 for SW/SH but a completely different error than the unable to match encounter error that I'm facing.

**Comment by sora10pls** [comment]
Duplicate #3917 
HOME legality quirks are a work in progress, please be patient.

**Comment by Sentry108** [comment]
Will do! Thanks :)
