### ISSUE TITLE
Migrate to GitHub Actions for Build Transparency

### ISSUE THREAD

**Issue by LeoDog896** [kwsch/PKHeX#3937]
**Is your feature request related to a problem? Please describe.**
It's very hard to see what exactly went wrong or right in a check for the current setup CI.

**Describe the solution you'd like**
Allowing external contributors to contribute to the actions pipeline, and being able to see the errors and warnings in pull requests can help contributors get faster feedback

**Describe alternatives you've considered**
Continuing on.

**Additional context**
This may also allow for automatic CD, which means that artifacts can be built and deployed per version.

**Comment by LeoDog896** [comment]
By the way, GitHub actions has [support for windows VMs with visual studio installed](https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/)

**Comment by kwsch** [comment]
The Azure Pipelines access was set to "private" during the lead up to Scarlet/Violet release and we forgot to make it public again. I've now made it public, so people can now see the details behind the checkmark.

I don't want to start using a separate CI service. Azure Pipelines does everything and has our (ProjectPokemon) custom integrations built in (pushing to NuGet and uploading builds to the forums).

**Comment by LeoDog896** [comment]
Thanks for the clarification! I didn't know it was possible to make it open, which achieves the same thing I made this issue for.
