### ISSUE TITLE
Valid Shiny Alphas edited in SV, are flagged as ilegal when they are sent to PLA

### ISSUE THREAD

**Issue by CarlosRamirezGriego** [kwsch/PKHeX#3945]
**Describe the problem**
Alpha Pokemon edited in SV, are flagged as ilegal in PLA. 
They lose Alpha Mark,  Mastery move errors and Alpha Flag mismatch.

**Preconditions**
I've these Shiny Alphas generated back in Jan/22 with the Legality Plugin.  It was legal then, its still legal now in PLA.
I took these Pokemon, from PLA -> HOME -> SV
Once in SV, I changed the TID, SID and PID, keeping them Shiny and Legal.
Sent this Pokemon from my gamet to the other person (whose TID, SID I've used). 

**To Reproduce**
By the receiver, they are moved to PLA:   SV -> HOME -> PLA. 

**Actual behavior**
In PLA they lose the Alpha Mark, as you can see for Psyduck in MissingMark.jpg

So, I got this same pokemon sent from the received PLA game to my game, to check it directly there. And PkHex flags it as ilegal. (see InvalidMessage.jpg)

**Expected behavior**
Perhaps the Pokemon is not flagged as ilegal? Im not sure where the error is.

**Screenshots**
![MissingMark](https://github.com/kwsch/PKHeX/assets/32551875/9c4d978f-9c99-4a96-9307-ff355f22b3ab)
![InvalidMessage](https://github.com/kwsch/PKHeX/assets/32551875/763cc2df-ab8a-4b57-8e31-5732153336cc)

[Debug.zip](https://github.com/kwsch/PKHeX/files/12178014/Debug.zip)

**Additional context**
Im attaching the original PK9.
Then how it looks after I edit the TID/SID/PID
Also the same Pokemon once it gets to PLA.

**Comment by sora10pls** [comment]
Working as intended, and not a PKHeX bug.

Do not edit immutable stats with PKHeX and then move them across games again with HOME. HOME expects to see specific values associated with the PKM's tracker, and if anything that can not be edited (e.g. trainer info) is changed, it will be assigned a new tracker, _losing that game-specific data in HOME in the process_.
