### ISSUE TITLE
Cured Pokerus doesn't show strain

### ISSUE THREAD

**Issue by MrPerson0** [kwsch/PKHeX#3957]
**Describe the bug**
Once a Pokemon is cured from Pokerus, its strain should be shown with the "Cured" box checked. However, as of the latest development release, the strain isn't shown. Tested this with Gen 2 and Gen 6 Pokemon, so it seems to be an issue that affects every save.

**To Reproduce**
Either cure a Pokemon naturally or just make it infected + cured, then set it. It'll look normal at that point, but if you view the Pokemon, you'll see the strain is gone.

**Expected behavior**
Strain should appear when a Pokemon is cured.

**Screenshots**
How it looks: 

![image](https://github.com/kwsch/PKHeX/assets/26208088/5513a22e-d520-4e9d-9fcf-d2b504d9f768)

How I believe it should look:

![image](https://github.com/kwsch/PKHeX/assets/26208088/737e0dc9-48d3-4184-abe2-ebe83537bbde)

**Additional context**
If you mess around with a cured Pokemon by checking infected then unchecking cured, the day count will show off to the left:

![image](https://github.com/kwsch/PKHeX/assets/26208088/c1202287-c5c7-43d7-a795-aa0d3b62d658)

Which shows it might be an issue with the display itself.

**Comment by kwsch** [comment]
Cured without ever being infected is not a valid state. 

1. The "Cured" checkbox is indicated if Strain>0 && Days==0
2. The "Infected" checkbox is indicated if Strain>0.

Not sure how you managed to only have "Cured" checked, since it should always be infected as well.

**Comment by MrPerson0** [comment]
Here's a quick video showcasing the issue. I moved to other generation save files showcasing the issue happening there as well: 

https://youtu.be/iaysShh5YHg

Here's my Croconaw where you can see the Pokerus strain in offset 1F is set '30', so it should have a strain of 3 while showing as cured.

[0159 - Ripple - FA48.zip](https://github.com/kwsch/PKHeX/files/12328907/0159.-.Ripple.-.FA48.zip)

Forgot to mention that I am using PKHeX with Windows 11, not sure if that is an issue.

**Comment by MrPerson0** [comment]
Looking into it a bit more, it seems the error started to occur between the 23.04.06 and the 23.05.11 releases.

**Comment by kwsch** [comment]
As mentioned, probably the strain=0 state handling
https://github.com/kwsch/PKHeX/commit/9a768dded3350e4f4c798e42f4d1a2f1cfd82dd0

**Comment by MrPerson0** [comment]
All of my tests have been with strain 3, not strain 0, and the glitch isn't limited to a gen 2 Pokemon, it affects all gens. I'm guessing somewhere in that commit is what threw this off as a whole?
