### ISSUE TITLE
German Sun and Moon Munchlax with Z crystal corrupts save

### ISSUE THREAD

**Issue by Erdnussflip007** [kwsch/PKHeX#3960]
**Describe the bug**
When I inject the wondercard Card # 1601 - Ein Mampfaxo mit Relaxonium Z!.wc7 from the data tab of PKHeX into my pokémon sun game it corrupts the save file.

**To Reproduce**
1. start fresh save file of pokémon sun
2. open savefile in PKHeX
3. Click tools
4. Hover over data
5. Click Mystery Gift Database
6. Scroll down to Card # 1601 - Ein Mampfaxo mit Relaxonium Z!.wc7
7. save it on PC
8. go back to main window by closing the Window „Database“
9. click sav
10. click Mystery Gift
11. click import
12. navigate to file u saved in step 7
13. right-click empty slot
14. click set
15. click save
16. click export save
17. save the save file
18. start Pokémon sun with that file
-> get error screen saying the save is corrupted

**Expected behavior**
Game to start normal, with mystery gift Munchlax activated

**Screenshots**
![grafik](https://github.com/kwsch/PKHeX/assets/69727409/e8c84200-4e35-4198-8bd6-9d79c764ca0f)

**Additional context**
Neither real 3ds nor citra will play the savefile.
after removing the mystery gift the save file will start normally.
[this](https://projectpokemon.org/home/files/file/405-snorlium-z-munchlax/) Website has a version of that card that when injected acts as expected

**Comment by kwsch** [comment]
Unable to replicate; the only difference in the dumped Mystery Gift and the one in the save file is the Year-Month-Date timestamp located at `0x4C` within the file data.

We imported the MGDB gift to our game and were able to receive the gift just fine. I would recommend trying again; probably file transfer issues / truncated save data.
