### ISSUE TITLE
About GEN1 and GEN2 Egg Encounter non-Legality

### ISSUE THREAD

**Issue by ppllouf** [kwsch/PKHeX#3963]
GEN1 and GEN2 egg encounters a minimum of level 5
The current PKHeX is legal at level 1, while level 5 is illegal

**Comment by sora10pls** [comment]
Unable to replicate on latest commit? Eggs are hatched at Lv. 5 in Generations 1-3, which PKHeX both generates and validates correctly on my end.
![image](https://github.com/kwsch/PKHeX/assets/17801814/da5153b5-04c3-45db-8c2a-d4ba635da276)

**Comment by kwsch** [comment]
Looks to be an issue with Egg gifts checking level 1 (met level) and ignoring the actual minimum level (5).
