### ISSUE TITLE
Gen 3 - Gameboy Stamp Issue

### ISSUE THREAD

**Issue by ZapperManYT** [kwsch/PKHeX#3968]
The issue I'm having here is that whenever I select Emerald as the game that the Shiny Faraway Island Mew came from, the Gameboy Stamp does not show up. However, it seems that every other generation shows their respective stamp, apart from RSE, and the icon appears invisible, however whenever selecting games like Gold for this particular Mew, it shows the Gameboy icon.

Here's how you can reproduce this behavior, and it'll be the same for any other Pokémon: 

1. Go to "Cosmetic" on the left-hand side.
2. Click under the left hand side of the "Markings" box, this'll bring you to the "Met" Section to select a game.
3. Scroll down and select one of the three games: Ruby, Sapphire, or Emerald.
4. Upon returning to the 'Cosmetic' section, the Gameboy stamp does not show up, appearing invisible, and when transferred to SwSh, it'll act as though the Mew never had the stamp.

What I expected to happen was for me to simply click on the 'Emerald' option, and for the Gameboy stamp to re-appear, as I thought it was a visual glitch, and as it turns out, it does not appear.

So, for context, someone was looking to trade with me, and they wanted a Shiny Faraway Island Mew, so after using PKHex, and the ALM (Auto Legality Mod) mod to ensure everything was 100% legalized, I went ahead and transferred it to SwSh, and they were about to send me a trade, however they pointed out this issue, so that's why I'm writing here.

**Comment by kwsch** [comment]
The Virtual Console stamp is only for Gen1/2 transfers into Gen7.
