### ISSUE TITLE
Legality Checker

### ISSUE THREAD

**Issue by UranusDarkness** [kwsch/PKHeX#397]
![cattura](https://cloud.githubusercontent.com/assets/18262571/20246635/17e4566a-a9bb-11e6-9d71-b6ef9c58b586.PNG)

**Comment by sora10pls** [comment]
![img_3397](https://cloud.githubusercontent.com/assets/17801814/20246894/b4fb791a-a98e-11e6-80f5-ba07a1c5fd4a.PNG)

#377

**Comment by kwsch** [comment]
Added in latest commit.
https://github.com/kwsch/PKHeX/commit/2c45e499f7cfb9ccd2114f61ade94a7b0eae9591
