### ISSUE TITLE
Bettle Tree Great Ribbon shows legal on the special Pokemon like Mew or Rayquaza

### ISSUE THREAD

**Issue by adaxew** [kwsch/PKHeX#3975]
**Describe the problem**
I am editing the ribbon for some Gen 3 Pokemon, and find the auto selected ribbons show legal for Mew and Rayquaza with the battle tree great ribbon. I think the special Pokemon is not allowed to attend the battle tree.

**Screenshots**
![LegalMedal](https://github.com/kwsch/PKHeX/assets/143809197/9c77cf78-c82e-440e-8f0b-007a18ebde85)

**Comment by sora10pls** [comment]
Working as intended, restricted Pokémon are permitted to enter Single/Double/Multi (not Super) Battle Tree in USUM.
