### ISSUE TITLE
Gen 4 Nickname too long from Pokémon renamed in different language game

### ISSUE THREAD

**Issue by WildEep219** [kwsch/PKHeX#3980]
**Describe the problem**
If you have a Pokémon from one language in gen 4 (such as Japanese) and trade it to an English gen 4 game with the same trainer ID, you can rename the Pokémon (unlike other generations, the name doesn't need to match, just the TID). This can result in Japanese Pokémon with English characters in the nickname. Such a Pokémon can have PKHeX flag it for its nickname being too long.

**To Reproduce**
I attached a PKM of an otherwise-legal Japanese Palkia I obtained from the GTS that I changed the name of in English Pearl with a save with a matching TID. See the Additional context section.

**Expected behavior**
This Palkia should be considered legal.

**Screenshots**

**Additional context**
[0484 - ReallyLong - D30E2242A1DF.zip](https://github.com/kwsch/PKHeX/files/12518323/0484.-.ReallyLong.-.D30E2242A1DF.zip)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/3809
