### ISSUE TITLE
I can't use pkhex because of the update that came in.

### ISSUE THREAD

**Issue by miku1881** [kwsch/PKHeX#3989]
**Describe the bug**
When I try to load saved data due to an update, it says the file is too large and won't load.

**To Reproduce**
1. Go to 'load to save data'
4. See error  input file too large 

**Expected behavior**

**Screenshots**
https://imgur.com/a/c2Luxpq

**Additional context**
Please update pkhex ASAP!

**Comment by ReignOfComputer** [comment]
Not a bug.
https://github.com/kwsch/PKHeX/issues/3988
