### ISSUE TITLE
Input file too large

### ISSUE THREAD

**Issue by ZeztyDragon** [kwsch/PKHeX#3990]
"Input file too large"

1. Go to 'open'
2. Click on 'main save file'
![Screenshot (62)](https://github.com/kwsch/PKHeX/assets/145115724/5788df1e-aed1-4bd7-9aab-0026784637d3)

This happened after the update of pokemon violet. The save file simply wont go inside PKhex🥲

**Comment by Emberion99** [comment]
Just having the same issue with my 2.0.1 save file.

**Comment by ZeztyDragon** [comment]
> Just having the same issue with my 2.0.1 save file. 

I hope they will come with some solution.

**Comment by ZeztyDragon** [comment]
> > Just having the same issue with my 2.0.1 save file. 
> 
> I hope they will come with some solution.
> 

Do you happen to have the old save file before update. I tried to put that file into the save Directory and then the game doesn't recognise the save. I hope someone will help🥲😔

**Comment by Bazinga-lfz** [comment]
NOT A BUG.
Every major update takes time to adapt new version.
Just wait for it,no need to rush.

**Comment by Bazinga-lfz** [comment]
NOT A BUG.
Every major update takes time to adapt the new version.
Just wait for it,no need to rush.

**Comment by Lusamine** [comment]
https://github.com/kwsch/PKHeX/issues/3988
