### ISSUE TITLE
The file is too large(23.09.16.)

### ISSUE THREAD

**Issue by scd02** [kwsch/PKHeX#3991]
**Describe the bug**

**To Reproduce**

**Expected behavior**

The file is too large.
File size: 4401590 bytes

**Screenshots**
![1694853669076](https://github.com/kwsch/PKHeX/assets/96989282/a4ed3993-17e8-4d3d-a198-498e587d0dd1)

**Additional context**

**Comment by Lusamine** [comment]
Should already be fixed on latest commit. You can try on the development build:
https://projectpokemon.org/home/files/file/2445-pkhex-development-build/
