### ISSUE TITLE
Modifications to the pokedex don't seem to work in DLC

### ISSUE THREAD

**Issue by txy960608** [kwsch/PKHeX#3992]
When I clicked "complete DEX" in PKHEX, and then clicked save, after entering the game, the modification of pokedex did not take effect.

**Comment by kwsch** [comment]
Did other changes you made (besides save file) take effect?

**Comment by txy960608** [comment]
When I modified the pokedex, I also modified the wallpaper, and the wallpaper took effect.

![saveeditor](https://github.com/kwsch/PKHeX/assets/33309906/b4fe632e-deb0-45a7-b645-acaedf441f51)

The above is the result shown when I use pkhex to open the save file.

![game](https://github.com/kwsch/PKHeX/assets/33309906/2eee900b-6d96-485f-be70-ae0422ba57ba)

However, in the game, I didn't catch Spinarak

**Comment by ootorikagerou** [comment]
The same phenomenon happened to me.
I used pokedex after modifying ograpon, but only ograpon was reflected and pokedex was not.

**Comment by miku1881** [comment]
I'm having the same problem, except for a few of them, I'm sure I saved them as captured, but when I play with the saved data, the pokedex is not filled in, and the Kitakamidex is the same.　kwsch, please fix it as soon as possible!

**Comment by Lusamine** [comment]
> I'm having the same problem, except for a few of them, I'm sure I saved them as captured, but when I play with the saved data, the pokedex is not filled in, and the Kitakamidex is the same.　kwsch, please fix it as soon as possible!

The problem is already known and more research is being done to fix it. Please be patient; if you are not contributing information for how to fix it, then do not post asking for it to be done faster.

**Comment by miku1881** [comment]
Yesterday, I used pkhex to make the Pokémon Diagram Book complete except for some Pokémon and loaded the save data.
It was not reflected.

Today, I loaded the save data into an older version of the game.

It is now reflected.

**Comment by Lusamine** [comment]
> Yesterday, I used pkhex to make the Pokémon Diagram Book complete except for some Pokémon and loaded the save data. It was not reflected.
> 
> Today, I loaded the save data into an older version of the game.
> 
> It is now reflected.

Please use the development build -- I would suggest using a backup of your save before you edited it with the nonworking version.
https://projectpokemon.org/home/files/file/2445-pkhex-development-build/
