### ISSUE TITLE
Clear all Boxes + Hotkeys

### ISSUE THREAD

**Issue by Sarutopi21** [kwsch/PKHeX#3993]
Asking for the implementation of an option where you can clear all boxes at once instaed of one by one by right clicking and going to clear etc..
OR
Adding the option to set hotkeys for the different options such as clear box, save box data, dump boxes etc..

**Comment by BakaKaito** [comment]
This can already be done. Read through "About PKHeX" from options Dropdown

"Right click on Box Tab: Clear/Sort/Modify Box contents. Hold shift when selecting the action to apply to ALL boxes."

**Comment by Sarutopi21** [comment]
Thanks, didnt know that been doing it one by ine for so long 😭
