### ISSUE TITLE
adding all clothes (duplicates the standard academy-outfits)

### ISSUE THREAD

**Issue by Razzor96** [kwsch/PKHeX#3994]
I used all the "unlock clothing options" functions in the Trainer Data Editor. It is working, but it duplicates the standard academy-outfits in the inventory. You can't use the duplicates but can see them in the selection-inventory

**Comment by sora10pls** [comment]
Probably functionally identical outfits for male and female. Going to keep this open for a bit until I’m able to address it, because the clothing unlock cheat needs to be expanded for new DLC content.
