### ISSUE TITLE
Pokemon caught in Kitakami are not reflected in the Pokedex editor

### ISSUE THREAD

**Issue by observeroftime01** [kwsch/PKHeX#3999]
**Describe the bug**
None of the pokemon I caught in Kitakami show in the Pokedex editor. I almost completed my Kitakami dex, but all the "K-000-Pokemon" entries in the editor are all blank for me.

**To Reproduce**
1. Catch pokemon in Kitakami
2. Dump your save and load it up in PKHeX
3. Click on "Pokedex" and go into the Pokedex editor
4. Observe all of the entries for the pokemon you caught, starting with K-, none of the pokemon caught are registered there.

**Expected behavior**
For pokemon caught via in-game methods to be properly reflected in the pokedex editor

**Screenshots**
See below

**Additional context**

None of the pokemon I caught in Kitakami show in the Pokedex editor. I almost completed my Kitakami dex, but all the "K-000-Pokemon" entries in the editor are all blank for me.

![image](https://github.com/kwsch/PKHeX/assets/57168924/8e82a545-9898-4668-99c6-6842ba4b94d1)

As you can see, I caught a sandslash and sandshrew in game, for example. However, the pokedex editor does not reflect this. This is the same for all pokemon caught (in kitakami) through in-game methods, with one exception. The only pokemon appropriately recognized in the editor as being caught in game, out of all things, is Ogerpon-Hearthflame. 

![image](https://github.com/kwsch/PKHeX/assets/57168924/52a2a3c6-9fc2-4096-876f-27b1f69795b9)

![image](https://github.com/kwsch/PKHeX/assets/57168924/02148a0b-e3a1-45ad-8f58-620e31c82dbf)

However, adding in a new pokemon through PKHeX (from the encounter database) properly populates the data, and it is appropriately reflected in the in-game Pokedex:

![image](https://github.com/kwsch/PKHeX/assets/57168924/29959757-f6fb-4f90-85d8-1fc1c302d88f)

Furthermore, "picking up" a pokemon from your box into the editor and "setting" it again also populates the missing pokedex entry, which is pretty strange.

I would be happy to provide further details regarding this matter, if required.

I know these are early days, thank you for your dedication and work on this. I did not expect an update to drop this soon ♥

**Comment by sora10pls** [comment]
Duplicate #3992

**Comment by observeroftime01** [comment]
I wasn't exactly sure if the two issues were related. #3992 seems to have an issue with edits made not showing up in game, I am having the reverse problem (pokemon caught in game don't show up in the editor, but edits made in the editor reflect in game). True, it's probably related to each other somehow. I don't know if it's bad etiquette to add my issue to a potentially unrelated issue.

Either way, thanks for confirming that this is in fact related. Sorry to bug you guys 😅
