### ISSUE TITLE
New version of Pkhex cannot open my save that increased in storage since the new version of Pokémon scarlet and the dlc

### ISSUE THREAD

**Issue by dennyzs** [kwsch/PKHeX#4002]
**New version of Pkhex cannot open my save that increased in storage since the new version of Pokémon scarlet and the dlc**
I don't know if it's a bug but i just can't edit my save file anymore since the new version of pokémon scarlet and the dlc came and i downloaded the upload. 
Before this my save file had a storage of 3187 Ko and now has a storage (numeric data idk what is the name sry) 4299 Ko and Pkhex telling me that is too big to be opened but idk what happened, does anyone can help me pls would be really kind ?
My discord in case (cause sry i don't know how to use properly github for non) : Hirokaze#7021.

**To Reproduce**
1. Go to Pkhex with the latest version downloaded
2. Click on open and select my main file (my save)
3. see the error

**Expected behavior**

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/145261325/f14629db-ccf2-4c88-9178-fc988e1ed88a)
![Capture](https://github.com/kwsch/PKHeX/assets/145261325/604063fe-b301-48bc-b409-6126fa8a8c03)

**Additional context**
I recently downloaded the dlc with a modded switch, so i thought it was the problem, so i deleted it and try to edit the new save without the dlc on my switch but it didn't work my saves were still too big and i don't know why they got this big just after the new upload pls somebody help that would be so nice.

**Comment by MIO1339** [comment]
https://projectpokemon.org/home/files/file/2445-pkhex-development-build/ go to this link you can access your save file while waitiing on the latest fix soon
