### ISSUE TITLE
Arceus should allow Acid Spray

### ISSUE THREAD

**Issue by aaroncampbell** [kwsch/PKHeX#4003]
When creating an [Arceus raid build ](https://game8.co/games/Pokemon-Scarlet-Violet/archives/413392#hs_1) for SV, I tried to add the move Acid Spray. Adding it causes PKHex to show Invalid Move.

**To Reproduce**
Attached is a zipped .pkm file, but you can also reproduce by adding "Acid Spray" as a move to an Arceus

**Expected behavior**
Acid Spray can be added in-game via TM and shows as valid on sites like [Serebii](https://www.serebii.net/pokedex-sv/arceus/#attacks) and [pokemondb](https://pokemondb.net/pokedex/arceus#tab-moves-21)

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/802412/7baeae95-728c-4737-a10b-398ee2b8ef80)

[0493 - Arceus - CB8EE2FE77E6 - Acid Spray - Should Be Legal.zip](https://github.com/kwsch/PKHeX/files/12643035/0493.-.Arceus.-.CB8EE2FE77E6.-.Acid.Spray.-.Should.Be.Legal.zip)

**Comment by Lusamine** [comment]
TM moves need TM flags. Not a bug.
![image](https://github.com/kwsch/PKHeX/assets/30205550/0e2882b0-3299-44e5-bca6-f9976f6e5152)

**Comment by aaroncampbell** [comment]
Awesome! Learned something new and it worked like a charm. Thank you!
For anyone newer like me, the "Relearn Flags" button is what you want to click to see what is in that screenshot above
