### ISSUE TITLE
I added Ursaluna to the box with PKHeX Development Build 23.9.17+16, but it's not reflected.

### ISSUE THREAD

**Issue by miku1881** [kwsch/PKHeX#4011]
**Describe the bug**
I added Ursaluna to my box with PKHeX Development Build 23.9.17+16, but it's not reflected. I tried with other Pokémon in the box, but it didn't work.

**To Reproduce**
1. Go to 'box'
2. Added to 'Ursaluna'
3. Launch pokemon
4. Not reflected.

**Expected behavior**

**Screenshots**
Image of Pokémon added to a box with pkhex. https://imgur.com/a/P4tr9Xs 
Image confirming that the Pokémon added by pkhex are reflected.　https://imgur.com/a/9TT3DD4

**Additional context**

**Comment by miku1881** [comment]
I did the same thing with the one released on 9/16, not the pkhex Development Build, and it didn't reflect.

**Comment by Lusamine** [comment]
Works fine for others, so this is likely something you are doing wrong with exporting the save or using your emulator. Ensure that your save file and game are properly updated for any Pokémon you added. This isn't the place for us to troubleshoot emulator use, so look elsewhere for that.
