### ISSUE TITLE
Requesting

### ISSUE THREAD

**Issue by MIO1339** [kwsch/PKHeX#4012]
I'm requesting to add the new race in DLC to get shiny legal Munchlax
cause as a solo player I can't bearly to clear the race in Stage 3 above

**Comment by ReignOfComputer** [comment]
You'd need to complete Stage 3 to receive the Munchlax anyway, AFAIK. Unlocking it might just end up skipping obtaining Munchlax.

Just go on Reddit or find a Discord that pairs people up for Ogre Outsin.

**Comment by MIO1339** [comment]
> You'd need to complete Stage 3 to receive the Munchlax anyway, AFAIK. Unlocking it might just end up skipping obtaining Munchlax.
> 
> Just go on Reddit or find a Discord that pairs people up for Ogre Outsin.

ouch i use emulator only

**Comment by ReignOfComputer** [comment]
If you don't have a Switch, how did you get the game?

**Comment by MIO1339** [comment]
downloaded in site i use emulator only not modded switch

**Comment by sora10pls** [comment]
Unrelated to PKHeX.
