### ISSUE TITLE
Cloudy Mark flagged as invalid on Oni Mountain cave encounters despite cloudy weather being possible there

### ISSUE THREAD

**Issue by IAmEmber** [kwsch/PKHeX#4013]
Caught two shiny Feebas from an outbreak in the cave accessible from the Crystal Pool (which is considered part of Oni Mountain) and both had the Cloudy Mark. PKHeX says the mark is invalid, but when standing in the cave the map shows the weather is indeed cloudy (not sure how it's cloudy in a cave but that's what it says). Interestingly, despite the cave being part of Oni Mountain, the exterior part of Oni Mountain has clear weather rather than cloudy. Maybe the exterior can never be cloudy and PKHeX flags the mark because it only has one list of valid weather marks for that location? Bulbapedia says cloudy weather can occur everywhere in Paldea, but I'm not sure if that applies to Kitakami as well. Regardless, at the very least the cave itself can definitely have cloudy weather and the Cloudy Mark is valid for anything that spawns there.

[0349 ★ - Feebas - 95782E4C6434.zip](https://github.com/kwsch/PKHeX/files/12696416/0349.-.Feebas.-.95782E4C6434.zip)

![2023092120104000-B6CE40797459B0890BF7CEF68A4CE587](https://github.com/kwsch/PKHeX/assets/36805037/ab58ad09-c9d3-418f-b085-f15cbfbd148e)

**Comment by kwsch** [comment]
Weather table for mark permissions has not been updated yet for Kitakami.

https://github.com/kwsch/PKHeX/blob/703e2ed5adf19d5ff9c2a0419d2f408e82ab336c/PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterSlot9.cs#L48-L82

**Comment by kwsch** [comment]
Fixed as of https://github.com/kwsch/PKHeX/commit/f6ee2b1ffa42cc21cfee7d1c4c5b766966cea76e

Thanks for reminding me about this :)
