### ISSUE TITLE
Wild Tera Dusclops marked illegal

### ISSUE THREAD

**Issue by spacesonata** [kwsch/PKHeX#4017]
**Describe the problem**
Tera Dusclops in Timeless Woods marked as encounter type invalid in Pkhex-20230925.
[0356 - Dusclops - CE75457DF13F.zip](https://github.com/kwsch/PKHeX/files/12715055/0356.-.Dusclops.-.CE75457DF13F.zip)

**To Reproduce**
Catch the Tera Dusclops in the cave in eastern Timeless woods.

**Expected behavior**
Should be legal like the other wild tera mons.

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/86179327/46843f7a-c5e9-42a9-bf09-e151420ea932)
![image](https://github.com/kwsch/PKHeX/assets/86179327/b31a103d-8102-4111-a837-cd483deb225a)

**Additional context**
The rest listed on Serebii are fine btw

**Comment by Lusamine** [comment]
This should be fixed in https://github.com/kwsch/PKHeX/commit/17e0f1feeede4486d55aea2bbfa2a3c6c960e6ee.
