### ISSUE TITLE
Pokemon Jump and Dodorio Berry Picking

### ISSUE THREAD

**Issue by Sarutopi21** [kwsch/PKHeX#4021]
I noticed while editing my leaf green save that there is no event flag option that makes you chose that you have done 200 jumps in pokemon jump and 200 berries picked.
I cant obtain the 4 star trainer card without it.
Not sure if there is a way to do it, if yes would really like to know, otherwise would be nice to add it.

**Comment by Lusamine** [comment]
To add an editor, research must be done to know exactly what to edit. If you know exactly where and how this is stored in the save, then this can be done. Otherwise, more research is needed from the community.

**Comment by Sarutopi21** [comment]
> To add an editor, research must be done to know exactly what to edit. If you know exactly where and how this is stored in the save, then this can be done. Otherwise, more research is needed from the community.

would like to help, should be relatively easy to find. I just need to learn how to read a save file

**Comment by sora10pls** [comment]
![image](https://github.com/kwsch/PKHeX/assets/17801814/553aed84-a452-4250-b118-5ae15a1e5ed3)

**Comment by Lusamine** [comment]
If you're needing help with how to research saves in the future, you're better off going to Project Pokémon where others can help you learn. This is a repo for PKHeX after all.

https://projectpokemon.org/home/forums/forum/206-technical-discussions/
