### ISSUE TITLE
Still Having Filesize Issues

### ISSUE THREAD

**Issue by Doctor-Pokemon** [kwsch/PKHeX#4024]
I'm attempting to open my Pokémon Violet gamesave in the 9-25-2023 version of PKHeX, but it's giving me an error message about the filesize being wrong?

Since I've taken no update to the game since 9-25-2023, I figured this issue had been fixed in the 9-25-2023 PKHeX release, but I'm still having this issue.

![image](https://github.com/kwsch/PKHeX/assets/94033446/1dd826c4-3822-4af3-9e60-de2a9455b9ca)

**Comment by Lusamine** [comment]
4418716 = 0x436C9C which is way out of the range of valid save files.
https://github.com/kwsch/PKHeX/blob/8b2b858e69e3064d4236e42e98bd29e0b12de493/PKHeX.Core/Saves/Util/SaveUtil.cs#L54-L65

Probably same issue as this one: https://github.com/kwsch/PKHeX/issues/4019

Check how you are transferring the file. This is unlikely to be an issue with PKHeX.

**Comment by Doctor-Pokemon** [comment]
Thank you.
I tried a few other FTPs, as well as attempting with the original one again.
They all produced a save PKHeX could open.

I don't understand how my original transfer was inexplicably larger, but it only happened that one time.
So the transfer itself WAS, indeed the issue.
Sorry.
Thank you.
