### ISSUE TITLE
Opening a Gen9 Box/Trainer save file not working. Gives an error message

### ISSUE THREAD

**Issue by mmanlapat** [kwsch/PKHeX#4026]
**Describe the bug**
Opening a Gen9 Box/Trainer save file not working anymore. Gives an error message

**To Reproduce**
1. Open a Gen9 Box/Trainer save file. (not a *.pk9)
2. An error message will appear.
3. See error.

**Expected behavior**
Opens the save file with all Box pokemon and saved trainer data.

**Screenshots**
![ss1](https://github.com/kwsch/PKHeX/assets/5326695/34e78f59-a8c8-4520-819f-5baa30d68399)

Here is the error message
=================================================================
Exception Details:
System.Collections.Generic.KeyNotFoundException: key
   at PKHeX.Core.SCBlockAccessor.Find(IReadOnlyList`1 array, UInt32 key)
   at PKHeX.Core.SaveBlockAccessor9SV..ctor(SAV9SV sav)
   at PKHeX.Core.SAV9SV..ctor(IReadOnlyList`1 blocks)
   at PKHeX.Core.SaveUtil.GetVariantSAVInternal(Byte[] data)
   at PKHeX.Core.SaveUtil.GetVariantSAV(Byte[] data, String path)
   at PKHeX.Core.FileUtil.GetSupportedFile(Byte[] data, ReadOnlySpan`1 ext, SaveFile reference)
   at PKHeX.WinForms.Main.OpenFile(Byte[] input, String path, String ext)
   at PKHeX.WinForms.Main.OpenFromPath(String path)

Loaded Assemblies:
--------------------
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Private.CoreLib.dll

PKHeX, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\mark_\AppData\Local\Temp\.net\PKHeX\l4dJgvlfTZ4g6yE4uRXvTF1FHFN3uoQ=\PKHeX.dll

System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.dll

System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\System.Windows.Forms.dll

System.ComponentModel.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.ComponentModel.Primitives.dll

System.Windows.Forms.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\System.Windows.Forms.Primitives.dll

System.Runtime.InteropServices, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.InteropServices.dll

System.Drawing.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Drawing.Primitives.dll

System.Collections.Specialized, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Collections.Specialized.dll

System.Threading.Thread, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Threading.Thread.dll

System.Collections, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Collections.dll

System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Threading.dll

System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Diagnostics.TraceSource.dll

System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\System.Drawing.Common.dll

Microsoft.Win32.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\Microsoft.Win32.Primitives.dll

System.ComponentModel.EventBasedAsync, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.ComponentModel.EventBasedAsync.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\Accessibility.dll

System.Resources.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\System.Resources.Extensions.dll

System.Memory, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Memory.dll

System.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\System.Drawing.dll

System.Numerics.Vectors, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Numerics.Vectors.dll

PKHeX.Core, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\mark_\AppData\Local\Temp\.net\PKHeX\l4dJgvlfTZ4g6yE4uRXvTF1FHFN3uoQ=\PKHeX.Core.dll

System.Linq, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Linq.dll

Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\Microsoft.Win32.SystemEvents.dll

System.Collections.NonGeneric, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Collections.NonGeneric.dll

System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Text.Json.dll

System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Text.Encodings.Web.dll

System.Text.Encoding.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Text.Encoding.Extensions.dll

System.ComponentModel.TypeConverter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.ComponentModel.TypeConverter.dll

System.Runtime.Intrinsics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.Intrinsics.dll

System.Collections.Concurrent, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Collections.Concurrent.dll

System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.ComponentModel.dll

PKHeX.Drawing.PokeSprite, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\mark_\AppData\Local\Temp\.net\PKHeX\l4dJgvlfTZ4g6yE4uRXvTF1FHFN3uoQ=\PKHeX.Drawing.PokeSprite.dll

System.ObjectModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.ObjectModel.dll

System.Runtime.Loader, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.Loader.dll

System.Private.Uri, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Private.Uri.dll

System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Net.Http.dll

System.Net.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Net.Primitives.dll

System.Diagnostics.Tracing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Diagnostics.Tracing.dll

System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Diagnostics.DiagnosticSource.dll

System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Net.Security.dll

System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Security.Cryptography.dll

System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Net.Quic.dll

Microsoft.Win32.Registry, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\Microsoft.Win32.Registry.dll

System.Threading.ThreadPool, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Threading.ThreadPool.dll

AutoModPlugins, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null
D:\Tools\PKHex\plugins\AutoModPlugins.dll

System.Net.Sockets, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Net.Sockets.dll

System.Threading.Overlapped, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Threading.Overlapped.dll

System.Net.NameResolution, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Net.NameResolution.dll

System.IO.Compression, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.IO.Compression.dll

System.Security.Principal.Windows, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Security.Principal.Windows.dll

System.Security.Claims, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Security.Claims.dll

PKHeX.Core.Injection, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null

PokeFilename.GUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Tools\PKHex\plugins\PokeFilename.GUI.dll

System.Reflection.Emit.Lightweight, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Reflection.Emit.Lightweight.dll

System.Reflection.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Reflection.Primitives.dll

System.Reflection.Emit.ILGeneration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Reflection.Emit.ILGeneration.dll

System.Console, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Console.dll

PokeFilename.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

System.Runtime.Serialization.Formatters, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.Serialization.Formatters.dll

System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Linq.Expressions.dll

System.Runtime.Numerics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.Numerics.dll

System.Runtime.Serialization.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Runtime.Serialization.Primitives.dll

System.Data.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Data.Common.dll

System.Xml.ReaderWriter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Xml.ReaderWriter.dll

System.Private.Xml, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Private.Xml.dll

PKHeX.Core.AutoMod, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null

Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Drawing, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\mark_\AppData\Local\Temp\.net\PKHeX\l4dJgvlfTZ4g6yE4uRXvTF1FHFN3uoQ=\PKHeX.Drawing.dll

PKHeX.Drawing.Misc, Version=23.9.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\mark_\AppData\Local\Temp\.net\PKHeX\l4dJgvlfTZ4g6yE4uRXvTF1FHFN3uoQ=\PKHeX.Drawing.Misc.dll

System.Text.RegularExpressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Text.RegularExpressions.dll

System.Windows.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.11\System.Windows.Extensions.dll

System.Diagnostics.StackTrace, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Diagnostics.StackTrace.dll

System.Reflection.Metadata, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Reflection.Metadata.dll

System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Collections.Immutable.dll

System.Diagnostics.FileVersionInfo, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Diagnostics.FileVersionInfo.dll

System.Text.Encoding.CodePages, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.11\System.Text.Encoding.CodePages.dll

--------------------
User Message:
Unable to load file.
Path: D:\Tools\PKHex\Saves\Scarlet

=================================================================

Hope it gets fixed. Thank you

**Comment by Lusamine** [comment]
Can you provide an example of a "Gen9 Box/Trainer save file"?

**Comment by mmanlapat** [comment]
Hello, sorry for the late reply. I got quite busy. Here are the save files I'm using. They are working fine before I updated. Thanks
[Saves.zip](https://github.com/kwsch/PKHeX/files/12818216/Saves.zip)

**Comment by mmanlapat** [comment]
Hello again, I tried the PKHeX 23.09.25 release from "projectpokemon.org"
![Screenshot 2023-10-05 210338](https://github.com/kwsch/PKHeX/assets/5326695/51b41f2b-8a98-455c-887b-2eab41fc8aac)
And it was able to read my save file.
![Screenshot 2023-10-05 210144](https://github.com/kwsch/PKHeX/assets/5326695/ca1f48bc-fe96-4873-bdbf-8fd10fa5c22e)

**Comment by Lusamine** [comment]
The issue was that any save before SV version 2.0.1 is throwing an exception due to not being able to find the camera config block that was added. All of your saves (which are just regular save files, but for base game) would not have this save block.

This problem arose after this commit: https://github.com/kwsch/PKHeX/commit/e58a1565ad2e4d9d4e6b99c98ba751077fe6f7a8
