### ISSUE TITLE
Gen3 batch editor issue

### ISSUE THREAD

**Issue by Sarutopi21** [kwsch/PKHeX#4038]
.Gender=0  is not working, pokemons are staying all the same gender.

**Comment by sora10pls** [comment]
Working as intended, gender is a derived value in those games.

**Comment by Sarutopi21** [comment]
Hm but  i want to turn all the female ones into males but its not doing anything, i dont understand what you mean by working as intended.

**Comment by sora10pls** [comment]
In the Gen 3/4 games, a Pokémon's PID is used to determine its nature as well as its gender, amongst other things. These values are derived from the PID, and as such, can not be directly modified without also modifying the PID (which would, in most cases, make the resulting PKM become illegal).

PKHeX's batch editor does not provide a way to do this.

**Comment by Sarutopi21** [comment]
> In the Gen 3/4 games, a Pokémon's PID is used to determine its nature as well as its gender, amongst other things. These values are derived from the PID, and as such, can not be directly modified without also modifying the PID (which would, in most cases, make the resulting PKM become illegal).
> 
> PKHeX's batch editor does not provide a way to do this.

Understandable, thanks for the clarification
