### ISSUE TITLE
Using the “Complete Dex” Function in PKHeX for Pokemon Platinum Causes Sprite Errors In-Game to Appear in the Pokedex

### ISSUE THREAD

**Issue by DeadSkullzJr** [kwsch/PKHeX#4047]
**Describe the bug**
Using the "Complete Dex" function under the Pokedex save data option in PKHeX, saving said changes, and loading the newly modified save to view the Pokedex causes some of the Pokemon sprites to appear incorrectly. In emulation, at least with DeSmuME this won't yield a crash due to exception handling inaccuracies, but on genuine hardware this yields an instant game crash.

**To Reproduce**
1. Load your Pokemon: Platinum Version save file into PKHeX.
2. Head to the "SAV" tab and click the "Pokedex" option.
3. Click on the "Modify..." button, then click the "Complete Dex" option.
4. Save the changes, then export the save file.
5. Load the save file in-game and check the Pokedex, you will need to navigate through each one until you run into an invalid sprite. Multiple of these error sprites occur throughout the Pokedex.

**Expected behavior**
Using the "Complete Dex" option is supposed to yield accurate (completed) Pokedex data that won't cause issues.

**Screenshots**
https://i.imgur.com/1UDKCLr.png

**Additional context**
The error sprites are not all the same, all of them are squares but can sometimes be different colors. I have no idea if this impacts Pokemon Diamond, Pearl, HeartGold, or SoulSilver, that will likely have to be tested.

**Comment by kwsch** [comment]
If you can identify a pattern of which species are affected, would help in identifying the root cause.

Potentially related: https://github.com/kwsch/PKHeX/issues/3045 (not setting the Gender display index)

**Comment by DeadSkullzJr** [comment]
The following Pokemon seem to be impacted by this:
- Nidoran (Female)
- Nidorina
- Nidoqueen
- Chansey
- Kangaskhan
- Jynx
- Smoochum
- Miltank
- Blissey
- Illumise
- Latias
- Vespiquen
- Happiny
- Froslass
- Cresselia

The commonality between all of these Pokemon are that all of them are pure female Pokemon. Their forms are viewable in the "Forms" section of the Pokedex, but the actual sprites are colored squares. Looking at some of the data, it seems the data that makes these forms render properly aren't being set at all. The workaround would be to search for the exact Pokemon and click "Check All" to manually set the right data.

**Comment by DeadSkullzJr** [comment]
Well....It seems even using "Check All" renders issues...
https://i.imgur.com/B4MyFVB.png

It seems PKHeX sets the forms to always be male in HeartGold and SoulSilver??
