### ISSUE TITLE
Route 47 headbutt Butterfree encounter marked as illegal when encountered whilst surfing

### ISSUE THREAD

**Issue by MaxAkito** [kwsch/PKHeX#4058]
**Describe the problem**
Butterfree can be encountered on Route 47 via headbutt only a select few trees, however you can also headbutt a singular tree at the top of the waterfall, and this will provide a Butterfree with an encounter location of "water".

**To Reproduce**

PKM file is attached.
[0012 - BUTTERFREE - EB3F24CC403C.zip](https://github.com/kwsch/PKHeX/files/13304192/0012.-.BUTTERFREE.-.EB3F24CC403C.zip)

**Expected behavior**
As far as I know, this should be a legal Pokemon as I'm playing on an official cart and there should be no issue. Expected behavior should be that encounter type is NOT a mismatch.

**Screenshots**
![chrome_6sb81IItVT](https://github.com/kwsch/PKHeX/assets/10167995/e89bc950-da84-47f3-a74e-69d62aed9ba1)

**Additional context**
If any other headbutt while surfing trees exist in the games, this problem might persist for them as well.

**Comment by kwsch** [comment]
lol the headbutt permission tables are manually entered
i blame the gamefreak dev who misaligned the rocks, exposing the trees :(
