### ISSUE TITLE
Can Physical Undo/Redo Symbols/Buttons Be Added?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#406]
Is it possible to add an undo/redo button with it's symbols in the future?

**Comment by kwsch** [comment]
??????

![img](http://i.imgur.com/SoIZYro.png)

**Comment by ricksee** [comment]
@kwsch I mean like as a user interface.

**Comment by ricksee** [comment]
![image](https://cloud.githubusercontent.com/assets/21182549/20288238/d2593e86-aa9f-11e6-8cc6-13644c2675c1.png)

**Comment by kwsch** [comment]
Then no, that's too much visual clutter for a feature that shouldn't ever be used unless the user overwrites something.
