### ISSUE TITLE
Colosseum Fateful Encounter/Obedience Flag Legality 

### ISSUE THREAD

**Issue by ObedienceFlag** [kwsch/PKHeX#4072]
**Describe the bug**
For Colosseum and Colosseum only (not XD) when trading a Pokemon with the fateful encounter flag it is removed the next time the .gci save file is loaded. This is for the Fateful encounter check box/obedience flag  and not the location fateful encounter. When the Pokémon are traded back to emerald/FRLG they once again retain the fateful encounter flag. This leads me to believe that the Flag is stored differently than FRLG/Emerald/XD as they all display the Pokémon as legal. 

**To Reproduce**
1 - Trade a Faraway Island Mew/Birth island Deoxys (Any fateful encounter like wish Blissey) to Colosseum
2- Back Up the save file and load in most recent PKhex
3- Observe legality and see that the Pokémon is missing its fateful encounter flag in the Colosseum .Gci file.   

**Expected behavior**
Pokemon should have the fateful encounter checkbox checked and present as a "legal/legit" Pokemon

**Screenshots**

![Colosseum](https://github.com/kwsch/PKHeX/assets/151788400/0c3620e9-4a5e-4cce-a684-9efe6fbf8fbd)

![XD](https://github.com/kwsch/PKHeX/assets/151788400/7a52e6ea-f67f-4eaf-8890-d4fdfe2bd439)

**Additional context**
I believe the flag is stored elsewhere in the Pokemon data substructure compared to other games.

**Comment by kwsch** [comment]
We tried to replicate and were unable to observe the behavior you've noted. We've tested on Ruby/Sapphire as well as Emerald, trading into Colosseum and back, and the fateful encounter flags matched what we expected.
1. Torchic with & without fateful.
2. Deoxys with & without fateful.
3. Mew with & without fateful.

If you can provide the before & after files as well as an exact replication setup (game, patch, etc), we can try to replicate on our end here; but we don't think PKHeX is wrong based on our tests.

**Comment by kwsch** [comment]
Looks like English behaves differently (has better legality checks?)
