### ISSUE TITLE
Allow codes in fields

### ISSUE THREAD

**Issue by drvictorvs** [kwsch/PKHeX#4078]
**Is your feature request related to a problem? Please describe.**
Sort of, in the sense that it's not currently possible to set custom data (e.g., custom Pokémon manually added). It's not a problem anyone using PKHeX for its intended purpose in its intended games would have, except maybe for researching the role of undocumented codes (e.g., form 1 mega evolutions).

**Describe the solution you'd like**
I would like for there to be a "developer option" that allows directly typing the value I want into most fields where that makes sense: Species, Moves, Abilities and Form come to mind. Obviously, that would be in the form of an int.

**Describe alternatives you've considered**
Honestly, outside of the one thing I haven't tried, which is to manually input that data into a .pk* file, the only solution is manually editing the save file. The thing I'm asking is actually outside the scope of PKHeX, so I find it completely understandable to be denied. If I had the resources I'd try to implement it myself.

**Additional context**
I think it's pretty clear to any dev why that's desirable. For all the hatred that SV get, I'm genuinely impressed at how flexible it is (and, frankly, it's no wonder it had so many bugs).

**Comment by sora10pls** [comment]
The batch editor already lets you assign any values to a given property to a number of pkm files at a time. In your use case, you could do the following:
```
.Species=6
.Form=2
.Ability=11
.Move1=656
.Move2=709
```
The above would give you a custom Mega Charizard Y with Water Absorb for its ability, with the moves Twinkle Tackle and Accelerock.

If you wish to do this strictly with the GUI, PKHeX has a built-in HaX mode (see startup settings) that allows you to enter in illegal values that the main GUI usually disallows. Outside of what PKHeX already provides, I personally do not see much need in adding other means to create significantly hacked Pokémon.

**Comment by kwsch** [comment]
Can also use things like LINQPad to mutate/create Pokémon via PKHeX.Core, which is a far superior experience compared to the batch editor.

Closing, as the GUI already has HaX to show form ID, and the batch editor can set values directly to slots as Matt has described.
