### ISSUE TITLE
Event Flag (Received Gift Cosmog)

### ISSUE THREAD

**Issue by sharpedit** [kwsch/PKHeX#409]
I haven't received Cosmog from Lake of Moone yet and I was looking at some of the event flags. On my save file, the event flag is checked "Received Gift Cosmog". I hadn't claimed the Cosmog at this point while inspecting my save file. Why is the event checked by default unless that means it's safe to claim the Cosmog without messing with the storyline/events?

**Comment by SciresM** [comment]
The flag is probably used for other things, too. Unsetting it causes the cosmog entity to show up in the relevant map -- it's also possible it's not "Received Cosmog Gift" but "Prevent Cosmog Entity from Showing On Map".

Either way, it should be totally safe. Just don't touch it until you've actually received cosmog.
