### ISSUE TITLE
Incorrect illegal move warning: Pokemon Crystal/Marill/Bubble Beam

### ISSUE THREAD

**Issue by Velkorious** [kwsch/PKHeX#4097]
**Describe the bug**
Marills being caught on the first floor of Mt. Mortar via surfing on an unmodified Pokemon Crystal game are being incorrectly flagged as illegal due to knowing the move Bubble Beam.

**To Reproduce**
In Pokemon Crystal, surf around inside the middle entrance of Mt. Mortar and catch a Marill at level 22 or higher.
It will know Bubble Beam.
Save the game and open it up in PKHex. The Marill is flagged as illegal due to Bubble Beam.

I think this may be because Marills in Mt. Mortar  [can be caught at level 20-24 (Generation 2 - 1F South - Surfing)](https://pokemondb.net/location/johto-mt-mortar). But they only [learn Bubble Beam at level 21](https://pokemondb.net/pokedex/marill/moves/2). So perhaps PKHex incorrectly assumes all of them can't learn Bubble Beam at this level?

**Expected behavior**
Bubble Beam shouldn't be flagged as an illegal move.

**Screenshots**
<img width="432" alt="marill1" src="https://github.com/kwsch/PKHeX/assets/153449508/7290a204-c7bf-4e02-a497-693a3ea5fd5f">
<img width="434" alt="marill2" src="https://github.com/kwsch/PKHeX/assets/153449508/4a9f4526-0b9d-4b53-90a7-45f8a6dd2755">

**Comment by kwsch** [comment]
Try the latest dev build. Should already be fixed.

https://github.com/kwsch/PKHeX/issues/4046

**Comment by Velkorious** [comment]
Dang I didn't think something this specific and obscure would be noticed by anyone else since the previous release. Made sure I had the latest release build and everything too first...

Tried doing a build, and yep it's fixed. Thanks for the prompt reply, but yeah this isn't an issue anymore.
