### ISSUE TITLE
BDSP Items not being loaded properly

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#4099]
**Describe the bug**
I was able to replicate this in stable and dev builds of PKHeX, including going back to 22.05.08 PKHeX. The when opening the Items editor, the program only displays a small handful of items, specifically only the ones that have recently changed values (amount of items changed, new item obtained, etc). The rest of the bag appears empty, regardless of what appears ingame.
[SaveData.zip](https://github.com/kwsch/PKHeX/files/13629493/SaveData.zip)

**Screenshots**
Example, using 3 Rare Candy in-game causes them to appear in PKHeX as the amount of Rare Candy changed, but the entire rest of the bag appears empty to the program, despite the fact it is actually full of items in-game.
![2023121015395800-7F4AACC644EAC4BF4E5897B413FFD611](https://github.com/kwsch/PKHeX/assets/39707481/b57455b4-b799-4a64-9599-8dfe14a1e864)
![Capture](https://github.com/kwsch/PKHeX/assets/39707481/288081aa-8dc4-48af-ade0-846f52017e42)

**Additional context**
No cheats codes were used on this savefile, to my memory, the only time it has been edited is to grant myself additional items, which was done in PKHeX. I'm not sure what the cause is, as it affects backups of my savefile reaching all the way back to shortly after I began the savefile on SP v1.1.0, and I don't remember this occurring in older versions of PKHeX (older than 22.05.08 at the very least)

**Comment by Atrius97** [comment]
I also appear to be missing some items, it's as if at some point my bag was reverted to an earlier state. As an example, I legitimately acquired the Azure Flute, and caught Arceus on this savefile. The Azure Flute no longer appears to be in my bag, and I confirmed it isn't supposed to vanish after use.

**Comment by Lusamine** [comment]
Did you ever use LiveHeX to modify your bag in BDSP?

**Comment by Lusamine** [comment]
Yes, it was a known issue where LiveHeX wasn't writing the bag correctly in early BSDP, so the bag would appear empty in PKHeX. Should be documented in the general-pkhex channel on Discord. I'm unsure if using the updated version of LiveHeX will fix it but it was determined at the time not to be a PKHeX issue.

**Comment by Atrius97** [comment]
Updated Livehex appears to have the same issue, I'll just import uncorrupt bag data from a different savefile.
Was unsure of the cause but if it wasn't PKHeX, and PKHeX can't be made to recognize/fix the corrupt bag data, seems safe to close this issue.
