### ISSUE TITLE
Use Ctrl + X as cut, not closing application.

### ISSUE THREAD

**Issue by forsureitsme** [kwsch/PKHeX#41]
I'm not sure if it's a bug or feature, but everytime I do CTRL+X when changing EVs the program closes itself without any warning or confirm dialog asking if I want to save, and this gets me really frustrated,

**Comment by kwsch** [comment]
Fixed in latest commit.
https://github.com/kwsch/PKHeX/commit/f5917c031921fa3d317506e41d911d622b9efab4

Thanks for bringing this to my attention!
