### ISSUE TITLE
SUMO  Ash-Greninja is marked as Illegal, same with lycanrock

### ISSUE THREAD

**Issue by addi33** [kwsch/PKHeX#410]
They´re both marked as illegal, I know that the legality check dosn´t work that good for greninja but lycanrock is also marked as illegal so please fix this

**Comment by Orionsilver** [comment]
i do not have yet the game and i have friends tell the location and they show and i make one and i check the legality check it is thick for and legit for me 


[745 ★ - Lycanroc both Version Exclusive is legit.zip](https://github.com/kwsch/PKHeX/files/592350/745.-.Lycanroc.both.Version.Exclusive.is.legit.zip)

**Comment by addi33** [comment]
could you actually explain what you mean? Im confused

Am 15.11.2016 16:23 schrieb "Orionsilver" <notifications@github.com>:
