### ISSUE TITLE
Save file size for S/V 3.0.0 / DLC 2

### ISSUE THREAD

**Issue by TheBrain0110** [kwsch/PKHeX#4107]
With the new 3.0.0 Release of Scarlet / Violet with the new DLC part 2, there's a new save file size.

`4435286 bytes`

That's for my Violet save I just tested. It also includes the "new clothes" DLC bundled, in case that matters.

**Comment by ReignOfComputer** [comment]
https://github.com/kwsch/PKHeX/issues/4104

Not a "bug".

**Comment by TheBrain0110** [comment]
Well, more just giving the size of my file, in case they didn't already have it. Just making sure it gets added to the list.

**Comment by nhutminh9799** [comment]
Same thing happened to me! I hope there will be a PkHex update soon

**Comment by Vanir-Labs** [comment]
Haing same issue. I restored old save and entered DLC and it changed file size. This several times. Don't think this is a mistake. There is a new file size on my end for sure.

**Comment by Darth-Cthoras** [comment]
Same thing's happening on my end. Posted my results, waiting on a PkHex update. This program's been a lifesaver for years, I'd hate to see this be what kills it.

**Comment by Alexa-RR** [comment]
hi, I am still not able to open my save file after updating PkHex to the latest version, am I opening the right file?
<img width="996" alt="image" src="https://github.com/kwsch/PKHeX/assets/53471801/14a0da16-fdad-40bf-ace7-85a87ab9d77b">

**Comment by kwsch** [comment]
Your save file size is too small. Assuming you're dumping via FTP, fix your transfer mode.

**Comment by Alexa-RR** [comment]
> Your save file size is too small. Assuming you're dumping via FTP, fix your transfer mode.

I didn't know there was an issue using ftp, after using USB it worked, thanks so much for your help <3
