### ISSUE TITLE
[Gen6 Ninjask/Shedinja] Invalid: EC sharing for 3DS-onward origin detected.

### ISSUE THREAD

**Issue by diogofd8** [kwsch/PKHeX#4110]
**Describe the bug**
The legality report for all pokémon on the SAV tab accuses a Ninjask and Shedinja of being invalid by sharing the PID and the EC. Originally I had them hacked so I thought that perhaps they wouldn't share PID and EC in this generation so I went on the physical copy of OR, caugh a Nincada and let it evolve. The PID and EC were the same and I believe the algorithim to check for legality of the whole save is not taking into consideration that those two are meant to be clones.

**Comment by Lusamine** [comment]
Not intended to be a robust check; human checks the flags themselves.

Pretty much the same issue here:
https://github.com/kwsch/PKHeX/issues/4048#issuecomment-1786231582
