### ISSUE TITLE
Encounter Database Terastal Error

### ISSUE THREAD

**Issue by leafeon012** [kwsch/PKHeX#4113]
![스크린샷 2023-12-18 135807](https://github.com/kwsch/PKHeX/assets/77223325/9849b72d-5e35-476d-b454-6ee7042ea090)
This is a Pokémon that set on PKMEditor first.

![스크린샷 2023-12-18 135833](https://github.com/kwsch/PKHeX/assets/77223325/1809bc89-ca0e-4edf-b6c5-581160dfacf9)
If later load a Pokémon from the Encounter database, there is an error that overrrides the previously loaded Pokémon's Terrastal type.

**Comment by kwsch** [comment]
Works as intended; the `SetTabsFromCriteria` setting should be disabled if you don't want this kind of behavior.
