### ISSUE TITLE
Legality: Dewgong / Minior from Terarium

### ISSUE THREAD

**Issue by lithiumjs** [kwsch/PKHeX#4114]
**Describe the problem**
Dewgong and Minior legitimately caught in the Terarium do not pass the legality check.

**To Reproduce**
PK9 files here: [Dewgong](https://cdn.discordapp.com/attachments/1131776700435411007/1186173349060149248/0087_-_Dewgong_-_E87A47F6CAF3.pk9?ex=65924904&is=657fd404&hm=f00eb0e93e05bc06415e11084e373a3bada5af3ffafa052325787c84bd42629f&), [Minior](https://cdn.discordapp.com/attachments/1131776700435411007/1186173349416681493/0774-09_-_Minior_-_C7AE72C52078.pk9?ex=65924904&is=657fd404&hm=8dc34308beab303709cc79be53af7a125d33bfd33056ca3b3ecd5018d53e9b14&)
Both were caught in the Terarium, in Polar Biome and Chargestone Cavern respectively.

**Expected behavior**
These Pokémon should pass legality check.

**Comment by kwsch** [comment]
Per the latest release changelog:

https://github.com/kwsch/PKHeX/blob/f2419db0929a921158832b3db7ed33c2e6891c28/PKHeX.WinForms/Resources/text/changelog.txt#L10

We're aware of this issue; we wanted to get a release out, knowing there are issues with encounter recognition. Minior needs to be set to FormRandom in the pkNX export, and some encounters are not being emitted into the list of possible encounters.

Leaving this open until we have time to audit for errors in our pkNX dumper.

**Comment by kwsch** [comment]
Fixed by https://github.com/kwsch/PKHeX/commit/d4eccd92ca3dd02d2bd8d2047778bd851a6ba342
