### ISSUE TITLE
is marking a lot of legal illegal for oras

### ISSUE THREAD

**Issue by Dandy562** [kwsch/PKHeX#412]
with the new build, when i load my alpha saphire save file, a lot of pokemon that i collected auslove, is making them illegal most of the for the pokeball and some for the moves,  i dont know if somebody else already summit this problem.

**Comment by sora10pls** [comment]
"most of the for the pokeball"

AuSLove puts **all** of his Pokemon in Love Balls, and more than half of them were never legal to begin with (i.e. a Kalos Pokemon in a Love Ball was never legal in Gen 6).

**Comment by kwsch** [comment]
Closing, hacks be hacks.
