### ISSUE TITLE
Word filter issue with trainer Name

### ISSUE THREAD

**Issue by Zoromark** [kwsch/PKHeX#4121]
**Describe the bug**
This is a legit Espurr caught, and the trainer name has not been modified, it has been checked by the in game profanity filter and not been reported.

**To Reproduce**

[0677 - Espurr - 91DD6A0FF9B8.zip](https://github.com/kwsch/PKHeX/files/13722725/0677.-.Espurr.-.91DD6A0FF9B8.zip)

**Expected behavior**
The game has not blocked the trainer name "Sobek" so it shouldn't be flagged as illegal.

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/154398064/f41807c9-a025-4150-a371-5d41e4039625)

**Additional context**
Game language is English

**Comment by sora10pls** [comment]
Duplicate #3620 

PKHeX uses a superset of the 3DS/Switch bad words lists, and is more strict than the actual games. Working as intended.
