### ISSUE TITLE
Batch Editor can‘t edit one of the box

### ISSUE THREAD

**Issue by a375891918** [kwsch/PKHeX#4129]
**Describe the bug**
when i use this code,it changes all of the boxes, i cant only change the box number 1
=Box=1
.OT_Name=XXX
.OT_Gender=1
.DisplaySID=XXXX
.DisplayTID=XXXXXX
.Language=9
.Ball=26

![M5~OG(GSCE`VD9XOPK9W`(L](https://github.com/kwsch/PKHeX/assets/64283166/18cc8b49-dec0-4929-8860-11cdcee56711)

**Comment by sora10pls** [comment]
Unable to replicate
![image](https://github.com/kwsch/PKHeX/assets/17801814/58a33e83-8572-4ed2-ba87-9569d80044c2)
