### ISSUE TITLE
Add scale column to Box Data Report for Gen 9

### ISSUE THREAD

**Issue by pofehof** [kwsch/PKHeX#4132]
**Is your feature request related to a problem? Please describe.**
Box Data Report is great for outputting to a .csv file, but I would like to see a column for scale as well so I can quickly see which Pokemon is at minimum or maximum size.

**Describe the solution you'd like**
If possible, add a column for scale.

**Comment by sora10pls** [comment]
Duplicate https://github.com/kwsch/PKHeX/issues/3799

There are far more games without height/weight than there are with it.
