### ISSUE TITLE
Choosing a Nature for a Mon keeps switching to a random one instead

### ISSUE THREAD

**Issue by esfanlock52** [kwsch/PKHeX#4134]
**Describe the bug**
Anytime I try to change the nature of a Pokemon I'm building, it switches to a random one instead. I want Bold for this Mon and yet even type I choose it in the drop down menu or type it in with the autofill or even type it in fully, it switches to another random nature.

**To Reproduce**
[Already explained]

PS - An older version of PKHex that I still use 22.09.13 doesn't have this issue

**Comment by Lusamine** [comment]
Please be more specific. What game are you having this issue in?

**Comment by esfanlock52** [comment]
> Please be more specific. What game are you having this issue in?

Sorry. Forgot about that.

Game: Pokemon Platinum (USA) (Rev 1)

**Comment by Lusamine** [comment]
I suspect you are running into PIDIV correlation, but your description is not enough to replicate the issue. Here I am simply changing the nature and it changes to what I requested, even if I type it in.

![nature platinum](https://github.com/kwsch/PKHeX/assets/30205550/c6f4bcd3-e05d-49c1-9176-926d25500367)

Can you please be more specific and explain how to replicate the issue?

**Comment by esfanlock52** [comment]
It works properly sometimes but I don't know what's going on to be honest

![ezgif com-optimize](https://github.com/kwsch/PKHeX/assets/151974752/0e64b063-863b-4e6c-aca3-ab87d51371bd)

**Comment by Lusamine** [comment]
You may need to supply the exact Pokémon that is affected. I picked a random one from Encounter DB and it lets me change the nature properly.

Here's a guide to fixing PID mismatch in gen 4 if it's a specific encounter that's being corrected:
https://projectpokemon.org/home/tutorials/save-editing/using-pkhex/pid-mismatch-origin-game-dppt-hgss-r95/

I used ScreenToGIF to capture one window.

**Comment by esfanlock52** [comment]
Set up an Aipom just like you and it still happens

![Animation](https://github.com/kwsch/PKHeX/assets/151974752/8685065a-18f2-4fab-b89e-9193872f8498)
