### ISSUE TITLE
Lack of Sevii Island locations from Firered/leafgreen

### ISSUE THREAD

**Issue by Lord-Xanthus** [kwsch/PKHeX#4139]
**Describe the problem**
Lack of Sevii Island locations from Firered/leafgreen
A perfect example is Sevault Canyon, the only location in generation 3 you can legitimately catch a Larvitar https://bulbapedia.bulbagarden.net/wiki/Sevault_Canyon < link to the actual route on bulbapedia for proof this is an area.

This isn't just a the program doesn't accept is as a valid location, the application doesn't accept the location as a location.

**To Reproduce**
Try to set the met Location as Sevault canyon

**Expected behavior**
to be a location that is recognised by the application

**Screenshots**
easy to reproduce, no need for screenshot

**Additional context**
After checking a few of the sevii islands locations, PKHeX is missing all the sevii island locations.
Here is a list of locations and links to their bulbapedia page.

[Treasure Beach](https://bulbapedia.bulbagarden.net/wiki/Treasure_Beach)
[Kindle Road](https://bulbapedia.bulbagarden.net/wiki/Kindle_Road)
[Mt. Ember](https://bulbapedia.bulbagarden.net/wiki/Mt._Ember)

[Cape Brink](https://bulbapedia.bulbagarden.net/wiki/Cape_Brink)

[Three Isle Port](https://bulbapedia.bulbagarden.net/wiki/Three_Isle_Port)
[Three Isle Path](https://bulbapedia.bulbagarden.net/wiki/Three_Isle_Path)
[Bond Bridge](https://bulbapedia.bulbagarden.net/wiki/Bond_Bridge)
[Berry Forest](https://bulbapedia.bulbagarden.net/wiki/Berry_Forest)

[Icefall Cave](https://bulbapedia.bulbagarden.net/wiki/Icefall_Cave)

[Water Labyrinth](https://bulbapedia.bulbagarden.net/wiki/Water_Labyrinth)
[Resort Gorgeous](https://bulbapedia.bulbagarden.net/wiki/Resort_Gorgeous)
[Lost Cave](https://bulbapedia.bulbagarden.net/wiki/Lost_Cave)
[Five Isle Meadow](https://bulbapedia.bulbagarden.net/wiki/Five_Isle_Meadow)
[Rocket Warehouse](https://bulbapedia.bulbagarden.net/wiki/Rocket_Warehouse)
[Memorial Pillar](https://bulbapedia.bulbagarden.net/wiki/Memorial_Pillar)

[Water Path](https://bulbapedia.bulbagarden.net/wiki/Water_Path)
[Pattern Bush](https://bulbapedia.bulbagarden.net/wiki/Pattern_Bush)
[Green Path](https://bulbapedia.bulbagarden.net/wiki/Green_Path)
[Outcast Island](https://bulbapedia.bulbagarden.net/wiki/Outcast_Island)
[Altering Cave](https://bulbapedia.bulbagarden.net/wiki/Altering_Cave)
[Ruin Valley](https://bulbapedia.bulbagarden.net/wiki/Ruin_Valley)
[Dotted Hole](https://bulbapedia.bulbagarden.net/wiki/Dotted_Hole)

[Trainer Tower](https://bulbapedia.bulbagarden.net/wiki/Trainer_Tower)
[Canyon Entrance](https://bulbapedia.bulbagarden.net/wiki/Canyon_Entrance)
[Sevault Canyon](https://bulbapedia.bulbagarden.net/wiki/Sevault_Canyon)
[Tanoby Key](https://bulbapedia.bulbagarden.net/wiki/Tanoby_Key)
[Tanoby Ruins](https://bulbapedia.bulbagarden.net/wiki/Tanoby_Ruins)
[Tanoby Chambers](https://bulbapedia.bulbagarden.net/wiki/Tanoby_Chambers)
[Navel Rock](https://bulbapedia.bulbagarden.net/wiki/Navel_Rock)
[Birth Island](https://bulbapedia.bulbagarden.net/wiki/Birth_Island)

**Comment by ReignOfComputer** [comment]
What are you seeing?

![image](https://github.com/kwsch/PKHeX/assets/2667537/e1aaaf82-d412-47f4-867d-beab8cbbb979)

![image](https://github.com/kwsch/PKHeX/assets/2667537/1cae46a6-596a-4a10-8cc2-56d35af4968c)
