### ISSUE TITLE
PKHEX 12/22 release version shows some egg moves as legal despite what serebii or pokemondb state

### ISSUE THREAD

**Issue by k20stitch** [kwsch/PKHeX#4145]
**Describe the bug**
I'm not really sure if this issue is with PKHEX or if the issue is with the sites like pokemondb and serebii, it is my understanding that solar beam is not an egg move.
https://pokemondb.net/pokedex/bulbasaur/moves/9
https://www.serebii.net/attackdex-sv/solarbeam.shtml

Yet,
![image](https://github.com/kwsch/PKHeX/assets/25312232/9a393c24-9348-4cf8-9b72-b74ad98de0c6)

**To Reproduce**
Create a Bulbasaur from the egg encounter. Click "is egg". add Solar Beam as Third Move.
Suggest Relearn Moves
Check legality.

**Comment by Lusamine** [comment]
Solar Beam can be learned by Bulbasaur.
Breed with both parents knowing Solar Beam and the egg will have it too.
Not a bug, that's how eggs work.

See the second bullet here: https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_breeding#Passing_moves_down
