### ISSUE TITLE
Bulk Edit Hyper Training

### ISSUE THREAD

**Issue by pineapple21** [kwsch/PKHeX#4157]
Using Batch Edit .HyperTrainFlags=$suggest and right clicking Box tab -> Modify -> Shift click Hyper Train are both not performing as expected. Neither of them are actually putting any hyper training flags onto any Pokemon. Though there's definitely room for user error. I have tried several different ways and tests and cannot get it working. 

I am using a Scarlet save.
1. Use encounter database to select Pikachu that has the level 15 encounter in Apple Hills.
2. CTRL+ALT click open spot in box to clone Pikachu to entire box
3. Use batch edit ".IVs=$rand" to randomize all IVs across all Pikachus (not really needed but I wanted to see if it was working in some cases and not all)
4. Try both batch edit ".HyperTrainFlags=$suggest" or by right clicking on the Box tab -> modify -> (Shift Click) Hyper Train

Any IV that is not 31 should be highlighted green and shows that it is hyper trained but they are not. I assume that there is a way to do it as the PKHeX-Plugin (ALM) can generate living dexes that have hyper training. 

For reference, there was a commit a while ago for this so I am not sure why I can't get this working. [Commit](https://github.com/kwsch/PKHeX/commit/07133e22fd63359dcac075ec8e5630bb11a7802a)
This code seems to have be consolidated somewhere else and this was for pkm format < 7. 

I also looked at these files below and it does look like this $suggest for Hyper Training is in there. Maybe there is a new way to do it?
PKHeX.Core/Editing/Bulk/BatchEditing.cs
PKHeX.Core/Editing/Bulk/BatchMods.cs
[PKHeX Batch Edit Info](https://projectpokemon.org/home/tutorials/save-editing/using-pkhex/how-to-use-the-batch-editor-in-pkhex-r77/) (Hyper Training not updated here but I did check)
A few forums from google searching also yielded no results for me. 

Please let me know if I'm just being dumb :)

**Comment by kwsch** [comment]
Can't hyper train until at least level 50 in S/V.

**Comment by pineapple21** [comment]
I feel dumb now. I definitely knew that. Thanks XD
