### ISSUE TITLE
Improvement Request, Bag Sorting

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#416]
An ability to sort bag items by Name or Count would be nice

**Comment by evandixon** [comment]
Should be pretty easy to do by Count or Name.  I could do this myself later.

(I haven't checked in a while.)  Does anyone know how the game sorts them?  It's probably by name, but I'm double checking since I focus more on Mystery Dungeon, which has a special order for items.

**Comment by sora10pls** [comment]
You're given multiple methods for sorting. There's:

- By Type (not for TMs/HMs)
- By Number (TMs/HMs only)
- By Name
- From Most (not for TMs/Hms or Key Items)
- From Fewest (not for TMs/HMs or Key Items)
- +NEW (Sun/Moon only; sorts Items from newest to oldest)

For sorting in Black/White, it was automatically By Type (and By Number for TMs/HMs); I am unsure of what sorting methods are available for Black 2/White 2 as I don't have the games on me right now.

**Comment by kwsch** [comment]
Basically would just need to set pouch and do an OrderBy(item => Array.IndexOf(itemlist, item.ID) or OrderByDescending(item => item.Count)

Sorting by type would require adding the item info files from the ROM; kinda a little excessive / bloaty. Sorting alphabetically or numerically should be sufficient for whatever edits they are trying to do.

**Comment by Ninjistix** [comment]
alphabetically would be great

**Comment by evandixon** [comment]
I added sorting by count and name, and I think that should cover most everything.

I took care to ensure all the `(None)`'s were at the end.  I didn't even consider that until it happened.  I'd imagine that would erase all items in the inventory, but I didn't exactly test for that.
