### ISSUE TITLE
Fateful Encounter Flag is required for PCNY Wish Eggs

### ISSUE THREAD

**Issue by notblisy** [kwsch/PKHeX#4161]
**Describe the problem**
I have a legal PCNY Wish Chansey that PKHeX is flagging as Illegal because it's missing the "Fateful Encounter" flag. However, eggs hatched in Ruby & Sapphire that contain the Fateful Encounter flag lose it upon hatch. I traded my Wish Chansey as an egg to RS to hatch it shiny, so it doesn't have the flag. 

As a reminder, PCNY Wish Pokemon were distributed as Eggs, and it's not uncommon to trade them to other games to hatch them shiny. 

This is also documented in PRET as how the games behave. 

**To Reproduce**
Here are a PK3 and PK4 of the Wish Chansey in question. In gen 4 it's evolved and EV Trained, but that doesn't effect the issue at hand. They're in Zip because github won't let me upload pk3/pk4 files. I haven't traded it up further, so I'm unaware if the legality is incorrect into gen 5+.
[Wish Blissey.zip](https://github.com/kwsch/PKHeX/files/13933175/Wish.Blissey.zip)

All you have to do to fix legality is set the fateful flag. However, if you set the flag, turn it into an egg, and then hatch in R/S(or just download any wish egg and hatch in rs) you'll see the flag is deleted. 

**Expected behavior**
Fateful Encounter Egg Events with Met Locations in Hoenn areas should not require the flag set to be considered legal, unless it's an Emerald exclusive location, because Emerald keeps the Fateful Encounter flag on hatch. All FRLG Hatch locations should be required to have fateful still

**Screenshots**
[Screenshot of issue, with link to pret line. ](https://github.com/pret/pokeemerald/blob/6c96641035099db8a2c1e680fb8793f1b29cf2fd/include/pokemon.h#L170C8-L170C8)
![Screenshot 2024-01-14 163008](https://github.com/kwsch/PKHeX/assets/50887637/ad3bba83-87c0-4107-837a-a9f56f24e5ca)

**Comment by kwsch** [comment]
Already known and working as you've described, it just currently hard-matches on the fateful for everything (including eggs) even though there's a later check.
