### ISSUE TITLE
Clear all boxes not working 

### ISSUE THREAD

**Issue by Sarutopi21** [kwsch/PKHeX#4168]
Hi, after the newest build the clear all boxes option doesnt work anymore.

**Comment by Lusamine** [comment]
![clear boxes](https://github.com/kwsch/PKHeX/assets/30205550/e5d626cc-43fd-422f-9967-ab9b05819562)
Worked fine for me. Can you explain what you are doing exactly for it to not work?

**Comment by Sarutopi21** [comment]
my bad, i was holding crtl+shift, even if it says clear all boxes it wasnt clearing them.

**Comment by Lusamine** [comment]
Ctrl+shift+left clicking the box tab will sort all boxes, not clear all boxes.

You only need to hold shift if you are right clicking and navigating the menu to click "Clear" to clear all boxes.
![image](https://github.com/kwsch/PKHeX/assets/30205550/55ab242f-5e31-4531-a23d-39379e9ba435)

I see that you're using ctrl+shift and navigating the menu, which is giving the "clear" popup and doing nothing.
