### ISSUE TITLE
Setting a Country/Sub Region on ORAS doesn't persist

### ISSUE THREAD

**Issue by Sad-theFaceless** [kwsch/PKHeX#4170]
Hello! I'm not sure if this is intended, so I'm reporting this to be sure.

I play Alpha Sapphire on Citra, my 3DS Region is set to Europe in the config files, and my Pokémon game(s) detect it correctly (as shown in the screenshot below).

However, when I check my Pokémons' OT/Misc informations with PkHeX, I have the following:
![image](https://github.com/kwsch/PKHeX/assets/21340420/215139db-317a-4cd8-b2f4-30a6e040fbda)
So I obviously have this nice error on all my Pokémons:
![image](https://github.com/kwsch/PKHeX/assets/21340420/fa98490e-0657-4572-b2c5-a19ed8edc9ac)

I then proceed to batch edit everything to set them to the right country and remove the sub region. **BUT** I want to avoid having to do that every time I catch a Pokémon, so my save doesn't depend of PKHeX to have valid data.
Fortunately, there is this handy setting within PKHeX, aka the "Trainer Data Editor", where I could change my Country to the right one and remove the wrong Sub Region as well, I also change the Vivillon to the one I'm supposed to have:
![image](https://github.com/kwsch/PKHeX/assets/21340420/fb58e0b1-e32f-4d21-99d7-1a78c042c50e)

Life is good, I replace my save with this, I re-open it to verify the right Trainer Data is still there, and it is. PKHeX is trusting this data saved correctly. From now on, every Pokémon I catch should have the right Country, right ?

I launch the game, save without doing anything, open the save in PKHeX to verify everything is still good, but then:
![image](https://github.com/kwsch/PKHeX/assets/21340420/a03b919b-445a-42a6-adc5-810762e598ce)
The Country and Sub Region were back to the wrong ones. I am, once again, living in the District of Columbia. (the correct Vivillon stayed, though)

I tried with a new save file, and the issue persists as the save is set with the wrong Country/Sub Region from the very start. The only thing I do is selecting the "English" language when the game launches.

Is this because PKHeX doesn't set those values properly ?

Thanks for your help.

**Comment by kwsch** [comment]
Emulator issue. Not PKHeX.

**Comment by Sad-theFaceless** [comment]
Indeed. For those having my issue:
The Citra core doesn't offer any setting to set up a Country and Sub Region, which means you'll always be on USA, District of Columbia, when you use RetroArch.

However, with the standalone/regular Citra, you can change your Country in your System setting. You still can't change your Sub Region there, so is set to a default one depending of the country.

There is a workaround to set the correct Sub Region: if you download the System Files, you can boot on the emulated 3DS menu.
From there, go to **Other Settings** > **Profile** > **Region Settings** > Select your Country, then your Sub Region (you can scroll up to put "Do not set". The country might still be displayed wrong, but as long as the one set inside Citra's System settings is correct, it will work regardless. Exit everything, boot your game, and from now one everything should be good.
Credits to https://projectpokemon.org/home/forums/topic/60925-gen-7-3ds-sub-region-and-legality/?do=findComment&comment=274715

To make it work on RetroArch Citra from Steam, copy this file from the standalone Citra after you've done the manipulation above:
`%AppData%\Citra\nand\data\00000000000000000000000000000000\sysdata\00010017\00000000\config`
And paste it under
`C:\Program Files (x86)\Steam\steamapps\common\RetroArch\saves\Citra\nand\data\00000000000000000000000000000000\sysdata\00010017\00000000`
This should replace the config file already present, and your Pokémon game will not have the correct (and persistent) country & sub region!
