### ISSUE TITLE
please post binary version build with net 7 and not net 8

### ISSUE THREAD

**Issue by amidevous** [kwsch/PKHeX#4171]
please post binary PKHeX.exe version build with net 7 and not net 8

net 7 work for windows 7,8, 10, 11 and Linux and Mac OSX with wine and winestrick

winetricks -q --force 'dotnetdesktop7'

wine "/usr/share/pkhex/PKHeX.exe"

net 8 version work online windows 11

please post net 7 version binary build

**Comment by kwsch** [comment]
PKHeX uses .NET 8 as of last month. The program uses features only available on .NET 8.

If you are using wine to run the program, you will have to update wine.

**Comment by amidevous** [comment]
net 8 not found and not work on wine

winetricks -q --force 'dotnetdesktop8'
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20240105-next - sha256sum: cd868b5357fc4d22a0c811687280759fb4575ab7e3687da5ab972c66c9614d76 with wine-9.0 (Staging) and WINEARCH=win64
Unknown arg dotnetdesktop8
Usage: /usr/bin/winetricks [options] [command|verb|path-to-verb] ...
Executes given verbs.  Each verb installs an application or changes a setting.

Options:
    --country=CC      Set country code to CC and don't detect your IP address
-f, --force           Don't check whether packages were already installed
    --gui             Show gui diagnostics even when driven by commandline
    --gui=OPT         Set OPT to kdialog or zenity to override GUI engine
    --isolate         Install each app or game in its own bottle (WINEPREFIX)
    --self-update     Update this application to the last version
    --update-rollback Rollback the last self update
-k, --keep_isos       Cache isos (allows later installation without disc)
    --no-clean        Don't delete temp directories (useful during debugging)
    --optin           Opt in to reporting which verbs you use to the Winetricks maintainers
    --optout          Opt out of reporting which verbs you use to the Winetricks maintainers
-q, --unattended      Don't ask any questions, just install automatically
-r, --ddrescue        Retry hard when caching scratched discs
-t  --torify          Run downloads under torify, if available
    --verify          Run (automated) GUI tests for verbs, if available
-v, --verbose         Echo all commands as they are executed
-h, --help            Display this message and exit
-V, --version         Display version and exit

Commands:
list                  list categories
list-all              list all categories and their verbs
apps list             list verbs in category 'applications'
benchmarks list       list verbs in category 'benchmarks'
dlls list             list verbs in category 'dlls'
fonts list            list verbs in category 'fonts'
settings list         list verbs in category 'settings'
list-cached           list cached-and-ready-to-install verbs
list-download         list verbs which download automatically
list-manual-download  list verbs which download with some help from the user
list-installed        list already-installed verbs
arch=32|64            create wineprefix with 32 or 64 bit, this option must be
                      given before prefix=foobar and will not work in case of
                      the default wineprefix.
prefix=foobar         select WINEPREFIX=/home/andy/.local/share/wineprefixes/foobar
annihilate            Delete ALL DATA AND APPLICATIONS INSIDE THIS WINEPREFIX

please emergencie post build version for net 7 and not net 8
