### ISSUE TITLE
please emergencie post build PKHeX.exe version for net 7 and not net 8

### ISSUE THREAD

**Issue by amidevous** [kwsch/PKHeX#4172]
net 8 not found and not work on wine

```
winetricks -q --force 'dotnetdesktop8'
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20240105-next - sha256sum: cd868b5357fc4d22a0c811687280759fb4575ab7e3687da5ab972c66c9614d76 with wine-9.0 (Staging) and WINEARCH=win64
Unknown arg dotnetdesktop8
Usage: /usr/bin/winetricks [options] [command|verb|path-to-verb] ...
Executes given verbs.  Each verb installs an application or changes a setting.

Options:
    --country=CC      Set country code to CC and don't detect your IP address
-f, --force           Don't check whether packages were already installed
    --gui             Show gui diagnostics even when driven by commandline
    --gui=OPT         Set OPT to kdialog or zenity to override GUI engine
    --isolate         Install each app or game in its own bottle (WINEPREFIX)
    --self-update     Update this application to the last version
    --update-rollback Rollback the last self update
-k, --keep_isos       Cache isos (allows later installation without disc)
    --no-clean        Don't delete temp directories (useful during debugging)
    --optin           Opt in to reporting which verbs you use to the Winetricks maintainers
    --optout          Opt out of reporting which verbs you use to the Winetricks maintainers
-q, --unattended      Don't ask any questions, just install automatically
-r, --ddrescue        Retry hard when caching scratched discs
-t  --torify          Run downloads under torify, if available
    --verify          Run (automated) GUI tests for verbs, if available
-v, --verbose         Echo all commands as they are executed
-h, --help            Display this message and exit
-V, --version         Display version and exit

Commands:
list                  list categories
list-all              list all categories and their verbs
apps list             list verbs in category 'applications'
benchmarks list       list verbs in category 'benchmarks'
dlls list             list verbs in category 'dlls'
fonts list            list verbs in category 'fonts'
settings list         list verbs in category 'settings'
list-cached           list cached-and-ready-to-install verbs
list-download         list verbs which download automatically
list-manual-download  list verbs which download with some help from the user
list-installed        list already-installed verbs
arch=32|64            create wineprefix with 32 or 64 bit, this option must be
                      given before prefix=foobar and will not work in case of
                      the default wineprefix.
prefix=foobar         select WINEPREFIX=$HOME/.local/share/wineprefixes/foobar
annihilate            Delete ALL DATA AND APPLICATIONS INSIDE THIS WINEPREFIX
```

please emergencie post build PKHeX.exe version for net 7 and not net 8

**Comment by MrPerson0** [comment]
PKHeX only supports Windows, it does not officially support Mac or Linux. No need to make duplicate issues when you have already been told this.

**Comment by amidevous** [comment]
so please post a binary version that works in net 7 as it did before you changed to net 8

even if it's an older version it doesn't matter

but you must always leave available

a binary version in net 7

you can put one version in net 7 and one in net 8 (more recent)

the important thing and that you must always leave a binary version PKHeX.exe available running under net 7

normally the binaries should be posted here

https://github.com/kwsch/PKHeX/releases

and not here

https://projectpokemon.org/home/files/file/1-pkhex/

and we should always be able to find

https://github.com/kwsch/PKHeX/releases

a version compatible with net 7

which is not the case

so thank you for doing what is necessary

for this you should use an old version of visual studio 2017 or 2019 and not 2022

**Comment by amidevous** [comment]
in other words we should be able to download

PKHeX (23.09.16).zip

who was in net 7

except with what you did you can only have

PKHeX (24.01.12).zip

who and in net 8

so please make sure to leave a zip link available

PKHeX (23.09.16).zip

running under net 7

it is not a complicated request to leave available

the old binary version on links that do not change

and it barely takes you 30 seconds to do it

I ask you which one is not spankable as far as I know

**Comment by kwsch** [comment]
Previous releases are still available on the forums, and you can compile the code from any point in the ~10 years of git history here.

Please do not open any more issues related to this.

**Comment by Lusamine** [comment]
> normally the binaries should be posted here
> 
> https://github.com/kwsch/PKHeX/releases
> 
> and not here
> 
> https://projectpokemon.org/home/files/file/1-pkhex/
> 
> and we should always be able to find

I will help you out a bit.

If you go to the official download site on projectpokemon.org, you can download previous versions of PKHeX. I have drawn a red box around where you need to look to help you find them.

![image](https://github.com/kwsch/PKHeX/assets/30205550/dd2e8b88-7e0b-4d43-ad67-8104073e1790)

If the files you want are not present, then you can rebuild any release yourself.
Please do not open any more issues in the future making demands for older versions or that any files be uploaded for you.
You already did this once when the repo was upgraded to NET7.
https://github.com/kwsch/PKHeX/issues?q=is%3Aissue+author%3A%22amidevous+%22+is%3Aclosed
