### ISSUE TITLE
Mystery Gift Database issue

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#418]
I have Hoopa and Volcanion, both as .pk6 files and .wc6 files that I ripped directly from my save file after legitimately receiving them from their respective distributions (HOOPA2016 Serial Code and GameStop). Adding the .wc6 files to the /wc6/ directory did show them as legal (in the 09/18/2016 release), however that isn't the case with recent commits.

I've tested them both online and they both pass the legality checks... perhaps the latest commit has a bug where it doesn't detect anything from the /wc6/ directory? I'm pretty sure neither are a part of the built-in Mystery Gift Database at the moment.

Below are pictures of legality results from the same .wc6

09/18/2016 release:
![image](https://cloud.githubusercontent.com/assets/17801814/20329989/a479cd3a-ab69-11e6-87f2-c8f97bfacdc4.png)

Latest commit:
![image](https://cloud.githubusercontent.com/assets/17801814/20329978/9271c11a-ab69-11e6-8144-5a9837f9c933.png)

If you need the .wc6 files, by all means:
[Hoopa WC6.zip](https://github.com/kwsch/PKHeX/files/593452/Hoopa.WC6.zip)
[Volcanion WC6.zip](https://github.com/kwsch/PKHeX/files/593454/Volcanion.WC6.zip)

**Comment by kwsch** [comment]
Database locations have been moved from 
wc6->mgdb
db->pkmdb

Haven't added the latest round of new wc6's yet.

**Comment by sora10pls** [comment]
Ah, that's why. Just tested renaming the folder and it's working as intended, thanks :)

**Comment by SuperBubbleGumHaZe** [comment]
Hey please can someone help me, i got a marshadow from a legit even code,, however after changing the nature and stats when i run it through servelegality i get error saying unable to match to a event in the data base. Is this jisy because the evnt is new?
