### ISSUE TITLE
BDSP - Changing a Legally Caught Mesprit's Nature Trips Legality Check

### ISSUE THREAD

**Issue by ThisNekoGuy** [kwsch/PKHeX#4190]
**Describe the problem**

When changing Mesprit's nature to Timid after being caught (legitimately), PKHeX returns an odd legality check error for that alone: "Encounter Type PID Mismatch."

Mesprit's a roaming legendary, and the PID values are basically always illegible to the average user (they have no real meaning to us), so this comes across as what must be some kind of bug? Re-rolling the PID doesn't resolve the issue either, so I don't understand why something that should be legal is being reported as not so.

**To Reproduce**

Mesprit's data should be considered legal regardless of the nature value. And if it truly isn't, the reason should be made more clear to the average user rather than with a vague PID error.

**Screenshots**
![Screenshot_20240217_153119](https://github.com/kwsch/PKHeX/assets/28468662/644e7abe-7992-4715-bc32-722dcdacb5b8)

**Comment by kwsch** [comment]
Roamers have a detectable PIDIV+ correlation, which is indicated as a specific type when viewing the verbose legality report. The same message is shown for every other detectable PIDIV+ correlation type.

The program is working as intended; by changing one of the correlated values to something unexpected, the program does not find a correlation in the Pokémon data, and indicates that the PIDIV+ correlation type does not match what was expected.

**Comment by Lusamine** [comment]
[There are many places to get help and understand PID mismatch by Googling the phrase.](https://www.google.com/search?&q=encounter+type+pid+mismatch)

**Comment by ThisNekoGuy** [comment]
> [There are many places to get help with PID mismatch by Googling the phrase.](https://www.google.com/search?&q=encounter+type+pid+mismatch)

@Lusamine I tried this. All I've found were references to an abandonware and PokeFinder. PokeFinder itself being complicated to use and with no usage guide at all on its github. I don't understand why if PKHeX _**can detect**_ invalid PIDs why it can't simply can't resolve conflicts. One would think half the logic for doing so is already there.

**Comment by Lusamine** [comment]
> I don't understand why if PKHeX _**can detect**_ invalid PIDs why it can't simply can't resolve conflicts. One would think half the logic for doing so is already there.

Solving an RNG correlation is not the same as finding a seed that matches any number of specific criteria you want.
Regardless, this is not the place to get help with hacking Pokémon.
The first few hits on Google that I linked you go to Project Pokémon where you can ask for help with this if you still do not understand it.
