### ISSUE TITLE
Nature Stats on Hover

### ISSUE THREAD

**Issue by swarley** [kwsch/PKHeX#42]
Perhaps you could make it so that in the dropdown for nature there is an info box that shows under the cursor like [SpA-, Speed+] when there is an extended hover.

I could look into trying it myself if you would rather have someone else do this.

**Comment by kwsch** [comment]
Implemented; thanks for the suggestion!
https://github.com/kwsch/PKHeX/commit/9bd1d302e1dd616879295a33a2879ba5ba348386
Hover over the dropdown arrow and you can scroll through to check.
