### ISSUE TITLE
[Suggestion] If CyberGadgets is installed create dir (dirty)

### ISSUE THREAD

**Issue by iGlitch** [kwsch/PKHeX#420]
Currently PKHeX creates a 3DSSaveBank folder whether you use it or not, use a dirty check to see if Cyber Gadgets is actually installed before actually creating the folder.

https://github.com/kwsch/PKHeX/blob/af22a1577c860bee2cf54145922defda43477cb1/PKHeX/Util/PathUtil.cs#L42

Maybe change to:

```
if(Directory.Exists(@"SOFTWARE\CYBER Gadget\3DSSaveEditor")) 
            {
                Directory.CreateDirectory(path);
            }
```

**Comment by kwsch** [comment]
Heh, these methods were copypasted out of a decompiled version of CGSE with little thought.
