### ISSUE TITLE
[Feature Request] Option to Disable Altering Trainer Records When a Pokemon is Set

### ISSUE THREAD

**Issue by Priestyle** [kwsch/PKHeX#4202]
Can there be an option to disable pkhex from altering trainer records when a pokemon is set? I know that it's not legal to have 0 wild pokemon battles while have 100 pokemon in the box as an example but I just want an option to disable this regardless. Please consider this feature request.

Update 1:
In gen 7 game saves, the following trainer records go up by 1 as Pokemon is set:
-Wild Pokemon Battles
-Pokemon Caught
-Balls Used
Update 2:
When an egg is set, "Eggs hatched" goes up by 1

**Comment by sora10pls** [comment]
Already exists
![image](https://github.com/kwsch/PKHeX/assets/17801814/8633d1fd-806f-49b4-b31c-bec227657e17)

**Comment by kwsch** [comment]
For the *record*, this was recently added, after the latest release.
