### ISSUE TITLE
Gen 1 and 2 - Rename IVs and EVs

### ISSUE THREAD

**Issue by MrPerson0** [kwsch/PKHeX#4210]
**Is your feature request related to a problem? Please describe.**
If possible, for the Gen 1 and Gen 2 GB + Stadium games, can you rename IV to 'DV' and EV to 'Stat Exp' (if the latter isn't too long)? Those are the names used for the Gen 1 and 2 games.

**Describe the solution you'd like**
When a Gen 1 or 2 GB or N64 save is loaded, have DV and Stat Exp show up in place of IV and DV.

**Comment by kwsch** [comment]
No
