### ISSUE TITLE
mGBA saves not loading.

### ISSUE THREAD

**Issue by sergiotarxz** [kwsch/PKHeX#4217]
**Describe the bug**
mGBA uses more than 128k of save for RTC and that causes the save not to load.

**To Reproduce**
* Save pokemon emerald in mgba
* Try to open in PKHex

**Expected behavior**
PKHex should ignore everything after 128k in a save and allow 128k + 16b saves for the third gen.

**Screenshots**
No

**Additional context**
I used the latest version in the forum.

**Comment by sergiotarxz** [comment]
This issue #3604 says it was implemented, but it is not currently working, I think it is a regression.

**Comment by MrPerson0** [comment]
A save file used through mGBA that reads as 129 KB works for me on the latest release. Did you make sure you're at least on 20240310?

**Comment by sergiotarxz** [comment]
I am not sure know, maybe I got the wrong binary, I will try again.

**Comment by sergiotarxz** [comment]
I am not quite sure what happened now, in my first time installation it would not allow me to load any saves until I trimmed them to 128k but after loading a trimmed save it now allows me to load mgba saves. Is there a way to delete all pkhex data to test in clean installation?

**Comment by Lusamine** [comment]
PKHeX doesn't need to be installed. You can delete the zip folder and any unzipped contents, then download a brand new copy from Project Pokemon: https://projectpokemon.org/home/files/file/1-pkhex/ 

The version number should show on the top menu bar of the program.

**Comment by MrPerson0** [comment]
AFAIK, PKHeX isn't really installed to your computer, it's a portable program. You should be able to unpack the .exe to a new folder and it should be seen as a "fresh" program.

**Comment by sergiotarxz** [comment]
No luck, I am closing the issue since I cannot reproduce.
