### ISSUE TITLE
Check for empty files is not reached in some cases

### ISSUE THREAD

**Issue by Bl4ckSh4rk** [kwsch/PKHeX#4223]
**Describe the bug**
The check for empty files that recently got added in commit https://github.com/kwsch/PKHeX/commit/a93a626dad540accf996503e218aca865b153552 currently is not reached in some cases. It should happen before even trying to get a supported file, because in _GetSupportedFile_ PKHeX already jumps into one of the cases and then fails to read the file.
For example it tries to load an empty Gen 3 save as PCBoxBin or an empty Gen 4/5 save as GCMemoryCard.

**To Reproduce**
1. Try to load an all-00/FF Gen 3 save
2. PKHeX tries to load it as a PCBoxBin
3. PKHeX fails to load it because it's empty

or

1. Try to load an all-00/FF Gen 4 save
2. PKHeX tries to load it as a GCMemoryCard
3. PKHeX fails to load it because it's empty

**Expected behavior**
Actually show the added messages and skip all the other checks because the file isn't supported anyways.

[empty_saves.zip](https://github.com/kwsch/PKHeX/files/14641893/empty_saves.zip)

**Comment by kwsch** [comment]
I have this fixed locally (changed the GC memcard message method to check for all 0 / FF) and was waiting on a commit to stuff this into. I'll push it and close this issue later today ☺️
