### ISSUE TITLE
Festival Point modifier and Zygarde Cells number modifier

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#423]
can you add a Festival Point (and battle point) modifier, and a way to add the missing zygarde cells to the zygarde item? thanks!

**Comment by kwsch** [comment]
Savegame related feature requests that require research/documentation to be done should be created as threads in the Save Editing Help forum, not as an issue with PKHeX.

It's trivial to add editing of certain values, just have to know what needs to be edited before it can be implemented.
