### ISSUE TITLE
Ribbon Error on Transfer

### ISSUE THREAD

**Issue by CorvusAtrox** [kwsch/PKHeX#4236]
**Describe the bug**
Attempting to transfer Pokemon from a Diamond version with Sinnoh Champion Ribbon with no Battle Ribbons erroneously adds a Battle Memory Ribbon when transferring to a Gen 6 or later game

**To Reproduce**
1. Create/copy a Pokemon in a Gen 4 game with the Sinnoh Champion ribbon and no other onesand save it as a file
2. Open a Gen 7 game
3. Open said Pokemon
4. Observe that said Pokemon has a Battle Memory count of 1

**Expected behavior**
Should not have a Battle Memory Ribbon in this case

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/7748403/edd65990-06bc-4289-9d0b-00f15ab30a63)
![image](https://github.com/kwsch/PKHeX/assets/7748403/71a6384d-4001-4154-a5d9-2e0522de4167)

**Comment by kwsch** [comment]
already fixed
https://github.com/kwsch/PKHeX/commit/f27326cb2e148e410ba88c4b765f35dfbbf0f909
