### ISSUE TITLE
(Legends: Arceus) Letter N Unown caught in Sand's Reach is flagged as illegal

### ISSUE THREAD

**Issue by Anon942** [kwsch/PKHeX#4237]
In Legends: Arceus, catching Unown (Letter N) in Sand's Reach makes PKHeX flag it as an illegal Pokemon despite being obtainable in the game.

I'm not sure if this is just a problem with me but to reproduce I guess all you need to do is just catch the static Unown (Letter N) in Sand's Reach in Legends: Arceus.

PKHeX will flag it as illegal due to the reason being ' Invalid: Unable to match an encounter from origin game).

![pkhex](https://github.com/kwsch/PKHeX/assets/155502587/94d94abe-bebe-4b37-b024-6db61a4de599)

I'm not sure if this was caused by a PKHeX update or if it was always there but I don't think it's supposed to flag it as illegal.

**Comment by Lusamine** [comment]
Seems that if you jump up and throw a ball at it on Basculegion, then wait for it to finish, you'll get "Cobalt Coastlands". But there's enough time for you to run over onto the beach and that'll give you "Sand's Reach."
