### ISSUE TITLE
[BDSP] Shiny Arceus not in Encounter Database result

### ISSUE THREAD

**Issue by TuxSH** [kwsch/PKHeX#4243]
![image](https://github.com/kwsch/PKHeX/assets/1922548/b264e51a-3e99-4795-888a-1fcee63e154b)

Encounter Database believe the only way to have a shiny Arceus is the WC6 event. However, to my knowledge, the Arceus Hall Of Origin encounter isn't shiny-locked.

**Comment by Lusamine** [comment]
![image](https://github.com/kwsch/PKHeX/assets/30205550/0fa32caa-5837-41f2-9702-e3efaa461914)
Shows up for me.

![image](https://github.com/kwsch/PKHeX/assets/30205550/46ac6d40-eb88-44b7-9c9a-8554660f0293)
Might be one of your settings here.

**Comment by TuxSH** [comment]
You have selected shiny=Any, and in the tooltip you have IsShiny=False

**Comment by Lusamine** [comment]
Pretty sure that setting is only for mons that come as shiny, not mons that can be shiny. You can see it shows "Shiny = Random" underneath. Try searching without any species and it brings up only mons that are coming as shiny.

**Comment by kwsch** [comment]
Checkmark meanings:
[ ] Unchecked => Exclude always-shiny encounters
[ ] Checked => Only include always-shiny encounters
[ ] Indeterminate => Don't filter
