### ISSUE TITLE
Implement trainer records editing for gen 5 save files

### ISSUE THREAD

**Issue by Priestyle** [kwsch/PKHeX#4245]
I'm always frustrated when you are not able to edit trainer records for gen 5 save files

**Comment by kwsch** [comment]
Do you have any documentation where this is stored, where & what each record is?

Things would have to be researched first before they would be a candidate for implementing into a program.

**Comment by foohyfooh** [comment]
I believe they may be partially documented in https://github.com/suloku/BW_tool/blob/master/BW_tool/Editors/TrainerRec.cs
