### ISSUE TITLE
Gen 2 savs do not load correctly 

### ISSUE THREAD

**Issue by Manurocker95** [kwsch/PKHeX#4253]
**Describe the bug**

The Pokémon and some other data is not loading properly. Some mons are missing and objects and data are not loaded.

**To Reproduce**
1. Open Pokémon Crystal (tested Spanish version) and play until you can get some pokémon.
2. Save the game.
3. Extract the save and open it in PKHex.
4. Check the Pokémon.

**Expected behavior**
Data being loaded properly. Mons in party, etc.

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/17181899/4c8c0148-2ba6-4e64-a874-41b73699a5d5)
![image](https://github.com/kwsch/PKHeX/assets/17181899/6265c494-afd9-45aa-b2a4-aaad280bd48d)
![image](https://github.com/kwsch/PKHeX/assets/17181899/fe6f45f0-4fec-4225-bd5b-2a6dbf334dae)

**Additional context**
haven't tested PKHex for gen 2 in a while but I think the issue started when refactoring for modern C#.

**Comment by kwsch** [comment]
Probably recent commit not putting data back correctly: 
https://github.com/kwsch/PKHeX/commit/1b294f7c97c37e070e209c3fc4dd91635b9cfb75
Should be a simple fix once identified

**Comment by kwsch** [comment]
Error is in both SAV1/SAV2 method GetPartyOffset, needs to be SIZE_PARTY not SIZE_STORED.

Also need to update the daycare offset fetch as well (now at positions 6+, not 7/9). All buffered slots are party format.

**Comment by Manurocker95** [comment]
> Error is in both SAV1/SAV2 method read of party (false->true isPartyFormat).
> 
> Also need to update the daycare offset fetch as well (now at positions 6+, not 7/9). All buffered slots are party format.

Are EVs supposed to look like this?

![image](https://github.com/kwsch/PKHeX/assets/17181899/60f18630-e90f-4358-a4be-17e64715b060)
