### ISSUE TITLE
cant fish anymore

### ISSUE THREAD

**Issue by Donf4b** [kwsch/PKHeX#426]
i guess its a problem with the inventory,
i had the rod before changing my inventory (i think it was in the "favorite bag", dunno how its called in english)
after saving i still got it but cant use it anymore

**Comment by SciresM** [comment]
Provide before/after save files? I tried to reproduce this a few days ago, but can still fish.

**Comment by Donf4b** [comment]
i only got a save befor getting it, and one where i got it and cant use it

**Comment by Naifus** [comment]
You can't use the fishing rod like in the other pokémon games. You must fish in specific undersea rock places by pressing "A".
The fact that you placed the fishing rod in the favs tab means that you didn't know that (it happened to me aswell XD)

Hope it helped and my apologies for my crappy English :)

**Comment by Donf4b** [comment]
thx but i do know that^^
it doesnt work plus those white flows above some fishing spots doesnt show up anymore aswell

**Comment by whimsicott0907** [comment]
Use Lapras, sharpedo too angry so you can not fish :D

**Comment by ricksee** [comment]
@Donf4b @whimsicott0907 Only Lapras can be used to fish with. Sharpedo scares them away or something.

**Comment by Donf4b** [comment]
that wasnt the problem, i just started a new save to fix this
