### ISSUE TITLE
BallUseLegality

### ISSUE THREAD

**Issue by bdawg1989** [kwsch/PKHeX#4263]
Can you please make this class accessible instead of internal?  I am using it for another project and would rather not have to make a new fork just for this update.

**Comment by kwsch** [comment]
It's not intended to be used externally by others, because it only surfaces permission bitflags.

Is BallApplicator not relevant to your use case?
https://github.com/kwsch/PKHeX/blob/bcb7135940ea2c7ab4cedce1b104c0432a79bdfe/PKHeX.Core/Editing/Applicators/BallApplicator.cs#L10

**Comment by bdawg1989** [comment]
> It's not intended to be used externally by others, because it only surfaces permission bitflags.
> 
> Is BallApplicator not relevant to your use case?
> 
> https://github.com/kwsch/PKHeX/blob/bcb7135940ea2c7ab4cedce1b104c0432a79bdfe/PKHeX.Core/Editing/Applicators/BallApplicator.cs#L10

Ugh, you are such a genius I swear.

That worked like a charm, thank you.

I'm working on an Auto Correct feature for showdown sets and this allowed me to also use a fallback method to use the color matched legal ball if a close match wasn't found.

![image](https://github.com/kwsch/PKHeX/assets/80122551/e8ab1382-b15e-4474-818e-8bc0df25f9b3)


Thanks Kurt <3

**Comment by kwsch** [comment]
There's other applicators to fix stuff, like ribbons. Glad to hear it worked for you.
