### ISSUE TITLE
wc6 says "null" when dropping it into editor

### ISSUE THREAD

**Issue by thunderkai** [kwsch/PKHeX#427]
what the titles says 🍡 
![image](https://cloud.githubusercontent.com/assets/20761061/20408834/31a3e5ca-ace5-11e6-8841-3995de75110c.png)

**Comment by SciresM** [comment]
The Munchlax+Snorlium Z card is a new type of wondercard that's not fully documented.

**Comment by ConcernedCitzen** [comment]
The z stones are key items so i don't know how well that works to try to add them to a pokemon and import them.

**Comment by thunderkai** [comment]
This is Ash Greninja

**Comment by kwsch** [comment]
Gen 7 mystery gifts do not use .wc6, they use .wc7

Pretty sure the program tries loading the file as a wc6, then realized it's
really not a wc6.
