### ISSUE TITLE
Italian Sapphire save file is recognized as a Fire Red one

### ISSUE THREAD

**Issue by glu8716** [kwsch/PKHeX#4273]
**Describe the bug**
As the title says, the Italian Sapphire's save file is recognized as a Fire Red one. Therefore, things like event flags or Pokédex edits are the ones of FR/LF.

**To Reproduce**
1. Open Italian Sapphire's save file
2. Check Event Flags or Pokédex

**Expected behavior**
Data should be of Sapphire.

**Additional context**
[Save file](https://0x0.st/XKdx.sav) for reference.

**Comment by sora10pls** [comment]
It's recognized as a Ruby/Sapphire save file on latest commit, not a FireRed one.
![image](https://github.com/kwsch/PKHeX/assets/17801814/b24983da-fd58-49a8-b277-391e546c0579)

**Comment by glu8716** [comment]
I've just downloaded the newest development build and yes, I can confirm now it's recognized as Sapphire. It wasn't the case for the previous build from yesterday.
