### ISSUE TITLE
Pokemon sun Corrupt save (fixed)

### ISSUE THREAD

**Issue by ConcernedCitzen** [kwsch/PKHeX#428]
I was using JKSV and saved the file to the SD card went into PKhex preformed a nature change. Then exported the file. when I imported the save file to the game it Corrupted it.

![15126286_1295037963850865_1680328797_o](https://cloud.githubusercontent.com/assets/23534626/20412461/8181e694-acec-11e6-9349-c2bd00a0f34c.jpg)

To try to fix it i originally turned it off and turned it back on. Then I tried to re-import the save file and reboot the DS. Neither of these worked.
What solved it was taking the save file going back on PkHex and re-exporting it, then I imported this "new save" and the game functions correctly again.

**Comment by kwsch** [comment]
Other users had previously reported a 'corrupted' issue, but upon investigation it was discovered that their method of transferring files from 3DS<->PC was resulting in incomplete files.

Were you using an FTP app to transfer the save?

**Comment by Hezron91** [comment]
I am having a similar issue, but slightly different.  

I am using Pokémon Sun and after editing a Pokémon and importing the save the game freezes right after loading into the game.  Background sounds play and it is nighttime. (normally it's daytime) but the game is frozen and the player character is not visible.

After exporting and importing (and making the same edits) on the save using PKHeX multiple times it finally worked, not sure why.  I was using an SD card and JKSM to transfer the save.

**Comment by kwsch** [comment]
Did you edit trainer info?

**Comment by Hezron91** [comment]
I modified my money and added some masterballs the first time, didn't work.  The second time I noticed the "Time Offset" option was blank so I assumed it was that causing the crash so I changed that to "Sun" and also modified my Pokémon but that didn't make a difference. it still froze.

The time in which it worked all I edited was the Pokémon (Natures, IV & Gender).  Nothing else.

**Comment by kamuisama** [comment]
i have the same problem with Hezron91... is it because I changed my start playing date in trainer info?

**Comment by ConcernedCitzen** [comment]
lol so it happened to me again. The incomplete file makes sense since after i get a "corrupted file" the PKhex doesn't identify my main as the file it should open unless i directly go to it.  I have been fixing it in the same method of keeping a back-up file and resaving the file until i produce a completed file.
