### ISSUE TITLE
Friend Ball Bug

### ISSUE THREAD

**Issue by mxava** [kwsch/PKHeX#4282]
Hi hi!

When I attempt to modify a pokemon to have been caught with a friend ball, it shows as having been caught by a pokeball when I attempt to save it.

When I load a pokemon to be edited again, it shows as having been caught by a pokeball, which indicates to me the bug is probably not visual.

1. Go to 'Met' menu
2. Select Friend Ball from the dropdown.
3. Move pokemon into a box slot
4. See pokeball is a regular pokeball.
5. Attempt to load pokemon from box for further editing, and you will find it's a regular pokeball instead of the friend ball which was selected.

Expected behavior would be that the pokemon reflects that it has been caught by a friend ball.

I stumbled across this on a HGSS save file - I haven't checked for other games/gens.

**Comment by Lusamine** [comment]
I tried this on a Pokémon from HGSS in HGSS and it worked fine. Then, I tried it on a Pokémon from Platinum in HGSS and it reset to Poké Ball. What Pokémon are you specifically trying to edit?

**Comment by kwsch** [comment]
Working as intended. Be sure you are editing something that originated from HG/SS when trying to set an HG/SS ball.

https://github.com/kwsch/PKHeX/blob/a7421a7cebd598776de91edd8d745a199709d3f2/PKHeX.Core/PKM/Shared/G4PKM.cs#L259-L282
