### ISSUE TITLE
Livehex bug in PKHeX 24.06.03

### ISSUE THREAD

**Issue by Aura67** [kwsch/PKHeX#4289]
Livehex bug in 24.06.03 here is the error that PKHeX spits out for me.
![grafik](https://github.com/kwsch/PKHeX/assets/152577275/03fcc132-8e68-4b73-bad9-84ad2ae67d9d)
And when I want to create a Living Dex with it, Windows is somehow stuck. The old version works without any problems. 
I have the latest PKHeX plugins from santacrab2

**Comment by MrPerson0** [comment]
This is a plugin issue, nothing to do with PKHeX.
