### ISSUE TITLE
Versions after 24/01/12 cannot open gamecube .raw saves

### ISSUE THREAD

**Issue by Loch32** [kwsch/PKHeX#4296]
Opening a .raw Colosseum or XD save results in no save file opening

Reproduction: Either open a .raw save in PKHeX, or open it with PKHeX from the file explorer.

https://github.com/kwsch/PKHeX/assets/140365955/2bd2d7c1-db64-41f0-a166-5652ce7b5beb

https://github.com/kwsch/PKHeX/assets/140365955/996271b5-10f3-401a-80c2-3ce01adc6bcc

The first of the videos above is of me trying to open my Japanese Colosseum save file from Nintendont my Wii and PKHeX not recognising it. The second is of me trying to open my PAL Colosseum save file from Nintendont on my Wii U. 

Versions before and including 24/01/12 were able to open my PAL save, but in 24/01/12 I was still unable to open my Japanese save file.

**Comment by kwsch** [comment]
I'm still able to open `.raw` save files from the File->Open menu and drag-drop. Do either of those methods work for you?
![image](https://github.com/kwsch/PKHeX/assets/6393368/8a204c29-12a0-4ef3-a5bb-9791243ddc2c)

**Comment by kwsch** [comment]
Ah I see, Memory Cards are not save files, so the startup arguments defer loading not-PKM/SAV files to {never}.

**Comment by Loch32** [comment]
Thanks for having a look mate I appreciate it.
