### ISSUE TITLE
[bug] Box layout setting "X" unlocked doesn't do anything

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#430]
After setting Unlocked boxes from 32 back to 24 since I did a clean up and re-ordering of my boxes the amount of boxes available in-game remains to be 32. 

Amount as shown in pkhex:

![image](https://cloud.githubusercontent.com/assets/4019718/20429496/54056828-ad8f-11e6-913a-38281d733563.png)

Amount as shown in-game:

![img_0734](https://cloud.githubusercontent.com/assets/4019718/20429666/5f0c9664-ad90-11e6-8baf-186df781a3b2.jpg)

**Comment by kwsch** [comment]
Could be that the game is overriding it back to 32 since you have 24 boxes in use (giving you more), or that you have defined box names already.

**Comment by kwsch** [comment]
Try checking a before-after @ 0x4DE1

**Comment by Favna** [comment]
Excerpt Offset 0x4DE0 until 0x4E09

When pkhex and in-game are both set to 32:

```
15 1F 00 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

When Pkhex is set to 24 but in-game still shows all 32:

```
11 17 00 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by kwsch** [comment]
I meant after re-saving ingame

**Comment by Favna** [comment]
Sorry. of course.  Same offset region.


32 boxes set in pkhex and visible in game 
```
15 1F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

after setting to 24 in pkhex and resaving in-game (pkhex also still says 24):

```
15 17 00 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```


Also I recorded a short video concerning the earlier mentioned side note and the bug with box 32. Currently looking for some other people on discord to  check what happens to them when replicating this. [video here](https://streamable.com/b8xg)

**Comment by Favna** [comment]
Ok my friend pulled through and he actually at the time when I asked him had 16 boxes unlocked. He tried to replicate the issue but since he was also passing 24 boxes I asked him to dump that as well so here are the hex bytes in the same ranges of that

24 boxes currently unlocked by official means:
```
00 18 00 17 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

32 boxes currently unlocked by official means:

```
00 20 00 1F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

That all said, I think this isn't so much a bug in pkhex but more so just my save being somehow broken since I also have the bug in the box 32. Right now I'm just thinking about dumping my pcdata.bin and restarting the game then rushing through the story to get where i am right now, that is, unless I can fix this in hex by simply taking one of the above sets and putting it in my own save file.

**Comment by Favna** [comment]
Just tested it out with the build of 0fbb380accdf66048f7f79c3251c65ff6d941d9d and it has fully fixed it - both the actual fact that I am now back at 24 boxes and when I extend that to 32 in-game the weird duplication glitch doesn't occur anymore. As always thanks! I think this issue can be closed so I'll do so.
