### ISSUE TITLE
PKHeX corrupts save files (.dat) when exporting VC Crystal Save file

### ISSUE THREAD

**Issue by SpoonyBoobah** [kwsch/PKHeX#4307]
When I recently decided to use PKHex to modify my save file to evolve my Seadra to a Kingdra after inserting my memory card to my PC starting PKHeX and modifying the Seadra to Kingdra, then exporting the sav.dat back to my memory card. Then using the checkpoint app on my 3DS, then starting Pokemon Crystal it shows the "save file is corrupted error".

However when using the backup from earlier that day from the "bak" folder, I manually renamed it to "sav.dat" and put it on the memory card in a new folder without using the PKHex to export it. And the save file loaded on the 3DS correctly with no error.

I am am able to reproduce this everytime, whenever I load up my save file in PKHex and make any change, then export it to the memory card the 3DS VC shows it as corrupted.. yet using any .bak file I have available. I manually rename it to "sav.dat" and copy it onto the memory card the save file is recognised and loads fine.

**Comment by kwsch** [comment]
Can you upload your before & after save file?

**Comment by SpoonyBoobah** [comment]
Corrupted save

[Corrupted Save.zip](https://github.com/user-attachments/files/16034304/Corrupted.Save.zip)

**Comment by SpoonyBoobah** [comment]
Fixed Save

[sav.zip](https://github.com/user-attachments/files/16034312/sav.zip)

**Comment by MrPerson0** [comment]
Tested on my own Gen 2 VC save. It seems that even on the latest dev build, PKHeX is erroneously removing the 0x8000 line from the save file, which houses the RTC.
