### ISSUE TITLE
[PKHeX (24.01.12) & PKHeX (24.06.03)] Flag 1341 in Pokemon Platinum not being checked

### ISSUE THREAD

**Issue by Priestyle** [kwsch/PKHeX#4310]
**Describe the bug**
In pokemon platinum, flag 1341 is a nugget in one of the following locations: In the final room of the Solaceon Ruins, in the northeast of the lake northeast of Psychics Deandre and Kendra in the Victory Road, in the northeastern corner of the room in the Stark Mt., in the northwest of the Villa in the Resort Area. I picked up the nuggets in all of these locations and flag 1341 is not checked in pkhex.

**To Reproduce**
1. Go to the following locations listed above in-game.
2. Pick up the nugget ground items located in those locations.
3. See if flag 1341 is checked in pkhex.
4. See that flag 1341 is not checked in pkhex.

**Expected behavior**
Flag 1341 should be checked in pkhex.

**Screenshots**
![2024-07-01-13-07-35-PKHeX-w386iNll15](https://github.com/kwsch/PKHeX/assets/52426313/e2809eac-ef57-4017-849a-f36c727869ed)

**Additional context**
There are no additional contexts.

**Comment by Lusamine** [comment]
If picking up the Nugget does not toggle the flag, my assumption would be that that flag is unrelated to the Nugget, not that PKHeX is bugged. Why do you believe this flag is related to the Nugget?

**Comment by Priestyle** [comment]
I went on event file 404 in dspre which is the list of field items available for pick-up then I saw 92 which is the index number for the in-game item nugget. Wait but as I'm typing this, I just realized that there are 6 92's in the list in event file 404 which means ther are 6 nuggets available for pick-up in game... I'm really confused...

**Comment by Lusamine** [comment]
It sounds like this flag is not proven to be the Nuggets in question. As far as I can tell, the Event Flag Editor is reading flags properly. I don't think it is bugged at displaying this flag, but rather your understanding is incomplete.

**Comment by Priestyle** [comment]
Hey, could I report something else? I just started a new game in platinum and it has flag 1106 checked. I'm 1 hour 30 minutes into the game and I'm standing right before entering Jubilife City. Flag 1106 represents Lunar Wing field item in the Fullmoon Island. I think there might be a bug with pkhex. I didn't check flag 1106; I swear.

**Comment by Lusamine** [comment]
> Hey, could I report something else? I just started a new game in platinum and it has flag 1106 checked. I'm 1 hour 30 minutes into the game and I'm standing right before entering Jubilife City. Flag 1106 represents Lunar Wing field item in the Fullmoon Island. I think there might be a bug with pkhex. I didn't check flag 1106; I swear.

What is your evidence that this is related to Lunar Wing? Did you compare before/after saves to see if this flag is toggled? Again, if you have no evidence that this flag is related, and interacting in game does not alter it, the issue is not with PKHeX.
