### ISSUE TITLE
Dream Ball legality in gen 6

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#432]
Pokémon that don't have a unique hidden ability in at least one of their evolution stages in gen 5 but gain one in gen 6 (Plusle, Minun, Kecleon, Duskull, I forget if there are others) will not have their HA flag set when encountered in the Dream World, and thus will not gain their new HA when transferred to gen 6, making the Dream Ball illegal with their HAs*. PKHeX currently recognizes them as legal.

*In gen 6 anyway. They're legal in gen 7 with the new breeding mechanics but I'm assuming that won't be added to the legality checker until Bank updates since it's irrelevant now.

EDIT:
Pokémon that aren't found in the Dream World but have an evolved form that is (Roggenrola, Timburr, Venipede, Sandile, Dwebble, Solosis, Vanillite, and Joltik) are also incorrectly flagged as illegal if bred in a Dream Ball in gen 6.

**Comment by DracoMilesX** [comment]
In gen 6 you have ability capsules which allows ability switches. Haven't tested it myself but maby this is why they are legal?

**Comment by White-Canary** [comment]
Ability Capsules only switch between standard abilities, they can't give a Pokémon its hidden ability.

**Comment by White-Canary** [comment]
Found another issue with Dream Balls in gen 6, see above.
