### ISSUE TITLE
Pokemon Arceus: PP variable not honored in game

### ISSUE THREAD

**Issue by DunhamGitHub** [kwsch/PKHeX#4327]
- Exported save (with Edizon)
- Imported save (into Pkhex)
- Edited move's PP
- Set PP to max (231 is seems)
- Exported save
**- In game the PP is set to the max of the move (sanity check) not 231 (or whatever I set in the editor)**

<img width="500" src="https://github.com/user-attachments/assets/eece405a-0034-4d19-b1d2-469dc835529a">

<img width="500" src="https://github.com/user-attachments/assets/e1f4d8e5-f726-4b6f-a1de-4649e80f0f8b">

**Comment by Lusamine** [comment]
If this is how the game works, this is how the game works. It should not be expected that the game honors crazy illegal values. Not related to PKHeX.
