### ISSUE TITLE
Legality Checker Error (Gen 3 - RS)

### ISSUE THREAD

**Issue by ecrs98** [kwsch/PKHeX#4333]
**The problem**
The legality checker erroneously flags a legal PID/ability combination of the following Pokemon in a blank RS save file.

**For reproducibility**
[0251 - Celebi_JP - 8CC8AB87D82B.zip](https://github.com/user-attachments/files/16436489/0251.-.Celebi_JP.-.8CC8AB87D82B.zip)

**Expected behavior**
Given the PID `AB87D82B`, I expect the ability to be Natural Cure (2). However, the legality checker flags this PID/ability combo with the message **"Invalid: Ability does not match ability number."** Keeping the same PID and changing the ability to Natural Cure (1) returns a **"Legal!"** message.

Converting the PID `AB87D82B` to binary yields `10101011100001111101100000101011`. The last bit in this number is 1, so the Pokemon should have its second ability.

**Additional context**
I am matching a genned Celebi to a legitimate Ageto Celebi from the JP Colosseum Bonus Disc, in accordance with the retail RNG guide contained in [this Reddit post](https://www.reddit.com/r/pokemonrng/comments/es11nh/ageto_celebi_retail_rng_guidealso_colo_pikachu/). The Celebi I am matching is described in the second row of data in the screenshot below, displaying the correct PID and ability -- `AB87D82B` and 特性2 (Ability 2), respectively.
![image](https://github.com/user-attachments/assets/2feff4b1-2f37-40c6-bb41-6afe92ebbe05)

**Comment by Lusamine** [comment]
This seed shows up in both PokeFinder and RNGReporter as Ability 1 which matches what PKHeX expects, so I question whether that program is predicting it accurately. Ideally, the issues should be for legitimate Pokémon that are being flagged, not for asking why genned Pokémon are being flagged.

![image](https://github.com/user-attachments/assets/0f722875-55fb-46f5-b823-8fff80ab3df6)
![image](https://github.com/user-attachments/assets/f31ff273-cc70-42b8-a089-90cdf81daaeb)

**Comment by ecrs98** [comment]
Understood, thank you.

**Comment by Lusamine** [comment]
Made an edit to my earlier comment once I realized the programs index ability differently.

I also noticed that the [111 Ageto Celebi examples provided on PPORG](https://projectpokemon.org/home/files/file/1694-ageto-celebi/) are all Ability 1.

I'll leave this issue open for someone else to explain what we are observing.

**Comment by kwsch** [comment]
In generation 3, Pokemon without distinct second abilities have their second ability as 0, and the game will not set the ability bitflag. Thus, it will only select the first slot.

**Comment by kwsch** [comment]
In generation 3, Pokemon without distinct second abilities have their second ability as 0, and the game will not set the ability bitflag. Thus, it will only select the first slot.

**Comment by Real96** [comment]
> This seed shows up in both PokeFinder and RNGReporter as Ability 1 which doesn't matches what PKHeX expects. Ideally, the issues should be for legitimate Pokémon that are being flagged, not for asking why genned Pokémon are being flagged.
> 
> ![image](https://private-user-images.githubusercontent.com/30205550/353710172-0f722875-55fb-46f5-b823-8fff80ab3df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjM1NjEsIm5iZiI6MTcyMjQyMzI2MSwicGF0aCI6Ii8zMDIwNTU1MC8zNTM3MTAxNzItMGY3MjI4NzUtNTVmYi00NmY1LWI4MjMtOGZmZjgwYWIzZGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZmVjZjI0OTcxMmRhYzk1YTJhMDgxOGZkMGU0NWU2YjMxNzU3NjcxMmY0OTM5MWUyNWVkNzlhOTE3NTAwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CnA6fgVjyrlJ12qyjzPECZB2QdRnEluiuuH8EnpSw2E) ![image](https://private-user-images.githubusercontent.com/30205550/353710242-f31ff273-cc70-42b8-a089-90cdf81daaeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjM1NjEsIm5iZiI6MTcyMjQyMzI2MSwicGF0aCI6Ii8zMDIwNTU1MC8zNTM3MTAyNDItZjMxZmYyNzMtY2M3MC00MmI4LWEwODktOTBjZGY4MWRhYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOTQ2ZjQxZmNiNGVlYmFmNTUyMjU3OWI3ZjMyOWIxMTI0Njg3Yzk4ZGI1ZmZiNWU0ZjQwNGJhYjRlNjBlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.15I4mqZD5ef0Box_5gzVxSjXqI5n4OsBtPhU9y_AgQk)
> 
> EDIT: I forgot that both of these programs use Ability 0 or 1 rather than 1 or 2, so 1 would match up to the 2nd ability. But I'm unsure if there's something else to that Pokémon such that all of them end up as Ability 1 after transferring to RS, for example.

Just wanted to point out that PokeFinder correctly calculate Celebi as ability 0 only. You have to use latest release/commit for this.
