### ISSUE TITLE
[Gen 6-ORAS] "Times used area/play/dex/buzz-nav" doesn't increment by 1 when I use go on them. Maybe the numbers aren't the records?

### ISSUE THREAD

**Issue by Priestyle** [kwsch/PKHeX#4338]
**Describe the bug**
"Times used area/play/dex/buzz-nav" doesn't increment by 1 when I use go on them. Maybe the numbers that represent them aren't the records? I have 16 for "Times areanav used", 49 for "Times dexnav used", 1 for "Times buzznav used", and 12 for "Times playnav used." Maybe these numbers aren't those records? Could you look into this?

**To Reproduce**
1. Go on area/buzz/play/dex-nav in-game in an Omega Ruby save file
2. Save the game
3. Check the "Times used area/play/dex/buzz-nav" trainer records in pkhex
4. Compare to the last saved save file. the "Times used area/play/dex/buzz-nav" trainer records didn't each increment by 1. 

**Expected behavior**
"Times used area/play/dex/buzz-nav" trainer records should go up each by 1 or however many times you used area/buzz/play/dex-nav.

**Screenshots**
![2024-08-11-17-36-30-msedge-Exvm0UpCrR](https://github.com/user-attachments/assets/57e471a7-0eb4-460b-8540-9b211502cc41)

**Additional context**
There are no additional context

**Comment by kwsch** [comment]
They are for them, they do not increment when you flip to them, only when they're activating.
