### ISSUE TITLE
Set the raw value of stats instead of relying on calculation

### ISSUE THREAD

**Issue by bryc** [kwsch/PKHeX#434]
So in Gen I and maybe others, you can set the stats of pokemon directly. 999 hp, 999 attack etc. The game recalculates the stats upon leveling up, but if the pokemon is Lv100 it does not, and the stats actually take effect. 

It'd be nice to be able to override the stat calculation and set values directly. It just seems limiting that I can't create my SuperPika in PKHeX when I can in PikaSav.. PKHex has a lot more potential.

**Comment by kwsch** [comment]
Rename the executable to PKHaX -- HaX mode removes the training wheels and allows more illegal edits.
