### ISSUE TITLE
The last 3 IVs of all the Gen4 roamers block data are swapped

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#4346]
**Describe the bug**
The last 3 IVs of all the Gen4 roamers block data are swapped. PKHex atm shows them in this wrong order:
- HP
- Atk
- Def
- Spe
- SpA
- SpD

**To Reproduce**
1. Open a Gen4 save file where raomers Pokémon are still roaming
2. `SAV` tab -> `Block data`
3. Scroll down to any Roamer data block
4. You can see the error by checking the latest 3 IVs (SpA, SpD, Spe)

**Expected behavior**
PKHex should show the IVs of roamer block data as follow:
- HP
- Atk
- Def
- SpA
- SpD
- Spe

**Screenshots**
![image](https://github.com/user-attachments/assets/bd1bae2f-73b2-430c-861c-82add16f10d0)

**Additional context**
This same behaviour happens in Gen5 raomers block data, but it is correct in these games.

**Comment by kwsch** [comment]
The consistent internal ordering maintained by PKHeX is Speed-Middle like is stored in the 32-bit IV structure, not Speed-Last like is displayed in games.
```cs
        get => [IV_HP, IV_ATK, IV_DEF, IV_SPE, IV_SPA, IV_SPD];
```

**Comment by Real96** [comment]
> The consistent internal ordering maintained by PKHeX is Speed-Middle like is stored in the 32-bit IV structure, not Speed-Last like is displayed in games.
> 
> ```cs
>         get => [IV_HP, IV_ATK, IV_DEF, IV_SPE, IV_SPA, IV_SPD];
> ```
> 
> Roamer4.cs and Roamer5.cs both implement the same 32-bit read/write order, so if you're saying that Gen5 roamer IVs are wrong, then that would be something worth revising.

The image below shows that in Gen5 the IVs are ordered correctly:

![image](https://github.com/user-attachments/assets/a97cc1eb-1733-4360-a62f-25db7a0281d9)

If you create an Entei with PID D1C85F23 and IVs 26/10/24/0/6/16 (as showed in the first image of Entei block data), PKHex will flag it as not legal. So gen4 roamers block data are showing swapped IVs atm.
