### ISSUE TITLE
Manaphy BDSP in the mystery gift database always is marked illegal due trash bytes

### ISSUE THREAD

**Issue by milotic** [kwsch/PKHeX#4352]
**Describe the bug**
Open the database of mistery gifts and take the manaphy egg of BDSP and always is showing a error in trash bytes nothing work to fix the problem.

**To Reproduce**
1. Go to 'mistery gift database'
2. Download the manaphy egg of BDSP
3. Always is marked illegal due trash bytes

**Expected behavior**

manaphy eggs works in BDSP

**Screenshots**

![imagen](https://github.com/user-attachments/assets/e43b2fdf-a0f2-4fbf-99a7-22820167c811)

**Additional context**
i try do the google answer to delete trashbytes in pkhex and nothing happen the egg still ilegal: https://projectpokemon.org/home/forums/topic/65281-how-to-clear-trash-bytes-with-option-1-mentioned-in-this-forum-but-the-mod-is-offline/
the only info what i found in google was a person with the same problem but with other egg event showing the same problem: https://projectpokemon.org/home/forums/topic/65109-learning-about-trash-bytes/

**Comment by Lusamine** [comment]
It should be addressed that it is coming out of the database with trash bytes, but I don't know why are not able to clear them. I think you are clearing them wrong.

The very first guide you linked says to ctrl+click on the nickname field and click to clear them, which is what I did.
![manaphytrash](https://github.com/user-attachments/assets/c125fe3a-68e5-48d3-9a3f-4ea963b40cbb)

**Comment by milotic** [comment]
thanks i delete the egg and make another and works

**Comment by Lusamine** [comment]
Please do not close the issue.

I gave you a workaround to fix the problem for yourself. The problem still exists and should be handled.
