### ISSUE TITLE
Batch Editor isn't capable of renaming OTName to Japanese

### ISSUE THREAD

**Issue by Glazeddberrie** [kwsch/PKHeX#4354]
**Describe the bug**
I'm trying to use the batch editor to rename some imported Pokemon from another game into my Sapphire OT name, but the batch editor doesn't do it when i hit the "Run" button

**To Reproduce**
1. Go to Batch editing
2. Add the desired parameters to the prompt with a Japanese name
![image](https://github.com/user-attachments/assets/c585af98-25f1-4b72-b43c-9c2514c42468)
3. Press "Run" and prompt says that everything was edited.
![image](https://github.com/user-attachments/assets/e9972136-f25f-4f95-8870-bd131a030cae)
4. Check any Pokemon and the OT is in blank but everything else changed.
![image](https://github.com/user-attachments/assets/e5df0f09-d073-444d-a8c5-191ec80b1d3f)

**Expected behavior**
OT name should change to Japanese

**Screenshots**
Already added them up there.
 
**Additional context**
Posted this issue since i wasn't able to find anyone reporting this bug.

**Comment by kwsch** [comment]
Invalid whitespace before the Japanese chars.
```
.OriginalTrainerName= ほうお
```
vs
```
.OriginalTrainerName=ほうお
```
Can't mix and match halfwidth (int) and fullwidth (jpn). Invalid char -> abort writing.
