### ISSUE TITLE
Gen 3/4 NidoranF/Illumise Egg PID constraint

### ISSUE THREAD

**Issue by abcboy101** [kwsch/PKHeX#4356]
**Describe the problem**
Gen 3/4 determine which species is in an Egg produced by Nidoran♀ or Illumise based on the value of `PID & 0x8000` when the player obtains the Egg from the Day-Care Man. If that bit is 1, it's set to be a Nidoran♂ or Volbeat; if it's 0, it's Nidoran♀ or Illumise.

Hatched Nidoran♂ or Volbeat bred from a male and Ditto don't have this constraint, since they always hatch into Nidoran♂ or Volbeat in these games.

**To Reproduce**
See decomp:
- [pokeruby](https://github.com/pret/pokeruby/blob/714bd0ac0e38fa4ee51a11f7679ea91f6ce6762b/src/daycare.c#L645-L653)
- [pokefirered](https://github.com/pret/pokefirered/blob/539ed36160b697ffa6674d18ee62fb9a06e510de/src/daycare.c#L1042-L1050)
- [pokeemerald](https://github.com/pret/pokeemerald/blob/04197b49126604a310fae1d314709334f6d2460d/src/daycare.c#L783-L791)
- [pokeheartgold](https://github.com/pret/pokeheartgold/blob/1ffb090e94dcf63b593ee47f284751a7323bc33a/src/get_egg.c#L602-L615)

**Expected behavior**
- If the constraint isn't met, it should be flagged as invalid, like Wurmple evolutions with an EC mismatch are.
- Egg encounters generated from the Encounter Database should follow this constraint.

**Additional context**
Gen 2 and Gen 5+ roll rand(2) to determine the species separately.

**Comment by kwsch** [comment]
Fortunately the encounter detection mechanism is 100%, so no deferral scenarios like with wild Wurmple:
* Gen3: not having a PID/IV -> only from an egg (no gift eggs)
* Gen4: having an egg met location -> only from a daycare egg (no gift eggs)

**Comment by abcboy101** [comment]
`VerifyEC` is only called for `pk.Format >= 6`, so the check is not running in Gen 3-5 saves. For comparison, the Wurmple check is in `PIDVerifier.Verify` so that it runs in Gen 3-5 as well.

----

Some Nidoran♂/Volbeat bred from a Ditto are being incorrectly flagged; the constraint shouldn't be applied to Nidoran♂/Volbeat that _could've_ been bred from Ditto. As far as I'm aware, the only way you could tell it _must not_ have been bred from Ditto is in Gen 3-6 if it has an inherited level-up move, since that would mean both parents must've had the move.

**To Reproduce**
[nidoran.zip](https://github.com/user-attachments/files/16901753/nidoran.zip)

- Nidoran♂ (F4EF3BFC) was from a Ditto parent and has `(ec & 0x8000) >> 15 == 0`. Should be marked as valid.
- Nidoran♂ (F5C9B9C9) was from a NidoranF parent. It has the inherited level-up moves Double Kick, Poison Sting, and Helping Hand. Since it knows those moves, it must follow the constraint `(ec & 0x8000) >> 15 == 1`.
- Nidoran♂ (F5C939C9) is identical to F5C9B9C9 except for its PID being edited so that `(ec & 0x8000) >> 15 == 0`. Since the constraint isn't met, it must have been from a Ditto parent.
  - It would be invalid in Gen 3-6, since it also must have inherited level-up moves from two non-Ditto parents, which contradicts this.
  - It would be valid in Gen 7+, since it could have learned all three of those moves from the Move Relearner while in Gen 7.
