### ISSUE TITLE
PKHeX not loading Gen 1 party box pokemon

### ISSUE THREAD

**Issue by NimbusFox** [kwsch/PKHeX#4358]
**Describe the bug**
Using version 24.07.27 and a complete Pokemon Red save the pokemon in the other boxes except for Box 1 are completely missing. I have checked with version 23.09.25 and the box pokemon are showing correctly.

I went back to find when this bug started. It started from version 24.06.03

**To Reproduce**
1. Start up PKHeX 24.07.27
2. Load a Pokemon Red save with pokemon in multiple boxes
3. You will see boxes that are not the currently loaded box will have no pokemon in them

**Expected behavior**
When loading a gen 1 save all pokemon in the boxes should be visible

**Screenshots**
![23.09.25](https://github.com/user-attachments/assets/d26ea4bd-ed85-4499-9d6a-f1a15874a7f0)
![24.07.27](https://github.com/user-attachments/assets/f3a84236-77b4-415b-91c2-3d185e2fefb2)

I have included a complete save of Pokemon Red that I have been using to test my project
[Gen 1 - Red (ENG).zip](https://github.com/user-attachments/files/17098973/Gen.1.-.Red.ENG.zip)

**Comment by NimbusFox** [comment]
It seems this save file has some weird data that is causing it to not appear in the games either. After playing about I got the save working correctly.

**Comment by MrPerson0** [comment]
Did you personally edit this save file, or was this downloaded? Might have been an issue with older PKHeX versions when it was previously edited.
