### ISSUE TITLE
Pokemon Sun Crash

### ISSUE THREAD

**Issue by Trainiax** [kwsch/PKHeX#436]
So, I started game. Got starter, saved, PKHeXed in a team, all items, all pokebean, max money, max dex, and all boxes. Went in, crashed right when I got there. Music playing, everything loaded but me. Now when I try to go in via HBL, have tried 3 different save editors, gives me yellow screen bug.

**Comment by kwsch** [comment]
Closing, duplicate with #437 (a little more descriptive / has some discussion already).
