### ISSUE TITLE
Flawless IVs on Certain encounters showing Illegal.

### ISSUE THREAD

**Issue by bdawg1989** [kwsch/PKHeX#4361]
**Describe the problem**
I notice that certain encounters in SV, such as Kingambit, do not allow perfect IVs unless it is shown that it was hatched from an egg, even though a Met Location of 30024 should be legal, as there are 6IV Kingambit encounters that are legal.  

**To Reproduce**
Import showdown set:
```
Kingambit (M) @ Ability Patch
Ball: Poké Ball
Level: 75
Shiny: Yes
Ability: Pressure
EVs: 4 HP / 252 Atk / 252 Def
Tera Type: Dark
Brave Nature
.MetLocation=30024
- Brick Break
- Dark Pulse
- Guillotine
- Iron Defense
```

**Expected behavior**
Should be legal.

**Screenshots**
On initial import, it randomizes the IVs, even though a specific IV was not specified, and should automatically apply perfect IVs.

![image](https://github.com/user-attachments/assets/f417623e-4993-4ee1-8b67-da6949019c2a)

Then, if you change all of the IVs to perfect, it shows illegal.  Even though it's perfectly legal.

![image](https://github.com/user-attachments/assets/d972c4d0-b05b-408c-84ad-80b0ff40466d)

**Comment by sora10pls** [comment]
> Met Location of 30024
The encounter is from a Tera Raid Battle, which has RNG correlation. You modified the IVs, breaking said correlation, making it illegal. Please only report flags on legitimately obtained Pokémon that have not been edited.
