### ISSUE TITLE
Pokémon Sun/Moon: Unplayable and frozen game after some edits

### ISSUE THREAD

**Issue by Naifus** [kwsch/PKHeX#437]
Hello, first of all my apologies for my English, I will try to explain what happened to me and hope that you guys can understand what I'm trying to spell:

**Issue**: After editing the save and importing it, the character dissapears, can't move, the game freezes but the music keeps. The game is totally unplayable.

I have not the save file where it happened but I remember everything that I did so maybe you can reproduce it:

1. I saved the game inside the Pokémon Daycare
2. I used `JKSM` to extract the `main.bin`
3. Downloaded `PKHeX commit 866`
4. I dumped all my boxes by pressing: `Tools` > `Data` > `Dump Boxes`
5. Cleared all my boxes using the shortcut `Alt`+`Click`
6. Loaded all my boxes back by pressing `Tools` > `Data` > `Dump Boxes`
7. Then I pressed `No` and `Cancel`
8. Edited my Poké Beans by adding 255 Rainbow Beans.
9. Also I changed all my boxes names using no special characters and using the proper text size.

**Edit**: I also entered to the Trainer Info tab but I didn't touch anything.

**Comment by kamuisama** [comment]
this happened to me too.

**Comment by kwsch** [comment]
I'm thinking the issue is opening->saving the Trainer Editor; the Overworld data block is updated with the current trainer position and likely is being stored in a different format (indoor coordinates vs outside).

**Comment by kamuisama** [comment]
is there a hot fix yet? I'm kinda afraid to edit the money/time now lol

**Comment by kwsch** [comment]
Try using the latest commit and set your coordinates to the following:

![image](https://cloud.githubusercontent.com/assets/6393368/20451876/a1c39bba-adb3-11e6-9140-88c20bd610ba.png)

**Comment by ApacheThunder** [comment]
I noticed that editing the game start date/Hall of Fame Date causes the game to hang. (trainer model doesn't even show on overworld. It hangs just before it shows I guess?)

Wasn't sure I should make a new issue for this, so I'll mention it here since it's related.

**Comment by kwsch** [comment]
I was looking at the coordinate issue and found that casting between decimal and float lost some precision, and made it difficult to edit correctly. In one test the player would clip through the map -> not show up -> causing the game to hang.
