### ISSUE TITLE
Incineroar can learn Knock Off but legality checker marked it as an invalid move

### ISSUE THREAD

**Issue by rekkitcwts** [kwsch/PKHeX#4400]
**Describe the problem**
Incineroar can learn Knock Off via TM181 in SV, but the legality checker said that it is an invalid move

**To Reproduce**
Set one of the movesets to Knock Off and the legality checker said it is an invalid move, even though [Bulbapedia showed it is a valid move](https://bulbapedia.bulbagarden.net/wiki/Incineroar_(Pok%C3%A9mon)). Even online teams (including VGC teams) that use Incineroar indicate that it can have the move Knock Off.
[PK9 file here.](https://filebin.net/gya0cah348zgeabs)

**Expected behavior**
Normally it should pass the check since Bulbapedia showed it as a valid move.

**Screenshots**
![image](https://github.com/user-attachments/assets/b3904407-aaab-4d36-91bb-06ca37440f30)

**Additional context**
This is the Mightiest Mark Incineroar, but other Incineroar that do not have the Mightiest Mark can learn Knock Off in SV.

**Comment by MrPerson0** [comment]
Not a bug. In SV, when you teach a TM to a Pokemon, it gets added to its Relearn Flag, which you have failed to do.

**Comment by rekkitcwts** [comment]
Tested with another Incineroar but adding the same move (Knock Off) to the Relearn Moves also marked it as invalid -- I'm guessing these Relearn Moves are intended for Pokemon that hatched from Eggs.

![image](https://github.com/user-attachments/assets/044b344e-1b9d-4ee0-9e88-a81083378a68)

Are these Relearn Flags that you mentioned internal and can't be seen by PKHex, or are they the same as the Relearn Moves I just mentioned?

**Comment by MrPerson0** [comment]
I said Relearn Flags, not Relearn Moves.
