### ISSUE TITLE
Add Hall of Fame viewer/editor for Gen 1

### ISSUE THREAD

**Issue by pofehof** [kwsch/PKHeX#4403]
**Is your feature request related to a problem? Please describe.**
Would like to see if this can be added as a feature. Might be helpful with people wanting to clear our junk/glitched HoF data they might have.

**Describe the solution you'd like**
Allows you to view Pokemon stored in the Hall of Fame, and delete records when necessary.

**Describe alternatives you've considered**
Research has already been done in terms of where the data is stored in the save file for Gen 1 international games: https://www.pokecommunity.com/threads/the-save-file-structure-of-gen-1-hall-of-fame-data.429083/

So it is possible for people to edit it manually through a hex editor. Would like to see it through a GUI in PKHeX.

**Comment by kwsch** [comment]
Would need to be documented for Japanese games as well.
