### ISSUE TITLE
Togepi Egg from Water Labyrinth can be Method 4

### ISSUE THREAD

**Issue by notblisy** [kwsch/PKHeX#4404]
**Describe the problem**
Currently PKHeX Marks the Togepi you can receive from the gentleman in the Water Labyrinth as illegal if you get a Method 4 one. However, it is possible to get Method 1 and Method 4 PID Types on it. 

**To Reproduce**
The conditions I used were specific on retail hardware (DS) to ensure I'd get Method 4 with a near 100% guarantee, but it works on mGBA as well. 

I had 5 Hariyama in my party with a PID of 5999999B and received the egg on Initial Seed 52D2 frame 40544. (32 bit seed 388A2E32, and a Togepi with a PID 59999995). Provided in the zip is the Togepi I received along with the Hariyama I used. 

[Method 4 Togepi Squad.zip](https://github.com/user-attachments/files/18171357/Method.4.Togepi.Squad.zip)

**Expected behavior**
This Togepi specifically is able to be Method 4 because of the way its script works. 

https://github.com/pret/pokefirered/blob/2a3e92e10f8353e167874d1d2f6b311560a2a80d/data/maps/FiveIsland_WaterLabyrinth/scripts.inc#L30

The "getpartysize" script command checks the party size by seeing if the species of a Pokemon in a given party slot is "0". By having extreme values for my parties PID, we are able to effect both how long the PID % 24 takes, and the value of said PID % 24, which affects the efficiency of the switch case used to identify substructures. 

In short, making these things take a long time allow us to shift when the game is likely to blank to almost guarantee we hit a method 4 togepi. 

**Screenshots**
I've attached screenshots of my PKHeX showing it's illegal. And here is the link to my stream where I verify I hit Method 4. https://youtu.be/c8Qk9QjNvIc?t=15194

![M4Togepi1](https://github.com/user-attachments/assets/30248ff6-a021-4406-8765-32635e3f8007)
![m4togepi2](https://github.com/user-attachments/assets/5530131c-988a-426b-bf51-a5139ebd0c16)
![m4togepi3](https://github.com/user-attachments/assets/7cda1fb1-2153-4117-9247-a40c67e9e5f5)

**Additional context**
I streamed myself doing this entirely on retail, mostly without glitching(I used the clone glitch to get 5 Hariyamas so I only ha
d to manip it once. And I used ACE to change my trainers SID to make the Togepi Shiny. I obviously used RNG Manipulation to guarantee the PIDs I needed.

Despite that, the reason I did this was not to push buttons about some edge case, but because a user in my discord was going through their childhood Fire Red save, and this Togetic flagged illegal for them. So my friend Shao and I did a bit of a deep dive to see if they were lying, or it was possible, since I think the rarity of a non Box RS Mon being able to be method 4 is interesting. I'll also link screenshots of that happening. 

![Noahtogetic](https://github.com/user-attachments/assets/d07668a4-864f-4c0c-ae9f-23ca2f1571c0)
![Noah2](https://github.com/user-attachments/assets/acd3c1a0-7ac0-4f2a-9ec6-a2c3426ed805)

It's worth noting that it's also likely possible to hit Method 1 and Method 4 using similar techniques on the PCNY Wish Eggs (which were thought to be locked to Method 2). But this is just using the scripts that are available to the public, and I'm not sure if those are actual leaked event scripts.

**Comment by kwsch** [comment]
> But this is just using the scripts that are available to the public, and I'm not sure if those are actual leaked event scripts.
Pretty sure those are the real ones.

**Comment by kwsch** [comment]
For additional context, Gen3 statics have their PID Type matching logic as below:
https://github.com/kwsch/PKHeX/blob/c198ab08e0c08bc47bafaa01d0372b731dcf2ce7/PKHeX.Core/Legality/Encounters/Templates/Gen3/EncounterStatic3.cs#L179-L188
Since RS Box's emulation is "legal", it results in the laggy-Method4 spreads being possible.

Is there a rough/specific PID threshold to compare to for this Togepi encounter? Or is the only requirement having 5 high PIDs? Since Method 4 is ABC-E, I don't think it's able to be slowed further to yield Method 2 for this encounter.

In the context of Wish gifts, should be straightforward to check via single-party zero PID (and get a low PID gift?)

**Comment by notblisy** [comment]
The party alone doesn't cut it, Togepi also needs a pretty extreme PID. Vblank happened around 40k cycles after IV1 was generated. We don't think Method 2 is possible. 

For PCNY, we were able to hit Method 1 and Method 4. Used high PID Full party with a low PID Drowzee for Method 4, and a Low PID lead low PID Drowzee for Method 1.

![Drowzee M4](https://github.com/user-attachments/assets/c6237105-a0c0-4e4c-a389-779981b0a1f3)
![Drowzee M1](https://github.com/user-attachments/assets/1bb1d581-e1a6-4792-8943-88679a1e4528)
