### ISSUE TITLE
Batch Editor do not change all Pokemon's nature in the box

### ISSUE THREAD

**Issue by ELY3M** [kwsch/PKHeX#4408]
This is a bug in the batch editor.    
I put this in batch editor.    

=Box=29
.Nature=Modest  

I wanted to change all Pokemon's nature to Modest in box 29    

It only changed the Pokemon Nature in the first slot and do not change rest of the Pokemon in the box 29      

This is in Pokemon Violet game save.

**Comment by kwsch** [comment]
Use the command builder drop downs, which will tell you the value & type of the property you are interacting with. 

Nature is an integer.

**Comment by ELY3M** [comment]
I think this should be a number.... 

here is the screenshot 

![nature](https://github.com/user-attachments/assets/56648c10-b7d9-45e8-bb9d-0493277938d7)

**Comment by ELY3M** [comment]
I have been using drop downs and looking at the numbers.    
Why do it say Modest instead of a number?     It should have been a number.  
I think it is some kind of typo?  in programming.

**Comment by Lusamine** [comment]
I tried your exact batch commands in an SV save and it changed all the natures in my box 29 to Modest.
```
=Box=29
.Nature=Modest
```
Here is a video:
![basculin](https://github.com/user-attachments/assets/ee9cf2fe-1d70-4777-a0f4-ae49369bdac9)

Your program is out of date too.
![image](https://github.com/user-attachments/assets/4b425e67-d644-4a9c-b89a-aae7da33136a)
![image](https://github.com/user-attachments/assets/c17db4af-512c-4cff-852f-83e2ebfd3223)
You should only report issues that are present on the latest commit.

**Comment by ELY3M** [comment]
I will try latest pkhex

**Comment by ELY3M** [comment]
I know why now!     I had to add .StatNature=Modest  

like this       

=Box=29
.Nature=Modest
.StatNature=Modest

it is working now.      

Resolved  :)
