### ISSUE TITLE
Sun and Moon Label Misspelled: "SN" instead of SM

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#441]
![sa](https://cloud.githubusercontent.com/assets/21182549/20453301/647cf14a-aded-11e6-9494-066f24467ddf.png)

**Comment by White-Canary** [comment]
SN means Sun. Moon is labelled separately.

**Comment by sora10pls** [comment]
Like White-Canary said, "SN" is Sun and "MN" is Moon.
Not a bug
