### ISSUE TITLE
Illegal form/HA combos + incorrect form labels

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#443]
Super Size Pumpkaboo only gets its hidden ability from an event while Summer, Autumn, and Winter Deerling only get their HA from an in-game gift in gen 5. These forms are therefore illegal with their HAs if hatched in anything other than a standard Poké Ball.

Orange and White Flower Flabébé and Small and Large Size Pumpkaboo on the other hand are completely illegal with their HAs as they're not found in the Friend Safari, which is the only way to encounter those species with their HAs.

Also, Deerling and Sawsbuck's forms are incorrectly labeled. Spring is labeled Autumn, Summer is labeled Winter, and Autumn and Winter are both labeled Therian.

**Comment by sora10pls** [comment]
I would also like to point out that Flabebe has "White" listed twice under Forms; unsure if that is the case with Floette and Florges as well :)

**Comment by kwsch** [comment]
Hidden ability legality isn't something that PKHeX does -- it's left up to the user for now since rules regarding availability are subject to official events.
