### ISSUE TITLE
Keep Getting invalid option 6 after update.

### ISSUE THREAD

**Issue by rageclick** [kwsch/PKHeX#447]
IDK what happened since a couple of days ago I keep getting Invalid option '6' and fail compiling pkhex. it was fine 4 days ago. Im using MSBuild to compile. :(

this is the error : 
"C:\Users\admin\desktop\PKHeX\PKHeX.csproj" <default target> <1>-
>
<CoreCompile target> ->
      CSG : error CS1617: Invalid Option '6' for /langversion; nust be ISO-1, ISO-2
, 3, 4, 5 or Default [C:\Users\admin\Desktop\PKHeX.csproj]
                   2 Warning<s>
                   1 Errror<s>

Any solutions?
PS IM noob.

**Comment by kwsch** [comment]
PKHeX uses c# 6.0

You need to use a compiler that supports c# 6.0
