### ISSUE TITLE
Heal Bell on Gen 6 Legality Check for Eeveelutions

### ISSUE THREAD

**Issue by krelbit** [kwsch/PKHeX#448]
Heal bell rings up as illegal on gen 6 legality checks for eeveelutions, even though it can be taught via move tutor. However, I've seen that it's illegal for gen 7, so maybe something got caught up.

**Comment by kwsch** [comment]
Unable to replicate -- came out legal on my end. Did you set it as a Relearn Move accidentally?

**Comment by kamuisama** [comment]
Rowlet line also can't use Apricorn Balls...
