### ISSUE TITLE
How do I use this just to make money in game

### ISSUE THREAD

**Issue by Neshira** [kwsch/PKHeX#449]
Hello, I have no interest in creating pokemon or changing them or any such thing like that. All I want to do is give my character more money because I've found that making it is a bit more tedious in this game than previous iterations. Can this tool do that? Can it do it without altering my 3ds or anything?

**Comment by kwsch** [comment]
Trainer Info -> click the [+] next to the money box?

You need a way to obtain your save file (homebrew/cfw), both unrelated to the operaiton of PKHeX.
