### ISSUE TITLE
Trash bytes

### ISSUE THREAD

**Issue by LunarCookies** [kwsch/PKHeX#45]
Nicknames can also have trash bytes if a new nick with 2 chars or less from current one is provided.

**Comment by kwsch** [comment]
I figured that this would be the case. Thanks for confirming!

https://github.com/kwsch/PKHeX/commit/1d3b439753b731953417964cbca0a0b514d12b66

Interesting question: Would eggs traded and hatched (long OT -> short OT) have trash bytes in the OT? I'd guess that they would, but I'm not adding that unless someone confirms!

**Comment by LunarCookies** [comment]
They do have OT trash bytes. Just did a quick test with an injected egg.

**Comment by kwsch** [comment]
Thanks again :)

https://github.com/kwsch/PKHeX/commit/53cfb0d54f42cdd84403ce0eb61777e841c8c7df
