### ISSUE TITLE
Passimian and Oranguru with HAs not legal.

### ISSUE THREAD

**Issue by ForcedToRock** [kwsch/PKHeX#452]
I've almost pulled my hair out finding out why they wouldn't trade, they got the green checkmark with their hidden abilities but still. Serebii also said their hidden abilities are "available" yet they still didn't trade. This is confusing, and I only just started playing, never even encountering these two. Rowlet's another that the program deems legal with its hidden ability, but I couldn't get it to trade until I gave it the normal Overgrow ability. I'm convinced the hidden abilities of most of the Alolan pokemon haven't been snuffed out as illegal. Unless I'm mistaken.

**Comment by Gliscor** [comment]
I got the same issue with the starters and their HA's

**Comment by Tsunamical** [comment]
Interesting. Starters should be an obvious unavailable, those + fossils tend to be event only for HA. Not sure why version exclusives like Passimian and Oranguru would not have their HAs normally obtainable, that one *may* be an issue with PKHeX, or Serebii is wrong.

**Comment by flagrama** [comment]
Passimian and Oranguru are not available via calling for backup with SOS battles, therefore it is currently impossible to get their Hidden Abilities in-game.

**Comment by kamuisama** [comment]
@flagrama what about Turtonator and Drampa?

**Comment by kwsch** [comment]
Wild Hidden Ability checking has been added in the latest commit. 
https://github.com/kwsch/PKHeX/commit/a91966362434e8627d39424496c2f7a810f48da1

In terms of Hidden Ability checking for breeding, it's still undecided whether or not PKHeX will check those or if it will be left to the user to double check availability. A hidden ability banlist is not something I'm interested in maintaining ;)
