### ISSUE TITLE
Pokemon Sun/Moon trainer ID is incorrect

### ISSUE THREAD

**Issue by SydneySedai** [kwsch/PKHeX#455]
[Image comparison between the game and pkhex](http://i.imgur.com/5bT3G3u.jpg)
(apologies for the image quality but I don't have a N3DS, so I can't take direct screenshots as far as I'm aware)

So, as seen in the above image, pkhex thinks my TID is 06344, but the game says my TID is 656648.

**Comment by kwsch** [comment]
Hover over the ID boxes.

**Comment by SydneySedai** [comment]
Hovering shows a tooltip with only "TSV: 2493".
I tried hovering over the TID box on my starter though and it showed "G7TID: 656648" which is accurate, but I'm not seeing how I'd go about editing my actual visible TID.
