### ISSUE TITLE
Feature request: Unlock All Version Exclusives Clothing

### ISSUE THREAD

**Issue by kamuisama** [kwsch/PKHeX#457]
I just told that there are version exclusives clothing for Sun and Moon. Is it possible to implement a feature to unlock all clothing options including the version exclusives for your character gender?

**Comment by kwsch** [comment]
Feature requests that require researching save file structure for changes are not relevant to the operation of PKHeX (ie an Issue).

Feel free to document a before/after by using the desired [NTR/Gateshark code](http://gbatemp.net/threads/release-sumohax-pokemon-sun-moon-ntr-plugin.448255/), then reply to this issue and I'll re-open and implement.
