### ISSUE TITLE
Legality Bug of Ash's Greninja? 

### ISSUE THREAD

**Issue by koukakou** [kwsch/PKHeX#458]
The Greninja received from SuMo Demo shows illegal. Four "invalid relearn moves", and "unable to match to a mystery gift in the database". 
![greninja](https://cloud.githubusercontent.com/assets/23416118/20465413/59706f00-af11-11e6-90ef-48334448097c.png)
![greninja2](https://cloud.githubusercontent.com/assets/23416118/20465419/7df50e94-af11-11e6-8a11-d413d6c516c1.png)

**Comment by Ninjistix** [comment]
also have this issue

**Comment by SirCouve** [comment]
show the MISC tab

**Comment by Ninjistix** [comment]
![capture](https://cloud.githubusercontent.com/assets/12572974/20649843/2edba13a-b496-11e6-8d37-783bfc070126.PNG)

sorry was away for holidays, just got back
