### ISSUE TITLE
G7 Starters with HA abilitys "Legal, but not available"

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#459]
I started a random online battle with Primarina and its HA ability and the battle has been cancelled.
It' marked as legal in PKHeX, but actually starters' HA abilitys can't be obtained _(afaik)_.
I just removed Primarina from my team, and it's ok.
http://image.noelshack.com/fichiers/2016/46/1479678441-oratoria.png

**Comment by kwsch** [comment]
#443
