### ISSUE TITLE
Save Dongle .Sav File.

### ISSUE THREAD

**Issue by dew4l1fe** [kwsch/PKHeX#46]
i recently Purchased a R4i Save Dongle. installed all the firmware updates and so forth. exported my saved file of Omega Ruby to my PC. tried to load the save file in PKHex and was receiving an error about the file not being decrypted. (ive been all over google and cant seem to find a way to decrypt my files so any help in that direction would be awesome). but after receiving that error i noticed there was a brand new update to PKHex. after installing that, whenever i attempt to load/drop the .sav file into pkhex it just completely stops responding, no error messages or anything.

**Comment by kwsch** [comment]
PKHeX does not support encrypted saves, and has no compatibility with R4i Save Dongle as that only copies the encrypted content of the save.
