### ISSUE TITLE
Poké Pelago Hatched Egg Legality

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#460]
After the Hot springs are unlocked in the Poké Pelago, you may leave a Pokemon there to increase its friendship, or slowly hatch eggs.  PKHeX throws an Invalid:Invalid S/M location for hatched egg.
(On a side note, what is the id for the Met Location Poké Pelago?)
Thank you.

**Comment by kamuisama** [comment]
wow i never knew u can have eggs from there

**Comment by greenDarkness** [comment]
Yup, there's a trainer tip sign that tells you about it.
