### ISSUE TITLE
Feature Request: Batch Re-roll PID or Batch Shiny/Non-Shiny

### ISSUE THREAD

**Issue by matthewjdavis85** [kwsch/PKHeX#461]
Title

**Comment by eivanhoe** [comment]
How do you set a pokemon to be shiny?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Subforms/PKM%20Editors/BatchEditor.cs#L21-L22

use either of those as the 'set' values and the program will do exactly that
