### ISSUE TITLE
Suggestion - Import boxes in order.

### ISSUE THREAD

**Issue by Zetchzie** [kwsch/PKHeX#462]
so would it be possible to export box data and import it into another save keeping the name and order pokemon were stored into them so we don't have to sort them out afterwards.

**Comment by kwsch** [comment]
![image](https://cloud.githubusercontent.com/assets/6393368/20489757/88440f94-afc0-11e6-9044-7d40713e5f4b.png)

**Comment by Zetchzie** [comment]
thanks i didnt know what that did lol
