### ISSUE TITLE
Cottonee showing "Not a valid encounter"

### ISSUE THREAD

**Issue by khim09** [kwsch/PKHeX#463]
Cottonee showing not a valid encounter where I legally caught it. Im using build 894 and the latest upload 11-18-16 on projectpokemon

![image](https://cloud.githubusercontent.com/assets/23632975/20481729/a2426e28-b023-11e6-989f-ce843e106111.png)

**Comment by kwsch** [comment]
Fixed in the following commit:
https://github.com/kwsch/PKHeX/commit/a23cafc8d8a8a2b1c04e5bac32a4f5539434d2aa
