### ISSUE TITLE
[Legality] Zygarde Met Location

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#466]
On Route 16 you can generate a lv 30 Zygarde in a Pokeball once you have collected 10 Zygarde Cells I believe. Currently PKHeX says this is an invalid met location.

**Comment by kwsch** [comment]
`new EncounterStatic { Species = 718, Form = 0, Level = 50, Relearn = new[]{000, 000, 000, 000}, Shiny = false, Ability = 1, Location = 118, IV3 = true, }, // Zygarde`

you're the first person to report a level 30 zygarde instead of level 50.

**Comment by greenDarkness** [comment]
The 10% form is obtained at level 30. I'm unsure about 50%. I'm positive it's legal though, as I traded one out today.

**Comment by flagrama** [comment]
It depends on how far into the story you are I believe. If you generate a Zygarde pretty much as soon as you get the cube you get a level 30 Zygarde 10%. I also received one shortly after receiving the cube.

**Comment by sora10pls** [comment]
Zygarde obtained with Aura Break is Level 30.
Zygarde obtained with Power Construct is Level 50.

These apply to both 10% and 50% formes.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/4d60f60ccf9d6ff64db082d818dcd0f0c58898ee

Without furthering the story, the player can obtain 100 cores by disassembling pkm's from other trainers to get the lower leveled variant Power Construct .
