### ISSUE TITLE
Import "Set/Party" to clipboard not working in some cases

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#467]
Hi.
I want to export my team in a showdown set format, but only 3 Pokemon are generated.
http://image.noelshack.com/fichiers/2016/47/1479838204-01.png

And If I want export only the set pokémon (the first in my team) 
http://image.noelshack.com/fichiers/2016/47/1479838202-02.png

What can cause this?

**Comment by kwsch** [comment]
I believe the latest commit (https://github.com/kwsch/PKHeX/commit/ab237b970e54f076283ce60fe9f8a48af9056550 ) should fix this issue.

**Comment by kwsch** [comment]
Tested, should work now.
