### ISSUE TITLE
Export/Import Pokedex progression

### ISSUE THREAD

**Issue by GothicIII** [kwsch/PKHeX#47]
Hi,

I appreciate your hard work. The tool is working fine except for the fill all button in the pokedex tab but thats just a minor issue. Maybe you already solved it with the April'15 release.

I want to make a request for exporting/importing pokedex data from Gen6. This would be a very nice feature for those who don't want to trade all pokemon to the new cart and/or can't use Pokebank.
I didn't look into that myself but I would guess the dataformat and flags should be very similar if not completly the same inside the save files.

Thank you :)

**Comment by kwsch** [comment]
Closing; choosing not to have any I/O associated with dex binaries.

You can always copy byte arrays between save files (via a hex editor), or you can 'Fill Dex' to complete the Pokedex.

(main offset: 0x15000)
