### ISSUE TITLE
button next to ot for every gen

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#470]
Hi. I wanted to know if it was possible to have a button next to the OT on every gen for PKHeX, so that you can click it and it switches the ot tid and sid to the current save's info. When im making pokemon in sun and moon and I have to edit certain pokemon, its pretty annoying having to keep checking my tid and sid and then having to copy  and paste it. Thanks and keep up the great work

**Comment by kwsch** [comment]
Read the shortcuts via Options->About PKHeX->Shortcuts
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Resources/text/shortcuts.txt#L39

> Click on the OT label to set relevant details to that of the save file.
