### ISSUE TITLE
[Legality] Island Scan Pokemon

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#471]
There are 28 Pokemon that may be obtained via Island Scan. A list can be found here.
http://www.serebii.net/sunmoon/qrscanner.shtml
These Pokemon may be caught in 4th generation Apricorn Balls.
Chicorita, Cyndaquil, Totodile, Klink, Litwick, Deino, Venipede, Gothita, Honedge, Duosion, Axew, Serperior, Emboar, Samurott , Conkeldurr, Leavanny, and Eelectross are the only families requiring the exception.
These Pokemon cannot have their hidden abilities, as they cannot be SOS chained.
 Thank you for reading.

**Comment by kwsch** [comment]
Unfortunately, that list is not complete enough to implement. Serebii lists which island they appear on, not the exact met location it can be found at. For example, the Litwick's met location is Hau’oli Cemetery.

Pretty much need every single one to be found and logged before implementing.

**Comment by greenDarkness** [comment]
Ah, I understand. I'll do what I can to contribute to the specific Island Locations then. 
What about the Apricot Pokeball legality for for hatched Island Scan Pokemon?
Thanks for the reply.

**Comment by kamuisama** [comment]
So, all Island Scan Pokemon can't have its hidden ability?

**Comment by greenDarkness** [comment]
That is correct.
