### ISSUE TITLE
Received Gift Cosmog Flag is wrong

### ISSUE THREAD

**Issue by Leanny** [kwsch/PKHeX#476]
I noticed that the flag is set to "true" even on a completly new savegame. This does not look correct as you cannot get it before post-game.

**Comment by kwsch** [comment]
Event flag being checked prevents you from activating the event. When the story has progressed enough the game makes the event available by un-disabling it.

The current language used in the [event flag description](https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX/Resources/text/other/flags_sm.txt):
> Received Gift Cosmog

Possible changed text:
> Gift Cosmog Event Disabled/Unavailable

Double negatives aren't fun for users though.

Another possible change:
> Gift Cosmog Event Hidden

Open for suggestions.

**Comment by ricksee** [comment]
@kwsch How about Received Cosmog Post-Game ?

**Comment by blahbax** [comment]
'Cosmog gift locked' solves without double negative

**Comment by kwsch** [comment]
Eh, that isn't as clear as Received. There's always downsides to all possible descriptions. The description for the flag in question is from the same perspective as all past games, which have their event flag descriptors from the POV of a completed save.

Closing; event flags are the game's way of locking out certain events. If you haven't passed that point in the story, don't worry about story flags.
