### ISSUE TITLE
convert pk1 to pk7

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#478]
Hi I just wanted to know, will you be able to convert pk1 files to pk7 files once pokemon bank comes out for the virtual console games because that would be great if you could see how pokemon bank converts dvs into ivs and maybe you could use the same formula for pkhex. Thanks

**Comment by kwsch** [comment]
Of course; PKHeX reimplements the official transfer changes. 

Since the transfer mechanism isn't out yet, there's no need to have an open issue.
