### ISSUE TITLE
sorting pokemon that are dumped from pkhex

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#479]
Hi. I wanted to know if it is possible to make it so that when you dump all of your pokemon from pkhex it sorts the forms as well as the numbers because for instance, I have an archive of every pokemon with every single form (like unown) for every gen. when I dump the pokemon it jumbles up the forms so when i go to restore them, all of the forms are in the wrong order causing me to have to rename all of the forms once I dump them

**Comment by kwsch** [comment]
When you import the files it imports based off of the file name. The filename of saved pkm does not save the form #.

Just re-sort the box(es) when you reimport. (see the shortcuts for more info).

**Comment by NinFanBoyFTW** [comment]
Yeah I know that but it seems like it would be better if when your exporting every pokemon, the name of the pokemon with forms are named so they are ordered 

ex. with unown my names are 201 - unown a
