### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by RyDroid** [kwsch/PKHeX#48]
What is the license? Is it a free/libre one?

**Comment by kwsch** [comment]
PKHeX does not have a common license, thus I retain all rights to all code
that I have written.

However... I personally don't care if people modify the code in their own
forks or use it in other free projects. But, I do care if people try to use
my code for monetized applications. As long as money is not involved, feel
free to use my code.

ProjectPokemon is built upon shared free information :)

**Comment by RyDroid** [comment]
It would be good to clarify that in the repo. You can [sell exceptions](https://www.fsf.org/blogs/rms/selling-exceptions) to a copyleft license (like the [GPL](https://www.gnu.org/licenses/gpl.html)) or use a non commercial license (like [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) or [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)).

**Comment by kwsch** [comment]
Added GPLv3.
