### ISSUE TITLE
Default TID/SID/OT

### ISSUE THREAD

**Issue by marat569** [kwsch/PKHeX#480]
The ability to have a small .cfg file to be able to set your own default TID/SID/OT would be amazing.

Having to change the current default data (OT:PKHeX , PID: 12345) for every pokemon gets very tedious.

I do not want to fork and recompile pkhex with the strings changed for many reasons (not familiar with codebase, etc); but I'm sure adding an option to change those three default items would not be extremely difficult.

Thank you for bringing this amazing program, and maintaining it for all these years! PokeGen/Hex opened the door for battling online for those of us who have no spare time to breed!

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/470
