### ISSUE TITLE
opening pk files in their proper gen

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#486]
Hey I wanted to see if it was possible to have it so when you open for instance a pk1 file it opens in a gen 1 empty save or whatever it would normaly do. For every gen that isn't gen 7 it is kind of annoying when you open a pk 1 file or a pk 3 file and it says converted to 7th gen or whatever when you can easily do that if you actually intended to import it to 7th gen

**Comment by kwsch** [comment]
The PKM editor is directly tied to the current loaded Save File generation.
Open a save file from the desired generation first if you don't want any conversion to happen.

**Comment by NinFanBoyFTW** [comment]
I understand that but pkhex automatically opens up a blank sun save file and I dont think it would be too hard to implement this since you already have different file types for different gens

**Comment by sora10pls** [comment]
This has already been suggested in the way of a "Target Game" option, similar to PokeGen. I'm not sure if it'll be added, and and I would personally have no use for it as I have backups of save files from all 7 Generations to work with, but I can see why others would like it.

**Comment by NinFanBoyFTW** [comment]
yeah I have backups of all games too but sometimes I just want to double click on a pk file to see what the stats are or something like that. Like I said I dont think it would be very hard to implement though because he already put the pk file system in place so a pk 1 file would open up in a blank pokemon blue save for instance. It would be another story if every file gen 1 or gen 7 was just a .pk file with no number

**Comment by SciresM** [comment]
Just open a save from the desired game.
