### ISSUE TITLE
having tabs in pkhex

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#487]
This isnt a necessary change but I think it would be nice if pkhex had a tabs bar at the top like chrome or any browser. I dont know how many people have multiple pkhex tabs open at once but I know that it can be very awkward having multiple pkhex windows open at once and having to manage them when trying to gen certain pokemon. even though you can just drag them from one window to another I still think it might be a nice option for the future as a drop down option to enable or disable. Thanks

**Comment by kwsch** [comment]
Due to the way the program is structured (assumes only 1 instance of a save file), this is not possible without an obscene amount of rework.

Best to just open separate instances of the executable.
