### ISSUE TITLE
Anyway to fix the save glitch?

### ISSUE THREAD

**Issue by spicysnake** [kwsch/PKHeX#488]
The save glitch was fixed with the new version of PkHex but is there anyway to fix a game currently with the glitch?

**Comment by NinFanBoyFTW** [comment]
yeah I made a video on it here: https://www.youtube.com/watch?v=HTs-Tsx0Lbc

but all you need to do is go to your trainer info and put in some good map coordinates. here is one I have

current map: 0
X coordinate: 25927.1
Z coordinate: 19711

leave the rest

**Comment by spicysnake** [comment]
Thanks a ton, I actually tried doing that and it worked and it makes sense
