### ISSUE TITLE
sorting pokemon that are dumped from pkhex pt 2

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#489]
Hey sorry I dont mean to be a dick about this but I just used the compiled version and I completely forgot that some pokemon have different forms based on gender (pyroar, jellicent...) you dont have to change it again if you dont want to or cant that's fine I just wanted to let you know and I also think it might be potentially useful to have a male/female sign on the pk file so you can get more useful info. Thanks and you guys are the best.

**Comment by kwsch** [comment]
Too much, it's literally just a saved file name. There has to be a limit on how much detail is saved in the filename.
