### ISSUE TITLE
Explaining how creating a binary

### ISSUE THREAD

**Issue by RyDroid** [kwsch/PKHeX#49]
There is no explanation to create a binary and no file that seems to do it (makefile, configure, *.pro, etc). I have found elements that suggests that it is possible with MS VisualStudio, but is it simple? Moreover, I am interrested to know if it runs on at least one free/libre OS (like Debian GNU/Linux) and if it is possible to build this program with only free/libre tools on a free/libre OS.

**Comment by kwsch** [comment]
You can compile the program with any c# compiler.

With Visual C# Express it's easy; load the project and either build a
release or start debugging via the ribbon at the top.
