### ISSUE TITLE
G7TID editing directly.

### ISSUE THREAD

**Issue by ForcedToRock** [kwsch/PKHeX#490]
The current setup has G7TID being visible if you hover over the TID box. To change that value, the TID and SID have to change, but the problem is not knowing how to change them to fit a certain G7TID. Can there be a way to just replace the TID with G7TID through loading an appropriate save file? Then with Gen VI below, the box would become a normal TID one.

**Comment by greenDarkness** [comment]
I too would enjoy a feature like this if possible. Of course I don't understand how G7TIDs are calculated, and for all I know it could be painfully easy haha.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/455
https://github.com/kwsch/PKHeX/issues/389
https://github.com/kwsch/PKHeX/issues/383

G7TID is a derived number. You can see the derived value by hovering over the TID/SID text boxes.

**Comment by ForcedToRock** [comment]
I know about the value, I'm asking how to edit that directly without playing around with TID and SID in order to come up with a designated number. Basically, how to make the process a bit easier.

**Comment by kwsch** [comment]
Again, it's a derived number, not a stored value. You can't edit it directly. You have to edit the underlying value.

TID and SID are lossless representations of the full 32 bit value, being 16 bits each.
If you want a given G7TID, come up with any number less than 4294|967295, where the right half is the G7TID you want.

Convert to 8 digit hex; left 4 digits back to decimal are SID, right 4 digits are TID.

Alternatively, you can tweak your TID in the program and check. Just +1/-1 until you get your number or hit 65535. If you hit 65535, just reset to 0 and increment the SID by 1.

**Comment by greenDarkness** [comment]
Thank you for the explanation. This has shed a lot of light for me.

**Comment by kwsch** [comment]
First 4 digits have to be <= 4294. Pick whatever you want per the constraint.

32bits = 4294967295

G7TID = u32%1,000,000
oldTID = u32%0x10000
oldSID = u32>>16
TSV = (oldTID^oldSID)>>4 (>>3 in past games)

**Comment by greenDarkness** [comment]
So talking the oldTID to the power of the oldSID will give you a 4 digit TSV?
What does the 'u' symbolize? 
Thanks for taking the time to answer my questions by the way.

**Comment by kwsch** [comment]
[u = unsigned](http://stackoverflow.com/questions/30896489/why-is-u8-u16-u32-u64-used-instead-of-unsigned-int-in-kernel-programming)

[^](https://en.wikipedia.org/wiki/Exclusive_or#Alternative_symbols)

tid xor sid, then right shift by 4 (remove 4 lowest bits)

**Comment by greenDarkness** [comment]
You are a saint. Thanks for this feature Kathotics. Some of these concepts are way over my head. :c

**Comment by greenDarkness** [comment]
>^
> is used to denote the bitwise XOR operator. This is not used outside of programming contexts because it is too easily confused with other uses of the caret.
Oh I see. Thanks for the info. 
So since the G7TID is a derived value does that mean it's impossible/non-plausible to have PKHeX Change the TID and SID to the correct value of an entered G7TID? 
Happy Thanksgiving!
