### ISSUE TITLE
Batch editor randomize IVs

### ISSUE THREAD

**Issue by arturfelipet** [kwsch/PKHeX#491]
Hi,

just wondering, was randomize IVs supposed to work with the batch editor ? i'm trying things like .IV_ATK=$rand or .IVs = $rand but it always returns an error:

`Unable to set IV_ATK to $rand.
Unable to set IV_DEF to $rand.
Unable to set IV_HP to $rand.
Unable to set IV_SPA to $rand.
Unable to set IV_SPD to $rand.
Unable to set IV_SPE to $rand.
Unable to set IVs to $rand.`

.PID=$rand works perfectily for example.

if it's not implemented elsewhere maybe could have something like this in the BatchEditor form to have support to Batch rand the IVs ?

![randivs](https://cloud.githubusercontent.com/assets/515567/20618363/b17ec8be-b2d5-11e6-9317-4950abaca1fc.png)

**Comment by kwsch** [comment]
IV's are 0-31, so the modulo in your pic would result in 0-30.

Implementing with shortly 👍
