### ISSUE TITLE
[Sun/Moon] Froslass/Poké Pelago/Special QR code pokémon legality check issue

### ISSUE THREAD

**Issue by Naifus** [kwsch/PKHeX#492]
Hello guys, tonight I went to **Mount Lanakila** and catched a female Snorunt at lvl 44.
I evolved her by using a **Dawn Stone** into Froslass.
The wild female Snorunt had the movement "**Crunch**" but when you go to PKHeX `build 950` and you check the Froslass with "Crunch" she is flagged as an illegal (also the met location).

Here is a screenshot: https://i.imgur.com/e5Dq1eC.png

The Poké Pelago **wild Pokémon** are also flagged as an illegal (I know this is a little bit harder to fix).

The **Special** wild pokémon catched by scannig x10 QRs are also flagged as an illegal (I think that this is even harder to fix).

Screenshot of a **legit** Emboar catched by using x10 QR (he is at lvl 43): http://i.imgur.com/ydbNDT1.png

I hope that I helped you by reporting those issues. Thank you for your awesome job! (_and my apologies for my crappy English_).

**Comment by kwsch** [comment]
Unable to replicate Froslass:
![image](https://cloud.githubusercontent.com/assets/6393368/20637124/83cbbb82-b331-11e6-914f-86a18a238aae.png)

Please upload PKM file for analysis.

Poké Pelago / Island Scan are currently unsupported as nobody has fully documented met locations and level (range). Unlike regular / SOS encounters, they have to be manually added (see [scans here](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L196-L224), and [pelago here](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L244-L269)). -1 implies unknown.

**Comment by Naifus** [comment]
Here is the Frosslas PK7 file: https://drive.google.com/open?id=0Bzv0xY3FZbaaUWl4ZTJaOHJtdWs

I was using the build 950, gonna check it in the new ones now.

**Comment by kwsch** [comment]
Pelago / QR scan are still un-documented but are discussed in other issues -- they will be resolved when documentation is complete.
