### ISSUE TITLE
Game crash when seeing sample to dye in festival plaza.

### ISSUE THREAD

**Issue by kamuisama** [kwsch/PKHeX#493]
So I just got this error. Chronology: Go to Festival Plaza > Dye Shop > Select Dye (top option) > view samples > crashed happen. Is it because the unlock all outfits thingy? :(

**Comment by kwsch** [comment]
I haven't heard any problems from anyone regarding this issue, is anyone able to replicate?

**Comment by fadeZero** [comment]
happened to me once, when i have used the Unlock every clothes button

**Comment by noakei** [comment]
Same error here after using the unlock all clothes button

**Comment by noakei** [comment]
most likely the error is due to giving all the recolored clothes, legally you can only have 1 recolor of every given piece at a time, that substitutes the white one.
