### ISSUE TITLE
PKHeX and Pokemon Battle Revolution.

### ISSUE THREAD

**Issue by NaturalHarmonia** [kwsch/PKHeX#494]
On the Project Pokemon forums about a week ago I read about a build/version of PKHeX being compatible with Pokemon Battle Revolution save files. I've tried 3 builds and I just downloaded PKHeX from here and tried as well. None of those worked. So is it really possible or not? I just want to edit my PBR save file. Thanks.

**Comment by kwsch** [comment]
Are the PBR save files decrypted?

It's not obvious what exactly you are opening or what error messages you are receiving, so any feedback would be appreciated.

**Comment by NaturalHarmonia** [comment]
I used an old version of Savegame Manager GX to extract the PBR save file from my Wii. Sorry, I'm not really sure if it is or not. I'll upload the save file if you want.

**Comment by NaturalHarmonia** [comment]
The error I got was "Attempted to load an unsupported file type/size."

**Comment by SciresM** [comment]
The save file is genuinely corrupted.

Also, you don't even have any pokemon in the single save file you created? (Link).

Have you saved twice in-game? That could theoretically be necessary.

**Comment by NaturalHarmonia** [comment]
I tried another save file that has Pokemon and it still didn't work.
