### ISSUE TITLE
Ability Capsule in an incorrect category.

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#495]
It appears that the program thinks that the Ability Capsule is an item and not a medicine. As such, when I buy them in game and then open my bag in this program, it states that my ability capsules have been removed, even though they were in the correct pouch.

**Comment by fortran-favors-the-old** [comment]
I observe similar behavior.  If a Pokemon is holding an Ability Capsule and I remove the item in-game, it is placed within the Medicine pouch and not the Items pouch.
