### ISSUE TITLE
Various issues with Colosseum/XD/Sun&Moon

### ISSUE THREAD

**Issue by Ale1998** [kwsch/PKHeX#496]
Hi, I've experienced various issues using PKHeX with different games:

### Pokémon Colosseum:

- Pokémon are not appearing in-game after you finish editing them. Their former spots in the box show up as empty.
- The "Trainer Info" option pops-up with a large error message: http://pastebin.com/PzNLhcpg
- The "Item" option loops the "Unknown item detected" pop-up window.

### Pokémon XD:

- Pokémon are not appearing in-game after you finish editing them. Their former spots in the box show up as empty (same problem I had with Colosseum).
- The "Trainer Info" option pops-up with a large error message: http://pastebin.com/E3CfxXzk
- The "Items" option pops-up with a large error message: http://pastebin.com/ngs0xqws

### Pokémon Sun&Moon:

- When you try to export main after clicking "Complete Dex" (inside of the "Pokédex" option), it shows up the following error message:

"0x200 chunk @ 0x3000 is FF'd.
Cyber will screw up (as of August 31st 2014).

Problem lies in the Pokédex.

Continue saving?"

Thank you for your attention.

**Comment by kwsch** [comment]
Cyber save editor has issues when saving certain values.
If a chunk (0x200 bytes) is all 0xFF, the device thinks it is is uninitialized data, leading to the encryption failing => invalid save.

Not sure how authentic your trainer info for XD/Colosseum saves are; the only index is player gender. Items that are out of range.

Please send me the save files in question for debugging; a PM on IRC or email/forum message (when they are back) is fine.

**Comment by fortran-favors-the-old** [comment]
Regarding the Sun/Moon Pokedex issue, I wonder if that is due to Sun/Moon not having a National Dex and just the Alolan Dex, which has entries for only 302 Pokemon. I noticed that even for Sun/Moon, the "Complete Dex" option sets (among other things) "Caught" flags for Pokemon not in the Alolan Dex.

@Ale1998 : after clicking "Complete Dex" and writing out the save file, are you then able to restore that save to your game and load the game successfully? Does the game treat the save as corrupt?

**Comment by kwsch** [comment]
I've changed the complete dex to not give zh2 Petilil entry so that no contiguous 0x200 chunk is all 0xFF.

**Comment by fortran-favors-the-old** [comment]
Thanks @kwsch . Out of curiosity: since there is no National Dex in Sun/Moon, is it not harmful to set "Seen", "Caught", etc flags for Pokemon not in the Alolan Dex?

**Comment by Ale1998** [comment]
@kwsch [Here](https://filetrip.net/view?uq0CrSi848) are the savefiles. It's worth mentioning that they have been created after running PAL backups with Citra. I've edited the first row of the main box in both savegames, so they will not appear in-game because they're "invalid".

@fortran-favors-the-old I haven't tried to save after having the "Complete Dex" issue, because I've been busy finishing the game and I didn't want to mess up my save file.

I can do it if it's neccesary, though. But it doesn't seem like it after reading kwsch's comment.
