### ISSUE TITLE
shit aint workin

### ISSUE THREAD

**Issue by craftsygaming** [kwsch/PKHeX#497]
![01](https://cloud.githubusercontent.com/assets/23726260/20636032/69149878-b32b-11e6-8a21-134c53efe1ea.PNG)
![02](https://cloud.githubusercontent.com/assets/23726260/20636033/6b612254-b32b-11e6-94eb-464c57d655ad.PNG)
![03](https://cloud.githubusercontent.com/assets/23726260/20636036/6e95d8fc-b32b-11e6-8a58-5cb60134f022.PNG)

**Comment by greenDarkness** [comment]
![image](https://cloud.githubusercontent.com/assets/15519892/20636191/8316314a-b336-11e6-8787-7008b2afe29a.png)

**Comment by kwsch** [comment]
>Transfer required

wow its almost as if transferring is required

wonder if that's possible yet?
