### ISSUE TITLE
Trade banned save.

### ISSUE THREAD

**Issue by ForcedToRock** [kwsch/PKHeX#498]
Is there a way to reverse that with PKHex? My save was banned due to forcing a power interruption, a shut down so I could correct an issue with a request without having to do a second trade. This is what the ban message looks like, not some error code.

![gimp](https://cloud.githubusercontent.com/assets/10488946/20636310/c2a49188-b338-11e6-845b-5488aa84d4e0.png)

Restoring an older save does the trick, but my issue is getting back the privilege without resorting to that, and not waiting the not-set-in-stone time period.

**Comment by kwsch** [comment]
99% sure it's a server side ban since an old save file does not unblock you.

**Comment by ForcedToRock** [comment]
It does unblock me, I never used Game sync, the old save file is from 6 days ago, same trainer info and everything, just at a point where I first got Festival Plaza, and being able to do trades there. About 12 hours so far since the newer save got temp-banned, other people reported this in different forums, some say upwards of 48 hours, one said 70 hours, another said 10 minutes.

**Comment by kwsch** [comment]
Ohh I misread.

It's probably a certain flag that is set when you enter, and reset when you leave. Look for a single bit flip.

Possible game methods:

```
signed int __fastcall NetAppLib::Util::NetAppEntryChecker::CheckTradePenalty(int a1)
{
  signed int v1; // r4@1
  int v2; // r0@1

  v1 = 0;
  v2 = gfl2::base::SingletonAccessor<GameSys::GameManager>::GetInstance(a1);
  if ( !sub_4A7608(*(*(v2 + 0x24) + 4) + 0x4EF20) )
    v1 = 1;
  return v1;
}
```
It doesn't line up with any offset off the top of my head.

Still looking:
```
_BOOL4 __fastcall Savedata::GameTime::IsPenaltyMode(Savedata::GameTime *this)
{
  return *(this + 0x10) != 0;
}
```
Savedata::GameTime is at 0x04600, if you subtract 4 for the memchunk header (obvious if you dumped RAM there's 32 bits used at the front before the actual data begins), the offset would be 0x0460C. Try checking before/after for that offset.

**Comment by blahbax** [comment]
Yeah I was the 10 minute guy. I wasn't waiting 72 hours so I tried importing my save again, I'd literally only just imported it. If you're Hexing regularly, it's not an issue as you always have a current save to import.

**Comment by ForcedToRock** [comment]
How would I go about reporting it? I did ram dumps and I think I found the offset, the value is different.  
  
Before the ban.
![oldoffset](https://cloud.githubusercontent.com/assets/10488946/20637333/d0847862-b352-11e6-863a-6b35a11fe700.png)

After 
![newoffset](https://cloud.githubusercontent.com/assets/10488946/20637334/d6114d3c-b352-11e6-9b9e-8dffe1d91b31.png)

**Comment by kwsch** [comment]
Naw, you have to dump the save file not RAM.

**Comment by ForcedToRock** [comment]
How about this then?

Unbanned save: 
![oldsave](https://cloud.githubusercontent.com/assets/10488946/20638195/35fbd7fc-b36d-11e6-8264-d32375378170.png)

Banned save
![newsave](https://cloud.githubusercontent.com/assets/10488946/20638198/3a606efc-b36d-11e6-99c7-0425e1ea951a.png)

**Comment by ForcedToRock** [comment]
I guess it's a moot point now that the save is no longer banned. About 36 hours. Lessons from this: never shut off the console during a trade or battle (i.e. ragequitting). backup your save regularly.
