### ISSUE TITLE
Trainer is invisble after overwriting and importing a save edit with the "official" build? 

### ISSUE THREAD

**Issue by proflayton123** [kwsch/PKHeX#499]
The problem is in its self, im quite worried. Its a fresh save, but still, at the start of the game..

**Comment by kwsch** [comment]
It's a known bug with the latest release, but the source code here has been fixed for a week. You can always grab it from the continuous integration server (accessible via each commit's green checkmark).

Next official release should be soon, but a few more things to patch up.

**Comment by proflayton123** [comment]
Aah, ok. Im using the "nightly" builds with no problem tho
