### ISSUE TITLE
Feature Request: View/Edit Festival Plaza Player Data

### ISSUE THREAD

**Issue by ChaoticKyuubi** [kwsch/PKHeX#501]
As title says is it possible in the future for us to view/edit our festival plaza player data via pkhex since iirc theres no way to view your own festival plaza data unless u have a friend that tells you your own data or another 3ds to view ur own player data there

**Comment by kwsch** [comment]
Feature requests that require researching save file structure for changes are not relevant to the operation of PKHeX (ie an Issue).

Has to be researched by the community before it can be implemented as a feature.
