### ISSUE TITLE
Alola Vulpix Invalid: Unknown Encounter

### ISSUE THREAD

**Issue by kevin791129** [kwsch/PKHeX#503]
Transferred a alola vulpix caught in Tapu Village from Sun to Moon.

Even without editing the Pokemon, by just viewing the Pokemon, I am getting an invalid error.

**Comment by kwsch** [comment]
Are you using the latest commit or the latest release?
https://github.com/kwsch/PKHeX/issues/456

**Comment by kevin791129** [comment]
Tried the latest release, works perfectly.
Thanks
