### ISSUE TITLE
Invalid save file

### ISSUE THREAD

**Issue by Balmung42** [kwsch/PKHeX#506]
I managed to export my save file(sun) via r4i and pkhex claims that the save isn't a valid save (i've made a couple since).  Am I doing something wrong or does the save need to be exported through certain things only?  I'll attach save file incase you want to look at it.  Anything else I can do to help just let me know.

[SunSave.zip](https://github.com/kwsch/PKHeX/files/614420/SunSave.zip)

**Comment by kwsch** [comment]
PKHeX cannot decrypt 3DS save files. An r4i is insufficient -- use homebrew or custom firmware (both unrelated to PKHeX).

**Comment by Balmung42** [comment]
Aye, wasn't sure.  Thanks for reply.
