### ISSUE TITLE
extention to #505

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#509]
Hi I just wanted to add as a possibility for the future in addition to the things mentioned in #505 it would be nice to have the sprites of the items in the item pouch when you open it. When you open the item pouch now there is a large gray space to the right of the names of the items and I think it would help a lot to have the pictures of the items for clarification of the items and obviously looking more polished. I saw most of the items in the same project listed at #505. I would also love to be of assistance to you if you need any help. I have pretty good photoshop skills and it wouldn't be hard to get together the rest of the items or anything else that we would need. Thanks

**Comment by kwsch** [comment]
Problematic in that past generation sprites aren't the same dimensions (32x32), and that certain ItemID values between generations correspond to different items.

The current row height of the Inventory Editor data grid would be stretched (it's ~22 px not 32) so it'd vertically stretch everything out. I don't think it's a good idea.

**Comment by NinFanBoyFTW** [comment]
I agree that it possibly could add visual noise but I was playing around with the size of the item editor and I dont think that switching the size to fit the sprites would make it look any worse. Like I said before I think it would be a shame to have the item editor and have a huge gray column next to it instead of the sprites or whatever else. to the point of the itemID values that would be something to sort out manually I would assume but like I said this would be a future thing to really polish out some of the menus of pkhex and make it easier to not get confused with certain items ex. (focus sash and focus band)
