### ISSUE TITLE
Suggested Moves not level based; applies illegal move sets, legality checker gives OK

### ISSUE THREAD

**Issue by blahbax** [kwsch/PKHeX#510]
When you double click the moveset of a low level Pokemon, the 'suggested moves' are often illegal. It suggests, applies high level, non-egg moves and the legality checker gives it the green tick. I have attached 4 screens relating to a level 5 Rowlet:

1. Main Screen showing level 5 Rowlet I'm working on

![screenshot 463](https://cloud.githubusercontent.com/assets/23710592/20645158/3b7089b6-b4a9-11e6-936e-0453a489a92a.png)

2. What the moveset should look like at level 5

![screenshot 464](https://cloud.githubusercontent.com/assets/23710592/20645161/4285520e-b4a9-11e6-846c-75b304f1ebbd.png)

3. Suggested (illegal) moves

![screenshot 465](https://cloud.githubusercontent.com/assets/23710592/20645162/451e9d5e-b4a9-11e6-8b0d-3e14617926b9.png)

4. Passes Legality check

![screenshot 467](https://cloud.githubusercontent.com/assets/23710592/20645167/679d215c-b4a9-11e6-8b6e-a447323b500f.png)

Feather dance, Brave Bird & Nasty Plot aren't learned til >= 39 and aren't inheritable.

**Comment by lomejor18** [comment]
maybe pkhex should set the last 4 attacks under the level? or perhaps learnable TMs?

**Comment by kwsch** [comment]
Move tutor (heart scale) can now teach moves from any level; I can see what I can do to have this check bypass this.

**Comment by blahbax** [comment]
Ah cool so they aren't actually illegal. Yeah a bypass would be awesome - not sure about other users, but when I use that double click feature, trying to create stock Pokemon on the fly.

**Comment by kwsch** [comment]
The old behavior before adding the relearner -> level 100 behaved exactly as you're asking. Shouldn't be too hard to adjust.
