### ISSUE TITLE
Batch Editor: Randomize Nature/Valid Abilities

### ISSUE THREAD

**Issue by froslumugu** [kwsch/PKHeX#512]
Is there any chance of having a variable in the Batch Editor to set the Pokemon's Nature and Ability to random ones, much like $rand does for IVs/PID/EC?

**Comment by lomejor18** [comment]
random pokeball, level and helditem would be nice too!

**Comment by lomejor18** [comment]
does the batch editor set memories? now that we now 7º gen pokémon can't have memories, it would be usefull erasing it in a row...

**Comment by kwsch** [comment]
@lomejor18 You can always set them to 0.

```
=GenNumber=7
.OT_Intensity=0
.OT_Memory=0
.OT_Name=0
.OT_TextVar=0
.HT_Intensity=0
.HT_Memory=0
.HT_Name=0
.HT_TextVar=0
```

The batch editor is not intended to be a randomizer; the randomization is only to differentiate clones.
Ability is handled multiple ways in different generations (ie, Ability Number and actual Ability ID), and Nature is tied to PID in gens 3/4. There has to be a limit on what it does.

**Comment by lomejor18** [comment]
@kwsch thanks for the info! BTW, ".HT_Name=0" doesn't clear latest handler, just set "0" as a name... thanks for everything!

**Comment by xXAquaNightXx** [comment]
Just leave it as .HT_Name= and run it and it should clear it, had the same problem too

**Comment by xXAquaNightXx** [comment]
Just running it as ".HT_Name=" would clear the name in the latest handler section providing your OT Name, TID and SID match the save file you loaded up
