### ISSUE TITLE
batch editor how to make pokemon shiny

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#513]
I just wanted to know how to make pokemon shiny in the batch editor. I figured out some of the items but I couldnt figure out how to make them shiny

**Comment by lomejor18** [comment]
@NinFanBoyFTW 

.PID=$shiny

(i don't know every single command, i would like to know where to find them)

**Comment by NinFanBoyFTW** [comment]
thanks
