### ISSUE TITLE
Hyper Training/Bottle Caps support?

### ISSUE THREAD

**Issue by vonKoenigsberg** [kwsch/PKHeX#518]
Am I overlooking something or is it not implemented?

If it isn't, does editing a pkm corrupt Hyper Training data and is support planned?

It would be quite useful to minmax hidden power sets.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/8ade9b21c73385f90e7644cfec8f1d5cbe5ab2ec

https://github.com/kwsch/PKHeX/blob/master/PKHeX/Resources/text/shortcuts.txt#L18-L21

**Comment by vonKoenigsberg** [comment]
Very nice. Ty.
