### ISSUE TITLE
Hack Compatibility Issues

### ISSUE THREAD

**Issue by NinetyPercentSpiff** [kwsch/PKHeX#521]
I'm attempting to use PKHeX with a hacked ROM that changes sprites, base stats, moves, and adds Pokemon outside of the National Dex. I'm having two issues, one that I understand and one that I can't figure out what is causing it.

1) The out of dex Pokemon (any Pokemon added by the hack past dex number 386) show up as empty slots and cannot be viewed or edited in PKHeX, although exporting the save does not remove these Pokemon when loaded up by the hack.
2) Some Pokemon are not loaded properly by PKHeX. The level, species, shininess, and a few other traits appear properly when the Pokemon is viewed, but traits such as moves, EVs, IVs, nickname, ball, origin game, and met level do not appear.

Messing around with PKHeX (and PKHaX) to try and understand what is causing issue 2 has resulted in even more confusion, since even some Unown forms are loaded properly while many others are not. One Unown R is loaded properly, while another Unown R is not. I would appreciate it if there was some way to get PKHeX to view all of the traits of these Pokemon.

As for issue 1, I only suggest that there be some way to view and edit Pokemon added by hacks outside of the National Dex.

**Comment by NinFanBoyFTW** [comment]
I dont know what rom hacks your using but obviously pkhex wont be adding rom hack support when it comes to fake pokemon and base stats. If your using something like liquid crystal I had a similar problem with the unowns but that was a liquid crystal problem and not pkhex

**Comment by kwsch** [comment]
PKHeX only supports main series games, not modified ROM save files. It is unknown what changes were made to the storage structure to 'enhance' the hack.
