### ISSUE TITLE
QR string to data failed

### ISSUE THREAD

**Issue by ShadowzI** [kwsch/PKHeX#522]
Unable to transfer QR code into PKHeX

**Comment by NinFanBoyFTW** [comment]
are you using the most recent compiled version from github because they have been fixing many things over the past 2 weeks. Also what do you mean by transfer QR code "into" PKHeX

**Comment by kwsch** [comment]
Please post a QR url and confirm that you are using the latest commits (not latest release).
[Changes to this area were made 6 days ago](https://github.com/kwsch/PKHeX/commit/0a6228ff0b2022f7dfab6f6786c629afa5bc866f), probably fixing the issue you are experiencing.

**Comment by ShadowzI** [comment]
I looked it over and both of you are right.

Any QR codes created from the previous version has issues when being read with the new version.

Posting one right now.
http://i.imgur.com/9rQkH2E.png
