### ISSUE TITLE
PKHex throws error when exporting to a Network Drive (FTP)

### ISSUE THREAD

**Issue by marat569** [kwsch/PKHeX#523]
![image of error](http://i.imgur.com/SR9yciq.png)

So, I've created a FTP server on the 3ds (ftpd) [works 100%], then proceeded to create a windows network drive that connects to the server, and basically emulates a regular drive.

When using the Windows Explorer to browse the files like normal, everything is fine.

Loading the main from the network drive works. Though PKHex does not auto detect the main's location like it does when I insert the SD card, manually browsing opening the main works.

After trying to export the main via pkhex, the error pops up. I end up having to export to my desktop and use windows explorer to drag the main file to the proper folder.

What I'd like:
1*: PKSav being able to export into these net drives c:
2(optional): Auto loading main file from a net drive like it does via SD card.

Some info:
OS: Windows 7.1 Ultimate 64x
PKHex: 1.0.7 (Release: 11/18/16, Initial Sun/Moon support)
FTP Server: https://github.com/mtheall/ftpd

How to create a network drive (w7)
1. Go to My Computer
2. Right click > Add network location
3. Choose custom network location
4. For address type: "ftp://ipaddress.com:port
5. done, net drive will appear in my computer like any normal hard drive

Side note: What are you guys planning for the next official stable release? I've been seeing a lot of awesome commits c:

Thank you!

**Comment by kwsch** [comment]
It's a c# limitation:

http://stackoverflow.com/questions/3098486/cannot-access-files-on-drive-mapped-network-share-from-a-windows-service

**Comment by marat569** [comment]
@kwsch that says cannot access in general; thing is I can open the main from netdrive no problem; its just saving that throws the error.

Any suggestions other than having to drag the main; trying to get my lazy-boy setup going c:

**Comment by kwsch** [comment]
Still, that's not a PKHeX error.

Try resolving the full path it's trying to save to (ie, the 'url'). Possible that it's an illegal path (a colon : in the path) that prevents it from saving.
