### ISSUE TITLE
Feature request: Edit Poke Finder points

### ISSUE THREAD

**Issue by onmyouji** [kwsch/PKHeX#524]
Can I request this feature?

The points are useful to upgrade the [Poke Finder version.](http://www.serebii.net/sunmoon/pokefinder.shtml) 

![versionup](https://cloud.githubusercontent.com/assets/8424198/20697745/306d09be-b62e-11e6-99bf-50b5ef3e2a02.jpg)

Thanks

**Comment by kwsch** [comment]
Can you open your save file in a hex editor and show me 0x65000 ?

**Comment by onmyouji** [comment]
Sorry, can you guide me how to do that? I already download HxD, what's the next step?

Do I just choose "Go to" and type "65000"?

**Comment by kamuisama** [comment]
+1 for this feature :+1:

**Comment by kwsch** [comment]
@onmyouji yes

**Comment by onmyouji** [comment]
Here's the hex:

![hex](https://cloud.githubusercontent.com/assets/8424198/20737421/239001e0-b6df-11e6-90be-af608fa65dff.png)


And current in-game values:

![img_20161130_091226](https://cloud.githubusercontent.com/assets/8424198/20737436/48d2890a-b6df-11e6-9715-79fd66a100c4.jpg)
