### ISSUE TITLE
[Request] Edit Natures from the Stats Tab

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#525]
The feature that I'm requesting would work something like this. If you add a + and - pair before the EVs in the Stats tab, the the nature would change accordingly. IE If you wanted to change your nature to Adamant, you'd just at a + to the Attack EV box, and a - to the Sp Attack EV box. 
Thank you for reading.

**Comment by kwsch** [comment]
Nah, too much clutter. Just hover over the Nature combobox to see what the stat amps are.

**Comment by greenDarkness** [comment]
How about Ctrl clicking to set the boosted stat, and Alt clicking to set the reduced stat? This would really save time if it's not a huge amount of trouble.
Thanks for the swift response.

**Comment by marat569** [comment]
On the topic of natures; I find it strange why blue = minus stats, red = plus stats
Psychologically we're conditioned to red = bad, blue = good

**Comment by kwsch** [comment]
http://www.gamefaqs.com/boards/960100-pokemon-soulsilver-version/54448256

**Comment by marat569** [comment]
@kwsch I know that's how it is in game, but doesn't mean I agree with it -- nor does it make sense.

Blue should be possible, Red hindering

If you want to stick to game colors, that's cool; but adding a +/- in front of say "Attack"; not having just the color would be a small quality of life change

**Comment by bournejason** [comment]
If you are not used to red = plus, blue = minus, you are not a true pokemon trainer:)

**Comment by greenDarkness** [comment]
I like the colors the way they are, but I don't really have a preference whether or not they're changed. But I would like a way to change natures from the stats tab; similar to the way the teambuilder on Pokemon Showdown functions. Assuming it isn't a lot of trouble, or a hassle to do.

**Comment by kwsch** [comment]
The joy of the program being open source is that anyone can make modifications.

I don't see a need to duplicate controls across multiple tabs, or add extra indication. Both tabs are already quite full with information; no need to add clutter.
