### ISSUE TITLE
[Request] Specify amount for "Give All Items"

### ISSUE THREAD

**Issue by fixotherm** [kwsch/PKHeX#526]
Sun/Moon doesn't have a toss function, and it'd be hard to sell every time.

**Comment by bui** [comment]
If not, I'd like to suggest the 999 to be lowered to something like 900. In-game, you can't pick up items if you already have 999 of them, which is always a bit annoying.

**Comment by fortran-favors-the-old** [comment]
@kwsch: Thanks for adding this option!  It will be very useful.

However, with the latest commit bfc6733a25f8140ce1b20d7f777f602311b1e19c, this appears to be broken.  Whenever I click any of the "Give All" buttons in the Inventory Editor, the "Count" field resets to 1, regardless of the value I specify in the Count field beforehand.

**Comment by fortran-favors-the-old** [comment]
Thanks for the very rapid fix!
