### ISSUE TITLE
Festival Coin editing error 

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#527]
So this is a simple error, but when editing Festival Coins in the trainer ID section, it appears to edit the total amount of Festival Coins collected which allows quick leveling of the Festival Plaza but doesn't change your actual currency amount at all.

Example: I had 243 coins in total and 243 total collected on record. When I increased the value in PKHEX to 443, the amount of lifetime collected increased to 443, but I still only had 243 coins to spend.

**Comment by kwsch** [comment]
Duplicate with #475
