### ISSUE TITLE
Starter ball legality

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#529]
Alola starters are currently marked as legal if bred in any ball available in SM, pretty sure they can't be caught in the wild so they should be illegal in anything other than a regular Poké Ball.

**Comment by bengeminuy** [comment]
You can breed it with another female pokemon having a different ball and it would then inherit the female parent's ball so it's possible.

**Comment by lomejor18** [comment]
@bengeminuy the baby will be the same mother's species, never the father's... so, 7º gen starters can't have special balls, only pokeball -_-

**Comment by TCJJ** [comment]
@lomejor18 But males can now pass down balls, so you could breed a female Gen 7 starter with a male of another species that is compatible, and potentially end up with a different ball.

**Comment by kamuisama** [comment]
Here's the rule of ball passing in gen 7

A -- There is 50/50 split of passing the ball down only if the parents are the same species.

B -- If one of the parents is a Ditto, the non-Ditto parent will pass down their ball 100% of the time.

C -- If two different species are breeding, the mother will pass down the ball 100% of the time.

so based on this, i think it's still impossible to have gen 7 starters in any ball other than regular pokeball.

**Comment by lordxiad** [comment]
1. Breed starter with Ditto until you have male.
2. Breed male starter with non-starter female with desired ball.

Pretty sure Popplio is usually male anyway, as well as the others only most of the time being female.

**Comment by lomejor18** [comment]
@TCJJ @lordxiad  look, as @kamuisama said, male pass pokeballs only with ditto and same **species female**, the child always will be the same of the mother's... EX: Male popplio + Female Squirtle = baby Squirtle

by the way @kwsch, i believe that fossils can not be on special balls, only pokeball (until pokebank's release on january)

**Comment by onmyouji** [comment]
@lomejor18 
Seems like many PKHex users have never bred a pokemon themselves :D

**Comment by lordxiad** [comment]
Looks like you guys are correct. Shouldn't brain that late at night. Here's some detailed information: http://www.neoseeker.com/forums/90765/t2223390-sun-moon-breeding-guide/

**Comment by bournejason** [comment]
wow, seems gen7 has some big changes at the ball type heritage, previous generations children can only inherit their mother's ball.

So, I still have a question@kamuisama, what about the non-type? can they breed with special ball now?

**Comment by bournejason** [comment]
wow seems gen7 made some big changes with the breed mechanism, children have a chance to inherit ball types from both parents now instead of only mothers in previous generations.
So, I still have a question, how about the non-gender like Beldrum? Is there a way to inherit ball type?
