### ISSUE TITLE
Missing reference when building from latest commit

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#53]
Tried to build PKHeX with the latest commit using Microsoft Visual Studio 2012 and I got this warning. Might be worth looking into Kaphotics.

[Image](https://cloud.githubusercontent.com/assets/4019718/9426287/6a751a40-4936-11e5-8980-82bdc86435ca.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/cf94b1caf0553250415a8230ac013e650960bc86/PKHeX.csproj#L64

Probably should try deleting that line to see if it is really necessary.

**Comment by Favna** [comment]
That did it indeed :+1:

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/a140cefa09e27e45439cfca6804ac526e8645dce
