### ISSUE TITLE
[Request] Edit current win streak on Battle Tree

### ISSUE THREAD

**Issue by jfgoncalves** [kwsch/PKHeX#530]
I think that'd be nice if we could edit our current Battle Tree win streak just like in XY/ORAS.

**Comment by kwsch** [comment]
Needs to be documented first.

Data is stored at 0x6B200

```
int __fastcall Savedata::BattleInstSave::GetWinCount(int a1, int a2, int a3)
{
  int v3; // r0@1
  int result; // r0@2

  v3 = a1 + 2 * a3;
  if ( a2 )
  {
    if ( a2 == 1 )
    {
      result = *(_WORD *)(v3 + 0x0x0C);
    }
    else if ( a2 == 3 )
    {
      result = *(_WORD *)(v3 + 0x14);
    }
    else
    {
      result = 0;
    }
  }
  else
  {
    result = *(_WORD *)(v3 + 0x04);
  }
  return result;
}
```
```
int __fastcall Savedata::BattleInstSave::GetMaxWinCount(int a1, int a2, int a3)
{
  int v3; // r0@1
  int result; // r0@2

  v3 = a1 + 2 * a3;
  if ( a2 )
  {
    if ( a2 == 1 )
    {
      result = *(_WORD *)(v3 + 0x10);
    }
    else if ( a2 == 3 )
    {
      result = *(_WORD *)(v3 + 0x18);
    }
    else
    {
      result = 0;
    }
  }
  else
  {
    result = *(_WORD *)(v3 + 8);
  }
  return result;
}
```

**Comment by jfgoncalves** [comment]
I only have a "main" save file. How do I go from there? Do I just open the file in HxD?

**Comment by kwsch** [comment]
@jfgoncalves refer to #524

**Comment by ricksee** [comment]
@kwsch Like this?
![seddd](https://cloud.githubusercontent.com/assets/21182549/20805799/41703a8a-b7c6-11e6-91e7-05bf1bd00bc4.png)

**Comment by ricksee** [comment]
@kwsch @evandixon I don't know if this helps but here is my save file.

![ed](https://cloud.githubusercontent.com/assets/21182549/20868420/4f33dac2-ba29-11e6-9136-ad3fd9b6f23f.png)

**Comment by ricksee** [comment]
@kwsch @evandixon When you hit a 20 battle streak, Super Battles are implemented. Dexio, Sina, Wally, Grimsley, Colress & Cynthia can be encountered every 10 battles.

**Comment by RGreywind** [comment]
if you can edit the records in the battle frontier of 4 gen games will be awesome
