### ISSUE TITLE
Fatal non-UI Crash on MacOS 12.1 Wine

### ISSUE THREAD

**Issue by alchemistake** [kwsch/PKHeX#532]
When I try to use latest PKHeX.exe and latest Wine this error happens:

> A fatal non-UI error has occured in PKHeX, and details could not be displayed. Please report this to the author

So I am reporting :D

**Comment by evandixon** [comment]
What were you doing before you got the error?

(Note to devs: this message means an exception occurred in the Error Window when trying to display the details of another exception)

**Comment by alchemistake** [comment]
Whenever I open PKHeX through Wine it gives this error 3 times, immediately.

I would like to help, Is there a way to get into Error Window without raising errors?

**Comment by kwsch** [comment]
Are you using the Mono build or the .NET build?
