### ISSUE TITLE
Batch Editor: Changing the game origin 

### ISSUE THREAD

**Issue by CD877** [kwsch/PKHeX#533]
Was just wondering was the code would be for changing everyones game origin to 'Moon'. 

Side note: if theres a correct format into changing met date = today that would be super handy 

Thanks

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Resources/text/en/text_Games_en.txt

LineNumber - 1 = GameVersion

so for Moon:

.Version=31
