### ISSUE TITLE
Gen 2 Errors

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#534]
Im just opening this back up here because I found another error and I didnt want to make more edits

for gen 2 when you dump the pokemon, it does not show the star symbol on the file name when shiny and it doesnt show the form number for pokemon like unown

also if it is possible I think it would be nice to have a "reroll" feature like the one on other gens to change the dvs otherwise it is kind of awkward and confusing to get rid of a pokemon being shiny

 I also cannot get a shiny unown with the letter I. I know you can only have a shiny unown with the letters I and V but I can only get V to work

**Comment by kwsch** [comment]
Can always specify the IVs to get the "I" form.

Currently the shinitize button sets to the best shiny IVs, but I'll change it so that the ATK IV is random.
