### ISSUE TITLE
Pokesnap Editor Error: Snap Count resets

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#537]
Whenever you edit the PokeSnap data or edit anything in the trainer info tab, the Snap value is automatically set back to zero even though its supposed to be able to be set to any desired value, it just sets it to zero every time

**Comment by onmyouji** [comment]
I just tried this with my save file, you're right, the "Snap Count" is always reset back. But it's reset back to 1, not 0.

Btw, does this Snap Count value can be viewed in-game? In Poke Finder, you can view the Total and Record thumbs-up, but I don't see the Snap Count value anywhere in-game.
