### ISSUE TITLE
Memory doesn't work??

### ISSUE THREAD

**Issue by edwarbad23** [kwsch/PKHeX#542]
When I created 6th gen Pokemon I always put something in memory ex. A created hatched pokemon from egg in memory always put "hatched from a egg and saw..." and marked me legal!! But in this gen and in this Pkhex version when I put the same memory (I think is the same memory that 6 gen for a hatched pokemon) mark me illegal!! 

Is that normal?? or 7 gen all pokemon have the same memory??

**Comment by kwsch** [comment]
Gen 7 Pokemon do not have memories.
