### ISSUE TITLE
[Bug] Rowlet legality checks

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#546]
I was making a Rowlet coming from a Decidueye. I set Rowlet to level 10 whereas Decidueye was level 100. PKHeX now tells me Leaf Blade is legal on a level 10 rowlet even though it actually only learns it on level 36.

![image](https://cloud.githubusercontent.com/assets/4019718/20786509/c7403f40-b7a6-11e6-8930-c144f824e8c3.png)

![image](https://cloud.githubusercontent.com/assets/4019718/20786519/d25c48d8-b7a6-11e6-8070-c3fae08f0bf1.png)

**Comment by egzonqj** [comment]
1. It's not a bug.
2. Rowlet can't learn Spirit Shackle, only Decidueye.
3. Now every pokemon can learn their own moveset despite their current level.

**Comment by Favna** [comment]
> Rowlet can't learn Spirit Shackle, only Decidueye.

I'm talking about Leaf Blade that doesn't show up as illegal. I know spirit shackle is illegal on anything but Decidueye =P I just wasn't done yet...

> Now every pokemon can learn their own moveset despite their current level.

Wait really? how so?

**Comment by egzonqj** [comment]
Yeah, the move reminder in this gen (which is found in the Mount Lanakila's Pokemon Center) let your Pokemon to learn their own level-up moveset. (https://twitter.com/xJoelituh/status/798355880010018816)

**Comment by Favna** [comment]
oh well crap! TIL. Thanks for that info! I'll close the issue then haha.
