### ISSUE TITLE
[Request] for Met Date

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#549]
Would it be possible to add a Ctrl+Click option to both Origin Data Met date and Egg met Dates that auto sets todays date?

**Comment by kwsch** [comment]
Click on the Calendar Icon on the right side of the control, then click "Today".
![image](https://cloud.githubusercontent.com/assets/6393368/20820826/f461781c-b7f2-11e6-94b7-ee3e9f14c340.png)
