### ISSUE TITLE
PokeBlock Request

### ISSUE THREAD

**Issue by Dimensional** [kwsch/PKHeX#55]
With the return of PokeBlocks in ORAS, can the option to create them be added into the program?

**Comment by kwsch** [comment]
Not really a point in doing so. You can hack in the berries, you can hack in the contest stats. You're the first person to request such a feature after 9 months of the games being out ;)

I do not own a 3DS or any of the 3DS games, so any specific research is left to the community.

I believe the data would be in the range here:
0035	28A00	00000400	75FC2	Contest Data

**Comment by kwsch** [comment]
SciresM to investigate.

May end up using the "Berry Field" editor slot if research is done.
