### ISSUE TITLE
Changing TID and SID results in a corrupted save.

### ISSUE THREAD

**Issue by vonKoenigsberg** [kwsch/PKHeX#552]
I have to change my IDs, but whenever I do, opening the save ingame results in a corrupted data error message. I did nothing but modifying TID and SID. The save prior to this edit still works. Bug?

Or is it possible that this change creates an inconsistency with the external data?

It's a bit weird because I changed my OT, TID and SID at release when u get your starters and there wasn't a single problem till now...

Or is it possible that going online prior to this ID change is the problem? I didn't go online prior to the first ID change at release. I didn't game sync yet tho at all.

Edit: Somehow it worked now after I did the same edit 4 times. I still think it's a bug or something with external data, because when it worked right now, it created new external data at the beginning.

**Comment by kwsch** [comment]
Appears to be an issue with re-importing the save file, which is not a PKHeX issue.
