### ISSUE TITLE
Island Scan 

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#554]
http://www.serebii.net/sunmoon/qrscanner.shtml
u can check on the Link above^
![island scan](https://cloud.githubusercontent.com/assets/18640392/20839197/1caa4ace-b8c5-11e6-9813-e51639a1ec5f.jpg)
it would help the community of PKHeX Genners to create and it would help in the future 👍

**Comment by NinFanBoyFTW** [comment]
To create what, the ability to import island scans?

**Comment by kwsch** [comment]
These encounters have already been implemented.
