### ISSUE TITLE
Egg Moves that Require Chain Breeding Sometimes Display as Illegal 

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#555]
Example: PKHeX says that Encore is not an expected relearn move on Alakazam.
You can get Encore on Alakazam by breeding Encore from Slakoth to Spinda, and then Spinda with Enchore to Abra.
Thanks for reading.

**Comment by kwsch** [comment]
Thanks, was able to reproduce issue. Looks like the Base egg species is not returning the correct value for Alakazam. Obviously Kinesis/Kinesis/Teleport/Confusion aren't the correct egg relearn moves.

Try setting it as an Abra until this issue is fixed; Teleport/Encore/None/None

**Comment by kwsch** [comment]
With a second case being noted by @Eskuero it appears that the common theme is a trade evolution.
I'll bet that the Pokémon you're playing with has no Handling Trainer data set.

Still a few things to fix in the code tho :)

**Comment by greenDarkness** [comment]
Is there a way that I can make it look as though it was traded and then traded back to me?
Thanks for taking the time to correct this. ^_^
