### ISSUE TITLE
Interface problems: some icons and background seen corrupted

### ISSUE THREAD

**Issue by arturfelipet** [kwsch/PKHeX#557]
After an GitHub resync and compile this week this interfaces erros showed up for me, tried delete and re download the master and recompile and same result.

The transparent background shows black, the icons of file menu looks corrupted and the new icons for marking in gen 7 started showing bad too.

any ideas how do i fix this ? i use xamarin 6.1.2 build 44 to compile it on mac os 10.12.1 ... thanks.

![background errors 1](https://cloud.githubusercontent.com/assets/515567/20846866/c6c9a59e-b8b2-11e6-896a-3d1f5fef6b6a.png)
![background errors 2](https://cloud.githubusercontent.com/assets/515567/20846868/c8c32230-b8b2-11e6-8274-f7a251c9fd87.png)

**Comment by kwsch** [comment]
Gonna blame https://github.com/kwsch/PKHeX/pull/517, looks like the optimization did something to the transparency data.
