### ISSUE TITLE
Fishing Rod bug in Sun and Moon

### ISSUE THREAD

**Issue by Korados** [kwsch/PKHeX#560]
Hello everybody,

I'd like to report a bug in the latest version of PKHex. If you use it on a Sun or Moon save, the Fishing Rod gets deleted and you aren't able to use the fishing spots anymore. When you try to add a Fishing Rod with the item editor, PKHex gives you the Fishing Rod from X/Y and OR/AS instead of the one used in Sun and Moon. I figured this out because the flavor text and the sprite of the Fishing Rod are identical.
Maybe Game Freak initially intended to leave the fishing like it was in the Gen VI games, and then considered otherwise. But the old Fishing Rod is still in the data of Sun and Moon.

Thank you for your help!

**Comment by Tsunamical** [comment]
This must be what the guy with the issue the other day meant when he posted fishing no longer works. Thank you for describing it in detail.

**Comment by kwsch** [comment]
I don't think it's because PKHeX gives the past-gen fishing rod.

https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L72-L76

g7 fishing rod is 842 according to [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_VII)) (and [PKHeX](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Resources/text/en/text_Items_en.txt#L843))

Did you at one point have it in the free space bag instead of the Key Items? Recently PKHeX was updated to retain the NEW and Free Space flags, so this may not be an issue on the latest commits.

**Comment by Korados** [comment]
Yeah, I read what that guy wrote, he wasn't very specific about this issue.

I explain to you what I did exactly: When I opened the Pouch editor in PKHex, I got a message that the Fishing Rod was deleted and that it will be gone when I save. So I went to the Key Items tab, clicked on a free space there and selected the Fishing Rod. But back in the game I couldn't use this Fishing Rod because the command button didn't appear at a fishing spot. I opened the pouch to see what's going on and saw that the Fishing Rod flavor text states that you can fish with it anywhere in the water. But I knew that the flavor text of the new Fishing Rod states that you can only fish with it at the fishing spots. So I figured that PKHex gave me the Gen VI Rod.

I have the version from the GBAtemp forum thread. Is this the most recent build? The archive it was in is titled "PKHex Build 951".

**Comment by onmyouji** [comment]
@Korados 

Strange, I've edited my items before (changed the quantity of Calcium, Carbos, etc), and I never encountered any problem with fishing rod. I can still use fishing rod as usual.

The most recent build are the ones from [commit page.](https://github.com/kwsch/PKHeX/commits/master) Click on the green checkmark, it links to the build server. The 1st one is for Windows, the 2nd one for Linux.

**Comment by Korados** [comment]
Thank you very much for pointing me to build server. I downloaded the newest build and got the Fishing Rod back. So I think the build I download from GBATemp was a quite old one.
