### ISSUE TITLE
Crash when clicking on trainer info w/o save loaded + Feature Request - Gender Changing

### ISSUE THREAD

**Issue by Hking0036** [kwsch/PKHeX#561]
Firstly, I clicked on trainer info before loading in a save and it spit out this at me:
Exception Details:
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at PKHeX.SAV_Trainer7.getTextBoxes()
   at PKHeX.SAV_Trainer7..ctor()
   at PKHeX.Main.B_OpenTrainerInfo_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Hunter\Desktop\PKHeX.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

Also, I'm really looking to change the gender of my character. I hate to be that guy because I'm sure it's in the works (hell, it's been 2 weeks since a release and you guys clearly move fast) but if it's flown under the radar I wanted to bring it up.

**Comment by kwsch** [comment]
>System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.

you'd have to send your save file or show what data you have at 0x04600 and 0x40C00 so that it can be determined what value you currently have for those fields.

Chances are you have an invalid date on your save file.

Regarding gender: it's readonly for a reason. Due to trainer customization, changing just trainer gender causes the game to fail to load, and or causes ingame events to glitch out because they expect a certain gender. Feel free to set 0x1205 to 0x01 and resave with PKHeX.

**Comment by Hking0036** [comment]
That was trying to open without a save loaded yet so yes it's almost certain to have a bad date. My mess coincidentally caused that. As for the gender thing, that sucks but it makes sense, you guys really are on top of things. Keep up the good work!
