### ISSUE TITLE
Maxing Pokemon Levels makes ALL pokemon illegal

### ISSUE THREAD

**Issue by matthewjdavis85** [kwsch/PKHeX#562]
Maybe theres a better way to do this that I am not aware of. I used the batch editor, and set Exp = a value higher than the highest pokemons exp requirement to make them all level 100. This sets the EXP to each pokemons max value and it seems to work in PKHex.  All pokemon fail to trade.

If I go in, make the pokemon level 99, then delete and make it level 100, it trades fine. The pokemon exp field is the same.

Is there a better way to make all Pokemon level 100?

**Comment by kwsch** [comment]
Correct, this is due to a Pokémon's growth rate requiring different amounts of EXP to get to level 100.

http://bulbapedia.bulbagarden.net/wiki/Experience

**Comment by matthewjdavis85** [comment]
Set Level did not work either
