### ISSUE TITLE
Bug with all traded Pokemon

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#564]
![bug 1](https://cloud.githubusercontent.com/assets/18354599/20856935/18cffe0c-b8f8-11e6-8b2d-45aef2b8bb1c.PNG)

the default memories present for both OT and Not OT are the same

"The Pokémon seems to have a good memory, but it doesn’t seem to be able to remember..."

**Comment by kwsch** [comment]
![image](https://cloud.githubusercontent.com/assets/6393368/20856950/b1be2542-b8d2-11e6-9dae-424cc2770ff4.png)
should be empty as well

**Comment by Odaxis** [comment]
Tried that. It wont actually empty the list.
Clear all. Save and set as a new poke in an empty space. Go back into memories and the location data is still there.

**Comment by Dandy562** [comment]
same here having the same problem, "Geolocation Memories should not be present" for Toucanon
