### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#567]
I was given this error after opening an illegal Conkeldurr that new Mach Punch, and then attempting to replace Mach Punch with Bullet Punch.

Exception Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Windows.Forms.CurrencyManager.Find(PropertyDescriptor property, Object key, Boolean keepIndex)
   at System.Windows.Forms.ListControl.set_SelectedValue(Object value)
   at PKHeX.Main.updateLegality(LegalityAnalysis la, Boolean skipMoveRepop)
   at PKHeX.Main.clickMoves(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.GroupBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Isaiah\Desktop\PKHeX\1030.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by kwsch** [comment]
Can you upload the pkm to help replicate the issue?

**Comment by greenDarkness** [comment]
Yes. I'm trying to upload the winzip, but Github doesn't like that; so I'll have it uploaded once I zip it with some other program like 7zip.

**Comment by greenDarkness** [comment]
New plan, Winrar converts all zips to a format that Github doesn't like.
https://www.mediafire.com/?n22x7esntqjlbdy

**Comment by kwsch** [comment]
Are you sure you are using the latest commit? Unable to replicate.

**Comment by greenDarkness** [comment]
I'm using build 1030 compiled by skyeditor.org.

**Comment by greenDarkness** [comment]
I see you're at 1039 now. I'll try it with that build.

**Comment by greenDarkness** [comment]
Whatever the problem was. I am not getting that error now. I guess it was fixed by the latest comment.
Sorry about that. Thank you for your time.
