### ISSUE TITLE
Feature request: general legallity checker

### ISSUE THREAD

**Issue by lomejor18** [kwsch/PKHeX#570]
can we have a batch checker? or maybe, can each box's slot visually alert about illegalities?
i know it can be a visual mess, maybe this option shouldn't be automatic, only by user request. perhaps a new row on "box data report"...
thanks

![ilegal](https://cloud.githubusercontent.com/assets/24194552/20859917/80e8a8f0-b942-11e6-9009-8babc1c32ab4.png)

**Comment by lomejor18** [comment]
a red background for illegal would be nice!

![ilegal 2](https://cloud.githubusercontent.com/assets/24194552/20860012/b51a04e6-b944-11e6-887a-9ed98c27a4ec.png)

**Comment by kwsch** [comment]
Open up the database, and use the following settings:

![image](https://cloud.githubusercontent.com/assets/6393368/20861103/6d19ab40-b93c-11e6-994c-a9fcfb5169e3.png)

**Comment by lomejor18** [comment]
@kwsch oh thanks! that's something... i'm still hoping you implement something without leave the main screen...

another issue: i did as you say and i got a LOT of "illegal" pokemon, when i select "view" i get the red exclamation mark but when i clic it i get a message box saying "Legal"! check this meowth as example, i'm using commit "a6671b2"

[052-01 - Meowth - 5E88F3465306.zip](https://github.com/kwsch/PKHeX/files/629126/052-01.-.Meowth.-.5E88F3465306.zip)

**Comment by kwsch** [comment]
It's because PKHeX fixes common issues when setting the Pokémon.
If you turn off Options->Set to SAV->Modify PKM Info, the program won't automatically fix things and will tell you what exactly is wrong.
