### ISSUE TITLE
Error when loading and auto-loading save

### ISSUE THREAD

**Issue by Gourmont** [kwsch/PKHeX#572]
When PKHex launches, it tries to auto-load my save but it fails and gives me the following error :

http://pastebin.com/mwedbS0D

If I choose to continue, PKHeX windows appears but, if I try to manually open a save, there is also an error.

http://pastebin.com/CkvPRpiZ

What can be causing these issues ?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/520

Probably homebrew or something created an illegal filename.

**Comment by Gourmont** [comment]
That was a save name issue, indeed ! When I exported my save using JKSM, I named it 12¤03¤2017 but it has made the file buggy. It works now that I have edited the name, thank you very much !

**Comment by kwsch** [comment]
I'll add some error handling to this to help other not-so-keen users figure out what is going wrong 👍
