### ISSUE TITLE
Lv.1 pokemon can relearn all moves?

### ISSUE THREAD

**Issue by whimsicott0907** [kwsch/PKHeX#574]
After edit my lv.1 pkm hatched from egg (IVs,Nature,eggmove) I notice it can relearn all moves at Move Reminder.
edit: All pkm in my box have the same issue, even wild pkm ( I catch 1 and it can learn all previous move although it lv.6)

**Comment by kwsch** [comment]
Welcome to Sun/Moon. PKHeX already accounts for this.
