### ISSUE TITLE
Extrasensory Egg move legality check fail on budew/roselia/roserade

### ISSUE THREAD

**Issue by Shinigati** [kwsch/PKHeX#575]
So according to serebii extrasensory is an egg move that can be learned on budew but on pkhex it says it is legal on budew but if i change level/species to roselia or roserade i get the red mark saying it's no longer legal i believe this is a bug with the program as met locations are set to hatch from an egg.
edit: confirmed working via trade

**Comment by kwsch** [comment]
Are you using the latest commits or latest release?

![image](https://cloud.githubusercontent.com/assets/6393368/20863915/3f2dbdf2-b991-11e6-8597-0981644aa5ac.png)

**Comment by Shinigati** [comment]
Well that is very odd then.. it worked via trade and i was sure i done everything right (i'm no amateur) but i'm using the latest release that supports sun and moon

**Comment by Shinigati** [comment]
Moving around the slot where the move is seems to somehow fix it, i have no idea why but it works, i had to change extrasensory from slot 3 to slot 2 even though the move is in slot 3 of the relearn list which was added there automatically.

**Comment by kwsch** [comment]
You stated you were using the latest release (under release tab), which was >15 days ago. Tons of changes have been made to PKHeX since then (mostly in regards to legality checking).

Unable to replicate.

![image](https://cloud.githubusercontent.com/assets/6393368/20864065/e7b7d68e-b995-11e6-821a-7abe5cdf219f.png)

**Comment by Shinigati** [comment]
Ahh that makes sense i should have figured.. at least it's fixed now and not worth reporting anymore thanks.
