### ISSUE TITLE
Gen2 Illegal Mode Hacked Stats Bug

### ISSUE THREAD

**Issue by BeyondTheHorizon** [kwsch/PKHeX#576]
Say I wanted Hidden Power Ground on a Pokémon at 70 power. I'd have to change the Attack and Defense DVs (IVs) to 12 and 15 respectively. This, of course, changes the HP IV too and ultimately weakens the Pokémon's HP and Attack stats.

I went into illegal mode by renaming the application to PKHaX and hacked the Pokémon's stats to what they'd be if I had 15 DVs in HP and Attack while still maintaining the DVs needed for a Ground-type Hidden Power. But when I set the Pokémon and view it again, the stats are back to what they'd be if I never hacked them.

This is not for competitive play as that would be serious cheating, but it seems I've discovered a bug.

**Comment by BeyondTheHorizon** [comment]
I can also confirm this bug applies to Gen 1, too.

**Comment by kwsch** [comment]
The stats are currently refreshed when viewing the PKM; if you've set illegal stats you should be able to see them.
