### ISSUE TITLE
Sun Save Glitch Occurred

### ISSUE THREAD

**Issue by Anonymous436** [kwsch/PKHeX#577]
My save file is corrupted after using this tool. My character was in Route 1's pokémon center. Does anyone know the exact numbers to change my location to my house?

**Comment by Arch9SK7** [comment]
Here use these.

Current map: 87
X Coordinate: 1916.07700
Z Coordinate: 2137.17200
Y Coordinate: 0.00000
Rotation: 0.00000

They are my coordinates.

**Comment by Ninjistix** [comment]
which build are you using? pretty sure this was fixed recently, i believe the issue is pkhex was force writing coords even if you didnt change it

**Comment by onmyouji** [comment]
You're using old build, use the new one. It's already fixed.
