### ISSUE TITLE
File Association Backup / Bug

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#581]
When you drag the sav file to PKHeX, or Open it directly from PKHeX it creates the backup automatically (with newest build), but if you associate the .sav file with PKHeX (Windows) and double click to open it, it does not create the backup. 

Tried multiple times with different sav's

**Comment by kwsch** [comment]
Unable to reproduce, I stepped through the entire process and saw the backup was created.
openFile -> openSAV -> check if backup folder exists && file not already backed up

```
if (SAV.Exportable && Directory.Exists(BackupPath) && !File.Exists(backupName))
    File.WriteAllBytes(backupName, SAV.BAK);
```

Is it possible that your file was already backed up? PKHeX doesn't overwrite old backups.

**Comment by Ninjistix** [comment]
The issue is if you associate the .sav file with PKHeX on windows and you
double click the sav file to open it it won't prompt you for backup, it
will only prompt for backup when opening directly with PKHeX via file and
open or dragging the sav directly to the PKHeX .exe

**Comment by kwsch** [comment]
There's only two ways to trigger the backup folder creation prompt `promptBackup()`:

1. First run of the program
2. Manually back up a file (CTRL-B or via File->Export SAV->Export Backup

**There is no prompt for individual files loaded**, only for creating the backup folder. If the folder exists, save files are backed up automatically.
