### ISSUE TITLE
Alert window "Invalid: Unknown Encounter"

### ISSUE THREAD

**Issue by bournejason** [kwsch/PKHeX#582]
Hi, I am using the latest build(1059) and found the in-game link-trade pokemons have some problems.
I used an older version to modify their IVs and I clearly remember the legality check was good, but with latest build I met such Alerts as Title said.

![image](https://cloud.githubusercontent.com/assets/4476789/20877419/99986198-bb03-11e6-9dcc-cee19614a014.png)

![image](https://cloud.githubusercontent.com/assets/4476789/20877482/17c68efa-bb04-11e6-8853-e31f382c1759.png)

Am I doing something wrong or the tool has some bugs? Also are the traded pokemons with NPCs illegal to be modified?

**Comment by Silly-Aussie** [comment]
I don't know if this helps or complicates things, but the pokemon I got myself are doing this, and the one I got off the GTS is fine. *shrug*

**Comment by xXAquaNightXx** [comment]
@bournejason Can you upload the .pk7 files?

**Comment by kwsch** [comment]
>I used an older version to modify their IVs

which invalidates it -- most IVs are defined by the game.

**Comment by bournejason** [comment]
OK, so the pokemons traded from NPCs have fixed IVs, am I correct?
If I modify their IVs and breed for perfect children, will them be legal? I guess yes, but will test for sure.

**Comment by kwsch** [comment]
Sure, bred pkm would be legal.

Trade Pokemon have set IVs; if they differ they'd be flagged by PKHeX.

**Comment by bournejason** [comment]
@xXAquaNightXx don't know if you still need them..
I modified their IVs and evolved them, nothing else changed.

[067 - ＰＯＷ・Ｌｉ - 8744E2BF881E.zip](https://github.com/kwsch/PKHeX/files/632971/067.-.-.8744E2BF881E.zip)
[062 - Ｓｐｉｒ◎ｌ - 31CDF1514EF6.zip](https://github.com/kwsch/PKHeX/files/632972/062.-.-.31CDF1514EF6.zip)

**Comment by xXAquaNightXx** [comment]
I think kwsch already sorted it out, the error was caused by changing the ivs so that's why the error popped up, but if you change the ivs and  breed them their offspring would be legal no problem

**Comment by bournejason** [comment]
yeah, thanks to both of you @kwsch and @xXAquaNightXx XD
END OF THIS ISSUE
