### ISSUE TITLE
ash greninja

### ISSUE THREAD

**Issue by Silly-Aussie** [kwsch/PKHeX#583]
The Ash Greninja is marked as unobtainable in this version, even when I generate it directly from the mystery gift database.

![ashgreninja](https://cloud.githubusercontent.com/assets/24382301/20878752/aa6329c4-bb24-11e6-91f2-5ce01df6921c.png)

**Comment by bournejason** [comment]
I saw this too

**Comment by Ninjistix** [comment]
its still marked illegal though, #458

**Comment by bournejason** [comment]
still not working with latest build

**Comment by Silly-Aussie** [comment]
works for me. although I downloaded the one from the mystery gift database, then modified it to match the one I had to solve the other issue, so try that maybe?
