### ISSUE TITLE
mystery gift meloetta

### ISSUE THREAD

**Issue by Silly-Aussie** [kwsch/PKHeX#584]
Meloetta from this month's distribution event - English
[567 - The Mythical Pokémon Meloetta.zip](https://github.com/kwsch/PKHeX/files/631008/567.-.The.Mythical.Pokemon.Meloetta.zip)

😄

**Comment by Ninjistix** [comment]
did they start giving this out already? couldn't find QR anywhere

**Comment by xXAquaNightXx** [comment]
Yea they started giving them out.

[563 - The Mythical Pokémon Arceus.zip](https://github.com/kwsch/PKHeX/files/632061/563.-.The.Mythical.Pokemon.Arceus.zip)

This is my Arceus i was lucky to get with the ARCEUS20 code. Jolly 31/31/15/31/11/15

**Comment by Ninjistix** [comment]
wonder if its cuz I haven't beating the game yet, did not see the QR code on pkmn website and did not receive it via internet (only seen munchlax)

**Comment by xXAquaNightXx** [comment]
This is for X, Y, OmegaRuby, AlphaSapphire only.

**Comment by Ninjistix** [comment]
derp was thinking of Magearna mybad

**Comment by kwsch** [comment]
Event Submissions are unrelated to PKHeX; PKHeX only includes event files that have been fully vetted by the community.
