### ISSUE TITLE
Captivate on Cottenee

### ISSUE THREAD

**Issue by mcdrill89** [kwsch/PKHeX#585]
It should be reading as legal as Serperior is able to chain breed it from either Smeargle or any of the mons that learn it by level up that are obtainable this gen
![eggmoves](https://cloud.githubusercontent.com/assets/3318921/20894310/e253187c-bae2-11e6-9414-89cc5e7c8c3c.png)

**Comment by kwsch** [comment]
pastebin.com/Dy5a5JYC was the source of the illegal-eggmoves table. Any other discrepancies?

**Comment by mcdrill89** [comment]
As far as I can tell no you guys covered most of the rest I'll do another look into it when I'm not starving lol
