### ISSUE TITLE
Trainer Name Symbols Displayed Improperly 

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#586]
Under Trainer Info, in the Overview tab where your trainer's name can be edited if there is a symbol such as ★ included in the trainer's name it is displayed as .
Thank you for your time.

**Comment by xXAquaNightXx** [comment]
Shows up okay for me on latest build
![test](https://cloud.githubusercontent.com/assets/24309423/20907814/fc9f616a-bb26-11e6-8325-7ad9e3f77123.png)

**Comment by kwsch** [comment]
It's referring to the Trainer Info editor -- the games use their own font to show custom symbols.

**Comment by xXAquaNightXx** [comment]
ohhh my bad, thats good to know then
