### ISSUE TITLE
Porygon Legality

### ISSUE THREAD

**Issue by trainboy2019** [kwsch/PKHeX#587]
When I made a Porygon PKHeX said was legal, and tried to take it it would not work. I edited it a bit and realized that the issue was Porygon was not in a Pokéball. It seems that it needs to be in a Pokéball to be legal.

**Comment by sora10pls** [comment]
Gift Porygon in S/M is given to you in a Poke Ball. Genderless Pokemon can't pass down Poke Balls, so a Porygon that was bred cannot be in any other Poke Ball.

**Comment by mcdrill89** [comment]
Genderless pokemon CAN pass down their ball type but the only one available in game can only be caught in a pokeball. So once bank comes along you can have it in any legal ball it can be caught in so just no apricorn balls.

**Comment by sora10pls** [comment]
Wow, I knew about Male but not Genderless! Damn you Game Freak for changing a lot :P

**Comment by mcdrill89** [comment]
Yeah I was thrown back by it too I was just putting a staryu to see f the Time Machine Method stayed for the respective Gender brackets for IV inheritance I caught it in a Luxury Ball and sure enough the offspring followed suit I'm so hype even though Hyper Training all but made IV breeding obsolete save for 0IVs in speed or Atk
