### ISSUE TITLE
New 3DS XL Save Files not readable "unsupportet Type/Size error

### ISSUE THREAD

**Issue by MinaTheLoli** [kwsch/PKHeX#59]
I used the Youtube Exploid to get homebrew + Save-Manager. But any time i want edit the Main file with PKHeX, it tells me the file is unsupported type/size.  my used firmware (i use 10.1.0-27) and i use Pokemon X (DE/EU Version)

**Comment by kwsch** [comment]
Try re-exporting your save file with save-manager.

The valid save file sizes are 0x76000 & 0x65600 for OR/AS and X/Y, respectively.

**Comment by MinaTheLoli** [comment]
i already tried it, same problem, here the screen of the error

http://i.imgur.com/ESa6l5t.png

**Comment by kwsch** [comment]
X/Y save files are 0x65600 bytes, not 0x655FE. The save file you are referencing is too small and is not valid.

You can always try adding "00 00" to the end in a hex editor. Try using [svdt](https://gbatemp.net/threads/svdt-save-data-explorer-manager.396562/) if that does not work.

**Comment by MinaTheLoli** [comment]
but why is it so with save manager? i think it should work?

**Comment by kwsch** [comment]
save manager is not pulling out enough data for the save file. 

I do not know why.

**Comment by MinaTheLoli** [comment]
ok i will try the other one

**Comment by MinaTheLoli** [comment]
actual the other save file is 2 bytes larger, now i test it with pkhex

**Comment by MinaTheLoli** [comment]
still the same error

**Comment by MinaTheLoli** [comment]
it seems after transfer, it loses 2 bytes

**Comment by kwsch** [comment]
You'd have to email me the save file if you wanted a more in depth answer, but this isn't a PKHeX issue.

**Comment by MinaTheLoli** [comment]
its ok, was cause i used the homebrew ftp
