### ISSUE TITLE
Legality issue

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#590]
Got a Rufflet in trade that PKHeX identifies as illegal/invalid due to "Unknown Encounter"
The poke came from http://www.serebii.net/sunmoon/pokepelago.shtml
![bug](https://cloud.githubusercontent.com/assets/18354599/20935736/8b35ab08-bbba-11e6-86c7-c2bb4a3838ea.PNG)

**Comment by kwsch** [comment]
Poké Pelago encounters are still unsupported as nobody has documented the level ranges.

Tables are included in the program, however, no level = no match possible.
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L253-L278
