### ISSUE TITLE
[Bug] Batch Editor Cannot Change Levels

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#591]
When editing a Pokemon Moon save in the Batch Editor, the command .Stat_Level= doesn't edit levels. If the command is issued it runs properly, and says that several files were modified; however, no changes are made.

**Comment by kwsch** [comment]
`CurrentLevel` is the property you are looking for -- even though current level is a derived property, PKHeX can calculate the required EXP for you when you set the value.

Stat_* are party stats which are not stored in the box format.

**Comment by greenDarkness** [comment]
Thanks for the help. I'll forward your message to the other guy having trouble.
