### ISSUE TITLE
Batch Editor Version does nothing

### ISSUE THREAD

**Issue by windwolfr** [kwsch/PKHeX#592]
I've been trying to figure out what Version attribute is and how it works, couldn't find anything about it in the Batch source code. If anyone can enlighten me, because it fails to do anything, at first I thought it was the Origin Game, but no matter what I input, it fails.

**Comment by kwsch** [comment]
Have to use numbers, not strings/text.

**Comment by sora10pls** [comment]
directly from source code ;p

![image](https://cloud.githubusercontent.com/assets/17801814/20952810/0521e944-bbfd-11e6-8a90-0e0db5f7b433.png)
