### ISSUE TITLE
Zygarde Cell Editor Doesn't Work

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#594]
When I attempt to set a Zygarde cell in game to make it collected, it doesn't actually change my Zygarde cells collected count but it makes the cells vanish from their respective spot. I  had collected only one cell when I started, but if I go in and set set ten different cells to be collected, and then resume the game, it still say that I've only collected 1/100, but it does make the cell vanish from the spot.

**Comment by kwsch** [comment]
Have you tried changing the number at the bottom?
![image](https://cloud.githubusercontent.com/assets/6393368/20950673/f03a36ac-bbd5-11e6-8567-4036d0fb9302.png)

**Comment by PKMWM1** [comment]
Yeah, the total cell count from what I have observed simply allows you to build multiple zygarde. For example, if you trade a Zygarde in or clone it, you can break it down to get extra cells. So even if you set your cell count to the right amount to match the one's you've checked off.

For example, I had only collected one cell so far. So I decided to try setting the first 9 to received as a test, and I set the total count from 1 to 10 since this would account for the 1 that I had already found and plus the nine that I modified. However, when I save and then check the Zygarde cube in game it would say: "You have collected 1/100 Zygarde Cores and Cells. You have 10 in the cube now."

**Comment by kwsch** [comment]
Could you look in Event Flags and let me know which 'custom constant' has the value that matches ingame?

The Total is num 161, I think 169 is the collected count

**Comment by ricksee** [comment]
@kwsch It is actually both 161 and 169.

**Comment by ricksee** [comment]
![flag 1](https://cloud.githubusercontent.com/assets/21182549/20953746/a1d62894-bc03-11e6-9477-a3d4584fb112.png)
![flag 2](https://cloud.githubusercontent.com/assets/21182549/20953745/a1d61bc4-bc03-11e6-937b-12b62fb9f737.png)

**Comment by xXAquaNightXx** [comment]
Can confirm this 161 and 169 both show the collected count. I went around and collected 83/100 
![0](https://cloud.githubusercontent.com/assets/24309423/20955668/604fe85c-bc1b-11e6-8805-84f3b58b4a74.png)
![1](https://cloud.githubusercontent.com/assets/24309423/20955670/62ffa740-bc1b-11e6-9ff4-d6a0220fed32.png)
![2](https://cloud.githubusercontent.com/assets/24309423/20955673/65971312-bc1b-11e6-858a-cab64ca9714f.png)
