### ISSUE TITLE
Game Sync ID

### ISSUE THREAD

**Issue by TCJJ** [kwsch/PKHeX#596]
There is a space for the Game Sync ID in PKHeX but it cannot be viewed nor edited. I'm not sure if this is intentional or not, but it'd be nice if the Game Sync ID could be reset if need be, or viewed at the very least (though I would really like to be able to reset mine, even if I have to do it manually, but I have no idea where to even begin with such a thing).

**Comment by kwsch** [comment]
I don't think deleting it allows you to re-register; I recall seeing a function that checks another flag in the save file (that the save has been registered). Let me know how it goes.
