### ISSUE TITLE
[Bug] Legality issue on a breeded G7 starter

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#598]
It's showing my Luxury Ball as illegal however G7 starters can be breeded with ditto (and ditto can be caught with a Luxury Ball).
In plus my Pokémon work online just fine.
So it's a bug ?
http://image.noelshack.com/fichiers/2016/49/1481124008-01.png

**Comment by Arch9SK7** [comment]
Ditto doesn't pass the ball Hun, sorry to say by its illegal either way. Not a bug.

**Comment by Arch9SK7** [comment]
It's like how I can make a gen 5 tyrantrum and it shows as illegal but for some reason it is allowed online in Pokemon. 

But you can have whatever ball (barring the cherish ball) on the starters of G7 and it will be usable online but it isn't legit

**Comment by Asia81** [comment]
Since when Ditto doesn't pass the ball oO? And what do you mean by "hun" ?

Anyway my Primarina work online in a Luxury Ball, but not in a Love Ball, so...

"usable online" "it isn't legit"
Is not that a bit contradictory?

**Comment by Arch9SK7** [comment]
Ditto as far as I know has never ever been able to pass the pokéball and love ball is a bank ball so that isn't obtainable in SuMo till it updates for Pokemon bank so that's why that is illegal it's the same as dream ball. 

So as I said again, it's not a bug.

**Comment by Asia81** [comment]
Uh... Some Love Ball can't be found in SuMo, you know?

**Comment by Tsunamical** [comment]
Again, whenever another Pokemon is bred with Ditto, Ditto has literally, in ANY game, passed down his pokeball rather than the Pokemon bred with said Ditto.

**Comment by Arch9SK7** [comment]
But again the G7 starters only the Pokéball is legit

**Comment by bournejason** [comment]
@Arch9SK7 Hi, I've heard of that Gen7 has a big change on ball type heritage, when you breed children with Ditto, the other non-ditto parent has a possibility to pass his or her ball type to the children. Maybe you can do some experiments to verify this before you say it is impossible.

**Comment by bournejason** [comment]
@Arch9SK7 yeah for starters they shouldn't have other ball types but in this gen the father also can pass ball types when breed with ditto.
btw, love ball is obtainable in this game, also heavy ball, lure ball...
