### ISSUE TITLE
BUG Pokeballs Breed Eevee(Invalid: incorrect Ball on Ingame gift

### ISSUE THREAD

**Issue by leanderson2006** [kwsch/PKHeX#599]
Eevee pokebola when hatching accuses as illegal. This error appears in all other balls except for normal pokeball

![sem titulo](https://cloud.githubusercontent.com/assets/22108300/20975730/7cfaaf8e-bc87-11e6-9ba0-bd992136927c.png)

**Comment by kwsch** [comment]
Looks like you're missing the relearn moves, which are required for every bred Pokémon. The only difference between the Eevee egg gift and a naturally bred Eevee is that the latter has relearn moves.
