### ISSUE TITLE
Milotic evolved from DexNav Feebas with high Beauty flagged as "unknown encounter"

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#606]
Milotic is flagged as an illegal encounter if it doesn't have non-OT handler data even though you can evolve it by leveling up with a high Beauty condition in ORAS (well, you can in XY too, but it would have to be traded from another game to have a Beauty condition to begin with). Non-traded Milotic should be legal as long as it originated in ORAS, its Beauty is at least 170, and its current level is at least one higher than its met level.

EDIT: Seems it only applies to Feebas encountered with the DexNav. PKHeX thinks it's a wild Milotic, not evolved from a wild Feebas.

**Comment by xXAquaNightXx** [comment]
If you're playing sun/moon getting pokemon that originated in ORAS right now is impossible until bank is available, pkhex would flag this. 

If the game you're putting the mitotic into a game isn't ORAS but has that it came from ORAS under the Met tab then it would need a non-OT handler. Which would be the game its going to.

If you have it set to encountered in the wild (feebas) then met level needs to match the level that it can be encountered in the set area.

**Comment by sora10pls** [comment]
Legal in a Gen 6 save file, you're more than likely using a Gen 7 save file.

![image](https://cloud.githubusercontent.com/assets/17801814/21037693/e4713680-bd9d-11e6-8782-cb923a19aabd.png)

**Comment by Dandy562** [comment]
has anybody else notice kingdra marks legal, but online it says the pokemon has a problem?

**Comment by White-Canary** [comment]
@xXAquaNightXx It's a gen 6 save file. And it's a legit Pokémon I caught and evolved myself.

@sora10pls That's a hatched Feebas, the problem only affects DexNav encountered Feebas. As I said before PKHeX is interpreting it as a wild Milotic which obviously doesn't exist. I confirmed this by reverting it back to its freshly caught state (which showed up as legal) and then changing it to a Milotic 1 level higher with max Beauty, and in addition to the unknown encounter it flagged Splash and Tackle as illegal moves. So it recognizes the encounter itself but doesn't recognize the beauty evolution as a valid evolution method specifically for that type of encounter.

**Comment by xXAquaNightXx** [comment]
@White-Canary 

Feebas are met at levels 15, 25, 35 by fishing i'm assuming same level ranges for DexNav 

![1](https://cloud.githubusercontent.com/assets/24309423/21088594/ecfdb5d8-c006-11e6-88aa-0ac475568058.png)
![2](https://cloud.githubusercontent.com/assets/24309423/21088595/ef003a40-c006-11e6-96b8-65c94bf94750.png)
![3](https://cloud.githubusercontent.com/assets/24309423/21088596/f0ba887c-c006-11e6-9cc6-409416649bc6.png)

This is a wild encounter I made and it's legal

![4](https://cloud.githubusercontent.com/assets/24309423/21088657/984805a6-c007-11e6-9986-65b296bc89e0.png)

With splash and tackle as moves.

**Comment by White-Canary** [comment]
I really should check the commits and not just the thread, didn't realize this was fixed the day I reported it. Gotta love this vague comment though:

> fix comparison and always return false if beauty insufficient

It's okay, you can admit you mixed up your greater than and less than signs. It happens to the best of us. Guess my Milotic was just a little TOO beautiful. :^)
