### ISSUE TITLE
static encounter relearn move mismatch

### ISSUE THREAD

**Issue by craftsygaming** [kwsch/PKHeX#608]
Sylveon (M) @ Leftovers
Ability: Pixilate
EVs: 76 HP / 180 SpA / 252 SpD
Modest Nature
IVs: 0 Atk
- Hyper Voice
- Shadow Ball
- Protect
- Wish

trying to make that set but it says static encounter relearn move mismatch even tho i said it was hatched
please help

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/599

Did you forget to specify the egg's relearn moves?

**Comment by craftsygaming** [comment]
no, egg moves are tackle tail whip hypervoice and wish
