### ISSUE TITLE
Suggestions in the exportable format

### ISSUE THREAD

**Issue by luedgo** [kwsch/PKHeX#609]
Hello everyone, I do not know if it is the ideal place to comment. But I want to leave a suggestion.
For the smogon format, it would be very useful to add the following lines.

One line for the type of pokeball and another that indicates the IV in 31 for bottle caps
IVsBC(IV bottle caps) or IVsE(IV effective) any name

Example:

Ball: Dive Ball
Cloyster (F) @ Focus Sash
IVs: 14 HP / 26 Atk / 13 Def / 28 SpA / 4 SpD / 12 Spe
IVsBC: 31 HP / 31 Atk / 31 Def / 31 SpD / 31 Spe
EVs: 252 Atk / 4 Def / 252 Spe
Ability: Skill Link
Level: 100
Jolly Nature
- Rapid Spin
- Toxic Spikes
- Icicle Spear
- Shell Smash

**Comment by kwsch** [comment]
The Showdown Set format is for importing/exporting between the simulator website / smogon dex and PKHeX. The fields you are proposing are not used.

If your intention is to share PKM files, just export a QR pic and share that instead.

**Comment by luedgo** [comment]
@kwsch thank you!

**Comment by Dandy562** [comment]
having problems with some trade evolution pokemon, for example electivire, porygon2, porygonz, alola golem, Machamp, it "Invalid: Untraded-- Requires a trade evolution. but with slowking it doesnt show that or kindgra. thanks.

**Comment by luedgo** [comment]
write a name in Lastest (Not OT) Handler @Dandy562

**Comment by Dandy562** [comment]
amazing thanks bro
