### ISSUE TITLE
Nicknames when Left Empty in Batch Editor Makes Names Empty in Gen 3

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#613]
If you leave no nickname in the batch editor while leaving the nickname checked, it creates a Pokemon with no name in Gen 3.

**Comment by kwsch** [comment]
Nickname Flag isn't stored in gen 3, it's a derived property. Not sure what the problem is.

**Comment by ricksee** [comment]
@kwsch Well, if the Nickname Box is checked but has no name it creates this. I don't know if this is normal.
![pokemon](https://cloud.githubusercontent.com/assets/21182549/21052301/433c31e8-bdf2-11e6-9b98-04bb055646fb.png)

**Comment by ricksee** [comment]
![pokemon](https://cloud.githubusercontent.com/assets/21182549/21052396/d30ae1e8-bdf2-11e6-8928-78b92b9c567e.png)

**Comment by ricksee** [comment]
![pokemon 2](https://cloud.githubusercontent.com/assets/21182549/21052404/deb6543c-bdf2-11e6-9b76-d0d28f41bdde.png)

**Comment by kwsch** [comment]
As expected, the game uses the nickname bytes directly. There is no nickname flag in Gen3, it is only derived for UI appearances.
