### ISSUE TITLE
Feature Request: Pokemon Type and Hyper Training flag in Stats Tab

### ISSUE THREAD

**Issue by kamuisama** [kwsch/PKHeX#614]
Is it possible? It would be neat if Pkhex has this feature..

**Comment by PKMWM1** [comment]
I believe that type is a derived value from the game itself and isn't something that can be manipulated through editing the save file.However, hyper training flags are already a feature, although not apparent. All you have to do is simply CTRL + Double Click the IV value of the stat you want to Hyper Train and the boxshoul turn yellow, indicating that the stat has been Hyper Trained. Note that any Pokemon that isn't level 100 or has a trained stat that is already 31 will be an illegal Pokemon.

**Comment by kwsch** [comment]
PKM Types are baked into the ROM (Personal Info) and are not stored in PKM data.
Hyper Training IVs are via CTRL-Click individual IVs. Color is green :)
