### ISSUE TITLE
Fixed the System.Deployment issue in Mono on macOS Sierra 10.12

### ISSUE THREAD

**Issue by jimga150** [kwsch/PKHeX#618]
I dont really know where to put this, but i want other people to know--if you comment out this line:

AddFontMemResourceEx(fontPtr, (uint)Resources.pgldings_normalregular.Length, IntPtr.Zero, ref dummy);

...in PKHeX/PKM/PKX.cs (line 601), and...

return System.Deployment.Application.ApplicationDeployment.IsNetworkDeployed;

in PKHeX/Util/DeployUtil.cs (then add a "return false;" under it), the project builds with only a few unused variable errors, and runs great. 

Heres what the edits look like in Xamarin:
![image](https://cloud.githubusercontent.com/assets/17803304/21062305/368b1550-be1e-11e6-9a6e-c101ce03ea5a.png)

![image](https://cloud.githubusercontent.com/assets/17803304/21062384/a0cc783c-be1e-11e6-9cfd-c384dbab6e4f.png)

**Comment by Tsunamical** [comment]
https://github.com/julroy67/PKHeX/commit/95501698175f87dd719af235a30aba5181fead0f
https://github.com/julroy67/PKHeX/commit/fcc77fcf54f79950656be8d86a03bfe37c65a3f7

Better fixes.

**Comment by evandixon** [comment]
You're not supposed to build with the ClickOnce-Debug or ClickOnce-Release build configurations.  Only Debug or Release.
