### ISSUE TITLE
Illegal Mode does not Function Properly on Pokemon Fire Red

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#619]
So I opened my 3rd gen save with PKHaX, and it removed ??? from my bag which is a key item in a rom hack. I know that PKHeX doesn't support rom hacks but is there anyway I could prevent it from removing items from my bag?
Thanks for all your work by the way.

**Comment by SciresM** [comment]
PKHeX does not support rom hacks.

**Comment by kwsch** [comment]
Eh, quick inspection looks like HaX isn't acknowledged in `getBags` where it purges items from the pouch if not in the array.

`var incorrectPouch = invalid.Where(item => item.Index < itemlist.Length).ToArray();`
should be
`var incorrectPouch = invalid.Where(item => item.Index < itemlist.Length && !HaX).ToArray();`
Should pass the HaX parameter to `getBags`

**Comment by greenDarkness** [comment]
Is this a change that I would have to make myself, or is this something you could add to PKHeX? 
Thanks you for all the help.

**Comment by kwsch** [comment]
I'll fix it in the next 24 hours when time permits :)

**Comment by greenDarkness** [comment]
You are a saint. ^_^
Also, how similar are C# and C++?
