### ISSUE TITLE
OT and Met location Request

### ISSUE THREAD

**Issue by fallenlucario** [kwsch/PKHeX#62]
While using pkhex I've found the OT feature to be very useful. Merely clicking the "OT" under the OT/Misc tab lets me make any pokemon nicknameable. One thing I'd like to request is that clicking the OT also alters the Met location to a location in the game it corresponds to. 

Maybe you could have an option in the "trainer info" that stores preferred egg hatch location or something of that sort. That way when you click OT it will auto input the information into the "Met" tab. Just a minor thing. I only suggest it because having to constantly change all of my pokemon's met locations is tiresome :/  

Also I have some questions! I do believe it was possible to alter the game and gender of your character before. Now when i go in the Trainer info tab it is greyed out and i can't do that anymore. Is there a reason this feature was removed?

Lastly, I have some old saves that are 512 kb in size, when i try to import them into pkhex it says something about the file size and doesn't load. Is there a reason why these don't load anymore?

**Comment by kwsch** [comment]
PKHeX is not intended to be a mass "snagem machine"; please use other tools more appropriate for Mass Editing purposes.

Changing gender/game has negative effects in terms of model loading and event flags; it's for the user's protection. PKHeX currently uses it to detect the savegame type too.

Seems to be a RAM save file; be sure it was obtained as such and is not corrupt.

**Comment by fallenlucario** [comment]
Ah i understand, I'm sorry for the request then. I wasn't aware there were other tools for mass editing. If you don't mind could I get the name of some?

I see, I was just puzzled as before gender changing was a thing, not very important just thought I'd ask, thank you for your replies! 

I believe it was obtained with ram2sav, i never fiddled much with that so it's alright if pkhex doesn't read it. I don't believe the file is corrupt as I've done nothing to it.

**Comment by kwsch** [comment]
https://github.com/FullLifeGames/Mass-Editor
