### ISSUE TITLE
"Can't Hyper Train a pokemon that isn't level 100"

### ISSUE THREAD

**Issue by blahbax** [kwsch/PKHeX#622]
Having been making 6IV pokemon fine lately, lots of them. 

Just tried making a 5IV Golem with 0 Speed and started getting this "Can't Hyper Train a pokemon that isn't level 100" error. Had quick look around and can't see any options related to hyper training. Tried updating to latest build just now and still getting error. Zipped Pk7 attached.

[076-01) ★ - Golem - 02AE6EDC39C1.zip](https://github.com/kwsch/PKHeX/files/643569/076-01.-.Golem.-.02AE6EDC39C1.zip)

**Comment by sora10pls** [comment]
Your Golem is Level 50; Hyper Training requires a Pokemon to be at Level 100. This is not a bug by any means.

Taken straight off of the official Pokemon website:
![image](https://cloud.githubusercontent.com/assets/17801814/21071698/05894ea0-be77-11e6-88fa-c207bd318ba7.png)

**Comment by sora10pls** [comment]
If you're unsure of how to toggle on/off a Hyper Trained stat, simply Ctrl+click the IV textbox of the appropriate stat. So in this example, to remove Hyper Training from your Golem's Speed stat, hold Ctrl and click where it says "0" next to "Spe:". Hyper Trained stats are differentiated from others with the green fill.

![image](https://cloud.githubusercontent.com/assets/17801814/21071741/7c8448a6-be78-11e6-9599-3d983ae10737.png)

**Comment by ricksee** [comment]
@sora10pls Can these Hyper Trained Pokemon be used competitively online?

**Comment by sora10pls** [comment]
@ricksee Yes if made legal, though that has nothing to do with PKHeX's functionality as a program :P

**Comment by blahbax** [comment]
Had no idea green denoted a hyper trained stat / about ctrl click shortcut, must have ctrl clicked by accident. As OP clearly stated, was not trying to hyper train the Pokemon. Thanks for solution anyway.
