### ISSUE TITLE
[Question]- About Trainer's Gender

### ISSUE THREAD

**Issue by K33P0** [kwsch/PKHeX#628]
I checked in the changelog and ProjectPokemon's Forum to see if there was anything about it,
So far I only saw that it wasn't able to in XY/ORAS and found this in the changelog
from 1/28/15 (When Sun Moon wasn't released yet)
'' - Changed: Gender/Game changing in Trainer Info has been disabled (it's not a simple 'switch').''

And thus my questions:
Is this because of XY's Trainer customization?
Will there be any future possibility for us to change the gender in Sun and Moon?

**Comment by kwsch** [comment]
It's a model loading related issue with the games. Presumably overworld data has to be updated, plus the event scripts depending on gender may wonk out if not updated either.

Nobody has cared enough to figure out how to get the game to behave properly after switching gender. That topic is save research related, and not PKHeX related.
