### ISSUE TITLE
Showdown export has wrong IVs for Hidden Power types

### ISSUE THREAD

**Issue by Favna** [kwsch/PKHeX#63]
I just noticed that when exporting a Diancie with Hidden Power Fire (IVs in order from top to bottom: 30/30/31/30/31/30) it exports as "30 Atk / 30 SpA / 30 SpD".

Further testing gave the following result. I've set IVs to:
HP: 1
Atk: 2
Def: 3
SpA: 4
SpD: 5
Spe: 6

which is exported as: IVs: 1 HP / 2 Atk / 3 Def / 6 SpA / 4 SpD / 5 Spe

This is probably an incosistency error since I believe back in the day IVs were listed as HP/Atk/Def/Spe/SpA/SpD

**Comment by kwsch** [comment]
Fixed in latest commit https://github.com/kwsch/PKHeX/commit/54bd371b501c6c6d19c733e4fbeb75d05835c916. Thanks for reporting :)
