### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by PR3D4TOR3491** [kwsch/PKHeX#630]
Following error when i start the program (Windows 10 x64):

Exception Details:
System.Configuration.ConfigurationErrorsException: Das Konfigurationssystem konnte nicht initialisiert werden. ---> System.Configuration.ConfigurationErrorsException: Unbekannter Konfigurationsabschnitt "userSettings". (C:\Users\...\AppData\Local\ProjectPokémon\PKHeX.exe_Url_boi2qp3zusaphccnomq5fdxp01xy1d1z\1.0.0.0\user.config line 3)
   bei System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bei System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bei System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   bei System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   bei System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   bei System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   bei System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   bei System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   bei System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   bei System.Configuration.ConfigurationManager.GetSection(String sectionName)
   bei System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   bei System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   bei System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   bei System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   bei System.Configuration.SettingsBase.get_Item(String propertyName)
   bei System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   bei System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   bei PKHeX.Properties.Settings.get_Unicode()
   bei PKHeX.Main..ctor()
   bei PKHeX.Program.Main()

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Phil\Desktop\PKHeX.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.Windows.Forms.resources.dll

System.Configuration.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration.resources\v4.0_4.0.0.0_de_b03f5f7f11d50a3a\System.Configuration.resources.dll

mscorlib.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
PKHeX must now close.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/589

**Comment by PR3D4TOR3491** [comment]
Hey,

I am using this version here:
https://projectpokemon.org/forums/files/file/1-pkhex/

-> I found another version from 24. november and it works fine (so do any older verisons i still have on my PC)

**Comment by PR3D4TOR3491** [comment]
It works now when starting directly from the .zip :)
