### ISSUE TITLE
Steven's shiny Beldum

### ISSUE THREAD

**Issue by JusLi** [kwsch/PKHeX#631]
Not sure if it's a real error but, my shiny Beldum from Steven is a legit mon, and I noticed it produced an error in the current PKHex build.

It says "Event OT affection should be 0." The thing is I don't think I ever touched this mon with PKHex before, nor would I try to alter Event OT's affection.

The values for Steven are 20 affection and 35 friendship.

Thanks.

**Comment by xXAquaNightXx** [comment]
This is not an error in pkhex. For this event Beldum the base friendship should be 35 under memories with OT and affection should be 0.

**Comment by JusLi** [comment]
Hum okay, that's weird. IDK how my Event OT affection became a non 0 value.

**Comment by Cresceda** [comment]
I'm having the same issue. Base affection is 0. May be a regional change, or them changing it halfway the event? Never touched my save before in PkHex and saw it by accident. I'm 100% it's not a user error on my end.
