### ISSUE TITLE
Incorrect/Invalid Gen 7 Game Sync ID

### ISSUE THREAD

**Issue by rehv** [kwsch/PKHeX#632]
It should be working, according to this commit: https://github.com/kwsch/PKHeX/commit/562cd460c876826c53e84cd659a897205644a23d .

The problem is: for me it shows 707094C19E421969707094C19E421969 for both my Pokémon Sun / Moon which have completely different Game Sync IDs. The sync shown isn't even valid, considering it's showing 707094C19E421969 two times.

I'm using a self built PKHeX, compiled today after commit https://github.com/kwsch/PKHeX/commit/42da2707ba33f568120b1b9d9fe4e11b48e80b92 .

**Comment by kwsch** [comment]
Game Sync ID is stored at 0x1218 in the save file; PKHeX displays it in reverse as a 128 bit number. Double check that the save file value doesn't match what is displayed in the program.

**Comment by rehv** [comment]
What you said is correct, and yes the values displayed by PKHeX match the values shown using an Hex Editor. But then, is it really stored at 0x1218? Because 69 19 42 9E C1 94 70 70 69 19 42 9E C1 94 70 70 is present in both files yet the game sync ID from both is completely different. Am I missing something?

**Comment by kwsch** [comment]
Fixed in latest commit, was confused with the NexUniqueID :)

https://github.com/kwsch/PKHeX/commit/637c97172552a4535f0d92b72c6e97dae5fc777e
