### ISSUE TITLE
Trade Evolution Pokemon Error with Level Requirements

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#634]
Pokemon such as Alakazam, which evolve by trading, say that level is below evolution requirements even if the Pokemon is at level 100. 
Also, how can I set a Pokemon as traded without changing my OT?
Thanks for reading.

**Comment by Odaxis** [comment]
It needs a Latest (Not OT) Handler. Just copy and Paste your OT name in the Not OT section and save it. should be legal after that if all other requirements have been met.

**Comment by xXAquaNightXx** [comment]
Error:

![error](https://cloud.githubusercontent.com/assets/24309423/21205652/c9f3ef4c-c233-11e6-988b-acf5fd13dfc6.png)

Fix:

![fix](https://cloud.githubusercontent.com/assets/24309423/21205702/08951f14-c234-11e6-88ba-cb1201f18813.png)

**Comment by greenDarkness** [comment]
Adding my OT to the latest Handler seems to fix the problem. 
The message about level being below the evolution requirements is still incorrect though.
