### ISSUE TITLE
Evolution button enhancement 

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#635]
Hi I wanted to know if it would be possible to add a general evolution button into pkhex. I think this would be useful for Pokémon that you might not know the evolution to forcing you to look up the name. I think this would also fix the problems that people are having with trade evolutions as well because you could set the handler to pkhex or whatever needed. Triggers pc implemented this with an actual cut scene like in the games but I think you could just add a button which changes the species. Thanks

**Comment by sora10pls** [comment]
What about Pokemon with multiple evolutions? Poliwhirl, Slowpoke, and Eevee especially.

Perhaps having a drop-down with all possible evolutions would work better, if implemented at all.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/296
