### ISSUE TITLE
legality error

### ISSUE THREAD

**Issue by craftsygaming** [kwsch/PKHeX#638]
![capture](https://cloud.githubusercontent.com/assets/23726260/21162395/bc68cb0e-c152-11e6-9a67-96433f3baeeb.PNG)
![capture1](https://cloud.githubusercontent.com/assets/23726260/21162396/bf33b0ba-c152-11e6-95d1-0e3336a951d3.PNG)

**Comment by kwsch** [comment]
Relearn moves are incorrect. Click on the relearn moves groupbox and it will provide a suggestion assuming the other details (version) are correct.
