### ISSUE TITLE
[Improvement] OSX Support

### ISSUE THREAD

**Issue by mjolnic** [kwsch/PKHeX#64]
Hello, I would like to contribute by making it also work for OS X. I have a basic knowledge of C# and I wanted to know if you have (or could provide) some guidelines / tips of what needs to be changed (apart from what the README says).

Thanks

**Comment by kwsch** [comment]
I have no idea; never developed for anything for Apple products.

PKHeX should work with Wine (PKHeX requires .NET 4.0)

**Comment by mjolnic** [comment]
It's working with Wine, thanks.
