### ISSUE TITLE
"Not an expected relearn move"

### ISSUE THREAD

**Issue by Chiyah** [kwsch/PKHeX#641]
Still trying to figure out everything about genning mons but this is something I just can't figure out ..

So I have a Pikachu with Charge, Electric Terrain, Electro Ball and Thunderbolt as it's moveset. As I see it, ET and Charge are both obtainable on Pichu when bred, so shouldn't Pikachu be allowed to have these moves as well? Yet when I give them to Pikachu, it says they are invalid moves. If I then set them to the relearn moves, the moves are now valid, but "Not an expected relearn move"

What am I doing wrong? I just dont get it.

**Comment by Ninjistix** [comment]
could you post a screenshot? and also if this helps anyone else

http://www.serebii.net/attackdex-sm/electricterrain.shtml#egg - valid egg move for pikachu/pichu
http://www.serebii.net/attackdex-sm/charge.shtml#egg - valid egg move for pikachu/pichu
http://www.serebii.net/attackdex-sm/thunderbolt.shtml#egg - invalid egg move
http://www.serebii.net/attackdex-sm/electroball.shtml#egg - only Electrike/Manectric can have this as an egg move

**Comment by kwsch** [comment]
Relearn moves for egg pkm should be the moves it hatches with. TM moves do not fall under this category.
Click the Relearn Moves groupbox for a suggestion once you have filled out your desired moves.

**Comment by xXAquaNightXx** [comment]
![chu](https://cloud.githubusercontent.com/assets/24309423/21205388/69a340bc-c232-11e6-88f0-1e8a3c183bfa.png)

Your setup should look like this. If a pokemon has an egg move inherited by a parent it should be listed here in the Relearn Moves section. It can get Charge and Electric Terrain from breeding with a Togedemaru. Just check bulbapedia for the pokemon and go to learnset everything will be there.

**Comment by Dandy562** [comment]
having problems with sudowoodo, everything seems ok, i even caught it int he wild, but after i edit it, still says legal, when trading says an error with the pokemon.

**Comment by Chiyah** [comment]
![pkhexpikachu](https://cloud.githubusercontent.com/assets/24576120/21263330/d36f2caa-c39e-11e6-8292-1e126ec89192.png)

I clicked on the suggested box, and the Relearn Moves are the suggested one, but they are still invalid. I'm not sure what I'm doing wrong still.
