### ISSUE TITLE
[question] pokedex editor

### ISSUE THREAD

**Issue by fixotherm** [kwsch/PKHeX#642]
Can the pokedex editor let you add the extra forms of caught Pokemon? I mean edit the file so your pokedex can show you alternate forms even if you didnt catch the alternate form?

Also is it okay if you add an option to check "all languages" in the pokedex editor? 

Thanks!

**Comment by Ninjistix** [comment]
for your first question yes, you can have alternate forms of some Pokemon, but you have to remember alt forms depends on certain conditions or requirements, and some alt forms are only in battle.

http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences

**Comment by fixotherm** [comment]
I asked because after I tried using the "all pokemon seen" option in the pokedex editor, it won't show they shiny forms for the oricorio. It only showed the shiny form of one style. Is this normal? Should i just get/gen the shiny versions of the other styles? Or is there a way for the pokedex editor to do it? Thanks!
