### ISSUE TITLE
Using "Give All" on Zygarde Cells gets rid of my Zygarde Cores

### ISSUE THREAD

**Issue by snotyak** [kwsch/PKHeX#643]
I had all of the Zygarde Cores but was missing a few cells. I used the "Give All" feature on the Zygarde Cells section and manually changed "Stored" to 95, and it says I have 95/100 Cells and Cores when checking the Zygarde Cube. Changing "Stored" to 100 doesn't remedy the issue either.

**Comment by windwolfr** [comment]
Give all feature only changes the flags that mark if a cell has been picked or not, it doesn't changes the total number of cells picked up. What I did was to see how many cells I was missing, and picked the easiest locations on Melemele, then activated those cells and picked them.

**Comment by kwsch** [comment]
Has already been updated in the latest commits to be clear that the number box is for collected not stored (which has since been added).

![image](https://cloud.githubusercontent.com/assets/6393368/21254542/d87608c4-c31a-11e6-9ae8-8a417f4c36ae.png)

**Comment by ricksee** [comment]
@kwsch What does it mean by stored?

**Comment by snotyak** [comment]
So this is how mine currently appears:

![img_20161216_080633](https://cloud.githubusercontent.com/assets/1321576/21267250/cde16696-c366-11e6-87c9-a97646b48d89.jpg)
![img_20161216_080641](https://cloud.githubusercontent.com/assets/1321576/21267249/cddf9532-c366-11e6-92e7-e9c970d3e64b.jpg)

If I change the "Stored" to 100 it only updates the second screenshot's value and still leaves me at 95/100 on the first one.

**Comment by xXAquaNightXx** [comment]
The collected field is for the 95 Cells you can collect within your game. The stored value is the total number you currently have in the cube the reason for this is that you can collect a Zygarde from a trade and break it down adding the cubes to your total. I think pkhex only gives the CELLS and not the 5 CORES. Try giving all and going to the location of the 5 CORES to confirm this. After its just about finding the constant associated with the CORES.

![cores](https://cloud.githubusercontent.com/assets/24309423/21287925/8805ed7c-c44c-11e6-824b-b822c052f004.png)

**Comment by snotyak** [comment]
I obtained the actual cores in-game but when I messed with the cells in PKHex to have all 95, the Zygarde cube only registers 95 total (instead of the 100 total). I've tried going back to those locations above to no avail.

**Comment by xXAquaNightXx** [comment]
@snotyak yea probably because when you collected the 5 Cores it registered as Received in the game and using the Give All function removed them from the Zygarde Cube but they still remain received within game.

**Comment by kwsch** [comment]
PKHeX does not modify the cores. It only modifies the 95 flag states and the 2 counters it displays.

**Comment by snotyak** [comment]
Okay, so I definitely misinterpreted this. I think "Give All" is misleading. I clicked "Give All" when I already had the 5 cores, and it set the "Collected" value to 95, when I believe it should've set it to 100. Perhaps it should check how many cores the user has as well. Setting "Collected" and "Stored" to 100 resolves it, but I assume only because I already had the 5 cores. "Give All" ignored those.
