### ISSUE TITLE
Ash-Greninja being flagged as illegal

### ISSUE THREAD

**Issue by Ant1Pois0N** [kwsch/PKHeX#644]
I am not sure if this has been reported yet, but Ash Greninja is flagged as illegal.

http://puu.sh/sRirz/412a2db081.png

**Comment by egzonqj** [comment]
Which version are you using? I'm sure it was solved already.

**Comment by sora10pls** [comment]
This has been fixed as of bdd1158

![image](https://cloud.githubusercontent.com/assets/17801814/21282796/44bc6490-c3c7-11e6-81b5-d2cbcc5056ae.png)
