### ISSUE TITLE
Pikachu in a cap gender bug

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#647]
Pikachu in a cap can only be male, so PKHeX shouldn't allow it to be female. I realized this after checking Personal Stats in pk3DS, where Pikachu forms 1 through 6 have a Gender value of "000", meaning only male. I know that because Pokemon such as Gallade, Tornadus, and Thundurus share this same value, and they can only be male ;p

![image](https://cloud.githubusercontent.com/assets/17801814/21283968/b53ac9d2-c3db-11e6-998d-35048502b932.png)

**Comment by kwsch** [comment]
first case of different gender thresholds for forms, srsly gamefreak just make the encounter a set gender
