### ISSUE TITLE
Can't import Type: Null set from Clipboard

### ISSUE THREAD

**Issue by isleep2late** [kwsch/PKHeX#648]
If you copy a set from PokemonShowdown with Type: Null as your Pokemon and try to Import Set from Clipboard, the program returns "Set data not found in clipboard."

**Comment by kwsch** [comment]
Works fine for me.
![image](https://cloud.githubusercontent.com/assets/6393368/21285413/7c58c824-c3ec-11e6-8939-7a41718f16f4.png)

**Comment by isleep2late** [comment]
That is so weird... Because it doesn't work for me when I copy and paste from the pokemonshowdown.com website. I'm also using Windows 10 to do this.

**Comment by kwsch** [comment]
What exactly are you trying to paste?
Have you tried using Tools->Showdown->Import instead of alt clicking?

**Comment by isleep2late** [comment]
I always do it that way (the Tools>Showdown>Import method). Didn't even know there was an alt clicking method lol

Anyway, the set you copied and pasted in your previous comment worked, but when I directly copy-paste from the showdown website, it doesn't. However, all other pokemon work fine. I think it has something to do with the two spaces at the end of each line. Take a look:

Type: Null @ Eviolite  
Ability: Battle Armor  
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- Return  
- Facade  
- Dragon Claw  
- Iron Head

This is the set taken directly from showdown. Not sure if it shows up, but there are two spaces at the end of each line (except for the last - Iron Head). The set you posted doesn't have those spaces. Not sure if it's the same for you. I'm using Google Chrome btw

**Comment by isleep2late** [comment]
Thanks!
