### ISSUE TITLE
Memories/Residence on Imported WC6 Pokémon

### ISSUE THREAD

**Issue by hehephorap** [kwsch/PKHeX#65]
When dragging a .wc6 file to a save file box, the generated Pokémon has its residence set to the save file's location.
This seems to be incorrect, as Pokémon imported into the Wondercard system and acquired through the Pokémon Center delivery girl will have no residence set due to technically never having left the OT.

**Comment by kwsch** [comment]
Whenever a file is set to a storage slot (box/party), PKHeX will update the HT/Memories ONLY IF the [SetUpdatePK6](https://github.com/kwsch/PKHeX/blob/master/Misc/SAV6.cs#L29) attribute for the Save File is true.

This attribute is true by default, but can be overridden by changing the "Set to SAV -> Modify PK6 Info" option in the main window's dropdowns.

**Comment by kwsch** [comment]
Resolved in the latest commit; default behavior should now handle these Event Pokémon cases (they weren't thought of previously).

https://github.com/kwsch/PKHeX/commit/374f8b0c83f16abd58dcda33b650db431cc99c5a

Thanks :)
