### ISSUE TITLE
[Question] All of my Traded Pokemon are Invalid

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#650]
The error message is: 
Invalid: Geolocation memories should be present. 

Is there way I can fix this? This happened on my Pokemon Moon save. Thank you for reading.

**Comment by kwsch** [comment]
They're hacked.

Clear the geolocation memories via the Memory/Amie button -> Residence tab.

**Comment by greenDarkness** [comment]
I cleared the residency, and saved but the error still persists.

**Comment by kwsch** [comment]
`Geolocation memories should be present.`
^ not present anywhere in the code

be sure you are using the latest commit.

**Comment by greenDarkness** [comment]
Just updated to build 1215, and I got the error again.
http://www.mediafire.com/file/316x8t4uf9b16kh/038-01%29_-_Ninetales_-_3387F2F73CCD.pk7

**Comment by kwsch** [comment]
Shows up perfectly legal on my end.

**Comment by greenDarkness** [comment]
I just recompiled the 1215 build by using http://teamcity.skyeditor.org/viewType.html?buildTypeId=PKHeX_PKHeXBuildPr.
I still get the Alert:
Invalid: Geolocation memories should be present. 
I'm gonna clean out my PKHeX zips and try again. Do you have any suggestions for things that I could do?

**Comment by ReignOfComputer** [comment]
Getting this issue as well.

**Comment by greenDarkness** [comment]
I could provide my save, and the PKHeX that I'm using.

**Comment by ReignOfComputer** [comment]
Okay so the latest compiled using the green tick is not the latest commit.
![snip_20161218122653](https://cloud.githubusercontent.com/assets/2667537/21291509/49f0768e-c51d-11e6-86a7-03d7db3a8092.png)

**Comment by greenDarkness** [comment]
But you can find the build for the latest comment here, right?
https://snag.gy/2PXfCA.jpg

**Comment by ReignOfComputer** [comment]
Yeah, not sure what's going on with the builds there. Here's the latest commit compiled anyway.
http://cdn.reignofcomputer.com/pkm/PKHeX%20-%20796c299.zip

**Comment by greenDarkness** [comment]
@ReignOfComputer Thank you! This fixed the error for me.
