### ISSUE TITLE
Bug with Traded Evolution

### ISSUE THREAD

**Issue by kamuisama** [kwsch/PKHeX#651]
In the latest Pkhex build my Gigalith gives Geolocation error. I tried to set the country in Residence option but it won't be saved. Memories for both OT are empty. ![capture](https://cloud.githubusercontent.com/assets/21088445/21294464/9c59f740-c56f-11e6-89e9-c827bfbbc5a0.PNG)

**Comment by kwsch** [comment]
The newest commits aren't being compiled by build server; compile yourself until the build server is fixed.
