### ISSUE TITLE
Unable to load file - Drag and Drop from Box to Editor

### ISSUE THREAD

**Issue by arturfelipet** [kwsch/PKHeX#653]
If i do a Drag and Drop from the Box to The Main Editor Tab i get this:

![untitled3](https://cloud.githubusercontent.com/assets/515567/21329257/eff5a5ac-c61e-11e6-8cd3-3e2b2cfd9362.png)

if i use the view popup option it loads just fine to the main.
![untitled4](https://cloud.githubusercontent.com/assets/515567/21329305/2f4c93c8-c61f-11e6-8168-21ba928b8bfc.png)

the pictures are from Gen 1 but tried on Gen3, Gen4 and even Gen7 ... seems to happen in any Gen. 

seems to happened after the last 3 or 4 commits as was normal this morning before recompile the newer version.

**Comment by evandixon** [comment]
Please paste the full exception details (everything in the text box shown in the first screenshot), or at the very least the exception message.

**Comment by arturfelipet** [comment]
`Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.SaveUtil.getIsG2SAVU(Byte[] data)
   at PKHeX.SaveUtil.getIsG2SAV(Byte[] data)
   at PKHeX.SaveUtil.getSAVGeneration(Byte[] data)
   at PKHeX.SaveUtil.getVariantSAV(Byte[] data)
   at PKHeX.Main.openFile(Byte[] input, String path, String ext)
   at PKHeX.Main.openQuick(String path, Boolean force)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Z:\Users\arturfelipe\Downloads\Games\Pokemon Saves\_SaveEditors\PKHex\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
Unable to load file.
Path: C:\users\arturfelipe\Temp\001 - BULBASAUR - 1D6E.pk1
`
