### ISSUE TITLE
[question] OT 3DS Region and Pokemon Language

### ISSUE THREAD

**Issue by fixotherm** [kwsch/PKHeX#654]
Does pkhex check whether the OT's 3DS Region match with an owned pokemon's "language" field? I've done a few edits to pokemon and changed them to make me the OT, but then I forgot to change the "Language" field. PKHeX thought that the Pokemon was legal, but of course it wasn't tradeable. Is this okay? Thanks!

**Comment by White-Canary** [comment]
All Pokémon games on the 3DS can be played in any of the available languages regardless of their region. If your Pokémon isn't tradeable it's for reasons unrelated to the language.
