### ISSUE TITLE
Gen 2 saves not loading anymore

### ISSUE THREAD

**Issue by arturfelipet** [kwsch/PKHeX#655]
it seems the new Gen 2 support to VC unofficial save size messed up the normal saves check.

![untitled5](https://cloud.githubusercontent.com/assets/515567/21361347/c50874da-c6ca-11e6-9d06-fd6eb91e032e.png)

same save loading just fine on another version from last week.

![untitled6](https://cloud.githubusercontent.com/assets/515567/21361352/ca503586-c6ca-11e6-9959-2b9df202e116.png)

**Comment by kwsch** [comment]
Are you using the latest commit?
https://github.com/kwsch/PKHeX/commit/1899e4e11e7fab4c9536d2f9cb3b6a9a313674dc

**Comment by arturfelipet** [comment]
just synced ab64ce4 and compiled it and got this error.

**Comment by kwsch** [comment]
Possible to send the save file?

**Comment by arturfelipet** [comment]
sure

[Pokemon Gold.sav.zip](https://github.com/kwsch/PKHeX/files/664446/Pokemon.Gold.sav.zip)

**Comment by kwsch** [comment]
Opened just fine for me :\

![image](https://cloud.githubusercontent.com/assets/6393368/21362671/47de9d08-c69e-11e6-824e-7739f2e1bc1f.png)

**Comment by arturfelipet** [comment]
recompiled and same error, this is my exe.

[PKHeX.exe.zip](https://github.com/kwsch/PKHeX/files/664456/PKHeX.exe.zip)

**Comment by arturfelipet** [comment]
Deleted my project, downloaded again and now works for some reason.

thanks.
