### ISSUE TITLE
Mono: build failed

### ISSUE THREAD

**Issue by koukakou** [kwsch/PKHeX#657]
![failed](https://cloud.githubusercontent.com/assets/23416118/21387288/d614e112-c72b-11e6-83db-f4c9b5fed812.png)

**Comment by evandixon** [comment]
Use the Mono-Debug or Mono-Release build configuration.

**Comment by koukakou** [comment]
Do you mean something like "xbuild /p:Configuration=Release PKHex.sln"? I got the same error. Thanks.

**Comment by evandixon** [comment]
`xbuild /p:Configuration=Mono-Release PKHeX.sln`

**Comment by koukakou** [comment]
Thank you. It works.
