### ISSUE TITLE
[Request] Extra fields in GenI/II (Status, Gender etc)

### ISSUE THREAD

**Issue by bryc** [kwsch/PKHeX#659]
For Gen I, there is no way to change status (Asleep, Poisoned, Paralyzed etc), same with all gens I think. Also you cannot switch Pokemon's Gender in Gen 2 (or shiny state).  Also no way to see/change Rival name!

**Comment by kwsch** [comment]
Infliction status will not be added to the program.
Un-shinifying can be done by Randomizing the IVs, as IVs determine gender/shininess in Gen II.
Refer to #283 (still open) regarding rival name.

**Comment by bryc** [comment]
I am curious, why not add infliction status, even for viewing purposes alone (i.e. showing that a Pokemon is currently poisoned)?  I know you can easily cure aliments at a PokeCenter, but if the PokeRus details are exposed, why not infliction status?
