### ISSUE TITLE
Issue when editing any trainer info

### ISSUE THREAD

**Issue by rocket0634** [kwsch/PKHeX#66]
I'm not sure if editing trainer info- such as the map location, Trainer IDs, Time played and such are working, but whenever I try saving any changes to trainer info, the Z-Coordinate automatically switches to whatever the current map number is.

**Comment by kwsch** [comment]
Nice catch :)

Fixed in latest commit https://github.com/kwsch/PKHeX/commit/df5cbbd5b7f60fa6cf6dc802cb2aa894ed39fc48

Thanks for reporting!
