### ISSUE TITLE
Why are the battle box slots locked now?

### ISSUE THREAD

**Issue by vonKoenigsberg** [kwsch/PKHeX#661]
Just because of vgc cheating? It's incredible annoying, thankfully I got an old version as a backup.

**Comment by kwsch** [comment]
It's annoying because cheating against others in any form is not a desire for this program.
De-register the slots from your battle box if you aren't actively using a team; you'd have to do that anyway if you wanted to re-train individual PKM ingame.

**Comment by vonKoenigsberg** [comment]
I don't really get what this change is going to accomplish bar being annoying.

The ones who cheat in tournaments with locked teams will just do so with an old version. I'm not the only one who logs every single iteration of pkhex exactly for a case like this (bad changes).

The ones who just want to change up their teams quickly when playing normal battle spot (like me) will have to take an old version now.

If this is an act to just avoid Nintendo's attention because this whole vgc mess could blow pkhex as a whole up, at least say so in the patch notes and not advertise it as a feature... And again, it doesn't accomplish this goal at all as stated.

**Comment by kwsch** [comment]
There's ways to check if the team is actually locked, the problem is nobody has sent a save file with a locked team :)

**Comment by vonKoenigsberg** [comment]
That sounds definitely nice, but why all the hassle? The problem lies within Nintendo's vgc team lock check procedure, old pkhex versions will live on forever...

Unless this is all just for trying to avoid publicity. In this case, case closed pshhh. ;)

Thanks for all the effort you put into this as a whole, this was the first time I felt something went wrong.

**Comment by greenDarkness** [comment]
@kwsch I think @vonKoenigsberg has a point saying that older versions of PKHeX will always exist. But, I'm also glad that you implemented this feature to prevent people from changing their locked teams in official tournaments. I'll be sure to get participate in the next tournament, and get a locked battle box. Thanks for all your work. Merry Christmas! ^_^

**Comment by vonKoenigsberg** [comment]
Idk why you downvote me really, it is a big loss in convenience as I store all my battle spot/battle tree/battle royale mons exclusively in battle teams these days and manually unbinding them each time I want to make an adjustment ingame is **not** viable at all [if I did not had the version prior to this "feature"].

I mean, wtf, at no point I stated cheating in vgc with locked teams is even remotely good, it obviously isn't at all, why the downvotes lol.
