### ISSUE TITLE
FireRed party-battle box bug

### ISSUE THREAD

**Issue by fiercebead** [kwsch/PKHeX#663]
If I add pokemon to party-battle box, the pokemon will be level 0 in game, if I view the summary of it the game will be black screen.

If I add pokemon to box, withdraw it from pc, everything is fine.

**Comment by kwsch** [comment]
I take it you put it in the party by drag-drop instead of right clicking->set?

**Comment by fiercebead** [comment]
Thank you, right click and set works.
