### ISSUE TITLE
QR Code Box Injection

### ISSUE THREAD

**Issue by adrifcastr** [kwsch/PKHeX#669]
It would be really useful injecting whole boxes instead of having to scan every single Pokémon QR Code

**Comment by sora10pls** [comment]
I too would like to see this implemented, I'm just not sure how much data can be squeezed into one single QR Code...

**Comment by SciresM** [comment]
You can't fit that much data into a QR code.

For reference, see [here](http://blog.qr4.nl/page/QR-Code-Data-Capacity.aspx). 

Maximum data size for biggest QR codes is 23648 bits = 0xB8C bytes.

30 pokemon would be 0xE8*30 = 0x1B30 bytes, over double that before even getting into metadata (or the fact that QRs currently use 0x104 byte party pk7s :)
