### ISSUE TITLE
Adding a Pokedex Tab for Gen 3-5?

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#673]
Is it possible to add a Pokedex tab for gen 3 to 5. They are the only ones not added for those generations.

**Comment by ricksee** [comment]
Here is a link if it helps:
http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9dex_data_structure_in_Generation_III
http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_data_structure_in_Generation_IV
http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_data_structures_in_Generation_III

**Comment by kwsch** [comment]
Please do not close old Issues and reopen new ones with the same issue.
