### ISSUE TITLE
[question] Sorting specific range of boxes

### ISSUE THREAD

**Issue by fixotherm** [kwsch/PKHeX#674]
I'm trying to make a living dex. Aside from those pokemon, I have separate boxes for shiny/BR pokemon and I usually keep them at the last box. I do the sorting by moving the shiny/BR pokemon to another instance of PKHeX and sorting the original save file, however it takes a lot of time. Is there a way to sort a specific range of boxes? Thanks. Keep up the good work!

**Comment by kwsch** [comment]
Sorting a range of boxes is not possible through the current UI, you'd have to change how the code behaves or just call the sort function manually.

https://github.com/kwsch/PKHeX/blob/2261a466703b4dcaf7107fabb3c2fc0e9339fef1/PKHeX/MainWindow/Main.cs#L3187

Change it to (x-1),(y) to sort boxes x-y (values are 0 index).
