### ISSUE TITLE
Slots with no Pokemon in them are locked?

### ISSUE THREAD

**Issue by Nawor3565** [kwsch/PKHeX#676]
So I opened my SuMo save file today and I saw that a few empty slots had a lock over hthem and I couldnt edit that slot. It seems like it has something to do with the battle box, but I don't fully understand it, but from what I do know that's only supposed to happen when Pokemon are in that spot, right? 
Also, I can still drag Pokemon to these slots, but then they become stuck and I can't delete them.

![2016-12-27](https://cloud.githubusercontent.com/assets/19783632/21509707/7eba6ca6-cc59-11e6-9c36-bd9e3bcbe539.png)

**Comment by kwsch** [comment]
It's because those slots are registered to a Battle Team; PKHeX will not allow you to edit those unless you move a Pokémon there ingame and de-register the slot.

**Comment by evandixon** [comment]
Have you modified this save using an older version of PKHeX?  If so and you deleted Pokemon in those slots, then PKHeX didn't update the battle box link, resulting in this.  If not, it's definitely a bug.
