### ISSUE TITLE
Can the Hatching Egg Seed be Edited in the Future? 

### ISSUE THREAD

**Issue by koukakou** [kwsch/PKHeX#677]
There is a seed for each new eggs generated in the game. And the 128-bit seed can be viewed in PKHex. Using this seed one can calculate the seeds and the properties of next eggs. I am wondering is there a reason that this seed is locked uneditable, or will this be editable in future? Thanks.

**Comment by koukakou** [comment]
The tool to calculate the next seeds is "SMHatchingRNGTool"
![image](https://cloud.githubusercontent.com/assets/23416118/21531753/5cd9fac4-ccff-11e6-83b8-77b0a546bbd7.png)

**Comment by koukakou** [comment]
![image](https://cloud.githubusercontent.com/assets/23416118/21531771/87e6786e-ccff-11e6-91d8-f8f302201247.png)

This is the seed in PKHex I referred to.

**Comment by kwsch** [comment]
Egg RNG seeds are per save file. You haven't loaded a save file.

**Comment by koukakou** [comment]
Of course I know the seed is save file related. I meant if I can modify the seed after loading a save file.

**Comment by kwsch** [comment]
Obviously you can.

**Comment by koukakou** [comment]
OK. Thank you. I was scared by the red sentence "this tab is read only"
