### ISSUE TITLE
Using batch editor for abilities and items?

### ISSUE THREAD

**Issue by knyuki90** [kwsch/PKHeX#678]
I want to batch edit a box of dratini with the same hidden ability Marvel Scale, held item Gold Bottle Cap and moves but I can't for my life figure out how to use the batch editor for these? I've tried using the name of the item, item ID, I'm currently looking at the resource text files and nothing works? 

Also if I used pkhex to change  the trainer information of a JPN pokemon to my own NA info, will it be flagged when I try to trade/use it online? I'm attempting to do this on a ditto for the masuda method.

**Comment by kwsch** [comment]
1. A list of supported properties that can use strings or index values is [here](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Subforms/PKM%20Editors/BatchEditor.cs#L276-L291).

```
=Box=4
=Slot=2
.Ability=Marvel Scale
.AbilityNumber=4
.HeldItem=Gold Bottle Cap
.Move1=Pound
```
etc.

2. Doubt it.
