### ISSUE TITLE
[Bug] Can't give Pokemon illegal abilities in Fire Red

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#681]
Using PKHaX, I tried to change a Charizard's ability to Flame Body for egg hatching. However, the ability changed back to blaze after I set it in my party. 
Thanks for reading.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/311

**Comment by greenDarkness** [comment]
Thanks!
