### ISSUE TITLE
Sableye missing egg move: Metal Burst

### ISSUE THREAD

**Issue by derbayer36** [kwsch/PKHeX#683]
![sableye](https://cloud.githubusercontent.com/assets/24847629/21573739/5760e48c-cee8-11e6-815c-a023b443f932.png)

**Comment by sora10pls** [comment]
Requires for Sableye to be bred with Pawniard/Bisharp, which are currently unavailable in Sun and Moon until support is added to Pokemon Bank.

![image](https://cloud.githubusercontent.com/assets/17801814/21574116/8d6f3862-cebb-11e6-8e62-b9a5b22261a9.png)
