### ISSUE TITLE
Friend Safari Randomize IVs Not Guaranteed Max.

### ISSUE THREAD

**Issue by g1zstar** [kwsch/PKHeX#688]
So I noticed that for other stuff such as legendaries randomize IVs will have the guaranteed 31s.
Randomizing with a friend safari pokemon doesn't give them the two guaranteed 31s.

**Comment by kwsch** [comment]
`bool IV3 = Legal.Legends.Contains(pkm.Species) || Legal.SubLegends.Contains(pkm.Species);`

It's not currently set up to force a certain amount besides legends. Everything else is random; adding in cases for all 'legal' would deviate from the random aspect a little too much.

**Comment by g1zstar** [comment]
Aaah, well ok than.

**Comment by kwsch** [comment]
Added a legality check to let the user know they should bump up some IVs: https://github.com/kwsch/PKHeX/commit/15f2f07b4a433b761bc08be84726142e5eaaf2d7
