### ISSUE TITLE
Surfing Raichu + Nasty Plot Passes

### ISSUE THREAD

**Issue by TuxKick** [kwsch/PKHeX#694]
I noticed that Surfing Raichu with Nasty Plot passes the legality checks even though it is impossible to have. Surf is only possible on an event Pikachu and Nasty Plot is only possible via breeding. Since Surf is not inheritable via breeding, this should not be legal yet PKHeX states that it is legal with no issues - other than the error for post-bank not possible yet.

**Comment by kwsch** [comment]
Thanks, this was a fun one to refactor & fix! 👍
