### ISSUE TITLE
PKHeX not loading correctly into save manager

### ISSUE THREAD

**Issue by RaynebowDeathtrap** [kwsch/PKHeX#695]
Some saves from PKHeX aren't loading correctly into JKSM. It comes back as corrupted. I backup the last working save of mine obviously, but I have a really hard time understanding how to make it all work. Some pokémon (for Pokémon X) can be made shiny while others can't (Zygarde). Am I doing something wrong?

**Comment by kwsch** [comment]
You need to overwrite the existing "main" file, and save without an extension (thus the final filename is "main"). Only 1 file should be in the folder when importing.

http://www.serebii.net/games/shiny.shtml
Refer to the Shiny Locks section.

**Comment by RaynebowDeathtrap** [comment]
Thanks! I appreciate this! You got back to me quickly!
