### ISSUE TITLE
Eror with the festival coins counter

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#698]
So a problem that I had found was the fact that when you change your festival coins quantity in the trainer tab, it changes your current coins as well as your total collected coins. I feel that the total coins collected should be its own modifiable flag in case you want to create some custom scenarios. I checked the list of event flags that can be changed in the trainer tab, but it seems that the offset for total coins collected is at 50d0c, which isn't an offset that I can reach without manual hex editing. So adding that offset would be very much appreciated.

**Comment by kwsch** [comment]
It updates the total coins with the UsedCount+CurrentCount which is exactly what the game does when adding coins. Changing/allowing users to modify the total count would cause a desync in how the game displays current coin count (total-used).

https://github.com/kwsch/PKHeX/issues/475
https://github.com/kwsch/PKHeX/pull/602
