### ISSUE TITLE
Set hatch count for batch editor?

### ISSUE THREAD

**Issue by exegg** [kwsch/PKHeX#699]
Hi. I was wondering if such option exists. I looked into the batch editor and could finally find a way to hatch a box of Pokemon, using this

=Box=1
.IsEgg=false
.IsNicknamed=false
.Nickname=Lapras
.Met_Location=78
.MetDate=20170105
.OT_Friendship=70

This sets the values just like a legit hatch. However it is inconvenient when I have a box with mixed species since it would unify the nicknames and base friendship, unless there's a function that uses the default values for the species and I'm missing it.

I'd rather have a simple function to drop the hatch counter to 1 in all eggs and I do my hatching quickly in the game.

**Comment by ricksee** [comment]
I would love to see a counter for eggs to see how many steps remain until it hatches.

**Comment by exegg** [comment]
@ricksee well, there's the hatch counter. Each value can be multiplied for 256 (I think that's the value, it has changed over Gens) and that's the approximate amount of steps remaining for hatching.

**Comment by ricksee** [comment]
@exegg Hmmm at least can the program display it as steps?

**Comment by kwsch** [comment]
The OT friendship field is reused by the game for the hatch cycle counter.

To pre-hatch all eggs down to 1 hatch cycle:
```
=IsEgg=true
.OT_Friendship=1
```
