### ISSUE TITLE
PKHeX does not compile on Linux

### ISSUE THREAD

**Issue by autofire372** [kwsch/PKHeX#70]
Attempting to compile PKHeX on Linux (Mint 17.3, to be precise) causes MonoDevelop to spit out a series of "`]' is invalid attribute target. All attributes in this attribute section will be ignored (CS0658) (PKHeX)" errors in the following files:
PGT.cs PGF.cs PK5.cs PK4.cs PK6.cs WC6.cs

This is followed by 338 errors and, of course, compilation failing.

**Comment by kwsch** [comment]
Version of MonoDevelop?

**Comment by autofire372** [comment]
4.0.12

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/89368e384ea305edcf228313c669e3ef1c44907c

Changed from 'default' to C# 6.0; let me know if you're able to compile the latest commit.

**Comment by autofire372** [comment]
Nope, I get the exact same errors as before.

**Comment by kwsch** [comment]
Ah, looks like MonoDevelop doesn't support C# 6.0 yet.

You should be able to compile commits from 1/15/16 https://github.com/kwsch/PKHeX/commit/251664f1bfe17f01cf2bd7474959e955e9ef7364 and before.

**Comment by ApacheThunder** [comment]
What version of Visual Studio is the new minimum? I can no longer compile with the new C# 6.0 commits. I'm using Visual Studio C# 2010 Express. Looks like I'll need to update it now... Other C# projects I have downloaded is Ohana and Pk3DS. I hope updating to a newer one won't break compiling of those...... :(

**Comment by kwsch** [comment]
@ApacheThunder: You can always install [Visual Studio Community 2015](https://www.visualstudio.com/visual-studio-2015-compatibility-vs), it's what I'm currently using.

**Comment by ApacheThunder** [comment]
Is there alternatives to that for Windows 7? I installed it and my SSD performance dropped like a rock. I don't have the space and the "8GB across all drives" install requirement was ridiculous. I had to uninstall it. :(

**Comment by suloku** [comment]
sharpdevelod compiled fine not so long ago. Needs to install some dependencies, but its for sure under 1 gB

**Comment by ApacheThunder** [comment]
Ok got around to trying sharpdevelod. But I get this error:

"Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default (CS1617)"

Specifically what dependencies do I need? I seen some of them and I think I already have a few of the dependencies installed. I just got done installing  Microsoft .NET Framework 4.5.2 Developer Pack. Do I need the Windows 8 SDK stuff too? (even though the OS I'm using right now is Windows 7)

**Comment by kwsch** [comment]
@ApacheThunder: See [workaround posted on SharpDevelop forums](http://community.sharpdevelop.net/forums/p/22341/56942.aspx#56942) to compile.

**Comment by ApacheThunder** [comment]
That worked! Thanks!
