### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by smbridges3094** [kwsch/PKHeX#700]
Add ability to import boxes of pokemon from .csv

**Comment by kwsch** [comment]
PKHeX doesn't export pkm files to csv. It only exports a report of important properties, which does not contain minor details like ribbon status.

Even if the Box Data Report was expanded to have every property imaginable including the {language specific} text descriptions, importing manually edited values is again {language specific} and prone to user error. If you are looking to modify things in bulk, use the Batch Editor.
