### ISSUE TITLE
Mistery Gift Gen6 Meloetta missing relearn moves

### ISSUE THREAD

**Issue by Jisagi** [kwsch/PKHeX#701]
Most recent build is missing the relearn moves for Meloetta received through mistery gift.
Region: Europe
Game: PKMN Y
Link: [serebii](http://www.serebii.net/games/currentevents.shtml#europe)

![Image](http://i.imgur.com/9lP2nXj.png)

**Comment by kamronbatman** [comment]
I don't see that event pokemon in there at all.  WCID 0567.
