### ISSUE TITLE
Xamarin build all generating only PKHeX.Core.dll, not PKHeX.exe.

### ISSUE THREAD

**Issue by arturfelipet** [kwsch/PKHeX#703]
The new built config gave me some problems on Xamarin, when i select Mono-Release and click in Build All it only generates 3 archives:

PKHeX.Core.dll
PKHeX.Core.dll.config
PKHeX.Core.dll.mdb

No PKHeX.exe generated, any idea how can i solve that ?

Thanks.

**Comment by kwsch** [comment]
Compile the PKHeX.WinForms project instead :)
