### ISSUE TITLE
[SuMo] Add support to remove GTS ban.

### ISSUE THREAD

**Issue by fblz** [kwsch/PKHeX#705]
As you might know one mayor annoyance of Sun/Moon is the GTS trade ban which can stretch from 15 minutes to 72 hours after a connection abort. As this ban is only a soft ban and can be removed by  restoring a old save, it would be nice to add a reset function to PKHeX. If you consider it, and I can help in any way, feel free to cantact me.

**Comment by kwsch** [comment]
New game-specific features need to be researched before they can be up for consideration.
