### ISSUE TITLE
Batch Editor

### ISSUE THREAD

**Issue by brutalgg** [kwsch/PKHeX#708]
I'm trying to batch "hatch" pokemon. Code that I'm using in the batch editor is below. The isEgg works but met location and met date do not seem to be setting. Am i doing something incorrectly?
=Box=18
.MetDate=1/9/2017
.Met_Location=Paniola Ranch
.IsEgg=False

**Comment by kwsch** [comment]
Force hatching the egg does not update the species name. It's probably better to just pre-hatch them. Refer to the following issues:

https://github.com/kwsch/PKHeX/issues/699
https://github.com/kwsch/PKHeX/issues/678
