### ISSUE TITLE
Event Gallery gift updates

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#711]
Looks like the WC in PkHex might have been from someone who edited the WC with WC Editor.

**Comment by kamronbatman** [comment]
The one in PKHex can be replaced with this one:
https://github.com/projectpokemon/EventsGallery/pull/3

**Comment by kwsch** [comment]
It was, watermark is present.

When the event gallery has an updated zip posted on the forums I'll update pkhex's db

**Comment by kwsch** [comment]
Let's just keep one issue for this; I think the resolution is to just let me know when the site's event database has been re-validated so that the program's event binaries can be updated.

#712 
#713

**Comment by kamronbatman** [comment]
Ok will do!
