### ISSUE TITLE
Island Scan Pokemon legality checker

### ISSUE THREAD

**Issue by WebChromium** [kwsch/PKHeX#715]
PKHeX flags Conkeldurr as illegal as it requires trade evolution. Using Island Scan, however, it is encountered in its final form and because of that is not illegal. 

However as of today 01/11/2017 hidden abilities of Island scanned Pokemon, for example Thick Fat Mamoswine pass al legal, yet they are unobtainable because Island scanned Pokemon will not call for allies and cannot be encountered with Hidden Abilities.

**Comment by kwsch** [comment]
Are you using the latest commits (01/11/17) or the latest release (12/31/16)?

The following commits have been added after the latest release, but are available if compiled from source:

[Add static encounter trade evo skip](https://github.com/kwsch/PKHeX/commit/01f153007b5442ba7b3c74744b35be03d5c4930f)
[HA Legality Check for Gen 7 Island Scan](https://github.com/kwsch/PKHeX/commit/fc2cd6e8bf6e9210707365690e78d470aa5659cd)
