### ISSUE TITLE
(bug) perhaps? Pokemon XY & ORAS location error 

### ISSUE THREAD

**Issue by mudkip83** [kwsch/PKHeX#716]
So I was trying to create some pokemon from XY & ORAS and keep on getting this invalid unknown encounter error. Tried a few steps and finally after much back and forth got it working with a work around. Do you think this is expected behavior or a bug of some kind.

see thread for screenshots and info
https://projectpokemon.org/forums/forums/topic/39754-unknown-encounter-error/

Thanks

**Comment by kwsch** [comment]
Please do not report bugs for things that have obviously been hacked (incorrectly), as the program is working correctly flagging it as illegal.
