### ISSUE TITLE
Request: add warning about changing gender (Gen 7)

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#718]
As of commit 696398f, it's been possible to change your skin tone, but PKHeX also allows you to change your character's gender. Upon changing my player's gender from male -> female (with a save backup, of course), my game would consistently crash when trying to load my newly injected save file.

I'd recommend either having a warning at the top of the editor (similar to that in the Event Flags Editor), or prompt the user to be wary of the side effects after changing your player's gender through a prompt (if gender changed from male -> female or female -> male).

**Comment by kwsch** [comment]
It's currently disabled... ...?

`this.CB_Gender.Enabled = false;`

**Comment by sora10pls** [comment]
That's what I was referring to, yeah. Opposite gender skin tones are all enabled by default

![image](https://cloud.githubusercontent.com/assets/17801814/21916215/0462f480-d90d-11e6-848a-ac167725f5f7.png)

Unlike in the "Overview" tab, where gender changing is disabled
