### ISSUE TITLE
Changing Pokemon's origin game from Gen VI to pre-Gen VI leads to accidental inclusion of OT memories

### ISSUE THREAD

**Issue by chenzw95** [kwsch/PKHeX#72]
When a Pokemon that originated from Gen VI is edited to originate from an older game (anything Gen V and earlier), the Pokemon's memories with its OT are not erased properly. This gives an illegal combination of a non-pentagon Pokemon having memories of its OT.

While CB_OTMemory and CB_OTVar are disabled for a non-pentagon Pokemon, the values are not reset and retain previous memories. CB_OTQual and CB_OTFeel, on the other hand, are not disabled at all and the values are saved into a non-pentagon Pokemon.

**Comment by kwsch** [comment]
Should be fixed now

https://github.com/kwsch/PKHeX/commit/970a887728d129dbba1185cb58dde1f5c17689a7 : Clear on opening memory editor
https://github.com/kwsch/PKHeX/commit/3c1c6b86ba785e4a01388d66e2a0d369786962b1 : Clear on saving pk6

**Comment by chenzw95** [comment]
Yup, it is fixed now. Thank you!
