### ISSUE TITLE
Automatic Mystery Gift Database

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#722]
Is it possible for the program to search online for new mystery gifts and and add them to the database and make them legal automatically?

**Comment by kwsch** [comment]
* Not many people use the Mystery Gift database.
* Checking & Downloading small files for every user can add up (hosting bandwidth).
* I don't think it's worth the effort/setup.

I explicitly have not added past gen pgt/pcd/pgf as it would bloat the exe; gen6/7 files are useful for legality checking. People can always add events manually (including past gen events!) by adding them to a "mgdb" folder in the same directory as the exe.

**Comment by kamronbatman** [comment]
I would like to add to this subject that PP.org is making a repo that has a collation of all events.

I hope that PKHex and Porybox will eventually use that repo for their legality checking. If (or when?) @kwsch is ready for Gen 3/4/5 legality checking, I would be happy to help take the PGT/PGFs and create heuristical/templated data that is much smaller than having the whole WC itself.  I think it should be like that for all generations.

While on the subject of bloat, I am not against having two builds, a portable and regular.  Portable being bloated with a full database downloaded and included in the EXE, and the regular which has no database built in, but has a copy of it in the separate database folder. PKHex could also pull the new database files from a [Github CDN](http://rawgit.com) using tags/versioning.

Let me know what you think!

**Comment by evandixon** [comment]
I wonder if it would be worth installing Team City on PP.org.  While it's normally a build server, with a little imagination it can do anything in response to the event repository being updated.  Perhaps packing the events into a Nuget package that PKHeX consumes?

**Comment by ricksee** [comment]
I just thought it be a good idea I think it would be good if it just downloaded the data and added it to the folder.

**Comment by kwsch** [comment]
I think it'd be much better suited for an opt-in separate tool. Downloading files may take longer than a second, and the databases need to be initialized on main form load.

Launch external program, check for gift updates, download to mgdb, launch PKHeX when finished downloading.

**Comment by kamronbatman** [comment]
I think that works for me.  Quick question though, is that tool going to be provided with PKHex.  I ask because I am thinking about the bloat and whether or not you will need to continue to provide a database with PKHex.

**Comment by kwsch** [comment]
* 0.5MB wc6/wc7 of 1.37MB bin
* 1.8MB img
* 1.2MB txt

PKHeX.exe is 50% assets, 50% code; including wc6/wc7 binaries is not really a problem. Adding gen4/5 gifts is another ~0.5MB, which isn't a problem either.

If functionality ever were included it'd go in the Mystery Gift Database subform as a dropdown item triggering the server communications necessary to get the files not present. However, it's not something I'm interested in implementing or maintaining (other features may be more useful / other projects / life) hence why a totally separate app that fetches things and dumps them in the mgdb folder is preferred. Can be any other language too! PKHeX doesn't have to do everything ;)

**Comment by kwsch** [comment]
Can do this with a cloned repo of the Event Gallery in the mgdb folder; update scheduling is something that can be handled by an external app (or batch file to call updates first).

6 months of no external solution => closing.

**Comment by kamronbatman** [comment]
I started doing releases just for that.

https://github.com/projectpokemon/EventsGallery/releases
