### ISSUE TITLE
No Option For Pokemon Yellow/Blue/Red In Origin Game

### ISSUE THREAD

**Issue by MidgeThePidge** [kwsch/PKHeX#724]
It's possible to trade pokemon from Pokemon Yellow, Red, and Blue to Pokemon Sun and Moon but there is no option for it in the latest commit of PKHex.

**Comment by kwsch** [comment]
>It's possible to trade pokemon from Pokemon Yellow, Red, and Blue to Pokemon Sun and Moon

Is the updated Bank out yet?

**Comment by MidgeThePidge** [comment]
Oh no not yet. Didn't think you needed the bank to trade it over.

**Comment by MidgeThePidge** [comment]
By bad.
