### ISSUE TITLE
PKHeX Build 1426 won't launch

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#725]
Hello, I grabbed the #1426 build of PKHeX from http://teamcity.skyeditor.org/viewType.html?buildTypeId=PKHeX_PKHeXBuildPr and it won't launch on my computer. PKHeX's permission prompt opens asking if I'm sure that I want to run the software. I accept, but PKHeX never pulls up. The #1390 build that I have runs fine though. I have a 64-bit computer with Windows 7 installed. 

Thank you for reading this.

**Comment by kwsch** [comment]
You need to keep the .dll too.

**Comment by evandixon** [comment]
Extract the zip file before running PKHeX

**Comment by greenDarkness** [comment]
Thanks for the help guys. I didn't know the .dll was necessary.

**Comment by kamuisama** [comment]
I cant even extract the zip from that site..

**Comment by greenDarkness** [comment]
@kamuisama Did you mouse over 'Artifacts' on the right?
