### ISSUE TITLE
Give all Fashion Items doesn't unlock colors from Dye Shops

### ISSUE THREAD

**Issue by 00Echo00** [kwsch/PKHeX#732]
The colors you need 5 star Dye Shops for (the pastel, bright, and dark colors) aren't there when I use the "Give all Fashion Items" button. It worked on my other save, but I'm not sure if that's because I was using a previous PKHeX release then or because that save has a female Trainer. Maybe this issue only applies to the male Trainer? Thanks!

**Comment by kwsch** [comment]
Via [post on the forums](https://projectpokemon.org/forums/forums/topic/39433-sun-moon-stat-records/#comment-206504) regarding the older PKHeX cheat:

>...if you use the give all clothing option in PKHeX (...) it will crash the game if you go into a dye shop. This seems to be due to owning the Pastel, Bright, and Dark variants of clothing as they aren't meant to be cataloged in your clothing inventory (Unless you dyed one possible white item yourself which you can only have one of each and must use dye shops to change it to those colors).

Those dyes can't be owned and cause crashes in the dye shops, hence why they are not given by the button.
