### ISSUE TITLE
"Volt Tackle" valid move for Pikachu

### ISSUE THREAD

**Issue by MineRobber9000** [kwsch/PKHeX#733]
As shown on [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pikachu_(Pok%C3%A9mon)#By_tutoring), in Generation 7, Pikachu can learn Volt Tackle by being taught the move by a tutor. However, according to the legality checker, Pikachu cannot learn this move.

**Comment by MineRobber9000** [comment]
Also, Primarina can learn Moonblast. (and Legality Checker complains)

**Comment by kwsch** [comment]
Are you using the latest release (12/31/16)? 

Please link to a pk7 or post a QR example; I was able to make a bred & captured Pikachu with Volt Tackle.

**Comment by MineRobber9000** [comment]
How do you check which release you're using?

I tried to give my friend's Pikachu Volt Tackle, but the legality checker said it was an invalid move.

**Comment by kwsch** [comment]
Redownload from the forums, you're using an out of date version.

You should also see the 'update available' notification in the top right which was added back in August.
