### ISSUE TITLE
Gen 7 Special Characters aren't the same

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#734]
Using the Special Characters window, it appears there are some order changes to the first 4 boxed emotes.

The smiling face, for example, should now be in the L03 position instead of L01.

**Comment by kwsch** [comment]
PKHeX uses the font file from PGL's website; the only things specified by PKHeX for the Special Characters input window is the 16bit character code to display. The font file determines what it looks like.

Does it show up correctly on PGL's website? Last time I checked they were using the same font file, but maybe they kept the old one for past gen compatibility and use a new one for gen7 files.

**Comment by ReignOfComputer** [comment]
No idea on PGL's website, but it's probably different for Gen 7. Order's changed.

**Comment by ReignOfComputer** [comment]
Here you go. Made in 6th Gen in the order Meh-Happy-Sad-Angry. Appears in both Pokemon Bank and Sun/Moon as Happy-Angry-Sad-Meh.
[419.zip](https://github.com/kwsch/PKHeX/files/728927/419.zip)

**Comment by kwsch** [comment]
Closing with similar reason to #737, ingame bug as I expect these symbols were mistakenly swapped for the game font file.

**Comment by ReignOfComputer** [comment]
Those creating a Pokemon in Sun/Moon will have trouble though, since the symbols don't match up in the editor.

**Comment by kwsch** [comment]
I'd expect the eventual 1.2 patch to fix S/M now that it has been exposed, but we'll see.

Not like many people use those symbols, plus one can argue that PKHeX matches Bank/PGL not SM :)
If GameFreak conforms their applications...
