### ISSUE TITLE
PKHEX Relearn Issue 

### ISSUE THREAD

**Issue by CoSMiiCKiiD** [kwsch/PKHeX#735]
I run into this a lot with random mons when trying to gen moves, this is the only one I could be bothered asking why it doesn't recognize the egg move via breeding or relearn?

Any help would be greatly appreciated!

![gyrados bounce](https://cloud.githubusercontent.com/assets/25294977/22197477/0c42e266-e1b7-11e6-80be-b52ac25a4b5d.JPG)
![gyrados bounce 2](https://cloud.githubusercontent.com/assets/25294977/22197488/1766d9c2-e1b7-11e6-8cee-50d4305f51d0.JPG)

**Comment by ReignOfComputer** [comment]
IIRC Bounce is a Tutor (which doesn't exist in SuMo) move, not an Egg Move.

**Comment by CoSMiiCKiiD** [comment]
okay, thanks for that!!
