### ISSUE TITLE
Gen VI to VII Past Contest Ribbons Bug

### ISSUE THREAD

**Issue by MarcusCane** [kwsch/PKHeX#737]
Upon pokebank transfer from Gen VI to VII, Past Contest Ribbons Ribbon, while holding a value of 40 throughout transfer (verified pk files before and after transfer), will change its ribbon appearance from the Gold 40 ribbon, to the blue 39 and under ribbon- despite holding 40 ribbons held. Could this be extra byte related? I cloned a pokemon for each extra byte and assigned a value of 1 to each byte exclusive to each pokemon and reloaded the .sav but nothing reverted the blue 39 and under ribbon back to gold 40.

**Comment by MarcusCane** [comment]
Oddly enough the Gold Past Battle Ribbons (8) retain their appearance after being transferred to Sun/Moon. Is it possible the contest ribbons obtained in ORAS effect the Past Contest Ribbons total value?

**Comment by MarcusCane** [comment]
![img_4682](https://cloud.githubusercontent.com/assets/25338588/22307166/440c2be6-e2ff-11e6-9c74-94323a650100.JPG)

**Comment by MarcusCane** [comment]
This may be a glitch on Nintendo's side. Ive tried editing bytes for both pk6 and pk7 files as well as quantity of ribbons prior to transfer and after. If you have 3/8 battle ribbons the graphic remains the same as being "complete" and being Gold. The link below also confirms others are seeing the same.

https://www.gamefaqs.com/boards/187276-pokemon-sun/74897589

**Comment by SciresM** [comment]
Nintendo bug, not PKHeX bug :)
