### ISSUE TITLE
Issues when trading with people of the same Name, TID, SID

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#738]
When it comes to all my Pokemon Saves, I have the trainer name, TID and SID the same across all of my Pokemon Game saves, but when I look at Pokemon that, under specific circumstances, would have extra data from trading with a person, it will flag it as illegal. Such as when I traded my legit kadabra with another profile of mine, and evolved it and traded it back, it says that the Pokemon is illegal as it can't evolve without a trade as well as some error that states something like invalid Geo-Location. And since, even though the odds are astronomical, it is technically possible for two different people to have the same trainer IDs, I feel that it should be accounted for.

**Comment by kwsch** [comment]
>same name, same TID, same SID
1:4,294,967,296 + OT name matching

The odds of a specimen being hacked are orders of magnitude higher than someone getting the same TID/SID/OT. It's better to flag it.
