### ISSUE TITLE
0x2A should not be checked for gen7 elements

### ISSUE THREAD

**Issue by BernardoGiordano** [kwsch/PKHeX#741]
This has been caught in game and is untouched, but it's flagged as transferred, as per [this commit](https://github.com/kwsch/PKHeX/commit/1be7ecafce64c5ddd7a16e3a27611412273167c3)

![image](https://cloud.githubusercontent.com/assets/17624378/22285105/91af44c4-e2ea-11e6-97df-a41a86e564c9.png)

**Comment by kwsch** [comment]
```
if (pkm.Format == 7 && pkm.Data[0x2A] != 0)
{ AddLine(Severity.Invalid, "Incorrectly transferred from previous generation.", CheckIdentifier.Misc); return; }
```

0x2A was gen6 marking byte (and is cleared 6->7); if people edited transferred files as their base pkm, these wouldn't get updated. Would need proof & info if this is actually another (new) pkm-property.

**Comment by kwsch** [comment]
New property, message has been removed from legality checks. Hopefully it can be figured out what the property is, maybe bitflag tracking for pelago participation or something.
