### ISSUE TITLE
VC problems and other things

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#742]
the VC pokemon are seen as met location Zoroark (2)
the GBA mark will disappear when you save

also,
in the ORAS games, when you enter in pkhex the pokedex tab and you click on "complete dex" it will not update the formes, only the shiny one. Please test on both games, in one of those it seems to work properly. Test the same thing also with XY game

in pokedex tab of SuMo you can "see" and "catch" the totems, but it will make the save illegit as you cannot have them and they have no image in the dex. For example: Kommo-o -1 is the totem, so it should not be present in the dex menu

Greninja Ash will give always error (mistery gift problem)

**Comment by egzonqj** [comment]
Yeah the VC thing might be because the gen1>gen7 is still WIP? I mean, people should be patient.

**Comment by SciresM** [comment]
VC stuff is very much a work in progress. Latest can display the regions of VC transferred pokemon properly, but please keep in mind that it's all very much still a work in progress....

![pls](http://i.imgur.com/5oKXM9I.png)

**Comment by fadeZero** [comment]
in TeamCity the pkhex public page with the latest built is now empty, where can i find the last built? thanks!

**Comment by evandixon** [comment]
It simply moved.
http://teamcity.projectpokemon.org (the server)
http://pkhex.skyeditor.org/latest (the link to the latest build)
