### ISSUE TITLE
No .exe file after compiling. 

### ISSUE THREAD

**Issue by StreakArrow** [kwsch/PKHeX#744]
When compiling, there is no .exe file in the bin folder. What should i do?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/717

**Comment by StreakArrow** [comment]
@kwsch Sorry, but i'm not able to compile the winforms project, it doesn't even make a bin. It justs gives an error saying
"error : The OutputPath property
 is not set for project 'PKHeX.WinForms.csproj'....."

**Comment by kwsch** [comment]
then change the outputpath property?

right click the winforms project, go to Build, and make sure OutputPath has a folder to spit out to

![image](https://cloud.githubusercontent.com/assets/6393368/22300641/f3b4846c-e2dc-11e6-964a-5245a44d7fed.png)

**Comment by StreakArrow** [comment]
I checked it and its exactly the same as in your screenshot. Same error tho?

**Comment by StreakArrow** [comment]
Its fixed. thank you!
