### ISSUE TITLE
"Invalid: Geolocation Memories should not be present" error when transferring 6->7

### ISSUE THREAD

**Issue by malicious50** [kwsch/PKHeX#746]
I am experiencing this type of error with legality check everytime I try to move a pkm from gen6 (AS to be precise) to my Sun save. 
I am using the latest commit (45367cdce7472b82240cb962a833ef5225399921)

this is the resulting pk7 from the transfer:
https://files.catbox.moe/agli10.pk7

this is the original pk6 file:
https://files.catbox.moe/7s0dz8.pk6

**Comment by sora10pls** [comment]
I'm also experiencing the same exact problem. Moving Pokemon from Gen 6 (AS) to Gen 7 (Moon).

**Comment by Nawor3565** [comment]
Same here. Not sure what the problem is.

**Comment by Odaxis** [comment]
My guess is a bug with the legality checker not checking game of origin, the memories were not wiped in the transfer so they should be legal

**Comment by greenDarkness** [comment]
I'm getting this error as well.

**Comment by iViscosity** [comment]
Sorry to re-open this, but I'm getting this error, too. I have the latest version and I'm trying to make a Sandslash from Gen 1, this is the only legality error it's giving me.

**Comment by kwsch** [comment]
>I'm trying to make
GitHub issues are to report PKHeX errors, not 'how do i hak' questions.
