### ISSUE TITLE
issue with using the batch editor to change abilities to ha and it not showing in pokemon bank

### ISSUE THREAD

**Issue by lycilla** [kwsch/PKHeX#749]
So since bank updated I updated the abilities for apricorn pokemon that were bred in gen 6 to their hidden abilities using the batch editor and changed their met locations to the breeding center in gen 7 and origin game as moon (which worked fine), but after I rewrote the file over my moon cartridge the ability changes weren't showing up in pokemon bank.

the ability changes show up fine in pkhex though, and the batch editor for hidden abilities/abilities seem to work for pokemon that were really bred in gen 7 but not for previous gen 6 pokemon even with batch editor changes to origin game and met location to gen 7 stuff.

**Comment by kwsch** [comment]
[duplicate with forums](https://projectpokemon.org/forums/forums/topic/39862-issues-with-batch-editor-for-abilities-in-gen-7/)

Two properties have to be set (abilitynumber & abilityID), the latter can't be used generically for multiple species. Will be incorporated in future commits.
