### ISSUE TITLE
It keeps on saying i can't export to the file i want it to for my moon game for homebrew

### ISSUE THREAD

**Issue by PrinceScales** [kwsch/PKHeX#750]

**Comment by kwsch** [comment]
Open your save file first.

**Comment by PrinceScales** [comment]
![capture](https://cloud.githubusercontent.com/assets/25359029/22319509/2a4efab0-e338-11e6-92d9-22ced9a36192.PNG) it keeps on saying this when i try to save the file

**Comment by kwsch** [comment]
SD card write protection switch, obviously :) Save elsewhere or flip the protection off.

**Comment by PrinceScales** [comment]
Thx fren
