### ISSUE TITLE
Shiny Xerneas and Shiny Yveltall events problem

### ISSUE THREAD

**Issue by lomejor18** [kwsch/PKHeX#751]
This is not a PKHeX problem, but needs to be clarified...
I've got both shinies Xerneas and Yveltall from last year events, they were on Pokebank ever since... Today I sent them to Pokémon Moon without problem, but I can't sent them on trade online! It says there's something wrong with my pokemon...
Is this another gamefreak's messing ups?

**Comment by kwsch** [comment]
>This is not a PKHeX problem

well there you go
