### ISSUE TITLE
Can't edit Secret Training Unlocked flag?

### ISSUE THREAD

**Issue by kamuisama** [kwsch/PKHeX#752]
So I keep getting this error message and I can't edit the flag to be unchecked, what did i do wrong?
![capture2](https://cloud.githubusercontent.com/assets/21088445/22334278/ba68dd8a-e40c-11e6-8646-e2cf2296c435.PNG)
![capture](https://cloud.githubusercontent.com/assets/21088445/22334281/be0aab6c-e40c-11e6-97f4-e6c2e1dbb776.PNG)

**Comment by kamuisama** [comment]
The latest commit removes Secret Training flag checkbox but the error is still there..

**Comment by kwsch** [comment]
Use the batch editor to remove the flag; the flag should be cleared when transporting 6->7 so only previous (bad) transfers have this problem (which isn't a problem going forward).

**Comment by kamuisama** [comment]
what's the constant for it?
SecretSuperTrainingUnlocked=??
