### ISSUE TITLE
Feature request: Option to reroll values on set to SAV

### ISSUE THREAD

**Issue by froslumugu** [kwsch/PKHeX#76]
Would it be possible to have an option to reroll PID, EC, IVs and possibly nature and ability upon setting a pokemon to box?
It'd be an useful addition to the Clone to all box slots to avoid having every slot be identical without having to run through every single one.

**Comment by kwsch** [comment]
I'd rather not; PID and EC is related to other information for previous games.

If you want to mass edit the PID/EC, you can just clone with PKHeX then use [Mass Editor](https://projectpokemon.org/forums/showthread.php?44994-Mass-Editor-for-all-PKHeX-supported-files). But realistically, PID and EC do not matter as the legality checks do not care about them.
