### ISSUE TITLE
"Build succeeded" but PKHeX.exe file is nowhere to be found?

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#760]
I'm trying to compile PKHeX from the latest commit and for some reason the PKHeX.exe file isn't being created in the bin/Debug folder like it should be despite it telling me the build succeeded:

`Build succeeded.

"C:\Users\Siobhán\Desktop\PKHeX-master\PKHeX-master\PKHeX\PKHeX.Core.csproj" (default target) (1) ->
(GetReferenceAssemblyPaths target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: The referen
ce assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting
Pack for this framework version or retarget your application to a version of the framework for which you have the SDK o
r Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used
 in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[C:\Users\Siobhán\Desktop\PKHeX-master\PKHeX-master\PKHeX\PKHeX.Core.csproj]

"C:\Users\Siobhán\Desktop\PKHeX-master\PKHeX-master\PKHeX\PKHeX.Core.csproj" (default target) (1) ->
(ResolveCodeAnalysisRuleSet target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not fi
nd rule set file "MinimumRecommendedRules.ruleset". [C:\Users\Siobhán\Desktop\PKHeX-master\PKHeX-master\PKHeX\PKHeX.Core.c
sproj]`

I'm 99% sure those are the same warnings I've always gotten and they've never caused any issues before, I always ended up with a functional .exe file regardless. But now it's just not there.

**Comment by gocario** [comment]
Check into the PKHeX.WinForms output folder.

In your case: "C:\Users\Siobhán\Desktop\PKHeX-master\PKHeX-master\PKHeX.WinForms\bin\Debug"

**Comment by kwsch** [comment]
#744
