### ISSUE TITLE
Request: legality checking for Gen 1 VC origin Pokemon

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#761]
Considering they all have the same exact Met Data (Always Hidden Ability, Origin being R/G/B/Y, Location being "The Kanto Region", Level being whatever Level they were transferred at, no Fateful Encounter other than Mew, etc.), I feel as if this is much more reasonable right now in comparison to legality checking for other Generations (i.e. 3 through 5, due to various met locations and a lot of other factors).

Would be nice to see, I don't expect it right away though if you consider it or have it planned out :)

**Comment by kwsch** [comment]
Have you tried the latest commits?

~14 hours ago: https://github.com/kwsch/PKHeX/commit/e5d9381c586db5febea4139b71315b5943fca9c7

I think that covers your request...

PKHeX doesn't check moves or level; Gen1 would have to have legality checking added before transferred specimens could be checked in greater detail. Stuff like Encounter Tables, Learnsets, and EvolutionTree.

**Comment by sora10pls** [comment]
Ah I didn't even notice that was added haha, that's exactly what I'm looking for. Thanks!
