### ISSUE TITLE
Swiching version X/Y OR/AS

### ISSUE THREAD

**Issue by AngelSora** [kwsch/PKHeX#762]
I can see a scroll with Gen6/7 that can make you switch version of the Game. I was playing Alpha Sapphire but i wanted to Switch to Omega Ruby, well... the game was fine and Team Aqua was Replace by Team Magma but... in the PKHeX, it still say its AS. I now this is possible to Sun/Moon but can you also add it to Gen6 ? I'm just scared that it messed up one Single thing in the Game...

**Comment by kwsch** [comment]
Swapping versions won't fix the screwed up event flags.
The Version dropdown is disabled for user protection, it only serves as indication. If you really want to change it, you can change it in a hex editor.

change `0x14004` to 0x18, 0x19, 0x1A, 0x1B for X/Y/AS/OR respectively.

**Comment by AngelSora** [comment]
Thanks for the Help.

**Comment by AngelSora** [comment]
IT WORK !
