### ISSUE TITLE
PID calculator

### ISSUE THREAD

**Issue by kevin918** [kwsch/PKHeX#767]
Hi, I have a question about the PID generator. As the number is not changing when I modify the nature or ability for each Pokemon. Thus it should not be legal since the PID is not matched with the Pokemon information. However, the Pkhex could not find the problem and show its legal.

**Comment by kwsch** [comment]
PID is only related to nature for pkm that originated in 3 and 4.
PKHeX only checks legality for pkm that originated in gen 6 or 7.
