### ISSUE TITLE
Pokedex tab in XY and ORAS does not work properly

### ISSUE THREAD

**Issue by fadeZero** [kwsch/PKHeX#772]
Hi, 

i was trying to modify the pokedex in pokemon Y.

in the pkhex, for example, i've removed from Volcanion and Hoopa the Shiny seen/captured tag (displayed too).
in game the dex still have those formes as seen/captured, but inside the pkhex they are not selected. So, maybe there is a problem with saving the correct informations? i've tried with Victini, same problem.

**Comment by fadeZero** [comment]
edit: same problem with ORAS! in the pkhex pokedex tab i've seen and captured volcanion normal only, and in the in-game dex i still see the shiny. same with all the others

**Comment by fadeZero** [comment]
the different thing is that in ORAS the same settings on hoopa make him display correctly ingame (without the shiny version) but in volcanion does not work. Zygarde has the same problem as volcanion, in pkhex no-shiny-seen/captured but ingame dex it appears as seen/captured. AZ floette, instead, it works properly. vivillon works too, meloetta works, keldeo works, victini DOES NOT WORK, celebi DOES NOT WORK. i'll try to upload here the 2 files from Y and AS so you can see the problem

**Comment by fadeZero** [comment]
1) https://www.dropbox.com/s/pt9yshy8oe0ouk7/main?dl=0
2) https://www.dropbox.com/s/xp4cb051cb0vqvd/main%20AS?dl=0

open both in pkhex, open pokedex tab, you see for example Volcanion, or Hoopa, or Victini or zygarde or keldeo as "Seen/captured normal forme yes, Seen/captured shiny forme NO". but try to open the dex ingame and you will see their shiny formes registered.

this could be potentially a problem with the bank, as it register the data from ingame dex, and so registers forever a shiny-locked-impossibile-to-get-for-now pokemon (and can lead to a ban, in future, from the bank?)

**Comment by fadeZero** [comment]
i have seen a similar problem in SUMO, when you click on captured all some of the formes/info in pkhex will not be added, I had problem with minor, for example. Even if i click seen none or captured none some of those windows will not be updated, and so it gives problems ingame

**Comment by fadeZero** [comment]
i have found the problem for XY and ORAS (and maybe SuMo too):
when you click on "check all" in pkhex they will check also Shiny Female box under volcanion and all the other legendaries. But you cannot uncheck them, as they are greyed. the only way to uncheck them is to uncheck all the pokedex

**Comment by ReignOfComputer** [comment]
On latest commit.

Could not reproduce issue with SuMo.

On XYORAS, when I do [Modify] > [Complete Dex], can confirm that Female boxes for legendaries get checked. However, when I press [Check All] while having said Pokemon selected, the invalid boxes are cleared.

**Comment by fadeZero** [comment]
On SUMO I think it would be safe to hide the totem formes from the dex like kimmo-o 1. As they result in empty image in the game and can corrupt the bank dex?

Inviato da iPhone

**Comment by Mrtops** [comment]
probably but it is best to keep them for the moment just in case
