### ISSUE TITLE
Feature Request: Mass Legality Checker

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#773]
One major addition that I think would be useful would be a mass legality checker. Similar to how Box Data Report compares various Pokemon Data against each other and other Pokemon, would it be possible to add the legality checker to one pf those columns, that we people don't have to check each individual Pokemon one-by-one and can know exactly which ones need to be looked at?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/739
