### ISSUE TITLE
Minor Legality errors

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#774]
These are just some small errors that I found while fixing all my illegal Pokemon

Gen 3 & Gen 4 Starters= Invalid Pokeball: Luxury Ball
They could've been caught in Luxury Balls in the Entree Forest in 5th gen, then transferred to Sun and Moon and Bred with a Ditto
Source:
http://serebii.net/games/geniiiball.shtml
http://serebii.net/games/genivball.shtml
http://serebii.net/blackwhite/dreamworldpokemon.shtml

Scatterbug: PKHeX states that it can't have PoisonPowder or Rage Powder as valid egg moves, but they can
Source:
http://serebii.net/pokedex-sm/664.shtml

**Comment by kwsch** [comment]
Scatterbug: Works fine?

![image](https://cloud.githubusercontent.com/assets/6393368/22410837/069862b0-e652-11e6-99e2-51871d84fdf1.png)

**Comment by PKMWM1** [comment]
Upon closer inspection, it seems that the error is thrown for the following forms: 
Tundra
Continental
Garden
Elegant
Meadow
Modern
Marine
Archepalego
High Plains
Sandstorm
River
Monsoon
Savanna
Sun
Ocean
Jungle
Fancy
Pokeball
The last two are event exclusive, but still worth mentioning anyway

Which leaves only Icy Snow and Polar working properly
![error picture](https://cloud.githubusercontent.com/assets/20786416/22411007/4a8128d6-e65c-11e6-8712-f63ac83e96b7.png)
