### ISSUE TITLE
Glitch Pokemon & Glitch Item Issue Gen 1

### ISSUE THREAD

**Issue by Dionicio3** [kwsch/PKHeX#778]
Hello! I like using PKHeX for editing my gen 6 & 7 saves. However, when I tried to edit my gen 1 save, ~~I cannot view certain pokemon (Missingno. and others)~~ nvm found [here](https://github.com/kwsch/PKHeX/issues/748) thanks @sora10pls, and when I try to edit my bag, it deletes some items I use (mainly ????? (44)). I also cannot select glitch moves nor view them. Please fix this.

**Comment by sora10pls** [comment]
"PKHeX does not and will not support corrupted GB saves." -SciresM

#748

**Comment by Dionicio3** [comment]
@sora10pls it's not being corrupted, it's just deleting an item that I use and not letting me view certin pokemon.

**Comment by sora10pls** [comment]
>not being corrupted
>(Missingno. and others)

**Comment by Dionicio3** [comment]
@sora10pls Missingno. is not caused by save corruption.

**Comment by sora10pls** [comment]
Read the issue I referenced?

**Comment by Dionicio3** [comment]
@sora10pls ok, but that still does not say why my item is being deleted

**Comment by kwsch** [comment]
Because the item is not valid?

The default launch mode of PKHeX filters items for pouches for the user. You can always bypass certain UI enhancements by launching in HaX mode (rename the exe).
