### ISSUE TITLE
Alolan muk

### ISSUE THREAD

**Issue by Nyquis** [kwsch/PKHeX#786]
The move Knock Off learned by Alolan Muk at lvl 29 is flagged incorrectly as invalid.

**Comment by ReignOfComputer** [comment]
Couldn't reproduce the issue. Can you upload a screenshot or the .pk7?

**Comment by egzonqj** [comment]
But Grimer evolves to Muk at lvl 38

**Comment by kamuisama** [comment]
it's because you have to evolve Alolan-Grimer to lvl 38 before you get Alolan-Muk, so there's no way to get A-Muk with that level so pkhex flag it as invalid, I think...?

**Comment by Ninjistix** [comment]
yes can also confirm there's no wild muk's in S/M, so deff invalid because of the level... (maybe)

**Comment by egzonqj** [comment]
its basically about the level, it should be lvl 38 atleast
