### ISSUE TITLE
Ride Pokémon & Editing your way into the Post-Game

### ISSUE THREAD

**Issue by mpenaranda96** [kwsch/PKHeX#787]
Is there a way to flag unlocking the Ride Pokémon? I'm currently trying to modify a new save file and make it post-game

**Comment by Arch9SK7** [comment]
Lel

**Comment by egzonqj** [comment]
I think there isn't one, but that could be really awesome, I guess?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/768
https://github.com/kwsch/PKHeX/issues/87

Beyond event flags, other blocks may need to be updated to enable all features (like allowing Mega Evolution, in Trainer Info). Editing the save to identify as post game would be infeasible when it's easier to take a completed save file and modify to your desired OT/etc. 

As for the pokeride flags, would have to be researched by the community first; plus there's really no point doing so as a story-complete save would have them unlocked already.
