### ISSUE TITLE
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.

### ISSUE THREAD

**Issue by arturfelipet** [kwsch/PKHeX#789]
Hi,

After the last updates i'm getting this error everytime i recompile with Xamarin.

![screen shot 2017-01-31 at 1 15 58 pm](https://cloud.githubusercontent.com/assets/515567/22470885/d0418112-e7b7-11e6-8981-5caf1d971394.png)

this is the terminal output:

`
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:process:SetProcessDEPPolicy (1): stub
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_32" failed to start: 1053
fixme:thread:SetThreadStackGuarantee (0x32fc64): stub
err:ole:CoGetContextToken apartment not initialised
fixme:shell:URL_ParseUrl failed to parse L"System"
fixme:shell:URL_ParseUrl failed to parse L"System.Windows.Forms"
fixme:shell:URL_ParseUrl failed to parse L"System.Drawing"
fixme:shell:URL_ParseUrl failed to parse L"PKHeX.Core"
fixme:shell:URL_ParseUrl failed to parse L"System.Core"
fixme:nls:GetUserPreferredUILanguages stub: 0 0x329fec 0x0 0x329fe8
fixme:nls:GetThreadPreferredUILanguages 00000000, 0x329fec, 0x0 0x329fe8
fixme:nls:get_dummy_preferred_ui_language (0x0 0x329fec 0x0 0x329fe8) returning a dummy value (current locale)
fixme:nls:GetUserPreferredUILanguages stub: 0 0x329fec 0x17cad0 0x329fe8
fixme:nls:GetThreadPreferredUILanguages 00000000, 0x329fec, 0x17cad0 0x329fe8
fixme:nls:get_dummy_preferred_ui_language (0x0 0x329fec 0x17cad0 0x329fe8) returning a dummy value (current locale)
fixme:ntdll:EtwRegisterTraceGuidsW (0xa9047a, 0x0, {8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 1, 0x32a26c, (null), (null), 0xddaa18): stub
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {8e9f5090-2d75-4d03-8a81-e5afbf85daf1}
fixme:shell:URL_ParseUrl failed to parse L"Accessibility"

Unhandled Exception: System.TypeInitializationException: The type initializer for 'PKHeX.WinForms.Main' threw an exception. ---> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at PKHeX.Core.SAV7..ctor(Byte[] data)
   at PKHeX.Core.SaveUtil.getBlankSAV(GameVersion Game)
   at PKHeX.Core.SaveUtil.getBlankSAV(GameVersion Game, String OT)
   at PKHeX.WinForms.Main..cctor()
   --- End of inner exception stack trace ---
   at PKHeX.WinForms.Main..ctor()
   at PKHeX.WinForms.Program.StartPKHeX()
   at PKHeX.WinForms.Program.Main()
`

![screen shot 2017-01-31 at 1 19 22 pm](https://cloud.githubusercontent.com/assets/515567/22470915/e93b1dc2-e7b7-11e6-81f2-97af1fb686cc.png)

this is the content of the above window:

<
Unhandled exception: 0xe0434352 in 32-bit code (0x7b827058).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:1007 GS:000f
 EIP:7b827058 ESP:0032e634 EBP:0032e6ac EFLAGS:00000212(   - --  I   -A- - )
 EAX:7b8198e5 EBX:00000005 ECX:00000000 EDX:00000000
 ESI:00000005 EDI:00149cd8
Stack dump:
0x0032e634:  0032e708 00000014 7b826ff3 e0434352
0x0032e644:  00000001 00000000 7b827058 00000005
0x0032e654:  80131534 00000000 00000000 00000000
0x0032e664:  79140000 00000000 0032e708 003624b0
0x0032e674:  02000059 0032e688 79150579 0032e690
0x0032e684:  02000059 0032e694 7915bc5e 003dc828
0200: sel=1007 base=7ffc0000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x7b827058 _RaiseException+0x74() in kernel32 (0x0032e6ac)
  1 0x791cac08 in clr (+0x8ac07) (0x0032e73c)
  2 0x793b5e83 in clr (+0x275e82) (0x0032e75c)
  3 0x793b5eff in clr (+0x275efe) (0x0032e788)
  4 0x793b5f3d in clr (+0x275f3c) (0x0032e7b8)
  5 0x793b5f50 in clr (+0x275f4f) (0x0032e7cc)
  6 0x792e0896 in clr (+0x1a0895) (0x0032f124)
  7 0x791d497d in clr (+0x9497c) (0x0032f1c0)
  8 0x00362459 (0x0032f2dc)
  9 0x03824975 (0x0032f2e8)
  10 0x03822731 (0x0032f314)
  11 0x791421db in clr (+0x21da) (0x0032f324)
  12 0x79164a2a in clr (+0x24a29) (0x0032f3a0)
  13 0x79164bcc in clr (+0x24bcb) (0x0032f4e0)
  14 0x79164c01 in clr (+0x24c00) (0x0032f4fc)
  15 0x79164c21 in clr (+0x24c20) (0x0032f514)
  16 0x7922ce82 in clr (+0xece81) (0x0032f678)
  17 0x7922cf90 in clr (+0xecf8f) (0x0032f8e0)
  18 0x7922cda4 in clr (+0xecda3) (0x0032fdc4)
  19 0x7922d199 in clr (+0xed198) (0x0032fe18)
  20 0x7922d09a in clr (+0xed099) (0x0032fe64)
  21 0x792aaf00 in clr (+0x16aeff) (0x0032fe9c)
  22 0x603b55ab in mscoreei (+0x55aa) (0x0032fea8)
  23 0x79007f16 in mscoree (+0x7f15) (0x0032feb8)
  24 0x79004de3 in mscoree (+0x4de2) (0x0032fed8)
  25 0x7b845a86 _start_process+0x96() in kernel32 (0x0032ff18)
  26 0x7bc5d09c _call_thread_func_wrapper+0xb() in ntdll (0x0032ff28)
  27 0x7bc5f08d _call_thread_func+0x68() in ntdll (0x0032ffa8)
  28 0x7bc5d062 _call_thread_entry_point+0x11() in ntdll (0x0032ffc8)
  29 0x7bc3f5fd _start_process+0x19() in ntdll (0x0032ffe8)
0x7b827058 _RaiseException+0x74 in kernel32: addl	$12,%esp
Modules:
Module	Address			Debug info	Name (254 modules)
PE	  400000-  53e000	Deferred        pkhex
PE	40001000-401bd000	Stabs           libwine.1.0.dylib
ELF	407e0000-407fa000	Deferred        version<elf>
  \-PE	407f0000-407f7000	\               version
PE	42082000-420c0000	Deferred        libncurses.5.4.dylib
ELF	420c0000-420e4000	Deferred        imm32<elf>
  \-PE	420d0000-420dd000	\               imm32
ELF	42600000-4267b000	Deferred        advapi32<elf>
  \-PE	42610000-42656000	\               advapi32
ELF	4267b000-42708000	Deferred        shlwapi<elf>
  \-PE	42680000-426ce000	\               shlwapi
PE	42708000-4278b000	Deferred        libfreetype.6.dylib
ELF	4278b000-427c5000	Deferred        uxtheme<elf>
  \-PE	42790000-427ba000	\               uxtheme
ELF	43000000-43143000	Deferred        user32<elf>
  \-PE	43010000-430e1000	\               user32
ELF	43143000-4325c000	Deferred        gdi32<elf>
  \-PE	43150000-431dc000	\               gdi32
ELF	4325c000-433b7000	Deferred        ole32<elf>
  \-PE	43260000-43336000	\               ole32
ELF	433b7000-43452000	Deferred        rpcrt4<elf>
  \-PE	433c0000-43419000	\               rpcrt4
ELF	43452000-43509000	Deferred        winemac<elf>
  \-PE	43460000-434c2000	\               winemac
ELF	4505b000-45156000	Deferred        comctl32<elf>
  \-PE	45060000-4511a000	\               comctl32
ELF	471e5000-47226000	Deferred        usp10<elf>
  \-PE	471f0000-4721d000	\               usp10
PE	48800000-48f92000	Deferred        appleintelhd5000graphicsgldriver
PE	5e0d0000-5e17a000	Deferred        diasymreader
PE	60340000-6034d000	Deferred        culture
PE	603b0000-60416000	Export          mscoreei
PE	60930000-60940000	Deferred        nlssorting
PE	79000000-7904a000	Export          mscoree
PE	79060000-7911e000	Deferred        msvcr100_clr0400
PE	79140000-797af000	Export          clr
PE	79810000-79870000	Deferred        clrjit
ELF	7b800000-7b932000	Stabs           kernel32<elf>
  \-PE	7b810000-7b8e0000	\               kernel32
ELF	7bc00000-7bcee000	Stabs           ntdll<elf>
  \-PE	7bc10000-7bc9c000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
PE	91756000-91757000	Deferred        accelerate
PE	91757000-9176f000	Deferred        libcginterfaces.dylib
PE	9176f000-91dd6000	Deferred        vimage
PE	91dd6000-91f23000	Deferred        libblas.dylib
PE	91f23000-91f36000	Deferred        libbnns.dylib
PE	91f36000-922d2000	Deferred        liblapack.dylib
PE	922d2000-922e9000	Deferred        liblinearalgebra.dylib
PE	922e9000-92304000	Deferred        libsparseblas.dylib
PE	92304000-92452000	Deferred        libvdsp.dylib
PE	92452000-92534000	Deferred        libvmisc.dylib
PE	92534000-92535000	Deferred        veclib
PE	92535000-931ac000	Deferred        appkit
PE	931ac000-931ad000	Deferred        applicationservices
PE	931ad000-9321c000	Deferred        ats
PE	932b4000-933e2000	Deferred        libfontparser.dylib
PE	933e2000-9342e000	Deferred        libfontregistry.dylib
PE	9342e000-93461000	Deferred        libtruetypescaler.dylib
PE	934cc000-9357d000	Deferred        colorsync
PE	9357d000-935d4000	Deferred        hiservices
PE	935d4000-935e4000	Deferred        langanalysis
PE	935e4000-9363d000	Deferred        printcore
PE	9363d000-936d8000	Deferred        qd
PE	936d8000-936e5000	Deferred        speechsynthesis
PE	936e5000-938d4000	Deferred        audiotoolbox
PE	938d4000-938d5000	Deferred        audiounit
PE	938d5000-93c3c000	Deferred        cfnetwork
PE	93c3c000-93c3d000	Deferred        carbon
PE	93c3d000-93c47000	Deferred        carbonsound
PE	93c47000-93c4c000	Deferred        commonpanels
PE	93c4c000-93fe6000	Deferred        hitoolbox
PE	93fe6000-9403a000	Deferred        htmlrendering
PE	9403a000-9403e000	Deferred        help
PE	9403e000-94044000	Deferred        imagecapture
PE	94044000-940e4000	Deferred        ink
PE	940e4000-94120000	Deferred        navigationservices
PE	94120000-9413d000	Deferred        openscripting
PE	9413d000-94143000	Deferred        print
PE	94143000-94146000	Deferred        securityhi
PE	94146000-9414d000	Deferred        speechrecognition
PE	9414d000-9414e000	Deferred        cocoa
PE	9414e000-941e8000	Deferred        coreaudio
PE	941e8000-941fb000	Deferred        corebluetooth
PE	941fb000-944e2000	Deferred        coredata
PE	944e9000-9498a000	Deferred        corefoundation
PE	9498a000-9502c000	Deferred        coregraphics
PE	9502c000-95260000	Deferred        coreimage
PE	953c1000-953c2000	Deferred        coreservices
PE	953c2000-95414000	Deferred        ae
PE	95414000-956f6000	Deferred        carboncore
PE	956f6000-9572a000	Deferred        dictionaryservices
PE	9572a000-95732000	Deferred        fsevents
PE	95732000-95855000	Deferred        launchservices
PE	95855000-95904000	Deferred        metadata
PE	95904000-95965000	Deferred        osservices
PE	95965000-959d7000	Deferred        searchkit
PE	959d7000-95a1e000	Deferred        sharedfilelist
PE	95a1e000-95b61000	Deferred        coretext
PE	95b61000-95b99000	Deferred        corevideo
PE	95b99000-95c09000	Deferred        corewlan
PE	95c09000-95c13000	Deferred        diskarbitration
PE	95c16000-95f84000	Deferred        foundation
PE	95f84000-95fb5000	Deferred        gss
PE	95fb5000-96058000	Deferred        iobluetooth
PE	96058000-960f3000	Deferred        iokit
PE	960f3000-960fa000	Deferred        iosurface
PE	9614e000-962a8000	Deferred        imageio
PE	962a8000-962ac000	Deferred        libgif.dylib
PE	962ac000-963a5000	Deferred        libjp2.dylib
PE	963a5000-963c9000	Deferred        libjpeg.dylib
PE	963c9000-963f0000	Deferred        libpng.dylib
PE	963f0000-963f3000	Deferred        libradiance.dylib
PE	963f3000-9644a000	Deferred        libtiff.dylib
PE	96bdf000-96bf8000	Deferred        kerberos
PE	9715f000-971b0000	Deferred        metal
PE	971b0000-971b9000	Deferred        netfs
PE	971b9000-971c2000	Deferred        libcldcpuengine.dylib
PE	97395000-973e2000	Deferred        opencl
PE	973e2000-973fc000	Deferred        cfopendirectory
PE	973fc000-97408000	Deferred        opendirectory
PE	97408000-9740b000	Deferred        libcvmspluginsupport.dylib
PE	9740b000-9740f000	Deferred        libcorefscache.dylib
PE	9740f000-97413000	Deferred        libcorevmclient.dylib
PE	97413000-9741c000	Deferred        libgfxshared.dylib
PE	9741c000-97429000	Deferred        libgl.dylib
PE	97429000-97467000	Deferred        libglimage.dylib
PE	97467000-975ec000	Deferred        libglprogrammability.dylib
PE	975ec000-97630000	Deferred        libglu.dylib
PE	97ffe000-9800d000	Deferred        opengl
PE	9800d000-981aa000	Deferred        glengine
PE	981aa000-981d7000	Deferred        glrendererfloat
PE	98c6e000-98e6c000	Deferred        quartzcore
PE	99121000-99459000	Deferred        security
PE	99459000-994cd000	Deferred        securityfoundation
PE	994cd000-994d1000	Deferred        servicemanagement
PE	994d1000-99544000	Deferred        systemconfiguration
PE	9b27a000-9b296000	Deferred        appcontainer
PE	9b296000-9b2a4000	Deferred        appsandbox
PE	9b2a4000-9b2c9000	Deferred        apple80211
PE	9b2c9000-9b2d4000	Deferred        applefscompression
PE	9b39f000-9b3dd000	Deferred        applejpeg
PE	9b456000-9b4da000	Deferred        backup
PE	9b519000-9b523000	Deferred        commonauth
PE	9b883000-9b895000	Deferred        coreemoji
PE	9b932000-9b964000	Deferred        coreservicesinternal
PE	9b964000-9b9ef000	Deferred        coresymbolication
PE	9b9ef000-9bb1e000	Deferred        coreui
PE	9bb1e000-9bbac000	Deferred        coreutils
PE	9bbac000-9bc0d000	Deferred        corewifi
PE	9bc0d000-9bc1c000	Deferred        crashreportersupport
PE	9bc1c000-9bc8f000	Deferred        datadetectorscore
PE	9bc8f000-9bcd0000	Deferred        debugsymbols
PE	9bcd0000-9bdf0000	Deferred        desktopservicespriv
PE	9be50000-9c282000	Deferred        facecore
PE	9c282000-9c283000	Deferred        libmetal_timestamp.dylib
PE	9c28e000-9c299000	Deferred        libgpusupportmercury.dylib
PE	9c299000-9c2b5000	Deferred        generationalstorage
PE	9c924000-9c999000	Deferred        heimdal
PE	9cb2e000-9cb35000	Deferred        ioaccelerator
PE	9cb35000-9cb5c000	Deferred        iconservices
PE	9cb6d000-9cd2a000	Deferred        languagemodeling
PE	9cd2c000-9cd55000	Deferred        multitouchsupport
PE	9cd55000-9cd60000	Deferred        netauth
PE	9cd60000-9cd9e000	Deferred        performanceanalysis
PE	9cd9e000-9cdb8000	Deferred        protocolbuffer
PE	9cdc8000-9cdec000	Deferred        remoteviewservices
PE	9cdec000-9cdef000	Deferred        seccodewrapper
PE	9cdef000-9ce1d000	Deferred        sharing
PE	9ce3c000-9ceb8000	Deferred        skylight
PE	9ceb8000-9cec6000	Deferred        speechrecognitioncore
PE	9cec6000-9cf2e000	Deferred        symbolication
PE	9cf2e000-9cf35000	Deferred        tcc
PE	9cf35000-9d154000	Deferred        textureio
PE	9d154000-9d156000	Deferred        trustevaluationagent
PE	9d156000-9d2c9000	Deferred        uifoundation
PE	9d4ab000-9d556000	Deferred        viewbridge
PE	9d556000-9d55d000	Deferred        xpcservice
PE	9d55d000-9d560000	Deferred        loginsupport
PE	9e05c000-9e078000	Deferred        libcrfsuite.dylib
PE	9e078000-9e082000	Deferred        libchinesetokenizer.dylib
PE	9e082000-9e084000	Deferred        libdiagnosticmessagesclient.dyli
PE	9e084000-9e2b6000	Deferred        libfosl_dynamic.dylib
PE	9e2b6000-9e2be000	Deferred        libmatch.1.dylib
PE	9e2be000-9e2bf000	Deferred        libopenscriptingutil.dylib
PE	9e2bf000-9e2c3000	Deferred        libscreenreader.dylib
PE	9e2c3000-9e2c5000	Deferred        libsystem.b.dylib
PE	9e2c5000-9e2f2000	Deferred        libarchive.2.dylib
PE	9e2f2000-9e40d000	Deferred        libate.dylib
PE	9e40d000-9e40e000	Deferred        libauto.dylib
PE	9e40e000-9e41f000	Deferred        libbsm.0.dylib
PE	9e41f000-9e42d000	Deferred        libbz2.1.0.dylib
PE	9e42d000-9e484000	Deferred        libc++.1.dylib
PE	9e484000-9e4a8000	Deferred        libc++abi.dylib
PE	9e4a8000-9e4ba000	Deferred        libcmph.dylib
PE	9e4ba000-9e4ce000	Deferred        libcompression.dylib
PE	9e4ce000-9e4cf000	Deferred        libcoretls.dylib
PE	9e4cf000-9e4d1000	Deferred        libcoretls_cfhelpers.dylib
PE	9e573000-9e663000	Deferred        libcrypto.0.9.8.dylib
PE	9e663000-9e6b9000	Deferred        libcups.2.dylib
PE	9e6b9000-9e6ba000	Deferred        libenergytrace.dylib
PE	9e6bb000-9e6c0000	Deferred        libheimdal-asn1.dylib
PE	9e6c0000-9e7b1000	Deferred        libiconv.2.dylib
PE	9e7b1000-9e9ce000	Deferred        libicucore.a.dylib
PE	9e9ce000-9e9d0000	Deferred        liblangid.dylib
PE	9e9d0000-9e9ea000	Deferred        liblzma.5.dylib
PE	9e9ea000-9ea00000	Deferred        libmarisa.dylib
PE	9ea00000-9ecb7000	Deferred        libmecabra.dylib
PE	9ecb7000-9ed2f000	Deferred        libnetwork.dylib
PE	9ed2f000-9f0f3000	Deferred        libobjc.a.dylib
PE	9f0f3000-9f0f7000	Deferred        libpam.2.dylib
PE	9f0f7000-9f126000	Deferred        libpcap.a.dylib
PE	9f126000-9f143000	Deferred        libresolv.9.dylib
PE	9f143000-9f17b000	Deferred        libsandbox.1.dylib
PE	9f17b000-9f2be000	Deferred        libsqlite3.dylib
PE	9f39c000-9f3ab000	Deferred        libxar.1.dylib
PE	9f3ab000-9f490000	Deferred        libxml2.2.dylib
PE	9f490000-9f4b9000	Deferred        libxslt.1.dylib
PE	9f4b9000-9f4c8000	Deferred        libz.1.dylib
PE	9f4d6000-9f4db000	Deferred        libcache.dylib
PE	9f4db000-9f4e6000	Deferred        libcommoncrypto.dylib
PE	9f4e6000-9f4ec000	Deferred        libcompiler_rt.dylib
PE	9f4ec000-9f4f5000	Deferred        libcopyfile.dylib
PE	9f4f5000-9f55b000	Deferred        libcorecrypto.dylib
PE	9f55b000-9f58a000	Deferred        libdispatch.dylib
PE	9f58a000-9f590000	Deferred        libdyld.dylib
PE	9f590000-9f591000	Deferred        libkeymgr.dylib
PE	9f591000-9f59e000	Deferred        libkxld.dylib
PE	9f59e000-9f59f000	Deferred        liblaunch.dylib
PE	9f59f000-9f5a6000	Deferred        libmacho.dylib
PE	9f5a6000-9f5a9000	Deferred        libquarantine.dylib
PE	9f5a9000-9f5ab000	Deferred        libremovefile.dylib
PE	9f5ab000-9f5c3000	Deferred        libsystem_asl.dylib
PE	9f5c3000-9f5c4000	Deferred        libsystem_blocks.dylib
PE	9f5c4000-9f653000	Deferred        libsystem_c.dylib
PE	9f653000-9f657000	Deferred        libsystem_configuration.dylib
PE	9f657000-9f65b000	Deferred        libsystem_coreservices.dylib
PE	9f65b000-9f674000	Deferred        libsystem_coretls.dylib
PE	9f674000-9f67b000	Deferred        libsystem_dnssd.dylib
PE	9f67b000-9f6a3000	Deferred        libsystem_info.dylib
PE	9f6a3000-9f6c5000	Deferred        libsystem_kernel.dylib
PE	9f6c5000-9f712000	Deferred        libsystem_m.dylib
PE	9f712000-9f72d000	Deferred        libsystem_malloc.dylib
PE	9f72d000-9f781000	Deferred        libsystem_network.dylib
PE	9f781000-9f78b000	Deferred        libsystem_networkextension.dylib
PE	9f78b000-9f794000	Deferred        libsystem_notify.dylib
PE	9f794000-9f79b000	Deferred        libsystem_platform.dylib
PE	9f79b000-9f7a5000	Deferred        libsystem_pthread.dylib
PE	9f7a5000-9f7a9000	Deferred        libsystem_sandbox.dylib
PE	9f7a9000-9f7ab000	Deferred        libsystem_secinit.dylib
PE	9f7ab000-9f7b3000	Deferred        libsystem_symptoms.dylib
PE	9f7b3000-9f7d4000	Deferred        libsystem_trace.dylib
PE	9f7d4000-9f7db000	Deferred        libunwind.dylib
PE	9f7db000-9f802000	Deferred        libxpc.dylib
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\Users\arturfelipe\Downloads\Games\Pokemon Saves\_SaveEditors\PKHex\PKHeX.exe
	0000002d    2
	0000002c    0
	00000009    0 <==
0000000e services.exe
	00000026    0
	00000025    0
	0000001e    0
	00000010    0
	0000000f    0
00000014 explorer.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000015    0
0000001c winedevice.exe
	00000024    0
	00000021    0
	00000020    0
	0000001d    0
00000022 plugplay.exe
	00000028    0
	00000027    0
	00000023    0
00000030 wineconsole.exe
	00000031    0
System information:
    Wine build: wine-1.8.5
    Platform: i386
    Version: Windows XP
    Host system: Darwin
    Host version: 16.1.0
>

**Comment by kwsch** [comment]
.NET 4.6 was recently added as a requirement; I believe a user with the same error `'!!0[] System.Array.Empty()'` had the same issue on the forums.

Try deleting the old dll too

**Comment by arturfelipet** [comment]
ok, solved. 

- deleted my ./wine config
- added "export WINEARCH="win32""
- started a new wine config with winetricks dotnet46

it seems to be running as Windows 7 now and working.

thanks.
