### ISSUE TITLE
C-Gear Skin Tab error BW and BW2

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#790]
Hi again,

When I open my White game (I downloaded the C-gear from Nintendo back then-it is the official one) with PKHeX and go to the C-Gear Skin Tab,I can see the C-gear skin correctly:
![2017-01-31](https://cloud.githubusercontent.com/assets/20145301/22471213/6269276c-e7da-11e6-8cd2-89ce48a87aac.png)

This is what happens when I import a .cgb/ .psk file (i.e. Charizard [PPorg].cgb) from projectpokemon and press save in PKHeX, then re-opening the C-Gear Skin Tab:
![2017-01-31 2](https://cloud.githubusercontent.com/assets/20145301/22471435/fcd76eda-e7da-11e6-9951-6e033cf8ca1e.png)

In my White 2 game, I imported the C-Gear Skin with PokeGen from projectpokemon, PKHeX is showing a black screen:
![2017-01-31 3](https://cloud.githubusercontent.com/assets/20145301/22471708/da764568-e7db-11e6-8492-99b005ecbf08.png)

When I try to edit it by importing a new .cgb/ .psk file with PKHeX, it shows a glitched screen like White game:
![2017-01-31 4](https://cloud.githubusercontent.com/assets/20145301/22471827/33269ee2-e7dc-11e6-9385-9220b0c3ff03.png)

In-Game on both games, the C-gear is showing the default skin
With PokeGen, the C-Gear Skin from pporg on my White 2 game, imported and works fine in-game and it is showing correctly in PokeGen,in PKHeX it is shows a black screen. 
I don't use PokeGen anymore, I just wanted to test it to see if I would encounter the same error with my cartridge

Thank you

**Comment by kwsch** [comment]
It's an incomplete editor.

**Comment by PrometheusG** [comment]
I am sorry, I didn't knew that.
Thank you
