### ISSUE TITLE
Giratina-Origin and Arceus legality

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#792]
Currently, if you make a Giratina in its Origin Forme that is not holding a Griseous Orb (which causes the transformation), it is deemed legal by PKHeX.

![image](https://cloud.githubusercontent.com/assets/17801814/22478999/22926e20-e7ba-11e6-9e4c-326d1179f4a9.png)

Likewise, if you make an Arceus in any Forme other than Normal without the corresponding Plate to match its Forme, it also deemed legal by PKHeX.

![image](https://cloud.githubusercontent.com/assets/17801814/22479039/44524ef4-e7ba-11e6-9487-99eb25c879ec.png)

I bring this up because I noticed that Keldeo's Forme change is recognized as illegal, due to the fact that Keldeo must have Secret Sword to become Resolute Forme (which is how it SHOULD be). Likewise, Giratina-Origin should be holding Griseous Orb, and Arceus of any other Type should be holding its corresponding Plate.

![image](https://cloud.githubusercontent.com/assets/17801814/22479053/5ae964c2-e7ba-11e6-8d1a-e9f302ea4b2d.png)

**Comment by sora10pls** [comment]
Also should be noted: Z-Crystals also change Arceus' Type.

**Comment by Dionicio3** [comment]
Odd...
