### ISSUE TITLE
Coverting Pokemon from Gen 5 to 6 Applies Markings

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#798]
When converting a PK5 to PK6, it appears that all markings are applied, regardless of whether there were no markings or if only some markings were applied.

https://github.com/kwsch/PKHeX/blob/master/PKHeX/PKM/PK5.cs#L350

**Comment by kwsch** [comment]
Right, it'll copy whatever markings are currently applied to the new pkm file. Not sure I understand what the issue is here.

**Comment by ReignOfComputer** [comment]
Sorry, wasn't clear enough. For example, if a PK5 has no markings at all, converting it to PK6 will somehow set all markings. See image.

![image](https://cloud.githubusercontent.com/assets/2667537/22493722/cf0acb18-e86c-11e6-9da8-b0b33d025000.png)
