### ISSUE TITLE
Help with Compiling.

### ISSUE THREAD

**Issue by Arch9SK7** [kwsch/PKHeX#805]
Sorry for this being so skid to ask but how would I compile it to be just the .exe standalone again like the past. When I compile, it can't run without being in the same directory as PKHeX.core and the DLL files and such. 

Thanks.

**Comment by apassiou** [comment]
This is for reporting issues, not for asking for help compiling.

**Comment by kwsch** [comment]
The releases use ILMerge to merge the dll into the .exe
You can do the same, but there's really no reason to be afraid of a dll. It's just code.
