### ISSUE TITLE
Question/Request: Potential PC Box Form Checks?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#806]
Some Pokemon with multiple Forms have their Form reverted to Normal when deposited into the PC, making certain Forms in the PC technically not legal. Examples include Shaymin-Sky, all of Furfrou's trims, and Hoopa-Unbound; when these Forms are deposited into the PC, they automatically revert to 0 (Shaymin-Land, Furfrou-Natural, Hoopa-Confined).

My question is, would adding checks for these Pokemon be a possibility at all? Legal if Pokemon is in Party, illegal if Pokemon is in any PC Box slot. I could totally understand why they wouldn't be, but I figured I'd ask.

**Comment by kwsch** [comment]
Possible? Yes
Difficulty? Low (for me at least, I can implement the changes listed below later today)

Refer to the clickLegality method;

* Method called, finds if it was called from Tabs or from a stored slot via getSlot
* If the slot is -1 (not from a SAV storage slot, ie from Tabs), it prepares from tabs
* Else it grabs it from the save file.

Note that a [PKM has properties for Box and Slot](https://github.com/kwsch/PKHeX/blob/master/PKHeX/PKM/PKM.cs#L18), but they are unused asides from the Batch Editor (really, when retrieving BoxData, a `PKM[]` from the SAV.

If the PKM is from the save file and not tabs, we can check if it is in the party. The getSlot method has boxes ordered in BOX-PARTY-MISC.

So, if we know the slot it came from and that it came from the save file, we can insert the following [here](https://github.com/kwsch/PKHeX/blob/b7a29c1017db2db57ef16079c99e30d4c37b0cbc/PKHeX.WinForms/MainWindow/Main.cs#L3531-L3538):
```
            int slot = getSlot(sender);
            PKM pk;
            if (slot >= 0)
            {
                pk = SAV.getStoredSlot(getPKXOffset(slot));
                if (slot < 30 || slot > 36) // not party
                    pk.Box = CB_BoxSelect.SelectedIndex; // mark as in a box
            }
            else if (verifiedPKM())
                pk = preparePKM();
            else
                return;
```

Then in the `verifyForm()` legality check, we can add all of the species cases sequentially and check as follows:
```
if (pkm.AltForm != 0 && Box > -1) // has form but stored in box
    AddLine(Severity.Invalid, ....);
```

This will work for opening the Database Search as well, as (already mentioned) SAV.BoxData applies the Box & Slot values to the object for searching/modification.
