### ISSUE TITLE
"Corrupted save" on Moon with the latest build from source

### ISSUE THREAD

**Issue by Asia81** [kwsch/PKHeX#809]
Hi.

I compiled the last source of PKHeX.
I have just added a legal magikarp (just it, I didn't touch another thing), and I got "Corrupted save".

Same when restoring with JKSM and Save DataFiler.

I will try with the latest stable release, but this is just to let you know there is maybe something wrong with one of the latest commits.

**Comment by Skywalker25** [comment]
I used the latest commit and I have the same issue

**Comment by leanderson2006** [comment]
The same problem happened to me, I used to build 1639. But even with the corrupted save using pksm bank, it fixed the save

**Comment by Skywalker25** [comment]
Yes, I have noticed that too. Even if the game shows it as corrupted you are able to open it in pksm and re-save it and fixes the problem.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/898dbaf5dacbd72cd38c435a2762424df3f0de84

Recent change, fixes in progress. Just re-save with a version prior to this commit.

**Comment by SciresM** [comment]
Should theoretically be fixed: https://github.com/kwsch/PKHeX/commit/18c2cc4939bbe0c4e53e0e971a15089ffbc86089

Anyone want to verify?

**Comment by ReignOfComputer** [comment]
Still getting corrupted game save data with https://github.com/kwsch/PKHeX/commit/18c2cc4939bbe0c4e53e0e971a15089ffbc86089.

**Comment by leanderson2006** [comment]
Problem still persists in commit 18c2cc4

**Comment by SciresM** [comment]
Okay. Give me 15 minutes or so :)

**Comment by SciresM** [comment]
Okay, https://github.com/kwsch/PKHeX/commit/03780702638e761d1682dda5f764c47db1b5815a

I tested locally using Citra, and it seems to work fine.

If someone else can confirm I'll close the issue.

**Comment by ReignOfComputer** [comment]
All's good!
