### ISSUE TITLE
how to set pokemon nikename default

### ISSUE THREAD

**Issue by HeJerry** [kwsch/PKHeX#813]
Because my version of the game is played localization patch, so the name of the pokemon is chaotic, a lot of different areas of the pokemon on nicknames are not corresponding to the name, how to modify, please?
I want use Bath Editor

**Comment by egzonqj** [comment]
I don't get what do you want to do. Can you explain it, somehow, better?

**Comment by kwsch** [comment]
PKHeX does not support ROM Hacks.

You can always create a fork of the program and replace the text_species_en.txt with the list of species names.

**Comment by HeJerry** [comment]
It‘s meaning Alert：Nikename is emoty,  so i must select check box twice ,nikename auto appear. Can i use batch editor complete this operate ? @kwsch
