### ISSUE TITLE
No Egg in Party slot 1

### ISSUE THREAD

**Issue by mcdrill89** [kwsch/PKHeX#815]
![firstpartyslotnoegg](https://cloud.githubusercontent.com/assets/3318921/22609381/ff70bbbe-ea2e-11e6-92c3-683f80e7afbb.png)
I'm not sure if this is intentional or something that needs to be addressed. I mean it's arbitrary for me since I can just move them down Figured I'd let you guys know

**Comment by ricksee** [comment]
You can't have an egg in the first slot. That's where your starting Pokemon comes out in battle. An egg can't battle.

**Comment by mcdrill89** [comment]
Okay I wasn't sure since it's possible to have it in the game and the game just goes to the next available non-egg pokemon down the party when it comes to battle

**Comment by kwsch** [comment]
Rather than checking all slots for a non-egg, PKHeX just prevents setting the first slot to nothing/egg. Can only protect so much, as Drag&Drop doesn't prevent you from not having a pkm in your party.

**Comment by mcdrill89** [comment]
No I get it I just wasn't sure sorry for wasting your guys time
