### ISSUE TITLE
Lv50 Stats (suggestion)

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#817]
Not that important, but would be cool to see the Lv50 stats of a pokemon in the stats windows regardless of its current level.

something like this:
![level50](https://cloud.githubusercontent.com/assets/14510301/22620600/6d068b7a-eae5-11e6-9cd2-f894560b1ee3.jpg)

:D

**Comment by egzonqj** [comment]
iirc, this has been suggested already long time ago, anyway, you can always check that by changing the level, it's not that a big deal

**Comment by kwsch** [comment]
>you can always check that by changing the level
this, it's less visual clutter.
