### ISSUE TITLE
PelagoEventStatus not available in Batch Editor

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#825]
In an earlier post, I saw that it stated that PelagoEventStatus was an option in the Batch Editor but its not there and neither is 0x2A.

**Comment by Skywalker25** [comment]
It is. but is not listed in the drop menu. Obviously Marshado cannot be legal but PelagoEventStatus is in the Batch Editor. I'm using commit f64d31c.
![capture](https://cloud.githubusercontent.com/assets/17167674/22629557/593b987a-ebb6-11e6-97a2-252558771a98.PNG)
![pokeeventstatus](https://cloud.githubusercontent.com/assets/17167674/22629558/593c7bd2-ebb6-11e6-9d7d-0e2f81cbefc1.PNG)
