### ISSUE TITLE
Properly handle "Open with..."

### ISSUE THREAD

**Issue by Tsunamical** [kwsch/PKHeX#828]
Right now, you can drag a file over an already open PKHeX form to open the file, however if you try to right click, open with PKHeX or drag the file over PKHeX, it will fail to open properly. Tested on W10.

**Comment by Mrtops** [comment]
Could you leave a the error message please because I tried to right click and use open with PKHeX using a Pokemon Sun save and it worked fine

**Comment by kwsch** [comment]
Could be that your "Open with..." exe path was moved?

**Comment by Tsunamical** [comment]
I'm trying to open a .pk6, and it opens the form, it just sets it to Marshadow and keeps IVs, stats and stuff of the original pk6.

**Comment by Mrtops** [comment]
That is weird I just tried using Commit #f64d31c and got the same result it changes everything except the pokèmon species and leaves that as Marshadow.
