### ISSUE TITLE
Add Box filter in pkmdb

### ISSUE THREAD

**Issue by Mrtops** [kwsch/PKHeX#829]
@kwsch I was wondering if you could add a sort by box filter to the filters in the pokemon database filter options in PKHeX. I realize that this is an enhancement and probably won't happen soon but I would like to know if it is a possibility to add to the enhancement waiting list.

**Comment by kwsch** [comment]
Not sure I follow... what exactly are you trying to accomplish?

Data loaded from folders is displayed in order according to the file name (folder included), so it'd sort by folder and then by filename.
Data from the currently loaded save file is displayed in the same order it appears in for the boxes.

You can filter the search with the advanced filters (tools->settings->advanced search) using the same batch editor instructions.

**Comment by Mrtops** [comment]
When you dump boxes to the database it creates folders I wonder if there is a way to have those folders separated in the database menu like you would click a button to drop down a list of a the Pokemon in that folder

**Comment by Mrtops** [comment]
On a completely unrelated topic would it be possible to incorporate a database of smogon competitive Pokemon in PKHeX in the future?

**Comment by kwsch** [comment]
folder filtering: just use the [IdentifierContains](https://github.com/kwsch/PKHeX/commit/065795cdbea6a8277c35030f697de38b9de6f7a8) command to filter box names

>database of smogon competitive Pokemon

people can always pass around zips of pkm files, no need to include it in the program

**Comment by Mrtops** [comment]
Ok thanks
