### ISSUE TITLE
Adding .ds# Save States support?

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#831]
Can you add a save states support to edit them (as Pokegen)? It would be really useful

**Comment by kwsch** [comment]
We tried this with ramsavs in generaiton 6 and it was a huge hassle, which ended up getting dropped as save exporting became a thing.

The .dst files are just memory snapshots of the emulator and are specific to the game and emulator version. Just export backup memory.

**Comment by Real96** [comment]
Ok, thanks anyway!
