### ISSUE TITLE
Options restart when you close the application

### ISSUE THREAD

**Issue by j0zu3** [kwsch/PKHeX#833]
After 20170207 version, if it's the first time you open pkhex, the settings are not being saved like language and always ask for backups even if you accept the first time
It's seem like the pkhex folder with settings in appdata are not begin created anymore

**Comment by kwsch** [comment]
check if there's a "config error.txt" in your exe folder.
Settings are now saved when the application is closed.

**Comment by ReignOfComputer** [comment]
I'm facing this issue too. No error.txt.

**Comment by sharpedit** [comment]
Same issue, every time I restart the program, the changelog window pops up.

**Comment by kwsch** [comment]
Settings weren't saving unless a change was made (set/delete/save via editor).

Workaround with current release is to make a modification in the save file before closing => settings save.
