### ISSUE TITLE
Dex tab Enhancment

### ISSUE THREAD

**Issue by Mrtops** [kwsch/PKHeX#837]
Would it be possible to add a feature to the pokedex editor that sets the pokedex to everything that you have your boxes

**Comment by kwsch** [comment]
Why? Entries are automatically registered when you import/set files to the SAV. 

You can always re-register everything by importing your dumped boxes instead.

**Comment by Mrtops** [comment]
So that way it is there and if someone wants to use it it is there it was just one of the ideas I brainstormed that could potentially be a future enhancement

**Comment by kwsch** [comment]
Not implementing, sufficient alternative already exists.
