### ISSUE TITLE
Can't import .wc6 files to sav.

### ISSUE THREAD

**Issue by diegofg10** [kwsch/PKHeX#85]
Every **.wc6** file created or legit ([Gen VI Event Contribution Thread 2016](https://projectpokemon.org/forums/showthread.php?48113-Gen-VI-Event-Contribution-Thread-2016)) return "File is not a Wonder Card" error when tried to import to sav on **3/19/16** build.

Same files read without problem on **2/16/16** build.

**.pk6** data of **.wc6** files seems to load correctly.

**Comment by kwsch** [comment]
[Previously reported](https://projectpokemon.org/forums/showthread.php?48327) and [Fixed](https://github.com/kwsch/PKHeX/commit/0ceec780a10408bda4dfc7cd7fea7040d49ff878)
