### ISSUE TITLE
Question: possible to remove shininess while making .pk1?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#853]
Unless I'm missing some sort of button or shortcut, once clicking the star above the species name to make it shiny, I don't seem to know how to undo that and make it not shiny again.

Obviously, in any other instance you would just reroll the PID... but we can't do that for .pk1

**Comment by kwsch** [comment]
Randomize IVs instead :)

**Comment by sora10pls** [comment]
Perfect, thanks!
