### ISSUE TITLE
Pokemon from horde encounters considered illegal if pokemon has hidden ability, pokemon link glalie(oras) considered illegal

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#86]
My minun from route 5 (xy) has volt absorb(its hidden ability) and was captured legitimately but it is considered illegal by pkhex.

The problem with glalie is that it says that it's not a valid link gift and pkhex also complains about its relearn moves (which are nonexistent).

**Comment by kwsch** [comment]
Resolved in a [recent commit](https://github.com/kwsch/PKHeX/commit/36d74b8d8569128b67b2c728ea6d92a08a3ea0bc).
