### ISSUE TITLE
[RBY] Separate VC from Emulator/Cartdrige saves

### ISSUE THREAD

**Issue by xJoelituh** [kwsch/PKHeX#860]
There are some Pokémon that cannot learn some moves in RBY VC. Those are mainly from GSC and trade them back to RBY. This includes things from the [PCNY Events](http://bulbapedia.bulbagarden.net/wiki/List_of_Gotta_Catch_%27Em_All_event_Pok%C3%A9mon) and some other events and level-up changes that were in GSC(This is called "[Tradebacks](http://www.smogon.com/rb/articles/tradebacks)"). 

Also, there are some [Prize Pokemon](http://www.serebii.net/stadium/prizes.shtml) from Stadium (Although the only one that really matters is "Amnesia Psyduck", because all the other ones can be obtained in-game.)

I think, the best way to pull this off would be, finishing legality checks from regular RBY and, make an alert when a RBY save is detected (Like it happens with FRLG saves) and ask if it's from VC or not. And make Gen 1 -> Gen 7 exclusive to VC legality.

PS: Here is a [list](http://rby2k10.proboards.com/thread/95/rby-tradebacks-move-list) with every GSC -> RBY tradeback possible. (It doesn't include the Amnesia Psyduck, neither Surf Pikachu/Raichu)

**Comment by Mrtops** [comment]
I think that you have the right idea for the solution it just needs to be implemented

**Comment by javierhimura** [comment]
I think thare are two different options that should be chosed to determine what kind of legallity analysis should be performed.
First to choose betwen VC and Gameboy analysis, but also between gen2-> gen1 tradeback allowed and not. That way if someone want to check if a pokemon is possible in a pure gen 1 it can be done.

In the end Gen 1 will have 3 possible scenarios: Gen 1 GB, Gen 1 VC and Gen 1 GB with tradeback. And in the future if VC2 is released Gen 1 VC with tradeback. Also by the fact VC -> Gen7 transfer is made by bank im not sure if its possible to manipulate the 3DS clock to change the met date in Gen7, that would mean some VC format 7 pokemon wont be legaly with tradeback and some will be legal.

Maybe a pop-up every time a save is loaded is too much, another option is to select the legal mode in the menu for this games.

PD: Another different between VC and GB is the events and stadium 2 prices for gen 2.
