### ISSUE TITLE
Unhandled exception with evolved forms of Virtual Console Pokemon

### ISSUE THREAD

**Issue by spyjdh** [kwsch/PKHeX#864]
PKHeX 17.02.07

Error occurs when trying to load a box with a Pokemon transferred from Pokemon R/B/Y Virtual Console to Pokemon Sun/Moon that was evolved in game. The error can also be created when attempting to change certain Gen 1 Pokemon to another generation's evolution in PKHeX.

Specifically the pokemon evolutions causing crashes are; Bellossom, Kingdra, Rhyperior, Politoed, Crobat,  Magneton, Umbreon, Espeon, Glaceon, Leafeon, and Sylveon.

The following pokemon are showing false(?) flags after evolving; porygon2, slowking,  magmortar, and electrive. porygon-z, steelix, scizor
(Invalid; Should have a Link Trade HT Memory.
Invalid: Should have a HT Memory Intensity value (1st). )

The following do not cause crashes when manually changing pokemon species but have not been evolved in game to test for false flags; alola marowak, blissey

The following neither cause an error nor show a false flag; alola raichu, alola exeggutor, tangrowth, likiliky

Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.Legal.getValidMoves(PKM pkm, GameVersion Version, IEnumerable`1 vs, Boolean LVL, Boolean Relearn, Boolean Tutor, Boolean Machine, Boolean MoveReminder)
   at PKHeX.Core.Legal.getValidMoves(PKM pkm, IEnumerable`1 evoChain, Boolean Tutor, Boolean Machine, Boolean MoveReminder)
   at PKHeX.Core.LegalityAnalysis.getSuggestedMoves(Boolean tm, Boolean tutor, Boolean reminder)
   at PKHeX.Core.LegalityAnalysis..ctor(PKM pk)
   at PKHeX.WinForms.PKMUtil.getSprite(PKM pkm, SaveFile SAV, Int32 box, Int32 slot, Boolean flagIllegal)
   at PKHeX.WinForms.Main.getSlotFiller(Int32 offset, PictureBox pb)
   at PKHeX.WinForms.Main.setPKXBoxes()
   at PKHeX.WinForms.Main.getBox(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.Main.clickBoxRight(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX-win, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Forerunner\Desktop\3ds\PKHeX (170130)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by kwsch** [comment]
Are you using the latest commits or the latest release?

Bank applies memories when dealing with pkm transfers between games, hence why they're checked for 1->7 pkm.

**Comment by spyjdh** [comment]
I noted at the top of the comment I'm using PKHeX 17.02.07.

https://projectpokemon.org/forums/files/file/1-pkhex/

**Comment by spyjdh** [comment]
It should also be noted that pokemon have TM moves only learnable in the R/B/Y VC games. e.g. bide, rage, etc.

**Comment by javierhimura** [comment]
The VC1 legallity checks are not taking into account evolutions added in gens 2 to 6 of gen 1 pokemons, like a gen1 eevee evolved into espeon in a gen 7 game.
I think this errors wont happen in the source code of my pull request, i reworked the get evo chains and get valid moves functions to take into account this cases where a pokemon in previous gens existed with less evolved species and less level than current generation

**Comment by kwsch** [comment]
The latest release does have the described exception message, but the latest commits do not.
