### ISSUE TITLE
Legality Issue with Pokemon Bank Feraligtr with HA

### ISSUE THREAD

**Issue by Tailmon** [kwsch/PKHeX#865]
For some reason this legit Feraligtr is marked as illegal, this feraligtr was distributed in a event on Pokebank
PKHex marks as illegal the move Ice Punch, as far I can see in bulbapedia this move is legal even with tutor or egg move
Greetings
[160 - Feraligatr - 13B45422BB84.pk6.zip](https://github.com/kwsch/PKHeX/files/782182/160.-.Feraligatr.-.13B45422BB84.pk6.zip)

**Comment by Mrtops** [comment]
This is probably just an exception that was not added it should not be to hard to fix.

**Comment by kwsch** [comment]
Don't report things you've tried to create; the legality checker is functioning as intended.

Originated on X, and never was traded to OR/AS. Thus never able to receive a tutored move.

**Comment by Tailmon** [comment]
Sorry to keep bothering with this issue, this isn't a created Pokemon, yes it is originated on X, it's a legit Feraligtr from a Pokebank event and it's marked as a illegal one
http://www.serebii.net/bank/events.shtml
