### ISSUE TITLE
Legality issue for toxapex/relearn moves

### ISSUE THREAD

**Issue by Wormdog** [kwsch/PKHeX#866]
![screen cap](https://cloud.githubusercontent.com/assets/25836392/23052491/c2035d10-f49f-11e6-89fa-c5016bf2141d.png)
![screen cap 2](https://cloud.githubusercontent.com/assets/25836392/23052496/c68af938-f49f-11e6-9071-ab15d7081334.png)
Found an issue regarding relearn move legality, when putting haze on toxapex it list it as illegal which is expected but when i list haze as a relearn move it lists that as inccorect. Not sure if this is affecting other mons aswell

**Comment by ReignOfComputer** [comment]
You didn't read the error. It's missing the base egg move, Poison Sting. For your case, Relearn Moves should be, in order, Poison Sting, Haze.

You can click the Relearn Moves box to automatically set the moves in order.

**Comment by Wormdog** [comment]
I thought i might have made a mistake, thank you!

**Comment by Wormdog** [comment]
I did as you said and still get an error, when clicking the Relearn Moves box it suggests i should have no relearned moves, both Poison Sting and Haze

**Comment by ReignOfComputer** [comment]
Then your Toxapex isn't hatched.
