### ISSUE TITLE
Error: Current Handler can't be past gen OT

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#867]
When ever I look at my Blaziken that was bred in Pokemon Y. It gives the following error: "Invalid: Current handler cannot be past gen OT for transferred specimen." However, even if I change the OT or the Handling Trainers name, it still flags it as illegal. Why does this error keep happening?

**Comment by kwsch** [comment]
Don't have different save files with the same TID/SID/OT.

**Comment by MattOlivoto** [comment]
I'm having the same problem, but i'm trying to generate the pokemon without a save file. May that be the problem ?
