### ISSUE TITLE
Previously legal Zygarde flag as illegal (Unkown Encounter) after obtaining Power Construct.

### ISSUE THREAD

**Issue by choicescarf** [kwsch/PKHeX#868]
I've combed changelogs and issues to see if this was a known issue and have seen no such thing so:

Here is a Zygarde I have that has transferred up to 7th gen with no issues:

![8873d75814](https://cloud.githubusercontent.com/assets/25855503/23088237/89252dd0-f548-11e6-96aa-562f24bf17ee.png)

However, after converting it into a Power Construct Zygarde using the machine on Route 16 it begins to set off alarms:

![0276147e59](https://cloud.githubusercontent.com/assets/25855503/23088238/9053c850-f548-11e6-958a-905b9ab026fa.png)

I've changed nothing about the Zygarde short of running it through an ingame process so the legality check on PC Zygarde originating from 6th gen may need to be eased a little.

**Comment by kwsch** [comment]
As far as I understand you can't `convert` a Zygarde; you have to disassemble it and reassemble it. It'd lose any past gen information as it's an entirely new Pokémon.

Can't really tell anything else from the pictures that have been posted.

**Comment by choicescarf** [comment]
I can attach the .pk7 itself if it'd help but you absolutely can convert Zygarde from 6th gen.

At the machine you have the option of assembling a PC Zygarde using an existing Zygarde and 50 cells. If you do this with one from 6th gen it retains its ball, ribbons and the like.

**Comment by sora10pls** [comment]
Can confirm that what @choicescarf says is true. You can convert a Gen 6 Zygarde 50% into 50%-C no problem, so long as you have the extra 50 Cells to give it Power Construct :)
