### ISSUE TITLE
German demo Ash-Greninja imported legit into English game flagged as illegal.

### ISSUE THREAD

**Issue by Nyquis** [kwsch/PKHeX#869]
I have a German legit ash greninja imported from demo into Pokemon Sun english version. It is errenously flagged as illegal due to nickname.

**Comment by Mrtops** [comment]
Are you on the latest update version 17.02.07

**Comment by Nyquis** [comment]
Yes. Currently I have tested it on the 17.02.17 build and the and almost every master branch build such as the latest one : [139d081](https://github.com/kwsch/PKHeX/commit/139d08160bf0cd446149ec0806ece29a7e815921)
