### ISSUE TITLE
Altering things in xy event flags resets the encouter with sycamore in lumiose city's pokemon lab to the event that happens when you first encounter him and he gives you the kanto starters

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#87]
So far, I have only tested with battle maison related things (in event flags, not trainer info) so I don't know the specific flag that causes this but the fact is that it resets that specific encounter with professor sycamore. After you battle him and he gives you the starter you picked, go downstairs and you will encounter Lysandre. Then, your rivals will appear. After that I assume everything goes like as expected (you find your rivals in the places they said they would go to) but I don't know because I reset the game).

**Comment by kwsch** [comment]
That's what happens when you modify event flags; there may be unintended side-effects.

The game uses event flags to track story progress and to determine when certain events should trigger. There may be side effects as certain events trigger successive events.

**Comment by poutros** [comment]
But I only alter battle maison related things. This means the code used to alter those flags is wrong.

**Comment by kwsch** [comment]
No, it does not mean the code is incorrect.

The game may use certain event flags to trigger OTHER events. For example, the game may disable a legendary from appearing in the overworld until the correct time in the story. If you force that event flag, other events that rely on that flag (in addition to others) may cause those events to trigger at odd times.

It's just how the game works.

**Comment by poutros** [comment]
Except battle maison related events are not supposed to trigger early game events like that one.

**Comment by poutros** [comment]
This is the event that is triggered btw:
https://youtu.be/sqmvelV2JA0?t=8m30s

**Comment by kwsch** [comment]
Game Freak only has 3072 flags to use to track every event in the game; some flags are toggled on and off multiple times as the story progresses. Certain combinations of flags yield certain event permissives.

The checkboxes in PKHeX only toggle one flag at a time. You can view which flag a specific checkbox is altering by viewing the [designer code](https://github.com/kwsch/PKHeX/blob/master/SAV/SAV_EventFlagsXY.Designer.cs).

**Comment by suloku** [comment]
Just some proof that the game uses flags for more than one thing: https://projectpokemon.org/forums/showthread.php?48181-XY-event-flag-50-beat-chatelaine-enabled-on-new-savegame
