### ISSUE TITLE
Broken Gen 1 legality checks + bug reports

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#872]
As of commit 0f45add

Commit 679efcd:
![image](https://cloud.githubusercontent.com/assets/17801814/23111154/ac2bd1fa-f6f4-11e6-85bb-d341cfe5a02a.png)

Commit 0f45add:
![image](https://cloud.githubusercontent.com/assets/17801814/23111145/9a408f80-f6f4-11e6-96a4-a478f512c584.png)

Tested with the same save file among multiple builds, can only reproduce using commits 0f45add and above. Anything prior to this works.

Edit: mixed up the commits I was referring to, comment's been updated accordingly.

**Comment by Mrtops** [comment]
I will have to look into this this is probably just a minor exception that was removed

**Comment by Mrtops** [comment]
Try again and see if error still happens on commit https://github.com/kwsch/PKHeX/commit/139d08160bf0cd446149ec0806ece29a7e815921 I would but I do not have a RBY game

**Comment by sora10pls** [comment]
It still is broken with that commit. Like I said, anything from 0f45add onward is broken

**Comment by Mrtops** [comment]
@kwsch I cant seem to find where the legaity checks for Venasaur are. @sora10pls Also is this happening only with Venasaur or is it happening with other Pokemon to?

**Comment by sora10pls** [comment]
As shown in the picture, EVERY single Pokemon, no matter if they are legal or illegal, are flagged as illegal. This is the exact output given to me by PKHeX:
![image](https://cloud.githubusercontent.com/assets/17801814/23135206/b1b685f4-f765-11e6-9061-0c85caf01998.png)

**Comment by sora10pls** [comment]
And while we're on the topic of Gen 1 legality, I figured I'd drop info on Mr. Mime seeing as how it's the only Pokemon in Gen 1 that can only be obtained through in-game trade.

Obtained directly through Pokemon Blue VC.

Nickname: `MARCEL`
Minimum Level (R/B): `7`
Minimum Level (Y): `8`
TID: `04827`
OT: `TRAINER`

Level of the Mr. Mime matches that of the Level of the Pokemon you traded (Abra in R/B which has a min. Level of 7, and Clefairy in Yellow which has a min. Level of 8).

@kwsch

**Comment by sora10pls** [comment]
Found two more things.

First, when importing `.pk1` files into a Gen 7 save file, every Pokemon that isn't from a static encounter/gift is flagged as illegal with the following error:
![image](https://cloud.githubusercontent.com/assets/17801814/23135782/f1c1cdd2-f767-11e6-93ce-338220bfbb4d.png)

This is the full error:
![image](https://cloud.githubusercontent.com/assets/17801814/23135793/faa66bec-f767-11e6-8cb4-dfe303b252a0.png)

And second, Vaporeon/Jolteon/Vaporeon with Focus Energy from Gen 1 VC are flagged illegal when it is a valid pre-evolution move learned by Eevee at Lv. 36.
![image](https://cloud.githubusercontent.com/assets/17801814/23136109/2a01d664-f769-11e6-9dca-29cf626ea300.png)

**Comment by Mrtops** [comment]
Are you sure that Eevee learns that in RBY and that it was not changed to be updated with new generations

**Comment by sora10pls** [comment]
Yes, Eevee gets this move at Lv. 36 in Yellow. Bank uses Yellow learnsets, so this should be legal.

**Comment by sora10pls** [comment]
Any chance you took a look at the other comments I posted here, @kwsch? :)

Namely the Mr. Mime legality, and the Gen 1 -> 7 transfer falsely flagging non-static/gift Pokemon as illegal.

**Comment by kwsch** [comment]
@sora10pls Ingame trades were not yet added.
