### ISSUE TITLE
[Question] Sav States?

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#881]
Would it be possible to edit the save states that emulator's make, lets say I create a save state after collecting 1 pkm, reset to prior state, collect 2nd pkmn and make a diff save state. would just be easier than having to reset and reload multiple sav files.

**Comment by sora10pls** [comment]
#831

**Comment by Mrtops** [comment]
Sorry, but I agree with kwsch it is way to much of a hassle.

**Comment by Ninjistix** [comment]
i'm not only implying about the .ds, but i see its been inquired about before. thanks
