### ISSUE TITLE
Feature Request (Dumping PKMN adjustment)

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#883]
When Dumping Pokemon in PKHeX it places all the PKMN from boxes into the pkmndb folder, but it does not organize them by Game/Sav Name, it does do .pk1, pk2, pk3 etc... but it would be better to do, /gamename/pk1 or something along those lines

**Comment by Ninjistix** [comment]
essentially looking for a cleaner organized DB, so I don't have to remember which game which PK* came from.

**Comment by Mrtops** [comment]
You can use the database filter options in PKHeX to organize your Pokemon database. Why add complications to the database folder when you can sort it using PKHeX instead.

**Comment by Ninjistix** [comment]
the database doesn't allow you to filter by game version, just by pk version... and i'm talking about when the boxes are dumped, they dump all pk* files in 1 folder location regardless of game/gen, what I'm asking/suggesting is to have that process sort the dump by the game version/file name, so its better organized... what if i want pk files from a specific game for whatever reason.

**Comment by Mrtops** [comment]
You can use the OT filter to choose which gen the OT is.

**Comment by Ninjistix** [comment]
![ot version](https://cloud.githubusercontent.com/assets/12572974/23320161/9d0bdb6e-faa7-11e6-93c2-1b9f38df1b5d.png)
are you referring to the Above?

Pokemon Red - Returns no results
Pokemon Blue[INT]-Green[JP] - Returns no results
Pokemon Gold - Missing from list
Pokemon Silver - Missing from list
Pokemon Crystal- Missing from list

haven't tested the other OT filters since i'm restarting all games...

but all of that is withing PKHeX itself, I'm referring to the folder structure saved in Windows...

![pkmndb windows](https://cloud.githubusercontent.com/assets/12572974/23320406/9b1c6a8e-faa8-11e6-94bf-855550533cf6.png)
 
Having something like pkmdb/gameversion/ then pk* files would be easier to organize outside of PKHeX

**Comment by Ninjistix** [comment]
![part 1](https://cloud.githubusercontent.com/assets/12572974/23320595/6a842582-faa9-11e6-9a72-057d596cc3c9.PNG)
![part 2](https://cloud.githubusercontent.com/assets/12572974/23320597/6d6cabb6-faa9-11e6-9bfb-ed976dbd9873.PNG)
![part 3](https://cloud.githubusercontent.com/assets/12572974/23320599/6fd1fc94-faa9-11e6-8313-809c83b672df.PNG)


DB contains my dump from PKMN Red/Blue/Silver and Sapphire (for whatever pkmn I have), but as you can see above, the filters fro Red/Blue don't work, and GSC are missing.

**Comment by kwsch** [comment]
PKHeX stores files regardless of origin SAV to a single folder; the only thing differentiating the files is the filename (which contains a unique identifier as well as the format). It's done this way to reduce the amount of duplicate files saved (a pkm may be cloned to another save file).

The program retrieves files from the database folder, and all sub-directories inside. You can always dump to a specified folder with separated boxes, then move it into the db folder.

Formats 1/2 do not store the Version it originated from, so any pk1/pk2 files will not get picked up; only when they are transferred to 7+ do they receive the Version ID that they were transferred from.

The Database can use the same batch editor filter commands, so you can search the identifier (file path contains...) or any other property not immediately visible on the search pane. This can be done via `"=IdentifierContains=textString"`, where textString is a string within the identifier. The identifier is set to the file path for all .pk* files; for the currently loaded save file, it is set to the box name / slot.

**Comment by Ninjistix** [comment]
Okay, so the work around would be to not dump it directly to the pkmdb but to save it under a Folder (with a specific name), then move that folder to the pkmndb location.

**Comment by kwsch** [comment]
Correct.
