### ISSUE TITLE
Incorrect Gen 3 game recognition

### ISSUE THREAD

**Issue by LegoFigure11** [kwsch/PKHeX#887]
I was just using PKHeX to check the TID/SID of a new FireRed U save (no Pokemon on it, just saved as soon as I could after the intro scene) and it tried to load it as a Ruby Sapphire save, leading to a bunch of errors when trying to edit inventory and money.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/146
https://github.com/kwsch/PKHeX/issues/305

Receive your first pokemon before trying to edit.
