### ISSUE TITLE
Gen3 - PC Items tab missing?

### ISSUE THREAD

**Issue by fattard** [kwsch/PKHeX#889]
![gen3](https://cloud.githubusercontent.com/assets/1159052/23336073/a6e26e9a-fba2-11e6-8e88-c536ada1ba41.png)

From the above image, Gen1/2 does have a PC items tab, while Gen3 does not.

Not sure if this is intentional or not, but I searched over closed issues and did not find anything related to PC Items in Gen3. Sorry if this was already disclosed before.
So, is it missing, or there's some development issues right now?

Anyway, I can use 'A-Save' for this feature right now.

**Comment by kwsch** [comment]
Wasn't documented; once someone documents the offsets for RS/E/FRLG they can be added.

**Comment by fattard** [comment]
At least, it seems documented in [http://bulbapedia.bulbagarden.net/wiki/Save_data_structure_in_Generation_III](http://bulbapedia.bulbagarden.net/wiki/Save_data_structure_in_Generation_III)

RSE: 0x0498 (size: 200 bytes)
FRLG: 0x0298 (size: 120 bytes)
