### ISSUE TITLE
Feature Request: S/M legit available items

### ISSUE THREAD

**Issue by lomejor18** [kwsch/PKHeX#891]
is it too difficult to add "unavailable items" on S/M legality check? like some megastones or some berries? or that's not worth the effort? thanks

**Comment by ReignOfComputer** [comment]
You got a list of unavailable items?

**Comment by lomejor18** [comment]
@ReignOfComputer serebii has a S/M item list, blank spaces means not available:

http://www.serebii.net/sunmoon/items.shtml
