### ISSUE TITLE
Gen 4 OT Glitch

### ISSUE THREAD

**Issue by pkmnbumba** [kwsch/PKHeX#894]
Pokemon disappearing & OT changed

This is what happened:
I was editing the nature of my synchronizer when RNGing and moving my team around when my Feraligatr disappeared (this was all done in the party box).
I didn't think much of it since I just needed the synchronizer with the right nature but then I was on my second RNG when I realized that it changed the game's OT. It went from "Shy" to "?hy" in game while in PKHeX, there was no nickname displayed.

**Comment by kwsch** [comment]
Unable to reproduce anything described here; please figure out how to reproduce whatever issue you are experiencing and list the steps / files required.

**Comment by pkmnbumba** [comment]
I'll give it a go when I get home. As a side note, I've been getting a lot of 'save file corrupted' recently after editing things in pkhex for gen4. I'll try and reproduce these and let you know.

**Comment by pkmnbumba** [comment]
I was able to recreate it but it seems that this bug doesn't happen with every save. Is there an email I can send the save to? I used this save for RNGs for someone and I don't want it to be publicly available to people reading through the comments.

The steps are this:
- Change the second pokemon's nature to Timid (this causes the first Pokemon to disappear)
- Replace the empty space create in the first slot with the third Pokemon (this causes the OT to glitch)

**Comment by kwsch** [comment]
Can PM on the forums or send to my username (on forums) @ gmail.com

**Comment by kwsch** [comment]
Still not able to replicate with the steps listed & save file provided (OT: Test).

**Comment by Wynadorn** [comment]
I ran into this issue as well yesterday. The first pokemon in my party box by chance was also a Feraligatr, it became a red square (bad egg).
Also my trainer name in the trainer info (card) became corrupted. It had some alt-codes in there.

Maybe this was related to #909, If I run into it again today ill let you guys know.

**Comment by kwsch** [comment]
@Wynadorn yep
