### ISSUE TITLE
Held Item legality check bugs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#895]
Edit: useless, refer to below comment.

**Comment by sora10pls** [comment]
All information listed below is based on Gen 7, other Generations may (and probably will) vary.

Items that are flagged as illegal and should be legal:
- Adrenaline Orb
- Alakazite
- Assault Vest
- Blastoisinite
- Blue Orb
- Casteliacone
- Chill Drive
- Eject Button
- Festival Ticket (shouldn't be included to begin with, it's a Key Item)
- Garchompite
- Glalitite
- Gold Bottle Cap
- Grassy Seed
- Griseous Orb
- Ice Stone
- Lucarionite
- Mail #1 (G4)
- Mewnium Z
- Poké Doll
- Poké Toy
- Purple Nectar
- Quick Ball
- Rage Candy Bar
- Razor Claw
- Sablenite
- Safety Goggles
- Salamencite
- Shalour Sable
- Stick
- Strange Souvenir
- Tapunium Z
- 

Items that are flagged as legal and should be illegal:
- Abomasite
- Ampharosite
- Audinite
- Latiosite
- Manectite
- Marshadium Z
- Odd Keystone
- Old Amber
- Pidgeotite
- Relic Band
- Relic Copper
- Relic Crown
- Relic Gold
- Relic Silver
- Relic Statue
- Relic Gold
- Relic Silver
- Relic Statue
- Relic Vase
- Sceptilite
- Shoal Shell
- Snowball
- Yellow Scarf

And finally, these are Items that should always be considered illegal (unobtainable in all Generations outside of certain areas):
- Cherish Ball (can never be obtained)
- Dream Ball (temporarily obtained in Entree Forest)
- Safari Ball (temporarily obtained in Safari Zone/Great Marsh)

Will update through edits if I find any more discrepancies.

**Comment by kwsch** [comment]
it's just an off-by one error lol

**Comment by sora10pls** [comment]
go figure that'd be the case, oh well lmfao

**Comment by kwsch** [comment]
should be good now

**Comment by ReignOfComputer** [comment]
Lol I thought it was something I did D:

**Comment by sora10pls** [comment]
That did fix a majority of them, but these Items are still falsely flagged as legal:

- Dream Ball
- Relic Band
- Relic Copper
- Relic Crown
- Relic Gold
- Relic Silver
- Relic Statue
- Safari Ball
- Snowball

**Comment by ReignOfComputer** [comment]
Serebii didn't have those on the list so I didn't add them, thanks. Will add them in a bit.

**Comment by sora10pls** [comment]
No problem, I just scrolled through the list of Items available in PKHeX and double-checked each individual entry on Serebii to see whether or not it's available in Gen 7 :)

**Comment by ReignOfComputer** [comment]
You missed Relic Vase :P
Btw are you sure Snowball isn't available in SuMo? Looks to be held by wild Vulpix and Snorunt.

**Comment by sora10pls** [comment]
Ah I had Relic Vase listed in my initial list, and then removed it lmao

As for Snowball, you're right, I just ignored the bottom of the page.

**Comment by ReignOfComputer** [comment]
Would like to note that the off-by-one error still persists.
