### ISSUE TITLE
Feature request: still show suggested results containing accented letters if non-accented letters are used

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#896]
Title should be pretty clear. If not, here's an example:

User types in name with appropriately accented letter, results show as intended:
![image](https://cloud.githubusercontent.com/assets/17801814/23345131/e5cb2b56-fc56-11e6-91b2-3080a036a6ba.png)

User types in name without accented letter, no results are shown:
![image](https://cloud.githubusercontent.com/assets/17801814/23345119/cc84178e-fc56-11e6-81cb-201187458171.png)

Ideally, it should work like this:
![image](https://cloud.githubusercontent.com/assets/17801814/23345154/380917ca-fc57-11e6-8166-d48240cd0aa5.png)

**Comment by ReignOfComputer** [comment]
Requesting this for "Poke Ball" under Held Item / Ball too.

**Comment by kwsch** [comment]
ComboBox doesn't have the ability to override the autocomplete search behavior. Much more suited for a pull request if someone got it working rather than a feature request.

Looks like "Flab" -> Flabébé is the only result, and "Pok" -> Poké Ball is the only result too. Just type less characters :)
