### ISSUE TITLE
[FEATURE REQUEST] Legality added to Box Data Report

### ISSUE THREAD

**Issue by mjd85** [kwsch/PKHeX#899]
Any chance we could get legality as a Column in the box data report? Something similar to Shiny Status?

IsLegal? Would spit out True/False.

Would be very useful. Thank you!

**Comment by kwsch** [comment]
And the use is?
The database search can search for legality in addition to other properties; use it to prune your results prior to generating the report.

**Comment by mjd85** [comment]
I keep a spreadsheet with various save files, and it would be cool to see at a glance all of the Pokemon I have that are legal and which are not. Some are meant to be illegal.

Just an ease of use thing I guess. Would also be cool to implement checkboxes for the data you would like put out in the sheets as well, but I think I saw that idea turned down before.
