### ISSUE TITLE
4th gen event pokemon originated in platinum have their origin game changed to diamond when transfered through pkhex

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#90]
I don't know if this happens with pearl as well. This also only happens with pokemon received directly from the mystery gift guy, not the shaymin and darkrai that are caught in-game.

**Comment by kwsch** [comment]
Assuming this is an event file (pgt/pcd), PKHeX has no way to know what game received it besides the skeleton PKM within. For example, the VGC 2009 Milotic's version is 10, for Diamond, but the card can only be received on certain games.

PKHeX can't know which game received the event, thus it uses the default one within the card. It is up to the user to supply the actual game received by changing in the editor. Can always just inject to a past gen save, receive, then import the pkm.

**Comment by poutros** [comment]
>Can always just inject to a past gen save, receive, then import the pkm.

Perhaps I didn't phrase it correctly but it is by importing the pkm that pkhex "screws up" and alters the game origin. However, this only happens with event pokemon, not event pokemon files (pgt/pcd), actual event pkm received legitimately in-game, exported using pokegen and then injected using pkhex.

I have the save and the pkms(separately but also in the save as well) in the link below because github is being sttuburn and not allowing me to attach zip files. Open them in pokegen and you will see that the game origin is platinum. However, exporting the pkm to a folder and then importing it to pkhex changes the game location to diamond (tested with the most recent stable build released 26/03/16). That doesn't happen with the other pokemon, only event pokemon that were received through mistery gift in-game at the pokemart.

https://onedrive.live.com/redir?resid=A7459467F2F20460!147804&authkey=!AFynJs58hL0D0vE&ithint=file%2czip

**Comment by kwsch** [comment]
Looking at the raw data, the origin game byte is 0x0A (10), which corresponds to Diamond.

There's some Pt/HGSS met location information, but I do not believe that the origin game byte changes when transferred.

**Comment by poutros** [comment]
Well, pokegen identifies it as platinum and indeed I received them in platinum. But to be honest I received a platinum only event in HGSS and pokegen identifies it as platinum as well. Maybe the met location is tied with the wondercard and therefore registers other bytes (trash bytes maybe?) and not the actual game in which it was received or the byte at 0x5F exclusively?
