### ISSUE TITLE
[FEATURE REQUEST] Using =PID= as criteria

### ISSUE THREAD

**Issue by mjd85** [kwsch/PKHeX#901]
Use case would be mass unshiny without touching other details. I'm sure there would be other uses.

My example would be:

=PID=$shiny
.PID=$rand

This way it doesn't affect ALL pokemon, but it just changes the previously shiny pokemon.

Not sure if it's possible to use it as criteria or not. And I know I can already do this, just in a more convoluted way. It would just be another ease of use feature for the batch editor.

**Comment by mjd85** [comment]
Nevermind. Probably not worth the effort.

**Comment by kwsch** [comment]
```
=IsShiny=True
.PID=$rand
```

The property list only shows modifiable properties; any of the derived properties can still be used for filtering.

**Comment by mjd85** [comment]
Huh, that doesn't show in the Batch Editor.

Is there a list of those somewhere? Things that can be used but don't show up in the Batch Editor?

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/tree/master/PKHeX/PKM

Not every format has the same derived properties, so just looking at PKM.cs may not be enough.
https://github.com/kwsch/PKHeX/blob/master/PKHeX/PKM/PKM.cs#L261
