### ISSUE TITLE
How to use the new legality checker in the Batch Editor?

### ISSUE THREAD

**Issue by Nawor3565** [kwsch/PKHeX#910]
So the new legality checker in the batch editor is something I've been needing for awhile, but I'm not sure how to use it. I tried running .Legal=$suggest, but it just gave the 'Internal Error" message. Is there somewhere I can find documentation on how to use it? Thanks!

**Comment by kwsch** [comment]
Via changelog:

```
Added: Legality filtering and bulk suggestions for Met Location, Current Moves & Relearn Moves.
 - Use $suggest to use suggested result from the legality analysis.
```

Use the mentioned properties.

`Met_Location`, `Moves`, `RelearnMoves`

Using any of the above properties will trigger `[setSuggestedProperty](https://github.com/kwsch/PKHeX/blob/d248cdd28059c96c71deaff7dd9003e6e2a5f9ac/PKHeX.WinForms/Subforms/PKM%20Editors/BatchEditor.cs#L451-L477)`

**Comment by Nawor3565** [comment]
Alright, maybe I'm missing something, I'm not really good at the batch editor. I'm trying to remove all the Pokemon that are legal, but running this command gives the internal error message again.
`=Legal=Moves
.Species=0`
What am I doing wrong?

**Comment by sora10pls** [comment]
The following command sets suggested Met Location/Level:
`.Met_Location=$suggest`

The following command sets suggested moves:
`.Moves=$suggest`

The following command sets suggested relearn moves:
`.RelearnMoves=$suggest`

I don't see what the problem is.

**Comment by kwsch** [comment]
If you're looking to filter by legality, the legality is a boolean (use True/False for values).

If you're wanting to make changes on only illegal pkm, do:

```
=Legal=False
.Moves=$suggest
```
