### ISSUE TITLE
Gen2 Hidden Power

### ISSUE THREAD

**Issue by JFSushi** [kwsch/PKHeX#912]
There's a problem with the Hidden Power calculation for Generation 2 games. Currently, it displays the wrong type for most (if not all) cases. The only types it shows are Ground, Fighting, Poison and Flying. I did some testing with two different Unown (that both have HP Fighting, according to PKHeX) and their Hidden Powers turned out to be Fire and Rock.

While I doubt this is a high priority issue, it'd be neat if it could get fixed somewhere in the future.

**Comment by kwsch** [comment]
#890 
Fixed since last release:
https://github.com/kwsch/PKHeX/commit/cf7f11434de5d6b0496a173400ae0c836bc8fc18
