### ISSUE TITLE
Pokemon marked as Legal with moves they learn at a later level

### ISSUE THREAD

**Issue by mjd85** [kwsch/PKHeX#913]
I've came across the issue with numerous Pokemon. To the point where I'm not sure if it's being checked for legality or not.

My latest example.

Combee Level 1 is marked as Legal even when it knows Bug Bite and Bug Buzz. They're suggested moves even.

Lots of examples like this, and I can bring up more if needed.

http://bulbapedia.bulbagarden.net/wiki/Combee_(Pok%C3%A9mon)
https://pokemondb.net/pokedex/combee

**Comment by kwsch** [comment]
https://projectpokemon.org/forums/forums/topic/40249-mimikyu-legality-question/#comment-211057

**Comment by mjd85** [comment]
Did not realize that changed. Thank you.
