### ISSUE TITLE
Silvally Invalid: Unknown Encounter

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#917]
Silvally and Type: Null should have the same location information, correct?
Also, there is no suggested location for Silvally.
Thanks for reading!
https://snag.gy/mj0EcM.jpg

**Comment by kwsch** [comment]
It evolves via level up; I suspect you still have the current level as 40 not 41+.
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L126
Should have 3 flawless IVs.

**Comment by greenDarkness** [comment]
Nope, it is level 100, and it has perfect IVs. 
Here's the pk7.
http://www.mediafire.com/file/vgq5l3rp7wvucjq/773-04_-_Silvally_-_0E152A5197AC.pk7

**Comment by ReignOfComputer** [comment]
Form issue. PKHeX isn't detecting it correctly when a Memory is attached.
