### ISSUE TITLE
.xdpkm files reading wrong

### ISSUE THREAD

**Issue by Admiral-Fish** [kwsch/PKHeX#919]
![baltoy](https://cloud.githubusercontent.com/assets/24730718/23534272/f71e90d0-ff73-11e6-9733-2a0c50b48688.PNG)
![pooch](https://cloud.githubusercontent.com/assets/24730718/23534271/f71e35ae-ff73-11e6-866c-4d07030c42aa.PNG)
![teddirusa](https://cloud.githubusercontent.com/assets/24730718/23534270/f71b4ae2-ff73-11e6-98b9-6c2bd809b8f9.PNG)

PKHeX is reading the IVs of the .xdpkm file type wrong.

I tested using files from https://github.com/ReignOfComputer/RoCs-PC/tree/master/07%20-%20Gen%20III%20-%20XDCOLO%20Collection/Pokemon%20XD.

**Comment by kwsch** [comment]
PKHeX isn't reading them wrong :)
