### ISSUE TITLE
Feature Request: Extract PKM from PGL QR Code

### ISSUE THREAD

**Issue by ckohnke** [kwsch/PKHeX#922]
It would be nice to save (or copy) the QR code generated by PGL and be able to inject the team directly into the PKHex box to do further exploration and editing.

**Comment by SciresM** [comment]
Yeah, this is on the to-do list, and has been for a while.

**Comment by Edualvs** [comment]
nice when done, I love u em all

**Comment by architdate** [comment]
The way i generally do it myself is scanning QR ingame, dumping BV and then scanning BV in PKHeX (kind of a hacky workaround for now, just something I thought I would let you all know before SciresM implements this) the direct implementation would be just using the same logic that the game is using to decrypt the PGL QR codes

**Comment by kwsch** [comment]
Closing after 4 months of inactivity; if it's ever implemented, a mention will be made here.
