### ISSUE TITLE
Many Features from the Batch Editor are missing

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#925]
In a recent update, it seems that a lot items that could be specified in the Batch editor before are now missing. For example, in Alpha Sapphire, I used to be able to edit the handling trainer under  HT_Trainer, but that option and many others including those for HT_memory, HT_Intensity, etc are now gone. Can you add all the options to the batch editor or paste all the options below?

**Comment by evandixon** [comment]
The batch editor works (for the most part) using reflection, meaning it can only edit things if they're defined as a property in the PKM object.  That means a property must exist in one of the following classes:
* [PKM](https://github.com/kwsch/PKHeX/blob/master/PKHeX/PKM/PKM.cs)
* [PK6](https://github.com/kwsch/PKHeX/blob/master/PKHeX/PKM/PK6.cs)

I do not see HT_Trainer in either, but the others should work.

**Comment by PKMWM1** [comment]
Okay, thank you.  The problem was that the batch editor was set to "all". Setting it to the correct generation file (.pk6 and .pk7 in my case) seems to be the best solution.

**Comment by kwsch** [comment]
It was recently changed to not show properties unless they were defined in the class itself (not the abstract PKM class). You can still see all possible properties by viewing the "Any" format. 

"Any" = used by any
"All" = used by all
