### ISSUE TITLE
Event flag error

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#926]
A problem with Omega Ruby and Alpha Sapphire event flag s that even if you reset the ability to let you re-battle Latios or Latias on Southern Island, talking to Norman doesn't let you return to Southern Island. I then tried to set my coordinates to Southern Island but all I got was a black screen. Any help would be appreciated.

**Comment by kwsch** [comment]
The rebattle flag simply causes the NPC model to appear for interaction (and battle).

Warp there by editing your map coordinates, else find the correct event flags and toggle via the "custom" flag ID window in the bottom left(?).

**Comment by PKMWM1** [comment]
Can someone let me know which flag that is?

**Comment by kwsch** [comment]
Nobody knows. There's thousands of event flags, and it's been easier to just warp there and rebattle so nobody has bothered.

Discussion on how to warp or asking for flag numbers is outside the realm of GitHub Issues :P
