### ISSUE TITLE
Gen 3 Pokedex Error

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#927]
Hi,

When I click on: Seen All and Caught all on PKHeX and importing my Emerald save it is still showing in the pokedex in-game the same amount of seen and caught as before,with no changes.When I try to edit my SAV file again,after first saving in-game, the pokedex tab in PKHeX is being "reseted" like it didn't save the pokemon I clicked from previous edit.
I am using the latest release of PKHeX 2017.03.08

Thanks

**Comment by PrometheusG** [comment]
**Bonus**: It also corrupts the key items with the following error and then alert:
![2017-03-09](https://cloud.githubusercontent.com/assets/20145301/23762333/5588b7e2-04fe-11e7-8753-2f2506ae3238.png)
![2017-03-09 1](https://cloud.githubusercontent.com/assets/20145301/23762334/56a57cf0-04fe-11e7-998d-1d853f8af938.png)
Oddly enough, it removes some of my key items(In the first image, I have more key items below like Basement Key, Devon Scope, Wailmer Pail, Powder Jar, S.S. Ticket, Coin Case, Magma Emblem, Aurora Ticket, Mystic Ticket :

1)Key items before Checking Seen all, Caught all:
![2017-03-09 2](https://cloud.githubusercontent.com/assets/20145301/23762579/07ad9226-04ff-11e7-9509-072f6778b545.png)

2) Key Items after saving the file to my cartridge,exporting it with and then opening it again with PKHeX:
![2017-03-09 3](https://cloud.githubusercontent.com/assets/20145301/23762626/396d8618-04ff-11e7-9230-2af8a654fe23.png)

I am using the latest stable version of PKHeX
Thanks

**Comment by kwsch** [comment]
I believe it should be resolved now, it was writing to the dex2/dex3 areas for the incorrect game (E <-> FRLG). The item corruption was key in identifying the underlying cause :+1:

**Comment by PrometheusG** [comment]
Yes it is resolved now,I used PKHeX Build 2163 and it works like charm,thank you
