### ISSUE TITLE
Zygarde legality bug

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#933]
Zygarde 10% Forme with Power Construct cannot have Gen 6 origin, only 50% Forme and 50% Forme with Power Construct can. It is impossible to go from 50% to 10% without disassembling Zygarde entirely, giving it Gen 7 origin.

![image](https://cloud.githubusercontent.com/assets/17801814/23812815/173ec114-05aa-11e7-8343-a758b76a8171.png)
![image](https://cloud.githubusercontent.com/assets/17801814/23812830/24434b1e-05aa-11e7-85dc-551d1f33c27c.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/868

**Comment by sora10pls** [comment]
Yeah, only 50% -> 50%-C, no 50% -> 10% or 10%-C :)

**Comment by sora10pls** [comment]
Pull request referenced above resolves this issue.
