### ISSUE TITLE
 Legality about Mr. Mime

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#942]
![legality](https://cloud.githubusercontent.com/assets/24352145/24073732/68e6d10a-0c3f-11e7-8821-a83dce2fc29a.jpg)

Please understand that English is not my native language and I will use a translator.
Mr. Mime can learn healing wish by egg move when it is Mime Jr. before evolution. Or do I know the wrong thing?

**Comment by kwsch** [comment]
Mime Jr. cannot have Guard Swap as an egg move.
Mr. Mime cannot have Healing Wish as an egg move.
