### ISSUE TITLE
alolan raichu legality issue

### ISSUE THREAD

**Issue by jnrepo** [kwsch/PKHeX#944]
http://www.serebii.net/pokedex-sm/026.shtml says alolan raichu can learn fake out as an egg move, however I'm getting `invalid move` when I set it on pkhex.

![screen shot 2017-03-19 at 12 13 40 am](https://cloud.githubusercontent.com/assets/5111058/24078949/16d69d6a-0c39-11e7-90f4-6b38c9d54c27.png)

**Comment by kwsch** [comment]
you're lacking relearn moves.

this place is for reporting bugs, not for getting help for making something legal.
