### ISSUE TITLE
Translation support outside of forms

### ISSUE THREAD

**Issue by evandixon** [kwsch/PKHeX#959]
# Translation support outside of forms
## Overview
Right now, the translation system works by setting the values of controls with particular names in a form with a particular name.  This won't work on many strings shown to the user that aren't in controls, like legality reports and various message boxes.

I propose that the existing translation system be adapted to work on classes.  A language file would contain a section corresponding to the name of a class whose values can be updated with reflection.  Getting an instance of the class could look like `Util.Translate<LegalityStrings>()`, where LegalityStrings contains string properties used by message boxes or `CheckResult`s.  To speed things up, the function used can internally cache instances of these classes after the first call.

I can take care of this at some point soon if this design is approved.  Just assign me to the issue, and I'll take care of it.  (Or if you'd prefer to do it yourself, that's fine too.)

## Example
Given the following section in lang_en.txt:
```
! -----------------------------------------------------
- DO NOT CHANGE THIS SECTION.
! MyStringsClass
- Change stuff below this line, not above.
------------------------------------------------------
GenericError1 = A generic error has occurred
GenericError2 = Something went wrong
AString = This is a string
```
and the following class is defined:
```
public class MyStringsClass {
public string GenericError1 {get;set;}
public string GenericError2 {get;set;}
public string AString {get;set;}
}
```
Calling a static function named similar to the following would return an instance of `MyStringsClass` whose properties are set to the values defined in `lang_en.txt` (or some other resource file depending on the current culture):
```
var theStrings = Util.GetTranslatedStrings<MyStringsClass>();
Console.Writeline(theStrings.AString); // prints "This is a string"
```
## Acceptance Criteria

- [ ] Static util function exists to create an instance of the given type param, filling in the string properties with corresponding entries in the language file, as described above
- [ ] Class instances are internally cached to minimize the overhead of future calls

**Comment by kwsch** [comment]
Hopefully the heavy lifting (3027ead) is done; will have to run tests on this implementation later 💤
