### ISSUE TITLE
Legality Problem for Manaphy from Pokemon Ranger

### ISSUE THREAD

**Issue by koukakou** [kwsch/PKHeX#967]
![image](https://cloud.githubusercontent.com/assets/23416118/24183723/bd6f9e3a-0e8f-11e7-82bb-d8515bd25e13.png)

Manaphy can be transferred as egg from pokemon ranger to pokemon platium. This situation should be legal.

**Comment by kwsch** [comment]
Gen 3-5 legality checking is still a work in progress; many things have to be tweaked still :)

**Comment by koukakou** [comment]
Thanks for keep working!
