### ISSUE TITLE
Feature request: suggested Country/Sub Region/3DS Region for Vivillon

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#974]
Follow-up for #274.

Similar to the suggested Met Level/Location, Suggested Moves, and Suggested Relearn Moves, if the user clicks any of the following 3 labels (picture below for reference), PKHeX should provide a suggested Country, Sub Region, and 3DS Region that matches the Form (excluding Fancy and Poke Ball due to them being Event only).

In the example of this picture, if any of the 3 labels were clicked, PKHeX would suggest to make the Form "Elegant".

![image](https://cloud.githubusercontent.com/assets/17801814/24266413/12e0d872-0fdd-11e7-9916-f08aefca9c90.png)

**Comment by sora10pls** [comment]
Or as an alternative, when given a prompt due to illegality, have the error message display which Form the Vivillon should be, rather than just saying "Invalid Vivillon pattern." :)

**Comment by kwsch** [comment]
Closed, changed to Fishy https://github.com/kwsch/PKHeX/commit/6b25367be71856e4c19e1a41b420d51da0f8251a so it shouldn't appear as an Invalid message.
Hooking up the strings for a suggestion would be a little too much for little gain :)
