### ISSUE TITLE
Box Layout editor, amount of unlocked boxes causes a crash in-game (Gen. VI)

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#975]
Although I've only seen this from editing my Y save, I'm pretty sure this would for all Gen. VI games.

When editing the amount of boxes that are currently unlocked, the drop down menu allows you to pick 31, which you'd think makes sense since the game has 31 boxes available.

However, the 31st box in-game is implicitly unlocked by having the cover legendary Pokémon captured, and is not affected by that variable. This means that if you set the amount of unlocked boxes to 31 in PKHeX, the game thinks that there are 32 boxes unlocked and causes the game (and the whole 3DS) to hang trying to load a non-existent 32nd box when attempting to scroll past Box 31 (or past Battle Box.)

Easily verifiable by loading any save which has 31 boxes unlocked in-game, and seeing that PKHeX says that 30 boxes are unlocked, with the option to "unlock" a 31st (32nd) box.

**Comment by sora10pls** [comment]
Could vary well be a leftover from Gen 7, as it has 32 Boxes whereas Gen 6 has 31 Boxes and a Battle Box.
