### ISSUE TITLE
Bug(?): Auto filling in Trainer Info from save data sets incorrect Sub Region if only done once

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#976]
This is quite a particular bug, as it only happens once and then corrects itself. What I did in the proper order was:

Open PKHeX -> Open Gen 7 save file -> Blank Marshadow is loaded -> Click `OT` label in `OT/Misc` tab to auto fill in Trainer Info -> Go to `Main` tab

When viewing the Country, Sub Region, and 3DS Region, the Country and 3DS Region are accurate, however the Sub Region is not.

If I go back to the `OT/Misc` tab and re-click the `OT` label to re-fill the values, the Sub Region is set correctly. Why it does not do this on the first go is what I don't understand.

To give an example, my save file is from a Japanese New 3DS with the following info set in the System Settings:
- Country: Japan
- Sub Region: Tokyo
- 3DS Region: Japan

When auto filling with PKHeX for the first time, it sets the values to:
- Country: Japan (correct)
- Sub Region: Gifu (incorrect)
- 3DS Region: Japan (correct)

I've also tested with where I actually live, and the same issue occurs. I changed the info in the Trainer Info Editor to make the save file from Ontario, Canada, with a 3DS Region set to NA/SA. When auto filling with PKHeX, it sets the values to:
- Country: Canada
- Sub Region: — (incorrect)
- 3DS Region: Americas (correct)

If you need my save file to test, please let me know and I'll email it to you.

**Comment by kwsch** [comment]
changing country => load new subregion list for that country => clears existing one :P
