### ISSUE TITLE
Crystal encounters location id does not match met location from pokemon data

### ISSUE THREAD

**Issue by javierhimura** [kwsch/PKHeX#978]
The met location of crystal pokemon have a value from the following table

http://bulbapedia.bulbagarden.net/wiki/List_of_locations_by_index_number_(Generation_II)

There is no possible value above 0x80, values greater are literally impossible because there is only 7 bits to store the location data in the pokemon

But the location ids loaded in the crystal encounters have values greather than that, does not match pokemon data. Crystal encounters should have a location id matching the one stored in the pokemon to check the pokemon data match the encounter data.

With others gen 1 and 2 games its also have values above 0x80 but in those case does not matter becuse only crystal stores the caught location in the pokemon

**Comment by kwsch** [comment]
It's currently stored as the raw value from the ROM; I didn't hook anything up because I didn't feel like coming up with the code to map the location->met location.

**Comment by kwsch** [comment]
Implemented via https://github.com/kwsch/PKHeX/pull/1217

**Comment by lmmfranco** [comment]
Most encounter data for crystal still show empty met  location. Eg; Sentret, Ledyba
