### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by giveup** [kwsch/PKHeX#98]
xbuild ./PKHeX.sln 
XBuild Engine Version 12.0
Mono, Version 4.2.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 2016/4/16 0:19:27.

---

Project "/Documents/PKHeX/PKHeX.sln" (default target(s)):
    Target ValidateSolutionConfiguration:
        Building solution configuration "Debug|x86".
    Target Build:
        Project "/Documents/PKHeX/PKHeX.csproj" (default target(s)):
            Target PrepareForBuild:
                Configuration: Debug Platform: x86
            Target GenerateResources:
                Tool /usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "PKX/f1-Main.resx,obj/x86/Debug/PKHeX.Main.resources" 
/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
Position: Line 470, Column 5.
Inner exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

```
            Tool /usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Properties/Resources.resx,obj/x86/Debug/PKHeX.Properties.Resources.resources" 
            Unhandled Exception:
            System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
              at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
              at System.Drawing.GDIPlus..cctor () <0x1097e1de0 + 0x001d5> in <filename unknown>:0 
              --- End of inner exception stack trace ---
              at System.Drawing.Image.Dispose (Boolean disposing) <0x1097e4400 + 0x00017> in <filename unknown>:0 
              at System.Drawing.Image.Finalize () <0x1097e43c0 + 0x0001d> in <filename unknown>:0 
```

/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 255. Output: Error: Exception has been thrown by the target of an invocation.
Inner exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
  at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () <0x1097e1de0 + 0x001d5> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Drawing.Image.Dispose (Boolean disposing) <0x1097e4400 + 0x00017> in <filename unknown>:0 
  at System.Drawing.Image.Finalize () <0x1097e43c0 + 0x0001d> in <filename unknown>:0 

```
            Tool /usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Misc/SplashScreen.resx,obj/x86/Debug/PKHeX.SplashScreen.resources" 
```

/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
Position: Line 203, Column 5.
Inner exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

```
        Task "GenerateResource" execution -- FAILED
        Done building target "GenerateResources" in project "/Documents/PKHeX/PKHeX.csproj".-- FAILED
    Done building project "/Documents/PKHeX/PKHeX.csproj".-- FAILED
Task "MSBuild" execution -- FAILED
Done building target "Build" in project "/Documents/PKHeX/PKHeX.sln".-- FAILED
```

Done building project "/Documents/PKHeX/PKHeX.sln".-- FAILED

Build FAILED.
Errors:

/Documents/PKHeX/PKHeX.sln (default targets) ->
(Build target) ->
/Documents/PKHeX/PKHeX.csproj (default targets) ->
/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets (GenerateResources target) ->

```
/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
```

Position: Line 470, Column 5.
Inner exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

```
/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 255. Output: Error: Exception has been thrown by the target of an invocation.
```

Inner exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
  at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () <0x1097e1de0 + 0x001d5> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Drawing.Image.Dispose (Boolean disposing) <0x1097e4400 + 0x00017> in <filename unknown>:0 
  at System.Drawing.Image.Finalize () <0x1097e43c0 + 0x0001d> in <filename unknown>:0 

```
/usr/local/Cellar/mono/4.2.2.30/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
```

Position: Line 203, Column 5.
Inner exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

```
 0 Warning(s)
 3 Error(s)
```

**Comment by kwsch** [comment]
Looks like the inner exception is related to GDIPlus not being found.

>System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception.
> System.DllNotFoundException: libgdiplus.dylib

Possibly related to your compiler's configuration, I searched the above error and got [this page](http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/).

**Comment by giveup** [comment]
First, I try to fresh install mono with brew install mono.
Then put the libgdiplus.dylib into /usr/local/Cellar/mono/4.2.3.4/lib/ and edit /usr/local/Cellar/mono/4.2.3.4/etc/mono/config.
        dllmap dll="gdiplus" target="/usr/local/Cellar/mono/4.2.3.4/lib/libgdiplus.dylib" os="!windows"

 Doen't work..

**Comment by chenzw95** [comment]
Can you try doing the following instead?

- Copy libgdiplus.dylib to `/Library/Frameworks/Mono.framework/Versions/4.2.3/lib/`
- In the mono configuration file, change the dllmap line to read  `<dllmap dll="gdiplus" target="libgdiplus.dylib" os="!windows">` instead. If I remember correctly, the target parameter for dllmap does not accept paths.

By the way, while it may compile, PKHeX probably will not launch/run properly on OS X. You most likely will need wine as a further compatibility layer.

**Comment by giveup** [comment]
Well, After uninstall mono with brew. I try to install mono with offical pkg.
It work fine. No error in compile.
Thank you for your attention.

**Comment by giveup** [comment]
After upgrade mono to 4.6.2,(Offical PKG/brew install mono/brew cask install mono-mdk)
I have issue again.
config
`<configuration>
	<dllmap dll="i:cygwin1.dll" target="libc.dylib" os="!windows" />
	<dllmap dll="libc" target="libc.dylib" os="!windows"/>
	<dllmap dll="intl" target="libintl.dylib" os="!windows"/>
	<dllmap dll="intl" name="bind_textdomain_codeset" target="libc.dylib" os="solaris"/>
	<dllmap dll="libintl" name="bind_textdomain_codeset" target="libc.dylib" os="solaris"/>
	<dllmap dll="libintl" target="libintl.dylib" os="!windows"/>
	<dllmap dll="i:libxslt.dll" target="libxslt.dylib" os="!windows"/>
	<dllmap dll="i:odbc32.dll" target="libodbc.dylib" os="!windows"/>
	<dllmap dll="i:odbc32.dll" target="libiodbc.dylib" os="osx"/>
	<dllmap dll="oci" target="libclntsh.dylib" os="!windows"/>
	<dllmap dll="db2cli" target="libdb2_36.dylib" os="!windows"/>
	<dllmap dll="MonoPosixHelper" target="$mono_libdir/libMonoPosixHelper.dylib" os="!windows" />
	<dllmap dll="i:msvcrt" target="libc.dylib" os="!windows"/>
	<dllmap dll="i:msvcrt.dll" target="libc.dylib" os="!windows"/>
	<dllmap dll="sqlite" target="libsqlite.0.dylib" os="!windows"/>
	<dllmap dll="sqlite3" target="libsqlite3.0.dylib" os="!windows"/>
	<dllmap dll="libX11" target="libX11.dylib" os="!windows" />
	<dllmap dll="libgdk-x11-2.0" target="libgdk-x11-2.0.dylib" os="!windows"/>
	<dllmap dll="libgtk-x11-2.0" target="libgtk-x11-2.0.dylib" os="!windows"/>
	<dllmap dll="libXinerama" target="libXinerama.so.1" os="!windows" />
	<dllmap dll="libcairo-2.dll" target="libcairo.so.2" os="!windows"/>
	<dllmap dll="libcairo-2.dll" target="libcairo.2.dylib" os="osx"/>
	<dllmap dll="libcups" target="libcups.so.2" os="!windows"/>
	<dllmap dll="libcups" target="libcups.dylib" os="osx"/>
	<dllmap dll="i:kernel32.dll">
		<dllentry dll="__Internal" name="CopyMemory" target="mono_win32_compat_CopyMemory"/>
		<dllentry dll="__Internal" name="FillMemory" target="mono_win32_compat_FillMemory"/>
		<dllentry dll="__Internal" name="MoveMemory" target="mono_win32_compat_MoveMemory"/>
		<dllentry dll="__Internal" name="ZeroMemory" target="mono_win32_compat_ZeroMemory"/>
	</dllmap>
	<dllmap dll="gdiplus" target="/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.dylib" os="!windows"/>
	<dllmap dll="gdiplus.dll" target="/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.dylib"  os="!windows"/>
	<dllmap dll="gdi32" target="/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.dylib" os="!windows"/>
	<dllmap dll="gdi32.dll" target="/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.dylib" os="!windows"/>
</configuration>
`

**Comment by kwsch** [comment]
Appears to be an issue related to your mono installation, not PKHeX. I was able to find issues on other projects hosted on GitHub with the same error:

https://github.com/OpenRA/OpenRA/issues/9816
https://github.com/KSP-CKAN/CKAN/issues/1272
