### ISSUE TITLE
Bug regarding Gen 4 Egg legality

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#981]
I know that Gen 3-5 legality checks are still not fully complete, but I figured I would add this one in anyway.

Gen 4 Eggs should have a Met Level of 0, which is totally fine. If set to Lv. 1, you get the following:
![image](https://cloud.githubusercontent.com/assets/17801814/24305347/0595444e-1093-11e7-93a4-75379a79963b.png)

However, if it is set to Lv. 0 (as intended), you get the following output for legality:
![image](https://cloud.githubusercontent.com/assets/17801814/24305374/1d0e30b8-1093-11e7-8110-21c4031c960d.png)

Most notable being "Fishy: All EVs are zero, but leveled above Met Level."

While this may be true for Gen 5 onward, that is not the case for Gen 4 and should be ignored due to Met Level having to be 0, and it being impossible to have a Pokemon at Lv. 0. ;)

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/d8dcb4725225dc183faff54fa6fdb0d37e4a86bf/PKHeX/Legality/Checks.cs#L331

```
else if (sum == 0 && pkm.Stat_Level - pkm.Met_Level > 0)
    AddLine(Severity.Fishy, V23, CheckIdentifier.EVs);
```

to
```
else if (sum == 0 && pkm.CurrentLevel - Math.Max(1, pkm.Met_Level) > 0)
    AddLine(Severity.Fishy, V23, CheckIdentifier.EVs);
```

**Comment by sora10pls** [comment]
Cool, I'll submit a pull request soon. And while I'm here, suggested Met Level is still set to 1 for Gen 4, when it should be 0. If you let me know what to add/replace I could submit that as well :)

**Comment by sora10pls** [comment]
Pull request submitted: #982

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Analysis.cs#L326-L332

getSuggestedMetLocation doesn't handle gen3 origins, plus the level suggestion is currently const at 1. Would have to expand the returned encounter to calculate the level.

```
int lvl;
if (!pkm.IsNative) 
	lvl = pkm.CurrentLevel;
else if (Format < 5)
	lvl = 0;
else
	lvl = 1;
```

the getSuggestedEggMetLocation needs to have RSE/FRLG location indexes added to the switch table, with the 5 reaching the same chunk of code:
```
switch (pkm.Format)
{
    case 3: //rsefrlg
        return pkm.FRLG ? [frlg ID] : [rse ID];
    case 4: // pal park
        return [pal park 0x37?];
    default: // transporter
        return [transporter 300xx?];
}
```

don't worry about this one, I'll handle it later today ;)

**Comment by sora10pls** [comment]
sounds good, gives me time to play the Splatoon 2 Global Testfire :P
