### ISSUE TITLE
Legality string translation: CheckResult.ToString()

### ISSUE THREAD

**Issue by evandixon** [kwsch/PKHeX#984]
When translating legality analysis into Chinese, the English word for "Invalid" still appears.  This appears to be a result of implicitly calling CheckResult.ToString().  I traced one such occurrence to Analysis.getLegalityReport on line 260, in the string.Format(V196, **chk.Judgement,** ...) call, although it appears the same kind of thing occurs elsewhere.

I recommend not looking into this until reviewing #983, because if that PR is accepted, it may conflict with the design of a fix for this.

**Comment by kwsch** [comment]
probably best to add a helper method to switch between the values and return one of the translatable-string variables
