### ISSUE TITLE
Not an expected relearn move

### ISSUE THREAD

**Issue by razelsteer** [kwsch/PKHeX#986]
I have been using it to make Pokemon but I have an issue.
the issue is I want to make the Pokemon learn a move that needs to be in the relearn moves so I got to recommended and I give it the recommended but then it says "not an expected relearn move," what do I do?
![sdfdfdf](https://cloud.githubusercontent.com/assets/26666084/24319421/b294b3f6-10f1-11e7-9870-b2cffb4f8ca3.JPG)
 here is wevile as an example

**Comment by kwsch** [comment]
hack getting flagged as a hack, working as intended

tutor moves are not relearn moves.
