### ISSUE TITLE
Wrong met location in wc6->pk6 conversion

### ISSUE THREAD

**Issue by suloku** [kwsch/PKHeX#99]
I drag and dropped volcanion's WC to pkhex, then at met location it will say "Pokémon Movie 13" while the correct location should be "Pokémon Movie 16".

Here's the WC6 (the post may be moved when next wc compilation is done): https://projectpokemon.org/forums/showthread.php?48113-Gen-VI-Event-Contribution-Thread-2016&p=214002&viewfull=1#post214002

**Comment by kwsch** [comment]
Dropping it shows up as Pokémon Movie 16 for me.

**Comment by suloku** [comment]
Ok, tried again and it shows Pokémon Movie 16 only if a save has been loaded. I previously tried to drag it without a save, just to see some data of the pokemon, but I don't see why it would not show correct location if there's no save loaded though.

**Comment by kwsch** [comment]
Because the blank version defaults it to BW met locations :)
