### ISSUE TITLE
White & Orange Flabébé HA and Pumkaboo Small & Large size HA shouldn't be legal (atm)

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#999]
http://puu.sh/uZF8t.png

tittle explains all, I guess xD

there is neither Horde Encounter for Flabébé nor Safari available for those specific colors.

-sorry my bad english. I'm not native xD

edit: lol I'm the #999 🐱

**Comment by kwsch** [comment]
post the pkm

**Comment by jisn064** [comment]
Flabébé is female only

**Comment by jisn064** [comment]
I made a mistake. It is Orange and White, not blue.

**Comment by jisn064** [comment]
I have a new one:
http://puu.sh/v1iSb.png

Pumkaboo Large & Small shouldn't have their HA ( Average & Super Size is ok )

Male when breeding with female of the same species; the egg won't inherit the father's ability
Egg will inherit the mother's size./ Egg will inherit father's size if breeding with a Ditto.
Super Size obtained from event with a chance to get HA
Safari with the Average Size as the only possible encounter
